### ISSUE TITLE
[Issue]: Extension uninstallation not working

### ISSUE THREAD

**Issue by mark-wd** [vladmandic/automatic#1002]
### Issue Description

In the new interface, clicking Uninstall isn't really producing results for me in Firefox latest.

The console prints the request:

`INFO     Extension uninstall: G:stable-diffusion-vladmandicextensionsPBRemTools`

But nothing really happens afterwards. Can others reproduce?

Note: Manual deletion of the extension's folder works just fine and Automatic proceeds as normal on next boot.

### Version Platform Description

2023-05-13
hash: 926b8666

**Comment by vladmandic** [comment]
It's been fixed yesterday, your version is just a bit behind.
