### ISSUE TITLE
[Issue]: Changing emphasis with Ctrl+up/down doesn't clear parentheses at 1.0

### ISSUE THREAD

**Issue by EfourC** [vladmandic/automatic#1004]
### Issue Description
The prompt emphasis syntax should be cleared when Ctrl+up/down hits value 1.0, but it doesn't.

For example, instead of going from `(iceberg:1.1)` to `iceberg`, it currently goes to `(iceberg:1.0)`.

Looks like some code cleanup that changed `==` to `===` introduced a subtle bug preventing it:

https://github.com/vladmandic/automatic/blob/bce16a1db57978ce178bb78c68c3a97054876618/javascript/edit-attention.js#L101-L107

When I tested changing the if check back to use  `==`, the functionality worked.

### Version Platform Description

Version: bce16a1d Tue May 16 12:24:04 2023 -0400
Windows 10
RTX 2070S
Browsers:  ungoogled-chromium, firefox

**Comment by vladmandic** [comment]
fixed. thanks for chasing it down.
