### ISSUE TITLE
[Feature]: Human Ranking Feedback

### ISSUE THREAD

**Issue by ryukra** [vladmandic/automatic#1006]
### Feature description

There was a repo 2 month a go that implemented ranking feedback.. todo says they wanted to add it as extension, but I guess its abandoned:
https://github.com/TZW1998/Taming-Stable-Diffusion-with-Human-Ranking-Feedback

Could be pretty interesting, I'm not able to implement it myself sadly.

**Comment by vladmandic** [comment]
this would be a great extension, but i don't think it should be part of the core - unless i'm missing something?

**Comment by ryukra** [comment]
I think if it works well and improves quality, depending on how it works its like an imagebrowser or has to be integrated slightly deeper.. I don't know.. but I wanted to shed some light on it because it seems to be completely overlooked/forgotten.

**Comment by Metal079** [comment]
Wasnt really impressed with the results of the paper, the "improved" versions didnt really seem better to me, im guessing it was abandoned for a reason.
