### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'setup.log'

### ISSUE THREAD

**Issue by Renaldas111** [vladmandic/automatic#101]
### Issue Description

venv "E:\automatic\venv\Scripts\Python.exe"
22:19:58-490185 INFO     Python 3.10.6 on Windows
22:19:58-490185 INFO     Running setup
22:19:58-537052 INFO     Installing requirements
22:19:58-724528 INFO     Version: f46fa099 Wed Apr 12 14:55:46 2023 -0400
22:19:59-052647 WARNING  Latest available version: 2023-04-12T18:55:46Z
22:19:59-052647 INFO     Updating Wiki
22:20:00-302652 INFO     Installing packages
22:20:00-333899 ERROR    Cannot install xformers package: {e}
22:20:00-333899 INFO     Installing repositories
22:20:00-490181 INFO     Installing submodules
22:20:01-177673 INFO     Updating submodules
22:20:10-882716 INFO     Built-in extensions: ['clip-interrogator-ext', 'LDSR', 'Lora', 'prompt-bracket-checker',
                         'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer',
                         'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
22:20:11-554556 ERROR    Error running extension installer:
                         Traceback (most recent call last):
                           File "E:\automatic\extensions-builtin\clip-interrogator-ext\install.py", line 1, in <module>
                             import launch
                           File "E:\automatic\launch.py", line 5, in <module>
                             import setup
                           File "E:\automatic\setup.py", line 22, in <module>
                             os.remove('setup.log')
                         PermissionError: [WinError 32] The process cannot access the file because it is being used by
                         another process: 'setup.log'

### Platform Description

Windows 11 22H2

This error repeats ~10 times on various directories from "E:\automatic\extensions-builtin\

**Comment by mart-hill** [comment]
For now, I commented out these two lines in setup.py, (and had to remove controlnet extension for now) to see if the UI runs. 🙂 

```
#if os.path.isfile('setup.log'):
#    os.remove('setup.log')
```

**Comment by vladmandic** [comment]
duplicate #100
