### ISSUE TITLE
[Issue]: --Upgrade error

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#1016]
### Issue Description

I try to upgrad by using webui.bat --upgrade and get an error: 

[error webui upgrade.txt](https://github.com/vladmandic/automatic/files/11494686/error.webui.upgrade.txt)

### Version Platform Description

Device name	DESKTOP-89OI1TC
Processor	AMD Ryzen 7 6800H with Radeon Graphics            3.20 GHz
Installed RAM	32.0 GB (31.2 GB usable)
Device ID	57F773B6-2052-4400-9EEE-5DA99ADC9758
Product ID	00331-20350-00000-AA537
System type	64-bit operating system, x64-based processor
GPU NVIDIA RTX 3090

**Comment by bdulfer** [comment]
Did you try to rerun the upgrade?

For me this always fixes errors like this.

If not, the setup.log may provide more details. It is in the same directory as webui.bat.

**Comment by vladmandic** [comment]
fixed. it was a specific chicken-and-the-egg scenario where command line args were accessed before they were parsed

**Comment by ShmuelRonen** [comment]
Thanks!!! now it's works well.
