### ISSUE TITLE
[Issue] [DirectML] Modify text generation setting after first generation caused BSOD on Intel Xe Graphic GPU

### ISSUE THREAD

**Issue by Nathan-dm** [vladmandic/automatic#1017]
### Issue Description

at first generation no problem even i set batch count to more than 1, it happened when i tried to modify first text generation  setting (like adding lora,embeddings,lycoris,changing model,setting cfg scale,seeds,etc) and click generate, couple minutes later my pc crashed (BSOD),
it says VIDEO_TDR_FAILURE because igdkmdnd64.sys 
(i tried to disable TDR by modifying Tdrlevel to 0,it didn't work, reference : https://learn.microsoft.com/en-us/windows-hardware/drivers/display/tdr-registry-keys)

extension list:
--ControlNet (i didn't use it because haven't download models)

i tested with this repo and got same result https://github.com/lshqqytiger/stable-diffusion-webui-directml

I can't capture logs from console because my pc crashed but i can provide you log before i generate anything

How To Reproduce error
1. start webui-user.bat
2. configure text generation (adding prompt,etc) 
3. click generate
4. wait til finish generating
5. try to modify text generation 
6.  click generate
7.  crash
```
up to date.
Using VENV: C:\Stable Diffusion 1\automatic\venv
15:29:23-582889 INFO     Starting SD.Next
15:29:23-586879 INFO     Python 3.10.10 on Windows
15:29:23-643880 INFO     Version: 5250ba4b Tue May 16 21:20:36 2023 -0400
15:29:25-672698 INFO     Setting environment tuning
15:29:25-673696 INFO     Using DirectML Backend
15:29:27-292780 INFO     Torch 2.0.0+cpu
15:29:27-306771 INFO     Torch backend: DirectML (torch-directml 0.2.0.dev230426)
15:29:27-393770 INFO     Torch detected GPU: Intel(R) Iris(R) Xe MAX Graphics
15:29:27-424771 INFO     Torch detected GPU: Intel(R) Iris(R) Xe Graphics
15:29:27-426772 INFO     Verifying requirements
15:29:27-440779 WARNING  Package wrong version: transformers 4.28.1 required 4.26.1
15:29:27-442780 INFO     Installing package: transformers==4.26.1
15:29:29-753717 INFO     Installing packages
15:29:29-794718 INFO     No changes detected: Quick launch active
15:29:29-801710 INFO     Running extension preloading
15:29:29-802710 INFO     Server arguments: ['--lowvram', '--autolaunch', '--use-directml']
No module 'xformers'. Proceeding without it.
15:29:35-425393 INFO     Libraries loaded
15:29:35-429394 INFO     Skipping conflicting extension: C:\Stable Diffusion 1\automatic\extensions\sd-webui-controlnet
15:29:35-488487 INFO     Available models: C:\Stable Diffusion 1\automatic\models\Stable-diffusion 25
ControlNet v1.1.173
ControlNet v1.1.173
15:29:41-859410 INFO     Loading UI theme: SebastianBravo/simci_css
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
15:29:44-022501 INFO     Local URL: http://127.0.0.1:7860/
15:29:44-023511 INFO     API Docs: http://127.0.0.1:7860/docs
15:29:44-024500 INFO     Initializing middleware
15:29:44-347500 INFO     CUDA FP16 test passed but desired mode is set to FP32
15:29:44-348500 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
Loading weights: C:\Stable Diffusion 1\automatic\models\Stable-diffusion\neverendingDreamNED_v122BakedVae.safetensors
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
15:29:45-455511 INFO     Model created from config: C:\Stable Diffusion 1\automatic\configs\v1-inference.yaml
15:29:51-687510 INFO     Applying sub-quadratic cross attention optimization
15:29:51-706509 INFO     Embeddings loaded: 9 ['badhandv4', 'EasyNegative', 'negative_hand-neg',
                         'ng_deepnegative_v1_75t', 'pureerosface_v1', 'realisticvision-negative-embedding',
                         'style-empire', 'ti-emb_kobo-kanaeru', 'verybadimagenegative_v1.3']
15:29:51-715509 INFO     Model loaded in 7.4s (load=0.6s create=0.5s apply=6.2s)
15:29:51-934522 INFO     Model load finished: {'ram': {'used': 7.99, 'total': 15.8}}
15:29:52-288591 INFO     Startup time: 22.5s (torch=3.4s gradio=1.9s libraries=0.2s models=0.1s codeformer=0.1s
                         scripts=2.9s opts onchange=3.4s ui=1.9s start=0.2s scripts app_started_callback=0.1s
                         checkpoint=8.2s)
15:29:52-291510 INFO     Memory used: 4.78 total: 15.8 
``` 

### Version Platform Description

Version: 5250ba4b Tue May 16 21:20:36 2023 -0400
OS Version: Windows 10 22H2
Browser: Firefox 113.0.1 (64-bit)
GPU Driver: 31.0.101.4314
System Spec:
Laptop: Acer Swift 3X
Operating system:Windows 10 64 bit (22H2)
Processor: Intel Core I5 1135G7
Graphics card: Intel Xe Graphic (80eu), Intel Xe MAX
Ram: 16GB LPDDR4X 4267mhz
SSD:512Gb M.2 NVME

**Comment by vladmandic** [comment]
note that both app and torch-directml run in user-mode and they cannot cause system crash unless they interact with some bad system component - in this case, likely a device driver for gpu. there is pretty much nothing i can do about it from the app side.

you should check your system logs (in this case, windows event logs) for more details.

but in general, i'm not sure i'd suggest to use directml with onboard intel xe apu. might work, but i don't know anyone using it.

i'm sorry i cannot help more, but this is far outside of the app control. if you find something, please update here so community can learn more.
