### ISSUE TITLE
[Extension]: Multidiffusion Upscaler component Tiled VAE, unexpected behavior

### ISSUE THREAD

**Issue by gahara42** [vladmandic/automatic#1022]
### Issue Description

Hello! Recently i noticed that after using Tiled VAE feature, the VAE is not loaded off from GPU memory

To reproduce the problem, do the following:

- Load a checkpoint that does not have a baked VAE
- Enable Tiled VAE (default settings, fast encoder off)
- Generate image
- Image is lacking colors as expected
- Select a VAE
- Generate image again
- Result now has colors as expected as well
- Switch back to none VAE selected
- Generate image again
- Image still has VAE applied, because colors are applied

Illustrated:
![image](https://github.com/vladmandic/automatic/assets/73537708/b08b268a-589b-42d0-8bc6-361b297312f2)

> After that even if you __disable__ Tiled VAE, the VAE still will be applied.

My concern is that if we follow this behavior, when we switch to checkpoint that has baked VAE, the VAE that still in memory will be applied to it, which will cause incorrect results after generating.
This behavior is appeared recently, because previously i didn't have this issue.
I created an issue in extension repo as well, but i duplicate it here, because i'm not sure if its extension bug or recent additions to this fork caused this.

### Version Platform Description

Info from console log:
```
Version: 5250ba4b Tue May 16 21:20:36 2023 -0400
Server arguments: ['--medvram', '--autolaunch']
```
OS: `Win10 19045.2965`
Browser: `Firefox 113.0.1`
Extension version from Extensions tab: `23f3a144 Tue May09 2023 16:29`

### URL link of the extension

link to repo: https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/
link to issue on repo: https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/202

**Comment by vladmandic** [comment]
thanks for nicely written report AND creating issue upstream so it can be tracked!

**Comment by vladmandic** [comment]
closing this issue here as it can be tracked upstream and will be applied automatically to this repo once fix is available.
