### ISSUE TITLE
[Issue]: Extension update and uninstall is not working

### ISSUE THREAD

**Issue by Davikar** [vladmandic/automatic#1026]
### Issue Description

I hit the update button and restart the UI, but the extension is still not updated.
I hit the uninstall button and restart, but the extension is still there.

Idk if it's any clue, but the path in the log doesn't include any \'s so might be a character escaping issue?
C:AIautomaticextensionssd-webui-photopea-embed

### Version Platform Description

Windows 11, Python 3.10.10, Chrome
Version: 554f2629 Wed May 17 08:46:57 2023 -0400

**Comment by vladmandic** [comment]
what are your current command line flags?
can you run `webui.bat --debug` to capture information? it should print update/install messages

**Comment by Davikar** [comment]
Well... hitting the update button doesn't show anything in the terminal other than
21:53:59-261990 DEBUG    Extensions manager: refresh list search= sort=default
21:54:00-161407 DEBUG    Server alive: True Memory used: 5.47 total: 31.94

Not sure if there actually IS an update though. If I check the repo of the extension it hasn't been updated the last 4 days.

When I hit extension uninstall it says:
22:01:20-659669 INFO     Extension uninstall: C:AIautomaticextensionsmodel-keyword
22:01:20-660662 DEBUG    Extensions manager: refresh list search= sort=default

So not so much more info here, unfortunately.

**Comment by vladmandic** [comment]
i'll check tomorrow, going offline now.

**Comment by vladmandic** [comment]
just posted new version, this should be fixed.
