### ISSUE TITLE
[Issue]: Can't Train Hypernets

### ISSUE THREAD

**Issue by elchupacabrinski** [vladmandic/automatic#1028]
### Issue Description

Here is the Console Output. Same happens on MacOS and Linux (With Auto1111 it works though)

18:18:49-790954 ERROR    gradio call: KeyError                                                                          
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ /Users/xxti/automatic/modules/call_queue.py:33 in f                                                                │
│                                                                                                                      │
│    32 │   │   │   try:                                                                                               │
│ ❱  33 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    34 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                      │
│ /Users/xxti/automatic/modules/hypernetworks/ui.py:27 in train_hypernetwork                                         │
│                                                                                                                      │
│   26 │   │                                                                                                           │
│ ❱ 27 │   │   hypernetwork, filename = modules.hypernetworks.hypernetwork.train_hypernetwork(*                        │
│   28                                                                                                                 │
│                                                                                                                      │
│ /Users/xxti/automatic/modules/hypernetworks/hypernetwork.py:560 in train_hypernetwork                              │
│                                                                                                                      │
│   559 │   │   )                                                                                                      │
│ ❱ 560 │   │   logging.save_settings_to_file(log_directory, {**saved_params, **locals()})                             │
│   561                                                                                                                │
│                                                                                                                      │
│ /Users/xxti/automatic/modules/textual_inversion/logging.py:19 in save_settings_to_file                             │
│                                                                                                                      │
│   18 │   params.update({k: v for k, v in all_params.items() if k in keys})                                           │
│ ❱ 19 │   filename = f"{params['embedding_name']}-{now.strftime('%Y-%m-%d_%H-%M-%S')}.json"                           │
│   20 │   with open(os.path.join(log_directory, filename), "w", encoding='utf-8') as file:                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
KeyError: 'embedding_name'

### Version Platform Description

I tried on MacOS & Ubuntu. Both newest commit!

**Comment by vladmandic** [comment]
fixed in dev, will publish to github later today.

**Comment by vladmandic** [comment]
published. hopefully this is the only error.
