### ISSUE TITLE
[Issue]: I want this to work so badly but...

### ISSUE THREAD

**Issue by myndxero** [vladmandic/automatic#103]
### Issue Description

I just cannot get this to work. I played with it a bunch before today's update for which I started completely fresh, and it's just one thing after another.

My webUI-user.bat that I customized for auto's def doesn't work, tried a base webui.bat, tried manually activating venv and launching. :| errors everywhere. I probably did something stupid, probably my fault, grrr.

![image](https://user-images.githubusercontent.com/113237671/231675753-758dfb06-0bc3-4664-9837-9f355bfd328b.png)
![image](https://user-images.githubusercontent.com/113237671/231676773-3cde4964-2af6-4f93-84c0-49448f3f1109.png)

### Platform Description

Windows 10, 3090 TI, 64gb RAM, 2tb SSD

Just snapped this from Auto.
![image](https://user-images.githubusercontent.com/113237671/231676476-e9cf21f1-7d95-4cfd-a3fd-9ba747320a0f.png)

**Comment by vladmandic** [comment]
duplicate #101
