### ISSUE TITLE
[Issue]: UI Scripts Order Not Consistent Between Tabs

### ISSUE THREAD

**Issue by nullsweat** [vladmandic/automatic#1032]
### Issue Description

Version: b979d448 Wed May 17 14:41:13 2023 -0400

I have set my UI Scripts Order as the following: **Aspect Ratio Helper, ControlNet, Tiled Diffusion, Tiled VAE, After Detailer, Steps Animation**
![UI Scripts Order](https://github.com/vladmandic/automatic/assets/124303296/c22022a7-a5fb-498b-af57-fadf6586a80d)

It does indeed display properly in the From Text tab, as seen below:
![From Text Tab UI Order](https://github.com/vladmandic/automatic/assets/124303296/ec8e1244-f8b2-4f6d-9077-673b8dcc1b62)

However, in the From Image tab, it does not follow the order that is set:
![From Image Tab UI Order](https://github.com/vladmandic/automatic/assets/124303296/864899b8-cca6-4332-a7ba-54e1d04b047e)

How do I go about correcting this?

### Version Platform Description

Version: b979d448 Wed May 17 14:41:13 2023 -0400

Web Browser: Microsoft Edge Version 113.0.1774.42 (Official build) (64-bit)

arch: AMD64
cpu: Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.10.11

device: NVIDIA GeForce RTX 3090 (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8700

**Comment by vladmandic** [comment]
i think script order only applied to txt2img, i need to do the same to img2img.

**Comment by vladmandic** [comment]
fixed.

**Comment by nullsweat** [comment]
I just updated UI. Everything is in order now! Thanks!
