### ISSUE TITLE
[Issue]: Live previews not functional after update to 0ccda9b 

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#1033]
### Issue Description

Live previews are not displayed during generation (generation occurs normally). An inspection with Chrome's developer tools shows that there's some JS error being raised:

```js
Blocks.svelte:230 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'props')
    at Blocks.svelte:230:30
    at Array.forEach (<anonymous>)
    at ye (Blocks.svelte:215:9)
    at Blocks.svelte:300:7
progressbar.js?1684348655.0870676:17 ReferenceError: livePreview is not defined
    at progressbar.js?1684348655.0870676:116:11
    at xhr.onreadystatechange (progressbar.js?1684348655.0870676:15:11)
xhr.onreadystatechange @ progressbar.js?1684348655.0870676:17
progressbar.js?1684348655.0870676:79 Uncaught ReferenceError: livePreview is not defined
    at removeProgressBar (progressbar.js?1684348655.0870676:79:50)
    at progressbar.js?1684348655.0870676:129:7
    at xhr.onreadystatechange (progressbar.js?1684348655.0870676:18:11)
```

My guess would be that 0ccda9bc8b1c59ace99a5b09d7022f7912da196a broke something, however the changes even in `progressbar.js` are so many I can't figure out what exactly would cause this.

### Version Platform Description

Commit: 0ccda9bc8b1c59ace99a5b09d7022f7912da196a
OS: Linux (Ubuntu as provided by Paperspace)
GPU: NVIDIA RTXA4000 (in the Paperspace Gradient cloud)
Browsers tested: Firefox (latest version), Chrome (latest version)

**Comment by DyingWorld** [comment]
I'm experiencing the exact same issue on Firefox with my local install

**Comment by lbeltrame** [comment]
This also breaks generations, meaning that the UI will not reset its state afterwards (likely due to the JS error before that leaves things in an inconsistent state).

**Comment by vladmandic** [comment]
fixed.
