### ISSUE TITLE
[Issue]: Stop/Skip buttons don't disappear

### ISSUE THREAD

**Issue by Trojaner** [vladmandic/automatic#1036]
### Issue Description

Probably after [this commit](https://github.com/vladmandic/automatic/commit/0ccda9bc8b1c59ace99a5b09d7022f7912da196a) I can't generate more than one image, as the stop/skip buttons don't disappear after the image is generated. Clicking the buttons doesn't do anything. If I reload the page, it will stay on "Waiting..." after clicking on generate. No errors in console.

Got a bunch of errors in DevTools console instead:
![image](https://github.com/vladmandic/automatic/assets/1809172/90d9e729-8b4a-4609-8acf-db38ca6dda21)

### Version Platform Description

Python 3.10.6 on Windows
Version: b979d448 Wed May 17 14:41:13 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.0+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8900
Torch detected GPU: NVIDIA GeForce RTX 4080 VRAM 16376 Arch (8, 9) Cores 76

**Comment by vladmandic** [comment]
fixed.

**Comment by Trojaner** [comment]
Can confirm, thank you
