### ISSUE TITLE
[External] Xformers crash on Windows

### ISSUE THREAD

**Issue by githubUser01946** [vladmandic/automatic#104]
### Issue Description

When I launched `launch.py` for the first time it showed the following popup message:

![image](https://user-images.githubusercontent.com/117453319/231766053-4d65487c-a5de-452d-a899-136dfbd864b1.png)

### Platform Description

Windows 10

**Comment by vladmandic** [comment]
`xformers` need to be installed to exactly match version of `torch` - did you try reinstalling them?

**Comment by githubUser01946** [comment]
I'm away from it at the moment. When I get back I'll start it up again and
maybe it'll work?

If not how do I fix it?

**Comment by vladmandic** [comment]
try this:

```shell
venv\Scripts\activate
pip show torch
pip uninstall xformers
pip install -U xformers --no-deps
```

**Comment by githubUser01946** [comment]
I run that in CMD via the Automatic directory?

**Comment by vladmandic** [comment]
> CMD

yes.

**Comment by githubUser01946** [comment]
I just wanted to make sure it was done in the right place.

**Comment by mykeehu** [comment]
I have xformers installed in venv, but according to the System info it is not loaded, the `--xformers` option is not usable. Do I need to load it separately or does it use it automatically in the background?

**Comment by githubUser01946** [comment]
> ```shell
> venv\Scripts\activate
> ```

When I open CMD in D:\automatic it says `The system cannot findthe path specified`
Also when I run the `pip show torch` it returns with: `D:\automatic>pip show torch
WARNING: Ignoring invalid distribution -ransformers (c:\users\cpgsa\appdata\local\programs\python\python310\lib\site-packages)
Name: torch
Version: 1.12.1+cu113
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\githubUser01946\appdata\local\programs\python\python310\lib\site-packages
Requires: typing-extensions
Required-by: accelerate, basicsr, clean-fid, clip, clip-interrogator, facexlib, fairscale, gfpgan, invisible-watermark, kornia, lpips, open-clip-torch, pytorch-lightning, realesrgan, timm, torchdiffeq, torchmetrics, torchsde, torchvision, xformers`

**Comment by githubUser01946** [comment]
![image](https://user-images.githubusercontent.com/117453319/232040987-8bb65e2d-666a-4cf4-a704-c39c098012e3.png)

**Comment by vladmandic** [comment]
this is ancient. you need to uninstall torch and have webui.bat install requirements correctly.
see #107

**Comment by githubUser01946** [comment]
Ok so i have an update. I have moved webui-user.bat from the original automatic1111 install in the folder of yours and now it says this in cmd when I run it:

![image](https://user-images.githubusercontent.com/117453319/232041541-95621a5d-4b91-45b5-bee8-c3beb27db484.png)

**Comment by githubUser01946** [comment]
> your torch is obsolete. you need to uninstall it and have webui.bat install requirements correctly - see #107
> 
> and did you get `git` outputs as previously asked? that must work in order for anything to be ok.
> 
> and DO NOT copy files from a1111 blindly - you're just causing conflicts.

I am currently doing what #107 states. As for the last thing, I thought I read somewhere that you stated webui-user.bat was fine to use. Obviously not. I have removed that 1 file as thats the only file from A1111 I had moved across.

**Comment by githubUser01946** [comment]
Double clicked `launch.py` which has started `py.exe` that has a loads of errors but it is continuing to do things....

**Comment by githubUser01946** [comment]
It is now loaded but the model doesnt seem to want to load.
![image](https://user-images.githubusercontent.com/117453319/232066918-0cef59dd-b405-4f72-bde3-dfe2aaef369e.png)

**Comment by vladmandic** [comment]
why are you double-clicking `launch.py`??? what does it say in the readme? 
**webui.bat**: If you're unsure which launcher to use, this is the one you want
there is a good reason for that.

now you have tons of python libs installed in as **system**, **user** and **venv** and its a mess.
cleaning that up is non-trivial - and cleanup is clearly needed.

easiest is to uninstall python and start from scratch and follow install procedure.
and when complete, post console output here.

**Comment by vladmandic** [comment]
@Centurion-Rome i agree with what you've said, but note that he has obsolete `torch` 1.12 and did several different installs with and without `venv`, clean install is required.

**Comment by githubUser01946** [comment]
> why are you double-clicking `launch.py`??? what does it say in the readme? **webui.bat**: If you're unsure which launcher to use, this is the one you want there is a good reason for that.
> 
> now you have tons of python libs installed in as **system**, **user** and **venv** and its a mess. cleaning that up is non-trivial - and cleanup is clearly needed.
> 
> easiest is to uninstall python and start from scratch and follow install procedure. and when complete, post console output here.

Maybe you should look at how you wrote the instructions instead of being rude to people who have to follow them.

Rudeness isnt the way to go.
