### ISSUE TITLE
[Extension]: After Detailer causes UI Progress bar to break

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1044]
### Issue Description

When using After Detailer, the UI progress bar only seems to count the first image in a generation batch.

This doesn't affect generating at all, it's just a visual UI bug.

EDIT: After watching the console and UI progress bars, it seems that the UI progress bar is counting each After Detailer operation as a completed image generation.

### Version Platform Description

Version: 1dffd114
Win10/Chrome

**Comment by vladmandic** [comment]
that should probably be reported to extension author

**Comment by brknsoul** [comment]
Issue created
https://github.com/Bing-su/adetailer/issues/66

**Comment by vladmandic** [comment]
closing this as its a known issue to extension author and can be tracked there.
