### ISSUE TITLE
[Issue]: Model Files in Symlink Folders were perfectly loaded in Version Mon 15.05 and are not loaded in Version Wed 17.05 anymore

### ISSUE THREAD

**Issue by TheOnlyHolyMoly** [vladmandic/automatic#1045]
### Issue Description

I just pulled the latests release Wed 17.05 from Mon 15.05. 

I am a model hoarder so I have the repo installed on D:\ and a model library on E:\ drive... I did not want to bug your for alternate model paths so I just created symlinks in 
models\Stable-diffusion\linkfolder
models\LORA\linkfolder
models\LYCORIS\linkfolder

with the corresponding linkfolders pointing to 
models\Stable-diffusion\
models\LORA\
models\LYCORIS\

and it also worked super fine and comfortable. 

With the latest release SD will not find these externally linked files anymore, so I was just wondering if you had adjusted anything major on creating the model/lora list?

### Version Platform Description

Windows / CUDA / Torch 2

**Comment by vladmandic** [comment]
Change is from upstream A1111, but I think I can modify it to make it work with symlink. I'll check tomorrow.

**Comment by vladmandic** [comment]
fixed.

**Comment by TheOnlyHolyMoly** [comment]
Super, fix confirmed, all models loading fine! Thank you Sir!

**Comment by Acrivec** [comment]
.ckpt for 2.1 is loading correctly as a symlink, but I'm unable to load .safetensor files for SDXL. Tried placing in /models/, in /models/stable-diffusion/, in /models/diffusers/ and /models/diffusers/SDXL/. It's invisible.

**Comment by vladmandic** [comment]
Commenting on an issue that was closed 5month ago does not help
