### ISSUE TITLE
[Feature Request]: Can we have radio buttons for samplers back?

### ISSUE THREAD

**Issue by AlUlkesh** [vladmandic/automatic#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Give the choice to have samplers in dropdown or radio buttons.

### Proposed workflow

1. Go to Settings
2. Choose option

### Additional information

Was there a particular reason this was removed? I feel I'm way faster with clicking them via radio buttons.

If not, I can add an PR for that.

**Comment by vladmandic** [comment]
i'm trying to minimize number of items in the main ui and radio group is a very busy item.
majority of users will try couple of samplers and then settle on one for majority of operations. 
yes, having a combobox is one click longer, but its that vs cleaner ui - sorry.

**Comment by AlUlkesh** [comment]
Sure, no problem. I can always just add it for my local copy.
