### ISSUE TITLE
[Feature]:  Use XYZ Grid to create images only

### ISSUE THREAD

**Issue by TheOnlyHolyMoly** [vladmandic/automatic#1051]
### Issue Description

Not sure if this belongs to bug or feature request...

I am trying to rotate a prompt through all models with XYZ Script (using only X axis across all models (over 600). And I believe to remember from a different thread that you had said if the "save grid" options were turned off, it should not run into grid creation errors. 

Config.json says it should NOT save grids I believe
    "grid_save": false,
    "grid_format": "png",
    "grid_extended_filename": true,
    "grid_only_if_multiple": false,
    "grid_prevent_empty_spots": true,
    "grid_save_to_dirs": false,

However, when I try to execute the XYZ script error "Grid size: 310 excedes 200 MPixels, even though he'll discard the grid at the end."  >>I am only after the individual images and dont want/need the grid.

I think someone had suggested a "do not generate grid" flag for UI. An alternative could be to generate more grid tables, if the grid would be exceeded. This might be even a viable idea for people creating larger grids through permuatations across X / Y / Z axis.

I have been trying to create my own custom script (model walker) based on XYZ, but since there is so much going on in it, I have yet failed to come up with a useful approach what to delete first. 

The only option to bypass this now is to only select a certain number of models, but given the amount of models, that'd be not too practical.

I know the use case is kind of abusive for an XYZ Grid Script, pleasae let me know what you think. 

### Version Platform Description

latest Version

13:56:32-113940 INFO     Available VAEs: D:\VLADautomatic\models\VAE 3
13:57:24-077943 INFO     Available models: D:\VLADautomatic\models\Stable-diffusion 863

**Comment by vladmandic** [comment]
abuse of xyz grid? maybe. but i like the idea :)
its implemented as of now - new checkbox: `Do not create grid`

**Comment by TheOnlyHolyMoly** [comment]
works perfectly, thank you so much!! This helps me greatly exploring what the models are actually capable of...  :-)
