### ISSUE TITLE
[Issue]: Module load:                          D:/VLADautomatic/extensions-builtin/stable-diffusion-webui-rembg\scripts\postprocessing_rembg.  py: SystemError

### ISSUE THREAD

**Issue by TheOnlyHolyMoly** [vladmandic/automatic#1052]
### Issue Description

Just pulled latest release
- downgraded my numpy open start
- starts and then crashes with exception (please see below)

Using VENV: D:\VLADautomatic\venv
15:56:42-559093 INFO     Starting SD.Next
15:56:42-565091 INFO     Python 3.10.6 on Windows
15:56:42-716094 INFO     Version: 22a9e701 Thu May 18 09:46:36 2023 -0400
15:56:43-226093 INFO     Setting environment tuning
15:56:43-232093 INFO     nVidia CUDA toolkit detected
15:56:45-550094 INFO     Torch 2.0.0+cu118
15:56:45-578092 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
15:56:45-582092 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24563 Arch (8, 9) Cores 128
15:56:45-585092 INFO     Verifying requirements
15:56:45-609123 INFO     Installing packages
15:56:45-706094 INFO     No changes detected: Quick launch active
15:56:45-712095 INFO     Running extension preloading
15:56:45-715094 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
15:56:53-295094 INFO     Libraries loaded
15:56:53-339092 INFO     Available VAEs: D:\VLADautomatic\models\VAE 3
15:58:26-150206 INFO     Available models: D:\VLADautomatic\models\Stable-diffusion 2687
15:58:32-641207 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float32 unet=torch.float16
Loading weights: models\Stable-diffusion\E-Drive\sdartCompleteEdition_v2Base21.safetensors ---------- 0.0/2.6   -:--:--
                                                                                                      GB
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
15:59:32-283207 INFO     Model created from config: models\Stable-diffusion\E-Drive\sdartCompleteEdition_v2Base21.yaml
Loading weights: D:\VLADautomatic\models\VAE\E-Drive\vae-ft-mse-840000-ema-pruned (1).safetensors ------ 0.0/3… -:--:--
                                                                                                         MB
16:00:07-146207 INFO     Applying scaled dot product cross attention optimization (without memory efficient attention)
16:00:07-202206 INFO     Embeddings loaded: 0 []
16:00:07-212206 INFO     Model loaded in 94.7s (load=59.2s config=0.3s create=0.2s apply=18.8s vae=15.2s move=0.9s
                         embeddings=0.1s)
16:00:07-398206 INFO     Model load finished: {'ram': {'used': 3.74, 'total': 15.93}, 'gpu': {'used': 4.29, 'total':
                         23.99}, 'retries': 0, 'oom': 0}
ControlNet v1.1.174
ControlNet v1.1.174
16:00:08-824208 ERROR    Module load:
                         D:/VLADautomatic/extensions-builtin/stable-diffusion-webui-rembg\scripts\postprocessing_rembg.
                         py: SystemError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\VLADautomatic\modules\script_loading.py:10 in load_module                                                        │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 8 frames hidden ...                                               │
│                                                                                                                     │
│ D:\VLADautomatic\venv\lib\site-packages\numba\np\ufunc\__init__.py:3 in <module>                                    │
│                                                                                                                     │
│    2                                                                                                                │
│ >  3 from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize                           │
│    4 from numba.np.ufunc._internal import PyUFunc_None, PyUFunc_Zero, PyUFunc_One                                   │
│                                                                                                                     │
│ D:\VLADautomatic\venv\lib\site-packages\numba\np\ufunc\decorators.py:3 in <module>                                  │
│                                                                                                                     │
│     2                                                                                                               │
│ >   3 from numba.np.ufunc import _internal                                                                          │
│     4 from numba.np.ufunc.parallel import ParallelUFuncBuilder, ParallelGUFuncBuilder                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
SystemError: initialization of _internal failed without raising an exception
16:00:09-254238 INFO     Loading UI theme: black-orange

### Version Platform Description

15:56:42-716094 INFO     Version: 22a9e701 Thu May 18 09:46:36 2023 -0400

**Comment by vladmandic** [comment]
which numba version do you have?

```shell
venv\Scripts\activate
pip show numpy
pip show numba
```

**Comment by TheOnlyHolyMoly** [comment]
(venv) D:\VLADautomatic>pip show numpy
Name: numpy
Version: 1.24.3
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: BSD-3-Clause
Location: d:\vladautomatic\venv\lib\site-packages
Requires:
Required-by: accelerate, altair, basicsr, blendmodes, clean-fid, contourpy, diffusers, facexlib, fairscale, filterpy, fvcore, gfpgan, gradio, h5py, imageio, jax, lpips, matplotlib, mediapipe, ml-dtypes, numba, numexpr, onnxruntime, opencv-contrib-python, opencv-python, opt-einsum, pandas, PyMatting, pytorch-lightning, PyWavelets, realesrgan, rembg, scikit-image, scipy, tb-nightly, tensorboard, tensorflow-intel, tifffile, torchmetrics, torchsde, torchvision, transformers

(venv) D:\VLADautomatic>pip show numba
Name: numba
Version: 0.56.4
Summary: compiling Python code using LLVM
Home-page: https://numba.pydata.org
Author:
Author-email:
License: BSD
Location: d:\vladautomatic\venv\lib\site-packages
Requires: llvmlite, numpy, setuptools
Required-by: facexlib, PyMatting

**Comment by vladmandic** [comment]
try installing exact version manually and if that fixes it, i'll modify requirements to automatically perform that:

```shell
venv\Scripts\activate
pip install numba==0.57.0
```

**Comment by TheOnlyHolyMoly** [comment]
YUP! That solved it. Starting up like a charm again.

Thank you! Issue solved
