### ISSUE TITLE
[Issue]: ControlNet, Lora, Clip etc. models are all available in the checkpoint dropdown

### ISSUE THREAD

**Issue by tripletto** [vladmandic/automatic#1053]
### Issue Description

Instead of showing only the models in the folder \models\Stable-diffusion, every model which is recursively contained in the \models folder is shown. 

### Version Platform Description

Windows 10
16:01:51-263123 INFO     Python 3.10.6 on Windows
16:01:51-322137 INFO     Version: 22a9e701 Thu May 18 09:46:36 2023 -0400
16:01:51-617048 INFO     Setting environment tuning
16:01:51-620049 INFO     nVidia CUDA toolkit detected
16:01:53-225691 INFO     Torch 2.0.1+cu118
16:01:53-246098 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
16:01:53-248439 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 Ti VRAM 8192 Arch (8, 6) Cores 38

**Comment by tripletto** [comment]
![Screenshot 2023-05-18 16 11 42](https://github.com/vladmandic/automatic/assets/10447009/b62aca88-5dc0-46ac-a9f5-bb9c55d002d5)

**Comment by vladmandic** [comment]
uuups. fixed.
