### ISSUE TITLE
[Issue]: RecursionError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by ryukra** [vladmandic/automatic#1054]
### Issue Description

I updated and get an error, I deleted the config file and removed all user extensions.

`17:00:44-174138 ERROR    Exception: maximum recursion depth exceeded while calling a Python object
17:00:44-176636 ERROR    Arguments: args=('task(qbfk14ho6jyjz80)', 'test', '', [], 20, 0, False, False, 1, 1, 6, -1.0,
                         -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False,
                         'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64,
                         False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 3072, 192, True, True, True,
                         False, <controlnet.py.UiControlNetUnit object at 0x000001A963ABF670>, False, False,
                         'positive', 'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False,
                         False, 0, None, False, 50, False, 4.0, '', 10.0, 'Linear', 3, False, 30.0, True, False, False,
                         0, 0.0, 'Lanczos', 1, True, 0, 0, 0.001, 75, 0.0, False, True) kwargs={}
17:00:44-213633 ERROR    gradio call: RecursionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\vladomatic\modules\call_queue.py:33 in f                                                                         │
│                                                                                                                     │
│    32 │   │   │   try:                                                                                              │
│ >  33 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    34 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ D:\vladomatic\modules\txt2img.py:56 in txt2img                                                                      │
│                                                                                                                     │
│   55 │   if processed is None:                                                                                      │
│ > 56 │   │   processed = process_images(p)                                                                          │
│   57 │   p.close()                                                                                                  │
│                                                                                                                     │
│                                              ... 980 frames hidden ...                                              │
│                                                                                                                     │
│ D:\vladomatic\venv\lib\site-packages\torch\nn\modules\module.py:1627 in __setattr__                                 │
│                                                                                                                     │
│   1626 │   │   params = self.__dict__.get('_parameters')                                                            │
│ > 1627 │   │   if isinstance(value, Parameter):                                                                     │
│   1628 │   │   │   if params is None:                                                                               │
│                                                                                                                     │
│ D:\vladomatic\venv\lib\site-packages\torch\nn\parameter.py:10 in __instancecheck__                                  │
│                                                                                                                     │
│     9 │   │   return super().__instancecheck__(instance) or (                                                       │
│ >  10 │   │   │   isinstance(instance, torch.Tensor) and getattr(instance, '_is_param', False)                      │
│    11                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RecursionError: maximum recursion depth exceeded while calling a Python object`

### Version Platform Description

Version: 8b682183 Thu May 18 10:41:24 2023 -0400

**Comment by ryukra** [comment]
Newly installed works.

**Comment by vladmandic** [comment]
i'm glad it did because i cannot see anything from the traceback above.
