### ISSUE TITLE
[Issue]: Errors after --upgrade

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#1055]
### Issue Description

After webui.bat --upgrade
Two things:
1. VAE's not show in: Select VAE: only 'none' and 'Automatic'
2. Infinity-zoom extension make error and not show up. 
3. See log.

[log-18.5.txt](https://github.com/vladmandic/automatic/files/11508939/log-18.5.txt)
[setup.log](https://github.com/vladmandic/automatic/files/11508943/setup.log)

### Version Platform Description

Device name	DESKTOP-89OI1TC
Processor	AMD Ryzen 7 6800H with Radeon Graphics            3.20 GHz
Installed RAM	32.0 GB (31.2 GB usable)
Device ID	57F773B6-2052-4400-9EEE-5DA99ADC9758
Product ID	00331-20350-00000-AA537
System type	64-bit operating system, x64-based processor
GPU NVIDIA RTX 3090

**Comment by vladmandic** [comment]
issue should be resolved in latest update.

**Comment by ShmuelRonen** [comment]
Thanks!!!
