### ISSUE TITLE
[Feature] Handle extensions looking up removed command line flags

### ISSUE THREAD

**Issue by mart-hill** [vladmandic/automatic#106]
### Issue Description

[This extension](https://github.com/DominikDoom/a1111-sd-webui-tagcomplete) simply refuses to initialize, probably because handling wildcards directories changed a bit in this fork. Though, [UmiAI](https://github.com/Klokinator/Umi-AI/wiki/Umi-AI's-Tagging-System) extension, which relies on sort-of-wildcards, too, seems to be working fine. 
I'll check in the following run, if [UmiAI](https://github.com/Klokinator/Umi-AI/wiki/Umi-AI's-Tagging-System), despite throwing no errors during startup, functions properly.

```
Error loading script: tag_autocomplete_helper.py
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ X:\AI\automatic\modules\scripts.py:255 in load_scripts                                                           │
│                                                                                                                  │
│   253 │   │   │   current_basedir = scriptfile.basedir                                                           │
│   254 │   │   │                                                                                                  │
│ ❱ 255 │   │   │   script_module = script_loading.load_module(scriptfile.path)                                    │
│   256 │   │   │   register_scripts_from_module(script_module)                                                    │
│   257                                                                                                            │
│                                                                                                                  │
│ X:\AI\automatic\modules\script_loading.py:11 in load_module                                                      │
│                                                                                                                  │
│    9 │   module_spec = importlib.util.spec_from_file_location(os.path.basename(path), path)                      │
│   10 │   module = importlib.util.module_from_spec(module_spec)                                                   │
│ ❱ 11 │   module_spec.loader.exec_module(module)                                                                  │
│   12 │                                                                                                           │
│   13 │   return module                                                                                           │
│ in exec_module:883                                                                                               │
│ in _call_with_frames_removed:241                                                                                 │
│                                                                                                                  │
│ X:\AI\automatic\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py:27 in <module>          │
│                                                                                                                  │
│    25 # The path to the folder containing the wildcards and embeddings                                           │
│    26 WILDCARD_PATH = FILE_DIR.joinpath('scripts/wildcards')                                                     │
│ ❱  27 EMB_PATH = Path(shared.cmd_opts.embeddings_dir)                                                            │
│    28 HYP_PATH = Path(shared.cmd_opts.hypernetwork_dir)                                                          │
│    29                                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'embeddings_dir'
```
I have "embeddings" directory with some models inside, and it's being used properly within the UI.

### Platform Description

Windows 10 22H2, RTX 3090, MS Edge.

**Comment by vladmandic** [comment]
issue is that it checks for command line flag to detemine location of embeddings folder: `shared.cmd_opts.embeddings_dir`
and those flags no longer exist in this repo, its all been moved to settings.

i'll add some sort of "compatibility layer" not to disrupt such extensions.

**Comment by mart-hill** [comment]
Thank you so much for your hard work! It's incredible, how you, extension programmers, and the programmer of [-ux fork](https://github.com/anapnoe/stable-diffusion-webui-ux) strive to deliver a different, and unique experience for SD AI users.🙂

**Comment by Woisek** [comment]
I may add, that here I also get a namespace error for ckpt_dir:

AttributeError: 'Namespace' object has no attribute 'embeddings_dir'
Error executing callback ui_tabs_callback for I:\Super SD 2.0\automatic\extensions\sd-model-preview-xd\scripts\modelpreview.py
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\modules\script_callbacks.py:125 in ui_tabs_callback                                       │
│                                                                                                                     │
│   123 │   for c in callback_map['callbacks_ui_tabs']:                                                               │
│   124 │   │   try:                                                                                                  │
│ > 125 │   │   │   res += c.callback() or []                                                                         │
│   126 │   │   except Exception:                                                                                     │
│   127 │   │   │   report_exception(c, 'ui_tabs_callback')                                                           │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\extensions\sd-model-preview-xd\scripts\modelpreview.py:687 in on_ui_tabs                  │
│                                                                                                                     │
│   685 │   │   # create a tab for the checkpoint previews                                                            │
│   686 │   │   create_tab("Checkpoints", "cp",                                                                       │
│ > 687 │   │   │   │   list_all_models(),                                                                            │
│   688 │   │   │   │   show_model_preview,                                                                           │
│   689 │   │   │   │   filter_models,                                                                                │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\extensions\sd-model-preview-xd\scripts\modelpreview.py:168 in list_all_models             │
│                                                                                                                     │
│   166 │   model_list = sd_models.checkpoint_tiles()                                                                 │
│   167 │   checkpoint_choices = sorted(model_list, key=natural_order_number)                                         │
│ > 168 │   search_for_tags(checkpoint_choices, tags["checkpoints"], get_checkpoints_dirs())                          │
│   169 │   return checkpoint_choices                                                                                 │
│   170                                                                                                               │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\extensions\sd-model-preview-xd\scripts\modelpreview.py:489 in get_checkpoints_dirs        │
│                                                                                                                     │
│   487 │   # create list of directories                                                                              │
│   488 │   directories = [os.path.join('models','Stable-diffusion')] # models/Stable-diffusion                       │
│ > 489 │   set_dir = shared.cmd_opts.ckpt_dir                                                                        │
│   490 │   if set_dir is not None and not is_dir_in_list(directories, set_dir):                                      │
│   491 │   │   # WARNING: html files and markdown files that link to local files outside of the                      │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Namespace' object has no attribute 'ckpt_dir'
Running on local URL:  http://127.0.0.1:7861

**Comment by Razunter** [comment]
Related, probably: `NameError: name 'xformers' is not defined` in https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111 (great extension, btw)

xformers is installed, but not selected in the options

**Comment by vladmandic** [comment]
how a1111 works, if `xformers` are not explicitly enabled, webui will mark them as not-available to python, so nobody can use them. reason is that some extensions try to use them blindly and its causing major compatibility issues if some other cross-optimization is selected in main webui.

as such, extension should never assume xformers are available.

**Comment by vladmandic** [comment]
ok, pushed updated so cmdflags will be available in compatibility mode for extensions to use as-is.
if issue reoccurs, i'll reopen it.

**Comment by mart-hill** [comment]
For now, I still get this error with this extension, should I enable some option or use a commandline one?

```
loading script: tag_autocomplete_helper.py: AttributeError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ X:\AI\automatic\modules\scripts.py:255 in load_scripts                                                           │
│                                                                                                                  │
│   254 │   │   │                                                                                                  │
│ ❱ 255 │   │   │   script_module = script_loading.load_module(scriptfile.path)                                    │
│   256 │   │   │   register_scripts_from_module(script_module)                                                    │
│                                                                                                                  │
│ X:\AI\automatic\modules\script_loading.py:12 in load_module                                                      │
│                                                                                                                  │
│   11 │   module = importlib.util.module_from_spec(module_spec)                                                   │
│ ❱ 12 │   module_spec.loader.exec_module(module)                                                                  │
│   13                                                                                                             │
│                                                                                                                  │
│                                             ... 1 frames hidden ...                                              │
│ in _call_with_frames_removed:241                                                                                 │
│                                                                                                                  │
│ X:\AI\automatic\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py:27 in <module>          │
│                                                                                                                  │
│    26 WILDCARD_PATH = FILE_DIR.joinpath('scripts/wildcards')                                                     │
│ ❱  27 EMB_PATH = Path(shared.cmd_opts.embeddings_dir)                                                            │
│    28 HYP_PATH = Path(shared.cmd_opts.hypernetwork_dir)                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'embeddings_dir'
```

**Comment by vladmandic** [comment]
did you update the repo? how did you update it?
it does not perform auto-update by default on its own, its disabled for now.

**Comment by mart-hill** [comment]
I did, through "Git Bash here", not as administrator, and then `git pull`.

**Comment by vladmandic** [comment]
and you're still getting the error?

**Comment by Razunter** [comment]
Getting the same errors too.

https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper

> │ ❱  33 │   if shared.cmd_opts.embeddings_dir and os.path.isdir(shared.cmd_opts.embeddings_dir):                       │
│    34 │   │   folders["ti"] = shared.cmd_opts.embeddings_dir                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'embeddings_dir'

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete

> │ ❱  27 EMB_PATH = Path(shared.cmd_opts.embeddings_dir)                                                                │
│    28 HYP_PATH = Path(shared.cmd_opts.hypernetwork_dir)                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'embeddings_dir'

**Comment by mart-hill** [comment]
> and you're still getting the error?

Yes. I immediately tried to enable the extension after your post, since it's REALLY helpful, especially while selecting embeddings, LoRAs or even UmiAI wildcards.

**Comment by vladmandic** [comment]
ahh, my bad, sorry, my patch to cross-link cmdflags and options was loading too late for some specific scripts. should be ok now.

**Comment by Razunter** [comment]
@vladmandic testing https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/130
fails with
```
│ ❱  26 │   if cmd_opts.force_enable_xformers or (cmd_opts.xformers and shared.xformers_availabl                       │
│    27 │   │   attn_forward_method = xformers_attnblock_forward                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'force_enable_xformers'
```

**Comment by pkuliyi2015** [comment]
Ah? I'm copying this from the sd_hijack.py, it is weird. Let me have a look now.

**Comment by vladmandic** [comment]
@pkuliyi2015 don't check `cmd_opts` or `opts` - even if you get it right, it doesn't guarantee that xformers are actually active, only that user wanted to use them. simply check if its active or not `sd_hijack.model_hijack.optimization_method == 'xformers'`

**Comment by pkuliyi2015** [comment]
I have to use my own attention forward function as the norm and residual has to be removed from the function. So I need to know what type optimization the user is chosen, and switch to a proper one.

But you are right, I will do a switch on the sd_hijack.model_hijack.optimization_method.

**Comment by vladmandic** [comment]
> I have to use my own attention forward function as the norm and residual has to be removed from the function. So I need to know what type optimization the user is chosen, and switch to a proper one.
> 
> But you are right, I will do a switch on the sd_hijack.model_hijack.optimization_method.

fyi, even if user has `xformers` installed and wants to use them (via `cmd_opts` or `opts`), they still may fail in which case webui removes them from python modules cache so no extension can look them up and even try to use them - thats because `stable-diffusion-stability-ai` original repo attempts to use them regardless if user selected them or not. so by removing them from any possible lookups, that repo will behave nicely.

**Comment by pkuliyi2015** [comment]
Thanks for reminding. I pushed a new trial fix and this time it should work nicely.

**Comment by Razunter** [comment]
@pkuliyi2015 works good

**Comment by pkuliyi2015** [comment]
Great! I verified the update is still compatible with/without xformers optimization, and will merge the update into the main branch & close the issue.

**Comment by vladmandic** [comment]
> @pkuliyi2015 works good

same here.

**Comment by pkuliyi2015** [comment]
Thanks for all your effort in improving the SD webui.

**Comment by vladmandic** [comment]
> Thanks for all your effort in improving the SD webui.

btw, great job with the extension, i think i'll add it to list of preinstalled ones in my fork!
