### ISSUE TITLE
[Extension]: OpenOutpaint stop working

### ISSUE THREAD

**Issue by sebaxakerhtc** [vladmandic/automatic#1060]
### Issue Description

Morning was working, but now after restart isn't working
As i understand - cannot create tab outpaint, cannot update app: list index out of range
```
19:31:47-441607 ERROR    executing callback: D:/automatic/extensions/openOutpaint-webUI-extension\scripts\main.py
                         ui_tabs_callback: IndexError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ D:/automatic/extensions/openOutpaint-webUI-extension\scripts\main.py:64 in add_tab                                   ││                                                                                                                      ││   63 │   │   else:                                                                                                   ││ ❱ 64 │   │   │   update_app()                                                                                        ││   65 │   except Exception:                                                                                           ││                                                                                                                      ││ D:/automatic/extensions/openOutpaint-webUI-extension\scripts\main.py:55 in update_app                                ││                                                                                                                      ││   54 │   # print(scripts.basedir)                                                                                    ││ ❱ 55 │   run(f'"{git}" -C "' + os.path.join(scripts.basedir(), usefulDirs[0], usefulDirs[1])                         ││   56 │   │   '" submodule update --init --recursive --remote', live=True)                                            │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯IndexError: list index out of range

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ D:\automatic\modules\script_callbacks.py:151 in ui_tabs_callback                                                     ││                                                                                                                      ││   150 │   │   try:                                                                                                   ││ ❱ 151 │   │   │   res += c.callback() or []                                                                          ││   152 │   │   except Exception as e:                                                                                 ││                                                                                                                      ││ D:/automatic/extensions/openOutpaint-webUI-extension\scripts\main.py:66 in add_tab                                   ││                                                                                                                      ││   65 │   except Exception:                                                                                           ││ ❱ 66 │   │   update_app()                                                                                            ││   67                                                                                                                 ││                                                                                                                      ││ D:/automatic/extensions/openOutpaint-webUI-extension\scripts\main.py:55 in update_app                                ││                                                                                                                      ││   54 │   # print(scripts.basedir)                                                                                    ││ ❱ 55 │   run(f'"{git}" -C "' + os.path.join(scripts.basedir(), usefulDirs[0], usefulDirs[1])                         ││   56 │   │   '" submodule update --init --recursive --remote', live=True)                                            │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯IndexError: list index out of range
```

### Version Platform Description

Windows

### URL link of the extension

https://github.com/zero01101/openOutpaint-webUI-extension

**Comment by vladmandic** [comment]
there is nothing in recent updates that would justify this. and error is extension failing to import `modules.scripts` which is part of core and nothing would work without that.
i've tried tons of different things, but i cannot reproduce the problem.
all i can say is "try again"?

**Comment by sebaxakerhtc** [comment]
> all i can say is "try again"

Tried... Deleted venv dir but with no luck.


> failing to import `modules.scripts` which is part of core and nothing would work without that

Today i installed a clean version of yours nice fork, but have a problem with --models-dir and set it like this `D:\\stable-diffusion-webui\\models`
Now i see you work on it. Maybe i should try to set it like before `D:\stable-diffusion-webui\models`

**Comment by sebaxakerhtc** [comment]
I'm going to get clean fork installation...

**Comment by vladmandic** [comment]
try `webui --upgrade --reinstall` to refresh.

re: `Every restart i see this:`
it says EXPLICITLY `(ignore asyncio.exceptions.CancelledError)` - those are aborts for open sessions towards browser. if i hide them, i might be hiding some really important stuff.

**Comment by sebaxakerhtc** [comment]
`git reset --hard 1dffd114fcd048877f14bc8344510163bb5f9755` helps - you should know

**Comment by sebaxakerhtc** [comment]
> try `webui --upgrade --reinstall` to refresh.

Trying on another instance

**Comment by sebaxakerhtc** [comment]
> try `webui --upgrade --reinstall` to refresh.

No changes

**Comment by vladmandic** [comment]
i just went through all changes since `1dffd11` and there is nothing to justify this. changes on listing available models and vaes, fix extension uninstall code on windows, some improvements to xyz grid and update of gradio/numpy/numba requirements.

**Comment by vladmandic** [comment]
> Ok. I going through every commit to find which will do that

i would gladly do it myself, but i cannot reproduce the issue.

**Comment by sebaxakerhtc** [comment]
> i cannot reproduce the issue

Thats strange...
Do you have `--listen --listen --auth user:pass --insecure `?

**Comment by vladmandic** [comment]
ok, i just pushed an update `325c094`, can you try?

**Comment by sebaxakerhtc** [comment]
> ok, i just pushed an update `325c094`, can you try?

Thank you - i'll try, but give me 5 min to find the buggy commit...

**Comment by sebaxakerhtc** [comment]
> > ok, i just pushed an update `325c094`, can you try?
> 
> Thank you - i'll try, but give me 5 min to find the buggy commit...

0e46e74c5e7e7147ec9e8251d5fc4e1cf116aa3b - from this one!

**Comment by sebaxakerhtc** [comment]
Closing as solved

**Comment by sebaxakerhtc** [comment]
> some improvements to xyz grid

I can't see "Use -1 seed" checkbox in this script anymore...

**Comment by vladmandic** [comment]
what is the use case?

**Comment by Lalimec** [comment]
not related but I thought OpenOutpaint is broken, did it get fixed some how, is it working with this repo?

**Comment by sebaxakerhtc** [comment]
> what is the use case?

When you want to get different  images from different models.
When you test the result from different versions of the same model is not important, but if your models based on different checkpoints - there's no any reason to save the seed.

**Comment by sebaxakerhtc** [comment]
> not related but I thought OpenOutpaint is broken, did it get fixed some how, is it working with this repo?

Yes. It was fixed 1 hour ago. Update your local version

**Comment by vladmandic** [comment]
> I can't see "Use -1 seed" checkbox in this script anymore...

its back.

**Comment by Lalimec** [comment]
> > not related but I thought OpenOutpaint is broken, did it get fixed some how, is it working with this repo?
> 
> Yes. It was fixed 1 hour ago. Update your local version run `webui --upgrade`

first i need to install vlads repo though lol. i had some issues and had to got rid of it, gunna give it another chance.

**Comment by sebaxakerhtc** [comment]
> its back

Thats why i named your fork "the best fork" - feedback.
