### ISSUE TITLE
[Feature]: Add/Copy 'Free GPU' button function and give it a handy place in the UI.

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#1066]
### Feature description

I've found it useful to occasionally purge my GPU memory, and since plenty of people run across errors all the time where that could be helpful to sort out problems...
I propose we slap a button into the interface to execute torch_gc. The same thing that's in the TiledDiffusion extension in essence, which I've used, it's just in a terrible place. Hopefully this can help reduce issues.

A couple of Possible locations:
![GPU-Memory-Free-Button](https://github.com/vladmandic/automatic/assets/108482020/ec9fbaaf-04c8-4f10-93f5-f75c035bc133)

Obviously a standard button should be used, but it's already built in.
script used by tiled diffusion: button.id = 'script_txt2txt_tiled_diffusion_reset_status';

**Comment by vladmandic** [comment]
its mostly pointless as that only deallocates already free memory. and its done often enough in the code automatically (by default,  when model is unloaded then again after its loaded and for a good measure after each generate completes).
if you think this would free up everything, it wouldn't as it only frees up already deallocated objects inside torch and there is no way to see what is actually allocated inside torch or to force unload those.
