### ISSUE TITLE
[Extension]: openOutpaint

### ISSUE THREAD

**Issue by ExaltedRaddix** [vladmandic/automatic#1067]
### Issue Description

help, i have the following problem. with open outpainting. i have saved my models somewhere else, and now the api doesn't load them. I think.

**Comment by mark-wd** [comment]
Can you give more info about your setup, such as version you are running, folder structure of the involved files, and so on?

**Comment by ExaltedRaddix** [comment]
i run with --upgrade all time =)      openoutpaint is installed a hour ago hmmm... location from the models in on another drive. so i think all up to date.  api is allways on, or?   because i tried --api and become error. i tried to copy a model in the original... but nothing
![grafik](https://github.com/vladmandic/automatic/assets/92941382/46f8eed7-a2ea-420a-baa9-cbe08f9f8ef5)

**Comment by ExaltedRaddix** [comment]
> Can you give more info about your setup, such as version you are running, folder structure of the involved files, and so on?

![grafik](https://github.com/vladmandic/automatic/assets/92941382/a980d616-55e5-4efd-ba1f-eb8d9dff37ee)

**Comment by vladmandic** [comment]
i just tried installing openoutpaint and all my models showed up without issues.
i also checked if sd api that lists models is working fine and it is:
> curl -H 'accept: application/json' -X 'GET' 'http://127.0.0.1:7860/sdapi/v1/sd-models'

you need to document your model structure.

**Comment by ExaltedRaddix** [comment]
> 

how can i do that ? I'm slightly confused because it doesn't even load the model, which I've now put in the default folder

**Comment by ExaltedRaddix** [comment]
> i just tried installing openoutpaint and all my models showed up without issues. i also checked if sd api that lists models is working fine and it is:
> 
> > curl -H 'accept: application/json' -X 'GET' 'http://127.0.0.1:7860/sdapi/v1/sd-models'
> 
> you need to document your model structure.

how can i do that ? I'm slightly confused because it doesn't even load the model, which I've now put in the default folder

**Comment by ExaltedRaddix** [comment]
![grafik](https://github.com/vladmandic/automatic/assets/92941382/e9db1e06-7dea-4617-9375-a3ce881f0c53)
 confused again. all model here, but still waiting for the host  ... 
![grafik](https://github.com/vladmandic/automatic/assets/92941382/0b1790fb-de14-4835-8995-06711faba858)

**Comment by vladmandic** [comment]
no idea, you probably need to ask extension author in that git repo.

**Comment by Quindicesima** [comment]
This isn't a fix for the problem, but it will let you continue using openOutpaint in the meantime. I have this problem as well and what fixes it temporarily is to locate the tiny blue refresh icon at the top center of the openOutpaint window and click it. It will ask you if you are sure, click OK. That will refresh the tab and the models will appear in the list along with the green 'connected' icon next to it. You'll need to do this every time you reload the WebUI in your browser.

**Comment by vladmandic** [comment]
ahhhh, newer version of the core app do delayed model loading, so any extension that accesses the list upon initial load will have empty list. extension should not access the list via variable, but via method that returns current list - as simple as that. and ideally, that should be done not when extension is preloading, but when its actually active (for devs - use lambda function, not static variable).

report this to extension author.

**Comment by ExaltedRaddix** [comment]
> This isn't a fix for the problem, but it will let you continue using openOutpaint in the meantime. I have this problem as well and what fixes it temporarily is to locate the tiny blue refresh icon at the top center of the openOutpaint window and click it. It will ask you if you are sure, click OK. That will refresh the tab and the models will appear in the list along with the green 'connected' icon next to it. You'll need to do this every time you reload the WebUI in your browser.

thank you very much =)   it works now ^^
