### ISSUE TITLE
[Issue]: Escaping characters with "\" doesn't work inside emphasis parentheses

### ISSUE THREAD

**Issue by crazygonuts** [vladmandic/automatic#1071]
### Issue Description

I can escape characters by preceding them with "\\" but not if it is within an emphasis parens
Example: ":D" in the prompt has almost no effect, but "\\:D" in the prompt usually makes the person in the image very happy, interpreting it as an emoji, but "( \\:D )" will have almost no effect again.

I do not know if this ever worked inside emphasis parens, sorry.  It might be a unique bug with ":" because of its meaning inside parenthesis.

**Comment by crazygonuts** [comment]
Version: 1c700567 Thu May 18 19:09:34 2023 -0400
windows 10

**Comment by vladmandic** [comment]
like you said, `:` has special meaning inside `()` or `[]` and cannot be used like that. This is a valid question, but why create an issue for it if you're not sure if its supposed to be used like that at all?
