### ISSUE TITLE
[Issue]: onnxruntime can not be installed

### ISSUE THREAD

**Issue by DwGoing** [vladmandic/automatic#1074]
### Issue Description

onnxruntime can not be installed when setup
<img width="1092" alt="image" src="https://github.com/vladmandic/automatic/assets/16076018/be608bbb-d970-4673-8a39-3e3bbcc4112c">
<img width="1103" alt="image" src="https://github.com/vladmandic/automatic/assets/16076018/4e844df5-2d8f-4795-9ca9-d83f16149eb0">

### Version Platform Description

Version: 527dc0ee Thu May 18 19:46:11 2023 -0400
OS: Apple M1 Max 13.2.1 (22D68)

**Comment by vladmandic** [comment]
i don't know why onnxruntime `1.14.0` is not available for mac, but `1.14.1` is known to cause problems, so cannot install that. i' not sure how to proceed.
but more importantly, you also have `illegal hardware instruction` logged - check system logs what causes that?

**Comment by mark-wd** [comment]
@DwGoing  That's unfortunate, because 1.14.1 totally breaks the extensions that depend on it. In this case, rembg.

Maybe force install 1.13.1 and let us know if that works? Or if you don't use rembg, you can proceed as normal probably.

**Comment by vladmandic** [comment]
i've moved onnxruntime from mandatory to optional requirements to address platforms where it doesn't exist.
