### ISSUE TITLE
[Issue]: Failed to initialize ROCm

### ISSUE THREAD

**Issue by StDavisOfTheHolyC** [vladmandic/automatic#1077]
### Issue Description

When attempting to launch the program I have found that it appears to fail to load weights for any given model, and proceeds to hang before reaching the point of launching/instancing the GUI. 

I was initially able to instance the WebUI, though it would only make use of my CPU for some reason, resulting in ridiculously slow generations. I proceeded to try and reinstall various packages and fix issues to rectify this. I appear to have succeeded, it is seemingly attempting to make use of my GPU now... Though this has come at the cost of being able to actually make use of the program entirely.

Solutions attempted: Reinstalling Python, deleting the venv folder, forcing the --reinstall arg, entirely reinstalling from the git repo, downloading multiple different checkpoints to ensure it wasnt simply a specific one with an issue.

Bizarrely; upon running webui.sh it APPEARS to load checkpoints, and the progress bar then reverts to either 0.0/4.3, or 0.3/4.3. I am uncertain what this means precisely.

Additionally: Though I clearly get a warning for "Can't initialize NVML", I have to admit I have no idea what this means precisely, I have only recently begun to make use of Linux.

Thank you.

11:27:42-562024 INFO     Starting SD.Next                                       
11:27:42-564692 INFO     Python 3.10.10 on Linux                                
11:27:42-569328 INFO     Version: 527dc0ee Thu May 18 19:46:11 2023 -0400       
11:27:42-726758 INFO     Setting environment tuning                             
11:27:42-728080 INFO     AMD ROCm toolkit detected                              
11:27:43-774436 INFO     Torch 2.0.0+rocm5.4.2                                  
/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
/opt/amdgpu/share/libdrm/amdgpu.ids: No such file or directory
11:27:43-872213 INFO     Torch backend: AMD ROCm HIP 5.4.22803-474e8620         
/home/pip/automatic/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:546: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
11:27:43-877477 INFO     Torch detected GPU: AMD Radeon Graphics VRAM 8176 Arch 
                         (10, 3) Cores 20                                       
11:27:43-878831 INFO     Verifying requirements                                 
11:27:43-892479 INFO     Installing packages                                    
11:27:43-896579 INFO     No changes detected: Quick launch active               
11:27:43-897325 INFO     Running extension preloading                           
11:27:43-897903 INFO     Server arguments: []                                   
No module 'xformers'. Proceeding without it.
11:27:47-119176 INFO     Libraries loaded                                                                                               
11:27:47-122886 INFO     Available VAEs: /home/pip/automatic/models/VAE 0                                                               
11:27:47-124005 INFO     Available models: /home/pip/automatic/models/Stable-diffusion 1                                                
11:27:47-849737 WARNING  Default checkpoint not found: model.ckpt                                                                                               
11:27:47-850593 WARNING  Loading fallback checkpoint: v1-5-pruned-emaonly.ckpt [cc6cb27103]                                                                     
11:27:48-030432 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16                                                     
Loading weights: models/Stable-diffusion/v1-5-pruned-emaonly.ckpt ━━╸━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.3/4.3 GB 0:00:00
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
11:27:49-571108 INFO     Model created from config: /home/pip/automatic/configs/v1-inference.yaml

### Version Platform Description

Cinnamon Mint 21.1

**Comment by vladmandic** [comment]
its stuck because its trying to move model weights to VRAM. and that doesn't work because GPU failed to initialize.
you can see that GPU is correctly detected (AMD Radeon Graphics VRAM 8176 Arch), but it fails to initialize:

> /home/pip/automatic/venv/lib/python3.10/site-packages/torch/cuda/init.py:546: UserWarning: Can't initialize NVML
warnings.warn("Can't initialize NVML")

I cannot help with that, that is faar below app layer. But typically that has to do with display drivers used.

**Comment by StDavisOfTheHolyC** [comment]
Aha, I see. That at least an idea of what's wrong. I'll see about figuring out how to solve that, thank you.

**Comment by vladmandic** [comment]
one thing that comes to mind is that ROCm is really bad about detecting capabilities of GPU, so sometimes you need to specify it manually via environment variable.
this repo by default uses `HSA_OVERRIDE_GFX_VERSION=10.3.0`, but you can google for what might be a correct value for your specific GPU and simply set it in shell before starting webui.

**Comment by vladmandic** [comment]
any updates?

**Comment by vladmandic** [comment]
closing as no updates, if new information is provided i'll reopen.
