### ISSUE TITLE
[Issue]: An issue with clip-interrogator-ext

### ISSUE THREAD

**Issue by mart-hill** [vladmandic/automatic#108]
### Issue Description

I noticed that this extension, now being built in (thanks!), throws a bit of a fit while trying to generate a prompt based on an image. I deliberately deleted the CLIP model from the BLIP folder, to check:

```
Loading CLIP Interrogator 0.5.4...
Downloading: "https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth" to X:\AI\automatic\models\BLIP\model_base_caption_capfilt_large.pth

100%|███████████████████████████████████████████████████████████████████████████| 855M/855M [00:20<00:00, 43.7MB/s]
load checkpoint from X:\AI\automatic\models\BLIP\model_base_caption_capfilt_large.pth
Loading CLIP model...
Loaded CLIP model and data in 8.24 seconds.
The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 0
The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 0
```
![image](https://user-images.githubusercontent.com/55754730/231827366-e4776aa5-213c-406b-a907-0a9de0d2f77e.png)

The analysis section works flawlessly:
![image](https://user-images.githubusercontent.com/55754730/231828183-3a912d5a-fb33-417d-af35-53208791c9fb.png)

I know, this extension has quite an issue with vanilla WebUI (I couldn't make it work after latest updates at all).

### Platform Description

Windows 10 22H2, RTX 3090

**Comment by mart-hill** [comment]
I have this set of CLIP models in "checkpoints" folder of the UI:
![image](https://user-images.githubusercontent.com/55754730/231829207-87039685-0df3-47dd-8a76-b72a176b511e.png)

Could that be an issue for the interrogator? Even though it uses just the **model_base_caption_capfilt_large** model inside "models/BLIP" folder?

**Comment by vladmandic** [comment]
I'll take a look...

**Comment by Woisek** [comment]
Add me in to this issue.

**Comment by vladmandic** [comment]
latest `transformers` library is causing issues, pinned to 4.26.1 and interrogator is now working.

**Comment by vladmandic** [comment]
> Interesting is that the Analyze tab is working at the same time, while Prompt isn't, is "Analyze" using a different "call"?

exactly.

**Comment by Melligos** [comment]
But why it closed? An issue is still here.

**Comment by vladmandic** [comment]
> But why it closed? An issue is still here.

what issue? the fact that clip interrogator does not work with newer transformers? that would be a feature request for clip interrogator extension, not an issue in this app. yes, please go to appropriate repo and create a request there.
