### ISSUE TITLE
[Feature]: Add generate button to image output frame

### ISSUE THREAD

**Issue by mobilehacker** [vladmandic/automatic#1080]
### Feature description

Hello! I mainly use SD on phone, and on mobile UI generate button is located on top of the page, and output image on the bottom. It would be really cool to have a second generate button, where the output frame is located. There are already buttons, like show, send to inpaint, etc.

### Version Platform Description

Version: 527dc0ee Thu May 18 19:46:11 2023 -0400
OS: Windows 11 22H2
Browser: Firefox 113.0.1

**Comment by vladmandic** [comment]
while this may be part of the new ui (still in planning), tracking explicit feature is not required at this time, so closing.
