### ISSUE TITLE
[Feature]: confirmation when clicking on "Restore Defaults"

### ISSUE THREAD

**Issue by cjps-br** [vladmandic/automatic#1081]
### Feature description

I accidentally activated the "Restore Defaults" button in the settings tab and lost my settings, including extensions that I created myself and from third parties, as well as returning to generating black images when triggering the generation of images. I then implemented a command in the batch file that triggers the webui to make a copy of the config.json and config-ui.json files. So, I would like to make a suggestion that there be a confirmation when pressing this button or that it has its position repositioned in the line of buttons. He could be the last to appear.

**Comment by vladmandic** [comment]
extensions are NOT lost, only settings. but ok, i can move the button more to the right.

**Comment by cjps-br** [comment]
I expressed myself badly: it was really the extensions settings that were lost, not the extensions themselves!! grateful!
