### ISSUE TITLE
[Feature]: Automatic model move on error

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#1082]
### Feature description

Downloading as many models as a I do, I occasionally cut and paste one into the wrong directory. Loras into the embeddings folder, vice versa, that kinda thing.

When you do that it spits out errors to the console:

13:04:37-023045 ERROR    embedding load Card1-10.safetensors: AssertionError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ D:\AI\SD\automatic\modules\textual_inversion\textual_inversion.py:204 in load_from_dir                               ││                                                                                                                      ││   203 │   │   │   │   │                                                                                              ││ ❱ 204 │   │   │   │   │   self.load_from_file(fullfn, fn)                                                            ││   205 │   │   │   │   except Exception as e:                                                                         ││                                                                                                                      ││ D:\AI\SD\automatic\modules\textual_inversion\textual_inversion.py:170 in load_from_file                              ││                                                                                                                      ││   169 │   │   elif type(data) == dict and type(next(iter(data.values()))) == torch.Tensor:                           ││ ❱ 170 │   │   │   assert len(data.keys()) == 1, 'embedding file has multiple terms in it'                            ││   171                                                                                                                │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯AssertionError: embedding file has multiple terms in it
13:04:40-255980 ERROR    embedding load water02.pt: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ D:\AI\SD\automatic\modules\textual_inversion\textual_inversion.py:204 in load_from_dir                               ││                                                                                                                      ││   203 │   │   │   │   │                                                                                              ││ ❱ 204 │   │   │   │   │   self.load_from_file(fullfn, fn)                                                            ││   205 │   │   │   │   except Exception as e:                                                                         ││                                                                                                                      ││ D:\AI\SD\automatic\modules\textual_inversion\textual_inversion.py:162 in load_from_file                              ││                                                                                                                      ││   161 │   │   # textual inversion embeddings                                                                         ││ ❱ 162 │   │   if 'string_to_param' in data:                                                                          ││   163 │   │   │   param_dict = data['string_to_param']                                                               ││                                                                                                                      ││ D:\AI\SD\automatic\venv\lib\site-packages\torch\_tensor.py:999 in __contains__                                       ││                                                                                                                      ││    998 │   │                                                                                                         ││ ❱  999 │   │   raise RuntimeError(                                                                                   ││   1000 │   │   │   "Tensor.__contains__ only supports Tensor or scalar, but you passed in a %s.                      │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯RuntimeError: Tensor.__contains__ only supports Tensor or scalar, but you passed in a <class 'str'>.

My thought was to have a checkbox in the settings somewhere, or have it as a default, to move the file to the appropriate location as per your path setup rather than just report the error and have the user go look for it and do it manually. In fact, you could maybe even extend this to having a single folder you dump files into and it would sort them for you, I'm sure people would appreciate that as a time-saving feature. 

### Version Platform Description

Always the newest, Win10, FireFox

**Comment by vladmandic** [comment]
i really don't want to go into business of auto-detecteting what type of a model it is and especially automatically moving anything to "correct" folders.
what i can do is make those errors much more user friendly - i'm starting with this one.

**Comment by Aptronymist** [comment]
> i really don't want to go into business of auto-detecteting what type of a model it is and especially automatically moving anything to "correct" folders. what i can do is make those errors much more user friendly - i'm starting with this one.

That works too, I just figured why not turn an error message into a feature. Thanks.

**Comment by vladmandic** [comment]
take an example above - all i know is that embedding parsing failed - i have no idea what it actually is unless try to load it as model & lora & lyco & hypernetwork & whatever else exists. and there is no way to load "header" of model and try to auto-detect - i'd have to actually try to load it as anything and that would be a nightmare.

**Comment by Aptronymist** [comment]
> take an example above - all i know is that embedding parsing failed - i have no idea what it actually is unless try to load it as model & lora & lyco & hypernetwork & whatever else exists. and there is no way to load "header" of model and try to auto-detect - i'd have to actually try to load it as anything and that would be a nightmare.

Ahhh... I see, I didn't know that was the only way to do it. Interesting, thanks for explaining. I'll look around for a way to handle it.
