### ISSUE TITLE
[Feature]: Custom path to model-folder

### ISSUE THREAD

**Issue by horribleCodes** [vladmandic/automatic#1094]
### Feature description

As it is now, it's possible to reassign each and every directory of the different models, such as SD, LoRa, ControlNet and so on - but I'd rather just specify a root path of the model directory that contains each type of model as a subdirectory, unless specified.
I previously used a symbolic link to redirect with the default settings, but that solution can conflict with git operations.
The output paths already support this feature, so it'd be nice to have it work for models as well - it would make support for extensions that use different types of models easier, too.

**Comment by vladmandic** [comment]
you have `--models-dir <folder_name>` command line flag for that.
