### ISSUE TITLE
[Issue]: Strange warning

### ISSUE THREAD

**Issue by afbagwell** [vladmandic/automatic#1096]
### Issue Description

I let my system run overnight. The session completed, but when I looked this morning the UI preview window didn't show the usual grid with individual images to select. Instead it was frozen on a view of the last batch and stuck on displaying the "Stop/Skip" button.

Looking at the console, the final message was:
`01:20:02-316705 WARNING  Maximum image size exceded: size=(23040, 15360) maximum=200 MPixels`

It would be cool if I could make images that large, but this run wasn't so ambitious! Here's the parameters I used:

Steps: 25, Sampler: DPM++ 2M Karras, CFG scale: 8, Face restoration: CodeFormer, Size: 768x512, Model hash: a60cfaa90d, Model: Dreamshaper_v5_BakedVae, VAE: vae-ft-mse-840000-ema-pruned, Denoising strength: 0.33, Clip skip: 1, Version: 4c4e147, Hires upscale: 1.5, Hires upscaler: 4x_foolhardy_Remacri

I ran this 100 times with a batch size of 4. I've done this same kind of run on many occasions and never seen this warning message until now.

I'm guessing it failed on generating the final image grid.

### Version Platform Description

Windows 11, Firefox 113.0.1 (64-bit)
Version: 4c4e147

**Comment by vladmandic** [comment]
those dimensions imply you've tried to run 30x30 grid. so if you have batch size 4, that means you had high batch count as well? or you used xyz grid.

in either case, its a valid warning since creating such a large image grid uses a lot of memory and can cause a memory bomb. you can increase limit in settings.

but yeah, it should not get frozen when it reaches that condition, i'll take a look at that.

**Comment by afbagwell** [comment]
It generated a total of 400 images. Batch count: 100, Batch size: 4. No X/Y/Z plotting. Wasn't sure if this was really a bug or not as I've run this count/batch/dimensions combo many times in the past but never seen it bomb/freeze at the end like this.

Thanks!

**Comment by vladmandic** [comment]
100 x 4 x 768 x 512 x 2 (interim plus generated) x 4 (32bit) = 1.3GB of RAM.
sure, if you have enough RAM, increase default limit.
yes, it should not freeze, but warning is there for a good reason.
previously it was only in xyz grid, but i've moved it to general image processing.

**Comment by afbagwell** [comment]
Got it. 👍 

For reference, I also had my grids saving as JPG at 85% image quality if anyone else is wondering how they contributed to the final image size.

**Comment by vladmandic** [comment]
that doesn't matter, what matters is raw image held in memory before its converted to png or jpg or whatever.
i'll push a fix to prevent freeze soon. it should also just skip such image and continue processing of the rest (so in your case, you'd have a warning that grid was not saved, but everything else would work).

**Comment by vladmandic** [comment]
ok, i've pushed the update, should be addressed.
