### ISSUE TITLE
[Issue]: Many Install Errors

### ISSUE THREAD

**Issue by SoLoVision** [vladmandic/automatic#1098]
### Issue Description

When attempting to install, I get a lot of errors. Below is the log. It seems as if none of the dependencies are installing via pip.

1. This is a clean windows install
2. I installed python 3.10.9
3. Installed latest GIT
4. installed Nvidia Cuda
5. clone repository
6. ran winui.bat

Using VENV: C:\Users\jerem\AI_Projects\Vlad1111\automatic\venv
13:43:28-130697 INFO     Starting SD.Next
13:43:28-130697 INFO     Python 3.10.9 on Windows
13:43:28-232636 INFO     Version: e59ebe25 Sat May 20 10:33:31 2023 -0400
13:43:28-643231 INFO     Latest published version: b6289d56c744ae9d0d16aaa1f503f0ea2ff76ec1 2023-05-20T17:36:27Z
13:43:28-649088 INFO     Setting environment tuning
13:43:28-649088 INFO     nVidia CUDA toolkit detected
C:\Users\jerem\AI_Projects\Vlad1111\automatic\venv\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\jerem\AI_Projects\Vlad1111\automatic\venv\lib\site-packages\numpy\.libs\libopenblas.FB5AE2TYXYH2IJRDKGDGQ3XBKLKTF43H.gfortran-win_amd64.dll
C:\Users\jerem\AI_Projects\Vlad1111\automatic\venv\lib\site-packages\numpy\.libs\libopenblas64__v0.3.21-gcc_10_3_0.dll
  warnings.warn("loaded more than 1 DLL from .libs:"
13:43:47-810681 INFO     Torch 2.0.1+cu118
13:43:47-835657 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
13:43:47-839196 INFO     Torch detected GPU: NVIDIA GeForce RTX 2080 Ti VRAM 11264 Arch (7, 5) Cores 68
13:43:47-843189 INFO     Installing package: tensorflow==2.12.0
13:43:57-154048 INFO     Verifying requirements
13:43:57-166035 INFO     Installing package: blendmodes
13:43:59-309650 ERROR    Error running pip: install --upgrade blendmodes
13:43:59-314645 INFO     Installing package: clean-fid
13:44:02-397603 ERROR    Error running pip: install --upgrade clean-fid
13:44:02-403597 INFO     Installing package: facexlib
13:44:08-136732 ERROR    Error running pip: install --upgrade facexlib
13:44:08-142740 INFO     Installing package: gfpgan
13:44:17-034754 ERROR    Error running pip: install --upgrade gfpgan
13:44:17-043744 INFO     Installing package: lpips
13:44:20-096183 ERROR    Error running pip: install --upgrade lpips
13:44:20-103204 INFO     Installing package: open-clip-torch
13:44:22-963696 ERROR    Error running pip: install --upgrade open-clip-torch
13:44:22-966693 INFO     Installing package: opencv-contrib-python
13:44:26-111329 ERROR    Error running pip: install --upgrade opencv-contrib-python
13:44:26-120357 INFO     Installing package: realesrgan
13:44:35-222641 ERROR    Error running pip: install --upgrade realesrgan
13:44:35-238265 INFO     Installing package: scipy
13:44:38-208851 ERROR    Error running pip: install --upgrade scipy
13:44:38-208851 INFO     Installing package: tb_nightly
13:44:42-304260 ERROR    Error running pip: install --upgrade tb_nightly
13:44:42-319884 INFO     Installing package: torchdiffeq
13:44:45-336436 ERROR    Error running pip: install --upgrade torchdiffeq
13:44:45-336436 INFO     Installing package: torchsde
13:44:48-323376 ERROR    Error running pip: install --upgrade torchsde
13:44:48-323376 INFO     Installing package: scikit-image
13:44:52-555417 ERROR    Error running pip: install --upgrade scikit-image
13:44:52-559450 INFO     Installing package: basicsr
13:44:59-852464 ERROR    Error running pip: install --upgrade basicsr
13:44:59-857482 INFO     Installing package: compel
13:45:04-216393 ERROR    Error running pip: install --upgrade compel
13:45:04-224415 INFO     Installing package: accelerate==0.18.0
13:45:06-390272 ERROR    Error running pip: install --upgrade accelerate==0.18.0
13:45:06-396291 INFO     Installing package: opencv-python==4.7.0.72
13:45:09-155638 ERROR    Error running pip: install --upgrade opencv-python==4.7.0.72
13:45:09-160921 INFO     Installing package: diffusers==0.16.1
13:45:11-934133 ERROR    Error running pip: install --upgrade diffusers==0.16.1
13:45:11-941125 INFO     Installing package: gradio==3.31.0
13:45:17-099094 ERROR    Error running pip: install --upgrade gradio==3.31.0
13:45:17-104086 INFO     Installing package: numexpr==2.8.4
13:45:19-287849 ERROR    Error running pip: install --upgrade numexpr==2.8.4
13:45:19-291842 INFO     Installing package: numpy==1.24.3
13:45:21-433251 ERROR    Error running pip: install --upgrade numpy==1.24.3
13:45:21-437248 INFO     Installing package: numba==0.57.0
13:45:24-244965 ERROR    Error running pip: install --upgrade numba==0.57.0
13:45:24-249151 INFO     Installing package: pandas==1.5.3
13:45:26-641274 ERROR    Error running pip: install --upgrade pandas==1.5.3
13:45:26-648267 INFO     Installing package: pytorch_lightning==1.9.4
13:45:29-460192 ERROR    Error running pip: install --upgrade pytorch_lightning==1.9.4
13:45:29-466187 INFO     Installing package: transformers==4.26.1
13:45:33-079735 ERROR    Error running pip: install --upgrade transformers==4.26.1
13:45:33-086730 INFO     Installing package: timm==0.6.13
13:45:35-507538 ERROR    Error running pip: install --upgrade timm==0.6.13
13:45:35-514495 INFO     Installing package: onnxruntime==1.14.0
13:45:37-762936 ERROR    Error running pip: install --upgrade onnxruntime==1.14.0
13:45:37-767931 INFO     Installing packages
13:45:37-770928 INFO     Installing package:
                         git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
13:45:44-370061 ERROR    Error running pip: install --upgrade
                         git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
13:45:44-446004 INFO     Running setup
13:45:44-447979 INFO     Installing repositories
13:45:44-682848 INFO     Installing submodules
13:45:47-979437 INFO     Updating submodules
13:46:00-448027 ERROR    Error running extension installer:
                         C:\Users\jerem\AI_Projects\Vlad1111\automatic\extensions-builtin\clip-interrogator-ext\install
                         .py
13:46:16-882863 ERROR    Error running extension installer:
                         C:\Users\jerem\AI_Projects\Vlad1111\automatic\extensions-builtin\stable-diffusion-webui-rembg\
                         install.py
13:46:17-126637 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-system-info', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
13:46:17-136638 INFO     Updating Wiki
13:46:17-753798 WARNING  Setup complete with errors: 30
13:46:17-758762 WARNING  See log file for more details: setup.log
13:46:17-766752 INFO     Running extension preloading
13:46:17-774745 INFO     Server arguments: []
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\jerem\AI_Projects\Vlad1111\automatic\launch.py:144 in <module>                                             │
│                                                                                                                     │
│   143                                                                                                               │
│ > 144     instance = start_server(immediate=True, server=None)                                                      │
│   145     while True:                                                                                               │
│                                                                                                                     │
│ C:\Users\jerem\AI_Projects\Vlad1111\automatic\launch.py:116 in start_server                                         │
│                                                                                                                     │
│   115     server = importlib.util.module_from_spec(module_spec)                                                     │
│ > 116     module_spec.loader.exec_module(server)                                                                    │
│   117     if args.test:                                                                                             │
│ in exec_module:883                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ C:\Users\jerem\AI_Projects\Vlad1111\automatic\webui.py:19 in <module>                                               │
│                                                                                                                     │
│    18 import torchvision # pylint: disable=W0611,C0411                                                              │
│ >  19 import pytorch_lightning # pytorch_lightning should be imported after torch, but it re-e                      │
│    20 if ".dev" in torch.__version__ or "+git" in torch.__version__:                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'pytorch_lightning'
Press any key to continue . . .

### Version Platform Description

python 3.10.9
Windows 11

**Comment by vladmandic** [comment]
Check what it says first before posting console log:

```log
13:46:17-753798 WARNING Setup complete with errors: 30
13:46:17-758762 WARNING See log file for more details: setup.log
```

It seems that it's not "a lot of errors", it seems that install cannot install pretty much anything.

**Comment by SoLoVision** [comment]
I'm sorry for not translating correctly. I realize that the install could not install pretty much anything, I was considering that as the "errors". As I said in the original post, I pretty much went straight through the setup process, which seems to be straight forward. Any idea why most of my packages are not installing? I haven't messed with the requirement.txt file. 

I am really not here to upset anyone, especially the dev that put in all the hard work.  So if I am just too dumb for this, I get it and you can just ignore me. I am no programmer, but I have had success with projects like this in the past so I thought this would be a really cool to try.

If anyone does want to give a hand, here is my system log. 
[](https://pastebin.com/NaKGEhCh)

**Comment by vladmandic** [comment]
You don't have to be a programmer - for the second time:

`WARNING See log file for more details: setup.log`

**Comment by SoLoVision** [comment]
Sorry, I thought I had the log linked in my reply. Here is the log. 

https://pastebin.com/NaKGEhCh

**Comment by SoLoVision** [comment]
I see in the logs, permission issues. I tried running cmd as administrator, that did not help. It is worth noting that I can install all of these requirements directly using pip. It is jsut when the script runs and it creates a venv (I believe), is when I get the permission errors.

**Comment by vladmandic** [comment]
I don't want to download your log - it's really up to you to find first relevant error and post here.

**Comment by SoLoVision** [comment]
I understand. I apologize for wasting your time. I appreciate the time and effort you put into this project.  I hope you enjoy the rest of your weekend!

**Comment by vladmandic** [comment]
your `venv` is corrupt, delete it and start again.

> ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: > 'C:\\Users\\jerem\\AI_Projects\\Vlad1111\\automatic\\venv\\Lib\\site-packages\\numpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll'

**Comment by SoLoVision** [comment]
That did it! Thank you! I do apologize for how my original post may have come off.
