### ISSUE TITLE
[Issue]: getting black images on generation

### ISSUE THREAD

**Issue by cjps-br** [vladmandic/automatic#1099]
### Issue Description

I updated to commit b6289d5 and started getting black images in the generated images. I haven't made any changes to the cuda parameters from what they were before I updated the commit

I went back to commit e59ebe2 and the images are being generated properly.

### Version Platform Description

Platform:
arch: AMD64
cpu: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.6

Torch
2.0.0+cu118 Full  nohalf

GPU
device: NVIDIA GeForce GTX 1660 SUPER (1) (compute_37) (7, 5)
cuda: 11.8
cudnn: 8700

**Comment by vladmandic** [comment]
diff between latest and last known commit you say is fine is tiny: <https://github.com/vladmandic/automatic/compare/e59ebe25..b6289d5>

only minor change that i see that might have impact is in `installer.py`: `os.environ.setdefault('USE_TORCH', '1')`
can you try changing that value to 0 and try again?

**Comment by cjps-br** [comment]
Before seeing your suggestion, I did another test:
I did a GIT pull for the last commit and changed the "Device precision type" parameter to FP16 (I was using FP32). with this parameter the images were generated again.

grateful for the attention!! Your work is being incredible and I really liked this fork. It has greatly reduced memory consumption compared to the SD1111 environment
