### ISSUE TITLE
[Issue]: Extensions tab not sorting by "default" on load

### ISSUE THREAD

**Issue by mark-wd** [vladmandic/automatic#1100]
### Issue Description

In my setup, when I first click the Extensions tab, it is not sorted using "dafult". By clicking on the relevant box and choosing "default" it then applies the sort.

Maybe introudce an extra check to the code?

### Version Platform Description

2023-05-18
hash: 527dc0ee

**Comment by vladmandic** [comment]
fixed in dev, will publish update in ~2h.
