### ISSUE TITLE
[Issue]: Low Performance RTX 4090

### ISSUE THREAD

**Issue by xSemi** [vladmandic/automatic#1103]
### Issue Description

Reinstalled Automatic because gotting poor performance still getting Realy bad performance of 1-7it/s with a 4090 .
Tryed Reinstalling didnt Change the issue.
also no Change if 1 Img or 10er Batch is processing.
[setup.log](https://github.com/vladmandic/automatic/files/11523638/setup.log)

Made Benchmark with the Extention its Uploaded under ID 3956

### Version Platform Description

Version: b6289d56 Sat May 20 13:36:27 2023 -0400
Chrome
W11
RTX4090

**Comment by 1r00t** [comment]
Have you tried setting `Device precision type` to `BF16`,
and `Cross-attention optimization method` to `Scaled-Dot-Product` in the settings?
And don't use xformers with SDP.

**Comment by xSemi** [comment]
Tryed Deleteing Config and the BF16 setting Scaled -dot was Default
got Some Performance boost with normal SD1.5 model but still missing power

<html>
<body>


2023-05-21 12:31:41.865331 | 10.39 / 18.45 / 30.27 | updated:2023-05-20 hash:b6289d56 url:https://github.com/vladmandic/automatic/tree/master | arch:AMD64 cpu:AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system:Windows release:Windows-10-10.0.22621-SP0 python:3.10.6 | torch:2.0.1+cu118 Autocast half xformers:unavailable accelerate:0.18.0 transformers:4.26.1 | device:NVIDIA GeForce RTX 4090 (1) (compute_37) (8, 9) cuda:11.8 cudnn:8901 24GB | sdp none | v1-5-pruned-emaonly.safetensors [6ce0161689] | semix |   | 2e7efe
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --



</body>
</html>

**Comment by vladmandic** [comment]
@xSemi your benchmark data is **vastly different** than what you reported when you created the issue.
you said you're getting:

> 1-7 it/s 
you're getting 10 it/s minimum

> no Change if 1 Img or 10er Batch
you're getting 10 with batch size 1 and 30 with batch size 4 - that is massive difference and exactly as expected.

so what's left is *performance tuning*, not actual issue. what you noted was alarming. what you reported is below average, but not alarming.

i'll close the issue as its no longer an issue, but as a general advice what you can try:
- try disabling some extensions (even built-in extensions) as they do have some overhead before/after generate even if they are no used.
- try disabling gc in settings.
- monitor gpu clocks using your gpu utility and see if your gpu is fully boosting
- from cpu signature, thats a ryzen 5800x? that cpu will not be able to fully saturate a massive gpu such as 4090 so you'll always be slightly below best possible results for 4090
