### ISSUE TITLE
[Issue]: Saving files to subdirectories is broken

### ISSUE THREAD

**Issue by TeutonJon78** [vladmandic/automatic#1118]
### Issue Description

Saving files to a directory is broken for images and grids. Verified in --safe mode. It was working earlier in the day before I did a clean reinstall.

Commit d647bb5c052277ec48d5c1858a52d4b6de30e8f1 broke saving images to directories in modules/images.py

By removing the second if statement about save_to_dirs and turning it into an else, it will hit code regardless of true or false (which means it's ignoring the settings).

The behavior has also prevented it from making any subdirectories (such as [date]) to save images in.

### Version Platform Description

21:04:06-648942 INFO     Starting SD.Next
21:04:06-661945 INFO     Python 3.10.11 on Windows
21:04:06-749965 INFO     Version: d647bb5c Sun May 21 18:49:05 2023 -0400
21:04:07-143226 INFO     Setting environment tuning
21:04:07-144227 INFO     Using DirectML Backend
21:04:09-079186 INFO     Torch 2.0.0+cpu
21:04:09-091189 INFO     Torch backend: DirectML (torch-directml 0.2.0.dev230426)
21:04:09-202582 INFO     Torch detected GPU: Radeon RX 580 Series

Broswer: Firefox

**Comment by Woisek** [comment]
Can confirm that entries in **Directory name pattern** is ignored and no sub directory saving is done.

**Comment by Tillerz** [comment]
Me three. Whatever you set, on or off for the "When using "Save" button, save images to a subdirectory" toggle, it uses the entry.

**Comment by vladmandic** [comment]
fixed.
