### ISSUE TITLE
[Feature]: folder filter improvements and open file folder option

### ISSUE THREAD

**Issue by Ratinod** [vladmandic/automatic#1124]
### Feature description

I would like the ability to customize the display controls of the quick filter buttons. If you store data in a certain way, then this space starts to take up a lot of space.

3 options:
 - "off" (no changes)
 - "hide folders without main files" (without .safetensors or .pt or...)
 - "hide folders without main files and folders with only 1 main file"
 
see attached image:
![better_folders](https://github.com/vladmandic/automatic/assets/12137233/104cefeb-6e5d-4c0f-bdd6-a034163f6dd2)

\+ add an option to be able to quickly open a folder with a selected file in the file manager

### Version Platform Description

\-

**Comment by Ratinod** [comment]
How to hide\show all lora folder buttons:

create 2 bookmarks in the browser
name: `SD_hide_dirs`
url: `javascript:(function(){document.getElementById("txt2img_lora_subdirs").style.display = 'none';})();`
and
name: `SD_show_dirs`
url: `javascript:(function(){document.getElementById("txt2img_lora_subdirs").style.display = 'block';})();`

Maybe it will be useful for someone too...

**Comment by vladmandic** [comment]
extra networks are now sorted depth-first and will not display folders without valid models in them.

**Comment by Ratinod** [comment]
Great! 
But there are problems.
1. Now the Top directories are completely gone. This is bad, because it is impossible, for example, to select the display of everything ONLY from "STYLE" or ONLY from "TOOLS".
- "hide folders without main files" means that if the folder contains a folder with a main file, then it should be displayed ("2" in image) (tree hierarchy)

2. Still impossible to do as "3" in image  "hide folders without main files and folders with only 1 main file" 
- What's the point of showing a filter for a folder with only 1 file? Much better to choose the previous catalog filter.
- "3" in image is the most compact and functional option. I would like this implementation.

I apologize for not describing everything in greater detail. I thought the concept embodied in the picture would be more clear and understandable.

**Comment by vladmandic** [comment]
I understand what you're saying. On the other hand current design of extra networks is really bad internally, I don't want to spend time on minor improvements to it. I hope to do a full rewrite sometime in the near future.

**Comment by Ratinod** [comment]
> I understand what you're saying. On the other hand current design of extra networks is really bad internally, I don't want to spend time on minor improvements to it. I hope to do a full rewrite sometime in the near future.

I understand. I tried to find where the files responsible for all this and could not find. 
At least quick filter buttons can be completely removed as I wrote above and filtered by prescribing manually. 
In any case, thanks for trying. :)
