### ISSUE TITLE
[Feature]: Support HAT upscaler

### ISSUE THREAD

**Issue by r7vz9h3** [vladmandic/automatic#1131]
### Feature description

HAT seems to be one of the best upscalers available right now, but it's not supported yet.

Model repo:
https://github.com/XPixelGroup/HAT

ComfyUI supports it:
https://github.com/comfyanonymous/ComfyUI/blob/master/comfy_extras/chainner_models/architecture/HAT.py

Similar request is open here:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5614

**Comment by vladmandic** [comment]
done!
https://github.com/vladmandic/sd-extension-chainner
