### ISSUE TITLE
[Feature]: Use of a1111-sd-webui-lycoris to act as standard lora/lycoris handler

### ISSUE THREAD

**Issue by TheOnlyHolyMoly** [vladmandic/automatic#1132]
### Feature description

Preface: Built-in lora extension is currently incapable of handling many new lora formats. Lycoris extension is capable of handling such formats very well. 

Goal:  Enabling webui to use a1111-sd-webui-lycoris extension as default lora and lycoris handler

Prerequisites:  (related enhancement request: https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/issues/34)
Lycoris Extension is patched to 
- [ ] to evaluate flag if flag exists and if flag=true
- [ ] if flag is true, then handle also lora files 

Need for patch of webui
- [ ] Have explicit managable flag in settings "Use Lycoris extension also to handle lora"  @vladmandic @KohakuBlueleaf  please align on specs of this flag. config.json?
- [ ] Behaviour: If flag is found and  set to "true", webui will use Lycoris extension as default handler for both lycoris and lora files

**Comment by vladmandic** [comment]
will keep feature request open here for tracking purposes only, but actual work is done upstream.

**Comment by vladmandic** [comment]
implemented, but disabled by default, needs to be enabled by user.
