### ISSUE TITLE
[Feature]: Default Codeformer and GFPGAN values

### ISSUE THREAD

**Issue by HarrisTerry** [vladmandic/automatic#1133]
### Feature description

As someone making a wide variety of photos as well as art, I can tell you GFPGAN seems to be best for art, Codeformer for photorealism, and sometimes together.

At the moment, IIRL Codeformer is default on visibility 1. I think these should both be off and CF weight at minimum at first on tabs, unless there is a reason for this. Also, I almost never use a visibility of 1, always much less.

Just my 2 cents, not sure how others feel.

### Version Platform Description

Win11, 64GB RAM, 3070ti, 12700k 5GHZ

**Comment by vladmandic** [comment]
fair, i'll set default visibility to 0 in the next version.
