### ISSUE TITLE
[Issue]: 1-click metadata restoration issue

### ISSUE THREAD

**Issue by whythisusername** [vladmandic/automatic#1134]
### Issue Description

I encountered a problem restoring generation parameters in t2i tab with "read generation parameters" button under the big "Generate" one.  This also happens when im trying to restore generation params from "process image" tab, it throws the same error log in console:
```
Traceback (most recent call last):
  File "B:\progs\SD\vladmandic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "B:\progs\SD\vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "B:\progs\SD\vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "B:\progs\SD\vladmandic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "B:\progs\SD\vladmandic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "B:\progs\SD\vladmandic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "B:\progs\SD\vladmandic\modules\generation_parameters_copypaste.py", line 363, in paste_func
    params = parse_generation_parameters(prompt)
  File "B:\progs\SD\vladmandic\modules\generation_parameters_copypaste.py", line 260, in parse_generation_parameters
    v = v[1:-1] if v[0] == '"' and v[-1] == '"' else v
IndexError: string index out of range
```

In order to test it properly i have already moved all non built-in extensions to another folder, pulled the latest version and launched the UI with `launch.py --upgrade`. Launching with `--safe` argument didn't fixed it either.
What can cause this problem?

### Version Platform Description

- Version: beff89ba Mon May 22 15:27:20 2023 -0400
- Windows 10 20H2
- Python 3.10.6
- Either firefox 112 or chromium 104

**Comment by vladmandic** [comment]
you're doing read generation info from what? i'm guessing there is a parser issue, so i'd need to know what is the source?
if its image, please upload (here or somewhere else), if its text, paste it.

**Comment by whythisusername** [comment]
I think i have found the root of this problem, it's because of the xformers 0.0.19 version, just wanted to use it for deterministic outputs and run `pip install xformers==0.0.19` yesterday. Seems like its ruining the metadata somehow. Everything working fine with default 0.0.17 version.
Here is the images [this one](https://files.catbox.moe/lkgg1b.png) generated with 0.0.19 version and [this ](https://files.catbox.moe/cbs11b.png)with 0.0.17

**Comment by vladmandic** [comment]
xformers 0.0.18 have a known issue, i guess there are even more problems in 0.0.19.
xformers 0.0.17 are automatically installed first time you restart server once xformers are selected as cross-optimization method, you don't need to install them manually. and there is already option to select deterministic mode for xformers.

**Comment by whythisusername** [comment]
> and there is already option to select deterministic mode for xformers

Didn't know that, but where can i find that option for deterministic mode?

**Comment by vladmandic** [comment]
settings -> stable diffusion -> cross-attention advanced options -> xFormers enable flash Attention

**Comment by whythisusername** [comment]
Doesn't seem to work well, still can't generate the exact same image without minor changes as with later version of xformers. 
Is there any way to repeat image using xformers and dont install anything that could break something?

**Comment by vladmandic** [comment]
regarding metadata parsing, i'll fix that as regardless of currupt or not, exception should not happen. the rest, i don't know. i really don't use xformers anymore for a while now.

**Comment by whythisusername** [comment]
Thanks for the fix. Its working fine now on the latest version even with 0.0.19 xformers

**Comment by jmp909** [comment]
@vladmandic for me, metadata stored in PNGs from automatic1111 copies over to the "From Text" screen ok,  but metadata stored in JPGs output by your app gives that error

`if v[0] == '"' and v[-1] == '"':` 
`IndexError: string index out of range`

hope that's useful

**Comment by vladmandic** [comment]
Can you upload one such image that leads into this problem?

**Comment by jmp909** [comment]
here's the metadata in the comments. you can see it's different

i just typed "a" in the positive, and "b" in the negative

I'm trying to work out if there's a specific extension causing the difference

**broken.jpg**
```
a
Negative prompt: b
Version: aa62f6d, Pipeline: Original, Steps: 20, Seed: 581417225, Sampler: UniPC, CFG scale: 6, Size: 512x512, Parser: Full parser, Model: Realistic_Vision_V4.0_fp16-no-ema, Model hash: a43f2e8708, Operations:
```

**working.jpg**
```
a
Negative prompt: b
Steps: 20, Seed: 581417225, Sampler: UniPC, CFG scale: 6, Size: 512x512, Parser: Full parser, Model: Realistic_Vision_V4.0_fp16-no-ema, Model hash: a43f2e8708, Version: 02fe616, Pipeline: Original, Operations: txt2img
```
![broken](https://github.com/vladmandic/automatic/assets/2184982/4f5001b6-1e5d-469e-aba2-4d31f0515e6a)
![working](https://github.com/vladmandic/automatic/assets/2184982/c009104b-1f4e-494b-a72d-6761f9d040b7)

**Comment by vladmandic** [comment]
fixed.

**Comment by jmp909** [comment]
@vladmandic great thanks, they now work for me
