### ISSUE TITLE
[Issue]: Default Model will not unload from Vram

### ISSUE THREAD

**Issue by Mindset-Official** [vladmandic/automatic#1137]
### Issue Description

Basically the default model remains in vram whenever loading a new model.  Using the settings tab to unload checkpoint gives the message that it is removed but vram stays allocated and the model will load again taking up double vram.  Subsequent Models can be unloaded, but only the default seems to stay.  This does not happen on 554f26296e0045db78f86e97ffee60805c93fc9a which I believe is the commit right before the major update.  

Steps to reproduce 

Startup webui and try to unload model, vram will stay allocated.  Or load a new model and it will load on top of the older version and double the vram.  

Sorry for any errors reporting, this is my first time doing so on github.

### Version Platform Description

Version: beff89ba Mon May 22 15:27:20 2023 -0400 

Ubuntu 22.04
Intel Arc a750 --use-ipex
Firefox
Torch 1.13.0a0+gitb1dde16

**Comment by vladmandic** [comment]
run with `--debug` flag as it will print ram and vram statistics on each stage of model load and post log here.
also make sure you're not talking about default torch vram allocation which comes up to nearly 1gb even if everything is unloaded (as long as torch is active).

**Comment by Mindset-Official** [comment]
11:28:31-270620 INFO     Available models:                                      
                         /home/aaron/automatic/models/Stable-diffusion 25       
11:28:31-974367 DEBUG    Load model: info=False dict=False                      
11:28:31-975134 DEBUG    Select checkpoint:                                     
                         Realistic_Vision_V2.0-fp16-no-ema.safetensors          
                         [c0d1994c73]                                           
11:28:31-975748 DEBUG    Verifying Torch settings                               
11:28:32-998985 DEBUG    Torch FP16 test passed                                 
11:28:32-999801 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False     
                         no-half-vae=False upscast=True                         
11:28:33-000527 INFO     Setting Torch parameters: dtype=torch.float16          
                         vae=torch.float16 unet=torch.float16                   
11:28:33-001150 DEBUG    Torch default device: xpu                              
Loading weights: /home/aaron/automatic/models/Stable-diffusion/Realistic_Visio… 
11:28:33-162843 DEBUG    Model dict loaded: {'ram': {'used': 1.28, 'total':     
                         15.55}, 'gpu': {'used': 0.0, 'total': 7.54}, 'retries':
                         0, 'oom': 0}                                           
11:28:33-172526 DEBUG    Model config loaded: {'ram': {'used': 1.28, 'total':   
                         15.55}, 'gpu': {'used': 0.0, 'total': 7.54}, 'retries':
                         0, 'oom': 0}                                           
11:28:33-173437 DEBUG    Model config: {'linear_start': 0.00085, 'linear_end':  
                         0.012, 'num_timesteps_cond': 1, 'log_every_t': 200,    
                         'timesteps': 1000, 'first_stage_key': 'jpg',           
                         'cond_stage_key': 'txt', 'image_size': 64, 'channels': 
                         4, 'cond_stage_trainable': False, 'conditioning_key':  
                         'crossattn', 'monitor': 'val/loss_simple_ema',         
                         'scale_factor': 0.18215, 'use_ema': False,             
                         'scheduler_config': {'target':                         
                         'ldm.lr_scheduler.LambdaLinearScheduler', 'params':    
                         {'warm_up_steps': [10000], 'cycle_lengths':            
                         [10000000000000], 'f_start': [1e-06], 'f_max': [1.0],  
                         'f_min': [1.0]}}, 'unet_config': {'target':            
                         'ldm.modules.diffusionmodules.openaimodel.UNetModel',  
                         'params': {'image_size': 32, 'in_channels': 4,         
                         'out_channels': 4, 'model_channels': 320,              
                         'attention_resolutions': [4, 2, 1], 'num_res_blocks':  
                         2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8,       
                         'use_spatial_transformer': True, 'transformer_depth':  
                         1, 'context_dim': 768, 'use_checkpoint': True,         
                         'legacy': False, 'use_fp16': True}},                   
                         'first_stage_config': {'target':                       
                         'ldm.models.autoencoder.AutoencoderKL', 'params':      
                         {'embed_dim': 4, 'monitor': 'val/rec_loss', 'ddconfig':
                         {'double_z': True, 'z_channels': 4, 'resolution': 256, 
                         'in_channels': 3, 'out_ch': 3, 'ch': 128, 'ch_mult':   
                         [1, 2, 4, 4], 'num_res_blocks': 2, 'attn_resolutions': 
                         [], 'dropout': 0.0}, 'lossconfig': {'target':          
                         'torch.nn.Identity'}}}, 'cond_stage_config': {'target':
                         'ldm.modules.encoders.modules.FrozenCLIPEmbedder'}}    
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
11:28:33-438255 INFO     Model created from config:                             
                         /home/aaron/automatic/configs/v1-inference.yaml        
11:28:33-439444 DEBUG    Model weights loading: {'ram': {'used': 2.24, 'total': 
                         15.55}, 'gpu': {'used': 0.0, 'total': 7.54}, 'retries':
                         0, 'oom': 0}                                           
Loading weights: /home/aaron/automatic/models/VAE/kl-f8-anime2.ckpt ━━╺ 28… 0:0…
                                                                        MB      
11:28:35-541044 DEBUG    Model weights loaded: {'ram': {'used': 6.19, 'total':  
                         15.55}, 'gpu': {'used': 0.0, 'total': 7.54}, 'retries':
                         0, 'oom': 0}                                           
11:28:36-248590 DEBUG    Model weights moved: {'ram': {'used': 6.19, 'total':   
                         15.55}, 'gpu': {'used': 2.02, 'total': 7.54},          
                         'retries': 0, 'oom': 0}                                
11:28:36-253853 INFO     Applying sub-quadratic cross attention optimization    
11:28:36-370095 INFO     Applied IPEX Optimize                                  
11:28:36-924049 INFO     Embeddings loaded: 6 ['bad-artist', 'bad-artist-anime',
                         'bad-hands-5', 'bad_prompt', 'bad_prompt_version2',    
                         'easynegative']                                        
11:28:36-928761 INFO     Model loaded in 5.0s (load=1.2s create=0.3s apply=1.7s 
                         vae=0.4s move=0.7s embeddings=0.7s)                    
11:28:37-028605 DEBUG    gc: collected=1770 device=xpu {'ram': {'used': 6.25,   
                         'total': 15.55}, 'gpu': {'used': 2.02, 'total': 7.54}, 
                         'retries': 0, 'oom': 0}                                
11:28:37-029897 INFO     Model load finished: {'ram': {'used': 6.25, 'total':   
                         15.55}, 'gpu': {'used': 2.02, 'total': 7.54},          
                         'retries': 0, 'oom': 0}                                
ControlNet v1.1.189
ControlNet v1.1.189
Image Browser: ImageReward is not installed, cannot be used.
11:28:43-040922 INFO     Loading UI theme: name=gradio/default style=Auto       
11:28:43-063925 DEBUG    Creating UI                                            
11:28:43-066391 DEBUG    Adding JS scripts:                                     
                         ['/javascript/aspectRatioOverlay.js',                  
                         '/javascript/contextMenus.js',                         
                         '/javascript/dragdrop.js',                             
                         '/javascript/edit-attention.js',                       
                         '/javascript/extensions.js',                           
                         '/javascript/extraNetworks.js',                        
                         '/javascript/generationParams.js',                     
                         '/javascript/hints.js', '/javascript/hires_fix.js',    
                         '/javascript/imageMaskFix.js',                         
                         '/javascript/imageParams.js',                          
                         '/javascript/imageviewer.js',                          
                         '/javascript/notification.js',                         
                         '/javascript/progressbar.js',                          
                         '/javascript/textualInversion.js', '/javascript/ui.js',
                         '/extensions-builtin/multidiffusion-upscaler-for-automa
                         tic1111/javascript/bboxHint.js',                       
                         '/extensions-builtin/prompt-bracket-checker/javascript/
                         prompt-bracket-checker.js',                            
                         '/extensions-builtin/sd-extension-system-info/javascrip
                         t/system-info.js',                                     
                         '/extensions-builtin/sd-webui-controlnet/javascript/hin
                         ts.js',                                                
                         '/extensions-builtin/stable-diffusion-webui-images-brow
                         ser/javascript/image_browser.js',                      
                         '/extensions/posex/javascript/posex-webui.js',         
                         '/extensions/sd-webui-ar/javascript/button_titles.js', 
                         '/extensions/sd-webui-ar/javascript/sd-webui-ar.js',   
                         '/extensions/sd-webui-depth-lib/javascript/fabric.js', 
                         '/extensions/sd-webui-depth-lib/javascript/main.js',   
                         '/extensions/sd-webui-photopea-embed/javascript/data-ut
                         ility-functions.js',                                   
                         '/extensions/sd-webui-photopea-embed/javascript/photope
                         a-bindings.js',                                        
                         '/extensions/sd-webui-photopea-embed/javascript/photope
                         a-scripts.js',                                         
                         '/extensions/stable-diffusion-webui-depthmap-script/jav
                         ascript/depthmap.js',                                  
                         '/extensions/stable-diffusion-webui-fix-image-paste/jav
                         ascript/fix-image-paste.js']                           
11:28:43-069852 DEBUG    Adding CSS stylesheets: ['javascript/style.css',       
                         '/extensions-builtin/stable-diffusion-webui-images-brow
                         ser/style.css', '/extensions/posex/style.css',         
                         '/extensions/sd-webui-ar/style.css',                   
                         '/extensions/stable-diffusion-webui-two-shot/style.css'
                         ]                                                      
Create LRU cache (max_size=16) for preprocessor results.
Create LRU cache (max_size=16) for preprocessor results.
11:28:43-775185 DEBUG    Extensions list failed to load:                        
                         /home/aaron/automatic/html/extensions.json             
11:28:44-006755 DEBUG    Extensions manager: refresh list search=""             
                         sort="default"                                         
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
11:28:44-494397 INFO     Local URL: http://127.0.0.1:7860/                      
11:28:44-495274 INFO     API Docs: http://127.0.0.1:7860/docs                   
11:28:44-496055 DEBUG    Gradio registered functions: 1121                      
11:28:44-496820 INFO     Initializing middleware                                
11:28:44-524762 DEBUG    Creating API                                           
Create LRU cache (max_size=16) for preprocessor results.
11:28:44-764649 DEBUG    gc: collected=6024 device=xpu {'ram': {'used': 4.4,    
                         'total': 15.55}, 'gpu': {'used': 2.02, 'total': 7.54}, 
                         'retries': 0, 'oom': 0}                                
11:28:44-920937 DEBUG    gc: collected=0 device=xpu {'ram': {'used': 4.4,       
                         'total': 15.55}, 'gpu': {'used': 2.02, 'total': 7.54}, 
                         'retries': 0, 'oom': 0}                                
11:28:44-922046 INFO     Startup time: 26.0s (torch=1.6s gradio=3.2s            
                         libraries=7.3s vae=0.1s models=0.1s codeformer=0.1s    
                         scripts=11.4s upscalers=0.1s onchange=0.1s ui=1.2s     
                         launch=0.3s scripts app_started_callback=0.1s          
                         checkpoint=0.3s)                                       
11:28:44-923253 INFO     Memory used: 4.4 total: 15.55                          
11:29:51-104988 DEBUG    gc: collected=38 device=xpu {'ram': {'used': 4.4,      
                         'total': 15.55}, 'gpu': {'used': 2.02, 'total': 7.54}, 
                         'retries': 0, 'oom': 0}                                
11:29:51-106423 DEBUG    Model weights unloaded: {'ram': {'used': 4.4, 'total': 
                         15.55}, 'gpu': {'used': 2.02, 'total': 7.54},          
                         'retries': 0, 'oom': 0}                                
11:29:55-873084 DEBUG    Reload model weights: False None                       
11:29:55-873845 DEBUG    Select checkpoint:                                     
                         Realistic_Vision_V2.0-fp16-no-ema.safetensors          
                         [c0d1994c73]                                           
11:29:56-044461 DEBUG    gc: collected=95 device=xpu {'ram': {'used': 4.4,      
                         'total': 15.55}, 'gpu': {'used': 2.02, 'total': 7.54}, 
                         'retries': 0, 'oom': 0}                                
11:29:56-045795 DEBUG    Model weights unloaded: {'ram': {'used': 4.4, 'total': 
                         15.55}, 'gpu': {'used': 2.02, 'total': 7.54},          
                         'retries': 0, 'oom': 0}                                
Loading weights: /home/aaron/automatic/models/Stable-diffusion/Realistic_Visio… 
11:29:56-130149 DEBUG    Load model: info=True dict=True                        
11:29:56-130786 DEBUG    Verifying Torch settings                               
11:29:56-132027 DEBUG    Torch FP16 test passed                                 
11:29:56-132546 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False     
                         no-half-vae=False upscast=True                         
11:29:56-133167 INFO     Setting Torch parameters: dtype=torch.float16          
                         vae=torch.float16 unet=torch.float16                   
11:29:56-133740 DEBUG    Torch default device: xpu                              
11:29:56-134548 DEBUG    Model dict loaded: {'ram': {'used': 4.42, 'total':     
                         15.55}, 'gpu': {'used': 2.02, 'total': 7.54},          
                         'retries': 0, 'oom': 0}                                
11:29:56-143263 DEBUG    Model config loaded: {'ram': {'used': 4.42, 'total':   
                         15.55}, 'gpu': {'used': 2.02, 'total': 7.54},          
                         'retries': 0, 'oom': 0}                                
11:29:56-144171 DEBUG    Model config: {'linear_start': 0.00085, 'linear_end':  
                         0.012, 'num_timesteps_cond': 1, 'log_every_t': 200,    
                         'timesteps': 1000, 'first_stage_key': 'jpg',           
                         'cond_stage_key': 'txt', 'image_size': 64, 'channels': 
                         4, 'cond_stage_trainable': False, 'conditioning_key':  
                         'crossattn', 'monitor': 'val/loss_simple_ema',         
                         'scale_factor': 0.18215, 'use_ema': False,             
                         'scheduler_config': {'target':                         
                         'ldm.lr_scheduler.LambdaLinearScheduler', 'params':    
                         {'warm_up_steps': [10000], 'cycle_lengths':            
                         [10000000000000], 'f_start': [1e-06], 'f_max': [1.0],  
                         'f_min': [1.0]}}, 'unet_config': {'target':            
                         'ldm.modules.diffusionmodules.openaimodel.UNetModel',  
                         'params': {'image_size': 32, 'in_channels': 4,         
                         'out_channels': 4, 'model_channels': 320,              
                         'attention_resolutions': [4, 2, 1], 'num_res_blocks':  
                         2, 'channel_mult': [1, 2, 4, 4], 'num_heads': 8,       
                         'use_spatial_transformer': True, 'transformer_depth':  
                         1, 'context_dim': 768, 'use_checkpoint': True,         
                         'legacy': False, 'use_fp16': True}},                   
                         'first_stage_config': {'target':                       
                         'ldm.models.autoencoder.AutoencoderKL', 'params':      
                         {'embed_dim': 4, 'monitor': 'val/rec_loss', 'ddconfig':
                         {'double_z': True, 'z_channels': 4, 'resolution': 256, 
                         'in_channels': 3, 'out_ch': 3, 'ch': 128, 'ch_mult':   
                         [1, 2, 4, 4], 'num_res_blocks': 2, 'attn_resolutions': 
                         [], 'dropout': 0.0}, 'lossconfig': {'target':          
                         'torch.nn.Identity'}}}, 'cond_stage_config': {'target':
                         'ldm.modules.encoders.modules.FrozenCLIPEmbedder'}}    
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
11:29:56-400628 INFO     Model created from config:                             
                         /home/aaron/automatic/configs/v1-inference.yaml        
11:29:56-401764 DEBUG    Model weights loading: {'ram': {'used': 4.71, 'total': 
                         15.55}, 'gpu': {'used': 2.02, 'total': 7.54},          
                         'retries': 0, 'oom': 0}                                
Loading weights: /home/aaron/automatic/models/VAE/kl-f8-anime2.ckpt ━━╺ 28… 0:0…
                                                                        MB      
11:29:57-249057 DEBUG    Model weights loaded: {'ram': {'used': 7.75, 'total':  
                         15.55}, 'gpu': {'used': 2.02, 'total': 7.54},          
                         'retries': 0, 'oom': 0}                                
11:29:57-962594 DEBUG    Model weights moved: {'ram': {'used': 7.75, 'total':   
                         15.55}, 'gpu': {'used': 4.04, 'total': 7.54},          
                         'retries': 0, 'oom': 0}                                
11:29:57-967937 INFO     Applying sub-quadratic cross attention optimization    
11:29:58-015265 INFO     Applied IPEX Optimize                                  
11:29:58-026700 INFO     Model loaded in 2.0s (load=0.1s create=0.3s apply=0.4s 
                         vae=0.4s move=0.7s embeddings=0.1s)                    
11:29:58-200675 DEBUG    gc: collected=1081 device=xpu {'ram': {'used': 7.75,   
                         'total': 15.55}, 'gpu': {'used': 4.04, 'total': 7.54}, 
                         'retries': 0, 'oom': 0}                                
11:29:58-202052 INFO     Model load finished: {'ram': {'used': 7.75, 'total':   
                         15.55}, 'gpu': {'used': 4.04, 'total': 7.54},          
                         'retries': 0, 'oom': 0}                                
11:30:00-201215 DEBUG    Server alive: True Memory used: 5.76 total: 15.55 

this is initial load, unload and reload.  I don't personally see any errors, but vram jumps from initial load of 2gb to over 4gb after unload and reload.  Older commit unloading model set vram to 444mb and loading new models kept it around the same 2-3gb mark                   

The debug doesn't appear to show any error, but My vram doubles.  It does not do this on the older commits, or the ipex automatic1111.

**Comment by Mindset-Official** [comment]
Vram needed with initial loaded model, about the same for every generation

![Screenshot from 2023-05-23 11-37-30](https://github.com/vladmandic/automatic/assets/134022837/1a3b2c42-e8ec-49de-bdec-db9965ea47f5)

vram after unloading and reloading, or loading a new model

![Screenshot from 2023-05-23 11-38-30](https://github.com/vladmandic/automatic/assets/134022837/a5f9b1d7-0ae4-46d4-846a-05af17edfa37)

**Comment by Mindset-Official** [comment]
I am using the repo by Jboaval https://github.com/jbaboval/stable-diffusion-webui (updated to newer gradio by me I haven't checked his new one yet).  And it also doesn't happen on the commit https://github.com/vladmandic/automatic/commit/554f26296e0045db78f86e97ffee60805c93fc9a

**Comment by vladmandic** [comment]
ok, that makes more sense. i'll check.

**Comment by vladmandic** [comment]
looping in @Disty0, if you have any insights?

**Comment by vladmandic** [comment]
I've merged PR from @Disty0, should be fixed now - report if issue persists and I'll reopen.

**Comment by Mindset-Official** [comment]
seems to be working properly now, thanks!

**Comment by Mindset-Official** [comment]
Well, Okay now there is a new problem. Seems now the models load into system ram until the entire program crashes.  Should I make a new issue or just post in here?  I will test some more later but so far swapping models completely crashed the webui

**Comment by vladmandic** [comment]
lets confirm first - i'm seeing a yo-yo efffect - for example, inital load adds 2gb to ram, unload releases 1.5gb, new load adds 2gbb so now you're at 2.5gb so there is a leak of 500mb per model change - if that is what you're seeing (numbers are approximate), that is not specific to ipex. i've been chasing it down for over a month and its exremely annoying.

**Comment by Mindset-Official** [comment]
okay, yeah that does seem to be the case and it doesn't seem to happen on every model load, sometimes the ram stays exactly the same.

**Comment by vladmandic** [comment]
if you're on ubuntu, try libtcmalloc, its far better than pythons version of malloc. doesn't solve the problem, but it reduces it from xxx mb to x mb leak.

> sudo apt install libgoogle-perftools-dev
> export LD_PRELOAD=libtcmalloc.so; ./webui.sh

**Comment by Mindset-Official** [comment]
Thanks I will give it a shot!

**Comment by Mindset-Official** [comment]
Seems like adding that made the ram leak even worse? Might be placebo, but now if I load about 3 models ram usage goes up from 4gb to over 9 and keeps climbing until it crashes, doesn't release any it seems now. Going to try and see if the same happens on older commits.  I can confirm the leak doesn't exist in in this version https://github.com/jbaboval/stable-diffusion-webui at least no so far.

**Comment by Mindset-Official** [comment]
This commit here  https://github.com/vladmandic/automatic/tree/5c516332d79f6a9a8f20ed3bad48539acfcf8688  seems to work with both vram and ram consumption being used properly.  I was actually attempting to see what ram usage looked like with the vram issue, but it doesn't seem to happen here?

**Comment by Mindset-Official** [comment]
Yeah, its weird I was expecting to have the vram issue, I will try both later today and post back here.

**Comment by Disty0** [comment]
Are you using WSL?  WSL method has it's own memory leak issues, try native Linux. 
Native Linux adds 2-3 GB of extra system memory usage once when changing models but it doesn't inflate after that.

**Comment by Mindset-Official** [comment]
I am using native linux ubuntu 22.04

**Comment by Disty0** [comment]
DPC++ compiler patch is required according to the Intel's PyTorch Installation Guide.
Did you apply this?

https://intel.github.io/intel-extension-for-pytorch/xpu/1.13.120+xpu/tutorials/installation.html

https://registrationcenter-download.intel.com/akdlm/IRC_NAS/89283df8-c667-47b0-b7e1-c4573e37bd3e/2023.1-linux-hotfix.zip

```
This package is designed to patch your level zero plugin to address a potential resource issue when using multiple queues. 

The script in this package will attempt to backup the existing level zero plug and then copy over the new one. 

To manually perform this task, you can
1. Backup existing level zero plugin
	windows: C:\Program Files (x86)\Intel\oneAPI\compiler\2023.1.0\windows\bin\pi_level_zero.dll
	Linux: /opt/intel/oneapi/compiler/2023.1.0/linux/lib/pi_level_zero.so
2. Copy new file in current folder over to location above

*** PLEASE NOTE DEPENDING WHERE YOUR ONEAPI INSTALL IS, THIS CAN REQUIRE ROOT/ADMINISTRATOR priveleges"
```

**Comment by Mindset-Official** [comment]
> DPC++ compiler patch is required according to the Intel's PyTorch Installation Guide. Did you apply this?
> 
> https://intel.github.io/intel-extension-for-pytorch/xpu/1.13.120+xpu/tutorials/installation.html
> 
> https://registrationcenter-download.intel.com/akdlm/IRC_NAS/89283df8-c667-47b0-b7e1-c4573e37bd3e/2023.1-linux-hotfix.zip
> 
> ```
> This package is designed to patch your level zero plugin to address a potential resource issue when using multiple queues. 
> 
> The script in this package will attempt to backup the existing level zero plug and then copy over the new one. 
> 
> To manually perform this task, you can
> 1. Backup existing level zero plugin
> 	windows: C:\Program Files (x86)\Intel\oneAPI\compiler\2023.1.0\windows\bin\pi_level_zero.dll
> 	Linux: /opt/intel/oneapi/compiler/2023.1.0/linux/lib/pi_level_zero.so
> 2. Copy new file in current folder over to location above
> 
> *** PLEASE NOTE DEPENDING WHERE YOUR ONEAPI INSTALL IS, THIS CAN REQUIRE ROOT/ADMINISTRATOR priveleges"
> ```

I am not sure, I installed it all from the tutorial on reddit and updated my ipex to the latest wheels.  I will give this a try, but why is it only the latest commots that cause issue?

**Comment by vladmandic** [comment]
to avoid making changes + uploading + testing + reverting, etc...
can you use latest commit and manually edit two files to changes that are likely cause and test - its really just couple of lines?
<https://github.com/vladmandic/automatic/pull/1147/files>

**Comment by vladmandic** [comment]
Just to confirm, you're saying that latest commit minus changes I've highlighted works fine?

**Comment by Disty0** [comment]
It was putting that 2.5 GB to GPU's VRAM before the PR.
PR sent that 2.5 GB to System RAM instead of VRAM.

I just reverted it and It's not putting extra 2.5 GB to VRAM or System RAM.
Don't know what caused and fixed it :/

**Comment by vladmandic** [comment]
so should i revert the PR?

**Comment by Disty0** [comment]
> so should i revert the PR?

Yes, this issue seems to be fixed without it.

**Comment by vladmandic** [comment]
done. i'm closing the issue as resolved, if there is anything further update here and i'll reopen as needed.

**Comment by Mindset-Official** [comment]
> Just to confirm, you're saying that latest commit minus changes I've highlighted works fine?

I didn't need to change anything, I just updated and it worked after i patched the level zero driver.  Sorry for late response I went for a walk.
