### ISSUE TITLE
[Issue]: Generate button doesn't reactivate

### ISSUE THREAD

**Issue by AlUlkesh** [vladmandic/automatic#114]
### Issue Description

After generating an image the Generate button doesn't reactivate. Stop and Skip still show, but don't respond.

https://user-images.githubusercontent.com/99896447/231886553-09d1bfbf-19ae-45e3-9b9a-c4eed1889280.mp4

No errors on console. Javascript console has:
![image](https://user-images.githubusercontent.com/99896447/231886472-1f197adb-4634-447b-8a1a-00fad296acb9.png)

### Platform Description

Windows 10, Chrome

**Comment by vladmandic** [comment]
my skin is designed to have generate/skip/stop buttons always visible and always available. if you mess with the skin, cant guarantee what happens. at best this falls under #84

**Comment by AlUlkesh** [comment]
Ah, okay. I had put in an empty user.css. I thought that was optional. Copied it back and it is working again.

**Comment by vladmandic** [comment]
i need to cleanup `user.css`, merge it with `system.css` and then make `user.css` actual user-level again...
