### ISSUE TITLE
[Issue]: Saving ignores "save to subdirectory" setting

### ISSUE THREAD

**Issue by Razunter** [vladmandic/automatic#1141]
### Issue Description

I have disabled the subdirectory setting (`When using "Save" button, save images to a subdirectory`), but since some recent update, all saved images follow the `Directory name pattern` setting. That's annoying. I prefer flat structure for manually saved images.

![settings](https://github.com/vladmandic/automatic/assets/362900/ef8f7cd3-42fd-4c1f-a381-ba196909c083)

### Version Platform Description

Version: d36b16d0 Tue May 23 14:31:22 2023 -0400
Windows 11, Firefox

**Comment by vladmandic** [comment]
fixed (i hope).
