### ISSUE TITLE
[Issue]: installer.setup_logging requires rich library to be installed prior to venv init

### ISSUE THREAD

**Issue by Liraal2** [vladmandic/automatic#1142]
### Issue Description

When running the UI via regular `.\webui.bat`, if the `venv` directory is not present, installer script will return an error due to missing rich library. This is due to the fact that installer.setup_logging in line 57 imports rich, but dependencies aren't ensured till after setup_logging is called (lines 14 and 12 in launch.py, respectively).

This can be worked around by manually installing rich in venv, moving setup_logging till after ensure_base_requirements or manually adding dependency check for rich.

### Version Platform Description

Version: d36b16d03 Tue May 23 14:31:22 2023 -0400
Windows 10, RTX 3090

**Comment by vladmandic** [comment]
yeah, i moved things aroung in installer and ensure_base_requirements was triggered too late. fixed.
