### ISSUE TITLE
[Issue]: Model Load error on Intel Arc

### ISSUE THREAD

**Issue by xwang186** [vladmandic/automatic#1144]
### Issue Description

saw from some resource that you have supported Linux Arc for Stable diffusion **https://www.reddit.com/r/IntelArc/comments/11an12q/stable_diffusion_web_ui_for_intel_arc/**
May I know if what is the supported driver/package?

openvino solution works for me at this moment, [here](https://github.com/bes-dev/stable_diffusion.openvino)

Error Info:

WARNING  Default checkpoint not found: model.ckpt

WARNING  Loading fallback checkpoint: v1-5-pruned-emaonly.safetensors

WARNING  Torch FP16 test failed: Forcing FP32 operations

INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32

Loading weights: /home/ayase/repo/automatic/models/Stable-diffusion/v1-5-pruned-emaonly.safetensors 
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/4.3 GB -:--:--

ERROR    Failed to load stable diffusion model

ERROR    loading stable diffusion model: TypeError

### Version Platform Description

OS: Ubuntu, kernel 5.19.0.35
Driver: latest i-915 default graphics driver, refer to https://dgpu-docs.intel.com/installation-guides/ubuntu/ubuntu-jammy-arc.html
Hardware: Intel Arc A770 16GB RAM
Code base version:  5c516332d79f6a9a8f20ed3bad48539acfcf8688

**Comment by xwang186** [comment]
@vladmandic  Nice! Thank you for your support. Actually I didn't realize to have input here. After I corrected as --use-ipex, I can load the model correctly; but when I click on "generate" it gives me an error about "Input and weight should be of the same datatype"

![image](https://github.com/vladmandic/automatic/assets/39249169/a90a20f7-e4d8-4e2d-a7ca-63993d4b6858)

Do you have any idea on that?

**Comment by vladmandic** [comment]
no idea, looping in @Disty0 as SME for IPEX

**Comment by Disty0** [comment]
Can't reproduce.
Can you try removing config.json and restart?
It probably set the default config without --use-ipex.
Upcast Sampling has to be enabled with current version of ipex (1.13.120+xpu).

Currently supported driver is OneAPI BaseKit 2023.1.0:
https://intel.github.io/intel-extension-for-pytorch/xpu/1.13.120+xpu/tutorials/installation.html
