### ISSUE TITLE
[Issue]: instruct-pix2pix,sd21-unclip model file loading failed

### ISSUE THREAD

**Issue by xam0482** [vladmandic/automatic#1146]
### Issue Description

instruct-pix2pix,sd21-unclip model file  unusable.
x4-upscaler-ema model file  Fail to load

### Version Platform Description

version:1.6.4
OS:win11
browser:chrome

**Comment by vladmandic** [comment]
no title, no description, no valid version. this is the perfect example of invalid issue.
