### ISSUE TITLE
[Issue]: After the last update, some errors

### ISSUE THREAD

**Issue by ronbere** [vladmandic/automatic#1149]
### Issue Description

PleaUsing VENV: D:\automatic\venv
15:51:24-469139 INFO     Running extension preloading
15:51:24-587148 INFO     Starting SD.Next
15:51:24-588183 INFO     Python 3.10.9 on Windows
15:51:24-666173 INFO     Version: 0acc7d3b Wed May 24 08:49:33 2023 -0400
15:51:24-925188 INFO     Setting environment tuning
15:51:24-930193 INFO     nVidia CUDA toolkit detected
15:51:26-182528 INFO     Torch 2.0.1+cu118
15:51:26-203159 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
15:51:26-206160 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 Ti VRAM 12287 Arch (8, 6) Cores 80
15:51:26-207162 INFO     Installing package: tensorflow==2.12.0
15:51:46-637224 INFO     Verifying requirements
15:51:46-650236 WARNING  Package wrong version: numpy 1.23.5 required 1.24.3
15:51:46-652238 INFO     Installing package: numpy==1.24.3
15:51:54-555090 ERROR    Error running pip: install --upgrade numpy==1.24.3
15:51:54-559093 INFO     Installing packages
15:51:54-608138 INFO     No changes detected: Quick launch active
15:51:54-610139 INFO     Running extension preloading
15:51:54-611140 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\launch.py:145 in <module>                                               │
│                                                                                                                     │
│   144                                                                                                               │
│ > 145     instance = start_server(immediate=True, server=None)                                                      │
│   146     while True:                                                                                               │
│                                                                                                                     │
│ D:\automatic\launch.py:117 in start_server                                           │
│                                                                                                                     │
│   116     server = importlib.util.module_from_spec(module_spec)                                                     │
│ > 117     module_spec.loader.exec_module(server)                                                                    │
│   118     if args.test:                                                                                             │
│ in exec_module:883                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ D:\automatic\webui.py:37 in <module>                                                 │
│                                                                                                                     │
│    36 import ldm.modules.encoders.modules # pylint: disable=W0611,C0411                                             │
│ >  37 from modules import extra_networks, ui_extra_networks_checkpoints # pylint: disable=C041                      │
│    38 from modules import extra_networks_hypernet, ui_extra_networks_hypernets, ui_extra_netwo                      │
│                                                                                                                     │
│ D:\automatic\modules\ui_extra_networks_checkpoints.py:5 in <module>                  │
│                                                                                                                     │
│    4                                                                                                                │
│ >  5 from modules import shared, ui_extra_networks, sd_models                                                       │
│    6                                                                                                                │
│                                                                                                                     │
│ D:\automatic\modules\ui_extra_networks.py:10 in <module>                             │
│                                                                                                                     │
│     9 from modules import shared                                                                                    │
│ >  10 from modules.images import read_info_from_image                                                               │
│    11 from modules.generation_parameters_copypaste import image_from_url_text                                       │
│                                                                                                                     │
│ D:\automatic\modules\images.py:17 in <module>                                        │
│                                                                                                                     │
│    16 from PIL import Image, ImageFont, ImageDraw, PngImagePlugin, ExifTags                                         │
│ >  17 from modules import sd_samplers, shared, script_callbacks, errors, paths                                      │
│    18                                                                                                               │
│                                                                                                                     │
│ D:\automatic\modules\sd_samplers.py:1 in <module>                                    │
│                                                                                                                     │
│ >  1 from modules import sd_samplers_compvis, sd_samplers_kdiffusion, shared                                        │
│    2 from modules.sd_samplers_common import samples_to_image_grid, sample_to_image # pylint:                        │
│                                                                                                                     │
│ D:\automatic\modules\sd_samplers_kdiffusion.py:4 in <module>                         │
│                                                                                                                     │
│     3 import torch                                                                                                  │
│ >   4 import k_diffusion.sampling                                                                                   │
│     5 from modules import prompt_parser, devices, sd_samplers_common                                                │
│                                                                                                                     │
│ D:\automatic\repositories\k-diffusion\k_diffusion\__init__.py:1 in <module>          │
│                                                                                                                     │
│ > 1 from . import augmentation, config, evaluation, external, gns, layers, models, sampling,                        │
│   2 from .layers import Denoiser                                                                                    │
│                                                                                                                     │
│ D:\automatic\repositories\k-diffusion\k_diffusion\augmentation.py:6 in <module>      │
│                                                                                                                     │
│     5 import numpy as np                                                                                            │
│ >   6 from skimage import transform                                                                                 │
│     7 import torch                                                                                                  │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\skimage\transform\__init__.py:4 in <module>      │
│                                                                                                                     │
│    3                               hough_circle_peaks, hough_ellipse)                                               │
│ >  4 from .radon_transform import (radon, iradon, iradon_sart,                                                      │
│    5                               order_angles_golden_ratio)                                                       │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\skimage\transform\radon_transform.py:3 in        │
│ <module>                                                                                                            │
│                                                                                                                     │
│     2                                                                                                               │
│ >   3 from scipy.interpolate import interp1d                                                                        │
│     4 from scipy.constants import golden_ratio                                                                      │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\scipy\interpolate\__init__.py:167 in <module>    │
│                                                                                                                     │
│   166 """                                                                                                           │
│ > 167 from ._interpolate import *                                                                                   │
│   168 from ._fitpack_py import *                                                                                    │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\scipy\interpolate\_interpolate.py:12 in <module> │
│                                                                                                                     │
│     11                                                                                                              │
│ >   12 from . import _fitpack_py                                                                                    │
│     13 from . import dfitpack                                                                                       │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\scipy\interpolate\_fitpack_py.py:10 in <module>  │
│                                                                                                                     │
│     9 from . import _fitpack_impl as _impl                                                                          │
│ >  10 from ._bsplines import BSpline                                                                                │
│    11                                                                                                               │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\scipy\interpolate\_bsplines.py:8 in <module>     │
│                                                                                                                     │
│      7                           solve, solve_banded)                                                               │
│ >    8 from scipy.optimize import minimize_scalar                                                                   │
│      9 from . import _bspl                                                                                          │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\scipy\optimize\__init__.py:405 in <module>       │
│                                                                                                                     │
│   404 from ._optimize import *                                                                                      │
│ > 405 from ._minimize import *                                                                                      │
│   406 from ._root import *                                                                                          │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\scipy\optimize\_minimize.py:26 in <module>       │
│                                                                                                                     │
│     25 from ._trustregion_exact import _minimize_trustregion_exact                                                  │
│ >   26 from ._trustregion_constr import _minimize_trustregion_constr                                                │
│     27                                                                                                              │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\scipy\optimize\_trustregion_constr\__init__.py:4 │
│ in <module>                                                                                                         │
│                                                                                                                     │
│   3                                                                                                                 │
│ > 4 from .minimize_trustregion_constr import _minimize_trustregion_constr                                           │
│   5                                                                                                                 │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\scipy\optimize\_trustregion_constr\minimize_trus │
│ tregion_constr.py:5 in <module>                                                                                     │
│                                                                                                                     │
│     4 from .._differentiable_functions import VectorFunction                                                        │
│ >   5 from .._constraints import (                                                                                  │
│     6     NonlinearConstraint, LinearConstraint, PreparedConstraint, strict_bounds)                                 │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\scipy\optimize\_constraints.py:8 in <module>     │
│                                                                                                                     │
│     7 from warnings import warn, catch_warnings, simplefilter                                                       │
│ >   8 from numpy.testing import suppress_warnings                                                                   │
│     9 from scipy.sparse import issparse                                                                             │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\numpy\testing\__init__.py:11 in <module>         │
│                                                                                                                     │
│   10 from . import _private                                                                                         │
│ > 11 from ._private.utils import *                                                                                  │
│   12 from ._private.utils import (_assert_valid_refcount, _gen_alignment_data)                                      │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\numpy\testing\_private\utils.py:480 in <module>  │
│                                                                                                                     │
│    479                                                                                                              │
│ >  480 @np._no_nep50_warning()                                                                                      │
│    481 def assert_almost_equal(actual,desired,decimal=7,err_msg='',verbose=True):                                   │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\numpy\__init__.py:311 in __getattr__             │
│                                                                                                                     │
│   310         #                                                                                                     │
│ > 311         # The previous way Tester was imported also had a side effect of adding                               │
│   312         # the full `numpy.testing` namespace                                                                  │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: module 'numpy' has no attribute '_no_nep50_warning'
Appuyez sur une touche pour continuer...se fill this form with as much information as possible

### Version Platform Description

Windows10, Chrome

**Comment by vladmandic** [comment]
> 15:51:54-555090 ERROR Error running pip: install --upgrade numpy==1.24.3

there is error installing numpy near the top, everything below is just a consequence:

lets try to install it manually:

> venv\Scripts\activate
> pip show numpy
> pip install --upgrade numpy==1.24.3
> pip show numpy

**Comment by ronbere** [comment]
(venv) D:\automatic\venv\Scripts>pip install --upgrade numpy==1.24.3
Collecting numpy==1.24.3
  Using cached numpy-1.24.3-cp310-cp310-win_amd64.whl (14.8 MB)
Installing collected packages: numpy
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.3 which is incompatible.
Successfully installed numpy-1.24.3

(venv) D:\automatic\venv\Scripts>pip show numpy
Name: numpy
Version: 1.24.3
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: BSD-3-Clause
Location: d:\automatic\venv\lib\site-packages
Requires:
Required-by: accelerate, altair, basicsr, blendmodes, clean-fid, contourpy, diffusers, facexlib, filterpy, gfpgan, gradio, h5py, imageio, jax, lpips, matplotlib, mediapipe, ml-dtypes, numba, numexpr, onnxruntime, opencv-contrib-python, opencv-python, opt-einsum, pandas, pytorch-lightning, PyWavelets, realesrgan, scikit-image, scipy, seaborn, tb-nightly, tensorboard, tensorflow-intel, tifffile, torchmetrics, torchsde, torchvision, transformers

(venv) D:\automatic\venv\Scripts>

**Comment by vladmandic** [comment]
and what is the status now?

**Comment by ronbere** [comment]
Always a Numpy issue :

23:00:38-457896 INFO     Running extension preloading
23:00:38-619734 INFO     Starting SD.Next
23:00:38-642375 INFO     Python 3.10.9 on Windows
23:00:38-729057 INFO     Version: 9e66d88e Wed May 24 15:21:49 2023 -0400
23:00:39-465965 INFO     Setting environment tuning
23:00:39-469968 INFO     nVidia CUDA toolkit detected
23:00:57-590091 INFO     Torch 2.0.1+cu118
23:00:57-619742 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
23:00:57-620918 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 Ti VRAM 12287 Arch (8, 6) Cores 80
23:00:57-622920 INFO     Verifying requirements
23:00:57-635932 WARNING  Package wrong version: numpy 1.24.3 required 1.23.5
23:00:57-636933 INFO     Installing package: numpy==1.23.5
23:01:13-310352 ERROR    Error running pip: install --upgrade numpy==1.23.5
23:01:13-314356 INFO     Installing packages

**Comment by ronbere** [comment]
ok, all seems fine, excepts black images sometimes...i know than its a common issue

**Comment by vladmandic** [comment]
So resolved?

**Comment by vladmandic** [comment]
LOL! Yeah, annoying, but separate issue...
