### ISSUE TITLE
[Issue]: Exception: The parameter is incorrect. Error when using Hires fix

### ISSUE THREAD

**Issue by HyunJae5463** [vladmandic/automatic#1151]
### Issue Description

Getting the following Error when i use to use Hires fix

```
17:07:13-904335 ERROR    Exception: The parameter is incorrect.
17:07:13-905335 ERROR    Arguments: args=('task(dpq4d2uwesfdd6h)', '1girl', '', [], 20, 3, False, False, 1, 1, 6, 1,
                         -1.0, -1.0, 0, 0, 0, False, 512, 512, True, 0.7, 2, 'R-ESRGAN 4x+ Anime6B', 0, 0, 0, [], 0,
                         False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1,
                         64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0,
                         False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 512, 64, True, True, True, False,
                         False, 7, 100, 'Constant', 0, 'Constant', 0, 4, <controlnet.py.UiControlNetUnit object at
                         0x0000025C043899C0>, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0, '',
                         [], 0, '', [], True, False, False, False, 0, False, None, None, False, 50) kwargs={}
17:07:13-910341 ERROR    gradio call: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ E:\Arc Stable\automatic\modules\call_queue.py:33 in f                                                                │
│                                                                                                                      │
│    32 │   │   │   try:                                                                                               │
│ ❱  33 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    34 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                      │
│ E:\Arc Stable\automatic\modules\txt2img.py:57 in txt2img                                                             │
│                                                                                                                      │
│   56 │   if processed is None:                                                                                       │
│ ❱ 57 │   │   processed = process_images(p)                                                                           │
│   58 │   p.close()                                                                                                   │
│                                                                                                                      │
│                                               ... 31 frames hidden ...                                               │
│                                                                                                                      │
│ E:\Arc Stable\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                         │
│                                                                                                                      │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                       │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                                              │
│   1502 │   │   # Do not call functions when jit is used                                                              │
│                                                                                                                      │
│ E:\Arc Stable\automatic\modules\sd_hijack_optimizations.py:398 in scaled_dot_product_attention_forward               │
│                                                                                                                      │
│   397 │   # the output of sdp = (batch, num_heads, seq_len, head_dim)                                                │
│ ❱ 398 │   hidden_states = torch.nn.functional.scaled_dot_product_attention(                                          │
│   399 │   │   q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The parameter is incorrect.
```

### Version Platform Description

Using the latest Version
Windows 11
Arc A770 16GB

**Comment by vladmandic** [comment]
just to confirm, you're using `--use-ipex` to enable arc support?

this is veeeery deep in torch, its quite possible that arc does not implement some features used by when combo unipc sampler + sdp cross-attention are used.
i cannot reproduce this on cuda.

not sure what i can do about this, but just in case looping in @Disty0 as he's done pretty much all of ipex specific code

**Comment by Disty0** [comment]
Can't reproduce this but produced similar error when using tiled upscale and UniPC.

stable-diffusion-stability-ai repo tries to use INT64.
A770 doesn't support FP64.

Try DPM++ 2M Karras sampler.
Using any sampler other than UniPC and DPM++ SDE works fine. 

Also SDP optimizer is slow on ARC.
InvokeAI's or Sub-quadratic works the best for ARC.

@vladmandic should we change the default optimizer to InvokeAI's for ARC GPUs?
SDP uses double the VRAM and runs at half the speed for some reason on ARC.


`╭──────────────────────────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────────────────────────╮
│ /home/disty/Apps/automatic/modules/call_queue.py:33 in f                                                                                                   │
│                                                                                                                                                            │
│    32 │   │   │   try:                                                                                                                                     │
│ ❱  33 │   │   │   │   res = func(*args, **kwargs)                                                                                                          │
│    34 │   │   │   │   progress.record_results(id_task, res)                                                                                                │
│                                                                                                                                                            │
│ /home/disty/Apps/automatic/modules/img2img.py:159 in img2img                                                                                               │
│                                                                                                                                                            │
│   158 │   else:                                                                                                                                            │
│ ❱ 159 │   │   processed = modules.scripts.scripts_img2img.run(p, *args)                                                                                    │
│   160 │   │   if processed is None:                                                                                                                        │
│                                                                                                                                                            │
│                                                                  ... 21 frames hidden ...                                                                  │
│                                                                                                                                                            │
│ /home/disty/Apps/automatic/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py:356 in q_sample                                         │
│                                                                                                                                                            │
│    355 │   │   noise = default(noise, lambda: torch.randn_like(x_start))                                                                                   │
│ ❱  356 │   │   return (extract_into_tensor(self.sqrt_alphas_cumprod, t, x_start.shape) * x_star                                                            │
│    357 │   │   │   │   extract_into_tensor(self.sqrt_one_minus_alphas_cumprod, t, x_start.shape                                                            │
│                                                                                                                                                            │
│ /home/disty/Apps/automatic/repositories/stable-diffusion-stability-ai/ldm/modules/diffusionmodules/util.py:105 in extract_into_tensor                      │
│                                                                                                                                                            │
│   104 │   b, *_ = t.shape                                                                                                                                  │
│ ❱ 105 │   out = a.gather(-1, t)                                                                                                                            │
│   106 │   return out.reshape(b, *((1,) * (len(x_shape) - 1)))                                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: gather(): Expected dtype int64 for index`

**Comment by vladmandic** [comment]
ah, seems you found the cause. 

> Also SDP optimizer is slow on ARC.
> InvokeAI's or Sub-quadratic works the best for ARC.

not surprising as both xformers and sdp are highly tuned for cuda.
while invokeai's is best pure-software cross-optimizer.

@vladmandic should we change the default optimizer to InvokeAI's for ARC GPUs?

i always have an open ask for platform experts to tell me what best defaults are for that platform as i don't have them to test all possible combos. 
so yes, i can change it.

**Comment by vladmandic** [comment]
@Disty0 actually, have you tried Doggettx's? that is also pure-software and should be slightly more optimized than InvokeAI?

**Comment by Disty0** [comment]
> @Disty0 actually, have you tried Doggettx's? that is also pure-software and should be slightly more optimized than InvokeAI?


They are close but InvokeAI is slightly faster.

![image](https://github.com/vladmandic/automatic/assets/47277141/a961f9b4-f520-40bf-a29c-e59b7d5c368c)


Since I am getting bottlenecked by my CPU, I did my test at 768x768:

```
InvokeAI: 2.85
Doggettx: 2.80
Sub-quad: 2.50
Scaled-d: 2.40
Xformers: 2.40
Split-at: 2.00
Disabled: 2.40
```

**Comment by HyunJae5463** [comment]
> just to confirm, you're using `--use-ipex` to enable arc support?
> 
> this is veeeery deep in torch, its quite possible that arc does not implement some features used by when combo unipc sampler + sdp cross-attention are used. i cannot reproduce this on cuda.
> 
> not sure what i can do about this, but just in case looping in @Disty0 as he's done pretty much all of ipex specific code

Isn't ipex for Linux only? I'm using --use-directml.
I noticed however that it happens when i try to go up too high with the resolution without Highres Fix as well so it might just be a false "not enough GPU Memory" error because if i start going a bit lower it gives Errors like 
`RuntimeError: Could not allocate tensor with 3600000000 bytes. There is not enough GPU video memory available!`
instead which is weird because my GPU has 16GB Vram and it already says it could not even allocate 3GB or so.

**Comment by HyunJae5463** [comment]
> > Isn't ipex for Linux only? I'm using --use-directml.
> 
> yes, it is, but since you didn't write much, i asked the wrong question. thats why i always ask people to write appropriate description AND add platform info, not just "windows"
> 
> directml is really inefficient. but until both intel (for ipex) and amd (for rocm) release native support for windows, that's the only game in town. which cross-optimization method are you using? default sdp eats soo much memory on directml.

Tried InvokeAI and Sub-quadratic as the other person suggested.
Maybe i should just install Linux via a VM or something if that works better.

**Comment by vladmandic** [comment]
I'm using WSL2 inside Windows as my daily driver for a looong time now, only use SD on Windows for specific tests.

**Comment by Disty0** [comment]
IPEX does run inside WSL2 but Other reported that WSL2 has ghost VRAM usage issues. 
WSL2 adds 512 MB VRAM usage with every generation. I can't reproduce this in native Linux.

You can follow this guide until "Creating a Python* Virtual Environment" step.
Skip this step and steps below that and switch to installing Stable Diffusion for Linux.

https://www.intel.com/content/www/us/en/developer/articles/technical/running-tensorflow-stable-diffusion-on-intel-arc.html#gs.yjigol

**Comment by vladmandic** [comment]
any updates on this issue?

**Comment by Disty0** [comment]
There are datatype issues unique to ipex version 1.13.120+xpu that wasn't an issue with 1.13.10+xpu like this one: https://github.com/vladmandic/automatic/issues/1144#issuecomment-1562173240

I am waiting for a new version of ipex to see if this issue still persists.

**Comment by vladmandic** [comment]
sounds like fun :(

**Comment by Disty0** [comment]
This commit should fix this. If it still persist, you can write a message again with more details.
https://github.com/vladmandic/automatic/commit/09141ee1a8f51df7ef0a4b0c2ffbd053a3628b74
