### ISSUE TITLE
[Feature]: Change gradio temporary file names

### ISSUE THREAD

**Issue by bilwis** [vladmandic/automatic#1153]
### Issue Description

Since commit e129e83, files in gradio are served from `http://192.168.2.158:7860/file=/tmp/gradio/[...]/image.png` instead of `http://192.168.2.158:7860/file=/home/[user]/automatic/outputs/text/[filename].jpg`, making it very annoying to just drag and drop files from the browser to where I want them (since they're all named image.png).

Reverting to d647bb5 and gradio 3.31.0 solves this issue, without any changes to the `config.json`. 

### Version Platform Description

Python 3.10.9 on Linux
Torch 2.1.0.dev20230524+cu121
Torch backend: nVidia CUDA 12.1 cuDNN 8801
Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24575 Arch (8, 6) Cores 82

Browser: Microsoft Edge Version 113.0.1774.50 (Official build) (64-bit)

**Comment by vladmandic** [comment]
at best, this would be a feature request as changes to temp file names cannot be considered an issue.

**Comment by bilwis** [comment]
Sure. Is this intended behaviour from gradio, that is, should I take it to their repo?

**Comment by vladmandic** [comment]
the problem is i know why they did it, so i don't think they would change it.
but i'll look if it can be improved from this side - just not as an issue.

**Comment by bilwis** [comment]
I understand, I'm sure you got more important stuff to do. It just kind of blindsided me because I'm so used to just dragging "good images" directly from the Process Tab into my "good images folder".

**Comment by vladmandic** [comment]
done.
