### ISSUE TITLE
[Issue]: Denoising strength option suddenly gone with legacy `use_old_hires_fix_width_height` option ON.

### ISSUE THREAD

**Issue by mart-hill** [vladmandic/automatic#1159]
### Issue Description

I noticed this option being missing with the "legacy" hires fix option active, at least on gradio-soft theme:
![image](https://github.com/vladmandic/automatic/assets/55754730/dcf72cfb-f680-4551-9e28-95cbd4aa452e)

There's no such issue with the "usual" hires fix option though. 🙂

### Version Platform Description

20:23:46-489438 INFO     Running extension preloading
20:23:46-503444 INFO     Starting SD.Next
20:23:46-506438 INFO     Python 3.10.9 on Windows
20:23:46-837940 INFO     Version: 684851ae Wed May 24 13:50:01 2023 -0400
20:23:47-251758 INFO     Setting environment tuning
20:23:47-269260 INFO     nVidia CUDA toolkit detected
20:23:49-493262 INFO     Torch 2.0.1+cu118
20:23:49-527260 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
20:23:49-529758 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24575 Arch (8, 6) Cores 82

**Comment by vladmandic** [comment]
fixed.
