### ISSUE TITLE
[Issue]: Custom Temp directory no longer working

### ISSUE THREAD

**Issue by greythax** [vladmandic/automatic#1160]
### Issue Description

Looks like the settings for the temp directory (Settings->System Paths->Directory for temporary images; leave empty for default) are no longer working.  The path supplied is being ignored and instead %temp%/gradio is being used to store temporary images.  This seems to occur whether "always save all generated images" is selected or not.

### Version Platform Description

Version: 9e66d88e Wed May 24 15:21:49 2023 -0400
Platform: Windows 10
Browser:  Chrome
Config file value: "temp_dir": "R:\\temp",

Note, my R drive is a ram disk, but has been working fine in previous versions.

**Comment by vladmandic** [comment]
fixed.
