### ISSUE TITLE
[Issue]: Model does not finish loading on startup

### ISSUE THREAD

**Issue by 1r00t** [vladmandic/automatic#1161]
### Issue Description

When I run `./webui.sh` everything looks fine as always, but when I open the UI in Firefox or Chrome, the model does not finish loading and I cannot kill webui.sh with ctrl-c, it takes like 3 minutes to kill the process.

Everything is frozen.

I tried removing the env and reinstalled everything a few times now.
Tried downloading the default model because maybe my files are corrupted, but no.
Tried with `--disable-queue`, same thing.
No user extensions installed.
No idea what is causing this. `--debug` does not show anything special, and setup.log looks normal to me.

This is what the settings tab looks like:
![grafik](https://github.com/vladmandic/automatic/assets/9479785/5aede5aa-f77e-4156-b560-4d5597f4e5ab)

This is after I killed the process, don't know if it helps... 
![grafik](https://github.com/vladmandic/automatic/assets/9479785/5d6c8594-f306-469c-9cbe-b1eca567d232)

Please let me know if and how I can provide more informations about this.

## Logs
[setup.log](https://github.com/vladmandic/automatic/files/11562960/setup.log)
[startup_with_debug.log](https://github.com/vladmandic/automatic/files/11563047/startup_with_debug.log)
[startup.log](https://github.com/vladmandic/automatic/files/11563056/startup.log)

### Version Platform Description

- Windows 10 Pro 22H2
- WLS2
- Firefox 113.0.1 (64-Bit)
- GTX 1650
- Ubuntu: 20.04.6 LTS
- Python: 3.10.11
- automatic version: 9e66d88e Wed May 24 15:21:49 2023 -0400
- WSL-Version: 1.2.5.0
- Kernelversion: 5.15.90.1
- Windows-Version: 10.0.19045.2965

**Comment by 1r00t** [comment]
There are some POST requests that don't seem to resolve:
![grafik](https://github.com/vladmandic/automatic/assets/9479785/81a72943-525a-4f12-9de2-499e4fb6f115)

**Comment by 1r00t** [comment]
### Interesting update
I tried to refresh the page, it took like 3 minutes before anything happened,
then all of a sudden everything seems to load like normal.
The model loading animation stopped.

I am able to generate images but generation stops at 100% for another 3 minutes, then it finishes.

Looks like something is taking forever to load.

![grafik](https://github.com/vladmandic/automatic/assets/9479785/a81d1d72-34d0-4dd4-b33e-bb69f72a6b31)

**Comment by vladmandic** [comment]
you've posted a lot of useful data, but not the log itself which would show model loading - can you run `./webui.sh --debug` and capture log - it will show timestampts for each stage of model loading.

**Comment by 1r00t** [comment]
> you've posted a lot of useful data, but not the log itself which would show model loading - can you run `./webui.sh --debug` and capture log - it will show timestampts for each stage of model loading.

I provided the debug log in the initial post. At the bottom. "startup_with_debug.log"

**Comment by vladmandic** [comment]
`startup_with_debug.log` ends too early - you say that eventually it does get loaded and you can generate, but that is not captured.

end of log as it is is:
```log
11:03:46-863684 DEBUG    Model dict loaded: {'ram': {'used': 1.23, 'total': 15.62}, 'gpu': {'used': 0.78, 'total': 4.0}, 'retries': 0, 'oom': 0}
11:03:46-877378 DEBUG    Model config loaded: {'ram': {'used': 1.23, 'total': 15.62}, 'gpu': {'used': 0.78, 'total': 4.0}, 'retries': 0, 'oom': 0}
11:03:47-364046 INFO     Model created from config: /home/kroko/projects/vlad/configs/v1-inference.yaml
11:03:47-365618 DEBUG    Model weights loading: {'ram': {'used': 2.26, 'total': 15.62}, 'gpu': {'used': 0.78, 'total': 4.0}, 'retries': 0, 'oom': 0}
```

**Comment by 1r00t** [comment]
Here is a new one

[startup_with_debug_2.log](https://github.com/vladmandic/automatic/files/11564544/startup_with_debug_2.log)


![grafik](https://github.com/vladmandic/automatic/assets/9479785/1585dcc5-9fce-4785-bb28-af2c78b7707e)

**Comment by 1r00t** [comment]
This one is after I wait a long time and refresh the page, sometimes the model loading animation is gone and the UI is responding.
Here I was able to generate an image after like 5 minutes of waiting for the page to refresh.

[startup_with_debug_3.log](https://github.com/vladmandic/automatic/files/11564721/startup_with_debug_3.log)

**Comment by sebaxakerhtc** [comment]
Looks like [this](https://github.com/vladmandic/automatic/issues/1113) one

**Comment by 1r00t** [comment]
The `Server alive` message should appear every two minutes right? Look at this log, it didn't log that message for about 12 minutes.

```bash
14:32:14-933274 INFO     Model created from config: /home/kroko/projects/vlad/configs/v1-inference.yaml
14:32:14-934862 DEBUG    Model weights loading: {'ram': {'used': 3.73, 'total': 23.47}, 'gpu': {'used': 0.78,
                         'total': 4.0}, 'retries': 0, 'oom': 0}
14:32:16-097756 DEBUG    Model weights loaded: {'ram': {'used': 10.66, 'total': 23.47}, 'gpu': {'used': 0.78,
                         'total': 4.0}, 'retries': 0, 'oom': 0}
14:32:16-102321 DEBUG    Model weights moved: {'ram': {'used': 10.66, 'total': 23.47}, 'gpu': {'used': 0.78, 'total':
                         4.0}, 'retries': 0, 'oom': 0}
14:32:16-110929 INFO     Applying scaled dot product cross attention optimization
14:32:16-121199 INFO     Model loaded in 2.1s (load=0.5s create=0.4s apply=1.2s)
14:32:16-387914 DEBUG    gc: collected=131 device=cuda {'ram': {'used': 10.66, 'total': 23.47}, 'gpu': {'used': 0.78,
                         'total': 4.0}, 'retries': 0, 'oom': 0}
14:32:16-390006 INFO     Model load finished: {'ram': {'used': 10.66, 'total': 23.47}, 'gpu': {'used': 0.78, 'total':
                         4.0}, 'retries': 0, 'oom': 0}
14:32:16-792261 DEBUG    gc: collected=0 device=cuda {'ram': {'used': 6.69, 'total': 23.47}, 'gpu': {'used': 0.78,
                         'total': 4.0}, 'retries': 0, 'oom': 0}
14:32:16-793716 INFO     Startup time: 12.1s (torch=2.2s gradio=1.4s libraries=0.5s scripts=1.6s onchange=0.1s
                         ui=0.9s launch=0.1s scripts app_started_callback=0.1s checkpoint=5.2s)
14:32:16-795523 INFO     Memory used: 6.69 total: 23.47
14:44:00-370366 DEBUG    Server alive: True Memory used: 6.74 total: 23.47
14:45:59-531740 DEBUG    Server alive: True Memory used: 6.75 total: 23.47
14:47:59-695981 DEBUG    Server alive: True Memory used: 6.75 total: 23.47
14:49:59-861533 DEBUG    Server alive: True Memory used: 6.75 total: 23.47
```

**Comment by vladmandic** [comment]
its not even close to the issue you've mentioned, that is a server<->browser communication issue. what you have is a true process hang for couple of minutes. yes, "server alive" should log every 120 sec and that is as low-level check as possible as it happens in parent thread regardless of what actual server is doing (it could be busy loading a model or anything, but there is no valid reason why thread would not return immediately for `instance.thread.is_alive()`
and previous message `memory used` is printed after server is started - so it really is a full thread unresponsive for couple of minutes - that is baaad. and all this is happening after everything has been completely (model loaded without issues, etc.)

i just made some changes, but i doubt it will help much although i did find one issue with model loading.

please update the repo and then in `launch.py` replace this section (near the very end):

```python
try:
    alive = instance.thread.is_alive()
except:
    alive = False
if round(time.time()) % 120 == 0:
    installer.log.debug(f'Server alive: {alive} Memory {get_memory_stats()}')
```

with:

```python
installer.log.debug(f'Server alive check start')
try:
    alive = instance.thread.is_alive()
except:
    alive = False
installer.log.debug(f'Server alive check finished: {alive}')
```

**Comment by 1r00t** [comment]
I did what you said, updated repo (fc82ea2d) and replaced in launch.py
Looks like it hangs quite a lot if you look at the timings.
As soon as I open the UI in my browser it is updating only every few minutes

```bash
15:11:12-599662 DEBUG    Server alive check finished: True
15:11:13-602823 DEBUG    Server alive check start
15:11:13-606896 DEBUG    Server alive check finished: True
15:11:14-612620 DEBUG    Server alive check start
15:11:14-617418 DEBUG    Server alive check finished: True
15:11:15-622899 DEBUG    Server alive check start
15:11:15-627532 DEBUG    Server alive check finished: True
15:11:16-633030 DEBUG    Server alive check start
15:11:16-636966 DEBUG    Server alive check finished: True
15:11:17-641840 DEBUG    Server alive check start
15:11:17-642865 DEBUG    Server alive check finished: True
15:11:18-644987 DEBUG    Server alive check start
15:11:18-646125 DEBUG    Server alive check finished: True
15:11:19-648192 DEBUG    Server alive check start
15:11:19-649292 DEBUG    Server alive check finished: True
15:11:20-651778 DEBUG    Server alive check start
15:11:20-656884 DEBUG    Server alive check finished: True
15:11:21-661975 DEBUG    Server alive check start
15:11:21-665953 DEBUG    Server alive check finished: True
15:11:22-670933 DEBUG    Server alive check start
15:11:22-671956 DEBUG    Server alive check finished: True
15:11:23-674041 DEBUG    Server alive check start
15:11:23-675289 DEBUG    Server alive check finished: True
15:11:24-677343 DEBUG    Server alive check start
15:11:24-678485 DEBUG    Server alive check finished: True
15:11:25-685541 DEBUG    Server alive check start
15:11:25-697604 DEBUG    Server alive check finished: True
15:11:26-710297 DEBUG    Server alive check start
15:11:26-711335 DEBUG    Server alive check finished: True
15:11:27-713434 DEBUG    Server alive check start
15:11:27-714595 DEBUG    Server alive check finished: True
15:11:28-717236 DEBUG    Server alive check start
15:11:28-718327 DEBUG    Server alive check finished: True
15:11:29-720593 DEBUG    Server alive check start
15:11:29-721715 DEBUG    Server alive check finished: True
15:13:40-240743 DEBUG    Server alive check start
15:13:40-247192 DEBUG    Server alive check finished: True
15:15:53-360859 DEBUG    Server alive check start
15:15:53-380501 DEBUG    Server alive check finished: True
```

**Comment by 1r00t** [comment]
[server_alive.log](https://github.com/vladmandic/automatic/files/11565369/server_alive.log)

Here is another run. Just like before:

1. 1sec steps
2. loading UI
3. minute steps, model loading animation
4. wait a few minutes
5. 1sec steps and model loading animation is gone.

**Comment by vladmandic** [comment]
seems like gradio server thread is completely unresponsive sometimes (not busy, fully unresponsive).
only thing that comes to mind is to check is os is performing some excessive swapping perhaps? and thing in os system logs?
what are your system specs? and since you're running in WSL, did you give it sufficient resources? I believe defaults by default are quite low.

for example, my `/mnt/C/Users/mandi/.wslconfig`

    [wsl2]
    memory=28GB
    swap=0
    nestedVirtualization=false
    debugConsole=false
    guiApplications=true
    localhostForwarding=true
    kernel=C:\\Users\\mandi\\WSL\\vmlinux-6.1.21.2

**Comment by 1r00t** [comment]
this is my `.wslconfig`:

```yaml
[wsl2]
memory=24GB
swap=32GB
```

this is my system:

- Intel Core i7 9750H
- Nvidia GeForce GTX 1650
- 32GB RAM


looking into system logs now...

**Comment by vladmandic** [comment]
any updates?

**Comment by 1r00t** [comment]
> any updates?

No sorry. That's on my work laptop. My home desktop is working alright as always. No idea what it is. I'm back in office tomorrow and will try a few different things. After that we may close the issue...

**Comment by 1r00t** [comment]
So I deleted the whole repo again and set it up again and let it download the base model.

Now it works. No idea why. I'm closing this issue and I'm sorry I could not provide useful insights. If anyone else is getting this, maybe a reinstall could help.
