### ISSUE TITLE
[Issue]: PLMS Sampler fails on latest Vlad Diffusion Version

### ISSUE THREAD

**Issue by abline11** [vladmandic/automatic#1164]
### Issue Description

I made a brand new clone of Vlad Diffusion yesterday 24th May (Version: 9e66d88e Wed May 24 15:21:49 2023 -0400).  Everything seems to be working fine (and very fast), but the PLMS sampling method fails with on the second pass with: Exception: bad sampler name: None.  Any idea what is causing this and, if so, how to fix it? It happens both when I use no arguments and when I use –-medvram.

### Version Platform Description

(Windows 11, Nvidia 3070Ti (8GB VRAM) - 532.03 driver, Microsoft Edge)

**Comment by vladmandic** [comment]
i haven't seen anyone use PLMS in a loooong time. PLMS does not support img2img (never did), so in second pass a fallback sampler value (set it in settings -> samplers) is used. that fallback did not execute correctly, fixed now.

**Comment by abline11** [comment]
Thanks for the quick response
