### ISSUE TITLE
[Issue]: Several plugins seem to be causing 'maximum depth' error.

### ISSUE THREAD

**Issue by bbecausereasonss** [vladmandic/automatic#1165]
### Issue Description

I have had to disable 
- composable lora
- segment anything

and continue to get this error

"13:30:00-904824 ERROR    Exception: maximum recursion depth exceeded while calling a Python object
13:30:00-906826 ERROR    Arguments: args=('task(krheqxsv4tcr33p)', '(((masterpiece))), (((best quality))),
                         ((ultra-detailed)), (highly detailed CG illustration), ((an extremely delicate and
                         beautiful)),cinematic light,((1mechanical girl)),solo,(cowboy shot:1.2),(machine made
                         joints:1.2),((machanical limbs)),(blood vessels connected to tubes),(mechanical vertebra
                         attaching to back),((mechanical cervial attaching to neck)),expressionless,(wires and cables
                         attaching to neck:1.2),(wires and cables on head:1.2),(character focus),science fiction,extreme
                         detailed,colorful,highest detailed, loongs,fengs,background,', 'EasyNegative, drawn by
                         bad-artist, sketch by bad-artist-anime, (bad_prompt:0.8), (artist name, signature,
                         watermark:1.4), (ugly:1.2), (worst quality, poor details:1.4), bad-hands-5, badhandv4, blurry',
                         [], 10, 6, False, False, 1, 1, 7, 1, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2,
                         'Latent', 0, 0, 0, [], 0, False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 1,
                         'None', 2, False, 10, 1, 1, 64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4,
                         0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background',
                         0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2,
                         0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2,
                         -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 3072, 192, True, True,
                         True, False, False, 7, 100, 'Constant', 0, 'Constant', 0, 4, False, 'x264', 'blend', 10, 0, 0,
                         False, True, True, True, 'intermediate', 'animation', <controlnet.py.UiControlNetUnit object at
                         0x000001BB091A2F80>, False, '', 0, 'Send to Canvas Editor', False, 1, 0.15, False, 'OUT',
                         ['OUT'], 5, 0, 'Bilinear', False, 'Pooling Max', False, 'Lerp', '', '', False, False, None,
                         True, False, False, 'Horizontal', '1,1', '0.2', False, False, False, 'Attention', False, '0',
                         '0', '0.4', None, 1, 0, False, '1:1,1:2,1:2', '0:0,0:0,0:1', '0.2,0.8,0.8', 150, 0.2, 1, 1, 1,
                         1, 1, 1, 1, 1, 1, 1, 1, 1, False, False, 'positive', 'comma', 0, False, False, '', 1, '', [], 0,
                         '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, 50, False, 4.0, '',
                         10.0, 'Linear', 3, False, 30.0, True, False, False, 0, 0.0, 'Lanczos', 1, True, 0, 0, 0.001, 75,
                         0.0, False, True, 'Blur First V1', 0.25, 10, 10, 10, 10, 1, False, '', '', 0.5, 1, False, 5,
                         'all', 'all', 'all', '', '', '', '1', 'none', False, '', '', 'comma', '', True, '', 10.0, 30.0,
                         True, 0.0, 'Lanczos', 1, 0, 0, 75, 0.0001, 0.0, False, True, False, 0, 0, 512, 512, False, True,
                         False, False, 0, 1, False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'],
                         2.5, 'polylines_sharp', 0, False, False, False, False, False, False, 'u2net', False, True,
                         False, 'Not set', True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set',
                         1.3, 'Not set', 1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not
                         set', 1.3, 'Not set', False, 'None') kwargs={}
13:30:00-918828 ERROR    gradio call: RecursionError
╭────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\xxxx\Deep\automatic\modules\call_queue.py:34 in f                                                           │
│                                                                                                                       │
│    33 │   │   │   try:                                                                                                │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                     │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                           │
│                                                                                                                       │
│ C:\Users\xxxx\Deep\automatic\modules\txt2img.py:57 in txt2img                                                        │
│                                                                                                                       │
│   56 │   if processed is None:                                                                                        │
│ ❱ 57 │   │   processed = process_images(p)                                                                            │
│   58 │   p.close()                                                                                                    │
│                                                                                                                       │
│                                               ... 980 frames hidden ...                                               │
│                                                                                                                       │
│ C:\Users\xxxx\Deep\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1627 in __setattr__                   │
│                                                                                                                       │
│   1626 │   │   params = self.__dict__.get('_parameters')                                                              │
│ ❱ 1627 │   │   if isinstance(value, Parameter):                                                                       │
│   1628 │   │   │   if params is None:                                                                                 │
│                                                                                                                       │
│ C:\Users\xxxx\Deep\automatic\venv\lib\site-packages\torch\nn\parameter.py:10 in __instancecheck__                    │
│                                                                                                                       │
│     9 │   │   return super().__instancecheck__(instance) or (                                                         │
│ ❱  10 │   │   │   isinstance(instance, torch.Tensor) and getattr(instance, '_is_param', False)                        │
│    11                                                                                                                 │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RecursionError: maximum recursion depth exceeded while calling a Python object"

### Version Platform Description

Chrome, Win11x64, Latest Repo

**Comment by vladmandic** [comment]
please create issue using extension template.
btw, i'm not sure about segment anything, but there are a lot of problems with composable lora.
