### ISSUE TITLE
[Feature]: Nvidia GeForce Driver Promises Doubled Stable Diffusion Performance

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#1167]
### Feature description

Is it possible to implement the support for the new drivers inside the code?

https://www.tomshardware.com/news/nvidia-geforce-driver-promises-doubled-stable-diffusion-performance

https://www.reddit.com/r/StableDiffusion/comments/13r0fa5/new_optimized_nvidia_drivers_for_sd/

**Comment by vladmandic** [comment]
That is 100% FUD, what they came up with support for tensor cores inside ONNX backend, so if models are compiled to ONNX format, they can execute using tensor cores.

But you can already compile model to TensortRT and do the same.

So what's the big deal? MS is pushing ONNX inside Azure, not Torch.

And that's it.

**Comment by ShmuelRonen** [comment]
Thanks!
