### ISSUE TITLE
[Feature]: Toggle Textual inversion in extra networks

### ISSUE THREAD

**Issue by redrightsmile** [vladmandic/automatic#1169]
### Issue Description

When I click on the "textual inversion" card for the second time, I expect it to be removed.

However, the "textual inversion" string is added a second time, and this occurs each time I press:

![Animation1](https://github.com/vladmandic/automatic/assets/119710513/8452bb88-2f80-4c60-8299-993b80642de2)

The function should mirror the behavior of loras and be toggleable:

![Animation2](https://github.com/vladmandic/automatic/assets/119710513/5313cae7-4d70-45e5-ae55-6e798f1b88cb)

### Version Platform Description

Windows 10
Version: e0486799 Fri May 26 00:13:56 2023 +03002023 -0400
Browser: Chrome

**Comment by vladmandic** [comment]
valid low-priority feature request, not an issue as such.

**Comment by brunogcar** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/10803

for reference and inspiration

**Comment by vladmandic** [comment]
done.
