### ISSUE TITLE
[Issue]: CSS problem: resuse seed button hidden

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#117]
### Issue Description

The reuse seed button (CSS: id = "txt2img_reuse_seed") stays somehow hidden (display: none). This is marked down in the user.css but obviously then not shown via script.

![Zwischenablagebild](https://user-images.githubusercontent.com/122026301/231893802-f39130e8-cee3-4b7b-b90f-213562640eb8.png)

### Platform Description

Win10, Firefox 106

**Comment by vladmandic** [comment]
by design, for most users that button is just confusing and doesn't add much value.

**Comment by Woisek** [comment]
Sorry, with all due respect, but that's nonsense. What's confusing about that? Even more so after such a long time? I can't imagine that. And if this button would not be "needed", why the field at all? Where to get the seed for comparative generations?
Don't be angry, but the button is much more important than the clip skip that was added. 🙄

BTW, does the user.css actually remain untouched or could it be changed sometime/somehow? I have a lot of changes done there and don't want to lose it.

**Comment by vladmandic** [comment]
i need to clean-up `user.css` and merge it with `system.css` so it once again becomes empty by default so users can have their own values.

regarding button, i made the choice, but i could be persuaded otherwise, i just didn't see a strong reason to have it.

**Comment by AlUlkesh** [comment]
Ah, I see. Take your time. I'm glad you took on this fork. Thanks again!

No, the button choice is fine. It just wasn't obvious to me.

**Comment by Woisek** [comment]
Yes, you have made a decision, but honestly, not necessarily a good one. 😋
If only to test different prompts with the same seed, it is important to have the button without having to search too much.
We are talking about 35 pixels here, it can't be the space. And that it confuses the user, sorry, I don't buy that.

I use the button almost every 3rd or 4th time, when I either try out styles or test my loras. If I had to pick the seed out of a minitext every time, I would go insane. 🤪

**Comment by vladmandic** [comment]
i made a decision and you made a counter argument which is ok, but i have to say not the way you said.
"Sorry, with all due respect, but that's nonsense" basically is opposite of "due respect". 
i'm always willing to listen to feedback and change my opinion, but lets stick to actual facts and usability.

**Comment by Woisek** [comment]
Sorry if you misunderstood. It wasn't intended that way. And yes, I agree with facts and usabiility. Where or what are they for your decision to remove this button? Did you made a poll on that or was it your personal feel? I just want to know from where this come from as I absolutely don't understand it.

**Comment by vladmandic** [comment]
it was a personal feel as neither me or my friends ever used it and util few days ago this fork was pretty much for couple of people only. now its getting popular and i'm open to suggestions.

**Comment by Woisek** [comment]
Unfortunately, i can't say more than that I'm pretty sure that the vast majority of users find this button important, just like me. 🙄
Maybe it really should be voted on.

**Comment by vladmandic** [comment]
imo, voting is not the way to make technical decisions as who ever is loudest wins. its about facts. 
i did say "you made a counter argument which is ok" - you gave me a valid use case and that is good enough, i'll add it back.

**Comment by Woisek** [comment]
> imo, voting is not the way to make technical decisions

Because of a personal feeling but also not ... 😉
Anyway, I'm just trying to help. And again, I'm sorry if you misunderstood me, it wasn't meant as you maybe might have perceived it. You have my respect for what you do because I come from the same corner (developer) and know what's all behind it and maybe that's why I'm so eager to get it right.
