### ISSUE TITLE
[Feature]: Possibility to clear out dropdowns in "Merge models" tab

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#1175]
### Feature description

I just created a custom inpainting model from a checkpoint and this requires all three dropdowns populated. When it finished, I noticed, there is no way to clear the dropdowns once it was populated with an entry.
A problem arises, when one now want to merge two models. It's not possible because the third dropdown can't be cleared.

It would be necessary to be able to clear the dropdowns.

### Version Platform Description

Win10, Firefox

**Comment by vladmandic** [comment]
done.

**Comment by Woisek** [comment]
Perfect, thanks!
