### ISSUE TITLE
[Question]: about --api flag

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#1180]
### Issue Description

How to add --api to the boot process? (to webui.bat?)

**Comment by mobilehacker** [comment]
Its enabled by default, you can remove it safely!

**Comment by ShmuelRonen** [comment]
Thanks!

**Comment by dan4ik94** [comment]
For the future, you can create a .bat file in automatic directory and pass it the needed arguments, for example:

```
@echo off
set COMMANDLINE_ARGS=--no-download --no-hashing --autolaunch --skip-torch
call webui.bat
```

**Comment by vladmandic** [comment]
btw, discussions are better place for questions. closing as not-an-issue.
