### ISSUE TITLE
[Issue]: Broken inpaint after diffusers update

### ISSUE THREAD

**Issue by dan4ik94** [vladmandic/automatic#1183]
### Issue Description

After the last diffusers commit, inpaint randomly stops working on my side. I get the following error:
```
WARNING  Init image not set
WARNING  No result returned from function
```

A hard reset to https://github.com/vladmandic/automatic/commit/8022de74640ab62c27edefca0dd9875d041f36a3 fixes the problem. Switching to img2img, generating something then switching back to inpaint seems to also help.

![6EJqxNl](https://github.com/vladmandic/automatic/assets/84623377/420466c5-0d54-48ef-8841-aa42375052bb)

### Version Platform Description

Python 3.10.10 on Windows
Version: 421db2c0 Sat May 27 07:37:25 2023 -0400

 Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-system-info', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR', 'adetailer', 'canvas-zoom', 'loopback_scaler',
                         'sd-webui-regional-prompter', 'stable-diffusion-webui-fix-image-paste']

**Comment by vladmandic** [comment]
fixed.
