### ISSUE TITLE
[Feature] TensorRT extension from A1111

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#1185]
### Discussed in https://github.com/vladmandic/automatic/discussions/1184

<div type='discussions-op-text'>

<sup>Originally posted by **neuralweights** May 27, 2023</sup>
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/10684#discussioncomment-6019118

My dreams come true. I did not try it out yet but this looks promising. I hope it is compatible with SD.Next? I think it is</div>

**Comment by vladmandic** [comment]
i'm tracking it and its high on my radar, just diffusers integration right now have a higher priority for me.

**Comment by x-ili-x** [comment]
I tried it locally in the C# demo and it's crazy fast. It's gonna be so cool to have it implemented. Thanks for all the hard work, you're a legend.

**Comment by vladmandic** [comment]
Since this thread got that much attention, please take a look at #1195

**Comment by cool-bigdogs-tshirt** [comment]
it's compatible-ish. cherry-picked the relevant commit from the upstream dev branch and got it working far enough to convert to ONNX. waiting on the tensorrt compile now, will PR once it's looks like it's working.

only change so far is that they're calling `apply_optimizations` as a method on `StableDiffusionModelHijack` instead of as a module-level function, and they're passing in the string `'None'` to undo optimizations.

**Comment by cool-bigdogs-tshirt** [comment]
`Aborted (core dumped)` but i don't think that's the extension's fault :(
will push my branch anyways

**Comment by cool-bigdogs-tshirt** [comment]
https://github.com/vladmandic/automatic/pull/1199 is up if anyone else wants to try, i'm still still struggling to compile though

**Comment by vladmandic** [comment]
nice job with the pr, i'll dive into it when i clear up my todo a little bit...

**Comment by GalaxyTimeMachine** [comment]
I opened an issue with NVIDIA and they responded that it would be easy to implement in SD.Next. Does this help? https://github.com/NVIDIA/Stable-Diffusion-WebUI-TensorRT/issues/8#issuecomment-1768063428

**Comment by vladmandic** [comment]
tracked via newer #2329
