### ISSUE TITLE
[Feature]: Searchable Settings

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1188]
### Feature description

The number of settings and options in the Settings tab is getting quite large, it'd be nice to have a search function in the Settings tab.

### Version Platform Description

n/a

**Comment by vladmandic** [comment]
i love the idea. not easy to do, but i'll put it on my backlog.

**Comment by vladmandic** [comment]
actually, i had an inspiration so its done :)

**Comment by brknsoul** [comment]
ROFL.. nice!
