### ISSUE TITLE
[Issue]: Black Images are generated

### ISSUE THREAD

**Issue by huntermilo1** [vladmandic/automatic#1191]
### Issue Description

After running SD from Web UI a blank image is generated. I have tried all possible combinations from "Compute Settings", a black image is generated for all combinations of settings selected.

Below are the last tried settings. Please guide me or provide a solution so proper images are generated. Incase any additional information is required, please let me know.

![image](https://github.com/vladmandic/automatic/assets/133333647/cdc0b64c-52b2-49c8-a7fc-956562a3c9f4)

### Version Platform Description

- Python 3.10.9 on Windows
- Version: 851d1296 Sat May 27 15:49:54 2023 -0400
- Torch 2.0.1+cu118
- 12:37:49-423671 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
- 12:37:49-426676 INFO     Torch detected GPU: NVIDIA GeForce GTX 1650 Ti VRAM 4096 Arch (7, 5) Cores 16
- Server arguments: ['--autolaunch', '--lowvram', '--upgrade']

**Comment by brknsoul** [comment]
Although you have an nvidia GPU, this might help;
https://github.com/vladmandic/automatic/discussions/1087

**Comment by DirtyHamster** [comment]
Black images can happen even with all the settings correct. Check your selected sampler and it's settings in the text to img window. What do you have selected in there?

**Comment by ronbere** [comment]
The black images are really random, I haven't had any for a few days, and tonight they're here again...same sampler

**Comment by DirtyHamster** [comment]
Try these settings in the sampler and see if you get an image out they normally work for me and are reliable enough to test on. DPM++ 2M Karras @ 32 steps and a CFG scale of 12.5

You can also check your model using for errors using: (https://github.com/arenasys/stable-diffusion-webui-model-toolkit) that will tell you if you have a clip error in the model at least or if some of the components in the model are broken. Those components can be independently imported and exported to fix stuff. That doesn't always result in a black image though but it's something to look at.

What model are you using and give me the settings so I or someone else can try doing the same on my own computer as a repeatable event.

**Comment by 1r00t** [comment]
I have to use full precision with `--no-half` with my 1650. Have you tried that?

**Comment by huntermilo1** [comment]
> Try these settings in the sampler and see if you get an image out they normally work for me and are reliable enough to test on. DPM++ 2M Karras @ 32 steps and a CFG scale of 12.5
> 
> You can also check your model using for errors using: (https://github.com/arenasys/stable-diffusion-webui-model-toolkit) that will tell you if you have a clip error in the model at least or if some of the components in the model are broken. Those components can be independently imported and exported to fix stuff. That doesn't always result in a black image though but it's something to look at.
> 
> What model are you using and give me the settings so I or someone else can try doing the same on my own computer as a repeatable event.

I use Henmix Real, Realistic Vision Model and tried with almost all samplers. I used the tool you shared, the models are not having any errors. Also, i tried settings which you provided. No matter what i tried got the same black result. Also, did a clean reinstall still it didn't work. I have been at it 5-6 days.

**Comment by huntermilo1** [comment]
> I have to use full precision with `--no-half` with my 1650. Have you tried that?

yes, didn't work.

**Comment by 1r00t** [comment]
> > I have to use full precision with `--no-half` with my 1650. Have you tried that?
> 
> yes, didn't work.

these are the settings that work for my 1650...
![grafik](https://github.com/vladmandic/automatic/assets/9479785/8ac56c15-ac6b-4b9d-8418-00a3c679c63e)
![grafik](https://github.com/vladmandic/automatic/assets/9479785/6d33cbcc-fa79-475b-827e-08f91f6ec4f0)

**Comment by huntermilo1** [comment]
> > > I have to use full precision with `--no-half` with my 1650. Have you tried that?
> > 
> > 
> > yes, didn't work.
> 
> these are the settings that work for my 1650... ![grafik](https://user-images.githubusercontent.com/9479785/242314072-8ac56c15-ac6b-4b9d-8418-00a3c679c63e.png) ![grafik](https://user-images.githubusercontent.com/9479785/242314220-6d33cbcc-fa79-475b-827e-08f91f6ec4f0.png)

Thanks Mate! this actually worked and generated an image, but there's a catch. Now it seems like SD is not using my GPU as VRAM consumptions has dropped. During image generation system is lagging, freezes often & hard disk usage is at 100%.

**Comment by 1r00t** [comment]
@huntermilo1 maybe try to delete your `config.json`, then start webui and let it recreate it. Then set --no-half again.
This will remove all your configurations though... Like model paths ect...

**Comment by Yodrik** [comment]
You may want to share with us the initial log info from when you start up the UI. I kind of recall (but AMD user), if the device/precision type doesn't line up sometimes it defaults to CPU. Don't quote me on that though, I believe there is a relevant torch parameter sort of log message when that happens.
