### ISSUE TITLE
[Issue]: can't render

### ISSUE THREAD

**Issue by Rogal80** [vladmandic/automatic#1193]
### Issue Description

hi, so today i have this issue :
14:25:03-211483 ERROR    Exception: mat1 and mat2 must have the same dtype
14:25:03-215483 ERROR    Arguments: args=('task(wu0w05iqcidscdr)', 'test', '', [], 35, 3, False, False, 1, 1, 14, 1,
                         -1.0, -1.0, 0, 0, 0, False, 384, 704, True, 0.4, 2, '4x-UltraSharp', 0, 0, 0, [], 0, False,
                         'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64,
                         False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 3072, 192, True, True, True,
                         False, True, 7, 99.9, 'Half Cosine Up', 4.5, 'Half Cosine Down', 3, 4,
                         <controlnet.py.UiControlNetUnit object at 0x000002809948F220>, <controlnet.py.UiControlNetUnit
                         object at 0x00000280B7F32020>, <controlnet.py.UiControlNetUnit object at 0x00000280B7F30460>,
                         <controlnet.py.UiControlNetUnit object at 0x00000280A767C250>, False, False, 'positive',
                         'comma', 0, False, False, '', 1, '', [], 0, '', [], 0, '', [], True, False, False, False, 0,
                         False, None, None, False, None, None, False, None, None, False, None, None, False, 50)
                         kwargs={}
14:25:03-381084 ERROR    gradio call: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Github\Web_UI\automatic\modules\call_queue.py:34 in f                                                            │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ I:\Github\Web_UI\automatic\modules\txt2img.py:57 in txt2img                                                         │
│                                                                                                                     │
│   56 │   if processed is None:                                                                                      │
│ > 57 │   │   processed = process_images(p)                                                                          │
│   58 │   p.close()                                                                                                  │
│                                                                                                                     │
│                                              ... 25 frames hidden ...                                               │
│                                                                                                                     │
│ I:\Github\Web_UI\automatic\extensions-builtin\a1111-sd-webui-lycoris\lycoris.py:734 in lyco_Linear_forward          │
│                                                                                                                     │
│   733 │                                                                                                             │
│ > 734 │   return torch.nn.Linear_forward_before_lyco(self, input)                                                   │
│   735                                                                                                               │
│                                                                                                                     │
│ I:\Github\Web_UI\automatic\venv\lib\site-packages\torch\nn\modules\linear.py:114 in forward                         │
│                                                                                                                     │
│   113 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ > 114 │   │   return F.linear(input, self.weight, self.bias)                                                        │
│   115                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: mat1 and mat2 must have the same dtype

and i didnt add nothing new in terms of extensions and als test with --safe , same issue 

### Version Platform Description

windows 10 , firefox

14:22:40-127272 INFO     Running extension preloading
14:22:40-138273 INFO     Running in safe mode without user extensions
14:22:40-174382 INFO     Starting SD.Next
14:22:40-178382 INFO     Python 3.10.9 on Windows
14:22:40-346381 INFO     Version: 9bf0b1ae Sun May 28 07:46:47 2023 -0400
14:22:40-993296 INFO     Setting environment tuning
14:22:41-005294 INFO     nVidia CUDA toolkit detected
14:22:44-516231 INFO     Torch 2.0.1+cu118
14:22:44-547665 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
14:22:44-553760 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24575 Arch (8, 6) Cores 82
14:22:44-561758 INFO     Verifying requirements
14:22:44-596756 INFO     Installing packages
14:22:44-695756 INFO     Running setup
14:22:44-699364 INFO     Installing repositories
14:22:45-489467 INFO     Installing submodules
14:23:10-752723 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-system-info', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
14:23:10-770722 INFO     Running extension preloading
14:23:10-773722 INFO     Running in safe mode without user extensions
14:23:10-777722 INFO     Server arguments: ['--listen', '--insecure', '--skip-update', '--safe']
14:23:21-529842 INFO     Unloading xFormers

**Comment by vladmandic** [comment]
what are your settings -> compute settings?

**Comment by Rogal80** [comment]
![image](https://github.com/vladmandic/automatic/assets/112553453/bdc54435-caf9-4651-b64b-d25808b0de85)

**Comment by vladmandic** [comment]
WTF, you're missing one option - and thats the important one: precision type -> autocast?  
can you go back to default theme to make sure its not a theme issue?

**Comment by Rogal80** [comment]
wait i take precison to quick and its set on autocast

**Comment by Rogal80** [comment]
![image](https://github.com/vladmandic/automatic/assets/112553453/e616e0b3-cdde-4c9c-b50d-4055392258e8)

**Comment by vladmandic** [comment]
why would you ever set prompt attention to fixed, thats bad. but not related to black images.

**Comment by Rogal80** [comment]
in many cases with fix attention, i have very consistent results with prompts, I already reinstall all repo now it's working with my all old extension - that was weird, probably I break repo somehow :( anyway thx for the fast response

**Comment by vladmandic** [comment]
consistent results? yeah, because it has no strength parsing at all. none. that is the original code before a1111 ever existed.

**Comment by Rogal80** [comment]
hi , after latest update have this issue :
18:44:44-330267 ERROR    Exception: Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the
                         same
18:44:44-342272 ERROR    Arguments: args=('task(ylyfmfp1xcu7r9g)', 'Hyperrealistic, Hyperdetailed, ((analog photo)), te
                         upton as a post - apocalyptic warrior girl with tattoos & tribal face paint, bikini, tattered
                         military gear, holding a rocket launcher!!! standing in the desert, drawn by wlop, drawn by
                         jeehyung lee, drawn by artgerm, smooth, sharp focus, intricate, detailed, ZEISS, studio
                         quality, 8k', '(((bad art))), (((stock image))), (((stock photo))), (((stock-photo))), ((bad
                         fan art)), ((lazy art)), ((low quality)), (low efford), (rushed art), (((out of frame))),
                         ((watermark))),((signature)), striped, borders, white border, cutout, collage, incomplete
                         word, cut off text, half letter, latent space,(painting), (frame), (drawing), (sketch),
                         (camera), (rendering),(((cropped))), (((watermark))), ((logo)), ((barcode)), ((UI)),
                         ((signature)), ((text)), ((label)), ((error)), ((title)), stickers, markings, speech bubbles,
                         lines, cropped, lowres, low quality, artifacts', [], 35, 2, False, False, 1, 1, 10, 1,
                         442197473.0, -1.0, 0, 0, 0, False, 704, 384, True, 0.4, 2, '4x-UltraSharp', 0, 0, 0, [], 0,
                         False, 'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1,
                         64, False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0,
                         False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 3072, 192, True, True, True,
                         False, True, 7.5, 99, 'Half Cosine Up', 4.5, 'Half Cosine Down', 3, 4,
                         <controlnet.py.UiControlNetUnit object at 0x0000023AD2AF15A0>, <controlnet.py.UiControlNetUnit
                         object at 0x0000023AD2AF1EA0>, <controlnet.py.UiControlNetUnit object at 0x0000023AD2956E60>,
                         <controlnet.py.UiControlNetUnit object at 0x0000023AD4387640>, False, {'ad_prompt': 'young
                         beautiful woman', 'ad_inpaint_only_masked_padding': 16, 'ad_denoising_strength': 0.5,
                         'ad_model': 'face_yolov8n.pt', 'ad_negative_prompt': '', 'ad_confidence': 0.3,
                         'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0,
                         'ad_dilate_erode': 32, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4,
                         'ad_inpaint_only_masked': True, 'ad_use_inpaint_width_height': True, 'ad_inpaint_width': 768,
                         'ad_inpaint_height': 768, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False,
                         'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model': 'None',
                         'ad_controlnet_weight': 1}, {'ad_model': 'None', 'ad_prompt': '', 'ad_negative_prompt': '',
                         'ad_confidence': 0.3, 'ad_mask_min_ratio': 0, 'ad_mask_max_ratio': 1, 'ad_x_offset': 0,
                         'ad_y_offset': 0, 'ad_dilate_erode': 32, 'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4,
                         'ad_denoising_strength': 0.4, 'ad_inpaint_only_masked': True,
                         'ad_inpaint_only_masked_padding': 32, 'ad_use_inpaint_width_height': True, 'ad_inpaint_width':
                         1024, 'ad_inpaint_height': 1024, 'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale':
                         False, 'ad_cfg_scale': 7, 'ad_restore_face': False, 'ad_controlnet_model': 'None',
                         'ad_controlnet_weight': 1}, 'Send to Canvas Editor', False, False, 'LoRA', 'None', 0, 0,
                         'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, 'LoRA', 'None', 0, 0, None,
                         'Refresh models', False, '', 0.5, True, False, '', 'Lerp', False, False, False, False, '', '',
                         True, False, 'Run', False, False, 'Euler a', 0.95, 0.75, 'zero', 'pos', 'linear', 0.2, 0.0,
                         0.75, None, 'Lanczos', 1, 0, 0, False, False, 'positive', 'comma', 0, False, False, '', 1, '',
                         [], 0, '', [], 0, '', [], True, False, False, False, 0, False, None, None, False, None, None,
                         False, None, None, False, None, None, False, 50, 5, 'all', 'all', 'all', '', '', '', '1',
                         'none', False, '', '', 'comma', '', True, '', 0, 0, 512, 512, False, True, False, False, 0, 1,
                         False, 1, True, True, False, False, ['left-right', 'red-cyan-anaglyph'], 2.5,
                         'polylines_sharp', 0, False, False, False, False, False, False, 'u2net', False, True, False,
                         2, 'Lanczos', 'Adjust', 1024, 1024, 30, 0.5, None, False, '{inspiration}', None, 'Not set',
                         True, True, '', '', '', '', '', 1.3, 'Not set', 'Not set', 1.3, 'Not set', 1.3, 'Not set',
                         1.3, 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not set', 1.3, 'Not
                         set', False, 'None') kwargs={}
18:44:44-893200 ERROR    gradio call: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Github\Web_UI\automatic\modules\call_queue.py:34 in f                                                            │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ I:\Github\Web_UI\automatic\modules\txt2img.py:57 in txt2img                                                         │
│                                                                                                                     │
│   56 │   if processed is None:                                                                                      │
│ > 57 │   │   processed = process_images(p)                                                                          │
│   58 │   p.close()                                                                                                  │
│                                                                                                                     │
│                                              ... 32 frames hidden ...                                               │
│                                                                                                                     │
│ I:\Github\Web_UI\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward                           │
│                                                                                                                     │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                                              │
│ >  463 │   │   return self._conv_forward(input, self.weight, self.bias)                                             │
│    464                                                                                                              │
│                                                                                                                     │
│ I:\Github\Web_UI\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward                     │
│                                                                                                                     │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                                            │
│ >  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                                    │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.HalfTensor) should be the same


![image](https://github.com/vladmandic/automatic/assets/112553453/0e981ac6-5f27-40c3-ae4f-42482f61926f)
![image](https://github.com/vladmandic/automatic/assets/112553453/13bd7454-638e-4cb3-97ef-f1d0feb09e46)


and it happen randomly - most repro if i wii send from img browser to tex and then generate

**Comment by Rogal80** [comment]
I will try to debug some extensions - with safe option seems that all work fine

**Comment by Rogal80** [comment]
found it - composable lora extension
