### ISSUE TITLE
[Feature]: Extensions search keystroke delay

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1194]
### Feature description

At the moment, typing in the Extensions search box starts immediately searching, resulting in further keystrokes being ignored.

For example, if I quickly type "ade" for adetailer, the "a" is recognised, but "de" isn't parsed until I type further letters;
![image](https://github.com/vladmandic/automatic/assets/1969381/05abcf35-94c3-4cf1-8705-f2403f6d6973)

Perhaps re-code the search to delay, say, 25-50ms after keyup before searching.

### Version Platform Description

7254925d, Chrome, Win10

**Comment by vladmandic** [comment]
done.
