### ISSUE TITLE
[Issue]: Lora valueError

### ISSUE THREAD

**Issue by ronbere** [vladmandic/automatic#1196]
### Issue Description

23:58:29-036204 ERROR    loading Lora D:\automatic\models\Lora\bscdb2.0.safetensors: ValueError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic2\extensions-builtin\Lora\lora.py:219 in load_loras                                                     │
│                                                                                                                     │
│   218 │   │   │   │   try:                                                                                          │
│ > 219 │   │   │   │   │   lora = load_lora(name, lora_on_disk.filename)                                             │
│   220 │   │   │   │   except Exception as e:                                                                        │
│                                                                                                                     │
│ D:\automatic2\extensions-builtin\Lora\lora.py:142 in load_lora                                                      │
│                                                                                                                     │
│   141 │   for key_diffusers, weight in sd.items():                                                                  │
│ > 142 │   │   key_diffusers_without_lora_parts, lora_key = key_diffusers.split(".", 1)                              │
│   143 │   │   key = convert_diffusers_name_to_compvis(key_diffusers_without_lora_parts, is_sd2

strange, I don't understand why this error comes back,
I tested by lora and lycoris same result

### Version Platform Description

windows 10. chrome
Last commit

**Comment by vladmandic** [comment]
1. writing "last commit" is NOT a valid version.
2. which extensions do you have installed? post line from startup log showing it
3. you've provided traceback, but cut it just before actual error
4. is this happening with this specific lora only or with any lora?

**Comment by vladmandic** [comment]
no information provided, so closing the issue - will reopen once information is available.
