### ISSUE TITLE
[Issue]: Could not load torch: module 'torch.cuda' has no attribute 'get_allocator_backend'

### ISSUE THREAD

**Issue by DaniAndTheWeb** [vladmandic/automatic#1197]
### Issue Description

After the commit 2ee38cc I'm unable to start the program using pytorch rocm 1.13.1 on a radeon 5700XT.
The above version of pytorch is needed for this specific card as the latest pytorch doesn't work at all with it.

### Version Platform Description

Version: 2ee38cc
Linux, AMD Radeon 5700XT, pytorch rocm 1.13.1

**Comment by DaniAndTheWeb** [comment]
The error is  caused by line 296 of installer.py:
```
log.debug(f'Torch allocator: {torch.cuda.get_allocator_backend()}')
```

**Comment by vladmandic** [comment]
fixed.
