### ISSUE TITLE
[Feature]: Add delete button below generated image

### ISSUE THREAD

**Issue by crackfoo** [vladmandic/automatic#1198]
### Feature description

Hi, 

I think it would be handy to be able to have a button below the generated image to delete it.  Would make keeping your image folder(s) free of failed/unwanted images.

Would that be possible?

Thanks!

**Comment by vladmandic** [comment]
yes, doable & i like the idea. i'll see when i can squeeze it in.

**Comment by vladmandic** [comment]
done.

**Comment by crackfoo** [comment]
fantastic, thanks!
