### ISSUE TITLE
[Issue]: Extension Koyha ss Additional Networks

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#120]
### Issue Description

Runtime Error:

activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at 0x000001D01FC65840>]: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\modules\extra_networks.py:75 in activate                                                  │
│                                                                                                                     │
│    74 │   │   try:                                                                                                  │
│ >  75 │   │   │   extra_network.activate(p, extra_network_args)                                                     │
│    76 │   │   except Exception as e:                                                                                │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\extensions-builtin\Lora\extra_networks_lora.py:23 in activate                             │
│                                                                                                                     │
│   22 │   │                                                                                                          │
│ > 23 │   │   lora.load_loras(names, multipliers)                                                                    │
│   24                                                                                                                │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\extensions-builtin\Lora\lora.py:214 in load_loras                                         │
│                                                                                                                     │
│   213 │   │   │   if lora is None or os.path.getmtime(lora_on_disk.filename) > lora.mtime:                          │
│ > 214 │   │   │   │   lora = load_lora(name, lora_on_disk.filename)                                                 │
│   215                                                                                                               │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\extensions-builtin\Lora\lora.py:176 in load_lora                                          │
│                                                                                                                     │
│   175 │   │   with torch.no_grad():                                                                                 │
│ > 176 │   │   │   module.weight.copy_(weight)                                                                       │
│   177                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: output with shape [128, 320] doesn't match the broadcast shape [128, 320, 128, 320]

The dropdown where the LoRAs are listed, is not populated. Neither in tx2img, nor in the Additional Networks tab.

### Platform Description

Win10, Firefox 106

**Comment by vladmandic** [comment]
i've made some updates, can you update and try?

**Comment by vladmandic** [comment]
this looks like repo was only partially updated on your side, bad git pull?
you got some new files (e.g. shared.py) and some old (e.g. cmd_args.py)

**Comment by Woisek** [comment]
> this looks like repo was only partially updated on your side, bad git pull?

How is a "bad pull" done? 😁 I just use the webui.bat to start and let it run.

BTW, I re-run it just now and suddenly the script wants to download SD1.5 model from huggingface _again_ ... **without asking or the possibility to skip that** ... 😡

**Comment by vladmandic** [comment]
how did you update the repo itself? `webui.bat` by default does not auto-update main repository, it does auto-update extensions. its in readme.

**Comment by Woisek** [comment]
Ok ... didn't catch that. Just saw "git" running in the console and thought of updateing just like in A1111 ...
So ...
Main repository:
Update is not performed by default, enable with --upgrade flag

Where has this flag to be set?

**Comment by vladmandic** [comment]
`webui.bat --upgrade`? :)
or run `git pull` yourself if you want to be in control.

**Comment by Woisek** [comment]
> `webui.bat --upgrade`? :)

Then I hav to put it into another .bat, like in A1111 webui-user.bat ... what a bat out of hell ... 🤪

> or run `git pull` yourself if you want to be in control.

When I do so, it tells me about

I:\Super SD 2.0\automatic>git pull
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

I:\Super SD 2.0\automatic>

git stash tells me:
scripts/prompts_from_file.py: needs merge
user.css: needs merge

but 1. how and why would I merge that? I don't even know what "prompts_from_file.py" is for and 2. user.css is edited by me. That was I meant by "will it be replaced sometime".

Now ... what do you suggest should I do now? 🤔

**Comment by vladmandic** [comment]
copy your `user.css` somewhere, run `git pull --autostash`, replace `user.css` back.
as i've said before, current `user.css` is temporary until i clean it up and merge it with `system.css`, then it will become fully under user control and no longer part of the repo.

**Comment by Woisek** [comment]
Hmm ...

I:\Super SD 2.0\automatic>git pull --autostash
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict.

I:\Super SD 2.0\automatic>git stash
scripts/prompts_from_file.py: needs merge
user.css: needs merge

I:\Super SD 2.0\automatic>

user.css is renamed to user.css_

**Comment by vladmandic** [comment]
it only tries to download a model if no models are found. if there is a single model available in the model folder, it will use it.

**Comment by Woisek** [comment]
OK, looks like the folder was not found.
But another crucial change is the location of the embeddings. You put them into the models folder, completely different of what A1111 does. Any possibility to change the folder location for the embeddings in some setting/configuration?

**Comment by vladmandic** [comment]
> Any possibility to change the folder location for the embeddings in some setting/configuration?
 
UI -> Settings -> System Paths

**Comment by Woisek** [comment]
Ah, OK, everything is now here, I see ... cool, thanks!

**Comment by vladmandic** [comment]
additional networks extension does hard path lookups and many things are broken there - thats up to author to fix.  
unless you have a very specific reason to use it, there is not reason as all core lora/locon/lycoris functionality is already built-in in this repo.

**Comment by Woisek** [comment]
> unless you have a very specific reason to use it, 

Well, the one reason is: qol features, like making notes, lookup training data, etc.
The other reason is (but that I don't know if it's true) the use of LoRAs made for SD v2.1. Allegedly the don't work without it.
Maybe you have more info an that ... ?

**Comment by vladmandic** [comment]
i'll add that a deep-dive on that extension on my todo list.
