### ISSUE TITLE
[Feature]: Integrate new sampler(s) from A1111 1.3

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#1200]
### Feature description

As the subject says, the recent 1.3 version of A1111 added at least a new sampler from the upstream repositories (I say at least because I didn't look closely). As the number of changes upstream is likely massive, I thought it would be nice to have this issue for a specific piece of the puzzle.

Note: this is made as a "nice to have" / "useful to track" issue, as I expect things to get far more difficult in the future the more the two codebases diverge.

**Comment by DirtyHamster** [comment]
What new samplers? I'm looking at the release notes here:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/releases/tag/v1.3.0

**Comment by lbeltrame** [comment]
This one:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/31545abe145ac8833c9c15aa41300fb609dcb128

(it's in the tagged 1.3.0)

**Comment by DirtyHamster** [comment]
Ok on the same page now:

DPM++ 2M SDE

![image](https://github.com/vladmandic/automatic/assets/71010673/872fa35f-4417-455c-925d-1c91540aabef)

There's some notation I'll bring over from that comment thread: 
[catboxanon](https://github.com/catboxanon): I did a version with discard penultimate sigma and it was not much better. Another option is to use exponential sigmas (sigmas = k_diffusion.sampling.get_sigmas_exponential(n=steps, sigma_min=sigma_min, sigma_max=sigma_max, device=shared.device)) but that doesn't help much either. The implementation is obvious a subject to revision, I just added this quickly to let whoever wants to to play with it.

AUTOMATIC1111 Might want to take a look at this, it's suggested to discard the penultimate sigma: https://gist.github.com/crowsonkb/3ed16fba35c73ece7cf4b9a2095f2b78?permalink_comment_id=4570384#gistcomment-4570384

**Comment by rkiga** [comment]
One of Vlad's recent dev updates said that the latest k-diffusion is in this fork but currently only for new installs. 

Here is a bit more info about the sampler and why it was added: https://github.com/crowsonkb/k-diffusion/issues/59
LuChengTHU is the DPM-Solver and DPM++ lead author.

**Comment by lbeltrame** [comment]
It's in the k-diffusion repository but as far as I can tell it still needs to be hooked in the UI nevertheless (hence this issue).

**Comment by vladmandic** [comment]
something like this? :)

![image](https://github.com/vladmandic/automatic/assets/57876960/5c7f92ed-09bb-44b0-bef6-80c282e15d1a)

new version is posted...

**Comment by MDMAchine** [comment]
> something like this? :)
> 
> ![image](https://user-images.githubusercontent.com/57876960/242030105-5c7f92ed-09bb-44b0-bef6-80c282e15d1a.png)
> 
> new version is posted...

I'm on d1ab205d and not seeing DPM++ 2M SDE as an option?

**Comment by Razunter** [comment]
You have to enable it in the options. I've also manually updated k-diffusion repo, don't know if it's needed.
