### ISSUE TITLE
[Issue]: No full image display in inpainting

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#1203]
### Issue Description

I do some dual wallpaper generations lately and mostly, I don't need to edit them afterwards. But now I have a few where I'd like to inpaint some elements and noticed, that the image is not fully displayed in the inpainting tab unlike in the img2img tab.

![Zwischenablagebild](https://github.com/vladmandic/automatic/assets/122026301/7c716537-2db9-4a71-8e8f-148d3c6aecbf)
![Zwischenablagebild (1)](https://github.com/vladmandic/automatic/assets/122026301/7d9fc05e-ebcc-4f68-b011-5f4d32d45444)

Is this known and does a solution exist?

### Version Platform Description

Win10, FF106
Version: b2c3bc5a Sun May 28 21:26:29 2023 -0400

**Comment by vladmandic** [comment]
sorry, but i have no idea where do images come from and what does it mean "image not fully displayed"? image is image, question is how was it transferred to that tab?

**Comment by Woisek** [comment]
The images are drag and dropped into it.

**Comment by vladmandic** [comment]
img2img uses simple image with `object-fit: contain` so image is resized to fit inside display.
inpainting uses mutliple canvas elements at their full size, otherwise painting would not work. so its really up to theme you use to display scrollbars around the image. what you're showing is not that image is "not fully displayed", its simply that your theme is making it hard to see horizontal scrollbar.

**Comment by Woisek** [comment]
No, a canvas element normally has no scrollbars, it's just a fixed object that is not changeable once drawn. But you gave my an idea to try and now I can dismiss you from this issue. 😊
I use the extremely helpful canvas zoom extension and I looked for an overflow: hidden element and is seems like this extension sets the canvas to this state, meaning the canvas is there, but not visible.
I guess I have to report this to richrobber2, the developer of canvas zoom. 😋
Sorry for bothering, should have take a better look on it. 🙄

**Comment by vladmandic** [comment]
all good!
btw, canvas has no scrollbar, but a parent element in which canvas resides does if 
- canvas css height/width (which may be different than actual canvas dimension) are set to explicit value
- canvas overflows the dimensions of that element (and overflow is enabled).
