### ISSUE TITLE
[Issue]: Interrogate issue

### ISSUE THREAD

**Issue by Rogal80** [vladmandic/automatic#1204]
### Issue Description

Hi, since last update I encountered this issue when interrogate images :

 I:\Github\Web_UI\automatic\modules\interrogate.py:204 in interrogate                                                │
│                                                                                                                     │
│   203 │   │   │   with torch.no_grad(), devices.autocast():                                                         │
│ > 204 │   │   │   │   image_features = self.clip_model.encode_image(clip_image).type(self.dtyp                      │
│   205                                                                                                               │
│                                                                                                                     │
│ I:\Github\Web_UI\automatic\venv\lib\site-packages\clip\model.py:341 in encode_image                                 │
│                                                                                                                     │
│   340 │   def encode_image(self, image):                                                                            │
│ > 341 │   │   return self.visual(image.type(self.dtype))                                                            │
│   342                                                                                                               │
│                                                                                                                     │
│                                               ... 4 frames hidden ...                                               │
│                                                                                                                     │
│ I:\Github\Web_UI\automatic\venv\lib\site-packages\torch\nn\modules\normalization.py:190 in forward                  │
│                                                                                                                     │
│   189 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ > 190 │   │   return F.layer_norm(                                                                                  │
│   191 │   │   │   input, self.normalized_shape, self.weight, self.bias, self.eps)                                   │
│                                                                                                                     │
│ I:\Github\Web_UI\automatic\venv\lib\site-packages\torch\nn\functional.py:2515 in layer_norm                         │
│                                                                                                                     │
│   2514 │   │   )                                                                                                    │
│ > 2515 │   return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.c                     │
│   2516                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: expected scalar type Float but found Half

I am also using Interrogate folder with txt files .

### Version Platform Description

windows 10, firefox
![image](https://github.com/vladmandic/automatic/assets/112553453/ece5a68e-8c4e-4f15-91a7-1ebc6ff27fc2)

**Comment by vladmandic** [comment]
what are your compute settings?

**Comment by Rogal80** [comment]
![image](https://github.com/vladmandic/automatic/assets/112553453/461ca064-603a-4bd5-bf24-3e848f93ad28)

**Comment by Rogal80** [comment]
![image](https://github.com/vladmandic/automatic/assets/112553453/913943c6-c044-4a7d-8178-cd28918a8ee9)

**Comment by Rogal80** [comment]
ok, now it starts to works , after 10 restarts - and i didn't do any updates - weird

**Comment by vladmandic** [comment]
very weird but not much i can do about it :(
i'll close the issue, but if it reoccurs, update here and i'll reopen.

**Comment by Rogal80** [comment]
thx
