### ISSUE TITLE
[Feature]: Settings > System Paths > include Extensions path

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1207]
### Feature description

I use Vlad's fork in Windows and Linux, and I like to keep them the same as possible, including extensions.

While I can place models and repositories behind symlinks, I've found that browsers _really_ don't like it when scripts from extensions are behind symlinks.

If possible, could an Extensions path be added to System Paths?

### Version Platform Description

n/a

**Comment by vladmandic** [comment]
you can already use `--data-dir` to remap all user data. i really don't want to go into every single individual item separately.
