### ISSUE TITLE
[Issue]: fresh install not working

### ISSUE THREAD

**Issue by Holyniwa** [vladmandic/automatic#121]
### Issue Description

program wont boot up. something about submodule issue
![image](https://user-images.githubusercontent.com/13576034/231923926-96204f1f-6141-4293-a0a9-ef9b2338c41f.png)

### Platform Description

Win11

**Comment by vladmandic** [comment]
can you run `git submodule`?

**Comment by Holyniwa** [comment]
ima be real witchu, im not sure what that means, but from all the attempts i tried. nothing seems to work. if you want me to try something, I'm available for a bit.

**Comment by vladmandic** [comment]
1. is this a fresh `git clone`?
2. if yes, did you run using `webui.bat`?
3. if yes, activate venv using `venv/Scripts/activate` and run command i wrote above

**Comment by Holyniwa** [comment]
yes, fresh
yes, using that bat
did as instructed (wasn't sure where to run the git submodule I did it in in the webui,bat, activate,bat, and folder cmd just to be sure)
no progress. 
- when running that cmd in the folder cmd, it gives me "fatal: not a git repository (or any of the parent directories): .git" not sure if that's expected or not, so just mentioning it in case.

**Comment by exodia52** [comment]
Recommend delete the folder and try Clone another one fresh. Run Webui.bat and update here.

**Comment by Holyniwa** [comment]
Thank you. Doing another fresh install seems to have worked. Perhaps the first fresh install was corrupted somehow.
However, before writing this off as a success, the checkpoint section on the top left seems to be in an endless loop/loading. Any idea why that may be?
![image](https://user-images.githubusercontent.com/13576034/232051814-624e1885-24e3-4249-bad7-826769af2375.png)

**Comment by exodia52** [comment]
If it your first load it kinda always infinite loop. My recommendation is go to "Settings" -> "System Path" -> navigate to ur SD and others. Then restart your console.

**Comment by Holyniwa** [comment]
Thanks Exodia! That seems to have fixed it completely.
So in conclusion, looks like the submodule issue arised from a faulty installation.
