### ISSUE TITLE
[Feature]: Pause button for time-consuming jobs

### ISSUE THREAD

**Issue by myndxero** [vladmandic/automatic#1216]
### Feature description

Simple, press a PAUSE button, current job is PAUSED until user presses any variation of UNPAUSE , RESUME , PLAY , GET'ER DONE , etc. To free up CPU/GPU, maybe you want to open another instance and mess with another idea for a bit or play a game, watch a youtube video, whatever.

Expanded features, offload VRAM into a page file, regular RAM, some sort of saved state/instancing to free up VRAM down to minimum necessities to keep pytorch's lights on. Furthermore, to a saved state to allow closing of pytorch completely to be resumed at a later date and time, similar to Dreambooth training's save-instancing.

I'm 5 hours into an 8 hour XYZ grid job and by golly I wanna do other things briefly and resume. Yes, I am aware of mcmonkey's endless grid jim-jam but that's not my flavor nor does it solve the versatility this feature would offer users, especially those users with slower setups, or those doing a lot of big batch jobs, m2m, etc.

PS - Vlad also knows that a happy mynd, is a quiet mynd, and Vlad likes me quiet!

SIDE NOTE: Would it be possible to make grid generations more efficient, allow larger scales, etc? Or offer a way of predicting that a grid will be too big, and fail, with parameters set? I've got my megapixel setting set to 9999999999 but there's still a 65535 cap or something I *think*. Yes I know it's insane, but remember, xyz grid addict here (#gethelp).

### Version Platform Description

arch: AMD64
cpu: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
system: Windows
release: Windows-10-10.0.22621-SP0 (err windows 11? might think it's 10 cuz I messily copied my vlad-o-matic install from 10, to 11, like a lazy a-hole)
python: 3.10.11
Brave Browser (Chromium-based)

**Comment by vladmandic** [comment]
> SIDE NOTE: Would it be possible to make grid generations more efficient, allow larger scales, etc? Or offer a way of predicting that a grid will be too big, and fail, with parameters set? I've got my megapixel setting set to 9999999999 but there's still a 65535 cap or something I think. Yes I know it's insane, but remember, xyz grid addict here (#gethelp).

you can set mp limit high, but then you're going to run out of ram and crash.
imagine 64k x 64k image - that takes about 32gb of memory to create just for that. plus a bit more to encode it to any file format - so we're talking ~36-38gb.
btw, 65535px cap applies to jpeg, png does not have that limit.

but that's exactly why i've recently added option **Do not create grid** - so you can use xyz grid to generate images without running into huge grid issues.

**Comment by vladmandic** [comment]
btw, if there is pause - it can be actual pause that is applied in-between steps.
and it can maybe temporarily unload model weights to free up vram.
but server process must remain active and ram utilization will not go down, only vram.

that's about it - there is no chance of full suspend or equivalent of hybernate.
so let me know if that is still interesting enough to justify the work.

**Comment by myndxero** [comment]
That works for my case precisely. I've 128gb of system memory so I can afford any overhead there.

128gb is up from 64gb in my last system from a month ago, will that influence my max grid size per your explanation? So at 32gb is that 65535 on one axis? 64 for 65535x65535 64gb? If I am understanding that correctly, or is it some combination of X times Y = 65535, which seems maybe off to me?

As far as I can find atm, the biggest grid I've ever made is 28820x42986. This grid was made on the old xy script, before xyz I believe. Bunch of 2560x720 tests for potential wallpaper jim jams I was doing and checkpoint testing. I've a 5120x1440 monitor.

![desktop glory](https://github.com/vladmandic/automatic/assets/113237671/f6e931fb-91e1-4632-ac81-6639bdf693c2)

I have made use of disable grid generation for some things, but I am absolutely an addict for my xyz charts.

**Comment by vladmandic** [comment]
regarding maximum sizes, it all comes down to how many bits format uses for size.
- jpeg uses 16bits so max size is 64k
- png uses 32bits so max size is 16m
- webp uses 14bits - for a new format, that is a really low limit - 16383px!

regarding memory, think this way: width x height x 4 (rgba channels) x 2 (images + grid) * + ~10% (overhead) * + ~30% (encoding). and if you're using subgrids, then its x3 instead of x2 as those also exist in memory.

btw, i've just added rudimentary pause button. will improve functionality over time, but for now this is it...

**Comment by vladmandic** [comment]
I know what you mean, I switched from 4k to 1440p ultra wide as well and not regretting it for a sec, just mine is "only" 34" 😁

**Comment by myndxero** [comment]
34" ??? I honestly have never seen one under 49" (mine). Hey your PPI is higher than mine then, haha.

With some Nvidia jujitsu I got HOTS (don't flame me) to run in full 5120x1440, it's almost cheating playing a moba that way. It gets closer and closer every day to becoming more mainstream (which for once is a good thing).
