### ISSUE TITLE
[Feature Request]: Add installer output

### ISSUE THREAD

**Issue by Zetaphor** [vladmandic/automatic#122]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

Installing on Fedora 37

I had to restart this installer 3 times before I finally though to dig into the script and tail the log to figure out why it was appearing to hang on "Installing requirements" for 10+ minutes

I learned it was actually doing all of the requirements installs, but without any output I have no idea what's happening, so I just assumed it was hung. Turns out it was just downloading a large package.

It would be preferable to have console output during the install process, especially when you're in a fresh venv so a lot of large packages need to be downloaded and installed. In the very least I think a `--verbose` option would be a good idea.

### Proposed workflow

A) Script outputs logs while installing
B) Optional --verbose flag enables A

**Comment by vladmandic** [comment]
there already is `--debug` flag which enables verbose output.

**Comment by Zetaphor** [comment]
That flag is no different than me running a tail against the log. I still don't have any insight into what is happening beyond "Installing packages" or "Installing repositories, which in my case took 15+ minutes for the packages alone

**Comment by vladmandic** [comment]
it shows install step for each individual package. and only very large package is `torch` itself, the rest is much smaller.
