### ISSUE TITLE
[Feature]: Sampler for hi-res pass (and maybe hr prompt)

### ISSUE THREAD

**Issue by Panchovix** [vladmandic/automatic#1221]
### Feature description

Hi there, I'm wondering if it's possible to do something similar that auto did here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ff0e17174f8d93a71fdd5a4a80a4629bbf97f822

But for now, only with new sampler since hr positive/negative prompt breaks when using wildcards/dynamic prompts at the same time. (https://github.com/adieyal/sd-dynamic-prompts/issues/435). I did a change on a fork so hr samplers work but makes hr pos/neg prompt to not work. (https://github.com/Panchvzluck/stable-diffusion-webui/commit/08cd7a6cf4ab37e9e78368e690e6e64c9fd564f2)

The last comment explains the issue there, but that could be taken in mind for the future if the issue gets resolved somehow.

It would be really great to have the feature here as well, since for second order samplers like DPM++ SDE, the hires pass can be done with the new DPM++ 2M SDE or DPM++ 2M SDE Karras to get good results at half the speed on the hr pass, or getting different results with Euler a to upscale, etc

### Version Platform Description

https://github.com/vladmandic/automatic/commit/873371f1e5c26457f87871c576737664fe58b5e0
Windows 11/Ubuntu 22.04
Google Chrome/Firefox

**Comment by vladmandic** [comment]
yes, its coming.

**Comment by vladmandic** [comment]
added explicit second pass sampler.

**Comment by Panchovix** [comment]
Hi there, good work as always. Was wondering, re installed the UI and now I can't find the option, it is named differentely now?
