### ISSUE TITLE
[Issue]: Broken theme Ifeanyi-cyanister have broken the whole UI

### ISSUE THREAD

**Issue by tetsuoo-online** [vladmandic/automatic#1223]
### Issue Description

I have selected User Interface > Ifeanyi-cyanister theme and now the UI cannot work at all, when launched I get infinite loading... The theme preview page https://ifeanyi-cyanister.hf.space/ doesn't work, I should have know that trying it was risky x) I didn't expect a simple CSS operation to break everything. Well...
What can I do to get the default theme back so I can use the UI again ?
--safe didn't make any different, I'm stuck :/ 

### Version Platform Description

Version: 8354b7c6 Mon May 29 15:42:24 2023 -0400
Windows 10
Chrome/Firefox

**Comment by vladmandic** [comment]
Either delete config.json so it will be recreated with all defaults or edit it and change the theme.

**Comment by tetsuoo-online** [comment]
> Either delete config.json so it will be recreated with all defaults or edit it and change the theme.

wow that was fast. Thank you, I edited config.json and put "gradio_theme": "black-orange",
It's fixed

**Comment by vladmandic** [comment]
Black-orange and couple of gradio-* are official, the rest is a dynamic list that is downloaded when you click reshresh, I have no control how long it is or what's on it.
