### ISSUE TITLE
[Feature]: Customized Text-to-Image Generation: A Regularization-Free Approach

### ISSUE THREAD

**Issue by Metalica** [vladmandic/automatic#1233]
### Feature description

ProFusion: Code for Enhancing Detail Preservation for Customized Text-to-Image Generation: A Regularization-Free Approach.

Pro fusion: https://github.com/drboog/ProFusion/tree/main

**Comment by vladmandic** [comment]
interesting.

**Comment by vladmandic** [comment]
this is still interesting, but after 9 months, author does not seem to want to merge his work, it still requires a custom version of diffusers which is not compatibile

> Install dependencies (we revised original [diffusers](https://github.com/huggingface/diffusers));

if this feature is still desired, please create feature request on authors git so his work is actually merged (like into a community pipeline) and others can use it.

**Comment by vladmandic** [comment]
author has shown no interest in making this a valid pipeline other than being his prototype and the repo is idle for a year. closing.
