### ISSUE TITLE
[Feature]: Button to compute all model checksums in directories.

### ISSUE THREAD

**Issue by myndxero** [vladmandic/automatic#1234]
### Feature description

Simple QOL button to push and have the WebUI go through all your models, and calculate those checksums that don't already exist in your cache.json.

I've a directory of over 400 models now and I'd say a third of them have had their checksums calculated. I guess it's unreasonable to have so many models maybe, I dunno. But even on a fresh install, if you have 20 models, and not doing anything with WebUI, why not calculate all those checksums automatically and get it out of the way?

### Version Platform Description

For every platform but Apple, cuz Apple is evil and I hate them... nevermind that's rude, Apple users are people too, I GUESS! (I use windows so maybe I shouldn't judge, don't flame me, I love you).

EDIT: ** Enhanced feature maybe: Allow for easy downloading and replacing/converting of .pth files to your choice of .ckpt or .safetensors formats? Primarly for all BLIP, CLIP, RIBBIT and controlnet etc?

**Comment by vladmandic** [comment]
i didn't know where to put it so, i put it next to model merge in training tab for now:
![image](https://github.com/vladmandic/automatic/assets/57876960/42246b30-49ee-4937-8067-22f01b3e35cd)

re: apple - nothing wrong with a bit of sarcasm :)

re: downloading/replacing/converting for all those submodules - that's up to submodule, repo does not perform any of those ops and is unaware of any of those.

**Comment by myndxero** [comment]
For the button, maybe just put it next to the refresh list button next to the model dropdowns? I don't know if everyone still has the dropdown list in the top left like I do, if that's still standard in configs (I mean I added VAE and Seed Delta to my top too and clip skip was up there until it was moved).
![image](https://github.com/vladmandic/automatic/assets/113237671/1e28170e-e67a-4d08-9b42-23e5921a36dd)


I know a script exists to convert .pth files to models. @theally over at civitai uses it to host controlnets there.

When I re-read her description, I did notice the underlined part which is probably relevant? Perhaps no one script will apply and work with all .pth files? Just a thought.

https://civitai.com/models/9251/controlnet-pre-trained-models
![image](https://github.com/vladmandic/automatic/assets/113237671/5dc49b10-24c0-4a98-9b24-9a245a10cedd)

I am nothing but snark, usually good-humored, not always 👯

**Comment by vladmandic** [comment]
oh, hell no putting calc hash next to refresh model - i can only imagine how many ppl would click it by mistake and then create an issue because server is "hanging" - this way there is an explict button. plus there is no textbox to output the result.

regarding script - yeah, i'm aware of it, but i don't want to get into business of managing other peoples models - that should really be done by controlnet itself. why is controlnet not offering to download/convert/whatever models automatically - well, ask the author.

**Comment by myndxero** [comment]
> regarding script - yeah, i'm aware of it, but i don't want to get into business of managing other peoples models - that should really be done by controlnet itself. why is controlnet not offering to download/convert/whatever models automatically - well, ask the author.

Not unique to control net. I'd really like to have the various clip and blip models downloaded too. I've not poked around for those in awhile, maybe they exist somewhere now I dunno.

No worries though, thanks for entertaining me and pointing out said button exists! PS - system would only hang once!!!!!! if all checksums are handled, then it would do nothing! :D

**Comment by vladmandic** [comment]
> pointing out said button exists!

it didn't exist until 1h ago, i just added that feature.

> I'd really like to have the various clip and blip models downloaded too

yes, would be nice. but each one is handled separately and in its own module - i don't want to go through all possible upstream repos and making changes in each one separately.

**Comment by myndxero** [comment]
I just went to look for the button and intuitively checked system info for it. I recalled you put it in training of course, but since you didn't know a better place to put it, I wonder if others would intuitively think system info as well? Or match somewhere in settings, like system paths.

It's also fine where it is but I've personally never visited the training tab before until now haha. I had no idea the old model merge was here either LMAO. I grabbed merge board again, used to using it in a1111 anyway. Fun fact, I only recently discovered PNG Info was integrated into Process Image as well.

Final afterthought - maybe a renaming of the train tab would make the most sense if there's a good word or two that would work?

**Comment by vladmandic** [comment]
If you can come up with an good name, I'm open to it.

**Comment by myndxero** [comment]
First thought was Model Management, but I feel like that might leave the training aspect out in the cold. I'll think on it. Model Management & Training is probably too long. I guess you could consider breaking training back off from it to its own again if that makes sense to you.

I'll mull it over.

**Comment by myndxero** [comment]
Oh man I was wrong, 319 out of 399 models missing full hash, here we gooooooooooo. Pause button for checking hash? JKJKJK

**Comment by vladmandic** [comment]
Hell NO 🤣🤣🤣

**Comment by myndxero** [comment]
34 minutes for 319 models.

**Comment by vladmandic** [comment]
lol

~18sec per model, sounds about right on a decent ssd.

**Comment by myndxero** [comment]
https://www.bestbuy.com/site/crucial-p3-plus-4tb-internal-ssd-pcie-gen-4-x4-nvme/6509710.p?skuId=6509710

Used to only exclusively buy Crucial memory in my early days building computers. Feels like they've sorta become a forgotten classic. I've 2 of these and 2 1 TB SSDs. Still weird to me some days not having a cdrom anymore, and that's now that I'm finally over not having a floppy disk and/or whatever the 100mb disks were, zip drive? Betraying my age a little here!

**Comment by vladmandic** [comment]
If I remeber correctly, my first hard drive was Seagate ST-251-1 connected via MFM controller. 
42MB formatted capacity 🤣

**Comment by vladmandic** [comment]
PENTIUM?!?!? My first CPU was 386SX (not DX which is full 32bit since I couldn't afford it).
and MFM was waaaay before PATA.

**Comment by myndxero** [comment]
I'm trying to remember if I had a 386 first. I can't remember definitively
tho, just that something was so old it had a 20-30 mb hdd and I played
scorched earth, myst, and some CD my brother gave me of jazz music. Dave
Koz? Maybe.

I remember the pentium overdrive and my voodoo rush.

**Comment by vladmandic** [comment]
naaah, if you're talking CDs, you're a kid :)))

**Comment by myndxero** [comment]
My first cassette tape was weird al 'bad hair day' around it's release and
picked up alapalooza too.

**Comment by vladmandic** [comment]
OK, who used a screwdriver to adjust tape deck head angle to be able to load stuff without errors? 🤔😁

**Comment by myndxero** [comment]
Now you lost me haha
