### ISSUE TITLE
[Issue]: Model keeps refreshing forever when I refresh the WEBUI tab on Mozilla.

### ISSUE THREAD

**Issue by onegex1214** [vladmandic/automatic#1238]
### Issue Description

Well basically, sometimes when I happened to refresh to page, either by accident or because I wanted to to reset the settings, I have the icon on models loading forever and it prevents me from further selecting models. Forces me to "restart" from the settings. :(

No error message shows.

### Version Platform Description

Using VENV: I:\vlad-diffusion-webui\automatic\venv
17:21:17-512493 INFO     Running extension preloading
17:21:17-545547 INFO     Starting SD.Next
17:21:17-551554 INFO     Python 3.10.6 on Windows
17:21:18-194360 INFO     Version: 24bbe045 Mon May 29 20:55:33 2023 -0400
17:21:18-510177 INFO     Latest published version: d9f72b066f612e0220f61d142cb5e3106df6afb8 2023-05-31T13:14:15Z
17:21:18-512171 INFO     Setting environment tuning
17:21:18-514177 INFO     nVidia CUDA toolkit detected
17:21:25-774025 INFO     Torch 2.0.0+cu118
17:21:25-821003 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
17:21:25-824006 INFO     Torch detected GPU: NVIDIA GeForce GTX 1080 VRAM 8192 Arch (6, 1) Cores 20
17:21:25-826504 INFO     Verifying requirements
17:21:25-847503 INFO     Installing packages
17:21:25-918003 INFO     Running setup
17:21:25-920003 INFO     Installing repositories
17:21:27-247239 INFO     Installing submodules

**Comment by vladmandic** [comment]
duplicate #1113
