### ISSUE TITLE
[Issue]: No setting for Lora location in system paths

### ISSUE THREAD

**Issue by Electrofried** [vladmandic/automatic#124]
### Issue Description

Under system paths in settings tab you can set the location of almost every resource (a fantastic change btw), however there is no setting here for Lora locations, so only the default path is available.

### Platform Description

Linux, Chrome

**Comment by exodia52** [comment]
I already bring this up. The vlad will look into this. Can see #119.

**Comment by vladmandic** [comment]
unfortunately, Lora folder is defined by extension itself and not in the main repo:

> Lora/preload.py:preload()

```python
parser.add_argument("--lora-dir", type=str, help="Path to directory with Lora networks.", default=os.path.join(paths.models_path, 'Lora'))
```

I'll figure out something, but I don't want to modify extension as then it couldn't be auto-updated anymore.

**Comment by vladmandic** [comment]
ok, pushed update, should work.

**Comment by vladmandic** [comment]
built-in lora support doesn't work or they don't show up in additional networks? that extension maintains its own path to lora files and you need to set it under ui -> settings -> additional networks.

**Comment by biship** [comment]
I was talking about natively, but never mind, it works!
