### ISSUE TITLE
[Feature]: Button "save current settings to ui-config"

### ISSUE THREAD

**Issue by neuralweights** [vladmandic/automatic#1247]
### Feature description

I would like to have a button that saves the current ui state into ui-config. I often tinker with the files and scripts and have to restart often. While the read last generation parameter button is very nice to have, it does not cover scripts. It would just be nice to be able to config the ui once, press the button and forget about it. Or change a few things, click and be done on restart.

I think that would be a very nice feature that I would use often. Searching through the ui-config.json is quite a chore after awhile, some scripts need to be changed double, or some lines are deceptive and you make a mistake and have to reload the ui very often if you edit it

### Version Platform Description

-

**Comment by vladmandic** [comment]
yes, thats planned.

**Comment by vladmandic** [comment]
Done.
