### ISSUE TITLE
[Feature]: Separate ToMe control.

### ISSUE THREAD

**Issue by vidiotgameboss** [vladmandic/automatic#1249]
### Feature description

Currently as it is the token merging is done globally using a slider, from what I've noticed merging at different ratios would provide more optimal results as you can then merge at different ratios individually.

Example would be:
Cross-Attention merged at 0.9 ( yes, it works perfectly at that ratio in my testing), downscale 1.
Attention merged at 0.3-0.6, downscale 2.
MLP merged at 0.1-0.3, downscale 1.

I have already written a feature request on dbolya/tomesd but perhaps it's more of an UI issue rather than ToMe itself needing adjustments so I decided to open a feature request here too.

**Comment by vladmandic** [comment]
that would require that encoding is done multiple times and different encoding results are used in different sub-models. doable, but difficult plus overhead of multiple encoder runs would likely be bigger than benefits of any performance gains.

**Comment by vidiotgameboss** [comment]
> that would require that encoding is done multiple times and different encoding results are used in different sub-models. doable, but difficult plus overhead of multiple encoder runs would likely be bigger than benefits of any performance gains. or perhaps i misunderstood?

No, you understood correctly, perhaps the overhead would outweigh the perfromance benefits as you say, even so I hope this can be considered, if not for performance gains then just for the sake of different results as toying with these settings does provide potential for interesting/better generations already, being more in control wouldn't be a bad thing.

**Comment by vladmandic** [comment]
right now there is no concept of using different encodings for different submodules as results are basically passed as forwards between submodels. so this would be a **major** undertaking. i don't see it happening. even if someone did it and submitted a pr, the dangers of possible regressions would be massive.
