### ISSUE TITLE
[UI Issue]: Edge of screen Extra Network cards expand off screen.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1250]
### Issue Description

Hovering over an Extra Networks card that at the edge of the screen will zoom that card off the edge of the screen/window making part of the text unreadable.

Hovering over
![image](https://github.com/vladmandic/automatic/assets/1969381/8063cc18-863f-4f22-a50f-f3577d0d680a)

becomes
![image](https://github.com/vladmandic/automatic/assets/1969381/ca19c853-eb7e-405e-ac3f-796d8dfb028d)

Suggest adding an option in Settings to disable the zooming behaviour, and/or zoom the image within the confines of the window.

### Version Platform Description

8f4bc4df
Win10/Chrome

**Comment by vladmandic** [comment]
i'll reduce zoom, it was excessive anyhow.
