### ISSUE TITLE
[Extension]: ControlNet disables ToMe until model reload.

### ISSUE THREAD

**Issue by vidiotgameboss** [vladmandic/automatic#1257]
### Issue Description

1. Enable ToMe.
2. Generate once with a ControlNet. You will notice ToMe compression works for this one generation.
3. Disable ControlNet and hit Generate again. You will notice that the ToMe compression has stopped working completely on every successive generation until the model is reloaded.

This should not happen, ToMe should work even with ControlNet active. Currently it only works once after which it deactivates.
I am unsure whether this is an issue with automatic or sd-webui-controlnet so I will write this issue report there too.

### Version Platform Description

Latest Mikubill/sd-webui-controlnet as of writing.
Latest vladmandic/automatic as of writing.

**Comment by vladmandic** [comment]
i'll take a look, but can you use extension template next time since this clearly indicates that controlnet is involved.

**Comment by vidiotgameboss** [comment]
> i'll take a look, but can you use extension template next time since this clearly indicates that controlnet is involved.
Yeah my bad, just saw that.

**Comment by vidiotgameboss** [comment]
fixed as of today with the new controlnet update
