### ISSUE TITLE
[Issue]: "Bad sampler name: None" while using hires fix option.

### ISSUE THREAD

**Issue by mart-hill** [vladmandic/automatic#1259]
### Issue Description

The error shows up like this:

```
02:49:24-050625 ERROR    gradio call: AssertionError
╭─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────╮
│ X:\AI\automatic\modules\call_queue.py:34 in f                                                                    │
│                                                                                                                  │
│    33 │   │   │   try:                                                                                           │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                      │
│                                                                                                                  │
│ X:\AI\automatic\modules\txt2img.py:58 in txt2img                                                                 │
│                                                                                                                  │
│   57 │   if processed is None:                                                                                   │
│ ❱ 58 │   │   processed = process_images(p)                                                                       │
│   59 │   p.close()                                                                                               │
│                                                                                                                  │
│                                             ... 4 frames hidden ...                                              │
│                                                                                                                  │
│ X:\AI\automatic\extensions\sd-webui-neutral-prompt\lib_neutral_prompt\cfg_denoiser_hijack.py:245 in              │
│ create_sampler_hijack                                                                                            │
│                                                                                                                  │
│   244 def create_sampler_hijack(name: str, model, original_function):                                            │
│ ❱ 245 │   sampler = original_function(name, model)                                                               │
│   246 │   if name.startswith(('DDIM', 'PLMS', 'UniPC')):                                                         │
│                                                                                                                  │
│ X:\AI\automatic\modules\sd_samplers.py:30 in create_sampler                                                      │
│                                                                                                                  │
│   29 │   config = find_sampler_config(name)                                                                      │
│ ❱ 30 │   assert config is not None, f'bad sampler name: {name}'                                                  │
│   31 │   if backend == Backend.ORIGINAL:                                                                         │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: bad sampler name: None
```

I wonder if the newest update fixes this - gotta test! :)

### Version Platform Description

01:42:03-296111 INFO     Running extension preloading
01:42:03-309111 INFO     Starting SD.Next
01:42:03-311111 INFO     Python 3.10.9 on Windows
01:42:03-494111 INFO     Version: 562947c9 Fri Jun 2 01:14:12 2023 +0300
01:42:04-078111 INFO     Setting environment tuning
01:42:04-096111 INFO     nVidia CUDA toolkit detected
01:42:06-429611 INFO     Torch 2.0.1+cu118
01:42:06-459114 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
01:42:06-461616 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24575 Arch (8, 6) Cores 82
01:42:06-463615 INFO     Verifying requirements
01:42:06-487113 INFO     Installing packages
01:42:06-698611 INFO     Running setup
01:42:06-699611 INFO     Installing repositories
01:42:13-444840 INFO     Installing submodules
01:42:17-746931 INFO     Updating submodules

Edit:
Oh, so I'm supposed to select some sampler here? I had None here all this time.
![image](https://github.com/vladmandic/automatic/assets/55754730/3c8fb592-abf9-4138-b040-8f8714aaa708)

**Comment by myndxero** [comment]
This is broken for me too after just updating moments ago.

**Comment by mart-hill** [comment]
For me, the only way is to set the "Secondary sampler" to "Euler a" to make this error go away, for now. :)

**Comment by vladmandic** [comment]
the app code does checks for valid samplers - if i've missed any, i'll fix it  
but issue here is in extension `sd-webui-neutral-prompt` - it HIJAACKS sampler creation and performs NO CHECKS  

i've removed `assert` causing runtime error and replace it with error message and fallback to default sampler  
other than that, not much i can do

**Comment by mart-hill** [comment]
Thank you! Now I'll have to report the very same bug, albeit differently "asserted" (`AttributeError: module 'modules.sd_samplers' has no attribute 'create_sampler_original_md'`), for Tiled Diffusion extension. 🙂

**Comment by vladmandic** [comment]
the problem is that both extensions are trying to hijaack same function. so one hijaacks, then second hijaacks, then first one complains "oh, i'm missing something". it works if you set fallback sampler explicity since then extension skips part of its code trying to set it itself, but it doesn't mean they are not misbehaving.
