### ISSUE TITLE
[Feature]: Allow width/height to go higher than 2048 on text and image tabs

### ISSUE THREAD

**Issue by crazygonuts** [vladmandic/automatic#1265]
### Feature description

With some of the new controlnet features - inpaint_only, for example - it would be nice to be able to put the width and height of an image higher than 2048.

**Comment by myndxero** [comment]
You can set this yourself in the ui-config.json using a text editor like wordpad. This is what it would look like in the ui-config.
```
"txt2img/Resize width to/maximum": 2048,
"txt2img/Resize height to/maximum": 2048.

"img2img/Width/maximum": 2048,
"img2img/Height/maximum": 2048,
```

**Comment by vladmandic** [comment]
like @myndxero said, you can edit `ui-config.json` to change maximums. i'm not sure what values other than current 2048 would be "sane" for most users.

**Comment by myndxero** [comment]
https://drive.google.com/file/d/1rqx6qaVXPuulXOmLUg748SN8YYiuNcSZ/view?usp=drive_link

It took an hour to render this at 28 steps, 2048x2048, 115 s/it. I fell asleep. Erm, part of that almost was because I had left 8x upscale post processing on. Oops.

**Comment by vladmandic** [comment]
ok, i get it, but that's literally how stable diffusion works - there is a native resolution model is trained on and if you stray too much from that, you'll get those nightmares. and there are tons of ways to deal with that by segmenting image and processing each part separately, etc...but that's a question for discussions, i don't see an issue here.

and since i don't want to increase maximum native resolution to more than 2k, i'm closing the issue.

**Comment by myndxero** [comment]
If that response was to me, I wasn't trying to change your mind. Just sharing that insane 2048x2048 image of Doc Brown nightmare and wondering why it shared w system ram. On 10 it crashed oom.

**Comment by vladmandic** [comment]
@myndxero it seems that nvidia drivers 532/535 changed the memory management behavior and now vram spills into shared memory.

**Comment by sotonin** [comment]
Hmm.. when exactly did this change? I used Automatic 1111 about a year ago and i have a huge collection of "extras" generated at 3240 x 2160 .... I'm trying to do my normal flow here and it's not even an option anymore it caps at 2048 what gives?

**Comment by vladmandic** [comment]
You can still enter values manually. But yes, limits should be increased for upscaling.

**Comment by sotonin** [comment]
I can not find the right setting to change.... what is the setting for "extras" "Scale To" x and y max?

**Comment by vladmandic** [comment]
your `ui-config.json` is updated while you use sdnext. so if you started using it when maximums were at low values, those maximums are still there. delete `ui-config.json` so ui values are reset to default.

**Comment by sotonin** [comment]
I just did exactly what you recommended. removed the ui-config.json file. relaunched webui and when it loads. still max 2048 on extras

**Comment by vladmandic** [comment]
screenshot?

**Comment by sotonin** [comment]
![Screenshot 2023-10-20 at 5 41 16 AM](https://github.com/vladmandic/automatic/assets/130507/da4f5e94-e2ce-4ae6-94b4-2b212b21be25)

**Comment by vladmandic** [comment]
what am i looking at? that does not look like SDNext at all? and if it is SDNext, what's the version?

**Comment by sotonin** [comment]
Probably my dumb ass getting this mixed up. lmfao. i'm soo sorry. this is automatic 1111
