### ISSUE TITLE
[Issue]: Startup Issues

### ISSUE THREAD

**Issue by HarrisTerry** [vladmandic/automatic#1266]
### Issue Description

I have two issues during startup, I am not sure if the 1st one matters:

1) I often have some sort of error, but often on next startup it is gone and it loads 100%

2) Today on the startup with updates, it froze my computer on its screen, I could not escape it with CTRL ALT DLT or anything, I had to just shut off of the computer. When I reloaded SDNext, it loaded 100% fine?? Working perfectly!

It just seems to get pissed when updating.

### Version Platform Description

Win11, 12700 5GHZ i7, 64GB RAM, m.2 SSDs, 3070ti 8GB

05:53:34-966672 INFO     Version: 561ebc61 Thu Jun 1 20:54:16 2023 -0400

**Comment by vladmandic** [comment]
i'm not sure what do you except me to do with "some sort of error" without actually positing any errors.
and regarding computer freeze, well the app runs in user mode without any priviledges, so only way it would have that kind of impact is bad drivers.

**Comment by HarrisTerry** [comment]
Well, when I say some ort of error, I mean when on loadup it says ERROR on installing or some other process. I was not pointing out the error itself, but the fact on reload it works fine, which was confusing to me.

I have the latest NVIDIA drivers but I will update to make sure. Thanks for the reply.

**Comment by vladmandic** [comment]
again, it says error SOMETHING - without actual error, there is nothing i can do.
and yes, a lot of git operations do frequently have transient errors that go away, just the nature of git.
