### ISSUE TITLE
[Feature]: Fixing of Sampler Flaws (falsely interpolated steps / limiting results to medium brightness)

### ISSUE THREAD

**Issue by TheOnlyHolyMoly** [vladmandic/automatic#1268]
### Feature description

Reminder for conversation (https://github.com/vladmandic/automatic/discussions/1091#discussioncomment-6031380) as requested by @vladmandic 

Mainly the issue narrows down to issues with the timesteps function leading to a Non-Zero Terminal Noise Ratio, leading to a bias in at least DDIM samplers, but possibly other samplers that follow the timesteps approach. 

Details and solution approach captured in above linked discussion thread.

Resources
https://github.com/huggingface/diffusers/issues/2585
DDIM Repo Owner >https://github.com/ermongroup/ddim
Scientific Paper on problems & fixing: https://arxiv.org/abs/2305.08891

### Version Platform Description

Affects all platforms

**Comment by DirtyHamster** [comment]
There was a live stream going over this paper last week: https://www.youtube.com/watch?v=o1eJAUe-czQ

**Comment by vladmandic** [comment]
implemented in diffusers, no plan to bring it to original backend at the moment.
