### ISSUE TITLE
[Issue]: Generate Forever Not Working

### ISSUE THREAD

**Issue by exodia52** [vladmandic/automatic#127]
### Issue Description

![image](https://user-images.githubusercontent.com/121444875/232058571-509e48a5-a5bd-4866-afd0-5b686610a750.png)

![image](https://user-images.githubusercontent.com/121444875/232058650-ff80a4c5-82e7-4412-a1ad-c0f0637748df.png)

The image above is how you Generate Forever until you cancel it yourself. Currently Generating Forever is not working. Nothing happens when you click it.

### Platform Description

Window 10
Ryzen 7 2700
RTX 3060 Ti

**Comment by vladmandic** [comment]
fixed.

**Comment by exodia52** [comment]
> fixed.

Holy that was fast. Thank you very much ! I been abusing this feature bcs i always have to stay away from my PC from time to time. Really appreciate it.

**Comment by vladmandic** [comment]
original a1111 was checking if interrupt button had offset component to check if server is busy - that is baaad.
so any new skin was bound to break that.

i just implemented actual busy check.
