### ISSUE TITLE
[Issue]: Ipex fails to generate with Signals.SIGABRT

### ISSUE THREAD

**Issue by blaaaarggg** [vladmandic/automatic#1272]
### Issue Description

Unable to generate images. Intel Arc A770

After selecting Generate, errors below are displayed: 

Initializing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:00Abort was called at 718 line in file:
./shared/source/os_interface/windows/wddm_memory_manager.cpp
Traceback (most recent call last):
  File "/home/vm/.local/bin/ipexrun", line 8, in <module>
    sys.exit(main())
  File "/home/vm/.local/lib/python3.10/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 880, in main
    launcher.launch(args)
  File "/home/vm/.local/lib/python3.10/site-packages/intel_extension_for_pytorch/cpu/launch.py", line 542, in launch
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd_s)
subprocess.CalledProcessError: Command 'taskset -c 0-11 /usr/bin/python3 -u launch.py --use-ipex' died with <Signals.SIGABRT: 6>.

I followed the instructions in this video when installing: https://www.youtube.com/watch?v=YJeP6XJqa00

**Comment by vladmandic** [comment]
it looks like ipex drivers are not correctly installed and they are failing.
looping in @Disty0

**Comment by Disty0** [comment]
Remove config.json and venv folder then try again with this command:
`./webui.sh --use-ipex`

You have to use --use-ipex otherwise it will fall back to DirectML or CPU only.
Use webui.sh instead of launch.py. 
That guide is written for A1111 forks.

**Comment by blaaaarggg** [comment]
I removed the config.json and venv folder. After running the command, the error below is returned:

vm@Computer:~/automatic$ ./webui.sh --use-ipex
Create and activate python venv
Launching launch.py...
Traceback (most recent call last):
  File "/home/vm/.local/bin/ipexrun", line 5, in <module>
    from intel_extension_for_pytorch.cpu.launch import main
  File "/home/vm/.local/lib/python3.10/site-packages/intel_extension_for_pytorch/__init__.py", line 8, in <module>
    from .utils._trap_module import *
  File "/home/vm/.local/lib/python3.10/site-packages/intel_extension_for_pytorch/utils/_trap_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: /home/vm/.local/lib/python3.10/site-packages/intel_extension_for_pytorch/lib/libintel-ext-pt-gpu.so: undefined symbol: _ZNK5torch8autograd4Node4nameB5cxx11Ev

**Comment by Disty0** [comment]
Remove auromatic entirely and perform a clean install.
Seems like you have modified the webui.sh.

Git clone automatic and do not do anything other than running ./webui.sh --use-ipex

**Comment by Disty0** [comment]
Wrote my own guide:
https://www.technopat.net/sosyal/konu/using-stable-diffusion-webui-with-intel-arc-gpus.2593077/

**Comment by vladmandic** [comment]
Care to post it to discussions so it's searchable?

**Comment by blaaaarggg** [comment]
I found the issue was due to having iGPU enabled. After disabling iGPU, the wddm_memory_manager.cpp error no longer occurs. iGPU can be disabled under device manager or BIOS settings. Thanks again for your help!

**Comment by dstults** [comment]
@Disty0
> Wrote my own guide: https://www.technopat.net/sosyal/konu/using-stable-diffusion-webui-with-intel-arc-gpus.2593077/

Thank you, that's the best up-to-date guide I've found on the Intel Arc so far, plus it has everything in one place.

I'm still getting used to my Arc/WSL2, but the following might be useful additions:

```
# Required for mentioned hotfix (should be easy enough to figure out, but couldn't hurt?
sudo apt install unzip

# Possibly for WSL2 only, add to .bashrc, not sure if all three are needed but they seem to be for me
source /opt/intel/oneapi/setvars.sh
source /opt/intel/oneapi/compiler/latest/env/vars.sh
source /opt/intel/oneapi/mkl/latest/env/vars.sh
```

Previously I only had the `source /opt/intel/oneapi/setvars.sh` set and was having issues, then I got the idea to try the other two from this thread:
https://github.com/intel/intel-extension-for-pytorch/issues/287#issuecomment-1546730869
