### ISSUE TITLE
[Feature]: Generate Forever/Cancel Generate Forever Physical buttons

### ISSUE THREAD

**Issue by MrGingerSir222** [vladmandic/automatic#1274]
### Feature description

Can we get the generate forever and cancel generate forever options as actual buttons? I use my iPhone to access stable diffusion often, and for some reason it doesn't allow me to "right click" (click the screen using two fingers for iPhone) on the generate button to access these options. 
Thanks for your consideration.

**Comment by MrGingerSir222** [comment]
For iPhone users, that only highlights the text on the button (even if not pressing near the text).

**Comment by vladmandic** [comment]
additional buttons are not expected as i don't see a need for this.
