### ISSUE TITLE
[Issue]: Automatic Re-Installs all the incompatible extensions every time I start it?

### ISSUE THREAD

**Issue by Vendaciousness** [vladmandic/automatic#1280]
### Issue Description

I must be doing something wrong, because there's no way you would actually set it up this way...

I use Deforum.  It's the only extension besides ControlNet I ever use.  Extensions like Multidiffusion Tiled VAE cause it to crash, so I can't have it installed. You've set as "builtin", which I disagree with, but I guess I can uninstall it.  Now, it seems every time I start the webui from scratch, it re-installs all the broken extensions I can't use!  I have to uninstall them EVERY TIME I LOAD THE PROGRAM?!

These programs break my extension every time I load your version of Auto1111:

[sd-dynamic-thresholding](https://github.com/mcmonkeyprojects/sd-dynamic-thresholding.git)

[multidiffusion-upscaler-for-automatic1111](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111.git)

I'm also pretty sure you have it automatically update WebUI and every extension, which would have seemed unwise even after using this software a few weeks. I don't want to experience every bug as it happens, thanks.

Please consider making it a little easier to have a stable copy of Automatic.

-V

**Comment by vladmandic** [comment]
just set them to disabled.
