### ISSUE TITLE
[Issue]: Title: Unresponsive UI After Latest Update with "--autolaunch" Command

### ISSUE THREAD

**Issue by Eagle07-Sudo** [vladmandic/automatic#1282]
### Issue Description

**Issue Summary**

After the latest update, when starting the application using the `--autolaunch` command, the UI becomes unresponsive and lacks any kind of interaction. Even the _Restart server_ button does not respond. Additionally, while the _Agent Scheduler_ extension is present, the _Enqueue_ buttons are missing. Refreshing the page temporarily resolves the problem, but a server restart causes the issue to reappear. However, when starting the application by clicking the link in the command box, it functions normally, and a server restart does not cause any problems.

**Additional Information**

- The issue started occurring after the latest update.
- The problem seems to be specific to the `--autolaunch` command, as starting the application by clicking the link in the command box works as expected.
- The issue can be temporarily resolved by refreshing the page, but it reappears after a server restart, and no additional lines are added to the webui.log file after the refresh.
- The issue still persists when using the `--safe` command.

Please let me know if you need any further information or clarification.

### Version Platform Description

Environment:
- Version: 299f1229 Fri Jun 2 20:54:09 2023 -0400
- Nvidea Geforce RTX 2080
- Operating System: Win11
- Browser: Microsoft Edge (latest)

**Comment by gitbreiti** [comment]
Same here!

**Comment by LucasBGonzales** [comment]
Same here. I reinstalled the whole thing cleanly and it worked with autolaunch again, but then this morning the problem occurred again (before and after pulling).

**Comment by vladmandic** [comment]
autolaunch is internal function of gradio and last gradio change was on may 22nd.
so if it was working recently and its not now, its not because of changes in the app.

and looking at gradio code, it simply calls python built-in module `webbrowser.open(link)` - that's it.

how does python internally decide what to do and then actually do it? no idea - and even if i find something, it would require changes to python itself which is not going to happen.

and there really isn't any good way to debug what's going on there.

i'm sorry this is happening, but i really don't know how to proceed.

**Comment by LucasBGonzales** [comment]
Update: It seems to actually be fine after several seconds if the page is reopened. I refreshed 3 times and eventually the "Enqueue" button reappeared and the app was responsive again.
....
So I tried starting it without the --automatic and refreshed the page immediately when the server was up and same problem. So it appears to occur regardless of launch commands and its a period of time just after the server starts where this happens. 
...
Okay, so I use the default gradio theme and have this issue, but I noticed I didn't have the issue when black-orange was selected on fresh install. And it seems that putting it back to black-orange completely solved the problem for me. Put it back to Gradio Default and the problem returned. 

TLD If you have this issue, you can use other themes but they may cause unresponsive UI for the first few moments the server is running. Refresh the page a few times and it should be fine.

**Comment by TeutonJon78** [comment]
It seems to be an issue with the agent-scheduler. I have the same problem -- webpage loads, I can push buttons and switch tabs, but NOTHING happens. If you disable agent-scheduler in the config.json, things work normally again.

**Comment by vladmandic** [comment]
so basically it sounds like browser is asked to load the page before page is ready and its causing excessive dom recalculations in the browser.

**Comment by vladmandic** [comment]
As far as I can tell, impact is if autolaunch is enabled and only some users, far from "everyone".

**Comment by vladmandic** [comment]
i've removed autolaunch from gradio to an explict autolaunch a little bit later in the code, let me know if it helps.

**Comment by Eagle07-Sudo** [comment]
> i've removed autolaunch from gradio to an explict autolaunch a little bit later in the code, let me know if it helps.

Thanks a lot for sorting that out! The `--autolaunch` is back to working normally.
