### ISSUE TITLE
[Issue]: missing controlNet models in dropdown

### ISSUE THREAD

**Issue by Raivshard** [vladmandic/automatic#1288]
### Issue Description

The model dropdown in ControlNet is not showing any models. selecting any of the radio box options also does not select a model. Only the preprocessor can be selected.
https://i.imgur.com/TniVOKI.jpeg

For reference, the models are physically there in the relevant folder structure for the extension.
No log errors have been noted.

### OS, GPU, Browser
Windows 10
2070 Super
Firefox

### Extensions
- sd-webui-agent-scheduler
- SwinIR
- ScuNET
- Lora
- LDSR
- a1111-sd-webui-lycorisscript
- sd-webui-controlnetmanipulations
- sd-extension-system-infoscript, tab
- multidiffusion-upscaler-for-automatic1111manipulations
- sd-dynamic-thresholdingmanipulations
- stable-diffusion-webui-rembgscript, extras
- clip-interrogator-exttab, query
- sd-webui-infinite-image-browsingtab, UI related
- sd-webui-photopea-embed
- openpose-editortab
- adetailermanipulations
- Cozy-NestUI related
- batch-face-swapediting
- sd-webui-llulmanipulations

### Version Platform Description

Version: 549c02a8 Sat Jun 3 10:36:53 2023 -0400

**Comment by brknsoul** [comment]
> For reference, the models are physically there in the relevant folder structure for the extension.

Just to ensure, you've downloaded models from https://huggingface.co/lllyasviel/ControlNet-v1-1/tree/main and placed them into `automatic\models\ControlNet` ?
