### ISSUE TITLE
[Issue]: Clip skip widget not showing up, despite being in Quicksettings list

### ISSUE THREAD

**Issue by Trevor-Z** [vladmandic/automatic#1289]
### Issue Description

In a fresh installation done today, without any additions, the CLIP_stop_at_last_layers item in the Quicksettings is being ignored.

![Screenshot 2023-06-03 163646](https://github.com/vladmandic/automatic/assets/13950948/e9c60b21-e86a-4605-882e-98014826aae8)
![Screenshot 2023-06-03 163626](https://github.com/vladmandic/automatic/assets/13950948/35ce93c8-55a6-4667-85d6-b6160ade8b76)

### Version Platform Description

updated: 2023-06-03
hash: 549c02a8

**Comment by vladmandic** [comment]
just don't put it in quick settings! scroll down just a little bit more than your screenshot and you'll see its in local settings already. this has been asked and answered several times.
