### ISSUE TITLE
[Issue]: Textual inversions not showing up on the Extra Network UI 

### ISSUE THREAD

**Issue by Holyniwa** [vladmandic/automatic#129]
### Issue Description

When looking at the cmd box, it seems to load all the TI, but when trying to look for them in the extra network tab, they seem to be missing

You can see it properly pathed here
![chrome_yRImhUbR4A](https://user-images.githubusercontent.com/13576034/232078202-f6265e5a-5519-4749-a814-b1a20727184a.png)

No images loading
![chrome_irFp3gPRHd](https://user-images.githubusercontent.com/13576034/232078214-ff5280e3-c8fa-4163-aaf3-5b9075046020.png)

my directory to show
![explorer_6Jkzblvw8f](https://user-images.githubusercontent.com/13576034/232078235-fb1cc2b1-26dc-4dfb-9460-7358028a8b7a.png)

the cmd does load them
![cmd_HgkZfjaDON](https://user-images.githubusercontent.com/13576034/232078262-e78663a2-5019-46ab-a459-7f20d70c0a7e.png)

### Platform Description

Windows, Chrome

**Comment by econundrum** [comment]
If you press the refresh button on the extra networks they show up.

**Comment by vladmandic** [comment]
fixed.
this was a core issue, i'll also submit a pr to a1111.
issue was that extra network objects were enumerated early and embeddings cannot be loaded until model is loaded (since embeddings change model dictionary). so they are blank on startup, but once model is loaded, refresh works.
