### ISSUE TITLE
[Issue]: Save to directory when saving is ignored

### ISSUE THREAD

**Issue by afbagwell** [vladmandic/automatic#1290]
### Issue Description

Image Options -> "When using Save button, save images to a subdirectory" no longer places pictures in a sub-directory of the Save folder. Instead all files are placed directly in the Save folder whether the option is checked or not.

### Version Platform Description

commit 299f1229
Windows 11 Pro
Firefox 113.0.2 (64-bit)

**Comment by vladmandic** [comment]
fixed.
