### ISSUE TITLE
[Issue]: How to edit-out built-in extensions forcefully re-downloading everytime, even after disabling..

### ISSUE THREAD

**Issue by onegex1214** [vladmandic/automatic#1292]
### Issue Description

I do not know where I can edit this out, but even tho I haven't written --upgrade, when I launch it keeps re-downloading built-in extensions that I do not want like Steps animation and stuff like that. 

I would simply like to know here I need to go to edit out some built-in stuff and automated upgrades. Please! Thanks in advance

**Comment by vladmandic** [comment]
first, that particular extension has been removed a while ago, so i suggest you upgrade in general.
second, see #1284

**Comment by onegex1214** [comment]
I'm on the latest version from June 2.. that was just an example btw, but it's happening with Agent Scheduler now, and since Agent Scheduler keeps showing up with that Generate button error I can't use it right now, and so I'm forced to re-launch the Webui 3-4 times by manually deleting the builtin extension folders myself since I can't disable them even after enabling "ignore extensions" in the main config files..

Could you just please tell me where I can make sure to disable the automatic process ?

**Comment by vladmandic** [comment]
how to disable any extension #1284
