### ISSUE TITLE
[Issue]: New virsion can't start webui

### ISSUE THREAD

**Issue by simonvon2023** [vladmandic/automatic#1295]
### Issue Description

02:31:33-595103 INFO     Loading UI theme: name=black-orange style=Auto         
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/automatic/launch.py:149 in <module>                                 │
│                                                                              │
│   148                                                                        │
│ ❱ 149     instance = start_server(immediate=True, server=None)               │
│   150     while True:                                                        │
│                                                                              │
│ /content/automatic/launch.py:129 in start_server                             │
│                                                                              │
│   128         else:                                                          │
│ ❱ 129             server = server.webui()                                    │
│   130     if args.profile:                                                   │
│                                                                              │
│ /content/automatic/webui.py:276 in webui                                     │
│                                                                              │
│   275     start_common()                                                     │
│ ❱ 276     start_ui()                                                         │
│   277     load_model()                                                       │
│                                                                              │
│ /content/automatic/webui.py:204 in start_ui                                  │
│                                                                              │
│   203     startup_timer.record("scripts before_ui_callback")                 │
│ ❱ 204     shared.demo = modules.ui.create_ui()                               │
│   205     startup_timer.record("ui")                                         │
│                                                                              │
│ /content/automatic/modules/ui.py:353 in create_ui                            │
│                                                                              │
│    352     modules.scripts.scripts_current = modules.scripts.scripts_txt2img │
│ ❱  353     modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=Fal │
│    354     with gr.Blocks(analytics_enabled=False) as txt2img_interface:     │
│                                                                              │
│ /content/automatic/modules/scripts.py:282 in initialize_scripts              │
│                                                                              │
│   281         for script_class, path, _basedir, _script_module in auto_proce │
│ ❱ 282             script = script_class()                                    │
│   283             script.filename = path                                     │
│                                                                              │
│ /content/automatic/extensions-builtin/sd-webui-agent-scheduler/scripts/task_ │
│ scheduler.py:26 in __init__                                                  │
│                                                                              │
│    25         self.checkpoint_override = checkpoint_current                  │
│ ❱  26         self.generate_button                                           │
│    27                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Script' object has no attribute 'generate_button'

### Version Platform Description

Version: 5190f702 Sat Jun 3 14:02:21 2023 -0400

**Comment by vladmandic** [comment]
This is 4tg duplicate for the same issue. Please check first.
