### ISSUE TITLE
[Issue]: Unable to run after update

### ISSUE THREAD

**Issue by limico99** [vladmandic/automatic#1296]
### Issue Description

Please fill this form with as much information as possibleUsing VENV: C:\Users\LIMICO\Downloads\automatic\venv
13:01:01-532717 INFO     Running extension preloading
13:01:01-546270 INFO     Starting SD.Next
13:01:01-547277 INFO     Python 3.10.7 on Windows
13:01:01-599460 INFO     Version: 5190f702 Sat Jun 3 14:02:21 2023 -0400
13:01:02-033315 INFO     Setting environment tuning
13:01:02-036866 INFO     nVidia CUDA toolkit detected
13:01:03-793966 INFO     Torch 2.0.1+cu118
13:01:03-807981 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
13:01:03-809987 INFO     Torch detected GPU: NVIDIA GeForce GTX 1060 6GB VRAM 6144 Arch (6, 1) Cores 10
13:01:03-811987 INFO     Verifying requirements
13:01:03-836539 INFO     Installing packages
13:01:03-902160 INFO     No changes detected: Quick launch active
13:01:03-903165 INFO     Running extension preloading
13:01:03-905166 INFO     Server arguments: []
13:01:11-837114 INFO     Libraries loaded
13:01:11-841206 INFO     Using data path: C:\Users\LIMICO\Downloads\automatic
13:01:11-845206 INFO     Available VAEs: C:\Users\LIMICO\Downloads\automatic\models\VAE 2
13:01:11-876553 INFO     Available models: C:\Users\LIMICO\Downloads\automatic\models\Stable-diffusion 13
2023-06-04 13:01:15,359 - ControlNet - INFO - ControlNet v1.1.215
2023-06-04 13:01:15,630 - ControlNet - INFO - ControlNet v1.1.215
[-] ADetailer initialized. version: 23.6.1.post0, num models: 8
13:01:18-278086 INFO     Running extension preloading
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: C:\Users\LIMICO\Downloads\automatic\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
13:01:19-984401 INFO     Loading UI theme: name=gradio/default style=Light
                                                                                          Traceback (most recent call last) 
C:\Users\LIMICO\Downloads\automatic\launch.py:149 in &lt;module&gt;

&nbsp;&nbsp;148
❱ 149     instance = start_server(immediate=True, server=None)
&nbsp;&nbsp;150     while True:

C:\Users\LIMICO\Downloads\automatic\launch.py:129 in start_server

&nbsp;&nbsp;128         else:
❱ 129             server = server.webui()
&nbsp;&nbsp;130     if args.profile:

C:\Users\LIMICO\Downloads\automatic\webui.py:276 in webui

&nbsp;&nbsp;275     start_common()
❱ 276     start_ui()
&nbsp;&nbsp;277     load_model()

C:\Users\LIMICO\Downloads\automatic\webui.py:204 in start_ui

&nbsp;&nbsp;203     startup_timer.record("scripts before_ui_callback")
❱ 204     shared.demo = modules.ui.create_ui()
&nbsp;&nbsp;205     startup_timer.record("ui")

C:\Users\LIMICO\Downloads\automatic\modules\ui.py:353 in create_ui

&nbsp;&nbsp;352     modules.scripts.scripts_current = modules.scripts.scripts_txt2img
❱  353     modules.scripts.scripts_txt2img.initialize_scripts(is_img2img=False)
&nbsp;&nbsp;354     with gr.Blocks(analytics_enabled=False) as txt2img_interface:

C:\Users\LIMICO\Downloads\automatic\modules\scripts.py:282 in initialize_scripts

&nbsp;&nbsp;281         for script_class, path, _basedir, _script_module in auto_processing_scripts + sc
❱ 282             script = script_class()
&nbsp;&nbsp;283             script.filename = path

C:\Users\LIMICO\Downloads\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:26 in __init__               

&nbsp;&nbsp;25         self.checkpoint_override = checkpoint_current
❱  26         self.generate_button
&nbsp;&nbsp;27

AttributeError: 'Script' object has no attribute 'generate_button'
Press any key to continue. . .

### Version Platform Description

Version: 5190f702 Sat Jun 3 14:02:21 2023 -0400
Python 3.10.7 on Windows
torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce GTX 1060 6GB VRAM 6144 Arch (6, 1) Cores 10
xformers 0.0.17
tensorflow 2.12.0

**Comment by jinxishe** [comment]
same problem

**Comment by cjps-br** [comment]
to be able to use sd.next, I deleted the sd-webui-agent-scheduler extension directory inside Automatic\extensions-builtin

**Comment by limico99** [comment]
> sd.next를 사용할 수 있도록 Automatic\extensions-builtin 내부의 sd-webui-agent-scheduler 확장 디렉토리를 삭제했습니다.

Thank you, it works normally after removing "sd-webui-agent-scheduler" folder
