### ISSUE TITLE
[Feature]: Built-in wildcards

### ISSUE THREAD

**Issue by ghost** [vladmandic/automatic#1299]
### Feature description

I had so many problems with using extensions for wildcards. Dynamic prompts extension crashes and bricks every week, Unprompted had some other issues I was unable to resolve (I think it was how it handles batches). There is a wildcards extension but it is very old. Could there be built-in support for simple wildcards? So that it defaults to the in-built solution as long as there isnt another extension with wildcard support installed. I know a few people who all had the same problem as me.

I am in the process of learning how to contribute on Github so I might make a PR at some point, but until then... right now I can not use wildcards at all because dynamic prompts died again.

If this is possible then it would be great to be able to run a controlnet or img2img batch through it and not have the same prompt for the entire run

### Version Platform Description

-

**Comment by DirtyHamster** [comment]
What kind of dynamics are you trying to do?

**Comment by neuralweights** [comment]
I was only using the standard for wildcards: __wildcard__

There is no real wildcards-only extension that is not outdated right now, and the other ones are quite large for that I only use a few wildcard codes

**Comment by DirtyHamster** [comment]
Ok so what are the codes you wanted to use and what did you want them to do?

**Comment by TheOnlyHolyMoly** [comment]
Have not looked into wildcards too deeply yet, is this like running a set of prompts through?

**Comment by neuralweights** [comment]
Uhm... if you have prompt "beautiful picture of a zebra" then you only get zebras. With wildcards you make it like "beautiful picture of __ animal __" (without empty spaces__) and then you will get a lion, a cat, a dog,... all read from a txt file you create and put in a directory that is named "animal.txt".

Its pretty neat to get more variation in your output. You can use it for everything

**Comment by vladmandic** [comment]
i'm not against it, but that is not something i'd put in a base app, that's an extension.
i get what you're saying that existing extensions are either flaky or often broken, but it doesn't mean it shouldn't be an extension.

**Comment by DirtyHamster** [comment]
I think this can kind of be covered under the edit styles that we were talking about last week: https://github.com/vladmandic/automatic/issues/1201

From my large prompt that I mentioned:
In a prompt this is already natively supported:
"IF neckline:("(detail:1)(lace:0.3)(silk:0.3)(leather:0.3)(mesh:0.3)(transparent:0.5)","(colorful:0.25)(black:0.5)(white:0.5)","(detailed patterns)")",

The material weights sometimes seems to get translated as chance to be that one type rather than a percentage of or degree of merging the material being called. So it just might end up where and how you have to write the prompt and if it's trained into the model.

**Comment by vladmandic** [comment]
Not really. Any chance of built in styles I want to keep absolutely simple.
And this is very far from that.

**Comment by DirtyHamster** [comment]
I'm not saying do it extra I'm saying it's there already if I can call that into the prompt it should work.

**Comment by vladmandic** [comment]
dev branch allows for referening to new styles concept using partial names. so you can place n number of styles in a folder and refer to style in a promt using a folder name (or a partial filename) and it will cycle between them.

dev will be merged to master soon.
