### ISSUE TITLE
[Issue]: Error With Tag Autocomplete Extension

### ISSUE THREAD

**Issue by exodia52** [vladmandic/automatic#130]
### Issue Description

Additional Network extension not installed, Only hijack built-in lora
LoCon Extension hijack built-in lora successfully
loading script: tag_autocomplete_helper.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\zerok\Downloads\Test\automatic2\modules\scripts.py:255 in load_scripts                                     │
│                                                                                                                     │
│   254 │   │   │                                                                                                     │
│ > 255 │   │   │   script_module = script_loading.load_module(scriptfile.path)                                       │
│   256 │   │   │   register_scripts_from_module(script_module)                                                       │
│                                                                                                                     │
│ C:\Users\zerok\Downloads\Test\automatic2\modules\script_loading.py:12 in load_module                                │
│                                                                                                                     │
│   11 │   module = importlib.util.module_from_spec(module_spec)                                                      │
│ > 12 │   module_spec.loader.exec_module(module)                                                                     │
│   13                                                                                                                │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ C:\Users\zerok\Downloads\Test\automatic2\extensions\a1111-sd-webui-tagcomplete\scripts\tag_autocomplete_helper.py:2 │
│ 7 in <module>                                                                                                       │
│                                                                                                                     │
│    26 WILDCARD_PATH = FILE_DIR.joinpath('scripts/wildcards')                                                        │
│ >  27 EMB_PATH = Path(shared.cmd_opts.embeddings_dir)                                                               │
│    28 HYP_PATH = Path(shared.cmd_opts.hypernetwork_dir)                                                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Namespace' object has no attribute 'embeddings_dir'
Loading booru2prompt settings
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[VRAMEstimator] No stats available, run benchmark first
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: C:\Users\zerok\Downloads\Test\automatic2\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.

Model loaded in 47.9s (load=3.0s create=0.7s apply=30.8s vae=1.5s move=1.2s hijack=9.8s embeddings=1.0s)
00:23:15-413464 INFO     Startup time: 186.0s (torch=7.7s libraries=2.9s models=0.2s codeformer=0.3s gfpgan=0.1s
                         scripts=54.7s ui=71.2s gradio=0.8s scripts app_started_callback=0.1s checkpoint=48.1s)
API error: GET: http://127.0.0.1:7860/file=tmp/tagAutocompletePath.txt?1681489614021 {'error': 'RuntimeError', 'detail': '', 'body': '', 'errors': 'File at path C:\\Users\\zerok\\Downloads\\Test\\automatic2\\tmp\\tagAutocompletePath.txt does not exist.'}
http api: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\zerok\Downloads\Test\automatic2\venv\lib\site-packages\anyio\streams\memory.py:94 in receive               │
│                                                                                                                     │
│ C:\Users\zerok\Downloads\Test\automatic2\venv\lib\site-packages\anyio\streams\memory.py:89 in receive_nowait        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
WouldBlock

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\zerok\Downloads\Test\automatic2\venv\lib\site-packages\starlette\middleware\base.py:78 in call_next        │
│                                                                                                                     │
│ C:\Users\zerok\Downloads\Test\automatic2\venv\lib\site-packages\anyio\streams\memory.py:114 in receive              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
EndOfStream

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\zerok\Downloads\Test\automatic2\modules\api\api.py:132 in exception_handling                               │
│                                                                                                                     │
│   131 │   │   try:                                                                                                  │
│ > 132 │   │   │   return await call_next(request)                                                                   │
│   133 │   │   except Exception as e:                                                                                │
│                                                                                                                     │
│ C:\Users\zerok\Downloads\Test\automatic2\venv\lib\site-packages\starlette\middleware\base.py:84 in call_next        │
│                                                                                                                     │
│                                              ... 13 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\zerok\Downloads\Test\automatic2\venv\lib\site-packages\starlette\routing.py:69 in app                      │
│                                                                                                                     │
│ C:\Users\zerok\Downloads\Test\automatic2\venv\lib\site-packages\starlette\responses.py:338 in __call__              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: File at path C:\Users\zerok\Downloads\Test\automatic2\tmp\tagAutocompletePath.txt does not exist.

As title said. When starting with the extension it will always bring this error and the Extension won't work in the WebUI.

### Platform Description

Window 10
Ryzen 7 2700
RTX 3060 Ti

**Comment by vladmandic** [comment]
duplicate #106, fix is already posted

**Comment by exodia52** [comment]
Ah didn't notice that one. I should had done more searching. Thanks.
