### ISSUE TITLE
[Issue]: Unexpected behaviour of fallback sampler setting > none vs. explicit setting

### ISSUE THREAD

**Issue by TheOnlyHolyMoly** [vladmandic/automatic#1303]
### Issue Description

I think I may have found a glitch in the fall-back sampler logic

My understanding was that when I set "none" as fallback simpler it should use the same sampler for hires fix as for text2image  thus the image should be the same outcome as when I explictly set exactly the same fallsampler that I have selected in Text2Image... (I tried to simplify my settings today). However, the pictures come out differently and setting the fallback sampler explicitly gives me greater detail and better lights in the image. 

Steps: 40 | Sampler: DPM++ SDE | CFG scale: 10 | Seed: 289311804 | Face restoration: CodeFormer | Size: 768x768 | Model hash: 063e9ed089 | Model: sdartCompleteEdition_v2Base21 | VAE: vae-ft-mse-840000-ema-pruned (1) | Seed resize from: 2048x2048 | Denoising strength: 0.5 | Clip skip: 1 | Version: 5190f70 | Parser: Full parser | Hires upscale: 2 | Hires steps: 20 | Hires upscaler: None | Dynamic thresholding enabled: True | Mimic scale: 7 | Threshold percentile: 100

Images A and B where both generated upon the exact same settings (both using DPM++ SDE) with the only difference in settings DPM++ SDE vs. None

Image A > FALLBACK Sampler = None
![Image A (fallback is NONE)](https://github.com/vladmandic/automatic/assets/131612312/33b52ae8-8778-4ae1-9f62-6ac4754d1ff1)
Image B > FALLBACK Sampler = DPM++ SDE
![Image B (fallback is DPM++ SDE](https://github.com/vladmandic/automatic/assets/131612312/98699b4b-eb36-40c6-b35f-e9fb26d5a131)

### Version Platform Description

13:42:03-494835 INFO     Running extension preloading
13:42:03-597506 INFO     Starting SD.Next
13:42:03-601528 INFO     Python 3.10.6 on Windows
13:42:03-808667 INFO     Version: 5190f702 Sat Jun 3 14:02:21 2023 -0400
13:42:04-447377 INFO     Latest published version: b127ca48742a6a78be3234da2358dc69fdc5220f 2023-06-04T11:05:29Z
13:42:04-451357 INFO     Setting environment tuning
13:42:04-456344 INFO     nVidia CUDA toolkit detected
13:42:21-772809 INFO     Torch 2.0.0+cu118
13:42:21-903762 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
13:42:21-915730 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24563 Arch (8, 9) Cores 128
13:42:21-919730 INFO     Verifying requirements
13:42:21-958751 INFO     Installing packages
13:42:22-173729 INFO     Running setup
13:42:22-176731 INFO     Installing repositories
13:42:26-772736 INFO     Installing submodules

**Comment by vladmandic** [comment]
yes, there was a flaw in logic, should be corrected now. let me know if it still persists and i'll revisit.
