### ISSUE TITLE
[Issue]: Popup/Overlay Image Viewing During Image Generation Not Working

### ISSUE THREAD

**Issue by rcwatkins** [vladmandic/automatic#1304]
### Issue Description

Description:

The popup/overlay view for displaying full-size images is not functioning correctly during image generation. After generating an image, clicking on it opens the popup/overlay as expected. However, if a new image is generated the popup/overlay view of the previous generation fails to work until the image generation is complete. This issue occurs in both "txt2img" and "img2img" modes.

Steps to Reproduce:

    Generate an image.
    Start another generation and while it is being generated, click on the previous image.
    Once the image generation is complete, the popup/overlay view resumes functioning correctly.

Expected Behavior:

The popup/overlay view should remain functional even during generation.

**Comment by vladmandic** [comment]
first, any issue without version and platform description is INVALID. it really doesn't take much to fill it.

second, how are you even able to click on the previous image since preview replaces gallery view. and even if you disable live preview, you cannot click on image, lightbox is not displayed.

you're "expected behavior" is not really expected.

**Comment by rcwatkins** [comment]
Sorry for leaving out the version, and thank you for the reply. I started experiencing the issue after pulling yesterday, but updated again today to:
73015663530874af6c8539ed1180fbdf0c0a79b4

I do have live preview disabled, but I'm not sure what you mean by "lightbox is not displayed".

In prior versions my expected behavior is how it was working, something changed recently. Please allow me to elaborate, because I feel this is a valid issue. When you generate without live preview, your previous gen would remain visible (and clickable/expandable) until the current gen would complete. On the current version the previous gen remains visible, but nothing happens when you click on it. If my expected behavior is not expected, then what would you expect to happen without live preview while generating continuously? You get to only view the thumbnail of all the gens after each one completes and you cannot expand them? Because that's the current behavior. If I can see my previous generation while working on the next generation, wouldn't the expected behavior be that you can click and expand the image?

If there is any additional info I can provide, please let me know.

**Comment by vladmandic** [comment]
i don't really consider that "expected" behavior, more of a side-effect. but since fix was simple, i've just done it.
