### ISSUE TITLE
[Feature]: Use deviating model dict

### ISSUE THREAD

**Issue by TheOnlyHolyMoly** [vladmandic/automatic#1306]
### Feature description

I have been playing with the settings parameter "reuse previous model dict". I got some amazing images through unexpected combinations of model vs. foreign dict, however as only the checkpoint but not the used dict - if deviating - copies down in the meta-data of the image I cannot determine anymore what combinations where used effectively. It turned checkpoints into stars that I would have thrown away otherwise....long XYZ script with 800 checkpoints and some breaks in the middle, no way tracing it back for me..

Feature request:
-Record used dict into meta-data + override when imported through process image
-New option to select dict independently of checkpoint (e.g. through XYZ script)

**Comment by vladmandic** [comment]
honestly, i've never expected this kind of a use-case, but glad to see ppl experimenting and finding cool stuff!
can you share some of your results?

unfortunately, torch doesn't have equivalent of "read only metadata, not weights", so only way to get the state dict is to read entire model. so if this is to be used in xyz script (for example), it would be a double model load - first to load state dict and discard weights and then load second model while using state dict from first model.

**Comment by TheOnlyHolyMoly** [comment]
Yes, having understood the potential, I would not mind the wait tbh for the double load time, the knowledge about suprisingly great combinations of dictionary and actual weights would be super valuable. 

LEFT is DEVIATING DICT /// RIGHT is ORIGINAL DICT (if you just look at the first image you will understand why I was crying I could not get this recreated)

![Deviating Dict Examples 6](https://github.com/vladmandic/automatic/assets/131612312/67eecc24-ac9d-4585-be02-3fe0a9655656)
![Deviating Dict Examples 3](https://github.com/vladmandic/automatic/assets/131612312/0d7c30d2-047a-4a6f-884b-121e93448cfb)
![Deviating Dict Examples](https://github.com/vladmandic/automatic/assets/131612312/76332dea-b10b-48bb-b56e-16f5c137f6fa)
![Deviating Dict Examples 1](https://github.com/vladmandic/automatic/assets/131612312/d03dcba3-587d-4848-805f-e5178550e50b)

**Comment by vladmandic** [comment]
ok, you're definitely onto something here!

**Comment by cool-bigdogs-tshirt** [comment]
an (optional) set of parameters to pass in at model load time would be great. even besides super low-level stuff like this, having extra dropdowns for VAE/unet/etc that you can apply before loading the model is better than `load model -> go to settings -> change VAE -> reload model`.

**Comment by cool-bigdogs-tshirt** [comment]
ties into #1297 as well!

**Comment by DirtyHamster** [comment]
@TheOnlyHolyMoly I like your thinking I'll have to try this.

**Comment by DirtyHamster** [comment]
I tried doing a recursive loop back at one point using the output image with the same path spanning 50 images. Just a few out of the images so you can see the time-lapse between the stages. 
![01763-512321403-)_)_,__lips_(_((realistic_1)(large_kissable_lips_1))(red_lips_0 7)(glossy_1)(metalic_1)(smile_0 5)(happy_0 5)_))_,__hair_((blond](https://github.com/vladmandic/automatic/assets/71010673/db4b0092-34c2-4a22-8832-d70ba7d5c0d3)
![01785-738379542-)_)_,__lips_(_((realistic_1)(large_kissable_lips_1))(red_lips_0 7)(glossy_1)(metalic_1)(_(slight_smile_0 2)(seductive_0 5)_)_))_](https://github.com/vladmandic/automatic/assets/71010673/d33cef16-dfc7-47e3-a196-a834593c206e)
![01798-4071254594-)_)_,__lips_(_((realistic_1)(large_kissable_lips_1))(red_lips_0 7)(glossy_1)(metalic_1)(_(slight_smile_0 2)(seductive_0 5)_)_))_](https://github.com/vladmandic/automatic/assets/71010673/49cf028d-7b4d-4e8a-b67e-f85fa8dabed4)
![01809-1270237974-)_)_,__lips_(_((realistic_1)(large_kissable_lips_1))(red_lips_0 7)(glossy_1)(metalic_1)(_(slight_smile_0 2)(seductive_0 5)_)_))_](https://github.com/vladmandic/automatic/assets/71010673/82a87f7b-35f7-4d45-9c38-7592e1b45b78)
![01826-2361650846-)_)_,__lips_(_((realistic_1)(large_kissable_lips_1))(red_lips_0 7)(glossy_1)(metalic_1)(_(slight_smile_0 2)(seductive_0 5)_)_))_](https://github.com/vladmandic/automatic/assets/71010673/4c075981-266f-4a2b-b07f-452befb56322)

If I had known "reuse previous model dict" worked I would have tried that on it as well.

**Comment by TheOnlyHolyMoly** [comment]
If you want to use it, it's a little tricky, first have the feature deactivated, then select the model that should serve as dict base, then activate the feature and load your target model. Not all dicts are soo deviating that the outcome is soo siginificantly different. So you might not always get a great difference, sometimes a booom. I have a lot of second row model that have not made into the large merge-models, maybe that's why. Cannot tell you more right now as I am also just exploring the matter.

**Comment by vladmandic** [comment]
they are not large, but extracting is not simple. dict is basically definition of internal model structure.
and scenario here does not mean that it uses double the memory.
how it works is that you load raw model -> create config (dict) -> apply weights. and re-use dict means when you load second model it skips second step, so it applies new weights to an existing structure in memory. it doesn't use any more memory, but it does mean you need to load one model first and then second model to overwrite weights of the first model.

**Comment by vladmandic** [comment]
well, highly experimental, but now you have `sd_model_dict` in settings -> stable diffusion.
and if you really want, you can put it in quicksettings next to actual `sd_model_checkpoint`
`none` is default and it means use whatever dict is in checkpoint itself.

**Comment by TheOnlyHolyMoly** [comment]
great!!! thank you so much Vlad! will try tonight and report back.
