### ISSUE TITLE
[Extension]: Adetailer produces black images if ToMe is enabled until model is reloaded without ToMe.

### ISSUE THREAD

**Issue by vidiotgameboss** [vladmandic/automatic#1307]
### Issue Description

1. Enable ToMe.
2. Generate once with adetailer
3. Try generating again. You will notice that depending on merge ratio, seed and model, the entire image outputs or image masks are now black until the model is reloaded without ToMe being enabled.

This may possibly be related to #1257 .

While on this topic: ToMe does not disable using the "Enable redundant token merging via tomesd for speed and memory improvements" option but rather you've got to untick it along with Merge attention, Merge cross-attention and Merge MLP for it to completely deactivate.

### Version Platform Description

Latest vladmandic/automatic as of writing
Latest Bing-su/adetailer as of writing

**Comment by vidiotgameboss** [comment]
may be related to [adetailer 120](https://github.com/Bing-su/adetailer/issues/120) although i have not gotten any black images in any other scenario apart from using ToMe

**Comment by ronbere** [comment]
sorry for my ignorance, I also have problems with black images, I can't find where to deactivate Tome

**Comment by vidiotgameboss** [comment]
> sorry for my ignorance, I also have problems with black images, I can't find where to deactivate Tome

its token merging in the settings

[this](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/9fd6c1e3430f5947add23e2e94ac816c2546481c) commit maybe fixes it

**Comment by vidiotgameboss** [comment]
after some more testing it seems to only be reproductible at certain merge ratios, 0.5 to 0.6 ratio produces black images until the model is reloaded, 0.1 - 0.4 and 0.7 - 0.9 are completely fine??

**Comment by vidiotgameboss** [comment]
Fixed black image/NaN issues by turning on crossattention upcast and enabling tf32 and tf16 math ops.
