### ISSUE TITLE
[Issue]: After upscaling from the processing tab, regular txt2img is slow

### ISSUE THREAD

**Issue by root66** [vladmandic/automatic#1309]
### Issue Description

Step 1. generate a 512x512 image with txt2img and send to processing. For me this takes 0:16.
Step 2. set the upscale size to 2.0 and choose an upscaler of your choice such as Nearest. This will output a 1024x1024 image.
Step 3. generate a new 512x512 image with txt2img. Now it takes 0:43 seconds. The output is still 512x512.

### Version Platform Description

Windows 10, Firefox, GTX1660 Super, xformers

commit 9726b4d23cb63779964e1d4edff49dd2c9c11e51
Date:   Sun Jun 4 13:21:52 2023 -0400

EDIT: Tested via webui and API, same results.

**Comment by vladmandic** [comment]
see @1285.
