### ISSUE TITLE
[Issue]: image generation taking forever

### ISSUE THREAD

**Issue by XmartySS** [vladmandic/automatic#1311]
### Issue Description

I recently installed Vlad automatic and it's really really fast. Previously i was using Automatic1111. It was fine but suddenly from yesterday my performance degraded drastically. Previously i was getting 4 it/s but now it's 2 s/it. I tried everything but not able to fix it. So i shifted to Vlad Automatic. And it's faster then my previous speed. It's now 4.6 it/s. Thank you for your great work.

Now my issue is I have only 4gb of vram. Previously without --medvram or --lowvram i was able to generate almost 768 x 768 images. And after that i was getting OOM ereor. But now even if i am trying to generate 1024 x 1024 images. It's generating without any OOM Error but it's really really slow. Like 2 s/it. Even if i am trying to generate 2000 x 2000 image. It's not giving OOM and taking forever to start. My GPU is still working but not heating as much as it is heating during 512 x 512 image generation. 

512 x 512 images are generating really fast. But when i am trying to increase resolution like 608 x 608 it's still generating fast but after 95% it's taking way longer to generate and after generating 1 one image other images don't take time after 95% in the same resolution resolution. Same 1024 x 1024 taking 3.5 minutes to generate first image. After that it is taking only 50 seconds to generate each image. Before in automatic1111 i was not facing any issue like stuck after 95% in any resolution. I am not using any extention. Sorry for my bad english.

1024 x 1024 image is generating faster using --medvram but slow without it. And also it is taking less time after 95% to generate.

I am using Lenovo Legion 5 Laptop

AMD Ryzen 7
RTX 3050
4 GB VRAM
32 GB RAM
1.5 TB NVME SSD

Sorry for not including version as i am outside home. I will add it tomorrow.

All drivers are updated to latest version. Is this because of new update that i am not getting OOM error and it's teying to generate bigger images in cost of time ?

### Version Platform Description

I am using Vlad latest version. Tried in every browser but no luck. I am uaing windows 11 latest version.

**Comment by brknsoul** [comment]
> All drivers are updated to latest version
downgrade to driver version 351, as mentioned here; https://github.com/vladmandic/automatic/discussions/1285

**Comment by vladmandic** [comment]
as @brknsoul mentioned.
