### ISSUE TITLE
[Feature]: movable styles

### ISSUE THREAD

**Issue by crackfoo** [vladmandic/automatic#1313]
### Feature description

Hi, 

I'm not sure if adding the type of behavior is possible in the style selection box, but do you think it would be possible to have the ability to move/organize selected styles within the box?

For example, say you have 6-7 selected but want to change one of them in the beginning. If you remove it and put it's replacement in, it would go to the end of the list and subsequently, be near the end of the prompt when generated. It would be handy if it was possible to click and drag the new style into a specific spot without having to clear everything out and add them all back in the desired order.

Kinda of a sub request which might be more doable, perhaps have 2 style boxes, one for pre-pending what is in the Prompt box, and another for appending...

thanks!

**Comment by vladmandic** [comment]
duplicate.

**Comment by crackfoo** [comment]
oh shoot... sorry, didn't notice that there was. thnx
