### ISSUE TITLE
[Issue]:  SDP optimization problem at the end of generation

### ISSUE THREAD

**Issue by eadnams22** [vladmandic/automatic#1314]
### Issue Description

A the end of generation, with SDP optimization enabled, it fails, with this:

If I disable SDP optimization it works fine, though slower, of course.

> Expected query, key, and value to have the same dtype, but got query.dtype: float key.dtype: float and value.dtype: struct c10::Half instead.
> 
> 17:25:23-989815 ERROR    gradio call: RuntimeError
> ┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
> │ E:\automatic\modules\call_queue.py:34 in f                                                                          │
> │                                                                                                                     │
> │    33 │   │   │   try:                                                                                              │
> │ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
> │    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
> │                                                                                                                     │
> │ E:\automatic\modules\txt2img.py:58 in txt2img                                                                       │
> │                                                                                                                     │
> │   57 │   if processed is None:                                                                                      │
> │ > 58 │   │   processed = process_images(p)                                                                          │
> │   59 │   p.close()                                                                                                  │
> │                                                                                                                     │
> │                                              ... 13 frames hidden ...                                               │
> │                                                                                                                     │
> │ E:\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                                   │
> │                                                                                                                     │
> │   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                      │
> │ > 1501 │   │   │   return forward_call(*args, **kwargs)                                                             │
> │   1502 │   │   # Do not call functions when jit is used                                                             │
> │                                                                                                                     │
> │ E:\automatic\modules\sd_hijack_optimizations.py:518 in sdp_attnblock_forward                                        │
> │                                                                                                                     │
> │   517 │   v = v.contiguous()                                                                                        │
> │ > 518 │   out = torch.nn.functional.scaled_dot_product_attention(q, k, v, dropout_p=0.0, is_ca                      │
> │   519 │   out = out.to(dtype)

### Version Platform Description

Windows 10

> 16:11:17-679953 INFO     Starting SD.Next
> 16:11:17-684992 INFO     Python 3.10.7 on Windows
> 16:11:17-726949 INFO     Version: 9726b4d2 Sun Jun 4 13:21:52 2023 -0400
> 16:11:18-116951 INFO     Setting environment tuning
> 16:11:18-118950 INFO     nVidia CUDA toolkit detected
> 16:11:19-450953 INFO     Torch 2.0.1+cu118
> 16:11:19-468951 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
> 16:11:19-470951 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82

**Comment by vladmandic** [comment]
try with `--safe` command line flag?
what are the extensions?
what are compute settings?

**Comment by eadnams22** [comment]
Only extensions running are the system ones.

![IMG_0293](https://github.com/vladmandic/automatic/assets/68871928/119b9344-5019-4b33-a27f-5a138761c49d)

**Comment by vladmandic** [comment]
any particular reason you have `full-depth cuDNN benchmark` set?
also, why upscast sampling and upcast cross attention layer? that may be the problem, i don't think combination of those two with sdp was tested.

**Comment by eadnams22** [comment]
No particular reason I can remember now. I can’t remember the defaults either, hah.

It was working fine with those before yesterday, will give it a try without!

**Comment by eadnams22** [comment]
Yup, that did it.
