### ISSUE TITLE
[Issue]: Selecting a lora from the GUI no longer adds/removes it from the prompt.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [vladmandic/automatic#1321]
### Issue Description

Selecting a lora from the GUI no longer adds/removes it from the prompt. This changed with one of the updates today.

### Version Platform Description

Upgraded to version: c52fb69d Mon Jun 5 20:49:18 2023 +0300
Windows 11
RTX 4090
Chrome (latest)

**Comment by vladmandic** [comment]
should be fixed now.
