### ISSUE TITLE
[Feature]: 最主要的sd图片信息查看功能没有吗? 还有和sd一样的界面设置中文,

### ISSUE THREAD

**Issue by aaronkingdom** [vladmandic/automatic#1324]
### Feature description

最主要的sd-图片信息,查看功能没有吗? (就是把生成的图片拖上去就有显示提示词相关的信息, 不是类似tagger的)
还有和sd一样的界面设置中文, sd有个zh-hans的扩展可以自动获取最新翻译, 但是要在sd的设置界面设置中文包才可以使用, 所以vladmandic用不了...................................

### Version Platform Description

win11,chrome

**Comment by vladmandic** [comment]
english only in issues/features.
