### ISSUE TITLE
[Issue]: "Replace Preview" stopped working

### ISSUE THREAD

**Issue by crazygonuts** [vladmandic/automatic#1327]
### Issue Description

When you show extra networks, under each tab (such as checkpoints) you can mouseover each thumbnail and select "replace preview" to replace it with the currently selected image from generation.  After updating today this no longer works and doesn't appear to do anything.  I removed all my non-builtin extensions and the behavior remained the same.

### Version Platform Description

Version: da38d27f Mon Jun 5 16:07:51 2023 -0400
windows 10
chrome

**Comment by TKS4** [comment]
Lol had my report written up, and when I came back to post it, you already did it 🗡️ 👍

**Comment by vladmandic** [comment]
fixed.
