### ISSUE TITLE
[Issue]: Few small issues, ExtraNetworks card/thumbnail description functionality, illegible generation stats (VRAM+Time taken to generate), and wierd button in Settings after searches.

### ISSUE THREAD

**Issue by TKS4** [vladmandic/automatic#1328]
### Issue Description

~~The Replace button/word that you could press in order to update/create a new .description.txt file for the relevant thumb/card view doesn't work anymore (I presume a simple JS issue but I'm not sure, just reminds me of a dead button). The other buttons "read description" or "Metadata" all function fine.~~

There is no logging of any error in the console nevertheless.

EDIT: The Replace functionality was reported an hour earlier, sorry for the duplicate.

Another issue is on the normal default theme, the generation stats after an image is done generating is illegible (not sure, but I guess I must be the only light theme user out there), the text that describes how long and how much VRAM the last task used - was formerly black text, now it's yellow that's basically impossible to see on a white theme backdrop.

Another issue is using the Search keyword filter for settings - there is a random refresh icon that appear no matter what term you search for. Not sure what it does/refreshes.

![error1](https://github.com/vladmandic/automatic/assets/19920323/57a11edb-ed26-41e2-9a2d-438e02deb09d)
![error2](https://github.com/vladmandic/automatic/assets/19920323/13bed788-fb95-4779-8b19-ad72b7339c46)

Lastly, there is a problem with the new Enqueue functionality. I don't actually see a save button anywhere to save said generations (or do they auto-save somewhere?). Maybe I misunderstood the functionality of this new feature.

### Version Platform Description

Version: da38d27f Mon Jun 5 2023 -0400
Win10x64
FF 113.0.2 (64-bit)

**Comment by vladmandic** [comment]
fixed all 3, although i have no clue what that button at the end is (i've hidden it, but i cannot figure out who draws it to start with, it doesn't match anything - id is 'refresh_tac_refreshTempFiles`)
