### ISSUE TITLE
[Issue]: Image preview after generation is proken if there are special characters in the output directory name

### ISSUE THREAD

**Issue by TeutonJon78** [vladmandic/automatic#1331]
### Issue Description

I wanted to rename my output directory from "outputs" to "#outputs" so that it would always be at the top of the window in Explorer.

Image generation, live preview, saving, and image browser all worked correctly. However, the image preview after generation just shows a broken image.

I changed the directory back to normal and it worked fine. I changed back and broken again. Verified broken in safe mode.

Output base directory: D:\Graphic Design\AI\\#outputs
Preview Image link: http://127.0.0.1:7860/file=D:/Graphic%20Design/AI/#outputs\text\2023-06-06\20230606_084658_322218-3313430971.png

Trying the link directly pulls up this JSON error:

```
<html><body>
<!--StartFragment-->

error | "HTTPException"
-- | --
detail | "File cannot be fetched: D:/Graphic Design/AI/. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app."
body | ""
errors | "(403, 'File cannot be fetched: D:/Graphic Design/AI/. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.')"

<!--EndFragment-->
</body>
</html>

```

### Version Platform Description

Version: f0ad70c8 Tue Jun 6 08:48:11 2023 -0400, Win64, DirectML, Firefox

```
08:42:42-219964 INFO     Running extension preloading
08:42:42-224966 INFO     Running in safe mode without user extensions
08:42:42-233967 INFO     Starting SD.Next
08:42:42-234967 INFO     Python 3.10.11 on Windows
08:42:42-286979 INFO     Version: f0ad70c8 Tue Jun 6 08:48:11 2023 -0400
08:42:42-658638 INFO     Setting environment tuning
08:42:42-660638 INFO     Using DirectML Backend
08:42:44-727776 INFO     Torch 2.0.0+cpu
08:42:44-742896 INFO     Torch backend: DirectML (torch-directml 0.2.0.dev230426)
08:42:44-841238 INFO     Torch detected GPU: Radeon RX 580 Series
08:42:44-842239 INFO     Verifying requirements
08:42:44-862243 INFO     Installing packages
08:42:44-928374 INFO     Running setup
08:42:44-929374 INFO     Installing repositories
08:42:47-698889 INFO     Installing submodules
08:42:49-822495 INFO     Updating submodules
08:43:17-418980 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
08:43:17-420980 INFO     Updating Wiki
08:43:18-059962 INFO     Running extension preloading
08:43:18-061963 INFO     Running in safe mode without user extensions
08:43:18-062963 INFO     Server arguments: ['--autolaunch', '--use-directml', '--medvram', '--safe']
No module 'xformers'. Proceeding without it.
08:43:26-268666 INFO     Libraries loaded
08:43:26-272667 INFO     Using data path: D:\Graphic Design\AI\vladmandic-automatic
08:43:26-278668 INFO     Available VAEs: D:\Graphic Design\AI\SD models\VAE 3
08:43:26-402247 INFO     Available models: D:\Graphic Design\AI\SD models\Stable-diffusion 36
2023-06-06 08:43:30,326 - ControlNet - INFO - ControlNet v1.1.218
ControlNet preprocessor location: D:\Graphic Design\AI\vladmandic-automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
2023-06-06 08:43:30,568 - ControlNet - INFO - ControlNet v1.1.218
08:43:32-210301 INFO     Loading UI theme: name=nota-ai/theme style=Auto
08:43:36-399346 INFO     Torch override dtype: no-half set
08:43:36-400346 INFO     Torch override VAE dtype: no-half set
08:43:36-401346 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
```

**Comment by vladmandic** [comment]
some characters just cant be urlencoded and are not valid for http requests. to fix this, id have to have a completely separate copy of a file under a different (cleaned) name just so browser can display it and that would be a massive overhead - its not worth fixing.

**Comment by TeutonJon78** [comment]
Just a note for others that might run into this, there are other special characters that do work -- ! for example.

# is reserved in URLs to denote a hash as part of the address, but would still work if was encoded as %23 in the URL.

**Comment by vladmandic** [comment]
> # is reserved in URLs to denote a hash as part of the address, but would still work if was encoded as %23 in the URL.

yes, but unfortunately, built-in urlencode methods in python do not do that and unless someone wants to write one that is complete, i'm not about to do special per-char handling.

**Comment by TeutonJon78** [comment]
The hashtag error seems to actually be a github issue/quirk. I had escaped with character \\ to show it correctly, but it strips that out on quotes apparently.

I was looking through the code to even find where that image path gets generated, but I didn't have any luck. What I did notice that is the image view after generation links directly to the output file, whereas if you look at the default logo image on start or any image in the Image Browser, it uses a gradio generated temp location.

However, there is a built in python function to parse a path and convert special characters to URL correct syntax:

https://docs.python.org/3.10/library/urllib.parse.html#urllib.parse.quote

urllib.parse.urlencode also calls quote_plus by default (and can be made to use quote instead)

Something like that must be getting called already, since the spaces are getting converted to %20 already. You do use it in ui_extra_networks.py already as well.

**Comment by vladmandic** [comment]
> What I did notice that is the image view after generation links directly to the output file, whereas if you look at the default logo image on start or any image in the Image Browser, it uses a gradio generated temp location.

correct - that is done to avoid creation of yet another temp file if its not needed. temp files are generated if image is not saved, but if its already saved, it will use that path. see `pil_to_temp_file` function.

and urlencoding is done by gradio as component is gradio gallery component and it creates images within in.

**Comment by TeutonJon78** [comment]
> correct - that is done to avoid creation of yet another temp file if its not needed. temp files are generated if image is not saved, but if its already saved, it will use that path. see `pil_to_temp_file` function.

I wonder if it might be a good idea to update the image browser to use the direct path as well then, as it's all temp images rather than the direct paths, and those images obviously have been saved. Would be something to be raised upstream or have you basically forked that extensions at this point?

> and urlencoding is done by gradio as component is gradio gallery component and it creates images within in.

stupid Gradio -- figured it might be more of an issue there.

**Comment by vladmandic** [comment]
> I wonder if it might be a good idea to update the image browser to use the direct path as well then, as it's all temp images rather than the direct paths, and those images obviously have been saved. Would be something to be raised upstream or have you basically forked that extensions at this point?

oh, it would be very much worth it!
but no, i didn't fork it, i link to upstream as a git submodule.
