### ISSUE TITLE
[Issue]: Unable to install stable diffusion version

### ISSUE THREAD

**Issue by Metalica** [vladmandic/automatic#1332]
### Issue Description

Version: b8f432af Tue Jun 6 12:01:08 2023 -0400

19:26:36-341526 INFO     Available VAEs: D:\automatic\models\VAE 0
19:26:36-343520 INFO     Available models: D:\automatic\models\Stable-diffusion 0
Download the default model? (y/N) y
 Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\launch.py:150 in <module>                                                                              │
│                                                                                                                     │
│   149                                                                                                               │
│ > 150     instance = start_server(immediate=True, server=None)                                                      │
│   151     while True:                                                                                               │
│                                                                                                                     │
│ D:\automatic\launch.py:130 in start_server                                                                          │
│                                                                                                                     │
│   129         else:                                                                                                 │
│ > 130             server = server.webui()                                                                           │
│   131     if args.profile:                                                                                          │
│                                                                                                                     │
│ D:\automatic\webui.py:281 in webui                                                                                  │
│                                                                                                                     │
│   280 def webui():                                                                                                  │
│ > 281     start_common()                                                                                            │
│   282     start_ui()                                                                                                │
│                                                                                                                     │
│ D:\automatic\webui.py:195 in start_common                                                                           │
│                                                                                                                     │
│   194     async_policy()                                                                                            │
│ > 195     initialize()                                                                                              │
│   196     if shared.opts.clean_temp_dir_at_start:                                                                   │
│                                                                                                                     │
│ D:\automatic\webui.py:98 in initialize                                                                              │
│                                                                                                                     │
│    97     modelloader.cleanup_models()                                                                              │
│ >  98     modules.sd_models.setup_model()                                                                           │
│    99     startup_timer.record("models")                                                                            │
│                                                                                                                     │
│ D:\automatic\modules\sd_models.py:93 in setup_model                                                                 │
│                                                                                                                     │
│    92         os.makedirs(model_path)                                                                               │
│ >  93     list_models()                                                                                             │
│    94     enable_midas_autodownload()                                                                               │
│                                                                                                                     │
│ D:\automatic\modules\sd_models.py:137 in list_models                                                                │
│                                                                                                                     │
│   136                     shared.opts.data['sd_model_checkpoint'] = "v1-5-pruned-emaonly.safet                      │
│ > 137                     model_list = modelloader.load_models(model_path=model_path, model_ur                      │
│   138                 else:                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
UnboundLocalError: local variable 'model_path' referenced before assignment
Press any key to continue . . .

Want to install on new and got this error.

### Version Platform Description

win 10

**Comment by vladmandic** [comment]
fixed.
