### ISSUE TITLE
[Issue]: Broken cmd console logs

### ISSUE THREAD

**Issue by Rogal80** [vladmandic/automatic#1333]
### Issue Description

Hi, after the latest update, the console stopped working at the end of the load, but the web UI is still working.

21:16:39-119700 INFO     Server queues disabled
ERROR:    [Errno 10048] error while attempting to bind on address ('0.0.0.0', 7862): only one usage of each socket address (protocol/network address/port) is normally permitted

I also have args in bat file 

--listen --insecure --skip-update --port 7862 --disable-queue 

### Version Platform Description

windows 10 , firefox , 
![image](https://github.com/vladmandic/automatic/assets/112553453/e7a94314-77ff-40f0-9633-cd30e0d8f009)

**Comment by vladmandic** [comment]
> ERROR: [Errno 10048] error while attempting to bind on address ('0.0.0.0', 7862): only one usage of each socket address (protocol/network address/port) is normally permitted

are you sure you don't have server already started (in another window)?
if no, windows is sometimes slow to release ports. so stop server and restart it after 1min.

**Comment by Rogal80** [comment]
yep , you  were right after 1 min it worked again - thx
