### ISSUE TITLE
[Issue]: Extension tab search funcion weird behavior

### ISSUE THREAD

**Issue by Lalimec** [vladmandic/automatic#1338]
### Issue Description

I noticed that when I try to use search in extensions tab to deactivate or install one, all others that was deactive before, get activated. To test this deactivate an extention and restart ui with the button. After refreshing the page, search for an extension and diable it by unchecking the mark. And click on the restart button again. You will see the previos one is got enabled.

### Version Platform Description

12:38:23-074654 INFO     Python 3.10.11 on Linux
12:38:23-081835 INFO     Version: 82095082a Tue Jun 6 15:32:22 2023 -0400
12:38:23-282728 INFO     Latest published version:
                         2a664b1bdb6dcda2193abef0b9c8dd12f5b22c36
                         2023-06-06T21:32:34Z

**Comment by vladmandic** [comment]
hmm, yes, that's possible as disable method expects full list. i'll keep it open and in the backlog as i don't consider it a high-priority item at the moment.

**Comment by vladmandic** [comment]
fixed.
