### ISSUE TITLE
[Issue]: All extension "Type" are displayed as "SYSMTEM".

### ISSUE THREAD

**Issue by tkiikt** [vladmandic/automatic#1340]
### Issue Description

"Type" displayed on the screen where the Extension tab is opened is all displayed as "SYSTEM". My (user) installed extensions are also listed as SYSTEM.

### Version Platform Description

INFO     Python 3.10.9 on Windows
INFO     Version: 3bef3e3e Wed Jun 7 17:25:11 2023 +0300
INFO     Latest published version: 8e3a8fb474da7f1060c4d93bc5098977710e1f69 2023-06-07T16:17:55Z
INFO     Setting environment tuning
INFO     nVidia CUDA toolkit detected
INFO     Torch 2.0.0+cu118
INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28

**Comment by vladmandic** [comment]
fixed.
