### ISSUE TITLE
[Issue]: Issues with latest Gradio

### ISSUE THREAD

**Issue by Holyniwa** [vladmandic/automatic#135]
### Issue Description

not sure what got reverted, but suddenly its not opening for me. just crashes at the end. 
here's the whole crash (which may contain unnecessary/duplicate known issues)

14:32:46-320390 INFO     Available models: D:\stable-diffusion\stable-diffusion-webui\models\Stable-diffusion 153
loading script: toolkit_gui.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\stable-diffusion\automatic\modules\scripts.py:255 in load_scripts                                                │
│                                                                                                                     │
│   254 │   │   │                                                                                                     │
│ > 255 │   │   │   script_module = script_loading.load_module(scriptfile.path)                                       │
│   256 │   │   │   register_scripts_from_module(script_module)                                                       │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\modules\script_loading.py:12 in load_module                                           │
│                                                                                                                     │
│   11 │   module = importlib.util.module_from_spec(module_spec)                                                      │
│ > 12 │   module_spec.loader.exec_module(module)                                                                     │
│   13                                                                                                                │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\extensions\stable-diffusion-webui-model-toolkit\scripts\toolkit_gui.py:17 in <module> │
│                                                                                                                     │
│    16                                                                                                               │
│ >  17 MODEL_SAVE_PATH = shared.cmd_opts.ckpt_dir or os.path.join(models_path, "Stable-diffusio                      │
│    18 AUTOPRUNE_PATH = os.path.join(models_path, "Autoprune")                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Namespace' object has no attribute 'ckpt_dir'
loading script: tagger.py: ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\stable-diffusion\automatic\modules\scripts.py:255 in load_scripts                                                │
│                                                                                                                     │
│   254 │   │   │                                                                                                     │
│ > 255 │   │   │   script_module = script_loading.load_module(scriptfile.path)                                       │
│   256 │   │   │   register_scripts_from_module(script_module)                                                       │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\modules\script_loading.py:12 in load_module                                           │
│                                                                                                                     │
│   11 │   module = importlib.util.module_from_spec(module_spec)                                                      │
│ > 12 │   module_spec.loader.exec_module(module)                                                                     │
│   13                                                                                                                │
│                                                                                                                     │
│                                               ... 3 frames hidden ...                                               │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\extensions\stable-diffusion-webui-wd14-tagger\tagger\api.py:6 in <module>             │
│                                                                                                                     │
│    5 from modules import shared                                                                                     │
│ >  6 from modules.api.api import decode_base64_to_image                                                             │
│    7 from modules.call_queue import queue_lock                                                                      │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\modules\api\api.py:9 in <module>                                                      │
│                                                                                                                     │
│     8 from io import BytesIO                                                                                        │
│ >   9 from gradio_client.utils import decode_base64_to_file                                                         │
│    10 from fastapi import APIRouter, Depends, FastAPI, Request, Response                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'gradio_client'
loading script: api.py: ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\stable-diffusion\automatic\modules\scripts.py:255 in load_scripts                                                │
│                                                                                                                     │
│   254 │   │   │                                                                                                     │
│ > 255 │   │   │   script_module = script_loading.load_module(scriptfile.path)                                       │
│   256 │   │   │   register_scripts_from_module(script_module)                                                       │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\modules\script_loading.py:12 in load_module                                           │
│                                                                                                                     │
│   11 │   module = importlib.util.module_from_spec(module_spec)                                                      │
│ > 12 │   module_spec.loader.exec_module(module)                                                                     │
│   13                                                                                                                │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\extensions-builtin\sd-webui-controlnet\scripts\api.py:13 in <module>                  │
│                                                                                                                     │
│    12 from modules.api.models import *                                                                              │
│ >  13 from modules.api import api                                                                                   │
│    14                                                                                                               │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\modules\api\api.py:9 in <module>                                                      │
│                                                                                                                     │
│     8 from io import BytesIO                                                                                        │
│ >   9 from gradio_client.utils import decode_base64_to_file                                                         │
│    10 from fastapi import APIRouter, Depends, FastAPI, Request, Response                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'gradio_client'
loading script: controlnet.py: ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\stable-diffusion\automatic\modules\scripts.py:255 in load_scripts                                                │
│                                                                                                                     │
│   254 │   │   │                                                                                                     │
│ > 255 │   │   │   script_module = script_loading.load_module(scriptfile.path)                                       │
│   256 │   │   │   register_scripts_from_module(script_module)                                                       │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\modules\script_loading.py:12 in load_module                                           │
│                                                                                                                     │
│   11 │   module = importlib.util.module_from_spec(module_spec)                                                      │
│ > 12 │   module_spec.loader.exec_module(module)                                                                     │
│   13                                                                                                                │
│                                                                                                                     │
│                                               ... 3 frames hidden ...                                               │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\extensions-builtin\sd-webui-controlnet\scripts\external_code.py:7 in <module>         │
│                                                                                                                     │
│     6                                                                                                               │
│ >   7 from modules.api import api                                                                                   │
│     8                                                                                                               │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\modules\api\api.py:9 in <module>                                                      │
│                                                                                                                     │
│     8 from io import BytesIO                                                                                        │
│ >   9 from gradio_client.utils import decode_base64_to_file                                                         │
│    10 from fastapi import APIRouter, Depends, FastAPI, Request, Response                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'gradio_client'
loading script: external_code.py: ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\stable-diffusion\automatic\modules\scripts.py:255 in load_scripts                                                │
│                                                                                                                     │
│   254 │   │   │                                                                                                     │
│ > 255 │   │   │   script_module = script_loading.load_module(scriptfile.path)                                       │
│   256 │   │   │   register_scripts_from_module(script_module)                                                       │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\modules\script_loading.py:12 in load_module                                           │
│                                                                                                                     │
│   11 │   module = importlib.util.module_from_spec(module_spec)                                                      │
│ > 12 │   module_spec.loader.exec_module(module)                                                                     │
│   13                                                                                                                │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\extensions-builtin\sd-webui-controlnet\scripts\external_code.py:7 in <module>         │
│                                                                                                                     │
│     6                                                                                                               │
│ >   7 from modules.api import api                                                                                   │
│     8                                                                                                               │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\modules\api\api.py:9 in <module>                                                      │
│                                                                                                                     │
│     8 from io import BytesIO                                                                                        │
│ >   9 from gradio_client.utils import decode_base64_to_file                                                         │
│    10 from fastapi import APIRouter, Depends, FastAPI, Request, Response                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'gradio_client'
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\stable-diffusion\automatic\launch.py:93 in <module>                                                              │
│                                                                                                                     │
│   92     import webui                                                                                               │
│ > 93     webui.webui()                                                                                              │
│   94                                                                                                                │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\webui.py:207 in webui                                                                 │
│                                                                                                                     │
│   206     modules.progress.setup_progress_api(app)                                                                  │
│ > 207     create_api(app)                                                                                           │
│   208     ui_extra_networks.add_pages_to_demo(app)                                                                  │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\webui.py:157 in create_api                                                            │
│                                                                                                                     │
│   156 def create_api(app):                                                                                          │
│ > 157     from modules.api.api import Api                                                                           │
│   158     api = Api(app, queue_lock)                                                                                │
│                                                                                                                     │
│ D:\stable-diffusion\automatic\modules\api\api.py:9 in <module>                                                      │
│                                                                                                                     │
│     8 from io import BytesIO                                                                                        │
│ >   9 from gradio_client.utils import decode_base64_to_file                                                         │
│    10 from fastapi import APIRouter, Depends, FastAPI, Request, Response                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'gradio_client'
Press any key to continue . . .

### Platform Description

win11, chrome

**Comment by vladmandic** [comment]
`gradio` moved some of functionality into seprate library, `gradio_client` which i've added to `requirements.txt` to enable upgrade to new version of gradio.

did you run webui.bat? that should detect and install correct requirements automatically?

**Comment by Holyniwa** [comment]
Yeah, just tried the webui.bat and it still crashes at the end.

**Comment by vladmandic** [comment]
`pip show gradio_client` ?
if not present, just do `pip install gradio_client`
i cannot explain why its not getting installed automatically?

**Comment by Holyniwa** [comment]
i used the gitbash to run the cmd, and it gave me this (program still crashes):


$ pip install gradio_client
WARNING: Ignoring invalid distribution -umpy (c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages)
Collecting gradio_client
  Downloading gradio_client-0.1.2-py3-none-any.whl (286 kB)
     -------------------------------------- 286.1/286.1 kB 5.9 MB/s eta 0:00:00
Requirement already satisfied: requests in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from gradio_client) (2.28.2)
Requirement already satisfied: huggingface-hub>=0.13.0 in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from gradio_client) (0.13.4)
Requirement already satisfied: fsspec in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from gradio_client) (2023.1.0)
Requirement already satisfied: typing-extensions in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from gradio_client) (4.5.0)
Requirement already satisfied: httpx in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from gradio_client) (0.23.3)
Requirement already satisfied: websockets in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from gradio_client) (10.4)
Requirement already satisfied: packaging in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from gradio_client) (23.0)
Requirement already satisfied: filelock in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.13.0->gradio_client) (3.9.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.13.0->gradio_client) (4.64.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.13.0->gradio_client) (6.0)
Requirement already satisfied: sniffio in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from httpx->gradio_client) (1.3.0)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from httpx->gradio_client) (1.5.0)
Requirement already satisfied: httpcore<0.17.0,>=0.15.0 in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from httpx->gradio_client) (0.16.3)
Requirement already satisfied: certifi in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from httpx->gradio_client) (2022.12.7)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from requests->gradio_client) (1.26.14)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from requests->gradio_client) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from requests->gradio_client) (3.4)
Requirement already satisfied: anyio<5.0,>=3.0 in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from httpcore<0.17.0,>=0.15.0->httpx->gradio_client) (3.6.2)
Requirement already satisfied: h11<0.15,>=0.13 in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from httpcore<0.17.0,>=0.15.0->httpx->gradio_client) (0.14.0)
Requirement already satisfied: colorama in c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.13.0->gradio_client) (0.4.6)
WARNING: Ignoring invalid distribution -umpy (c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages)
Installing collected packages: gradio_client
WARNING: Ignoring invalid distribution -umpy (c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages)
Successfully installed gradio_client-0.1.2
WARNING: Ignoring invalid distribution -umpy (c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages)
WARNING: Ignoring invalid distribution -umpy (c:\users\USERNAME\appdata\local\programs\python\python310\lib\site-packages)

**Comment by vladmandic** [comment]
no clue why gradio_client is causing problems on your system, but after trying out gradio 3.26.0, there are no real benefits over previous 3.23.0, so i've downgraded it back.
