### ISSUE TITLE
[Issue]: Freezing at completion of image. 

### ISSUE THREAD

**Issue by zaileron** [vladmandic/automatic#1358]
### Issue Description

Version: 0d629f3c Thu Jun 8 09:01:43 2023 -0400
Windows 11, RTX 3090, Firefox, no new extensions. 

Issue: On completion of decoding image using DDIM, freezes at 20/20. Seems to be when VAE would be applied but happens with any VAE selected (automatic, none, etc.). Happens most frequently when I'm doing batched tasks. Can replicate this by opening a new terminal, opening the UI, and running with default settings and no prompt using batch size of 4 and DDIM. Kerras appears to operate better, but still occurs over time. Additionally happened with a tiled img2img overnight. When this happens, the preview of the image doesn't appear. 

When it freezes, GPU 3D goes to 99% and sits there. No memory changes, no changes in terminal or logs that I've seen. 

Timing: Updated last night (and this morning) and this issue is new. Have done a git reset and hard reset without fix. A1111 pulls from the same repository of models and is working without issue.

**Comment by vladmandic** [comment]
batch size of 4 at what resolution? can you start the job and then switch to system info tab and monitor memory usage there?

**Comment by zaileron** [comment]
any resolution. I'm using 512x512 (all defaults) in this case. Fractional GPU memory usage so it's not the known driver issue (though I am on 535, but haven't had memory problems. 

![image](https://github.com/vladmandic/automatic/assets/60076915/ff3e6ec5-cb9e-47ac-8084-728615aa379a)

![image](https://github.com/vladmandic/automatic/assets/60076915/4284258c-801e-4f38-bd0c-e687912e4298)

**Comment by vladmandic** [comment]
sampler is is stuck at final step and gpu is stuck at 99%? that's really weird.
just to double check:
- can you disable live preview?
- does this happen with any other sampler?

**Comment by TheLastWardian** [comment]
this has happened to me also in img to img with UniPC (always using controlnet so, maybe is not a problem related to you directly)

**Comment by ppkppk8520** [comment]
I had similar issue especailly in i2i(inpaint).
after i see vlad's comment, i checked Live preview setting and found none Live preview method selected.
i selected TAESD and there is no same issue so far. i did i2i(inpaint) 50 times in a row but it looks fine.

**Comment by TheLastWardian** [comment]
![image](https://github.com/vladmandic/automatic/assets/57380272/0ec392d6-5dbf-464f-8ab3-2f08735e8fa1)
happened again, does this helps?

**Comment by lebakerino** [comment]
Same issue, hadn't had SD open since last week and opened again last night, basically stops for a good while at the end of generating or close to and the images are not coming out the same either (from taking a picture and regenerating it)

**Comment by crazygonuts** [comment]
I was getting this every 3rd or 4th generation, following the comment from @ppkppk8520 I checked my live preview and nothing was selected.  I selected TAESD and so far have not had the issue happen again.

**Comment by zaileron** [comment]
> sampler is is stuck at final step and gpu is stuck at 99%? that's really weird. just to double check:
> 
>     * can you disable live preview?
> 
>     * does this happen with any other sampler?

Had time to update and test again briefly today, and seems to be working now for me after the latest pull. 

My preview generation buttons were unselected and no preview was being generated, if that adds to what people above are describing.

**Comment by vladmandic** [comment]
so we have root cause. i'll try to improve code so no "unselected" preview mode is possible, but otherwise i think this issue can be closed.

**Comment by cleverestx** [comment]
I'm having this issue now with Inpaint, but sometimes it freezes randomly at any percentage, although usually it's later like at 90%+

**Comment by TheLastWardian** [comment]
@cleverestx did u change the live preview? it was the solution to my problem. 
![image](https://github.com/vladmandic/automatic/assets/57380272/b5b151a5-b4f9-4aaf-9608-ce6cfbf7629f)
