### ISSUE TITLE
[Issue]: warning: modified files

### ISSUE THREAD

**Issue by crazygonuts** [vladmandic/automatic#1362]
### Issue Description

I'm getting this warning today even though I have never touched anything in any of these extensions

```
10:29:50-714018 WARNING  Modified files: ['extensions-builtin/sd-extension-system-info', 'wiki',
                         'extensions-builtin/sd-extension-aesthetic-scorer/',
                         'extensions-builtin/sd-extension-steps-animation/',
                         'extensions-builtin/sd-webui-model-converter/', 'extensions-builtin/seed_travel/']
```

### Version Platform Description

Version: b5f745b4 Thu Jun 8 11:56:29 2023 -0400

**Comment by solsol360** [comment]
Same warning message here after update.

20:47:12-799049 INFO     Python 3.10.9 on Windows
20:47:12-851942 INFO     Version: b5f745b4 Thu Jun 8 11:56:29 2023 -0400
20:47:13-405675 INFO     Setting environment tuning
20:47:13-409672 INFO     nVidia CUDA toolkit detected
20:47:19-251779 INFO     Torch 2.0.1+cu118
20:47:19-285768 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
20:47:19-288591 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10239 Arch (8, 6) Cores 68
20:47:19-445485 WARNING  Modified files: ['extensions-builtin/sd-extension-system-info',
                         'extensions-builtin/sd-webui-agent-scheduler',
                         'extensions-builtin/stable-diffusion-webui-images-browser', 'modules/lora', 'wiki',
                         'CheatSheet/', 'extensions-builtin/sd-extension-aesthetic-scorer/',
                         'extensions-builtin/sd-extension-steps-animation/',
                         'extensions-builtin/sd-webui-model-converter/', 'extensions-builtin/seed_travel/',
                         'javascript/themes.json']

**Comment by vladmandic** [comment]
yes, i need to skip extensions, i'll keep this open until i address that.
glad that cheatsheet shows up - that's the whole idea :)

**Comment by vladmandic** [comment]
btw, the point of this is to immediately see if user modified something and then reports an issue. like "i've edited webui.bat and it doesn't work anymore"
anyhow, closing as resolved in my local branch, i'll push update soon.
