### ISSUE TITLE
[Feature]: Continuous mode

### ISSUE THREAD

**Issue by neuralweights** [vladmandic/automatic#1364]
### Feature description

Simple concept, have the ui auto-save its current state every few minutes (or with every change?). Then have the option to make the ui continuous: after closing the window / console, and coming back later, you will always find everything like you left it.

I dont know how much work this is - if javascript needs to be adapted then that is probably the biggest part. Or the loaded images? I will leave the guesstimation of if this is worth it to someone else

Similar to https://github.com/vladmandic/automatic/issues/1247 dont know if it counts as duplicate, if yes pls close.

### Version Platform Description

-

**Comment by vladmandic** [comment]
its not identical, but its similar.
the thing is, i don't want to auto-save-on-change. same with settings - it would be easy to apply change immediately instead of asking user to click "apply", but that way its explict. i'll close this in favor of #1247
