### ISSUE TITLE
[Issue]:  detected: Trojan:Script/Wacatac.B!ml in \automatic\javascript\hires_fix.js (false positive?)

### ISSUE THREAD

**Issue by Rojinski** [vladmandic/automatic#1365]
### Issue Description

Hi,

When I've  started automatic, my antivirus put the "hires_fix.js" ifrom the "javascrip"t folder in quarantine. It indicates a Trojan script (Wacatac.B!ml). It's just happend. Never had that before.  So, now, it takes for ever to make a hires fix....  So, I've analyzed it with VirusTotal ( https://www.virustotal.com ) and the result is "No security vendors and no sandboxes flagged this file as malicious". 0/59 consulted. 

Anybody else had that "problem"? 

### Version Platform Description
Version: 3b994500 Wed May 31 12:12:55 2023 +0300

EDIT: 
After upgrading, everything seems OK.  The problematic file "hires_fix.js" is now named ""hires.js" and my antivirus is ok with it.

**Comment by vladmandic** [comment]
Like you said, it was a false positive - and you never mentioned which virus scanner reported it.

And even if the problem didn't go away, how can I prevent false positive in some external virus scanner?

**Comment by Rojinski** [comment]
> Like you said, it was a false positive - and you never mentioned which virus scanner reported it.
> 
> And even if the problem didn't go away, how can I prevent false positive in some external virus scanner?

Windows Defender is the antivirus that reported that.  As I wrote, I used VirusTotal (external analysis) to verify.
