### ISSUE TITLE
[Feature]: Integrate CiaoSR Upscaler

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#1366]
### Feature description

Per Vlad Request:
Ran across this on the interwebz, I don't know about performance, but the image quality is excellent.

[Paper](https://arxiv.org/pdf/2212.04362.pdf)

[Github](https://github.com/caojiezhang/CiaoSR)

**Comment by FullBleed** [comment]
What's "ground truth" (GT)?

**Comment by Aptronymist** [comment]
> What's "ground truth" (GT)?

I was puzzled by that too, but I think it's just... the original best image? I'm guessing it's graphics nerd terminology.

**Comment by FullBleed** [comment]
> > What's "ground truth" (GT)?
> 
> I was puzzled by that too, but I think it's just... the original best image? I'm guessing it's graphics nerd terminology.

Did some research and found that it's a ML term... I'm fairly up to date on most traditional "graphics nerd" terms so it was new to me.

But the nature of the GT seems to be somewhat tailored to the case... so I wondered how they generated the GT in this paper... like is it just a traditional interpolation upscaling method (and if so, why not just call it that)?  Regardless, it begs the question of why use any method other than whatever was used to produce the GT if it's inferior to it...  so my understanding of it is still quite hazy.

**Comment by Reledia** [comment]
My understanding of GT could be wrong, but GT should be the perfect output as it is the original. Probably, they took the original HD image, downscaled/compressed it and tried their method on it.
Having already the original, you can easily understand how much the algorithm has done wrong and in what ways

**Comment by DirtyHamster** [comment]
Ground Truth is simply referring to portions of original training data in this case images.

**Comment by vladmandic** [comment]
i finally took a closer look at this. unfortunately, it has one massive dependency: [mmedit](https://openi.pcl.ac.cn/open-mmlab/mmediting.git) as it uses it as a main wrapper that loads/executes models and untangling that is not really likely as `mmedit` internally uses `mmcv` with `mmengine` and completely abstracts `pytorch`.

if someone wants to create an extension that installs mmedit, that's ok. but i cannot bring such a massive dependency into core app.
