### ISSUE TITLE
[Issue]: Problem managing extensions

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#1369]
### Issue Description

Deforum extension is installed but it shows that it is not installed
![deforum1](https://github.com/vladmandic/automatic/assets/80190186/302d9afa-aea4-4f60-a4d8-41ff411cd1df)
![deforum2](https://github.com/vladmandic/automatic/assets/80190186/07412a56-ff81-485f-934b-a290fa10ec09)

### Version Platform Description

Version: 4a3ab4ed Thu Jun 8 16:10:39 2023 -0400

Processor	AMD Ryzen 7 6800H with Radeon Graphics            3.20 GHz
Installed RAM	32.0 GB (31.2 GB usable)
System type	64-bit operating system, x64-based processor
Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82

**Comment by vladmandic** [comment]
fixed. issue was that defrum info in extension index does not match its actual name from git repository.
