### ISSUE TITLE
[Issue]: I just want to inform something about the User Name problem

### ISSUE THREAD

**Issue by FutonGama** [vladmandic/automatic#137]
### Issue Description

![WindowsTerminal_9lyyPxyX3x](https://user-images.githubusercontent.com/95169493/232140886-d96b798a-2567-4a43-8634-9a193ee233f3.png)

I use Windows and I've noticed that weird errors happen to me using the SD in general even though this Fork or the main one happens to me. My User Profile contains a space between names and it seems that some things cannot read the path. The profile is called "Futon Gama" and the same goes for the user folder (which is the problem). I used some methods to change my username to "futongama" and now my problems are over, I was going to open a topic here talking about the problem but I decided to test changing the username first just to confirm and I saw that I was right. I don't know if you can "fix" this, or at least it would be interesting to inform you that profiles with separate names will cause problems. I don't understand programming but from what I know Linux is different and you don't use spaces in the same way and that's why it causes this, at least I think so, you guys tell me. I hope there's a way to fix things like this. You can close the topic if you want since it's already fixed, but I wanted to let you know because I think it could be the problem of many.

### Platform Description

Windows 11 using Explorer patcher to be like Windows 10 Interface in general. 
Firefox Browser

Intel i9 10900 
RTX 2080 Super 8 GB
32 RAM
5 TB HD, 1 TB SSD Nvme. 
1º Monitor 1080p 240hz, 2º Monitor 4K 60hz.

**Comment by Holyniwa** [comment]
oh holy crap, i hadn't realized this could be so problematic. my PC came with my Firstname Lastname, which may have contributed to the gradio issue from earlier. i know you omitted your method, but would you be willing to speak about it? I'm curious if it could easily addressed, or if its one of those things that's too deep to fix if you already have a lot of stuff that are dependant to that particular username.

**Comment by vladmandic** [comment]
Honestly, names with spaces should not be a problem. And if any library has issues with that, its a real issue. But seems like Gradio is the culprit here, not much I can do about that.

**Comment by FutonGama** [comment]
Alright then, i will take a look on Gradio. On the moment here i'm reverting back my windows name change cause like i imagined many problems happened related to path in other softwares here. Thanks for the help!

**Comment by FutonGama** [comment]
Vlad, a long time ago when I opened this topic I was just starting to learn and I didn't know that the problem was my gradio with the wrong version and strangely it worked with a profile with a name without spaces, but I mean that as time went by I realized numerous times problems related to spaces both in my user name and in folders, there were so many times that I lost count, it really happens very easily, since then I have a new profile and I only create folders without spaces to avoid all these problems. I just wanted to inform you about this and recommend in all cases to keep everything with the name together and preferably also reduce the use of many different characters in case you are going to do something new in the fork or other things, I know that you are an excellent programmer for many years and you already know about the most diverse problems, but I say this giving only my opinion thinking about the good with good intentions, thank you very much.

**Comment by vladmandic** [comment]
@FutonGama thanks for the note!
