### ISSUE TITLE
[Feature]: uninstall xformers  why?

### ISSUE THREAD

**Issue by xam0482** [vladmandic/automatic#1370]
### Feature description

为什么 要主动卸载   xformers 

            x = pkg_resources.working_set.by_key.get('xformers', None)
            if x is not None:
                log.warning(f'Not used, uninstalling: {x}')
                pip('uninstall xformers --yes --quiet', ignore=True, quiet=True)

**Comment by vladmandic** [comment]
this is better asked as question - why create a feature request for it???
and see announcement for it <https://github.com/vladmandic/automatic/discussions/99#discussioncomment-6074109>
