### ISSUE TITLE
[Extension]:  Deforum stops creating images

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#1371]
### Issue Description

After 2-15 images DeForum continues to work but not produce images. I tried it both with the default settings and with different checkpoints.
Actually it gets stuck and I have to start all over again.
I think it happened after the last update of Automatic.
I am attaching what happened in the CMD window as well as the deforum script.

_____________

Deforum extension for auto1111 webui, v2.4b
Git commit: <p>b58056f9</p><p>Wed Jun07 2023 00:47</p>
Saving animation frames to:
C:\vlad\automatic\outputs/image\Deforum_20230609080139
Animation frame: 0/120
Seed: 2962660201
Prompt: tiny cute bunny, vibrant diffraction, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera
Neg Prompt: nsfw, nude
Not using an init image (doing pure txt2img)
┌─────┬───┬───────┬─────┬──────┬────┬────┐
│Steps│CFG│Denoise│Angle│ Zoom │Tr X│Tr Y│
├─────┼───┼───────┼─────┼──────┼────┼────┤
│ 25  │7.0│   0   │  0  │1.0025│ 0  │ 0  │
└─────┴───┴───────┴─────┴──────┴────┴────┘
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  7.22it/s]
Animation frame: 2/120
Creating in-between cadence frame: 0; tween:0.50;
Creating in-between cadence frame: 1; tween:1.00;
Seed: 2962660202
Prompt: tiny cute bunny, vibrant diffraction, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera
Neg Prompt: nsfw, nude
┌─────┬───┬───────┬─────┬─────┬────┬────┐
│Steps│CFG│Denoise│Angle│Zoom │Tr X│Tr Y│
├─────┼───┼───────┼─────┼─────┼────┼────┤
│ 25  │7.0│ 0.35  │  0  │1.003│ 0  │ 0  │
└─────┴───┴───────┴─────┴─────┴────┴────┘
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 12.35it/s]
Animation frame: 4/120
Creating in-between cadence frame: 2; tween:0.50;
Creating in-between cadence frame: 3; tween:1.00;
Seed: 2962660203
Prompt: tiny cute bunny, vibrant diffraction, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera
Neg Prompt: nsfw, nude
┌─────┬───┬───────┬─────┬──────┬────┬────┐
│Steps│CFG│Denoise│Angle│ Zoom │Tr X│Tr Y│
├─────┼───┼───────┼─────┼──────┼────┼────┤
│ 25  │7.0│ 0.35  │  0  │1.0035│ 0  │ 0  │
└─────┴───┴───────┴─────┴──────┴────┴────┘
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 12.47it/s]
Animation frame: 6/120
Creating in-between cadence frame: 4; tween:0.50;
Creating in-between cadence frame: 5; tween:1.00;
Seed: 2962660204
Prompt: tiny cute bunny, vibrant diffraction, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera
Neg Prompt: nsfw, nude
┌─────┬───┬───────┬─────┬──────┬────┬────┐
│Steps│CFG│Denoise│Angle│ Zoom │Tr X│Tr Y│
├─────┼───┼───────┼─────┼──────┼────┼────┤
│ 25  │7.0│ 0.35  │  0  │1.0039│ 0  │ 0  │
└─────┴───┴───────┴─────┴──────┴────┴────┘
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 12.38it/s]
Animation frame: 8/120
Creating in-between cadence frame: 6; tween:0.50;
Creating in-between cadence frame: 7; tween:1.00;
Seed: 2962660205
Prompt: tiny cute bunny, vibrant diffraction, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera
Neg Prompt: nsfw, nude
┌─────┬───┬───────┬─────┬──────┬────┬────┐
│Steps│CFG│Denoise│Angle│ Zoom │Tr X│Tr Y│
├─────┼───┼───────┼─────┼──────┼────┼────┤
│ 25  │7.0│ 0.35  │  0  │1.0042│ 0  │ 0  │
└─────┴───┴───────┴─────┴──────┴────┴────┘
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 12.47it/s]
Animation frame: 10/120
Creating in-between cadence frame: 8; tween:0.50;
Creating in-between cadence frame: 9; tween:1.00;
Seed: 2962660206
Prompt: tiny cute bunny, vibrant diffraction, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera
Neg Prompt: nsfw, nude
┌─────┬───┬───────┬─────┬──────┬────┬────┐
│Steps│CFG│Denoise│Angle│ Zoom │Tr X│Tr Y│
├─────┼───┼───────┼─────┼──────┼────┼────┤
│ 25  │7.0│ 0.35  │  0  │1.0044│ 0  │ 0  │
└─────┴───┴───────┴─────┴──────┴────┴────┘
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 12.08it/s]
Animation frame: 12/120
Creating in-between cadence frame: 10; tween:0.50;
Creating in-between cadence frame: 11; tween:1.00;
Seed: 2962660207
Prompt: tiny cute bunny, vibrant diffraction, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera
Neg Prompt: nsfw, nude
┌─────┬───┬───────┬─────┬──────┬────┬────┐
│Steps│CFG│Denoise│Angle│ Zoom │Tr X│Tr Y│
├─────┼───┼───────┼─────┼──────┼────┼────┤
│ 25  │7.0│ 0.35  │  0  │1.0045│ 0  │ 0  │
└─────┴───┴───────┴─────┴──────┴────┴────┘
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 11.95it/s]
Animation frame: 14/120
Creating in-between cadence frame: 12; tween:0.50;
Creating in-between cadence frame: 13; tween:1.00;
Seed: 2962660208
Prompt: tiny cute bunny, vibrant diffraction, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera
Neg Prompt: nsfw, nude
┌─────┬───┬───────┬─────┬──────┬────┬────┐
│Steps│CFG│Denoise│Angle│ Zoom │Tr X│Tr Y│
├─────┼───┼───────┼─────┼──────┼────┼────┤
│ 25  │7.0│ 0.35  │  0  │1.0044│ 0  │ 0  │
└─────┴───┴───────┴─────┴──────┴────┴────┘
100%|████████████████████████████████████████████████████████████████████████████████████| 9/9 [00:00<00:00, 12.57it/s]

Here it stuck!

[20230609080139_settings.txt](https://github.com/vladmandic/automatic/files/11703504/20230609080139_settings.txt)

### Version Platform Description

Version: https://github.com/vladmandic/automatic/commit/4a3ab4ed3193ce82578e951a45dbee188214838c Thu Jun 8 16:10:39 2023 -0400

Processor AMD Ryzen 7 6800H with Radeon Graphics 3.20 GHz
Installed RAM 32.0 GB (31.2 GB usable)
System type 64-bit operating system, x64-based processor
Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82

_____________

https://github.com/deforum-art/sd-webui-deforum

**Comment by ShmuelRonen** [comment]
![deforum 3](https://github.com/vladmandic/automatic/assets/80190186/a749de8e-d6da-4a57-933f-b5c07dd0a589)

**Comment by watarukamei** [comment]
I have the same problem and can no longer generate images.

**Comment by vladmandic** [comment]
fill the issue using extensions template. i really need to classify issues correctly or this entire repo is going to degrade into thousands of filed issues that are not looked at - and nobody wants that.
marking issue as invalid.

**Comment by vladmandic** [comment]
since its a common issue in the last versions, please try to reset your settings -> live preview values, use any other than full.
see #1378 for details.

**Comment by ShmuelRonen** [comment]
Thanks!!

**Comment by vladmandic** [comment]
closing as no follow-ups. if there is an issue, provide upstream tracking info.
