### ISSUE TITLE
[Issue]: Controlnet not working.

### ISSUE THREAD

**Issue by aniketgore** [vladmandic/automatic#1373]
### Issue Description

Getting the error when I try to use any function. Also control net doesn't work with below error.

(ERROR) [.] Could not set ControlNet value: No module named 'extensions.sd-webui-controlnet'
(ERROR) [.] Could not set ControlNet value: No module named 'extensions.sd-webui-controlnet'

**Comment by vladmandic** [comment]
wrong template and no version info provided. marking as invalid.
