### ISSUE TITLE
[Issue]: AMD GPUs not running on with updated

### ISSUE THREAD

**Issue by seanthenry** [vladmandic/automatic#1376]
### Issue Description

When I try to generate an image I get the error below. It is related to the pytorch version as I can get it to work if I roll back the version.

```
MIOpen(HIP): Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' naive_conv.cpp: HIPRTC_ERROR_COMPILATION (6)
MIOpen(HIP): Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: naive_conv.cpp
MIOpen(HIP): Warning [BuildHip] /tmp/comgr-bafe6d/input/naive_conv.cpp:39:10: fatal error: 'limits' file not found
#include <limits> // std::numeric_limits
         ^~~~~~~~
1 error generated when compiling for gfx1030.
terminate called after throwing an instance of 'miopen::Exception'
  what():  /long_pathname_so_that_rpms_can_package_the_debug_info/data/driver/MLOpen/src/hipoc/hipoc_program.cpp:304: Code object build failed. Source: naive_conv.cpp
Aborted (core dumped)
```

I get the same issue with auto1111 1.3x but have if I modify webui.sh to install the older version of pytorch I can get it to run
```
#    export TORCH_COMMAND="pip install torch==2.0.1+rocm5.4.2 torchvision==0.15.2+rocm5.4.2 --index-url https://download.pytorch.org/whl/rocm5.4.2"
    export TORCH_COMMAND="pip install torch==1.13.1+rocm5.2 torchvision==0.14.1+rocm5.2 --index-url https://download.pytorch.org/whl/rocm5.2"
```

### Version Platform Description

Linux mint 21
kernel 6.3.2
CPU Ryzen  7900x

GPU 
Name:                    gfx1030
Marketing Name:          AMD Radeon RX 6800

**Comment by vladmandic** [comment]
so why create issue if you know the solution? and don't modify `webui.sh` (anytime you think that is a good idea, don't do it)
just set `TORCH_COMMAND="torch==1.13.1+rocm5.2 torchvision==0.14.1+rocm5.2 --index-url https://download.pytorch.org/whl/rocm5.2"`
and installer will pick it up from there.

**Comment by seanthenry** [comment]
I created the issue so that it might get addressed since AMD does not get much attention, and wishfully thinking that the move to pytorch 2 would give a speed boost. I was not sure if there is an argument or something left out of the build script giving me the error.

Sorry I was not clear I did not edit the webui.sh for this version, that is how I got it working on auto1111 I just commented out the updated line and copied in that one part from the previous script.

Your version uses a completely different webui.sh and did not have that option also on the install there is not a webui-user.sh so I was not sure if it would call it the same way. I will try setting torch the way you specified when I get off work.

Thanks for your time.

**Comment by vladmandic** [comment]
> I created the issue so that it might get addressed since AMD does not get much attention

I agree that AMD doesn't give ROCm sufficient attention, but I cannot provide an in-app solution that downgrades `torch` and `rocm` to versions before this repo even existed. Does it work? Sure, why not. But I cannot support such old versions.
