### ISSUE TITLE
[Issue]: after a few image generations from text, text generation hangs forever

### ISSUE THREAD

**Issue by klausman** [vladmandic/automatic#1378]
### Issue Description

After restarting the server I can generated maybe 5 images just fine, but then the image egenration hangs at the 90% mark. Reloading the page, or using the "Send interrupt" button, just doesn;t work. In the terminal, the task looks completed (progress bar at 100%, no further messages), but the webui sits at 89% or 90% and never makes any further progress. Only way to fix is to entirely restart the server. I have tried removing the venv and getting a fresh one, didn't make a difference. A random checkout from a few days ago worked fine. Memory bar on "System Info" slowly creeps up to max, and then stays there. no OOM messages or similar.

### Version Platform Description

Windows 10, RTX2070S, Browser is Vivaldi (Chromium-based)

updated: 2023-06-09
hash: e8e26040
url: https://github.com/vladmandic/automatic/tree/master
arch: AMD64
cpu: AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.10.11
Torch: 2.0.1+cu118 Autocast  half

Repos:
Stable Diffusion: [cf1d67a] 2023-03-25
Taming Transformers: [9e9981c] 2022-11-07
CodeFormer: [7a584fd] 2023-01-18
BLIP: [3a29b74] 2022-09-20
k_diffusion: [c9fe758] 2023-05-21

**Comment by klausman** [comment]
Commit that works fine: 2a664b1bdb6dcda2193abef0b9c8dd12f5b22c36

**Comment by vladmandic** [comment]
duplicate #1358
