### ISSUE TITLE
[Feature]: Use result from dynamic prompts/wildcard prompt when passing prompt from text2img to img2img.

### ISSUE THREAD

**Issue by Nyarlathotep885** [vladmandic/automatic#1379]
### Feature description

**Current behavior:** wildcard prompt gets passed into img2img verbatim, when the "->Image" button is used in txt2img tab.

original txt2img prompt
```
"__eyecolors__ eyes, 1girl"  
```
current img2img result
```
"__eyecolors__ eyes, 1girl"  
```

**Desired behavior:** result of dynamic prompt used to generate the image in txt2img is what gets passed into img2img.
original txt2img prompt
```
"__eyecolors__ eyes, 1girl" 
```
desired img2img result
```
"red eyes, 1girl"   
```

**Comment by vladmandic** [comment]
this works correctly when using built-in wildcard support in sdnext.
