### ISSUE TITLE
[Issue]: Running significantly slower than normal

### ISSUE THREAD

**Issue by drfacedoctor** [vladmandic/automatic#1381]
### Issue Description

I have been using this fork of Automatic for a long time, and within the last day my iterations per second have dropped from about 6 it/s to about 2.5 s/it. It seems to have happened midway through the day on June 9th after restarting the program. Nothing else has changed about my setup. I can still utilize all of my VRAM and make large batch sizes and highres fix, it's just running much slower now.

### Version Platform Description

My Specs are

Automatic: Version: 971e51fe Fri Jun 9 18:24:18 2023 -0400

NVidia Driver Version: 532.03
CUDA Version: 12.1

OS: Windows 10 Pro 19405
CPU: AMD Ryzen 7 5800x3D
RAM: 32GB DDR4 3200Mhz
GPU: Nvidia RTX 3070 8GB

I have not changed my hardware in recent history, and to my knowledge I haven't gotten any windows updates within the last few weeks, I have CUDA tools installed and everything, like I said everything was working fine a day ago and now it's running much slower. Tried restarting the program and restarting Windows multiple times but no luck.

**Comment by InfinityARS** [comment]
Downgrade to nvidia driver 531

**Comment by drfacedoctor** [comment]
> 

Tried downgrading to driver 531.68, doesn't seem to change anything. Hovers around 2.6 it/s at best.

**Comment by drfacedoctor** [comment]
Tried running the original fork of Automatic1111 and I'm getting 5-6 it/s. 

Also I just realized I wasn't getting ~2.5 it/s, it was 2.5 s/it, slower by several orders of magnitude. I don't know exactly what's changed here.

**Comment by vladmandic** [comment]
if you went from 2.5 it/s to 2.5 s/it, you're most likely not even using gpu and you're running on cpu.
look at your startup console log, is it even detecting gpu correctly and using right version of torch?

**Comment by Metalica** [comment]
> if you went from 2.5 it/s to 2.5 s/it, you're most likely not even using gpu and you're running on cpu. look at your startup console log, is it even detecting gpu correctly and using right version of torch?

Same problem; 1070 8Gb;

21:42:31-491273 INFO     Version: f63dd1c9 Sat Jun 10 22:01:09 2023 +0300
21:42:31-897404 INFO     Setting environment tuning
21:42:31-901480 INFO     nVidia CUDA toolkit detected
21:42:37-985120 INFO     Torch 2.0.1+cu118

**Comment by vladmandic** [comment]
@Metalica same answer - "me too" doesn't help if i don't even know what your task is and what performance numbers you're seeing.

**Comment by Metalica** [comment]
> @Metalica same answer - "me too" doesn't help if i don't even know what your task is and what performance numbers you're seeing.

 - Same 2.5s/It. No gpu usage.
 - Stop / dead at 50%
 - From 50% on is slow like a rock.

**Comment by Metalica** [comment]
Benchmark:  

  "2023-06-10 21:59:10.325079",
    "0.52",
    "updated:2023-06-10 hash:f63dd1c9 url:https://github.com/vladmandic/automatic/tree/master",
    "arch:AMD64 cpu:Intel64 Family 6 Model 158 Stepping 9, GenuineIntel system:Windows release:Windows-10-10.0.19044-SP0 python:3.10.6",
    "torch:2.0.1+cu118 Autocast  half xformers:unavailable accelerate:0.18.0 transformers:4.26.1",
    "device:NVIDIA GeForce GTX 1070 (1) (compute_37) (6, 1) cuda:11.8 cudnn:8700 8GB",
    "doggettx none",
    "v1-5-pruned-emaonly.safetensors [6ce0161689]",
    "Metal",
    "",
    "7f6dea"

**Comment by drfacedoctor** [comment]
`12:55:15-341789 INFO     Starting SD.Next
12:55:15-344793 INFO     Python 3.10.11 on Windows
12:55:15-381828 INFO     Version: f63dd1c9 Sat Jun 10 22:01:09 2023 +0300
12:55:15-589955 INFO     Setting environment tuning
12:55:15-592958 INFO     nVidia CUDA toolkit detected
12:55:16-907487 INFO     Torch 2.0.1+cu118
12:55:16-927346 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
12:55:16-928347 INFO     Torch detected GPU: NVIDIA GeForce RTX 3070 VRAM 8191 Arch (8, 6) Cores 46`

I submitted a benchmark but the log hasn't updated yet.

`TIMESTAMP - 2023-06-10 12:57:22.310006
PERFORMANCE - 0.36 / 0.68 / 1.19
VERSION - updated:2023-06-10 hash:f63dd1c9 url:https://github.com/vladmandic/automatic/tree/master
SYSTEM - arch:AMD64 cpu:AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system:Windows release:Windows-10-10.0.19045-SP0 python:3.10.11
LIBRARIES - torch:2.0.1+cu118 Autocast nohalf xformers:unavailable accelerate:0.18.0 transformers:4.26.1
DEVICE - evice:NVIDIA GeForce RTX 3070 (1) (compute_37) (8, 6) cuda:11.8 cudnn:8700 8GB
OPTIMIZATIONS - sdp medvram
MODEL - AbyssOrangeMix2_hard.safetensors [0fc198c490]
USERNAME - PC
HASH - 23a538
`

Sorry if I've left anything major out, trying my best to give you all the relevant info.

**Comment by vladmandic** [comment]
> Sorry if I've left anything major out, trying my best to give you all the relevant info.

this time you've provided everything asked, so no worries.

this is pretty strange - startup shows gpu correctly detected and right version of torch/cuda/cudnn used.
but benchmark is abysmal.
only thing that stands out is that you have nohalf when in reality any 3xxx/4xxx gpu should never need it (and i mean never unless underlying model is fundementaly broken and then its better to give up on that model). nohalf and other settings like that are for gpus that have issues running in fp16 mode. and you're using medvram, i guess because you're trying to run with as-high-as-possible resolution and that gives you few more pixels at the cost of performance.

can i suggest that for purpose of testing you copy your config.json somewhere else and then just delete it - let server create a new one with defaults? and then re-run benchmark.

**Comment by vladmandic** [comment]
> * Same 2.5s/It. No gpu usage.
> * Stop / dead at 50%
> * From 50% on is slow like a rock. 35~ /it.

if its starts with 2.5it/s and then slows down, its definitely not using cpu from get-go as your cpu wouldn't get to 2.5 its to start with. and there is no possibly to switch processing from gpu to cpu half-way, so don't say its same when its very different. even your symptoms are different.

**Comment by Metalica** [comment]
[
    "2023-06-10 22:28:21.360916",
    "0.43",
    "updated:2023-06-10 hash:f63dd1c9 url:https://github.com/vladmandic/automatic/tree/master",
    "arch:AMD64 cpu:Intel64 Family 6 Model 158 Stepping 9, GenuineIntel system:Windows release:Windows-10-10.0.19044-SP0 python:3.10.6",
    "torch:2.0.1+cu118 Autocast  half xformers:unavailable accelerate:0.18.0 transformers:4.26.1",
    "device:NVIDIA GeForce GTX 1070 (1) (compute_37) (6, 1) cuda:11.8 cudnn:8700 8GB",
    "sdp none",
    "v1-5-pruned-emaonly.safetensors [6ce0161689]",
    "Metal",
    "Deleted config and re made benchmark",
    "a7fd59"
  ]

**Comment by vladmandic** [comment]
just to rule something out, please disable live preview in settings.

**Comment by Metalica** [comment]
![kkkk](https://github.com/vladmandic/automatic/assets/411059/5cfb1a00-3b0a-4a1c-aee8-1dd410dc5de3)

    "2023-06-10 22:41:20.000111",
    "0.31",
    "updated:2023-06-10 hash:f63dd1c9 url:https://github.com/vladmandic/automatic/tree/master",
    "arch:AMD64 cpu:Intel64 Family 6 Model 158 Stepping 9, GenuineIntel system:Windows release:Windows-10-10.0.19044-SP0 python:3.10.6",
    "torch:2.0.1+cu118 Autocast  half xformers:unavailable accelerate:0.18.0 transformers:4.26.1",
    "device:NVIDIA GeForce GTX 1070 (1) (compute_37) (6, 1) cuda:11.8 cudnn:8700 8GB",
    "sdp none",
    "v1-5-pruned-emaonly.safetensors [6ce0161689]",
    "Metal",
    "Deleted config after removing all live preview",
    "a7fd59"
  ]
]

**Comment by vladmandic** [comment]
@Metalica lets simplify to bare minimum - basic workflow only. you're running hires fix here and that can cause a completely different codepaths to trigger. just spamming into issue doesn't help.

**Comment by Metalica** [comment]
![34234](https://github.com/vladmandic/automatic/assets/411059/230148f3-9f7a-4207-93e0-97e43db5d56e)

Omg, what the heck is going on ? Know a picture has been done in seconds.

**Comment by vladmandic** [comment]
first, stop posting screenshots on every post, it doesn't help at all.
second, i have no idea what you just said.

**Comment by drfacedoctor** [comment]
@vladmandic 
>can i suggest that for purpose of testing you copy your config.json somewhere else and then just delete it - let server create a new one with defaults? and then re-run benchmark and don't use any cmdline flags.

This seems to have done the trick, if you want I can paste copies of the two config files so you can see the differences.

**Comment by vladmandic** [comment]
closing as original issue is resolved.

**Comment by DrakeRichards** [comment]
I had this same issue, so I thought I'd dig a bit deeper and see what actually happened. I believe the culprit was the setting "Live Previews > Live Preview Method" (`show_progress_type` in config.json). After I updated to the most recent version, this setting seemed to have no default value, so I set it to "Full VAE". However, when I generated a new config.json file, this setting's default was "TAESD". This value was also changed in the settings list from @drfacedoctor, but it was set to "Approximate NN" in the non-working config. I didn't experience the same performance hit when I tried "Approximate NN", but that might just be due to different setups.

Did a recent update change the `show_progress_type` default value? I fixed it on my end now, but I just thought I'd ask in case anyone else experiences this.

**Comment by vladmandic** [comment]
> Did a recent update change the show_progress_type default value? I fixed it on my end now, but I just thought I'd ask in case anyone else experiences this.

bad spelling set it to undefined. if you do new install, it would be set correctly. but for existing installs, it was unfortunate.,

**Comment by ubemotho** [comment]
> I had this same issue, so I thought I'd dig a bit deeper and see what actually happened. I believe the culprit was the setting "Live Previews > Live Preview Method" (`show_progress_type` in config.json). After I updated to the most recent version, this setting seemed to have no default value, so I set it to "Full VAE". However, when I generated a new config.json file, this setting's default was "TAESD". This value was also changed in the settings list from @drfacedoctor, but it was set to "Approximate NN" in the non-working config. I didn't experience the same performance hit when I tried "Approximate NN", but that might just be due to different setups.
> 
> Did a recent update change the `show_progress_type` default value? I fixed it on my end now, but I just thought I'd ask in case anyone else experiences this.

thanks @DrakeRichards i fixed my slow iteration speed without deleting and installing again, thanks to you
