### ISSUE TITLE
[Issue]: Inpainting gets stuck, error

### ISSUE THREAD

**Issue by mildfever** [vladmandic/automatic#1385]
### Issue Description

I cant always reproduce this error, but this is what happens:

Transfer a generated image to inpaint, mask, press "Generate", the task doesn't complete.

The DOS box marks task as complete (100%), yet the number on top of the "Generate" button in the UI is stuck at 94% (or another high number like 86%, 80% etc). I can see the images getting processed, but no images appear on the final result (not ever the incomplete half baked images).
Same happens on 2x3 (Batch count 2, Batch size 3), here the "Generate" numbers get stuck around 45%, 48% etc., while on the DOS box, only the first iteration reaches 100% the second doesn't start. Again no images are displayed in the final result.

Also, while stuck, the GPU fans keep spinning like it's still processing, pressing "Stop" on the UI does nothing, they only stop when i close the DOS box.
There are no error messages in the DOS box.

This issue occurred more on version 971e51fe, but still occurs on version abd7d160
Never had this issue with any of the previous versions.

### Version Platform Description

version: 971e51fe
version: abd7d160

Firefox browser 114.0 64bit
3060 RTX

### Acknowledgements

- [ ] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
since its a common issue in the last versions, please try to reset your settings -> live preview values, use any other than full.
see https://github.com/vladmandic/automatic/issues/1378 for details.

**Comment by mildfever** [comment]
I set the parameter to TAESD, did a fair number of inpaints on abd7d16, not encountering the same error.
Also the overall generation (txt2img and inpainting) seems faster, some 5-10 seconds gain on a 6 image batch (Euler a with 28 sampling steps).
