### ISSUE TITLE
[Extension]: (ERROR) [.] Could not set ControlNet value: No module named 'extensions.sd-webui-controlnet'

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#1394]
### Issue Description

It start after I install the new --upgrade 
Version: 1d0a18ef Sun Jun 11 09:00:38 2023 -0400
This error appears with every image creation regardless of whether it is with  ControlNet or not. At the same time, everything seems to work fine, including  ControlNet.
_____________
(ERROR) [.] Could not set ControlNet value: No module named 'extensions.sd-webui-controlnet'
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]20:56:06-219686 INFO     ControlNet used torch.float16 VAE to encode torch.Size([1, 4, 64, 64]).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.06it/s]
20:56:59-876791 INFO     Loading preprocessor: reference_only
20:56:59-878790 INFO     Pixel Perfect Computation:
20:56:59-880792 INFO     resize_mode = ResizeMode.INNER_FIT
20:56:59-881791 INFO     raw_H = 976
20:56:59-883791 INFO     raw_W = 648
20:56:59-885791 INFO     target_H = 512
20:56:59-887791 INFO     target_W = 512
20:56:59-889791 INFO     estimation = 512.0
20:56:59-890791 INFO     preprocessor resolution = 512
(ERROR) [.] Could not set ControlNet value: No module named 'extensions.sd-webui-controlnet'
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]20:57:00-664791 INFO     ControlNet used torch.float16 VAE to encode torch.Size([1, 4, 64, 64]).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.15it/s]
20:57:29-497100 INFO     Loading preprocessor: reference_only
20:57:29-500102 INFO     Pixel Perfect Computation:
20:57:29-502101 INFO     resize_mode = ResizeMode.INNER_FIT
20:57:29-503103 INFO     raw_H = 976
20:57:29-505102 INFO     raw_W = 648
20:57:29-506101 INFO     target_H = 512
20:57:29-509100 INFO     target_W = 512
20:57:29-511101 INFO     estimation = 512.0
20:57:29-515101 INFO     preprocessor resolution = 512
(ERROR) [.] Could not set ControlNet value: No module named 'extensions.sd-webui-controlnet'
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]20:57:30-237099 INFO     ControlNet used torch.float16 VAE to encode torch.Size([1, 4, 64, 64]).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.18it/s]
20:57:50-725354 INFO     Loading preprocessor: reference_only
20:57:50-727355 INFO     Pixel Perfect Computation:
20:57:50-729354 INFO     resize_mode = ResizeMode.INNER_FIT
20:57:50-731354 INFO     raw_H = 976
20:57:50-733356 INFO     raw_W = 648
20:57:50-734355 INFO     target_H = 512
20:57:50-737354 INFO     target_W = 512
20:57:50-739354 INFO     estimation = 512.0
20:57:50-741355 INFO     preprocessor resolution = 512
(ERROR) [.] Could not set ControlNet value: No module named 'extensions.sd-webui-controlnet'
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]20:57:51-622354 INFO     ControlNet used torch.float16 VAE to encode torch.Size([1, 4, 64, 64]).
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.10it/s]
20:59:37-636746 INFO     Loading preprocessor: reference_only
20:59:37-641743 INFO     Pixel Perfect Computation:
20:59:37-643744 INFO     resize_mode = ResizeMode.INNER_FIT
20:59:37-644744 INFO     raw_H = 1536
20:59:37-646744 INFO     raw_W = 1024
20:59:37-648744 INFO     target_H = 512
20:59:37-649744 INFO     target_W = 512
20:59:37-652745 INFO     estimation = 512.0
20:59:37-654744 INFO     preprocessor resolution = 512
(ERROR) [.] Could not set ControlNet value: No module named 'extensions.sd-webui-controlnet'

### Version Platform Description

Using VENV: C:\vlad\automatic\venv
20:40:34-140556 INFO     Starting SD.Next
20:40:34-144561 INFO     Python 3.10.7 on Windows
20:40:34-234554 INFO     Version: 1d0a18ef Sun Jun 11 09:00:38 2023 -0400
20:40:34-955551 INFO     nVidia CUDA toolkit detected
20:40:38-253551 INFO     Torch 2.0.1+cu118
20:40:38-267554 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
20:40:38-270553 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i cannot reproduce, but i've just pushed a change that might help - please try.

**Comment by vladmandic** [comment]
separate report shows this as fixed. if issue persists, report and i'll reopen.
