### ISSUE TITLE
[Extension]: A number of extensions broken after 1d0a18e

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#1395]
### Issue Description

It looks like several extensions broke after 1d0a18e, which is the only recent change touching `scripts.py`. Basically, extensions (listed below) throw `ModuleNotFoundError` as if they weren't able to load a module from the search path. 

The errors vary, but they're all related to importing modules from the `scripts` namespace. 

For example, this line https://github.com/kohya-ss/sd-webui-additional-networks/blob/e9f3d622b5a98650008a685ea23b27eb810da35a/scripts/additional_networks.py#L13 fails with 1d0a18e with a ModuleNotFoundError.

If I revert 1d0a18e, errors no longer occur. I have no idea if it's a bug, or a fault of those extensions.

Some extensions affected (one put in the list):

- sd-webui-cutoff
- sd-webui-additional-networks
- PBRemTools

### Version Platform Description

Ubuntu with Python 3.9, supplied by Paperspace.
Torch 2.1.0 (cu118)

### URL link of the extension

https://github.com/kohya-ss/sd-webui-additional-networks/

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
Unfortunate push without real benefits, I hopes it would speed up extensions load, but it doesn't and 8t breaks few of them. And yes, those extensions are not following best practise, but still not a reason for me to break them. I'll fix it when I get back home.

**Comment by lbeltrame** [comment]
What would be the best practice? I could file issues for some of them, I guess. Or if it's easy, do the PRs myself.

**Comment by vladmandic** [comment]
I wrote an article on that just few days ago, I'll send you a link.

**Comment by vladmandic** [comment]
i cannot reproduce, but i've just made a change that might help - can you try?

**Comment by lbeltrame** [comment]
On it. Will edit once the webui is running.
