### ISSUE TITLE
[Issue]: Errors on Startup

### ISSUE THREAD

**Issue by HarrisTerry** [vladmandic/automatic#1396]
### Issue Description

Unsure if these are important for development, but I am getting these errors on load, although things are working fine

16:25:54-629869 WARNING  Modified files: ['webui.bat', 'javascript/themes.json']

16:25:59-189175 ERROR    Error updating submodule:  9e6bbd9b8931bbe869a8e28e7005b0e13c2efff0
                         extensions-builtin/clip-interrogator-ext (heads/main)
16:25:59-234445 ERROR    Error updating submodule:  b28c03b10f45d44d09b570b20fe8a4f61061b294
                         extensions-builtin/multidiffusion-upscaler-for-automatic1111 (sd-webui-v1.1.0-26-gb28c03b)

### Version Platform Description

Win11, 3070ti 8GB, 64gb RAM, 12700k 5ghz, m.2 PCI SSDs

16:33:00-812156 INFO     Version: 1d0a18ef Sun Jun 11 09:00:38 2023 -0400

16:33:33-228200 INFO     Starting SD.Next
16:33:33-231200 INFO     Python 3.10.9 on Windows
16:33:33-258201 INFO     Version: 1d0a18ef Sun Jun 11 09:00:38 2023 -0400
16:33:33-577347 INFO     nVidia CUDA toolkit detected
16:33:34-557229 INFO     Torch 2.0.0+cu118
16:33:34-565606 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
16:33:34-566559 INFO     Torch detected GPU: NVIDIA GeForce RTX 3070 Ti VRAM 8192 Arch (8, 6) Cores 48
16:33:34-629746 WARNING  Modified files: ['webui.bat', 'javascript/themes.json']
16:33:34-658745 INFO     Disabled extensions-builtin: ['a1111-sd-webui-haku-img']
16:33:34-659745 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
16:33:34-663746 INFO     Disabled extensions: ['a1111-sd-webui-haku-img']
16:33:34-664248 INFO     Enabled extensions: ['a1111-mini-paint', 'a1111-sd-webui-tagcomplete',
                         'deforum-for-automatic1111-webui', 'sd-dynamic-prompts', 'sd-webui-3d-open-pose-editor',
                         'sd-webui-ar', 'sd-webui-cutoff', 'stable-diffusion-webui-state',
                         'ultimate-upscale-for-automatic1111']

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by brknsoul** [comment]
>  I have read the above and searched for existing issues

apparently not. ;-)

#1395

**Comment by HarrisTerry** [comment]
ROFL dude I don't understand 90% of the website, sorry!

**Comment by vladmandic** [comment]
> Unsure if these are important for development, but I am getting these errors on load, although things are working fine

if you're unsure and everything is working, why not ask question in discussions instead of opening an issue?
and if you want to see the root cause for `Error updating submodule:`, log does later state `See log file for more details: sdnext.log`
