### ISSUE TITLE
[Extension]: SEAT launcher reports local changes

### ISSUE THREAD

**Issue by Aurety** [vladmandic/automatic#1399]
### Issue Description

Hi, since some latest updates, I can't run anymore my SEAT version of Automatic.. Any Idea Why, I tried some tips I've found on internet but without success..

ERROR MESSAGE : // UPDATE AND LAUNCH
Your local changes to the following files would be overwritten by merge:  extensions-builtin/a1111-sd-webui-lycoris
Please commit your changes or stash them before you merge

Updating automatic at F:\SEAIT\automatic
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 8 (delta 6), reused 8 (delta 6), pack-reused 0
Unpacking objects: 100% (8/8), 916 bytes | 1024 bytes/s, done.
From https://github.com/vladmandic/automatic
   1d0a18ef..c9e58c96  master     -> origin/master
error: Your local changes to the following files would be overwritten by merge:
        extensions-builtin/a1111-sd-webui-lycoris
Please commit your changes or stash them before you merge.
Aborting
Updating 5190f702..c9e58c96

launching automatic at F:\SEAIT\automatic
00:15:25-906992 INFO     Running extension preloading
00:15:25-911719 INFO     Running in safe mode without user extensions
00:15:26-099376 INFO     Starting SD.Next
00:15:26-117527 INFO     Python 3.10.7 on Windows
00:15:26-164342 INFO     Version: 5190f702 Sat Jun 3 14:02:21 2023 -0400
00:15:27-222458 INFO     Latest published version: c9e58c9604d851e02d8838de3f200ffc1521eae0 2023-06-11T21:21:28Z
00:15:27-224459 INFO     Setting environment tuning
00:15:27-228463 INFO     nVidia CUDA toolkit detected
00:15:48-577444 INFO     Torch 2.0.0+cu118
00:15:48-724179 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
00:15:48-727360 INFO     Torch detected GPU: NVIDIA GeForce RTX 2080 Ti VRAM 11264 Arch (7, 5) Cores 68
00:15:48-729073 INFO     Torch detected GPU: NVIDIA GeForce RTX 2080 Ti VRAM 11264 Arch (7, 5) Cores 68
00:15:48-731075 INFO     Torch detected GPU: NVIDIA GeForce RTX 2070 SUPER VRAM 8192 Arch (7, 5) Cores 40
00:15:48-734077 INFO     Verifying requirements
00:15:48-774205 INFO     Installing packages
00:15:48-832908 INFO     Running setup
00:15:48-834910 INFO     Installing repositories
00:15:53-634184 INFO     Installing submodules
00:16:00-639841 INFO     Updating submodules
00:17:24-042782 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext',
                         'hide-settings-v2-inner', 'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111',
                         'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer',
                         'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
00:17:24-063801 INFO     Updating Wiki
00:17:27-094308 INFO     Running extension preloading
00:17:27-096309 INFO     Running in safe mode without user extensions
00:17:27-098310 INFO     Server arguments: ['--autolaunch', '--theme=dark', '--safe']
No module 'xformers'. Proceeding without it.
00:18:01-242946 INFO     Libraries loaded
00:18:01-247951 INFO     Using data path: F:\SEAIT\automatic
00:18:01-454135 INFO     Available VAEs: F:\SEAIT\automatic\models\VAE 3
00:18:10-690642 INFO     Available models: F:\SEAIT\automatic\models\Stable-diffusion 131
2023-06-12 00:18:51,962 - ControlNet - INFO - ControlNet v1.1.224
ControlNet preprocessor location: F:\SEAIT\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
2023-06-12 00:18:54,343 - ControlNet - INFO - ControlNet v1.1.224
00:19:03-616796 INFO     Loading UI theme: name=sudeepshouche/minimalist style=Auto
00:19:08-732615 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
Loading weights: F:\SEAIT\automatic\models\Stable-diffusion\MergeWip\majchick2.safetensors ---------- 0.0/4.5   -:--:--
                                                                                                      GB
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
00:19:14-535342 INFO     Model created from config: F:\SEAIT\automatic\configs\v1-inference.yaml
Loading weights: F:\SEAIT\automatic\models\VAE\klF8Anime2VAE_klF8Anime2VAE.ckpt ----------- ---- 283.0/404.7 MB 0:00:00
00:23:08-294385 INFO     Applying scaled dot product cross attention optimization (without memory efficient attention)
00:23:17-838068 INFO     Embeddings loaded: 207 ['3d-female-cyborgs', '512paintstyle3-light', '512speedpainter',
                         '5h6n4', '852style-girl', 'abstract-concepts', 'advntr', 'alberto-mielgo', 'an5',
                         'anatomical-illustration', 'anime-background-style-v2', 'antonialastnamesd15', 'art by
                         sel-foc', 'art by Smoose2', 'AS-Adult', 'AS-Adult-neg', 'AS-Elderly', 'AS-MidAged',
                         'AS-Young', 'AS-Young-neg', 'AS-Young-neg(1)', 'AS-Younger', 'AS-Youngest', 'Asia SG',
                         'Asian-Less', 'Asian-Less-Neg', 'Asian-Less-Toon', 'atompunkstylesd15', 'bad-artist',
                         'bad-artist-anime', 'bad-hands-5', 'bad-image-9600', 'bad-image-v2-11000',
                         'bad-image-v2-27000', 'bad-image-v2-39000', 'bad_pictures', 'bad_prompt',
                         'bad_prompt_version2', 'BadDream', 'BadNegAnatomyV1-neg', 'black-and-white-design',
                         'bodygrammps', 'cadastredesign', 'cajwes', 'char-con', 'char_armor-concept', 'CharTurner',
                         'charturnerv2', 'chyleigh', 'conner-fawcett-style', 'corneo_covering_breasts_arms_crossed',
                         'corneo_tentacle_sex', 'CyberRealistic_Negative-neg', 'cyberware_style', 'darkest_diffusion',
                         'DarkFantasy', 'depthmap-style', 'dishonored-portrait-styles', 'DollsMarinaBychkova-6500',
                         'dollzy1', 'easynegative', 'Elease SG', 'elodie', 'emb-rrf-low', 'emb-rrf2', 'f4ystr4ng3r',
                         'fr4nki34d4ms', 'fractal-flame', 'frank-frazetta', 'Gatto SG', 'ghst-3000', 'glow-forest',
                         'grisstyle', 'happy512', 'haze-light-1800', 'HentaiManga', 'hotify', 'HyperStylizeV6',
                         'illustration-style', 'ilya-shkipin', 'ingmar-bergman', 'iridescent-photo-style', 'iulje',
                         'iuljeV4-1450-1950', 'jeansheels', 'k4sp14', 'kcboho07-3000', 'kcboho07-4000', 'KingLich ',
                         'kkw-Afro', 'kkw-Asian', 'kkw-bp', 'kkw-comicp', 'kkw-Euro', 'kkw-Extreme-Neg', 'kkw-fat-m',
                         'kkw-macro', 'kkw-micro', 'kkw-oily-helper', 'kkw-ph1', 'kkw-ph1-neg', 'kkw-splatter',
                         'kodakvision500t', 'KokoaAisu', 'land_style', 'landscape_style', 'Lass SG', 'leica-style',
                         'light-negative-neg', 'liquid-light', 'LivaHendriks', 'lr', 'madison', 'MakeItPopVA',
                         'MangaHentaiStyleConceptv2', 'marbling-art', 'Menasaurio SG', 'metropolis_e', 'microwaist',
                         'monster-girl', 'mrblng02-1500', 'mrblng02-4000', 'mrblng02-8000', 'mt_concept-art',
                         'n1n4d0brev', 'n3t0p', 'nbdy-julia-sd15', 'nebulae', 'negative_hand-neg',
                         'NG_DeepNegative_V1_2T', 'ng_deepnegative_v1_32t', 'NG_DeepNegative_V1_75T', 'NinaQ SG',
                         'nobg', 'olfn', 'optional_styleAI', 'orientalist-art', 'OVERMASKED', 'p0k13s', 'pervpulp15',
                         'photo of a daisyrey-100', 'piotr-jablonski', 'pjablonski-style', 'PlanIt',
                         'portrait-style-dishonored', 'prettify', 'prettyeyes', 'prt', 'PureErosFace_V1', 'retro-girl',
                         'RFKTR_bontrex', 'RFKTR_bontrex-150', 'rfktr_bwmnga', 'rfktr_circrex', 'rfktr_sinetempore',
                         'Riotdoll SG', 'rld', 'rmadanegative402_sd15-neg', 'ruan-jia', 'rz-neg-15-foranalog',
                         'S055_Rolyat', 'sablynn', 'sagbobz', 'sdflashlightv2', 'sdflashlightv2-1500',
                         'sdflashlightv2-600', 'shirtp_stt', 'Skella SG', 'small_tits', 'SouthOfTheBorderSD15',
                         'splash_style', 'splash_style2', 'starhavenmachinegods', 'Style-BladeRunner2049-8v',
                         'Style-Empire', 'Style-Glass', 'Style-Glorious', 'Style-Info', 'Style-Italy', 'Style-Kilt',
                         'Style-Necromancy', 'Style-Petal', 'style-princess', 'Style-Psycho', 'style-rustmagic',
                         'style-rustmagic-neg', 'style-swirlmagic', 'style-widow', 'style_tombraider', 'The 100
                         bellamy', 'The 100 octavia', 'transmutation-circles', 'travis-bedel', 'trypophobia',
                         'ulzzang-6500', 'ulzzang-6500-v1.1', 'uncannime', 'UnrealisticDream',
                         'walter-wick-photography', 'was-steampunk', 'wayne-reynolds-character', 'wholesomegrandpas',
                         'wholesomegrannies', 'wrinklystudiolights1', 'yam-negative-10000-neg', 'yoji-shinkawa-style',
                         'Zzef SG']
00:23:17-889114 INFO     Textual inversion embeddings skipped(46): 21charturnerv2, anthro, cartoonish_doll, Remix,
                         SCG768-Euphoria, dgtl, glitch, hellscape768, Apoc768, DaveSpaceFour, UrbanJungle, pinup768,
                         PortraitHelper, TungstenDispo, DrD_PNTE768, InkPunk768, inksketchcolour1subtle, rzviceb6,
                         ThisHonor, UlukInkSketch2, Art by Smoose-22, classipeint, dgtlv2, laxpeint, laxpeintV2,
                         mdjrny-ppc, PaintStyle3, PaintStyle4, paintstyle5, paintstyle8, rz-shear, rzminjourney,
                         style-princess_sd2, AnalogFilm768, CinemaHelper, nartfixer, negmutation-200, negmutation-2300,
                         negmutation-2400, negmutation-400, neg_Colorizer768-neutral, nfixer, nrealfixer,
                         rz-neg-foranalogportrait, rz-neg-general, VintageHelper
00:23:17-902126 INFO     Model loaded in 249.8s (load=5.5s create=0.9s apply=227.4s vae=5.6s move=0.7s embeddings=9.6s)
00:23:18-165360 INFO     Model load finished: {'ram': {'used': 5.22, 'total': 127.87}, 'gpu': {'used': 3.18, 'total':
                         11.0}, 'retries': 0, 'oom': 0}
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
00:23:19-191085 INFO     Local URL: http://127.0.0.1:7860/
00:23:19-193086 INFO     API Docs: http://127.0.0.1:7860/docs
00:23:19-195088 INFO     Initializing middleware
00:23:19-512371 INFO     [AgentScheduler] Task queue is empty
00:23:19-514373 INFO     [AgentScheduler] Registering APIs
00:23:20-284060 INFO     Startup time: 352.9s (torch=10.9s gradio=7.1s libraries=15.9s vae=0.2s models=9.2s
                         codeformer=1.1s gfpgan=0.2s scripts=50.9s upscalers=0.2s onchange=0.5s ui=254.8s launch=0.8s
                         scripts app_started_callback=0.5s checkpoint=0.6s)

### Version Platform Description

SEAIT // Firefox 
![image](https://github.com/vladmandic/automatic/assets/113844207/fd9a9956-e582-4d8a-bf4a-e65525775c80)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i don't see any issues with the repo itself. the message you've quoted comes from SEAT, not from this repo - so report issue there.

**Comment by Aurety** [comment]
Thanks ! I tried without the SEAIT launcher and it works !
