### ISSUE TITLE
[Feature]: Option to prefix LoRAs/Lycos.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1400]
### Feature description

It'd be nice to have an option where LoRAs and Lycos are added to the start of the prompt, rather than the end.
This is just a QoL feature, since I tend to forget to remove them when genning new prompts. :-P

### Version Platform Description

n/a

**Comment by vladmandic** [comment]
not planned as location of lora does not have any impact on generated text (it would if we're talking about activation keyword)
