### ISSUE TITLE
[Issue]: --autolaunch webui starts too early.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1404]
### Issue Description

This has been fixed in past commits, but in 1afb7c6c the bug is back. Essentially, when using `--autolaunch`, the webpage is started too early, before the backend is completely loaded.

![image](https://github.com/vladmandic/automatic/assets/1969381/db65ef1e-4a29-438b-a342-aa64d54859a6)

### Version Platform Description

1afb7c6c, win10, chrome.

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
its not back, its different as i've decoupled model loading from ui startup. autolaunch starts after ui startup and all extensions (before it was starting after gradio startup and if extensions were still adding elements, it caused churn).
i don't want to delay it until model is loaded.

if you have a suggestion, let me know, otherwise this is pretty much as-expected.

**Comment by brknsoul** [comment]
Personally, I didn't see a problem with the UI starting after models were loaded. But you're the coder, you'd know better. ;-)

**Comment by vladmandic** [comment]
models are no longer loaded as part of startup itself, they are loaded when first required (which happens to be when quicksetting is being read, but that's another story).
there is a valid scenario where i might want to start ui without loaded model.

regarding progress bar, they actualy work, but fastest way to load a model if via memory map, so you don't see it in progress.
if you set model loading type to streaming, it would show progress bar exactly.

and yeah, i might add one final "ready" message :)

**Comment by vladmandic** [comment]
ok, i've finally managed to finish what i wanted. now in settings you have option to auto-load model (in which case startup sequence will wait for model and autolaunch will execute at the very end) or not auto-load model at all, in which it will be loaded first time you use it (e.g. when you press generate).
