### ISSUE TITLE
[Issue]: sd-webui-cutoff extension doesn't work with Full Parser

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1405]
### Issue Description

The extension https://github.com/hnmr293/sd-webui-cutoff doesn't seem to work when the Parser is set to Full.

According to https://github.com/hnmr293/sd-webui-cutoff/issues/19 one has to set the parser to A1111 for the extension to function.

Would it be possible to get this extension functioning when using the Full Parser?

### Version Platform Description

1afb7c6c, win10, chrome

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
maybe, but report it to extension owner.
and use correct template - this is extension issue, so use extension template. marking this as invalid.

**Comment by brknsoul** [comment]
Ok, created correct issue.
https://github.com/vladmandic/automatic/issues/1407
