### ISSUE TITLE
[Extension]: sd-webui-cutoff doesn't function when Parser set to Full.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1407]
### Issue Description

The extension https://github.com/hnmr293/sd-webui-cutoff doesn't seem to work when the Parser is set to Full.

According to https://github.com/hnmr293/sd-webui-cutoff/issues/19 one has to set the parser to A1111 for the extension to function.

### Version Platform Description

https://github.com/vladmandic/automatic/commit/1afb7c6ca86c1e154f811e61da3f7c5ce0ae867f, win10, chrome

### URL link of the extension

https://github.com/hnmr293/sd-webui-cutoff

### URL link of the issue reported in the extension repository

https://github.com/hnmr293/sd-webui-cutoff/issues/19

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
thanks for the link to upstream, i've provided my comments there and i'm wiling to engage with author.

**Comment by Aptronymist** [comment]
Ah! That explains it.

**Comment by vladmandic** [comment]
original extension does not appear to be maintained, but there is a fork that works just fine and has several nice new features, so closing this issue.
fork is: <https://github.com/pmcculler/sd-webui-cutoff-in-prompt>
