### ISSUE TITLE
[Issue]: Weird behavior of ControlNet recently

### ISSUE THREAD

**Issue by dchatel** [vladmandic/automatic#1409]
### Issue Description

Sadly, I'm not sure when this happened, but since maybe a week or two, my ControlNet UI in vladmandic ui looks like this:
https://imgur.com/a/7TJf1Y6

Is this normal and if not any idea why this is happening or how to fix it?

### Version Platform Description

05:20:15-203882 INFO     Starting SD.Next
05:20:15-210688 INFO     Python 3.10.9 on Windows
05:20:15-240476 INFO     Version: 1afb7c6c Mon Jun 12 14:11:24 2023 -0400
05:20:15-553149 INFO     Updating main repository
05:20:17-481404 ERROR    Error running git: . / pull origin master --autostash --rebase --force
05:20:17-482404 ERROR    Local changes detected: check log for details: G:\ai\automatic\sdnext.log
05:20:17-504404 INFO     Upgraded to version: 1afb7c6c Mon Jun 12 14:11:24 2023 -0400
05:20:17-507404 INFO     nVidia CUDA toolkit detected
05:20:18-587525 INFO     Torch 2.0.0+cu118
05:20:18-606524 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8901
05:20:18-608525 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
05:20:18-713525 INFO     Verifying requirements
05:20:18-727524 INFO     Verifying packages
05:20:18-728524 INFO     Installing repositories
05:20:21-303495 INFO     Installing submodules
05:20:21-909446 ERROR    Error running git: None / submodule
05:20:21-911447 WARNING  Attempting repository recover
05:20:23-683663 INFO     Continuing setup
05:20:24-135663 INFO     Updating submodules
05:20:57-151646 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR',
                         'a1111-sd-webui-tagcomplete', 'adetailer', 'SD-CN-Animation', 'sd-webui-supermerger',
                         'stable-diffusion-webui-embedding-merge', 'stable-diffusion-webui-model-toolkit',
                         'ultimate-upscale-for-automatic1111', 'vid-faceswap']

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
and that is an issue how?
if you're unsure, ask in discussions first.
yes, controlnet is styled.
and yes, it looks better with some themes than other.
but i don't see an issue here.
