### ISSUE TITLE
[Issue]: Extension tabs are broken

### ISSUE THREAD

**Issue by ke1ne** [vladmandic/automatic#141]
### Issue Description

Some extensions are having tabs at the bottom of txt2img interface (instead of being regular tabs):
![image](https://user-images.githubusercontent.com/8934421/232165388-53d5f108-c5e2-413b-b875-02a9f2aa6212.png)

And some of tabs are not showing at all.

### Version Platform Description

Version: b28b7c7a Fri Apr 14 17:50:19 2023 -0400
Windows 11, Chrome 112

**Comment by vladmandic** [comment]
Can you specify exactly which extension should be a seprate tab (and maybe a screenshot of a correct placement)?
ControlNet was designed to be this way and I'm not familiar with Model Keyword at all.

**Comment by ke1ne** [comment]
Oh, I didn't use ControlNET previously, so didn't now that, sorry.

I was too quick during the reporting.
Basically, it works creepy with a custom data directory `--data-dir=data`

I've tried these ones:
1. https://github.com/mix1009/model-keyword (had to be "integrated" like on the screenshot, but didn't open)
2. https://github.com/CurtisDS/sd-model-preview-xd (had to create a tab on top, but didn't, with no error messages)
3. https://github.com/imrayya/stable-diffusion-webui-Prompt_Generator (had to create a tab on top, but didn't, with no error messages)

With default data paths, they're working better:
1. model-keyword (works ok)
2. sd-model-preview-xd (looking for the automatic/embeddings dir and crashes if can't find it)
3. stable-diffusion-webui-Prompt_Generator (works ok)

**Comment by vladmandic** [comment]
Yeah, thats not surprising. Quite a few places in the code don't check for "rehosted" data dir. I'm keeping that option for compatibility only, but would not recommend to use it.

**Comment by ke1ne** [comment]
> Yeah, thats not surprising. Quite a few places in the code don't check for "rehosted" data dir. I'm keeping that option for compatibility only, but would not recommend to use it.

Yea, got it. I will use paths set via UI or default ones. Some extensions are having hard-coded values (crazy, huh), so it's more simple then debug them one by one.

Thank you for the cool fork
