### ISSUE TITLE
[Feature]: Expanded System Info benchmarking for optimal performance out of the box

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#1415]
### Feature description

I (humbly?) propose an extra mode for the System Info benchmarking.

A mode that will iterate through each of the cross-attention optimization methods available (excluding xformers if not installed), including sub-quad with some reasonable ranges of settings. This will allow any user to fire up the benchmark and after it finishes, they should know what the best settings they could use are. 

Some additional analysis in the reporting to indicate the "best" methods, such as fastest (it/s), largest batch size, etc. would also be useful, say a color highlight. Sub-quadratic is slightly more complex due to the 3 additional settings, but say combinations of 128-1024 for each of the two chunk sizes (that don't need to be the same), and then 60-90+0 (disabled) for threshold, and would obviously take more time but again, that's time an automated test is spending, not a user having to manually adjust those settings and benchmark again.

I don't think this would require much effort as it's just looping through the same tests after making one change (though the tests could expand perhaps), and would additionally be an excellent thing to offer on the first run after install, so right out of the box any user could have an optimized setup for their particular hardware/software/OS combo, rather than have to do their own testing and evaluation, or run with the defaults when they could have better performance. A "Apply Best Settings" button would be icing on the cake.

I think this could easily reduce support issues, and at the very least, be a feature to make other webuis envious.

Additionally, if settings such as 'channels last' and 'cuDNN benchmark' can be activated dynamically, which I don't know, those could also come into play.

In time this could be expanded to even include other integrated options such as ToMe and Minimum Sigma, though the user might need to be involved (xyz plot?) as that would have a visual/quality impact.

**Comment by vladmandic** [comment]
nice idea, but...
changing cross-optimization on the fly is flaky at best, only way to get quality results is server restarts in-between.
and for largest batch sizes or resolutions, its even worse as torch frequently looses track of allocations when it gets into oom situation so it never properly recovers.

all-in-all, if someone wants to do a script that does this using api endpoints, great (and yes, you can use shutdown endpoint to stop server in-between attempts), but otherwise, this is going to sit here.

**Comment by vladmandic** [comment]
closing as not planned in-product as to gather reliable results, it requires server restarts between runs.
