### ISSUE TITLE
[Feature]: Clear VRAM button

### ISSUE THREAD

**Issue by tripletto** [vladmandic/automatic#1416]
### Feature description

Once in a while, after having (too) much fun with stable diffusion, I get an out of memory message, especially while inpainting. After restarting everything is fine again and the operation that failed before succeeds.

I don't know how many people run into those kind of VRAM problems but I if possible and relevant, I propose a manual gc / clear VRAM button.

Seems icky I guess?!
https://stackoverflow.com/questions/57496285/why-is-the-memory-in-gpu-still-in-use-after-clearing-the-object

<pre>OutOfMemoryError: CUDA out of memory. Tried to allocate 768.00 MiB (GPU 0; 8.00 GiB total capacity; 6.23 GiB already
allocated; 189.91 MiB free; 6.56 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try
setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[Mem] rss: 7.663 GB, vms: 16.257 GB
[VRAM] free: 0.203 GB, total: 8.000 GB</pre>

### Version Platform Description

Windows 10
RTX 3060 TI 8 GB

"disable_gc": true (I know...)

19:17:44-443832 INFO     Python 3.10.6 on Windows
19:17:44-477564 INFO     Version: 1d9e490e Tue Jun 13 12:22:39 2023 -0400
19:17:44-763239 INFO     Latest published version: cb71d05d98075d7bdbc9924f0c1e53377c675314 2023-06-13T17:08:42Z
19:17:44-767807 INFO     nVidia CUDA toolkit detected
19:17:46-169018 INFO     Torch 2.0.1+cu118
19:17:46-189376 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
19:17:46-191369 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 Ti VRAM 8192 Arch (8, 6) Cores 38

**Comment by Aptronymist** [comment]
> ### Feature description
> Once in a while, after having (too) much fun with stable diffusion, I get an out of memory message, especially while inpainting. After restarting everything is fine again and the operation that failed before succeeds.
> 
> I don't know how many people run into those kind of VRAM problems but I if possible and relevant, I propose a manual gc / clear VRAM button.
> 
It already happens all the time, as I understand it there isn't anything that can really be done about that. Perhaps unload and reload your model to see if that frees some up?

**Comment by vladmandic** [comment]
@Aptronymist is right, there is not much more that can be done other than what's already in the app.
Torch does not have option to say "release all and let me start from scratch", if it did, i'd be happy to use it and reload model as needed. And GC collects only what torch believes is unreferenced - and there is no way to see or free its internal references.
And even if reference is freed, it sometimes does not mark object as available for GC as it think it may be needed by something in the future. Again, no application control over it.

As much as i'd like to do something like this, right now this is not feasible so closing.
