### ISSUE TITLE
[Issue]: Missing DPM++ 2M SDE Karras

### ISSUE THREAD

**Issue by tetsuoo-online** [vladmandic/automatic#1419]
### Issue Description

Sampler DPM++ 2M SDE Karras is nowhere to be seen, I checked in the settings as well. Is that a deliberate choice ?

### Version Platform Description

Version: 8354b7c6 Mon May 29 15:42:24 2023 -0400
Windows 10
Chrome

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i'm not sure where you've looked, but its definitely there - it was never removed.
only recent work on samplers was to add a new one: dpm++ 2m sde (non-karras)

**Comment by tetsuoo-online** [comment]
I looked into the Samplers Settings, the Karras one was not there. I thought that maybe this sampler doesn't exist after all, but it was in Automatic1111
![image](https://github.com/vladmandic/automatic/assets/45845308/ebda52bf-55b3-4703-8f7f-01034b8daba4)

**Comment by tetsuoo-online** [comment]
> Have you checked #1229?

That looks quite confusing but thanks, I will try

**Comment by tetsuoo-online** [comment]
> Have you checked #1229?

git pull didn't help, it's already up to date apparently.
I tried to add --upgrade in webui.bat and it got upset lol then deleted.

Anyway... I'm tired with all this, forget about the damn sampler, forget everything. Delete this post lol

**Comment by snakebite1980** [comment]
download code from https://github.com/crowsonkb/k-diffusion and replace it in your sd folder, you will see the missing sampling option.
the reason is repo in sd webui is a fork(https://github.com/brkirch/k-diffusion.git)

**Comment by Nobelgraphic** [comment]
select karras in the "schedule type" beside the "sampling method"

**Comment by tetsuoo-online** [comment]
> select karras in the "schedule type" beside the "sampling method"

Coçme on man that was 1 year ago haha
