### ISSUE TITLE
[Issue]: Dict model not loading in correct order

### ISSUE THREAD

**Issue by BanJaxe42** [vladmandic/automatic#1423]
### Issue Description

When using sd_model_dict in XYZ grid, checkpoint model is loaded first then dict model second, which is backwards (If I understand correctly).

First image is XYZ grid with just X = checkpoint model, no Y set, normal dictionary settings
https://i.imgur.com/QQ0zFCZ.jpeg

Second image is same as above with added Y is Dict = Deliberate_v2 model
https://i.imgur.com/v5XvyQ8.jpeg

Log of second image generation, you can see it is loading the checkpoint model first then the dict model second (deliberate_v2):

> Loading weights: C:\AI\stable-diffusion-webui\models\Stable-diffusion\Realistic\deliberate_v2.safetensors ━━━━ 0.0… -:-…
>                                                                                                                GB
> LatentDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> Loading weights: C:\AI\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt ━━━━━━╺━━━ 210.6/334… 0:00:00
>                                                                                                       MB
> 100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.65it/s]
> Loading weights: C:\AI\stable-diffusion-webui\models\Stable-diffusion\Anime\lysergic_V20.safetensors ━━━━━ 0.0/5… -:--:…
>                                                                                                            GB
> LatentDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> Loading weights: C:\AI\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt ━━━━━━╺━━━ 210.6/334… 0:00:00
>                                                                                                       MB
> Loading weights: C:\AI\stable-diffusion-webui\models\Stable-diffusion\Realistic\deliberate_v2.safetensors ━━━━ 0.0… -:-…
>                                                                                                                GB
> LatentDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> Loading weights: C:\AI\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt ━━━━━━╺━━━ 210.6/334… 0:00:00
>                                                                                                       MB
> 100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  7.77it/s]
> Loading weights: C:\AI\stable-diffusion-webui\models\Stable-diffusion\Semirealistic\dreamshaper_6BakedVae.safetensors
> LatentDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> Loading weights: C:\AI\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt ━━━━━━╺━━━ 210.6/334… 0:00:00
>                                                                                                       MB
> Loading weights: C:\AI\stable-diffusion-webui\models\Stable-diffusion\Realistic\deliberate_v2.safetensors ━━━━ 0.0… -:-…
>                                                                                                                GB
> LatentDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> Loading weights: C:\AI\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt ━━━━━━╺━━━ 210.6/334… 0:00:00
>                                                                                                       MB
> 100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  7.31it/s]

### Version Platform Description

Windows 11, Firefox 114.0.1, intel i7-12700K, 32GB ram

14:04:04-847677 INFO     Starting SD.Next
14:04:04-853677 INFO     Python 3.10.9 on Windows
14:04:04-894418 INFO     Version: a9f66cb3 Wed Jun 14 12:18:08 2023 +0300
14:04:05-209498 INFO     nVidia CUDA toolkit detected
14:04:08-423148 INFO     Torch 2.0.1+cu118
14:04:08-445268 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
14:04:08-446267 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 Ti VRAM 8192 Arch (8, 6) Cores 38

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
should be fixed now.
