### ISSUE TITLE
[Issue]: Noise seed delta (eta)

### ISSUE THREAD

**Issue by motorist828** [vladmandic/automatic#1426]
### Issue Description

Since the Sub-quadratic problem is solved, I want to report another problem that I found while doing the checks
I don’t know from which update it appeared, but after 05/30/2023, the Noise seed delta (eta) parameter no longer applies to me
ENSD is no longer specified in generated images, although it has been changed in settings

![Screenshot_184](https://github.com/vladmandic/automatic/assets/40582999/31afc170-8a7d-41ea-b3ac-4865272a8b3b)
![Screenshot_183](https://github.com/vladmandic/automatic/assets/40582999/ab037a63-4992-40fa-b95d-28a3d7e4e51b)

### Version Platform Description

Using VENV: D:\neiro\last\automatic\venv
19:58:11-701857 INFO     Starting SD.Next
19:58:11-707858 INFO     Python 3.10.6 on Windows
19:58:11-750607 INFO     Version: 0ddf613b Wed Jun 14 11:22:59 2023 -0400
19:58:12-236500 INFO     Using DirectML Backend
19:58:13-859571 INFO     Torch 2.0.0+cpu
19:58:13-874583 INFO     Torch backend: DirectML (torch-directml 0.2.0.dev230426)
19:58:13-979583 INFO     Torch detected GPU: Radeon RX Vega
19:58:14-120340 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
19:58:14-129338 INFO     Enabled extensions: []
19:58:14-131588 INFO     Verifying requirements
19:58:14-149588 INFO     Verifying packages
19:58:14-151837 INFO     Installing repositories
19:58:17-741024 INFO     Installing submodules
19:58:19-510708 INFO     Updating submodules
19:58:47-112895 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
19:58:47-117394 INFO     Updating Wiki
19:58:47-885859 INFO     Extension preload: 0.0s D:\neiro\last\automatic\extensions-builtin
19:58:47-888108 INFO     Extension preload: 0.0s D:\neiro\last\automatic\extensions
19:58:47-903871 INFO     Server arguments: ['--use-directml', '--medvram', '--autolaunch']
No module 'xformers'. Proceeding without it.
19:58:55-685563 INFO     Libraries loaded
19:58:55-691563 INFO     Using data path: D:\neiro\last\automatic
19:58:55-696074 INFO     Available VAEs: D:\neiro\AMD\stable-diffusion-webui-directml\models\VAE 4
19:58:55-703565 INFO     Available models: D:\neiro\AMD\stable-diffusion-webui-directml\models\Stable-diffusion 8
19:58:59-021124 INFO     ControlNet v1.1.224
ControlNet preprocessor location: D:\neiro\last\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
19:58:59-284868 INFO     ControlNet v1.1.224
Image Browser: ImageReward is not installed, cannot be used.
19:59:00-666138 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
19:59:03-506547 INFO     Local URL: http://127.0.0.1:7860/
19:59:03-508797 INFO     Initializing middleware
19:59:03-693336 INFO     [AgentScheduler] Task queue is empty
19:59:03-695574 INFO     [AgentScheduler] Registering APIs
Loading weights: D:\neiro\AMD\stable-diffusion-webui-directml\models\Stable-diffusion\Based64mix-V3.safetensors - 0… -…
                                                                                                                  GB
19:59:05-160552 INFO     Torch override dtype: no-half set
19:59:05-162054 INFO     Torch override VAE dtype: no-half set
19:59:05-164301 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: D:\neiro\AMD\stable-diffusion-webui-directml\models\VAE\vae-ft-mse-840000-ema-pruned.ckpt - - 21… 0:0…
                                                                                                               MB
19:59:06-762740 INFO     Applying sub-quadratic cross attention optimization
19:59:06-773993 INFO     Embeddings: loaded=0 skipped=0
19:59:06-787491 INFO     Model loaded in 2.5s (load=0.9s create=0.6s apply=0.7s vae=0.3s)
19:59:07-088245 INFO     Model load finished: {'ram': {'used': 7.11, 'total': 31.94}}
19:59:07-216503 INFO     Startup time: 19.3s (torch=3.8s gradio=2.3s libraries=1.7s scripts=4.8s onchange=0.2s ui=2.6s
                         launch=0.3s app-started=0.5s checkpoint=3.2s)
19:59:07-225504 INFO     Launching browser
19:59:58-390246 INFO     Settings changed: 2 ['show_progress_every_n_steps', 'show_progress_type']
100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:48<00:00,  2.01s/it]
20:01:24-340712 INFO     Settings changed: 1 ['eta_noise_seed_delta']
100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:42<00:00,  1.78s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:18<00:00,  1.29it/s]

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by motorist828** [comment]
It still doesn't work
In addition, I can’t repeat past generations, even those where ENSD has not been changed
I don’t know what this is connected with, maybe there is some difference in my settings
![Screenshot_186](https://github.com/vladmandic/automatic/assets/40582999/0dae0509-5920-4a84-abc8-e1fd01c12867)
![Screenshot_185](https://github.com/vladmandic/automatic/assets/40582999/7aada629-9be5-4f85-a301-5fc34c1e021f)

**Comment by landrasss** [comment]
I came to comment the same, since the last update I can't repeat past generations too.

**Comment by brunogcar** [comment]
tested diferent models 1,5 an NAI based,  cant reproduce past generations
Noise seed delta (eta) does change images (subtle) on my tests, but indeed it does not record on  metadata anymore,  but it is not recent, cant determine from my images when it changed


Version: 9334b2f2 Wed Jun 14 13:54:23 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28

arch: AMD64
cpu: AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.6

**Comment by motorist828** [comment]
It looks like there is a problem not related to ensd
I have experimented with version f9a71a1a and 9334b2f, completely default settings, custom extensions are disabled
When using the standard model v1-5-pruned, the images on different versions were the same
Using a different model, I got a difference, but only in some images
I don’t understand how this is possible, but some seeds work differently on different versions
![Screenshot_195](https://github.com/vladmandic/automatic/assets/40582999/9edcb62f-471e-449a-a229-3f12a3c56e37)
![Screenshot_194](https://github.com/vladmandic/automatic/assets/40582999/5f0e0fe1-fa18-4ca1-9d6d-1b12777b7d77)
![Screenshot_193](https://github.com/vladmandic/automatic/assets/40582999/8dfa4272-9f3c-479c-bae0-d1170c166d2f)
![Screenshot_192](https://github.com/vladmandic/automatic/assets/40582999/980db388-f512-490e-8be2-257fd1042f8b)

**Comment by vladmandic** [comment]
a lot of server settings have changed in the past 3 weeks and those have a massive effect on how math operations are done internally. so using default settings means using different settings now and 3 weeks ago. and even if you do use exactly the same settings, there are quite a few new ones.

**Comment by brunogcar** [comment]
8749067510facdde6299775f7695afbac69c6312 fixed for me the problem of not being able to reproduce past generations (kinda)

what vlad said still  applies, although the changes are subtle,  ofc no  2 generations are the same anyway,  while clip skip takes huge effect on images
