### ISSUE TITLE
[Issue]: Fresh install -- error -- cannot load

### ISSUE THREAD

**Issue by Raivshard** [vladmandic/automatic#1428]
### Issue Description

The instant the server finishes loading, the following error appears in the log and then constantly repeats itself

Traceback (most recent call last):
  File "F:\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "F:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1159, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "F:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1146, in validate_inputs
    raise ValueError(
ValueError: An event handler (exif_update_dirs) didn't receive enough input values (needed: 3, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [textbox, textbox, html]
Received inputs:
    []
    
This is a completely fresh install with no user extensions. Tried running in --safe as well

### Version Platform Description

20:55:09-553237 INFO     Starting SD.Next
20:55:09-559458 INFO     Python 3.10.6 on Windows
20:55:09-654184 INFO     Version: 618097da Thu Jun 15 01:19:28 2023 +0300
20:55:10-120360 INFO     nVidia CUDA toolkit detected
20:55:11-587589 INFO     Torch 2.0.1+cu118
20:55:11-606541 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
20:55:11-609532 INFO     Torch detected GPU: NVIDIA GeForce RTX 2070 SUPER VRAM 8192 Arch (7, 5) Cores 40

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
looking through the code, this error happens when image browser extension is trying to read its ui values, but it cannot access them. but that function was last updated ~3 months ago, so i doubt its the new code issue, more likely something went wrong during installation.

can you delete `extensions-builtin/stable-diffusion-webui-images-browser` so the app will reinstall it?

**Comment by Raivshard** [comment]
Yay, it worked! Thanks!
