### ISSUE TITLE
[Issue]: Hires fix saved as default doesn't open params in GUI

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [vladmandic/automatic#1432]
### Issue Description

I have saved GUI defaults with Hires fix enabled. The option is saved and enabled correctly, but the view is not expanded to display the parameters:

![Screenshot 2023-06-15 175605](https://github.com/vladmandic/automatic/assets/52193044/160d9373-82cf-4a27-9e93-01d8d4d561f4)

If I uncheck and then re-select the option, it then displays correctly:

![Screenshot 2023-06-15 175723](https://github.com/vladmandic/automatic/assets/52193044/a931341f-5185-48d7-ae9e-1d031a373e58)

### Version Platform Description

17:50:37-917360 INFO     Python 3.10.6 on Windows
17:50:37-978054 INFO     Version: 618097da Thu Jun 15 01:19:28 2023 +0300
17:50:38-356698 INFO     Updating main repository
17:50:40-883954 INFO     Upgraded to version: ba6f9fb4 Thu Jun 15 10:31:30 2023 -0400
17:50:40-886958 INFO     nVidia CUDA toolkit detected
17:50:42-961224 INFO     Torch 2.0.1+cu118
17:50:42-980009 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
17:50:42-982011 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24563 Arch (8, 9) Cores 128

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by mobilehacker** [comment]
Can confirm, having the same issue.

**Comment by vladmandic** [comment]
todo: loading setting for a value that has associated change event does not trigger change event

**Comment by vladmandic** [comment]
fixed.
