### ISSUE TITLE
[Issue]: Desync of output field

### ISSUE THREAD

**Issue by neuralweights** [vladmandic/automatic#1433]
### Issue Description

This is standard behaviour for ages, there is no version or commit this is related to. Most people probably only use the ui and leave all images in the output folder. I tinker a lot and I have all sorts of animation projects going on, and I manage the files in my output folder with the windows explorer.

This always causes the problem that the generated outputs desync and it is impossible to use the "Send to" function and I have to live without it. Is it possible to "flush" whatever cache the output field has with each generation, so that it is always in sync? If the files are already deleted then it would give an error when sending but otherwise the thumbnail is not the wrong one anymore.

### Version Platform Description

newest, Win10, Chrome

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
if you're talking about txt2img or any of the primary workflows, you generate image(s), it shows up in gallery view, you delete it externally and try to send from the same gallery view - ok, i just did a handler for that, it will log an error in console and transfer blank instead of first available image.

if you're talking about send to from image browser, it would have to be sorted out there.

**Comment by vladmandic** [comment]
It's not "old", it's first available - if the one you've selected is not available. And thats solved.

**Comment by neuralweights** [comment]
Sorry for commenting on this closed bug, but I found out more about it. I was able to conclude that it only happens, if I restart the UI, while staying in the same chrome tab session (= not reloading UI while restarting console).

Not enough knowledge about the part of the code that manages this, I think its pretty complicated (asyncio?) and not many users are affected so I will find ways to work around it

**Comment by vladmandic** [comment]
too many things change if server is restarted (manually or via restart), browser reload is mandatory when doing so.
