### ISSUE TITLE
[Issue]: Checkpoint not loading automatically after change

### ISSUE THREAD

**Issue by dan4ik94** [vladmandic/automatic#1434]
### Issue Description

In the recent versions when I change the checkpoint, the new one doesn't get loaded automatically, I have to click on the "**Unload checkpoint**" button in the settings, then the new one loads normally.

**Expected behavior**: the new checkpoint model loads automatically on change or when you press the Generate button.

**Video demo**: https://streamable.com/dcodet

### Version Platform Description

Python 3.10.10 on Windows
Version: ba6f9fb4 Thu Jun 15 10:31:30 2023 -0400

```
Disabled extensions-builtin: ['sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg',
                         'sd-extension-system-info']

Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-webui-controlnet', 'sd-webui-model-converter', 'SwinIR']

Disabled extensions: ['sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'sd-extension-system-info']

Enabled extensions: ['adetailer', 'canvas-zoom', 'loopback_scaler',
                         'sd-webui-openpose-editor', 'sd-webui-regional-prompter',
                         'stable-diffusion-webui-fix-image-paste']
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
Settings -> Stable diffusion - > Stable Diffusion checkpoint autoload on server start

if its enabled and i change checkpoint in quicksettings, it gets changed immediately.

**Comment by vladmandic** [comment]
its one or the other.
btw, i create a new feature that works just as designed and you create issue that it doesn't work the way you'd like :( 
i wish you referenced that you're using a new feature and you'd like possible further enhancement. but in either case, closing this as not planned.

**Comment by dan4ik94** [comment]
> its one or the other. btw, i create a new feature that works just as designed and you create issue that it doesn't work the way you'd like :( i wish you referenced that you're using a new feature and you'd like possible further enhancement. but in either case, closing this as not planned.

Sorry, I forgot to mention that. Anyway, it's not a big deal, I can reload it manually. Thank you for that feature, it really speed ups the startup.
