### ISSUE TITLE
[Extension]:  sd-webui-prompt-history 

### ISSUE THREAD

**Issue by ronbere** [vladmandic/automatic#1437]
### Issue Description

Can't generate any images with the extension enabled. Works fine without

Version: **71b1532b** Thu Jun 15 23:55:23 2023 +0300
23:21:16-415198 INFO     nVidia CUDA toolkit detected
23:21:17-534064 INFO     Torch 2.0.1+cu118

### Version Platform Description

I'm on Windows11, browser Firefox ( tested on Chrome too)

Using VENV: C:\automatic\venv
23:21:16-147648 INFO     Starting SD.Next
23:21:16-150651 INFO     Python 3.10.9 on Windows
23:21:16-187686 INFO     Version: 71b1532b Thu Jun 15 23:55:23 2023 +0300
23:21:16-415198 INFO     nVidia CUDA toolkit detected
23:21:17-534064 INFO     Torch 2.0.1+cu118
23:21:17-544073 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
23:21:17-545074 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 Ti VRAM 12287 Arch (8, 6) Cores 80
23:21:17-631657 WARNING  Modified files: ['cmd_opts.data_dir/', 'train/templates/mypreset.txt']
23:21:17-665690 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'lora.py', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
23:21:17-672696 INFO     Enabled extensions: ['a1111-mini-paint', 'a1111-sd-webui-tagcomplete', 'adetailer',
                         'batch-face-swap', 'canvas-zoom', 'deforum-for-automatic1111-webui', 'model_preset_manager',
                         'sd-webui-aspect-ratio-helper', 'sd-webui-faceswap', 'sd-webui-inpaint-anything',
                         'sd-webui-photopea-embed', 'sd-webui-prompt-history', 'sd_dreambooth_extension',
                         'stable-diffusion-webui-promptgen', 'stable-diffusion-webui-Prompt_Generator',
                         'stable-diffusion-webui-two-shot', 'Styles-Editor', 'ultimate-upscale-for-automatic1111']
23:21:17-681704 INFO     Verifying requirements
23:21:17-689712 WARNING  Package wrong version: accelerate 0.19.0 required 0.20.3
23:21:17-690712 INFO     Installing package: accelerate==0.20.3
23:21:19-805249 WARNING  Package wrong version: transformers 4.29.2 required 4.26.1
23:21:19-806250 INFO     Installing package: transformers==4.26.1
23:21:27-548705 INFO     Verifying packages
23:21:27-549706 INFO     Installing repositories
23:21:30-295097 INFO     Installing submodules
23:21:31-808758 INFO     Updating submodules
23:22:26-738189 INFO     Extension installed packages: sd_dreambooth_extension ['transformers==4.29.2',
                         'accelerate==0.19.0']
23:22:30-777939 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'lora.py', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR',
                         'a1111-mini-paint', 'a1111-sd-webui-tagcomplete', 'adetailer', 'batch-face-swap',
                         'canvas-zoom', 'deforum-for-automatic1111-webui', 'model_preset_manager',
                         'sd-webui-aspect-ratio-helper', 'sd-webui-faceswap', 'sd-webui-inpaint-anything',
                         'sd-webui-photopea-embed', 'sd-webui-prompt-history', 'sd_dreambooth_extension',
                         'stable-diffusion-webui-promptgen', 'stable-diffusion-webui-Prompt_Generator',
                         'stable-diffusion-webui-two-shot', 'Styles-Editor', 'ultimate-upscale-for-automatic1111']
23:22:30-779940 INFO     Updating Wiki
23:22:31-426855 INFO     Extension preload: 0.0s C:\automatic\extensions-builtin
23:22:31-428856 INFO     Extension preload: 0.0s C:\automatic\extensions
23:22:31-441868 INFO     Server arguments: []
23:22:36-280481 INFO     Libraries loaded
23:22:36-282482 INFO     Using data path: C:\automatic
23:22:36-288488 INFO     Available VAEs: F:\Telechargements\SUPER SD 2.0 Dependencies\stable-diffusion-webui\models\VAE
                         5
23:22:36-334530 INFO     Available models: F:\Telechargements\SUPER SD 2.0
                         Dependencies\stable-diffusion-webui\models\Stable-diffusion 182
23:22:38-667796 INFO     ControlNet v1.1.224
ControlNet preprocessor location: D:\automatic\extensions-builtin\sd-webui-controlnet\models
23:22:38-775398 INFO     ControlNet v1.1.224
Image Browser: ImageReward is not installed, cannot be used.
[-] ADetailer initialized. version: 23.6.2, num models: 8
23:22:41-019525 INFO     Libraries loaded
2023-06-15 23:22:41,398 - FaceSwap - INFO - FaceSwap v0.0.7
2023-06-15 23:22:41,398 - FaceSwap - INFO - FaceSwap v0.0.7
Loading weights: F:\Telechargements\SUPER SD 2.0 Dependencies\stable-diffusion-webui\models\Stable-diffusion\realisti…
23:22:41-809290 INFO     Torch override dtype: no-half set
23:22:41-810291 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: F:\Telechargements\SUPER SD 2.0 Dependencies\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema…
23:22:44-789392 INFO     Applying xformers cross attention optimization
23:22:44-848948 INFO     Embeddings: loaded=49 skipped=24
23:22:44-855954 INFO     Model loaded in 3.4s (load=0.3s create=0.6s apply=0.9s vae=0.3s move=1.1s embeddings=0.1s)
23:22:45-119335 INFO     Model load finished: {'ram': {'used': 3.4, 'total': 31.94}, 'gpu': {'used': 5.31, 'total':
                         12.0}, 'retries': 0, 'oom': 0} cached=0
23:22:46-233391 INFO     Loading UI theme: name=gradio/default style=Auto
*Deforum ControlNet support: enabled*
23:22:47-497079 INFO     Available models: F:\Telechargements\SUPER SD 2.0
                         Dependencies\stable-diffusion-webui\models\Stable-diffusion 182
CUDA SETUP: Loading binary C:\automatic\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
23:22:49-889964 INFO     Local URL: http://127.0.0.1:7860/
23:22:49-890965 INFO     Initializing middleware
23:22:50-039107 INFO     [AgentScheduler] Task queue is empty
23:22:50-040108 INFO     [AgentScheduler] Registering APIs
23:22:51-368569 INFO     Startup time: 19.9s (torch=2.9s gradio=0.9s libraries=1.1s scripts=9.6s onchange=0.2s ui=3.4s
                         launch=0.2s app-started=0.8s checkpoint=0.7s)
Loading weights: D:\automatic\models\Lora\DocBrown.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/37.9 MB -:--:--
100%|█████████████████████████████████████████████████████████████████████████████████| 20/20 [00:12<00:00,  1.58it/s]
23:26:21-317594 ERROR    Exception: module 'modules.images' has no attribute 'save_image_with_geninfo'
23:26:21-318594 ERROR    Arguments: args=('task(zgv49of3sk1e12x)', '(masterpiece), raw photography of DocBrown smoking
                         a weed cigarette with a lei around his neck and wearing a lei around his neck and a shirt with
                         a flower on it, (smoking:0.999), (smoke:0.998), (cigarette:0.994), (blurry:0.991),
                         (blurry_background:0.961), (1boy:0.953), (depth_of_field:0.934), (male_focus:0.927),
                         (holding_cigarette:0.911), (old:0.856), (old_man:0.850), (solo:0.815), (cigar:0.769), highly
                         detailed, 8k, photorealistic portrait, bright studio setting, studio lighting, crisp quality
                         and light reflections, <lora:DocBrown:0.7>, detailed skin texture, (blush:0.5),
                         (goosebumps:0.5), subsurface scattering', '((((ugly)))), (((deformed))), (blurry), ((bad
                         anatomy)), ((ugly)), ((disfigured)), ((poorly drawn face)), (mutation), (mutated), (extra
                         limb), (poorly drawn hands), ((missing limbs)), (blurry), floating limbs, (disconnected
                         limbs), (malformed hands), blur, out of focus, ((deformed face))
23:26:21-333111 ERROR    gradio call: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────╮
│ C:\automatic\modules\call_queue.py:34 in f                                                                          │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ C:\automatic\modules\txt2img.py:56 in txt2img                                                                       │
│                                                                                                                     │
│   55 │   if processed is None:                                                                                      │
│ ❱ 56 │   │   processed = processing.process_images(p)                                                               │
│   57 │   p.close()                                                                                                  │
│                                                                                                                     │
│ C:\automatic\extensions\sd-webui-prompt-history\lib_history\image_process_hijacker.py:29 in process_images          │
│                                                                                                                     │
│   28 │   img = res.images[0]                                                                                        │
│ ❱ 29 │   images.save_image_with_geninfo(img, None, os.path.join(global_state.history_path, f"                       │
│   30 │   # add result to history                                                                                    │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'modules.images' has no attribute 'save_image_with_geninfo'

### URL link of the extension

https://github.com/namkazt/sd-webui-prompt-history

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
extension is attempting to use private function `modules.images.save_image_with_geninfo` which should not be directly accessed by extensions. instead extensions should use well defined `modules.images.save_image`.
if extensions are free to use any method from the app, there would be no possibility to change anything ever in the app.
