### ISSUE TITLE
[Feature]: Highly scalable web server

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#1441]
### Feature description

current app stack for http handling
1. uses `Gradio` which internally
2. uses `FastApi` which is
3. based on `Starlette` which 
4. uses default `Uvicorn` setup which is
5. based on `AsyncIO` loop and
6. `H11` as HTTP protocol parser

which is ok as default, but using standard gradio app `launch()` method does not allow passing any of the config parameters to underlying layers (with exception of some fastapi params, but that is limited).
and once underlying layers are created/started, their config cannot be modified.

goal for this feature request is to:
a) expose `uvicorn` itself to allow for alternative handlers, loops, etc.
b) enable alternative servers such as `hypercorn`

**Comment by vladmandic** [comment]
currently work is limited to `--api-only` mode until its finalized and then it can be ported to full ui mode as well  
note: this is highly experimental - should not be used without understanding the code and its implications  

to enable different `uvicorn` loops/handlers, install optional modules: `pip install httptools uvloop`
and switch handlers in `modules/api.py`:
- `loop=uvloop` instead of `asyncio` (default)  
- `http=httptools` instead of `h11` (default)  

to switch to `hypercorn`, install it manually: `pip install hypercorn`
and change `modules/api.py:launch()` to call `launch_hypercorn()`

**Comment by vladmandic** [comment]
common failure with the default setup  
app fails due to unexpected http connection close with 
> h11._util.LocalProtocolError: Can't send data when our state is ERROR

future possible ideas: restart loop periodically after n handled requests to avoid python memory leaks

**Comment by vladmandic** [comment]
modularized code to `modules/server.py`:
- `uvicorn`: runs in thread, supports all loops and protocol handlers, full thread monitoring and restart capabilities
- `hypercorn`: runs in thread for trio loop and in main thread for other loop types, limited monitoring and no restart capabilities

**Comment by montyanderson** [comment]
I was able to stop the errors by setting the uvicorn timeout via an environment variable.

```
UVICORN_TIMEOUT_KEEP_ALIVE=5000
```
