### ISSUE TITLE
[Feature]: Expand generation parameters text files with Details about IMG2IMG and Outpainting

### ISSUE THREAD

**Issue by StableInfo** [vladmandic/automatic#1442]
### Feature description

Actually, the text files only contain info about positive and negative prompt, steps, sampler, seed etc.; and denoising.
No information about the name of the input image (just the name), 
no information about outpaining parameters (sides, pixels, falloff exponent, color variation etc)
No information about ULTIMATE SD UPSCALE, which is a tool we use a lot. (Name of input file, name of upscaler etc)

### Version Platform Description

Firefox
and:
![image](https://github.com/vladmandic/automatic/assets/136593585/5b1ab6b2-e257-4763-b328-7a0bc800ae3e)

**Comment by vladmandic** [comment]
be explicit on exact parameters you'd want to include and where are they present.
if parameter is present in the extension (such as ultimate sd upscale), then its fully up to extension to ammend info text with extra params.
and regarding others, i don't know what is "sides" or "pixels".

**Comment by StableInfo** [comment]
I understand, 
but outpainting is working fine for me, is there a better tool? I dont want it to be replaced if there is no alternative working on img2img like it does.
What about adding the input image info into the text file? Interesting idea or too complicated?

**Comment by StableInfo** [comment]
I will to the suggestion, also included the controlnet image input data.
For example, I have been using the control net input + lama method (its OUTPAINING actually), it uses no prompt, just the image and it performs good outpaining.
The problem is when I open the generated text parameters, All i see is some txt2img parameters and no info about the input controlnet image that led to my output.
For example, here is my text file:
`Steps: 150, Sampler: DPM++ SDE Karras, CFG scale: 11, Seed: 2350172763, Size: 616x1416, Model hash: 4199bcdd14, Model: revAnimated_v122, VAE: vae-ft-mse-840000-ema-pruned, Clip skip: 2, ControlNet 0: "preprocessor: inpaint_only+lama, model: control_v11p_sd15_inpaint [ebff9138], weight: 1, starting/ending: (0, 1), resize mode: Resize and Fill, pixel perfect: False, control mode: ControlNet is more important, preprocessor params: (512, 64, 64)"`

The image associated with there parameters cannot be reproduced if I dont have info about the input image. I mean: this text file is of no use.

Another solution: maybe include an EXTRA text file? with an option "create text file data related to the inputed image for controlnet in t2i/i2i" and "create text file data related to the inputed image for i2i",
Format name of the file : 
[num_t2i_controlnet_inputimage_seedOfTheOutputImage]
[num_i2i_controlnet_inputimage_seedOfTheOutputImage]
[num_i2i_inputimage_seedOfTheOutputImage]
could combine the info about i2i input image and i2i controle net input image into one file.

**Comment by vladmandic** [comment]
@StableInfo i through i was clear about that - if information is about extension, then it is on extension to append that info to infotext. That capability exists and can be used by any extension - and what you're asking is fully valid, but must be implemented in the extension itself - so report it there.

**Comment by StableInfo** [comment]
oh so controlnet is considered an extension aswell, did not realize.
Fine then, I am talking about img2img in general, it could be good to have the inputed image png info inserted into the outputed image file info, or have a checkbox option "Generate an extra file with info about the inputed image when using img2img"
the extra text file will be called:          [numOfCurrentOutputIpage_i2i_inputimageInfo_seedOfTheOutputImage]    
It will contain: the PNG info of the inputed image, and if it does not contain png info, then it will be empty.

Reminder PNG info are found on "process image" -> parameters + full metadata

**Comment by vladmandic** [comment]
adding entire metadata of previous image is a no-go as that would soon degrade into full chain where metadata is huge and becomes useless.
but yes, i agree that some metadata about input image should be included - right now there is none at all.
i'll take a look at it.

**Comment by StableInfo** [comment]
Hello again, and thanks for your interactions.
I am doing some outpaining experiments, (I was not entirely satisfied with the controlnet llama method), so I went back to poorman outpaining and outpaining mk2, I am trying multiple experiments and its really painful to obtain exact similar TEXT files for every image, eventhough the images are different and every one of them has different outpaining parameters, for instance: different "Fall-off exponent (lower=higher detail)" and different "color variation"

Can I modify the UI myself to make the text file generation do that and include them in the text file? I never coded the webUI, just have some basic coding experience, maybe you can orient me to some files I should open with notepadd++ aand see what lines of code I could modify?

**Comment by vladmandic** [comment]
> Can I modify the UI myself to make the text file generation do that and include them in the text file? I never coded the webUI, just have some basic coding experience, maybe you can orient me to some files I should open with notepadd++ aand see what lines of code I could modify?

I can, but this is one of the most messy/complicated parts of the code as its not as simple as it sounds as params are carried over between multiple functions and use different formats in between.

**Comment by StableInfo** [comment]
Hello again @vladmandic , indeed it seems very complicated, I am trying to learn the code now, maybe I will be able to implement it myself if I learn enough (one day) and help you in the project of course. I will have quick question please:
So in order to understand the code I started searching the "text" of all the files of the vladUI installation, I started with the first text I encounter when I open the UI ("Prompt (press Ctrl+3)
-> This lead me to a file ui.py that contained the function create_ui(
-> I searched that and found the file api.py which contains (ui.create_ui(..)
-> The I found those 2 text "ui.create.." inside the class "Api"
-> I went and searched "Api" and got too many results.
I am looking for a line of code inside some file where the "object" ui is created out of the class "Api", but I cant find it, so I am stuck in understanding the full code,I dont know where it all starts.
Can you guide me further here? Just a tip or 2. Thanks

**Comment by vladmandic** [comment]
you're right that ui.create_ui() is the entry point, but going to api.py is wrong direction, that is just "fake" ui created by api so code works even when headless. create_ui is also triggered directly from webui.py, that is the main entry point.
if you want to trace down gen info params, you'd go webui.py->ui.py->img2img.py->processing.py and land at the function called `create_infotext`.

but at the end, what information about init image would you capture? cannot capture entire image, that is nonsense (and it physically doesn't fit in metadata). and filename of input image doesn't exist as soon as soon as you load it into ui, its pixels, its no longer a file - so there is no name (except when you're running batch from folder, but that is a different story).

**Comment by StableInfo** [comment]
Hey, 
Well I would like to save:
- the name of the file used as input in img2img.
- the metadata (png info) of the input image IF IT HAS that, 
and print that info at the end of the text file generated after each img2img, 
Possibly, the name of the current script used (the ones in the top down menu at the bottom of the tab img2img).

**Comment by vladmandic** [comment]
the thing is, by the time you reach create_infotext, none of that information exists.
name of script is useful, but it must be set by script itself as if you're inside processing.py, you don't know what called it.
and image is completely abstracted, only thing you have at that time is pixel data. and if image was uploaded via ui, there never was filename captured to start with.
and capturing metadata of input image is just whatever. doesn't do much, only bloats overall metadata - and there is a size limit.

**Comment by StableInfo** [comment]
So there is no way to capture the image data or the script used before it reaches processing.py?
As for the image metadata, I meant mostly the png info related to SD, not the general metadata that we find in irl image (name of phone, localization etc..), why would there be a limit? 

I find it useful when I am doing lot of outpaining or lot of inpaining, there is NO ONE in this worlds that was able to make a proper incredible tutorial /guide on the img2img processes because the whole community are mostly doign a trial and error? (and when they want to check what was the best setting that made the best output in img2img, they cant know because they dont have the info related to the input image not the precise script used, does that make sens?)

**Comment by StableInfo** [comment]
Okay, I am not sure I am understanding it all since I did not read all the code yet.
Since you are leaving and will be busy a bit (read that in another post) @vladmandic , do you mind making me a little paragraphe summary explaining the code that I could come read and read when I am trying to understand the code? So you said that I was in the right path in thinking ui.create_ui()  is the entry point? What happens next? 

My wish is doubled:
- I wish I can create some extension some day and even help here maybe.
-  I wish to be able to have a program (.exe) that I double click, enter a text, and press generate, it means I need to know how to "connect" my generate button to ui.create_ui() (locally with a .exe or even in some cloud someday for another use case), and also need to connect my text field content (the prompt) with the prompt that is going to be used by the auto UI we have here.
So knowing what I am aiming for, you can adapt your answer to insert in it some more info that can help me understand and "master" the code, if you wish for.

**Comment by vladmandic** [comment]
That's a much longer story and I'm literally boarding now...

**Comment by StableInfo** [comment]
Fair, if you login again and you are in transport and notknowing what to do, I would gladly read anything you read otherwise enjoy your time and when you come back you can write something if you wish. All the best

**Comment by vladmandic** [comment]
i've pushed a large update to metadata recently and as part of that image hash is also part of metadata when image is used for img2img or inpaint operations. but more than that - like i said before, it would overload metadata. i don't see anything truly useful that can be added to metadata given that both input image and mask are pixel values.

**Comment by StableInfo** [comment]
Cant we atleast get the "name" of the image input used?

**Comment by vladmandic** [comment]
Not really as name information is not available by then, only pixel data.
Name is not passed to backend at all. To get the name, we're talking a major rewrite - and at the end name can be anything, it doesn't mean much to start with.

**Comment by StableInfo** [comment]
AH ok, however  the name means somethign for me because I usually have it like "number-seed that number and that seed helps me find back the image used, just saying.
Anyway I started reading the code more and more, and I noticed how the bat file leads to the webui then to launch then to api.py then ui...() then I discovered the txt2img and img2img functions adn they are all inside "modules", I also saw that there was some kind of "call" that's the api, and everuthing is inside some gradio stuff (rows and columns etc) which the graphical user interface i think.
Anyway I will continue exploring the code hopefully getting it more and more and I will see then
