### ISSUE TITLE
[Issue]: ClipSkip Broken (and fixed)

### ISSUE THREAD

**Issue by Z1-Gamer** [vladmandic/automatic#1443]
### Issue Description

ClipSkip setting does not affect image generation. 1 or 2 or 3 does not matter, the image is the same.

I Fixed it when by uncommenting one line of code.
Before:
`#opts.data['clip_skip'] = clip_skip # todo is this necessary?`
ClipSkip does not work.

After:
`opts.data['clip_skip'] = clip_skip # todo is this necessary?`
ClipSkip works as intended.

The change was introduced in commit 0ddf613.
So my issue is practically resolved, this was more of an FYI post so you can fix it however you like 😉 .

Cheers. 😄 

### Version Platform Description

Windows
3070 TI
Version = eae813bc

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
my bad, i was testing something and forgot to remove the comment afterwards.

**Comment by brknsoul** [comment]
Should've also changed to comment to read `# todo this _is_ necessary!`
