### ISSUE TITLE
[Issue]: Since the commit "0ddf613", I can't repeat past generations

### ISSUE THREAD

**Issue by landrasss** [vladmandic/automatic#1444]
### Issue Description

Hello, as the title says, since the commit "0ddf613" I can't get the same images again. The last commit that does maintain them is "a9f66cb", which is the previous one. The change I see is that when you change to commit "0ddf613", "tomesd==0.1.2" is updated to "tomesd==0.1.3"
Hopefully you can see the issue, since the change of generations is quite noticeable. Cheers.

Additionally info:

- Windows 10
- Nvidia GTX 1660 Super
- Chrome
- Command line flags: --medvram
- no-half and no-half-vae, from the settings

Examples:

Version: a9f66cb3 Wed Jun 14 12:18:08 2023 +0300
![00033-161436149-RAW photo, a 22-year-old-girl, upper body, selfie in a car, blue hoodie, (1girl), (realistic), (photo-realistic_1 5), inside a c](https://github.com/vladmandic/automatic/assets/112908884/a7661754-c8f4-4434-b171-e50af7c84d1c)
![00030-3743294421-cinematic, filmic image 4k, 8k with  George Miller's Mad Max style  The image should be captured in a  wide-angle view  and dep](https://github.com/vladmandic/automatic/assets/112908884/031043b3-770f-49cf-9f1d-984758e9d53f)

Version: 0ddf613b Wed Jun 14 11:22:59 2023 -0400
![00035-161436149-RAW photo, a 22-year-old-girl, upper body, selfie in a car, blue hoodie, (1girl), (realistic), (photo-realistic_1 5), inside a c](https://github.com/vladmandic/automatic/assets/112908884/82fdca8a-026b-404f-acb0-81e98a349b18)
![00034-3743294421-cinematic, filmic image 4k, 8k with  George Miller's Mad Max style  The image should be captured in a  wide-angle view  and dep](https://github.com/vladmandic/automatic/assets/112908884/d6bb8ec9-c50b-4563-bcea-e34d470e3602)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
this is not an issue, this is a question - and the answer is you need to double check every setting you used before as some have changed default values. you've provided none and even if you did, i cannot check all your settings for you. this applies to server settings as well as ui txt2img (for example) settings.
