### ISSUE TITLE
[Issue]: Hires intermediate image is always saving according to Live Preview, instead of 'full quality'

### ISSUE THREAD

**Issue by EfourC** [vladmandic/automatic#1447]
### Issue Description

I noticed that Hires intermediate images recently started saving at whatever setting Live Preview is at, rather than normal 'full quality'.  After investigating, it appears that a change in 0ddf613 to the following block is the culprit, where it improperly uses `.keys()`:

https://github.com/vladmandic/automatic/blob/8749067510facdde6299775f7695afbac69c6312/modules/sd_samplers_common.py#L29-L30

The value in `approximation` will never be in .keys(), so it always enters the block and overwrites the passed-in approximation value with the live preview setting.

I'm not sure what the intent of the change was, but it was previously just the following:

```python
if approximation is None:
```
I'm guessing that the change was just an oversight in the jumbo merge effort?

### Version Platform Description

Browser: ungoogled-chromium

Python 3.10.11 on Windows
Version: 87490675 Fri Jun 16 16:18:15 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.0+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 2070 SUPER VRAM 8192 Arch (7, 5) Cores 40

- No extra startup flags
- Reset (deleted) config.json file to defaults

### Acknowledgements

- [x] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
> I'm guessing that the change was just an oversight in the jumbo merge effort?

Correct. Although not sure why was that change made in A1111 to start with?
Anyhow, corrected.
