### ISSUE TITLE
[Issue]: Install from URL doesn't autocreate repo folder

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#145]
### Issue Description

When installing a repository from URL, the repos folder is not created, instead a message comes up:
AssertionError: Extension directory already exists: I:\Super SD 2.0\automatic\extensions\

Adding a folder manually works.

### Version Platform Description

Win10, Firefox 106
Version: bf949a53 Fri Apr 14 21:27:29 2023 -0400

**Comment by vladmandic** [comment]
I cannot reproduce, but I've added some logging around that - can you update repo and try again?
It should log to console like:
> Installing extension: https://github.com/mix1009/model-keyword into /home/vlado/dev/automatic/extensions/model-keyword

**Comment by Woisek** [comment]
Allright, will watch it and give feedback then.

**Comment by Woisek** [comment]
So, I recently installed an extension from URL and this time it worked. Maybe the update meanwhile fixed it, idk ... 🙂

**Comment by vladmandic** [comment]
ok, i'll close for now. if issue reoccurs, let me know.

**Comment by ErikDombi** [comment]
Was just able to re-produce this. I believe it's caused by having a trailing forward slash at the end of the URL.

**Comment by vladmandic** [comment]
I can add handler to trailing slash, but it doesn't change the fact that trailing slash means it's not a valid repo URL to start with.
