### ISSUE TITLE
[Feature]: Option to prevent image from completing when clicking Stop.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1450]
### Feature description

At the moment, when you click Stop, the partially complete image is finalised and viewed in the Image Viewer.

It'd be nice if there were an option to simply stop and dump the image out of RAM/vRAM/etc.

**Comment by vladmandic** [comment]
What is the use case?

**Comment by brknsoul** [comment]
Usually, I hit Stop when I notice a mistake with my prompt, so I don't want to finish that generation and I'm not going to keep the partially generated image.

At the moment, hitting Stop attempts to finalise the image which takes time.

**Comment by vladmandic** [comment]
it also does a lot of cleanup after the current job is aborted. i could trace it down and skip only vae denoise/decode which is what's taking most of the time, but honestly i consider this a low priority item.

**Comment by brknsoul** [comment]
> consider this a low priority item

Understood. Stuff it behind the couch and get to it later when you're looking for loose change. ;-)

**Comment by Fadexz** [comment]
This would be great, it is annoying at times when the model tends to mess up a lot, you could quickly start a new generation once you notice large errors

**Comment by Aptronymist** [comment]
Actually this makes me think of generating the x/y/z grids I was doing last week, I could not get them to cancel when I spotted a mistake, not with skip, not with stop, once it was going I'd have to either let it play out or terminate the whole app.

**Comment by Fadexz** [comment]
> Actually this makes me think of generating the x/y/z grids I was doing last week, I could not get them to cancel when I spotted a mistake, not with skip, not with stop, once it was going I'd have to either let it play out or terminate the whole app.

Yeah, oddly enough I think it works only when using some settings, or at least it worked after I posted for a bit

**Comment by vladmandic** [comment]
this took too long, but its done.
- new option: *settings -> images -> keep incomplete*
  can be used to skip vae decode on aborted/skipped/interrupted image generations

**Comment by brknsoul** [comment]
Will auto prevent other actions (adetailer, post process upscaling) from happening?

**Comment by vladmandic** [comment]
yes.
and even if they somehow manage to execute, there is nothing to execute on as interrupt with keep incomplete disabled actually removes results, so any postprocessing would work on empty set.

**Comment by brknsoul** [comment]
Just updated and tested it, control returns significantly quicker. Thank you!
