### ISSUE TITLE
[Issue]: i changed some settings like use xformers and now i get error in img to img

### ISSUE THREAD

**Issue by rawheat1** [vladmandic/automatic#1451]
### Issue Description

RuntimeError: Input type (float) and bias type (struct c10::Half) should be the same
100%|██████████████████████████████████████████████████████████████████████████████████| 14/14 [00:06<00:00,  2.23it/s]
16:59:26-798219 INFO     Settings changed: 1 ['memmon_poll_rate']
16:59:34-768759 INFO     Settings changed: 1 ['enable_quantization']
2023-06-17 16:59:39,451 - ControlNet - INFO - Loading model from cache: control_v11p_sd15_normalbae [316696f1]
2023-06-17 16:59:39,453 - ControlNet - INFO - Loading preprocessor: normal_bae
2023-06-17 16:59:39,454 - ControlNet - INFO - preprocessor resolution = 512
 29%|███████████████████████▋                                                           | 4/14 [00:01<00:04,  2.36it/s]16:59:42-148031 ERROR    API error: POST: http://127.0.0.1:7860/internal/progress {'error': 'RuntimeError', 'detail':
                         '', 'body': '', 'errors': 'Input type (float) and bias type (struct c10::Half) should be the
                         same'}
16:59:42-154031 ERROR    HTTP API: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Sd\automatic\venv\lib\site-packages\anyio\streams\memory.py:94 in receive                                        │
│                                                                                                                     │
│ C:\Sd\automatic\venv\lib\site-packages\anyio\streams\memory.py:89 in receive_nowait                                 │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
WouldBlock

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Sd\automatic\venv\lib\site-packages\starlette\middleware\base.py:78 in call_next                                 │
│                                                                                                                     │
│ C:\Sd\automatic\venv\lib\site-packages\anyio\streams\memory.py:114 in receive                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
EndOfStream

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Sd\automatic\modules\middleware.py:72 in exception_handling                                                      │
│                                                                                                                     │
│   71 │   │   try:                                                                                                   │
│ > 72 │   │   │   return await call_next(req)                                                                        │
│   73 │   │   except CancelledError:                                                                                 │
│                                                                                                                     │
│ C:\Sd\automatic\venv\lib\site-packages\starlette\middleware\base.py:84 in call_next                                 │
│                                                                                                                     │
│                                              ... 31 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Sd\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward                                      │
│                                                                                                                     │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                                              │
│ >  463 │   │   return self._conv_forward(input, self.weight, self.bias)                                             │
│    464                                                                                                              │
│                                                                                                                     │
│ C:\Sd\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward                                │
│                                                                                                                     │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                                            │
│ >  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                                    │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                                            │
└─────────────────────────────────────────────────────────────────────────────────────

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
you said you changed "some settings" without even saying which ones.
and absolutely no information provided, not even what platform or what version you're running.
i've been very flexible in the past, but right now i have to start closing invalid issues as there is nothing here that i can even start looking at.
