### ISSUE TITLE
[Feature]: Make extra networks select folders more user-friendly

### ISSUE THREAD

**Issue by brunogcar** [vladmandic/automatic#1453]
### Feature description

to organize better each model, lora, etc i belive most of us create subfolders to place images, txt,  links,  whatever

and while viewing on Extra  Network  if you have a reasonable amount (few) is manageble, things get chaotic when you have a larger number of folders with way more subfolders 

so  i belive not displaying folders that do  not have ckpt,  safetensors,  pt,  bin would help a bit making Extra Networks more organized  to  view

![Screenshot 2023-06-17 111308](https://github.com/vladmandic/automatic/assets/53648/6467c3b3-b2b6-4f32-8b9d-4c55347fa23c)

long ago, i remember a1111 replying to a post saying that to prevent that, all files should be on same folder,  but that is just not reasonable and defeat to purpose of having folders to organize things

another improvement would be changing how the folder structure is displayed,  instead of on top of images, to a traditional file explorer view on the left with expand and collapse to show subfolders with models, but that would require a bit more work i presume

### Version Platform Description

Version: 5808b7a6 Sat Jun 17 08:13:19 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28

**Comment by vladmandic** [comment]
i've pushed an update to filter out empty folders.

and yes, i agree that folder view would be much better. in general, extra networks display can be better, i don't like that it pops up in the middle of the page. i'll keep this feature request open for future considerations.

**Comment by vladmandic** [comment]
i agree that depth-first makes sense, i've added that.
other stuff will have to wait until i redesign extra networks.

**Comment by Aptronymist** [comment]
> ### Feature description
> to organize better each model, lora, etc i belive most of us create subfolders to place images, txt, links, whatever
> 
> and while viewing on Extra Network if you have a reasonable amount (few) is manageble, things get chaotic when you have a larger number of folders with way more subfolders
> 
> so i belive not displaying folders that do not have ckpt, safetensors, pt, bin would help a bit making Extra Networks more organized to view
> 
> 
> long ago, i remember a1111 replying to a post saying that to prevent that, all files should be on same folder, but that is just not reasonable and defeat to purpose of having folders to organize things
> 
> another improvement would be changing how the folder structure is displayed, instead of on top of images, to a traditional file explorer view on the left with expand and collapse to show subfolders with models, but that would require a bit more work i presume

You may find some user.css things that might be able to help with that for the time being, we have a spot dedicated to it on the SD.Next discord server and someone just posted css to do this:

![image](https://github.com/vladmandic/automatic/assets/108482020/22ffa64c-2051-4b44-91ca-4286eec554c1)

**Comment by brunogcar** [comment]
8000d1965d7fc87ef1cc34adc09a124dd053bb36 pretty much covered all my requests

![new extra network](https://github.com/vladmandic/automatic/assets/53648/640deb43-48af-4f41-b7e5-716d8e721c16)

as i saw on other post,  collapsable folders might be revisited after new UI is deployed 

well done,  thanks

**Comment by Aptronymist** [comment]
> [8000d19](https://github.com/vladmandic/automatic/commit/8000d1965d7fc87ef1cc34adc09a124dd053bb36) pretty much covered all my requests
> 
Thought it might! Enjoy!
