### ISSUE TITLE
[Issue]: Batch Generation Stuck at 93%

### ISSUE THREAD

**Issue by danielbr93** [vladmandic/automatic#1454]
### Issue
I tried to make a picture for a friend (no really lol).
The batch generation sometimes stops at 93% (1s left). This didn't happen once, but multiple times in the past 2-3 weeks.
This forces a restart of the WebUI, not only a refresh of the web page.
Refreshing the web page will reset everything, but when generating images nothing happens in the WebUI or command window.
_EDIT:_ The pictures are not being saved in any folder and are lost "in the void".

### Pictures
Below you can find 2 pictures a few seconds after the generation gets stuck.
[WebUI + command window](https://imgur.com/a/YoJni2S)

### Generation Info
Positive:
(best quality, insanely detailed, masterpiece), (anime:1.3), (Enigmatic girl with white hair:1.2), (Mesmerizing crimson eyes:1.1), (Blood moon in the sky:1.3), (Gentle glow of moonbeams:1.1), (Delicate petals floating in the air:1.2), (Whispering night breeze:1.1), (Mystical spellcasting:1.1), (Eerie tranquility:1.1), (Otherworldly allure:1.2), looking at viewer, solo, sharp focus, full body, cinematic lighting, high quality, depth of field, bokeh, 8k resolution, trending on artstation, trending on cgsociety

Negative:
(worst quality:1.4), (low quality:1.4), bad-hands-5, by <bad-artist:1.0>, by <bad-artist-anime:1.0>, <bad_prompt_version2:1.0> , easynegative, ng_deepnegative_v1_75t, kitsch, ugly, oversaturated, grain, low-res, Deformed, out of focus, poorly drawn, childish, mangled, old, text

- No Controlnet.
- No Hires-fix.
- No LORA.
- Embeddings as seen in the negative prompt.

### Version Platform Description

```
Starting SD.Next
Python 3.10.6 on Windows
Version: 5808b7a6 Sat Jun 17 08:13:19 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3090 Ti VRAM 24564 Arch (8, 6) Cores 84
WARNING  Modified files: ['webui.bat']
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
Enabled extensions: ['deforum-for-automatic1111-webui', 'posex', 'sd-pixel',
                         'sd-webui-depth-lib', 'sd-webui-gelbooru-prompt', 'sd-webui-text2video',
                         'stable-diffusion-webui-pixelization', 'ultimate-upscale-for-automatic1111']
                          ...
```
_EDIT:_ "WARNING  Modified files: ['webui.bat']" is because of "--autolaunch" next to launch.py in the bat file.

- Windows 11 Home
- Version	10.0.22621 Build 22621	
- AMD Ryzen 9 3950X
- NVIDIA GeForce RTX 3090 Ti
- Microsoft Edge - Version 114.0.1823.43 (Official build) (64-bit)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
try to reset your settings -> live preview values, use any other than full (see #1378 for details).

and DO NOT modify `webui.bat`. you can either add params to windows shortcut or create your own batch file that calls `webui.bat --autolaunch` or any other supported solution (check FAQ for details).

**Comment by danielbr93** [comment]
Sorry for no comment Vlad!
Problem has been fixed!

1. Reset the preview values setting worked.
2. I removed the modification of the `webui.bat`
