### ISSUE TITLE
ValueError: Unrecognised argument(s): encoding

### ISSUE THREAD

**Issue by ibatuloff** [vladmandic/automatic#1455]
ValueError: Unrecognised argument(s): encoding

Fresh installation, after launching launch.py ValueError appears:
Traceback (most recent call last):
  File "launch.py", line 154, in <module>
    installer.setup_logging(False)
  File "/home/stepan/automatic/installer.py", line 69, in setup_logging
    logging.basicConfig(level=logging.ERROR, format='%(asctime)s | %(name)s | %(levelname)s | %(module)s | %(message)s', filename=log_file, filemode='a', encoding='utf-8', force=True)
  File "/usr/lib/python3.8/logging/__init__.py", line 2009, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding

### Version Platform Description

Linux Ubuntu 20.04.06
Firefox browser
Latest vladmandic commit

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
python 3.8 is not supported.
supported are 3.9 and 3.10 (recommended version) and 3.11 (experimental limited support).

i'll add better reporting so this is clearly visible when starting the app, but that's about it - you need to install newer python.
