### ISSUE TITLE
[Feature]: Stop Extra Networks buttons including files from wrong directory

### ISSUE THREAD

**Issue by roamingfrog** [vladmandic/automatic#1456]
### Feature description

Currently the buttons in Extra Networks for Loras, Textual Inversions, etc. will incorrectly include content from other folders that end with the same text as the folder you select. 

### Example To Replicate
- Have "men" and "women" directories containing Loras.
- Extra Networks shows buttons for "men/" and "women/".
- Click on "men/" button.
- Loras from the "women" directory incorrectly show up in the list that should just show the contents of the "men" directory.

### Solution 1

In `/modules/ui_extra_networks.py`
Line 108: `subdir = subdir + "/"` > `subdir = "/" + subdir + "/"`
Result: Button text changes from "men/" to "/men/", Content from "women" directory no longer shows when clicked.

### Solution 2

In `/javascript/extraNetworks.js`
Line 123: `text = button.classList.contains('search-all') ? '' : button.textContent.trim();` > `text = button.classList.contains('search-all') ? '' : '/' + button.textContent.trim();`
Result: Button text remains as "men/" but pastes "/men/" into the search box, Content from "women" directory no longer shows when clicked.

It's not exactly a life-changing fix, but it would stop my pineapple loras incorrectly showing up in my apples directory. :)

### Version Platform Description

This has always been the behaviour in all versions, but for what it's worth:
Version: 5808b7a6 Sat Jun 17 08:13:19 2023 -0400
Windows 11
Chrome

**Comment by vladmandic** [comment]
yeah, mixing apples and pineapples is definitely something we really really don't want. so its fixed :)
