### ISSUE TITLE
[Issue]: Getting 'JSONDecodeError: Invalid \escape: line 1 column 195 (char 194)' on startup.

### ISSUE THREAD

**Issue by drfacedoctor** [vladmandic/automatic#1459]
### Issue Description

Since updating a few minutes ago I can't launch the program. I tried doing a fresh install in a new folder and can't even launch that due to this error, it's the same whether I'm trying to launch my old install or do a clean install:

> ┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\PC\automatic\launch.py:189 in <module>                                                                     │
│                                                                                                                     │
│   188                                                                                                               │
│ > 189     instance = start_server(immediate=True, server=None)                                                      │
│   190     while True:                                                                                               │
│                                                                                                                     │
│ C:\Users\PC\automatic\launch.py:144 in start_server                                                                 │
│                                                                                                                     │
│   143         else:                                                                                                 │
│ > 144             server = server.webui(restart=not immediate)                                                      │
│   145     if args.profile:                                                                                          │
│                                                                                                                     │
│ C:\Users\PC\automatic\webui.py:301 in webui                                                                         │
│                                                                                                                     │
│   300                                                                                                               │
│ > 301     start_common()                                                                                            │
│   302     start_ui()                                                                                                │
│                                                                                                                     │
│ C:\Users\PC\automatic\webui.py:216 in start_common                                                                  │
│                                                                                                                     │
│   215     if shared.cmd_opts.data_dir is not None or len(shared.cmd_opts.data_dir) > 0:                             │
│ > 216         log.info(f'Using data path: {shared.cmd_opts.data_dir}')                                              │
│   217     create_paths(opts)                                                                                        │
│                                                                                                                     │
│ C:\Program                                                                                                          │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py:1477  │
│ in info                                                                                                             │
│                                                                                                                     │
│   1476         if self.isEnabledFor(INFO):                                                                          │
│ > 1477             self._log(INFO, msg, args, **kwargs)                                                             │
│   1478                                                                                                              │
│                                                                                                                     │
│ C:\Program                                                                                                          │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py:1624  │
│ in _log                                                                                                             │
│                                                                                                                     │
│   1623                                  exc_info, func, extra, sinfo)                                               │
│ > 1624         self.handle(record)                                                                                  │
│   1625                                                                                                              │
│                                                                                                                     │
│ C:\Program                                                                                                          │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py:1634  │
│ in handle                                                                                                           │
│                                                                                                                     │
│   1633         if (not self.disabled) and self.filter(record):                                                      │
│ > 1634             self.callHandlers(record)                                                                        │
│   1635                                                                                                              │
│                                                                                                                     │
│ C:\Program                                                                                                          │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py:1696  │
│ in callHandlers                                                                                                     │
│                                                                                                                     │
│   1695                 if record.levelno >= hdlr.level:                                                             │
│ > 1696                     hdlr.handle(record)                                                                      │
│   1697             if not c.propagate:                                                                              │
│                                                                                                                     │
│ C:\Program                                                                                                          │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py:968   │
│ in handle                                                                                                           │
│                                                                                                                     │
│    967             try:                                                                                             │
│ >  968                 self.emit(record)                                                                            │
│    969             finally:                                                                                         │
│                                                                                                                     │
│ C:\Users\PC\automatic\installer.py:62 in emit                                                                       │
│                                                                                                                     │
│    61             msg = self.format(record)                                                                         │
│ >  62             self.buffer.append(json.loads(msg))                                                               │
│    63             if len(self.buffer) > self.capacity:                                                              │
│                                                                                                                     │
│ C:\Program                                                                                                          │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\__init__.py:346 in   │
│ loads                                                                                                               │
│                                                                                                                     │
│   345             parse_constant is None and object_pairs_hook is None and not kw):                                 │
│ > 346         return _default_decoder.decode(s)                                                                     │
│   347     if cls is None:                                                                                           │
│                                                                                                                     │
│ C:\Program                                                                                                          │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py:337 in    │
│ decode                                                                                                              │
│                                                                                                                     │
│   336         """                                                                                                   │
│ > 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                     │
│   338         end = _w(s, end).end()                                                                                │
│                                                                                                                     │
│ C:\Program                                                                                                          │
│ Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\json\decoder.py:353 in    │
│ raw_decode                                                                                                          │
│                                                                                                                     │
│   352         try:                                                                                                  │
│ > 353             obj, end = self.scan_once(s, idx)                                                                 │
│   354         except StopIteration as err:                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
JSONDecodeError: Invalid \escape: line 1 column 195 (char 194)

### Version Platform Description

OS: Windows 10
GPU: RTX 3070 8GB
CPU: AMD Ryzen 7 5800x3D

startup log:

> 17:32:18-153258 INFO     Starting SD.Next
17:32:18-160264 INFO     Python 3.10.11 on Windows
17:32:18-194758 INFO     Version: fa35ea15 Sat Jun 17 20:12:04 2023 -0400
17:32:18-518435 INFO     Latest published version: 5f50c35388a23d41b6c01d63afb5e742833eb00c 2023-06-18T00:23:00Z
17:32:18-522440 INFO     nVidia CUDA toolkit detected
17:32:20-179026 INFO     Torch 2.0.1+cu118
17:32:20-206074 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
17:32:20-208075 INFO     Torch detected GPU: NVIDIA GeForce RTX 3070 VRAM 8191 Arch (8, 6) Cores 46
17:32:20-210077 INFO     Installing package: tensorflow==2.12.0

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
that version was up for 2min only before it was fixed as another commit was in progress.
