### ISSUE TITLE
[Issue]: When updating, hardlinks are getting replaced with folders

### ISSUE THREAD

**Issue by mobilehacker** [vladmandic/automatic#146]
### Issue Description

Greetings! I'm using several different SD forks, and using a shared folder for models, as they have a large size. When I'm getting an update using bat file, my hardlinks are getting overwritten by regular folders. That happens each update and is easily reproduceable. Create a hardlink using the command like this: 

in webui install folder open cmd: 

mklink /J outputs D:/_AI_GENERATED/outputs

This will make a shortcut which is treated like a folder, pointing to a folder on drive D; However, after update, this will be replaced with regular folder.

### Version Platform Description

Windows 11, Version: bf949a53 Fri Apr 14 21:27:29 2023 -0400

**Comment by mobilehacker** [comment]
Right now, I'm using a bat file like this to circumvent this issue:

cd /d S:\_AI\vladmandic
rmdir /s /q models
rmdir /s /q outputs
mklink /j models S:\_AI\models
mklink /j outputs D:\_AI_GENERATED\outputs

**Comment by vladmandic** [comment]
I need to remove all folders from `/models` from git, so it doesn't try to check them out, but...if i do that, then git will try to *remove* actual folder from users drive which would be baaad. need to figure out how to work around git on this one.
i'm keeping the issue open until fix is available.

**Comment by Woisek** [comment]
Just here to add, that I face the exact same issue as @mobilehacker.

**Comment by vladmandic** [comment]
yes, like i said, its a known issue, no need to flag

**Comment by AlUlkesh** [comment]
There's the same issue with the .vscode folder. It's now it .gitignore, but that apparently doesn't do anything, since it was already tracked by git. And deleting it from the repo would try to delete it from a user's local repo too.

**Comment by vladmandic** [comment]
@AlUlkesh that's correct. I've just applied `git update-index --skip-worktree .vscode/settings.json` on my side so that one should be ok from now, but that shouldn't be done for `/models`, so issue still remains.

**Comment by vladmandic** [comment]
i've fixed `outputs` in dev branch, release will be later today.

for `models`, you cannot link root of models as each is handled separately and definitely leads to problems. and some model files are included in repo itself and not downloaded on-demand, for example `models/VAE-approx` which is used for quick live preview.
you should link `models/Stable-diffusion` for actual checkpoints. the rest can also be linked as needed, but typically are not that large.
