### ISSUE TITLE
[Issue]: Batch Generation, saved image uses metadata from previous image in the batch

### ISSUE THREAD

**Issue by SoraEnkai** [vladmandic/automatic#1461]
### Issue Description

Ran with `--safe` on latest commit as of writting `e9f4ba02` for debugging purposes.

Issue: Generation metadata shown in T2T shows correct metadata, but saved image has metadata from the image to the left of it.

Example workflow:
From Text
Prompt: `night sky`
seed: `2340247729`

Make any batch size (used 1 count, size 3)
Save each individual image with 'Save' button.

Expected result:
2nd and 3rd image have seeds 2340247730 and 2340247731 respectively 

Result:
2nd image has seed 2340247729
3rd image has seed 2340247730

Added an example image with full generation data
![00008-2340247730-night sky](https://github.com/vladmandic/automatic/assets/39128897/67976cc2-4134-4bd9-a824-083c4cfbc603)

This is more noticeable when combined with Dynamic Prompts or another extension that allows different prompts in the same batch, as saved data has the prompts from the previous batch image.

### Version Platform Description

 Starting SD.Next
Python 3.10.6 on Windows
Version: e9f4ba02 Sat Jun 17 20:41:49 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10240 Arch (8, 6) Cores 68
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed.
btw, thanks for creating issue that is easy to understand and contains all relevant information.
