### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by jagadishrnaidu** [vladmandic/automatic#1462]
### Issue Description

when i pull available extensions there is a error

![Screenshot 2023-06-18 160907](https://github.com/vladmandic/automatic/assets/67152132/a1530e4c-a2df-4c0e-9ec7-ceb75c41f908)
![Screenshot 2023-06-18 163319](https://github.com/vladmandic/automatic/assets/67152132/2e117cc9-d336-4362-839b-ba40753af4a5)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
no title, no version info => invalid issue, closing.

and looking at the screenshot above, this does NOT look like app from this repo at all!
