### ISSUE TITLE
[Issue]: Refreshing Extra Networks removes LoRAs from view when using LyCORIS patch + no preview images

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1465]
### Issue Description

When using "Use LyCoris handler for all Lora types" the Refresh button on the Extra Networks panel removes all LoRAs from view in the LyCORIS tab, leaving only lycos visible.

Also, no Lora preview images are visible using the same setting.

### Version Platform Description

  Python 3.10.11 on Windows
  Version: 457dddf7 Sun Jun 18 11:38:42 2023 -0400
  Using DirectML Backend
  Torch 2.0.0+cpu
  Torch backend: DirectML (torch-directml 0.2.0.dev230426)
  Torch detected GPU: AMD Radeon RX 6600 XT

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
> When using "Use LyCoris handler for all Lora types" the Refresh button on the Extra Networks panel removes all LoRAs from view in the LyCORIS tab, leaving only lycos visible.

But that is the whole point of this option - so single handler handles both and there is no separation between the two.
Which means there are no two separate extra network tabs.

And if you want to use this efficiently, i suggest to put all Lora/Lyco files in a single folder.
