### ISSUE TITLE
[Extension]: Better Styles panel and icon missing

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1466]
### Issue Description

Better Style button and panel is no longer visible.
It was visible on commit 618097da and disappeared when I upgraded to commit 457dddf7.

### Version Platform Description

457dddf7, win10, chrome

### URL link of the extension

https://github.com/eideehi/sd-webui-better-styles

### URL link of the issue reported in the extension repository

https://github.com/eideehi/sd-webui-better-styles/issues/6

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
extension related issues without issue created upstream (as required in the issue template) will not be actively worked on.

**Comment by brknsoul** [comment]
Created

**Comment by vladmandic** [comment]
this is obsolete with new styles functionality introduced in dev branch (will be merged to master shortly)
