### ISSUE TITLE
[Issue]: UI tooltips clip under image preview window (z-index layering)

### ISSUE THREAD

**Issue by SoraEnkai** [vladmandic/automatic#1467]
### Issue Description

Small frontend issue when using UI Tooltips, it clips under preview image window.

Prerequisite:
UI Tooltips -> UI tooltips option has to be enabled
Create an image, click on it so preview is active.
Tested on nota-ai/theme and black-orange.

![Screenshot 2023-06-19 000324](https://github.com/vladmandic/automatic/assets/39128897/a25d3816-363e-4b37-9fc6-b7a87db8b01a)

Probably other places have higher z-index than preview so those should be checked.

`.tooltip` class should have atleast 20 z-index to hover above it.
 `z-index: var(--layer-2); `

### Version Platform Description

23:35:54-017970 INFO     Starting SD.Next
23:35:54-026479 INFO     Python 3.10.6 on Windows
23:35:54-502098 INFO     Version: 457dddf7 Sun Jun 18 11:38:42 2023 -0400
23:35:55-120022 INFO     Updating main repository
23:35:58-176402 INFO     Upgraded to version: b340e3f4 Sun Jun 18 16:30:59 2023 -0400
23:35:58-180401 INFO     nVidia CUDA toolkit detected
23:36:00-067150 INFO     Torch 2.0.1+cu118
23:36:00-090655 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
23:36:00-092658 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10240 Arch (8, 6) Cores 68
23:36:00-188984 INFO     Verifying requirements
23:36:00-200006 INFO     Verifying packages
23:36:00-202007 INFO     Installing repositories
23:36:03-308760 INFO     Installing submodules
23:36:07-694752 INFO     Updating submodules

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fair point. why not create a PR?

**Comment by SoraEnkai** [comment]
Fair enough, should've done this from the start.
Not familiar with gradio/github workflow yet, but it looks like it just uses the styles.css from javascript folder.
