### ISSUE TITLE
[Issue]: not starting

### ISSUE THREAD

**Issue by Holyniwa** [vladmandic/automatic#147]
### Issue Description

Not sure what happened, i cant get it to start now? I just clicked the bat file today, it seemed to update and do something, but it crashed, so I opened it again and it's returning this. Unsure of what to do. (haven't messed with any settings or anything today. Just got on my PC, lol)

venv "D:\stable-diffusion\automatic\venv\Scripts\Python.exe"
Traceback (most recent call last):
  File "D:\stable-diffusion\automatic\launch.py", line 5, in <module>
    import setup
  File "D:\stable-diffusion\automatic\setup.py", line 322
    <<<<<<< Updated upstream
    ^^
SyntaxError: invalid syntax
Press any key to continue . . .

### Version Platform Description

win11, chrome

**Comment by vladmandic** [comment]
ouch, this line:
````
<<<<<<< Updated upstream
```
looks like `git` attempted **merge** instead of overwrite file with new one?
can you open the file `D:\stable-diffusion\automatic\setup.py` in editor and check that line (322)

if its really like you've marked, thats a nightmare to get out of, easiest would be to do a fresh clone/checkout.

**Comment by Holyniwa** [comment]
Yeah it is. Can i edit it and fix it, maybe? 
![image](https://user-images.githubusercontent.com/13576034/232238850-2756dfbb-5875-40ef-957d-6c7be36a2e02.png)

**Comment by vladmandic** [comment]
my concern is that if this file is like that, how many others are affected?
you can try:

```shell
git merge --abort
git fetch --all
git reset --hard
```

**Comment by Holyniwa** [comment]
That seemed to have solved it. I can't tell if there were boxes around panels on the top before, but it doesn't bother me, just feels like they weren't there before. Program running as expected!
![chrome_Tyj6uc5kVa](https://user-images.githubusercontent.com/13576034/232245190-43f9e4e0-b32b-406b-ab2e-c88916d931c7.png)

**Comment by Holyniwa** [comment]
I noticed others talking about the errors in arg. the 

git merge --abort
git fetch --all
git reset --hard origin/master
git checkout master

also helped remove those errors

**Comment by vladmandic** [comment]
Sorry about that, I just documented how to get out of the situation and pushed a patch for future so it can be automatically handled.

See #152 for details.

**Comment by Holyniwa** [comment]
New push has me endlessly loading now... lol

**Comment by CapsAdmin** [comment]
> my concern is that if this file is like that, how many others are affected? you can try:
> 
> ```shell
> git merge --abort
> git fetch --all
> git reset --hard origin/master
> git checkout master
> ```

I got merge conflicts in ui-config.json earlier when you added more builtin-extensions.
