### ISSUE TITLE
[Feature]: Keep Inpainting Mask When Replacing Source Image with Matching Dimensions

### ISSUE THREAD

**Issue by rcwatkins** [vladmandic/automatic#1478]
### Feature description

A very common workflow when using img2img is to generate until you get something you like and then use the new generation as the source for further tweaks. This remains true for inpaint, but each time you replace the image the inpaint mask is reset. Inpaint masks are often tedious, especially given the current tools, and recreating a mask is time consuming. A better alternative would be to **allow the inpaint mask to persist if the new image resolution matches the old image resolution**. The resolution comparison allows you to be fairly certain the user is still working on the same image. If the user doesn't want the mask to persist then they can easily clear it with one click (already implemented), which is substantially faster than the alternative of recreating a painted mask.

### Version Platform Description

e9f4ba02, Windows 10, Firefox

**Comment by danaildichev** [comment]
In Settings > Canvas Zoom there's an option "Enable mask clearing in inpaint after any picture is moved in inpaint via buttons". That could be what you're looking for.

**Comment by rcwatkins** [comment]
> 

This doesn't seem to be working for me. It still clears the mask - I tried in chrome and firefox fyi.
