### ISSUE TITLE
[Issue]: Startup errors

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#148]
### Issue Description

Just now I worked with Automatic, re-wrote the CSS to my liking and rendered some images. Now I wanted to do a complete re-start and suddenly (or again) some errors occur:

16:51:51-167968 INFO     Available models: I:\Super SD 2.0\automatic\models\Stable-diffusion 159
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
100%|███████████████████████████████████████████████████████████████████████████████| 74/74 [00:00<00:00, 76316.33it/s]
executing callback: I:\Super SD 2.0\automatic\extensions\sd-model-preview-xd\scripts\modelpreview.py ui_tabs_callback:
FileNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\modules\script_callbacks.py:122 in ui_tabs_callback                                       │
│                                                                                                                     │
│   121 │   │   try:                                                                                                  │
│ > 122 │   │   │   res += c.callback() or []                                                                         │
│   123 │   │   except Exception as e:                                                                                │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\extensions\sd-model-preview-xd\scripts\modelpreview.py:773 in on_ui_tabs                  │
│                                                                                                                     │
│   772 │   │   create_tab("Embeddings", "em",                                                                        │
│ > 773 │   │   │   │   list_all_embeddings(),                                                                        │
│   774 │   │   │   │   show_embedding_preview,                                                                       │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\extensions\sd-model-preview-xd\scripts\modelpreview.py:92 in is_dir_in_list               │
│                                                                                                                     │
│    91 │   for dir_path in dir_list:                                                                                 │
│ >  92 │   │   if os.path.samefile(check_dir, dir_path):                                                             │
│    93 │   │   │   return True                                                                                       │
│                                                                                                                     │
│ F:\Programme\Python310\lib\genericpath.py:101 in samefile                                                           │
│                                                                                                                     │
│   100 │   s1 = os.stat(f1)                                                                                          │
│ > 101 │   s2 = os.stat(f2)                                                                                          │
│   102 │   return samestat(s1, s2)                                                                                   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'I:\\Super SD
2.0\\automatic\\embeddings'
loading ui settings: JSONDecodeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\modules\ui.py:1613 in create_ui                                                           │
│                                                                                                                     │
│   1612 │   │   │   with open(ui_config_file, "r", encoding="utf8") as file:                                         │
│ > 1613 │   │   │   │   ui_settings = json.load(file)                                                                │
│   1614 │   except Exception as e:                                                                                   │
│                                                                                                                     │
│ F:\Programme\Python310\lib\json\__init__.py:293 in load                                                             │
│                                                                                                                     │
│   292 │   """                                                                                                       │
│ > 293 │   return loads(fp.read(),                                                                                   │
│   294 │   │   cls=cls, object_hook=object_hook,                                                                     │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ F:\Programme\Python310\lib\json\decoder.py:337 in decode                                                            │
│                                                                                                                     │
│   336 │   │   """                                                                                                   │
│ > 337 │   │   obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                                     │
│   338 │   │   end = _w(s, end).end()                                                                                │
│                                                                                                                     │
│ F:\Programme\Python310\lib\json\decoder.py:353 in raw_decode                                                        │
│                                                                                                                     │
│   352 │   │   try:                                                                                                  │
│ > 353 │   │   │   obj, end = self.scan_once(s, idx)                                                                 │
│   354 │   │   except StopIteration as err:                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
JSONDecodeError: Expecting property name enclosed in double quotes: line 1017 column 1 (char 62295)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

I don't get why this appears -> FileNotFoundError: [WinError 2] Das System kann die angegebene Datei nicht finden: 'I:\\Super SD
2.0\\automatic\\embeddings'
when the settings say -> I:\Super SD 2.0\automatic\models\embeddings

### Version Platform Description

Win10, Firefox 106
Version: ed8819b8 Sat Apr 15 10:28:31 2023 -0400

**Comment by vladmandic** [comment]
that is a bug in **sd-model-preview-xd** extension, it looks for hard-coded embeddings folder:

https://github.com/CurtisDS/sd-model-preview-xd/blob/494af19003eb0fef8d08225265bef1589f3659ce/scripts/modelpreview.py#L550-L557

either remove the extension or create the issue there and work with the author to resolve it.

**Comment by Woisek** [comment]
OK, now I get it, thanks.
