### ISSUE TITLE
[Issue]: NansException: A tensor with all NaNs was produced in VAE

### ISSUE THREAD

**Issue by rockiecxh** [vladmandic/automatic#149]
### Issue Description

Just normal run: 
NansException: A tensor with all NaNs was produced in VAE. Use --disable-nan-check commandline argument to disable this
check.

But after adding the parameter  --disable-nan-check, it was not recognized. 

### Version Platform Description

Win11, Latest version, '--medvram', '--no-half-vae'

Model: https://civitai.com/models/7371

**Comment by vladmandic** [comment]
i've just changed behavior not to check for NaNs, that will remove the error, but the image will still be black/corrupt.
on why that happens, i cannot say. you already have `--no-half-vae` in your cmd flags, so its not precision.
its up to your cpu or gpu (you didn't specify) to execute model correctly.

**Comment by Shadowghost** [comment]
If you are using xformers, this might be caused by a problem with torch2 and xformers 0.0.18.
You can try downgrading to 0.0.17 and enabling upcast sampling.
See https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9619 for more info.

**Comment by vladmandic** [comment]
i'm pinning `xformers==0.0.17` as there are multiple issues with 0.0.18, new version will be on github in ~1h.

**Comment by jurandfantom** [comment]
Issue is still existing (most fresh updated version). In my case it looks like issue is with LoRA's (any). Of course --disable-nan-check is not supported so we got a Catch 22 situation here.

AMD (Threadripper 1950X) and Nvidia RTX 4090 if that matter.

``
2023-04-16 18:29:16,179 | INFO | E:\Magazyn\Grafika\AI\Vladmandic\automatic\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py | Prompt matrix will create 1 images in a total of 1 batches.
Loading weights: E:\Magazyn\Grafika\AI\Automatic1111\stable-diffusion-webui\models\Lora\Artistic\80sJapanAnalogFilm_1…
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:03<00:00,  2.98it/s]
gradio call: NansException
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ E:\Magazyn\Grafika\AI\Vladmandic\automatic\modules\call_queue.py:59 in f                                            │
│                                                                                                                     │
│    58 │   │   │   │   pr.enable()                                                                                   │
│ >  59 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    60 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ E:\Magazyn\Grafika\AI\Vladmandic\automatic\modules\call_queue.py:38 in f                                            │
│                                                                                                                     │
│    37 │   │   │   try:                                                                                              │
│ >  38 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    39 │   │   │   finally:                                                                                          │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ E:\Magazyn\Grafika\AI\Vladmandic\automatic\modules\processing.py:664 in process_images_inner                        │
│                                                                                                                     │
│    663 │   │   │   for x in x_samples_ddim:                                                                         │
│ >  664 │   │   │   │   devices.test_for_nans(x, "vae")                                                              │
│    665                                                                                                              │
│                                                                                                                     │
│ E:\Magazyn\Grafika\AI\Vladmandic\automatic\modules\devices.py:144 in test_for_nans                                  │
│                                                                                                                     │
│   143 │   message += " Use --disable-nan-check commandline argument to disable this check."                         │
│ > 144 │   raise NansException(message)                                                                              │
│   145                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
NansException: A tensor with all NaNs was produced in VAE. Use --disable-nan-check commandline argument to disable this
check.
``

**Comment by vladmandic** [comment]
> Of course --disable-nan-check is not supported so we got a Catch 22 situation here.

disable nan checks is now in UI: Settings -> Stable Diffusion -> Do not check if produced images/latent spaces have NaN values

**Comment by jurandfantom** [comment]
hmm indeed no error, but pure black generated “image”.

**Comment by FutonGama** [comment]
This is also happening with me but is not a problem of the Fork, its also happening in other ones with this Model. For work correctly needs always change to another Model, generate something and back to ReV Animated model. So will work but need to do that everytime when restart the SD. Ah and im also using that files on the model description.

**Comment by FutonGama** [comment]
> Which exact option and what do you thing should be a default value?

I think this is ok since it only happened to me with this model.

**Comment by FutonGama** [comment]
Ok they updated the model and now it's working. It was just a problem with this model, a lot of people are using it, it's very beautiful.

**Comment by vladmandic** [comment]
nice.
btw, i've never used that model, but it does look nice - i'll check it out.
is there anything else we can do in this issue?

**Comment by The-Noble** [comment]
Getting this error with Anything4.0
Anything4.0 definitely works on Automatics1111
I don't think we actually got to the bottom of the error.

**Comment by vladmandic** [comment]
i've created master issue that documents necessary steps - lets continue there: #374
