### ISSUE TITLE
[Extension]: sd-webui-text2video doesn't work.

### ISSUE THREAD

**Issue by toyxyz** [vladmandic/automatic#1490]
### Issue Description

sd-webui-text2video doesn't work. (https://github.com/kabachuha/sd-webui-text2video)

It worked fine in Automatic1111 webui, but when I tried it in this repo, I got the following error.

=================================================================

text2video — The model selected is:  ModelScope
 text2video extension for auto1111 webui
Git commit: <p>a44078d1</p><p>Sat Jun10 2023 23:47</p>
Starting text2video
Pipeline setup
config namespace(framework='pytorch', task='text-to-video-synthesis', model={'type': 'latent-text-to-video-synthesis', 'model_args': {'ckpt_clip': 'open_clip_pytorch_model.bin', 'ckpt_unet': 'text2video_pytorch_model.pth', 'ckpt_autoencoder': 'VQGAN_autoencoder.pth', 'max_frames': 16, 'tiny_gpu': 1}, 'model_cfg': {'unet_in_dim': 4, 'unet_dim': 320, 'unet_y_dim': 768, 'unet_context_dim': 1024, 'unet_out_dim': 4, 'unet_dim_mult': [1, 2, 4, 4], 'unet_num_heads': 8, 'unet_head_dim': 64, 'unet_res_blocks': 2, 'unet_attn_scales': [1, 0.5, 0.25], 'unet_dropout': 0.1, 'temporal_attention': 'True', 'num_timesteps': 1000, 'mean_type': 'eps', 'var_type': 'fixed_small', 'loss_type': 'mse'}}, pipeline={'type': 'latent-text-to-video-synthesis'})
device cuda
Working in txt2vid mode
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]Making a video with the following parameters:
{'prompt': 'big blue bird', 'n_prompt': 'text, watermark, copyright, blurry, nsfw', 'steps': 30, 'frames': 24, 'seed': 3557574797, 'scale': 17, 'width': 256, 'height': 256, 'eta': 0.0, 'cpu_vae': 'GPU (half precision)', 'device': device(type='cuda'), 'skip_steps': 0, 'strength': 0}
latents torch.Size([1, 4, 24, 32, 32]) tensor(0.0013, device='cuda:0') tensor(1.0011, device='cuda:0')
DDIM sampling:   0%|                                                                            | 0/31 [00:00<?, ?it/s]
Traceback (most recent call last):                                                              | 0/31 [00:00<?, ?it/s]
  File "C:\Vlad\Vla\automatic/extensions/sd-webui-text2video/scripts\t2v_helpers\render.py", line 27, in run
    vids_pack = process_modelscope(args_dict)
  File "C:\Vlad\Vla\automatic/extensions/sd-webui-text2video/scripts\modelscope\process_modelscope.py", line 209, in process_modelscope
    samples, _ = pipe.infer(args.prompt, args.n_prompt, args.steps, args.frames, args.seed + batch if args.seed != -1 else -1, args.cfg_scale,
  File "C:\Vlad\Vla\automatic/extensions/sd-webui-text2video/scripts\modelscope\t2v_pipeline.py", line 258, in infer
    x0 = self.diffusion.ddim_sample_loop(
  File "C:\Vlad\Vla\automatic\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Vlad\Vla\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 1485, in ddim_sample_loop
    xt = self.ddim_sample(xt, t, model, model_kwargs, clamp,
  File "C:\Vlad\Vla\automatic\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Vlad\Vla\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 1334, in ddim_sample    _, _, _, x0 = self.p_mean_variance(xt, t, model, model_kwargs, clamp,
  File "C:\Vlad\Vla\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 1275, in p_mean_variance
    y_out = model(xt, self._scale_timesteps(t), **model_kwargs[0])
  File "C:\Vlad\Vla\automatic\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Vlad\Vla\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 369, in forward
    x = self._forward_single(block, x, e, context, time_rel_pos_bias,
  File "C:\Vlad\Vla\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 432, in _forward_single
    x = self._forward_single(block, x, e, context,
  File "C:\Vlad\Vla\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 416, in _forward_single
    x = module(x, context)
  File "C:\Vlad\Vla\automatic\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Vlad\Vla\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 673, in forward
    x = block(x)
  File "C:\Vlad\Vla\automatic\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Vlad\Vla\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 740, in forward
    x = self.attn1(
  File "C:\Vlad\Vla\automatic\venv\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Vlad\Vla\automatic\extensions\sd-webui-text2video\scripts\modelscope\t2v_model.py", line 492, in forward
    if cmd_opts.force_enable_xformers or (cmd_opts.xformers and shared.xformers_available and torch.version.cuda and (6, 0) <= torch.cuda.get_device_capability(shared.device) <= (9, 0)):
AttributeError: 'Namespace' object has no attribute 'force_enable_xformers'
Exception occurred: 'Namespace' object has no attribute 'force_enable_xformers'

### Version Platform Description

Window 10, Edge browser

02:21:23-670156 INFO     Starting SD.Next
02:21:23-679921 INFO     Python 3.10.6 on Windows
02:21:23-746323 INFO     Version: b80fcca9 Thu Jun 22 13:05:26 2023 -0400
02:21:24-184770 INFO     nVidia CUDA toolkit detected
02:21:25-823014 INFO     Torch 2.0.1+cu118
02:21:25-843518 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
02:21:25-845472 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 Ti VRAM 24564 Arch (8, 6) Cores 84
02:21:26-058350 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
02:21:26-075924 INFO     Enabled extensions: ['a1111-sd-webui-tagcomplete', 'ABG_extension',
                         'infinite-zoom-automatic1111-webui', 'openOutpaint-webUI-extension',
                         'sd-webui-additional-networks', 'sd-webui-aspect-ratio-helper', 'sd-webui-cutoff',
                         'sd-webui-keyframer', 'sd-webui-model-converter', 'sd-webui-photopea-embed',
                         'sd-webui-regional-prompter', 'sd-webui-runtime-block-merge', 'sd-webui-segment-anything',
                         'sd-webui-text2video', 'sdweb-merge-block-weighted-gui', 'sd_save_intermediate_images',
                         'Stable-Diffusion-Webui-Civitai-Helper', 'stable-diffusion-webui-daam',
                         'stable-diffusion-webui-dataset-tag-editor', 'stable-diffusion-webui-depthmap-script',
                         'stable-diffusion-webui-wildcards', 'Styles-Editor', 'ultimate-upscale-for-automatic1111',
                         'vladmandic-WD14-Tagger']
02:21:26-109636 INFO     Verifying requirements
02:21:26-120381 INFO     Verifying packages
02:21:26-122334 INFO     Installing repositories
02:21:29-837539 INFO     Installing submodules
02:21:32-000184 INFO     Updating submodules
02:22:55-114689 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR',
                         'a1111-sd-webui-tagcomplete', 'ABG_extension', 'infinite-zoom-automatic1111-webui',
                         'openOutpaint-webUI-extension', 'sd-webui-additional-networks',
                         'sd-webui-aspect-ratio-helper', 'sd-webui-cutoff', 'sd-webui-keyframer',
                         'sd-webui-model-converter', 'sd-webui-photopea-embed', 'sd-webui-regional-prompter',
                         'sd-webui-runtime-block-merge', 'sd-webui-segment-anything', 'sd-webui-text2video',
                         'sdweb-merge-block-weighted-gui', 'sd_save_intermediate_images',
                         'Stable-Diffusion-Webui-Civitai-Helper', 'stable-diffusion-webui-daam',
                         'stable-diffusion-webui-dataset-tag-editor', 'stable-diffusion-webui-depthmap-script',
                         'stable-diffusion-webui-wildcards', 'Styles-Editor', 'ultimate-upscale-for-automatic1111',
                         'vladmandic-WD14-Tagger']
02:22:55-125432 INFO     Updating Wiki
02:22:55-905656 INFO     Extension preload: 0.0s C:\Vlad\Vla\automatic\extensions-builtin
02:22:55-910537 INFO     Extension preload: 0.0s C:\Vlad\Vla\automatic\extensions
02:22:55-929090 INFO     Server arguments: ['--autolaunch']
No module 'xformers'. Proceeding without it.
02:23:04-172713 INFO     Libraries loaded
02:23:04-175699 INFO     Using data path: C:\Vlad\Vla\automatic
02:23:04-188336 INFO     Available VAEs: G:\SD_Model\VAE 11
02:23:04-284034 INFO     Available models: G:\SD_Model\Ckpt 155
02:23:08-053712 INFO     ControlNet v1.1.224

### URL link of the extension

https://github.com/kabachuha/sd-webui-text2video

### URL link of the issue reported in the extension repository

https://github.com/kabachuha/sd-webui-text2video/discussions/178

### Acknowledgements

- [x] I have read the above and searched for existing issues

**Comment by ShmuelRonen** [comment]
I encountered the same problem and tried the text2video model on automatic1111 and there it worked without any problem.

Probably it is related to the need to use xformers that are not activated normally.

**Comment by vladmandic** [comment]
No, it's because extension checks cmdflags which are different. Extension should check if xformers are enabled or not, not check cmdflags from core app ever. 

I cannot support extensions that do things the wrong way and hard code things that prevent any kind of change ever.

**Comment by ShmuelRonen** [comment]
> No, it's because extension checks cmdflags which are different. Extension should check if xformers are enabled or not, not check cmdflags from core app ever.
> 
> I cannot support extensions that do things the wrong way and hard code things that prevent any kind of change ever.

Will proactively running of xformers make the extension work?

**Comment by vladmandic** [comment]
No, it has nothing to do if xformers are installed or enabled, extension doesn't actually check for that.
What fails is extension check of core repo command line flags - which it should never do. And that fails because flags are clearly different.

**Comment by kabachuha** [comment]
Added defaulting to cmd_opts and fixed the incompatibility in https://github.com/kabachuha/sd-webui-text2video/commit/9a1f8fbb403b69aa4dbd2669127f3c38ec1c4c40

**Comment by vladmandic** [comment]
thanks, that adds compatibility, but as an advice - parsing command line flags to determine cross-optimization is not a good idea, especially since built-in clean solution already exists - search for `optimization_method` - its set when cross-optimization is applied and its both here and in a1111 (i've added it there a while back).

https://github.com/vladmandic/automatic/blob/c90e9965c7b6b4d90bb3d63e3c58352309228e5c/modules/sd_hijack.py#L199
