### ISSUE TITLE
controlNet Installed and updated but not showing in Vlad

### ISSUE THREAD

**Issue by Koguist4** [vladmandic/automatic#1496]
### Issue Description

I copied the URL for the manual install and nothing appened, Somehow the extention is installed at \automatic\extensions as sd-webui-controlnet. Im doing something wrong. Cant see it under FromText or FromImage tabs in VLAD.

Thanks

### Version Platform Description

22:31:12-049121 INFO     Starting SD.Next
22:31:12-053586 INFO     Python 3.10.6 on Windows
22:31:12-139997 INFO     Version: 2a664b1b Tue Jun 6 17:32:34 2023 -0400
22:31:12-682919 INFO     Latest published version: b80fcca960eedc292dc3bc1372abc1af80c0fb34 2023-06-22T17:05:26Z
22:31:12-686220 INFO     Setting environment tuning
22:31:12-691675 INFO     nVidia CUDA toolkit detected
22:31:14-242205 INFO     Torch 2.0.1+cu118
22:31:14-268116 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
22:31:14-270909 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24575 Arch (8, 6) Cores 82
22:31:14-274381 INFO     Verifying requirements
22:31:14-292024 INFO     Installing packages
22:31:14-378272 INFO     Running setup
22:31:14-380305 INFO     Installing repositories
22:31:18-775083 INFO     Installing submodules

      0 [main] sh 1295 dofork: child -1 - forked process 33180 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
      0 [main] sh 1297 child_copy: dll data read copy failed, 0x127D000..0x1289FB0, done 0, windows pid 16608, Win32 error 299
1150978 [main] sh 1295 dofork: child -1 - forked process 16608 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
3302701 [main] sh 1295 dofork: child -1 - forked process 27988 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
      0 [main] sh 1299 dofork: child -1 - forked process 10344 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
      0 [main] sh 1301 child_copy: dll data read copy failed, 0x123D000..0x1249FB0, done 0, windows pid 22988, Win32 error 299
1173267 [main] sh 1299 dofork: child -1 - forked process 22988 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
      0 [main] sh 1302 child_copy: dll data read copy failed, 0x11DD000..0x11E9FB0, done 0, windows pid 4716, Win32 error 299
3350121 [main] sh 1299 dofork: child -1 - forked process 4716 died unexpectedly, retry 0, exit code 0xC0000005, errno 11      0 [main] sh 1303 child_copy: dll data read copy failed, 0x124D000..0x1259FB0, done 0, windows pid 28864, Win32 error 299
7524378 [main] sh 1299 dofork: child -1 - forked process 28864 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
15690161 [main] sh 1299 dofork: child -1 - forked process 10388 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
      0 [main] sh 1306 child_copy: dll data read copy failed, 0x123D000..0x1249FB0, done 0, windows pid 32032, Win32 error 299
23394859 [main] sh 1295 dofork: child -1 - forked process 32032 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
24546496 [main] sh 1295 dofork: child -1 - forked process 32240 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
26696171 [main] sh 1295 dofork: child -1 - forked process 19540 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
      0 [main] sh 1309 child_copy: dll data read copy failed, 0x123D000..0x1249FB0, done 0, windows pid 3240, Win32 error 299
30848751 [main] sh 1295 dofork: child -1 - forked process 3240 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
      0 [main] sh 1311 child_copy: dll data read copy failed, 0x129D000..0x12A9FB0, done 0, windows pid 29568, Win32 error 299
      0 [main] sh 1310 dofork: child -1 - forked process 29568 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
      0 [main] sh 1312 child_copy: dll data read copy failed, 0x11DD000..0x11E9FB0, done 0, windows pid 31452, Win32 error 299
1157896 [main] sh 1310 dofork: child -1 - forked process 31452 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
      0 [main] sh 1313 child_copy: dll data read copy failed, 0x12DD000..0x12E9FB0, done 0, windows pid 26600, Win32 error 299
3310518 [main] sh 1310 dofork: child -1 - forked process 26600 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
      0 [main] sh 1314 child_copy: dll data read copy failed, 0x122D000..0x1239FB0, done 0, windows pid 32720, Win32 error 299
7463843 [main] sh 1310 dofork: child -1 - forked process 32720 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
      0 [main] sh 1315 child_copy: dll data read copy failed, 0x11FD000..0x1209FB0, done 0, windows pid 22716, Win32 error 299
15622271 [main] sh 1310 dofork: child -1 - forked process 22716 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
      0 [main] sh 1316 child_copy: dll data read copy failed, 0x120D000..0x1219FB0, done 0, windows pid 31768, Win32 error 299
54808902 [main] sh 1295 dofork: child -1 - forked process 31768 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
      0 [main] sh 1317 child_copy: dll data read copy failed, 0x12AD000..0x12B9FB0, done 0, windows pid 27988, Win32 error 299
55963644 [main] sh 1295 dofork: child -1 - forked process 27988 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
58112031 [main] sh 1295 dofork: child -1 - forked process 16380 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
62263213 [main] sh 1295 dofork: child -1 - forked process 32760 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
      0 [main] sh 1320 child_copy: dll data read copy failed, 0x121D000..0x1229FB0, done 0, windows pid 2012, Win32 error 299
70435102 [main] sh 1295 dofork: child -1 - forked process 2012 died unexpectedly, retry 0, exit code 0xC0000005, errno 11
22:32:29-520542 ERROR    Error running git: None / submodule
      0 [main] sh 1586 dofork: child -1 - forked process 33060 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
1158572 [main] sh 1586 dofork: child -1 - forked process 26332 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
3307748 [main] sh 1586 dofork: child -1 - forked process 14416 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
7460792 [main] sh 1586 dofork: child -1 - forked process 31088 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
15614785 [main] sh 1586 dofork: child -1 - forked process 26304 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
22:32:45-445416 ERROR    Error running git: None / submodule --quiet update --init --recursive
22:32:45-448887 INFO     Updating submodules
22:32:45-639380 INFO     Disabled extensions-builtin: ['a1111-sd-webui-haku-img', 'sd-model-organizer', 'animator_extension']
22:32:45-642418 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
22:32:48-034159 INFO     Disabled extensions: ['a1111-sd-webui-haku-img', 'sd-model-organizer', 'animator_extension']
22:32:48-037386 INFO     Enabled extensions: ['model-keyword', 'sd-3dmodel-loader', 'sd-infinity-grid-generator-script', 'sd-model-downloader',
                         'sd-webui-3d-open-pose-editor', 'SD-WebUI-BatchCheckpointPrompt', 'sd-webui-color-enhance', 'sd-webui-infinite-image-browsing',
                         'sd-webui-inpaint-anything', 'sd-webui-openpose-editor', 'sd-webui-prompt-all-in-one', 'sd-webui-roop', 'sd-webui-supermerger',
                         'stable-diffusion-aws-extension', 'stable-diffusion-webui-model-toolkit', 'Styles-Editor']
22:33:29-270957 ERROR    Error running extension installer: F:\Vlad 1111\automatic\extensions\stable-diffusion-aws-extension\install.py
22:33:31-600560 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111',
                         'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR', 'model-keyword', 'sd-3dmodel-loader',
                         'sd-infinity-grid-generator-script', 'sd-model-downloader', 'sd-webui-3d-open-pose-editor', 'SD-WebUI-BatchCheckpointPrompt',
                         'sd-webui-color-enhance', 'sd-webui-infinite-image-browsing', 'sd-webui-inpaint-anything', 'sd-webui-openpose-editor',
                         'sd-webui-prompt-all-in-one', 'sd-webui-roop', 'sd-webui-supermerger', 'stable-diffusion-aws-extension',
                         'stable-diffusion-webui-model-toolkit', 'Styles-Editor']
22:33:31-608211 INFO     Updating Wiki
22:33:31-610195 WARNING  Setup complete with errors: 3
22:33:31-611188 WARNING  See log file for more details: F:\Vlad 1111\automatic\webui.log
22:33:31-615991 INFO     Extension preload: 0.0s F:\Vlad 1111\automatic\extensions-builtin
22:33:31-620051 INFO     Extension preload: 0.0s F:\Vlad 1111\automatic\extensions
22:33:31-621585 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
22:33:37-542976 INFO     Libraries loaded
22:33:37-547417 INFO     Using data path: F:\Vlad 1111\automatic
22:33:37-551611 INFO     Available VAEs: F:\Vlad 1111\automatic\models\VAE 4
22:33:37-574681 INFO     Available models: F:\Vlad 1111\automatic\models\Stable-diffusion 12
Model Downloader required aria2c, see tutorial https://www.youtube.com/watch?v=JnWQST4ay_E
Model Downloader v1.0.6 fixed
Checking Directories...
all Directories already Created.
22:33:39-977141 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
Loading weights: F:\Vlad 1111\automatic\models\Stable-diffusion\epi25dphotogodess_v3.safetensors ---------------------------------------- 0.0/2.1 GB -:--:--
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
22:33:40-626032 INFO     Model created from config: F:\Vlad 1111\automatic\configs\v1-inference.yaml
22:33:42-610265 INFO     Applying scaled dot product cross attention optimization
22:33:42-645953 INFO     Embeddings loaded: 1 ['bad_prompt_version2']
22:33:42-651057 INFO     Model loaded in 2.7s (load=0.2s create=0.4s apply=0.5s vae=0.8s move=0.7s)
22:33:42-803055 INFO     Model load finished: {'ram': {'used': 2.93, 'total': 63.95}, 'gpu': {'used': 3.3, 'total': 24.0}, 'retries': 0, 'oom': 0}
sd-webui-prompt-all-in-one background API service started successfully.
2023-06-22 22:33:43,337 - roop - INFO - roop v0.0.2
2023-06-22 22:33:43,338 - roop - INFO - roop v0.0.2
22:33:44-125625 INFO     Loading UI theme: name=black-orange style=Auto
2023-06-22 22:33:44,156 - roop - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/s0md3v/sd-webui-roop/
start refreshing resource list from cloud
An error occurred while updating SageMaker endpoints: Invalid URL '/inference/list-endpoint-deployment-jobs': No scheme supplied. Perhaps you meant https:///inference/list-endpoint-deployment-jobs?
Error refresh all models: Invalid URL 'checkpoints?status=Active&types=Stable-diffusion': No scheme supplied. Perhaps you meant https://checkpoints?status=Active&types=Stable-diffusion?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=embeddings': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=embeddings?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=Lora': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=Lora?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=hypernetworks': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=hypernetworks?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=ControlNet': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=ControlNet?
Exception occurred when fetching inference_job_ids
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=Stable-diffusion': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=Stable-diffusion?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=embeddings': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=embeddings?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=hypernetworks': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=hypernetworks?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=ControlNet': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=ControlNet?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=Stable-diffusion': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=Stable-diffusion?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=Stable-diffusion': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=Stable-diffusion?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=Stable-diffusion': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=Stable-diffusion?
2023-06-22 22:33:44,247 - roop - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/s0md3v/sd-webui-roop/
start refreshing resource list from cloud
An error occurred while updating SageMaker endpoints: Invalid URL '/inference/list-endpoint-deployment-jobs': No scheme supplied. Perhaps you meant https:///inference/list-endpoint-deployment-jobs?
Error refresh all models: Invalid URL 'checkpoints?status=Active&types=Stable-diffusion': No scheme supplied. Perhaps you meant https://checkpoints?status=Active&types=Stable-diffusion?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=embeddings': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=embeddings?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=Lora': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=Lora?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=hypernetworks': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=hypernetworks?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=ControlNet': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=ControlNet?
Exception occurred when fetching inference_job_ids
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=Stable-diffusion': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=Stable-diffusion?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=embeddings': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=embeddings?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=hypernetworks': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=hypernetworks?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=ControlNet': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=ControlNet?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=Stable-diffusion': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=Stable-diffusion?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=Stable-diffusion': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=Stable-diffusion?
Error fetching model list: Invalid URL '/checkpoints?status=Active&types=Stable-diffusion': No scheme supplied. Perhaps you meant https:///checkpoints?status=Active&types=Stable-diffusion?
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
22:33:49-499867 INFO     Local URL: http://....................
22:33:49-502062 INFO     API Docs: http://.............................
22:33:49-504046 INFO     Initializing middleware
22:33:50-003021 INFO     Startup time: 18.4s (torch=3.3s gradio=1.0s libraries=1.5s scripts=6.3s onchange=0.1s ui=2.9s launch=2.4s scripts
                         app_started_callback=0.1s checkpoint=0.4s)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
And now go back and remove it as controlnet already ships with this repo by default. You just installed it once again and created conflict.

**Comment by Koguist4** [comment]
so I have to renmove it just deleting the sd-webui-controlnet?

**Comment by vladmandic** [comment]
yes. remove from `extensions` folder.

**Comment by Koguist4** [comment]
Sorry I just get time to retake this. But deleted that folder and still the same. Also restarted and nothing happend. my objetive is enable the option of OpenPose but if I dont see the ControlNet.
Also I have in the automatic\models\ControlNet\ControlNet-v1-1 
![ControlNet v1-1](https://github.com/vladmandic/automatic/assets/137462950/fde808ef-de08-45b6-a9ea-4a911fcf0a76)

I dont know if this is also giving me error.

**Comment by vladmandic** [comment]
your original log makes no sense - if you're running under windows, then what is this? it looks like you're attempting to run under some 3rd party unsupported shell. and there are tons of other extensions that may or may not interfere.

can i ask for a clean install and open a new issue as this one is closed due to known root cause.

**Comment by Koguist4** [comment]
yeah I could do that, I can preserve the models folder if I do a clean install?

**Comment by vladmandic** [comment]
yes, you can copy your old models folder over to the new install.

**Comment by TheElementSwe** [comment]
I got same problem, I downloaded a new version of vladmandic and saw that controlnet is off, for some reason I can't turn it back on 🤔

![01](https://github.com/vladmandic/automatic/assets/132387755/5918a638-fddb-47b8-8a27-e9f5bf86eaee)
![02](https://github.com/vladmandic/automatic/assets/132387755/feacfdcd-2e0b-4d50-9599-10d833213889)

**Comment by vladmandic** [comment]
Replying on 8 months old thread is NEVER a good idea.
And this specific question has been asked-and-answered many times.

**Comment by TheElementSwe** [comment]
> Replying on 8 months old thread is NEVER a good idea. And this specific question has been asked-and-answered many times.

Okay, then maybe I should start a new thread and ask the same color again, then you can close the thread if it should not be open anymore!!!

**Comment by vladmandic** [comment]
Search for answers first

**Comment by TheElementSwe** [comment]
> Search for answers first

I want to do it, then I get the best advice too

**Comment by iamsuper123** [comment]
hey can someone post the link of the new thread? thanks
