### ISSUE TITLE
[Issue]: Default Agent Scheduler hotkey interferes with prompt.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1498]
### Issue Description

The default Agent Scheduler hotkey "Shift+E" interferes when entering a prompt. Attempting to type a capital 'E' while editing a prompt enqueues the generation.

Perhaps the default should be Ctrl+E.

### Version Platform Description

9a7c7655, win10, chrome

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
Use extension template and create issue upstream.

**Comment by brknsoul** [comment]
It's a built-in extension, though?

**Comment by brunogcar** [comment]
personally i would suggest `shift + enter` to queue
as i normally use `ctrl + enter`  to generate

btw he did a good job with settings 

![settings](https://github.com/vladmandic/automatic/assets/53648/d78177ca-5061-4f19-ae71-419357c3efbc)

**Comment by vladmandic** [comment]
> It's a built-in extension, though?

Doesn't matter. 

> Apparently the author is already aware of the situtation.

If it's an extension issue, either convert this to extension template and link with upstream issue or close.
