### ISSUE TITLE
[Issue]: cannot install ROOP: ERROR Error running extension installer: D:\vlad\automatic\extensions\sd-webui-roop\install.py

### ISSUE THREAD

**Issue by StableInfo** [vladmandic/automatic#1499]
### Issue Description

All the details is here: https://github.com/s0md3v/sd-webui-roop/issues/79
with their answer.

### Version Platform Description

firefox.
First version of vladUI (never updated)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
Close and refile using extension template.
And describe the issue, stating all the details are somewhere else doesn't help.

**Comment by vladmandic** [comment]
Btw, I took a look at the issue upstream and this extension installer.
Author apparently refuses to acknololedge the issue (which is his choice) and extension installer is doing really bad stuff that installer should not be doing. Too bad, seems like a potentially really interesting extension, but this installer needs a rewrite, not a quick fix.

**Comment by StableInfo** [comment]
Thank you!

**Comment by cleverestx** [comment]
@vladmandic - What about this version possibly? Would this work with Vladmandic okay? https://github.com/Gourieff/sd-webui-roop-nsfw

**Comment by cleverestx** [comment]
Sadly it doesn't seem to install, I get:
![image](https://github.com/vladmandic/automatic/assets/28905253/6638065e-47fc-4908-bf07-427de6e6d2e8), says installed, reboot it shows it's installed, listing an update button (fails to find update), but it's not loaded in the UI

**Comment by cleverestx** [comment]
> Helo @cleverestx were you able to solve it?

Sadly no; there appears to be a fundamental incompatibility.  @vladmandic indicated this extension does bad things, but I don't know what that means and if it's surmountable, but I really, really love to use this extension without having to also install automatic1111 for one extension. (ugh)

**Comment by vladmandic** [comment]
its been a while since ext was released, i'll take a second look.

**Comment by cleverestx** [comment]
Thank you so much sir!!

**Comment by vladmandic** [comment]
original author basically has "i don't care" attitude, cant work with that.
but there seem to be number of forks that are updated, check out <https://github.com/Gourieff/sd-webui-roop-nsfw>
i have not tried it, but it does have sdnext install procedure in its readme.
