### ISSUE TITLE
[Issue]: Interrogate CLIP <error>

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#150]
### Issue Description

Wanted to interrogate an image in the img2img tab and got an <error>:

load checkpoint from I:\Super SD 2.0\automatic\models\BLIP\model_base_caption_capfilt_large.pth
interrogate: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\modules\interrogate.py:194 in interrogate                                                 │
│                                                                                                                     │
│   193 │   │   │                                                                                                     │
│ > 194 │   │   │   self.load()                                                                                       │
│   195                                                                                                               │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\modules\interrogate.py:128 in load                                                        │
│                                                                                                                     │
│   127 │   │   if self.clip_model is None:                                                                           │
│ > 128 │   │   │   self.clip_model, self.clip_preprocess = self.load_clip_model()                                    │
│   129 │   │   │   if not shared.cmd_opts.no_half and not self.running_on_cpu:                                       │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\modules\interrogate.py:112 in load_clip_model                                             │
│                                                                                                                     │
│   111 │   │   else:                                                                                                 │
│ > 112 │   │   │   model, preprocess = clip.load(clip_model_name, download_root=shared.opts.cli                      │
│   113                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: module 'clip' has no attribute 'load'

### Version Platform Description

Win10, Firefox 106
Version: ed8819b8 Sat Apr 15 10:28:31 2023 -0400

**Comment by vladmandic** [comment]
to confirm: to to `from image` tab, load image, click on `interrogate clip` button? i just tried and cannot reproduce.

**Comment by carlosmachina** [comment]
I've managed to reproduce the same error, but the application is probably in an unexpected state since I've tried to interrogate after launching to test #151 

I think this could be a side effect from the git pull shenanigans.

![image](https://user-images.githubusercontent.com/8450363/232242345-c009b4f9-e08f-4667-87b3-1fdacd8bd494.png)

**Comment by carlosmachina** [comment]
> to confirm: to to `from image` tab, load image, click on `interrogate clip` button? i just tried and cannot reproduce.

And my test was exactly with this procedure:
Opened UI -> "From Image" -> Uploaded a picture -> Clicked "Interrogate CLIP"

![image](https://user-images.githubusercontent.com/8450363/232242452-6eede57c-0ba3-4d92-bd66-01bc8abdcfa1.png)

**Comment by Woisek** [comment]
> to confirm: to to `from image` tab, load image, click on `interrogate clip` button? i just tried and cannot reproduce.

Exactly.

![Zwischenablagebild](https://user-images.githubusercontent.com/122026301/232238251-b67cde40-0fb5-4ed3-89a1-36cb28566485.jpg)

**Comment by carlosmachina** [comment]
> I think this could be a side effect from the git pull shenanigans.

No dice. #152 fixed #151 but had no effect on this, tested with same result.

**Comment by vladmandic** [comment]
what does your `pip show clip` show?

**Comment by Woisek** [comment]
Mine here:

I:\Super SD 2.0\automatic>pip show clip
Name: clip
Version: 1.0
Summary:
Home-page:
Author: OpenAI
Author-email:
License:
Location: f:\programme\python310\lib\site-packages
Requires: ftfy, regex, torch, torchvision, tqdm
Required-by:

I:\Super SD 2.0\automatic>

**Comment by carlosmachina** [comment]
> what does your `pip show clip` show?

```
pip show clip
Name: clip
Version: 0.2.0
Summary: A CLI clipboard manager
Home-page: http://procrastinatingdev.com/clip/
Author: Adam McKerlie
Author-email: adammckerlie@gmail.com
License: Copyright (C) 2012 Adam McKerlie [...]
Location: d:\ai\apps\automatic\venv\lib\site-packages
Requires:
Required-by:
```

Ran it after activating the repo's Venv
(I've shortened the License info to save some space on this comment)

**Comment by vladmandic** [comment]
omg, thats a squatted package from pypi, thats not the actual clip we need!
ok, posted new version with added a check to setup.py for a very specific clip package, so it will install it automatically.
but you need to uninstall this one first: `pip uninstall clip`

**Comment by mykeehu** [comment]
Ok, I did the uninstall, but the next time I start it does not reinstall:

```
Unloading xFormers
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ H:\Stable-Diffusion-Automatic\automatic\launch.py:100 in <module>           │
│                                                                             │
│    99     logging.disable(logging.INFO)                                     │
│ > 100     import webui                                                      │
│   101     webui.webui()                                                     │
│                                                                             │
│ H:\Stable-Diffusion-Automatic\automatic\webui.py:27 in <module>             │
│                                                                             │
│    26 import ldm.modules.encoders.modules # pylint: disable=W0611,C0411     │
│ >  27 from modules import extra_networks, ui_extra_networks_checkpoints # p │
│    28 from modules import extra_networks_hypernet, ui_extra_networks_hypern │
│                                                                             │
│ H:\Stable-Diffusion-Automatic\automatic\modules\ui_extra_networks_checkpoin │
│ ts.py:5 in <module>                                                         │
│                                                                             │
│    4                                                                        │
│ >  5 from modules import shared, ui_extra_networks, sd_models               │
│    6                                                                        │
│                                                                             │
│ H:\Stable-Diffusion-Automatic\automatic\modules\ui_extra_networks.py:11 in  │
│ <module>                                                                    │
│                                                                             │
│    10 from modules import shared                                            │
│ >  11 from modules.images import read_info_from_image                       │
│    12 from modules.generation_parameters_copypaste import image_from_url_te │
│                                                                             │
│ H:\Stable-Diffusion-Automatic\automatic\modules\images.py:16 in <module>    │
│                                                                             │
│    15                                                                       │
│ >  16 from modules import sd_samplers, shared, script_callbacks, errors     │
│    17 from modules.shared import opts, cmd_opts # pylint: disable=unused-im │
│                                                                             │
│ H:\Stable-Diffusion-Automatic\automatic\modules\sd_samplers.py:1 in         │
│ <module>                                                                    │
│                                                                             │
│ >  1 from modules import sd_samplers_compvis, sd_samplers_kdiffusion, share │
│    2                                                                        │
│                                                                             │
│ H:\Stable-Diffusion-Automatic\automatic\modules\sd_samplers_kdiffusion.py:4 │
│ in <module>                                                                 │
│                                                                             │
│     3 import torch                                                          │
│ >   4 import k_diffusion.sampling                                           │
│     5 from modules import prompt_parser, devices, sd_samplers_common        │
│                                                                             │
│ H:\Stable-Diffusion-Automatic\automatic\repositories\k-diffusion\k_diffusio │
│ n\__init__.py:1 in <module>                                                 │
│                                                                             │
│ > 1 from . import augmentation, config, evaluation, external, gns, layers,  │
│   2 from .layers import Denoiser                                            │
│                                                                             │
│ H:\Stable-Diffusion-Automatic\automatic\repositories\k-diffusion\k_diffusio │
│ n\evaluation.py:6 in <module>                                               │
│                                                                             │
│     5 from cleanfid.inception_torchscript import InceptionV3W               │
│ >   6 import clip                                                           │
│     7 from resize_right import resize                                       │
└─────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'clip'
```

**Comment by vladmandic** [comment]
run `webui --upgrade` to force package checks and then check resulting `setup.log`, it should tell you there what happened (look immediately after line saying "installing packages")
