### ISSUE TITLE
[Issue]: train.py requires older accelerate and diffusers

### ISSUE THREAD

**Issue by JoelBrace** [vladmandic/automatic#1500]
### Issue Description

`preparing accelerator
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/joel/StableDiffusion/automatic/cli/train.py:395 in <module>            │
│                                                                              │
│   394         if args.type == 'lora' or args.type == 'lyco' or args.type ==  │
│ ❱ 395             train_lora()                                               │
│   396     except KeyboardInterrupt:                                          │
│                                                                              │
│ /home/joel/StableDiffusion/automatic/cli/train.py:255 in train_lora          │
│                                                                              │
│   254     print(options.lora)                                                │
│ ❱ 255     train_network.train(options.lora)                                  │
│   256     if args.type == 'lyco':                                            │
│                                                                              │
│ /home/joel/StableDiffusion/automatic/cli/../modules/lora/train_network.py:16 │
│ 1 in train                                                                   │
│                                                                              │
│   160     print("preparing accelerator")                                     │
│ ❱ 161     accelerator, unwrap_model = train_util.prepare_accelerator(args)   │
│   162     is_main_process = accelerator.is_main_process                      │
│                                                                              │
│ /home/joel/StableDiffusion/automatic/cli/../modules/lora/library/train_util. │
│ py:3068 in prepare_accelerator                                               │
│                                                                              │
│   3067                                                                       │
│ ❱ 3068     accelerator = Accelerator(                                        │
│   3069         gradient_accumulation_steps=args.gradient_accumulation_steps, │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: Accelerator.__init__() got an unexpected keyword argument 
'logging_dir'
`

Getting this error when runnning train.py with the following criteria.

python3 cli/train.py --type lora --name pokemon --tag pokemon --input datasets/pokemon

any idea where I am going wrong with this?

### Version Platform Description

01:34:21-852750 INFO     Starting SD.Next                                       
01:34:21-856975 INFO     Python 3.10.6 on Linux                                 
01:34:21-964389 INFO     Version: 4867dafa Fri Jun 23 08:00:51 2023 -0400       
01:34:22-469838 INFO     AMD ROCm toolkit detected                              
01:34:28-848483 INFO     Torch 2.1.0.dev20230623+rocm5.5                        
01:34:36-255935 INFO     Torch backend: AMD ROCm HIP 5.5.30201-c1741e9b         
01:34:36-258497 INFO     Torch detected GPU: Radeon RX 7900 XT VRAM 20464 Arch  
                         (11, 0) Cores 42                                       
01:34:36-580276 WARNING  Modified files: ['cli/train.py', 'installer.py',       
                         'modules/lora', 'requirements.txt', 'datasets/']       
01:34:36-598070 INFO     Enabled extensions-builtin: ['sd-webui-controlnet',    
                         'LDSR', 'stable-diffusion-webui-rembg',                
                         'multidiffusion-upscaler-for-automatic1111',           
                         'sd-dynamic-thresholding', 'Lora',                     
                         'sd-webui-agent-scheduler', 'ScuNET',                  
                         'clip-interrogator-ext',                               
                         'stable-diffusion-webui-images-browser', 'SwinIR',     
                         'a1111-sd-webui-lycoris', 'sd-extension-system-info']  
01:34:36-608195 INFO     Enabled extensions: []                                 
01:34:36-612370 INFO     No changes detected: Quick launch active               
01:34:36-633345 INFO     Extension preload: 0.0s                                
                         /home/joel/StableDiffusion/automatic/extensions-builtin
01:34:36-638307 INFO     Extension preload: 0.0s                                
                         /home/joel/StableDiffusion/automatic/extensions        
01:34:36-671874 INFO     Server arguments: []

Running with this script:
`TORCH_COMMAND='pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.5'

HSA_OVERRIDE_GFX_VERSION=11.0.0

python3 launch.py
`

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i've added checks to `train.py` so error messages are not cryptic.
also, i'm going to keep this issue open to track any upstream work.

**Comment by vladmandic** [comment]
resolved in dev branch.
