### ISSUE TITLE
[Issue]: sd-webui-agent-schedule

### ISSUE THREAD

**Issue by rayminator2020** [vladmandic/automatic#1502]
### Issue Description

13:05:13-830231 ERROR    executing callback:
                         C:\Users\raymi\AI\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.
                         py ui_tabs_callback: NameError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\raymi\AI\automatic\modules\script_callbacks.py:161 in ui_tabs_callback                                      │
│                                                                                                                      │
│   160 │   │   │   t0 = time.time()                                                                                   │
│ ❱ 161 │   │   │   res += c.callback() or []                                                                          │
│   162 │   │   │   timer(t0, c.script, 'ui_tabs')                                                                     │
│                                                                                                                      │
│ C:\Users\raymi\AI\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:254 in on_ui_tab   │
│                                                                                                                      │
│   253 │   global initialized                                                                                         │
│ ❱ 254 │   if not initialized:                                                                                        │
│   255 │   │   initialized = True                                                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
NameError: name 'initialized' is not defined

### Version Platform Description

 Starting SD.Next
13:04:56-687502 INFO     Python 3.10.10 on Windows
13:04:56-722583 INFO     Version: 4867 dafa Fri Jun 23 08:00:51 2023 -0400
13:04:57-014726 INFO     nVidia CUDA toolkit detected
13:04:58-453829 INFO     Torch 2.0.1+cu118
13:04:58-479900 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
13:04:58-481900 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
please refile using extensions template (and fill all required data on that form)
