### ISSUE TITLE
[Extension]: sd-webui-agent-scheduler error after latest update

### ISSUE THREAD

**Issue by LoveNug** [vladmandic/automatic#1504]
### sd-webui-agent-scheduler error after latedt update

Suddenly began getting an error message referencing built-in sd-webui-agent-scheduler extension after the latest update (4867daf). I also ran an unmodified fresh install and got the same error.

13:37:20-480318 ERROR    executing callback:
                         C:\SDWebUI\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py
                         ui_tabs_callback: NameError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\SDWebUI\automatic\modules\script_callbacks.py:161 in ui_tabs_callback                                            │
│                                                                                                                     │
│   160 │   │   │   t0 = time.time()                                                                                  │
│ > 161 │   │   │   res += c.callback() or []                                                                         │
│   162 │   │   │   timer(t0, c.script, 'ui_tabs')                                                                    │
│                                                                                                                     │
│ C:\SDWebUI\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:254 in on_ui_tab         │
│                                                                                                                     │
│   253 │   global initialized                                                                                        │
│ > 254 │   if not initialized:                                                                                       │
│   255 │   │   initialized = True                                                                                    │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
NameError: name 'initialized' is not defined

### Version Platform Description

Windows 10 Pro 64-bit build 19044.3086
Python 3.10.6 on Windows
Version: 4867dafa Fri Jun 23 08:00:51 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3070 VRAM 8191 Arch (8, 6) Cores 46

### URL link of the extension

https://github.com/ArtVentureX/sd-webui-agent-scheduler

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by brunogcar** [comment]
I cant reproduce,  works fine here

few things to make easier when vlad checks that
1. any other extensions installed besides builtin ones?
2. run with --debug  and post log as code
3.  URL link of the issue reported in the extension repository
that means when you post an extension issue, its required to make a post on extension repo, most of times, vlad cant do anything about as its not an issue with SD Next

**Comment by LoveNug** [comment]
Closing this issue because for some reason I cannot reproduce the error today after several attempts.
