### ISSUE TITLE
[Feature] Console Viewport

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#1509]
### Discussed in https://github.com/vladmandic/automatic/discussions/1508

<div type='discussions-op-text'>

<sup>Originally posted by **Eljoseto** June 25, 2023</sup>
It would be useful to see whats happening in the background without having to bring the actual console, like checking unexpected errors, or some extensions process. just a few lines would be fine.

Is it posible to have a little console viewport in the web interface?</div>

**Comment by vladmandic** [comment]
and that exe would include entire python/git/torch/all dependencies?  
there are attempts of doing that, it nearly-always leads into instant problems.

**Comment by JFronny** [comment]
I think his idea is that if an optional GUI were to be implemented, a second wrapper that automatically adds relevant command line arguments and hides the terminal should be provided for windows users as a more familiar alternative to the terminal

**Comment by vladmandic** [comment]
> a second wrapper that automatically adds relevant command line arguments and hides the terminal should be provided for windows users as a more familiar alternative to the terminal

that's called a windows shortcut? :)
literally, for normal installation there should be no "relevant command line arguments" required by default.
and if you create a shortcut to webui.bat, you have exactly what you want. you can even add `--autolaunch` hide console completely.

but like it says in the master README, this distribution is NOT intended for users that have no idea how to work with terminal. there are far easier distributions to use - so lets not go overboard with simplifications - anything more than already provided webui.bat is not likely going to happen.

**Comment by Aptronymist** [comment]
Funny, I was just thinking about making this five minutes ago and put it on my list. 
What if there was a GUI wrapper around /cli/sdapi.py? A few buttons to execute its functions in case of issues, execute shutdowns/restart/interrupt/skip/stop and see ongoing status info?

**Comment by Aptronymist** [comment]
Something like this maybe?
But would actually function properly in most regards. 😆 (Shutdown works!)
[sdapi_gui.zip](https://github.com/vladmandic/automatic/files/11887779/sdapi_gui.zip)

**Comment by Aptronymist** [comment]
Or... this?
https://github.com/AJpon/a1111-sd-webui-console-log-integrater

**Comment by vladmandic** [comment]
redirecting entire stdout and rendering as server-side hmtl is a nice hack that should never be released in public. not to mention that any kind of auto-update would kill the browser as gradio needs to re-render a lot. and there is no preset size buffer in redirect itself, so running with this would basically just use more and more memory as entire output is in a string stream.

there are better ways of doing it, i might throw something together tomorrow.

**Comment by Eljoseto** [comment]
VladGigaChadMandic, thank you so muck for this feature!
