### ISSUE TITLE
[Issue]: Drastic Reduction in Vram Usage

### ISSUE THREAD

**Issue by Mateous512** [vladmandic/automatic#1511]
### Issue Description

So yesterday I was able to set up SD.Next and get everything working fine. My vram limit before things crashed was around 9.7gb or so. Today after the 06/26/23 update it crashes at around 5gb usage (or there error is 5000000bytes). I'm wondering if something in the update may have done something here. I have an AMD 6650xt for reference. I can't think of anything else that would have cause this issue.

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
There are absolutely no code changes in the last few days that would impact this.

To be on the safe side, I'd suggest to delete config.json to restore settings to default.

Also post debut log leading to error and document exact workflow.

**Comment by Mateous512** [comment]
Yes you are correct. I'm going through and using previous version and I'm still having the same issue, looks like this was coincidental. Thanks!

**Comment by vladmandic** [comment]
If you want to just  ask a question, you can use discussions. But when creating an issue, if full required information is not provided, issue will be closed automatically.

**Comment by Mateous512** [comment]
Ok I understand, I'll perhaps ask there first, I'm not sure exactly how to share that information at the moment (very new to this).

**Comment by Mateous512** [comment]
Ok I will try this, thank you!
