### ISSUE TITLE
[Issue]: Stable Diffusion checkpoint autoload on server start breaks model switcher

### ISSUE THREAD

**Issue by mobilehacker** [vladmandic/automatic#1512]
### Issue Description

Hello! With this setting enabled in Stable diffusion settings, model is still getting loaded, but when selecting another and clicking "generate", it doesnt switch, and continues to use the previous model.
Issue persists in safe mode.

### Version Platform Description

19:32:55-410405 INFO     Starting SD.Next
19:32:55-419405 INFO     Python 3.10.6 on Windows
19:32:55-471914 INFO     Version: 0a49961ba Mon Jun 26 11:01:28 2023 -0400

Windows 11 22H2
Firefox 114.0.2
Python 3.10.6

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
this is very basic functionality, it would be noticed by everyone as soon as the feature was released.
can you show console logs with this sequence - it should be visible model loading and then generate.

**Comment by mobilehacker** [comment]
https://pastebin.com/zNe2E1Jk
same prompt, no change occured, and the image was the same style as the model never changed.
cosplaymix->deliberate->neverending dream

**Comment by mobilehacker** [comment]
First occurence at line 229, no model load indicator.

**Comment by vladmandic** [comment]
ok, so you mean when this function is explicitly disabled (its enabled by default).
that's possible, i'll check.

**Comment by mobilehacker** [comment]
> ok, so you mean when this function is explicitly disabled (its enabled by default). that's possible, i'll check.

Oh, I just noticed that I said enabled instead of disabled... sorry for confusion.

**Comment by vladmandic** [comment]
no worries, but it did confuse me :)
anyhow, fixed...
