### ISSUE TITLE
[Feature]: Add an option to disable rich

### ISSUE THREAD

**Issue by wfjsw** [vladmandic/automatic#1520]
### Feature description

The rich-formatted console enhancement provided by rich is nice in a real console, but is ugly in non-TTY environment, especially when it tries to set a hard wrap when it cannot determine the width of the console. Furthermore, the progress bar provided by rich simply does not render in non-TTY environment. 

So I'd like to have an option (preferably an environment variable) to remove all rich usage (and revert the progressbar to tqdm) across the project.

**Comment by vladmandic** [comment]
logging to console assumes that console is tty and its ok to redirect to null if you don't want it.
logging without control characters exists and is in a separate logging handler that writes to log file.
note that for non-tty, any type of tqdm cannot work as it requires control characters to move char back to overwrite previous output. so what you're asking is to cater to semi-compliant terminals - its either full (assumed for console) or none (assumed for log handler), i really don't see a point of doing something in-between.

**Comment by wfjsw** [comment]
tqdm outputs progress traces when it cannot overwrite, and rich refuses to output anything before it is completed.

**Comment by vladmandic** [comment]
like i said, output to log without any tty requirements already exists. i'm not adding special if/then to use rich.tqdm or tqdm depending on some flag.

**Comment by wfjsw** [comment]
wait what is there rich.tqdm

**Comment by vladmandic** [comment]
sorry, other way around - its `tqdm.rich`. but i'm also using `rich.progress`, not a simple tqdm progress bar.
in either case, this is fyi only. like i said, i will not add special handling since log file handler already exists.
