### ISSUE TITLE
[Extension]: Supermerger extension does not create correct xy grids

### ISSUE THREAD

**Issue by Anashel-RPG** [vladmandic/automatic#1523]
### Issue Description

New version of Vlad1111, the Sequential XY extension seem to have broken. It used to work fine.
![Broken](https://github.com/vladmandic/automatic/assets/36581141/efbe2700-8be0-4b5d-8fc5-e31a91eaad08)

### Version Platform Description

Tested on two differents AWS A10 PGU Server
Windows Server Datacenter 2022. 
2.8GHZ (AMD) 16 GB Ram
GPU Memory; 24 GB
<img width="1197" alt="Screenshot 2023-06-27 at 7 07 05 AM" src="https://github.com/vladmandic/automatic/assets/36581141/d4d1fbc5-53a4-43b6-8df3-fce182c1789c">

### URL link of the extension

https://github.com/hako-mikan/sd-webui-supermerger

### URL link of the issue reported in the extension repository

https://github.com/hako-mikan/sd-webui-supermerger/issues/128

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by Anashel-RPG** [comment]
For anyone with the same problem; Vlad's updates seem to have broken the ability for the extension to get all the data from txt2image tab. ( https://github.com/hako-mikan/sd-webui-supermerger/issues/128#issuecomment-1609314059 ) - They will try to fix it but it may take some time.

**Comment by Anashel-RPG** [comment]
After 110+ combination grid over hours and hours of test, I can confirm it is fixed! :)

**Comment by vladmandic** [comment]
Thanks!
