### ISSUE TITLE
[Issue] Git not working

### ISSUE THREAD

**Issue by Koguist4** [vladmandic/automatic#1527]
### Issue Description

Just installed Vlad from scratch and not added anithing elsa but ControlNet appear in extensions tab but not in the UI. Already restarted trying to check for updates.
Im runing it with webui.bat

Thanks

### Version Platform Description

Creating venv in directory F:\Vlad 1111\VLAD Diffusion\automatic\venv using python "C:\Users\Usuario\AppData\Local\Programs\Python\Python310\python.exe"
Using VENV: F:\Vlad 1111\VLAD Diffusion\automatic\venv
01:43:12-613671 INFO     Starting SD.Next
01:43:12-618108 INFO     Python 3.10.6 on Windows
01:43:12-714723 INFO     Version: c90e9965 Tue Jun 27 11:49:29 2023 -0400
01:43:12-800383 INFO     nVidia CUDA toolkit detected
01:43:12-814317 INFO     Installing package: torch torchvision --index-url https://download.pytorch.org/whl/cu118
01:45:45-926690 INFO     Torch 2.0.1+cu118
01:45:46-189253 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
01:45:46-192229 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24575 Arch (8, 6) Cores 82
01:45:46-194710 INFO     Installing package: tensorflow==2.12.0
01:46:10-258958 INFO     Verifying requirements
01:46:10-261520 INFO     Installing package: addict
01:46:11-244454 INFO     Installing package: aenum
01:46:12-477939 INFO     Installing package: aiohttp
01:46:16-667927 INFO     Installing package: anyio
01:46:18-004052 INFO     Installing package: appdirs
01:46:18-987653 INFO     Installing package: astunparse
01:46:20-524352 INFO     Installing package: bitsandbytes
01:46:25-159974 INFO     Installing package: blendmodes
01:46:27-775005 INFO     Installing package: clean-fid
01:46:35-342360 INFO     Installing package: easydev
01:46:37-112681 INFO     Installing package: extcolors
01:46:38-470115 INFO     Installing package: facexlib
01:46:54-152444 INFO     Installing package: filetype
01:46:55-234065 INFO     Installing package: future
01:46:56-856630 INFO     Installing package: gdown
01:46:58-325103 INFO     Installing package: gfpgan
01:47:14-975541 INFO     Installing package: GitPython
01:47:17-656988 INFO     Installing package: httpcore
01:47:19-147532 INFO     Installing package: inflection
01:47:21-176278 INFO     Installing package: jsonmerge
01:47:22-985949 INFO     Installing package: kornia
01:47:26-815574 INFO     Installing package: lark
01:47:28-378686 INFO     Installing package: lmdb
01:47:29-573552 INFO     Installing package: lpips
01:47:31-024021 INFO     Installing package: omegaconf
01:47:33-300436 INFO     Installing package: open-clip-torch
01:47:39-066949 INFO     Installing package: opencv-contrib-python
01:47:41-971007 INFO     Installing package: piexif
01:47:46-171216 INFO     Installing package: Pillow
01:47:48-552032 INFO     Installing package: psutil
01:47:50-380788 INFO     Installing package: pyyaml
01:47:51-754903 INFO     Installing package: realesrgan
01:47:53-568485 INFO     Installing package: resize-right
01:47:55-098459 INFO     Installing package: rich
01:47:56-480000 INFO     Installing package: safetensors
01:47:57-899093 INFO     Installing package: scipy
01:47:59-317009 INFO     Installing package: tb_nightly
01:48:01-026312 INFO     Installing package: toml
01:48:02-582265 INFO     Installing package: torchdiffeq
01:48:04-197008 INFO     Installing package: torchsde
01:48:06-424118 INFO     Installing package: voluptuous
01:48:08-245872 INFO     Installing package: yapf
01:48:10-015107 INFO     Installing package: scikit-image
01:48:11-888503 INFO     Installing package: basicsr
01:48:13-625000 INFO     Installing package: compel
01:48:23-208668 INFO     Installing package: requests==2.31.0
01:48:25-501614 INFO     Installing package: tqdm==4.65.0
01:48:27-386914 INFO     Installing package: accelerate==0.20.3
01:48:29-591189 INFO     Installing package: opencv-python==4.7.0.72
01:48:31-550888 INFO     Installing package: diffusers==0.17.1
01:48:33-422299 INFO     Installing package: einops==0.4.1
01:48:35-479581 INFO     Installing package: gradio==3.32.0
01:48:52-803316 INFO     Installing package: numexpr==2.8.4
01:48:55-748951 INFO     Installing package: numpy==1.23.5
01:48:57-889891 INFO     Installing package: numba==0.57.0
01:49:04-805484 INFO     Installing package: pandas==1.5.3
01:49:15-369560 INFO     Installing package: protobuf==3.20.3
01:49:17-419502 INFO     Installing package: pytorch_lightning==1.9.4
01:49:22-148337 INFO     Installing package: transformers==4.26.1
01:49:33-723418 INFO     Installing package: timm==0.6.13
01:49:37-110607 INFO     Installing package: tomesd==0.1.3
01:49:39-665627 INFO     Installing package: urllib3==1.26.15
01:49:42-308815 INFO     Verifying packages
01:49:42-311295 INFO     Installing package: git+https://github.com/openai/CLIP.git
01:49:48-166583 INFO     Installing package: onnxruntime==1.15.1
01:49:52-746655 INFO     Installing repositories
01:49:52-748638 INFO     Cloning repository: https://github.com/Stability-AI/stablediffusion.git
01:49:58-199420 INFO     Cloning repository: https://github.com/CompVis/taming-transformers.git
01:51:01-529094 INFO     Cloning repository: https://github.com/crowsonkb/k-diffusion.git
01:51:02-965075 INFO     Cloning repository: https://github.com/sczhou/CodeFormer.git
01:51:05-814636 INFO     Cloning repository: https://github.com/salesforce/BLIP.git
01:51:07-627677 INFO     Installing submodules
      0 [main] sh 1991 dofork: child -1 - forked process 8524 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
1168119 [main] sh 1991 dofork: child -1 - forked process 33492 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
3324493 [main] sh 1991 dofork: child -1 - forked process 31380 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
7488757 [main] sh 1991 dofork: child -1 - forked process 30744 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
15658860 [main] sh 1991 dofork: child -1 - forked process 34260 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
01:51:23-744634 ERROR    Error running git: None / submodule
      0 [main] sh 91 dofork: child -1 - forked process 32156 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
1177138 [main] sh 91 dofork: child -1 - forked process 17580 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
3349386 [main] sh 91 dofork: child -1 - forked process 32852 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
7508040 [main] sh 91 dofork: child -1 - forked process 29840 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
15677917 [main] sh 91 dofork: child -1 - forked process 34276 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
01:51:39-722275 ERROR    Error running git: None / submodule --quiet update --init --recursive
01:51:40-843756 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
01:51:40-850182 WARNING  Setup complete with errors: 2
01:51:40-852660 WARNING  See log file for more details: F:\Vlad 1111\VLAD Diffusion\automatic\sdnext.log
01:51:40-862580 INFO     Extension preload: 0.0s F:\Vlad 1111\VLAD Diffusion\automatic\extensions-builtin
01:51:40-865557 INFO     Extension preload: 0.0s F:\Vlad 1111\VLAD Diffusion\automatic\extensions
01:51:40-890851 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
01:51:49-197872 INFO     Libraries loaded
01:51:49-202832 INFO     Using data path: F:\Vlad 1111\VLAD Diffusion\automatic
01:51:49-209279 INFO     Available VAEs: F:\Vlad 1111\VLAD Diffusion\automatic\models\VAE 0
01:51:49-213248 INFO     Available models: F:\Vlad 1111\VLAD Diffusion\automatic\models\Stable-diffusion 0
Download the default model? (y/N) y
Downloading: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors" to F:\Vlad 1111\VLAD Diffusion\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors

100.0%
01:53:30-224977 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://127.0.0.1:7860
01:53:31-065717 INFO     Local URL: http://127.0.0.1:7860/
01:53:31-068742 INFO     Initializing middleware
01:53:31-146141 INFO     Model metadata saved: F:\Vlad 1111\VLAD Diffusion\automatic\metadata.json 1
Loading weights: F:\Vlad 1111\VLAD Diffusion\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors -- 0… -…
                                                                                                                  GB
01:53:31-658473 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Calculating model hash: F:\Vlad 1111\VLAD Diffusion\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors
01:53:44-397266 INFO     Applying scaled dot product cross attention optimization
01:53:44-432505 INFO     Embeddings: loaded=0 skipped=0
01:53:44-438930 INFO     Model loaded in 13.2s (load=0.3s config=0.1s create=0.5s hash=9.6s apply=0.9s vae=0.8s
                         move=0.9s)
01:53:44-580290 INFO     Model load finished: {'ram': {'used': 4.78, 'total': 63.95}, 'gpu': {'used': 3.3, 'total':
                         24.0}, 'retries': 0, 'oom': 0} cached=0
01:53:44-816642 INFO     Startup time: 123.9s (torch=2.2s gradio=2.4s libraries=3.7s models=99.4s codeformer=0.1s
                         scripts=1.4s onchange=0.1s ui=0.7s launch=0.1s app-started=0.1s checkpoint=13.7s)
02:01:06-847799 INFO     Extensions update check: update=0 disabled=2
02:04:01-100825 INFO     Server shutdown requested
02:04:01-252116 WARNING  WebSocket closed (ignore asyncio.exceptions.CancelledError)
Traceback (most recent call last):
  File "F:\Vlad 1111\VLAD Diffusion\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\Vlad 1111\VLAD Diffusion\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "F:\Vlad 1111\VLAD Diffusion\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\Vlad 1111\VLAD Diffusion\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\Vlad 1111\VLAD Diffusion\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
02:04:03-281410 INFO     Server will restart
02:04:03-557404 INFO     Server restarting...
02:04:06-694624 INFO     Server arguments: []
02:04:06-698600 INFO     Libraries loaded
02:04:06-700658 INFO     Using data path: F:\Vlad 1111\VLAD Diffusion\automatic
02:04:06-704625 INFO     Available VAEs: F:\Vlad 1111\VLAD Diffusion\automatic\models\VAE 0
02:04:06-708105 INFO     Available models: F:\Vlad 1111\VLAD Diffusion\automatic\models\Stable-diffusion 1
02:04:07-154167 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://127.0.0.1:7860
02:04:07-492307 INFO     Local URL: http://127.0.0.1:7860/
02:04:07-495231 INFO     Initializing middleware
02:04:07-790377 INFO     Startup time: 1.1s (scripts=0.3s onchange=0.1s ui=0.2s launch=0.1s checkpoint=0.3s)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by Aptronymist** [comment]
> ### Issue Description
> Just installed Vlad from scratch and not added anithing elsa but ControlNet appear in extensions tab but not in the UI. Already restarted trying to check for updates. Im runing it with webui.bat
> 
> Thanks
If this is still happening, can you run it with --debug? To me it looks like there was a major failure in getting the submodules from github, which certainly implies your setup would be pretty busted, depending on what didn't get downloaded.

Other than that I would suggest trying a --reinstall flag to see if that sorts it out and re-downloads everything properly.

**Comment by vladmandic** [comment]
> 01:43:12-618108 INFO Python 3.10.6 on Windows

if this is windows, where is this coming from?

> 1168119 [main] sh 1991 dofork: child -1 - forked process 33492 died unexpectedly, retry 0, exit code 0xC0000142, errno 11

if i had to guess, to me it seems you're trying to run `webui.sh` using git bash shell (or something like that) which is NOT supported  

if running on windows, only thing that is supported is running webui.bat via cmd interpreter.

**Comment by Koguist4** [comment]
yes is Windows 10 22h2, I created a new folder and with git clon I bring all files and installed running webui.bat , the log have all that process and a restart.

**Comment by vladmandic** [comment]
the core issue is that your git is not working correctly - and quick google shows that is typically due to a conflict between git installed shell and some other shell already present on the system (e.g., cygwin).
i would uninstall git, search what else may be installed that has a cygwin shell, remove that. and then reinstall git from official repo.
