### ISSUE TITLE
[Feature]: Extra Networks preview image thumbnailing/cache

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#1528]
### Feature description

I've noticed a lot of slowdowns in my extra network screen coming up, so I looked around for a cause, the only thing I can come up with is that some civitai model authors are putting animated images, highres images, bloated pics in general, up as their primary image, which of course things like civitai  helper and other similar extensions are downloading and including in the same folder with the model itself.
I've got some as big as 34mb, and the vast majority are far larger than needed, so I propose using the PIL library to cut them down to size and rip out the junk that isn't needed to be an actual thumbnail-ish image.

Proposed solution is to create a separate images folder structure, have sd.next periodically scan for the presence of new preview images in the /models folders, clean and downscale them (max size of say 300-400px on long edge?), and save them as jpg files in the new folder structure to be used as extra networks thumbnail images. I expect this would be a large speedup. 

In addition I think adding the model's hash value (trimmed sha256 or some legacy format, like metadata.json has) to the thumbnail name, such as for FastNegativeEmbedding as an example. That's already stored in cache.json.

        
        "textualinversion/Quality\\Negative\\FastNegativeEmbedding": {
            "mtime": 1684891192.7643964,
            "sha256": "687b669d8234a418005ca9bfda93464b1721285b0a6a8d92490df0f02124ab7c"
        }
So if the saved jpeg filename was FastNegativeEmbedding.212bab7c.preview.jpg or something you could keep better track of them and hopefully keep from creating duplicates and whatnot, then again, that could also easily be stored in EXIF (along with other things? filename of model, location, etc), as we've definitely got libraries installed to process that. 

That may be something that is saved for an extra networks redesign, but just putting it out there.

**Comment by vladmandic** [comment]
done.

thumbnails are autocreated (filename = `<name>.thumb.jpg`) in the background thread if preview image exists and thumbnail is not found.

i though about doing it on-demand, but its pretty fast and since its only doing it once for each found preview, why not just spin a new thread and do it like that. so on first start, ui will use full images while thumbs are being created in the background, but on subsequent starts, thumb will be found and used.

**Comment by SLAPaper** [comment]
Hi, is there a arg or setting that can disable this feature? Or move them to seperate place? It's not okay to add auto-generated files to user folders

**Comment by vladmandic** [comment]
It's not ok to have high resolution images set as previews. If image is of reasonable size, thumbnail will not be created.

**Comment by SLAPaper** [comment]
> It's not ok to have high resolution images set as previews. If image is of reasonable size, thumbnail will not be created.

then it's better save to a seperate path or a internal database, rather than throw everything into user's folder

**Comment by Aptronymist** [comment]
> > It's not ok to have high resolution images set as previews. If image is of reasonable size, thumbnail will not be created.
> 
> then it's better save to a seperate path or a internal database, rather than throw everything into user's folder

Everything gets thrown into the users folder by pretty much every extension, especially whatever downloaded the preview images in the first place, along with potentially several other files for each and every model, so I don't see why adding... around a large loras worth of jpg files for your entire library to have thumbnails is such a concern. What is the real issue? Vlad's not exactly in the habit of making changes without a reasonable justification being presented, when people can do that, it's usually done. What is yours?

**Comment by SLAPaper** [comment]
> > > It's not ok to have high resolution images set as previews. If image is of reasonable size, thumbnail will not be created.
> > 
> > 
> > then it's better save to a seperate path or a internal database, rather than throw everything into user's folder
> 
> Everything gets thrown into the users folder by pretty much every extension, especially whatever downloaded the preview images in the first place, along with potentially several other files for each and every model, so I don't see why adding... around a large loras worth of jpg files for your entire library to have thumbnails is such a concern. What qualifies as the user's folder? They're all the user's folders, one way or another. What is the real issue? Vlad's not exactly in the habit of making changes without a reasonable justification being presented, when people can do that, it's usually done. What is yours?

Fine, there is no need to further discuss this issue.
