### ISSUE TITLE
[Feature]: Collapsible Subfolders

### ISSUE THREAD

**Issue by HeartlessAUS** [vladmandic/automatic#1533]
### Feature description

i would love to see a way to have collapsible subfolders, for example in the LORA networks. examples shown below.... badly made c:
this could help alot with organisation
all open (current system)
![all opens](https://github.com/vladmandic/automatic/assets/47524314/c6b4e972-91a7-4d08-a953-9b0d0e448ead)

Closed folders
![closed folder](https://github.com/vladmandic/automatic/assets/47524314/22eef93c-1e7c-45b8-8005-1afd712c6ed8)

When clicking on a main folder
![openfolder](https://github.com/vladmandic/automatic/assets/47524314/44021ff1-047f-4a63-a2ca-2764f1ccabf8)

**Comment by vladmandic** [comment]
extra networks redesign is in process and will likely be published later today.
this part will change significantly, but collapsable folders is not on the list. lets revisit once new ui is published.

**Comment by HeartlessAUS** [comment]
got something working using new networks ui and some javascript
`onUiLoaded(() => {
	var id = document.getElementById("txt2img_lora_subdirs");
    var children = id.querySelectorAll('.gradio-button');
    var mainFolders = [];
    var folderVar = [];
    children.forEach(function(child) {
        var text = child.innerText;
        if (!text.includes("/")){
            console.log("Found Main Folder: " + text);
            mainFolders.push(child);
        }
    });
    children.forEach(function(child) {
        var text = child.innerText;
        if (text.includes("/")){
            var textSplit = text.split("/");
            if(mainFolders.indexOf(textSplit[0])){
                console.log("Found Sub Folder: " + textSplit[1] + ". inside: " + textSplit[0]);
                child.style.display = "none";
                child.nextSibling.style.display = "none";
            }
        }
    });
for (i of mainFolders) {
  i.addEventListener('click', function() {
    var folder = this.innerText;
    if (folderVar[i] === 1){
        folderVar[i] = 0;
        console.log("Folder: " + folder + " is now closed");
    } else {
        folderVar[i] = 1;
        console.log("Folder: " + folder + " is now open");
    }
    console.log("Checking: " + folder);
    children.forEach(function(child) {
        var text = child.innerText;
        if (text.includes(folder) && text.includes("/")){
            console.log("Found Sub Folder: " + text);
            if (folderVar[i] === 1){
                child.style.display = "inline-flex";
                child.nextSibling.style.display = "inline-flex";
            } else {
                child.style.display = "none";
                child.nextSibling.style.display = "none";
            }
        }
    });
  });
}
});`

**Comment by HeartlessAUS** [comment]
[collapsable-folders.js.txt](https://github.com/vladmandic/automatic/files/11926083/collapsable-folders.js.txt)
with the new networks ui, its easily possible now using some JS, here's a simple example

**Comment by vladmandic** [comment]
why not submit a PR?

**Comment by HeartlessAUS** [comment]
> why not submit a PR?

i dont think my work is really production quality tbh, just a pleb with a bit of coding knowledge c:

**Comment by vladmandic** [comment]
Maybe, maybe not. But it can be iterated upon - gotta start somewhere and this is a good suggestion.
