### ISSUE TITLE
[Feature]: Batch process multiple images at once in Img2img

### ISSUE THREAD

**Issue by Ktrcoyote** [vladmandic/automatic#1536]
Oops. hit the wrong button. Sorry. 

### Feature description

Current version of img2img batch processing processes multiple versions of the same image instead of multiple source images at once  I.E  Batch size set to 3 will output three versions of 1.jpg instead of simultaneously processing 1.jpg 2.jpg 3.jpg then moving onto 4.jpg 5.jpg 6.jpg. If you're using img2img to process video fames it's a massive bottleneck.

### Version Platform Description

Current one?

**Comment by vladmandic** [comment]
that would be a completely different workflow and doesn't fit into existing batch processing.
valid feature request, but given the large scope and my current backlog, i don't see this anytime soon.

**Comment by derspanier1** [comment]
been away in merica for 3 weeks, finally back. Hope everyone is good. there was a discussion about this a few months ago, maybe this could help for a quick fix, because that script does not work with this fork:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7909

**Comment by vladmandic** [comment]
forgot to close this issue as feature has been implemented, see option `batch_frame_mode`
