### ISSUE TITLE
[Issue]: A bunch of newer versions of dependencies cause ImportErrors at start

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#1539]
### Issue Description

In particular, `pydantic` v2 (just released) is incompatible with `fastapi`, and the newest `typing-extensions` release either dropped or moved the `deprecated` namespace.

If any of these are installed, SD.Next won't obviously start, as it references imports that no longer are present.
Quick workaround:

```
pip install pydantic==1.10.9
pip install typing-extensions==4.6.3
```

### Version Platform Description

```
22:36:09-299480 INFO     Python 3.9.13 on Linux                                 
22:36:09-320108 INFO     Version: 0d3092c2 Fri Jun 30 17:22:42 2023 -0400       
22:36:09-532206 INFO     nVidia CUDA toolkit detected                           
22:36:10-939046 INFO     Torch 2.0.1+cu118                                      

```
Running on Paperspace (which uses Ubuntu 20.04)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
thanks. i'll lock down those versions for now.
