### ISSUE TITLE
[Issue]: Assorted Javascript Errors

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#1540]
### Issue Description

Checked my developer mode when trying out the new Networks and saw a few JS problems I thought I should bring to your attention.

![vivaldi_dw0BrU5ZoA](https://github.com/vladmandic/automatic/assets/108482020/441a7bfd-4bf6-400b-a5af-7bf3859d5210)
I expect the ones for Civitai Helper are due to the Extra Networks changes, so that might cause some issues coming in, thought I would get out in front of it in case it's a real problem as many use it. Can report to repo if desired.

The one for dynamic prompts is related to tooltips I believe, I'm only sharing that in case others use that same method, and it's pretty popular. I'll report to repo.
![vivaldi_tE1u6eKGHB](https://github.com/vladmandic/automatic/assets/108482020/f2cf9172-2b23-4aab-b3dc-9a6321e82d4b)
Had this in my log when I try to generate with empty prompts, unsure if related or another issue entirely, so I'll report this as well.

<details>
<summary>Details</summary>

```
17:43:10-868240 ERROR    Running script process:
                         H:\AI\SD.Next\extensions\sd-dynamic-prompts\scripts\dynamic_prompting.py: StopIteration
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\AI\SD.Next\modules\scripts.py:406 in process                                                                     │
│                                                                                                                     │
│   405 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                      │
│ > 406 │   │   │   │   script.process(p, *args, **kwargs)                                                            │
│   407 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                     │
│                                                                                                                     │
│ H:\AI\SD.Next\extensions\sd-dynamic-prompts\sd_dynamic_prompts\dynamic_prompting.py:478 in process                  │
│                                                                                                                     │
│   477 │   │   │                                                                                                     │
│ > 478 │   │   │   all_prompts, all_negative_prompts = generate_prompts(                                             │
│   479 │   │   │   │   generator,                                                                                    │
│                                                                                                                     │
│ H:\AI\SD.Next\extensions\sd-dynamic-prompts\sd_dynamic_prompts\helpers.py:93 in generate_prompts                    │
│                                                                                                                     │
│    92 │   """                                                                                                       │
│ >  93 │   all_prompts = prompt_generator.generate(prompt, num_prompts, seeds=seeds) or [""]                         │
│    94                                                                                                               │
│                                                                                                                     │
│ H:\AI\SD.Next\venv\lib\site-packages\dynamicprompts\generators\randomprompt.py:71 in generate                       │
│                                                                                                                     │
│   70 │   │   │   │   self._context.rand.seed(seed)                                                                  │
│ > 71 │   │   │   │   prompts.append(next(iter(gen)))                                                                │
│   72 │   │   │   return prompts                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
StopIteration
17:43:11-007722 DEBUG    Script process: ['Upscale:0.0s', 'Rembg:0.0s', 'GFPGAN:0.0s', 'CodeFormer:0.0s', 'Tiled
```

</details>

Not sure what's up with openpose to cause that error, I don't use controlnet much, so that might even be normal.

Other than that there are the local ones with SD.Next's JS file.
![vivaldi_SPz3GJ8RkB](https://github.com/vladmandic/automatic/assets/108482020/0cca4676-c008-422c-b54c-b1222bfa1c58)

![vivaldi_qXYPuRYMVo](https://github.com/vladmandic/automatic/assets/108482020/6b9b389a-f478-4b67-b1dc-f40c64e2e66e)
![vivaldi_hpmWukGEQF](https://github.com/vladmandic/automatic/assets/108482020/57db2012-f8b7-4202-b1f6-acc818f8c560)

Edit: 
I also saw this one pop up when I had the extra networks open:
![image](https://github.com/vladmandic/automatic/assets/108482020/d5aebfcc-76a8-4a86-b55f-62841a1da167)

### Version Platform Description

SD.Next [8000d19](https://github.com/vladmandic/automatic/commit/8000d1965d7fc87ef1cc34adc09a124dd053bb36)
Win10 LTSC - Vivaldi (chromium)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i've just pushed update with fixes for `logMonitor` JSON parser and defined global `titles` var.
the rest is unknown to me.
