### ISSUE TITLE
[Feature]: Extension sets for launching UI

### ISSUE THREAD

**Issue by Bodzijun** [vladmandic/automatic#1541]
### Feature description

Is it possible to implement preset selection with sets of active selective extensions for different tasks? (set for animation, set for image generation, set for train etc)
Goal: reduce lags and interface latency when dozens of unnecessary extensions are enabled.
Implementation:
1 -  It is possible to generate in a separate file a list of all installed extensions with their status (0 or 1).
Then save different versions of such files with a selection of extensions and use them to launch WEBUI
2  - Create a preset list in the Extension tab

**Comment by Aptronymist** [comment]
> ### Feature description
> Is it possible to implement preset selection with Webui settings (active/inactive extensions for different tasks) before launch? (for example, as in a blender : modeling, video, sculpting) Task: reduce lags and interface latency when dozens of unnecessary extensions are enabled
> 
> ### Version Platform Description
> _No response_

Do you mean like [these](https://github.com/Zyin055/Config-Presets) [three](https://github.com/Gerschel/sd_web_ui_preset_utils) [extensions](https://github.com/rifeWithKaiju/model_preset_manager) do?

I can't promise they work, or do what you want, but they are all in the extensions tab.

**Comment by vladmandic** [comment]
btw, empty title => invalid record. and please fill everything that is required by the form.

**Comment by Aptronymist** [comment]
> ### Feature description
> 
> Is it possible to implement preset selection with sets of active selective extensions for different tasks? (set for animation, set for image generation, set for train etc)
> Goal: reduce lags and interface latency when dozens of unnecessary extensions are enabled.
> Implementation:
> 1 -  It is possible to generate in a separate file a list of all installed extensions with their status (0 or 1).
> Then save different versions of such files with a selection of extensions and use them to launch WEBUI
> 2  - Create a preset list in the Extension tab

Well at the moment you can just go uncheck them in extensions tab and hit restart. That would make them inactive. 
They would still be in memory, but not doing anything. 
Unless vlad had any input, all I could suggest would be a hacky batch file or script to swap out the disabled extensions list entry in your config.json file, but I'm not sure when the best time to do that would be, as it seems to ignore changes to the file while active.
Not very hard to do, if it worked.

**Comment by vladmandic** [comment]
you could have 10 different versions of `config.json`, each with its list of active extensions and then use `webui --config <file>` to specify which to load.
