### ISSUE TITLE
[Issue]: Not looking for Loras and Lycoris in the right directory

### ISSUE THREAD

**Issue by cobaltbeau** [vladmandic/automatic#1542]
### Issue Description

I changed my lora and lycoris directories (among others) to be the same as the ones for the standard SD webui, but it's not actually looking there.

I restarted the server just to make sure, and it's still not finding them:

![image](https://github.com/vladmandic/automatic/assets/5383283/bbd2fa97-08ad-4f69-91cf-de627a8f612e)

As you can see, the checkpoints are also pointed to that directory, but it only sees the checkpoints, not the Loras/Lycos

![image](https://github.com/vladmandic/automatic/assets/5383283/42071753-ba81-4713-a0cd-196287ed7703)

![image](https://github.com/vladmandic/automatic/assets/5383283/69333e46-76a2-4ea3-8548-8196094bd0ce)

### Version Platform Description

``` 19:09:07-857256 INFO     Starting SD.Next
19:09:07-864769 INFO     Python 3.10.0 on Windows
19:09:08-046842 INFO     Version: 0d3092c2 Fri Jun 30 17:22:42 2023 -0400
19:09:08-507753 INFO     nVidia CUDA toolkit detected
19:09:17-033516 INFO     Torch 2.0.1+cu118
19:09:17-059010 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
19:09:17-062488 INFO     Torch detected GPU: NVIDIA GeForce GTX 1070 VRAM 8192 Arch (6, 1) Cores 15
19:09:17-065988 INFO     Installing package: tensorflow==2.12.0
19:10:38-919581 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
19:10:38-962580 INFO     Enabled extensions: []
```

I'm unsure if this would be installation/setup related or not, so i checked my sdnext.log and found this:

``` 
2023-06-30 19:57:38,043 | sd | INFO | ui | Settings changed: 56 ['ckpt_dir', 'lora_dir', 'lyco_dir'
```

So it definitely tried to change the settings

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i'm pretty sure this worked ok, but i'll check.

**Comment by vladmandic** [comment]
i've justed tested and it works for me.
the only thing is that server restart is (was) needed after the change - i've updated that now, so even server restart is not needed, just click refresh in extra networks ui.

**Comment by byteconcepts** [comment]
No, it's not OK, it's broken.

If I (in img2img now) click on Lora and then on the Rescan Button, it shows all checkpoints (Models) in the List.
If I then click on Checkpoints and then the Rescan Button, it shows nothing in the list.
If I then click on LyCORIs and then the Rescan Button, it shows all Loras AND LyCORIs in the list.

This is definitely broken since a few days.

**Comment by MakingMadness** [comment]
I'm finding this broken for the last few days too. I see only a list of checkpoints, and no sign of a section for loras or embeddings. Attempting to use loras or embeddings in a prompt results in no change to the image. No idea if it's to do with paths. I use the --data-dir parameter in case that's any help.

https://github.com/vladmandic/automatic/commit/3bcca6f92b4d457eff8616e157ba13421f59527f
Ubuntu 22.04
Firefox 102.11.0esr

**Comment by vladmandic** [comment]
i'll push an update by tomorrow (i hope).
one other thing, there are multiple reports that config needs to be reset for extra networks to start working correctly, so any chance you can delete config.json? i cannot reproduce that.

**Comment by MakingMadness** [comment]
Deleting config.json fixed it. Thanks!
