### ISSUE TITLE
[Feature]: Resolve GIT env_var to absolute path in order to support a portable build

### ISSUE THREAD

**Issue by ForgetfulWasAria** [vladmandic/automatic#1544]
### Feature description

I have a portable build with the following structure:
```
poc_setup
    python
    PortableGit
    scripts
    automatic
    setup.bat
```
where setup.bat clones the repository then copies the webui-user.bat from scripts to automatic. For the build to be portable, the paths in webui.bat need to be relative.  While this isn't a problem with python, git is run in different directories to update repositories (and probably extensions?) This results in failed clones with repositories as the working directory is not ```./automatic``` 
Changing line 193 of installer.py from
```
git_cmd = os.environ.get('GIT', "git")
```
to
```
git_cmd = os.environ.get('GIT', "git")
    if git_cmd != "git":
        git_cmd = os.path.abspath(git_cmd)
```
resolves this issue without breaking a system installed git. If the path to git is already an absolute path, this does not break it.
I tested launching the server, restarting, installing and updating extensions and all seem to work identically. I'm a git/Github newbie and mostly 20 or more years out of date on coding practices. The only thing I've noticed is that on relaunch the "--autolaunch" shows up twice in the server arguments.

Is this worth a pull request? To have a really newbie friendly install there would need to be releases of sd.next but this looks like a first stop. 

### Version Platform Description

Only tested on windows 11.

**Comment by vladmandic** [comment]
thats fair, i'll add it today.
