### ISSUE TITLE
[Issue]: recent update broke the gallery view

### ISSUE THREAD

**Issue by Razunter** [vladmandic/automatic#1546]
### Issue Description

Gallery view overlaps buttons and generation info on my PC since the recent update, I think it's this one: https://github.com/vladmandic/automatic/commit/6e89d3b867171e8a14026cbde74531826e0938b7#diff-fe2129c140fc5cff6a2b769eaffa44583ed8dc64e7aee39f52377e4624c7a84eR127

![looks like this](https://github.com/vladmandic/automatic/assets/362900/f40d8e86-4d85-46d1-a9f0-4164ed4cfbfb)

Commenting out the `height` on `#txt2img_gallery` fixes the issue for me.

Some debug console values:

```
window.innerHeight - gallery.getBoundingClientRect().top - 200
362

gallery.getBoundingClientRect()
DOMRect { x: 516.7999877929688, y: 139, width: 1963.199951171875, height: 450, top: 139, right: 2479.9999389648438, bottom: 589, left: 516.7999877929688 }

window.innerHeight
701
```

### Version Platform Description

Version: fbbb56f6
Windows 11, Firefox

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i've disabled gallery height calculations for now until i figure out a better way.
