### ISSUE TITLE
[Issue]: RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by FE4RLEZ** [vladmandic/automatic#1550]
### Issue Description

D:\Vladmandic\automatic>webui.bat --autolaunch --medvram --upgrade
Using VENV: D:\Vladmandic\automatic\venv
11:55:17-350547 INFO     Starting SD.Next
11:55:17-354768 INFO     Python 3.10.11 on Windows
11:55:17-382136 INFO     Version: 12aaeac2 Sat Jul 1 10:46:11 2023 -0400
11:55:18-233828 INFO     Updating main repository
11:55:21-000226 INFO     Upgraded to version: ab52ae92 Sat Jul 1 17:35:03 2023 -0400
11:55:21-003376 INFO     nVidia CUDA toolkit detected
11:55:22-191835 INFO     Torch 2.0.1+cu118
11:55:22-210302 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
11:55:22-213757 INFO     Torch detected GPU: NVIDIA GeForce GTX 1660 Ti VRAM 6144 Arch (7, 5) Cores 24
11:55:22-292006 INFO     Verifying requirements
11:55:22-308412 INFO     Verifying packages
11:55:22-310569 INFO     Installing repositories
11:55:27-744742 INFO     Installing submodules
11:55:30-015095 INFO     Updating submodules
11:56:03-884157 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
11:56:03-888788 INFO     Updating Wiki
11:56:05-076072 INFO     Extension preload: 0.0s D:\Vladmandic\automatic\extensions-builtin
11:56:05-078034 INFO     Extension preload: 0.0s D:\Vladmandic\automatic\extensions
11:56:05-088007 INFO     Server arguments: ['--autolaunch', '--medvram', '--upgrade']
No module 'xformers'. Proceeding without it.
HERE D:\Vladmandic\automatic\models\Lora D:\Vladmandic\automatic\models\Lora
11:56:09-852089 INFO     Libraries loaded
11:56:09-857122 INFO     Using data path: D:\Vladmandic\automatic
11:56:09-860068 INFO     Available VAEs: D:\Vladmandic\automatic\models\VAE 0
11:56:09-863897 INFO     Available models: D:\Vladmandic\automatic\models\Stable-diffusion 2
11:56:11-884980 INFO     ControlNet v1.1.227
ControlNet v1.1.227
ControlNet preprocessor location: D:\Vladmandic\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
11:56:12-034582 INFO     ControlNet v1.1.227
ControlNet v1.1.227
Image Browser: ImageReward is not installed, cannot be used.
11:56:13-322776 INFO     Loading UI theme: name=black-orange style=Dark
11:56:13-333257 INFO     Theme does not support custom mode
Running on local URL:  http://127.0.0.1:7860
11:56:15-126413 INFO     Local URL: http://127.0.0.1:7860/
11:56:15-129290 INFO     Initializing middleware
11:56:15-248003 INFO     [AgentScheduler] Task queue is empty
11:56:15-251759 INFO     [AgentScheduler] Registering APIs
Loading weights: D:\Vladmandic\automatic\models\Stable-diffusion\deliberate_v2.safetensors ---------- 0.0/2.1   -:--:--
                                                                                                      GB
11:56:15-962374 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
11:56:18-149633 INFO     Applying scaled dot product cross attention optimization (without memory efficient attention)
11:56:18-157612 INFO     Embeddings: loaded=0 skipped=0
11:56:18-165591 INFO     Model loaded in 2.6s (load=0.4s create=0.4s apply=0.5s channels=0.5s vae=0.7s)
11:56:18-402995 INFO     Model load finished: {'ram': {'used': 5.17, 'total': 31.82}, 'gpu': {'used': 0.98, 'total':
                         6.0}, 'retries': 0, 'oom': 0} cached=0
11:56:18-486815 INFO     Startup time: 13.4s (torch=2.5s gradio=0.9s libraries=1.3s scripts=2.9s onchange=0.5s ui=1.6s
                         launch=0.2s app-started=0.2s checkpoint=3.1s)
11:56:18-493731 INFO     Launching browser
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [01:21<00:00,  4.06s/it]
11:58:52-274439 ERROR    Exception: PytorchStreamReader failed reading zip archive: failed finding central directory
11:58:52-278468 ERROR    Arguments: args=('task(alap4zu2dzu72vh)', '1woman, swimsuit, show full body, wide view, sexy,
                         pretty, cute, high res, photorealistic, very clear, ultra hd', 'blur, low res, 3d. render,
                         unreal engine, out of frame body', [], 20, 3, True, False, 1, 1, 3, 1, 593346168.0,
                         593346168.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False,
                         'MultiDiffusion', False, True, 1024, 1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64,
                         False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',
                         'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False,
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 960, 64, True, True, True, False,
                         False, 7, 100, 'Constant', 0, 'Constant', 0, 4,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000164098EE8C0>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000164098ECB80>,
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNetUnit object at 0x00000164098EE020>,
                         False, False, 'positive', 'comma', 0, False, False, '', 0, '', [], 0, '', [], 0, '', [], True,
                         False, False, False, 0, False, None, None, False, None, None, False, None, None, False, 50)
                         kwargs={}
11:58:52-305357 ERROR    gradio call: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\Vladmandic\automatic\modules\call_queue.py:34 in f                                                               │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ D:\Vladmandic\automatic\modules\txt2img.py:56 in txt2img                                                            │
│                                                                                                                     │
│   55 │   if processed is None:                                                                                      │
│ > 56 │   │   processed = processing.process_images(p)                                                               │
│   57 │   p.close()                                                                                                  │
│                                                                                                                     │
│                                               ... 6 frames hidden ...                                               │
│                                                                                                                     │
│ D:\Vladmandic\automatic\venv\lib\site-packages\torch\serialization.py:797 in load                                   │
│                                                                                                                     │
│    796 │   │   │   orig_position = opened_file.tell()                                                               │
│ >  797 │   │   │   with _open_zipfile_reader(opened_file) as opened_zipfile:                                        │
│    798 │   │   │   │   if _is_torchscript_zip(opened_zipfile):                                                      │
│                                                                                                                     │
│ D:\Vladmandic\automatic\venv\lib\site-packages\torch\serialization.py:283 in __init__                               │
│                                                                                                                     │
│    282 │   def __init__(self, name_or_buffer) -> None:                                                              │
│ >  283 │   │   super().__init__(torch._C.PyTorchFileReader(name_or_buffer))                                         │
│    284                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

This happen when i use restore face. What does it mean? do i have to delete venv and redownload it again?

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by Limbicnation** [comment]
@FE4RLEZ What is the solution to this problem?
