### ISSUE TITLE
[Issue]: gradio call: ZeroDivisionError

### ISSUE THREAD

**Issue by CAFlynnAI** [vladmandic/automatic#1552]
### Issue Description

Receiving the following error log when using "Refresh extension list" via the Extensions tab.

ERROR    gradio call: ZeroDivisionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ E:\Stable Diffusion\vladmandic\automatic\modules\call_queue.py:58 in f                                              │
│                                                                                                                     │
│    57 │   │   │   │   pr.enable()                                                                                   │
│ >  58 │   │   │   res = func(*args, **kwargs)                                                                       │
│    59 │   │   │   if res is None:                                                                                   │
│                                                                                                                     │
│ E:\Stable Diffusion\vladmandic\automatic\modules\ui_extensions.py:257 in refresh_extensions_list                    │
│                                                                                                                     │
│   256 │   update_extension_list()                                                                                   │
│ > 257 │   code = refresh_extensions_list_from_data(search_text, sort_column)                                        │
│   258 │   return code, f'Extensions | {len(extensions.extensions)} registered | {len(extension                      │
│                                                                                                                     │
│ E:\Stable Diffusion\vladmandic\automatic\modules\ui_extensions.py:335 in refresh_extensions_list_from_data          │
│                                                                                                                     │
│   334 │   │   timedelta = datetime.now() - datetime.fromisoformat(ext.get('created', '2000-01-                      │
│ > 335 │   │   ext['sort_trending'] = round(stars / min(timedelta.days, 5), 1)                                       │
│   336 │   │   tags = ext.get("tags", [])                                                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ZeroDivisionError: division by zero

### Version Platform Description

Using Firefox 114.0.2

Starting SD.Next
Python 3.10.9 on Windows
Version: fbbb56f6 Sat Jul 1 16:12:38 2023 -0400
Updating main repository
Upgraded to version: d61b0cfd Sun Jul 2 07:43:01 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8902
Torch detected GPU: NVIDIA GeForce RTX 3060 Ti VRAM 8192 Arch (8, 6) Cores 38

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
silly me. fixed.
