### ISSUE TITLE
[Extension]: Config-Presets is now displayed only after an image is created?

### ISSUE THREAD

**Issue by gitbreiti** [vladmandic/automatic#1554]
### Issue Description

In the current version, the extension "Config-Preset" is only displayed once an image has been created (under the created image). previously, the extension was displayed directly after the start. But I am not sure if it is because of the last update of the extension or the last update of SD.Next.

After the start:
![Screenshot 2023-07-02 152723](https://github.com/vladmandic/automatic/assets/45651354/54503e65-4ac1-4bfe-869b-e900db7b4e68)

After the first generation:
![Screenshot 2023-07-02 152857](https://github.com/vladmandic/automatic/assets/45651354/6d5654f4-279e-4967-8379-985671edc41a)

### Version Platform Description

15:00:48-172549 INFO     Python 3.10.6 on Windows
15:00:48-215448 INFO     Version: 875d0db1 Sun Jul 2 08:26:51 2023 -0400
15:00:48-361495 INFO     nVidia CUDA toolkit detected
15:00:49-654582 INFO     Torch 2.0.0+cu118
15:00:49-670460 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
15:00:49-671489 INFO     Torch detected GPU: NVIDIA GeForce RTX 4080 VRAM 16375 Arch (8, 9) Cores 76
15:00:49-769119 WARNING  Modified files: ['webui.bat']
15:00:49-811189 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
15:00:49-818269 INFO     Enabled extensions: ['Config-Presets', 'deforum-for-automatic1111-webui', 'sd-webui-roop']

### URL link of the extension

https://github.com/Zyin055/Config-Presets

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
it was extensions choice to use that particular element as parent element. if you want to change where extension displays its elements, open issue with extension owner.
note that form itself **requires** that field - which you've skipped.
