### ISSUE TITLE
[Feature]: Singular folder for all Upscalers

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1556]
### Feature description

At the moment, there's like a half-dozen different folders for the various Upscalers scattered around the `models` folder.

It'd be nice to combine all these Upscalers into a single folder.

### Version Platform Description

n/a

**Comment by vladmandic** [comment]
not viable as different upscalers have very different architecture. and upscaler does not know which model files are compatible or not without attempting to load that model.
