### ISSUE TITLE
[Feature]: Cache and re-use if no new models

### ISSUE THREAD

**Issue by midcoastal** [vladmandic/automatic#1563]
### Feature description

I have...  Perhaps *too* many models (something like 5k at last count, I know I know), and this has developed into a problem: WebUI blocks for >1500 seconds on start for "Creating UI".

Ignoring the fact that I am an extreme case (another wrench is that the models are over a network share, but that is a 10gb fiber connection, that is fully capable of saturation), it does bring to light a potential optimization: caching (something), and reuse if there are no new models.

Even if I had a more modest collection, on local storage, there would be gains from some form of caching to be sure.

I am not sure *what* to cache, as I haven't dug in to what is causing the hang, but it certainly seems like there is an opportunity here, somewhere, anyway.

### Version Platform Description

Ubuntu 22.05, Kernel 6.2, Nvidia 530, latest WebUI as of posting.

**Comment by vladmandic** [comment]
valid request, i'll take a look.

**Comment by vladmandic** [comment]
majority of delay is enumerating and building extra network pages.
that shouldn't really be cached, but it can safely be deferred, there is no reason why it should be done during server startup.

i've added new option: settings -> extra networks -> do not automatically build extra network pages  

note this is in dev branch and will be published to master later this week.

**Comment by midcoastal** [comment]
@vladmandic - WOW, this is GREAT, a start up of 11 seconds vs 5-10 minutes is great.  That said, I still can not do anything until things are done generating...  Seems weird to need thumbnails before generating an image?

**Comment by vladmandic** [comment]
Im guessing that agent scheduled queue DB - if so, you'll need to post issue there.

**Comment by midcoastal** [comment]
Hate to be a bother, but this is fantastic, however, would it be possible to have it generate the pages in the background?  IE: Not block WebUI, and automatically trigger the generation anyway?  It was a little surprising after I had been using it a while, and went to the extra nets page, and realized I still had to wait 6+ minutes for the pages to populate, even though I had had the UI up for an hour or more.

:-/

**Comment by vladmandic** [comment]
eventually, yes. there is sooo much legacy code that needs to be replaced.
