### ISSUE TITLE
[Extension]:  Latent Couple

### ISSUE THREAD

**Issue by cleverestx** [vladmandic/automatic#1564]
### Issue Description

Installed Latent Couple from here using Extensions \ Manual install as per this video:
https://youtu.be/aBiGYIwoN_k?t=248

The install part from the GUI for this extension works fine, but when closing Vladmandic and running the .PATCH file from cmd it fails, this still is shown here:
https://youtu.be/aBiGYIwoN_k?t=284

Error is shown in the screenshot. When launching Vladmandic the extension is not shown. Can this be fixed? Thank you.

![image](https://github.com/vladmandic/automatic/assets/28905253/f883fd54-cfe5-4c8c-bbcf-22526a45de6d)

### Version Platform Description

Windows 11 Pro
Latest Vladmandic 
Chrome Browser, but this issue is not related to the browser being used:

```Using VENV: C:\Users\cleverest\Vlad1111\automatic\venv
08:55:16-315580 INFO     Starting SD.Next
08:55:16-321583 INFO     Python 3.10.9 on Windows
08:55:16-344768 INFO     Version: ab52ae92 Sat Jul 1 17:35:03 2023 -0400
08:55:16-673057 INFO     Latest published version: 875d0db1038cfecf445cf26a58a678590906e6c8 2023-07-02T12:26:51Z
08:55:16-675474 INFO     nVidia CUDA toolkit detected
08:55:17-654837 INFO     Torch 2.0.1+cu118
08:55:17-666847 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8901
08:55:17-667848 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128``


### URL link of the extension

https://github.com/miZyind/sd-webui-latent-couple

### URL link of the issue reported in the extension repository

_No response_

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by cleverestx** [comment]
Unlike the YouTube video install guide I linked above which uses Automatic1111 as the software being used; I noticed Vladmandic has this already in the extensions..is this the same thing? Should I just try to install this and report back if there is an issue? 

![image](https://github.com/vladmandic/automatic/assets/28905253/3e5eb001-25d5-4d57-8da3-8e1ee0ccab7c)

**Comment by vladmandic** [comment]
running patch of any kind automatically results in unsupported scenario as the whole point of patch is to MODIFY underlying app.
if that extension requires a specific callback, i'm more than open to add it - but lets do that the right way - author tells me which callback he needs and i add it. this is nightmare to deal with - i'm closing the issue as will-not-fix.

**Comment by cleverestx** [comment]
Honestly, I don't think it's needed...as per my last comment the one in the EXTENSIONS section installed fine and shows up in the GUI. As long as it works...  Thanks.

![image](https://github.com/vladmandic/automatic/assets/28905253/a26a7026-81e0-43f7-b914-37b9b769a4e9)
