### ISSUE TITLE
[Feature]: Filter all extra networks based on model architecture

### ISSUE THREAD

**Issue by Machinekng** [vladmandic/automatic#1566]
### Feature description

Currently, embeddings for SD 1.x and SD 2.x are only loaded when the correct model type is selected. This behavior does not extend to LoRAs and other extra network types. While this has been somewhat of a minor issue, since there is a comparative dearth of SD 2.1 LoRAs, improvements to LoRA training for SDXL may make this issue relevant. This can be manually mitigated by sorting LoRAs in folders based on architecture, but an automatic solution would be good if possible.

### Version Platform Description

Version: 875d0db1 Sun Jul 2 08:26:51 2023 -0400

**Comment by vladmandic** [comment]
valid feature request, but its going to take some time as currently lora architecture is not known until load is attempted.

**Comment by vladmandic** [comment]
done in dev branch, will be merged to master shortly.
