### ISSUE TITLE
[Feature]: Allow txt2img controlnet batch images match the input image filenames

### ISSUE THREAD

**Issue by hassan-sd** [vladmandic/automatic#1567]
### Feature description

When we use "extra" tab for batch processing, we can allow the images to be named the same as the input images but I use txt2img as my batch processing with controlnet running and would like the same feature there. 

Here's the current setting that seems to apply to the "Process batch" tab. Can we have the same option applied to txt2img batch when controlnet is active?

![image](https://github.com/vladmandic/automatic/assets/119671806/cf946464-615e-435b-ab65-b3847b57c3be)

Should this be a feature on the controlnet repo or here?

**Comment by vladmandic** [comment]
> Should this be a feature on the controlnet repo or here?

i'll check where is filename generated.

**Comment by vladmandic** [comment]
Sounds similar, but I haven't investigated properly.

**Comment by SuroshAhmadZobair** [comment]
Hi

Any updates?
@vladmandic Have you managed to check where the filename is generated?

I appreciate your effort. 
Thanks in advance

**Comment by vladmandic** [comment]
this should be done on controlnet side, but issue there is closed.
