### ISSUE TITLE
[Extension]: Config Preset no longer visible

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1570]
### Issue Description

The latest commit makes Config Preset's UI no longer visible under the image previewer.

### Version Platform Description

Starting SD.Next
Python 3.10.11 on Windows
Version: 0d3092c2 Fri Jun 30 17:22:42 2023 -0400
Updating main repository
Upgraded to version: 875d0db1 Sun Jul 2 08:26:51 2023 -0400
Using DirectML Backend
Torch 2.0.0+cpu
Torch backend: DirectML (torch-directml 0.2.0.dev230426)
Torch detected GPU: AMD Radeon RX 6600 XT

### URL link of the extension

https://github.com/Zyin055/Config-Presets

### URL link of the issue reported in the extension repository

https://github.com/Zyin055/Config-Presets/issues/50

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
its visible once button toolbar itself is displayed. its just that button toolbar has no meaning until there is image generated, so its not there in the latest updates. its extensions choice to anchor its ui to button toolbar.

duplicate #1554

**Comment by brknsoul** [comment]
Could you assist the author of Config Presets so suggest a place to anchor his extension?
Both of you have closed this issue with no resoultion.
IMHO, I don't see a point to hiding UI elements until an image is generated.

**Comment by vladmandic** [comment]
To me clearly logical place would be below styles.

**Comment by brknsoul** [comment]
Guess I'm the middle man?

> That area of the UI is constructed before all the other components so it wouldn't work.

https://github.com/Zyin055/Config-Presets/issues/50#issuecomment-1620628318
