### ISSUE TITLE
[Issue]: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by Deniryer** [vladmandic/automatic#1574]
### Issue Description

After recent update agent scheduler produces errors regarding CUDA. It can run few tasks then crashes. 

So far I've tried to reinstall (using DDU & safe mode) graphics drivers, cuda toolkit, reinstall Vlad's SD webUI without additional extensions and it seems to be still broken. Since my knowledge is extremely limited I'm absolutely clueless what could case it.  

Installed extensions apart from built-in: 
sd_dreambooth_extension
adetailer 
sd-webui-infinite-image-browsing 
sd-webui-supermerger

 `5:57:52-751355 ERROR    API error: POST: http://127.0.0.1:7860/internal/progress {'error': 'RuntimeError', 'detail':
                         '', 'body': '', 'errors': 'cuDNN error: CUDNN_STATUS_EXECUTION_FAILED'}
Traceback (most recent call last):
  File "C:\Users\...\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner

15:57:52-752925 ERROR    gradio call: RuntimeError
15:57:52-753862 ERROR    HTTP API: RuntimeError
    self.run()
  File "D:\SD\Vlad\automatic\modules\memmon.py", line 60, in run
    free, _total = self.cuda_mem_get_info()
  File "D:\SD\Vlad\automatic\modules\memmon.py", line 43, in cuda_mem_get_info
    return torch.cuda.mem_get_info(index)
  File "D:\SD\Vlad\automatic\venv\lib\site-packages\torch\cuda\memory.py", line 618, in mem_get_info
    return torch.cuda.cudart().cudaMemGetInfo(device)
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\venv\lib\site-packages\anyio\streams\memory.py:98 in receive                                    │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\anyio\streams\memory.py:93 in receive_nowait                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
WouldBlock

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\venv\lib\site-packages\starlette\middleware\base.py:78 in call_next                             │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\anyio\streams\memory.py:118 in receive                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
EndOfStream

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\modules\middleware.py:41 in log_and_time                                                        │
│                                                                                                                      │
│   40 │   │   │   ts = time.time()                                                                                    │
│ ❱ 41 │   │   │   res: Response = await call_next(req)                                                                │
│   42 │   │   │   duration = str(round(time.time() - ts, 4))                                                          │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\starlette\middleware\base.py:84 in call_next                             │
│                                                                                                                      │
│                                               ... 27 frames hidden ...                                               │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward                                  │
│                                                                                                                      │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ ❱  463 │   │   return self._conv_forward(input, self.weight, self.bias)                                              │
│    464                                                                                                               │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward                            │
│                                                                                                                      │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                                             │
│ ❱  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                                     │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\modules\call_queue.py:58 in f                                                                   │
│                                                                                                                      │
│    57 │   │   │   │   pr.enable()                                                                                    │
│ ❱  58 │   │   │   res = func(*args, **kwargs)                                                                        │
│    59 │   │   │   if res is None:                                                                                    │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\modules\txt2img.py:56 in txt2img                                                                │
│                                                                                                                      │
│   55 │   if processed is None:                                                                                       │
│ ❱ 56 │   │   processed = processing.process_images(p)                                                                │
│   57 │   p.close()                                                                                                   │
│                                                                                                                      │
│                                               ... 7 frames hidden ...                                                │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\torch\utils\_contextlib.py:115 in decorate_context                       │
│                                                                                                                      │
│   114 │   │   with ctx_factory():                                                                                    │
│ ❱ 115 │   │   │   return func(*args, **kwargs)                                                                       │
│   116                                                                                                                │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\repositories\k-diffusion\k_diffusion\sampling.py:522 in sample_dpmpp_2s_ancestral               │
│                                                                                                                      │
│   521 │   │   │   callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoi                       │
│ ❱ 522 │   │   if sigma_down == 0:                                                                                    │
│   523 │   │   │   # Euler method                                                                                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

15:57:52-867527 ERROR    API error: POST: http://127.0.0.1:7860/internal/progress {'error': 'RuntimeError', 'detail':
                         '', 'body': '', 'errors': 'CUDA error: an illegal memory access was encountered\nCUDA kernel
                         errors might be asynchronously reported at some other API call, so the stacktrace below might
                         be incorrect.\nFor debugging consider passing CUDA_LAUNCH_BLOCKING=1.\nCompile with
                         `TORCH_USE_CUDA_DSA` to enable device-side assertions.\n'}
15:57:53-119321 ERROR    [AgentScheduler] Task 989677cb-5abd-46bd-8696-4dc06afc3511 failed: CUDA error: an illegal
                         memory access was encountered
                         CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace
                         below might be incorrect.
                         For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
                         Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

15:57:53-121320 ERROR    HTTP API: RuntimeError
15:57:53-128333 INFO     [AgentScheduler] Task queue is empty
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\venv\lib\site-packages\anyio\streams\memory.py:98 in receive                                    │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\anyio\streams\memory.py:93 in receive_nowait                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
WouldBlock

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\venv\lib\site-packages\starlette\middleware\base.py:78 in call_next                             │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\anyio\streams\memory.py:118 in receive                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
EndOfStream

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD\Vlad\automatic\modules\middleware.py:41 in log_and_time                                                        │
│                                                                                                                      │
│   40 │   │   │   ts = time.time()                                                                                    │
│ ❱ 41 │   │   │   res: Response = await call_next(req)                                                                │
│   42 │   │   │   duration = str(round(time.time() - ts, 4))                                                          │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\starlette\middleware\base.py:84 in call_next                             │
│                                                                                                                      │
│                                               ... 23 frames hidden ...                                               │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\modules\sd_vae_approx.py:29 in forward                                                          │
│                                                                                                                      │
│   28 │   │   │   x = layer(x)                                                                                        │
│ ❱ 29 │   │   │   x = nn.functional.leaky_relu(x, 0.1)                                                                │
│   30                                                                                                                 │
│                                                                                                                      │
│ D:\SD\Vlad\automatic\venv\lib\site-packages\torch\nn\functional.py:1632 in leaky_relu                                │
│                                                                                                                      │
│   1631 │   else:                                                                                                     │
│ ❱ 1632 │   │   result = torch._C._nn.leaky_relu(input, negative_slope)                                               │
│   1633 │   return result                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
`

### Version Platform Description

Python 3.10.6 on Windows
Version: 875d0db1 Sun Jul 2 08:26:51 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128

Windows 11 64Bit latest release, 
CUDA Toolkit 12.2 
Graphics Driver 536.40
AMD 7950X
32GB DDR5 6000 CL36
ASUS X670E Strix
ASUS 4090 TUF
Firefox 114.2

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i don't think this has anything to do with agent scheduler changes, its more likely that agent scheduler is just pushing your system to limits and it breaks - what fails is a very simple and basic call `torch.cuda.mem_get_info()` - and if that fails, that means that there is a memory corruption. 

couple of things i'd try:
- remove cuda 12.2. you've installed that yourself, but torch comes with cuda 11.8 on its own. you dont want to have possibly conflicting libraries on the system. if you really want to use cuda 12.x, install torch 2.1-nightly which comes with it
- use nvidia driver 531? they are last known good ones, there are severe issues with memory in newer drivers (and nvidia has finally acknowledged that, so hopefully it will be fixed soon)
- try to downclock your gpu?

**Comment by Deniryer** [comment]
GPU is on Def clock for both mem and core, couldn't be it. Downgrading graphics drivers didn't solve it.

Once I'll get back home I'll try to downgrade CUDA to 12.1 which seemed to work without issues, but even then I can do batch size of 2 with count of 20 using Res 768x768, the issue only occurs when I try to queue them through scheduler agent, I'll test some things out I'll see if that works.

**Comment by Deniryer** [comment]
That's what I meant by saying downgrade, dunno what NV did in 12.2 so it causes so many issues but it seems to be stable now.

And it would be downgrade in terms of functionality because I do use FP8 so unfortunately atm going back to 11.8 is not an option. If that's the only permanent solution I guess I'll have to wait until WebUIs add fp8 support like dev of draw things app did in his latest update. 

Thank you for your response  help and time.
