### ISSUE TITLE
[Issue]: Set new defaults button not working

### ISSUE THREAD

**Issue by mobilehacker** [vladmandic/automatic#1575]
### Issue Description

Hello! When pressing "Set new defaults" button in "User interface defaults" section, nothing happens. If ui-config.json is present, "restore system defaults" button deletes it, but changes is not saved to a new file.

S:\_AI\vladmandic>call webui.bat --upgrade --listen --port 65000 --disable-queue --allow-code --insecure --no-download --debug
Using VENV: S:\_AI\vladmandic\venv
20:14:26-198348 INFO     Starting SD.Next
20:14:26-203349 INFO     Python 3.10.6 on Windows
20:14:26-256800 INFO     Version: 875d0db10 Sun Jul 2 08:26:51 2023 -0400
20:14:26-787256 DEBUG    Setting environment tuning
20:14:26-789230 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False
20:14:26-791231 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True
20:14:26-793264 INFO     nVidia CUDA toolkit detected
20:14:28-683117 INFO     Torch 2.0.1+cu118
20:14:28-700224 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
20:14:28-702218 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12287 Arch (8, 6) Cores 28
20:14:28-703193 DEBUG    Package version not found: tensorflow
20:14:28-705757 INFO     Installing package: tensorflow==2.12.0
20:14:28-706758 DEBUG    Running pip: install --upgrade tensorflow==2.12.0
20:15:37-161443 WARNING  Modified files: ['ui-config.json.bck', 'venv_1/']
20:15:37-271151 DEBUG    Repository update time: Sun Jul  2 15:26:51 2023
20:15:37-273151 DEBUG    Previous setup time: Tue Jul  4 20:11:34 2023
20:15:37-278191 INFO     Disabled extensions-builtin: ['sd-webui-lobe-theme']
20:15:37-280193 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'model-keyword', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
20:15:37-292230 INFO     Disabled extensions: ['sd-webui-lobe-theme']
20:15:37-294222 INFO     Enabled extensions: ['a1111-mini-paint', 'a1111-sd-webui-tagcomplete', 'adetailer',
                         'canvas-zoom', 'multi-subject-render', 'openpose-editor', 'sd-webui-additional-networks',
                         'sd-webui-inpaint-anything', 'sd-webui-regional-prompter',
                         'Stable-Diffusion-Webui-Civitai-Helper']
20:15:37-302248 DEBUG    Latest extensions time: Tue Jul  4 20:11:32 2023
20:15:37-304248 DEBUG    Timestamps: version:1688300811 setup:1688490694 extension:1688490692
20:15:37-306264 INFO     No changes detected: Quick launch active
20:15:37-322298 INFO     Extension preload: 0.0s S:\_AI\vladmandic\extensions-builtin
20:15:37-329338 INFO     Extension preload: 0.0s S:\_AI\vladmandic\extensions
20:15:37-353348 DEBUG    Memory used: 0.33 total: 47.94 Collected 0
20:15:37-356366 DEBUG    Starting module: <module 'webui' from 'S:\\_AI\\vladmandic\\webui.py'>
20:15:37-362888 INFO     Server arguments: ['--upgrade', '--listen', '--port', '65000', '--disable-queue',
                         '--allow-code', '--insecure', '--no-download',
                         '--debug']
20:15:37-373924 DEBUG    Loading Torch
20:15:49-096984 DEBUG    Loading Gradio
20:15:51-519712 DEBUG    Loading Modules
No module 'xformers'. Proceeding without it.
20:15:53-067641 DEBUG    Loaded styles: styles.csv 0
20:15:58-056317 INFO     Libraries loaded
20:15:58-069353 DEBUG    Entering start sequence
20:15:58-352822 DEBUG    Version: {'app': 'sd.next', 'updated': '2023-07-02', 'hash': '875d0db10', 'url':
                         'https://github.com/vladmandic/automatic/tree/master'}
20:15:58-355837 INFO     Using data path: S:\_AI\vladmandic
20:15:58-357851 DEBUG    Event loop: <_WindowsSelectorEventLoop running=False closed=False debug=False>
20:15:58-364358 DEBUG    Entering initialize
20:15:58-391974 INFO     Available VAEs: S:\_AI\vladmandic\models\VAE 12
20:15:58-513365 INFO     Available models: S:\_AI\vladmandic\models\Stable-diffusion 58
20:15:58-707166 DEBUG    Loading scripts
20:16:04-546217 INFO     ControlNet v1.1.229
ControlNet v1.1.229
ControlNet preprocessor location: S:\_AI\vladmandic\extensions-builtin\sd-webui-controlnet\annotator\downloads
20:16:04-991913 INFO     ControlNet v1.1.229
ControlNet v1.1.229
Image Browser: ImageReward is not installed, cannot be used.
[-] ADetailer initialized. version: 23.7.2, num models: 9
20:16:46-058450 ERROR    Module load: S:\_AI\vladmandic\extensions\multi-subject-render\scripts\simple_depthmap.py:
                         ModuleNotFoundError
Module load: S:\_AI\vladmandic\extensions\multi-subject-render\scripts\simple_depthmap.py: ModuleNotFoundError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ S:\_AI\vladmandic\modules\script_loading.py:13 in load_module                                                        │
│                                                                                                                      │
│   12 │   try:                                                                                                        │
│ ❱ 13 │   │   module_spec.loader.exec_module(module)                                                                  │
│   14 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│                                                                                                                      │
│                                               ... 3 frames hidden ...                                                │
│                                                                                                                      │
│ S:\_AI\vladmandic\extensions\multi-subject-render\repositories\midas\midas\blocks.py:4 in <module>                   │
│                                                                                                                      │
│     3                                                                                                                │
│ ❱   4 from .backbones.beit import (                                                                                  │
│     5 │   _make_pretrained_beitl16_512,                                                                              │
│                                                                                                                      │
│ S:\_AI\vladmandic\extensions\multi-subject-render\repositories\midas\midas\backbones\beit.py:9 in <module>           │
│                                                                                                                      │
│     8 from .utils import forward_adapted_unflatten, make_backbone_default                                            │
│ ❱   9 from timm.models.beit import gen_relative_position_index                                                       │
│    10 from torch.utils.checkpoint import checkpoint                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'timm.models.beit'
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: S:\_AI\vladmandic\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
20:16:50-990860 DEBUG    Scripts load: ['a1111-sd-webui-lycoris:2.462s', 'clip-interrogator-ext:0.352s', 'LDSR:0.11s',
                         'Lora:0.638s', 'model-keyword:0.119s', 'sd-dynamic-thresholding:0.118s',
                         'sd-extension-aesthetic-scorer:0.272s', 'sd-extension-system-info:0.243s',
                         'sd-webui-agent-scheduler:1.052s', 'sd-webui-controlnet:0.883s',
                         'sd-webui-model-converter:0.116s', 'seed_travel:0.071s',
                         'stable-diffusion-webui-images-browser:0.394s', 'stable-diffusion-webui-rembg:38.723s',
                         'SwinIR:0.074s', 'ScuNET:0.076s', 'a1111-mini-paint:0.073s',
                         'a1111-sd-webui-tagcomplete:0.141s', 'adetailer:1.377s', 'multi-subject-render:0.074s',
                         'openpose-editor:0.077s', 'sd-webui-additional-networks:0.299s',
                         'sd-webui-inpaint-anything:4.331s', 'sd-webui-regional-prompter:0.08s',
                         'Stable-Diffusion-Webui-Civitai-Helper:0.079s']
Scripts load: ['a1111-sd-webui-lycoris:2.462s', 'clip-interrogator-ext:0.352s', 'LDSR:0.11s', 'Lora:0.638s', 'model-keyword:0.119s', 'sd-dynamic-thresholding:0.118s', 'sd-extension-aesthetic-scorer:0.272s', 'sd-extension-system-info:0.243s', 'sd-webui-agent-scheduler:1.052s', 'sd-webui-controlnet:0.883s', 'sd-webui-model-converter:0.116s', 'seed_travel:0.071s', 'stable-diffusion-webui-images-browser:0.394s', 'stable-diffusion-webui-rembg:38.723s', 'SwinIR:0.074s', 'ScuNET:0.076s', 'a1111-mini-paint:0.073s', 'a1111-sd-webui-tagcomplete:0.141s', 'adetailer:1.377s', 'multi-subject-render:0.074s', 'openpose-editor:0.077s', 'sd-webui-additional-networks:0.299s', 'sd-webui-inpaint-anything:4.331s', 'sd-webui-regional-prompter:0.08s', 'Stable-Diffusion-Webui-Civitai-Helper:0.079s']
20:16:51-208758 INFO     Loading UI theme: name=gradio/default style=Dark
20:16:51-214313 DEBUG    Creating UI
20:16:51-215319 WARNING  Triggered lyco-patch-lora, will take lora_dir and <lora> format.
20:16:54-672418 DEBUG    Script: 2.49s ui_tabs
                         S:\_AI\vladmandic\extensions-builtin\stable-diffusion-webui-images-browser\scripts\image_browse
                         r.py
20:16:54-801557 DEBUG    Extensions list loaded: S:\_AI\vladmandic\html\extensions.json
20:16:57-557772 INFO     Server queues disabled
Running on local URL:  http://0.0.0.0:65000
20:17:02-097106 INFO     Local URL: http://localhost:65000/
20:17:02-101106 DEBUG    Gradio registered functions: 1955
20:17:02-103074 INFO     Initializing middleware
20:17:02-107615 DEBUG    Creating API
20:17:02-270593 INFO     [AgentScheduler] Task queue is empty
20:17:02-272624 INFO     [AgentScheduler] Registering APIs
20:17:02-422456 DEBUG    Scripts setup: ['Model keyword:0.016s', 'Tiled Diffusion:0.034s', 'ControlNet:0.018s',
                         'ADetailer:0.104s', 'Additional networks for generating:0.015s', 'Regional Prompter:0.01s',
                         'X/Y/Z grid:0.007s', 'Seed travel:0.006s']
20:17:02-424426 DEBUG    Scripts components: ['Custom code:0.007s']
20:17:02-425516 DEBUG    Model metadata: S:\_AI\vladmandic\metadata.json no changes
20:17:02-427517 DEBUG    Model auto load disabled
20:17:02-428516 INFO     Startup time: 85.1s (torch=11.7s gradio=2.4s libraries=6.5s vae=0.3s models=0.1s
                         codeformer=0.1s scripts=52.3s onchange=0.2s ui=6.3s launch=4.5s app-started=0.3s)
20:18:00-019781 DEBUG    Server alive=True Requests=276 memory used: 1.14 total: 47.94

### Version Platform Description

20:14:26-198348 INFO     Starting SD.Next
20:14:26-203349 INFO     Python 3.10.6 on Windows
20:14:26-256800 INFO     Version: 875d0db10 Sun Jul 2 08:26:51 2023 -0400

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by cjps-br** [comment]
I couldn't get it to work either and so I gave up.

**Comment by vladmandic** [comment]
@mobilehacker 
- change some setting
- press view changes - does it list changes you've made?
- now press save new default - what happens? and what is printed in console log?

@cjps-br your comment is not really helpful.  
if you didn't create issue and go through troubleshooting, how it can be fixed that way?

**Comment by cjps-br** [comment]
> @cjps-br your comment is not really helpful. if you didn't create issue and go through troubleshooting, how it can be fixed that way?

I chatted with you on Discord in the dev-chat channel on June 14th. As this functionality is not essential for me, and because I understand that there must be more important things in the development backlog, I decided not to continue. Sorry if I commented here. I just wanted to let the author of the issue know that it's not something that just happens to him.

**Comment by mobilehacker** [comment]
> @mobilehacker
> 
>     * change some setting
> 
>     * press view changes - does it list changes you've made?
> 
>     * now press save new default - what happens? and what is printed in console log?
> 
> 
> @cjps-br your comment is not really helpful. if you didn't create issue and go through troubleshooting, how it can be fixed that way?

No buttons except restore defaults work, and no additional output in console. Thats what gets output when restore defaults is pressed, along with the deletion of the ui-config.json:

18:37:48-890628 INFO     UI defaults reset: S:\_AI\vladmandic\ui-config.json
18:37:59-871299 DEBUG    Server alive=True Requests=709 memory used: 5.6 total: 47.94
