### ISSUE TITLE
[Feature] Support user-defined multiple style.csv files

### ISSUE THREAD

**Issue by Panchvzluck** [vladmandic/automatic#158]
### Issue Description

Hi there, really nice work!

Wondering if there's an option like "--styles-file" to specify a path where a style.csv file is.

Searched on all the settings but I didn't found this setting specifically.

Thanks in advance.

### Version Platform Description

updated: 2023-04-15
hash: 45dcc694
url: https://github.com/vladmandic/automatic/tree/master

Windows 11

Google Chrome

**Comment by vladmandic** [comment]
not at the moment, but is it really necessary to support or have multiple `style.csv` files? what is the use case? i want to keep it as simple as possible, not add extra command line flags that would only be used very rarely.

**Comment by Panchvzluck** [comment]
I want to mostly to be able use the same style.csv in two stable diffusions instances (folders) at the same time, instead of having to update one and then copy it to the other instance (folder).

So, if on one SD instance I update the style.csv, it is updated on the other one as well.

**Comment by vladmandic** [comment]
> So, if on one SD instance I update the style.csv, it is updated on the other one as well.

why not symlink?

**Comment by Panchvzluck** [comment]
> why not symlink?

You're right, that's another way to do it.

Closing with that then.
