### ISSUE TITLE
[Issue]: Question about VRam usage compared to other forks

### ISSUE THREAD

**Issue by HyunJae5463** [vladmandic/automatic#1587]
### Issue Description

I have been using [this fork](https://github.com/Aloereed/stable-diffusion-webui-arc-directml/) for quite some time now which allows me to generate images like 440 x 780 with 2x Upscale. The downside is that its rather slow due to the lack of optimization and its not getting any updates either, which can result in Extensions breaking etc.

With this version however i have to go down like a hundred pixels on both sides to not run out of memory. In both versions i have been using med vram and quad attention. I have also tried different processing methods in this version but i still run out of Vram when i use the same resolutions as in Aloereeds SD version.

I have an Arc A770 btw with 16 GB VRam. 

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by brknsoul** [comment]
Questions belong in the Discussion section, not here. You've also forgotten to paste the first few lines of the console.

**Comment by vladmandic** [comment]
like @brknsoul said, closing the issue.
