### ISSUE TITLE
[Issue]: Process Tab loads model for every image

### ISSUE THREAD

**Issue by Sniper199999** [vladmandic/automatic#1593]
### Issue Description

While Processing multiple images using "Process Batch" and using both upscalars: Upscaler and Secondary Upscaler, the models are loaded again and again for each images and slowing the speed of overall process.
Maybe there is a way to load The first Upscaler and process all images and then load the second Upscaler and process all the images.

### Version Platform Description

 Starting SD.Next
Python 3.10.9 on Windows
Version: 875d0db1 Sun Jul 2 08:26:51 2023 -0400
Latest published version: 3bcca6f92b4d457eff8616e157ba13421f59527f 2023-07-05T23:51:27Z
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
first, this is not an issue. at best, its a feature request.
and i've always been against chaining multiple upscalers - its always better to find a single good upscaler (and there are good ones out there) than do chaining. if you really want to use chaining, this is it - i will not work on additional code for this.
