### ISSUE TITLE
[Issue]: System path to models not working anymore (?)

### ISSUE THREAD

**Issue by Centurion-Rome** [vladmandic/automatic#1594]
### Issue Description

After new git clone and copying my backup config "config.json" & "ui-config.json"
I can not use custom path to models, getting error:
```
23:16:40-512018 INFO     Available VAEs: E:\AI\SD_Models\vae 3
23:16:40-514533 INFO     Available models: E:\AI\SD_Models 0
Download the default model? (y/N)
```
I have models directly in that dir and also some in sub-dirs, until now it was working correctly.

What I have also tried: Made some changes in UI config => system path" and save them to overwrite, but no help

### Version Platform Description

windows 11,

```
23:15:56-204725 INFO     Starting SD.Next
23:15:56-208726 INFO     Python 3.10.7 on Windows
23:15:56-269963 INFO     Version: 3bcca6f9 Thu Jul 6 02:51:27 2023 +0300
23:15:56-481480 INFO     nVidia CUDA toolkit detected
23:15:58-054481 INFO     Torch 2.0.1+cu118
23:15:58-085418 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
23:15:58-087416 INFO     Torch detected GPU: NVIDIA GeForce RTX 2080 SUPER VRAM 8192 Arch (7, 5) Cores 48
```Windows

```
COMMANDLINE_ARGS=--autolaunch --medvram --upgrade 
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by brknsoul** [comment]
Your Stable Diffusion checkpoints are located in `modes\Stable-diffusion`, not `models\`.
