### ISSUE TITLE
[Issue]: Unable to save generated images - module 'modules.images' has no attribute 'save_image_with_geninfo'

### ISSUE THREAD

**Issue by DEC1MU5** [vladmandic/automatic#1596]
### Issue Description

One of my settings seems to be incorrect, SD cant save the images as I generate them. I have specific directories specified etc, everything looks fine to me. 
The image generates to about 99% then throws this
module 'modules.images' has no attribute 'save_image_with_geninfo'

### Version Platform Description

Win 11, Chrome
Using VENV: C:\AI\VladMatic\venv
01:48:34-566398 INFO     Starting SD.Next
01:48:34-570399 INFO     Python 3.10.6 on Windows
01:48:34-610408 INFO     Version: 3bcca6f9 Thu Jul 6 02:51:27 2023 +0300
01:48:34-989494 INFO     nVidia CUDA toolkit detected
01:48:36-453826 INFO     Torch 2.0.1+cu118
01:48:36-476830 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
01:48:36-478831 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 Ti VRAM 8192 Arch (8, 6) Cores 38
01:48:36-615861 INFO     Disabled extensions-builtin: ['Cozy-Nest', 'sd-webui-lobe-theme']
01:48:36-617863 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
01:48:36-626864 INFO     Disabled extensions: ['Cozy-Nest', 'sd-webui-lobe-theme']
01:48:36-629864 INFO     Enabled extensions: ['--sd-webui-ar-plus', 'a1111-stable-diffusion-webui-vram-estimator',
                         'adetailer', 'canvas-zoom', 'model-keyword', 'sd-dynamic-prompts',
                         'sd-webui-additional-networks', 'sd-webui-prompt-all-in-one', 'sd-webui-prompt-history',
                         'sd-webui-roop', 'sd-webui-stablesr', 'sd_delete_button', 'sd_dreambooth_extension',
                         'Stable-Diffusion-Webui-Civitai-Helper', 'stable-diffusion-webui-conditioning-highres-fix',
                         'stable-diffusion-webui-distributed', 'ultimate-upscale-for-automatic1111']
01:48:36-644869 INFO     Verifying requirements
01:48:36-654870 WARNING  Package wrong version: accelerate 0.19.0 required 0.20.3
01:48:36-656871 INFO     Installing package: accelerate==0.20.3
01:48:38-943871 WARNING  Package wrong version: diffusers 0.16.1 required 0.17.1
01:48:38-945872 INFO     Installing package: diffusers==0.17.1
01:48:41-709373 WARNING  Package wrong version: transformers 4.29.2 required 4.26.1
01:48:41-711375 INFO     Installing package: transformers==4.26.1
01:48:49-612441 INFO     Verifying packages
01:48:49-614441 INFO     Installing repositories
01:48:52-446082 INFO     Installing submodules

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by GraspGG** [comment]
As of here: [vladmantic SD.NEW issue about this](https://github.com/vladmandic/automatic/issues/1596)

> you have not posted actual trace of the error, only noted it in a headline.
> 
> **function `modules.images.save_image_with_geninfo` was obsoleted a long time ago and its not referenced anywhere.**
> 
> which means you have an extension that is trying to use it. well, that function was always internal-only and no extension should use it. if extension wants to use a correct method, it should rely on `modules.images.save_image`.
> 
> i suggest to find which extension is doing this (you'll see it in console log showing actual error) and report to extension owner.

...if that is of any help (:
