### ISSUE TITLE
[Extension]: Latent Couple extension bugging with Inpainting

### ISSUE THREAD

**Issue by razvan-nicolae** [vladmandic/automatic#160]
### Issue Description

https://github.com/opparco/stable-diffusion-webui-two-shot - seems to have a conflict when you try to inpaint:
TypeError: unsupported operand type(s) for -=: 'bool' and 'str'
Time taken: 0.68sTorch active/reserved: 2861/3004 MiB, Sys VRAM: 4966/24564 MiB (20.22%)

Full log below - I think there are 2 or 3 attempts there, similar errors.

running script process: I:\SD\automatic\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py: ValueError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:415 in process                                                                   │
│                                                                                                                     │
│   414 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 415 │   │   │   │   script.process(p, *script_args)                                                               │
│   416 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ I:\SD\automatic\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:204 in process                       │
│                                                                                                                     │
│   203 │   │                                                                                                         │
│ > 204 │   │   self.filters = self.create_filters_from_ui_params(raw_divisions, raw_positions,                       │
│   205                                                                                                               │
│                                                                                                                     │
│ I:\SD\automatic\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:71 in create_filters_from_ui_params  │
│                                                                                                                     │
│    70 │   │   for division in raw_divisions.split(','):                                                             │
│ >  71 │   │   │   y, x = division.split(':')                                                                        │
│    72 │   │   │   divisions.append(Division(float(y), float(x)))                                                    │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError: not enough values to unpack (expected 2, got 1)
Steps animation patching sampler callback for: Euler a
running script process: I:\SD\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:415 in process                                                                   │
│                                                                                                                     │
│   414 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 415 │   │   │   │   script.process(p, *script_args)                                                               │
│   416 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:640 in process                         │
│                                                                                                                     │
│   639 │   │   for idx, unit in enumerate(params_group):                                                             │
│ > 640 │   │   │   unit = self.parse_remote_call(p, unit, idx)                                                       │
│   641 │   │   │   if not unit.enabled:                                                                              │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:552 in parse_remote_call               │
│                                                                                                                     │
│   551 │   │                                                                                                         │
│ > 552 │   │   unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True                      │
│   553 │   │   unit.module = selector(p, "control_net_module", unit.module, idx)                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'str' object has no attribute 'enabled'
  0%|                                                                                           | 0/30 [00:00<?, ?it/s]
gradio call: TypeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\call_queue.py:59 in f                                                                       │
│                                                                                                                     │
│    58 │   │   │   │   pr.enable()                                                                                   │
│ >  59 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    60 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ I:\SD\automatic\modules\call_queue.py:38 in f                                                                       │
│                                                                                                                     │
│    37 │   │   │   try:                                                                                              │
│ >  38 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    39 │   │   │   finally:                                                                                          │
│                                                                                                                     │
│                                              ... 12 frames hidden ...                                               │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-dynamic-thresholding\dynthres_core.py:42 in dynthresh                         │
│                                                                                                                     │
│    41 │   def dynthresh(self, cond, uncond, cfgScale, weights):                                                     │
│ >  42 │   │   mimicScale = self.interpretScale(self.mimic_scale, self.mimic_mode, self.mimic_s                      │
│    43 │   │   cfgScale = self.interpretScale(cfgScale, self.cfg_mode, self.cfg_scale_min)                           │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-dynamic-thresholding\dynthres_core.py:18 in interpretScale                    │
│                                                                                                                     │
│    17 │   def interpretScale(self, scale, mode, min):                                                               │
│ >  18 │   │   scale -= min                                                                                          │
│    19 │   │   max = self.maxSteps - 1                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: unsupported operand type(s) for -=: 'bool' and 'str'
running script process: I:\SD\automatic\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py: ValueError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:415 in process                                                                   │
│                                                                                                                     │
│   414 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 415 │   │   │   │   script.process(p, *script_args)                                                               │
│   416 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ I:\SD\automatic\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:204 in process                       │
│                                                                                                                     │
│   203 │   │                                                                                                         │
│ > 204 │   │   self.filters = self.create_filters_from_ui_params(raw_divisions, raw_positions,                       │
│   205                                                                                                               │
│                                                                                                                     │
│ I:\SD\automatic\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:71 in create_filters_from_ui_params  │
│                                                                                                                     │
│    70 │   │   for division in raw_divisions.split(','):                                                             │
│ >  71 │   │   │   y, x = division.split(':')                                                                        │
│    72 │   │   │   divisions.append(Division(float(y), float(x)))                                                    │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError: not enough values to unpack (expected 2, got 1)
running script process: I:\SD\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:415 in process                                                                   │
│                                                                                                                     │
│   414 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 415 │   │   │   │   script.process(p, *script_args)                                                               │
│   416 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:640 in process                         │
│                                                                                                                     │
│   639 │   │   for idx, unit in enumerate(params_group):                                                             │
│ > 640 │   │   │   unit = self.parse_remote_call(p, unit, idx)                                                       │
│   641 │   │   │   if not unit.enabled:                                                                              │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:552 in parse_remote_call               │
│                                                                                                                     │
│   551 │   │                                                                                                         │
│ > 552 │   │   unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True                      │
│   553 │   │   unit.module = selector(p, "control_net_module", unit.module, idx)                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'str' object has no attribute 'enabled'
  0%|                                                                                           | 0/30 [00:00<?, ?it/s]
gradio call: TypeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\call_queue.py:59 in f                                                                       │
│                                                                                                                     │
│    58 │   │   │   │   pr.enable()                                                                                   │
│ >  59 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    60 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ I:\SD\automatic\modules\call_queue.py:38 in f                                                                       │
│                                                                                                                     │
│    37 │   │   │   try:                                                                                              │
│ >  38 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    39 │   │   │   finally:                                                                                          │
│                                                                                                                     │
│                                              ... 12 frames hidden ...                                               │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-dynamic-thresholding\dynthres_core.py:42 in dynthresh                         │
│                                                                                                                     │
│    41 │   def dynthresh(self, cond, uncond, cfgScale, weights):                                                     │
│ >  42 │   │   mimicScale = self.interpretScale(self.mimic_scale, self.mimic_mode, self.mimic_s                      │
│    43 │   │   cfgScale = self.interpretScale(cfgScale, self.cfg_mode, self.cfg_scale_min)                           │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-dynamic-thresholding\dynthres_core.py:18 in interpretScale                    │
│                                                                                                                     │
│    17 │   def interpretScale(self, scale, mode, min):                                                               │
│ >  18 │   │   scale -= min                                                                                          │
│    19 │   │   max = self.maxSteps - 1                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: unsupported operand type(s) for -=: 'bool' and 'str'

### Version Platform Description

Windows 11, RTX 4090

commit: [4955a90c](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/4955a90c7ba0524e091009e6742e4c805a6dfc60)  
•  checkpoint: [3cb09d984c](https://google.com/search?q=3cb09d984cdd6400fbff3abc1b01c49db952d0c7c7259ee935ba4d2dc3ee74b4)

**Comment by vladmandic** [comment]
there is a lot going on here, interaction between 3 extensions, its going to take me a bit to unpack.

**Comment by razvan-nicolae** [comment]
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:415 in process                                                                   │
│                                                                                                                     │
│   414 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 415 │   │   │   │   script.process(p, *script_args)                                                               │
│   416 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ I:\SD\automatic\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:204 in process                       │
│                                                                                                                     │
│   203 │   │                                                                                                         │
│ > 204 │   │   self.filters = self.create_filters_from_ui_params(raw_divisions, raw_positions,                       │
│   205                                                                                                               │
│                                                                                                                     │
│ I:\SD\automatic\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:70 in create_filters_from_ui_params  │
│                                                                                                                     │
│    69 │   │   divisions = []                                                                                        │
│ >  70 │   │   for division in raw_divisions.split(','):                                                             │
│    71 │   │   │   y, x = division.split(':')                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'bool' object has no attribute 'split'
running script process: I:\SD\automatic\extensions-builtin\model-keyword\scripts\model_keyword.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:415 in process                                                                   │
│                                                                                                                     │
│   414 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 415 │   │   │   │   script.process(p, *script_args)                                                               │
│   416 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\model-keyword\scripts\model_keyword.py:657 in process                            │
│                                                                                                                     │
│   656 │   │   if kw is not None or ti_keywords != 'None' or lora_model != 'None':                                   │
│ > 657 │   │   │   p.prompt = new_prompt(p.prompt, kw, no_iter=True)                                                 │
│   658 │   │   │   p.all_prompts = [new_prompt(prompt, kw) for prompt in p.all_prompts]                              │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\model-keyword\scripts\model_keyword.py:612 in new_prompt                         │
│                                                                                                                     │
│   611 │   │   │   if ti_keywords != 'None':                                                                         │
│ > 612 │   │   │   │   ti = ti_keywords[:ti_keywords.rfind('.')]                                                     │
│   613                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'int' object has no attribute 'rfind'
running script process:
I:\SD\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py: ValueError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:415 in process                                                                   │
│                                                                                                                     │
│   414 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 415 │   │   │   │   script.process(p, *script_args)                                                               │
│   416 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:301 in        │
│ process                                                                                                             │
│                                                                                                                     │
│   300 │   │   if is_img2img:    # img2img                                                                           │
│ > 301 │   │   │   upscaler_name = [x.name for x in shared.sd_upscalers].index(upscaler_index)                       │
│   302 │   │   │   init_img = p.init_images[0]                                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError: 0.2 is not in list
Steps animation patching sampler callback for: DPM++ SDE Karras
running script process: I:\SD\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:415 in process                                                                   │
│                                                                                                                     │
│   414 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 415 │   │   │   │   script.process(p, *script_args)                                                               │
│   416 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:639 in process                         │
│                                                                                                                     │
│   638 │   │   for idx, unit in enumerate(params_group):                                                             │
│ > 639 │   │   │   unit = self.parse_remote_call(p, unit, idx)                                                       │
│   640 │   │   │   if not unit.enabled:                                                                              │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:554 in parse_remote_call               │
│                                                                                                                     │
│   553 │   │                                                                                                         │
│ > 554 │   │   unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True                      │
│   555 │   │   unit.module = selector(p, "control_net_module", unit.module, idx)                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'str' object has no attribute 'enabled'
[Tiled VAE]: input_size: torch.Size([1, 3, 512, 512]), tile_size: 0, padding: 32
gradio call: ZeroDivisionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\call_queue.py:59 in f                                                                       │
│                                                                                                                     │
│    58 │   │   │   │   pr.enable()                                                                                   │
│ >  59 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    60 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ I:\SD\automatic\modules\call_queue.py:38 in f                                                                       │
│                                                                                                                     │
│    37 │   │   │   try:                                                                                              │
│ >  38 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    39 │   │   │   finally:                                                                                          │
│                                                                                                                     │
│                                              ... 13 frames hidden ...                                               │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py:543 in         │
│ vae_tile_forward                                                                                                    │
│                                                                                                                     │
│   542 │   │                                                                                                         │
│ > 543 │   │   in_bboxes, out_bboxes = self.split_tiles(height, width)                                               │
│   544                                                                                                               │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py:429 in         │
│ split_tiles                                                                                                         │
│                                                                                                                     │
│   428 │   │   pad = self.pad                                                                                        │
│ > 429 │   │   num_height_tiles = math.ceil((h - 2 * pad) / tile_size)                                               │
│   430 │   │   num_width_tiles = math.ceil((w - 2 * pad) / tile_size)                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ZeroDivisionError: division by zero
running script process: I:\SD\automatic\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:415 in process                                                                   │
│                                                                                                                     │
│   414 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 415 │   │   │   │   script.process(p, *script_args)                                                               │
│   416 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ I:\SD\automatic\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:204 in process                       │
│                                                                                                                     │
│   203 │   │                                                                                                         │
│ > 204 │   │   self.filters = self.create_filters_from_ui_params(raw_divisions, raw_positions,                       │
│   205                                                                                                               │
│                                                                                                                     │
│ I:\SD\automatic\extensions\stable-diffusion-webui-two-shot\scripts\two_shot.py:70 in create_filters_from_ui_params  │
│                                                                                                                     │
│    69 │   │   divisions = []                                                                                        │
│ >  70 │   │   for division in raw_divisions.split(','):                                                             │
│    71 │   │   │   y, x = division.split(':')                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'bool' object has no attribute 'split'
File I:\SD\automatic\extensions\stable-diffusion-webui-wildcards\wildcards\asd.txt not found for the __asd__ wildcard.
running script process: I:\SD\automatic\extensions-builtin\model-keyword\scripts\model_keyword.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:415 in process                                                                   │
│                                                                                                                     │
│   414 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 415 │   │   │   │   script.process(p, *script_args)                                                               │
│   416 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\model-keyword\scripts\model_keyword.py:657 in process                            │
│                                                                                                                     │
│   656 │   │   if kw is not None or ti_keywords != 'None' or lora_model != 'None':                                   │
│ > 657 │   │   │   p.prompt = new_prompt(p.prompt, kw, no_iter=True)                                                 │
│   658 │   │   │   p.all_prompts = [new_prompt(prompt, kw) for prompt in p.all_prompts]                              │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\model-keyword\scripts\model_keyword.py:612 in new_prompt                         │
│                                                                                                                     │
│   611 │   │   │   if ti_keywords != 'None':                                                                         │
│ > 612 │   │   │   │   ti = ti_keywords[:ti_keywords.rfind('.')]                                                     │
│   613                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'int' object has no attribute 'rfind'
running script process:
I:\SD\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py: ValueError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:415 in process                                                                   │
│                                                                                                                     │
│   414 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 415 │   │   │   │   script.process(p, *script_args)                                                               │
│   416 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:301 in        │
│ process                                                                                                             │
│                                                                                                                     │
│   300 │   │   if is_img2img:    # img2img                                                                           │
│ > 301 │   │   │   upscaler_name = [x.name for x in shared.sd_upscalers].index(upscaler_index)                       │
│   302 │   │   │   init_img = p.init_images[0]                                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError: 0.2 is not in list
running script process: I:\SD\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\scripts.py:415 in process                                                                   │
│                                                                                                                     │
│   414 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 415 │   │   │   │   script.process(p, *script_args)                                                               │
│   416 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:639 in process                         │
│                                                                                                                     │
│   638 │   │   for idx, unit in enumerate(params_group):                                                             │
│ > 639 │   │   │   unit = self.parse_remote_call(p, unit, idx)                                                       │
│   640 │   │   │   if not unit.enabled:                                                                              │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:554 in parse_remote_call               │
│                                                                                                                     │
│   553 │   │                                                                                                         │
│ > 554 │   │   unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True                      │
│   555 │   │   unit.module = selector(p, "control_net_module", unit.module, idx)                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'str' object has no attribute 'enabled'
[Tiled VAE]: input_size: torch.Size([1, 3, 512, 512]), tile_size: 0, padding: 32
gradio call: ZeroDivisionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\SD\automatic\modules\call_queue.py:59 in f                                                                       │
│                                                                                                                     │
│    58 │   │   │   │   pr.enable()                                                                                   │
│ >  59 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    60 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ I:\SD\automatic\modules\call_queue.py:38 in f                                                                       │
│                                                                                                                     │
│    37 │   │   │   try:                                                                                              │
│ >  38 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    39 │   │   │   finally:                                                                                          │
│                                                                                                                     │
│                                              ... 13 frames hidden ...                                               │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py:543 in         │
│ vae_tile_forward                                                                                                    │
│                                                                                                                     │
│   542 │   │                                                                                                         │
│ > 543 │   │   in_bboxes, out_bboxes = self.split_tiles(height, width)                                               │
│   544                                                                                                               │
│                                                                                                                     │
│ I:\SD\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\vae_optimize.py:429 in         │
│ split_tiles                                                                                                         │
│                                                                                                                     │
│   428 │   │   pad = self.pad                                                                                        │
│ > 429 │   │   num_height_tiles = math.ceil((h - 2 * pad) / tile_size)                                               │
│   430 │   │   num_width_tiles = math.ceil((w - 2 * pad) / tile_size)                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ZeroDivisionError: division by zero


different error for this issue now, after uninstalling dynamic prompts.

**Comment by vladmandic** [comment]
@razvan-nicolae what is the workflow that leads to this traceback?

**Comment by razvan-nicolae** [comment]
just open an image try to inpaint, no prompt needed. it will crash either way.

**Comment by vladmandic** [comment]
i've tried to engage, but extension <https://github.com/opparco/stable-diffusion-webui-two-shot> seems to be abandoned. it has no updates in 7+ months and author is non responsive.
