### ISSUE TITLE
[Feature]: revert extra networks interface

### ISSUE THREAD

**Issue by doomiiiii** [vladmandic/automatic#1600]
### Feature description

now i'm not saying that this new ui is a stinking pile of garbage; but that is most absolutely what i'm saying, it takes too much space, it's buggy, it's ugly, it's incredibly inconvenient and shows less than the previous one despite taking three times as much screen space, and it breaks apart as soon as you scroll down
![gsdgf](https://github.com/vladmandic/automatic/assets/138892427/1dd0b760-2c9c-4d7c-9cdd-e53cb415a49b)
![image](https://github.com/vladmandic/automatic/assets/138892427/db20246e-9573-4b74-aa7d-126732936d71)

this is a piece of shit and should never have happened, much less replace the old one entirely, so if you really want this piece of junk to stay that's fine but at least don't remove the option to have a functional one like you did

**Comment by vladmandic** [comment]
closing. and you're really close to ban due to language.

**Comment by doomiiiii** [comment]
is graphic design your passion by any chance

oh well, good time to find a better fork i guess cause this is so bad as to be intolerable

**Comment by vladmandic** [comment]
congratulations for being second ever blocked user.

**Comment by Aptronymist** [comment]
If you weren't so busy being a jackass, any issues you had would likely have been addressed. There are changes to that coming out of our dev branch very soon, possibly today, but I guess you won't be trying it.

**Comment by Aptronymist** [comment]
> is graphic design your passion by any chance
> 
> oh well, good time to find a better fork i guess cause this is so bad as to be intolerable
> 
> i made a github account specifically because this change is so fucking horrendously bad that it warranted the insult you think threatening a ban matters to me?

If you weren't so busy being a jackass, any issues you had would likely have been addressed. There are changes to that coming out of our dev branch very soon, possibly today, but I guess you won't be trying it.
