### ISSUE TITLE
[Issue]: Error on initial install

### ISSUE THREAD

**Issue by jp7189** [vladmandic/automatic#1604]
### Issue Description

Cloned the repo today (7/7/23) and ran webui.bat which triggered the initial install.  The failed with the traceback below.  Re-running webui.bat completed the installation, so I'm able to move past it, but thought you might want to know the details.

┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\vlad\automatic\launch.py:189 in <module>                                                      │
│                                                                                                  │
│   186 │   # installer.log.debug(f"Args: {vars(args)}")                                           │
│   187 │   logging.disable(logging.NOTSET if args.debug else logging.DEBUG)                       │
│   188 │                                                                                          │
│ > 189 │   instance = start_server(immediate=True, server=None)                                   │
│   190 │   while True:                                                                            │
│   191 │   │   try:                                                                               │
│   192 │   │   │   alive = instance.thread.is_alive()                                             │
│                                                                                                  │
│ C:\vlad\automatic\launch.py:136 in start_server                                                  │
│                                                                                                  │
│   133 │   server = importlib.util.module_from_spec(module_spec)                                  │
│   134 │   installer.log.debug(f'Starting module: {server}')                                      │
│   135 │   installer.log.info(f"Server arguments: {sys.argv[1:]}")                                │
│ > 136 │   module_spec.loader.exec_module(server)                                                 │
│   137 │   if args.test:                                                                          │
│   138 │   │   installer.log.info("Test only")                                                    │
│   139 │   │   server.wants_restart = False                                                       │
│ in exec_module:883                                                                               │
│ in _call_with_frames_removed:241                                                                 │
│                                                                                                  │
│ C:\vlad\automatic\webui.py:35 in <module>                                                        │
│                                                                                                  │
│    32 startup_timer.record("torch")                                                              │
│    33                                                                                            │
│    34 errors.log.debug('Loading Gradio')                                                         │
│ >  35 from fastapi import FastAPI # pylint: disable=W0611,C0411                                  │
│    36 import gradio # pylint: disable=W0611,C0411                                                │
│    37 startup_timer.record("gradio")                                                             │
│    38 errors.install([gradio])                                                                   │
│                                                                                                  │
│ C:\vlad\automatic\venv\lib\site-packages\fastapi\__init__.py:7 in <module>                       │
│                                                                                                  │
│    4                                                                                             │
│    5 from starlette import status as status                                                      │
│    6                                                                                             │
│ >  7 from .applications import FastAPI as FastAPI                                                │
│    8 from .background import BackgroundTasks as BackgroundTasks                                  │
│    9 from .datastructures import UploadFile as UploadFile                                        │
│   10 from .exceptions import HTTPException as HTTPException                                      │
│                                                                                                  │
│ C:\vlad\automatic\venv\lib\site-packages\fastapi\applications.py:16 in <module>                  │
│                                                                                                  │
│    13 │   Union,                                                                                 │
│    14 )                                                                                          │
│    15                                                                                            │
│ >  16 from fastapi import routing                                                                │
│    17 from fastapi.datastructures import Default, DefaultPlaceholder                             │
│    18 from fastapi.exception_handlers import (                                                   │
│    19 │   http_exception_handler,                                                                │
│                                                                                                  │
│ C:\vlad\automatic\venv\lib\site-packages\fastapi\routing.py:22 in <module>                       │
│                                                                                                  │
│     19 │   Union,                                                                                │
│     20 )                                                                                         │
│     21                                                                                           │
│ >   22 from fastapi import params                                                                │
│     23 from fastapi._compat import (                                                             │
│     24 │   ModelField,                                                                           │
│     25 │   Undefined,                                                                            │
│                                                                                                  │
│ C:\vlad\automatic\venv\lib\site-packages\fastapi\params.py:6 in <module>                         │
│                                                                                                  │
│     3 from typing import Any, Callable, Dict, List, Optional, Sequence, Union                    │
│     4                                                                                            │
│     5 from pydantic.fields import FieldInfo                                                      │
│ >   6 from typing_extensions import Annotated, deprecated                                        │
│     7                                                                                            │
│     8 from ._compat import PYDANTIC_V2, Undefined                                                │
│     9                                                                                            │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
ImportError: cannot import name 'deprecated' from 'typing_extensions'
(C:\vlad\automatic\venv\lib\site-packages\typing_extensions.py)
Press any key to continue . . .

### Version Platform Description

updated: 2023-07-06
hash: 3bcca6f9
url: https://github.com/vladmandic/automatic/tree/master
15:47:51-776756 INFO     Starting SD.Next
15:47:51-776756 INFO     Python 3.10.6 on Windows
15:47:51-806758 INFO     Version: 3bcca6f9 Thu Jul 6 02:51:27 2023 +0300
15:47:52-127330 INFO     Latest published version: 205b5164872aadc61b49ee409352c0a5c736aa84 2023-07-07T19:41:26Z
15:47:52-127330 INFO     nVidia CUDA toolkit detected
15:47:53-336874 INFO     Torch 2.0.1+cu118
15:47:53-356910 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
15:47:53-356910 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82
15:47:53-466910 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
15:47:53-466910 INFO     Enabled extensions: []
15:47:53-466910 INFO     No changes detected: Quick launch active
15:47:53-476909 INFO     Extension preload: 0.0s C:\vlad\automatic\extensions-builtin
15:47:53-476909 INFO     Extension preload: 0.0s C:\vlad\automatic\extensions
15:47:53-486911 INFO     Server arguments: []

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed in dev, will be merged to main tomorrow

**Comment by ouchnet** [comment]
> ### Issue Description
> Cloned the repo today (7/7/23) and ran webui.bat which triggered the initial install. The failed with the traceback below. Re-running webui.bat completed the installation, so I'm able to move past it, but thought you might want to know the details.
> 
> ┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐ │ C:\vlad\automatic\launch.py:189 in │ │ │ │ 186 │ # installer.log.debug(f"Args: {vars(args)}") │ │ 187 │ logging.disable(logging.NOTSET if args.debug else logging.DEBUG) │ │ 188 │ │ │ > 189 │ instance = start_server(immediate=True, server=None) │ │ 190 │ while True: │ │ 191 │ │ try: │ │ 192 │ │ │ alive = instance.thread.is_alive() │ │ │ │ C:\vlad\automatic\launch.py:136 in start_server │ │ │ │ 133 │ server = importlib.util.module_from_spec(module_spec) │ │ 134 │ installer.log.debug(f'Starting module: {server}') │ │ 135 │ installer.log.info(f"Server arguments: {sys.argv[1:]}") │ │ > 136 │ module_spec.loader.exec_module(server) │ │ 137 │ if args.test: │ │ 138 │ │ installer.log.info("Test only") │ │ 139 │ │ server.wants_restart = False │ │ in exec_module:883 │ │ in _call_with_frames_removed:241 │ │ │ │ C:\vlad\automatic\webui.py:35 in │ │ │ │ 32 startup_timer.record("torch") │ │ 33 │ │ 34 errors.log.debug('Loading Gradio') │ │ > 35 from fastapi import FastAPI # pylint: disable=W0611,C0411 │ │ 36 import gradio # pylint: disable=W0611,C0411 │ │ 37 startup_timer.record("gradio") │ │ 38 errors.install([gradio]) │ │ │ │ C:\vlad\automatic\venv\lib\site-packages\fastapi__init__.py:7 in │ │ │ │ 4 │ │ 5 from starlette import status as status │ │ 6 │ │ > 7 from .applications import FastAPI as FastAPI │ │ 8 from .background import BackgroundTasks as BackgroundTasks │ │ 9 from .datastructures import UploadFile as UploadFile │ │ 10 from .exceptions import HTTPException as HTTPException │ │ │ │ C:\vlad\automatic\venv\lib\site-packages\fastapi\applications.py:16 in │ │ │ │ 13 │ Union, │ │ 14 ) │ │ 15 │ │ > 16 from fastapi import routing │ │ 17 from fastapi.datastructures import Default, DefaultPlaceholder │ │ 18 from fastapi.exception_handlers import ( │ │ 19 │ http_exception_handler, │ │ │ │ C:\vlad\automatic\venv\lib\site-packages\fastapi\routing.py:22 in │ │ │ │ 19 │ Union, │ │ 20 ) │ │ 21 │ │ > 22 from fastapi import params │ │ 23 from fastapi._compat import ( │ │ 24 │ ModelField, │ │ 25 │ Undefined, │ │ │ │ C:\vlad\automatic\venv\lib\site-packages\fastapi\params.py:6 in │ │ │ │ 3 from typing import Any, Callable, Dict, List, Optional, Sequence, Union │ │ 4 │ │ 5 from pydantic.fields import FieldInfo │ │ > 6 from typing_extensions import Annotated, deprecated │ │ 7 │ │ 8 from ._compat import PYDANTIC_V2, Undefined │ │ 9 │ └──────────────────────────────────────────────────────────────────────────────────────────────────┘ ImportError: cannot import name 'deprecated' from 'typing_extensions' (C:\vlad\automatic\venv\lib\site-packages\typing_extensions.py) Press any key to continue . . .
> 
> ### Version Platform Description
> updated: 2023-07-06 hash: [3bcca6f](https://github.com/vladmandic/automatic/commit/3bcca6f92b4d457eff8616e157ba13421f59527f) url: https://github.com/vladmandic/automatic/tree/master 15:47:51-776756 INFO Starting SD.Next 15:47:51-776756 INFO Python 3.10.6 on Windows 15:47:51-806758 INFO Version: [3bcca6f](https://github.com/vladmandic/automatic/commit/3bcca6f92b4d457eff8616e157ba13421f59527f) Thu Jul 6 02:51:27 2023 +0300 15:47:52-127330 INFO Latest published version: [205b516](https://github.com/vladmandic/automatic/commit/205b5164872aadc61b49ee409352c0a5c736aa84) 2023-07-07T19:41:26Z 15:47:52-127330 INFO nVidia CUDA toolkit detected 15:47:53-336874 INFO Torch 2.0.1+cu118 15:47:53-356910 INFO Torch backend: nVidia CUDA 11.8 cuDNN 8700 15:47:53-356910 INFO Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82 15:47:53-466910 INFO Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR'] 15:47:53-466910 INFO Enabled extensions: [] 15:47:53-466910 INFO No changes detected: Quick launch active 15:47:53-476909 INFO Extension preload: 0.0s C:\vlad\automatic\extensions-builtin 15:47:53-476909 INFO Extension preload: 0.0s C:\vlad\automatic\extensions 15:47:53-486911 INFO Server arguments: []
> 
> ### Acknowledgements
> * [x]  I have read the above and searched for existing issues

try : 

pip install --upgrade typing_extensions
