### ISSUE TITLE
[Issue]: 'StableDiffusionXLPipeline' object has no attribute 'load_lora_weights'

### ISSUE THREAD

**Issue by Tophness** [vladmandic/automatic#1608]
### Issue Description

Lora doesn't seem to work with Stable Diffusion XL.
Getting error `'StableDiffusionXLPipeline' object has no attribute 'load_lora_weights'`

### Version Platform Description

Starting SD.Next
Python 3.10.6 on Windows
Version: 816876c8 Fri Jul 7 21:59:50 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 4080 VRAM 16376 Arch (8, 9) Cores 76
Disabled extensions-builtin: ['sd-webui-controlnet', 'sd-dynamic-thresholding', 'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris']
 Enabled extensions-builtin: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
Disabled extensions: ['sd-webui-controlnet', 'sd-dynamic-thresholding', 'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris']
Enabled extensions: []

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
Instructions clearly state not to open issues for this but to reach out on Discord while its in experimental phase.

**Comment by Torcelllo** [comment]
My response at Discord was "as SDXL is not yet fully implemented, don't expect any software to support it yet!"
![ObjNoAttrib SDXL](https://github.com/vladmandic/automatic/assets/114806454/306dd09a-9fe7-4b4a-90d7-ed4256936508)

**Comment by Torcelllo** [comment]
Was wondering about "Options object has no attribute 'schedulers_prediction_type'?

**Comment by vladmandic** [comment]
i just fixed that, will push update in the next 1h, issue is switching backend without ever first initializing it. 
if you start webui --backend diffusers once then it initializes config values and after that switching from ui works.

**Comment by Torcelllo** [comment]
Thanks!
