### ISSUE TITLE
[Issue]: Image viewer after generation doesn't stay in full screen mode

### ISSUE THREAD

**Issue by afbagwell** [vladmandic/automatic#1614]
### Issue Description

If you click on a generated image, it will only be in full screen mode as long as the mouse button is pressed. The moment you let off the button it pops back to preview mode. This happens on 'From Text' and 'From Image' tab.

You can linger in full screen mode if you move the mouse pointer first before letting it go, but any click in the window (even on the image forward/backward buttons) will return to preview mode.

### Version Platform Description

Firefox 115.0.1 (64-bit)
Python 3.10.11 on Windows 11
Version: db30f5fa Sat Jul 8 14:22:51 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8902
Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
Disabled extensions-builtin: ['Lora']
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
Disabled extensions: ['Lora']
Enabled extensions: ['adetailer', 'canvas-zoom', 'openpose-editor', 'sd-dynamic-prompts',
                         'sd-extension-aesthetic-scorer', 'sd-webui-3d-open-pose-editor',
                         'sd-webui-aspect-ratio-helper', 'sd-webui-depth-lib', 'sd-webui-roop',
                         'sd-webui-segment-anything', 'seed_travel', 'Styles-Editor',
                         'ultimate-upscale-for-automatic1111']

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
So, question is if this is desired or not - you should ask in discussions first as this is not an issue as such.

**Comment by afbagwell** [comment]
Doesn't it make the full screen image part of browsing images useless then? I mean if you were going to take it out, then don't have it flash on and off when you click the image.

**Comment by vladmandic** [comment]
How is it useless? Click to open, click to close.

**Comment by afbagwell** [comment]
You're not clicking to open, clicking to close. You're click-holding to open then release to close. Unless you wiggle to mouse. But then the foward/backward buttons in the view are useless because if you click them you close the view.

**Comment by vladmandic** [comment]
If I click, it opens and stays open until I click again and then it closes.

**Comment by afbagwell** [comment]
Hmmm... OK. That's not how it behaves for me. Are you using Firefox 115 on Windows?

Basically -- for me -- it's no longer possible to remain in full-view mode and back and forth through generated images. You have to click-hold in-and-out of each one individually.

**Comment by afbagwell** [comment]
https://github.com/vladmandic/automatic/assets/1495201/c69a2420-d490-4217-a919-e07d95b5bdba

In this video during the first few seconds I'm clicking fast a few times.
The next couple I'm click-pressing and holding for a few seconds, then releasing.
Finally I click-hold, move the mouse while holding, release the mouse button, go to the forward arrow button on the right, click it, then get popped back to the main window view.

**Comment by afbagwell** [comment]
I just confirmed it does behave as you described in Chrome 114.0.5735.199 (64-bit), at least clicking to open, clicking to close.

It still pops back to the main view if you click on either of the arrow buttons at the left and right hand sides of the full-view screen.

**Comment by fbellgr** [comment]
I experience the same issue with Firefox on two installs.

Kind of a workaround: if you click and drag slightly, it will remain open after releasing the button. You have to do the same thing when clicking on the chevrons to switch between images, and sometimes that sends the image gliding off the screen at high speed...

I`m using Firefox 115 on Linux Mint.

**Comment by Silanda** [comment]
> I experience the same issue with Firefox on two installs.
> 
> Kind of a workaround: if you click and drag slightly, it will remain open after releasing the button. You have to do the same thing when clicking on the chevrons to switch between images, and sometimes that sends the image gliding off the screen at high speed...

I'm finding this too. Also Firefox.

**Comment by vladmandic** [comment]
So it's a Firefox specific issue with click detection - that narrows it down and definitely makes it possible to solve. ETA Monday.

**Comment by Aptronymist** [comment]
Until then, there's a partial workaround, you can click on the image and then slightly move your mouse, then release the click. it stays open.

**Comment by vladmandic** [comment]
fixed.
