### ISSUE TITLE
[Issue]: Permission denied

### ISSUE THREAD

**Issue by carlosandreslopez-com** [vladmandic/automatic#1619]
### Issue Description

I'm trying to download the model but I get this error:

23:46:28-675229 ERROR    Diffuser model downloaded error: model=stabilityai/stable-diffusion-xl-base-0.9 [Errno 13]
                         Permission denied: 'D:\\AI
                         Tools\\vladmandic\\automatic\\models\\Diffusers\\models--stabilityai--stable-diffusion-xl-base
                         -0.9\\refs\\main'

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by TeutonJon78** [comment]
They have specifically said to not open issues related to  SDXL or diffusers.

But you have to apply for permission to access the model on huggingface and then the download will work. I think you need a token as well, but I haven't seen how to get that.

**Comment by CmoneBK** [comment]
Go to https://huggingface.co/stabilityai/stable-diffusion-xl-base-0.9/tree/main and fill out form.
On the Huggingface Website go to your Profile -> Settings -> Access Tokens. Generate an Access Token and copy that.
Go to UI -> Models -> Huggingface and enter the Access Token in Huggingface token
Enter stabilityai/stable-diffusion-xl-base-0.9 in Select Model and press Download
Enter stabilityai/stable-diffusion-xl-refiner-0.9 in Select Model and press Download
