### ISSUE TITLE
[Issue]: Buttons don't work when viewing an image on tablet

### ISSUE THREAD

**Issue by horribleCodes** [vladmandic/automatic#1620]
### Issue Description

With the pan and zoom update it's now impossible to perform any action after opening the image viewer. Any tap will be registered as an attempt to pan, so once I view an image, there is no way to navigate or close the viewer.

### Version Platform Description

OS: Android
Browser: Opera
Commit: db30f5faec3bec92cd83714850226cc54ad4d31a

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by horribleCodes** [comment]
https://github.com/vladmandic/automatic/blob/6b63893348fc302fdf6fc7945c6ad240f7a57f9b/javascript/imageViewer.js#L190-L194
I think this is the part that causes the issue.Assuming the problem is that it's basically impossible to tap without moving the cursor a little, I propose the following fix:
Instead of immediately setting `drag` to true on `mousemove`, `mousedown` should set a timer flag that triggers `dragready` after 0.2 seconds or so. `mousemove` can only activate the `drag` flag once `dragready` equals `true`.
If you're concerned about responsiveness, the timer could be skipped if the position of the cursor has changed enough since the start of the `mousedown` event.

**Comment by vladmandic** [comment]
i agree with overall analysis, but its getting really complicated as i cannot reproduce that on my touch screen notebook.
i've added explict buttons on top that should work regardless of touch controls.
any further, i'd love to see a pr.

**Comment by horribleCodes** [comment]
The new update (738a8324fb284a8bb51442ea6d0a849c3ffda7fd) did help with the unresponsive buttons, but the gesture to move to the next image triggers far too easily, as well as at sections where it is not wanted. For instance, with an image in the browser selected, but not fullscreened.
