### ISSUE TITLE
SDXL error

### ISSUE THREAD

**Issue by AbramovS1** [vladmandic/automatic#1622]
### Issue Description

Downloading shards:   0%|                                                                        | 0/2 [14:24<?, ?it/s]
11:26:03-105938 ERROR    Diffusers failed loading model using pipeline:
                         H:\1Aivlad\automatic\models\Stable-diffusion\sd_xl_refiner_0.9.safetensors Stable Diffusion XL
                         Consistency check failed: file should be of size 9990161549 but has size 1142959478
                         ((…)l-00001-of-00002.bin).
                         We are sorry for the inconvenience. Please retry download and pass `force_download=True,
                         resume_download=False` as argument.
                         If the issue persists, please let us know by opening an issue on
                         https://github.com/huggingface/huggingface_hub.
Downloading (…)l-00001-of-00002.bin:  11%|████▎                                 | 1.14G/9.99G [14:24<1:51:32, 1.32MB/s]
11:26:04-431528 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
11:26:04-439074 INFO     Loading diffuser model:
                         H:\1Aivlad\automatic\models\Stable-diffusion\sd_xl_refiner_0.9.safetensors
Downloading shards:   0%|                                                                        | 0/2 [00:00<?, ?it/s]11:28:24-753946 INFO     Settings changed: 9 ['cross_attention_optimization', 'cross_attention_options',               ]
                         'schedulers_prediction_type', 'schedulers_beta_schedule', 'schedulers_solver_order',
                         'schedulers_use_karras', 'schedulers_use_loworder', 'schedulers_use_thresholding',
                         'schedulers_dpm_solver']
                                                                                                                       11:28:26-407870 INFO     Server shutdown requested                                                                     ]
11:28:26-638271 WARNING  WebSocket closed (ignore asyncio.exceptions.CancelledError)
Traceback (most recent call last):
  File "H:\1Aivlad\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
11:28:26-777168 WARNING  WebSocket closed (ignore asyncio.exceptions.CancelledError)
Traceback (most recent call last):
  File "H:\1Aivlad\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
                                                                                                                       11:28:28-884360 INFO     Server will restart                                                                           ]
                                                                                                                       11:28:29-097390 INFO     Server restarting...                                                                          ]
                                                                                                                       11:28:35-062988 INFO     Server arguments: ['--backend', 'diffusers']                                                  ]
11:28:35-108204 INFO     Libraries loaded
11:28:35-113192 INFO     Using data path: H:\1Aivlad\automatic
11:28:35-129149 INFO     Available VAEs: H:\1Aivlad\automatic\models\VAE 0
11:28:35-196097 INFO     Available models: H:\1Aivlad\automatic\models\Stable-diffusion 3
                                                                                                                       Image Browser: ImageReward is not installed, cannot be used.                        | 115M/9.99G [00:13<19:34, 8.41MB/s]
                                                                                                                       11:28:38-709909 INFO     Loading UI theme: name=abidlabs/Lime style=Auto                                               ]
                                                                                                                       Running on local URL:  http://127.0.0.1:7860                                        | 178M/9.99G [00:18<15:17, 10.7MB/s]
11:28:41-672184 INFO     Local URL: http://127.0.0.1:7860/
11:28:41-676172 INFO     Initializing middleware
11:28:41-812147 INFO     [AgentScheduler] Task queue is empty
11:28:41-815139 INFO     [AgentScheduler] Registering APIs
Downloading (…)l-00001-of-00002.bin: 100%|████████████████████████████████████████| 9.99G/9.99G [14:47<00:00, 11.3MB/s]
Downloading (…)l-00002-of-00002.bin: 100%|██████████████████████████████████████████| 169M/169M [00:14<00:00, 11.6MB/s]
Downloading shards: 100%|███████████████████████████████████████████████████████████████| 2/2 [15:02<00:00, 451.30s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [01:06<00:00, 33.34s/it]
11:45:39-005928 INFO     Embeddings: loaded=0 skipped=0
11:45:39-050834 INFO     Model loaded in 1174.7s (diffusers=0.1s load=1174.7s)
11:45:39-391976 INFO     Model load finished: {'ram': {'used': 0.49, 'total': 15.9}, 'gpu': {'used': 7.25, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
11:45:39-400952 INFO     Embeddings: loaded=0 skipped=0
11:45:39-413923 INFO     Pipeline class changed from StableDiffusionXLImg2ImgPipeline to StableDiffusionXLPipeline
11:45:39-775455 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
11:45:39-781601 INFO     Loading diffuser model:
                         H:\1Aivlad\automatic\models\Stable-diffusion\sd_xl_refiner_0.9.safetensors
11:46:02-780188 ERROR    Exception: Model expects an added time embedding vector of length 2560, but a vector of 2816
                         was created. The model has an incorrect config. Please check `unet.config.time_embedding_type`
                         and `text_encoder_2.config.projection_dim`.
11:46:02-785176 ERROR    Arguments: args=('task(rh67d6uup1iddmn)', 'Forest', '', [], 20, 0, False, False, 1, 1, 6, 1,
                         -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False,
                         'positive', 'comma', 0, False, False, '', 0, '', [], 0, '', [], 0, '', [], True, False, False,
                         False, 0, False) kwargs={}
11:46:02-813100 ERROR    gradio call: ValueError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\1Aivlad\automatic\modules\call_queue.py:34 in f                                                                  │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ H:\1Aivlad\automatic\modules\txt2img.py:56 in txt2img                                                               │
│                                                                                                                     │
│   55 │   if processed is None:                                                                                      │
│ > 56 │   │   processed = processing.process_images(p)                                                               │
│   57 │   p.close()                                                                                                  │
│                                                                                                                     │
│                                               ... 3 frames hidden ...                                               │
│                                                                                                                     │
│ H:\1Aivlad\automatic\venv\lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py │
│ :734 in __call__                                                                                                    │
│                                                                                                                     │
│   733 │   │   add_text_embeds = pooled_prompt_embeds                                                                │
│ > 734 │   │   add_time_ids = self._get_add_time_ids(                                                                │
│   735 │   │   │   original_size, crops_coords_top_left, target_size, dtype=prompt_embeds.dtype                      │
│                                                                                                                     │
│ H:\1Aivlad\automatic\venv\lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py │
│ :532 in _get_add_time_ids                                                                                           │
│                                                                                                                     │
│   531 │   │   if expected_add_embed_dim != passed_add_embed_dim:                                                    │
│ > 532 │   │   │   raise ValueError(                                                                                 │
│   533 │   │   │   │   f"Model expects an added time embedding vector of length {expected_add_e                      │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError: Model expects an added time embedding vector of length 2560, but a vector of 2816 was created. The model
has an incorrect config. Please check `unet.config.time_embedding_type` and `text_encoder_2.config.projection_dim`.
Traceback (most recent call last):
  File "H:\1Aivlad\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "H:\1Aivlad\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "H:\1Aivlad\automatic\modules\call_queue.py", line 16, in f
    res = func(*args, **kwargs)
  File "H:\1Aivlad\automatic\modules\ui.py", line 206, in update_token_counter
    has_bos_token = tokenizer.bos_token_id is not None
AttributeError: 'NoneType' object has no attribute 'bos_token_id'
11:46:03-396256 ERROR    Exception: Model expects an added time embedding vector of length 2560, but a vector of 2816
                         was created. The model has an incorrect config. Please check `unet.config.time_embedding_type`
                         and `text_encoder_2.config.projection_dim`.
11:46:03-400245 ERROR    Arguments: args=('task(7czd2467d7y5hcq)', 'Forest', '', [], 20, 0, False, False, 1, 1, 6, 1,
                         -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False,
                         'positive', 'comma', 0, False, False, '', 0, '', [], 0, '', [], 0, '', [], True, False, False,
                         False, 0, False) kwargs={}
11:46:03-408224 ERROR    gradio call: ValueError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\1Aivlad\automatic\modules\call_queue.py:34 in f                                                                  │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ H:\1Aivlad\automatic\modules\txt2img.py:56 in txt2img                                                               │
│                                                                                                                     │
│   55 │   if processed is None:                                                                                      │
│ > 56 │   │   processed = processing.process_images(p)                                                               │
│   57 │   p.close()                                                                                                  │
│                                                                                                                     │
│                                               ... 3 frames hidden ...                                               │
│                                                                                                                     │
│ H:\1Aivlad\automatic\venv\lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py │
│ :734 in __call__                                                                                                    │
│                                                                                                                     │
│   733 │   │   add_text_embeds = pooled_prompt_embeds                                                                │
│ > 734 │   │   add_time_ids = self._get_add_time_ids(                                                                │
│   735 │   │   │   original_size, crops_coords_top_left, target_size, dtype=prompt_embeds.dtype                      │
│                                                                                                                     │
│ H:\1Aivlad\automatic\venv\lib\site-packages\diffusers\pipelines\stable_diffusion_xl\pipeline_stable_diffusion_xl.py │
│ :532 in _get_add_time_ids                                                                                           │
│                                                                                                                     │
│   531 │   │   if expected_add_embed_dim != passed_add_embed_dim:                                                    │
│ > 532 │   │   │   raise ValueError(                                                                                 │
│   533 │   │   │   │   f"Model expects an added time embedding vector of length {expected_add_e                      │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError: Model expects an added time embedding vector of length 2560, but a vector of 2816 was created. The model
has an incorrect config. Please check `unet.config.time_embedding_type` and `text_encoder_2.config.projection_dim`.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████| 2/2 [01:01<00:00, 30.68s/it]
11:50:27-594392 ERROR    Failed to load diffusers model
11:50:27-636197 ERROR    loading Diffusers model: OutOfMemoryError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\1Aivlad\automatic\modules\sd_models.py:739 in load_diffuser                                                      │
│                                                                                                                     │
│    738 │   │   sd_model.sd_model_hash = checkpoint_info.hash # pylint: disable=attribute-define                     │
│ >  739 │   │   sd_model.to(devices.device)                                                                          │
│    740 │   except Exception as e:                                                                                   │
│                                                                                                                     │
│ H:\1Aivlad\automatic\venv\lib\site-packages\diffusers\pipelines\pipeline_utils.py:681 in to                         │
│                                                                                                                     │
│    680 │   │   │   else:                                                                                            │
│ >  681 │   │   │   │   module.to(torch_device, torch_dtype)                                                         │
│    682                                                                                                              │
│                                                                                                                     │
│                                               ... 8 frames hidden ...                                               │
│                                                                                                                     │
│ H:\1Aivlad\automatic\venv\lib\site-packages\torch\nn\modules\module.py:820 in _apply                                │
│                                                                                                                     │
│    819 │   │   │   with torch.no_grad():                                                                            │
│ >  820 │   │   │   │   param_applied = fn(param)                                                                    │
│    821 │   │   │   should_use_set_data = compute_should_use_set_data(param, param_applied)                          │
│                                                                                                                     │
│ H:\1Aivlad\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1143 in convert                              │
│                                                                                                                     │
│   1142 │   │   │   │   │   │   │   non_blocking, memory_format=convert_to_format)                                   │
│ > 1143 │   │   │   return t.to(device, dtype if t.is_floating_point() or t.is_complex() else No                     │
│   1144                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 12.00 GiB total capacity; 10.44 GiB already
allocated; 0 bytes free; 10.49 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
11:50:28-429079 INFO     Embeddings: loaded=0 skipped=0
11:50:28-433327 INFO     Model loaded in 289.0s (load=289.0s)
11:50:28-459872 WARNING  GPU high memory utilization: 100% {'ram': {'used': 1.55, 'total': 15.9}, 'gpu': {'used': 12.0,
                         'total': 12.0}, 'retries': 1, 'oom': 1}
11:50:28-840131 INFO     Model load finished: {'ram': {'used': 1.55, 'total': 15.9}, 'gpu': {'used': 7.97, 'total':
                         12.0}, 'retries': 1, 'oom': 1}
11:50:29-632403 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
11:50:29-905674 INFO     Startup time: 1314.8s (models=0.1s scripts=1.6s onchange=1.9s ui-txt2img=0.1s ui-img2img=0.1s
                         ui-train=0.1s ui-settings=0.1s ui-extensions=2.1s ui-defaults=0.1s launch=0.2s
                         app-started=0.3s checkpoint=1308.0s)
11:50:44-810100 INFO     Pipeline class changed from StableDiffusionXLImg2ImgPipeline to StableDiffusionXLPipeline
11:50:47-724868 ERROR    Exception: Expected all tensors to be on the same device, but found at least two devices,
                         cuda:0 and cpu! (when checking argument for argument weight in method
                         wrapper_CUDA__native_layer_norm)
11:50:47-728748 ERROR    Arguments: args=('task(hrtvr7xpk6k38fj)', 'Forest', '', [], 20, 1, False, False, 1, 1, 6, 1,
                         -1.0, -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False,
                         'positive', 'comma', 0, False, False, '', 0, '', [], 0, '', [], 0, '', [], True, False, False,
                         False, 0, False) kwargs={}
11:50:47-737804 ERROR    gradio call: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\1Aivlad\automatic\modules\call_queue.py:34 in f                                                                  │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ H:\1Aivlad\automatic\modules\txt2img.py:56 in txt2img                                                               │
│                                                                                                                     │
│   55 │   if processed is None:                                                                                      │
│ > 56 │   │   processed = processing.process_images(p)                                                               │
│   57 │   p.close()                                                                                                  │
│                                                                                                                     │
│                                              ... 14 frames hidden ...                                               │
│                                                                                                                     │
│ H:\1Aivlad\automatic\venv\lib\site-packages\torch\nn\modules\normalization.py:190 in forward                        │
│                                                                                                                     │
│   189 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ > 190 │   │   return F.layer_norm(                                                                                  │
│   191 │   │   │   input, self.normalized_shape, self.weight, self.bias, self.eps)                                   │
│                                                                                                                     │
│ H:\1Aivlad\automatic\venv\lib\site-packages\torch\nn\functional.py:2515 in layer_norm                               │
│                                                                                                                     │
│   2514 │   │   )                                                                                                    │
│ > 2515 │   return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.c                     │
│   2516                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when
checking argument for argument weight in method wrapper_CUDA__native_layer_norm)
11:52:56-110996 INFO     Settings changed: 3 ['cross_attention_optimization', 'no_half', 'no_half_vae']
11:52:57-091728 INFO     Server shutdown requested
11:52:57-233408 WARNING  WebSocket closed (ignore asyncio.exceptions.CancelledError)
Traceback (most recent call last):
  File "H:\1Aivlad\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\1Aivlad\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
11:52:59-288221 INFO     Server will restart
11:52:59-860713 INFO     Server restarting...
11:53:03-262283 INFO     Server arguments: ['--backend', 'diffusers']
11:53:03-286769 INFO     Libraries loaded
11:53:03-288767 INFO     Using data path: H:\1Aivlad\automatic
11:53:03-308584 INFO     Available VAEs: H:\1Aivlad\automatic\models\VAE 0
11:53:03-510817 INFO     Available models: H:\1Aivlad\automatic\models\Stable-diffusion 3
Image Browser: ImageReward is not installed, cannot be used.
11:53:06-409060 INFO     Loading UI theme: name=abidlabs/Lime style=Auto
Running on local URL:  http://127.0.0.1:7860
11:53:08-735899 INFO     Local URL: http://127.0.0.1:7860/
11:53:08-737893 INFO     Initializing middleware
11:53:08-805824 INFO     [AgentScheduler] Task queue is empty
11:53:08-806822 INFO     [AgentScheduler] Registering APIs
11:53:08-919847 INFO     Startup time: 5.6s (models=0.2s scripts=1.4s onchange=1.4s ui-txt2img=0.1s ui-img2img=0.1s
                         ui-train=0.1s ui-settings=0.2s ui-extensions=1.6s ui-defaults=0.1s launch=0.2s
                         app-started=0.2s)
11:53:32-090665 ERROR    Exception: Expected all tensors to be on the same device, but found at least two devices,
                         cuda:0 and cpu! (when checking argument for argument weight in method
                         wrapper_CUDA__native_layer_norm)
11:53:32-093657 ERROR    Arguments: args=('task(7s90plhyndsvfp9)', '', '', [], 20, 0, False, False, 1, 1, 6, 1, -1.0,
                         -1.0, 0, 0, 0, False, 512, 512, False, 0.7, 2, 'Latent', 0, 0, 0, [], 0, False, False,
                         'positive', 'comma', 0, False, False, '', 0, '', [], 0, '', [], 0, '', [], True, False, False,
                         False, 0, False) kwargs={}
11:53:32-103145 ERROR    gradio call: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ H:\1Aivlad\automatic\modules\call_queue.py:34 in f                                                                  │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ H:\1Aivlad\automatic\modules\txt2img.py:56 in txt2img                                                               │
│                                                                                                                     │
│   55 │   if processed is None:                                                                                      │
│ > 56 │   │   processed = processing.process_images(p)                                                               │
│   57 │   p.close()                                                                                                  │
│                                                                                                                     │
│                                              ... 14 frames hidden ...                                               │
│                                                                                                                     │
│ H:\1Aivlad\automatic\venv\lib\site-packages\torch\nn\modules\normalization.py:190 in forward                        │
│                                                                                                                     │
│   189 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ > 190 │   │   return F.layer_norm(                                                                                  │
│   191 │   │   │   input, self.normalized_shape, self.weight, self.bias, self.eps)                                   │
│                                                                                                                     │
│ H:\1Aivlad\automatic\venv\lib\site-packages\torch\nn\functional.py:2515 in layer_norm                               │
│                                                                                                                     │
│   2514 │   │   )                                                                                                    │
│ > 2515 │   return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.c                     │
│   2516                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when
checking argument for argument weight in method wrapper_CUDA__native_layer_norm)

### Version Platform Description

Win11 
16RAM
3060 12VRAM

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
Instructions explictly state do not open issues for diffusers and/or sd-xl and instead reach out on discord. Closing.

**Comment by Natotela** [comment]
> Instructions explictly state do not open issues for diffusers and/or sd-xl and instead reach out on discord. Closing.

the instructions also explicitly state:
"You can remove your --backend commands."
But only when [some of us] use the arg on execution, it works, rather than getting a  `'Options' object has no attribute 'schedulers_prediction_type'`

btw thanks for all this :-}
