### ISSUE TITLE
interrogator [Issue]: The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 0

### ISSUE THREAD

**Issue by flashbackpoductions** [vladmandic/automatic#1630]
### Issue Description

Until a day ago -interrogator worked, and after I updated the library, it now throws me this error.
I tried downloading the extension, also from the physical library on the computer and reinstalling it, but it's still the same error on every model I try .
The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 0.
there is no error b4 that line

### Version Platform Description

win10, updated[vladmandic](https://github.com/vladmandic)

Using VENV: D:\automatic\venv
23:53:49-867605 INFO     Starting SD.Next
23:53:49-871609 INFO     Python 3.10.6 on Windows
23:53:49-912646 INFO     Version: 85a197ca Sun Jul 9 16:11:08 2023 -0400
23:53:50-366820 INFO     nVidia CUDA toolkit detected
23:53:51-477202 INFO     Torch 2.0.1+cu118
23:53:51-501444 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
23:53:51-503445 INFO     Torch detected GPU: NVIDIA GeForce RTX 3070 Ti VRAM 8192 Arch (8, 6) Cores 48
23:53:51-589653 WARNING  Modified files: ['modules/lycoris', 'cmd_opts.data_dir/']
23:53:51-627929 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
23:53:51-634935 INFO     Enabled extensions: ['clip-interrogator-ext', 'sd-webui-roop-uncensored',
                         'sd-webui-text2video']
23:53:51-637938 INFO     Verifying requirements
23:53:51-648948 INFO     Verifying packages
23:53:51-650812 INFO     Verifying repositories
23:53:55-066045 INFO     Verifying submodules
23:54:08-433189 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR',
                         'sd-webui-roop-uncensored', 'sd-webui-text2video']
23:54:08-436530 WARNING  Extensions duplicates: ['clip-interrogator-ext']
23:54:08-438533 INFO     Verifying packages
23:54:08-442537 INFO     Extension preload: 0.0s D:\automatic\extensions-builtin
23:54:08-444539 INFO     Extension preload: 0.0s D:\automatic\extensions
23:54:08-457550 INFO     Server arguments: []
23:54:12-322735 INFO     Pipeline: Backend.ORIGINAL
No module 'xformers'. Proceeding without it.
23:54:13-266807 INFO     Libraries loaded
23:54:13-268809 INFO     Using data path: D:\automatic
23:54:13-272813 INFO     Available VAEs: D:\automatic\models\VAE 0
23:54:13-274815 INFO     Skipping conflicting extension: D:\automatic\extensions\clip-interrogator-ext
23:54:13-284824 INFO     Available models: D:\automatic\models\Stable-diffusion 23
23:54:15-286655 INFO     ControlNet v1.1.232
ControlNet v1.1.232
ControlNet preprocessor location: D:\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
23:54:15-382743 INFO     ControlNet v1.1.232
ControlNet v1.1.232
Image Browser: ImageReward is not installed, cannot be used.
2023-07-09 23:54:16,372 - roop - INFO - roop v0.0.2-uncensored
2023-07-09 23:54:16,373 - roop - INFO - roop v0.0.2-uncensored
23:54:16-473742 INFO     Libraries loaded
Libraries loaded
23:54:16-676928 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://127.0.0.1:7860
23:54:18-697040 INFO     Local URL: http://127.0.0.1:7860/
23:54:18-698041 INFO     Initializing middleware
23:54:18-789124 INFO     [AgentScheduler] Task queue is empty
23:54:18-791126 INFO     [AgentScheduler] Registering APIs
Loading weights: D:\automatic\models\Stable-diffusion\noam-shiri.ckpt - ---------------------------- 0.1/2.1 GB 0:00:00
23:54:20-163505 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
23:54:22-164175 INFO     Applying scaled dot product cross attention optimization
23:54:22-187195 INFO     Embeddings: loaded=1 skipped=0
23:54:22-194202 INFO     Model loaded in 2.8s (load=0.8s create=0.3s apply=0.4s vae=0.5s move=0.7s)
23:54:22-454440 INFO     Model load finished: {'ram': {'used': 3.12, 'total': 63.91}, 'gpu': {'used': 3.12, 'total':
                         8.0}, 'retries': 0, 'oom': 0} cached=0
23:54:22-778736 INFO     Startup time: 14.3s (torch=2.7s gradio=0.7s libraries=1.4s scripts=3.2s onchange=0.2s
                         ui-txt2img=0.1s ui-img2img=0.1s ui-settings=0.1s ui-extensions=1.6s launch=0.2s
                         app-started=0.2s checkpoint=3.9s)

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
known issue as switch to diffusers require new transformers package as well and old clip-interrrogator is not compatible with those.
sdnext now includes different/newer version of clip-interrogator for new installs, but it doesn't uninstall existing one to prevent any issues on users system.

you can try changing existing clip-interrogator directly using command
> git submodule set-url extensions-builtin/clip-interrogator-ext https://github.com/Dahvikiin/clip-interrogator-ext.git

and then run `webui.bat/webui.sh --upgrade`

@Aptronymist add this to list of known issues?

**Comment by flashbackpoductions** [comment]
thank you very much. solved ! :-)

**Comment by Aptronymist** [comment]
@vladmandic You got it. Will add both at the same time.
