### ISSUE TITLE
[Issue]: Downloading SD-XL Model

### ISSUE THREAD

**Issue by Anashel-RPG** [vladmandic/automatic#1633]
### Issue Description

I have accepted the LUA from Huggin Face and supplied a valid token. Logs from the command prompt;
Your token has been saved to C:\Users\Administrator\.cache\huggingface\token
Login successful
14:56:18-652133 ERROR    Diffuser model downloaded error: model=stabilityai/stable-diffusion-xl-base-0.9 module 'diffusers' has no attribute 'StableDiffusionXLPipeline'

### Version Platform Description

Model being download: stabilityai/stable-diffusion-xl-base-0.9
---
14:48:58-412436 INFO     Starting SD.Next
14:48:58-428059 INFO     Python 3.10.6 on Windows
14:48:58-474964 INFO     Version: 768daecd Mon Jul 10 08:36:46 2023 -0400
14:48:58-727817 INFO     nVidia CUDA toolkit detected
14:49:05-147362 INFO     Torch 2.0.0+cu118
14:49:05-319244 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
14:49:05-334853 INFO     Torch detected GPU: NVIDIA A10G VRAM 22842 Arch (8, 6) Cores 80
14:49:05-537993 WARNING  Modified files: ['modules/lycoris']
14:49:05-569245 INFO     Disabled extensions-builtin: ['seed_travel', 'model-keyword']
14:49:05-569245 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
14:49:05-600475 INFO     Disabled extensions: ['seed_travel', 'model-keyword']
14:49:05-600475 INFO     Enabled extensions: ['sd-webui-supermerger', 'sd_dreambooth_extension', 'StylePile']
---
updated: 2023-07-10
hash: 768daecd
2.0.0+cu118 Autocast  half
device: NVIDIA A10G (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8700
xformers: 0.0.20
accelerate: 0.19.0
transformers: 4.29.2
Stable Diffusion: [cf1d67a] 2023-03-25
Taming Transformers: [9e9981c] 2022-11-07
CodeFormer: [7a584fd] 2023-01-18
BLIP: [3a29b74] 2022-09-20
k_diffusion: [c9fe758] 2023-05-21

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
a) answered in #1627
b) wiki explicitly states to NOT open issues for SD-XL yet as its experimental. there are documented channels how to reach out.

**Comment by Anashel-RPG** [comment]
My bad, i'll take the time to review your answer! Thanks!
