### ISSUE TITLE
[Issue]: Keyboard bindings in the image viewer don't work properly

### ISSUE THREAD

**Issue by Razunter** [vladmandic/automatic#1647]
### Issue Description

Since the image viewer rework, all keyboard bindings are broken:
1) Key events are usually ignored right after opening the viewer. Sometimes they work, but rarely. Switching tabs breaks them again.
2) But they work after dragging the image (why is it draggable?!)
3) And esc doesn't close the viewer at all.

### Version Platform Description

```
02:20:56-998475 INFO     Python 3.10.11 on Windows
02:20:57-114327 INFO     Version: ec99bad0 Tue Jul 11 15:55:02 2023 -0400
```

`--safe` doesn't help

Windows 11, Firefox. Same in Chrome.

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
I'll take a look at keybindings?
Why is it draggable? Because if I zoom 400%, I want to pan around it.

**Comment by vladmandic** [comment]
just pushed a major update with pretty large javascript refactoring, i hope this issue is resolved.
if not, post here and i'll reopen.
