### ISSUE TITLE
[Issue]: "error: argument --api: expected one argument"

### ISSUE THREAD

**Issue by DrCyanide** [vladmandic/automatic#1651]
### Issue Description

At first I thought this was a problem with me accidentally adding some new arg, but I just cloned the project again into a new directory and got the same error message - without any modifications to webui.bat

```
Using VENV: D:\Documents\AI\ImgGen\stable-diffusion-webui\venv
usage:  [-h] [--config CONFIG] [--ui-config UI_CONFIG] [--medvram] [--lowvram] [--ckpt CKPT] [--vae VAE] [--data-dir DATA_DIR] [--models-dir MODELS_DIR] [--allow-code] [--share] [--insecure]
        [--use-cpu USE_CPU [USE_CPU ...]] [--listen] [--port PORT] [--freeze] [--auth AUTH] [--auth-file AUTH_FILE] [--autolaunch] [--docs] [--api-only] [--api-log] [--device-id DEVICE_ID]
        [--cors-origins CORS_ORIGINS] [--cors-regex CORS_REGEX] [--tls-keyfile TLS_KEYFILE] [--tls-certfile TLS_CERTFILE] [--tls-selfsign] [--server-name SERVER_NAME] [--no-hashing] [--no-download]
        [--profile] [--disable-queue] [--subpath SUBPATH] [--backend {original,diffusers}] [--debug] [--reset] [--upgrade] [--quick] [--use-ipex] [--use-directml] [--use-cuda] [--use-rocm]
        [--skip-requirements] [--skip-extensions] [--skip-git] [--skip-torch] [--experimental] [--reinstall] [--test] [--version] [--ignore] [--safe]
: error: argument --api: expected one argument
```

Something that strikes me as slightly odd about the error message is the `D:\Documents\AI\ImageGen\stable-diffusion-webui\venv` part. That's not the directory where I was running this project from, that's my A1111 directory (which I had installed first, and for which the `--api` argument is a valid command line arg). I was running it from `D:\Documents\AI\ImgGen\automatic` and `D:\Documents\AI\ImgGen\clean_automatic\automatic` 

### Version Platform Description

Windows 10
Git commit 562ca33275d5836906b6c62ffd8c7f1cd61be24c

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by DevilsCrypto** [comment]
There is not argument --api available, if you want only the api use --api-only. Regarding the path you see, maybe you still have an old virtual environment active?

**Comment by DrCyanide** [comment]
> There is no argument `--api` available, if you want only the api use `--api-only`, default the full api is available already

I'm aware. The args I'm providing are `--listen --lowvram --insecure --skip-requirements --ckpt "path\to\that\model.ckpt"`

> Regarding the path you see, maybe you still have an old virtual environment active?

I'm not very familiar with how virtual environments work to know how this should be managed. I've been switching to A1111 while I've been unable to use this version. A1111 crashes pretty frequently on me, but since it's at least working some of the time I'd rather not do anything to mess up that environment.

**Comment by DevilsCrypto** [comment]
Are you starting automatic with the webui.bat ?

**Comment by DrCyanide** [comment]
Yes. When I re-cloned the repo this morning, I used an unmodified webui.bat as well, so not even my arg changes were present.

**Comment by vladmandic** [comment]
there is no `--api` here, its always-on. please read notes or search before creating issue, this was mentioned more that few times.

**Comment by DrCyanide** [comment]
> there is no `--api` here, its always-on. please read notes or search before creating issue, this was mentioned more that few times.

It was mentioned more than a few times that I did not add `--api` to my webui.bat or command line, yet I still got this error, even on a clean pull of the project. There's something else causing the error message.

**Comment by vladmandic** [comment]
back to your venv path, its clearly loading from wrong one. 
from code:
```batch
if not defined VENV_DIR (set "VENV_DIR=%~dp0%venv")
```
so check if VENV_DIR environment variable is set - it shouldn't be.

**Comment by DrCyanide** [comment]
VENV_DIR isn't defined by my system, but I see where it's going now.

The default webui.bat sets it to `D:\Documents\AI\ImgGen\automatic\venv`, just like it should, and that sticks around until A1111 is called in the same window.

A1111's webui-user.bat sets it to `D:\Documents\AI\ImgGen\stable-diffusion-webui\venv`, which also sticks around until something else changes it or the window is closed.

However, the default webui.bat here uses `if not defined VENV_DIR (set "VENV_DIR=%~dp0%venv")`, which doesn't work now because VENV_DIR was defined by the previous run of A1111.
