### ISSUE TITLE
[Issue]: Info file for embedding searched for w/o removing extension first

### ISSUE THREAD

**Issue by schumar** [vladmandic/automatic#1655]
### Issue Description

Info files are searched for by appending `.info` (and `.civitai.info`) to the model name (`path`), see `ui_extra_networks.py` line 250.

But while that path does *not* contain the extension when doing this for checkpoints, hypernetworkss or loras, for embeddings (aka textual inversions) it *does*.

e.g. the info file for `embeddings/foo.pt` is searched for at `embeddings/foo.pt.info` instead of `embeddings/foo.info` (while the description *is* searched for at `embeddings/foo.description.txt` \*shrugs*)

Not sure if this is intended behaviour; if it is, I'll just rename my info files :)

### Version Platform Description

```
18:16:35-681656 INFO     Starting SD.Next
18:16:35-687371 INFO     Python 3.10.11 on Linux
18:16:35-694299 INFO     Version: de2c239c Wed Jul 12 10:58:32 2023 -0400
18:16:36-080417 INFO     AMD ROCm toolkit detected
18:16:37-307626 INFO     Torch 2.0.1+rocm5.4.2
18:16:37-366491 INFO     Torch backend: AMD ROCm HIP 5.4.22803-474e8620
18:16:37-368420 INFO     Torch detected GPU: AMD Radeon RX 6800 XT VRAM 16368 Arch (10, 3) Cores 36
18:16:37-398588 INFO     Enabled extensions-builtin: ['LDSR', 'Lora', 'ScuNET', 'SwinIR', 'a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'multidiffusion-upscaler-for-automatic1111', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'sd-webui-agent-scheduler']
18:16:37-403746 INFO     Enabled extensions: []
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed.
