### ISSUE TITLE
[Issue]: Generate hotkey no longer working when viewing generated image.

### ISSUE THREAD

**Issue by greythax** [vladmandic/automatic#1658]
### Issue Description

As of 5c8ead7b ctrl-enter hotkey no longer works to generate a new image while viewing image (in image view after clicking on preview image.)  Additionally image in image viewer no longer updates when Generate Forever is active.

### Version Platform Description

15:45:07-371549 INFO     Starting SD.Next
15:45:07-378549 INFO     Python 3.10.11 on Windows
15:45:07-448042 INFO     Version: 5c8ead7b Wed Jul 12 15:35:36 2023 -0400
15:45:07-895511 INFO     nVidia CUDA toolkit detected
15:45:10-349744 INFO     Torch 2.0.0+cu118
15:45:10-394756 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
15:45:10-398756 INFO     Torch detected GPU: NVIDIA GeForce RTX 2080 Ti VRAM 11264 Arch (7, 5) Cores 68
15:45:10-671101 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
15:45:10-691105 INFO     Enabled extensions: ['Config-Presets', 'Disabled', 'model-keyword',
                         'openpose-editor', 'posex', 'sd-dynamic-prompts', 'sd-webui-3d-open-pose-editor',
                         'sd-webui-roop-nsfw', 'sd-webui-txt-img-to-3d-model', 'Stable-Diffusion-Webui-Civitai-Helper']
1

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
first one is by design. i don't want that.

second is ripped out because it was written badly. i hope to be reintroduced in the future. but in either case, it will be treated as feature, not issue.
