### ISSUE TITLE
[Issue]: Image looks different after update

### ISSUE THREAD

**Issue by djdookie** [vladmandic/automatic#1659]
### Issue Description

After updating to the current version of SD.next images from 3 days ago look worse, although using the same parameters and models.

![00179-masterpiece best quality Beautiful Woman Amber Heard appearing](https://github.com/vladmandic/automatic/assets/17240204/57ba13a1-47e6-4d74-8afb-c771923502ad)
![00213-masterpiece best quality Beautiful Woman Amber Heard appearing](https://github.com/vladmandic/automatic/assets/17240204/8da1c77c-01c2-44eb-baae-faa58bc50e17)

The PNG info says only the version differs.

> Steps: 25, Sampler: DEIS, CFG scale: 7, Seed: 2076718369, Size: 1024x1024, Model hash: 02570925, Model: stabilityai/stable-diffusion-xl-base-0.9, Version: 7452cee, Parser: Full parser

> Steps: 25, Sampler: DEIS, CFG scale: 7, Seed: 2076718369, Size: 1024x1024, Model hash: 02570925, Model: stabilityai/stable-diffusion-xl-base-0.9, Version: 6947776, Parser: Full parser

I was using diffusers backend and the diffusers models structure. Also refiner 0.9 for both runs.

I guess it has to do with the refiner updates, since if i use refiner "none" the image is closer to what it used to be.
Even with the new refiner option i was not able to get back the quiality of the image 3 days ago.
Possibly a new bug in the pipeline?

### Version Platform Description

Windows 10

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by djdookie** [comment]
After rolling back to 7452cee the image looks the same as before again.
So it's definitely related to the updates in between.

And btw. the progressbar also looks worse now and doesn't fiil the whole width of the screen now.

**Comment by zethfoxster** [comment]
refiner 0.9 as in sdxl 0.9? Im pretty sure he stated not to open any tickets for sdxl related problems as its not fully finished yet.

**Comment by djdookie** [comment]
> refiner 0.9 as in sdxl 0.9? Im pretty sure he stated not to open any tickets for sdxl related problems as its not fully finished yet.

Yes, I was using base v0.9 and refinder v0.9 from SDXL.
Didn't know about not opening SDXL tickets. But possibly it could help in the development to find and revert regressions.

**Comment by vladmandic** [comment]
image looks different for experimental model??? sorry, but thats just how it is.
and like @zethfoxster, for the same reason it explicitly states no issues for sd-xl, use discord channels until its polished.
re: progressbar, i'm sorry you don't like it, but i prefer shorter progress bar.
