### ISSUE TITLE
[Issue]: Extra Networks - Multiple Textual inversion files on launch

### ISSUE THREAD

**Issue by runew0lf** [vladmandic/automatic#166]
### Issue Description

When you initially load into VD (vlad diffusion) if there are any other files in the TI folder, they display initially, see screenshot
![msedge_A9MwPbtZFG](https://user-images.githubusercontent.com/9966016/232273709-0480ee62-287a-4f89-8a15-8634718281b9.png)

A refresh fixes this
![msedge_tX1LyyVTOH](https://user-images.githubusercontent.com/9966016/232273791-58573a0e-e660-4b61-b530-fce6ade1cb2a.png)

### Version Platform Description

OS: Windows 11
Browser: Microsoft Edge Version 114.0.1788.0 (Official build) dev (64-bit)
Version: 353eb9b0 Sat Apr 15 21:24:06 2023 -0400

**Comment by vladmandic** [comment]
fixed in latest release (will be on github in ~1h)
