### ISSUE TITLE
[Feature]: Allow setting defaults for width and height

### ISSUE THREAD

**Issue by djmaze** [vladmandic/automatic#1663]
### Feature description

Especially with the support of alternative models which need different image width and height (like SDXL), it would be good to be able to configure alternative defaults for width and height.

This could be done globally in the settings or even on a model-by-model basis I guess.

**Comment by vladmandic** [comment]
already exists. settings -> user interface defaults.

**Comment by djmaze** [comment]
That's just an empty page for me:
![User_interface_defaults](https://github.com/vladmandic/automatic/assets/7229/ae298ba6-1aac-4df4-bce4-8eb2805d25d9)

(Using commit 562ca33275d5836906b6c62ffd8c7f1cd61be24c from yesterday + changes from the Docker PR)

**Comment by djmaze** [comment]
Ah, now I understand how this works. Thanks!
