### ISSUE TITLE
[Feature]: Detect comma when applying a Style

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1665]
### Feature description

This is like real tiny and probably should end up at the bottom of the backlog:

When adding a Style, it auto-prefixes a comma, unless the Prompt box is empty. It'd be nice if the Style could detect if the current prompt already ends with a comma and not add one.

### Version Platform Description

n/a

**Comment by vladmandic** [comment]
done.

**Comment by brknsoul** [comment]
Wranglin' successful!
