### ISSUE TITLE
[Issue]: Model compile not supported: module 'torch' has no attribute '_logging'

### ISSUE THREAD

**Issue by tripletto** [vladmandic/automatic#1667]
### Issue Description

I tried to use model compile (reduce-overhead) under Windows but it seems there is something wrong. Is model compile still a Linux only thing? Do I need a different version of Torch?

15:20:27-014912 WARNING  Model compile not supported: module 'torch' has no attribute '_logging'

The log file says practically the same:
2023-07-13 15:20:27,014 | sd | WARNING | sd_hijack | Model compile not supported: module 'torch' has no attribute '_logging'

### Version Platform Description

<pre>15:18:16-080637 INFO     Starting SD.Next
15:18:16-105294 INFO     Python 3.10.6 on Windows
15:18:16-188099 INFO     Version: 36e7bf4e Thu Jul 13 08:32:58 2023 -0400
15:18:16-828682 INFO     nVidia CUDA toolkit detected
15:18:26-001300 INFO     Torch 2.0.1+cu118
15:18:26-075669 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
15:18:26-082670 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 Ti VRAM 8192 Arch (8, 6) Cores 38
15:18:26-440283 INFO     Disabled extensions-builtin: ['sd-webui-controlnet', 'sd-dynamic-thresholding',
                         'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris']
15:18:26-446286 INFO     Enabled extensions-builtin: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-model-converter', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
15:18:26-466950 INFO     Disabled extensions: ['sd-webui-controlnet', 'sd-dynamic-thresholding',
                         'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris']
15:18:26-471952 INFO     Enabled extensions: ['adetailer', 'canvas-zoom', 'stable-diffusion-webui-state']
15:18:26-484387 INFO     Verifying requirements
15:18:26-518395 WARNING  Package wrong version: diffusers 0.18.1 required 0.18.2
15:18:26-522395 INFO     Installing package: diffusers==0.18.2
15:18:42-390968 INFO     Verifying packages
15:18:42-395969 INFO     Verifying repositories
15:18:47-153420 INFO     Verifying submodules
15:19:45-246267 INFO     Extensions enabled: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-model-converter', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR', 'adetailer', 'canvas-zoom', 'stable-diffusion-webui-state']
15:19:45-254269 INFO     Verifying packages
15:19:45-280843 INFO     Extension preload: 0.0s C:\stable-diffusion-webui-vlad\extensions-builtin
15:19:45-285843 INFO     Extension preload: 0.0s C:\stable-diffusion-webui-vlad\extensions
15:19:45-344467 INFO     Server arguments: []
15:19:57-630075 INFO     Pipeline: Backend.ORIGINAL
No module 'xformers'. Proceeding without it.
15:20:03-829486 INFO     Libraries loaded
15:20:03-833490 INFO     Using data path: C:\stable-diffusion-webui-vlad
15:20:03-845495 INFO     Available VAEs: C:\stable-diffusion-webui-vlad\models\VAE 1
15:20:04-498613 INFO     Available models: C:\stable-diffusion-webui-vlad\models\Stable-diffusion 29
[-] ADetailer initialized. version: 23.7.5, num models: 9
15:20:15-025362 INFO     Loading UI theme: name=gradio/base style=Light
Running on local URL:  http://127.0.0.1:7860
15:20:20-724290 INFO     Local URL: http://127.0.0.1:7860/
15:20:20-728291 INFO     Initializing middleware
15:20:21-165029 INFO     [AgentScheduler] Runner is paused
15:20:21-169030 INFO     [AgentScheduler] Registering APIs
Loading weights: C:\stable-diffusion-webui-vlad\models\Stable-diffusion\realisticVisionV20_v20.safetensors ---------- 0.0/2.1 GB -:--:--
15:20:22-446497 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
15:20:27-014912 WARNING  Model compile not supported: module 'torch' has no attribute '_logging'
15:20:27-018914 INFO     Applying scaled dot product cross attention optimization (without memory efficient attention)
15:20:27-146620 INFO     Embeddings: loaded=2 skipped=0
15:20:27-161623 INFO     Model loaded in 5.4s (load=0.6s config=0.2s create=0.9s apply=1.9s vae=0.5s move=1.1s embeddings=0.1s)
15:20:27-565715 INFO     Model load finished: {'ram': {'used': 7.04, 'total': 79.93}, 'gpu': {'used': 3.08, 'total': 8.0}, 'retries': 0,
                         'oom': 0} cached=1
15:20:28-115955 INFO     Startup time: 42.8s (torch=8.5s gradio=2.4s libraries=7.6s models=0.7s codeformer=0.2s gfpgan=0.1s
                         scripts=10.0s onchange=0.2s ui-txt2img=0.4s ui-img2img=0.1s ui-train=0.1s ui-settings=0.2s ui-extensions=4.3s
                         ui-defaults=0.1s launch=0.4s app-started=0.7s checkpoint=6.7s)</pre>

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
torch compile in general is pretty broken in torch 2.0.1 and best used with torch 2.1 nightly and there the function is present.
