### ISSUE TITLE
[Issue]: Deforum won't load/show in UI

### ISSUE THREAD

**Issue by jmartens22** [vladmandic/automatic#167]
### Issue Description

I downloaded/installed Deforum extension via UI. Receive this error message when webui loads:

loading script: deforum.py: ModuleNotFoundError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ G:\SD-ALT\automatic\modules\scripts.py:255 in load_scripts                                                           │
│                                                                                                                      │
│   254 │   │   │                                                                                                      │
│ ❱ 255 │   │   │   script_module = script_loading.load_module(scriptfile.path)                                        │
│   256 │   │   │   register_scripts_from_module(script_module)                                                        │
│                                                                                                                      │
│ G:\SD-ALT\automatic\modules\script_loading.py:9 in load_module                                                       │
│                                                                                                                      │
│    8 │   module = importlib.util.module_from_spec(module_spec)                                                       │
│ ❱  9 │   module_spec.loader.exec_module(module)                                                                      │
│   10                                                                                                                 │
│                                                                                                                      │
│                                               ... 7 frames hidden ...                                                │
│                                                                                                                      │
│ G:\SD-ALT\automatic/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/src\midas\blocks.py:4 in      │
│ <module>                                                                                                             │
│                                                                                                                      │
│     3                                                                                                                │
│ ❱   4 from .backbones.beit import (                                                                                  │
│     5 │   _make_pretrained_beitl16_512,                                                                              │
│                                                                                                                      │
│ G:\SD-ALT\automatic/extensions/deforum-for-automatic1111-webui/scripts/deforum_helpers/src\midas\backbones\beit.py:9 │
│ in <module>                                                                                                          │
│                                                                                                                      │
│     8 from .utils import forward_adapted_unflatten, make_backbone_default                                            │
│ ❱   9 from timm.models.beit import gen_relative_position_index                                                       │
│    10 from torch.utils.checkpoint import checkpoint                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'timm.models.beit'

Tried:

Updating extension via UI
Updating extension via git pull
Updating webui via git pull

Love this project and this is by no means a complaint - this fork has already made vast improvements vs A1111 and can't wait to see its evolution. Thanks for all your work Vlad!

### Version Platform Description

Windows 11
Python 3.10
Chrome Version 112.0.5615.87 (Official Build) (64-bit)

System Info: 

![Screenshot 2023-04-16 042637](https://user-images.githubusercontent.com/113121510/232286709-84bed8db-3aec-4434-bdf7-374cb18d4614.png)

**Comment by Shadowghost** [comment]
A more recent than the currently automatically installed version of the `timm` package is required to make this work. AFAIK this is due to one of the upstream repositories setting a hard dependency on  an old version of it.
I forced `timm=0.6.13` via `requirements.txt` and did not have any problems with it up until now.

**Comment by jmartens22** [comment]
> A more recent than the currently automatically installed version of the `timm` package is required to make this work. AFAIK this is due to one of the upstream repositories setting a hard dependency on an old version of it. I forced `timm=0.6.13` via `requirements.txt` and did not have any problems with it up until now.

Did this and now Deforum is showing/accessible in UI! Thank you!!

When trying to generate video, received following error message. Unsure if system issue or user error.

G:\SD-ALT\automatic/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\colors.py:18 in               │
│ maintain_colors                                                                                                      │
│                                                                                                                      │
│   17 │   │   color_match_lab = cv2.cvtColor(color_match_sample, cv2.COLOR_RGB2LAB)                                   │
│ ❱ 18 │   │   matched_lab = match_histograms(prev_img_lab, color_match_lab, multichannel=True)                        │
│   19 │   │   return cv2.cvtColor(matched_lab, cv2.COLOR_LAB2RGB)                                                     │
│                                                                                                                      │
│ G:\SD-ALT\automatic\venv\lib\site-packages\skimage\_shared\utils.py:326 in fixed_func                                │
│                                                                                                                      │
│   325 │   │   │   if channel_axis is None:                                                                           │
│ ❱ 326 │   │   │   │   return func(*args, **kwargs)                                                                   │
│   327                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: match_histograms() got an unexpected keyword argument 'multichannel'
Traceback (most recent call last):
  File "G:\SD-ALT\automatic\venv\lib\site-packages\gradio\blocks.py", line 987, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\SD-ALT\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\SD-ALT\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "G:\SD-ALT\automatic\venv\lib\site-packages\gradio\blocks.py", line 991, in postprocess_data
    raise ValueError(
ValueError: Number of output components does not match number of values returned from from function f

**Comment by vladmandic** [comment]
i'll add to `requirements.txt`
```
opencv-python==4.7.0.72
timm==0.6.13
```
