### ISSUE TITLE
[Issue]: No models detected, but many models are in the folder

### ISSUE THREAD

**Issue by ultrawyde** [vladmandic/automatic#1673]
### Issue Description

I started the webui script today with the --upgrade flag, and it suddenly prompted me if I wanted to download the default checkpoint, which I thought was very odd because I already have it. I actually have 19 checkpoints in the models/Stable-diffusion folder.

```
18:47:59-824212 ERROR    Error listing diffusers: D:\vladmandic-sd\models\Diffusers Cache directory not found:
                         D:\vladmandic-sd\models\Diffusers. Please use `cache_dir` argument or set
                         `HUGGINGFACE_HUB_CACHE` environment variable.
18:47:59-825212 INFO     Available models: D:\vladmandic-sd\models\Stable-diffusion 0
```

When I go into the webUI and refresh the checkpoint dropdown, it loads endlessly, and I get this in the command line output:
```
Download the default model? (y/N) Traceback (most recent call last):
  File "D:\vladmandic-sd\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\vladmandic-sd\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\vladmandic-sd\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\vladmandic-sd\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\vladmandic-sd\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\vladmandic-sd\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\vladmandic-sd\modules\ui_common.py", line 215, in refresh
    refresh_method()
  File "D:\vladmandic-sd\modules\shared.py", line 248, in refresh_checkpoints
    return modules.sd_models.list_models()
  File "D:\vladmandic-sd\modules\sd_models.py", line 159, in list_models
    key = input('Download the default model? (y/N) ')
ValueError: I/O operation on closed file.
```

I have reran the webui script with --reinstall but get the same behavior.

### Version Platform Description

Version: d4c9d752 Thu Jul 13 23:13:44 2023 +0300
Windows 11 Build 22621.1992
Nvidia driver 536.40

 ```
Starting SD.Next
18:55:26-256904 INFO     Python 3.10.11 on Windows
18:55:26-298444 INFO     Version: d4c9d752 Thu Jul 13 23:13:44 2023 +0300
18:55:26-495827 INFO     nVidia CUDA toolkit detected
18:55:26-496828 INFO     Installing package: torch torchvision --index-url https://download.pytorch.org/whl/cu118
18:55:29-828953 INFO     Torch 2.0.1+cu118
18:55:29-856720 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
18:55:29-858722 INFO     Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by ultrawyde** [comment]
I found that the backend setting was not selected in the settings. I chose original and restarted and my models were detected.

Not sure if this was intended to happen with the upgrade?

**Comment by Aurety** [comment]
Same behavior from the last update, I checked yes for the runway model, now I have just one model available now..

**Comment by Aurety** [comment]
> I found that the backend setting was not selected in the settings. I chose original and restarted and my models were detected.
> 
> Not sure if this was intended to happen with the upgrade?
> 
> Edit: I went back and changed it to diffusers as well just to check, and it detected my models as well in this setting.

Thank you, fixed the issue !!

**Comment by vladmandic** [comment]
its not intended, its a bug - i'll fix it tomorrow.

**Comment by vladmandic** [comment]
should be fixed now.
