### ISSUE TITLE
[Issue]: loading stable xl weights mismatch

### ISSUE THREAD

**Issue by zhangvia** [vladmandic/automatic#1676]
### Issue Description

i just install the webui from main repo,but when i load stable xl base 0.9, there is always the weights miss match error,and the webui will still load the weights.but when i use text2img,the result image is completely black
![image](https://github.com/vladmandic/automatic/assets/38352569/b785463d-d67c-42bf-8d93-bab423691fbe)
![image](https://github.com/vladmandic/automatic/assets/38352569/a001adb2-2607-41d3-87ec-e66d4dc25774)
how do i use the stable xl weights?

### Version Platform Description

ubuntu20.04
torch2.0.1

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by zhangvia** [comment]
besides，the backend diffusers can't load the diffusers repo that downloaded manually,it can only use the huggingface cache folder. that's pretty inconvenience

**Comment by Darkflo264** [comment]
As i know SDXL can only be used with the Diffusers backend right now. 
(i would love to see some "best practice" about the settings there - refiner is doing terrible results and even with setting of 5 steps only doing 1 step)

I also hope SDXL is going to work as .safetensor file(s) for the Original Backend somewhen / soon, too!

@vladmandic Is this on the ToDo list to implement as well?

**Comment by zhangvia** [comment]
> As i know SDXL can only be used with the Diffusers backend right now. (i would love to see some "best practice" about the settings there - refiner is doing terrible results and even with setting of 5 steps only doing 1 step)
> 
> I also hope SDXL is going to work as .safetensor file(s) for the Original Backend somewhen / soon, too!
> 
> @vladmandic Is this on the ToDo list to implement as well?
i'm new to this webui, i found that when i set the base model path and change to diffuser backend, the real load diffusers model path will be like base model path +"Diffusers". how do i set my custom diffusers models path? and i look at the source code, it looks like that the diffusers backend can only load the huggingface diffusers cache dir. if i download the huggingface model repo manually, the webui can't recognize the path. is that right?

**Comment by vladmandic** [comment]
ask in discord. there is clear instruction not to open issues here for sd-xl as its experimental.
and yes, all your questions do have answers.
