### ISSUE TITLE
[Feature]: Verbose output

### ISSUE THREAD

**Issue by littleboot** [vladmandic/automatic#1681]
### Feature description

I would like have verbose output on what the program is doing.
Example:
Below is an example of the cmd output when running the program first time, what I'm missing is the progress information of the current task.
In this case I would like to see the download progression and download speed (I'm using a mobile internet connection that is quite unstable, seeing this information would help in trouble shooting
```
19:37:30-417289 INFO     nVidia CUDA toolkit detected
19:37:30-419288 INFO     Installing package: torch torchvision --index-url https://download.pytorch.org/whl/cu118
```
I propose adding the --verbose option to enable addition output messages.

**Comment by vladmandic** [comment]
it already exists, its `webui --debug`
