### ISSUE TITLE
[Extension]: Deforum Generate Unresponsive 

### ISSUE THREAD

**Issue by neonjung** [vladmandic/automatic#1684]
### Issue Description

The Deforum extension 'Generate' button no longer does anything. I have been using this extension without issues for many months now. Everything is up to date, tried reinstalling everything from clean. Recently I started webui with --backend diffusers to use sdxl 0.9, but then returned to normal webui with --backend original. I also once launched in medvram so unsure if that changed anything, but that was all before I completed a fresh install of everything. I'm on Win11, browser doesn't make any difference, Edge, Chrome, Firefox all have totally unresponsive Generate button. 

### Version Platform Description

Win 11, Chrome Browser, SD Next latest version, Deforum latest version, rtx 3090.

There is nothing to report from Console as the generate button literally does nothing.

### URL link of the extension

https://github.com/deforum-art/sd-webui-deforum

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
just pushed an update, please try

**Comment by neonjung** [comment]
Fixed, many thanks.

**Comment by derspanier1** [comment]
Parseq still has issues, or it´s me.

```
*START OF TRACEBACK*
Traceback (most recent call last):
  File "E:\SD_Next\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\run_deforum.py", line 78, in run_deforum
    render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root)
  File "E:\SD_Next\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\render.py", line 548, in render_animation
    image = generate(args, keys, anim_args, loop_args, controlnet_args, root, parseq_adapter, frame_idx, sampler_name=scheduled_sampler_name)
  File "E:\SD_Next\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\generate.py", line 56, in generate
    return generate_inner(args, keys, anim_args, loop_args, controlnet_args, root, parseq_adapter, frame, sampler_name)
  File "E:\SD_Next\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\generate.py", line 243, in generate_inner
    processed = processing.process_images(p)
  File "E:\SD_Next\modules\processing.py", line 545, in process_images
    res = process_images_inner(p)
  File "E:\SD_Next\extensions-builtin\sd-webui-controlnet\scripts\batch_hijack.py", line 42, in processing_process_images_hijack
    return getattr(processing, '__controlnet_original_process_images_inner')(p, *args, **kwargs)
  File "E:\SD_Next\modules\processing.py", line 695, in process_images_inner
    file.write(processed.infotext(p, 0))
  File "E:\SD_Next\modules\processing.py", line 341, in infotext
    return create_infotext(p, self.all_prompts, self.all_seeds, self.all_subseeds, comments=[], position_in_batch=index % self.batch_size, iteration=index // self.batch_size)
  File "E:\SD_Next\modules\processing.py", line 475, in create_infotext
    "Token merging ratio hr": None if not p.enable_hr or token_merging_ratio_hr == 0 else token_merging_ratio_hr,
AttributeError: 'StableDiffusionProcessingImg2Img' object has no attribute 'enable_hr'
*END OF TRACEBACK*

User friendly error message:
Error: 'StableDiffusionProcessingImg2Img' object has no attribute 'enable_hr'. Check your schedules/ init values please. Also make sure you don't have a backwards slash in any of your PATHs - use / instead of \.
```

02:46:18-767250 INFO     Upgraded to version: ce92bf06 Fri Jul 14 20:43:50 2023 -0400

**Comment by fbellgr** [comment]
> StableDiffusionProcessingImg2Img' object has no attribute

Exact same thing here.

**Comment by vladmandic** [comment]
that's a different one, i'll take care of it tomorrow.

**Comment by vladmandic** [comment]
this last error has been fixed.

**Comment by YKefasu** [comment]
@vladmandic When using --share in, the "Generate'" button becomes unresponsive for some Google Colab users.

This issue occurs after the live preview progress bar is moved inside the generate button.

**Comment by YKefasu** [comment]
hoping you would consider taking a look at this issue
