### ISSUE TITLE
[Feature Request]: Excluding some files from the git to allow easier upgrade

### ISSUE THREAD

**Issue by razvan-nicolae** [vladmandic/automatic#169]
### Feature description

At this time, every git pull we need to replace 
/user.css
/styles.csv
/styles.csv.bak

The same goes for any tweaks we do in launch.py, but for that one I don't know of any easy fix, or how you do the os.environ tweaks to stick between upgrades.

The gitignore itself is also in the git, so we can't use it to exclude anything either. 
Any ideas?

**Comment by vladmandic** [comment]
done.
