### ISSUE TITLE
[Issue]: Cannot start webui.bat, missing module named 'rich'

### ISSUE THREAD

**Issue by RoyalCyan** [vladmandic/automatic#1698]
### Issue Description

**Problem**
I have just copied the files from github using the git command. I tried to launch the program by running webui.bat, but inside the command line I get this:

```
Using VENV: S:\automatic\venv
Error running pip: install --upgrade rich
Traceback (most recent call last):
  File "S:\automatic\launch.py", line 154, in <module>
    installer.setup_logging()
  File "S:\automatic\installer.py", line 69, in setup_logging
    from rich.theme import Theme
ModuleNotFoundError: No module named 'rich'
Press any key to continue . . .
```

After that I made sure to check if I had `rich` installed. I ran `pip install rich` and it got the latest version. But the problem still persists. This is my first attempt at launching this software, but so far I can't even check the version number. Strangely enough it didn't generate any sdnext.log

### Version Platform Description

Python 3.10.6
Windows 11
Version: Can't check it but it is the latest as of writing this (15.07.2023)
Intel Arc a770 GPU with use_ipex enabled

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
there is no log file generated because error happens during initialization of logging.
since rich is pretty much the first package it installs, it seems it cant install in venv (you installed it globally, but that doesn't matter).
remove venv folder and try again. if it doesn't help, you'll need to check whats possibly wrong with venv on your system.

> Using VENV: S:\automatic\venv
> Error running pip: install --upgrade rich

**Comment by RoyalCyan** [comment]
> there is no log file generated because error happens during initialization of logging. since rich is pretty much the first package it installs, it seems it cant install in venv (you installed it globally, but that doesn't matter). remove venv folder and try again. if it doesn't help, you'll need to check whats possibly wrong with venv on your system.
> 
> > Using VENV: S:\automatic\venv
> > Error running pip: install --upgrade rich

Thank you very much for the help! It did fix the problem. After deleting venv folder and launching the webui.bat again it has successfully started and installed all dependencies. Although I have noticed that it installed torch in CPU only mode and during an image generation it only uses my CPU. Any ideas how can I enable my GPU?

Should I instead make a new issue regarding my question?

**Comment by vladmandic** [comment]
run `webui --use-ipex --reinstall`

**Comment by Disty0** [comment]
IPEX is Linux only. Use WSL if you want to use it in Windows.

Either use the docker image or install it manually.

https://blog.nuullll.com/ipex-sd-docker-for-arc-gpu/#/getting-started

https://www.technopat.net/sosyal/konu/using-stable-diffusion-webui-with-intel-arc-gpus.2593077
