### ISSUE TITLE
[Feature]: Extend ui-config.json to include the new "second pass" options

### ISSUE THREAD

**Issue by a2ZxgdqHeSs8F51cIyuK** [vladmandic/automatic#1699]
### Feature description

Hello, with a very recent update the hires fix section was changed and expanded into a "second pass" section.
However it seems the default values used in it don't appear in the ui-config.json file, which I use to set the defaults to values that work well for me so I don't have to reconfigure them every time I use the WebUI.

### Version Platform Description

5e2fb4d6 Sat Jul 15 07:17:48 2023 -0400

**Comment by vladmandic** [comment]
done.
