### ISSUE TITLE
Can't start anymore after newest commit: NameError: name 'css' is not defined

### ISSUE THREAD

**Issue by tripletto** [vladmandic/automatic#170]
### Issue Description

<pre>14:39:09-641109 INFO     Python 3.10.6 on Windows
14:39:09-686574 INFO     No changes detected: quick launch active
14:39:09-687575 INFO     Setting environment tuning
14:39:11-302204 INFO     Torch 2.0.0+cu118
14:39:11-323154 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
14:39:11-325154 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 Ti VRAM 8192 Arch (8, 6) Cores 38
14:39:11-326154 INFO     Server arguments: []
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ c:\stable-diffusion-webui-vlad\launch.py:94 in <module>                                                             │
│                                                                                                                     │
│   93     import webui                                                                                               │
│ > 94     webui.webui()                                                                                              │
│   95                                                                                                                │
│                                                                                                                     │
│ c:\stable-diffusion-webui-vlad\webui.py:174 in webui                                                                │
│                                                                                                                     │
│   173     startup_timer.record("scripts before_ui_callback")                                                        │
│ > 174     shared.demo = modules.ui.create_ui()                                                                      │
│   175     startup_timer.record("ui")                                                                                │
│                                                                                                                     │
│ C:\stable-diffusion-webui-vlad\modules\ui.py:1503 in create_ui                                                      │
│                                                                                                                     │
│   1502                                                                                                              │
│ > 1503     with gr.Blocks(css=css, theme=shared.gradio_theme, analytics_enabled=False, title="S                     │
│   1504         with gr.Row(elem_id="quicksettings", variant="compact"):                                             │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
NameError: name 'css' is not defined</pre>

Did try git reset --hard and git pull afterwards with no success. Everything was working flawlessly about 10 hours ago.

**Comment by vladmandic** [comment]
youre quick - that error was due to pr merge and was up for ~10min, its fixed now

**Comment by tripletto** [comment]
It's seems, that my git pull timing wasn't optimal! 😄 

Thanks again for your great work! Let me know if I can buy you a coffee!
