### ISSUE TITLE
[Extension]: unresponsive generate button on goggle colab

### ISSUE THREAD

**Issue by PEPOoooPPPoooopopOPOPOpopopo** [vladmandic/automatic#1705]
### Issue Description

Hello, so there is an error while you click the generate button on goggle colab, when you click first is responding but afther 3 or maybe 5 it would be not responding and there is no logs exist like showing Info or maybe error if error (lol), but if u use like change check point its still work and no error. I think the problem is on Generate button not goggle colab. I hope u read this and fix it (if error) soon cyaa😁

(sorry if my english bad;-;)

### Version Platform Description

Starting SD.Next, Python 3.10.12 on Linux, ver 55c0269, Cuda toolkit detected, Torch backend: nVidia CUDA 11.8 cuDNN 8700, Torch detected GPU: Tesla T4 VRAM 15102 Arch (7, 5) Cores 40

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by PEPOoooPPPoooopopOPOPOpopopo** [comment]
Btw, there is a same issue like this before but someone say is alr patched but another sides say still error

**Comment by DirtyHamster** [comment]
Check to see if Shift+Enter with the cursor attention in the prompt will trigger it to generate still.

**Comment by PEPOoooPPPoooopopOPOPOpopopo** [comment]
@DirtyHamster Alr i will try it

**Comment by PEPOoooPPPoooopopOPOPOpopopo** [comment]
@DirtyHamster Ty bro is work i
