### ISSUE TITLE
[Extension]: Interrogator

### ISSUE THREAD

**Issue by FeatureIsNotABug** [vladmandic/automatic#1707]
### Issue Description

Using Interrogator on the prompt page resulting every time in an error:
The size of tensor a (8) must match the size of tensor b (64) at non-singleton dimension 0

### Version Platform Description

current version

Starting SD.Next
Python 3.10.11 on Windows
Version: a7f5e75a Sat Jul 15 16:07:10 2023 -0400
nVidia CUDA toolkit detected
Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3090 VRAM 24576 Arch (8, 6) Cores 82
Modified files: ['modules/lycoris', 'results/', 'scripts/loopback_scaler.py',
'scripts/prompt_enhancer.py']
Disabled extensions-builtin: ['canvas-zoom']
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
'model-keyword', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET',
'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser',
'stable-diffusion-webui-rembg', 'SwinIR']
Disabled extensions: ['canvas-zoom']
Enabled extensions: ['infinite-zoom-automatic1111-webui', 'SadTalker',
'sd-webui-3d-open-pose-editor', 'Stable-Diffusion-Webui-Civitai-Helper',
'stable-diffusion-webui-two-shot', 'ultimate-upscale-for-automatic1111']

### URL link of the extension

https://github.com/pharmapsychotic/clip-interrogator-ext.git

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by TeutonJon78** [comment]
I believe this error is why they switched the current version to use a fork instead of the main one -- https://github.com/Dahvikiin/clip-interrogator-ext

They didn't update existing installations though. There is a command to update the extension to the other version, but I'm having an issue relocating it.

**Comment by vladmandic** [comment]
Correct. Follow instructions in the linked post.
