### ISSUE TITLE
[Feature]: instruct pix2pix ui drop down menu

### ISSUE THREAD

**Issue by DirtyHamster** [vladmandic/automatic#1708]
### Feature description

I recently was reading up on this and pix2pix can run as it's own model or from another model layer. Could this get the same treatment as the existing Stable Diffusion checkpoint dict's optional dropdown does. As this is a solo trainable model/layer for function it should probably get it's own pathing to folders though if someone wants to drop in the base pix2pix model. Is there anyway to do both i.e. pull from it's own folder for the base model and check the architecture for fine tuned models in the general model folder?

**Comment by vladmandic** [comment]
enhanced support for instruct pix2pix (sd and sdxl) has been added to dev branch so it can be used as refiner.
