### ISSUE TITLE
[Issue]: FinalizeS3 was not called on exit

### ISSUE THREAD

**Issue by scpedicini** [vladmandic/automatic#1709]
### Issue Description

On Ctrl-C to exit Vlad, I get the following error which hangs indefinitely until I manually terminate python. I ran `webui --upgrade`, and also tried using `webui --safe` earlier today to see if that would fix the issue but still seems to occur every time I attempt to exit.

Including a startup / ending of console:
```
17:10:27-737506 INFO     Starting SD.Next
17:10:27-740402 INFO     Python 3.10.9 on Windows
17:10:27-763403 INFO     Version: a7f5e75a Sat Jul 15 16:07:10 2023 -0400
17:10:28-031008 INFO     nVidia CUDA toolkit detected
17:10:28-818189 INFO     Torch 2.0.0+cu118
17:10:28-836535 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
17:10:28-839163 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
17:10:28-938887 INFO     Verifying requirements

<SNIP>

17:11:23-631664 INFO     Applying scaled dot product cross attention optimization
17:11:23-657307 INFO     Embeddings: loaded=11 skipped=3
17:11:23-662302 INFO     Model loaded in 1.7s (load=0.3s create=0.3s apply=0.5s vae=0.3s move=0.4s)
17:11:24-026252 INFO     Model load finished: {'ram': {'used': 7.9, 'total': 63.15}, 'gpu': {'used': 3.78, 'total': 23.99}, 'retries': 0, 'oom':
                         0} cached=1
17:11:24-447350 INFO     Startup time: 33.7s (torch=2.0s gradio=0.4s libraries=1.2s scripts=19.9s onchange=0.2s ui-txt2img=0.1s ui-settings=0.1s
                         ui-extensions=2.5s launch=4.2s app-started=0.2s checkpoint=2.9s)
22:23:50-041814 INFO     Exiting
C:\arrow\cpp\src\arrow\filesystem\s3fs.cc:2598:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit
```

This is the only reference I could find to this issue:
https://github.com/lshqqytiger/stable-diffusion-webui-directml/pull/172

### Version Platform Description

Windows 10 x64 + GTX 4090

```
17:10:27-737506 INFO     Starting SD.Next
17:10:27-740402 INFO     Python 3.10.9 on Windows
17:10:27-763403 INFO     Version: a7f5e75a Sat Jul 15 16:07:10 2023 -0400
17:10:28-031008 INFO     nVidia CUDA toolkit detected
17:10:28-818189 INFO     Torch 2.0.0+cu118
17:10:28-836535 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
17:10:28-839163 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by brknsoul** [comment]
A workaround or fix;

```venv\Script\activate
pip install --upgrade --force-reinstall pyarrow==11.0.0
deactivate
```

**Comment by TeutonJon78** [comment]
Just to add to the info for the reporter, it's due to change in the image browser built-in extension from 2023-7-14. Even if it's a bug, it doesn't really affect much since it only triggers when quitting the app anyway

**Comment by brknsoul** [comment]
> since it only triggers when quitting the app anyway

Not helpful if you're problem solving or experimenting with settings and you want to return to the command prompt. :-P

**Comment by vladmandic** [comment]
i've changed os._exit to sys.exit and frozen version of pyarrow==11.0.0, those two things should fix this.
fixed in dev, release expected in 1-2h.
