### ISSUE TITLE
[Issue]: After upgrade to  7a859cdb version error in SDXL 0.9

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#1719]
### Issue Description

 I made a clean installetion only for defusers. and I work with SDXL 0.9 for cople of dayes.
Aftar upgrade to 7a859cdb I got this error: "list indices must be integers or slices, not NoneType"

Here is the full list in the CMD: 

C:\V\automatic>webui.bat --backend diffusers --medvram --upgrade
Using VENV: C:\V\automatic\venv
22:29:46-322114 INFO     Starting SD.Next
22:29:46-326115 INFO     Python 3.10.7 on Windows
22:29:46-411117 INFO     Version: 7a859cdb Sun Jul 16 12:56:52 2023 -0400
22:29:47-017114 INFO     nVidia CUDA toolkit detected
22:29:47-162116 INFO     Verifying requirements
22:29:47-173113 INFO     Verifying packages
22:29:47-176113 INFO     Verifying repositories
22:29:52-311115 INFO     Verifying submodules
22:30:36-530354 INFO     Extensions enabled: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR',
                         'Mask2Background']
22:30:36-534351 INFO     Verifying packages
22:30:36-536351 INFO     Updating Wiki
22:30:37-642351 INFO     Extension preload: 0.0s C:\V\automatic\extensions-builtin
22:30:37-644356 INFO     Extension preload: 0.0s C:\V\automatic\extensions
22:30:37-658351 INFO     Server arguments: ['--backend', 'diffusers', '--medvram', '--upgrade']
No module 'xformers'. Proceeding without it.
22:30:44-077351 INFO     Pipeline: Backend.DIFFUSERS
22:30:44-716351 INFO     Libraries loaded
22:30:44-719353 INFO     Using data path: C:\V\automatic
22:30:44-722351 INFO     Available VAEs: C:\V\automatic\models\VAE 0
22:30:44-739351 INFO     Available models: C:\V\automatic\models\Stable-diffusion 2
22:30:47-992353 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://127.0.0.1:7860
22:30:50-230351 INFO     Local URL: http://127.0.0.1:7860/
22:30:50-232353 INFO     Initializing middleware
22:30:50-350352 INFO     [AgentScheduler] Task queue is empty
22:30:50-352350 INFO     [AgentScheduler] Registering APIs
22:30:50-469352 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
22:30:50-472353 INFO     Loading diffuser model: stabilityai/stable-diffusion-xl-base-0.9
22:30:56-837353 INFO     Embeddings: loaded=0 skipped=0
22:30:56-839352 INFO     Model loaded in 6.4s (load=6.4s)
22:30:57-160351 INFO     Model load finished: {'ram': {'used': 1.11, 'total': 31.24}, 'gpu': {'used': 8.11, 'total':
                         24.0}, 'retries': 0, 'oom': 0}
22:30:57-167351 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
22:30:57-169352 INFO     Loading diffuser refiner: stabilityai/stable-diffusion-xl-refiner-0.9
22:30:59-718354 INFO     Embeddings: loaded=0 skipped=0
22:30:59-720352 INFO     Model loaded in 2.6s (load=2.6s)
22:31:00-023352 INFO     Model load finished: {'ram': {'used': 6.8, 'total': 31.24}, 'gpu': {'used': 8.11, 'total':
                         24.0}, 'retries': 0, 'oom': 0}
22:31:00-028352 INFO     Startup time: 22.3s (torch=4.7s gradio=0.7s libraries=1.6s scripts=2.9s onchange=0.3s
                         ui-txt2img=0.1s ui-img2img=0.1s ui-settings=0.1s ui-extensions=1.8s ui-defaults=0.1s
                         launch=0.1s app-started=0.2s checkpoint=9.6s)
22:32:08-677171 ERROR    Exception: list indices must be integers or slices, not NoneType
22:32:08-680169 ERROR    Arguments: args=('task(267kasb4ogtpngr)', 'A cheeky innocence that begs to be explored and
                         touched', '', [], 20, 0, None, False, False, 1, 1, 6, 6, 0.7, 1, -1.0, -1.0, 0, 0, 0, 1024,
                         1024, False, 0.7, 2, 'Latent', 20, 0, 0, 0, 1, '', '', [], 0, False, False, 'positive',
                         'comma', 0, False, False, '', 0, '', [], 0, '', [], 0, '', [], True, False, False, False, 0,
                         False) kwargs={}
22:32:08-693168 ERROR    gradio call: TypeError
┌──────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────┐
│ C:\V\automatic\modules\call_queue.py:34 in f                                                                      │
│                                                                                                                   │
│    33 │   │   │   try:                                                                                            │
│ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                 │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                       │
│                                                                                                                   │
│ C:\V\automatic\modules\txt2img.py:34 in txt2img                                                                   │
│                                                                                                                   │
│   33 │   │   sampler_name=sd_samplers.samplers[sampler_index].name,                                               │
│ > 34 │   │   latent_sampler=sd_samplers.samplers[latent_index].name,                                              │
│   35 │   │   batch_size=batch_size,                                                                               │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: list indices must be integers or slices, not NoneType

### Version Platform Description

Windows 10 pro with 32 GB ram
NVIDIA RTX 3090
Browser: Chrom

 Version: 7a859cdb Sun Jul 16 12:56:52 2023 -0400

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
duplicate.
