### ISSUE TITLE
[Issue]: Not loading

### ISSUE THREAD

**Issue by holly604** [vladmandic/automatic#1721]
### Issue Description

I was using SD:next with no problems when it suddenly stopped working, no errors were shown on the console, so I restarted it, and it wouldn't restart. The webui:bat opened as normal, but then it just stops, with no error code, and not crashed, just doesn't load. It's the same with Automatic1111. I had made no changes to either SD:Next or Automatic1111, the only thing that changed was that Norton updated all the drivers, I have rolled back the Nvidia driver as I knew there was an issue previously, but that made no difference. I have looked at the sdnext.log, and there seems to be nothing there. I am using the current version, and have tried running it the --safe arguement.

### Version Platform Description

"Using VENV: C:\Users\phili\OneDrive\automatic\venv
16:28:52-598072 INFO     Starting SD.Next
16:28:52-598072 INFO     Python 3.10.11 on Windows
16:28:52-660991 INFO     Version: da11f32d Sun Jul 16 17:58:57 2023 -0400
16:28:53-116919 DEBUG    Setting environment tuning
16:28:53-131438 DEBUG    Torch overrides: cuda=True rocm=False ipex=False diml=False
16:28:53-132954 DEBUG    Torch allowed: cuda=True rocm=False ipex=False diml=False
16:28:53-132954 INFO     nVidia CUDA toolkit detected
16:28:53-274733 INFO     Verifying requirements
16:28:53-290359 INFO     Verifying packages
16:28:53-290359 INFO     Verifying repositories
16:28:53-337640 DEBUG    Submodule: C:\Users\phili\OneDrive\automatic\repositories\stable-diffusion-stability-ai / main
16:28:54-123252 DEBUG    Submodule: C:\Users\phili\OneDrive\automatic\repositories\taming-transformers / master
16:28:54-866445 DEBUG    Submodule: C:\Users\phili\OneDrive\automatic\repositories\k-diffusion / master
16:28:56-230862 DEBUG    Submodule: C:\Users\phili\OneDrive\automatic\repositories\BLIP / main
16:28:56-913909 INFO     Verifying submodules
16:29:00-515324 DEBUG    Submodule: extensions-builtin/a1111-sd-webui-lycoris / main
16:29:01-281643 DEBUG    Submodule: extensions-builtin/clip-interrogator-ext / main
16:29:01-999529 DEBUG    Submodule: extensions-builtin/multidiffusion-upscaler-for-automatic1111 / main
16:29:02-712671 DEBUG    Submodule: extensions-builtin/sd-dynamic-thresholding / master
16:29:03-441836 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
16:29:04-162323 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
16:29:04-917975 DEBUG    Submodule: extensions-builtin/sd-webui-controlnet / main
16:29:05-676562 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-images-browser / main
16:29:06-427722 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
16:29:07-139888 DEBUG    Submodule: modules/lora / main
16:29:07-861227 DEBUG    Submodule: modules/lycoris / main
16:29:08-584459 DEBUG    Submodule: wiki / master
16:29:09-581131 DEBUG    Installed packages: 223
16:29:09-583132 DEBUG    Extensions all: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
16:29:09-638171 DEBUG    Submodule: C:\Users\phili\OneDrive\automatic\extensions-builtin\a1111-sd-webui-lycoris / main
16:29:10-685925 DEBUG    Submodule: C:\Users\phili\OneDrive\automatic\extensions-builtin\clip-interrogator-ext / main
16:29:11-388373 DEBUG    Running extension installer:
                         C:\Users\phili\OneDrive\automatic\extensions-builtin\clip-interrogator-ext\install.py
16:29:20-235949 DEBUG    Submodule:
                         C:\Users\phili\OneDrive\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111
                         / main
16:29:22-087962 DEBUG    Submodule: C:\Users\phili\OneDrive\automatic\extensions-builtin\sd-dynamic-thresholding /
                         master
16:29:23-058810 DEBUG    Submodule: C:\Users\phili\OneDrive\automatic\extensions-builtin\sd-extension-system-info / main
16:29:23-724129 DEBUG    Running extension installer:
                         C:\Users\phili\OneDrive\automatic\extensions-builtin\sd-extension-system-info\install.py
16:29:24-496775 DEBUG    Submodule: C:\Users\phili\OneDrive\automatic\extensions-builtin\sd-webui-agent-scheduler / main
16:29:25-295381 DEBUG    Running extension installer:
                         C:\Users\phili\OneDrive\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
16:29:26-022686 DEBUG    Submodule: C:\Users\phili\OneDrive\automatic\extensions-builtin\sd-webui-controlnet / main
16:29:26-725347 DEBUG    Running extension installer:
                         C:\Users\phili\OneDrive\automatic\extensions-builtin\sd-webui-controlnet\install.py
16:29:27-465401 DEBUG    Submodule:
                         C:\Users\phili\OneDrive\automatic\extensions-builtin\stable-diffusion-webui-images-browser /
                         main
16:29:28-154427 DEBUG    Running extension installer:
                         C:\Users\phili\OneDrive\automatic\extensions-builtin\stable-diffusion-webui-images-browser\inst
                         all.py
16:31:31-440393 DEBUG    Submodule: C:\Users\phili\OneDrive\automatic\extensions-builtin\stable-diffusion-webui-rembg /
                         master
16:31:32-140551 DEBUG    Running extension installer:
                         C:\Users\phili\OneDrive\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
16:31:33-881559 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
16:31:33-883560 INFO     Verifying packages
16:31:33-885560 INFO     Updating Wiki
16:31:33-939077 DEBUG    Submodule: C:\Users\phili\OneDrive\automatic\wiki / master
16:31:34-651965 DEBUG    Setup complete without errors: 1689550295
16:31:34-653801 INFO     Running in safe mode without user extensions
16:31:36-645558 INFO     Extension preload: 1.6s C:\Users\phili\OneDrive\automatic\extensions-builtin
16:31:37-603465 DEBUG    Memory used: 0.04 total: 31.35 Collected 0
16:31:37-605474 DEBUG    Starting module: <module 'webui' from 'C:\\Users\\phili\\OneDrive\\automatic\\webui.py'>
16:31:37-606637 INFO     Server arguments: ['--safe', '--lowvram', '--autolaunch', '--use-cuda', '--upgrade', '--debug']
16:31:37-933557 DEBUG    Loading Torch"

Using Windows 11 and have the same issue on Google Chrome and Opera.

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
its literally stuck while simply loading torch, that is far outside of application control.
i would suggest to reinstall torch and also check windows event logs.

**Comment by holly604** [comment]
Thank you, that fixed that issue.
