### ISSUE TITLE
[Issue]: Cannot start webui.sh

### ISSUE THREAD

**Issue by RoyalCyan** [vladmandic/automatic#1728]
### Issue Description

Hello! I am trying to launch webui.sh for the first time, but when I try to do it via terminal I get this:

```
rudolf@Ruby:~/AI/automatic$ sh webui.sh --use-ipex
webui.sh: 15: [[: not found
webui.sh: 21: [[: not found
webui.sh: 27: [[: not found
webui.sh: 32: [[: not found
webui.sh: 48: [[: not found
Error:  is not installed, aborting...
webui.sh: 56: hash: : Permission denied
```

When I try to launch installer.py nothing happens at all. I don't get anything in return. What should I do? I have python and git installed. I get the same result when launching without the --use-ipex flag. Unfortunately no logs are being generated.

### Version Platform Description

Ubuntu 23.04
Python 3.11.2-1
Version: latest as of 17.07.2023

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
well, don't use `sh` to start it, i don't know why you even tried that.
simply type `./webui.sh`.
