### ISSUE TITLE
[Issue]: Error loading webui - 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by TomerGadol** [vladmandic/automatic#173]
### Issue Description

After latest commit `d9a83b0a` I get the following error when launching webui.bat `404 Client Error: Not Found for url: https://huggingface.co/api/spaces/Default`
See the photos attached:
![image](https://user-images.githubusercontent.com/37028768/232315537-8d9c1cd0-d795-4c11-a924-a6152f5da7fa.png)
![image](https://user-images.githubusercontent.com/37028768/232315545-c308c696-8e2c-4273-8a6a-31ee10acfc55.png)

### Version Platform Description

Windows 10, latest commit 1660ti 6GB vram

**Comment by tripletto** [comment]
Yupp, I have this as well:
<pre>
15:50:47-653238 INFO     Python 3.10.6 on Windows
15:50:47-699256 INFO     Running setup
15:50:47-728257 INFO     Version: d9a83b0a Sun Apr 16 09:05:29 2023 -0400
15:50:48-146628 INFO     Latest available version: d9a83b0abc0cbf4795bdd1e697e264cd0f141697 2023-04-16T13:05:29Z
15:50:48-148628 INFO     Updating Wiki
15:50:49-456785 INFO     Installing requirements
15:50:49-679856 INFO     Installing packages
15:50:49-681851 INFO     Installing repositories
15:50:49-806884 INFO     Installing submodules
15:50:50-513861 INFO     Updating submodules
15:51:01-027678 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
15:51:19-103191 INFO     Extensions enabled: ['multidiffusion-upscaler-for-automatic1111',
                         'stable-diffusion-webui-state']
15:51:20-283400 INFO     Setting environment tuning
15:51:21-679744 INFO     Torch 2.0.0+cu118
15:51:21-701750 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
15:51:21-704751 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 Ti VRAM 8192 Arch (8, 6) Cores 38
15:51:21-705751 INFO     Server arguments: []
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ c:\stable-diffusion-webui-vlad\venv\lib\site-packages\huggingface_hub\utils\_errors.py:259 in hf_raise_for_status   │
│                                                                                                                     │
│   258     try:                                                                                                      │
│ > 259         response.raise_for_status()                                                                           │
│   260     except HTTPError as e:                                                                                    │
│                                                                                                                     │
│ c:\stable-diffusion-webui-vlad\venv\lib\site-packages\requests\models.py:1021 in raise_for_status                   │
│                                                                                                                     │
│   1020         if http_error_msg:                                                                                   │
│ > 1021             raise HTTPError(http_error_msg, response=self)                                                   │
│   1022                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/spaces/Default

The above exception was the direct cause of the following exception:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ c:\stable-diffusion-webui-vlad\venv\lib\site-packages\gradio\themes\base.py:157 in from_hub                         │
│                                                                                                                     │
│ c:\stable-diffusion-webui-vlad\venv\lib\site-packages\huggingface_hub\utils\_validators.py:120 in _inner_fn         │
│                                                                                                                     │
│   119                                                                                                               │
│ > 120         return fn(*args, **kwargs)                                                                            │
│   121                                                                                                               │
│                                                                                                                     │
│ c:\stable-diffusion-webui-vlad\venv\lib\site-packages\huggingface_hub\hf_api.py:1750 in space_info                  │
│                                                                                                                     │
│   1749         r = requests.get(path, headers=headers, timeout=timeout, params=params)                              │
│ > 1750         hf_raise_for_status(r)                                                                               │
│   1751         d = r.json()                                                                                         │
│                                                                                                                     │
│ c:\stable-diffusion-webui-vlad\venv\lib\site-packages\huggingface_hub\utils\_errors.py:301 in hf_raise_for_status   │
│                                                                                                                     │
│   300         # as well (request id and/or server error message)                                                    │
│ > 301         raise HfHubHTTPError(str(e), response=response) from e                                                │
│   302                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
HfHubHTTPError: 404 Client Error: Not Found for url: https://huggingface.co/api/spaces/Default (Request ID:
Root=1-643bfd61-587335e0615abd617f0fa15b)

Sorry, we can't find the page you are looking for.

The above exception was the direct cause of the following exception:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ c:\stable-diffusion-webui-vlad\launch.py:94 in <module>                                                             │
│                                                                                                                     │
│   93     import webui                                                                                               │
│ > 94     webui.webui()                                                                                              │
│   95                                                                                                                │
│                                                                                                                     │
│ c:\stable-diffusion-webui-vlad\webui.py:168 in webui                                                                │
│                                                                                                                     │
│   167 def webui():                                                                                                  │
│ > 168     initialize()                                                                                              │
│   169     if shared.opts.clean_temp_dir_at_start:                                                                   │
│                                                                                                                     │
│ c:\stable-diffusion-webui-vlad\webui.py:95 in initialize                                                            │
│                                                                                                                     │
│    94     shared.opts.onchange("temp_dir", ui_tempdir.on_tmpdir_changed)                                            │
│ >  95     shared.opts.onchange("gradio_theme", shared.reload_gradio_theme)                                          │
│    96     startup_timer.record("opts onchange")                                                                     │
│                                                                                                                     │
│ c:\stable-diffusion-webui-vlad\modules\shared.py:546 in onchange                                                    │
│                                                                                                                     │
│   545         if call:                                                                                              │
│ > 546             func()                                                                                            │
│   547                                                                                                               │
│                                                                                                                     │
│ c:\stable-diffusion-webui-vlad\modules\shared.py:631 in reload_gradio_theme                                         │
│                                                                                                                     │
│   630         try:                                                                                                  │
│ > 631             gradio_theme = gr.themes.ThemeClass.from_hub(theme_name)                                          │
│   632         except requests.exceptions.ConnectionError:                                                           │
│                                                                                                                     │
│ c:\stable-diffusion-webui-vlad\venv\lib\site-packages\gradio\themes\base.py:159 in from_hub                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError: The space Default does not exist</pre>

**Comment by vladmandic** [comment]
ahhh, i've set default gradio theme with wrong spelling. corrected.
