### ISSUE TITLE
[Issue]: Generation Info does not update when switching between multiple rendered images

### ISSUE THREAD

**Issue by brianjz** [vladmandic/automatic#1733]
### Issue Description

The small box below the image generation no longer updates when switching between images while using either Batch Count or Batch Size > 1. This would be the "#html_info_formatted_txt2img" box. This still happens when running in --safe mode and it happens in both Firefox and Chrome.

There are no browser console errors or server errors. I tried to debug it and narrow it down, but I couldn't track it without spending much more time figuring out how it all works and what changes that. I don't know when it last worked, but I feel like it was working within the last week.

### Version Platform Description

15:39:09-715716 INFO     Starting SD.Next
15:39:09-730660 INFO     Python 3.10.9 on Windows
15:39:09-804665 INFO     Version: 11cc14e5 Mon Jul 17 12:45:24 2023 -0400
15:39:10-349205 INFO     Latest published version: 57dd6652dfdead0e0efd1ebfad0cff29dea2221a 2023-07-17T19:30:53Z
15:39:10-359208 INFO     nVidia CUDA toolkit detected

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed in dev, will publish in ~1h.
