### ISSUE TITLE
"Use original name for output filename during batch process" does not work 

### ISSUE THREAD

**Issue by bdulfer** [vladmandic/automatic#1738]
### Issue Description

The setting "Use original name for output filename during batch process" (use_original_name_batch) does not work.

Neither in Process Batch nor in Process Folder.

Always a new filename is generated following the filename pattern.

Tested after reinstall, all extensions disabled, --safe used.

### Version Platform Description

From System Info Tab

Version:
app: SD.next
updated: 2023-07-17
hash: c71467e7
url: https://github.com/vladmandic/automatic/tree/master

Platform:
arch: x86_64
cpu: x86_64
system: Linux
release: 5.14.21-150400.24.69-default
python: 3.10.11

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed. plus few other things while i was looking at that code.
fixed img2img batch was not writing image metadata.
added option to run batch on uploaded files, not just folder.
