### ISSUE TITLE
[Extension]: sd-webui-regional-prompter unconditionally active

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#1744]
### Issue Description

As the subject says, regardless of whether the checkbox is active or not, this extension is always active, which means that any BREAK in the prompt will be hijacked, creating very strange results in outputs. This is a recent regression introduced by the extension, I think.

### Version Platform Description

Ubuntu 20.04, Ubuntu 22.04. Tested with a fresh checkout in a new VM to make sure existing configuration wasn't getting in the way.
SD.Next latest master as of 2023-07-18 (debec28be6530542a71c1812ec9d333c94e50420).

### URL link of the extension

https://github.com/hako-mikan/sd-webui-regional-prompter

### URL link of the issue reported in the extension repository

https://github.com/hako-mikan/sd-webui-regional-prompter/issues/171

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by Davikar** [comment]
This was fixed today:
https://github.com/hako-mikan/sd-webui-regional-prompter/issues/171#issuecomment-1642285081
