### ISSUE TITLE
[Issue]: API Docs not working

### ISSUE THREAD

**Issue by DevilsCrypto** [vladmandic/automatic#1748]
### Issue Description

I have waited some releases, but i can't get the API docs working. Did a clean install several times including fresh virtual environments, but after starting the `/docs` url shows an error: `Internal Server Error /openapi.json`. When the docs where default enabled before the `--docs` argument they worked.

Automatic has been started as follows:
`./webui.sh --listen --models-dir ../../models --port 8888 --allow-code --insecure --docs`

![error_docs](https://github.com/vladmandic/automatic/assets/95778834/172a5eeb-2140-49e6-b746-11ea726213bc)

### Version Platform Description

Using Ubuntu 20.04.6 LTS on LambdaLabs

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i just tried with just `--docs` and with full list of args i cannot reproduce, `/docs` url is loading fine

**Comment by DevilsCrypto** [comment]
Thanks for the fast response, it looks like it's being cause by some script that adds api endpoints. Will check in there whats causing the exact issue. Thanks for the fast reaction!!

**Comment by vladmandic** [comment]
scripts/extensions are allowed to add api endpoints and that works if done correctly. i wonder what that extension is doing that its breaking core functionality.
