### ISSUE TITLE
[Feature]: Could there be a ComfyUI extension?

### ISSUE THREAD

**Issue by ninjasaid2k** [vladmandic/automatic#1761]
### Feature description

Could there be a ComfyUI extension like there was for Automatic1111? https://github.com/ModelSurge/sd-webui-comfyui 

### Version Platform Description

Windows 10
Chrome/Edge

**Comment by vladmandic** [comment]
As far as a i know, ComfyUI works on SD.Next.

**Comment by zethfoxster** [comment]
it does indeed work just fine
