### ISSUE TITLE
[Issue]: ScuNET not listed as available

### ISSUE THREAD

**Issue by 5KilosOfCheese** [vladmandic/automatic#177]
### Issue Description

ScuNET is present in the files along with the code, as it is inbuilt extension from Automatic1111 repo. However it is not available within the UI itself. It is not listed in: 

- filepaths, 
- process upscalers, 
- text2img upscalers, 
- img2img upscalers.

Considering that the upscalers

- LDSR,
- SwinIR
- Scunet

are listed as inbuilt-extensions are controlled from within the extensions tab, It would be expected that they would exhibit the same behavior. In this case

- LDSR
- SwinIR

can be enabled and disabled from the extensions tab. However **ScuNet** can not. I even tried to force **ScuNET** to appear by adjusting ui-configs to force it as the default, however the UI defaults to **SwinIR_4x** instead even if not defined as the default. Everything needed to have **ScuNET** to appear however seems to be present in the files. 

Expected behavior: 

- ScuNET available as upscaler.
- ScuNET extensions controllable from Extensions tab same way as SwinIR and LDSR.

![kuva](https://user-images.githubusercontent.com/117771081/232326239-b4704a97-bf34-4b34-ad30-876413baaf2e.png)
Picture 1. Extensions tab.

![kuva](https://user-images.githubusercontent.com/117771081/232326276-ca0e4c48-7493-4184-9062-4b2d3d37f557.png)
Picture 2. Process tab.

![kuva](https://user-images.githubusercontent.com/117771081/232326332-6ac8f970-7a1e-4454-9200-a9f816b11295.png)
Picture 3. Settings - System Paths

![kuva](https://user-images.githubusercontent.com/117771081/232326595-12dad97d-dcf4-4622-ab4e-dade7b71ab50.png)
Picture 4. System Info tab extension.

### Version Platform Description

updated: 2023-04-16
hash: b7e4b041

**Comment by vladmandic** [comment]
known issue in a1111: <https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6765> <https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8364>
i'll get to it, but placing on backlog for now.

**Comment by 5KilosOfCheese** [comment]
> known issue in a1111: [AUTOMATIC1111#6765](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6765) [AUTOMATIC1111#8364](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/8364) i'll get to it, but placing on backlog for now.

From the 6765 you linked the solution https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/6765#issuecomment-1383289673 seems to be a functional workaround. 

This for refrence to those who may also come across this.

**Comment by vladmandic** [comment]
its functional, but its fundamentally wrong. there is something wrong with scunet registration - it actually gets loaded correctly and while other extensions are loading, it unloads itself. moving it to `modules` basically makes it load last, so it stays.

**Comment by 5KilosOfCheese** [comment]
> its functional, but its fundamentally wrong. there is something wrong with scunet registration - it actually gets loaded correctly and while other extensions are loading, it unloads itself. moving it to `modules` basically makes it load last, so it stays.

Well... It is functional as in "_people can use it_" I myself have no idea on how to actually debug this sort issue. I'm a mechanical engineer, I hit things with hammers until they start working correctly. :)

**Comment by vladmandic** [comment]
its fixed now, i've added option for scripts & extensions to set loading priority and by setting ScuNET to load last, it just works.
