### ISSUE TITLE
[Issue]: 'Settings - UI defaults' doesn't work.

### ISSUE THREAD

**Issue by blueball81** [vladmandic/automatic#1770]
### Issue Description

Recently, it seems that the function to save UI defaults doesn't work. 
In Settings, User Interface Defaults, either 'View changes' or 'Set new defaults' does not work without any log or debug message.
Only 'Restore system defaults' works, that delete the ui-config.json file in the data-dir. 

### Version Platform Description

ff445566, windows 11, chrome

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i cannt reproduce, need more information. so you change something in ui, then click on view changes and what happens?
even if there are no changes, it should say that.

**Comment by ppkppk8520** [comment]
same issue.
i found my ui-config.json was empty(more precisely it contained only "{}") and when i clicked 'Restore system defaults' button, it removed ui-config.json file.

**Comment by vladmandic** [comment]
@ppkppk8520 yes, and what is the problem? how ui-config.json works now that it saves only differences between app defaults and user settings. so if you don't have any changes, it will be empty. it no longer saves everything - that is by design.

**Comment by blueball81** [comment]
> i cannt reproduce, need more information. so you change something in ui, then click on view changes and what happens? even if there are no changes, it should say that.

Hi, @vladmandic

**Comment by blueball81** [comment]
I just saw a closed issue of the following.
https://github.com/vladmandic/automatic/issues/1575#issuecomment-1622021702
After deleting config.json, the function works. I do not know what was the problem, but it works now, anyways.

**Comment by blueball81** [comment]
This seems to related to this

**Comment by blueball81** [comment]
This seems to be related to the following issue that happens when there are hidden tabs in the UI. 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10772#issue-1729236110
