### ISSUE TITLE
[Issue]: hires_fix checkbox is missing

### ISSUE THREAD

**Issue by natuttag** [vladmandic/automatic#1772]
### Issue Description

After updating from older version to new, hires_fix check box is missing. I tried new installation and problem is still here.
![Snímka](https://github.com/vladmandic/automatic/assets/124516941/476e5d61-069c-42de-9034-c8595813520d)
![Snímka2](https://github.com/vladmandic/automatic/assets/124516941/5cc9122f-fc9a-470a-93dd-c6f8c2166d8c)

### Version Platform Description

app: SD.next
updated: 2023-07-19
hash: e002652a
url: https://github.com/vladmandic/automatic/tree/master
arch: AMD64
cpu: AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.10.6
firefox 115.0.2 64-bit

Starting SD.Next
Python 3.10.6 on Windows
Version: ff445566 Thu Jul 20 09:59:57 2023 -0400
Latest published version: db1976b3cf38d76261177d590f54d69360f5d675 2023-07-20T19:28:09Z
nVidia CUDA toolkit detected

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by Xerdunits** [comment]
It's not missing, it's under 'second pass' now

**Comment by natuttag** [comment]
> It's not missing, it's under 'second pass' now

thank you

**Comment by ronbere** [comment]
> It's not missing, it's under 'second pass' now

I was on vacation, so many changes!
So we have to make a second pass to use hires?

**Comment by vladmandic** [comment]
Hires was always a second pass, now it's just actually called that.
