### ISSUE TITLE
[Feature]: Collapsible Settings

### ISSUE THREAD

**Issue by RancidPandemic** [vladmandic/automatic#1775]
### Feature description

With the increase of options being added, along with the move of HiResFix under Second Pass, the UI has become very, very cumbersome when attempting to use it from mobile. The sheer amount of different options makes it difficult to maneuver down a page after sending a generation, and that must be done to get to the image, which is at the bottom of the page.

I suggest the basic settings and Second Pass settings be made collapsible like the Scripts block so that we can hide the options when we do not need to change them. This would go a long way in improving the use on mobile devices.

**Comment by vladmandic** [comment]
done.
