### ISSUE TITLE
[Issue]: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by zavicode** [vladmandic/automatic#1776]
### Issue Description

have an issue img2img batch

controlnet batch mode
01:59:49-154776 ERROR    Exception: object of type 'NoneType' has no len()      
01:59:49-156303 ERROR    Arguments: args=('task(tar37rdq334spbv)', 5, '1boy,    
                         ChopperCzar, ArmPoint, hands not holding anything,     
                         (brown fur, animal ears, antlers, hooves, black eyes,  
                         Big Muscles, big biceps, big forearms, snout, fingers, 
                         fist), (hat, pink headwear, shorts, full body),        
                         (masterpiece:1.2), hires, ultra-high resolution, 8K,   
                         high quality, (sharp focus:1.2), clean, crisp,         
                         cinematic, <lora:Chopper-v1:1>', 'Negative prompt:     
                         (hooved fingers:1.6), (low quality, worst quality:1.4),
                         bad composition, (human, smooth skin:1.4), (extra      
                         antlers:1.6), (bad antlers:1.6), (extra ears:1.6),     
                         bad-image-v2-39000, bad_prompt_version2,               
                         badhandsv5-neg', [], None, None, None, None, None,     
                         None, None, 30, 11, 0, 4, 0, 1, False, False, 1, 1, 7, 
                         1.5, 0.7, 0, 1, 2, 0.75, 572238950.0, -1.0, 0, 0, 0, 0,
                         960, 540, 1, 2, 0, 32, 0, None,                        
                         '/content/drive/MyDrive/1', '/content/drive/MyDrive/2',
                         '', [], 0, False, 'MultiDiffusion', False, True, 1024, 
                         1024, 96, 96, 48, 4, 'None', 2, False, 10, 1, 1, 64,   
                         False, False, False, False, False, 0.4, 0.4, 0.2, 0.2, 
                         '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 0.2, 
                         0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 0.4, 
                         0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 0.4, 
                         0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0, False, 
                         0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2, -1.0,   
                         False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 0.2,  
                         -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '', 'Background', 
                         0.2, -1.0, False, 0.4, 0.4, 0.2, 0.2, '', '',          
                         'Background', 0.2, -1.0, False, 2048, 128, True, True, 
                         True, False, False, 7, 100, 'Constant', 0, 'Constant', 
                         0, 4,                                                  
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNet
                         Unit object at 0x7fe36453e1d0>,                        
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNet
                         Unit object at 0x7fe3658a47f0>,                        
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNet
                         Unit object at 0x7fe363e579a0>,                        
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNet
                         Unit object at 0x7fe3658a7c40>,                        
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNet
                         Unit object at 0x7fe3658a6590>,                        
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNet
                         Unit object at 0x7fe363e57d30>,                        
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNet
                         Unit object at 0x7fe364857b20>,                        
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNet
                         Unit object at 0x7fe3658a5e70>,                        
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNet
                         Unit object at 0x7fe3648572e0>,                        
                         <scripts.controlnet_ui.controlnet_ui_group.UiControlNet
                         Unit object at 0x7fe364855030>, '<ul>\n<li><code>CFG   
                         Scale</code> should be 2 or lower.</li>\n</ul>\n',     
                         True, True, '', '', True, 50, True, 1, 0, False, 4,    
                         0.5, 'Linear', 'None', '<p                             
                         style="margin-bottom:0.75em">Recommended settings:     
                         Sampling Steps: 80-100, Sampler: Euler a, Denoising    
                         strength: 0.8</p>', 128, 8, ['left', 'right', 'up',    
                         'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up',   
                         'down'], False, False, 'positive', 'comma', 0, False,  
                         False, '', '<p style="margin-bottom:0.75em">Will       
                         upscale the image by the selected scale factor; use    
                         width and height sliders to set tile size</p>', 64, 0, 
                         2, 0, '', [], 0, '', [], 0, '', [], True, False, False,
                         False, 0, False, None, None, False, None, None, False, 
                         None, None, False, None, None, False, None, None,      
                         False, None, None, False, None, None, False, None,     
                         None, False, None, None, False, None, None, False, 50) 
                         kwargs={}                                              
01:59:49-169827 ERROR    gradio call: TypeError                                 
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/automatic/modules/call_queue.py:34 in f                             │
│                                                                              │
│    33 │   │   │   try:                                                       │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                            │
│    35 │   │   │   │   progress.record_results(id_task, res)                  │
│                                                                              │
│ /content/automatic/modules/img2img.py:183 in img2img                         │
│                                                                              │
│   182 │   if is_batch:                                                       │
│ ❱ 183 │   │   process_batch(p, img2img_batch_files, img2img_batch_input_dir, │
│   184 │   │   processed = processing.Processed(p, [], p.seed, "")            │
│                                                                              │
│ /content/automatic/extensions-builtin/sd-webui-controlnet/scripts/batch_hija │
│ ck.py:30 in img2img_process_batch_hijack                                     │
│                                                                              │
│    29 │   │   try:                                                           │
│ ❱  30 │   │   │   return getattr(img2img, '__controlnet_original_process_bat │
│    31 │   │   finally:                                                       │
│                                                                              │
│ /content/automatic/modules/img2img.py:14 in process_batch                    │
│                                                                              │
│    13 │   processing.fix_seed(p)                                             │
│ ❱  14 │   if len(input_files) > 0:                                           │
│    15 │   │   image_files = [f.name for f in input_files]                    │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: object of type 'NoneType' has no len()

### Version Platform Description

Starting SD.Next                                       
01:41:49-026646 INFO     Python 3.10.6 on Linux                                 
01:41:49-049113 INFO     Version: 0a083c24 Tue Jul 18 20:43:30 2023 -0400       
01:41:49-522295 INFO     Latest published version:                              
                         db1976b3cf38d76261177d590f54d69360f5d675               
                         2023-07-20T19:28:09Z                                   
01:41:49-524244 INFO     nVidia CUDA toolkit detected  

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
if its a controlnet issue, refile using extension template. and describe the issue, don't just dump the log. "have an issue" is not a description.
