### ISSUE TITLE
[Extension]: controlnet batch mode TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by zavicode** [vladmandic/automatic#1778]
### Issue Description

when I run img2img batch mode with controlnet extension, it shows error TypeError: object of type 'NoneType' has no len()

03:20:23-427477 INFO     ControlNet v1.1.233                                    
ControlNet v1.1.233
ControlNet preprocessor location: /content/automatic/extensions-builtin/sd-webui-controlnet/annotator/downloads
03:20:23-816888 INFO     ControlNet v1.1.233                                    
ControlNet v1.1.233

![Tanpa judul2](https://github.com/vladmandic/automatic/assets/101306047/b0e551d0-d530-4523-bdc4-d9d619adf0f6)

### Version Platform Description

Starting SD.Next                                       
Python 3.10.6 on Linux                                 
Version: 0a083c24 Tue Jul 18 20:43:30 2023 -0400       
nVidia CUDA toolkit detected 

### URL link of the extension

https://github.com/Mikubill/sd-webui-controlnet

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fix in dev, will publish later today.
