### ISSUE TITLE
[Feature]: ROOP inside main install

### ISSUE THREAD

**Issue by VitaliyAT** [vladmandic/automatic#1780]
### Feature description

Could you include ROOP inside main installation?

Right now it's default and main instrument for a lot of people. It would be better if we will get ROOP from box.

Plus, we still have problems with ROOP installation - wrote it in independent theme: [#1779](https://github.com/vladmandic/automatic/issues/1779#issue-1815132495)

**Comment by TeutonJon78** [comment]
ROOP requires the installation of separate external programs, so it's probably not likely candidate for inclusion as a default extension.

**Comment by vladmandic** [comment]
correct. i cannot introduce binary dependencies if they do not include pre-built wheels for all platforms.
