### ISSUE TITLE
[Issue]: secondary sampler ignored for hires fix

### ISSUE THREAD

**Issue by MDMAchine** [vladmandic/automatic#1782]
### Feature description

I am writing to request the reintroduction of the "force_latent_sampler" option, which appears to have been removed or is currently not functional.

I have been relying on the "force_latent_sampler" option to fine-tune and optimize the latent sampling process. However, I noticed that in the latest version, this option is no longer available in the settings. I initially assumed that the new Secondary Sampler might have taken its place, but after conducting tests with the debug console, I found that the Secondary Sampler does not appear to affect the force latent sampler setting.

Presently, the only workaround I've discovered to modify the "force_latent_sampler" setting is by manually editing line 155 in the config.json file, which requires restarting SDNext for the changes to take effect. This process is cumbersome and not conducive to a seamless user experience.

This feature has been instrumental in tailoring the sampling process to specific use cases. I am working in the Original backend of the SD pipeline. 

Thank you.

### Version Platform Description

**Platform:**
arch: AMD64
cpu: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.6

**Version:**
app: SD.next
updated: 2023-07-20
hash: db1976b3

**Comment by vladmandic** [comment]
fixed in dev, will publish later today.

**Comment by MDMAchine** [comment]
I was about to start putting together the information for you. Looks like you figured it out before I had the chance!

Many thanks, your promptness is always appreciated!
