### ISSUE TITLE
[Issue]: Minor Conditional Extra Networks UI Issue 

### ISSUE THREAD

**Issue by i-liek-katz** [vladmandic/automatic#1784]
### Issue Description

If you have a description.txt with an unclosed < followed by an alpha character (so, like <lora or <lyco), it will mess up the UI depending on where the lora/lyco file name is ordered. These are in a folder and using the folder filter. In this example, choccymilk has the offending characters. If you have a closed one with certain alpha characters (tested a and b, so `<a> <b>`), it gets put to the side and anything after the offending characters will be blue when mouse is over.
example 1 has an unclosed "<lyco:" with a higher filename forces single column, should be at top but a bottom overlapping), example 2 has an unclosed "<lyco:" with a lower filename (added zz to the filename front, you can what happens), example 3 has <a> in the file (forces single column for the rest of the folder). UI seems fine closed with certain (most?) characters.
![image](https://github.com/vladmandic/automatic/assets/75770893/ce4e9ef3-97f0-419a-a506-8cffd497e3b1)
![image](https://github.com/vladmandic/automatic/assets/75770893/313a1c45-e22d-4d16-9d5f-feccd34090da)
![image](https://github.com/vladmandic/automatic/assets/75770893/c1e111ce-92d5-4d80-ab31-8169d949d9b8)

### Version Platform Description

Windows 10, RTX 3060, Firefox

Using VENV: G:\automatic\venv
04:45:08-547956 INFO     Starting SD.Next
04:45:08-551957 INFO     Python 3.10.6 on Windows
04:45:08-585965 INFO     Version: 8e301442 Fri Jul 21 00:12:22 2023 -0400
04:45:08-815059 INFO     nVidia CUDA toolkit detected
04:45:08-897212 WARNING  Modified files: ['modules/lora', 'modules/lycoris']
04:45:08-938221 INFO     Disabled extensions: []
04:45:08-940222 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
04:45:08-948223 INFO     No changes detected: Quick launch active
04:45:08-949224 INFO     Verifying requirements
04:45:08-960226 INFO     Disabled extensions: []
04:45:08-962226 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
04:45:08-969228 INFO     Running in safe mode without user extensions
04:45:08-975230 INFO     Extension preload: 0.0s G:\automatic\extensions-builtin
04:45:08-998235 INFO     Server arguments: ['--safe']

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed in dev, will publish later today.
