### ISSUE TITLE
[Issue]: Hypernetworks - when clicking on a hyper network it doesnt add to the prompt

### ISSUE THREAD

**Issue by SOELexicon** [vladmandic/automatic#1788]
### Issue Description

when clicking any hypernetworks it seems to give an error to the console in inspector.

?__theme=dark:1 Uncaught ReferenceError: shared is not defined
    at HTMLDivElement.onclick (?__theme=dark:1:48)
onclick @ ?__theme=dark:1
2?__theme=dark:1 Uncaught ReferenceError: shared is not defined
    at HTMLDivElement.onclick (?__theme=dark:1:47)
onclick @ ?__theme=dark:1

### Version Platform Description

Chrome:

18:00:02-149706 INFO     Starting SD.Next
18:00:02-152212 INFO     Python 3.10.11 on Windows
18:00:02-184262 INFO     Version: 67e22586 Fri Jul 21 10:42:05 2023 -0400

### Relevant log output

```shell
no errors in console log
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
i need a bit more on that browser inspector console log, this is not enough to trace it.

**Comment by Psychloor** [comment]
just here to say i get the same. when i click on a hypernetwork it doesn't add it to prompt

**Comment by vladmandic** [comment]
and i still need more info!
