### ISSUE TITLE
[Issue]: UI - Generate and Enqueue buttons are slightly differently sized.

### ISSUE THREAD

**Issue by Synitare** [vladmandic/automatic#1789]
### Issue Description

The change to the generate/enqueue buttons on the main From Text and From Image tabs are slightly different sizes. 

As a tack-on to this, could the generate button be changed to fill the space in the event that the agent scheduler is disabled? Currently there's just a big empty void. 

Here's a screenshot of the buttons after restarting with --safe to make sure it wasn't an extension issue:

![firefox_6b80NwRpgO](https://github.com/vladmandic/automatic/assets/3077398/127b17dc-8335-49cd-9fcb-bf6d94f66e2c)

### Version Platform Description

12:20:51-198054 INFO     Starting SD.Next
12:20:51-202055 INFO     Python 3.10.11 on Windows
12:20:51-253054 INFO     Version: 67e22586 Fri Jul 21 10:42:05 2023 -0400
12:20:51-726068 INFO     nVidia CUDA toolkit detected
12:20:51-834066 WARNING  Modified files: ['scripts/prompt_gallery.py']
12:20:51-884066 INFO     Disabled extensions: ['sd-webui-agent-scheduler', 'sd-webui-lora-block-weight']
12:20:51-886067 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
12:20:51-894067 INFO     No changes detected: Quick launch active
12:20:51-895067 INFO     Verifying requirements
12:20:51-910066 INFO     Disabled extensions: ['sd-webui-agent-scheduler', 'sd-webui-lora-block-weight']
12:20:51-912068 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
12:20:51-918065 INFO     Running in safe mode without user extensions

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
i'll fix height asap. regarding width, i don't see how to do that easily in css without extra if/then checks in js which i don't want to add just for this case. agent scheduler is built-in extension, if you disable it, you'll be missing a button.
