### ISSUE TITLE
[Issue]: installation issue

### ISSUE THREAD

**Issue by gsgoldma** [vladmandic/automatic#179]
### Issue Description

Please fill this form with as much information as possiblevenv "D:\automatic\venv\Scripts\Python.exe"
11:49:43-402760 INFO     Python 3.10.9 on Windows
11:49:43-455759 INFO     Running setup
11:49:43-496761 INFO     Version: 332b8b83 Thu Apr 13 13:13:11 2023 -0400
11:49:43-927957 INFO     Latest available version: b7e4b0414a1ad9cf9d4b8010a7b48cbc55249533 2023-04-16T14:01:28Z
11:49:43-937953 INFO     Updating Wiki
11:49:45-514842 INFO     Installing requirements
11:49:46-035845 INFO     Installing packages
11:49:46-037844 INFO     Installing repositories
11:49:46-210843 INFO     Installing submodules
11:49:48-021885 INFO     Updating submodules
11:50:00-051437 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
11:50:01-841400 ERROR    Error running git with args: -C "D:\automatic\extensions-builtin\a1111-sd-webui-lycoris" pull
                         --rebase --autostash
11:50:12-991584 ERROR    Error running git with args: -C "D:\automatic\extensions-builtin\LDSR" pull --rebase
                         --autostash
11:50:14-807315 ERROR    Error running git with args: -C "D:\automatic\extensions-builtin\Lora" pull --rebase
                         --autostash
11:50:16-552214 ERROR    Error running git with args: -C
                         "D:\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111" pull --rebase
                         --autostash
11:50:18-276875 ERROR    Error running git with args: -C "D:\automatic\extensions-builtin\prompt-bracket-checker" pull
                         --rebase --autostash
11:50:19-898396 ERROR    Error running git with args: -C "D:\automatic\extensions-builtin\ScuNET" pull --rebase
                         --autostash
11:50:31-309834 ERROR    Error running git with args: -C "D:\automatic\extensions-builtin\SwinIR" pull --rebase
                         --autostash
11:50:31-358839 INFO     Extensions enabled: ['put extensions here.txt']
11:50:31-392833 ERROR    Error running git with args: -C "D:\automatic\extensions\put extensions here.txt" branch
11:50:31-394834 WARNING  Unknown branch for: D:\automatic\extensions\put extensions here.txt
11:50:31-428833 ERROR    Error running git with args: -C "D:\automatic\extensions\put extensions here.txt" pull
                         --rebase --autostash
11:50:31-463832 ERROR    Error running git with args: -C "D:\automatic\extensions\put extensions here.txt" branch
11:50:31-465833 WARNING  Setup complete with errors (10)
11:50:31-467832 INFO     Setting environment tuning

### Version Platform Description

windows 10

**Comment by vladmandic** [comment]
i'm not sure what you did, but this looks like a mashup of this repo and original a1111. for example, there is no path `extensions\put extensions here.txt` in this repo nor there ever was, but that exists in the original repo.

i suggest you do a clean clone/checkout to a separate folder.

**Comment by Alzucard** [comment]
I had this too and it was related to Extensions.

Did "git reset"
and then "git pull"
and fixed it.

**Comment by vladmandic** [comment]
closing due to lack of information. if user follows suggested steps and issue is still present, report here and i'll reopen it.
