### ISSUE TITLE
[Issue]: "Delete" button doesn't work on Windows

### ISSUE THREAD

**Issue by Targren** [vladmandic/automatic#1790]
### Issue Description

#1586 mentioned this and was marked as compelted, but that mentioned 2 problems, and this one is still occurring. Clicking the button clears the preview image from the UI, but the file itself isn't removed (nor the .txt sidecar, if enabled in the settings)

### Version Platform Description

14:07:48-612911 INFO     Starting SD.Next
14:07:48-615832 INFO     Python 3.10.6 on Windows
14:07:48-646005 INFO     Version: 67e22586 Fri Jul 21 10:42:05 2023 -0400
14:07:49-197973 INFO     nVidia CUDA toolkit detected

### Relevant log output

```shell
13:57:09-360709 ERROR    gradio call: TypeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ E:\SD.Next\automatic\modules\call_queue.py:58 in f                                                     │
│                                                                                                                     │
│    57 │   │   │   │   pr.enable()                                                                                   │
│ >  58 │   │   │   res = func(*args, **kwargs)                                                                       │
│    59 │   │   │   if res is None:                                                                                   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: delete_files() missing 1 required positional argument: 'index'
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
just fixed.

**Comment by Targren** [comment]
That was quick, thank you! But it still leaves the sidecar file behind.

**Comment by vladmandic** [comment]
fixed that as well ;)
