### ISSUE TITLE
[Issue]: Artifacts and banding on images w/ watermark enabled

### ISSUE THREAD

**Issue by MDMAchine** [vladmandic/automatic#1796]
### Issue Description

Edit: I apparently had watermark enabled, when I disabled it it appeared to go away!?

I noticed there is strange banding and artifacts on the images. At first I figured I never noticed it before and it was some kind of dithering, but upon comparing a new and older generations I can say these artifacts never happened before. I am saving these images as jpeg, so maybe theres an issue with the jpeg encoding quality?

Here is a closeup of an older image:
![Screenshot 2023-07-22 at 7 54 09 AM](https://github.com/vladmandic/automatic/assets/59008042/fa1c1231-8a30-42b3-9d7e-33b31320beb3)

And I regenerated the same image today and here is another closeup of that region:
![Screenshot 2023-07-22 at 7 54 29 AM](https://github.com/vladmandic/automatic/assets/59008042/1a15ac75-98e5-4610-9885-99cfbe342a11)

Upon closer inspection you can see "bands/blocks" in the black background.

And on images with skin and whatnot there are light pinkish bands all over. Here is an example on the right arm and stomach:
![00437-etherRealMix_21-1152x1536-Bhabhi AI Hot Saree Bra Panty navel 3D](https://github.com/vladmandic/automatic/assets/59008042/a9514ad5-7e35-4449-8e32-3454f80f4c90)

My workflow hasn't changed. I did a reinstall to see if that might help and made another generation of the same images and the banding has changed (less noticeable) but is still there. 

Also these images were hires upscaled, but I checked and it happens on images generated without the 2nd pass option enabled. I tried other VAE's, upscalers and various settings but nothing changed. Also my jpeg quality was always set to 85, I tried 100 and no difference. To the best of my knowledge this started happening about 1 or 2 days ago. 

I have also tested in safe mode and it still happens.

### Version Platform Description

SD.Next
Python 3.10.6 on Windows 11
Version: 511a8cbb Fri Jul 21 15:04:27 2023 -0400
Torch: 2.0.1+cu118 Autocast  half
device: NVIDIA GeForce RTX 3060 Ti (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8700
driver: 531.79

Brave Browser (MacOS)

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
what's changed is:
- yes, you can set watermark. its disabled by default. if watermark adds artifacts, don't use it, as simple as that.
- second pass now actually uses secondary sampler. that feature did not exist until a week ago, but it was actually ignored until yesterday. previously hires fix was using "force sampler" set in settings, that is now gone.

but other than that, not sure what do you want me to do here?

**Comment by MDMAchine** [comment]
Hi sorry if it was confusing. I don't want you to do anything. :)

I just left this up so that it was documented that the watermark feature adds artifacts in case anyone else comes across the phenomenon.

As always thank you for your effort!

**Comment by vladmandic** [comment]
sounds good! i was just wondering since i posted my question before you closed the issue :)
