### ISSUE TITLE
[Issue]: Cant launch because it complains all Ports are in use

### ISSUE THREAD

**Issue by TPPy** [vladmandic/automatic#1797]
### Issue Description

23:09:16-649230 INFO     Starting SD.Next
23:09:16-654232 INFO     Python 3.10.9 on Windows
23:09:16-715732 INFO     Version: e491813e Sat Jul 22 16:33:27 2023 -0400
23:09:17-116371 INFO     nVidia CUDA toolkit detected
23:09:17-263875 INFO     Verifying requirements
23:09:17-278372 INFO     Verifying packages
23:09:17-288374 INFO     Verifying repositories
23:09:20-347162 INFO     Verifying submodules
23:10:19-769429 INFO     Extensions enabled:

Error when launching (happened today after updating). Even when launching with --safe:

(venv) *********\Vlad1111\automatic>webui --safe
Using VENV: ****\Vlad1111\automatic\venv
23:18:54-922351 INFO     Starting SD.Next
23:18:54-927851 INFO     Python 3.10.9 on Windows
23:18:54-987352 INFO     Version: e491813e Sat Jul 22 16:33:27 2023 -0400
23:18:55-362737 INFO     nVidia CUDA toolkit detected
23:18:55-559970 INFO     Disabled extensions: []
23:18:55-562971 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
23:18:55-582970 INFO     No changes detected: Quick launch active
23:18:55-584970 INFO     Verifying requirements
23:18:55-599993 INFO     Disabled extensions: []
23:18:55-602473 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
23:18:55-621494 INFO     Running in safe mode without user extensions
23:18:55-631470 INFO     Extension preload: 0.0s **\Vlad1111\automatic\extensions-builtin
23:18:55-654993 INFO     Server arguments: ['--safe']
No module 'xformers'. Proceeding without it.
23:19:05-213019 INFO     Pipeline: Backend.ORIGINAL
23:19:06-063020 INFO     Libraries loaded
23:19:06-065519 INFO     Using data path: *******\Vlad1111\automatic
23:19:06-071019 INFO     Available VAEs: *******\Vlad1111\automatic\models\VAE 1
23:19:06-084019 INFO     Available models: *******\Vlad1111\automatic\models\Stable-diffusion 11
23:19:10-148493 INFO     ControlNet v1.1.233
ControlNet v1.1.233
ControlNet preprocessor location:*********\Vlad1111\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
23:19:10-361064 INFO     ControlNet v1.1.233
ControlNet v1.1.233
23:19:11-886486 INFO     No internet access detected, using default fonts
23:19:11-890986 ERROR    Theme download error accessing HuggingFace
23:19:11-892962 INFO     Loading UI theme: name=abidlabs/Lime style=Auto
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ **\Vlad1111\automatic\launch.py:192 in <module>                                                        │
│                                                                                                                     │
│   191                                                                                                               │
│ > 192     instance = start_server(immediate=True, server=None)                                                      │
│   193     while True:                                                                                               │
│                                                                                                                     │
│ **\Vlad1111\automatic\launch.py:144 in start_server                                                    │
│                                                                                                                     │
│   143         else:                                                                                                 │
│ > 144             server = server.webui(restart=not immediate)                                                      │
│   145     if args.profile:                                                                                          │
│                                                                                                                     │
│**\Vlad1111\automatic\webui.py:317 in webui                                                            │
│                                                                                                                     │
│   316     start_common()                                                                                            │
│ > 317     start_ui()                                                                                                │
│   318     modules.sd_models.write_metadata()                                                                        │
│                                                                                                                     │
│**\Vlad1111\automatic\webui.py:264 in start_ui                                                         │
│                                                                                                                     │
│   263     global local_url # pylint: disable=global-statement                                                       │
│ > 264     app, local_url, share_url = shared.demo.launch( # app is FastAPI(Starlette) instance                      │
│   265         share=cmd_opts.share,                                                                                 │
│                                                                                                                     │
│**\Vlad1111\automatic\venv\lib\site-packages\gradio\blocks.py:1745 in launch                           │
│                                                                                                                     │
│   1744         else:                                                                                                │
│ > 1745             server_name, server_port, local_url, app, server = networking.start_server(                      │
│   1746                 self,                                                                                        │
│                                                                                                                     │
│ **\Vlad1111\automatic\venv\lib\site-packages\gradio\networking.py:114 in start_server                  │
│                                                                                                                     │
│   113     if server_port is None:                                                                                   │
│ > 114         port = get_first_available_port(                                                                      │
│   115             INITIAL_PORT_VALUE, INITIAL_PORT_VALUE + TRY_NUM_PORTS                                            │
│                                                                                                                     │
│ **\Vlad1111\automatic\venv\lib\site-packages\gradio\networking.py:64 in get_first_available_port       │
│                                                                                                                     │
│    63             pass                                                                                              │
│ >  64     raise OSError(                                                                                            │
│    65         f"All ports from {initial} to {final - 1} are in use. Please close a port."                           │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
OSError: All ports from 7860 to 7959 are in use. Please close a port.

### Version Platform Description

Windows 10, running with Backend Original.
Checked netstat -ano | findstr :7860 and nothing is using any of the ports in question.

### Relevant log output

```shell
No relevant outputs from log.
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
nothing is using ports, but there is no networking initialized at all.
windows 10 does not initialize network if there is no network connectivity. if you want to run completely offline, you might need to at least install a loopback network adapter so windows initializes a dummy network and app can then use it.
