### ISSUE TITLE
[Issue]: All ports in use after restarting

### ISSUE THREAD

**Issue by horribleCodes** [vladmandic/automatic#1798]
### Issue Description

Since today, whenever I launch the webui, I encounter the following error:
```
OSError: All ports from 7860 to 7959 are in use. Please close a port.
```
According to netstat, only the port 7860 is open:
```
  TCP    0.0.0.0:5357           0.0.0.0:0              LISTENING       4
  TCP    0.0.0.0:7680           0.0.0.0:0              LISTENING       9740
  TCP    0.0.0.0:27036          0.0.0.0:0              LISTENING       13520
```
I tried closing the port with `taskkill`, but the system told me I'd have to include a force-flag, and I wanted to avoid messing something critical. I also tried restarting my PC, but that had no effect.
I've been using the WebUI for months without problem. There's two things that were different with the last time I ran the WebUI:

The latest commit had the new interface (I don't remember which one it was), and I did notice that the console only listed the URL `0.0.0.0:7680`, whereas before it always noted that one and `192.168.1.127:7680`. I believe there also wasn't an https connection anymore, though I'm not sure about that one.
The other is that I've added the extension [Stable Diffusion webui Infinite Image Browsing](https://github.com/zanllp/sd-webui-infinite-image-browsing). I'm not sure if that's it, though - removing it from the extension folder had no effect and none of the issues in that repo mention anything about ports.

### Version Platform Description

Commit: e491813eb8d17d38477490800e9baf42ddfdc896
OS: Windows 11 Home 22621.1992

### Relevant log output

```shell
PS C:\Users\source\repos\automatic> .\webui.bat --listen
Using VENV: C:\Users\source\repos\automatic\venv
23:44:53-997247 INFO     Starting SD.Next
23:44:54-000257 INFO     Python 3.10.7 on Windows
23:44:54-031256 INFO     Version: e491813e Sat Jul 22 16:33:27 2023 -0400
23:44:54-429842 INFO     nVidia CUDA toolkit detected
23:44:54-545355 INFO     Disabled extensions: []
23:44:54-546355 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
23:44:54-553355 INFO     Enabled extensions: ['a1111-sd-webui-tagcomplete', 'sd-webui-infinite-image-browsing']
23:44:54-555355 INFO     No changes detected: Quick launch active
23:44:54-556354 INFO     Verifying requirements
23:44:54-566355 INFO     Disabled extensions: []
23:44:54-567355 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
23:44:54-573355 INFO     Enabled extensions: ['a1111-sd-webui-tagcomplete', 'sd-webui-infinite-image-browsing']
23:44:54-578359 INFO     Extension preload: 0.0s C:\Users\source\repos\automatic\extensions-builtin
23:44:54-579359 INFO     Extension preload: 0.0s C:\Users\source\repos\automatic\extensions
23:44:54-596447 INFO     Server arguments: ['--listen']
No module 'xformers'. Proceeding without it.
23:45:00-891669 INFO     Pipeline: Backend.ORIGINAL
23:45:01-426190 INFO     Libraries loaded
23:45:01-427735 INFO     Using data path: C:\Users\source\repos\automatic
23:45:01-430734 INFO     Available VAEs: C:\models\image\VAE 5
23:45:01-446735 INFO     Available models: C:\models\image\Stable-diffusion 6
23:45:03-429839 INFO     ControlNet v1.1.233
ControlNet v1.1.233
ControlNet preprocessor location: C:\Users\source\repos\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
23:45:03-539214 INFO     ControlNet v1.1.233
ControlNet v1.1.233
Tag Autocomplete: Could not locate model-keyword extension, LORA/LYCO trigger word completion will be unavailable.
23:45:04-652378 INFO     No internet access detected, using default fonts
23:45:04-654378 INFO     Loading UI theme: name=gradio/default style=Auto
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\source\repos\automatic\launch.py:192 in <module>                                                            │
│                                                                                                                      │
│   191                                                                                                                │
│ ❱ 192     instance = start_server(immediate=True, server=None)                                                       │
│   193     while True:                                                                                                │
│                                                                                                                      │
│ C:\Users\source\repos\automatic\launch.py:144 in start_server                                                        │
│                                                                                                                      │
│   143         else:                                                                                                  │
│ ❱ 144             server = server.webui(restart=not immediate)                                                       │
│   145     if args.profile:                                                                                           │
│                                                                                                                      │
│ C:\Users\source\repos\automatic\webui.py:317 in webui                                                                │
│                                                                                                                      │
│   316     start_common()                                                                                             │
│ ❱ 317     start_ui()                                                                                                 │
│   318     modules.sd_models.write_metadata()                                                                         │
│                                                                                                                      │
│ C:\Users\source\repos\automatic\webui.py:264 in start_ui                                                             │
│                                                                                                                      │
│   263     global local_url # pylint: disable=global-statement                                                        │
│ ❱ 264     app, local_url, share_url = shared.demo.launch( # app is FastAPI(Starlette) instance                       │
│   265         share=cmd_opts.share,                                                                                  │
│                                                                                                                      │
│ C:\Users\source\repos\automatic\venv\lib\site-packages\gradio\blocks.py:1745 in launch                               │
│                                                                                                                      │
│   1744         else:                                                                                                 │
│ ❱ 1745             server_name, server_port, local_url, app, server = networking.start_server(                       │
│   1746                 self,                                                                                         │
│                                                                                                                      │
│ C:\Users\source\repos\automatic\venv\lib\site-packages\gradio\networking.py:114 in start_server                      │
│                                                                                                                      │
│   113     if server_port is None:                                                                                    │
│ ❱ 114         port = get_first_available_port(                                                                       │
│   115             INITIAL_PORT_VALUE, INITIAL_PORT_VALUE + TRY_NUM_PORTS                                             │
│                                                                                                                      │
│ C:\Users\source\repos\automatic\venv\lib\site-packages\gradio\networking.py:64 in get_first_available_port           │
│                                                                                                                      │
│    63             pass                                                                                               │
│ ❱  64     raise OSError(                                                                                             │
│    65         f"All ports from {initial} to {final - 1} are in use. Please close a port."                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
OSError: All ports from 7860 to 7959 are in use. Please close a port.
Press any key to continue . . .
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by horribleCodes** [comment]
Update: I tried changing the initial port index to `3000`, but I got the same error. However, this time netstat lists no ports from 3000 to 3099.
It looks like the error seems to be independent from the status of the ports.

**Comment by vladmandic** [comment]
there were no recent changes in this part of the code.
and in this case, it doesn't seem that ports are in use, it seems that either app does not have permission to use them or networking is not initialized at all.

what is the output if `ipconfig /all`?

**Comment by horribleCodes** [comment]
I haven't changed my network settings at all, and experienced no other network issues either.
Here is the result from `ipconfig /all` - I've removed all information which may or may not be used to identify my PC.
```
Windows IP Configuration

   Host Name . . . . . . . . . . . . : PC
   Primary Dns Suffix  . . . . . . . :
   Node Type . . . . . . . . . . . . : Hybrid
   IP Routing Enabled. . . . . . . . : No
   WINS Proxy Enabled. . . . . . . . : No
   DNS Suffix Search List. . . . . . : fritz.box

Unknown adapter Tailscale:

   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : Tailscale Tunnel
   Physical Address. . . . . . . . . :
   DHCP Enabled. . . . . . . . . . . : No
   Autoconfiguration Enabled . . . . : Yes
   IPv6 Address. . . . . . . . . . . : XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX:XXXX(Preferred)
   Link-local IPv6 Address . . . . . : XXXX::XXXX:XXXX:XXXX%6(Preferred)
   IPv4 Address. . . . . . . . . . . : XXX.XXX.XXX.XXX(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.255
   Default Gateway . . . . . . . . . :
   NetBIOS over Tcpip. . . . . . . . : Disabled

Ethernet adapter Ethernet:

   Connection-specific DNS Suffix  . : fritz.box
   Description . . . . . . . . . . . : Killer 2.5 Gigabit Ethernet Controller
   Physical Address. . . . . . . . . : XX-XX-XX-XX-XX-XX
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
   Link-local IPv6 Address . . . . . : XXXX::XXXX:XXXX:XXXX%9(Preferred)
   IPv4 Address. . . . . . . . . . . : XXX.XXX.XXX.XXX(Preferred)
   Subnet Mask . . . . . . . . . . . : 255.255.255.0
   Lease Obtained. . . . . . . . . . : Saturday, 22 July 2023 23:19:24
   Lease Expires . . . . . . . . . . : Wednesday, 2 August 2023 00:11:22
   Default Gateway . . . . . . . . . : 192.168.178.1
   DHCP Server . . . . . . . . . . . : 192.168.178.1
   DHCPv6 IAID . . . . . . . . . . . : XXXXXXXX
   DHCPv6 Client DUID. . . . . . . . : XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX-XX
   DNS Servers . . . . . . . . . . . : 192.168.178.1
   NetBIOS over Tcpip. . . . . . . . : Enabled
```

**Comment by Felsync** [comment]
Having the same issue, started today  with --upgrade arg (yesterday there were no issues) and got the 2 errors. Then launching it without --upgrade just throws out ports in use without any other errors. I did do a fresh clone and it launched completely fine while the old clone still says ports are in use. Also installed Infinite Image Browsing extension on the new clone and it doesn't seem to be the cause. 

The output I get when launching is the exact same as @horribleCodes . 


### --upgrade output snippet
```
2023-07-22 21:20:16,881 | sd | INFO | installer | Updating main repository
2023-07-22 21:20:17,468 | sd | ERROR | installer | Error running git: . / pull --autostash --rebase --force
2023-07-22 21:20:17,469 | sd | DEBUG | installer | Git output: fatal: unable to access 'https://github.com/vladmandic/automatic/': Recv failure: Connection was reset
2023-07-22 21:20:17,492 | sd | INFO | installer | Upgraded to version: 511a8cbb Fri Jul 21 15:04:27 2023 -0400
2023-07-22 21:20:17,493 | sd | DEBUG | installer | Setting environment tuning
2023-07-22 21:20:17,493 | sd | DEBUG | installer | Torch overrides: cuda=False rocm=False ipex=False diml=False
2023-07-22 21:20:17,493 | sd | DEBUG | installer | Torch allowed: cuda=True rocm=True ipex=True diml=True
2023-07-22 21:20:17,494 | sd | INFO | installer | nVidia CUDA toolkit detected
2023-07-22 21:20:17,556 | sd | INFO | installer | Verifying requirements
2023-07-22 21:20:17,571 | sd | INFO | installer | Verifying packages
2023-07-22 21:20:17,572 | sd | INFO | installer | Verifying repositories
2023-07-22 21:20:17,613 | sd | DEBUG | installer | Submodule: C:\Users\Fel\Desktop\automatic\repositories\stable-diffusion-stability-ai / main
2023-07-22 21:20:18,169 | sd | DEBUG | installer | Submodule: C:\Users\Fel\Desktop\automatic\repositories\taming-transformers / master
2023-07-22 21:20:18,717 | sd | DEBUG | installer | Submodule: C:\Users\Fel\Desktop\automatic\repositories\k-diffusion / master
2023-07-22 21:20:19,739 | sd | DEBUG | installer | Submodule: C:\Users\Fel\Desktop\automatic\repositories\BLIP / main
2023-07-22 21:20:20,273 | sd | INFO | installer | Verifying submodules
2023-07-22 21:20:22,833 | sd | DEBUG | installer | Submodule: extensions-builtin/a1111-sd-webui-lycoris / main
2023-07-22 21:20:23,351 | sd | DEBUG | installer | Submodule: extensions-builtin/clip-interrogator-ext / main
2023-07-22 21:20:23,882 | sd | DEBUG | installer | Submodule: extensions-builtin/multidiffusion-upscaler-for-automatic1111 / main
2023-07-22 21:20:24,602 | sd | DEBUG | installer | Submodule: extensions-builtin/sd-dynamic-thresholding / master
2023-07-22 21:20:24,762 | sd | ERROR | installer | Error running git: extensions-builtin/sd-dynamic-thresholding / pull origin master --autostash --rebase --force
2023-07-22 21:20:24,763 | sd | DEBUG | installer | Git output: fatal: unable to access 'https://github.com/mcmonkeyprojects/sd-dynamic-thresholding/': Recv failure: Connection was reset
2023-07-22 21:20:24,783 | sd | DEBUG | installer | Submodule: extensions-builtin/sd-extension-system-info / main

```

**Comment by Seafan75** [comment]
127.0.0.1 7860
[WinError 10093] Either the application has not called WSAStartup, or WSAStartup failed
127.0.0.1 7861
[WinError 10093] Either the application has not called WSAStartup, or WSAStartup failed
127.0.0.1 7862

This is the error I get in gradio
(venv\Lib\site-packages\gradio\networking.py, get_first_available_port), the print statements I added to get some more info.

So perhaps gradio has added something that doesn't work with windows?

```
def get_first_available_port(initial: int, final: int) -> int:
    """
    Gets the first open port in a specified range of port numbers
    Parameters:
    initial: the initial value in the range of port numbers
    final: final (exclusive) value in the range of port numbers, should be greater than `initial`
    Returns:
    port: the first open port in the range
    """
    for port in range(initial, final):
        try:
            print(LOCALHOST_NAME + " " +  str(port))
            s = socket.socket()  # create a socket object
            s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            s.bind((LOCALHOST_NAME, port))  # Bind to the port
            s.close()
            return port
        except OSError as error:
            print(error)
            pass
    raise OSError(
        f"All ports from {initial} to {final - 1} are in use. Please close a port."
    )
```

**Comment by vladmandic** [comment]
from everything i'm hearing, this sounds like windows started blocking gradio. check windows defender logs and windows event logs. this has nothing to with ports in use, its about windows not allowing gradio to use them.

**Comment by vladmandic** [comment]
> I haven't changed my network settings at all, and experienced no other network issues either. Here is the result from `ipconfig /all` - I've removed all information which may or may not be used to identify my PC.

not that relevant, but removing information about your private custom class c network is not really necessary - there is no identifiable information there. it would be different if youre running direct on public ip.

**Comment by scooller** [comment]
i have same error, erase the VENV folder fixed but i have another error:
HTTP API: KeyError

**Comment by Seafan75** [comment]
Solved my problem (but did not find the cause) in windows.
1. Deleted venv (renamed it actually).
2. Ran "set PYTHON=" (might not be needed depending on your setup)
3. Ran "webui.bat"
4. After errors, ran "webui.bat --upgrade" (will get all the packages for the extensions and so on)
5. Everything worked again
Oh well :)

**Comment by vladmandic** [comment]
unconfirmed root cause is that latest update to windows defender set gradio files in quarantine if you try to run with `--listen` or `--share` as that is considered "security risk" to listen on network - duh, its users choice if he wants to do that!

once files are in quarantine, even restoring them is not enough as sufficient corruption already happened and only solution is to reinstall (either use `--reinstall` or delete `venv`)

**Comment by scooller** [comment]
I try --reinstall, but when open the url i have error:
API error: GET: http://127.0.0.1:7860/info {'error': 'KeyError', 'detail': '', 'body': '', 'errors':"'dataset'"}
ERROR    HTTP API: KeyError

**Comment by Felsync** [comment]
> unconfirmed root cause is that latest update to windows defender set gradio files in quarantine if you try to run with `--listen` or `--share` as that is considered "security risk" to listen on network - duh, its users choice if he wants to do that!
> 
> once files are in quarantine, even restoring them is not enough as sufficient corruption already happened and only solution is to reinstall (either use `--reinstall` or delete `venv`)

I've only ever run with --upgrade and never with --listen or --share so in my case atleats I don't think that was the trigger?
I "fixed" it by reinstalling the whole thing with a new clone

**Comment by vladmandic** [comment]
> I try --reinstall, but when open the url i have error: API error: GET: http://127.0.0.1:7860/info {'error': 'KeyError', 'detail': '', 'body': '', 'errors':"'dataset'"} ERROR HTTP API: KeyError

totally different, lets not confuse the issue even more.

**Comment by scooller** [comment]
you all have the extension _sd-webui-depth-lib_ ??

**Comment by mart-hill** [comment]
I noticed that one package was changed/upgraded, since my previous update of VENV, on 19th of July:
![image](https://github.com/vladmandic/automatic/assets/55754730/ad8f4c84-0a06-491d-ada5-8e4ed3bee3c6)

Would that mean anything?

**Comment by ppkppk8520** [comment]
i had got same issue and problem was fixed after windows update.
in my case, i found some updates were not finished.

but i get new problem same with scooller

**Comment by mildfever** [comment]
ver: 5dbcc72c
OS: Win 10
Browser: Firefox 115.0.2

Same error here:

" OSError: All ports from 7860 to 7959 are in use. Please close a port. "

There was no window 10 update or firewall tinkering before or after i did the --upgrade

**Comment by slimeqslimedog** [comment]
Confirming that deleting `venv` and reinstalling via `.\webui.bat --upgrade` fixed the problem for me.

**Comment by vladmandic** [comment]
seems that for everyone deleting `venv` so packages get reinstalled solves this problem. and yes, it is windows defender as original root cause, although exact circumstances required to trigger it are undetermined.

**Comment by scooller** [comment]
> I just deleted my venv folder and did --upgrade.
> 
> The server starts fine now but when I start up the UI I get the following along with not being able to load a model:
> 
> 18:11:54-294479 ERROR API error: GET: http://127.0.0.1:7860/info {'error': 'KeyError', 'detail': '', 'body': '', 'errors': "'dataset'"} 18:11:54-296479 ERROR HTTP API: KeyError ╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮ │ D:\AiApps\StableDiffusion\sd-next1.5\venv\lib\site-packages\anyio\streams\memory.py:98 in receive │ │ │ │ D:\AiApps\StableDiffusion\sd-next1.5\venv\lib\site-packages\anyio\streams\memory.py:93 in receive_nowait │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ WouldBlock
> 
> During handling of the above exception, another exception occurred:
> 
> ╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮ │ D:\AiApps\StableDiffusion\sd-next1.5\venv\lib\site-packages\starlette\middleware\base.py:78 in call_next │ │ │ │ D:\AiApps\StableDiffusion\sd-next1.5\venv\lib\site-packages\anyio\streams\memory.py:118 in receive │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ EndOfStream
> 
> During handling of the above exception, another exception occurred:
> 
> ╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮ │ D:\AiApps\StableDiffusion\sd-next1.5\modules\middleware.py:41 in log_and_time │ │ │ │ 40 │ │ │ ts = time.time() │ │ ❱ 41 │ │ │ res: Response = await call_next(req) │ │ 42 │ │ │ duration = str(round(time.time() - ts, 4)) │ │ │ │ D:\AiApps\StableDiffusion\sd-next1.5\venv\lib\site-packages\starlette\middleware\base.py:84 in call_next │ │ │ │ ... 16 frames hidden ... │ │ │ │ D:\AiApps\StableDiffusion\sd-next1.5\venv\lib\site-packages\gradio\routes.py:271 in api_info │ │ │ │ 270 │ │ │ config = app.get_blocks().config │ │ ❱ 271 │ │ │ return gradio.blocks.get_api_info(config, serialize) # type: ignore │ │ 272 │ │ │ │ D:\AiApps\StableDiffusion\sd-next1.5\venv\lib\site-packages\gradio\blocks.py:504 in get_api_info │ │ │ │ 503 │ │ │ # Serializer's API info. │ │ ❱ 504 │ │ │ serializer = serializing.COMPONENT_MAPPINGtype │ │ 505 │ │ │ if component.get("api_info") and after_new_format: │ ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ KeyError: 'dataset'

Delete **sd-webui-depth-lib** Extension

**Comment by afbagwell** [comment]
> sd-webui-depth-lib
That worked! Thank you!
