### ISSUE TITLE
[Issue]: Image browser is possibly broken in Img2Img / Process.

### ISSUE THREAD

**Issue by scpedicini** [vladmandic/automatic#1803]
### Issue Description

![CleanShot 2023-07-22 at 23 56 09@2x](https://github.com/vladmandic/automatic/assets/2040540/e630f4df-4956-4fda-a139-25e8224aac2a)

In Text2Img/Img2Img/Process after generating an image, I can click on the generated image to bring up a nice full-screen image browser. After updating to the newest version of Vlad - it still works in txt2img, but fails to work in either img2img or process tabs. This is tested in multiple browsers.

### Version Platform Description

Python 3.10.9 on Windows 
Version: 5dbcc72c Sat Jul 22
Extension
stable-diffusion-webui-images-browser: 6386e0c8 Sat Jul22 2023 11:12

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by Razunter** [comment]
OK, that's my fault. Image viewer works only for the first used tab.
For now, replace `function initImageViewer() {` in `javascript/imageViewer.js` with

```
function initImageViewer() {
  const galleryPreviews = gradioApp().querySelectorAll('.gradio-gallery > div.preview');
  if (galleryPreviews.length > 0) {
    for (const galleryPreview of galleryPreviews) {
      const fullImgPreview = galleryPreview.querySelectorAll('img');
      if (fullImgPreview.length > 0) {
        galleryPreview.addEventListener('click', galleryClickEventHandler, true);
        fullImgPreview.forEach(setupImageForLightbox);
      }
    }
  }
```

**Comment by vladmandic** [comment]
merged.
