### ISSUE TITLE
[Issue]: Dropping image in prompt field does not work

### ISSUE THREAD

**Issue by Anashel-RPG** [vladmandic/automatic#1809]
### Feature description
---
I don't know if it's a bug or it was intended, but two important Quality of Life features got remove;

1- When drag and dropping and image in the prompt field, it used to fill out all the prompt generation information's. clicking on the book icon (read generation param) then formatted it correctly in all the field.

2- When an image was render, clicking it once enlarge it (so you could inspect and move to the next image wiht your arrow key). Right click on the image enabled you to save it. Now it close the view mode and send you back to the main UI and not let you save it.

### Version Platform Description
Windows 11 - Chrome and Edge latest version.

**Comment by eadnams22** [comment]
Not sure if this is what you mean, but this area is all weird and the 5 buttons are gone for me on my iPad/iPhone. Work in chrome for windows, haven’t checked safari on macOS yet.
![IMG_0342](https://github.com/vladmandic/automatic/assets/68871928/ca729a5e-6090-4c02-9a6b-c1ba750360ae)

**Comment by vladmandic** [comment]
@eadnams22 lets not confuse issue, those are completely unrelated.
@Anashel-RPG i'll check why dropping image in prompt field doesn't work.

**Comment by vladmandic** [comment]
fixed both right click in image viewer and image drop in prompt.

**Comment by Anashel-RPG** [comment]
This is crazy, you fixed it in less than a day. Thank you so much!
