### ISSUE TITLE
[Issue]: generation button area misaligned and missing buttons on webkit based browsers.

### ISSUE THREAD

**Issue by eadnams22** [vladmandic/automatic#1810]
### Issue Description

This area is all weird and the 5 buttons are gone for me on my iPad/iPhone on any browser (they’re all using WebKit anyway). Works in chrome for windows, haven’t checked safari on macOS yet.

Seems to have started when the extra networks area got re-flowed.

Skip button *is* cut off at the edge of the screen, if I enable the agent scheduler it’s even worse:

![IMG_0342](https://github.com/vladmandic/automatic/assets/68871928/2dfa7b40-2021-4147-bae0-c9078f1f7293)
![IMG_0343](https://github.com/vladmandic/automatic/assets/68871928/5f7c9a6b-a8df-4129-89dc-2fbd5b0719f9)

Enabling/disabling 3rd party extensions doesn’t change it.

### Version Platform Description

app: SD.next
updated: 2023-07-23
hash: 455f2133
url: https://github.com/vladmandic/automatic/tree/master

Running on windows 10, headless, so accessed from other machines.

arch: AMD64
cpu: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.10.7

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
unfortunately, i don't have safari equipped device, so this will have to wait for someone else to take a look at and submit a pr.

**Comment by eadnams22** [comment]
I’ll take a look at the css on desktop safari/dev tools next time I’m on my Mac.

**Comment by Seafan75** [comment]
I do get the same thing in chrome Version 115.0.5790.102 (Official Build) (64-bit), windows.
![image](https://github.com/vladmandic/automatic/assets/132169108/cc8678d0-bd33-44fa-a865-1a232d51db44)

**Comment by eadnams22** [comment]
Hmm, interesting, what’s your screen resolution or window/viewport size? Like, does it fix itself if you resize the window or change the zoom?

**Comment by eadnams22** [comment]
If I change the theme to gradio/default, that seems to work, so might be something in the orange theme?

**Comment by Seafan75** [comment]
Changing zoom or chrome windows size (screen resolution is 3840x2160) does not help.

Did try some other themes and they look alright, didn't test all of them of course, but only the orange one had the problem for me.

**Comment by brknsoul** [comment]
This also happens if you have an exceptionally large prompt;
![image](https://github.com/vladmandic/automatic/assets/1969381/cb415f4f-503c-43d5-9349-39a0d947a67f)

Win10/Chrome 114.0.5735.248

**Comment by vladmandic** [comment]
this chrome reproduction helped, i've fixed that. still no idea how it looks on safari - someone else should take a look at that.

**Comment by Seafan75** [comment]
Can confirm that it looks good in chrome/windows now. Thanks!

**Comment by eadnams22** [comment]
Ah, there it is.

black-orange.css
line 107

#txt2img_actions_column, #img2img_actions_column {
    display: -webkit-box;
    -webkit-box-pack: justify;
}

#txt2img_actions_column, #img2img_actions_column {
    -webkit-box-pack: justify;
}

Works fine with that line removed.

**Comment by vladmandic** [comment]
Yeah, but that is desired for chrome, it's not a general solution to remove it. You can unset in user.css if you want but ideally we need to find setting that works for both chrome and safari.

**Comment by eadnams22** [comment]
> Yeah, but that is desired for chrome, it's not a general solution to remove it. You can unset in user.css if you want but ideally we need to find setting that works for both chrome and safari.

Oh? I did remove it in Chrome as well to see what happened, and it stayed exactly the same as with it. Unless its for an edge case of some kind I didn't duplicate. Where does it come into play?

I'm still exploring if theres something that could be added for the sake of safari stuff, just posting my initial findings.

**Comment by eadnams22** [comment]
Ah, looks like almost all of -webkit-box is depreciated, including -webkit-box-pack (and box-pack)?

https://developer.mozilla.org/en-US/docs/Web/CSS/box-pack

**Comment by vladmandic** [comment]
the point of those was to align `generate` and `enqueue` buttons to be next to each other on the same line. if you can find a different way without a complete rewrite of parent elements, great.

**Comment by eadnams22** [comment]
Ooooh boy, gradio CSS. What a nightmare. 😂

**Comment by vladmandic** [comment]
i am not disagreeing with anyone that says *anything* bad about gradio :)

**Comment by eadnams22** [comment]
Well, the easy solution was to put them both in the same wrapper, and set that wrapper to flex-wrap: initial

I have a feeling that they cant be placed in the same wrapper though, in gradio.

```html
<div id="txt2img_generate_box" class="gradio-row svelte-15lo0d8">
<button class="lg primary gradio-button svelte-1ipelgc" style="  " id="txt2img_generate" data-hint="Start processing">Generate</button>
<button class="lg primary gradio-button svelte-1ipelgc" style="  " id="txt2img_enqueue" data-hint="Add task to background queueu in Agent Scheduler">Enqueue</button>
</div>
``` 

```css
#txt2img_generate_box, #img2img_generate_box {
gap: 0.5em;
flex-wrap: initial;
height: fit-content;
}
```

**Comment by vladmandic** [comment]
they are created in different places in the code, no chance to place them inside same wrapper.

**Comment by eadnams22** [comment]
Ah, this works for both chrome and safari:

```css
#txt2img_actions_column, #img2img_actions_column {
    /* display: -webkit-box; */
    /* -webkit-box-pack: justify; */
    flex-flow: wrap;
}
```

**Comment by vladmandic** [comment]
it does, but also needs `justify-content: space-between;` to align properly. thanks - i'll make the change now.

**Comment by eadnams22** [comment]
Out of curiosity, where do you change that? 

I'm unfamiliar with Gradio and a lot of Python, but do know CSS and some other languages, and would love to be able to just propose a change or make a branch in the future, less work for you.

**Comment by vladmandic** [comment]
- `html/style.css` is master
- then themes get applied, default is `html/black-orange.css`
- then user overrides get applied from `user.css` if it exists.

and yes, totally, please do contribute!
