### ISSUE TITLE
[Extension]: ComfyUI causes failure due to runtime error in its callback

### ISSUE THREAD

**Issue by imo9** [vladmandic/automatic#1819]
### Issue Description

When generating an image the process is seemingly finished but stuck at 100%.
Since it's stil in the finishing process, there is no way to interact with the UI anymore.
It looks like it's stuck at the point when applying VAE maybe?
I cant cancel the process and i found no way to keep generating anything.

(The image, however, is actually being generated in the folder and looks fine. )

The issue only happened today for the first time, 
i cant think of anything that changed except updating SD Next.

- no error messages
- restarting SD Next or the OS did not help
- had to disable agent scheduler because the image was stuck even after restart
- running it in --safe mode works, but i did not use any special extensions when generating before

### Version Platform Description

Version: d4aa840a Mon Jul 24 16:10:01 2023 +0900
launched with --upgrade
Python 3.10.6 on Windows
OS: Windows 10
GPU: GTX 1060 VRAM 6GB
Browser: Edge, Brave

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
run with `--debug` to capture more info.

**Comment by imo9** [comment]
okay i think i found the issue. i disabled the ComfyUI extension (which i did not use to generate the image).
i will still run it with debug mode to see if it shows an error.

**Comment by imo9** [comment]
This is from --debug mode with ComfyUI extension active. Not sure why it even does something, since i am not using it. Maybe you can make something of it. Also, the image generation in debug mode does work despite the error code.
Thank you for your time :)

`14:16:16-391688 DEBUG    Saving image: JPEG E:\vlad1\automatic\outputs/text\2023-07-24\00277-a garden shed ultra
                         detailed 8k UHD.jpg (512, 512)
14:16:16-763314 DEBUG    gc: collected=1279 device=cuda {'ram': {'used': 2.93, 'total': 7.9}, 'gpu': {'used': 3.25,
                         'total': 6.0}, 'retries': 0, 'oom': 0}
14:16:16-852892 ERROR    Running script postprocess: E:\vlad1\automatic\extensions\sd-webui-comfyui\scripts\comfyui.py:
                         KeyError
RemoteError: None

The above exception was the direct cause of the following exception:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ E:\vlad1\automatic\modules\scripts.py:442 in postprocess                                                            │
│                                                                                                                     │
│   441 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                      │
│ > 442 │   │   │   │   script.postprocess(p, processed, *args)                                                       │
│   443 │   │   │   │   s.append(f'{script.title()}:{round(time.time()-t0, 2)}s')                                     │
│                                                                                                                     │
│ E:\vlad1\automatic\extensions\sd-webui-comfyui\scripts\comfyui.py:65 in postprocess                                 │
│                                                                                                                     │
│   64 │   │   │   images_batch = images[range_start:range_end]                                                       │
│ > 65 │   │   │   batch_results = ComfyuiNodeWidgetRequests.start_workflow_sync(                                     │
│   66 │   │   │   │   batch=images_batch,                                                                            │
│                                                                                                                     │
│ E:\vlad1\automatic\extensions\sd-webui-comfyui\lib_comfyui\ipc.py:15 in wrapper                                     │
│                                                                                                                     │
│   14 │   │   │   │   │   raise NotImplemented('WSL is not yet supported for integrated workfl                       │
│ > 15 │   │   │   │   return current_process_queues[process_id].get(args=(function.__module__,                       │
│   16                                                                                                                │
│                                                                                                                     │
│ E:\vlad1\automatic\extensions\sd-webui-comfyui\lib_comfyui\parallel_utils.py:64 in get                              │
│                                                                                                                     │
│   63 │   │   if isinstance(res, RemoteError):                                                                       │
│ > 64 │   │   │   raise res.error from res                                                                           │
│   65 │   │   else:                                                                                                  │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
KeyError: None`

**Comment by imo9** [comment]
another point worth mentioning is that the extension never worked for me in the first place but that's a whole other story

**Comment by John-WL** [comment]
Are you running with wsl? We have had issues with wsl for the last few updates because of how threads are handled.

**Comment by John-WL** [comment]
Oh nevermind, I wasn't understanding the stacktrace. Running on wsl doesn't seem to be the issue.

**Comment by imo9** [comment]
no WSL. 
i deactivated the extension now, but when activated the ComfyUI tab was only showing a white screen with a message saying something like "127.0.0.1:7860 has not permitted connection"
this is probably a different issue though, since the issue i posted here locked up the normal SD Next image generation process.

**Comment by John-WL** [comment]
Yes, the connection error occurs when the extension loads after the UI has loaded. It should load correctly if you refresh the UI with "F5".

**Comment by John-WL** [comment]
It should be fixed now as of the last commit. Let us know if it works or not.
