### ISSUE TITLE
[Issue]: The footer link opens a wrong repo

### ISSUE THREAD

**Issue by ke1ne** [vladmandic/automatic#182]
### Issue Description

A small detail: this link opens the a1111's repo:
![image](https://user-images.githubusercontent.com/8934421/232346856-5ca1c7d8-c923-47df-ba16-d5cb2ae5ae8b.png)

### Version Platform Description

Version: 58df74cf

Win 11, Chrome 112

**Comment by vladmandic** [comment]
fixed.
