### ISSUE TITLE
[Issue]: AttributeError: module 'modules.sd_samplers' has no attribute

### ISSUE THREAD

**Issue by SAC020** [vladmandic/automatic#1821]
### Issue Description

Using controlnet + tiled diffussion (doesn't matter if multidiffusion or mixture of diffusers, happens to both) + regional prompt control + highres fix

- if I don't activate the region prompt control, it doesn't manifest
- if primary sampler = secondary sampler, it doesn't manifest
- if primary sampler (DSM 2s a Karras) is different than the secondary sampler (Euler a), then it happens

Not sure if related with https://github.com/vladmandic/automatic/issues/1302#issuecomment-1646755554 but it is not fixed for me.

### Version Platform Description

Using VENV: C:\ai\automatic\venv
14:12:02-642238 INFO     Starting SD.Next
14:12:02-646229 INFO     Python 3.10.11 on Windows
14:12:02-736984 INFO     Version: fae6033a Sun Jul 23 08:29:02 2023 -0400
14:12:03-282544 INFO     Latest published version: d4aa840a77de06eee4a26f013a0858d47788ab6b 2023-07-24T07:10:01Z
14:12:03-285536 INFO     nVidia CUDA toolkit detected
14:12:03-524184 WARNING  Modified files: ['modules/lora', 'modules/lycoris']
14:12:03-568068 INFO     Disabled extensions: []
14:12:03-569065 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
14:12:03-590162 INFO     Enabled extensions: ['adetailer', 'openpose-editor', 'sd-webui-3d-open-pose-editor',
                         'sd-webui-openpose-editor', 'sd-webui-regional-prompter']
14:12:03-608247 INFO     No changes detected: Quick launch active
14:12:03-609245 INFO     Verifying requirements
14:12:03-623207 INFO     Disabled extensions: []
14:12:03-624205 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
14:12:03-632183 INFO     Enabled extensions: ['adetailer', 'openpose-editor', 'sd-webui-3d-open-pose-editor',
                         'sd-webui-openpose-editor', 'sd-webui-regional-prompter']

### Relevant log output

```shell
08:57:01-773216 ERROR    gradio call: AttributeError ╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ C:\ai\automatic\modules\call_queue.py:34 in f                                                                        ││                                                                                                                      ││    33 │   │   │   try:                                                                                               ││ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                    ││    35 │   │   │   │   progress.record_results(id_task, res)                                                          ││                                                                                                                      ││ C:\ai\automatic\modules\txt2img.py:65 in txt2img                                                                     ││                                                                                                                      ││   64 │   if processed is None:                                                                                       ││ ❱ 65 │   │   processed = processing.process_images(p)                                                                ││   66 │   p.close()                                                                                                   ││                                                                                                                      ││                                               ... 5 frames hidden ...                                                ││                                                                                                                      ││ C:\ai\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:362 in         ││ <lambda>                                                                                                             ││                                                                                                                      ││   361 │   │   sd_samplers.create_sampler_original_md = sd_samplers.create_sampler                                    ││ ❱ 362 │   │   sd_samplers.create_sampler = lambda name, model: self.create_sampler_hijack(                           ││   363 │   │   │   name, model, p, Method(method),                                                                    ││                                                                                                                      ││ C:\ai\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\scripts\tilediffusion.py:434 in         ││ create_sampler_hijack                                                                                                ││                                                                                                                      ││   433 │   │   # create a sampler with the original function                                                          ││ ❱ 434 │   │   sampler = sd_samplers.create_sampler_original_md(name, model)                                          ││   435 │   │   if method == Method.MULTI_DIFF: delegate_cls = MultiDiffusion                                          │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯AttributeError: module 'modules.sd_samplers' has no attribute 'create_sampler_original_md' 08:57:01-865967 WARNING  GPU high memory utilization: 100% {'ram': {'used': 5.76, 'total': 31.92}, 'gpu': {'used': 15.99, 'total': 15.99}, 'retries': 0, 'oom': 0}
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
you're using TWO extensions and still not using extension template. marking issue as invalid.
and yes, some combination of extensions do not work since they hijaak same part of the code. so one takes over, second overwrites the function and then first one tries to use function that was just overwritten by second extension. not much i can do about that.
