### ISSUE TITLE
[Feature]: Allow browsing filesystem for target directories/paths/files in addition to text entry fields

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#1830]
### Feature description

Implement a file browser window popup button (such as when clicking on the Click to Upload in From Image tab) like this:
![image](https://github.com/vladmandic/automatic/assets/108482020/65bc223d-ab2b-42e3-8f8c-2b6302480ee7)

For areas such as this:
![image](https://github.com/vladmandic/automatic/assets/108482020/70935a95-090f-4e46-a03d-30aa73e9c91d)
So that users may more easily browse to locations from the many text-field-only UI elements that want paths.

**Comment by vladmandic** [comment]
as per detailed discussion in discord, closing this as no-op as its not possible in browsers.
