### ISSUE TITLE
[Issue]: Can no longer generate images since latest commit

### ISSUE THREAD

**Issue by Trojaner** [vladmandic/automatic#1834]
### Issue Description

The error below show's up when I try to generate anything

### Version Platform Description

https://github.com/vladmandic/automatic/commit/c5b089cbb665cdb02b8d3876b7340153da289e4c
Windows 11
Chrome
No user extensions enabled

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1321, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1165, in preprocess_data
    assert isinstance(
AssertionError: <class 'modules.ui_components.FormGroup'> Component with id 8874 not a valid input component.
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
fixed. in general, if update causes obvious issue, best to wait 30min and check if there is a newer update as most likely cause was a bad merge. this was fixed within minutes.
