### ISSUE TITLE
[Issue]: LivePreviews ApproxNN doesn't work

### ISSUE THREAD

**Issue by Nyaster** [vladmandic/automatic#184]
### Issue Description

After enabling LivePreviews(On ApproxNN) i have this error:
FileNotFoundError: [Errno 2] No such file or directory: '/home/nyaster/automatic/models/VAE-approx/model.pt'
After replace this from Main repo, i have another errors:
gradio call: FileNotFoundError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ /home/nyaster/automatic/modules/call_queue.py:59 in f                                                                │
│                                                                                                                      │
│    58 │   │   │   │   pr.enable()                                                                                    │
│ ❱  59 │   │   │   res = list(func(*args, **kwargs))                                                                  │
│    60 │   │   │   if shared.cmd_opts.profile:                                                                        │
│                                                                                                                      │
│ /home/nyaster/automatic/modules/call_queue.py:38 in f                                                                │
│                                                                                                                      │
│    37 │   │   │   try:                                                                                               │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    39 │   │   │   finally:                                                                                           │
│                                                                                                                      │
│                                               ... 5 frames hidden ...                                                │
│                                                                                                                      │
│ /home/nyaster/automatic/venv/lib/python3.10/site-packages/torch/serialization.py:271 in _open_file_like              │
│                                                                                                                      │
│    270 │   if _is_path(name_or_buffer):                                                                              │
│ ❱  271 │   │   return _open_file(name_or_buffer, mode)                                                               │
│    272 │   else:                                                                                                     │
│                                                                                                                      │
│ /home/nyaster/automatic/venv/lib/python3.10/site-packages/torch/serialization.py:252 in __init__                     │
│                                                                                                                      │
│    251 │   def __init__(self, name, mode):                                                                           │
│ ❱  252 │   │   super().__init__(open(name, mode))                                                                    │
│    253                                                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

### Version Platform Description

win11(WSL ubuntu)

**Comment by vladmandic** [comment]
i've added vae-approx files and confirmed as working on my system. however, note that compvis diffusors such as unipc do not have denoising until last step, so preview in general is not that useful. it works fine for k-diffusion diffusors such as dpm* or euler-a.
