### ISSUE TITLE
[Diffusers]: Second pass not being applied

### ISSUE THREAD

**Issue by Automaticism** [vladmandic/automatic#1842]
### Issue Description

When using diffusers as backend the second pass checkbox doesn't do anything. 
Also tested with the `-safe` launch option, no change. 

---
Additionally doing a one-shot generation takes a really long time to finish saving and showing up in the UI / on disk. (Note that this actually seems to have a relationship with vram and size of generation being generated. 512x768 was relatively quick compared to 768x1024 which died / never finished one generation, 3080 10GB vram)
CTRL+C also takes a really long time to exit the program when using the diffusers backend.

### Diffusers pipeline used

Testing with dreamshaperXL10_alpha2Xl10.safetensors [0f1b80cfe8] model. 
{'size': '512x768', 'parser': 'Full parser', 'version': '8320859', 'pipeline': 'Diffusers', 'operations': 'txt2img'}

### Version Platform Description

13:26:39-491818 INFO     Starting SD.Next
13:26:39-499817 INFO     Python 3.10.11 on Windows
13:26:39-602391 INFO     Version: 83208591 Wed Jul 26 22:22:35 2023 -0400
13:26:39-896955 INFO     nVidia CUDA toolkit detected
13:26:40-038954 WARNING  Modified files: ['modules/lora', 'modules/lycoris']
13:26:40-089074 INFO     Disabled extensions: ['sd-webui-controlnet', 'sd-dynamic-thresholding',
                         'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris']
13:26:40-090076 INFO     Enabled extensions-builtin: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
13:26:40-094074 INFO     Enabled extensions: ['adetailer', 'sd-dynamic-prompts', 'sd_civitai_extension']
13:26:40-096076 INFO     No changes detected: Quick launch active
13:26:40-097075 INFO     Verifying requirements
13:26:40-112073 INFO     Disabled extensions: ['sd-webui-controlnet', 'sd-dynamic-thresholding',
                         'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris']
13:26:40-113074 INFO     Enabled extensions-builtin: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
13:26:40-116076 INFO     Enabled extensions: ['adetailer', 'sd-dynamic-prompts', 'sd_civitai_extension']
13:26:40-122074 INFO     Extension preload: 0.0s F:\sdnext\extensions-builtin
13:26:40-124076 INFO     Extension preload: 0.0s F:\sdnext\extensions
13:26:40-157072 INFO     Server arguments: ['--listen']
No module 'xformers'. Proceeding without it.
13:26:55-291394 INFO     Pipeline: Backend.ORIGINAL
13:26:56-627522 INFO     Libraries loaded
13:26:56-629521 INFO     Using data path: F:\sdnext
13:26:56-632524 INFO     Available VAEs: F:\sdnext\models\VAE 0
13:26:56-649521 INFO     Available models: F:\sdnext\models\Stable-diffusion 27
Image Browser: ImageReward is not installed, cannot be used.
[-] ADetailer initialized. version: 23.7.5, num models: 9
Civitai: API loaded
13:27:01-473467 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://0.0.0.0:7860
13:27:08-142198 INFO     Local URL: http://localhost:7860/
13:27:08-143197 INFO     Initializing middleware
13:27:08-275200 INFO     [AgentScheduler] Task queue is empty
13:27:08-276197 INFO     [AgentScheduler] Registering APIs
Civitai Link: Connecting to Civitai Link Server
Loading weights: F:\sdnext\models\Stable-diffusion\dreamshaperXL10_alpha2Xl10.safetensors ━━━━━━━━━━━ 0.0/6.9 GB -:--:--
13:27:10-455937 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
Civitai Link: Connected to Civitai Link Server
Civitai: Check resources for missing preview images
13:27:10-639936 INFO     Startup time: 30.5s (torch=11.1s gradio=1.7s libraries=3.7s codeformer=0.1s scripts=4.5s
                         onchange=0.2s ui-txt2img=0.2s ui-img2img=0.1s ui-settings=0.1s ui-extensions=1.9s
                         ui-defaults=0.1s launch=4.2s app-started=2.5s)
Civitai: Found 13 resources missing preview images
DiffusionWrapper has 859.52 M params.
Civitai: Found 8 hash matches
Civitai: Updated 0 preview images
Civitai Link: Presence update: SD: 1, Clients: 0

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
first, log output should go into LOG OUTPUT so its formatted correctly.
second, for second pass to do anything, you need to LOAD refiner model. i don't see it loaded anywhere in your log.
read wiki.

**Comment by vladmandic** [comment]
> Having both "Version Platform Description" and "Relevant log output" is unclear / redundant.

Its not. Log file can be long. version/platform/description should be just that. Log should be what's relevant to issue.
Its not hard, its one more paste for you - think of ppl trying to help you instead of arguing with them.
