### ISSUE TITLE
[Diffusers]: 

### ISSUE THREAD

**Issue by toyssamurai** [vladmandic/automatic#1849]
### Issue Description

When using the diffuser backend, it appears that the seed won't change when "batch" is enabled. 

### Diffusers pipeline used

SDXL 1.0 Base + SDXL 1.0 Refiner

### Version Platform Description

OS: Ubuntu 
Browser: Chrome

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
no title, no version info - its not that hard to fill issue correctly. and show log that shows what you're saying.
marking as invalid.
