### ISSUE TITLE
[Issue]: SDXL 1.0 Load problem

### ISSUE THREAD

**Issue by Someonetoldme584** [vladmandic/automatic#1851]
### Issue Description

Please fill this form with as much information as possible

### Version Platform Description

![image](https://github.com/vladmandic/automatic/assets/79592731/799e8ea7-9b52-4550-9ce7-6be16081fdac)

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by eadnams22** [comment]
Are you using diffusers backend with the Stable Diffusion XL loader?

**Comment by Ke031** [comment]
@eadnams22 i have the same problem and yes, i have VAE, model, refiner and diffusers activated ....my version is up to date ..

**Comment by vladmandic** [comment]
is it really too much to ask to fill description and version/platform info? any issue with missing information is considered invalid.
also, this is exactly what happens if you have wrong **pipeline** selected before you load a model.

**Comment by Ke031** [comment]
@vladmandic i have the last version of sd.next, last version of refiner and diffuser and correct pipeline loaded as diffusers.
i have already done everything wrote on the wiki and i have errors everywhere when i try to load SD
![result156](https://github.com/vladmandic/automatic/assets/119963095/e9a7a7e8-693e-4d5f-8a92-61bb3ab50357)

**Comment by vladmandic** [comment]
this last problem is totally different and if you actually take a look at the log, its clear that extension batch-face-swap is not compatible.

**Comment by Ke031** [comment]
@vladmandic cause that vae was in the video of AItpreneur he said to use that that too ..
Look everything is fine in the quick list.... i muted other extensions and....same problem...
![result156](https://github.com/vladmandic/automatic/assets/119963095/bdca8839-aa19-4280-a65e-2092106413c8)

**Comment by vladmandic** [comment]
what does even "muted" mean? start with `--safe` so none of user-extensions get loaded.
first error was clearly wrong pipeline, second was clearly incompatible extension. and you have soo many installed i cannot even start to figure it out. instead of forcing things, can you take it step-by-step? load with --safe (or disable extensions), start with diffusers, set correct pipeline, load sd-xl model. follow wiki. 

and don't use stuff "just because someone on the internet said it" unless you know what its for. if you do know, great.

**Comment by Ke031** [comment]
@vladmandic muted = disabled extension (already done that) but i don't understand "pipeline" and my diffuser pipeline is the correct one ? loot at my screen it's sd xl 1.0 from stability :O

**Comment by Ke031** [comment]
ok seems to work now but....i have problem with oom .....
"CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 8.00 GiB total capacity; 6.90 GiB already
allocated; 0 bytes free; 7.16 GiB reserved in total by PyTorch)" @vladmandic is there a solution to solve this problem ? my card is a rtx2080 super :)

**Comment by vladmandic** [comment]
you can enable vae slicing and tiling in diffuser settings. there are other parameters as well to tune, but thats where i'd start.
btw, if you disabled extensions, they wouldn't show up like they do. in your screenshot you had tons of them.

**Comment by Ke031** [comment]
you right, i unload them after the screenshot ^^ and this is why the model loaded correctly after but still have some OOM just for 40mb missing of memory haha, but i don't get it is my gpu isn't enough for sdxl ? i have i9 9900K 64Go ram rtx2080 super :O @vladmandic is there any trick to get it work on my system ? (thanks for your replies, it's very appreciated) you're great !

**Comment by vladmandic** [comment]
i already just answered that?

**Comment by Ke031** [comment]
@vladmandic maybe i can unload the refiner when generating image and after going on img2img select refiner instead of the main model and try to regenerate with a lower noise ?

**Comment by vladmandic** [comment]
there are already options for that in settings that do all that automatically, just take a look whats there, you don't need to invent workflows. but in general, for 99% of cases you don't even need refiner.

**Comment by vladmandic** [comment]
for more, ask on discord, lets not continue here on a closed issue talking about something else.

**Comment by Ke031** [comment]
@vladmandic 
do i miss something ? or made mistake here ? 
![result156](https://github.com/vladmandic/automatic/assets/119963095/61c3e296-525a-4092-93fe-51a0295debfe)
