### ISSUE TITLE
[Diffusers]: Checkpoint Models are not listed, thus cannot use SDXL.

### ISSUE THREAD

**Issue by Sniper199999** [vladmandic/automatic#1862]
### Issue Description

Stable diffusers backend: Diffusers 

When I use Diffusers backend for using SDXL, no checkpoints are detected and it tells me to download the 1.5 model.
While in original backend, all the checkpoints are detected and shown.

SDXL model: Dreamshaper SDXL (safetensors)

What I tried: 
- using --safe
- changing model name to "sd_xl_base_1.0"
- Adding Folder "SDXL" inside "Stable-diffusion" folder

### Diffusers pipeline used

Stable Diffusion XL

### Version Platform Description

19:50:12-541381 INFO     Starting SD.Next
19:50:12-543396 INFO     Python 3.10.9 on Windows
19:50:12-580664 INFO     Version: 77de9cd0 Fri Jul 28 23:18:28 2023 +0900
19:50:13-035244 INFO     nVidia CUDA toolkit detected
19:50:13-128936 WARNING  Modified files: ['models/karlo/ViT-L-14_stats.th', 'modules/lora', 'modules/lycoris']
19:50:13-184711 INFO     Disabled extensions: ['sd-webui-controlnet', 'sd-dynamic-thresholding',
                         'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris']
19:50:13-186259 INFO     Enabled extensions-builtin: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']

### Relevant log output

```shell
19:52:37-274471 INFO     Available models: D:\Learn\automatic\models\Stable-diffusion 0
Download the default model? (y/N) n
19:53:25-861090 INFO     Available models: D:\Learn\automatic\models\Stable-diffusion 0
Download the default model? (y/N) n
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
Enable allow safetensors in settings - diffusers.

**Comment by Sniper199999** [comment]
Yes this fixed the issue. I think the setting should be enabled by default OR the Wiki for SDXL should be updated to tell  users to enable this setting in the settings tab.

**Comment by vladmandic** [comment]
It is enabled by default nowadays, but it wasn't in the past and you carried over your configuration.
