### ISSUE TITLE
[Diffusers]: 'diffusers' has no attribute 'StableDiffusionXLPipeline'

### ISSUE THREAD

**Issue by Sniper199999** [vladmandic/automatic#1863]
### Issue Description

The above error while trying to load the SDXL 1.0 checkpoint (safetensors).
SDXL model: Dreamshaper SDXL (safetensors)

What I tried:
    using --safe

### Diffusers pipeline used

Stable Diffusion XL

### Version Platform Description

19:50:12-541381 INFO Starting SD.Next
19:50:12-543396 INFO Python 3.10.9 on Windows
19:50:12-580664 INFO Version: https://github.com/vladmandic/automatic/commit/77de9cd0934c386ce4798c05955826bab09544b4 Fri Jul 28 23:18:28 2023 +0900
19:50:13-035244 INFO nVidia CUDA toolkit detected
19:50:13-128936 WARNING Modified files: ['models/karlo/ViT-L-14_stats.th', 'modules/lora', 'modules/lycoris']
19:50:13-184711 INFO Disabled extensions: ['sd-webui-controlnet', 'sd-dynamic-thresholding',
'multidiffusion-upscaler-for-automatic1111', 'a1111-sd-webui-lycoris']
19:50:13-186259 INFO Enabled extensions-builtin: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET',
'sd-extension-system-info', 'sd-webui-agent-scheduler',
'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']

### Relevant log output

```shell
Diffusers model failed initializing pipeline: Stable Diffusion XL module 'diffusers' has no
                         attribute 'StableDiffusionXLPipeline'
21:01:09-195814 WARNING  Model not loaded
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
Something downgraded diffusers package, likely an extension such as dreambooth.
Run with `--upgrade`, even if you're on latest 8t will force recheck of requirements.

**Comment by Sniper199999** [comment]
You are correct, some other extension (most probably dreambooth) was downgrading diffusers. The error from my side was I was using these parameters alongside --side : "--quick --skip-requirements --skip-extensions --skip-git --skip-torch". The skip-requirements parameter did not check for installed versions.
I ran using just --skip and the problem got fixed.

**Comment by PSYCHEER** [comment]
I'm having this exact issue but on clean installation. No extensions or something. With the last commit from 2 days back. Going to set venv manually and check for results

**Comment by vladmandic** [comment]
@PSYCHEER 
this issue was resolved and closed over a year ago, please create a new issue and document everything.

**Comment by PSYCHEER** [comment]
I will as soon as I'll reinstall manually all of the packages if the issue persist. Sorry btw
