### ISSUE TITLE
[Issue]: Read Generation parameters does not work (index error string out of range)

### ISSUE THREAD

**Issue by StableInfo** [vladmandic/automatic#1864]
### Issue Description

here is an example of a prompt text  generation that was saved in one of my text files, 

```
a w........................ ..... .......... ........ ........ ., full of high tech w............ ......... ........ .......... ....... ........ ................ ................ ,  refractions,  space in the background, nebula, 

Negative prompt: planet, face, nsfw, (worst quality:2), (low quality:2), (normal quality:2), bad-hands-5
Version: aa62f6d, Pipeline: Original, Steps: 25, Seed: 1693458539, Sampler: Euler a, CFG scale: 7, Size: 768x512, Parser: Full parser, Model: revAnimated_v122, Model hash: 4199bcdd14, Clip skip: 2, Latent sampler: UniPC, Image CFG scale: 6, Denoising strength: 0.5, Denoise start: 0.8, Denoise end: 1, Operations: , ControlNet 0: "preprocessor: canny, model: control_v11p_sd15_canny [d14c016b], weight: 1, starting/ending: (0, 1), resize mode: Crop and Resize, pixel perfect: True, control mode: My prompt is more important, preprocessor params: (512, 100, 200)", Hires upscale: 1.3, Hires steps: 20, Hires upscaler: 4x-UltraSharp
```

The text is  AS IS except for the points I removed few words (this text file is the one associated to the image after hires), I will include the text before the hires because it's interesting, it ends with the word "operations:" then nothing:

```
a w........................ ..... .......... ........ ........ ., full of high tech w............ ......... ........ .......... ....... ........ ................ ................ ,  refractions,  space in the background, nebula, 

Negative prompt: planet, face, nsfw, (worst quality:2), (low quality:2), (normal quality:2), bad-hands-5
Version: aa62f6d, Pipeline: Original, Steps: 25, Seed: 1693458539, Sampler: Euler a, CFG scale: 7, Size: 768x512, Parser: Full parser, Model: revAnimated_v122, Model hash: 4199bcdd14, Clip skip: 2, Latent sampler: UniPC, Image CFG scale: 6, Denoising strength: 0.5, Denoise start: 0.8, Denoise end: 1, Operations:
```

When I press the read generation parameters button nothing happens and in the cmd window I see this:

```
Traceback (most recent call last):
  File "D:\vladNEXTGEN\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\vladNEXTGEN\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\vladNEXTGEN\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\vladNEXTGEN\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\vladNEXTGEN\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\vladNEXTGEN\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\vladNEXTGEN\automatic\modules\generation_parameters_copypaste.py", line 352, in paste_func
    params = parse_generation_parameters(prompt)
  File "D:\vladNEXTGEN\automatic\modules\generation_parameters_copypaste.py", line 276, in parse_generation_parameters
    if v[0] == '"' and v[-1] == '"':
IndexError: string index out of range
```

What's the matter?
Thanks

### Version Platform Description

app: SD.next
updated: 2023-07-25
hash: aa62f6d8
url: https://github.com/vladmandic/automatic/tree/master

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by StableInfo** [comment]
One thing I did not say is the positive prompt contained the word "break" in the middle of it. Wonder if that messed the creation of the text file or not. I will go check the png file, maybe the content there is not broken (just about this).

**Comment by vladmandic** [comment]
If this image created with latest version? Because, yes there was a bug where operations were blank and that caused parsing issues.

**Comment by Aptronymist** [comment]
> 

the version listed is from 3 days ago, so it's likely the buggy one where the order was wrong.

**Comment by StableInfo** [comment]
I dont know if its the latest version, mine is from 3 days ago.
I think I found whats the problem, the text files generated next to the images, miss the word "prompt" at the beginning, 
adding that, still does not fix it. 
I think I know what is the problem:
The png files contains text that is separated by "pipes" |...|..|..
Except those pipes are not characters that show up on the text files I believe.
I am one of those guys that rely hugely on the text files generated next to each image, I dont use the png file info, here are differences between the png file info and the text file:

PNG INFO:
```
prompt: a ........................................
Negative prompt: planet, face, nsfw, (worst quality:2), (low quality:2), (normal quality:2), bad-hands-5
Version: aa62f6d, Pipeline: Original,
Steps: 25 | Seed: 1879635471 | Sampler: Euler a | CFG scale: 7 | Size: 768x512 | Parser: Full parser | Model: revAnimated_v122 | Model hash: 4199bcdd14 | Clip skip: 2 | Latent sampler: UniPC | Image CFG scale: 6 | Denoising strength: 0.5 | Denoise start: 0.8 | Denoise end: 1 | Operations: | Hires upscale: 2 | Hires steps: 20 | Hires upscaler: 4x-UltraSharp
```

The text file:

`a watermelon facing a sky full of high tech planes, full of high tech waterlmelon parts, red watermelon flesh, dome islamic coissant ,  refractions,  space in the background, nebula, muslims on the ground praying

Negative prompt: planet, face, nsfw, (worst quality:2), (low quality:2), (normal quality:2), bad-hands-5
Version: aa62f6d, Pipeline: Original, Steps: 25, Seed: 1879635471, Sampler: Euler a, CFG scale: 7, Size: 768x512, Parser: Full parser, Model: revAnimated_v122, Model hash: 4199bcdd14, Clip skip: 2, Latent sampler: UniPC, Image CFG scale: 6, Denoising strength: 0.5, Denoise start: 0.8, Denoise end: 1, Operations:
`

**Comment by StableInfo** [comment]
I dont know if its the latest version, mine is from 3 days ago.
I think I found whats the problem, the text files generated next to the images, miss the word "prompt" at the beginning, 
adding that, still does not fix it. 
I think I know what is the problem:
The png files contains text that is separated by "pipes" |...|..|..
Except those pipes are not characters that show up on the text files I believe.
I am one of those guys that rely hugely on the text files generated next to each image, I dont use the png file info, here are differences between the png file info and the text file:

PNG INFO:
```
prompt: a ........................................
Negative prompt: planet, face, nsfw, (worst quality:2), (low quality:2), (normal quality:2), bad-hands-5
Version: aa62f6d, Pipeline: Original,
Steps: 25 | Seed: 1879635471 | Sampler: Euler a | CFG scale: 7 | Size: 768x512 | Parser: Full parser | Model: revAnimated_v122 | Model hash: 4199bcdd14 | Clip skip: 2 | Latent sampler: UniPC | Image CFG scale: 6 | Denoising strength: 0.5 | Denoise start: 0.8 | Denoise end: 1 | Operations: | Hires upscale: 2 | Hires steps: 20 | Hires upscaler: 4x-UltraSharp
```

The text file:

`a.......................

Negative prompt: planet, face, nsfw, (worst quality:2), (low quality:2), (normal quality:2), bad-hands-5
Version: aa62f6d, Pipeline: Original, Steps: 25, Seed: 1879635471, Sampler: Euler a, CFG scale: 7, Size: 768x512, Parser: Full parser, Model: revAnimated_v122, Model hash: 4199bcdd14, Clip skip: 2, Latent sampler: UniPC, Image CFG scale: 6, Denoising strength: 0.5, Denoise start: 0.8, Denoise end: 1, Operations:
`

**Comment by Aptronymist** [comment]
> One thing I did not say is the positive prompt contained the word "break" in the middle of it. Wonder if that messed the creation of the text file or not. I will go check the png file, maybe the content there is not broken (just about this).

Please update, this was from a few days ago, there was a slight

> I dont know if its the latest version, mine is from 3 days ago. I think I found whats the problem, the text files generated next to the images, miss the word "prompt" at the beginning, adding that, still does not fix it. I think I know what is the problem: The png files contains text that is separated by "pipes" |...|..|.. Except those pipes are not characters that show up on the text files I believe. I am one of those guys that rely hugely on the text files generated next to each image, I dont use the png file info, here are differences between the png file info and the text file:
> 
> PNG INFO:
> 
> ```
> prompt: a ........................................
> Negative prompt: planet, face, nsfw, (worst quality:2), (low quality:2), (normal quality:2), bad-hands-5
> Version: aa62f6d, Pipeline: Original,
> Steps: 25 | Seed: 1879635471 | Sampler: Euler a | CFG scale: 7 | Size: 768x512 | Parser: Full parser | Model: revAnimated_v122 | Model hash: 4199bcdd14 | Clip skip: 2 | Latent sampler: UniPC | Image CFG scale: 6 | Denoising strength: 0.5 | Denoise start: 0.8 | Denoise end: 1 | Operations: | Hires upscale: 2 | Hires steps: 20 | Hires upscaler: 4x-UltraSharp
> ```
> 
> The text file:
> 
> `a.......................
> 
> Negative prompt: planet, face, nsfw, (worst quality:2), (low quality:2), (normal quality:2), bad-hands-5 Version: [aa62f6d](https://github.com/vladmandic/automatic/commit/aa62f6d8d44844df29814b204ec1ad3582ffb4f0), Pipeline: Original, Steps: 25, Seed: 1879635471, Sampler: Euler a, CFG scale: 7, Size: 768x512, Parser: Full parser, Model: revAnimated_v122, Model hash: 4199bcdd14, Clip skip: 2, Latent sampler: UniPC, Image CFG scale: 6, Denoising strength: 0.5, Denoise start: 0.8, Denoise end: 1, Operations: `

Please update, this was a slight bug in the order of the metadata, the issue is that the Version: and Pipeline: were first, where what is expected by everything is that the normal Seed: or Steps: would be there, since these are new and only exist in our application. They have now been moved to the end of the metadata so they do not create an issue.

**Comment by StableInfo** [comment]
Updated. Now its working indeed.
I would like a button, or a TAB, called "UPDATE", where you can go click a button to see if there is any new version, and then another button to decide to upgrade or not. Instead of the webui --upgrade.

**Comment by vladmandic** [comment]
That's fair, pls create a feature request so it doesn't fall off the radar.
