### ISSUE TITLE
[Feature]: a TAB or a button to check if there is any new version of the sd.next

### ISSUE THREAD

**Issue by StableInfo** [vladmandic/automatic#1866]
### Feature description

Hello,
It could be useful to have a button, or a TAB, called "UPDATE", where you can go click a button to see if there is any new version, and then another button to decide to upgrade or not. Instead of the webui --upgrade.

### Version Platform Description

.

**Comment by vladmandic** [comment]
valid, confirmed as "will be done", jsut cant say exactly when - i'm traveling for a bit.

**Comment by vladmandic** [comment]
added in dev branch, will be part of the next release.
