### ISSUE TITLE
[Issue]: "Create text file next to every image with generation parameters" does not include the seed in the name of the file anymore?

### ISSUE THREAD

**Issue by StableInfo** [vladmandic/automatic#1870]
### Issue Description

Hello I have been used the oldest version of sd.next for a long time, and upgraded recently.
I am noticing something that I actually miss having.
The text files generation info, were named like this: num_seed and now they are named num_fewWordsFromPrompts
Can I get back the seed in its name?

### Version Platform Description

app: SD.next
updated: 2023-07-28
hash: 77de9cd0
url: https://github.com/vladmandic/automatic/tree/master

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
And best way to achieve that is to open an issue?
Filename follows user configurable pattern, set it to what you like. In either case, this is NOT an issue.
