### ISSUE TITLE
[Extension]: Config Preset no longer functions due to change in element IDs.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#1877]
### Issue Description

The element IDs that were changed due to moving to the Second Pass 'system' causes Config Presets to no longer find these IDs, causing it to not load.

A work-around has been mentioned here https://github.com/Zyin055/Config-Presets/issues/52

### Version Platform Description

```
12:41:34-956691 INFO     Starting SD.Next
12:41:34-969812 INFO     Python 3.10.11 on Windows
12:41:35-223896 INFO     Version: 83208591 Wed Jul 26 22:22:35 2023 -0400
12:41:35-977857 INFO     Latest published version: 813eb48bf70576ab455db3f9cb5f358df4a11000 2023-07-29T03:10:41Z
12:41:35-982858 INFO     Using DirectML Backend
```

### URL link of the extension

https://github.com/Zyin055/Config-Presets

### URL link of the issue reported in the extension repository

https://github.com/Zyin055/Config-Presets/issues/53

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by brknsoul** [comment]
I imagine that this is just a notification Issue, as it'll be up to the devs of Config Preset to adjust elemental ID detection.
It'd be helpful if a table of old and new IDs could be supplied.

**Comment by vladmandic** [comment]
that is always a conceptual problem with any extension that relies on ui not changing.

**Comment by brknsoul** [comment]
Config Preset's Pull Request https://github.com/Zyin055/Config-Presets/pull/55 solves this issue. Closing.
