### ISSUE TITLE
[Issue]: XL will no longer generate Images.  Was working a couple of hours ago.

### ISSUE THREAD

**Issue by Thom293** [vladmandic/automatic#1878]
### Issue Description

XL was working about 2 hours ago.  Generating images fine.  I made no changes, but I did not turn off git update, like a damn fool.

Here is what it is doing:
Now I get black images, and a message model not loaded.  Also, when I have diffusers pip selected, I cannot change models.  If I switch to original pip, I can change models/vae, etc.  But if I switch back to diffusers pip, no more.  I am certain I am in XL mode and have extensions, but none are running or being used.  

I can generate SD1.5 images just fine.

I presume whatever change was made recently caused this.  I am not a git expert, but Id love advice on how to go back to a previous commit.  Thank you. 

I get the following message in the command prompt.

![Screenshot 2023-07-28 231141](https://github.com/vladmandic/automatic/assets/23645569/6183c6e4-7afd-4116-96cc-dd2f53ff6cda)

### Version Platform Description

Windows 10, 64gb ram, 4090.  It was working a few hours ago...

![Screenshot 2023-07-28 232348](https://github.com/vladmandic/automatic/assets/23645569/87202c68-21ae-47fe-854c-517d773b16d4)

### Relevant log output

```shell
log is too long, but here is a screen:
Loading weights: C:\Users\Main\Documents\SD\Vlad\7.28.23\automatic\models\Stable-diffusion\XL1,0\sd_xl_refiner_1.0.sa…
23:10:35-953381 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
23:10:37-426779 ERROR    Error loading model weights:
                         C:\Users\Main\Documents\SD\Vlad\7.28.23\automatic\models\Stable-diffusion\XL1,0\sd_xl_refiner_
                         1.0.safetensors Error(s) in loading state_dict for LatentDiffusion:
                                 size mismatch for model.diffusion_model.time_embed.0.weight: copying a param with
                         shape torch.Size([1536, 384]) from checkpoint, the shape in current model is torch.Size([1280,
                         320]).
                                 size mismatch for model.diffusion_model.time_embed.0.bias: copying a param with shape
                         torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([1280]).
                                 size mismatch for model.diffusion_model.time_embed.2.weight: copying a param with
                         shape torch.Size([1536, 1536]) from checkpoint, the shape in current model is
                         torch.Size([1280, 1280]).
                                 size mismatch for model.diffusion_model.time_embed.2.bias: copying a param with shape
                         torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([1280]).
                                 size mismatch for model.diffusion_model.input_blocks.0.0.weight: copying a param with
                         shape torch.Size([384, 4, 3, 3]) from checkpoint, the shape in current model is
                         torch.Size([320, 4, 3, 3]).
                                 size mismatch for model.diffusion_model.input_blocks.0.0.bias: copying a param with
                         shape torch.Size([384]) from checkpoint, the shape in current model is torch.Size([320]).
                                 size mismatch for model.diffusion_model.input_blocks.1.0.in_layers.0.weight: copying a
                         param with shape torch.Size([384]) from checkpoint, the shape in current model is
                         torch.Size([320]).
                                 size mismatch for model.diffusion_model.input_blocks.1.0.in_layers.0.bias: copying a
                         param with shape torch.Size([384]) from checkpoint, the shape in current model is
                         torch.Size([320]).
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by Thom293** [comment]
Update:  After closing and restarting a number of times, It now works, but Control Net has disabled itself for some reason.

**Comment by ronbere** [comment]
> Update: After closing and restarting a number of times, It now works, but Control Net has disabled itself for some reason.

extension not compatible

**Comment by vladmandic** [comment]
Root cause was that some of your extensions actually downgraded required package, most likely dreambooth.

**Comment by vladmandic** [comment]
Root cause was that some of your extensions actually downgraded required package, most likely dreambooth.
