### ISSUE TITLE
[Feature]: Support moving SDXL Refiner to RAM when VAE decoding?

### ISSUE THREAD

**Issue by SLAPaper** [vladmandic/automatic#1879]
### Feature description

It seems that even enabled "Move refiner model to CPU when not in use", the refiner model will remaining in VRAM when doing VAE decoding, leads to a VRAM spike of (refiner + vae)
move refiner to RAM earlier may significantly lower VRAM usage

**Comment by Disty0** [comment]
Added it: https://github.com/vladmandic/automatic/commit/38ecfb6dff529e7ec88174e5672030299de0d4be

![image](https://github.com/vladmandic/automatic/assets/47277141/9dfe0d87-ef0e-482d-a39e-7bee3b7b424d)
