### ISSUE TITLE
[Issue]: Disabled saving all images and grids but they still getting getting saved

### ISSUE THREAD

**Issue by nailz420** [vladmandic/automatic#188]
### Issue Description

Disabled saving all images and grids but they still getting getting saved

Settings>Image Options
Always save all generated images - Unchecked
Always save all generated image grids - Unchecked

### Version Platform Description

updated: 2023-04-16
hash: d67c1dcb
url: https://github.com/vladmandic/automatic.git/tree/master

arch: AMD64
cpu: Intel64 Family 6 Model 167 Stepping 1, GenuineIntel
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.10

**Comment by vladmandic** [comment]
i just tried and works ok on my side:
1. click generate -> image is saved
2. go to settings -> image options
3. change `samples_save`, `grid_save`, click apply
4. click generate -> image is not saved

**Comment by nailz420** [comment]
can't reproduce anymore after restart

**Comment by vladmandic** [comment]
closing.
