### ISSUE TITLE
[Issue]: Seed Details & Second Pass Checkboxes not auto-checked

### ISSUE THREAD

**Issue by Holyniwa** [vladmandic/automatic#1882]
### Feature description

Something I noticed, but I cannot say when it began (if it's with SDN or recent commit, since I only recently git pulled from before SDN) is that when sending a Process image to txt2img, the seedbox and the secondpass box aren't auto checked (they remain unchecked; same with Batch and Advance). Aside from that, I also noticed that unlike A1111, SDN also does not auto-change the checkpoint nor the vae to whichever the referenced image used. 
Were these changes made deliberately, or are they a byproduct of recent changes? While it only takes a few moments to make sure everything is changed/checked, it is an extra step I sometimes forget if I'm not paying close attention. Is there an option in the settings to make it auto-change, or is it stuck this way?

### Version Platform Description

Win11, OperaGX

**Comment by vladmandic** [comment]
I'd say there are things that need to be polished as recent changes have been huge.

**Comment by vladmandic** [comment]
btw, i'd suggest to delete ui-config.json so new defaults take effect. at least checkboxes should be settable as permanent.
the rest is like i said, work in progress.

**Comment by vladmandic** [comment]
Thanks, I'll check it out.

**Comment by vladmandic** [comment]
i cant reproduce, if i change ui defaults so checkbox is selected, it shows as selected/expanded when i restart the app.
when you save defaults, can you check `ui-config.json`, it should include lines such as:
```json
  "txt2img/Batch/value": true,
  "txt2img/Seed details/value": true
```

also, update the app and run with webui with `--debug`, it will print lines on startup such as:
```log
08:23:20-479000 DEBUG    UI interface: tab=txt2img batch=True seed=True advanced=False second_pass=False
08:23:20-605246 DEBUG    UI interface: tab=img2img seed=False resize=False batch=False denoise=True advanced=False
```

**Comment by vladmandic** [comment]
any updates here?

**Comment by Holyniwa** [comment]
Sorry about that, iRL stuff happened. My ui-config.json was empty. Putting the 2 lines ensured the boxes remained checked upon a new restart.
