### ISSUE TITLE
[Feature]: Add Checkpoint dropdown menu for Second Pass

### ISSUE THREAD

**Issue by abetteridea** [vladmandic/automatic#1887]
### Feature description

As far as I understand (from Discord conversations), there is an idea for the _Stable Diffusion refiner_ setting to work as a Second Pass checkpoint when using SD 1.5. It doesn't seem to work this way just yet (at least via Original backend).

I was wondering if you could simplify the process of choosing a second pass checkpoint by adding a Checkpoint dropdown menu to the Second Pass section.

**Comment by abetteridea** [comment]
On a second thought, I'm not sure I fully understand the need for 'From Image' and 'Process Image' tabs when we have the Second Pass section. From what I understand, the only real difference is being able to see the intermediate image before sending it further?

**Comment by vladmandic** [comment]
yup, i came to that conclusion as well, but it will require a mjor redesign. i'm tracking that in the todo list already (you can see it in the repo) so no need for this feature request - i'm closing only because of that, but its a valid request otherwise.
