### ISSUE TITLE
[Issue]: Can't Create Embedding

### ISSUE THREAD

**Issue by Jukari2003** [vladmandic/automatic#1888]
### Issue Description

Getting the following error when trying to create an embedding:

File "C:\Users\Jukari\Desktop\SD Next\automatic\venv\lib\site-packages\diffusers\configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'cond_stage_model'

Start Log is as follows:
--------------------------------------------------------
Using VENV: C:\Users\Jukari\Desktop\SD Next\automatic\venv
22:23:13-097002 INFO     Starting SD.Next
22:23:13-102004 INFO     Python 3.10.11 on Windows
22:23:13-169003 INFO     Version: 085d1da8 Sat Jul 29 21:01:24 2023 +0300
22:23:13-751033 INFO     nVidia CUDA toolkit detected
22:23:13-948003 WARNING  Modified files: ['modules/lycoris']
22:23:13-951002 INFO     Verifying requirements
22:23:13-966003 INFO     Verifying packages
22:23:13-968003 INFO     Verifying repositories
22:23:19-622003 INFO     Verifying submodules
22:23:57-402524 INFO     Extensions enabled: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
22:23:57-405523 INFO     Verifying packages
22:23:57-408523 INFO     Updating Wiki
22:23:58-281526 INFO     Extension preload: 0.0s C:\Users\Jukari\Desktop\SD Next\automatic\extensions-builtin
22:23:58-283525 INFO     Extension preload: 0.0s C:\Users\Jukari\Desktop\SD Next\automatic\extensions
22:23:58-301523 INFO     Server arguments: ['--backend', 'diffusers', '--upgrade', '--listen']
No module 'xformers'. Proceeding without it.
22:24:08-039563 INFO     Pipeline: Backend.DIFFUSERS
22:24:09-133451 INFO     Libraries loaded
22:24:09-139486 INFO     Using data path: C:\Users\Jukari\Desktop\SD Next\automatic
22:24:09-142483 INFO     Available VAEs: C:\Users\Jukari\Desktop\SD Next\automatic\models\VAE 0
22:24:09-150484 INFO     Available models: C:\Users\Jukari\Desktop\SD Next\automatic\models\Stable-diffusion 6
22:24:13-787483 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://0.0.0.0:7860
22:24:20-626521 INFO     Local URL: http://localhost:7860/
22:24:20-629524 INFO     Initializing middleware
22:24:20-773522 INFO     [AgentScheduler] Task queue is empty
22:24:20-776520 INFO     [AgentScheduler] Registering APIs
22:24:20-979519 INFO     Torch override VAE dtype: no-half set
22:24:20-981519 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float32 unet=torch.float16
22:24:20-986519 INFO     Loading diffuser model: C:\Users\Jukari\Desktop\SD
                         Next\automatic\models\Stable-diffusion\sd_xl_base_1.0.safetensors
22:24:45-171518 INFO     Embeddings: loaded=0 skipped=0
22:24:45-174520 INFO     Model loaded in 24.2s (load=24.2s) native=1024
22:24:45-443557 INFO     Model load finished: {'ram': {'used': 1.08, 'total': 30.0}, 'gpu': {'used': 8.36, 'total':
                         23.99}, 'retries': 0, 'oom': 0}
22:24:45-449558 INFO     Torch override VAE dtype: no-half set
22:24:45-452557 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float32 unet=torch.float16
22:24:45-454557 INFO     Loading diffuser refiner: C:\Users\Jukari\Desktop\SD
                         Next\automatic\models\Stable-diffusion\sd_xl_refiner_1.0.safetensors
22:25:04-078631 INFO     Embeddings: loaded=0 skipped=0
22:25:04-080631 INFO     Model loaded in 18.6s (load=18.6s) native=1024
22:25:04-337666 INFO     Model load finished: {'ram': {'used': 6.89, 'total': 30.0}, 'gpu': {'used': 8.36, 'total':
                         23.99}, 'retries': 0, 'oom': 0}
22:25:04-341666 INFO     Startup time: 66.0s (torch=6.9s gradio=1.0s libraries=2.9s codeformer=0.1s scripts=4.3s
                         onchange=0.2s ui-txt2img=0.1s ui-img2img=0.2s ui-settings=0.1s ui-extensions=1.8s
                         ui-defaults=0.1s launch=4.5s app-started=0.3s checkpoint=43.5s)
Traceback (most recent call last):
  File "C:\Users\Jukari\Desktop\SD Next\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\Jukari\Desktop\SD Next\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "C:\Users\Jukari\Desktop\SD Next\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\Jukari\Desktop\SD Next\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Jukari\Desktop\SD Next\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Jukari\Desktop\SD Next\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\Jukari\Desktop\SD Next\automatic\modules\textual_inversion\ui.py", line 9, in create_embedding
    filename = modules.textual_inversion.textual_inversion.create_embedding(name, nvpt, overwrite_old, init_text=initialization_text)
  File "C:\Users\Jukari\Desktop\SD Next\automatic\modules\textual_inversion\textual_inversion.py", line 272, in create_embedding
    cond_model = shared.sd_model.cond_stage_model
  File "C:\Users\Jukari\Desktop\SD Next\automatic\venv\lib\site-packages\diffusers\configuration_utils.py", line 137, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'cond_stage_model'

### Version Platform Description

- Fresh Install of SD.Next
- Python 3.10.11

- Using SDXL 1.0 Base + Refiner
- Command Line Args:  --backend diffusers --upgrade --listen
- ESXi VM System w/GPU Pass-through: 
CPU i9 10900K 3.7 Ghz
30 GB Ram
RTX 4090

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
you're using sd-xl and cannot create embeddings? but any kind of built-in training is not yet supported for any kind of diffusers workflow. its coming, but creating issues for something that's not supposed to work doesn't make it work faster.
