### ISSUE TITLE
[Issue]: Civitai Helper extension wont display buttons on extra networks

### ISSUE THREAD

**Issue by runew0lf** [vladmandic/automatic#189]
### Issue Description

Extension : [Civitai Helper](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper) displays buttons on extra networks cards usually, however this is not the case i've tried multiple themes too to see if it was a theme'ing issue
![model_card](https://user-images.githubusercontent.com/9966016/232402639-d3285a98-87b1-490b-a451-58e881b1b862.jpg)
That is what its means to look like, however when the refresh button is clicked (it has a refresh civit button to display the images)
![refresh_ch](https://user-images.githubusercontent.com/9966016/232402775-26e796c7-91a4-4bfd-881e-05347ea2881f.jpg)
Nothing happens, is it something that can be looked into at all (if not its perfectly ok, my wife uses it a lot to quickly jump to the model page in civit)

### Version Platform Description

Browser: MsEdge
OS: Windows 11
Version: latest version (if no changes are detected, it doesnt display the version number in the logs)

**Comment by vladmandic** [comment]
so just to confirm, you've tried with different theme such as `gradio/default`?

**Comment by vladmandic** [comment]
@Shadowghost thanks for chasing it down, i've added a compatibility layer for that, will be published in ~1h.
