### ISSUE TITLE
[Issue]: UI unresponsive and not reponding to Prompts.

### ISSUE THREAD

**Issue by Thom293** [vladmandic/automatic#1890]
### Issue Description

Something seemed off.  Images washed out.  Didnt seem to be responding to refiner use.  

I was trying to figure out what is going on.  I put in silly prompt: A bight cheery leery Ciri.  got some images of Witcher Ciri.  Tried to Add Loras.  get the "object has no attribute" message (from the other bug report #1889). decide to completely delete prompt with nothing but the Lora to see if that does anything.  Only the LORA tag is in the prompt.  Stil get images of Ciri.  Delete LORA prompt and prompt is completely blank.  Still get images of Ciri. Its getting "stuck" on stuff a lot.

![image](https://github.com/vladmandic/automatic/assets/23645569/feec8812-9ef6-4f9c-a27d-4edd95f96254)

### Version Platform Description

![image](https://github.com/vladmandic/automatic/assets/23645569/c30604d3-93a4-408e-93c1-1c06f6e116d3)

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by Thom293** [comment]
Ok - thinking about it now - it may have been reading the secondary prompt from the Second Pass feature.  But I had turned Second pass "Off" by unchecking it.  

Perhaps it was still "on" while unchecked.  If this is the case, I think it should clear or not read the secondary prompt when unchecked, or this is going to cause endless confusion.

Perhaps the whole second pass thing, especially for the refiner, should be changed?  It always says its disabled.  It appears to work sometimes when set to 0 or 1.  Its completely unclear if it is working when set in the middle.  It might be, but there is no real visual feedback that it is, other than the "Disabled" line.

![image](https://github.com/vladmandic/automatic/assets/23645569/150f0c4f-7ace-4998-9b21-7f0dde0f86eb)

Thank you.

**Comment by vladmandic** [comment]
this is actually covered in Wiki.
yes, better design is desirable and its coming, but it was a question of getting full functionality out or wait until redesign which will take much longer.
