### ISSUE TITLE
[Feature]: Cannot Change SDXL models with no internet connection

### ISSUE THREAD

**Issue by Thom293** [vladmandic/automatic#1891]
### Issue Description

Simple:  If I switch my computer to airplane mode or swith off internet, cannot change XL models.  If I switch to 1.5 mode I can change models and vae, etc.  If I switch to XL it won't let me change models at all.  Here is the message:

![image](https://github.com/vladmandic/automatic/assets/23645569/8b1e16e5-ccb8-400a-8a8f-bb9fb92195c6)

If it matters, I am using the following command line args:

@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --skip-requirements --skip-git --skip-torch

call webui.bat

### Version Platform Description

I have a 4090 with 64gb of ram.

![image](https://github.com/vladmandic/automatic/assets/23645569/82dc1b64-b6bb-4cc5-aa06-3ac66ccaf4af)

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
valid request, but will be treated as feature request, not issue.

**Comment by StableInfo** [comment]
Hello,
I don't understand, why would SDXL need internet connection to work?
Also Vlad, yu marked this as feature request as in "Introduce the possibility to use SDXL without internet"? Or what is the request here?

I don't like that SDXL need internet not do I understand it.

**Comment by vladmandic** [comment]
It's simple and will be fixed soon.

Every model needs a config, even old ones not related to diffusers (config files are yaml files in /config folder).

Issue is that diffusers have a bug reading local config file, so they fetch it from the internet. It's few kb only, but yes, it needs to be fetched each time since loading from local doesn't work.

**Comment by vladmandic** [comment]
https://github.com/huggingface/diffusers/pull/5019

**Comment by vladmandic** [comment]
fixed in dev.
