### ISSUE TITLE
[Extension]: Sd comfyui extenstion not work since endpoint is missing

### ISSUE THREAD

**Issue by TingTingin** [vladmandic/automatic#1892]
### Issue Description

A new callback [postprocess_batch_list ](https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/11957)was added to automatic that is used by the comfy extension this is not yet implemented in SD.Next and is required for some functionality.

### URL link of the extension

https://github.com/ModelSurge/sd-webui-comfyui

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
its planned.
cc @ljleb

**Comment by ljleb** [comment]
Yes, I will be able to start working on a PR in 2-3 days if it hasn't been worked on before then.

**Comment by ljleb** [comment]
Opened a PR, let me know if you have any feedback @vladmandic and I'll update the code asap.
