### ISSUE TITLE
[Feature]: Hidden Directory Filtering

### ISSUE THREAD

**Issue by KaptainSkurvy** [vladmandic/automatic#1902]
### Feature description

The current directory scanning mechanism for loading the VAEs, checkpoints, extra networks, and embeddings does not ignore files located under hidden directories and shows the corresponding cards on the extra networks tab. It also shows the complete path, including hidden directories, in the checkpoint dropdown menu. This can clutter the UI and make file management difficult for users who utilize hidden directories for organization.

&nbsp;&nbsp;&nbsp;&nbsp;**1. Directory Scanning Update:** Modify the directory scanning algorithm that generates cards of VAEs, checkpoints, extra networks, and embeddings to filter out files located in hidden directories. The files in hidden directories will still be loaded and available for use in the software, but their presence will be masked in the UI (extra networks tab) to streamline the user interface.

&nbsp;&nbsp;&nbsp;&nbsp;**2. Dropdown Display Update:** For the loaded files from hidden directories, the checkpoint dropdown menu should not include the hidden directory segment in the file name display. For instance, if a file is located under .hidden/modelX.safetensors, the dropdown should only display modelX.safetensors.

These improvements are primarily intended for users dealing with a growing assortment of models. This increased collection size may not be suitable for all workflows, or are perhaps not desired for the most frequently used workflow. By enabling a more streamlined user interface, we can improve model management, reduce clutter, and allow users to focus more on their most used files.

### Version Platform Description

Python 3.10.6 on Windows
Version: 8787f36b Tue Aug 1 02:03:51 2023 +0900

**Comment by vladmandic** [comment]
> By enabling a more streamlined user interface, we can improve model management, reduce clutter, and allow users to focus more on their most used files.

this does not create more streamlined user interface, it adds additional layer of complexity.
i understand the desire, but the app exposes everything that user has made avaiable.

one option i'm looking at as alternative is to show/hide items in extra networks based on their tags (e.g. nsfw or not). and that would work for items with correctly set tags. but defiintely not based on folder naming scheme.
