### ISSUE TITLE
[Issue]: not a git repository when running install from bat file on win10

### ISSUE THREAD

**Issue by 2blackbar** [vladmandic/automatic#1903]
### Issue Description

Microsoft Windows [Version 10.0.19044.1288]
(c) Microsoft Corporation. All rights reserved.

G:\vlad>webui.bat -debug
Using VENV: G:\vlad\venv
03:26:44-090570 INFO     Starting SD.Next
03:26:44-094527 INFO     Python 3.10.9 on Windows
03:26:44-098516 ERROR    Not a git repository
Press any key to continue . . .

### Version Platform Description

win10

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
Exactly like it says - how did you create thar copy of sdnext?

**Comment by 2blackbar** [comment]
Downloaded zip and extracted, then ran bat file ,exactly like  i install original auto11

**Comment by vladmandic** [comment]
Exactly. Only supported is git clone, there is no mention of downloading zip and unpacking it as supported.
