### ISSUE TITLE
[Issue]: black images with xl

### ISSUE THREAD

**Issue by santaonholidays** [vladmandic/automatic#1905]
### Issue Description

Please fill this form with as much information as possiblei get black images with xl with original mode with diffusers it works but the Checkpoints disappear

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by georgzoeller** [comment]
Duplicate: See https://github.com/vladmandic/automatic/issues/1858
