### ISSUE TITLE
[Feature]: iA3 Support for SDXL

### ISSUE THREAD

**Issue by synapsestorm** [vladmandic/automatic#1911]
### Feature description

https://huggingface.co/docs/peft/conceptual_guides/ia3

iA3 is presented as an improvement over LoRas - it's quicker and easier to train, can take up around 100kb~ of space per iA3, and is already implemented in A1111 (possibly SD.Next, haven't checked) for SD 1.5.

Due to the speed in which it trains and the other improvements, I'd love to be able to dive into this method of training.

Thanks

**Comment by AI-Casanova** [comment]
I hope to be working on this over the next week or so, will reference this issue if and when I submit a PR.

**Comment by vladmandic** [comment]
new unified lora handler in dev handles this, will be merged to master shortly

**Comment by AI-Casanova** [comment]
Well that ended up being a bit more than a week. 😅
