### ISSUE TITLE
[Feature]: Lazy background refresh of EN models

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#1912]
### Feature description

Pretty much what it says in the title, have an occasional (on idle?) check in the model directories for any changes, to avoid having to use the refresh button which is quite time-consuming as it rescans *everything*.

Also, maybe having the rescan only look at the type of EN that is currently selected?  
That would save a lot of time, and that's probably how people are using it anyway.

**Comment by vladmandic** [comment]
as refresh is much faster and also only refreshes currently selected page, this is pretty much a no-op anymore.
