### ISSUE TITLE
Whole interface is BROKEn what the hell.

### ISSUE THREAD

**Issue by NinjaDanny87** [vladmandic/automatic#1915]
### Issue Description

![image](https://github.com/vladmandic/automatic/assets/59182752/2c63c8de-4119-4af6-9168-f9bc70c3363b)

All my settings and extensions aren't working with this latest update what the hell?!

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by NinjaDanny87** [comment]
On top of this controlnet which comes loaded doesn't even work I have tested this with a fresh install! Why the hell do you change the whole thing?!? At least give us the option to make these changes in settings instead of forcing these changes on us by default!

**Comment by vladmandic** [comment]
"all my settings and extensions" doesn't help - you need to be specific. What doesn't work? Under which scenario? There are thousands of ppl using sdnext and nobody said this and new interface has been live for a bit already.

I understand your frustration, but if you need help, give us information to be able to help you.

Also, there is NO excuse for not filing version/platform info.
