### ISSUE TITLE
[Extension]: what's wrong with the controlnet when i run it

### ISSUE THREAD

**Issue by min-star** [vladmandic/automatic#1916]
### Issue Description

Please fill this form with as much information as possible

Traceback (most recent call last):
  File "/home/meta/msf/sd/automatic/venv/lib/python3.9/site-packages/gradio/routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/meta/msf/sd/automatic/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1326, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/home/meta/msf/sd/automatic/venv/lib/python3.9/site-packages/gradio/blocks.py", line 1260, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/home/meta/msf/sd/automatic/venv/lib/python3.9/site-packages/gradio/components.py", line 4461, in postprocess
    file = self.pil_to_temp_file(img, dir=self.DEFAULT_TEMP_DIR)
  File "/home/meta/msf/sd/automatic/modules/ui_tempdir.py", line 61, in pil_to_temp_file
    file_obj = tempfile.NamedTemporaryFile(delete=False, suffix=".png", dir=dir)
  File "/home/meta/miniconda3/lib/python3.9/tempfile.py", line 545, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
  File "/home/meta/miniconda3/lib/python3.9/tempfile.py", line 255, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/tmp/gradio/tmpzo5r9g_k.png'

### Version Platform Description

ubuntu22.04
4090

### URL link of the extension

https://github.com/Mikubill/sd-webui-controlnet

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by Aptronymist** [comment]
> PermissionError: [Errno 13] Permission denied: '/tmp/gradio/tmpzo5r9g_k.png'

To me this is pretty obviously a, as it states, permissions issue, are you running it as the correct user that has write permissions on the /tmp folder?

**Comment by vladmandic** [comment]
wait, you have ubuntu and did not have /tmp until you created it? i'm not sure if any linux can work properly without /tmp and /tmp cannot be just created as normal folders, it has special permissions assigned to it.

**Comment by min-star** [comment]
i don't know whether just my ubuntu is not work，and I found almost no one has this mistake as me.



---Original---
From: "Vladimir ***@***.***&gt;
Date: Thu, Aug 3, 2023 00:19 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [vladmandic/automatic] [Extension]: what's wrong with thecontrolnet when i run it (Issue #1916)




 
wait, you have ubuntu and did not have /tmp until you created it? i'm not sure if any linux can work properly without /tmp and /tmp cannot be just created as normal folders, it has special permissions assigned to it.

**Comment by vladmandic** [comment]
i've never seen a linux system without `/tmp`

**Comment by min-star** [comment]
maybe it has /tmp,and just the png cannot be generated,thus not be found and get a mistake




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vladimir ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 凌晨0:36
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vladmandic/automatic] [Extension]: what&#39;s wrong with the controlnet when i run it (Issue #1916)





 
i've never seen a linux system without /tmp

**Comment by min-star** [comment]
tomorrow i will reproduce the&nbsp;previous mistake,and put this issue,thanks your reply，have a good night!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Vladimir ***@***.***&gt;; 
发送时间: 2023年8月3日(星期四) 凌晨0:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [vladmandic/automatic] [Extension]: what&#39;s wrong with the controlnet when i run it (Issue #1916)





 
it not "not found", its actually Permission denied: '/tmp/gradio/tmpzo5r9g_k.png' which happens while trying to write it. and /tmp has special flag on it that its always writeable. linux without a writeable /tmp cannot work reliably, regardless of sdnext or not.

**Comment by vladmandic** [comment]
any updates here?

**Comment by vladmandic** [comment]
closing due to no updates.

**Comment by JDihlmann** [comment]
I encountered the same issue recently although it should be solved here https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/12717 

The problem for me was that another user on the machine also run the code which created a gradio directory that only this user could access. So if you encounter this issue, please also check the permission if a /tmp/gradio directory already exists.

**Comment by xddun** [comment]
it is ok:

[https://qq742971636.blog.csdn.net/article/details/140150136](https://qq742971636.blog.csdn.net/article/details/140150136)
