### ISSUE TITLE
[Issue]: "Image error: cannot identify image file" when using too many images in batch mode

### ISSUE THREAD

**Issue by SouljaVR** [vladmandic/automatic#1917]
### Issue Description

Hi,

Firstly, to everyone involved, thank you for your work. I am currently having an issue where if I batch generate more than 100 images or so in img2image (for video restyling etc.) I get the error "Image error: cannot identify image file"

![image](https://github.com/vladmandic/automatic/assets/97592971/557c2e84-1bcc-4e8c-b95d-a38c11951ee6)

If I do under 100 or so, I dont have any issues. It seems to just have an overflow issue or something with too many images in the queue. However for restyling videos etc. its necessary to process potentially thousands of frames one after the other. Not sure if this is just a 'me' issue, but I have been able to replicate this with all self-added extensions disabled etc. Hopefully this is an easy fix, thank you again for your work!

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
i believe the issue, but its not going to be a quick fix - i don't know if its a gradio limitation with temp files or pillow limitation (image library), in either case, if its a limitation, i'll need to break it into sub-jobs - all doable, but i'm traveling right now and trying to reproduce this on a notebook is a bit of a pain. i'm afraid, this will have to go into a backlog for now.

**Comment by SouljaVR** [comment]
Thank you for taking note of this! Much appreciated and yes, its not a major issue so it should be low priority. Thank you again.

**Comment by vladmandic** [comment]
i've removed first bottleneck, i'm sure there are more - please check and see how many you can generate now. i believe this will be an iterative process, removing bottlenecks one by one.

also, when generating large batches, make sure that `Show result images` is disabled as appening each image to gradio gallery is definitely one of the bottlnecks.

**Comment by vladmandic** [comment]
closing with the latest fix. if issue persists, report here and i'll reopen.
