### ISSUE TITLE
[Issue]: Colab compatibility

### ISSUE THREAD

**Issue by mykeehu** [vladmandic/automatic#192]
### Issue Description

I have version 3.9.16 installed on my Colab, and I get an error on startup that it is not compatible with this version:

![image](https://user-images.githubusercontent.com/6390413/232426988-1cc2ddb8-7c0f-4e52-9e9f-a95fb20785b1.png)

### Version Platform Description

Python 3.9.16
Mon Apr 17 08:23:47 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   38C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) CPU @ 2.00GHz
stepping	: 3
microcode	: 0xffffffff
cpu MHz		: 2000.168
cache size	: 39424 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4000.33
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 85
model name	: Intel(R) Xeon(R) CPU @ 2.00GHz
stepping	: 3
microcode	: 0xffffffff
cpu MHz		: 2000.168
cache size	: 39424 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed
bogomips	: 4000.33
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual

**Comment by vladmandic** [comment]
i think that somehow collab reported python version as string instead of number.
i just changed installer to account for that, new version will be up in ~1h.

**Comment by vladmandic** [comment]
actually, my bad, issue is that this repo was requiring python 3.10 while collab has 3.9, i've relaxed requirements now.

**Comment by AI-Casanova** [comment]
@mykeehu were you able to get Colab running? I was able to get basic functionality last night, but no extensions were showing up at all (ControlNet not where it should be on the text tab etc)

**Comment by mykeehu** [comment]
@AI-Casanova works for me, I'm running it right now and it seems more stable than auto1111. 
However, use these switches to run it and even then there are extension gaps here and there, but at least it starts and runs most functions:
`--no-hashing --share --noupdate --skip-extensions --gradio-auth login:pass`

**Comment by AI-Casanova** [comment]
@mykeehu thanks for the response, I'm confused as to what I'm doing wrong, perhaps because I'm hacking together a notebook from TheLastBen, but extensions are still not showing up. 
![webui](https://user-images.githubusercontent.com/54461896/233404990-98b89161-6fe8-449a-b58e-a2cbe5d01827.png)
![webui2](https://user-images.githubusercontent.com/54461896/233405018-4693173e-7787-40d0-b3bf-15fd8a712194.png)

I can install extensions, and that one got a tab, but no accordion fold on the generating tabs. I'm stumped. 

You wouldn't by change be able to share your notebook as a gist would you?

**Comment by jeremyg7** [comment]
Would be great if there were a Colab notebook for this. I was also using TheLastBen on Colab.

**Comment by AI-Casanova** [comment]
@jeremyg7 If I get it working, I'll definitely release a notebook. 

@vladmandic do you have an idea why extensions might not be showing up where they should? I'm running out of places to look for silent issues.

**Comment by vladmandic** [comment]
i'd take a look at `modules/scripts.py:` and throw some print statements around,
specifically 
- `list_scripts()` if they are getting enumerated
- `load_scripts()` if they are getting initialized

**Comment by mykeehu** [comment]
I can't share my notebook, because I'm already pretty busy, and I'm booting both auto and vlad versions from the same place.
However, here are the notebook blocks I use on colab. I have my models and settings on Google drive to use the next time I start up, so take that into account. So:

- Connect to Google drive:
```
#@title Connect to Google Drive
from google.colab import drive
drive.mount('/content/drive')
```

- Clone vlad's repo:
```
#@title V2 - Clone Vladmandic SD
%cd /content/
!git clone https://github.com/vladmandic/automatic
```

- install a few extensions:
```
#@title Extensions install (optional)
%cd /content/automatic/extensions/
!git clone https://github.com/fkunn1326/openpose-editor
!git clone https://github.com/mcmonkeyprojects/sd-dynamic-thresholding
!git clone https://github.com/kohya-ss/sd-webui-additional-networks.git
!git clone https://github.com/Klace/stable-diffusion-webui-instruct-pix2pix
!git clone https://github.com/KohakuBlueleaf/a1111-sd-webui-locon
!git clone https://github.com/opparco/stable-diffusion-webui-composable-lora
!git clone https://github.com/opparco/stable-diffusion-webui-two-shot
!git clone https://github.com/nonnonstop/sd-webui-3d-open-pose-editor
!git clone https://github.com/richrobber2/canvas-zoom
!git clone https://github.com/hako-mikan/sd-webui-regional-prompter
!git clone https://github.com/ilian6806/stable-diffusion-webui-state
!git clone https://github.com/jtydhr88/sd-canvas-editor
```

- install vlad's SD:
```
#@title Launch Vladmandic webui (GPU mode)
%cd /content/automatic/
!COMMANDLINE_ARGS="--no-hashing --share --noupdate --skip-extensions --gradio-auth login:pass --ckpt /content/drive/MyDrive/SDmodels/clarity_19-pruned.safetensors --ui-config-file /content/drive/MyDrive/1my/vlad-ui-config-my.json --ui-settings-file /content/drive/MyDrive/1my/vlad-config-my.json" REQS_FILE="requirements.txt" python launch.py
```

That's it, and it works.
