### ISSUE TITLE
[Feature]: Move any .safetensor files in "models" to correct folder upon UI start

### ISSUE THREAD

**Issue by Nekos4Lyfe** [vladmandic/automatic#1920]
### Feature description

Let's say I download the github repo and download a civitai model in the "automatic/models" folder.

I would like to have a feature where, upon starting the UI, any .safetensors files that are stored in the "models" folder are moved to the "Stable-diffusion" folder

**Comment by brknsoul** [comment]
The problem is; loras, lycoris and vars are also .safetensors files

**Comment by Nekos4Lyfe** [comment]
True. Though some initial guesses could be made, as there should not be any loose .safetensors files in the models folder anyway. A .safetensors file with size>2GB can be assumed to be a model, for instance. The rest could be ignored.

**Comment by vladmandic** [comment]
guess what the file might be and then try to move it on its own from the folder where user placed it?
if any application does that to my pc, i'd consider that application hostile.
i understand the idea behind it, but there are some user mistakes that app should not meddle in.
