### ISSUE TITLE
[Feature]: Sign for extension that are not compatible with SDXL

### ISSUE THREAD

**Issue by razvanab** [vladmandic/automatic#1925]
### Feature description

A sign in the extension tab that shows witch extension are not compatible with SDXL.

### Version Platform Description

Windows 10
32 GB Ram
6 GB Vram
Microsoft Edge

**Comment by vladmandic** [comment]
It's planned, but it requires ppl to actually report what is compatible. Also, in many cases extension may have a better maintained fork which works while original doesn't.

**Comment by razvanab** [comment]
I understand.
Where is the best place to report what extension doesn't work? Here in Issues or Discussion?

**Comment by jlitz** [comment]
Trying to get wildcards  extension to work   installed dynamic prompts and installed wildcards in it .  I will see if  it works.

**Comment by vladmandic** [comment]
> I understand.
> Where is the best place to report what extension doesn't work? Here in Issues or Discussion?

I'll create a place for reporting.

**Comment by derspanier1** [comment]
> Trying to get wildcards extension to work installed dynamic prompts and installed wildcards in it ..
> 
> Wildcard Manager did show up . I get a drop down list of artists ect. Not sure if it is compatible with SD Next

Dynamic prompts works without a hitch.

**Comment by Aptronymist** [comment]
The best place to report it is just in our discord, though I suppose a Discussion could be created too, we're trying to get through and update for extensions we know, I should be able to push out a list for that today in fact. 
I just created a post in Resources on the discord for people to report extension compatibility, you can't miss it.

**Comment by Aptronymist** [comment]
Okay, I've created a post in Resources on the discord server to report them, some are already coming in, and I've finally merged in the updated list of extensions that work, it should show up in the next update of the extensions that goes through. I'll keep testing them. I will also create a Discussion about this so that people that don't want to use discord can report there.
