### ISSUE TITLE
[Feature]: download & use diffusers models by URL (name/repo format)

### ISSUE THREAD

**Issue by oxysoft** [vladmandic/automatic#1939]
### Feature description

Hi, I already used Diffusers on my machine in other projects and have several models downloaded in the HF format. For example..

```
pipeline = StableDiffusionControlNetPipeline.from_pretrained('SG161222/Paragon_V1.0')
```

I believe these models are downloaded into `$HF_HOME/hub/`, one directory per model, and it would be really convenient if we could use these directly or enter a URL. I believe these also load faster due to safetensors format.

### Version Platform Description

```
app: SD.next
updated: 2023-08-04
hash: 81cfb444
url: https://github.com/vladmandic/automatic/tree/master
```

**Comment by vladmandic** [comment]
You can already do thar, just set diffuser path in settings to where your models reside, sdnext will enumerate them and they can be loaded as usual.

Or move them to default sdnext path for diffuser models, either way.
