### ISSUE TITLE
[Issue]: xformers is automatically installed and used which breaks on non nvidia hardware

### ISSUE THREAD

**Issue by CapsAdmin** [vladmandic/automatic#194]
### Issue Description

To workaround this I have to manually uninstall xformers after activate the venv and remove the code that does it in [setup.py](https://github.com/vladmandic/automatic/blob/master/setup.py#L194-L198)

Otherwise xformers will error when rendering about the device not being supported after sampling. (vae decoding?)

I'm not sure why it's being used though since SDP is the default cross attention optimizer?

**Comment by CapsAdmin** [comment]
Sorry, I should have done that. I'm out traveling and won't have access to my main PC for a whole month so I can't do anything.

**Comment by vladmandic** [comment]
i'll close the issue since i don't want to have it open without activity, but post here once you do have more info and i'll reopen it.

**Comment by vladmandic** [comment]
i understand the issue and how it works is that if `xformers` are not selected, there is actual code that forces unload.
but if something forces re-import, then exactly this happens. i need to nail down where does re-import happen.

i've added re-remove in one common place, hopefully that helps, please test.
