### ISSUE TITLE
[Issue]: Error setting current image: step=19 unsupported operand type(s) for *: 'int' and 'NoneType' + Controlnet installed packages

### ISSUE THREAD

**Issue by hypercryptoman** [vladmandic/automatic#1948]
### Issue Description

Any idea why controlnet installed all new packages? 
![image](https://github.com/vladmandic/automatic/assets/110080854/ee1c88b9-34c2-40cb-a301-455db8d8befd)

 21:57:17-791397 INFO     Extension installed packages: sd-webui-controlnet ['setuptools==60.2.0',
                         'cryptography==41.0.3', 'ordered-set==4.1.0', 'pycryptodome==3.18.0', 'json-tricks==3.17.2',
                         'terminaltables==3.1.10', 'mmdet==3.1.0', 'requests==2.28.2', 'oss2==2.17.0',
                         'aliyun-python-sdk-kms==2.16.1', 'aliyun-python-sdk-core==2.13.36', 'pycocotools==2.0.6',
                         'mmcv==2.0.1', 'shapely==2.0.1', 'xtcocotools==1.13', 'crcmod==1.7', 'munkres==1.1.4',
                         'mmpose==1.1.0', 'chumpy==0.70', 'jmespath==0.10.0', 'tabulate==0.9.0', 'mmengine==0.8.4',
                         'openmim==0.3.9', 'model-index==0.1.11', 'openxlab==0.0.17', 'opendatalab==0.0.10']

Started stable and starting doing some images but i keep getting this error in my logs

![image](https://github.com/vladmandic/automatic/assets/110080854/b281f034-db09-4322-ada2-c204f63ff92b)

22:19:06-100797 ERROR    Error setting current image: step=17 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:07-108866 ERROR    Error setting current image: step=17 unsupported operand type(s) for *: 'int' and 'NoneType'
 47%|██████████████████████████████████████▊                                           | 18/38 [00:47<00:52,  2.61s/it]22:19:08-103128 ERROR    Error setting current image: step=17 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:09-096940 ERROR    Error setting current image: step=18 unsupported operand type(s) for *: 'int' and 'NoneType'
 50%|█████████████████████████████████████████                                         | 19/38 [00:50<00:49,  2.61s/it]22:19:10-106144 ERROR    Error setting current image: step=18 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:11-118289 ERROR    Error setting current image: step=18 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:12-096753 ERROR    Error setting current image: step=19 unsupported operand type(s) for *: 'int' and 'NoneType'
 53%|███████████████████████████████████████████▏                                      | 20/38 [00:52<00:46,  2.61s/it]22:19:13-111473 ERROR    Error setting current image: step=19 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:14-106443 ERROR    Error setting current image: step=20 unsupported operand type(s) for *: 'int' and 'NoneType'
 55%|█████████████████████████████████████████████▎                                    | 21/38 [00:55<00:44,  2.61s/it]22:19:15-096081 ERROR    Error setting current image: step=20 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:16-102075 ERROR    Error setting current image: step=20 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:17-102707 ERROR    Error setting current image: step=21 unsupported operand type(s) for *: 'int' and 'NoneType'
 58%|███████████████████████████████████████████████▍                                  | 22/38 [00:58<00:41,  2.61s/it]22:19:18-097737 ERROR    Error setting current image: step=21 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:19-107162 ERROR    Error setting current image: step=22 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:20-105372 ERROR    Error setting current image: step=22 unsupported operand type(s) for *: 'int' and 'NoneType'
 61%|█████████████████████████████████████████████████▋                                | 23/38 [01:00<00:39,  2.61s/it]22:19:21-101234 ERROR    Error setting current image: step=22 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:22-096991 ERROR    Error setting current image: step=23 unsupported operand type(s) for *: 'int' and 'NoneType'
 63%|███████████████████████████████████████████████████▊                              | 24/38 [01:03<00:36,  2.61s/it]22:19:23-096623 ERROR    Error setting current image: step=23 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:24-110656 ERROR    Error setting current image: step=23 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:25-107072 ERROR    Error setting current image: step=24 unsupported operand type(s) for *: 'int' and 'NoneType'
 66%|█████████████████████████████████████████████████████▉                            | 25/38 [01:05<00:33,  2.61s/it]22:19:26-103765 ERROR    Error setting current image: step=24 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:27-098777 ERROR    Error setting current image: step=25 unsupported operand type(s) for *: 'int' and 'NoneType'
 68%|████████████████████████████████████████████████████████                          | 26/38 [01:08<00:31,  2.61s/it]22:19:28-096364 ERROR    Error setting current image: step=25 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:29-099214 ERROR    Error setting current image: step=25 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:30-104673 ERROR    Error setting current image: step=26 unsupported operand type(s) for *: 'int' and 'NoneType'
 71%|██████████████████████████████████████████████████████████▎                       | 27/38 [01:11<00:28,  2.62s/it]22:19:31-104968 ERROR    Error setting current image: step=26 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:32-101784 ERROR    Error setting current image: step=27 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:33-093513 ERROR    Error setting current image: step=27 unsupported operand type(s) for *: 'int' and 'NoneType'
 74%|████████████████████████████████████████████████████████████▍                     | 28/38 [01:13<00:26,  2.62s/it]22:19:34-104844 ERROR    Error setting current image: step=27 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:35-103382 ERROR    Error setting current image: step=28 unsupported operand type(s) for *: 'int' and 'NoneType'
 76%|██████████████████████████████████████████████████████████████▌                   | 29/38 [01:16<00:23,  2.62s/it]22:19:36-101702 ERROR    Error setting current image: step=28 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:37-093552 ERROR    Error setting current image: step=28 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:38-105650 ERROR    Error setting current image: step=29 unsupported operand type(s) for *: 'int' and 'NoneType'
 79%|████████████████████████████████████████████████████████████████▋                 | 30/38 [01:19<00:20,  2.62s/it]22:19:39-095025 ERROR    Error setting current image: step=29 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:40-104386 ERROR    Error setting current image: step=30 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:41-102800 ERROR    Error setting current image: step=30 unsupported operand type(s) for *: 'int' and 'NoneType'
 82%|██████████████████████████████████████████████████████████████████▉               | 31/38 [01:21<00:18,  2.63s/it]22:19:42-107074 ERROR    Error setting current image: step=30 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:43-105637 ERROR    Error setting current image: step=31 unsupported operand type(s) for *: 'int' and 'NoneType'
 84%|█████████████████████████████████████████████████████████████████████             | 32/38 [01:24<00:15,  2.63s/it]22:19:44-101543 ERROR    Error setting current image: step=31 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:45-107310 ERROR    Error setting current image: step=31 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:46-104976 ERROR    Error setting current image: step=32 unsupported operand type(s) for *: 'int' and 'NoneType'
 87%|███████████████████████████████████████████████████████████████████████▏          | 33/38 [01:26<00:13,  2.63s/it]22:19:47-102343 ERROR    Error setting current image: step=32 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:48-095545 ERROR    Error setting current image: step=33 unsupported operand type(s) for *: 'int' and 'NoneType'
 89%|█████████████████████████████████████████████████████████████████████████▎        | 34/38 [01:29<00:10,  2.62s/it]22:19:49-105150 ERROR    Error setting current image: step=33 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:50-101205 ERROR    Error setting current image: step=33 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:51-100637 ERROR    Error setting current image: step=34 unsupported operand type(s) for *: 'int' and 'NoneType'
 92%|███████████████████████████████████████████████████████████████████████████▌      | 35/38 [01:32<00:07,  2.62s/it]22:19:52-094495 ERROR    Error setting current image: step=34 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:53-105987 ERROR    Error setting current image: step=35 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:54-104328 ERROR    Error setting current image: step=35 unsupported operand type(s) for *: 'int' and 'NoneType'
 95%|█████████████████████████████████████████████████████████████████████████████▋    | 36/38 [01:34<00:05,  2.62s/it]22:19:55-100963 ERROR    Error setting current image: step=35 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:56-094346 ERROR    Error setting current image: step=36 unsupported operand type(s) for *: 'int' and 'NoneType'
 97%|███████████████████████████████████████████████████████████████████████████████▊  | 37/38 [01:37<00:02,  2.62s/it]22:19:57-107775 ERROR    Error setting current image: step=36 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:58-107584 ERROR    Error setting current image: step=36 unsupported operand type(s) for *: 'int' and 'NoneType'
22:19:59-104075 ERROR    Error setting current image: step=37 unsupported operand type(s) for *: 'int' and 'NoneType'
100%|██████████████████████████████████████████████████████████████████████████████████| 38/38 [01:40<00:00,  2.63s/it]
22:20:00-101100 ERROR    Error setting current image: step=37 unsupported operand type(s) for *: 'int' and 'NoneType'
22:20:01-096063 ERROR    Error setting current image: step=37 unsupported operand type(s) for *: 'int' and 'NoneType'
22:20:02-092601 ERROR    Error setting current image: step=37 unsupported operand type(s) for *: 'int' and 'NoneType'

### Version Platform Description

Windows 11

### Relevant log output

```shell
D:\automatic>git pull
remote: Enumerating objects: 24, done.
remote: Counting objects: 100% (24/24), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 24 (delta 14), reused 24 (delta 14), pack-reused 0
Unpacking objects: 100% (24/24), 9.12 KiB | 3.00 KiB/s, done.
From https://github.com/vladmandic/automatic
   4b01e607..e2ee02a1  master     -> origin/master
Fetching submodule extensions-builtin/sd-webui-controlnet
From https://github.com/Mikubill/sd-webui-controlnet
   56c376a..4b815cc  main       -> origin/main
Updating 4b01e607..e2ee02a1
Fast-forward
 extensions-builtin/sd-extension-system-info |  2 +-
 extensions-builtin/sd-webui-controlnet      |  2 +-
 modules/api/api.py                          |  2 +-
 modules/processing.py                       |  3 +-
 modules/sd_models.py                        | 10 ++--
 modules/sd_samplers.py                      |  4 +-
 modules/sd_samplers_common.py               | 21 +++----
 modules/sd_vae_taesd.py                     | 88 ---------------------------
 modules/shared.py                           | 28 ++++++---
 modules/taesd/sd_vae_taesd.py               | 57 ++++++++++++++++++
 modules/taesd/taesd.py                      | 93 +++++++++++++++++++++++++++++
 modules/txt2img.py                          |  5 +-
 modules/ui.py                               |  2 +
 webui.py                                    |  3 +
 14 files changed, 201 insertions(+), 119 deletions(-)
 delete mode 100644 modules/sd_vae_taesd.py
 create mode 100644 modules/taesd/sd_vae_taesd.py
 create mode 100644 modules/taesd/taesd.py
Using VENV: D:\automatic\venv
21:46:53-305736 INFO     Starting SD.Next
21:46:53-425380 INFO     Python 3.10.6 on Windows
21:46:53-549878 INFO     Version: e2ee02a1 Sat Aug 5 09:38:11 2023 +0200
21:46:55-758009 INFO     nVidia CUDA toolkit detected
21:46:57-587670 WARNING  Modified files: ['modules/lora', 'modules/lycoris', 'webui.bat', '.venv/']
21:47:00-630576 INFO     Disabled extensions: ['sd-webui-fabric', 'Mask2Background', 'TemporalKit',
                         'a1111-sd-webui-lycoris', 'sd-webui-comfyui', 'stable-diffusion-webui-aesthetic-image-scorer']
21:47:00-633536 INFO     Enabled extensions-builtin: ['clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
21:47:00-968649 INFO     Enabled extensions: ['adetailer', 'deforum-for-automatic1111-webui', 'loopback_scaler',
                         'sd-webui-faceswaplab', 'sd-webui-lora-block-weight', 'sd-webui-roop-uncensored',
                         'sd-webui-supermerger', 'Stable-Diffusion-Webui-Civitai-Helper',
                         'stable-diffusion-webui-depthmap-script', 'ultimate-upscale-for-automatic1111']
21:47:01-526222 INFO     Verifying requirements
21:47:01-586830 WARNING  Package wrong version: pydantic 1.10.9 required 1.10.11
21:47:01-588790 INFO     Installing package: pydantic==1.10.11
21:47:28-909177 INFO     Verifying packages
21:47:28-913178 INFO     Verifying repositories
21:47:39-575042 INFO     Verifying submodules
21:57:17-791397 INFO     Extension installed packages: sd-webui-controlnet ['setuptools==60.2.0',
                         'cryptography==41.0.3', 'ordered-set==4.1.0', 'pycryptodome==3.18.0', 'json-tricks==3.17.2',
                         'terminaltables==3.1.10', 'mmdet==3.1.0', 'requests==2.28.2', 'oss2==2.17.0',
                         'aliyun-python-sdk-kms==2.16.1', 'aliyun-python-sdk-core==2.13.36', 'pycocotools==2.0.6',
                         'mmcv==2.0.1', 'shapely==2.0.1', 'xtcocotools==1.13', 'crcmod==1.7', 'munkres==1.1.4',
                         'mmpose==1.1.0', 'chumpy==0.70', 'jmespath==0.10.0', 'tabulate==0.9.0', 'mmengine==0.8.4',
                         'openmim==0.3.9', 'model-index==0.1.11', 'openxlab==0.0.17', 'opendatalab==0.0.10']
21:57:42-896359 INFO     Extension installed packages: sd-webui-faceswaplab ['onnxruntime==1.15.1']
21:58:02-113556 INFO     Extension installed packages: sd-webui-roop-uncensored ['onnxruntime==1.15.0']
21:58:12-098865 INFO     Extensions enabled: ['clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR', 'adetailer',
                         'deforum-for-automatic1111-webui', 'loopback_scaler', 'sd-webui-faceswaplab',
                         'sd-webui-lora-block-weight', 'sd-webui-roop-uncensored', 'sd-webui-supermerger',
                         'Stable-Diffusion-Webui-Civitai-Helper', 'stable-diffusion-webui-depthmap-script',
                         'ultimate-upscale-for-automatic1111']
21:58:12-101864 INFO     Verifying packages
21:58:12-861453 INFO     Extension preload: 0.5s D:\automatic\extensions-builtin
21:58:14-158392 INFO     Extension preload: 1.3s D:\automatic\extensions
21:58:14-438570 INFO     Server arguments: ['--medvram']
No module 'xformers'. Proceeding without it.
21:58:45-918108 INFO     Pipeline: Backend.ORIGINAL
21:58:59-158472 INFO     Libraries loaded
21:58:59-161490 INFO     Using data path: D:\automatic
21:58:59-323784 INFO     Available VAEs: D:\automatic\models\VAE 3
21:59:01-622344 INFO     Available models: D:\automatic\models\Stable-diffusion 19
21:59:15-836497 INFO     ControlNet v1.1.237
ControlNet preprocessor location: D:\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
21:59:17-143421 INFO     ControlNet v1.1.237
[-] ADetailer initialized. version: 23.7.11, num models: 12
21:59:38-692209 INFO     Libraries loaded
2023-08-05 21:59:47,172 - roop - INFO - roop v0.0.2-uncensored
2023-08-05 21:59:47,174 - roop - INFO - roop v0.0.2-uncensored
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\automatic\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
21:59:54-966474 INFO     Loading UI theme: name=remilia/Ghostly style=Auto
2023-08-05 21:59:55,570 - FaceSwapLab - INFO - FaceSwapLab v1.2.0 Config :
2023-08-05 22:00:03,662 - FaceSwapLab - INFO - FaceSwapLab config :
2023-08-05 22:00:03,662 - FaceSwapLab - INFO - + MODEL DIR : D:\automatic\models\faceswaplab
2023-08-05 22:00:03,664 - FaceSwapLab - INFO - + MODELS: ['D:\\automatic\\models\\faceswaplab\\inswapper_128.onnx']
2023-08-05 22:00:03,664 - FaceSwapLab - INFO - + FACES DIR : D:\automatic\models\faceswaplab\faces
2023-08-05 22:00:03,664 - FaceSwapLab - INFO - + ANALYZER DIR : D:\automatic\models\faceswaplab\analysers
2023-08-05 22:00:04,861 - roop - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/P2Enjoy/sd-webui-roop/
2023-08-05 22:00:05,149 - roop - WARNING - You should at least have one model in models directory, please read the doc here : https://github.com/P2Enjoy/sd-webui-roop/
22:00:07-038649 INFO     Extra network created thumbnails: checkpoints 7
22:00:07-649027 INFO     Extra network created thumbnails: textual inversion 6
*Deforum ControlNet support: enabled*
Running on local URL:  http://127.0.0.1:7860
22:00:23-671743 INFO     Local URL: http://127.0.0.1:7860/
22:00:23-688705 INFO     Initializing middleware
22:00:24-979234 INFO     [AgentScheduler] Task queue is empty
22:00:24-980949 INFO     [AgentScheduler] Registering APIs
22:00:25-497383 INFO     Model metadata saved: D:\automatic\metadata.json 5
Loading weights: D:\automatic\models\Stable-diffusion\divas_v10.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/2.1 GB -:--:--
22:00:36-317461 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: D:\automatic\models\VAE\anythingKlF8Anime2VaeFtMse_vaeFtMse840000Ema.pt ━━━━━━━━╸━━ 130.8/167.4 0:00:00
                                                                                                     MB
22:02:15-207052 INFO     Applying scaled dot product cross attention optimization
22:02:16-004163 INFO     Embeddings: loaded=7 skipped=0
22:02:16-011165 INFO     Model loaded in 110.2s (load=9.6s config=1.0s create=1.1s apply=91.3s vae=6.4s embeddings=0.8s)
22:02:16-453400 INFO     Model load finished: {'ram': {'used': 5.39, 'total': 15.85}, 'gpu': {'used': 0.71, 'total':
                         4.0}, 'retries': 0, 'oom': 0} cached=0
22:02:17-043325 INFO     Startup time: 242.5s (torch=13.1s gradio=5.6s libraries=25.9s vae=0.2s models=2.3s
                         codeformer=0.9s gfpgan=0.9s scripts=50.1s upscalers=0.3s onchange=1.1s extra-networks=0.2s
                         ui-txt2img=9.8s ui-img2img=0.3s ui-settings=0.5s ui-extensions=15.9s ui-defaults=0.1s
                         launch=2.5s app-started=1.1s checkpoint=111.6s)
22:12:14-330904 INFO     Available models: D:\automatic\models\Stable-diffusion 19
Loading weights: D:\automatic\models\Stable-diffusion\realcartoon3d_v6.safetensors ━━━━━━━━━━━━━━━━━━ 0.0/2.1 GB -:--:--
22:12:25-533903 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: D:\automatic\models\VAE\anythingKlF8Anime2VaeFtMse_vaeFtMse840000Ema.pt ━━━━━━━━╸━━ 130.8/167.4 0:00:00
                                                                                                     MB
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
why does controlnet install all those additional packages, you have to ask controlnet author.
and regarding your error, try running with `--safe` option - right now you have quite a lot of extensions and its impossible to tell how they all interact.

**Comment by hypercryptoman** [comment]
> why does controlnet install all those additional packages, you have to ask controlnet author. and regarding your error, try running with `--safe` option - right now you have quite a lot of extensions and its impossible to tell how they all interact.


D:\automatic>git pull
remote: Enumerating objects: 17, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 9 (delta 8), reused 7 (delta 6), pack-reused 0
Unpacking objects: 100% (9/9), 929 bytes | 0 bytes/s, done.
From https://github.com/vladmandic/automatic
   e2ee02a1..cfe14884  master     -> origin/master
Fetching submodule wiki
From https://github.com/vladmandic/automatic.wiki
   f76cc3a..35142f0  master     -> origin/master
Updating e2ee02a1..cfe14884
Fast-forward
 CHANGELOG.md                    | 9 +++++++++
 modules/processing.py           | 3 +--
 modules/processing_diffusers.py | 2 --
 modules/txt2img.py              | 5 ++---
 modules/ui.py                   | 2 --
 pyproject.toml                  | 1 +
 wiki                            | 2 +-
 7 files changed, 14 insertions(+), 10 deletions(-)
Using VENV: D:\automatic\venv
22:30:36-342131 INFO     Starting SD.Next
22:30:36-347129 INFO     Python 3.10.6 on Windows
22:30:36-450797 INFO     Version: cfe14884 Sat Aug 5 12:06:56 2023 +0000
22:30:37-769352 INFO     nVidia CUDA toolkit detected
22:30:38-610240 WARNING  Modified files: ['modules/lora', 'modules/lycoris', 'webui.bat', '.venv/']
22:30:41-514562 INFO     Disabled extensions: ['sd-webui-fabric', 'Mask2Background', 'TemporalKit',
                         'a1111-sd-webui-lycoris', 'sd-webui-comfyui', 'stable-diffusion-webui-aesthetic-image-scorer']
22:30:41-517560 INFO     Enabled extensions-builtin: ['clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
22:30:41-534565 INFO     Verifying requirements
22:30:41-598853 WARNING  Package wrong version: requests 2.28.2 required 2.31.0
22:30:41-601478 INFO     Installing package: requests==2.31.0
22:31:01-752348 INFO     Verifying packages
22:31:01-755390 INFO     Verifying repositories
22:31:11-759869 INFO     Verifying submodules
22:32:28-844112 INFO     Extensions enabled: ['clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
22:32:28-847074 INFO     Verifying packages
22:32:28-850557 INFO     Running in safe mode without user extensions
22:32:28-957684 INFO     Extension preload: 0.1s D:\automatic\extensions-builtin
22:32:29-096299 INFO     Server arguments: ['--medvram', '--safe']
No module 'xformers'. Proceeding without it.
22:33:02-428261 INFO     Pipeline: Backend.ORIGINAL
22:33:09-249357 INFO     Libraries loaded
22:33:09-251317 INFO     Using data path: D:\automatic
22:33:09-259357 INFO     Available VAEs: D:\automatic\models\VAE 3
22:33:09-755557 INFO     Available models: D:\automatic\models\Stable-diffusion 19
22:33:18-429790 INFO     ControlNet v1.1.237
ControlNet preprocessor location: D:\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
22:33:19-529822 INFO     ControlNet v1.1.237
22:33:27-372629 INFO     Loading UI theme: name=remilia/Ghostly style=Auto
22:33:27-971695 INFO     Extra network created thumbnails: checkpoints 0
Running on local URL:  http://127.0.0.1:7860
22:33:36-201310 INFO     Local URL: http://127.0.0.1:7860/
22:33:36-204355 INFO     Initializing middleware
22:33:36-617654 INFO     [AgentScheduler] Task queue is empty
22:33:36-620051 INFO     [AgentScheduler] Registering APIs
Loading weights: D:\automatic\models\Stable-diffusion\realcartoon3d_v6.safetensors ━━━━━━━━━━━━━━━━━━ 0.0/2.1 GB -:--:--
22:33:44-214283 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: D:\automatic\models\VAE\anythingKlF8Anime2VaeFtMse_vaeFtMse840000Ema.pt ━━━━━━━━╸━━ 130.8/167.4 0:00:00
                                                                                                     MB
22:36:05-854100 INFO     Applying scaled dot product cross attention optimization
22:36:06-152703 INFO     Embeddings: loaded=7 skipped=0
22:36:06-158649 INFO     Model loaded in 149.1s (load=7.1s config=0.1s create=3.3s apply=133.3s vae=5.0s
                         embeddings=0.3s)
22:36:06-453836 INFO     Model load finished: {'ram': {'used': 5.22, 'total': 15.85}, 'gpu': {'used': 0.71, 'total':
                         4.0}, 'retries': 0, 'oom': 0} cached=0
22:36:06-950109 INFO     Startup time: 217.8s (torch=11.6s gradio=11.0s libraries=17.5s models=0.5s codeformer=0.5s
                         gfpgan=0.1s scripts=14.2s upscalers=0.1s onchange=2.6s extra-networks=0.1s ui-txt2img=1.1s
                         ui-img2img=0.2s ui-settings=0.1s ui-extensions=6.2s ui-defaults=0.1s launch=1.0s
                         app-started=0.6s checkpoint=150.1s)
Loading weights: D:\automatic\models\Lora\onoff4.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/75.7 MB -:--:--
Loading weights: D:\automatic\models\Lora\lkjshay-10.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/37.9 MB -:--:--
  5%|████▎                                                                              | 2/38 [00:14<03:49,  6.38s/it]22:36:23-095044 ERROR    Error setting current image: step=1 unsupported operand type(s) for *: 'int' and 'NoneType'
22:36:24-112730 ERROR    Error setting current image: step=1 unsupported operand type(s) for *: 'int' and 'NoneType'
22:36:25-103077 ERROR    Error setting current image: step=1 unsupported operand type(s) for *: 'int' and 'NoneType'
  8%|██████▌                                                                            | 3/38 [00:16<02:42,  4.63s/it]22:36:26-098599 ERROR    Error setting current image: step=2 unsupported operand type(s) for *: 'int' and 'NoneType'
22:36:27-096782 ERROR    Error setting current image: step=2 unsupported operand type(s) for *: 'int' and 'NoneType'
 11%|████████▋                                                                          | 4/38 [00:19<02:09,  3.82s/it]22:36:28-094765 ERROR    Error setting current image: step=3 unsupported operand type(s) for *: 'int' and 'NoneType'
22:36:29-107199 ERROR    Error setting current image: step=3 unsupported operand type(s) for *: 'int' and 'NoneType'
22:36:30-102408 ERROR    Error setting current image: step=3 unsupported operand type(s) for *: 'int' and 'NoneType'
 13%|██████████▉                                                                        | 5/38 [00:22<01:51,  3.37s/it]22:36:31-109914 ERROR    Error setting current image: step=4 unsupported operand type(s) for *: 'int' and 'NoneType'
22:36:32-104086 ERROR    Error setting current image: step=4 unsupported operand type(s) for *: 'int' and 'NoneType'
 16%|█████████████                                                                      | 6/38 [00:24<01:39,  3.10s/it]22:36:33-101495 ERROR    Error setting current image: step=5 unsupported operand type(s) for *: 'int' and 'NoneType'
22:36:34-101562 ERROR    Error setting current image: step=5 unsupported operand type(s) for *: 'int' and 'NoneType'
22:36:35-096280 ERROR    Error setting current image: step=5 unsupported operand type(s) for *: 'int' and 'NoneType'
 18%|███████████████▎                                                                   | 7/38 [00:27<01:30,  2.93s/it]22:36:36-110029 ERROR    Error setting current image: step=6 unsupported operand type(s) for *: 'int' and 'NoneType'
22:36:37-097442 ERROR    Error setting current image: step=6 unsupported operand type(s) for *: 'int' and 'NoneType'
22:36:38-093979 ERROR    Error setting current image: step=6 unsupported operand type(s) for *: 'int' and 'NoneType'
 21%|█████████████████▍                                                                 | 8/38 [00:29<01:24,  2.82s/it]22:36:39-108176 ERROR    Error setting current image: step=7 unsupported operand type(s) for *: 'int' and 'NoneType'
22:36:40-107064 ERROR    Error setting current image: step=7 unsupported operand type(s) for *: 'int' and 'NoneType'
 24%|███████████████████▋                                                               | 9/38 [00:32<01:1
 
 
 same issue

**Comment by hypercryptoman** [comment]
possible issue with live preview? not showing anymore

**Comment by hypercryptoman** [comment]
ok problem went away changing TAESD to approx and back when selection again. 

14%|███████████▌                                                                       | 7/50 [00:36<03:42,  5.17s/it]22:56:56-471189 ERROR    Error setting current image: step=6 unsupported operand type(s) for *: 'int' and 'NoneType'
22:56:56-798187 INFO     Settings changed: 3 ['cuda_compile_backend', 'ipex_optimize', 'show_progress_type']
 20%|████████████████▍                                                                 | 10/50 [00:51<03:29,  5.24s/it]22:57:12-448880 INFO     Settings changed: 1 ['show_progress_type']
22:57:15-245839 ERROR    Error setting current image: step=10 unsupported operand type(s) for *: 'int' and 'NoneType'
22:57:15-819839 ERROR    Error setting current image: step=10 unsupported operand type(s) for *: 'int' and 'NoneType'
22:57:16-378843 ERROR    Error setting current image: step=10 unsupported operand type(s) for *: 'int' and 'NoneType'

**Comment by mart-hill** [comment]
For me also TAESD preview throws these errors, so I'll turn it off for the time being. :)

**Comment by sullenfish** [comment]
Same on my M1 Max.

**Comment by steffenr** [comment]
@sullenfish 
Had the same error on Mac M2 Max. The issue seems to be related to the **TAESD** Preview method. After setting it to **Approximate NN** the error is gone.

**Comment by SAC020** [comment]
> @sullenfish Had the same error on Mac M2 Max. The issue seems to be related to the **TAESD** Preview method. After setting it to **Approximate NN** the error is gone.

same issue, same fix. thanks!

**Comment by vladmandic** [comment]
i'll check taesd.

**Comment by vladmandic** [comment]
fixed taesd for original backend
