### ISSUE TITLE
[Feature request]: Support onnxruntime>=0.15.0 requires numpy >= 1.24.2 requires tensorflow >= 2.13.0 

### ISSUE THREAD

**Issue by glucauze** [vladmandic/automatic#1954]
### Issue Description

To support onnxruntime-gpu >= 0.15.0 it requires numpy >= 1.24.2

Changing numpy versions breaks tensorflow dependency. It should be upgraded to tensorflow >= 2.13.0

Support onnxruntime-gpu would be great to improve performance on some extensions.

I don't think it breaks other things.

### Version Platform Description

Manjaro, python 3.11

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
I'll check on overall compatibility, but please requalify this as feature/enhancement, it's not an issue.

**Comment by glucauze** [comment]
thx

**Comment by vladmandic** [comment]
implemented in dev (although dev is not stable at the moment, but that's a separate story)
