### ISSUE TITLE
[Feature]: Enable XYZ script to work with Kohya additional networks

### ISSUE THREAD

**Issue by Nyaster** [vladmandic/automatic#197]
### Issue Description

Where i installed kohhya additional networks its not integrated in xyz script

### Version Platform Description

win11(wsl2 ubuntu)

**Comment by vladmandic** [comment]
be explict how would you like to use xyz script with additional networks?
also, this is not an issue, this is at best a feature request.

**Comment by Nyaster** [comment]
![изображение](https://user-images.githubusercontent.com/43608647/232582239-df578a3a-9b65-4a9e-9b2a-3cf96bd37e1f.png)
Like this/

**Comment by vladmandic** [comment]
Is there any example where XYZ script allows usage of values which are only defined in user extension?

**Comment by Nyaster** [comment]
In original repo?

**Comment by vladmandic** [comment]
that's not the answer. and xyz script here is identical to original repo.

**Comment by vladmandic** [comment]
so its up to extension to register itself with xyz script - that is correct and how it should be done.
but it seems that <https://github.com/kohya-ss/sd-webui-additional-networks> extension is misbehaving here and not registering what it should. i'll look into that - are we ok to close this?

**Comment by Nyaster** [comment]
Yes
