### ISSUE TITLE
[Extension]: Image offset issue while inpainting using Auto-Photoshop-StableDiffusion-Plugin

### ISSUE THREAD

**Issue by dougbtv** [vladmandic/automatic#1974]
### Issue Description

When inpainting with the Auto-Photoshop-StableDiffusion-Plugin, the edge of a resulting image from inpainting.

It's speculated that this may be on the vlad/automatic end and not the stable diffusion end.

Related issues: https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/351
And also reported and fixed in a fork for photopea extension: https://github.com/huchenlei/stable-diffusion-ps-pea/issues/1

![inpaint-offset-problem-sd-photoshop](https://github.com/vladmandic/automatic/assets/5472189/9fb8a809-0e93-4412-adfe-47cbeca2b507)

### Version Platform Description

Vlad version @ latest: https://github.com/vladmandic/automatic/commit/417ef540039e2d89a02cefb4fea2d767a5ba1380
OS/Browser: Windows 11, Chrome

### URL link of the extension

https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin

### URL link of the issue reported in the extension repository

https://github.com/AbdullahAlfaraj/Auto-Photoshop-StableDiffusion-Plugin/issues/351

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
this should be resolved in the dev branch.
