### ISSUE TITLE
[Diffusers]: Lora for SDXL broken

### ISSUE THREAD

**Issue by radry** [vladmandic/automatic#1979]
### Issue Description

When using Lora following error occurs. 2 Weeks ago when Lora support for SDXL was added, it still worked fine.
So some update since that time broke it.

`12:31:03-255567 ERROR    Exception: Tensor on device meta is not on the expected device cuda:0!`

Full log output below.

### Diffusers pipeline used

Stable Diffusion XL

### Version Platform Description

Windows 10
app: SD.next
updated: 2023-08-08
hash: 417ef540

```
12:22:00-969994 INFO     Starting SD.Next
12:22:01-016414 INFO     Python 3.10.6 on Windows
12:22:02-189809 INFO     Version: 417ef540 Tue Aug 8 12:05:30 2023 -0400
12:22:03-049130 INFO     nVidia CUDA toolkit detected
12:22:04-867060 INFO     Verifying requirements
12:22:04-894061 INFO     Verifying packages
12:22:04-897562 INFO     Verifying repositories
12:22:09-014601 INFO     Verifying submodules
12:22:34-933945 INFO     Extensions enabled: ['LDSR', 'Lora', 'ScuNET', 'sd-extension-system-info',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR',
                         'sd-webui-lora-block-weight']
12:22:34-936945 INFO     Verifying packages
12:22:34-938945 INFO     Updating Wiki
12:22:35-758718 INFO     Extension preload: 0.1s G:\_AI\Stable Diffusion\automatic\extensions-builtin
12:22:35-760718 INFO     Extension preload: 0.0s G:\_AI\Stable Diffusion\automatic\extensions
12:22:35-892505 INFO     Server arguments: ['--upgrade', '--skip-extensions', '--autolaunch', '--theme=dark']
12:23:35-864934 INFO     Pipeline: Backend.DIFFUSERS
```

### Relevant log output

```shell
12:31:03-255567 ERROR    Exception: Tensor on device meta is not on the expected device cuda:0!
12:31:03-257569 ERROR    Arguments: args=('task(qmbqs6vg4tds4oz)', 'kl1m ,<lora:kl1m:1.0>', 'ugly, bad art', [], 10, 0,
                         None, False, False, 1, 1, 7, 6, 0.7, 1, -1.0, -1.0, 0, 0, 0, 512, 512, False, 0.7, 2,
                         'Latent', 20, 0, 0, 0.5, '', '', [], 0,
                         'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,
                         0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,
                         0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUT
                         S:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,
                         0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values',
                         '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1',
                         'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,
                         OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False,
                         'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:
                         0\n\nXYZ:::1', False, False, False, False, 'positive', 'comma', 0, False, False, '', 7, '',
                         [], 0, '', [], 0, '', [], True, False, False, False, 0, False,
                         'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,
                         0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,
                         0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUT
                         S:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,
                         0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values',
                         '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1',
                         'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,
                         OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False,
                         'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:
                         0\n\nXYZ:::1', False, False) kwargs={}
12:31:03-290552 ERROR    gradio call: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ G:\_AI\Stable Diffusion\automatic\modules\call_queue.py:34 in f                                                     │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ G:\_AI\Stable Diffusion\automatic\modules\txt2img.py:64 in txt2img                                                  │
│                                                                                                                     │
│   63 │   if processed is None:                                                                                      │
│ > 64 │   │   processed = processing.process_images(p)                                                               │
│   65 │   p.close()                                                                                                  │
│                                                                                                                     │
│                                              ... 19 frames hidden ...                                               │
│                                                                                                                     │
│ G:\_AI\Stable Diffusion\automatic\venv\lib\site-packages\torch\_prims\__init__.py:346 in _elementwise_meta          │
│                                                                                                                     │
│    345 │                                                                                                            │
│ >  346 │   utils.check_same_device(*args_, allow_cpu_scalar_tensors=True)                                           │
│    347 │   utils.check_same_shape(*args_, allow_cpu_scalar_tensors=True)                                            │
│                                                                                                                     │
│ G:\_AI\Stable Diffusion\automatic\venv\lib\site-packages\torch\_prims_common\__init__.py:596 in check_same_device   │
│                                                                                                                     │
│    595 │   │   │   │   )                                                                                            │
│ >  596 │   │   │   │   raise RuntimeError(msg)                                                                      │
│    597 │   │   else:                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: Tensor on device meta is not on the expected device cuda:0!
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by radry** [comment]
Has this been merged with the update from 11.august?

Lora is still broken but with a different error now:

`15:21:59-818887 ERROR    Exception: cannot import name 'ReturnedEmbeddingsType' from 'compel' (G:\_AI\Stable
                         Diffusion\automatic\venv\lib\site-packages\compel\__init__.py)
15:21:59-822386 ERROR    Arguments: args=('task(3y2lpuyvoxnldn5)', 'kl1m,<lora:kl1m:1.0>', 'ugly, bad art', [], 10, 0,
                         None, True, False, False, 1, 1, 7, 6, 0.7, 1, -1.0, -1.0, 0, 0, 0, 1024, 1024, False, 0.7, 2,
                         'Latent', 20, 0, 0, 0.5, '', '', [], 0,
                         'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,
                         0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,
                         0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUT
                         S:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,
                         0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values',
                         '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1',
                         'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,
                         OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False,
                         'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:
                         0\n\nXYZ:::1', False, False, False, False, 'positive', 'comma', 0, False, False, '', 7, '',
                         [], 0, '', [], 0, '', [], True, False, False, False, 0, False,
                         'NONE:0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0\nALL:1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1\nINS:1,1,1,1,0,
                         0,0,0,0,0,0,0,0,0,0,0,0\nIND:1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0\nINALL:1,1,1,1,1,1,1,0,0,0,0,0,
                         0,0,0,0,0\nMIDD:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0\nOUTD:1,0,0,0,0,0,0,0,1,1,1,1,0,0,0,0,0\nOUT
                         S:1,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1\nOUTALL:1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1\nALL0.5:0.5,0.5,
                         0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5', True, 0, 'values',
                         '0,0.25,0.5,0.75,1', 'Block ID', 'IN05-OUT05', 'none', '', '0.5,1',
                         'BASE,IN00,IN01,IN02,IN03,IN04,IN05,IN06,IN07,IN08,IN09,IN10,IN11,M00,OUT00,OUT01,OUT02,OUT03,
                         OUT04,OUT05,OUT06,OUT07,OUT08,OUT09,OUT10,OUT11', 1.0, 'black', '20', False,
                         'ATTNDEEPON:IN05-OUT05:attn:1\n\nATTNDEEPOFF:IN05-OUT05:attn:0\n\nPROJDEEPOFF:IN05-OUT05:proj:
                         0\n\nXYZ:::1', False, False) kwargs={}
15:21:59-852887 ERROR    gradio call: ImportError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ G:\_AI\Stable Diffusion\automatic\modules\call_queue.py:34 in f                                                     │
│                                                                                                                     │
│    33 │   │   │   try:                                                                                              │
│ >  34 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ G:\_AI\Stable Diffusion\automatic\modules\txt2img.py:65 in txt2img                                                  │
│                                                                                                                     │
│   64 │   if processed is None:                                                                                      │
│ > 65 │   │   processed = processing.process_images(p)                                                               │
│   66 │   p.close()                                                                                                  │
│                                                                                                                     │
│ G:\_AI\Stable Diffusion\automatic\modules\processing.py:565 in process_images                                       │
│                                                                                                                     │
│    564 │   │   else:                                                                                                │
│ >  565 │   │   │   res = process_images_inner(p)                                                                    │
│    566 │   finally:                                                                                                 │
│                                                                                                                     │
│ G:\_AI\Stable Diffusion\automatic\modules\processing.py:708 in process_images_inner                                 │
│                                                                                                                     │
│    707 │   │   │   elif shared.backend == shared.Backend.DIFFUSERS:                                                 │
│ >  708 │   │   │   │   from modules.processing_diffusers import process_diffusers                                   │
│    709 │   │   │   │   x_samples_ddim = process_diffusers(p, p.seeds, p.prompts, p.negative_pro                     │
│                                                                                                                     │
│ G:\_AI\Stable Diffusion\automatic\modules\processing_diffusers.py:13 in <module>                                    │
│                                                                                                                     │
│    12 from modules.processing import StableDiffusionProcessing                                                      │
│ >  13 import modules.prompt_parser_diffusers as prompt_parser_diffusers                                             │
│    14                                                                                                               │
│                                                                                                                     │
│ G:\_AI\Stable Diffusion\automatic\modules\prompt_parser_diffusers.py:5 in <module>                                  │
│                                                                                                                     │
│     4 import diffusers                                                                                              │
│ >   5 from compel import Compel, ReturnedEmbeddingsType                                                             │
│     6 import modules.shared as shared                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ImportError: cannot import name 'ReturnedEmbeddingsType' from 'compel' (G:\_AI\Stable
Diffusion\automatic\venv\lib\site-packages\compel\__init__.py)`

**Comment by vladmandic** [comment]
nothing to do with lora, uninstall `compel` so installer can install a correct one. as soon as author adds a new version tag, installer will be able to handle it automatically, but for the moment, its manual since cannot compare installed version with target version.
