### ISSUE TITLE
[Feature]: Allow to select separate styles for refiner

### ISSUE THREAD

**Issue by Olivmamman** [vladmandic/automatic#1990]
### Feature description

Currently the refiner only allows for writing a manual prompt; positive and negative.
Found under "Second pass".
Workflow could be much faster with a dropdown accessing your styles in the "styles.csv".

![Screenshot_801](https://github.com/vladmandic/automatic/assets/142082309/fe00eed5-0904-4b7a-8969-defab49debae)

**Comment by Olivmamman** [comment]
Made a workaround by configuring the "ui-config.jason" file by adding:

```
"txt2img/Secondary Prompt/value": "RAW photo, subject, 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3",
"txt2img/Secondary negative prompt/value": "(deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime, mutated hands and fingers:1.4), (deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation, UnrealisticDream"
```

Using Realistic Vision as refiner model and above is its recommended prompt :D

Is there any list of UI items?
Right now I just bruteforced e.g. guessed with some trial and error what it could be.
Looked in "models\ui.py" and found something similar but not written exactly as what I ended up with in the "ui-config.jason".

Edit: sorry for not understanding github ui... :/

**Comment by vladmandic** [comment]
Any UI setting (including prompts) you can change, you can also apply as default (in settings) and then it creates UI-config.json - so your workaround can be muuuch easier.

Regarding feature request in general, I agree and it's planned (actually a much larger change to replace current styles completely)

**Comment by Olivmamman** [comment]
> Any UI setting (including prompts) you can change, you can also apply as default (in settings) and then it creates UI-config.json - so your workaround can be muuuch easier.
> 
> Regarding feature request in general, I agree and it's planned (actually a much larger change to replace current styles completely)

oooooh... makes sense!
Sorry for overlooking this fundamental part of the settings, have totally missed it!

Many thanks for taking your time answering and working on SDnext, truly awesome! 👍

**Comment by vladmandic** [comment]
further work will be tracked under #800, closing
