### ISSUE TITLE
[Feature]: Allow to change refiner model under Second pass

### ISSUE THREAD

**Issue by Olivmamman** [vladmandic/automatic#1991]
### Feature description

Currently the refiner is selected in the Settings menu.

Workflow would be faster and allow for more creativity if the refiner model can be switched within the Second pass sub-menu.
Currently we are limited by sending the image to "From Image" tab, then change Checkpoint.
Putting it in Second pass would streamline it significantly!

![image](https://github.com/vladmandic/automatic/assets/142082309/50fb9355-e860-466d-a017-70ee7fe9e8ce)

**Comment by vladmandic** [comment]
Refiner is just like a model, and it's loaded in global settings.
You can always add it's pull down to quicksettings (just like model is there by default).
