### ISSUE TITLE
[Issue]:  bitsandbytes 0.35.4 keeps being unistalled, can;t use 8bit optimasers for traning with dreambooth

### ISSUE THREAD

**Issue by Deniryer** [vladmandic/automatic#1992]
### Issue Description

Like in tile, after last update webUI started to uninstall bitsandbytes due to being "not used", which resulted in being unable to use any other optimisations than dAdaptation ones which uses over 24GB (start using RAM, which results in 6-7sec/it) regardless of setting.

### Version Platform Description

Win 11 latest mainstream build
Firefox 115.0
AMD 7900X
32GB RAM CL40
RTX4090
Driver ver. 536.99
Starting SD.Next
Python 3.10.9 on Windows
Version: 69eaf4c6 Sat Aug 12 08:32:19 2023 +0000
nVidia CUDA toolkit detected
Disabled extensions: []
  Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
1Enabled extensions: ['adetailer', 'sd-webui-infinite-image-browsing', 'sd-webui-supermerger',
                         'sd_dreambooth_extension']

### Relevant log output

```shell
14:21:27-393766 INFO     Verifying requirements
14:21:27-402273 WARNING  Package wrong version: accelerate 0.19.0 required 0.20.3
14:21:27-403273 INFO     Installing package: accelerate==0.20.3
14:21:29-295224 WARNING  Package wrong version: diffusers 0.16.1 required 0.19.3
14:21:29-296221 INFO     Installing package: diffusers==0.19.3
14:21:32-220001 WARNING  Package wrong version: transformers 4.30.2 required 4.31.0
14:21:32-221000 INFO     Installing package: transformers==4.31.0
14:21:42-593735 INFO     Verifying packages
14:21:42-594736 INFO     Verifying repositories
14:21:45-812419 INFO     Verifying submodules
14:22:19-826422 INFO     Extension installed packages: sd_dreambooth_extension ['transformers==4.30.2',
                         'bitsandbytes==0.35.4', 'accelerate==0.19.0', 'diffusers==0.16.1']
14:22:19-827372 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR', 'adetailer',
                         'sd-webui-infinite-image-browsing', 'sd-webui-supermerger', 'sd_dreambooth_extension']
14:22:19-828372 INFO     Verifying packages
14:22:19-829372 WARNING  Not used, uninstalling: bitsandbytes 0.35.4
14:22:20-401894 INFO     Extension preload: 0.0s F:\SD\SDNext\automatic\extensions-builtin
14:22:20-403893 INFO     Extension preload: 0.0s F:\SD\SDNext\automatic\extensions
14:22:20-413401 INFO     Server arguments: []
14:22:25-046162 INFO     Pipeline: Backend.ORIGINAL
14:22:25-673022 INFO     Libraries loaded
14:22:25-674020 INFO     Using data path: F:\SD\SDNext\automatic
14:22:25-676599 INFO     Available VAEs: F:\SD\SDNext\automatic\models\VAE 3
14:22:25-697044 INFO     Available models: F:\SD\SDNext\automatic\models\Stable-diffusion 45
14:22:27-149207 INFO     ControlNet v1.1.237
ControlNet v1.1.237
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
i had to do it since lately bitsandbytes because quite problematic where they crash torch if everything is not perfect.

you can set env variable `BITSANDBYTES_PACKAGE` to a package you want to use and installer will be happy to use that.

or you can run `webui --experimental` which basically means "don't touch my packages, i know what i'm doing".
(with that, you can install any version of any package and installer will not try to change it)
