### ISSUE TITLE
cannot import name 'ReturnedEmbeddingsType' from 'compel'

### ISSUE THREAD

**Issue by ExaltedRaddix** [vladmandic/automatic#1995]
### Issue Description

22:22:35-572138 INFO     Embeddings: loaded=0 skipped=6
22:22:35-575136 DEBUG    Script process: ['Agent Scheduler:0.0s']
22:22:35-597214 DEBUG    Script before-process-batch: ['Agent Scheduler:0.0s']
22:22:35-598213 DEBUG    Script process-batch: ['Agent Scheduler:0.0s']
22:22:35-703740 ERROR    Exception: cannot import name 'ReturnedEmbeddingsType' from 'compel'
                         (C:\Users\Johannes\Desktop\Stable_Diffusion\automatic\venv\lib\site-packages\compel\__init__.py
                         )
22:22:35-705740 ERROR    Arguments: args=('task(3i7h6ohk482vuwo)', 'Victor Schauberger, energy, holographic, fantasy,
                         torches, lights, magic lights, mystical, energy, Nature, Photo, glowing, purple, turquoise
                         --hd', '', [], 20, 6, 0, True, False, False, 1, 1, 6, 6, 0.7, 1, -1.0, -1.0, 0, 0, 0, 1024,
                         1536, False, 0.3, 2, 'Latent', 20, 0, 0, 0, '', '', [], 0, False, False, 'positive', 'comma',
                         0, False, False, '', 0, '', [], 0, '', [], 0, '', [], True, False, False, False, 0, False)
                         kwargs={}
22:22:35-708744 ERROR    gradio call: ImportError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\Johannes\Desktop\Stable_Diffusion\automatic\modules\call_queue.py:34 in f                                   │
│                                                                                                                      │
│    33 │   │   │   try:                                                                                               │
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    35 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                      │
│ C:\Users\Johannes\Desktop\Stable_Diffusion\automatic\modules\txt2img.py:65 in txt2img                                │
│                                                                                                                      │
│   64 │   if processed is None:                                                                                       │
│ ❱ 65 │   │   processed = processing.process_images(p)                                                                │
│   66 │   p.close()                                                                                                   │
│                                                                                                                      │
│ C:\Users\Johannes\Desktop\Stable_Diffusion\automatic\modules\processing.py:565 in process_images                     │
│                                                                                                                      │
│    564 │   │   else:                                                                                                 │
│ ❱  565 │   │   │   res = process_images_inner(p)                                                                     │
│    566 │   finally:                                                                                                  │
│                                                                                                                      │
│ C:\Users\Johannes\Desktop\Stable_Diffusion\automatic\modules\processing.py:708 in process_images_inner               │
│                                                                                                                      │
│    707 │   │   │   elif shared.backend == shared.Backend.DIFFUSERS:                                                  │
│ ❱  708 │   │   │   │   from modules.processing_diffusers import process_diffusers                                    │
│    709 │   │   │   │   x_samples_ddim = process_diffusers(p, p.seeds, p.prompts, p.negative_pro                      │
│                                                                                                                      │
│ C:\Users\Johannes\Desktop\Stable_Diffusion\automatic\modules\processing_diffusers.py:13 in <module>                  │
│                                                                                                                      │
│    12 from modules.processing import StableDiffusionProcessing                                                       │
│ ❱  13 import modules.prompt_parser_diffusers as prompt_parser_diffusers                                              │
│    14                                                                                                                │
│                                                                                                                      │
│ C:\Users\Johannes\Desktop\Stable_Diffusion\automatic\modules\prompt_parser_diffusers.py:5 in <module>                │
│                                                                                                                      │
│     4 import diffusers                                                                                               │
│ ❱   5 from compel import Compel, ReturnedEmbeddingsType                                                              │
│     6 import modules.shared as shared                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'ReturnedEmbeddingsType' from 'compel'
(C:\Users\Johannes\Desktop\Stable_Diffusion\automatic\venv\lib\site-packages\compel\__init__.py)

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
uninstall compel so installer can install latest required version.
at the moment its manual since required version is not yet "versioned" by author, as soon as it gets a version tag, then installer will be able to handle it automatically.

**Comment by ExaltedRaddix** [comment]
Thank you, i try it 😁Am 12.08.23, 22:40 schrieb Vladimir Mandic ***@***.***>:

   
  uninstall compel so installer can install latest required version. at the moment its manual since required version is not yet "versioned" by author, as soon as it gets a version tag, then installer will be able to handle it automatically.
