### ISSUE TITLE
[Feature]: img2img Batch > Interrogate image metadata to provide prompt, if no prompt provided

### ISSUE THREAD

**Issue by demoran23** [vladmandic/automatic#1999]
### Feature description

An img2img generation fares much better when a prompt is applied.

When no prompt is specified in an img2img batch, interrogate the image for its metadata and use that as the prompt / negative prompt.

**Comment by Silanda** [comment]
IMO, this should be optional if added as not using a prompt can be deliberate. The results can be better with a prompt, but using the image's original prompt can make upscaling more prone to introducing unwanted results (that's a streetlamp, not a woman, dammit!), especially with tiled upscaling.

**Comment by vladmandic** [comment]
feature to interrogate image in img2img tab has been added in dev branch.
