### ISSUE TITLE
[Extension]: Batch count and size is multiplied by itself using Dynamic prompts

### ISSUE THREAD

**Issue by Olivmamman** [vladmandic/automatic#2000]
### Issue Description

While Dynamic prompts is active the Batch count and size is multiplied by itself resulting in exponential more images.

Batch count: 1 / size: 2 = 4 images
Batch count: 2 / size: 1 = 4 images
Batch count: 2 / size: 2 = 16 images

I have
- Turned off all extensions
- Run UI in safe mode
- Resetting UI to default
- Resetting Settings to default
- Deleted ui-config.jason
- Rebooted the computer
- Removed cookies

Narrowed it down to the Dynamic prompts extension
Also posted the issue on their issue tracker.

**Dynamic prompts inactive**
![Screenshot_814](https://github.com/vladmandic/automatic/assets/142082309/49642572-8f74-4747-ac78-4978feabb40d)

**Dynamic prompts active Batch count: 1 / size: 2 = 4 images**
![Screenshot_812](https://github.com/vladmandic/automatic/assets/142082309/0ac72b4c-7442-4450-bf8b-3f2943e7c23e)

### Version Platform Description

13:56:11-905329 INFO     Starting SD.Next
13:56:11-909318 INFO     Python 3.10.11 on Windows
13:56:11-977138 INFO     Version: 83d1ee77 Sun Aug 13 00:32:03 2023 +0200
13:56:12-799938 INFO     nVidia CUDA toolkit detected
13:56:12-926600 WARNING  Modified files: ['scripts/detect_extension.py']
13:56:12-984446 INFO     Disabled extensions: ['sd-webui-agent-scheduler', 'sd-dynamic-thresholding','multidiffusion-upscaler-for-automatic1111', 'a1111-stable-diffusion-webui-vram-estimator']
13:56:12-987438 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR','Lora', 'ScuNET', 'sd-extension-system-info', 'sd-webui-controlnet','stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR','vae-ft-mse-840000-ema-pruned.ckpt']
13:56:12-996413 INFO     Enabled extensions: ['a1111-sd-webui-tagcomplete', 'adetailer', 'canvas-zoom','sd-dynamic-prompts', 'sd-webui-aspect-ratio-helper', 'sd-webui-infinite-image-browsing','sd-webui-photopea-embed', 'ultimate-upscale-for-automatic1111']

### URL link of the extension

https://github.com/adieyal/sd-dynamic-prompts

### URL link of the issue reported in the extension repository

https://github.com/adieyal/sd-dynamic-prompts/issues/594#issue-1848438546

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by BrentOzar** [comment]
@Olivmamman great job writing up the issue. For other people hitting it, the root cause is this pull request in the extension's repo: https://github.com/adieyal/sd-dynamic-prompts/commit/638d4b1784b95d19b69c54f93aeee987d2c5b0a2

That commit was done just after they released v2.15.0, so you can manually downgrade your Dynamic Prompts extension to 2.15.0: https://github.com/adieyal/sd-dynamic-prompts/releases/tag/v2.15.0

**Comment by vladmandic** [comment]
Btw, I also have to agree with the comment on the issue writeup - great job!

**Comment by vladmandic** [comment]
fixed upstream
