### ISSUE TITLE
[Feature]: Quantized diffusion

### ISSUE THREAD

**Issue by 4eJIoBek1** [vladmandic/automatic#2003]
### Feature description

https://github.com/Xiuyu-Li/q-diffusion

![256841508-fdd995f3-724c-4fac-a772-37b0c02e55b2](https://github.com/vladmandic/automatic/assets/109795993/68ed4de6-69d9-4286-8ecd-21f58ed66c90)

This one provides very good results while decreasing vram usage by 4 times. This will be very good for extremely lowvram users and maybe for sdxl.

There is another one from apple

https://github.com/apple/ml-stable-diffusion#mbp

https://huggingface.co/apple/coreml-stable-diffusion-mixed-bit-palettization
![256841256-c3c0a377-e311-4eea-8038-455a45d719e7 (1)](https://github.com/vladmandic/automatic/assets/109795993/cd21101d-2b8e-46e7-a0c6-5e41993409fc)

**Comment by vladmandic** [comment]
closing here as work will be tracked via <https://github.com/users/vladmandic/projects/4?pane=issue&itemId=42266396>

**Comment by 4eJIoBek1** [comment]
![Screenshot_2023-10-21-20-37-15-197_org bromite bromite](https://github.com/vladmandic/automatic/assets/109795993/9732fde7-64c3-4798-b9c2-3bcd4b7c0173)
Or i dont understand anything?

**Comment by vladmandic** [comment]
i need to sort out github permissions for projects.

**Comment by 4eJIoBek1** [comment]
Yea, its working now, thx
