### ISSUE TITLE
[Feature]: Option to disable the splash screen

### ISSUE THREAD

**Issue by cyatarow** [vladmandic/automatic#2006]
### Feature description

To be honest, I don't really like the splash screen images, so I want an option to disable the screen.

### Version Platform Description

```
Version: fce48be4 Mon Aug 14 07:58:42 2023 +0000
```

**Comment by vladmandic** [comment]
"i don't like" is not a reason to implement a new feature. but feel free to change it on your side, its open source.
or if you want a less visual splash screen, design one - contributions are welcome.

**Comment by lbeltrame** [comment]
Question: does the splash screen effectively hide the UI until it is ready? On some systems, especially when tunneling, it takes quite a while (30+ seconds): this might be a better use-case (assuming the actual UI *works*, though).

**Comment by vladmandic** [comment]
splash screen doesn't have its duration, as soon as ui is ready, it disables spash screen. so yes, thats exact time it takes to initialize ui.
