### ISSUE TITLE
[Issue]: Image Info > Text = UI Freezes

### ISSUE THREAD

**Issue by Arkane** [vladmandic/automatic#201]
### Issue Description

1. Drag / Dropped an image in the image info field
2. Hit the > Text button
3. UI completely freezes, cannot switch tabs or do anything until I reload the page
4. Tried again with a different image, same results

Following error in the console:
```
Traceback (most recent call last):
  File "C:\Stable Diffusion - Vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Stable Diffusion - Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Stable Diffusion - Vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 329
```

### Version Platform Description

Windows 11
Opera GX
Version: d67c1dcb Sun Apr 16 22:06:05 2023 -0400

**Comment by Arkane** [comment]
Force quit through terminal, restarted webui.
Image info tab disappeared, used process image tab instead and tried again, functioned as expected.

Might be a first run issue?

**Comment by Anipsy** [comment]
Not 100% sure if related, but my "Image info" tab disappeared completely as well after running update on default extensions and restarting webui, any way to bring it back?

**Comment by vladmandic** [comment]
see <https://github.com/vladmandic/automatic/discussions/99#discussioncomment-5641294>

**Comment by Arkane** [comment]
Oh wow, crazy timing haha
Issue was fixed in between me using this fork for the first time and opening this thread.

Awesome update 👍 
Loving the fork so far!
Will be trying out the new UI stuff for sure
