### ISSUE TITLE
[Issue]: RuntimeError: The GPU device does not support Double (Float64) operations!

### ISSUE THREAD

**Issue by Indrarup** [vladmandic/automatic#2011]
## **steps to recreate** 

- #### git clone https://github.com/vladmandic/automatic.git
- #### cd automatic
- #### webui.bat --debug  --use-directml

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
cc @Disty0 not sure if this is actual error or missing install. btw, should we add a wiki page for ipex?

**Comment by Disty0** [comment]
ARC GPUs doesn't support Float64 or Double so this is expected on DirectML.

You can try this to use IPEX:
https://blog.nuullll.com/ipex-sd-docker-for-arc-gpu/#/getting-started

**Comment by vladmandic** [comment]
also, if you have ANY chance of using IPEX, its always going to be faster than DirectML.
