### ISSUE TITLE
[Issue]: ERROR    Incompatible Python version: 3.11.0 required 3.[9, 10] - windows

### ISSUE THREAD

**Issue by Deanodirector** [vladmandic/automatic#2013]
### Issue Description

during installation no windows, running webui stops with 

ERROR    Incompatible Python version: 3.11.0 required 3.[9, 10]

I fixed this problem on linux by changing a line in the webui.sh, but I don't know how to fix this in windows. Any help would be appreciated. python 3.10 is installed.

### Version Platform Description

Windows 10

### Relevant log output

```shell
20:43:36-028234 INFO     Starting SD.Next
20:43:36-033238 INFO     Python 3.11.0 on Windows
20:43:36-034240 ERROR    Incompatible Python version: 3.11.0 required 3.[9, 10]
Press any key to continue . . .
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by brknsoul** [comment]
Uninstall Python 3.11, install Python 3.10.11; https://www.python.org/ftp/python/3.10.11/python-3.10.11-amd64.exe

Delete `venv`, run webui.bat.

**Comment by Deanodirector** [comment]
> Uninstall Python 3.11, install Python 3.10.11; https://www.python.org/ftp/python/3.10.11/python-3.10.11-amd64.exe
> 
> Delete `venv` folder, run webui.bat.

I think I need 3.11 for another program. surely there's a line of code I can change somewhere...

**Comment by brknsoul** [comment]
Edit webui.bat, under `@echo off` place `set PYTHON=FULLPATH\python.exe` changing "FULLPATH" to the location of Python 3.10.11

**Comment by vladmandic** [comment]
don't exit `webui.bat` directly ever as it will prevent future upgades.
create `webui-user.bat` or whatever you want and just write lines
```batch
@echo off
set PYTHON=<path_to_your_python.exe>
webui.bat
```

**Comment by Deanodirector** [comment]
thanks!
