### ISSUE TITLE
[Diffusers]: Cannot load SDXL model in diffusers due to low ram.

### ISSUE THREAD

**Issue by Symbiomatrix** [vladmandic/automatic#2015]
### Issue Description

Whenever I attempt to load a SDXL model using the corresponding pipeline, I end up receiving the following error (number of bytes vary).
`Diffusers failed loading model using pipeline: {MODEL} Stable Diffusion XL [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 6553600 bytes.`

Here's what I've learned having debugged this further.
The culprit appears to be order of loading by diffusers, sorta: in `diffusers.pipelines.stable_diffusion.convert_from_ckpt`, `download_from_original_stable_diffusion_ckpt`, line 1371, the entire SDXL model is moved to cpu because accelerate is on `set_module_tensor_to_device(unet, param_name, "cpu", value=param)`. Then, it tops that with the vae a little later, and finally when reaching the tokenizers and text_encoder loads in line ~1550, that's when everything implodes; my guess is, the torch model shift will permit itself to get up to 95% only, but the frozen clip (cpp) has no such reservations, and will happily throw an error because there's not enough space left. If I reverse the load order, the ram reaches 95% but doesn't die.

Having made the necessary code adjustment in diffusers library, the model appears to have loaded successfully (in ~10 minutes). I have absolutely no idea if it's working correctly, but it might be useful to someone.

EDIT: The model runs successfully, ~5 seconds per gen, very nice. Output appears to be in order. Loras probably broken, either many mismatching sizes and complete corruption or incorrect output, depending on model.
Increasing paging memory remains a more effective strategy of handling this problem for now: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/1746

### Diffusers pipeline used

SDXL, no refiner

### Version Platform Description

Windows 10, chrome, RTX 3090, 16gb ram

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
great analysis, i'll see what can be done (although it may be delayed a bit due to my travels)

**Comment by Symbiomatrix** [comment]
A patch for the particular issue has been merged, so the next diffusers release should alleviate this symptom.
https://github.com/huggingface/diffusers/pull/4628
