### ISSUE TITLE
[Issue]: running webui.bat from zip off of github doesn't work, but git clone does, you might what to update the readme to let people know that download it as a zip doesn't work when running webui.bat on windows 11

### ISSUE THREAD

**Issue by ghost** [vladmandic/automatic#2018]
### Issue Description

I have git installed and Python 3.10.11 on Windows, but when I try to use webui.bat its displaying the below error, I used the download zip from here, on windows extracted it then launched the bat file and again below is the end result, I don't have any idea what's broken, I have the easy diffusion installed from its installer, and I was able to download the normal automatic111
sd.webui and run.bat it installed and is working correctly from its download but for whatever reason when I tried this one, even after updating git and Python to current builds it seems to fail as seen below.

Creating venv in directory C:\Users\Robert\Downloads\automatic-master\automatic-master\venv using python "C:\Users\Robert\AppData\Local\Programs\Python\Python310\python.exe"
Using VENV: C:\Users\Robert\Downloads\automatic-master\automatic-master\venv
22:30:25-489338 INFO     Starting SD.Next
22:30:25-489338 INFO     Python 3.10.11 on Windows
22:30:25-504963 ERROR    Not a git repository
Press any key to continue . . .

afterwards I used cmd and did this below.

C:\Users\Robert>git clone https://github.com/vladmandic/automatic batsGUI
Cloning into 'batsGUI'...
remote: Enumerating objects: 29626, done.
remote: Counting objects: 100% (84/84), done.
remote: Compressing objects: 100% (55/55), done.
remote: Total 29626 (delta 41), reused 63 (delta 29), pack-reused 29542
Receiving objects: 100% (29626/29626), 38.09 MiB | 1.39 MiB/s, done.
Resolving deltas: 100% (21182/21182), done.

C:\Users\Robert>

its now working from webui.bat

Creating venv in directory C:\Users\Robert\batsGUI\venv using python "C:\Users\Robert\AppData\Local\Programs\Python\Python310\python.exe"
Using VENV: C:\Users\Robert\batsGUI\venv
22:39:25-553237 INFO     Starting SD.Next
22:39:25-556242 INFO     Python 3.10.11 on Windows
22:39:25-583242 INFO     Version: 79c01311 Tue Aug 15 12:25:08 2023 +0000
22:39:25-608220 INFO     nVidia CUDA toolkit detected
22:39:25-610218 INFO     Installing package: torch torchvision --index-url https://download.pytorch.org/whl/cu118

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by brknsoul** [comment]
It's good then that the installation instructions don't mention downloading a zip file, but rather tells you to run `git clone https://github.com/vladmandic/automatic`
