### ISSUE TITLE
[Issue]: --quick launch option no longer recognized (Or maybe just Documentation needing update?)

### ISSUE THREAD

**Issue by SqueakyZee** [vladmandic/automatic#202]
### Issue Description

After installing commit [d69738cc](https://github.com/vladmandic/automatic/commit/d69738cc0795669b5baaab203e09a6fd5be79f5c), --quick launch option for webui.bat is no longer recognized as valid.
(Note: I was a few commits behind, so commit [d69738cc](https://github.com/vladmandic/automatic/commit/d69738cc0795669b5baaab203e09a6fd5be79f5c) might not have been the actual issue itself)

<details> 
  <summary>Console Log (<i>click to expand</i>)</summary>

```python

venv "D:\Users\SqueakyZee\Programs\Automatic1111\automatic\venv\Scripts\Python.exe"
usage: launch.py [-h] [--no-half] [--no-half-vae] [--precision {full,autocast}] [--medvram] [--lowvram] [--lowram] [--ckpt CKPT] [--vae VAE] [--data-dir DATA_DIR] [--allow-code] [--share]
                 [--enable-insecure] [--use-cpu USE_CPU [USE_CPU ...]] [--listen] [--port PORT] [--hide-ui-dir-config] [--freeze-settings] [--gradio-auth GRADIO_AUTH]
                 [--gradio-auth-path GRADIO_AUTH_PATH] [--autolaunch] [--disable-console-progressbars] [--disable-safe-unpickle] [--api-auth API_AUTH] [--api-log] [--device-id DEVICE_ID]
                 [--cors-origins CORS_ORIGINS] [--cors-regex CORS_REGEX] [--tls-keyfile TLS_KEYFILE] [--tls-certfile TLS_CERTFILE] [--server-name SERVER_NAME] [--no-hashing] [--no-download-sd-model]
                 [--profile] [--debug] [--reset] [--upgrade] [--noupdate] [--skip-requirements] [--skip-extensions]
launch.py: error: unrecognized arguments: --quick
Press any key to continue . . .

```

</details>

### Version Platform Description

System Info:

Python 3.10.8 on Windows 64 Pro 22H2
Commit Version: d69738cc Mon Apr 17 17:39:20 2023 -0400
Torch 2.0.0+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3070 Laptop GPU VRAM 8192 Arch (8, 6) Cores 40

**Comment by SqueakyZee** [comment]
Has it been replaced by --noupdate?

**Comment by SqueakyZee** [comment]
after looking at the code, seems like --quick is the new default launch? If so, then it's just a matter of updating documentation

**Comment by vladmandic** [comment]
documentation needing update. `--quick` is now auto-detected if its possible, cannot be forced.
basically, if time of your last sucessful full setup run is newer than version of the repo, requirements or timestamp of newest extension, quick is assumed.

so if you upgrade repo (either git pull or using `--upgrade`), quick will not be allowed.
same if you install or upgrade extension as it should go through extension installer.

**Comment by SqueakyZee** [comment]
So in this case, which is the proper way to update the repo? I thought it was to run start webui.bat --upgrade but as you said, that way doesn't seem to ever let --quick be assumed so slower startup every time

**Comment by vladmandic** [comment]
`webui --upgrade` is correct way, but you don't want to do that on each start, do you?
altnatively, you could do manual `git pull` and if there is nothing downloaded, `webui` will run in quick mode.

**Comment by SqueakyZee** [comment]
That's what I thought, but even after running "start webui.bat --upgrade" and letting it complete, and then restarting the script with just "start webui.bat" it doesn't seems like --quick is being assumed fully, it takes quite a lot longer to start up rather than using "start webui.bat --noupdate --skip-requirements --skip-extensions"
specifically on the extensions part of startup

**Comment by SqueakyZee** [comment]
I'm just going to stick this here just in case for future reference, but some extensions cause quick launch to never get called. 

In my installation, I narrowed it down to the extension [Additional Networks by kohya-ss (commit: d944d428 (Thu Apr  6 10:42:19 2023))](https://github.com/kohya-ss/sd-webui-additional-networks.git) that was causing the issue for me. (Hence my confusion earlier)

With it installed and enabled, for whatever reason, that extension in particular made the check for quick launch fail every time

**Comment by vladmandic** [comment]
thre is something weird with behavior of that extension in general, its on my todo to investigate it.
you can run with `--skip-extensions` - that will make setup skip step where it updates exention and runs per-extension custom installer (i assume custom installer inside that extension is doing something each time regardless if its needed or not, so extension appears as modified).

**Comment by SqueakyZee** [comment]
~~yeah, just having that extension makes start up take 1000% longer, it's annoying, but I quite like it.~~

After updating to [eb2a36c](https://github.com/vladmandic/automatic/commit/eb2a36cd3a3944587532accfd9b496eb83c05ba2) the extension now isn't blocking quick launch... huh

Though random ERROR in console during "start webui.bat --upgrade" that updated me to [eb2a36c](https://github.com/vladmandic/automatic/commit/eb2a36cd3a3944587532accfd9b496eb83c05ba2) but couldn't see anything else wrong... 

![image](https://user-images.githubusercontent.com/83526556/233110276-6c0beda9-8f65-4067-9bdc-95c270861993.png)

Though I couldn't get it to re-appear on subsequent start ups, both with and without --upgrade flag

So can't repeat the "issue" with the ERROR but was weird, and I feel not worth its own issue...

**Comment by SqueakyZee** [comment]
Possibly, I've been having some internet issues this morning as well. Upgrading to [955b841](https://github.com/vladmandic/automatic/commit/955b841d0fdcb36abc8b91988e6514e966d247c0) showed the random ERROR too but still can't get it to show if I'm not upgrading and actually updating the repo via the --upgrade flag
