### ISSUE TITLE
[Issue]: Img2Img Inpainting Mask Artifacts 

### ISSUE THREAD

**Issue by xedis** [vladmandic/automatic#2020]
### Issue Description

When performing img2img inpainting the following occurs with regard to visible mask vs applied mask

First mask : character right arm(our left) and bottom left corner of the image
![image](https://github.com/vladmandic/automatic/assets/4144634/1bca758c-9804-4418-bd52-3363763d1ce8)
![image](https://github.com/vladmandic/automatic/assets/4144634/93c280c5-19d1-4c7e-9b53-920ee55f8c90)
Next I clicked the undo button 3x times to remove the black mask covering character right arm. Followed by adding new mask to the character's left arm (our right). 
This image was generated after undoing all but the bottom left corner of the original mask created. 
![image](https://github.com/vladmandic/automatic/assets/4144634/6411e853-393c-41af-b2fe-e7997e6f14e6)

Next i hit clear which should completely reset the mask but as we can see below:
![image](https://github.com/vladmandic/automatic/assets/4144634/87fac49d-caa1-4bf8-b84c-df4015628249)

Residual mask remains
Green arrow just to indicate that i did draw some mask down there to cover up the watermark on the image. 

Interestingly enough, when i clear the mask and do not apply any additional mask following the undo/clear 

![image](https://github.com/vladmandic/automatic/assets/4144634/37d74e1a-d168-41c4-b275-d082e0f1cb2f)
The image shows no residual mask. 

Only for it to return again in the next image i draw a mask to. 
![image](https://github.com/vladmandic/automatic/assets/4144634/848731ab-78b6-4449-871b-f828a81325d8)

Here is the log file, i did start with the below image test since it was already set for diffusers prior just to see if it occurred there as well and it does 
[sdnext-mask.log](https://github.com/vladmandic/automatic/files/12365879/sdnext-mask.log)

![Screenshot_20230816_220004](https://github.com/vladmandic/automatic/assets/4144634/02cd1265-b84e-4643-8851-1c05ac96581e)

Settings remained consistent throughout the testing and only the mask area was manipulated and modified.
![image](https://github.com/vladmandic/automatic/assets/4144634/87389f85-4948-40ec-bb9c-491b7995c328)
![image](https://github.com/vladmandic/automatic/assets/4144634/7b6afa08-51ef-4a5b-a639-a8e5d2fb5641)
![image](https://github.com/vladmandic/automatic/assets/4144634/576e15f9-e2d4-42d5-ba2f-7725da2a3852)

log from --profile
[sdnext-mask.log-profile.txt](https://github.com/vladmandic/automatic/files/12365929/sdnext-mask.log-profile.txt)

### Version Platform Description

root@iusearchbtw 
---------------- 
OS: Arch Linux 
Kernel: 6.4.10-arch1-1 
Uptime: 1 day, 38 mins 
Packages: 1240 (pacman) 
Shell: bash 5.1.16 
Resolution: 4480x1440 
DE: KDE 
WM: KWin 
Theme: [KDE], Adwaita [GTK2/3] 
Icons: [KDE], Adwaita [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 5 3600 (12) @ 3.8GHz [101.4°F] 
GPU: NVIDIA GeForce RTX 3060 
Memory: 16.95GiB / 125.71GiB (13%) 

Using firefox for this testing. I did not attempt to recreate it on vivaldi or chromium.                    
                         

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
can you check if the issue persists?

**Comment by vladmandic** [comment]
any updates?

**Comment by vladmandic** [comment]
@xedis ?

**Comment by xedis** [comment]
Based on recent tests. Issue is no longer present. 
![image](https://github.com/vladmandic/automatic/assets/4144634/96797f01-4973-4645-9cce-ccf1f166e676)
![image](https://github.com/vladmandic/automatic/assets/4144634/2099618b-1674-4beb-8e6b-e18aae9443d5)
