### ISSUE TITLE
[Issue]: VRam problem after loading a model after the other.

### ISSUE THREAD

**Issue by Nyx01** [vladmandic/automatic#2021]
### Issue Description

To the best of my knowledge, this doesn't seem like a diffusor or extension issue.

Everything was working fine until I updated today. I did a git pull and an --upgrade, but this led to the issue. Basically, if I load a model, for example SDXL 1.0, then generate my image, everything will work correctly, and I'll use at most 7.6-8.2gb out of 12gb of vram. But after using one model, and trying to swap to a different one, the original model will unload and vram will drop to >1gb, and then the second model will load and it'll load straight away at 12gb, and trying to generate an image will just cause the server to freeze (I even let it sit for 6 hours or so to see if it was just going very...very slowly). 

![MemoryUsage](https://github.com/vladmandic/automatic/assets/39126005/2140d41b-0818-492c-98bb-7ec2cafb3874)

The only workaround I've found is that I will have to completely shutdown the server, and uncheck "Stable Diffusion checkpoint autoload on server start", then select the model I was trying to switch to. It will work fine again, until I try to swap model again. I tried to run it on --debug, but I didn't notice any warnings or errors before this issue occurs.

This only started happening after updating yesterday.

I've tried a clean installation and it did not help. I've also tried loading with --safe and there was no change.

### Version Platform Description

On Win11, 22H2, using Chrome as my browser.

Platform:
arch: AMD64
cpu: Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.6

Version:
app: SD.next
updated: 2023-08-17
hash: fcff5912
url: https://github.com/vladmandic/automatic/tree/master

Backend:
cuda

Pipeline:
diffusers

Torch:
2.0.1+cu118 Autocast  nohalf

GPU:
device: NVIDIA GeForce RTX 3060 (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8700
driver: 531.79

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
what are your settings -> diffusers?

**Comment by Nyx01** [comment]
![DiffuserSettings](https://github.com/vladmandic/automatic/assets/39126005/089c5bf7-38af-4e95-8021-1349850a060a)

**Comment by vladmandic** [comment]
attention slicing should be enabled only in very specific circumstances, please disable it.

but in general, this is a known issue with pythons memory allocator - it stabilizes on second load due to accelerate handling of internal variables that prevent gc from working correctly) - i'm working with huggingface on optimizations, but i'm not sure if much can be done in the short term.

**Comment by Nyx01** [comment]
Ah, alright. Thanks for the tip. 

I see. Thank you for working on it, hope you'll see some optimization bonuses in the future.

**Comment by vladmandic** [comment]
just fyi, on linux issue can be mitigated by switching internal memory allocator from default to `tcmalloc` which works much better with gc routines. but on windows, switching memory allocator is not possible.
