### ISSUE TITLE
[Issue]: Error extension update - CLIP Interrogator

### ISSUE THREAD

**Issue by landrasss** [vladmandic/automatic#2032]
### Issue Description

Hello, I get an error in the console when updating my extensions, specifically it has to do with CLIP Interrogator. This is what appears to me:

ERROR    extensions check update: clip-interrogator-ext: TypeError
TypeError: Cannot handle reference type: "'c0bf90052a14a104b2dbfd9b7e7818aae5ca5ae1'"

Cheers.

### Version Platform Description

Starting SD.Next
Python 3.10.6 on Windows
Version: 05c3bd07 Fri Aug 18 16:57:14 2023 +0300
nVidia CUDA toolkit detected
Disabled extensions: []
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
Enabled extensions: ['a1111-sd-webui-tagcomplete', 'adetailer', 'sd-webui-reactor']

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
i cannot reproduce.
can you run
```batch
cd extensions-builtin/clip-interrogator-ext/
git log
```
and post 10 lines.

**Comment by landrasss** [comment]
`commit 6e31272e14308b4918f9785b1dda7cc1149e8838 (HEAD -> main, origin/main, origin/HEAD)
Author: Dahvikiin <61070238+Dahvikiin@users.noreply.github.com>
Date:   Wed May 31 16:03:50 2023 -0300

    Update clip_interrogator_ext.py

    fix typ0

commit dfb3098f1a1b51f4a6c6449dea4eb5227e05018a
Author: Dahvikiin <61070238+Dahvikiin@users.noreply.github.com>
Date:   Wed May 31 16:01:48 2023 -0300

    Update README.md

    better description

commit edfbf3759f7ddac0110348ff5ddf3f9e7410f43a
Author: Dahvikiin <61070238+Dahvikiin@users.noreply.github.com>
Date:   Wed May 31 15:57:30 2023 -0300

    Add files via upload

    UI

commit fb75484576b240d65b9f18b5b00e43e35fe16d06
Author: Dahvikiin <61070238+Dahvikiin@users.noreply.github.com>
Date:   Wed May 31 15:48:23 2023 -0300

    Update
:`

**Comment by vladmandic** [comment]
thats the correct version and there are no updates - not sure why update is complaining.

**Comment by landrasss** [comment]
What happens is that in the extensions tab, it is always with the update icon

![CLIP interrogator](https://github.com/vladmandic/automatic/assets/112908884/0eff01bf-763b-4188-a69c-7d317f8517f8)

And when I click update, it gives me the following error in the console (Full code):

19:15:47-267312 ERROR    Extensions update failed: clip-interrogator-ext
19:15:47-269315 ERROR    extensions check update: clip-interrogator-ext: TypeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\*****\*****\*****\*****\automatic\modules\ui_extensions.py:229 in update_extension                  │
│                                                                                                                     │
│   228 │   │   try:                                                                                                  │
│ > 229 │   │   │   ext.check_updates()                                                                               │
│   230 │   │   │   if ext.can_update:                                                                                │
│                                                                                                                     │
│ C:\Users\*****\*****\*****\*****\automatic\modules\extensions.py:95 in check_updates                         │
│                                                                                                                     │
│    94 │   │   │   return                                                                                            │
│ >  95 │   │   for fetch in repo.remote().fetch(dry_run=True):                                                       │
│    96 │   │   │   if fetch.flags != fetch.HEAD_UPTODATE:                                                            │
│                                                                                                                     │
│ C:\Users\*****\*****\*****\*****\automatic\venv\lib\site-packages\git\remote.py:1015 in fetch                │
│                                                                                                                     │
│   1014 │   │   )                                                                                                    │
│ > 1015 │   │   res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_a                     │
│   1016 │   │   if hasattr(self.repo.odb, "update_cache"):                                                           │
│                                                                                                                     │
│ C:\Users\*****\******\*****\*****\automatic\venv\lib\site-packages\git\remote.py:889 in                       │
│ _get_fetch_info_from_stderr                                                                                         │
│                                                                                                                     │
│    888 │   │   │   try:                                                                                             │
│ >  889 │   │   │   │   output.append(FetchInfo._from_line(self.repo, err_line, fetch_line))                         │
│    890 │   │   │   except ValueError as exc:                                                                        │
│                                                                                                                     │
│ C:\Users\*****\*****\*****\*****\automatic\venv\lib\site-packages\git\remote.py:484 in _from_line            │
│                                                                                                                     │
│    483 │   │   else:                                                                                                │
│ >  484 │   │   │   raise TypeError("Cannot handle reference type: %r" % ref_type_name)                              │
│    485 │   │   # END handle ref type                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: Cannot handle reference type: "'c0bf90052a14a104b2dbfd9b7e7818aae5ca5ae1'"

PD: The extension URL is https://github.com/pharmapsychotic/clip-interrogator-ext, is this the correct repo?

**Comment by vladmandic** [comment]
its not. repo switch has been performed quite a while ago.
see post from july 10th for solution: <https://github.com/vladmandic/automatic/discussions/1627#discussioncomment-6398573>
