### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by brentjohnston** [vladmandic/automatic#2033]
### Issue Description

Can't tell if refiner being used or not for sdxl 1.0. I selected the refiner under settings.

I see no difference between no refiner and the refiner so it makes me think it's not being used? Do I need to select "second pass" I though that the refiner was supposed to work half way through the generation? Thanks!

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by brentjohnston** [comment]
I'm new to this as are many others. I'm actually new to github also. So the issue is for me is it's not very user friendly or clear that it's actually using the refinder. I follow all of the instructions and looked at wiki but it's not very clear. I will try the fooocus github now, Thanks!

**Comment by vladmandic** [comment]
just read this paragraph: <https://github.com/vladmandic/automatic/wiki/SD-XL#using-sd-xl-refiner>
