### ISSUE TITLE
[Issue]: config.json is just one big string

### ISSUE THREAD

**Issue by demoran23** [vladmandic/automatic#2037]
### Issue Description

The contents of config.json is just one big string.  It should be formatted as json, not a string with escaped json inside of it.

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
its fixed in dev, will be merged with master soon.
