### ISSUE TITLE
[Issue]: How to install with Python 3.11?

### ISSUE THREAD

**Issue by bbecausereasonss** [vladmandic/automatic#2038]
### Issue Description

I have 3.11 in my system. Is it possible to get it to create a venv with Python 3.10? 

### Relevant log output

```shell
Creating venv in directory C:\Users\vdrut\Deep\automatic\venv using python "C:\Users\xxxx\AppData\Local\Programs\Python\Python311\python.exe"
Using VENV: C:\Users\vdrut\Deep\automatic\venv
07:57:11-493771 INFO     Starting SD.Next
07:57:11-500770 INFO     Python 3.11.4 on Windows
07:57:11-501772 ERROR    Incompatible Python version: 3.11.4 required 3.[9, 10]
Press any key to continue . . .
```

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
this is not an issue as it clearly states that its not compatible.
and topic has been covered in some details several times - i suggest to search in discussions for "python 3.11" and if you still need help, then create a discussion topic, not an issue.
