### ISSUE TITLE
[Issue]: text2Img tab in Image Browser doesn't seem to be loading

### ISSUE THREAD

**Issue by SqueakyZee** [vladmandic/automatic#204]
### Issue Description

After updating to commit [d69738cc](https://github.com/vladmandic/automatic/commit/d69738cc0795669b5baaab203e09a6fd5be79f5c), within the Image Browser tab added by the extension, the txt2img tab isn't initializing the load of images like the other tabs do. 

At first I thought it was just a folder path issue, but if you click "Open images output directory" within that txt2img tab (the little folder icon), it correctly recognizes the output folder and properly opens the outputs/text folder in windows explorer. 

No error in console or anything. All the other tabs within Image Browser appear to be working correctly. 
I also disabled all user installed extensions and restarted, the issue persisted.

### Version Platform Description

System Info:

Python 3.10.8 on Windows 64 Pro 22H2
Commit Version: d69738cc Mon Apr 17 17:39:20 2023 -0400
Torch 2.0.0+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3070 Laptop GPU VRAM 8192 Arch (8, 6) Cores 40

**Comment by vladmandic** [comment]
so, this is explictly related to extension `image browser`? if so, open issue there please.

**Comment by vladmandic** [comment]
image info functionality is still there, see <https://github.com/vladmandic/automatic/discussions/99#discussioncomment-5641294>

**Comment by SqueakyZee** [comment]
Ahhh, okay, so you just now stick the image there, then click the =>text, etc buttons right under the picture, I was confused, but now I understand. Thanks for your help

**Comment by vladmandic** [comment]
yup. i just didn't see the point of a separate tab that was doing one thing only.
