### ISSUE TITLE
[Issue]: Config file doesn't save in the proper json format.

### ISSUE THREAD

**Issue by xarathos517** [vladmandic/automatic#2040]
### Issue Description

I'm trying to work out if this is an issue with my configuration because I've installed the app through StabilityMatrix or what else is going on. But here's the long and the short of what's happening. When I save a setting in SDNext, watching the config file, all the special characters end up being escaped. So instead of being proper json format, it ends up looking something like this: [config.txt](https://github.com/vladmandic/automatic/files/12386435/config.txt)

This also occurs anytime I hit 'Apply Settings' whether I've made changes or not, and again when I hit something like 'Apply and Restart Server' 

Then when I relaunch the server later, it gets wiped entirely and replaced with a properly sanitized default json file and all my custom settings are gone again. So any extra UI toggles I add are gone again, and I can't resume with my last used checkpoint either. Effectively the only way I can launch the server with my custom settings is by manually editing the config file before launch to ensure it's formatted correctly. 

### Version Platform Description

Python 3.10.11 on Windows                             
Version: 1666ee68 Sat Aug 19 19:44:58 2023 +0300      
nVidia CUDA toolkit on RTX 4070
Mozilla Firefox

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension or diffusers-specific issue

**Comment by vladmandic** [comment]
Duplicate.
Also already fixed in dev.
