### ISSUE TITLE
[Issue]: cards in Extra-Networks are not fetching images in the directories defined in "system Paths"

### ISSUE THREAD

**Issue by cjps-br** [vladmandic/automatic#2049]
### Issue Description

I updated to the last commit and noticed that the extra-networks card images are no longer following the directories defined in the "system Paths" settings. My SD.Next installation is in the "d:\automatic" directory and my models are in "d:\Automatic_data\models". only images that are placed in "d:\automatic\models\*" are shown on cards. I tried to generate a new image and save and got an error message:

AssertionError: writing to D:\Automatic_data\models.jpg is not allowed

### Version Platform Description

app: SD.next
updated: 2023-08-20
hash: 8d97b358
arch: AMD64
cpu: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.6
device: NVIDIA GeForce GTX 1660 SUPER (1) (compute_37) (7, 5)
cuda: 11.8
cudnn: 8700
driver: 528.24

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\automatic\venv\lib\site-packages\gradio\routes.py", line 422, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1323, in process_api
    result = await self.call_function(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1051, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\automatic\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\automatic\modules\ui_extra_networks.py", line 400, in save_preview
    assert is_allowed, f'writing to {filename} is not allowed'
AssertionError: writing to D:\Automatic_data\models.jpg is not allowed
11:36:18-838228 INFO     Settings changed: 0 []
11:41:37-554539 INFO     Available models: D:\Automatic_data\models\Stable-diffusion 70
11:41:37-651242 INFO     Extra network created thumbnails: checkpoints 0
11:41:37-751194 INFO     Extra network created thumbnails: lycoris 0
11:41:37-834812 INFO     Extra network created thumbnails: lora 0
11:41:37-950906 INFO     Extra network created thumbnails: textual inversion 0
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
Ah... I merged a change and kept it in dev for couple of days, but I guess this was still not caught.
Valid issue, I'll work on a fix.

**Comment by cjps-br** [comment]
Hi, Thanks for the feedback!

**Comment by vladmandic** [comment]
hopefully fixed now

**Comment by arcusmaximus** [comment]
Doesn't appear to be fixed. I installed SD.Next for the first time today and pointed the system paths to my Automatic1111 folders (absolute paths), and while it finds and lists my checkpoints/loras/embeddings, all the preview images are broken.

Using relative paths doesn't work either, even when pointing to a non-default subfolder in the SD.Next directory.

If I move the embeddings to the default "models\embeddings" folder, they show up with correct thumbnails, even if the system path is something else.

**Comment by vladmandic** [comment]
@arcusmaximus i've tried to reproduce and no luck (both using relative and absolute paths).
if you have issues please document exact scenario.

**Comment by arcusmaximus** [comment]
Reproduction steps are as follows (on commit `48c0ce9b2b46`):
* Starting situation: embeddings are stored in the default location ("models\embeddings"), system path is set accordingly.
* Launch SD.Next, open the Extra Networks tab, and verify that the thumbnails show up correctly.
* Rename the "embeddings" folder to "embeddings2".
* Back in the SD.Next UI, change the system path for embeddings to "models\embeddings2" and click "Apply settings".
* Switch back to the "From Text" tab and click the blue Refresh button in the Extra Networks popup. The thumbnails stay visible, but the console logs the following error, indicating the list may not actually have been refreshed:

```
Traceback (most recent call last):
  File "D:\SD.Next\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\SD.Next\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\SD.Next\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\SD.Next\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\SD.Next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\SD.Next\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\SD.Next\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\SD.Next\modules\ui_extra_networks.py", line 365, in refresh
    res.append(pg.create_html(ui.tabname))
  File "D:\SD.Next\modules\ui_extra_networks.py", line 162, in create_html
    for parentdir, dirs in {d: modelloader.directory_directories(d) for d in allowed_folders}.items():
  File "D:\SD.Next\modules\ui_extra_networks.py", line 162, in <dictcomp>
    for parentdir, dirs in {d: modelloader.directory_directories(d) for d in allowed_folders}.items():
  File "D:\SD.Next\modules\modelloader.py", line 213, in directory_directories
    for _dir in modelloader_directories:
RuntimeError: dictionary changed size during iteration
```

* Press Ctrl-F5 to refresh the page manually.
* Open the Extra Networks popup again and notice that the embedding thumbnails are now broken. The console shows that SD.Next is still trying to get them from the original folder.

Things work after a server restart, however.

**Comment by cjps-br** [comment]
> hopefully fixed now

I updated to the most current commit today and the problem with the card images disappearing when the templates are not stored in the default folder happened again. 

app: SD.next
updated: 2023-09-06
hash: 26e18b0a

**Comment by vladmandic** [comment]
do you have log for it?
