### ISSUE TITLE
[Issue]: custom config.json settings wiped out on save

### ISSUE THREAD

**Issue by demoran23** [vladmandic/automatic#2051]
### Issue Description

![image](https://github.com/vladmandic/automatic/assets/6959036/1bc894eb-8440-42cb-a7f1-a0889a1e5fbe)

The Dynamic Prompts extension can specify a wildcard directory.  You put `wildcard_dir` in config.json and it picks it up.  It's not configurable in the Settings section of the UI.

Upon saving my settings, the wildcard_dir member is erroneously removed.

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed, but only as a side-effect of another thing - in general, config.json should NOT be used as general purpose storage - if its not in settings, it should not be in config.json, i'd suggest to report it to extension owner so its either removed or properly exposed.
