### ISSUE TITLE
[Feature]: Add ability to use control-lora in diffusers

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#2053]
### Feature description

Ability to use control-lora in diffusers SDXL
A new models from Stability AI that combine lora with ControlNet

https://huggingface.co/stabilityai/control-lora

### Version Platform Description

W:\V\automatic>webui.bat --backend diffusers --medvram --experimental --upgrade
Using VENV: W:\V\automatic\venv
20:14:02-643730 INFO     Starting SD.Next
20:14:02-656725 INFO     Python 3.10.7 on Windows
20:14:02-862728 INFO     Version: 79c01311 Tue Aug 15 12:25:08 2023 +0000
20:14:03-347728 INFO     Updating main repository
20:14:09-336545 INFO     Upgraded to version: 1666ee68 Sat Aug 19 19:44:58 2023 +0300
20:14:09-341540 INFO     nVidia CUDA toolkit detected

**Comment by vladmandic** [comment]
closing here as work is tracked under https://github.com/users/vladmandic/projects/3
