### ISSUE TITLE
[Issue]: (New install) When apply the settings, don't apply the defaults from all options

### ISSUE THREAD

**Issue by landrasss** [vladmandic/automatic#2064]
### Issue Description

Hi, I just installed "Automatic" on another PC and when I apply the settings, they are simply not applied, leaving the gray check:

![Problem Automatic](https://github.com/vladmandic/automatic/assets/112908884/f9c99948-474d-402a-94a0-94fc070fcac8)

Another problem is that when I apply some options, they appear in the console as "Unknown settings":

![Problem Automatic 2](https://github.com/vladmandic/automatic/assets/112908884/a1af1fb8-57d7-4a89-b7b1-096727b74fda)

Thanks in advance.

PD: I just found another problem, I can't see all the options in the config files:

![Problem Automatic 3](https://github.com/vladmandic/automatic/assets/112908884/b7c537fb-c524-4c43-ab6f-91b61958aee3)

![Problem Automatic 4](https://github.com/vladmandic/automatic/assets/112908884/b6450808-7000-4479-a1f5-619790c31c36)

### Version Platform Description

Starting SD.Next
Python 3.10.6 on Windows
Version: 89a3994c Wed Aug 23 09:12:13 2023 +0000
nVidia CUDA toolkit detected
Disabled extensions: []
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
Enabled extensions: []

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
This is known.
If a setting is left at default, then it won't be written to `config.json`.
Vlad knows about this and will either re-code or remove the vertical lines.

**Comment by vladmandic** [comment]
> Hi, I just installed "Automatic" on another PC and when I apply the settings, they are simply not applied, leaving the gray check:

only settings which are set to non-default value are saved. 
this change was done to ui-config.json several weeks ago and to config.json recently.

> Another problem is that when I apply some options, they appear in the console as "Unknown settings":

fixed in dev, will update main branch shortly.
