### ISSUE TITLE
During generation computer is freezing

### ISSUE THREAD

**Issue by Tiome22** [vladmandic/automatic#2065]
### Issue Description

I use amd 5700xt, During generation computer is freezing, and not working just after hard restarting, i think my gpu not working , but i instaled Rocm

### Version Platform Description

Chrome, Windows 10

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
windows 10? torch-rocm does not yet exist for windows. amd has just recently released rocm for windows and its going to take a while until entire stack is available. toch rocm right now is linux only.

for amd on windows, your best option is directml. i suggest running `webui --use-directml --reinstall` so it reinstalls all packages required for that. and if you have questions about that, check previous issues and discussions and only if its a new issue, create an issue.

**Comment by Tiome22** [comment]
> windows 10? torch-rocm does not yet exist for windows. amd has just recently released rocm for windows and its going to take a while until entire stack is available. toch rocm right now is linux only.
> 
> for amd on windows, your best option is directml. i suggest running `webui --use-directml --reinstall` so it reinstalls all packages required for that. and if you have questions about that, check previous issues and discussions and only if its a new issue, create an issue.

Ok, thanks
