### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by evgebrtwjhr** [vladmandic/automatic#2066]
### Issue Description

I get this error when I try to load a model, it fails to load the model
 7:46:30-082639 INFO     Available models: models\Stable-diffusion items=1
Loading weights: C:\Users\Z5050\Desktop\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors ━━━━ 0.0… -:-…                                                                                                               GB       Press any key to continue . . .                                         

### Version Platform Description

Windows, Google Chrome

### Relevant log output

```shell
Running on local URL:  http://127.0.0.1:7860
17:52:45-842583 INFO     Local URL: http://127.0.0.1:7860/
17:52:45-845448 INFO     Initializing middleware
17:52:46-104570 INFO     [AgentScheduler] Task queue is empty
17:52:46-106561 INFO     [AgentScheduler] Registering APIs
17:52:46-853582 INFO     Selecting first available checkpoint
Loading weights: C:\Users\Z5050\Desktop\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors ━━━━ 0.0… -:-…                                                                                                               GB       Press any key to continue . . .
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by evgebrtwjhr** [comment]
It gives the error on every model I try to load

**Comment by vladmandic** [comment]
That looks like python process just dies.
Can you run with `--debug`to capture a bit more details?

**Comment by brunogcar** [comment]
try to install  in someplace else other than inside C:\Users\ as it has different write/read permissions than regular folder, in your case, you installed on a folder created on DESKTOP which is inside C:\Users\

**Comment by vladmandic** [comment]
required info was not provided, issue can be reopened once it has all required info.
