### ISSUE TITLE
[Issue]: "Resize by" in img2img can't be used

### ISSUE THREAD

**Issue by YHD233** [vladmandic/automatic#2068]
### Issue Description

In the "Batch" of "From Image", "Resize by" can't be used, it will only read the width and height in "Resize to", and the image resolution generated by all options in "Resize mode" is "Resize to" Width and height.

### Version Platform Description

Starting SD.Next
Python 3.10.6 on Windows
Version: 1666ee68 Sat Aug 19 19:44:58 2023 +0300
nVidia CUDA toolkit detected
device: NVIDIA GeForce RTX 2080 Ti (1) (compute_37) (7, 5)
cuda: 11.8
cudnn: 8700
driver: 531.79
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
Enabled extensions: ['a1111-sd-webui-tagcomplete', 'adetailer', 'ebsynth_utility',
                         'sd-webui-bilingual-localization', 'sd-webui-IS-NET-pro', 'sd-webui-segment-anything',
                         'vladmandic-WD14-Tagger']
Server arguments: ['--autolaunch', '--port', '7860']

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by YHD233** [comment]
I want to automatically read the image resolution and zoom in twice when batch generating images in img2img

**Comment by vladmandic** [comment]
valid request and when i first looked at it, i though its an issue - but that part of the code was never implemented. 
anyhow, i've added code for this and its in dev branch, will be published to main soon.
