### ISSUE TITLE
[Extension]: sd-webui-controlnet is incompatible

### ISSUE THREAD

**Issue by aappaapp** [vladmandic/automatic#2069]
### Issue Description

So I want to enable `sd-webui-controlnet` (version de868abd) but every time I enable and restart the program, it logs `WARNING  Diffusers disabling uncompatible extension: sd-webui-controlnet`.

### Version Platform Description

```
01:33:08-078986 INFO     Starting SD.Next
01:33:08-081985 INFO     Python 3.10.6 on Windows
01:33:08-181540 INFO     Version: 0512e297 Thu Aug 24 10:01:39 2023 +0200
01:33:08-736791 DEBUG    Setting environment tuning
01:33:08-738796 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
01:33:08-739795 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
01:33:08-741859 INFO     nVidia CUDA toolkit detected
01:33:08-991827 DEBUG    Repository update time: Thu Aug 24 16:01:39 2023
01:33:08-992810 DEBUG    Previous setup time: Fri Aug 25 01:22:06 2023
01:33:08-994806 INFO     Disabled extensions: ['a1111-sd-webui-lycoris', 'sd-dynamic-thresholding',
                         'multidiffusion-upscaler-for-automatic1111', 'sd-webui-controlnet']
01:33:08-995828 INFO     Enabled extensions-builtin: ['clip-interrogator-ext', 'LDSR', 'Lora', 'ScuNET',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
```

### URL link of the extension

https://github.com/Mikubill/sd-webui-controlnet

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by jabialowas** [comment]
Same problem here.
Additional logs regarding git:

On install :
`19:50:10-650713 ERROR    Failed reading extension data from Git repository: sd-dynamic-thresholding:                    19:50:10-652642 ERROR    Failed reading extension data from Git repository: sd-extension-system-info:                   19:50:10-654434 ERROR    Failed reading extension data from Git repository: sd-webui-agent-scheduler:                   19:50:10-656298 ERROR    Failed reading extension data from Git repository: sd-webui-controlnet:                        19:50:10-658159 ERROR    Failed reading extension data from Git repository: stable-diffusion-webui-images-browser:      19:50:10-659726 ERROR    Failed reading extension data from Git repository: stable-diffusion-webui-rembg:  `

On Start
`19:50:10-650713 ERROR    Failed reading extension data from Git repository: sd-dynamic-thresholding:                    19:50:10-652642 ERROR    Failed reading extension data from Git repository: sd-extension-system-info:                   19:50:10-654434 ERROR    Failed reading extension data from Git repository: sd-webui-agent-scheduler:                   19:50:10-656298 ERROR    Failed reading extension data from Git repository: sd-webui-controlnet:                        19:50:10-658159 ERROR    Failed reading extension data from Git repository: stable-diffusion-webui-images-browser:      19:50:10-659726 ERROR    Failed reading extension data from Git repository: stable-diffusion-webui-rembg:    `

**Comment by vladmandic** [comment]
Extension works for original backend.
Controlnet support for diffusers backend is planned, but not via existing extension. As such this is a no-op.
