### ISSUE TITLE
[Feature]: Style file path

### ISSUE THREAD

**Issue by mykeehu** [vladmandic/automatic#207]
### Feature description

I store the style file (Style.csv) on Google drive and update it there, so I would like to be able to set a custom path for the style file.

### Version Platform Description

Google Colab

**Comment by vladmandic** [comment]
Create symlink?

**Comment by mykeehu** [comment]
I understand that symlink cannot be used for Google drive

**Comment by vladmandic** [comment]
i've added option to specify path/file in ui settings -> system paths, new version will be published in ~1h.

**Comment by mykeehu** [comment]
Thank you very much for the quick solution!
