### ISSUE TITLE
[Issue]: Windows -> Installer fails -> requires Python 3. [9, 10] but 11 was released yesterday [08/24]

### ISSUE THREAD

**Issue by Coffee-Viking** [vladmandic/automatic#2070]
### Issue Description

Running the webui.bat installer terminates unsuccessful :

> 10:11:53-440633 ERROR    Incompatible Python version: 3.11.5 required 3.[9, 10]

I'm assuming a downgrade will fix the issue and that's what I'll do now, but would be good to support the new release.

### Version Platform Description

Windows 10 64bit, Python 3.11.5

### Relevant log output

```shell
2023-08-25 10:11:53,420 | sd | INFO | launch | Starting SD.Next
2023-08-25 10:11:53,437 | sd | INFO | installer | Python 3.11.5 on Windows
2023-08-25 10:11:53,440 | sd | ERROR | installer | Incompatible Python version: 3.11.5 required 3.[9, 10]
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
Not an issue. SD.Next's requirement is 3.9 or 3.10.
This is more a Feature Request.

**Comment by vladmandic** [comment]
Also, SDnext itself has no issues with Python 3.11, but quite a few modules and extensions are not compatible. If you really want, you can run using `--experimental` (but then can't report any issues if they occur).

**Comment by Coffee-Viking** [comment]
@vladmandic got it, thanks. I thought this was the installer itself causing an error that requires fixing.

Downgraded Python to 3.10 and it's working as expected.

**Comment by thewayur** [comment]
can i set custom path of python for this repo?

**Comment by brknsoul** [comment]
You can manually create the venv folder by running in your cloned directory;
`\path\to\python3.10\python -m venv venv`
