### ISSUE TITLE
[Issue]: Modules and scritps layout following gradio update

### ISSUE THREAD

**Issue by fbellgr** [vladmandic/automatic#2073]
### Issue Description

After updating to e810d59fb898a6c61c613794f38630c6a5215796 and getting the gradio update, the modules and scripts layout has become horizontal, messy and things don't really fit anymore.

These screenshot are from img2img

![image](https://github.com/vladmandic/automatic/assets/27892962/52a2f4c8-a652-4f61-97b1-f2872eaf2e9a)

Expanding Ultimate SD Upscale gives this:

![image](https://github.com/vladmandic/automatic/assets/27892962/c691c09a-f0a2-4f36-af1a-2b756c49e728)

The screenshot is not cropping anything, it is really how it looks on the right.

Also, some settings override don't take, such as 

```"img2img/Control Mode/value": "ControlNet is more important"```

I don't know if the glitchy layout has a side effect on ui some overrides. Default resolution takes without an issue.

### Version Platform Description

Theme: gradio/default light (I tried several and as far as I know it does not have any effect on the problem)
Firefox 116 and Chromium 116
```
2023-08-25 12:58:57,895 | sd | INFO | launch | Starting SD.Next
2023-08-25 12:58:57,900 | sd | INFO | installer | Python 3.10.12 on Linux
2023-08-25 12:58:57,903 | sd | INFO | installer | Version: e810d59f Fri Aug 25 16:36:45 2023 +0000
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
How does it look with default theme?

**Comment by fbellgr** [comment]
I deleted the ui and config overrides, so back to all defaults.

![image](https://github.com/vladmandic/automatic/assets/27892962/50d801af-a39f-4370-8e38-d9ed634bd512)

**Comment by fbellgr** [comment]
When I was at the previous revision, I had an override for the default upscaler Ultimate SD Upscale.
The override does not take anymore.
Could upgrading gradio render extensions and module incompatible?
ControlNet also has issues displaying properly and loading config.

**Comment by vladmandic** [comment]
Gradio is notorious for making such breaking changes...

**Comment by vladmandic** [comment]
which browser? i just checked with chrome and it doesn't look anywhere close to posted screenshots.

**Comment by fbellgr** [comment]
Firefox and Chromium 116.

This is from Chromium

![image](https://github.com/vladmandic/automatic/assets/27892962/465effd6-9281-4abc-80a1-5c1c0b9dcedc)

**Comment by vladmandic** [comment]
> Kind of makes me have to stay behind.

that is your right. now imagine if i had the same approach - no updates, no new features?

**Comment by vladmandic** [comment]
anyhow, i just pushed a small update, hope it helps.

**Comment by Monty1836** [comment]
Chrome dev tools make the issue fairly simple to find.  The .styler class is overriding the flex direction because it has the !important flag enabled.  Removing the important flag solves the issue, as does adding it to the container.
![image](https://github.com/vladmandic/automatic/assets/143219756/9306627b-d7f3-4eee-a719-53240e8692e8)

**Comment by fbellgr** [comment]
So fixable through user.css as a workaround?
I haven't played much with this kind of tweaking in this project.

**Comment by vladmandic** [comment]
yes, i did that in the lastest update. but that on its own breaks settings, so a bit more was needed.

**Comment by vladmandic** [comment]
> So fixable through user.css as a workaround? I haven't played much with this kind of tweaking in this project.

check update first.

**Comment by fbellgr** [comment]
ok I still see e810d59fb898a6c61c613794f38630c6a5215796 as the head.
Will wait for your commit.

**Comment by vladmandic** [comment]
pushed

**Comment by Monty1836** [comment]
Looks good on my end, back to how it should be.  Thanks!

**Comment by fbellgr** [comment]
The layout is fixed, and some ui overrides now do appear to work.

Something weird is going on, though.

At 0512e2973c584489a0d4f6149bd5b8435d6dfc56, all of these overrides take.
Since e810d59fb898a6c61c613794f38630c6a5215796, the last one does not. 

```
"customscript/ultimate-upscale.py/img2img/Scale/value": 3,
"customscript/ultimate-upscale.py/img2img/Seams fix/value": true,
"customscript/ultimate-upscale.py/img2img/Tile height/value": 768,
"customscript/ultimate-upscale.py/img2img/Tile width/value": 768,
"customscript/ultimate-upscale.py/img2img/Upscaler/value": "4x_ESRGAN"
```

**Comment by vladmandic** [comment]
AFAIK, there were no changes in that area of code. In either case, needs to be investigated separately.

**Comment by fbellgr** [comment]
Alright. Fair enough.

Closing note: it seems the overrides not taking issue affects radio buttons in modules ans scripts.

Maybe it would do the same in the main UI, but the main UI appears to use only dropdowns and checkboxes for multiple selections.

**Comment by dan4ik94** [comment]
@vladmandic I have a similar problem, for example my "Inpaint" tab has double labels which makes it unusable. 
Any idea?

https://i.imgur.com/ChDXD3j.png

**Comment by vladmandic** [comment]
@dan4ik94 

> @vladmandic I have a similar problem, for example my "Inpaint" tab has double labels which makes it unusable.

i cant reproduce, see my screenshot below. try deletin `ui-config.json`.

![image](https://github.com/vladmandic/automatic/assets/57876960/e4bc67eb-946c-4621-939d-77b9775092bf)

**Comment by vladmandic** [comment]
@fbellgr 

> Closing note: it seems the overrides not taking issue affects radio buttons in modules and scripts.
> 
> Maybe it would do the same in the main UI, but the main UI appears to use only dropdowns and checkboxes for multiple selections.

its seems new gradio has different value format for radio controls - try selecting one value, go to settings -> ui defaults and apply - let me know if that works.

**Comment by dan4ik94** [comment]
@vladmandic 

Reverting gradio to **3.32.0** fixed all the UI issues for me, strange it works on your side. I'll stick with 3.32, seems like 3.41 has some issues. 

![mO1syGljTY](https://github.com/vladmandic/automatic/assets/84623377/58564785-7774-4319-89ea-483f1d32d06c)

**Comment by vladmandic** [comment]
its not that new gradio has issues, its more that gradio doesn't care about backward compatibility that much, so every new version introduces number of changes that everyone has to adjust to. but i don't have luxury of leaving sdnext on old version forever.

**Comment by dan4ik94** [comment]
@vladmandic Little update on my issue: seems like I had some local git conflicts with various extensions, after updating every single one, everything is working fine even on **3.41.***. 

Yahooo, thank you.
