### ISSUE TITLE
[Issue]: Sampler settings no longer wrap

### ISSUE THREAD

**Issue by fbellgr** [vladmandic/automatic#2075]
### Issue Description

It is no longer possible to view/select the whole list of samplers in the admin.
The list does not wrap and there is no overflow.

![image](https://github.com/vladmandic/automatic/assets/27892962/c4b86fe9-d78a-4d7a-9a43-59fba7c83d00)

### Version Platform Description

Chromium and Firefox 116
```
2023-08-25 16:49:07,261 | sd | INFO | launch | Starting SD.Next
2023-08-25 16:49:07,265 | sd | INFO | installer | Python 3.10.12 on Linux
2023-08-25 16:49:07,276 | sd | INFO | installer | Version: 2e13c988 Fri Aug 25 21:15:41 2023 +0200
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
