### ISSUE TITLE
[Issue]: Save button meta data missing

### ISSUE THREAD

**Issue by zethfoxster** [vladmandic/automatic#2076]
### Issue Description

images saved after generation using the "save" button do not write the meta data to the img.
![00006-masterpiece high resolution fit Markus tune an adventurer](https://github.com/vladmandic/automatic/assets/5951657/396a3621-4f38-4b01-81d3-25f3027d1514)
![tmpcz1e6rpo](https://github.com/vladmandic/automatic/assets/5951657/879b280c-4de9-4cb5-819c-954c8a52a046)

included here is an img dragged directly from the txt2img tab to desktop, and the one produced after hitting "save" button

last known working commit 0512e297... aug 24 was the last date in my image browser where the images contained their generation data.

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by zethfoxster** [comment]
could possibly be the commit before the 24th, not sure at what time exactly i git pulled...if it was before or after this commit. im using my save folders date structure to determine when the last time data was present and it is the 24th.

**Comment by vladmandic** [comment]
can you run with `--debug` and post ~20-30 lines of log leading to saving image message.

**Comment by Aptronymist** [comment]
I can confirm this is the case, xedis, idenoh, and I are aware of this behavior and discussed it. it doesn't take metadata with it if you do a copy paste of the image from the view area either, which was how I usually do it.
We all noticed that as the case when we were posting images with the new metadata bot in effect.

**Comment by vladmandic** [comment]
if `Always save all generated images` is enabled, then save button is a copy operation, not even save - so metadata is 100% correct. if image is not already saved, then save button needs to re-assemble metadata from bits and pieces from previous generate op and that goes wrong.

anyhow, its fixed.

**Comment by zethfoxster** [comment]
it still not saving metadata on current, has the actual fix been pushed in yet?
