### ISSUE TITLE
[Extension] ControlNet missing models

### ISSUE THREAD

**Issue by unkleb** [vladmandic/automatic#2079]
### Issue Description

Fresh install of Vladmandic and no models showing under controlnet.  No errors, just no models listed.

### Version Platform Description

Windows 10, plenty of HD space and memory.  Fresh install of Vladmandic/automatic via GitHub desktop.  No errors on install.  Everything looks great, just no ControlNet models listed.
![Capture](https://github.com/vladmandic/automatic/assets/56565306/4de63118-68dd-489d-b5c3-939db0f4f323)

14:02:17-011423 INFO     Starting SD.Next
14:02:17-025423 INFO     Python 3.10.9 on Windows
14:02:17-088426 INFO     Version: 594f0331 Sat Aug 26 19:35:50 2023 +0300
14:02:17-442454 INFO     nVidia CUDA toolkit detected
14:02:17-561423 INFO     Verifying requirements
14:02:17-590423 INFO     Verifying packages
14:02:17-594423 INFO     Verifying repositories
14:02:21-151845 INFO     Verifying submodules
14:02:53-614500 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
14:02:53-620498 INFO     Verifying packages
14:02:53-623498 INFO     Updating Wiki
14:02:54-360353 INFO     Extension preload: 0.0s
                         C:\Users\BMer\stable-diffusion-webui-next\extensions\automatic\extensions-builtin
14:02:54-364353 INFO     Extension preload: 0.0s extensions
14:02:54-387366 INFO     Server arguments: ['--upgrade']
No module 'xformers'. Proceeding without it.
14:03:03-396371 INFO     Engine: backend=Backend.ORIGINAL
14:03:04-218711 INFO     Libraries loaded
14:03:04-222683 INFO     Using models path:
14:03:04-226683 INFO     Available VAEs: models\VAE items=0
14:03:04-231683 INFO     Available models: models\Stable-diffusion items=1
14:03:07-581621 INFO     ControlNet v1.1.312
ControlNet v1.1.312
ControlNet preprocessor location: C:\Users\BMer\stable-diffusion-webui-next\extensions\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads
14:03:07-829655 INFO     ControlNet v1.1.312
ControlNet v1.1.312
14:03:09-273622 INFO     Loading UI theme: name=black-orange style=Auto
Running on local URL:  http://127.0.0.1:7860
14:03:11-812717 INFO     Local URL: http://127.0.0.1:7860/
14:03:11-815757 INFO     Initializing middleware
14:03:11-978788 INFO     [AgentScheduler] Task queue is empty
14:03:11-980758 INFO     [AgentScheduler] Registering APIs
Loading weights: C:\Users\BMer\stable-diffusion-webui-next\extensions\automatic\models\Stable-diffusion\v1-5-pruned-e…
14:03:12-631787 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
14:03:15-921756 INFO     Applying scaled dot product cross attention optimization
14:03:15-958756 INFO     Embeddings: loaded=0 skipped=0
14:03:15-968786 INFO     Model loaded in 3.6s (load=0.2s config=0.1s create=0.5s apply=0.8s vae=0.9s move=1.1s)
14:03:16-239805 INFO     Model load finished: {'ram': {'used': 5.05, 'total': 31.93}, 'gpu': {'used': 3.05, 'total':
                         12.0}, 'retries': 0, 'oom': 0} cached=0
14:03:16-756785 INFO     Startup time: 22.3s (torch=6.6s gradio=1.0s libraries=2.3s codeformer=0.1s scripts=4.8s
                         onchange=0.1s ui-txt2img=0.1s ui-img2img=0.1s ui-settings=0.1s ui-extensions=1.8s
                         ui-defaults=0.1s launch=0.3s app-started=0.3s checkpoint=4.6s)

### URL link of the extension

Default

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by brunogcar** [comment]
if you models are in `C:\Users\BMer\stable-diffusion-webui-next\extensions\automatic\extensions-builtin\sd-webui-controlnet\annotator\downloads` then something is wrong,  
but if your models are in lets say `C:\Users\BMer\stable-diffusion-webui-next\extensions\automatic\models\Controlnet` just change in settings, cos default path is pointed to folder inside controlnet extension, which is odd but ....

**Comment by vladmandic** [comment]
and fill issue template correctly. you've chosen to change title to an invalid one and not filled all fields.

**Comment by bjornlarssen** [comment]
I wrote a script that links my Google Drive folder with all the models to stable-diffusion-webui/extensions-builtin/sd-webui-controlnet/models – I run the script after SD.Next starts. Otherwise only the .yaml files are there and the list of models consists of "none."

**Comment by unkleb** [comment]
Thanks for all your help.  Everything seems fine now...
