### ISSUE TITLE
[Feature]: Implement "Hard Prompts Made Easy" into Sd.next please.

### ISSUE THREAD

**Issue by StableInfo** [vladmandic/automatic#2083]
### Feature description

Hello,
There is a tech that nobody talks about, it's a powerful tool that can generate prompts from images, but in a very different way that the usual clip button, it actually generate abnormal words and characters and they word very well, the prompts generated are very powerful and be re used.
The technology is here: https://github.com/YuxinWenRick/hard-prompts-made-easy
( https://arxiv.org/abs/2302.03668 )

I did not find one single extension that implemented this tech, except for "unprompted" which is quite special and it sometimes conflicting with other extensions. The description of the extensions does not contain any info about the "Hard Prompts Made Easy" but it apparently works by writring  [img2pez] in img2img, and instead of getting an image when pressing generate, it gets you a text with a generated prompt. (https://github.com/ThereforeGames/unprompted)
___
Given this tech is very powerful, 
and given its quite poorly described in another extension and we are not quite sure how it works anyway, 
I think that sd.next should be the pioneer in adding a powerful method to generate powerful and unseen prompts, by adding this tech into img2img tab, a button next to the CLIP button called PEZ or HPME. It could become a native feature.

If it's not too complicated, can you add this to sd.next please? It's really surprising, and no one knows, we actually need it, it's really good technology.
Thanks

**Comment by StableInfo** [comment]
Apparently it exists here: https://github.com/r0mar0ma/sd-webui-pez-dispenser
My bad.
Could be nice to add it as native maybe, otherwise its no longer a priority because i found a second extension who implemented it.

**Comment by vladmandic** [comment]
i don't think this should be part of core - and given that extension that does it already exists, i'm closing this issue.
