### ISSUE TITLE
[Issue]: Gradio 3.41.1 - default settings for radio lists

### ISSUE THREAD

**Issue by fbellgr** [vladmandic/automatic#2085]
### Issue Description

Setting custom default settings for radio button lists does not take.

Following up on a secondary issue raised with [issue 2073](https://github.com/vladmandic/automatic/issues/2073), this [comment](https://github.com/vladmandic/automatic/issues/2073#issuecomment-1693844587) and this [comment](https://github.com/vladmandic/automatic/issues/2073#issuecomment-1694264487).

If I set this for ControlNet on txt2img (Pixel Perfect and ControlNet is more important).

![image](https://github.com/vladmandic/automatic/assets/27892962/fafa1ba3-b3f9-4394-8b45-5e44e77409f3)

The default settings generated in the admin are:

UI

![image](https://github.com/vladmandic/automatic/assets/27892962/fd4edbae-e250-4ea8-8c79-647679ce6d1c)

JSON

```json
{
  "txt2img/Pixel Perfect/value": true,
  "txt2img/Control Mode/value": "ControlNet is more important",
  "img2img/Resize mode/value": [
    "None",
    "None"
  ],
  "img2img/Mask mode/value": [
    "Inpaint masked",
    "Inpaint masked"
  ],
  "img2img/Masked content/value": [
    "original",
    "original"
  ],
  "img2img/Inpaint area/value": [
    "Whole picture",
    "Whole picture"
  ],
  "customscript/poor_mans_outpainting.py/img2img/Masked content/value": [
    "fill",
    "fill"
  ],
  "customscript/sd_upscale.py/img2img/Upscaler/value": [
    "None",
    "None"
  ],
  "customscript/ultimate-upscale.py/img2img/Upscaler/value": [
    "None",
    "None"
  ],
  "customscript/ultimate-upscale.py/img2img/Type/value": "Linear",
  "customscript/ultimate-upscale.py/img2img/Mask blur/value": 8,
  "customscript/ultimate-upscale.py/img2img/Padding/value": 32,
  "models/Model configuration/value": [
    "Primary",
    "Primary"
  ]
}
```
When reloading the app, the Control Mode setting is still on Balance.

I notice that some config for radios are using an array instead of a literal, so I tried this instead:

```json
"txt2img/Control Mode/value": [
    "ControlNet is more important",
    "ControlNet is more important"
  ],
```

But it still does not work.

I note the same issue with setting the default upscaler for Ultimate SD upscale in img2img, except that the admin is generating the config as an array this time:

![image](https://github.com/vladmandic/automatic/assets/27892962/79d545b2-3c22-41f9-aa76-2fb698716a7a)

```json
"customscript/ultimate-upscale.py/img2img/Upscaler/value": [
    "4x_ESRGAN",
    "4x_ESRGAN"
  ],
```

But this also does not take on load.

The overrides for the other field types work in both extensions.

I tried to change the Resize Mode in img2img, since it is part of the main UI and also a radio button list. It remembers to check Resize, but it does not select the proper resize mode. It does save the setting as an array, though.

```json
  "img2img/Resize mode/value": [
    "Crop and resize",
    "Crop and resize"
  ],
```

To sum up:

- The setting for Control Mode seems to be saved in the wrong format, but both literal and array formats do not take on load.
- Changing the Resize Mode in img2img generates the default value as an array, but the proper resize mode is not selected on load.
- Changing the default upscaler in Ultimate Ultimate SD upscale generates the default value as an array, but the proper upscaler is not selected on load.

Note: all the JSON shown here was generated by SD.Next, except for the attempt to change the value format for Control Mode.

### Version Platform Description

Firefox and Chromium 116
```
00:12:46-791252 INFO     Starting SD.Next                                                                                                                                           
00:12:46-795216 INFO     Python 3.10.12 on Linux                                                                                                                                    
00:12:46-806820 INFO     Version: 594f0331 Sat Aug 26 19:35:50 2023 +0300
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i really really hate how new gradio changed behavior of radio control.
anyhow, i hope its fixed now.

**Comment by fbellgr** [comment]
Seems to be back to the old working normal. Thank you.
