### ISSUE TITLE
[Issue]: Generated image info not updated

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#2094]
### Issue Description

I noticed lately, that the information text of the generated images are not updated, but stay on the information of the first image generated. In the screen shot the image shown in SD Prompt reader was the first image generated, in SD:Next is the second image generated, but with the info of the first one still existing.

![Zwischenablagebild](https://github.com/vladmandic/automatic/assets/122026301/21639974-30dc-4bd2-8dc7-361ce73a2074)

### Version Platform Description

Win10, FF 114

### Relevant log output

```shell
Using VENV: I:\Super SD 2.0\automatic\venv
12:54:38-384122 INFO     Starting SD.Next
12:54:38-388097 INFO     Python 3.10.6 on Windows
12:54:38-560260 INFO     Version: 48c0ce9b Sun Aug 27 08:01:29 2023 +0000
12:54:39-050839 INFO     nVidia CUDA toolkit detected
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev, will push to main later today along with number of other fixes.
