### ISSUE TITLE
Controlnet 1.1.313 kills python: connection errored out - 

### ISSUE THREAD

**Issue by MajorGruberth** [vladmandic/automatic#2099]
### Issue Description

When I activate Controlnet and generate an image python quits ("python quits unexpectedly")

 error: input types 'tensor<2x1280xf32>' and 'tensor<1280xf16>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).

I didn't touch anything. mom, but yesterday controlnet disappeared from the UI, updates didn't work (as updates of other extensions didn't). Today I did a fresh install of SD Next and Controlnet was back on the UI. Activating Controlnet and generate an image leads to python crash - game over

The log doesn't show anything. ("2023-08-29 16:44:59,754 | ControlNet | INFO | controlnet | preprocessor resolution = 512").

I worked with SD Next now a week or so without issues. But somehow I am reminded at the time around 1983 or so, when we would try to code on our ZX Spectrums or Commodore 64 and failed and failed and failed (For younger people: there where a time, THE INTERNET didn't exist - not even in our dreams and we had to pick our knowledge from BOOKS :). )

### Version Platform Description

Mac M1, Controlnet 1.1. 313, SD Next from todays installation. 

### Relevant log output

```shell
2023-08-29 16:44:59,754 | ControlNet | INFO | controlnet | preprocessor resolution = 512
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
refile using extension template (and fill it as required). marking as invalid.

**Comment by vladmandic** [comment]
you've created an issue when the problem is with extension. when creating issue in github, it asks you which type of an issue it is and directs to proper form to fill.

**Comment by MajorGruberth** [comment]
ah ok - thanks
