### ISSUE TITLE
[Issue]: Metadata isn't saved into final image if the SD upscale script is used in img2img

### ISSUE THREAD

**Issue by Silanda** [vladmandic/automatic#2100]
### Issue Description

This is a problem I've noticed in the last couple of days since I last updated (possibly since the Gradio update), and is still true up to 348943fceedba48301d31934ce19a5ce8db95bde.

When I use the SD upscale script in img2img for upscaling, it's not saving the generation metadata in the image output, nor is it displayed in the Window under the output image. It doesn't create a text file with the parameters in either, if that's selected. 

If I do an upscale without the script, the metadata/parameters still don't display under the output image, but the metadata is present in the image itself, and a text file is created.

Everything works fine if I'm doing inpainting.

Something else I've noticed, that I'm not sure is related, is that init images (e.g. the tiles used for the SD upscale) are saved as .jpg irrespective of the output format that I've selected for images and grids. 

I had to do a settings reset after the Gradio changes as something became messed up at that point, so I can't rule out that I've missed something obvious, but I don't think I have.

Related to #2094 and #2078, maybe?

### Version Platform Description

2023-08-29 16:07:40,728 | sd | INFO | launch | Starting SD.Next
2023-08-29 16:07:40,736 | sd | INFO | installer | Python 3.10.6 on Windows
2023-08-29 16:07:40,798 | sd | INFO | installer | Version: 48c0ce9b Sun Aug 27 08:01:29 2023 +0000
2023-08-29 16:07:41,235 | sd | INFO | installer | Updating main repository
2023-08-29 16:07:44,021 | sd | INFO | installer | Upgraded to version: 348943fc Tue Aug 29 11:03:21 2023 -0400

Firefox 116.0.3

I'm using SDXL on the diffusers backend, with only the built in extensions.

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev, will push to main later today.
