### ISSUE TITLE
[Feature]: Add deterministic mode preset

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#2101]
### Feature description

Implement deterministic mode, called from cli argument.
Lock/change all applicable settings to align with their deterministic option.
Requires implementing CPU-only random generator for original backend, cross-attention mem opts (setting SDP disable memory attention), 0 ToME, eta, sampler settings, etc

**Comment by vladmandic** [comment]
from torch side, deterministic mode is implemented.

**Comment by Aptronymist** [comment]
Woohoo!
