### ISSUE TITLE
[Issue]: AttributeError: 'Options' object has no attribute 'queue_button_placement' during startup

### ISSUE THREAD

**Issue by BaiMatthias** [vladmandic/automatic#2102]
### Issue Description

I started the webui.bat as usual and right at the start of the startng process I get the following error message:

03:01:13-793556 INFO     Loading UI theme: name=black-orange style=Auto
03:01:13-843597 ERROR    Running script after component:
                         E:\NAI\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py
                         : AttributeError
┌───────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────┐
│ E:\NAI\automatic\modules\scripts.py:518 in after_component                                                  │
│                                                                                                             │
│   517 │   │   │   │   t0 = time.time()                                                                      │
│ > 518 │   │   │   │   script.after_component(component, **kwargs)                                           │
│   519 │   │   │   │   time_component[script.title()] = time_component.get(script.title(), 0) +              │
│                                                                                                             │
│ E:\NAI\automatic\extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py:94 in                │
│ after_component                                                                                             │
│                                                                                                             │
│    93 │   │   if (                                                                                          │
│ >  94 │   │   │   shared.opts.queue_button_placement == placement_between_prompt_and_generate               │
│    95 │   │   │   and component.elem_id == neg_id                                                           │
│                                                                                                             │
│ E:\NAI\automatic\modules\shared.py:679 in __getattr__                                                       │
│                                                                                                             │
│    678 │   │   │   return self.data_labels[item].default                                                    │
│ >  679 │   │   return super(Options, self).__getattribute__(item) # pylint: disable=super-with-             │
│    680                                                                                                      │
└────────────────────────────────────────────────────────────────────────────── AttributeError: 'Options' object has no attribute 'queue_button_placement' during startup

This error message is repeated indefinitely until I kill the process.

### Version Platform Description

03:00:56-430227 INFO     Starting SD.Next
03:00:56-436227 INFO     Python 3.10.6 on Windows
03:00:56-490227 INFO     Version: 579be529 Tue Aug 29 17:57:02 2023 -0400
03:00:56-935282 INFO     nVidia CUDA toolkit detected

03:00:57-529838 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext',
                         'LDSR', 'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer',
                         'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter',
                         'seed_travel', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
03:00:57-541707 INFO     Enabled extensions: ['a1111-sd-webui-tagcomplete', 'adetailer', 'SD-Prompt-Enhancer',
                         'Stable-Diffusion-Webui-Civitai-Helper', 'ultimate-upscale-for-automatic1111']

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
your agent scheduler extension is out of date, that issue was fixed long time ago.
since sdnext is current, but extension is not, how are you upgrading sdnext?
update extension manually once:
```shell
cd extensions-builtin/sd-webui-agent-scheduler/
git pull
```

**Comment by BaiMatthias** [comment]
>  since sdnext is current, but extension is not, how are you upgrading sdnext?

I switched to vladautomatic in late april and followed the install instruction at that time including cloning the repo:
` git clone https://github.com/vladmandic/automatic`

For installing changes and upgrades I simply right-clicked on the automatic folder, selected Git Bash and typed `git pull`, that's it.

**Comment by vladmandic** [comment]
git pull only updates main repository, so your extensions were ancient. i suggest to use `webui --upgrade` to run upgrades which will update all components as needed, not just main repo.

or update all submodules and extensions manually.
