### ISSUE TITLE
[Issue]: "Read Generation..." button creates infinite spinning in "Override Settings"

### ISSUE THREAD

**Issue by tranzmatt** [vladmandic/automatic#2103]
### Issue Description

When I fire up Automatic, if I click on the icon for "Read generation parameters from prompt or last generation...".  The UI will populate, but the "Override Settings" will appear (with the VAE of the most recent generation) and begin its infinite spin.  I can X out the VAE, but the box keeps spinning and often prevents me from using "Generate" as it'll no longer respond.

![image](https://github.com/vladmandic/automatic/assets/867466/4efa21ed-da4f-484e-b1e0-b5416cfaa353)

### Version Platform Description

Hash: 579be529da4ff54d8268608b96d2e20cce1dc740
Windows 10
Opera GX, Firefox

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
> I hate gradio. :D

just so you know, you're not the only one! :(
