### ISSUE TITLE
[Issue]: same error with various models

### ISSUE THREAD

**Issue by robertJene** [vladmandic/automatic#2104]
### Issue Description

I get this error when trying to generate an image:

WARNING  Model not loaded

same error with various models

### Version Platform Description

browser: firefox

commit 579be529da4ff54d8268608b96d2e20cce1dc740 (HEAD -> master, origin/master, origin/HEAD)

### Relevant log output

```shell
size mismatch for model.diffusion_model.output_blocks.8.0.skip_connection.weight:
                         copying a param with shape torch.Size([320, 640, 1, 1]) from checkpoint, the shape in current
                         model is torch.Size([640, 960, 1, 1]).
                                 size mismatch for model.diffusion_model.output_blocks.8.0.skip_connection.bias:
                         copying a param with shape torch.Size([320]) from checkpoint, the shape in current model is
                         torch.Size([640]).
23:51:11-017937 WARNING  Model not loaded
```

### Backend

Original

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
if you check earlier log messages, its going to tell you why - you're probably trying to load sd-xl model using original backend instead of diffusers.

**Comment by robertJene** [comment]
when I watched the video for installing SD.Next, there was no mention of having to do this.
How do load diffusers?

**Comment by robertJene** [comment]
how to switch to diffusers is not here:
https://github.com/vladmandic/automatic/blob/master/README.md
or here:
https://github.com/vladmandic/automatic/wiki/Diffusers

**Comment by vladmandic** [comment]
short version: settings -> stable diffusion -> backend = diffusers
long version: <https://github.com/vladmandic/automatic/wiki/SD-XL>

**Comment by robertJene** [comment]
I found this here:
https://stable-diffusion-art.com/sdxl-model/
put this in my custom webui-SDXL.bat
--backend diffusers
this is a good option for users who want different settings in webui-user.bat for SD 1.5

**Comment by vladmandic** [comment]
that command line flag is the same as selecting it in settings.
