### ISSUE TITLE
"Generate" button is broken. Some other buttons like "Apply & Restart UI" or "Check for updates" are not working as well.

### ISSUE THREAD

**Issue by tripletto** [vladmandic/automatic#211]
### Issue Description

I tried 3 different themes and 2 browsers to verify. Generate button does nothing. Restarted webui a few times as well. Must have happened between yesterday evening and today. Chrome console says:

<pre>caught (in promise) ReferenceError: submit is not defined
    at Object.eval [as frontend_fn] (eval at <anonymous> (Blocks.svelte:66:7), <anonymous>:3:14)
    at ze (Blocks.svelte:283:6)
    at HTMLButtonElement.<anonymous> (Blocks.svelte:342:7)
    at index.37b24c07.js:4:1266
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.zr (index.37b24c07.js:4:1253)
    at HTMLButtonElement._ (Button.svelte:12:42)
    at index.37b24c07.js:4:1266
    at Array.forEach (<anonymous>)
    at HTMLButtonElement.zr (index.37b24c07.js:4:1253)
eval @ VM1468:3
ze @ Blocks.svelte:283
(anonymous) @ Blocks.svelte:342
(anonymous) @ index.37b24c07.js:4
zr @ index.37b24c07.js:4
_ @ Button.svelte:12
(anonymous) @ index.37b24c07.js:4
zr @ index.37b24c07.js:4
c @ Button.svelte:11
Promise.then (async)
ze @ Blocks.svelte:288
(anonymous) @ Blocks.svelte:342
(anonymous) @ index.37b24c07.js:4
zr @ index.37b24c07.js:4
_ @ Button.svelte:12
(anonymous) @ index.37b24c07.js:4
zr @ index.37b24c07.js:4
c @ Button.svelte:11</pre>

### Version Platform Description

Windows 10
gradio default, your dark theme and ...
Firefox, Chrome

**Comment by runew0lf** [comment]
Same a me, all the buttons have stopped working, i've tried multiple themes to see if that was the issue

**Comment by vladmandic** [comment]
omg, my bad, i forgot that same file enumerator is responsible for both python and javascript files, so modifying it stopped js files to load. fixed.
