### ISSUE TITLE
[Feature]: Improving XYZ, by adding "presets" of values for each parameter selected.

### ISSUE THREAD

**Issue by StableInfo** [vladmandic/automatic#2111]
### Feature description

So for example, when you select the parameter "CFG scale", some matrix box appear to select the range desired and distance.
So if you choose distance 0.5 and range 5 to 14, you will fill the values of X (or Y or Z) wth 5.0,5.5,6.0,6.5 .. until 14.

I believe it already exist for things like type of sampler (you can select them all at once but the yellow button), but other things that have values such as CFG etc are missing this type of option.

Good day

**Comment by vladmandic** [comment]
in dev branch - added full range control in xyz grid
