### ISSUE TITLE
[Issue]: UI and performance bug in Img2Img (resizing options) and Control Net (type quick pick)

### ISSUE THREAD

**Issue by danaildichev** [vladmandic/automatic#2112]
### Issue Description

The text of the labels for the options in Resize mode of img2img are duplicated. This bug can also be seen in Control Net's Control Type radio options

e.g. instead of "None", "Resize fixed", "Canny" they are "None,None" and "Resize fixed,Resize fixed" and "Canny,Canny"

See [screenshot - resize](https://i.imgur.com/PcU0YDD.png) and [screenshot - control net](https://i.imgur.com/aU9sTJg.png)

These text values are being passed into other parts of the app and causing:

- a value error for img2img
- an unhashable type 'list' in control net

I am able to use the UI, perform a canny preview, and click the generate button but I am unable to:

- perform an img2img operation
- perform an img2img with control net
- re control net, this happens when I use the Canny radio button and when I manually select canny from the preprocessor and model dropdowns 

### Version Platform Description

Using latest version pulled from git today on Chrome on Windows 10 with Python 3.10.11

Start up:

Already up to date.
Using VENV: F:\Media\vlad1111\automatic\venv

07:46:23-363474 INFO     Starting SD.Next
07:46:23-367442 INFO     Python 3.10.11 on Windows
07:46:23-397414 INFO     Version: df65df3f Wed Aug 30 09:45:47 2023 -0400
07:46:23-803377 INFO     nVidia CUDA toolkit detected

07:46:23-876312 WARNING  Modified files: ['modules/lora', 'modules/lycoris', 'webui.bat', 'launch_bkup.py']
07:46:23-910572 INFO     Disabled extensions: []
07:46:23-912060 INFO     Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
07:46:23-920492 INFO     Enabled extensions: ['canvas-zoom', 'sd-webui-openpose-editor',
                         'stable-diffusion-webui-two-shot', 'stable-diffusion-webui-vectorstudio']

### Relevant log output

```shell
-----------------------------
img2img
-----------------------------

Traceback (most recent call last):
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1429, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1239, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\gradio\components\radio.py", line 170, in preprocess
    return [value for _, value in self.choices].index(x)
ValueError: ['Resize fixed', 'Resize fixed'] is not in list



-----------------------------
control net
-----------------------------
Traceback (most recent call last):
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\Media\vlad1111\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 541, in filter_selected
    ) =  global_state.select_control_type(k)
  File "F:\Media\vlad1111\automatic\extensions-builtin\sd-webui-controlnet\scripts\global_state.py", line 228, in select_control_type
    default_option = preprocessor_filters[control_type]
TypeError: unhashable type: 'list'
Traceback (most recent call last):
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "F:\Media\vlad1111\automatic\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "F:\Media\vlad1111\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet_ui\controlnet_ui_group.py", line 541, in filter_selected
    ) =  global_state.select_control_type(k)
  File "F:\Media\vlad1111\automatic\extensions-builtin\sd-webui-controlnet\scripts\global_state.py", line 228, in select_control_type
    default_option = preprocessor_filters[control_type]
TypeError: unhashable type: 'list'
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by fbellgr** [comment]
With regard to ControlNet,  I find it very glitchy and often just not working when it comes to remembering / initializing settings.
There are a few issues open on the extension's repo. Have you tried checking out an older revision of ControlNet? I find my issues going away when I use [this revision](https://github.com/Mikubill/sd-webui-controlnet/commit/eeec9d8d6d31784a1583744528402f1bc7bcbd3d).

**Comment by vladmandic** [comment]
try deleting config.json and ui-config.json, issue should be resolved but if bad values were written in config, its needs clearing.

**Comment by danaildichev** [comment]
> try deleting config.json and ui-config.json, issue should be resolved but if bad values were written in config, its needs clearing.

I did. I tired to do img2mg and I got the same result. There is duplicated text in the label and value of the radio inputs for Resize Mode and Control Type.

Right now I am thinking about reverting to commit [48c0ce9](https://github.com/vladmandic/automatic/commit/48c0ce9b2b46aec36a0c722eef92733a4a21793d) from 3 days ago. That's the most recent one before someone came thru and made some oddball changes to default settings in commit 90afba3.

**Comment by vladmandic** [comment]
default settings commit has been reverted.
duplicate labels have nothing to do with that, it has to do with gradio making undocumented change how radio buttons behave.

**Comment by danaildichev** [comment]
I understand.

The last time I used Next was Aug 16th. Right now as far as I can tell the quickest way to get this working again is to revert to a previous commit.

**Comment by fbellgr** [comment]
Have you tried or considered trying a fresh clone? Rename current automatic folder, clone repo, move over from old folder: venv and models then launch.

**Comment by danaildichev** [comment]
> Have you tried or considered trying a fresh clone? Rename current automatic folder, clone repo using same location as the old one, move over from old folder: venv and models then launch.

That sounds less impactful than a revert. I'll try that. Thank you.

**Comment by danaildichev** [comment]
> No guaranty. Just sometimes I had issue after upgrading from previous versions and that solved it. Hope it's one of these cases.
> 
> To me, recent revisions of ControlNet just aren't working properly. Still waiting for any issue on their repo to be acknowledged or shutdown.

Yeah, if it's a problem with Gradio like vladmandic mentioned then a fresh install won't change anything.

**Comment by fbellgr** [comment]
> Yeah, if it's a problem with Gradio like vladmandic mentioned then a fresh install won't change anything.

With ControlNet, there are actually UI issues that have nothing to do with the version of Gradio in SD.Next.
Reverting to an older version of ControlNet fixes the issues I have with it, but they are different issues from what you are describing.

**Comment by danaildichev** [comment]
@fbellgr The fresh install is performing img2img. I need to copy over a bunch of things to try Control Net, but it's looking good.

@vladmandic I'm hoping that using the fresh install will be the solution here. 

Thank you to both of you.

**Comment by vladmandic** [comment]
@danaildichev sounds good - update the issue when you can

**Comment by danaildichev** [comment]
@vladmandic it might not be gradio. I copied over a bunch of things and the problem came back. When I deleted all of the .pth files from extensions-builtin\sd-webui-controlnet\models the problem went away

**Comment by fbellgr** [comment]
I typically just bring back the whole models folders when I fresh-clone. In fact the whole thing, in my case, is just a bunch of symlinks. There is nothing in there that creates conflicts. So the quick road to fresh-cloning is to use the exact same path (so that venv works), keep the old venv, keep the old models.

**Comment by vladmandic** [comment]
> I copied over just canny.pth and the error isn't appearing

thanks for the update. i'll close the issue for now, but if it reoccurs, update here and i'll reopen.

**Comment by danaildichev** [comment]
I'm running with just canny. when I have time I'll play around with it
