### ISSUE TITLE
[Feature]: Diffusers backend --medvram and --lowvram checkboxes should be radio buttons.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#2115]
### Feature description

The Diffusers settings;
`Enable model CPU offload (--medvram)`
and
`Enable sequential CPU offload (--lowvram)`
should be radio buttons, as they're incompatible with each other.

This is just a minor nitpick, as the second option will auto-override the first, if both are ticked.

### Version Platform Description

Python 3.10.11 on Windows
Upgraded to version: 8bf0e71a Wed Aug 30 23:17:35 2023 +0300
Using DirectML Backend

**Comment by Aptronymist** [comment]
> ### Feature description
> The Diffusers settings; `Enable model CPU offload (--medvram)` and `Enable sequential CPU offload (--lowvram)` should be radio buttons, as they're incompatible with each other.
> 
> This is just a minor nitpick, as the second option will auto-override the first, if both are ticked.
> 
> ### Version Platform Description
> Python 3.10.11 on Windows Upgraded to version: [8bf0e71](https://github.com/vladmandic/automatic/commit/8bf0e71a244d9ee66b834895e3d1f11894b27155) Wed Aug 30 23:17:35 2023 +0300 Using DirectML Backend

Let me point out that: 
1. They're not incompatible, they supersede the previous as you go down.
2. If they were radio buttons, you would not be able to use the Move To options at all, as either of these overrides that, radio buttons are either selected or not, and one has to be.

**Comment by brknsoul** [comment]
> If they were radio buttons, you would not be able to use the Move To options at all, as either of these overrides that, radio buttons are either selected or not, and one has to be.

`( ) Disable offloading`

**Comment by Aptronymist** [comment]
> > If they were radio buttons, you would not be able to use the Move To options at all, as either of these overrides that, radio buttons are either selected or not, and one has to be.
> 
> `( ) Disable offloading`

Better yet, rather than change the current format of it, which would add yet another choice, that conflicts with shuffle mode, we leave it as checkboxes and alter the description a little. It could be structured better and that's easy, just like I did image options/image paths/postprocessing.

**Comment by vladmandic** [comment]
closing as although correct, its not necessary and would cause compatibility issues.
