### ISSUE TITLE
[Extension]: Dynamic thresholding changes secondary sampler name

### ISSUE THREAD

**Issue by afbagwell** [vladmandic/automatic#2124]
### Issue Description

The secondary sampler metadata that was recently added back is (at least in some instances) adding text to the name of the sampler that shouldn't be there. In the case below, I'm using the DPM++ 2M Karras setting, but the recorded image metadata and re-population of it to the "From Text" UI has appended "_dynthres218" to the sampler name. Obviously this completely mucks up recreating the original image. ;)

<img width="454" alt="Screenshot 2023-09-01 142236" src="https://github.com/vladmandic/automatic/assets/1495201/650c26e8-cf9a-4e25-8d22-5d963f5e32fa">

### Version Platform Description

app: automatic.git
updated: 2023-08-31
hash: ce0be4a2
url: https://github.com/vladmandic/automatic.git/tree/master
arch: x86_64
cpu: x86_64
system: Linux
release: 5.10.16.3-microsoft-standard-WSL2
python: 3.10.12
torch: 2.0.1+cu118 Autocast  half
device: NVIDIA GeForce RTX 4090 (1) (sm_90) (8, 9)
cuda: 11.8
cudnn: 8904
driver: 531.79

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
That's weird.
Can you upload the image so I can check raw metadata?

**Comment by afbagwell** [comment]
Here's an example. It appears that the end number changes. In this case it's "_dynthres1085"

![3313247675_20230901_181433_328547](https://github.com/vladmandic/automatic/assets/1495201/d3a8ab4f-8070-4363-a85d-9e211c07fbb1)

**Comment by afbagwell** [comment]
If I had to guess, I'd say _dynthres is somehow related to dynamic threshold, which I have turned on in these images runs. Maybe there is some metadata that is attempting to be included but is not being parsed and appended correctly?

**Comment by vladmandic** [comment]
i was just looking at that. dynamic thresholding is actually modifying sampler (that's how it works internally) and as part of that, its changing its name. not much i can do about that unless you want to report it to author.

**Comment by afbagwell** [comment]
Reported on the extension github issues page.

**Comment by vladmandic** [comment]
closing as this issue was reported to extension owner 4 months ago without any progress.
