### ISSUE TITLE
[Extension]: ConrolNet always disabled on launch, even if "original" models in use

### ISSUE THREAD

**Issue by 6630507** [vladmandic/automatic#2129]
### Issue Description

Whenever I launch webui, controlnet is disabled by the diffusers pipeline, even if i have webui configured to use 1.5/original.  This prevents me from using ControlNet under all circumstances

### Version Platform Description

Ubuntu 20.04, CUDA

### URL link of the extension

https://github.com/Mikubill/sd-webui-controlnet

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
can you show proof of that claim?
- set backend=original
- enable controlnet extension
- restart server
- upload log

**Comment by acorderob** [comment]
I think the disabling of the extensions incompatible with diffusers should not be persisted in config.json, so just restarting the server after changing to original would restore them, without the user having to know which ones he has to enable.

**Comment by vladmandic** [comment]
@acorderob i agree, i've made the change.
