### ISSUE TITLE
[Feature]: Package Update timm 0.9.2

### ISSUE THREAD

**Issue by brunogcar** [vladmandic/automatic#2131]
### Feature description

Extension [depthmap-script](https://github.com/thygate/stable-diffusion-webui-depthmap-script) updated requirements, probably ControlNet will  do as well, due to A1111 update, related to timm, torch, midas, zoe

https://github.com/thygate/stable-diffusion-webui-depthmap-script/commit/91b5ea23c05b530b8d230d1686ed98113dd10ee8

```
11:38:15-126401 INFO     Verifying requirements
11:38:15-145441 WARNING  Package wrong version: timm 0.9.7 required 0.6.13
11:38:15-146553 INFO     Installing package: timm==0.6.13
11:38:21-115497 INFO     Verifying packages
11:38:21-117499 INFO     Verifying repositories
11:38:24-674053 INFO     Verifying submodules
11:39:18-170469 INFO     Extension installed packages: stable-diffusion-webui-depthmap-script ['timm==0.9.7']
```

not an issue as things seem to work,  except that warning and nor really extension issue, so i would say upstream or backport compatibility

### Version Platform Description

11:38:14-655255 INFO     Starting SD.Next
11:38:14-662837 INFO     Python 3.10.6 on Windows
11:38:14-687078 INFO     Version: 1d04014d Sat Sep 2 17:25:31 2023 +0300
11:38:15-037586 INFO     nVidia CUDA toolkit detected

**Comment by vladmandic** [comment]
done in dev branch.
