### ISSUE TITLE
[Issue]: Process Batch ERROR Exception: division by zero

### ISSUE THREAD

**Issue by gungwang** [vladmandic/automatic#2132]
### Issue Description

I tried to run "Process Batch" and "Process Folder" on Webui. But, 
only the 1st image is processed. After that, it shows the error "division by zero":

**Error in console:** 

09:08:05-392913 ERROR    Exception: division by zero
09:08:05-393983 ERROR    Arguments: args=(2, None, None, '/home/wang/automatic/outputs/text/1',
 '/home/wang/automatic/outputs/text/1-4K', True, 0, 4, 512, 512, True, 'R-ESRGAN 4x+',
'Lanczos', 0.5, 0, 0.5, 0.5, 'None', False, False, 240, 10, 10) kwargs={}
09:08:05-395077 ERROR    gradio call: ZeroDivisionError
 Traceback (most recent call last)  

│ /home/wang/automatic/modules/call_queue.py:34 in f                                                                   
│    33 │   │   │   try:                                                                                            
│ ❱  34 │   │   │   │   res = func(*args, **kwargs)                                                                    
│    35 │   │   │   │   progress.record_results(id_task, res)

│ /home/wang/automatic/modules/ui_postprocessing.py:16 in submit_click                                                 
│   15 def submit_click(tab_index, extras_image, image_batch, extras_batch_input_dir, extras_ba                        │
│ ❱ 16 │   result_images, geninfo, js_info = postprocessing.run_postprocessing(tab_index, extra                        │
│   17 │   return result_images, geninfo, json.dumps(js_info), ''                                                      
│ /home/wang/automatic/modules/postprocessing.py:67 in run_postprocessing                                              
│    66 │   │   │   basename = ''                                                                                      │
│ ❱  67 │   │   geninfo, items = images.read_info_from_image(image)                                                    │
│    68 │   │   params = generation_parameters_copypaste.parse_generation_parameters(geninfo)                          
│ /home/wang/automatic/modules/images.py:633 in read_info_from_image                                                   
│   632 │   │   │   │   │   if isinstance(val, tuple) and isinstance(val[0], int) and isinstance                       
│ ❱ 633 │   │   │   │   │   │   val = round(val[0] / val[1], 2)                                                        
│   634 │   │   │   │   │   if val is not None and key in ExifTags.TAGS: # add known tags
                              
ZeroDivisionError: division by zero
`

![image](https://github.com/ospangler/intel-arc-stable-diffusion-tutorial/assets/13302008/a33a1ad5-83a8-4bba-a401-ba1ca38a09e0)

### Version Platform Description

Windows 11  WSL2 Ubuntu 22:
5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev will merge to main soon.
