### ISSUE TITLE
[Issue]: UI Freeze with image inserted in Process tab

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#214]
### Issue Description

If I insert a image and then click any of the buttons (show, image, inpaint), the whole thing freezes. Nothing in the browser works anymore. Only a browser reload makes it work again.

```
Traceback (most recent call last):
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 346
```

### Version Platform Description

Win10, Firefox 106
Version: e8d8dae4 Tue Apr 18 10:06:55 2023 -0400

**Comment by vladmandic** [comment]
what do you mean "instert image" and then click buttons? if you load image in left column, you need to do something with it so it shows up in right column before any of the buttons in right column have any meaning.

for example:
1. load
2. click generate (by default its 4x upscale)
3. click `-> image`
4. it transfers image to `from image` tab

**Comment by Woisek** [comment]
*insert , was a typo. 😌
You pointed out, PNG Info is now in the Process tab. So, when I want the PNG info, I load up an image and press -> text to send the info to the From Text tab. This should be the way, right?
But instead, the whole UI freezes and no matter what I click, nothing works. No buttons, no tabs, no dropdown. Only checkboxex can be clicked.
Can't say since when it is like this, because I haven't used the Process tab lately.

**Comment by vladmandic** [comment]
just tried:
1. load image -> exif data shows up in right column
2. press button `-> text` just below image
3. ui switches to `from text` tab and all fields are populated.

do you have any errors in console?
anything in browser inspector?

**Comment by Woisek** [comment]
Error is in first post.

**Comment by vladmandic** [comment]
ah, sorry.
keyerror typically means that some api param does not match expected type, but no way to see which one.
can you try: ui -> settings -> apply settings (even if you changed nothing, this will validate everything)
and then restart server and try again

**Comment by Woisek** [comment]
OK, this seems to have resolved this ... 😓

**Comment by vladmandic** [comment]
phew :)
btw, unless its not obvious, i really hate gradio.

**Comment by Aure0** [comment]
I have the exact same issue in the Image Browser tab, when clicking "-> Image" or "-> Text", I get this error (clicking "apply settings didn't help") : 
`Traceback (most recent call last):
  File "D:\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 938
`

This example is when clicking on "-> Image".

**Comment by vladmandic** [comment]
And did you follow recommended steps?

**Comment by Slightlyxz** [comment]
Also getting this error, but it only happens after pressing "Apply & restart UI" inside the extensions tab, which causes a different error on it's own. (Didn't check if there is a issue for this yet, if not I can open one).

```
WebSocket closed (ignore asyncio.exceptions.CancelledError)
Traceback (most recent call last):
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
Server shutdown
Server restart
```

When I stop the UI and start it again, the error is gone, until I press the mentioned button again.

**Comment by vladmandic** [comment]
Just to check, what does very first line says?

`WebSocket closed (ignore asyncio.exceptions.CancelledError)`

**Comment by Slightlyxz** [comment]
This is everything from me starting the webui and then pressing the "Apply & restart UI" button in extensions again:

```
venv "D:\webui vladmandic\automatic\venv\Scripts\Python.exe"
04:25:21-969321 INFO     Python 3.10.6 on Windows
04:25:22-027942 INFO     No changes detected: quick launch active
04:25:22-028930 INFO     Setting environment tuning
04:25:25-425482 INFO     Torch 2.0.0+cu118
04:25:25-454292 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
04:25:25-455797 INFO     Torch detected GPU: NVIDIA GeForce RTX 4070 Ti VRAM 12282 Arch (8, 9) Cores 60
04:25:25-455797 INFO     Server arguments: []
Available models: D:\webui vladmandic\automatic\models\Stable-diffusion 15
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\webui vladmandic\automatic\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Loading theme: gradio/default
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Loading weights: D:\webui vladmandic\automatic\models\Stable-diffusion\cetusMix_Version35.safetensors ━━━━━ 0.0/… -:--:…                                                                                                            GB
Creating model from config: D:\webui vladmandic\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: D:\webui vladmandic\automatic\models\Stable-diffusion\pastel-waifu-diffusion.vae.pt ━━━━━ 0.0/4… -:--:…                                                                                                           MB
Applying scaled dot product cross attention optimization
Embeddings loaded: bad-artist-anime, bad-artist, bad-hands-5, bad-image-v2-39000, bad_prompt_version2, easynegative,
ng_deepnegative_v1_75t, ulzzang-6500 (8)
Model loaded in 10.6s (load=0.8s create=0.4s apply=5.6s vae=3.0s move=0.7s embeddings=0.2s)
Startup time: 26.0s (torch=5.6s gradio=1.9s libraries=1.3s codeformer=0.2s scripts=3.6s ui=2.5s start=0.1s
checkpoint=10.8s)
WebSocket closed (ignore asyncio.exceptions.CancelledError)
Traceback (most recent call last):
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
Server shutdown
Server restart
Available models: D:\webui vladmandic\automatic\models\Stable-diffusion 15
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: D:\webui vladmandic\automatic\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Loading theme: gradio/default
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Startup time: 3.8s (scripts=1.1s ui=2.3s start=0.1s scripts app_started_callback=0.3s)
```

The `WebSocket closed (ignore asyncio.exceptions.CancelledError)` line appears after pressing the button.

Now when I'm trying to copy generation info like the other users here, I'm getting the error again, until I restart the ui w/o pressing the button in extensions:


```
Traceback (most recent call last):
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\webui vladmandic\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 329
```

Also sorry for the kinda terrible explanation.

**Comment by vladmandic** [comment]
You misunderstood /misread - the line I've quoted **explicitly says to ignore that exception**.
And if you care about reason why, it's already been discussed. So you're error is not an error at all.

**Comment by Slightlyxz** [comment]
Ah okay, sorry.
Just happened to have the same thing happening as other users in this issue, only exactly when using the button in the extensions tab, else it worked fine.

**Comment by Woisek** [comment]
Want to add: This problem also happens, if an wrong image is accidently inserted, like an AVIF for example.
