### ISSUE TITLE
[Issue]: Problem with the new "Extra Networks" update (Weird move in the UI)

### ISSUE THREAD

**Issue by landrasss** [vladmandic/automatic#2140]
### Issue Description

With the new update, the UI auto-adjusts weirdly when hovering over and loading descriptions for Loras and others. I think it would be convenient to have the specific button again to load them.

And another question, is there any way to be able to edit the Loras tags from the interface or with some other tool outside of automatic?

![Edit Tag](https://github.com/vladmandic/automatic/assets/112908884/84735b57-e8a6-4e08-a373-6589a4fc5a13)

Thanks in advance.

### Version Platform Description

Starting SD.Next
Python 3.10.6 on Windows
Version: 26e18b0a Wed Sep 6 13:28:35 2023 -0400
nVidia CUDA toolkit detected
Disabled extensions: []
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
Enabled extensions: ['a1111-sd-webui-tagcomplete', 'adetailer', 'sd-webui-reactor']

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
regarding tags - no, those are set in model metadata itself. even if you could edit tags, what would that mean? newly edited tag would be a complete mismatch with tag that was used during training. and the fact that most authors dont set tags correctly is not something i can change.

regarding ui move. yes, its a bit annoying for long descriptions. but is it really an issue? issue means something is not working. this is valid, but more of a discussion item or at best a feature request. no, i don't want to have a button to read descriptions. but i'm open to suggestions where to place them so they don't impact ui that much.

i'm closing as its not an issue, but feel free to post with suggestions.
