### ISSUE TITLE
[Issue]: ControlNet not working after update

### ISSUE THREAD

**Issue by caleidoscopio** [vladmandic/automatic#2144]
### Issue Description

After I updated from Vlad Diffusion to SD.Next I cannot use ControlNet v1.1.401 anymore.

When starting SD.Next I get this message:

```
ControlNet v1.1.401
Warning: ControlNet failed to load SGM - will use LDM instead.
```

### Version Platform Description

MacBook Pro 16-inch, 2021
32 GB RAM
macOS Ventura 13.4.1 (c) 

Microsoft Edge for Business
Version 116.0.1938.69 (Official build) (arm64)

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
That's just informational, not the reason why ControlNet doesn't work. Also, ControlNet is an extension and needs to be the issue report needs to be classed as such.

**Comment by caleidoscopio** [comment]
The extension issue requires the URL of the extension, which I am unaware of because it is installed by default.

**Comment by caleidoscopio** [comment]
How would I know you're using this one and not one of the forked versions?

**Comment by caleidoscopio** [comment]
I just realised you can do that. It retuned this URL https://github.com/Mikubill/sd-webui-controlnet

**Comment by vladmandic** [comment]
what was the issue? it cannot be the message you've posted as that is INFO and has no impact.

**Comment by caleidoscopio** [comment]
It's not solved. I closed it because I was informed this is an extension issue. I don't have the availability to find out at the moment.

**Comment by vladmandic** [comment]
you don't have availability to report what the problem is?
