### ISSUE TITLE
[Issue]: Extra Networks does not refresh new Loras, Checkpoints and others in the UI

### ISSUE THREAD

**Issue by landrasss** [vladmandic/automatic#2149]
### Issue Description

With the new update, if I put new files, the Extra Networks refresh button does not update the new Loras and others on the fly. I have to close the console and run SD.Next again to get them to show up in the UI. Previous updates, this was working fine.

Thanks in advance.

PD: I just realized that the refresh button in the VAE, Checkpoints, outside of Extra Networks, doesn't work either.

### Version Platform Description

Starting SD.Next
Python 3.10.6 on Windows
Version: ee40033c Thu Sep 7 11:53:55 2023 -0400
nVidia CUDA toolkit detected
Disabled extensions: []
Enabled extensions-builtin: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR',
                         'Lora', 'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
Enabled extensions: ['a1111-sd-webui-tagcomplete', 'adetailer', 'sd-webui-reactor']

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by GamingDiffusion** [comment]
Yes, I just noticed this when I did a model merge and wanted to test the model. sd_model_checkpoint shows the generated models only after a restart

**Comment by vladmandic** [comment]
fixed.
