### ISSUE TITLE
[Issue]: Deforum starts but stops with error

### ISSUE THREAD

**Issue by gadsdencode** [vladmandic/automatic#215]
### Issue Description

After pressing generate button Deforum starts and gets through 2 iterations before hitting the error:

gradio call: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ G:\SD-ALT\automatic\modules\call_queue.py:61 in f                                                                    │
│                                                                                                                      │
│    60 │   │   │   │   pr.enable()                                                                                    │
│ ❱  61 │   │   │   res = list(func(*args, **kwargs))                                                                  │
│    62 │   │   │   if shared.cmd_opts.profile:                                                                        │
│                                                                                                                      │
│ G:\SD-ALT\automatic\modules\call_queue.py:39 in f                                                                    │
│                                                                                                                      │
│    38 │   │   │   try:                                                                                               │
│ ❱  39 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    40 │   │   │   finally:                                                                                           │
│                                                                                                                      │
│                                               ... 2 frames hidden ...                                                │
│                                                                                                                      │
│ G:\SD-ALT\automatic/extensions/deforum-for-automatic1111-webui/scripts\deforum_helpers\colors.py:18 in               │
│ maintain_colors                                                                                                      │
│                                                                                                                      │
│   17 │   │   color_match_lab = cv2.cvtColor(color_match_sample, cv2.COLOR_RGB2LAB)                                   │
│ ❱ 18 │   │   matched_lab = match_histograms(prev_img_lab, color_match_lab, multichannel=True)                        │
│   19 │   │   return cv2.cvtColor(matched_lab, cv2.COLOR_LAB2RGB)                                                     │
│                                                                                                                      │
│ G:\SD-ALT\automatic\venv\lib\site-packages\skimage\_shared\utils.py:326 in fixed_func                                │
│                                                                                                                      │
│   325 │   │   │   if channel_axis is None:                                                                           │
│ ❱ 326 │   │   │   │   return func(*args, **kwargs)                                                                   │
│   327                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: match_histograms() got an unexpected keyword argument 'multichannel'
Traceback (most recent call last):
  File "G:\SD-ALT\automatic\venv\lib\site-packages\gradio\blocks.py", line 987, in postprocess_data
    if predictions[i] is components._Keywords.FINISHED_ITERATING:
IndexError: tuple index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\SD-ALT\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\SD-ALT\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "G:\SD-ALT\automatic\venv\lib\site-packages\gradio\blocks.py", line 991, in postprocess_data
    raise ValueError(
ValueError: Number of output components does not match number of values returned from from function f

I updated Gradio but did not solve issue. Also, I noticed I get this message about Deforum at startup:

venv "G:\SD-ALT\automatic\venv\Scripts\Python.exe"
14:55:13-855527 INFO     Python 3.10.6 on Windows
14:55:13-959687 INFO     Running setup
14:55:14-032661 INFO     Version: 71b29c99 Tue Apr 18 14:31:40 2023 -0400
14:55:14-379014 INFO     Updating Wiki
14:55:15-869211 INFO     Installing requirements
14:55:16-478988 INFO     Installing packages
14:55:16-481000 INFO     Installing repositories
14:55:16-772670 INFO     Installing submodules
14:55:20-465456 INFO     Updating submodules
14:55:33-355292 INFO     Extensions enabled: ['LDSR', 'Lora', 'ScuNET', 'SwinIR', 'clip-interrogator-ext',
                         'prompt-bracket-checker', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer',
                         'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'a1111-sd-webui-lycoris', 'model-keyword',
                         'multidiffusion-upscaler-for-automatic1111']
14:55:57-840684 INFO     Extensions enabled: ['StylePile', 'model-keyword', 'sd-webui-additional-networks',
                         'Hypernetwork-MonkeyPatch-Extension', 'sd-webui-multiple-hypernetworks',
                         'stable-diffusion-webui-promptgen', 'stable-diffusion-webui-state', 'sd-dynamic-prompts',
                         'sd_auto_fix', 'deforum-for-automatic1111-webui']
**14:56:06-999456 WARNING  Unknown branch for: G:\SD-ALT\automatic\extensions\deforum-for-automatic1111-webui**

### Version Platform Description

Windows 11 Pro
Python 3.10
Chrome Version 112.0.5615.87 (Official Build) (64-bit)

System Info:

![sys](https://user-images.githubusercontent.com/113121510/232883760-4fe669f2-8f40-4bd5-bf7c-72d545ea6ac5.png)

**Comment by vladmandic** [comment]
Is it working now when I changed load order?

**Comment by gadsdencode** [comment]
> Is it working now when I changed load order?

Doesn't seem to be fixed yet - same error. This is what it looks like right before error:

Deforum extension for auto1111 webui, v2.3b
Git commit: 4c0fdccc (Tue Apr 18 12:53:24 2023)
Saving animation frames to:
G:\SD-ALT\automatic\outputs/image\Deforum_20230418155811
Animation frame: 0/120
Seed: 4236938917
Prompt: HD, HDR tiny cute swamp bunny, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera
Neg Prompt: bad art, bad anatomy
Not using an init image (doing pure txt2img)
╭─────┬───┬───────┬─────┬──────┬────┬────╮
│Steps│CFG│Denoise│Angle│ Zoom │Tr X│Tr Y│
├─────┼───┼───────┼─────┼──────┼────┼────┤
│ 30  │7.0│ None  │  0  │1.0025│ 0  │ 0  │
╰─────┴───┴───────┴─────┴──────┴────┴────╯
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:07<00:00,  4.03it/s]
Animation frame: 2/120
Creating in-between cadence frame: 0; tween:0.50;
Creating in-between cadence frame: 1; tween:1.00;
Seed: 4236938918
Prompt: HD, HDR tiny cute swamp bunny, highly detailed, intricate, ultra hd, sharp photo, crepuscular rays, in focus, by tomasz alen kopera
Neg Prompt: bad art, bad anatomy
╭─────┬───┬───────┬─────┬─────┬────┬────╮
│Steps│CFG│Denoise│Angle│Zoom │Tr X│Tr Y│
├─────┼───┼───────┼─────┼─────┼────┼────┤
│ 30  │7.0│ 0.35  │  0  │1.003│ 0  │ 0  │
╰─────┴───┴───────┴─────┴─────┴────┴────╯
100%|██████████████████████████████████████████████████████████████████████████████████| 11/11 [00:01<00:00,  6.64it/s]
Animation frame: 4/120
Creating in-between cadence frame: 2; tween:0.50;
Creating in-between cadence frame: 3; tween:1.00;
gradio call: TypeError

**Comment by vladmandic** [comment]
so why did you close it? yes, its an extension issue, but still..
update: ok, i see it reopened now.

**Comment by gadsdencode** [comment]
Sorry for the close/re-open. I was looking through the discussions and noticed there was already a post about a likely known issue with deforum and libraries or something like that. Didn't want to spam with duplicates.

**Comment by vladmandic** [comment]
i appreciate good intentions :)
that issue was different (and its resolved)

**Comment by gadsdencode** [comment]
No idea if this is applicable here:

I have a separate install of Deforum locally https://github.com/HelixNGC7293/DeforumStableDiffusionLocal and I got the same error message with it. Did some searching with chatgpt and found an issue with the color.py file. 

"It appears that you are encountering an error with OpenCV, specifically with the image depth. The error message states that the input image has a depth of CV_64F, which is not supported. To resolve this issue, you can try converting the image depth to a supported format, such as CV_32F, before passing it to the cvtColor function.

You can do this by modifying the maintain_colors function in the colors.py file. Here's an example of how you can change the function:"

So I updated the color.py file from:

"from skimage.exposure import match_histograms
import cv2

def maintain_colors(prev_img, color_match_sample, mode):
    if mode == 'Match Frame 0 RGB':
        return match_histograms(prev_img, color_match_sample, multichannel=True)
    elif mode == 'Match Frame 0 HSV':
        prev_img_hsv = cv2.cvtColor(prev_img, cv2.COLOR_RGB2HSV)
        color_match_hsv = cv2.cvtColor(color_match_sample, cv2.COLOR_RGB2HSV)
        matched_hsv = match_histograms(prev_img_hsv, color_match_hsv, multichannel=True)
        return cv2.cvtColor(matched_hsv, cv2.COLOR_HSV2RGB)
    else: # Match Frame 0 LAB
        prev_img_lab = cv2.cvtColor(prev_img, cv2.COLOR_RGB2LAB)
        color_match_lab = cv2.cvtColor(color_match_sample, cv2.COLOR_RGB2LAB)
        matched_lab = match_histograms(prev_img_lab, color_match_lab)
        return cv2.cvtColor(matched_lab, cv2.COLOR_LAB2RGB)"

to:

"from skimage.exposure import match_histograms
import cv2
import numpy as np

def maintain_colors(prev_img, color_match_sample, mode):
    prev_img = prev_img.astype(np.float32)  # Convert image depth to CV_32F
    color_match_sample = color_match_sample.astype(np.float32)  # Convert image depth to CV_32F

    if mode == 'Match Frame 0 RGB':
        return match_histograms(prev_img, color_match_sample, multichannel=True)
    elif mode == 'Match Frame 0 HSV':
        prev_img_hsv = cv2.cvtColor(prev_img, cv2.COLOR_RGB2HSV)
        color_match_hsv = cv2.cvtColor(color_match_sample, cv2.COLOR_RGB2HSV)
        matched_hsv = match_histograms(prev_img_hsv, color_match_hsv, multichannel=True)
        return cv2.cvtColor(matched_hsv, cv2.COLOR_HSV2RGB)
    else: # Match Frame 0 LAB
        prev_img_lab = cv2.cvtColor(prev_img, cv2.COLOR_RGB2LAB)
        color_match_lab = cv2.cvtColor(color_match_sample, cv2.COLOR_RGB2LAB)
        matched_lab = match_histograms(prev_img_lab, color_match_lab)
        return cv2.cvtColor(matched_lab, cv2.COLOR_LAB2RGB)"

**Comment by amiremami** [comment]
Hey Vlad, thanks a lot for your support. 

I wanted to interpolate a video with Deforum, it says "Video stitching done in 0.05 seconds!" , with this time, it means it's not working and nothing generated. Is this related to this github issue? So, I guess nothing in Deforum works currently, yes?

Thanks

**Comment by vladmandic** [comment]
honestly, i don't know, checking out whats going on with **deforum** extension has been on my todo list, just delayed until i was working on core. if there are no new critical issues, i should be able to take a look at it soon.

**Comment by hithereai** [comment]
@vladmandic welcome to talk with me on discord. It's hard keeping up with webui for mac, windows, linux, g-colab free tier, pro tier, and vast.ai/ runpod etc' :)

**Comment by hithereai** [comment]
webui: 
scikit-image            0.19.2

vladui:
scikit-image                 0.20.0

this is the core of that histogram error. I'll see what I can do about it in the weekend.

**Comment by vladmandic** [comment]
if that's what it takes, easy. `scikit-image` is used by outpainting, but that code is not fussy about version.
current requirements did not have it pinned to any specific version, so setup automatically installed latest available.
i'll pin it: `scikit-image==0.19.3`
can you confim if you add that to `requirements.txt`, `deforum` actually works?

**Comment by hithereai** [comment]
@vladmandic keep the new version, I already created a branch called 'vlad-fixes', this error is fixed, now I'm handling the others.

**Comment by vladmandic** [comment]
> @vladmandic keep the new version, I already created a branch called 'vlad-fixes', this error is fixed, now I'm handling the others.

sounds good, ping me if you need anything from my side

**Comment by hithereai** [comment]
@vladmandic https://github.com/deforum-art/deforum-for-automatic1111-webui/pull/592

Working for me, didn't test CN, I heard there's some issues with the location of the models. Will test laters.

**Comment by hithereai** [comment]
ControlNet doesn't work because it's located in a different folder than in the reg webui - extensions-builtin and not 'extensions'. 

I will make it dynamic laters.

**Comment by vladmandic** [comment]
thanks for the deforum fixes!!!
closing this issue as controlnet is tracked separately.
