### ISSUE TITLE
[Issue]: Upscale in Process Image tab causes crash

### ISSUE THREAD

**Issue by afbagwell** [vladmandic/automatic#2152]
### Issue Description

Any attempt to upscale an image in the "Process Image" tab causes the server to crash with the following stack trace:

```
Exception in thread Thread-1 (atomically_save_image):
Traceback (most recent call last):
  File "/home/afbag/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/afbag/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/afbag/sdnext/modules/images.py", line 445, in atomically_save_image
    if extension[0] != '.': # add dot if missing
IndexError: string index out of range
```

### Version Platform Description

Starting SD.Next
Python 3.10.12 on Linux
Version: e0d8a924 Thu Sep 7 23:47:24 2023 -0400
nVidia CUDA toolkit detected
arch: x86_64
cpu: x86_64
system: Linux
release: 5.15.90.1-microsoft-standard-WSL2
torch: 2.0.1+cu118 Autocast half
device: NVIDIA GeForce RTX 4090 (1) (sm_90) (8, 9)
cuda: 11.8
cudnn: 8904
driver: 531.79
Firefox: 117.0 (64-bit) Windows

### Relevant log output

```shell
see above
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i cannot reproduce this, but according to provided backtrace issue is that desired filename/extension is somehow blank. 
what are your settings for:
- File format for generated images
- Add number to filename when saving
- Use original name for output filename during batch process
- Use upscaler name as filename suffix in the extras tab
- Images filename pattern

**Comment by afbagwell** [comment]
File format: png
Add number to filename when saving: unchecked
Use original name for output filename during batch process: checked
Use upscaler name as filename suffix in the extras tab: checked
Image filename pattern set to: [seed]_[datetime<%Y%m%d_%H%M%S_%f>]

These are the same settings I've been using for months without issue.

I'm encountering this running on a single image, not a batch job.

**Comment by vladmandic** [comment]
filename pattern was not processed correctly for upscale-only jobs and since you don't have "add number", it resulted in invalid filename.

fixed.
