### ISSUE TITLE
[Issue]: Attempting to install a SDXL Lora as a model leaves the project in a broken state

### ISSUE THREAD

**Issue by inktomi** [vladmandic/automatic#2160]
### Issue Description

If you use the model downloader to attempt to download a lora (for instance, https://huggingface.co/artificialguybr/LogoRedmond-LogoLoraForSDXL) it begins the process but quickly fails. 

When it fails, an invalid folder is left under models/Diffusers. This will break the project at startup, as "snapshots" is not found where it's expected. This means that no Diffusers will load or be available, as this single invalid folder breaks the loading process (in my case, this was the first folder listed alphabetically). 

When a model fails to install for some reason, the installer should clean up any remaining files and folders. 

Something like.. 

```
try { 
    // install 
} finally {
    //clean up temp or everything if the install failed. 
}
```

### Version Platform Description

Latest `master` branch pulled this morning. This issue has been around though, I just figured out the cause today.

### Relevant log output

```shell
....
11:36:58-336110 ERROR    Error listing diffusers: models\Diffusers [WinError 3] The system cannot find the path specified:
                         'models\\Diffusers\\models--artificialguybr--LogoRedmond-LogoLoraForSDXL\\snapshots'
11:36:58-342115 INFO     Available models: models\Stable-diffusion items=34 time=0.01s
11:37:00-555771 INFO     Extension: script='extensions-builtin\sd-dynamic-thresholding\scripts\dynamic_thresholding.py' ======
11:37:00-557773 INFO     Extension: script='extensions-builtin\sd-dynamic-thresholding\scripts\dynamic_thresholding.py' Warning! Using legacy KDiff version! Is your WebUI
                         up to date?
11:37:00-558774 INFO     Extension: script='extensions-builtin\sd-dynamic-thresholding\scripts\dynamic_thresholding.py' ======
11:37:02-057235 INFO     Extensions time: 3.63s { clip-interrogator-ext=1.89s Lora=0.17s sd-extension-aesthetic-scorer=0.06s sd-webui-agent-scheduler=0.35s
                         stable-diffusion-webui-images-browser=0.09s stable-diffusion-webui-rembg=0.84s }
11:37:02-127803 INFO     Loading UI theme: name=black-teal style=Auto
11:37:02-396558 INFO     Themes: builtin=6 default=5 external=38
11:37:02-397558 INFO     Extra network thumbnails: lora created=1
11:37:09-010519 INFO     Local URL: http://localhost:7860/
11:37:09-011520 INFO     Initializing middleware
11:37:09-168167 INFO     [AgentScheduler] Task queue is empty
11:37:09-168167 INFO     [AgentScheduler] Registering APIs
11:37:09-318309 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16 context=no_grad fp16=True bf16=False
11:37:09-320311 WARNING  Selected checkpoint not found: stabilityai/stable-diffusion-xl-base-1.0 [f898a3e026]
11:37:09-321312 INFO     Loading diffuser model: G:\automatic\models\Stable-diffusion\512-inpainting-ema.safetensors
```

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
- model download is designed for models only, not for something random from huggingface site.
- cleanup on aborted download is not automatic as main use case when downloading a large model is ability to resume download
- yes, diffusers enumeration should not fail because of a single corrupt model, that is now fixed.
