### ISSUE TITLE
[Issue]: SD next not support any more styles.csv

### ISSUE THREAD

**Issue by ShmuelRonen** [vladmandic/automatic#2161]
### Issue Description

Hello...

 I have a styles.csv file that I work a lot to make and arrange by categories for XDXL. 
Starting with the latest versions, SD next to my surprise no longer supports this format but only the .json format and that too in separate files where each style is found separately.
Is there an option to the users to choose which styles format they want to use?

### Version Platform Description

W:\V\automatic>webui.bat --backend diffusers --medvram --experimental --upgrade
Using VENV: W:\V\automatic\venv
17:49:29-459635 INFO     Starting SD.Next
17:49:29-465636 INFO     Python 3.10.7 on Windows
17:49:29-753634 INFO     Version: app=sd.next updated=2023-09-10 hash=4898c0ff
                         url=https://github.com/vladmandic/automatic/tree/master
17:49:30-411642 INFO     Updating main repository
17:49:33-401781 INFO     Upgraded to version: 60df52f6 Sun Sep 10 08:32:53 2023 -0400
17:49:33-449780 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.7
17:49:33-455795 INFO     nVidia CUDA toolkit detected

### Relevant log output

```shell
No
```

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
> Is there an option to the users to choose which styles format they want to use?
no.

> I have a styles.csv file that I work a lot to make and arrange by categories for XDXL.
feel free to sort new styles into subfolders to organize them however you like.

anyhow, this is a good question - but its not something you should create issue for - because clearly its working as designed. if something is broken, then you create an issue. for things like this, create a discussion topic or ask on discord.
