### ISSUE TITLE
[Issue]: Style.csv

### ISSUE THREAD

**Issue by Ke031** [vladmandic/automatic#2164]
### Issue Description

Hello Vlad ! congratulations for your incredible work for SD.NEXT ! You are really a talented coder !
but i have a problem since the last update, before i was able to load as Automatic 1111 my styles.csv Files.
but now even if they're in the root or in the models folder they are showing weird and some line missing too.

i saw there was a new folders with models/styles, i deleted all the files inside cause i saw the lines on the webui was showed exactly as files i saw on the models folder, and re add my style.csv on root but now there is nothing anymore, no styles at all :/

it's really annoying, maybe there is a solution but i don't know which one, and nobody talks about that on internet :)

And i i have a last question a reverted my nvidia drivers to 532.03 (cause the new implementations of memory management cause sd running incredibly slow) for you, is there a better drivers than that one ?

### Version Platform Description

Windows 10 21h1
Nvidia 532.03 
GeForce RTX 4090 X2 
64Go RAM
SD.NEXT last update.

### Relevant log output

```shell
No logs, it's a Styles.CSV problem..
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
new version of sdnext automatically converts styles.csv to models/styles/*.json and its a one-time operation.
your styles.csv file from that point is not used at all (just not deleted as i don't want to delete user files)

if you've manually deleted those files, then you need to force conversion to happen again:
- delete entre folder models/styles
- in settings -> paths -> set styles path back to `styles.csv`

**Comment by Ke031** [comment]
the problem is that i made special categorie in that csv files with like that =>
![image](https://github.com/vladmandic/automatic/assets/119963095/6317878f-b8f4-4001-97a5-0f939c642131)

but now the files seems to be a mich mach of all styles i made, on week needed to build this files, it's like a giant prompt book :O 

if i understand i cannot revert this to be like on the screen (it's my A1111 version), thanks for your help and lights !
and for you what is the best nvidia drivers cause the latest broke Stable diffusion, im using 532.03 :)

**Comment by vladmandic** [comment]
i'm afraid you'll just have to rearrange them in folders.
for example, create '/models/styles/negative-prompts-only' and move those 11 styles there.
and navigation using extra networks is much more flexible then using old-style pulldown combobox.

regarding drivers, old 531 still remains the best. 532 is already affected by shared vram usage, although not as much as newer ones.

**Comment by Ke031** [comment]
thanks for all this answers, you helped me a lot ! 
can you just explain me how to "move" those new styles into new json files ?
the concept is really good cause now we have more flexibility with the choise of styles, especially when we have a lot like me !

**Comment by vladmandic** [comment]
styles.csv is automatically converted so each line becomes one json file.
and then you can move them using explorer or whatever else into subfolders as long as main folder is models/styles.

**Comment by Ke031** [comment]
incredible, you are very smart, no doubt about it, i'm using vlad since the beginning of the project, and the way you making dayli update and do some great stuff with SD.Next is really great ! keep up the good work ! you are very talented ! it's just wow. :) 

i'm closing the issue then cause it's not one anymore ^^

**Comment by Ke031** [comment]
i deleted the folders styles, and put the styles csv on root, and then change the paths of the new csv folders and.....nothing appears.... ouch......big problems do i need to reinstall SDNEXT ?!

**Comment by vladmandic** [comment]
styles path needs to be set to `styles.csv`
- if it points to a valid file, its going to migrate the file.
- if it points to a folder, its just going to use that folder

**Comment by Ke031** [comment]
oh ! ok !! sorry about that, i didn't understand, thanks :) !

**Comment by Ke031** [comment]
@vladmandic hello, me again, i followed all your instructions, i made a folders insode models folder with the name "negative prompts" but when i'm starting SD and select this folder in styles (where the lora etc are stored) nothing appears... have you got an idea about that ? all the negative prompt (json files) are stored in it :/

**Comment by Mindset-Official** [comment]
> styles.csv is automatically converted so each line becomes one json file. and then you can move them using explorer or whatever else into subfolders as long as main folder is models/styles.
> 
> btw, one of main reasons why the change at all is because i want to create a full-fledged styles editor and styles should be able to have any param, not just prompt/negative-prompt.

So i was having the same issue and followed this advice, and it all works but they are still just randomly grouped together and the folders are ignored?  Or do I just need to manually edit each file name to begin to organize them?

**Comment by vladmandic** [comment]
if folders are ignored, open new issue. they are not ignored here nor on my system.
