### ISSUE TITLE
[Issue]: Error loading any SDXL Model: Error(s) in loading state_dict for LatentDiffusion: size mismatch for model.diffusion_model.input_blocks.4.1.proj_in.weight

### ISSUE THREAD

**Issue by 2zzly** [vladmandic/automatic#2181]
### Issue Description

Any SDXL model gives this error after pressing generate:
`14:16:51-800339 ERROR    Error(s) in loading state_dict for LatentDiffusion:     size mismatch for
                         model.diffusion_model.input_blocks.4.1.proj_in.weight: copying a param with shape
                         torch.Size([640, 640]) from checkpoint, the shape in current model is torch.Size([640, 640, 1,
                         1]).
14:16:52-236076 WARNING  Model not loaded`

### Version Platform Description

Python 3.10.11 on Windows
sd.next updated=2023-09-12 hash=5142b2ab
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 141 Stepping 1, GenuineIntel system=Windows
release=Windows-10-10.0.19045-SP0

### Backend

Original

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
And what does the log sat before thar? That loading SDXL using backend=original is not supposed to work. Also, please search before opening issue as this is one of the most common ones.

**Comment by 2zzly** [comment]
_I did search, the only answers were look in the wiki._
Do I need to _delete and reinstall vladmandic_?
The wiki does not say how to change backend=diffusers, or mention reinstalling to use SDXL.
[https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki](url)

**Comment by vladmandic** [comment]
> Works for 1 image with a long delay after generating the image.

long delay after generating is decoding using vae to actual pixels. and delay means you're hitting one of the most common item there is - see #1285.
