### ISSUE TITLE
[Issue]: Loading SDXL refiner and VEA throws error

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#2182]
### Issue Description

Because I tested SDXL with success on A1111, I wanted to try it with automatic. But the loading of the refiner and the VAE does not work, it throws errors in the console..

### Version Platform Description

Starting SD.Next
22:25:34-183141 INFO     Python 3.10.6 on Windows
22:25:34-242560 INFO     Version: c98a4ddb Fri Sep 8 17:53:46 2023 -0400
22:25:34-942496 INFO     Latest published version: 5142b2ab301ebc2a8f9faa5130a18ba334fe4551 2023-09-12T19:51:55Z
22:25:34-961484 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 158 Stepping 13, GenuineIntel system=Windows
                         release=Windows-10-10.0.19044-SP0 python=3.10.6
22:25:34-968510 INFO     nVidia CUDA toolkit detected

Win10, FF 114

### Relevant log output

```shell
22:53:14-051697 INFO     Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
                         context=no_grad fp16=True bf16=False
22:53:15-583935 INFO     LDM: LatentDiffusion: Running in eps-prediction mode
22:53:15-585929 INFO     LDM: DiffusionWrapper has 859.52 M params.
22:53:15-642777 ERROR    Error loading model weights: I:\Super SD
                         2.0\automatic\models\Stable-diffusion\sdxl\sdxl_v1.0_refiner_vaefix.safetensors
22:53:15-644772 ERROR    Error(s) in loading state_dict for LatentDiffusion:     size mismatch for
                         model.diffusion_model.time_embed.0.weight: copying a param with shape torch.Size([1536, 384])
                         from checkpoint, the shape in current model is torch.Size([1280, 320]).
22:53:22-223319 ERROR    Error in onchange callback: sd_vae sdxl_vae.safetensors 'LatentDiffusion' object has no
                         attribute 'sd_checkpoint_info'
```

### Backend

Original

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
Search for 1sec, this is most common issue.
Or read Wiki. 
You can't use backend=original with SDXL.

**Comment by 2zzly** [comment]
This is the procedure:
https://github.com/vladmandic/automatic/issues/2181#issuecomment-1716538693

**Comment by Woisek** [comment]
Yeah, okay ... I use A1111 now. It's way easier without any cumbersome settings search/activation/modification ... it "just works".

**Comment by Woisek** [comment]
It's more than that. SD:Next has become cumbersome itself. But never mind. I assume it's just me ...

**Comment by vladmandic** [comment]
any chance you can ping me on discord and explain in private?
