### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by FeatureIsNotABug** [vladmandic/automatic#2184]
### Issue Description

Error on startup:
│ F:\Stable Diffusion\AUTOMATIC1111\vladmandic\automatic\launch.py:213 in <module>                                     │
│                                                                                                                      │
│   212                                                                                                                │
│ ❱ 213     uv, instance = start_server(immediate=True, server=None)                                                   │
│   214     while True:                                                                                                │
│                                                                                                                      │
│ F:\Stable Diffusion\AUTOMATIC1111\vladmandic\automatic\launch.py:156 in start_server                                 │
│                                                                                                                      │
│   155         else:                                                                                                  │
│ ❱ 156             uvicorn = server.webui(restart=not immediate)                                                      │
│   157     if args.profile:                                                                                           │
│                                                                                                                      │
│ F:\Stable Diffusion\AUTOMATIC1111\vladmandic\automatic\webui.py:304 in webui                                         │
│                                                                                                                      │
│   303                                                                                                                │
│ ❱ 304     start_common()                                                                                             │
│   305     start_ui()                                                                                                 │
│                                                                                                                      │
│ F:\Stable Diffusion\AUTOMATIC1111\vladmandic\automatic\webui.py:216 in start_common                                  │
│                                                                                                                      │
│   215     async_policy()                                                                                             │
│ ❱ 216     initialize()                                                                                               │
│   217     if shared.opts.clean_temp_dir_at_start:                                                                    │
│                                                                                                                      │
│ F:\Stable Diffusion\AUTOMATIC1111\vladmandic\automatic\webui.py:121 in initialize                                    │
│                                                                                                                      │
│   120     shared.reload_hypernetworks()                                                                              │
│ ❱ 121     shared.prompt_styles.reload()                                                                              │
│   122                                                                                                                │
│                                                                                                                      │
│ F:\Stable Diffusion\AUTOMATIC1111\vladmandic\automatic\modules\styles.py:74 in reload                                │
│                                                                                                                      │
│    73                                                                                                                │
│ ❱  74         list_folder(self.path)                                                                                 │
│    75         log.debug(f'Loaded styles: folder={self.path} items={len(self.styles.keys())}')                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'StyleDatabase' object has no attribute 'path'

### Version Platform Description

Win 11

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
just fixed.
next time take 2sec to write title and description as well.
