### ISSUE TITLE
[Issue]: new forcehires fix button

### ISSUE THREAD

**Issue by zethfoxster** [vladmandic/automatic#2187]
### Issue Description

the new force hires fix no longer gives you a live preview of the portion done by the hires fix. it live previews the first pass, then sits there showing the last step of the first pass until the img is fully completed.

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by 4joeknight4** [comment]
I noticed the same thing with the preview on a forced Hires Fix. It doesn't update the image with 30 steps.  But, like you (Vlad) said, if I increase the steps to 50, the image updates start happening at about step 35 of the second pass.  Never bothered me though as my card is relatively fast. 

Commit 2513342, using Firefox and using TAESD for live preview method (switching does not fix it).

However, setting **Live preview display period**  to **0**  from 1 fixes the update steps issue for Hires fix.

**Comment by vladmandic** [comment]
@4joeknight4 yup, that's what i expected.
regarding "live preview display period", default is 1. having 0 basically means disabled.
how it works is that browser checks every "Progress update period" miliseconds current state is "Live preview display period" steps more than current preview - if it is, it requests and calculates new preview.

**Comment by zethfox** [comment]
I'll give seeing more steps for second pass once I get home from work. Just for info, I'm on latest version, using cozy nest, had the preview set to 1...just for clarity, I'm specifically talking about the preview image not the progression bar. Tried with approximate NN and teased modes both failed to update the second pass preview. Also, this just started happening with this current update that added the "force hires fix"...

**Comment by zethfoxster** [comment]
100 steps, it updated a single time at 60 steps, then not again until it completely finished. even as 2 passes i would assume it would display the preview the same wouldn't it? it does the first pass updates smooth as butter. 

DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████| 31/31 [00:01<00:00, 19.04it/s]
15:55:40-580063 DEBUG    Init hires: upscaler=4x_NMKD-UltraYandere_300k sampler=DDIM resize=0x0 upscale=1024x1632
15:55:41-817070 DEBUG    Sampler: sampler=DDIM config={'default_eta_is_0': True, 'uses_ensd': True}
Running DDIM Sampling with 99 timesteps
Decoding image:  72%|███████████████████████████████████████████████▎                  | 71/99 [00:18<00:07,  3.94it/s]15:56:00-189624 DEBUG    Server alive=True jobs=6 requests=763 uptime=200s memory used=5.02 total=127.75 job="txt2img"
                         0/2
Decoding image: 100%|██████████████████████████████████████████████████████████████████| 99/99 [00:25<00:00,  3.91it/s]
15:56:07-451542 INFO     Processed: images=1 time=28.56s its=1.05 memory={'ram': {'used': 5.03, 'total': 127.75}, 'gpu':
                         {'used': 15.19, 'total': 23.99}, 'retries': 0, 'oom': 0}

**Comment by vladmandic** [comment]
ah, found how to remove delay before hires starts showing previews. fixed.

**Comment by zethfoxster** [comment]
> ah, found how to remove delay before hires starts showing previews. fixed.

confirmed fixed and working snappier than ever :D awesome work vlad!
