### ISSUE TITLE
[Issue]: batch size 2 exhibits strange behavior, especially in xyz grids

### ISSUE THREAD

**Issue by nCoderGit** [vladmandic/automatic#2189]
### Issue Description

SD.Next currently has some weird behavior when batch size is set to 2.

Try this:
- Enter any prompt.
- Set batch size to 1, hit Generate. Output will be a single image. (Correct behavior)
- Set batch size to 2, hit Generate. Output will be 2 images (as expected). **But the 1x2 grid image is missing.**
- Set batch size to 3, hit Generate. Output will be 3 images (as expected) and the 1x3 grid is also generated correctly.
- Set batch size to 4, hit Generate. Output will be 4 images (as expected) and the 1x4 grid is also generated correctly.

---
When you enable the XYZ grid script with a batch size of 2, SD actually does generate all the images it should, but it seems to throw away the second one from the batch. Result will be only a single image per cell (not a subgrid of 2 images as expected).

### Version Platform Description

app: SD.next
updated: 2023-09-13
hash: d4871414
url: https://github.com/vladmandic/automatic/tree/master
---

04:05:59-428026 INFO     Starting SD.Next
04:05:59-450996 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6
04:05:59-460878 INFO     Skipping all checks
04:05:59-472895 INFO     Extension preload: {'extensions-builtin': 0.01, 'extensions': 0.0}
04:05:59-477883 INFO     Command line args: ['--skip-all'] skip_all=True
04:06:10-446188 INFO     Engine: backend=Backend.ORIGINAL compute=cuda mode=no_grad device=cuda
04:06:10-512023 INFO     Device: device=NVIDIA GeForce RTX 3060 Ti n=1 arch=compute_37 cap=(8, 6) cuda=11.8 cudnn=8700 driver=536.23

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
