### ISSUE TITLE
[Issue]: Image Info Tab Missing

### ISSUE THREAD

**Issue by ForceX34** [vladmandic/automatic#219]
### Issue Description

The Image Info Tab went missing after an update late Apr-16-2023. Thinking it might be a broken theme, I've tried a few themes and it has been missing from all of them. As of the current release (Apr-18-2023) the Image Info tab is still on vacation.

### Version Platform Description

AMD 5950X
NVIDIA GeForce RTX 4090 (1) (compute_37) (8, 9)
Windows 11 Pro
Brave Browser : 1.50.119
Edge Browser : 112.0.1722.48
Theme : gradio/default

Stable Diffusion:
updated: 2023-04-18
hash: 2b1b75dd
url: https://github.com/vladmandic/automatic/tree/master

cuda: 11.8
cudnn: 8700
torch: 2.0.0+cu118 autocast  half
xformers: 0.0.17
accelerate: 0.18.0
transformers: 4.26.1

Attached are two screen shots showing the tabs bar from two themes.

 Gradio/Default
![Screenshot 2023-04-18 202959](https://user-images.githubusercontent.com/33190317/232943506-d1edf8a9-4938-40a8-a753-7cf378c3f429.png)

mindrapped/Flamingo_Dark

![Screenshot 2023-04-17 195803](https://user-images.githubusercontent.com/33190317/232943605-febde9ff-5ed7-4bb5-bda0-c2aae6862c43.png)

**Comment by vladmandic** [comment]
That's correct - thanks for providing the answer. 
Also mentioned several times, so simple search would shoe that.
Closing the issue.

**Comment by ForceX34** [comment]
Thank you!
