### ISSUE TITLE
[Extension]: ControlNet (e67e017) slowing generation by 20-25x when active

### ISSUE THREAD

**Issue by raisindetre** [vladmandic/automatic#2190]
### Issue Description

I installed a fresh copy of SD.Next today (d487141) onto a Macbook Pro M2 (16GB RAM) and after running a few quick renders to confirm it was working. Loaded in a Txt2Img prompt from an image generated in base Automatic1111 v1.6.0 (3c8530cb22). The prompt uses Canny so loaded that image into ControlNet. A generation that was taking around 20s now takes 25x as long  (I stopped the processes).
<img width="1202" alt="image" src="https://github.com/vladmandic/automatic/assets/10620977/c3d1079f-60ac-4743-b6cb-55a798c50d17">

Tried the following with no change to performance:
- Disabling the Controlnet unit still results in excessively long generation times and only resolves when the server is restarted from the console.
- Disabling all user added extensions and restarting.
- Switching Device from fp32 to fp16 in settings and restarting.
-  Testing with a fresh prompt generation and different image in ControlNet
-  Rolling back from latest ControlNet commit (e67e017) to one from Sunday 9th (b15636ed) which is working fine in my base Automatic1111 install.
- Replacing ControlNet models with different [pruned ControlNet 1.1 Models](https://civitai.com/models/38784/controlnet-11-models)

For comparison, here are generation times in Automatic1111 for the same prompt (2 without ControlNet and one with).
<img width="1278" alt="image" src="https://github.com/vladmandic/automatic/assets/10620977/ff1471e9-7fca-4df6-8452-d9ace89b1209">

**Precision Compute Settings**
<img width="491" alt="image" src="https://github.com/vladmandic/automatic/assets/10620977/055dff53-bccc-4383-b1b9-7ac718cfee8a">

### Version Platform Description

18:44:07-807969 INFO     Starting SD.Next                                                                                                                                 
18:44:07-809712 INFO     Python 3.11.5 on Darwin                                                                                                                          
18:44:07-841998 INFO     Version: app=sd.next updated=2023-09-12 hash=c3cbb6a4 url=https://github.com/vladmandic/automatic.git/tree/master                                
18:44:08-474324 INFO     Latest published version: d4871414ea5cd2bbb87532cedea04b7d9e4d5b94 2023-09-13T21:26:15Z                                                          
18:44:08-487618 INFO     Platform: arch=arm64 cpu=arm system=Darwin release=22.6.0 python=3.11.5                                                                          
18:44:08-550313 INFO     Extensions: disabled=['sd-webui-agent-scheduler', 'clip-interrogator-ext', 'sd-extension-system-info',                                           
                         'multidiffusion-upscaler-for-automatic1111', 'stable-diffusion-webui-rembg', 'adetailer', 'sd-webui-regional-prompter']                          
18:44:08-551306 INFO     Extensions: enabled=['SwinIR', 'sd-webui-controlnet', 'ScuNET', 'Lora', 'stable-diffusion-webui-images-browser', 'LDSR',                         
                         'a1111-sd-webui-lycoris'] extensions-builtin                                                                                                     
18:44:08-552316 INFO     Extensions: enabled=[] extensions                                                                                                                
18:44:08-552829 INFO     Verifying requirements                                                                                                                           
18:44:08-554835 INFO     Verifying packages                                                                                                                               
18:44:08-555295 INFO     Verifying repositories                                                                                                                           
18:44:12-700212 INFO     Verifying submodules                                                                                                                             
18:44:13-573104 INFO     Extensions enabled: ['SwinIR', 'sd-webui-controlnet', 'ScuNET', 'Lora', 'stable-diffusion-webui-images-browser', 'LDSR',                         
                         'a1111-sd-webui-lycoris']                                                                                                                        
18:44:13-573864 INFO     Verifying packages                                                                                                                               
18:44:13-578699 INFO     Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}                                                                                
18:44:13-579393 INFO     Command line args: []                                                                                                                            
18:44:19-265485 INFO     Engine: backend=Backend.ORIGINAL compute=mps mode=no_grad device=mps                                                                             
18:44:19-266901 INFO     Device:                                                                                                                                          
18:44:19-635988 INFO     Available VAEs: /Users/guest/Documents/Projects/StableDiffusion/models/VAE items=1                                                            
18:44:19-638581 INFO     Available models: /Users/guest/Documents/Projects/StableDiffusion/models/Stable-diffusion items=7 time=0.00s                                  
18:44:20-542869 INFO     Extension: script='extensions-builtin/sd-webui-controlnet/scripts/controlnet.py' Warning: ControlNet failed to load SGM - will use LDM instead.  
18:44:20-543481 INFO     Extension: script='extensions-builtin/sd-webui-controlnet/scripts/controlnet.py' ControlNet preprocessor location:                               
                         /Users/guest/Documents/Projects/StableDiffusion/stable-diffusion-webui-sdnext/automatic/extensions-builtin/sd-webui-controlnet/annotator/downl
                         oads                                                                                                                                             
18:44:20-546828 INFO     Extension: script='extensions-builtin/sd-webui-controlnet/scripts/hook.py' Warning: ControlNet failed to load SGM - will use LDM instead.        
18:44:20-614755 INFO     Extensions time: 0.95s { a1111-sd-webui-lycoris=0.47s Lora=0.08s sd-webui-controlnet=0.31s }                                                     
18:44:20-990142 INFO     Loading UI theme: name=black-teal style=Auto                                                                                                     
18:44:21-134116 INFO     Themes: builtin=6 default=5 external=51                                                                                                          
18:44:21-670676 INFO     Local URL: http://127.0.0.1:7860/                                                                                                                
18:44:21-671426 INFO     Initializing middleware                                                                                                                          
Loading weights: /Users/guest/Documents/Projects/StableDiffusion/models/Stable-diffusion/cyberrealistic_v33.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/2.1 GB -:--:--
18:44:21-951632 INFO     Torch override dtype: no-half set                                                                                                                
18:44:21-952168 INFO     Torch override VAE dtype: no-half set                                                                                                            
18:44:21-952518 INFO     Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32 context=no_grad fp16=True bf16=False                          
18:44:22-619858 INFO     LDM: LatentDiffusion: Running in eps-prediction mode                                                                                             
18:44:22-620495 INFO     LDM: DiffusionWrapper has 859.52 M params.                                                                                                       
18:44:24-152056 INFO     Applying InvokeAI cross attention optimization                                                                                                   
18:44:24-163029 INFO     Loaded embeddings: loaded=0 skipped=0                                                                                                            
18:44:24-166070 INFO     Model loaded in 2.46s { load=0.21s create=0.66s apply=0.98s move=0.55s }                                                                         
18:44:24-342139 INFO     Model load finished: {'ram': {'used': 3.46, 'total': 16.0}} cached=0                                                                             
18:44:24-348496 INFO     Startup time: 10.76s { torch=4.50s gradio=0.38s diffusers=0.53s libraries=0.63s extensions=0.95s onchange=0.37s ui-txt2img=0.06s                 
                         ui-extensions=0.38s launch=0.11s checkpoint=2.64s }                                                                                              
18:45:13-328364 INFO     Themes: builtin=6 default=5 external=51  

### URL link of the extension

https://github.com/Mikubill/sd-webui-controlnet

### URL link of the issue reported in the extension repository

https://github.com/Mikubill/sd-webui-controlnet/issues/2095#issuecomment-1718833038

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
closing as issue is closed upstream
