### ISSUE TITLE
Latest commit - black image with simple params using XL

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#2193]
### Discussed in https://github.com/vladmandic/automatic/discussions/2191

<div type='discussions-op-text'>

<sup>Originally posted by **afbagwell** September 14, 2023</sup>
I upgraded this morning and tried to generate some images with SDXL. Everything returned a black image with no errors in the console. I reverted to doing something very simple and got the same thing.

**Comment by vladmandic** [comment]
seems that upgrade to `diffusers=0.21.1` breaks VAE `force_upcast` functionality

**Comment by Disty0** [comment]
DDPM Guassian hijack was causing a lot of NaN issues with IPEX before (especially on SDXL).
I had to disable it with IPEX for a while and i don't know what fixed it but it's not causing issues anymore.
And everything seems to be working fine on IPEX with Diffusers 0.21.1.

It's worth investigating this to see if it's the cause:
https://github.com/vladmandic/automatic/blob/master/modules/sd_hijack.py#L314

**Comment by vladmandic** [comment]
this is happening inside diffusers pipline, hijack doesnt execute.

**Comment by vladmandic** [comment]
fixed. added explicit upcast as needed.
