### ISSUE TITLE
[Issue]: Python 3.11

### ISSUE THREAD

**Issue by Chinico68** [vladmandic/automatic#2198]
### Issue Description

Hi, just wanted to know if Python 3.11.x is supported or not. running on Apple Studio M1 Max

### Version Platform Description

Apple studio, M1 max, Ventura 13.5.2 (22G91)

07:52:43-769001 INFO     Starting SD.Next                                       
07:52:43-771654 INFO     Python 3.10.6 on Darwin                                
07:52:43-820486 INFO     Version: app=sd.next updated=2023-09-13 hash=d4871414  
                         url=https://github.com/vladmandic/automatic/tree/master
07:52:44-385337 INFO     Latest published version:                              
                         083ab521fa6e8fa77a7494619f2d0739fd499ade               
                         2023-09-15T00:01:30Z                                   
07:52:44-391260 INFO     Platform: arch=arm64 cpu=arm system=Darwin             
                         release=22.6.0 python=3.10.6                           
07:52:44-458215 WARNING  Modified files: ['scripts/detect_extension.py',        
                         'stylesYT.csv']                                        
07:52:44-472218 INFO     Extensions: disabled=[]                  

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
sdnext is python 3.11 compatible, but some packages may not be available for it. i don't know if all packages are available for m1.
and in general, this is a question - so use discussions for that and lets use issues for actual issues.
