### ISSUE TITLE
[Feature]: Support Apple CoreML

### ISSUE THREAD

**Issue by BadIdea102** [vladmandic/automatic#220]
### Feature description

This is a lightly-edited copy of https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/5309 .

Apple added support to convert Stable Diffusion models to the CoreML format to allow for faster generation time (https://github.com/apple/ml-stable-diffusion).

- Allow the webUI to run the coreML models instead of the regular SD pytorch models.
- It would be nice to support this conversion pipeline within the web UI, perhaps as an option in an extras tab or checkpoint merger (its not really a merge per say, but it could apply?)

Proposed workflow

1. Go to the extras tab or checkpoint merger tab
1. Select a script or similar to convert a .ckpt file in your models directory to the coreML format
1. Allow use of the coreML model within the webUI for Apple users.

### Version Platform Description

Any Apple device supporting Core ML (M1 MacBooks, recent iPhones, etc)

**Comment by vladmandic** [comment]
i'd be totally for that, but i don't have M1 platform, so someone would need to contribute.

**Comment by BadIdea102** [comment]
That's probably not going to be me, I'm afraid.

But here's an infodump for any future contributors: Apple's [example code](https://github.com/apple/ml-stable-diffusion/blob/main/python_coreml_stable_diffusion/coreml_model.py) uses a library called [Core ML Tools](https://coremltools.readme.io/docs). Example code for loading and using a Core ML model is [here](https://coremltools.readme.io/docs/mlmodel).

Already-converted Core ML models can be found [here](https://huggingface.co/coreml?sort_models=likes#models). For example, [here](https://huggingface.co/coreml/coreml-stable-diffusion-v1-5/blob/main/split-einsum/v1-5_split-einsum.zip)'s SD 1.5 as a Core ML model in split-einsum flavor.

Core ML models come in two "flavors", original and split-einsum. TL;DR is original is more feature-complete (resolutions other than 512x512, for example) and runs on GPU. Split-einsum is more power-efficient (and faster on some machines), can run at all on a phone (!) and runs on the Neural Engine hardware. **For full Core ML support it would be good to support both so that users could pick the one that better fits their hardware.** Note the benchmark tables on Apple's Core ML readme. I don't know which would be easier to start with.

Separately from the original / split-einsum distinction, Apple provides both Python and Swift bindings for Core ML. Everything linked so far has been language-agnostic or Python. It seems like the Swift bindings are more efficient in places, such as not needing to recompile models on load. I haven't measured the real-world impact of this. **For now it should be fine to ignore the Swift side of things and just use Python like everything else does.**

A typical ready-to-use Core ML model on disk looks like a directory with the following files:
- `merges.txt`
- `SafetyChecker.mlmodelc`
- `TextEncoder.mlmodelc`
- `Unet.mlmodelc`
- `VAEDecoder.mlmodelc`
- `VAEEncoder.mlmodelc`
- `vocab.json`
I don't think all of these are strictly necessary, but I haven't tested this.

An `.mlmodelc` file is an archive (like .zip) containing some metadata and the actual weight in `weights/weight.bin`.

**Comment by nemilya** [comment]
It will be a great feature! Also interesting - is there someone who started up `automatic` on Mac M1/M2?

**Comment by nemilya** [comment]
And also - just note, for `Stable Diffusion with Core ML on Apple Silicon` is needed `macOS Ventura 13.1`, I (M2) now on `12 Monterey`, and `a1111` is working on `Monterey`.

**Comment by zachatkinson** [comment]
I've used Automatic on my M1 Pro Mac.  It works, but I'm sure it would be faster with an NVIDIA card.  This interests me greatly but I have no idea how to help or even what I'm doing, so I don't mind being a tester but I don't think I can help with code implementation.

**Comment by 9Somboon** [comment]
please.

**Comment by vladmandic** [comment]
i took a quick look and coreml is vastly different than torch that is used throughout the app.
yes, in theory any torch model can be converted, but none of the workflows would work anymore and it would be a massive efford.
unless apple actually provides something like torch-coreml, this is not happening.
