### ISSUE TITLE
[Issue]: "before-highres-fix" images saved twice with "Force Hires"

### ISSUE THREAD

**Issue by r7vz9h3** [vladmandic/automatic#2201]
### Issue Description

If "Force Hires" is on, the "before-highres-fix" image is saved twice, additionally to the image after hires fix. Each generation is saving three images. I think it started when hires fix was changed and "force hires" was introduced.

The issue persists when run with `--safe`.

### Version Platform Description

```
Version: app=sd.next updated=2023-09-15 hash=d833b853
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
    release=Windows-10-10.0.22621-SP0 python=3.10.11
```
No command-line options. I use Firefox. 

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by ChiaYen-Kan** [comment]
me too, i delete duplicate image by myself

**Comment by vladmandic** [comment]
fixed.
