### ISSUE TITLE
[Issue]: System paths changes does not apply

### ISSUE THREAD

**Issue by Davikar** [vladmandic/automatic#2204]
### Issue Description

Changing the system paths in settings does not seem to apply.
I change the settings, hit Apply and restart SD Next, but going back to the tab they are still at the default values.

<img width="279" alt="image" src="https://github.com/vladmandic/automatic/assets/8229634/9f9bbd2f-6aa1-4f6f-87a7-21283d01b48f">

Seems to only affect the paths shown in this image (except Lora).

### Version Platform Description

Windows 11 22H2, Python 3.10.9, Vivaldi browser (chromium)

Starting SD.Next
Python 3.10.9 on Windows
Version: app=sd.next updated=2023-09-16 hash=b13494a1
url=https://github.com/vladmandic/automatic/tree/master
Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
release=Windows-10-10.0.22621-SP0 python=3.10.9
Setting environment tuning
Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
nVidia CUDA toolkit detected
Repository update time: Sat Sep 16 13:38:55 2023
Previous setup time: Sat Sep 16 14:07:02 2023
Extensions: disabled=['stable-diffusion-webui-images-browser']
Extensions: enabled=['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-dynamic-thresholding',
'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
'stable-diffusion-webui-rembg', 'SwinIR'] extensions-builtin
Extensions: enabled=['adetailer', 'openOutpaint-webUI-extension', 'openpose-editor',
'sd-webui-aspect-ratio-helper', 'sd-webui-deoldify', 'sd-webui-infinite-image-browsing',
'sd-webui-inpaint-anything', 'sd-webui-lora-block-weight', 'sd-webui-neutral-prompt',
'sd-webui-nulienhance', 'sd-webui-regional-prompter', 'sd-webui-segment-anything',
'sd-webui-supermerger', 'sd_civitai_extension', 'Stable-Diffusion-Webui-Civitai-Helper',
'ultimate-upscale-for-automatic1111'] extensions
Latest extensions time: Sat Sep 16 14:07:27 2023

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
does this happen when you apply settings and actually restart server from cli (not from ui)?

**Comment by Davikar** [comment]
> does this happen when you apply settings and actually restart server from cli (not from ui)?

Yes, that's what I am doing.

**Comment by vladmandic** [comment]
just pushed an update, please try.

**Comment by Davikar** [comment]
It is working now. 👍
