### ISSUE TITLE
[Extension]: sd-webui-negpip is not compatible with SD.Next

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2207]
### Issue Description

The code relies on something that I guess is only available in A1111. 

It can be triggered with any prompt making use of the extension (e.g. "1man, (1girl:-1.5)") . At that point, it will try to access `SdConditioning` in `modules.prompt_parser` and it will fail.

For some reason the extension broke only recently, although the changes both in SD.Next and in the extension itself are fairly old.  

```
12:49:51-811743 ERROR    Running script process batch:                          
                         extensions/sd-webui-negpip/scripts/negpip.py:          
                         AttributeError                                         
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /notebooks/automatic/modules/scripts.py:467 in process_batch                 │
│                                                                              │
│   466 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_ │
│ ❱ 467 │   │   │   │   script.process_batch(p, *args, **kwargs)               │
│   468 │   │   │   except Exception as e:                                     │
│                                                                              │
│ /notebooks/automatic/extensions/sd-webui-negpip/scripts/negpip.py:149 in     │
│ process_batch                                                                │
│                                                                              │
│   148 │   │                                                                  │
│ ❱ 149 │   │   self.conds_all = calcconds(nip)                                │
│   150 │   │   self.unconds_all = calcconds(pin)                              │
│                                                                              │
│ /notebooks/automatic/extensions/sd-webui-negpip/scripts/negpip.py:141 in     │
│ calcconds                                                                    │
│                                                                              │
│   140 │   │   │   │   │   │   if targets:                                    │
│ ❱ 141 │   │   │   │   │   │   │   conds, contokens = conddealer(targets)     │
│   142 │   │   │   │   │   │   │   regionconds.append([region, conds, contoke │
│                                                                              │
│ /notebooks/automatic/extensions/sd-webui-negpip/scripts/negpip.py:114 in     │
│ conddealer                                                                   │
│                                                                              │
│   113 │   │   │   for target in targets:                                     │
│ ❱ 114 │   │   │   │   input = prompt_parser.SdConditioning([f"({target[0]}:{ │
│   115 │   │   │   │   cond = prompt_parser.get_learned_conditioning(shared.s │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: module 'modules.prompt_parser' has no attribute 'SdConditioning'
```

### Version Platform Description

Paperspace, Ubuntu 20.04, Python 3.9, GPU is a NVIDIA A4000.

### URL link of the extension

https://github.com/hako-mikan/sd-webui-negpip

### URL link of the issue reported in the extension repository

https://github.com/hako-mikan/sd-webui-negpip/issues/7

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by zethfoxster** [comment]
i think that extension is trying to solve a problem that doesnt actually exist. this could be just my own opinion
![tmpf5apy1za](https://github.com/vladmandic/automatic/assets/5951657/95719dce-99df-49c8-ad03-1b6d59952ba6)
![tmpfno_qlj8](https://github.com/vladmandic/automatic/assets/5951657/1a54783d-0f79-4a0a-9464-9b2854f8aa63)
but both of his examples I was able to get by adding the word into the negatives prompt.

it would be nice to have all extensions working, but that "full parser" mode in the settings on sdnext seems to already do this stuff correctly.

**Comment by lbeltrame** [comment]
The problem does exist in certain models (anime particularly) where there's a massive deal of overfitting (especially since they merges of merges of merges of merges).
I can do the same stuff without negpip, but with some models it's really hard without.

**Comment by vladmandic** [comment]
i took a quick look and it looks like a lot of work to support this extension - and i'm not sure if extension does only what it says as it actually creates negative segments in prompt when its triggered, it doesn't just set negative weight on specific term. as such, extension modifies prompt conditioning quite heavily - for better or worse - but its really far more than what would appear from the surface.

**Comment by lbeltrame** [comment]
The author claims to have at least addressed the problem. I'll leave this open until I can test it.

**Comment by lbeltrame** [comment]
It seems to be working. Closing.
