### ISSUE TITLE
[Issue]: "before-highres-fix" filenames don't include "[batch_number]" tag

### ISSUE THREAD

**Issue by r7vz9h3** [vladmandic/automatic#2209]
### Current behavior
I set my `samples_filename_pattern` to `[job_timestamp]_[batch_number]`. With highres fix on and `save_images_add_number == True`, when generating twice with batch size 2, the resulting filenames are:
```
00000-20230917181702-before-highres-fix.jpg
00001-20230917181702-before-highres-fix.jpg
00002-20230917181702_1.jpg
00003-20230917181702_2.jpg
00004-20230917181723-before-highres-fix.jpg
00005-20230917181723-before-highres-fix.jpg
00006-20230917181723_1.jpg
00007-20230917181723_2.jpg
```
(If I disabled `save_images_add_number`, the last `before-highres-fix` file would overwrite all previous ones from that batch.)

### Expected behavior
Instead, I would expect these names, where `before-highres-fix` files also have their batch numbers:
```
00000-20230917181702_1-before-highres-fix.jpg
00001-20230917181702_2-before-highres-fix.jpg
00002-20230917181702_1.jpg
00003-20230917181702_2.jpg
00004-20230917181723_1-before-highres-fix.jpg
00005-20230917181723_2-before-highres-fix.jpg
00006-20230917181723_1.jpg
00007-20230917181723_2.jpg
```

### Motivation
My personal motivation is, when I sort the files alphabetically I want to have upscaled images right next to originals, so I can compare them while scrolling through all images in the outputs folder. With that change, I could disable `save_images_add_number` to achieve my goal, sorted alphabetically:
```
20230917181702_1-before-highres-fix.jpg
20230917181702_1.jpg
20230917181702_2-before-highres-fix.jpg
20230917181702_2.jpg
20230917181723_1-before-highres-fix.jpg
20230917181723_1.jpg
20230917181723_2-before-highres-fix.jpg
20230917181723_2.jpg
```

### Version Platform Description

```
18:09:34-690232 INFO     Version: app=sd.next updated=2023-09-17 hash=f4492f4c
                         url=https://github.com/vladmandic/automatic/tree/master
18:09:35-622633 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.22621-SP0 python=3.10.11
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.

**Comment by r7vz9h3** [comment]
Would it be more consistent if the first image also got `batch_number` "1" added to the filename? Right now with `[job_timestamp]-[batch_number]` it looks rather messy.

On Linux, zsh `ls -1` a batch of 4 is sorted: 2,3,4,1:
```
20230918003445-2-before-hires.jpg
20230918003445-2.jpg
20230918003445-3-before-hires.jpg
20230918003445-3.jpg
20230918003445-4-before-hires.jpg
20230918003445-4.jpg
20230918003445-before-hires.jpg
20230918003445.jpg
20230918003541-2-before-hires.jpg
20230918003541-2.jpg
20230918003541-3-before-hires.jpg
20230918003541-3.jpg
20230918003541-4-before-hires.jpg
20230918003541-4.jpg
20230918003541-before-hires.jpg
20230918003541.jpg
```

In Windows File Explorer the sorting is more unfortunate:
```
20230918003445.jpg
20230918003445-2-before-hires.jpg
20230918003445-2.jpg
20230918003445-3-before-hires.jpg
20230918003445-3.jpg
20230918003445-4-before-hires.jpg
20230918003445-4.jpg
20230918003445-before-hires.jpg
20230918003541.jpg
20230918003541-2-before-hires.jpg
20230918003541-2.jpg
20230918003541-3-before-hires.jpg
20230918003541-3.jpg
20230918003541-4-before-hires.jpg
20230918003541-4.jpg
20230918003541-before-hires.jpg
```

In these cases, I think it would be clearer if 1st file in every batch had the `-1` in its name.

**Comment by vladmandic** [comment]
It would, but it would require a lot more logic to be introduced as save is atomic process and it doesn't know if there are more coming.

**Comment by r7vz9h3** [comment]
This is probably too niche to add, but I personally would love an option to just assume "1" by default, no matter if there are more coming or not. So with batch 1 all files would get a `-1` and that's OK, so I could have my `-1` in bigger batches too.

Or, make it two tags. `[batch_number]` could work as it does now and `[batch_number_1]` would give 1 by default, even for batch size 1.
