### ISSUE TITLE
[Issue]: Cannot expand ControlNet dialog in img2img tab 

### ISSUE THREAD

**Issue by Ancanus** [vladmandic/automatic#2212]
### Issue Description

As soon as I click on `ControlNet v1.1.410`, that entire session slows down to a crawl and it's impossible to accomplish anything until restarted. I am as confused as you are. Nothing shows in console.

Observe my exact repro steps:
1. Copy any random image from the internet into your clipboard. I provide you one in case you don't have: 
![image](https://github.com/vladmandic/automatic/assets/487030/007d0729-83df-4a95-961a-5a726c0a9b76)
2. Click `From Image`
3. Click `Inpaint`
4. Press CTRL+V in your keyboard to release the image unto the canvas.
5. Click on `ControlNet v1.1.410` and hopefully you repro with me. 
6. Then the day the it eventually opens, try to change any setting in it.
7. Then the day those settings change, try to generate image. You cannot.

### Version Platform Description

[startup.log](https://github.com/vladmandic/automatic/files/12643653/startup.log)

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i've reproduced it
1. thanks for the sample image! :)
2. issue seems to be that opening clicking on ANY controlnet control triggers  
  a full browser relayout recursively, that on my system takes about 7sec, so its pretty massive.
3. this happens on inpaint when selecting any controlnet control - can be accordion itself or model selector later
4. it only happens on inpaint, normal img2img is ok which makes no sense
5. relayout seems to be triggered for rearranging models into grid. no idea why, but i've removed that style setting for now.
