### ISSUE TITLE
[Issue]: Extra Networks tab can no longer be ordered. 

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#2215]
### Issue Description

In previous versions, the Extra Network panel could have their tabs ordered and hidden. No longer possible in 792893e6.

Also, there's no way to change the folder selector size.
![image](https://github.com/vladmandic/automatic/assets/1969381/c5bea427-a62d-4d52-98d3-1534485ca9f5)

### Version Platform Description

```
19:33:54-312830 INFO     Starting SD.Next
19:33:54-325002 INFO     Python 3.10.11 on Windows
19:33:54-494589 INFO     Version: app=sd.next updated=2023-09-17 hash=792893e6 url=https://github.com/vladmandic/automatic/tree/master
19:33:55-118260 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 158 Stepping 11, GenuineIntel system=Windows release=Windows-10-10.0.19045-SP0
                         python=3.10.11
19:33:55-125262 INFO     Using DirectML Backend
```

Win10/Chrome 116/AMD 6600XT 8GB

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
reimplemented: ui -> system -> settings -> extra networks, very first setting
you can show/hide or set order in a same setting.

**Comment by brknsoul** [comment]
What about
> Also, there's no way to change the folder selector size.

Or do you want me to add a new issue for that?

**Comment by vladmandic** [comment]
if you're in wide-screen scenario, its set by default to 20% of visible area. i'll reduce to 15% but i really don't want to add more and more settings in ui.
you can adjust it in your user.css.

```css
.extra-network-subdirs { min-width: max(15%, 120px); }
```

**Comment by brknsoul** [comment]
Maybe set it to the lower of 20% or a few pixels past the longest name?
Or not. lol.

**Comment by vladmandic** [comment]
i don't think css syntax would allow for that - if you find it, let me know.
