### ISSUE TITLE
[Issue]: Is it just me or Img2img text files do not contain ANY useful info about the img2img parameters used?

### ISSUE THREAD

**Issue by StableInfo** [vladmandic/automatic#2216]
### Issue Description

I just checked one of my img2img text files to try to reproduce the parameterqs (mainly to check the deoinse used) and I notice the  text file is like:
(positive prompt)
Negative prompt: (negative prompt)
Steps, seed, samplerf, cfg, size, parser, model, model hash, img cfg, backedn, version comment, OPERATIONS (ultimate sd upscale)

- There is no info about the denoise (object of this issue).
- Optional issue: When I press the button to import the values, it never works with the different extensins (controlnet, and ultimate sd upscale).

### Version Platform Description

1d04014d

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
try some newer version. i just run img2img and heres a sample metadata:

> Prompt: cutie
Steps: 20 | Seed: 489641143 | Sampler: UniPC | CFG scale: 6 | Size: 512x512 | Parser: Full parser | Model: sd15_lyriel-v16 | Model hash: ec6f68ea63 | Backend: Original | Version: 792893e | Operations: img2img | Init image size: 785x786 | Init image hash: 0c265246 | Resize mode: 1 | Denoising strength: 0.75
