### ISSUE TITLE
[Feature]: Portable version Automatic - One-click installation for Windows

### ISSUE THREAD

**Issue by 0-NiK-0** [vladmandic/automatic#222]
### Feature description

For AUTOMATIC1111, there is a one-click installation for Windows
Portable Stable Diffusion - https://github.com/serpotapov/stable-diffusion-portable
Please do the same for Stable Diffusion - Automatic

**Comment by vladmandic** [comment]
i'm all for it, but portable is created by different author and not part of A1111 repo, this request should go to him.
