### ISSUE TITLE
[Issue]: Minimum denoising strength set at 0.05

### ISSUE THREAD

**Issue by dan4ik94** [vladmandic/automatic#2225]
### Issue Description

The denoising strength in the **From Image** tab can't go lower than 0.05. Is this a feature or a bug, I can't seem to find in the setting an option responsible for this?

Thank you. GIF attached.
![chrome_XWpdr4RvUo](https://github.com/vladmandic/automatic/assets/84623377/b07f3639-d135-4c14-ae88-1a56cda581cf)

### Version Platform Description

Python 3.10.10 on Windows
Version: app=sd.next updated=2023-09-19 hash=f82e05c5
url=https://github.com/vladmandic/automatic/tree/master
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 58 Stepping 9, GenuineIntel system=Windows
release=Windows-10-10.0.19045-SP0 python=3.10.10

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed
