### ISSUE TITLE
[Feature]: Aspect Ratio with Presets - Show / Hide

### ISSUE THREAD

**Issue by brunogcar** [vladmandic/automatic#2227]
### Feature description

A feature i think was  always missing from  SD is presets to Aspect Ratios, it is a quality of live feature that helps a lot

Auto always refused to include, saying it should be extensions, specially because it would add more features to UI and some PRs were refused

but i personally think it should be a core feature, as its present in apps like PS or any other image app or StableSwarmUI and InvokeAI in different forms

as we can hide/show it to not pollute default UI, my idea would be adding an icon below the swap button (as vlad suggested on other post) to expand and collapse, something like

 ![Presets](https://github.com/vladmandic/automatic/assets/53648/435e627e-44c9-41d5-a74c-f21d3545e509)

and have on System > Settings > User interface

![config](https://github.com/vladmandic/automatic/assets/53648/f39318ec-4d39-4334-afff-a00fb883434f)

---------------
for reference:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/7601
- discussion about AR

extensions:
https://github.com/LEv145/--sd-webui-ar-plus 
- simpler, but  config in on file instead of settings, with just the basics, Ratios and Presets 

https://github.com/thomasasfk/sd-webui-aspect-ratio-helper
- way more complex than whats actually needed,  but has an interesting approach with the dropdown preset 

### Version Platform Description

Python 3.10.6 on Windows
Version: app=sd.next updated=2023-09-19 hash=d73f5f6f
Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD 
system=Windows release=Windows-10-10.0.22621-SP0 python=3.10.6
nVidia CUDA toolkit detected

**Comment by Aptronymist** [comment]
Well this has my full support, I and many others consider these extensions essential, unless you want to keep a calculator open just to figure out ARs, and we'll assume nobody likes that, this is still the best way.

**Comment by vladmandic** [comment]
yeah, i get it. but after seeing a pretty good job that `sd-webui-aspect-ratio-helper` does, not sure if there is a point of building something partial?

**Comment by Woisek** [comment]
The existing AR extension works perfect and there is no need to integrate it directly. Maybe Vlad consider to include it as a 'internal extension' for new setups, but to integrate it fully makes no sense.
Also, AR are set up once and then maybe once in a while on a special occasion.

**Comment by vladmandic** [comment]
closing the request as it would just duplicate what extension already does.
