### ISSUE TITLE
[Issue]: API docs not available?

### ISSUE THREAD

**Issue by APISeeker** [vladmandic/automatic#2229]
### Issue Description

Hello I was experimenting with API with both A1111 main and A1111 vlad fork, (from here: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/API) and I discovered that:

The docs page: http://127.0.0.1:7860/docs
Does not work with Vlad fork.
Can we fix the docs? I would love to explore the API more.

### Version Platform Description

app: SD.next
updated: 2023-09-02
hash: 1d04014d

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by APISeeker** [comment]
Hello @vladmandic  I just edited the whole post. I am talking specifically about the API docs, not the normal docs, this is how it looks:
![image](https://github.com/vladmandic/automatic/assets/145594487/3c73e5da-9ef9-4567-b041-9b34dc2901d1)

**Comment by vladmandic** [comment]
> Hello @vladmandic I just edited the whole post. I am talking specifically about the API docs, not the normal docs, this is how it looks: ![image](https://user-images.githubusercontent.com/145594487/269364007-3c73e5da-9ef9-4567-b041-9b34dc2901d1.png)

yes, that's what i'm talking about
