### ISSUE TITLE
[Issue]: Shifted Icons in Extra Networks

### ISSUE THREAD

**Issue by AsaTyr2018** [vladmandic/automatic#2236]
### Issue Description

The Icons in the Extra Network Tab are shifted. The hitboxes are still at the same position but the icons shifted in place.
![grafik](https://github.com/vladmandic/automatic/assets/43162495/ca09d5a0-d3f5-4c69-8df0-8b0821ff72de)
![grafik](https://github.com/vladmandic/automatic/assets/43162495/ef693623-4284-4c8e-87eb-513145ccc257)

Theme Used: black-teal But also applied to other Themes.

I also tested it with disabled extensions and a freshly installed version.

### Version Platform Description

app: automatic.git
updated: 2023-09-20
hash: 89ba8e3c
(just Updated directly from Git)

Computer:
device: NVIDIA GeForce RTX 3090 (1) (compute_37) (8, 6)
arch: AMD64
cpu: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.6

Browser: Tested with Chrome (116.0.5845.188) and Firefox (117.0.1)
Both browsers with and without extensions.

### Relevant log output

```shell
No relevant Log Output.
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i'm planning to replace icon row with a single button that opens en details very soon, so this issue is no-op as such.

**Comment by vladmandic** [comment]
fixed in dev branch.
