### ISSUE TITLE
[Feature]: An option to disable NSFW filter

### ISSUE THREAD

**Issue by saekiamae** [vladmandic/automatic#2242]
### Feature description

Hello, I was trying to find the way to remove the NSFW filter but I failed so far. The original AUTOMATIC1111's Stable Diffusion Web UI never had this problem. Which file I should modify? 

Thank you in advance for help! <3

### Version Platform Description

Windows 11

**Comment by vladmandic** [comment]
its already disabled, its always been that way.

**Comment by saekiamae** [comment]
Then why some of the images I generate render as black?

**Comment by vladmandic** [comment]
Many possible issues, most common is math precision issue with VAE leading to overflows.
Search for past issues.
