### ISSUE TITLE
[Issue]: Importing generation parameters sets VAE as override even when it is the current one

### ISSUE THREAD

**Issue by acorderob** [vladmandic/automatic#2245]
### Issue Description

As the title says, when i click the read generation parameters button, the VAE is set as override, even when it is the one already selected.

Initial data:
![image](https://github.com/vladmandic/automatic/assets/6293935/7d5da97a-16da-475c-92a5-947c45bffe83)
Prompt:
![image](https://github.com/vladmandic/automatic/assets/6293935/f92ddc5b-6286-44a4-8701-ad96b7dde03b)
Clicking 
![image](https://github.com/vladmandic/automatic/assets/6293935/366c19cd-b2eb-4153-b865-3393cf390f05)
produces:
![image](https://github.com/vladmandic/automatic/assets/6293935/fadc5a5c-b67c-444e-a823-0cab218c476e)

The VAE file is in a subfolder. Maybe there lies the problem?

### Version Platform Description

version: b13494a1

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
> The VAE file is in a subfolder. Maybe there lies the problem?

most likely, yes. 
is the issue mostly cosmetic or is there an actual problem?

**Comment by acorderob** [comment]
Not a real problem, just annoying.

**Comment by vladmandic** [comment]
different file format is different vae. its stored differently, so it has different hash. i don't want to analyze internals of vae to compare every key if it matches.

**Comment by vladmandic** [comment]
fix in dev, will be merged to master soon
