### ISSUE TITLE
[Issue]: sd_lora UI quicksetting doesn't show drop down list

### ISSUE THREAD

**Issue by findpaths** [vladmandic/automatic#2251]
### Issue Description

I used sd_lora in UI quicksettings to see a list of my lora's but it hasn't shown up for a while, so I'm not sure when it was broken. sd_model_checkpoint, sd_vae and sd_lyco all show up correctly - in the image below sd_lora should be between vae and lycoris only the reload is showing up (and does nothing)

<img width="800" alt="image" src="https://github.com/vladmandic/automatic/assets/143102415/e62366c2-9975-4db8-abd2-c1c0d6c1ce77">

### Version Platform Description

Latest - I always git pull changes as part of starting the UI

09:34:35-473005 INFO     Starting SD.Next
09:34:35-477048 INFO     Python 3.10.6 on Windows
09:34:35-668773 INFO     Version: app=sd.next updated=2023-09-20 hash=89ba8e3c
                         url=https://github.com/vladmandic/automatic/tree/master
09:34:36-209993 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 158 Stepping 13, GenuineIntel system=Windows
                         release=Windows-10-10.0.22621-SP0 python=3.10.6
09:34:36-213969 INFO     nVidia CUDA toolkit detected
09:34:36-555760 INFO     Extensions: disabled=[]
09:34:36-557759 INFO     Extensions: enabled=['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR'] extensions-builtin
09:34:36-578974 INFO     Extensions: enabled=['deforum-for-automatic1111-webui', 'DWPose', 'ebsynth_utility',
                         'openOutpaint-webUI-extension', 'prompt_gallery_name.json', 'sd-dynamic-prompts',
                         'sd-extension-aesthetic-scorer', 'SD-WebUI-BatchCheckpointPrompt', 'sd-webui-openpose-editor',
                         'sd-webui-prompt-history', 'stable-diffusion-webui-aesthetic-image-scorer',
                         'stable-diffusion-webui-artists-to-study', 'Stable-Diffusion-Webui-Civitai-Helper',
                         'stable-diffusion-webui-state', 'stable-diffusion-webui-tokenizer', 'ultimate-upscale-for-automatic1111']
                         extensions

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
`sd_lora` option is a very very obsolete way of loading loras. lora should be specified in prompt, using <lora:name:strength> syntax.

and to see list of loras, use extra network. there is absolutely no use of `sd_lora` opt
