### ISSUE TITLE
[Issue]: Save button bugged in Agent Scheduler

### ISSUE THREAD

**Issue by afbagwell** [vladmandic/automatic#2265]
Found another save button problem. This time its the save button inside the viewer instance provided by the Agent Scheduler. I ran several batches overnight, ran through them this morning with the viewer, hit the save button for the ones I wanted to keep, then deleted all the generations from their initial folder.

Just a few minutes ago I verified that none of the images saved this way actual get copied. No "Copying image: ..." output in the console. I lost about 60 images this way.

If you use the image viewer from the "From Text" tab it works fine though.

_Originally posted by @afbagwell in https://github.com/vladmandic/automatic/issues/2223#issuecomment-1740022829_

**Comment by vladmandic** [comment]
that may be so, but that is an extension, built-in or not. please refile and report upstream.
