### ISSUE TITLE
[Issue]: ROCm Linux using CPU only

### ISSUE THREAD

**Issue by iskamag** [vladmandic/automatic#2268]
### Issue Description

I've been trying to get back into Stable Diffusion after months, and last night the generation was extremely slow. I've now realized it's only using the CPU
`15:43:12-647227 INFO     Engine: backend=Backend.ORIGINAL compute=cpu mode=no_grad device=cpu        `
despite detecting my GPU just fine
`15:42:35-558875 DEBUG    ROCm agent used by default: idx=4 gpu=gfx1030 arch=navi2x                   `
(I've even confirmed this in the python REPL)
```
>>> modules.devices.get_optimal_device_name()
'cuda'
```

It also currently works fine on automatic1111

### Version Platform Description

Host OS: debian sid (trixie), linux 6.5.0
RAM: 32GB
GPU: GIGABYTE AMD Radeon RX6800 (navi21), 16GB VRAM
Docker image: rocm/pytorch:latest
Python: 3.9.18, also used 3.11.4
Torch: 2.2.0.dev20230928+rocm5.6 Autocast  half (also had torch 2.1, 2.0.1 and 2.2 with nohalf give the same results)
It also defaulted to the cuda version at first, but I've fixed that.

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
your notes may be true, but no way to see anything without actual log - that's why there is section for that in issue.

**Comment by BalakayA** [comment]
Same issue here
CPU: AMD 5800x
GPU: AMD 6750xt
Running up to date Arch Linux

Tried master and dev branches, both only use the CPU.
[sdnext.log](https://github.com/vladmandic/automatic/files/12775752/sdnext.log)

**Comment by vladmandic** [comment]
@BalakayA in your case, detection of rocm failed - please provide output of `hipconfig --version`
and then it failed when checking for the most basic python package: `setuptools` which doesn't make much sense, but i'd rather check the first part first.

**Comment by BalakayA** [comment]
I'm not able to run hipconfig, no command found.

I installed rocm with:
pacman -S rocm-hip-sdk rocm-opencl-sdk

Maybe its a Arch issue?
I could try Debian 12 later today to test.

**Comment by vladmandic** [comment]
`hipversion` is a utility provided by amd hip libraries.
and its used by sdnext to determine version of hip and install appropriate version of torch rocm.
without it, it will fallback to ancient torch-rocm-5.4.2

you can force specific torch package manually using env variable before running webui, for example:
`export TORCH_COMMAND="torchvision --pre --index-url https://download.pytorch.org/whl/nightly/rocm5.6"`

note that if torch is already installed, sdnext will just use it, it will not force reinstall unless `--reinstall` flag is present.

**Comment by vladmandic** [comment]
@iskamag you've not provided logs since issue was created two weeks ago so closing due to idle. issue can be reopened if new information is provided.
