### ISSUE TITLE
[Feature]: FreeU support

### ISSUE THREAD

**Issue by demoran23** [vladmandic/automatic#2269]
### Feature description

https://github.com/ChenyangSi/FreeU

**Comment by vladmandic** [comment]
its in progress already.

**Comment by brknsoul** [comment]
Isn't it already support via extension?
Manually install this via the Extension > Manual install tab
`https://github.com/ljleb/sd-webui-freeu`

**Comment by vladmandic** [comment]
for backend=original, yes, you can use the exension and i don't plan to integrate directly into core as extension does a good job already.

integration into diffusers is in progress.

**Comment by drax-xard** [comment]
For reference: [PR in diffusers](https://github.com/huggingface/diffusers/pull/5164)

**Comment by drax-xard** [comment]
Already merged in diffusers.

**Comment by vladmandic** [comment]
if i said its in progress that means i'm monitoring and/or working on it, not sure what are last two updates supposed to do?

**Comment by drax-xard** [comment]
Just being informative for people that may be curious about it and the work being done. :-)

**Comment by vladmandic** [comment]
anyhow its done in dev branch, but requires unpublished diffusers. as soon as diffusers 0.22 are released, its going to be available.
