### ISSUE TITLE
[Issue]: Gradio links close without notice significantly less than 72-hours

### ISSUE THREAD

**Issue by MysticDaedra** [vladmandic/automatic#2270]
### Issue Description

I've already submitted a bug report to Gradio, but in case this is somehow not related directly to them, I thought I'd post here as well. Obviously feel free to close if unrelated. 

I started SD.next with --share this morning before heading to work, while also connecting my VPN (ExpressVPN). I was able to use my instance for several hours at work with no issues, but something happened and I lost connection to my PC. Upon refreshing, Gradio gave me the message "No interface is running". I had someone at my house restart SD.next and give me the new URL, which worked again for about 2 hours, before once again failing to connect. 

In the console there are no errors at all related to Gradio, let alone anything from the time period that the url stopped working.

### Version Platform Description

SD.Next hash ccae1ef0
Python 3.10.6
Windows 10 64-bit releast 10-10.0.19045-SP0
Firefox

### Relevant log output

```shell
Starting SD.Next
15:22:21-113163 INFO     Python 3.10.6 on Windows
15:22:21-450239 INFO     Version: app=sd.next updated=2023-09-28 hash=ccae1ef0
                         url=https://github.com/vladmandic/automatic/tree/master
15:22:21-961355 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6
15:22:21-967356 INFO     nVidia CUDA toolkit detected
15:22:22-211412 WARNING  Modified files: ['scripts/detect_extension.py', 'scripts/prompt_gallery.py']
15:22:22-212412 INFO     Verifying requirements
15:22:22-229416 INFO     Verifying packages
15:22:22-231416 INFO     Verifying repositories
15:22:27-092518 INFO     Verifying submodules
15:23:03-238712 ERROR    Error updating extension: extensions\prompt_gallery_name.json
15:23:23-172230 INFO     Extensions enabled: ['clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR', 'adetailer', 'canvas-zoom', 'OneButtonPrompt',
                         'PromptGallery-stable-diffusion-webui', 'prompt_gallery_name.json', 'sd-civitai-browser-plus',
                         'sd-dynamic-prompts', 'sd-dynamic-thresholding', 'sd-fast-pnginfo',
                         'sd-webui-infinite-image-browsing', 'sd-webui-prompt-history', 'sd_civitai_extension',
                         'Stable-Diffusion-Webui-Civitai-Helper', 'stable-diffusion-webui-depthmap-script',
                         'stable-diffusion-webui-GPU-temperature-protection', 'stable-diffusion-webui-wildcards',
                         'ultimate-upscale-for-automatic1111']
```

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this really seems to be a gradio internal thing, nothing i can do.
if you've reported it to gradio already, please include tracking info in the issue itself.
i'm ok to leave this issue open so we can track upstream issue, but otherwise its a no-op.

**Comment by vladmandic** [comment]
can you update the issue with reference to gradio issue created?

**Comment by MysticDaedra** [comment]
> can you update the issue with reference to gradio issue created?

https://github.com/gradio-app/gradio/pull/5731

Seems they fixed on their end a couple of weeks ago, just needs to be updated for Sd.Next.

**Comment by vladmandic** [comment]
unfortunately, newer version of gradio will have to wait a bit longer - anything above 3.43 has issues, i've found 1 in 3.44, 2 in 3.45 and 1 more in 3.47. its all being looked at, but this means that i cannot update gradio just yet.

anyhow, since this is resolved upstream, i'll close the issue here.
