### ISSUE TITLE
[Extension]: Controlnet error?

### ISSUE THREAD

**Issue by mildfever** [vladmandic/automatic#2271]
### Issue Description

Keep getting this on start.

Extension: script='extensions-builtin\sd-webui-controlnet\scripts\controlnet.py' Warning: ControlNet failed to load SGM - will use LDM instead.

Controlnet seems to work, but why doesn't it load the SGM

### Version Platform Description

version: 01c46663
Firefox 118.0.1
Win 10
RTX 3060

### URL link of the extension

https://github.com/Mikubill/sd-webui-controlnet

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
do you have an issue? no. then please ask a question in discord or discussions first.
and search first since i've spoken in details about sgm in the past. sdnext does not use sgm, so this is perfectly normal.
