### ISSUE TITLE
[Extension]: Tag Autocomplete popup hidden in some textareas after Gradio update (CSS issue)

### ISSUE THREAD

**Issue by DominikDoom** [vladmandic/automatic#2282]
### Issue Description

After the recent Gradio update, the tag autocomplete popup is hidden in some cases, since recent versions for whatever reason set an explicit `overflow: hidden` inline style on gradio-textbox elements.

The normal prompts are not affected by this since you explicitly set `display: content` on them, however tag autocomplete also supports some third party textareas (such as Image Browser keyword search) where this fix doesn't apply.

A1111 had this issue too in the past but was fixed in dev, see this issue: https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/issues/213
And the related PR: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/12310

The same fix would also work here if you are comfortable with it. As far as I know, this doesn't break any Gradio styling.
Another option would be to apply the `display: content` fix to all textareas instead of just the prompts.

If you don't feel comfortable with either, it is technically possible to fix on my side, however this would result in a large amount of CSS baggage since the selectors need to be very specific to override inline styles without breaking other stuff by accident.

### Version Platform Description

app: SD.next
updated: 2023-10-01
hash: c6226605

### URL link of the extension

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete

### URL link of the issue reported in the extension repository

https://github.com/DominikDoom/a1111-sd-webui-tagcomplete/issues/244

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i'm ok with that, i've just added it to dev branch.

**Comment by DominikDoom** [comment]
@Woisek This was already merged long ago in the 2023-10-17 update, so any issue you see now would be either a regression or different bug. After checking, it does still work for me in the current SD.Next version.
