### ISSUE TITLE
[Issue]: Can't hide tabs anymore

### ISSUE THREAD

**Issue by akvyalkov** [vladmandic/automatic#2288]
### Issue Description

About month ago I was able to hide tabs. Now there is no such settings.
UI Config is empty and Settings tab has no more such parameters.
I've copied old config.json, but it didn't worked.

```
{
  "sd_model_checkpoint": "deliberate_v2.safetensors [9aba26abdf]",
  "sd_checkpoint_hash": "9aba26abdfcd46073e0a1d42027a3a3bcc969f562d58a03637bf0a0ded6586c9",
  "gradio_theme": "gradio/base",
  "theme_style": "Light",
  "hidden_tabs": [
    "System Info",
    "Interrogator",
    "Models",
    "Train",
    "Extensions",
    "Settings",
    "Image Browser",
    "Agent Scheduler"
  ],
  "sd_model_refiner": "deliberate_v2.safetensors [9aba26abdf]",
  "show_samplers": [
    "Default",
    "DEIS",
    "DPM 1S",
    "DPM 2M",
    "DPM++ 2M SDE Karras",
    "DPM2 Karras",
    "DPM++ 2M Karras"
  ],
  "queue_paused": true,
  "samples_format": "png",
  "grid_format": "png",
  "clip_skip": 1,
  "uni_pc_lower_order_final": true,
  "uni_pc_order": 2,
  "styles_dir": "models\\styles",
  "outdir_txt2img_samples": "outputs\\text",
  "outdir_img2img_samples": "outputs\\image",
  "outdir_extras_samples": "outputs\\extras",
  "outdir_txt2img_grids": "outputs\\grids",
  "outdir_img2img_grids": "outputs\\grids",
  "outdir_save": "outputs\\save",
  "image_browser_active_tabs": "txt2img, img2img"
}
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
hiding tabs is disabled as it had some bad side-effects. what is the use-case?

**Comment by akvyalkov** [comment]
Disable unnecessary tabs to simplify UI for less advanced users. Like leave only "From text" and "From image" tabs.

**Comment by vladmandic** [comment]
default number of tabs is not high.
and this is not a very simple product regardless how you look at it.
even then, models includes download functionality useful for even less advanced users and process contains basic upscale.
interrogate is optional, you can and don't have to use it. same for agent scheduler.
only thing worth hiding would be train. 

```log
From Text
From Image
Process Image
Train
Models
Interrogator
Agent Scheduler
Image Browser
System
Extensions
```

i would need a much stronger use case to bring this feature back.

**Comment by Manniala** [comment]
Well came here to see if there was a way to disable them, well there was not. so i just use a css, with stylish.

The "color" tag is if you want to color the menu, if not than just remove it or ignore it, the display: none that tells it to hide a menu point.
Depending on what position the menu point is you want to hide, you may have to change the last number (4), you can hide more menu points, but to make it simple, just make another copy of the code, and replace the number at the end.

`/* Svelte kqij2n */
.main .tab-nav:nth-child(1) .svelte-kqij2n:nth-child(4){
	color:#dc1818 !important;
	display: none !important;
}`

**Comment by vladmandic** [comment]
closing the issue as its not really an issue. if this feature is highly desired, please create a feature request and document a good use case for it. i don't mind bringing it back, but like i said, it needs to have a strong use case.
