### ISSUE TITLE
[Feature]: Add Wildcard support to the new style system in EN

### ISSUE THREAD

**Issue by iDeNoh** [vladmandic/automatic#2291]
### Feature description

I noticed that the new style system built into extended networks gives us an opportunity to implement a native wildcard system. The workflow would require that we can reference styles in the prompt, I suggest having a <<style:>> option like we do for Lora/embeds, that way a user can set a folder structure of files and then reference them, the system can then pull from that folder randomly. As an example a user could do <<style:artists>> or <<style:artists/abstract>> and as long as the styles exists it would work. This also opens the possibility of users referencing styles in prompt without having to select them from extended networks like this <<style:ambiance/horror/zombie_apocalypse>>

**Comment by Woisek** [comment]
If you use wildcards in the first place, you can do this all by yourself, in any way you want/need it.
Just create your wildcards with the styles you would like to have as prompt and use it as intended.
No need for something complicated.

**Comment by iDeNoh** [comment]
I get that, but that's an extension, those break. And I can't create new wildcards without manually creating the files on my PC, I *can* create now styles on my phone without needing to mess with my pc.

**Comment by Woisek** [comment]
>I get that, but that's an extension, those break. 

Every extensions could break, do you now want every extension 'build inside'? And that prevents nothing to be not broken.  So far, the Wildcards extension is well maintained and it exists pretty long by now. 

> And I can't create new wildcards without manually creating the files on my PC, 

You can create the wildcards pretty much anywhere and then copy them. 

> I can create now styles on my phone without needing to mess with my pc.

Wildcards are simple txt files. Your phone can't handle txt files ... ?

**Comment by iDeNoh** [comment]
Please tell me how I can create wildcards and add them to the current implementation without being on the PC or remote connecting to it? I'd love to know. I don't understand why this is even an issue for you because more features aren't a *bad* thing. 

I don't enjoy using the current form of wildcards, it is cumbersome and outdated, I would like to see a better version of it.

**Comment by Woisek** [comment]
Dude, create a text file with your whatever content and then copy&paste it into the wildcards extensions folder. Where is the problem? Do you really need a text editor inside the UI?

> I don't enjoy using the current form of wildcards, it is cumbersome and outdated, I would like to see a better version of it.

Feel free to suggest a workflow. I personally don't know what could be better/simpler then using __wildcard__ but you've probably already thought about that, right?

**Comment by Aptronymist** [comment]
> Every extensions could break, do you now want every extension 'build inside'? And that prevents nothing to be not broken.

Extensions break all the time, especially with SD.Next, because it seems like most extension authors don't even care if they work with us or not. If it's built in, we know it won't break unexpectedly, and we can build in whatever features we want, which we will be doing. Don't like it? Don't use it.

**Comment by vladmandic** [comment]
guys, what's the point of this argument? there's a feature request which is valid. question is how much should it be prioritized or not, nothing else.

**Comment by vladmandic** [comment]
from changelog in dev branch:
    - styles can also be used in a prompt directly: `<style:style_name>`  
      if style if an exact match, it will be used  
      otherwise it will rotate between styles that match the start of the name  
      that way you can use different styles as wildcards when processing batches

**Comment by Woisek** [comment]
> I legit just said that I _don't_ want to have to create the file on my PC and add it to the file system

How do you then want to use wildcard files, which consist of TXT files ... ?
Do you even understand how this extension actually works?

**Comment by iDeNoh** [comment]
> > I legit just said that I _don't_ want to have to create the file on my PC and add it to the file system
> 
> How do you then want to use wildcard files, which consist of TXT files that are on your file system ... ? Do you even understand how this extension actually works?

You don't understand what I'm saying, vlads right, drop it. If you *really* want to argue about this pm me on discord.
