### ISSUE TITLE
[Feature]: Allow use of ControlNet while using diffusers backend

### ISSUE THREAD

**Issue by Manchovies** [vladmandic/automatic#2300]
### Feature description

Hello, 

Not sure if this is an issue specific to me and my setup, but when I run webui.bat with backend diffusers, everything works fine except that the controlnet extension gets disabled automatically. I can use ControlNet using stock A1111 and diffusers, and I can use SDNext with ControlNet with the original backend. I did notice that switching between the two backends also disabled CN in original backend, but I fixed that with a simple modification to the config json. 

Let me know if you need any more info or if there's anything I can try to get this working!
Thanks

### Version Platform Description

Windows 11, RTX 2070 Super, 3600x CPU, most recent commit on the main branch

**Comment by vladmandic** [comment]
there are open issues for this and its already tracked, closing as duplicate.

**Comment by Manchovies** [comment]
Oh, my apologies. I searched for it but couldn't find it. Thanks for working on this!
