### ISSUE TITLE
[Extension]: Deforum with ControlNet

### ISSUE THREAD

**Issue by amesemyta1** [vladmandic/automatic#2301]
### Issue Description

Hi, I'm trying to use DeForum with ControlNet and I'm getting this error. Although all Extensions are disabled

16:04:11-356853 WARNING  No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: [].                                                                                                                                       
16:04:11-361942 WARNING  No ControlNetUnit detected in args. It is very likely that you are having an extension conflict.Here are args received by ControlNet: []. 

![image](https://github.com/vladmandic/automatic/assets/32303139/dd6ab61d-76e6-45c0-8fdb-f1e1971d3d44)

### Version Platform Description

RunPod Pytorch 2.0.1
1 x A100 80GB
16 vCPU 125 GB RAM
runpod/pytorch:2.0.1-py3.10-cuda11.8.0-devel

### URL link of the extension

https://github.com/Mikubill/sd-webui-controlnet

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by amesemyta1** [comment]
My Extensions
![image](https://github.com/vladmandic/automatic/assets/32303139/62ecd3c3-f8af-42ff-b738-fe2c98cfdbca)

**Comment by vladmandic** [comment]
closing as all related issues were closed upstream. if issue still exits, it should be freshly documented and reported upstream.
