### ISSUE TITLE
[Extension]: ADETAILER (Person Detection Module) 

### ISSUE THREAD

**Issue by EKKIV0K** [vladmandic/automatic#2309]
### Issue Description

Hi @vladmandic i hope you are fine !
there is a big problem coming from Adetailer in the detection person modules, 
i'm sorry the log is long but i cannot see the problem here, It says that Vladmandic SDNEXT version is too old ?!
But my version is the updated one, adetailer is updated too. 

### Version Platform Description

04:24:54-402573 ERROR    Running script postprocess image: extensions\adetailer\scripts\!adetailer.py: ValueError
┌─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────┐
│ C:\SDNEXT\modules\scripts.py:536 in postprocess_image                                                            │
│                                                                                                                  │
│   535 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                   │
│ > 536 │   │   │   │   script.postprocess_image(p, pp, *args)                                                     │
│   537 │   │   │   except Exception as e:                                                                         │
│                                                                                                                  │
│ C:\SDNEXT\extensions\adetailer\adetailer\traceback.py:159 in wrapper                                             │
│                                                                                                                  │
│   158 │   │   │   │   error = RuntimeError(output)                                                               │
│ > 159 │   │   │   raise error from None                                                                          │
│   160                                                                                                            │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError:
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                 System info                                                  │
│ ┌─────────────┬────────────────────────────────────────────────────────────────────────────────────────────┐ │
│ │             │ Value                                                                                      │ │
│ ├─────────────┼────────────────────────────────────────────────────────────────────────────────────────────┤ │
│ │    Platform │ Windows-10-10.0.19044-SP0                                                                  │ │
│ │      Python │ 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]           │ │
│ │     Version │ Unknown (too old or vladmandic)                                                            │ │
│ │      Commit │ Unknown                                                                                    │ │
│ │ Commandline │ ['launch.py']                                                                              │ │
│ │   Libraries │ {'torch': '2.0.1+cu118', 'torchvision': '0.15.2+cu118', 'ultralytics': '8.0.198',          │ │
│ │             │ 'mediapipe': '0.10.5'}                                                                     │ │
│ └─────────────┴────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                            Inputs                                                                            │
│ ┌─────────────────┬────────────────────────────────────────┐                                                 │
│ │                 │ Value                                  │                                                 │
│ ├─────────────────┼────────────────────────────────────────┤                                                 │
│ │          prompt │                                        │                                                 │
│ │ negative_prompt │                                        │                                                 │
│ │          n_iter │ 1                                      │                                                 │
│ │      batch_size │ 1                                      │                                                 │
│ │           width │ 563                                    │                                                 │
│ │          height │ 844                                    │                                                 │
│ │    sampler_name │ DPM++ SDE Karras                       │                                                 │
│ │       enable_hr │ None                                   │                                                 │
│ │     hr_upscaler │                                        │                                                 │
│ │      checkpoint │ realisticVisionV51_v51VAE.safetensors  │                                                 │
│ │             vae │ Automatic                              │                                                 │
│ │            unet │ ------                                 │                                                 │
│ └─────────────────┴────────────────────────────────────────┘                                                 │
│                                                  ADetailer                                                   │
│ ┌─────────────────────┬────────────────────────────────────────────────────────────────────────────────────┐ │
│ │                     │ Value                                                                              │ │
│ ├─────────────────────┼────────────────────────────────────────────────────────────────────────────────────┤ │
│ │             version │ 23.10.0                                                                            │ │
│ │            ad_model │ person_yolov8n-seg.pt                                                              │ │
│ │           ad_prompt │ MrPIXL  <lora:MrPIXL_5500_RV13:1.0> sitting on a ledge wearing a black leather     │ │
│ │                     │ jacket and black boots with a white t - shirt and black jeans and a black leather  │ │
│ │                     │ jacket, (a stock photo:0.166)                                                      │ │
│ │  ad_negative_prompt │ disfigured, kitsch, ugly, oversaturated, grain, low-res, Deformed, blurry, bad     │ │
│ │                     │ anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly,       │ │
│ │                     │ poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed    │ │
│ │                     │ hands, blur, out of focus, long neck, long body, ugly, disgusting, poorly drawn,   │ │
│ │                     │ mutilated, mangled, old, surreal, out of frame, ((((mutated hands and fingers)))), │ │
│ │                     │ deformed eyes, ((bad art)), extra fingers, cloned face, body out of frame, gross   │ │
│ │                     │ proportions, canvas frame, cartoon, 3d, weird colors,  badhandsv5-neg, badhandv4   │ │
│ │ ad_controlnet_model │ None                                                                               │ │
│ │              is_api │ False                                                                              │ │
│ └─────────────────────┴────────────────────────────────────────────────────────────────────────────────────┘ │
│ ┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐         │
│ │ C:\SDNEXT\extensions\adetailer\adetailer\traceback.py:139 in wrapper                             │         │
│ │                                                                                                  │         │
│ │   136 │   │   width = width - 4 if width > 4 else None                                           │         │
│ │   137 │   │   console = Console(file=string, width=width)                                        │         │
│ │   138 │   │   try:                                                                               │         │
│ │ > 139 │   │   │   return func(*args, **kwargs)                                                   │         │
│ │   140 │   │   except Exception as e:                                                             │         │
│ │   141 │   │   │   tables = [                                                                     │         │
│ │   142 │   │   │   │   get_table(title, data)                                                     │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\extensions\adetailer\scripts\!adetailer.py:703 in postprocess_image                    │         │
│ │                                                                                                  │         │
│ │   700 │   │   │   for n, args in enumerate(arg_list):                                            │         │
│ │   701 │   │   │   │   if args.ad_model == "None":                                                │         │
│ │   702 │   │   │   │   │   continue                                                               │         │
│ │ > 703 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)            │         │
│ │   704 │   │                                                                                      │         │
│ │   705 │   │   if is_processed and not getattr(p, "_ad_skip_img2img", False):                     │         │
│ │   706 │   │   │   self.save_image(                                                               │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\extensions\adetailer\scripts\!adetailer.py:666 in _postprocess_image_inner             │         │
│ │                                                                                                  │         │
│ │   663 │   │   │   p2.subseed = subseed + j                                                       │         │
│ │   664 │   │   │                                                                                  │         │
│ │   665 │   │   │   try:                                                                           │         │
│ │ > 666 │   │   │   │   processed = process_images(p2)                                             │         │
│ │   667 │   │   │   except NansException as e:                                                     │         │
│ │   668 │   │   │   │   msg = f"[-] ADetailer: 'NansException' occurred with {ordinal(n + 1)} se   │         │
│ │   669 │   │   │   │   print(msg, file=sys.stderr)                                                │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\modules\processing.py:626 in process_images                                            │         │
│ │                                                                                                  │         │
│ │    623 │   │   │   res = process_images_inner(p)                                                 │         │
│ │    624 │   │   │   print_profile(pr, 'Torch')                                                    │         │
│ │    625 │   │   else:                                                                             │         │
│ │ >  626 │   │   │   res = process_images_inner(p)                                                 │         │
│ │    627 │   finally:                                                                              │         │
│ │    628 │   │   if not shared.opts.cuda_compile:                                                  │         │
│ │    629 │   │   │   modules.sd_models.apply_token_merging(p.sd_model, 0)                          │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\modules\processing.py:717 in process_images_inner                                      │         │
│ │                                                                                                  │         │
│ │    714 │   with devices.inference_context(), ema_scope_context():                                │         │
│ │    715 │   │   t0 = time.time()                                                                  │         │
│ │    716 │   │   with devices.autocast():                                                          │         │
│ │ >  717 │   │   │   p.init(p.all_prompts, p.all_seeds, p.all_subseeds)                            │         │
│ │    718 │   │   │   if shared.opts.live_previews_enable and shared.opts.show_progress_type == "A  │         │
│ │    719 │   │   │   │   modules.sd_vae_approx.model()                                             │         │
│ │    720 │   │   if shared.state.job_count == -1:                                                  │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\modules\processing.py:1128 in init                                                     │         │
│ │                                                                                                  │         │
│ │   1125 │   │   │   │   crop_region = modules.masking.expand_crop_region(crop_region, self.width  │         │
│ │   1126 │   │   │   │   x1, y1, x2, y2 = crop_region                                              │         │
│ │   1127 │   │   │   │   mask = mask.crop(crop_region)                                             │         │
│ │ > 1128 │   │   │   │   image_mask = images.resize_image(3, mask, self.width, self.height)        │         │
│ │   1129 │   │   │   │   self.paste_to = (x1, y1, x2-x1, y2-y1)                                    │         │
│ │   1130 │   │   │   else:                                                                         │         │
│ │   1131 │   │   │   │   image_mask = images.resize_image(self.resize_mode, image_mask, self.widt  │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\modules\images.py:262 in resize_image                                                  │         │
│ │                                                                                                  │         │
│ │   259 │   │   │   res.paste(resized.resize((width, fill_height), box=(0, resized.height, width   │         │
│ │   260 │   │   elif ratio > src_ratio:                                                            │         │
│ │   261 │   │   │   fill_width = width // 2 - src_w // 2                                           │         │
│ │ > 262 │   │   │   res.paste(resized.resize((fill_width, height), box=(0, 0, 0, height)), box=(   │         │
│ │   263 │   │   │   res.paste(resized.resize((fill_width, height), box=(resized.width, 0, resize   │         │
│ │   264 │   if output_type == 'np':                                                                │         │
│ │   265 │   │   return np.array(res)                                                               │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\venv\lib\site-packages\PIL\Image.py:2193 in resize                                     │         │
│ │                                                                                                  │         │
│ │   2190 │   │   │   │   │   (box[3] - reduce_box[1]) / factor_y,                                  │         │
│ │   2191 │   │   │   │   )                                                                         │         │
│ │   2192 │   │                                                                                     │         │
│ │ > 2193 │   │   return self._new(self.im.resize(size, resample, box))                             │         │
│ │   2194 │                                                                                         │         │
│ │   2195 │   def reduce(self, factor, box=None):                                                   │         │
│ │   2196 │   │   """                                                                               │         │
│ └──────────────────────────────────────────────────────────────────────────────────────────────────┘         │
│ ValueError: height and width must be > 0                                                                     │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

04:24:55-228576 INFO     Processed: images=1 time=10.54s its=4.75 memory={'ram': {'used': 4.02, 'total': 31.85},
                         'gpu': {'used': 3.46, 'total': 8.0}, 'retries': 0, 'oom': 0}
100%|█████████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.98it/s]
04:25:46-627306 INFO
04:25:46-655305 INFO     0: 640x448 1 face, 9.0ms
04:25:46-657307 INFO     Speed: 2.0ms preprocess, 9.0ms inference, 2.0ms postprocess per image at shape (1, 3, 640,
                         448)
Loading weights: H:\SD1.5 MODELS\lora\MrPIXL_5500_RV13.safetensors ----------------------------- 0.0/37.9 MB -:--:--
100%|███████████████████████████████████████████████████████████████████████████████| 21/21 [00:09<00:00,  2.14it/s]
04:25:57-749383 INFO     Processed: images=1 time=11.09s its=4.51 memory={'ram': {'used': 4.12, 'total': 31.85},
                         'gpu': {'used': 5.19, 'total': 8.0}, 'retries': 0, 'oom': 0}
04:25:58-402357 INFO     Processed: images=1 time=14.37s its=3.48 memory={'ram': {'used': 4.09, 'total': 31.85},
                         'gpu': {'used': 5.19, 'total': 8.0}, 'retries': 0, 'oom': 0}
100%|█████████████████████████████████████████████████████████████████████████████████| 6/6 [00:02<00:00,  2.60it/s]
04:26:25-293427 INFO
04:26:28-718488 INFO     0: 640x448 1 person, 1657.1ms
04:26:28-720515 INFO     Speed: 1.0ms preprocess, 1657.1ms inference, 2.0ms postprocess per image at shape (1, 3,
                         640, 448)
04:26:29-334517 ERROR    Running script postprocess image: extensions\adetailer\scripts\!adetailer.py: ValueError
┌─────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────┐
│ C:\SDNEXT\modules\scripts.py:536 in postprocess_image                                                            │
│                                                                                                                  │
│   535 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                   │
│ > 536 │   │   │   │   script.postprocess_image(p, pp, *args)                                                     │
│   537 │   │   │   except Exception as e:                                                                         │
│                                                                                                                  │
│ C:\SDNEXT\extensions\adetailer\adetailer\traceback.py:159 in wrapper                                             │
│                                                                                                                  │
│   158 │   │   │   │   error = RuntimeError(output)                                                               │
│ > 159 │   │   │   raise error from None                                                                          │
│   160                                                                                                            │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError:
┌──────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                 System info                                                  │
│ ┌─────────────┬────────────────────────────────────────────────────────────────────────────────────────────┐ │
│ │             │ Value                                                                                      │ │
│ ├─────────────┼────────────────────────────────────────────────────────────────────────────────────────────┤ │
│ │    Platform │ Windows-10-10.0.19044-SP0                                                                  │ │
│ │      Python │ 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]           │ │
│ │     Version │ Unknown (too old or vladmandic)                                                            │ │
│ │      Commit │ Unknown                                                                                    │ │
│ │ Commandline │ ['launch.py']                                                                              │ │
│ │   Libraries │ {'torch': '2.0.1+cu118', 'torchvision': '0.15.2+cu118', 'ultralytics': '8.0.198',          │ │
│ │             │ 'mediapipe': '0.10.5'}                                                                     │ │
│ └─────────────┴────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                            Inputs                                                                            │
│ ┌─────────────────┬────────────────────────────────────────┐                                                 │
│ │                 │ Value                                  │                                                 │
│ ├─────────────────┼────────────────────────────────────────┤                                                 │
│ │          prompt │                                        │                                                 │
│ │ negative_prompt │                                        │                                                 │
│ │          n_iter │ 1                                      │                                                 │
│ │      batch_size │ 1                                      │                                                 │
│ │           width │ 563                                    │                                                 │
│ │          height │ 844                                    │                                                 │
│ │    sampler_name │ DPM++ SDE Karras                       │                                                 │
│ │       enable_hr │ None                                   │                                                 │
│ │     hr_upscaler │                                        │                                                 │
│ │      checkpoint │ realisticVisionV51_v51VAE.safetensors  │                                                 │
│ │             vae │ Automatic                              │                                                 │
│ │            unet │ ------                                 │                                                 │
│ └─────────────────┴────────────────────────────────────────┘                                                 │
│                                                  ADetailer                                                   │
│ ┌─────────────────────┬────────────────────────────────────────────────────────────────────────────────────┐ │
│ │                     │ Value                                                                              │ │
│ ├─────────────────────┼────────────────────────────────────────────────────────────────────────────────────┤ │
│ │             version │ 23.10.0                                                                            │ │
│ │            ad_model │ person_yolov8s-seg.pt                                                              │ │
│ │           ad_prompt │ MrPIXL  <lora:MrPIXL_5500_RV13:1.0> sitting on a ledge wearing a black leather     │ │
│ │                     │ jacket and black boots with a white t - shirt and black jeans and a black leather  │ │
│ │                     │ jacket, (a stock photo:0.166)                                                      │ │
│ │  ad_negative_prompt │ disfigured, kitsch, ugly, oversaturated, grain, low-res, Deformed, blurry, bad     │ │
│ │                     │ anatomy, disfigured, poorly drawn face, mutation, mutated, extra limb, ugly,       │ │
│ │                     │ poorly drawn hands, missing limb, floating limbs, disconnected limbs, malformed    │ │
│ │                     │ hands, blur, out of focus, long neck, long body, ugly, disgusting, poorly drawn,   │ │
│ │                     │ mutilated, mangled, old, surreal, out of frame, ((((mutated hands and fingers)))), │ │
│ │                     │ deformed eyes, ((bad art)), extra fingers, cloned face, body out of frame, gross   │ │
│ │                     │ proportions, canvas frame, cartoon, 3d, weird colors,  badhandsv5-neg, badhandv4   │ │
│ │ ad_controlnet_model │ None                                                                               │ │
│ │              is_api │ False                                                                              │ │
│ └─────────────────────┴────────────────────────────────────────────────────────────────────────────────────┘ │
│ ┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐         │
│ │ C:\SDNEXT\extensions\adetailer\adetailer\traceback.py:139 in wrapper                             │         │
│ │                                                                                                  │         │
│ │   136 │   │   width = width - 4 if width > 4 else None                                           │         │
│ │   137 │   │   console = Console(file=string, width=width)                                        │         │
│ │   138 │   │   try:                                                                               │         │
│ │ > 139 │   │   │   return func(*args, **kwargs)                                                   │         │
│ │   140 │   │   except Exception as e:                                                             │         │
│ │   141 │   │   │   tables = [                                                                     │         │
│ │   142 │   │   │   │   get_table(title, data)                                                     │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\extensions\adetailer\scripts\!adetailer.py:703 in postprocess_image                    │         │
│ │                                                                                                  │         │
│ │   700 │   │   │   for n, args in enumerate(arg_list):                                            │         │
│ │   701 │   │   │   │   if args.ad_model == "None":                                                │         │
│ │   702 │   │   │   │   │   continue                                                               │         │
│ │ > 703 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)            │         │
│ │   704 │   │                                                                                      │         │
│ │   705 │   │   if is_processed and not getattr(p, "_ad_skip_img2img", False):                     │         │
│ │   706 │   │   │   self.save_image(                                                               │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\extensions\adetailer\scripts\!adetailer.py:666 in _postprocess_image_inner             │         │
│ │                                                                                                  │         │
│ │   663 │   │   │   p2.subseed = subseed + j                                                       │         │
│ │   664 │   │   │                                                                                  │         │
│ │   665 │   │   │   try:                                                                           │         │
│ │ > 666 │   │   │   │   processed = process_images(p2)                                             │         │
│ │   667 │   │   │   except NansException as e:                                                     │         │
│ │   668 │   │   │   │   msg = f"[-] ADetailer: 'NansException' occurred with {ordinal(n + 1)} se   │         │
│ │   669 │   │   │   │   print(msg, file=sys.stderr)                                                │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\modules\processing.py:626 in process_images                                            │         │
│ │                                                                                                  │         │
│ │    623 │   │   │   res = process_images_inner(p)                                                 │         │
│ │    624 │   │   │   print_profile(pr, 'Torch')                                                    │         │
│ │    625 │   │   else:                                                                             │         │
│ │ >  626 │   │   │   res = process_images_inner(p)                                                 │         │
│ │    627 │   finally:                                                                              │         │
│ │    628 │   │   if not shared.opts.cuda_compile:                                                  │         │
│ │    629 │   │   │   modules.sd_models.apply_token_merging(p.sd_model, 0)                          │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\modules\processing.py:717 in process_images_inner                                      │         │
│ │                                                                                                  │         │
│ │    714 │   with devices.inference_context(), ema_scope_context():                                │         │
│ │    715 │   │   t0 = time.time()                                                                  │         │
│ │    716 │   │   with devices.autocast():                                                          │         │
│ │ >  717 │   │   │   p.init(p.all_prompts, p.all_seeds, p.all_subseeds)                            │         │
│ │    718 │   │   │   if shared.opts.live_previews_enable and shared.opts.show_progress_type == "A  │         │
│ │    719 │   │   │   │   modules.sd_vae_approx.model()                                             │         │
│ │    720 │   │   if shared.state.job_count == -1:                                                  │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\modules\processing.py:1128 in init                                                     │         │
│ │                                                                                                  │         │
│ │   1125 │   │   │   │   crop_region = modules.masking.expand_crop_region(crop_region, self.width  │         │
│ │   1126 │   │   │   │   x1, y1, x2, y2 = crop_region                                              │         │
│ │   1127 │   │   │   │   mask = mask.crop(crop_region)                                             │         │
│ │ > 1128 │   │   │   │   image_mask = images.resize_image(3, mask, self.width, self.height)        │         │
│ │   1129 │   │   │   │   self.paste_to = (x1, y1, x2-x1, y2-y1)                                    │         │
│ │   1130 │   │   │   else:                                                                         │         │
│ │   1131 │   │   │   │   image_mask = images.resize_image(self.resize_mode, image_mask, self.widt  │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\modules\images.py:262 in resize_image                                                  │         │
│ │                                                                                                  │         │
│ │   259 │   │   │   res.paste(resized.resize((width, fill_height), box=(0, resized.height, width   │         │
│ │   260 │   │   elif ratio > src_ratio:                                                            │         │
│ │   261 │   │   │   fill_width = width // 2 - src_w // 2                                           │         │
│ │ > 262 │   │   │   res.paste(resized.resize((fill_width, height), box=(0, 0, 0, height)), box=(   │         │
│ │   263 │   │   │   res.paste(resized.resize((fill_width, height), box=(resized.width, 0, resize   │         │
│ │   264 │   if output_type == 'np':                                                                │         │
│ │   265 │   │   return np.array(res)                                                               │         │
│ │                                                                                                  │         │
│ │ C:\SDNEXT\venv\lib\site-packages\PIL\Image.py:2193 in resize                                     │         │
│ │                                                                                                  │         │
│ │   2190 │   │   │   │   │   (box[3] - reduce_box[1]) / factor_y,                                  │         │
│ │   2191 │   │   │   │   )                                                                         │         │
│ │   2192 │   │                                                                                     │         │
│ │ > 2193 │   │   return self._new(self.im.resize(size, resample, box))                             │         │
│ │   2194 │                                                                                         │         │
│ │   2195 │   def reduce(self, factor, box=None):                                                   │         │
│ │   2196 │   │   """                                                                               │         │
│ └──────────────────────────────────────────────────────────────────────────────────────────────────┘         │
│ ValueError: height and width must be > 0                                                                     │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

04:26:30-164493 INFO     Processed: images=1 time=7.85s its=6.37 memory={'ram': {'used': 4.1, 'total': 31.85},
                         'gpu': {'used': 3.66, 'total': 8.0}, 'retries': 0, 'oom': 0}

### URL link of the extension

https://github.com/Bing-su/adetailer

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by brknsoul** [comment]
As this is an extension, you'll need to submit an issue report at the extension's github too.

**Comment by vladmandic** [comment]
re: too old. message may be weird in choice of words, but its correct.
> Version │ Unknown (too old or vladmandic)

sdnext does not use same pipeline as a1111 and adetailer detects that. that's perfectly fine.

actual error is that adetailer detected a region and then asked sdnext to resize it for further processing - well, that detected region had invalid width/height. adetailer should check if all detected regions are actually valid before attempting to process them, not process them without validation.

this should be reported upstream.

**Comment by EKKIV0K** [comment]
@vladmandic there is no way to get rip of it ? cause switching between Next and a1111 is annoying, honestly :)

**Comment by vladmandic** [comment]
switch back/forth why? adetailer works with sdnext in backend original mode.

**Comment by EKKIV0K** [comment]
i am already in backend original, and this happens only when i use the "person detection module" :)

**Comment by vladmandic** [comment]
Is this happening for every image?
And same image and workflow work in A1111?

**Comment by vladmandic** [comment]
OK, now I have something to look at. You did not provide any of that information originally, so there really isn't much I could do even if I tried.

**Comment by EKKIV0K** [comment]
but yeah you right i didn't mentioned about a1111 ^^

**Comment by vladmandic** [comment]
this is working with current versions of sdnext and adetailer.
