### ISSUE TITLE
[Feature]: Extra Networks: "Sort By"

### ISSUE THREAD

**Issue by xedis** [vladmandic/automatic#2310]
### Feature description

Sort by: 
Date: CreatedOn,ModifiedOn; Name; Size?; Metadata length?; Image/No Image?; Description?; Activation Text? 

Should be possible both ASC and DESC. 

Quite a few possibilities exist. Not all of those listed above are desired, just was running thru what information there was.

Primarily Date so one can easily see newly downloaded/added entries.

![image](https://github.com/vladmandic/automatic/assets/4144634/67f9d558-2849-4cf6-96f0-64d167a1c4cd)

**Comment by vladmandic** [comment]
done in dev branch.
