### ISSUE TITLE
[Issue]:  the new update is terrible

### ISSUE THREAD

**Issue by tembel123456** [vladmandic/automatic#2317]
### Issue Description

the new update is terrible.. half of what worked doesn't work, the design is also terrible, why dig into what works? or ask us at startup if we want an update?  the previous version was TOP, that's new one is shit
  back to automatic1111

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
Ask at startup? Update is neither forced nor automatic. It's a user action by definition.

And what is broken? Be specific.

**Comment by tembel123456** [comment]
sorry , if i am be a rude...  for example, i am reinstall you SDnext from
scratch, but i canot install again faceswaplab, extension...

trying like 5 times... and model is placed on
C:\SD_Next\automatic\models\faceswaplab like before


Downloading inswapper model: 529MB [00:27, 20.4MB/s]
23:31:41-462011 ERROR    Module load:
extensions\sd-webui-faceswaplab\scripts\faceswaplab.py: FileNotFoundError
┌──────────────────────────────────────────────────── Traceback (most
recent call last) ─────────────────────────────────────────────────────┐
│
C:\SD_Next\automatic\extensions\sd-webui-faceswaplab\scripts\faceswaplab_utils\models_utils.py:78
in get_current_swap_model                │
│
                                                                 │
│   77 │   │   │   logger.error("The model %s cannot be found or loaded",
model)                                                             │
│ > 78 │   │   │   raise FileNotFoundError(
                                                                 │
│   79 │   │   │   │   "No faceswap model found. Please add it to the
faceswaplab directory. En                                              │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
FileNotFoundError: No faceswap model found. Please add it to the
faceswaplab directory. Ensure the model is in the proper directory
(<sdwebui>/models/faceswaplab/inswapper_128.onnx)

During handling of the above exception, another exception occurred:

┌──────────────────────────────────────────────────── Traceback (most
recent call last) ─────────────────────────────────────────────────────┐
│ C:\SD_Next\automatic\modules\script_loading.py:21 in load_module
                                                                  │
│
                                                                 │
│   20 │   │   │   with contextlib.redirect_stdout(io.StringIO()) as
stdout:                                                                 │
│ > 21 │   │   │   │   module_spec.loader.exec_module(module)
                                                                 │
│   22 │   │   │   setup_logging() # reset since scripts can hijaack
logging                                                                 │
│ in exec_module:883
                                                                  │
│ in _call_with_frames_removed:241
                                                                  │
│
                                                                 │
│
C:\SD_Next\automatic\extensions\sd-webui-faceswaplab\scripts\faceswaplab.py:4
in <module>                                                  │
│
                                                                 │
│     3
                                                                 │
│ >   4 check_configuration()
                                                                 │
│     5
                                                                 │
│
                                                                 │
│
C:\SD_Next\automatic\extensions\sd-webui-faceswaplab\scripts\configure.py:55
in check_configuration                                        │
│
                                                                 │
│   54 │   │   download(model_url, model_path)
                                                                  │
│ > 55 │   │   check_model()
                                                                  │
│   56
                                                                  │
│
                                                                 │
│
C:\SD_Next\automatic\extensions\sd-webui-faceswaplab\scripts\faceswaplab_utils\models_utils.py:33
in check_model                           │
│
                                                                 │
│   32 def check_model() -> bool:
                                                                 │
│ > 33 │   model_path = get_current_swap_model()
                                                                  │
│   34 │   if not is_sha1_matching(
                                                                 │
│
                                                                 │
│
C:\SD_Next\automatic\extensions\sd-webui-faceswaplab\scripts\faceswaplab_utils\models_utils.py:82
in get_current_swap_model                │
│
                                                                 │
│   81 │   except:
                                                                  │
│ > 82 │   │   raise FileNotFoundError(
                                                                 │
│   83 │   │   │   "No faceswap model found. Please add it to the
faceswaplab directory. Ensure                                              │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
FileNotFoundError: No faceswap model found. Please add it to the
faceswaplab directory. Ensure the model is in the proper directory
(<sdwebui>/models/faceswaplab/inswapper_128.onnx)
23:31:41-536688 INFO     Extensions time: 28.18s { Lora=0.15s
sd-webui-agent-scheduler=0.09s sd-webui-controlnet=0.18s
                         stable-diffusion-webui-images-browser=0.07s
sd-webui-faceswaplab=27.54s }
23:31:41-636711 INFO     Loading UI theme: name=black-teal style=Auto
23:31:43-395121 INFO     Local URL: http://127.0.0.1:7860/
23:31:43-397584 INFO     Initializing middleware
23:31:43-502306 INFO     [AgentScheduler] Task queue is empty
23:31:43-504601 INFO     [AgentScheduler] Registering APIs
23:31:43-620675 INFO     Startup time: 262.43s { samplers=232.17s
extensions=28.18s onchange=0.10s ui-extra-networks=0.05s ui-txt2img=0.06s
                         ui-img2img=0.10s ui-settings=0.10s
ui-extensions=1.08s ui-defaults=0.07s launch=0.24s app-started=0.21s }
23:31:45-521467 INFO     MOTD:
23:31:49-287398 INFO     Browser session: client=127.0.0.1
agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
like
                         Gecko) Chrome/118.0.0.0 Safari/537.36

**Comment by vladmandic** [comment]
Since youve created an issue for that extension, we can continue there.

**Comment by tembel123456** [comment]
I apologize once again... it just happened in the middle of the work in
progress and the plugin is important to me

**Comment by vladmandic** [comment]
Upgrade never happens on its own, it's always user initiated.

But ok. I'll take a look at extension issue tomorrow.

**Comment by tembel123456** [comment]
thanx... have good day
