### ISSUE TITLE
[Issue]: Save Current Prompt as Style Template Missing?

### ISSUE THREAD

**Issue by thestorytree** [vladmandic/automatic#2318]
### Issue Description

How do i save the current prompt as a new or overwrite a style now?

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
It's right there in extra networks, styles, top right icons.

If unsure, better to ask question before creating an issue.
