### ISSUE TITLE
[Issue]: Themes Design Question

### ISSUE THREAD

**Issue by xGeekpower** [vladmandic/automatic#2321]
### Issue Description

I notice the new update deleted my fav theme (bethecloud/storj_theme) so I tried the new one (STiGMaTaCH/stig_storj) but then the font and the whole ui size changed and Im not sure if this is by design or if I miss something on the settings because this style of formatting applies to every single theme I pick except the top ones that are designed to be compact, I also tried to enable compact mode and restart but nothing changes.
![2023-10-17 16_40_48-SD Next — Mozilla Firefox](https://github.com/vladmandic/automatic/assets/86837667/9982a37b-e57c-484f-be06-3b7b530e0b3f)

So just wondering if this is on my end or if all this changed with the new update I can barely read any of the text and I never liked that compact design so wondering if this can be change back like it was before (like the basic gradio design and yes even when I pick that theme it shows like that).

### Version Platform Description

Windows 10/Firefox.

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by gitbreiti** [comment]
It's the same here. Each individual field slides further down.

**Comment by vladmandic** [comment]
- all built-in themes are fully supported:  
  - *black-teal (default), light-teal, black-orange, invoked, amethyst-nightfall, midnight-barbie*  
- if you're using any **gradio default** themes or a **3rd party** theme or  that are not optimized for SD.Next, you may experience issues  
  default minimal style has just been updated for compatibility, but actual styling is completely outside of SD.Next control
