### ISSUE TITLE
[Issue]: Accordion submenu layout

### ISSUE THREAD

**Issue by fbellgr** [vladmandic/automatic#2324]
### Some new information

After more tests, this appears to be an issue after switching to a gradio theme.
After reverting to the default black-teal, the problems described here do not happen.

### Issue Description

After reinstalling from scratch to the latest revision, I notice that the layout of the submenus are now vary narrow and compact.

I tried toggling on and off the new "Compact view" settings in case this was the cause, but it does not change anything.

It makes the whole page very long and some elements overlap with each other.

It would be easier to use if the submenus were allowed to occupy more horizontal space.

Also, in img2img, in addition to having the same layout issues, the resulting image is no longer on the side but comletely at the bottom of the page. Extensions take up more than the screen size, even on a 2K monitor.

![image](https://github.com/vladmandic/automatic/assets/27892962/5ad13ef2-6b08-4da6-98a8-21e0f9e79033)

And in img2img, the submenus appear like this.
Notice the upscalers lists in Ultimate SD Upscale. There is actually an horizontal scrollbar further down the page that allows seeing all the settings that are way out of the page width on the right.
ControlNet suffers from the same issues.

![image](https://github.com/vladmandic/automatic/assets/27892962/8a3b82d9-d92e-4154-9ab9-828f7271ebf1)

### Version Platform Description

Firefox 118
Gradio default

```
2023-10-17 20:02:23,535 | sd | INFO | launch | Starting SD.Next
2023-10-17 20:02:23,536 | sd | INFO | installer | Python 3.10.12 on Linux
2023-10-17 20:02:23,543 | sd | INFO | installer | Version: app=sd.next updated=2023-10-17 hash=379fe1f3 url=https://github.com/vladmandic/automatic/tree/master
2023-10-17 20:02:23,843 | sd | INFO | launch | Platform: arch=x86_64 cpu=x86_64 system=Linux release=5.15.0-86-generic python=3.10.12
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by fbellgr** [comment]
Here is a screenshot taken from Chromium 118

![image](https://github.com/vladmandic/automatic/assets/27892962/49e7d1c4-f413-46e2-841b-fd26c05d78a3)

**Comment by Felsync** [comment]
There's 1000px padding added to settings-accordion and gap classes. I added 

.settings-accordion .gap {
    padding-right: 0px;
}

to user.css to temporarily sort of aleviate the issue till someone smarter than me figures it out.

**Comment by vladmandic** [comment]
Make sure you're using black-teal theme. Other themes will be updated shortly.

**Comment by vladmandic** [comment]
- all built-in themes are fully supported:  
  - *black-teal (default), light-teal, black-orange, invoked, amethyst-nightfall, midnight-barbie*  
- if you're using any **gradio default** themes or a **3rd party** theme or  that are not optimized for SD.Next, you may experience issues  
  default minimal style has just been updated for compatibility, but actual styling is completely outside of SD.Next control

**Comment by fbellgr** [comment]
I was not aware of the distinction built-in vs 3rd party.
Thanks for clearing that up.
Black-teal is a much better default than black-orange, in my opinion, so thank also for changing this.
Trying out all the themes to find your favourite is kind of laborious, so I am happy with this default. :smiley:
