### ISSUE TITLE
[Issue]: Clicking on the image "Show" button opens the wrong directory.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [vladmandic/automatic#2327]
### Issue Description

Under the "From Text" tab, create an image and click the "Show" button, expecting it to open the explorer window in the correct directory (F:\automatic\outputs\text) to view the images. It actually opens the window in directory "C:\Users\{username}\AppData\Local\Temp\gradio"

Because of the latest update recommendations, this was freshly installed yesterday. I also tried running it with "--safe", but the same problem persists.

### Version Platform Description

08:48:36-689822 INFO     Starting SD.Next
08:48:36-699334 INFO     Python 3.10.6 on Windows
08:48:36-851531 INFO     Version: app=sd.next updated=2023-10-17 hash=379fe1f3
                         url=https://github.com/vladmandic/automatic.git/tree/master
08:48:37-116187 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22621-SP0 python=3.10.6
08:48:37-120187 INFO     nVidia CUDA toolkit detected: nvidia-smi present
08:48:37-121692 INFO     Installing torch - this may take a while
08:48:37-217024 INFO     Verifying requirements
08:48:37-234579 INFO     Verifying packages
08:48:37-236583 INFO     Verifying repositories
08:48:40-128089 INFO     Verifying submodules
08:49:16-993685 INFO     Extension installed packages: sd-webui-controlnet ['opencv-python==4.8.1.78']
08:49:27-001797 INFO     Extension installed packages: sd-webui-roop ['opencv-python==4.7.0.72']
08:49:27-003805 INFO     Extensions enabled: ['clip-interrogator-ext', 'Lora', 'sd-extension-chainner',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'adetailer',
                         'sd-dynamic-prompts', 'sd-webui-roop']

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by GalaxyTimeMachine** [comment]
I've realised this happens when the grid image is selected, but I am not saving the grid to any location. I'm sure this used to default to going to the ".../output/text" directory, which is more useful.

**Comment by vladmandic** [comment]
show button has been changed so instead of blindly opening single predefined output save location, it actually opens location where image is.
so if image is SAVED, its going to open folder where its saved. so it works for txt2img, img2img, with custom path formats, etc.
and if image is NOT SAVED, its going to open gradio temp folder because that is exactly where image is.
