### ISSUE TITLE
[Extension]: (Apparent) incompatibility with Lora Block Weight extension

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2328]
### Issue Description

The LoRA block weight extension allows to define presets as a shortcut for actual weights in the prompt, such as:

```
<lora:add_detail:0.1:BG>
```

where  BG is defined as

```
0,0,0,0.5,1,1,0,1,0,0,0,0,0,0,0,1,1
```

This used to work before the rewrite of the LoRA/LyCORIS handler. At this time, instead, it generates an exception:

```
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /notebooks/automatic/modules/extra_networks.py:73 in activate                │
│                                                                              │
│    72 │   │   try:                                                           │
│ ❱  73 │   │   │   extra_network.activate(p, extra_network_args)              │
│    74 │   │   except Exception as e:                                         │
│                                                                              │
│ /notebooks/automatic/extensions-builtin/Lora/extra_networks_lora.py:38 in    │
│ activate                                                                     │
│                                                                              │
│   37 │   │   │   te_multiplier = float(params.named.get("te", te_multiplier) │
│ ❱ 38 │   │   │   unet_multiplier = float(params.positional[2]) if len(params │
│   39 │   │   │   unet_multiplier = float(params.named.get("unet", unet_multi │
╰──────────────────────────────────────────────────────────────────────────────╯
ValueError: could not convert string to float: 'BG'
```

My guess is that the extension does something that is either "wrong" or unsupported by the current handler. I can't however file an issue upstream until I can confirm whether this is the extension misbehaving, or a SD.Next bug.

### Version Platform Description

Paperspace, Ubuntu 20.04
NVIDIA A4000

### URL link of the extension

https://github.com/hako-mikan/sd-webui-lora-block-weight

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by lbeltrame** [comment]
It's worth noting that there is no exception if the `lbw=` syntax is used instead. However, I don't see any output from the extension in the log so I'm unable to confirm whether it is actually working or not.

**Comment by vladmandic** [comment]
all i can see is that lbw gets loaded and triggered correctly:
> {'isnet': True, 'isxl': False, 'islora': True, 'enable LBW': True, 'registerd': True}
but what happens inside lbw, i have no idea.

regarding dissapearing ui on restore gen params, i can see that and i'll look into that. from the first look it seems to happen as lbw is applying xyz grid settings - instead of hiding xyz grid, it hides the parent element.

**Comment by lbeltrame** [comment]
As far as I can tell, it is working as I'm selectively applying LoRAs. However, I need to test with the shorthand.

If need be I'll ask the upstream maintainer on how to debug.

**Comment by vladmandic** [comment]
Closing.
