### ISSUE TITLE
[Issue]: Extra network description files cut the filename incorrectly if it contains more than one dot

### ISSUE THREAD

**Issue by slimeqslimedog** [vladmandic/automatic#2331]
### Issue Description

A model description file's name should be "_model_.txt", but if the model name contains any dots, the name is truncated to before the first dot, rather than the last one.

Example: the description file name for `model v2.0.safetensors` should be `model v2.0.txt`, but instead it ends up being `model v2.txt`. This can result in several models with names that differ only after a dot to have description files that overwrite each other.

(I'm also surprised that you changed the file names from the previous `model.description.txt`, but I understand that may just be a personal decision.)

### Version Platform Description

```
08:02:17-557767 INFO     Python 3.10.9 on Windows
08:02:17-665014 INFO     Version: app=sd.next updated=2023-10-17 hash=379fe1f3
                         url=https://github.com/vladmandic/automatic.git/tree/master
08:02:18-224321 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 2, GenuineIntel system=Windows
                         release=Windows-10-10.0.22621-SP0 python=3.10.9
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i cannot reproduce this:

renamed one model, opened details and added description - description filename looks good to me.

```
-rw-r--r-- 1 vlado vlado 3.9G 2023-10-18 10:59 'model v2.0.safetensors'
-rw-r--r-- 1 vlado vlado   14 2023-10-18 11:33 'model v2.0.txt'
```

**Comment by slimeqslimedog** [comment]
Hmm -- maybe it was something else about that filename causing the problem. The name is `Adventures of Pippi Longstocking - Pippi Longstocking - deygdrixe221 v2.0 (Dreamshaper).safetensors`.

**Comment by vladmandic** [comment]
```log
-rw-r--r-- 1 vlado vlado 3.9G 2023-10-18 10:59 'Adventures of Pippi Longstocking - Pippi Longstocking - deygdrixe221 v2.0 (Dreamshaper).safetensors'
-rw-r--r-- 1 vlado vlado   14 2023-10-18 11:51 'Adventures of Pippi Longstocking - Pippi Longstocking - deygdrixe221 v2.0 (Dreamshaper).txt'
```

i know the problem you describe WAS a real problem, but it was resolved. so if your txt file was created using older version of SDNext, that is entirely possible. but i cannot reproduce using current version.

**Comment by slimeqslimedog** [comment]
No problem, thanks!
