### ISSUE TITLE
[Feature]: Cache Embedding data for parsing on model change.

### ISSUE THREAD

**Issue by midcoastal** [vladmandic/automatic#2339]
### Feature description

It's a known issue that I have what may be considered "too many of all the things," but re-parsing Embeddings is impacting model switching for me. I haven't delved into it, I am more putting this Issue here so I can look in to it and have an Issue to post to/link to.

**Comment by midcoastal** [comment]
I hate to be dumb, but why do embeddings have to be added if they are not used (are they not triggered to be included at tokenization? I seem to remember seeing code to that affect.  If not for embeddings, than for Loras)

As I understand it, the activation tokens for Embeddings are culled to *just* the filename.  So...  Why add them all?  Why not just apply them on tokenization of the string?

**Comment by vladmandic** [comment]
because there is no way if they are triggered or not unless they are actually added to tokenizer.
in theory it would be possible to add a "custom" token list based on embeddings to check if tokenizer needs to be updated or not. note that such custom list should still be rebuilt on each model change to ensure compatibility of each token with loaded model.

if someone contributes a pr, i'd welcome it. but given the current load, its not something i would do anytime soon.

**Comment by midcoastal** [comment]
Fair, I will have a look I guess, because...

```
Extra networks: page='embedding' items=3245 subdirs=3239 tab=txt2img dirs=['models/embeddings'] time=55.47s
```

And the model-load time get's impacted quite a bit...

**Comment by vladmandic** [comment]
with 3k embeddings, yes, i believe that.
contributions are definitely welcome!

**Comment by vladmandic** [comment]
to "compatible" pipelines. there are check is there a compatibile text_encoder inside a loaded model, etc.

**Comment by midcoastal** [comment]
> with 3k embeddings, yes, i believe that. contributions are definitely welcome!

Yeah, I am going to have to look in to this.  Currently, switching from XL to non-XL (something I have FAR more embeddings for) isn't possible.  I am going to guess that using non-sdxl is going to be a no-go at the moment...  Loading SDXL, with only 26 embeddings, takes 32 seconds:

```
Loaded embeddings: loaded=29 skipped=3218 time=32.01s
```

I don't have the patience to try to wait for non XL to load.

This is new behavior, I was bouncing around from XL to non-XL prior to the latest release.  Heck, I was doing it in Dev just prior to this release.  Any idea what may have changed?

**Comment by midcoastal** [comment]
> Until recently sdnext supported only small subset of embeddings for SDXL. Now it has full support for both text encoders and adding tokens to encoders in SDXL is just slow.

Yeah, but this is a switching back to standard SD issue.  Is this a `Diffusers` Issue?

Also new with this locking behavior, I left SDNext sitting for the better part of an hour "loading" the embeddings for an SD1.5 model, gave up, `ctrl+C` and got a Segfault?  That's new...

```
15:42:00-432416 DEBUG    Server alive=True jobs=1 requests=233 uptime=4170s memory used=26.17 total=125.53 idle                                                                                                                                                                           
^C15:43:48-690374 INFO     Exiting                                                                                                                                                                                                                                                          
terminate called without an active exception
Fatal Python error: Aborted

Fatal Python error: Segmentation fault


Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, PIL._imaging, PIL._imagingft, yaml._yaml, matplotlib._c_internal_utils, matplotlib._path, kiwisolver._cext, matplotlib._image, regex._regex, sentencepiece._sentencepiece, google.protobuf.pyext._message, tensorflow.python.framework.fast_tensor_util, h5py._errors, h5py.defs, h5py._objects, h5py.h5, h5py.h5r, h5py.utils, h5py.h5s, h5py.h5ac, h5py.h5p, h5py.h5t, h5py._conv, h5py.h5z, h5py._proxy, h5py.h5a, h5py.h5d, h5py.h5ds, h5py.h5g, h5py.h5i, h5py.h5f, h5py.h5fd, h5py.h5pl, h5py.h5o, h5py.h5l, h5py._selector, scipy._lib._ccallback_c, scipy.sparse._sparsetools, _csparsetools, scipy.sparse._csparsetools, scipy.sparse.linalg._isolve._iterative, scipy.linalg._fblas, scipy.linalg._flapack, scipy.linalg.cython_lapack, scipy.linalg._cythonized_array_utils, scipy.linalg._solve_toeplitz, scipy.linalg._decomp_lu_cython, scipy.linalg._matfuncs_sqrtm_triu, scipy.linalg.cython_blas, scipy.linalg._matfuncs_expm, scipy.linalg._decomp_update, scipy.linalg._flinalg, scipy.sparse.linalg._dsolve._superlu, scipy.sparse.linalg._eigen.arpack._arpack, scipy.sparse.csgraph._tools, scipy.sparse.csgraph._shortest_path, scipy.sparse.csgraph._traversal, scipy.sparse.csgraph._min_spanning_tree, scipy.sparse.csgraph._flow, scipy.sparse.csgraph._matching, scipy.sparse.csgraph._reordering, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.tslib, pandas._libs.lib, pandas._libs.hashing, pandas._libs.ops, numexpr.interpreter, pandas._libs.arrays, pandas._libs.index, pandas._libs.join, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.internals, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.tslibs.strptime, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json, scipy.ndimage._nd_image, scipy.special._ufuncs_cxx, scipy.special._ufuncs, scipy.special._specfun, scipy.special._comb, scipy.special._ellip_harm_2, _ni_label, scipy.ndimage._ni_label, pydantic.typing, pydantic.errors, pydantic.version, pydantic.utils, pydantic.class_validators, pydantic.config, pydantic.color, pydantic.datetime_parse, pydantic.validators, pydantic.networks, pydantic.types, pydantic.json, pydantic.error_wrappers, pydantic.fields, pydantic.parse, pydantic.schema, pydantic.main, pydantic.dataclasses, pydantic.annotated_types, pydantic.decorator, pydantic.env_settings, pydantic.tools, pydantic, websockets.speedups, markupsafe._speedups, PIL._webp, psutil._psutil_linux, psutil._psutil_posix, skimage._shared.geometry, _pi_heif, scipy._lib._uarray._uarray, scipy.integrate._odepack, scipy.integrate._quadpack, scipy.integrate._vode, scipy.integrate._dop, scipy.integrate._lsoda, scipy.optimize._minpack2, scipy.optimize._group_columns, scipy._lib.messagestream, scipy.optimize._trlib._trlib, numpy.linalg.lapack_lite, scipy.optimize._lbfgsb, _moduleTNC, scipy.optimize._moduleTNC, scipy.optimize._cobyla, scipy.optimize._slsqp, scipy.optimize._minpack, scipy.optimize._lsq.givens_elimination, scipy.optimize._zeros, scipy.optimize.__nnls, scipy.optimize._highs.cython.src._highs_wrapper, scipy.optimize._highs._highs_wrapper, scipy.optimize._highs.cython.src._highs_constants, scipy.optimize._highs._highs_constants, scipy.linalg._interpolative, scipy.optimize._bglu_dense, scipy.optimize._lsap, scipy.spatial._ckdtree, scipy.spatial._qhull, scipy.spatial._voronoi, scipy.spatial._distance_wrap, scipy.spatial._hausdorff, scipy.spatial.transform._rotation, scipy.optimize._direct, scipy.special.cython_special, scipy.stats._stats, scipy.stats.beta_ufunc, scipy.stats._boost.beta_ufunc, scipy.stats.binom_ufunc, scipy.stats._boost.binom_ufunc, scipy.stats.nbinom_ufunc, scipy.stats._boost.nbinom_ufunc, scipy.stats.hypergeom_ufunc, scipy.stats._boost.hypergeom_ufunc, scipy.stats.ncf_ufunc, scipy.stats._boost.ncf_ufunc, scipy.stats.ncx2_ufunc, scipy.stats._boost.ncx2_ufunc, scipy.stats.nct_ufunc, scipy.stats._boost.nct_ufunc, scipy.stats.skewnorm_ufunc, scipy.stats._boost.skewnorm_ufunc, scipy.stats.invgauss_ufunc, scipy.stats._boost.invgauss_ufunc, scipy.interpolate._fitpack, scipy.interpolate.dfitpack, scipy.interpolate._bspl, scipy.interpolate._ppoly, scipy.interpolate.interpnd, scipy.interpolate._rbfinterp_pythran, scipy.interpolate._rgi_cython, scipy.stats._biasedurn, scipy.stats._levy_stable.levyst, scipy.stats._stats_pythran, scipy.stats._statlib, scipy.stats._sobol, scipy.stats._qmc_cy, scipy.stats._mvn, scipy.stats._rcont.rcont, pywt._extensions._dwt, pywt._extensions._cwt, pywt._extensions._pywt, pywt._extensions._swt, matplotlib.backends._tkagg, lxml._elementpath, lxml.etree (total: 236)
Segmentation fault (core dumped)
```

**Comment by vladmandic** [comment]
segfault can always happen when interrupting operation which is happening somewhere in binary code (in this case inside numpy), that is not strange.

but yes, i see a good case for optimizing how embeddings are handled.
(a different question would be why do you need to have 3+k embeddings to start with as that is not a common user scenario)

**Comment by midcoastal** [comment]
Oh...  It's not just the Embeddings...

```
Loaded upscalers: total=158 downloaded=116 user=115 ['None', 'Lanczos', 'Nearest', 'ChaiNNer', 'SCUNet', 'SD', 'SwinIR', 'RealESRGAN', 'ESRGAN', 'LDSR']
Extra networks: page='model' items=4552 subdirs=4890 tab=txt2img dirs=['models/Stable-diffusion', 'models/Diffusers'] time=50.54s
Extra networks: page='style' items=291 subdirs=2 tab=txt2img dirs=['models/styles', 'html'] time=0.18s 
Extra networks: page='embedding' items=3253 subdirs=3247 tab=txt2img dirs=['models/embeddings'] time=53.47s
Extra networks: page='hypernetwork' items=61 subdirs=62 tab=txt2img dirs=['models/hypernetworks'] time=1.39s
Extra networks: page='vae' items=19 subdirs=1 tab=txt2img dirs=['models/VAE'] time=0.69s
Extra networks: page='lora' items=23964 subdirs=23982 tab=txt2img dirs=['models/Lora', 'models/LyCORIS'] time=165.71s\
```

```
$ find ./Poses -name '*.jpg' | wc -l
4084
```

```
sd-dynamic-prompts/wildcards$ find ./ -name '*.txt' -exec cat {} \; | wc -l
509711
```

As for "why?" I don't know, I have the bandwidth and the storage and a strong urge to hoard...

*Don't judge me*

;-)

**Comment by midcoastal** [comment]
As for the inevitable "why is everything in a dedicated folder?"

Well, directory traversal over the network is inefficient for large directories, so this keeps my directories small, and the app, actually, quite a bit faster.

Per-Model folder-structure looks like this:

```
$ ls -la models/embeddings/SK_VECTORART/
... SK_VECTORART.civitai.info
... SK_VECTORART.image.2626614.jpeg
... SK_VECTORART.preview.jpeg
... SK_VECTORART.safetensors
```

Where `*.image.*` can be any number of images (basically, every image attached to the Model Version on CivitAI at the time of fetching).

As you can imagine, the amplification in the directory was enormous, with some models having and many as 10 images, some having many many more.  So, that's why the folders. :-D

**Comment by vladmandic** [comment]
> As for "why?" I don't know, I have the bandwidth and the storage and a strong urge to hoard...

as good as answer as any...

> Don't judge me

naah, curiosity and judgement are different things :)

anyhow, i get the subfolder thing. although your comment on traversal depends on which underlying os function is used.
things like scandir or glob are horrible while listdir is actually pretty good.

i can just imagine how many performance problems this may create. and i'd love to have spare cycles to figure out how to optimize for that (i actually like doing that), but i need to pick my battles.

**Comment by midcoastal** [comment]
`Loaded embeddings: loaded=3123 skipped=137 time=1226.54s`

Ugh...

**Comment by midcoastal** [comment]
@vladmandic: `22:40:57-200943 INFO     Loaded embeddings: loaded=3368 skipped=147 time=51.27s`

PR inbound.

**Comment by midcoastal** [comment]
@vladmandic - Before I submit my PR, I wanted to check on the repo preferences:

The performance hit is due to the way that we load the embeddings, and the way that `diffusers.loaders.TextualInversionLoaderMixin` is written, our hands are tied.  My solution requires either implementing duplicate functionality for several class methods, OR patching `diffusers.loaders.TextualInversionLoaderMixin` in-place.  Which practice is preferred?

I have currently implemented the fixes as a patch against the class, and it works swimmingly.  Performance is stellar, and I was able to preserve function signatures and behavior.

I could just as easily break the behavior out into dedicated functions, but then we have duplicated functionality, and perhaps significant changes if/when the `diffusers` library changes. As it stands, with patching, if the `diffusers` library implements the same behavior, it would be as simple as removing our patches and moving on.

I may submit my PR as it stands, and re-factor if requested. Let me know.

**Comment by vladmandic** [comment]
There is no general preference, it's about what is cleaner for each specific case. And it sounds like patching is cleaner here.

**Comment by midcoastal** [comment]
@vladmandic - PR #2506 submitted.

Side note on that:

During testing I noticed that `DIFFUSERS` handles `BREAK` differently (and breaks).

Example using an SD1.5 model:

`wood elf rogue, BREAK (white_background:1.4), illustration, absurdres, rpg dnd fantasy, character_portrait, solo, full_body, BREAK traveller rpg`
![image](https://github.com/vladmandic/automatic/assets/125929259/be69bf09-95ec-4152-af85-c2bdca84de39)

`wood elf rogue, BREAK (white_background:1.4), illustration, absurdres, rpg dnd fantasy, character_portrait, solo, full_body, traveller rpg`
![image](https://github.com/vladmandic/automatic/assets/125929259/ddaf44ee-998c-4d50-9467-d59a0a11752d)

Examples using SD-XL model (same prompts):

![image](https://github.com/vladmandic/automatic/assets/125929259/2de2e35e-2267-4053-9f85-8e79621e7322)

![image](https://github.com/vladmandic/automatic/assets/125929259/34d913eb-d88c-4d7a-91fa-9d7a61960ec2)

In theory, the added `BREAK`s shouldn't change the image "much", or at least, "drastically."  For example, here is the same prompt without *any* `BREAK`s:

![image](https://github.com/vladmandic/automatic/assets/125929259/677e6775-4845-4646-9c8b-d42c33a92917)

Pretty much the same as the one with `BREAK`, but still *very* different from the one with 2.

Am I missing something?  This sent me down a *very* annoying rabbit hole...  :-(

**Comment by vladmandic** [comment]
link to #2506

**Comment by vladmandic** [comment]
this is considered resolved.
