### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by EKKIV0K** [vladmandic/automatic#2340]
Enhance preview thumbnails for GIF preview ?

Hello i have a little question about an improvement for our favorite SDNEXT <3 
in fact it's really simple, some model on CivitAI, have GIF version preview, is it possible, to get this preview on SDNEXT ? 

cause it create on the status lauch some error cause sdnext cannot read the preview :) 
but there is something that i cannot understant too is that some preview are in png wich is usualy read by sdnext 

### Version Platform Description

Windows 10 
Nvidia 531.18

**Comment by vladmandic** [comment]
Can you provide actual example instead of just theory?

Also, please fill issue title!

**Comment by EKKIV0K** [comment]
@vladmandic there is no issues, and there is no theory lol, i was just asking to maybe bring as preview on the web ui, animated gif used on CivitAI as preview on some models, (not all) but it seems to be the "sliders lora" models that the author use animated preview on their model pages, it's good but when you update with civitai helper thumbnails on downloaded models after a restart sd.next cannot identfy them as a correct preview maybe because they are gif or animated picture format :)

**Comment by vladmandic** [comment]
That's why I want exact image to check. Is it animated gif or something else. I don't know. I cannot add support for something without even checking it out.

**Comment by EKKIV0K** [comment]
right now i cannot provide you an example cause my sd.next is down, gradio problem cannot load theme :/ 
so i cannot copy the part of the console mentioning the errors about thos "png" @vladmandic

**Comment by vladmandic** [comment]
closing.
