### ISSUE TITLE
[Issue]: missing arrow to parse pasted prompt

### ISSUE THREAD

**Issue by mkossigit** [vladmandic/automatic#2350]
### Issue Description

*this was an upgrade*
Missing the arrow button on the right side of the prompt box that parsed a pasted prompt to the correct settings.
Forgot the name sorry..
Heres how it was :

![vlad button](https://github.com/vladmandic/automatic/assets/90536087/5637219d-3f78-4fe4-995b-7f404b0a74fe)

Heres how it looks now:
![vlad  button now](https://github.com/vladmandic/automatic/assets/90536087/2f71c8f4-5142-49f5-b6ce-5b7eb9013dee)

### Version Platform Description

Starting SD.Next
Python 3.10.6 on Windows
Version: app=sd.next updated=2023-10-18 hash=66f75b6a
url=https://github.com/vladmandic/automatic/tree/master
Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows
 release=Windows-10-10.0.19045-SP0 python=3.10.6
 nVidia CUDA toolkit detected: nvidia-smi present

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
![image](https://github.com/vladmandic/automatic/assets/1969381/a11bb199-0a16-451d-8962-bc68240e1280)

**Comment by mkossigit** [comment]
Doh, thought that was to recall a prompt when you use clear.. so sorry, working fine. :)
