### ISSUE TITLE
[Issue]: Batch size >1 produces different results than when it is 1 with DPM++ 2M SDE Sampler

### ISSUE THREAD

**Issue by dpinav** [vladmandic/automatic#2352]
### Issue Description

With DPM++ 2M SDE sampler, when generating images using the same seed, prompt and settings, the result will vary if the image is generated while using batch size bigger than 1 and then regenerated with batch size set to 1. 

This didn't happen in previous versions. From some quick testing it also does not appear to happen in other samplers

To reproduce:
- Set sampler to DPM++ 2M SDE.
- Generate N images by using batch size = N. 
- Select the first image (not grid), reuse its seed, and set batch size to 1. 
- Generate the image. It will be different from the previous one. Expected result should be the same initial image.
- If you set batch size back to N and regenerate, the image will be the same as initially (Supposing you selected the first image of all).

Two example images that should be identical but are not:

![00108-anime-jellyDonut_v10-photo of beautiful swiss valley](https://github.com/vladmandic/automatic/assets/55802041/1d6a9748-c643-4a2a-9001-fe3cf0cca5fa)
> Steps: 15, Seed: 1194124464, Sampler: DPM++ 2M SDE, CFG scale: 6, Size: 512x768, Batch: 1x2, Index: 1x1, Parser: Full parser, Model: jellyDonut_v10, Model hash: 442231323f, VAE: vae-ft-mse-840000-ema-pruned, Clip skip: 2, Backend: Original, App: SD.Next, Version: 505f36d, Operations: txt2img, Sampler brownian: False

![00110-anime-jellyDonut_v10-photo of beautiful swiss valley](https://github.com/vladmandic/automatic/assets/55802041/367ff39f-3f24-4d74-8b8f-f8a8106b046b)
> Steps: 15, Seed: 1194124464, Sampler: DPM++ 2M SDE, CFG scale: 6, Size: 512x768, Parser: Full parser, Model: jellyDonut_v10, Model hash: 442231323f, VAE: vae-ft-mse-840000-ema-pruned, Clip skip: 2, Backend: Original, App: SD.Next, Version: 505f36d, Operations: txt2img, Sampler brownian: False

### Version Platform Description

- Python 3.10.6 on Windows
- Version: app=sd.next updated=2023-10-19 hash=505f36df  url=https://github.com/vladmandic/automatic.git/tree/master
- Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows release=Windows-10-10.0.19045-SP0 python=3.10.6
- Engine: backend=Backend.ORIGINAL compute=cuda mode=no_grad device=cuda cross-optimization="Scaled-Dot-Product"
- Device: device=NVIDIA GeForce RTX 3090 n=1 arch=sm_90 cap=(8, 6) cuda=12.1 cudnn=8905 driver=531.79

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by dpinav** [comment]
In fact SDE samplers seem to produce significant different results between step variations too. But I do not know if that is normal behavior.

**Comment by brknsoul** [comment]
IIRC Unless you turn on a setting, SDP isn't deterministic.

**Comment by dpinav** [comment]
Haven't disabled memory attention. 

All the other samplers are working fine, generating the same image given same values. Even SDE samplers are, just not when using batch size.

SDE samplers overall are acting kind of weird but I haven't got the knowledge to nail it down.

**Comment by srcrist** [comment]
I am also seeing a general discrepancy in SDE samplers since the latest merge. I've been putting off adding a comment here, because I have very little concrete to add. I am unable to reproduce images generated from before the merge with SDE samplers, and no matter how I tweak the sigmas and noise it doesn't seem to make a difference. I suspect a larger issue with SDE samplers in general, as @dpinav mentioned in a comment above, but I just can't put my finger on it. They function, but they function...differently. And that's about as concrete as I can put it right now.

**Comment by Threnos** [comment]
I also noticed this, but never cared enough to post an issue.

**Comment by srcrist** [comment]
Forgot to add that SDE samplers also seem broken in Diffusers. Every generation with the same seed returns an entirely different image.

**Comment by dpinav** [comment]
> Forgot to add that SDE samplers also seem broken in Diffusers. Every generation with the same seed returns an entirely different image.

Yeah they're working pretty weird in both backends.

**Comment by nalf3in** [comment]
I'm still getting a different result with the same seed and batch size and count = 1 with 93f35ccf885b7ad0e85878d58421507aecf14f95, anybody else still getting the issue/ is that expected behavior ?

**Comment by leppie** [comment]
> I'm still getting a different result with the same seed, settings and batch size and count = 1 with [93f35cc](https://github.com/vladmandic/automatic/commit/93f35ccf885b7ad0e85878d58421507aecf14f95), anybody else still getting the issue/ is that expected behavior ?

I  think  it was broken with https://github.com/vladmandic/automatic/commit/84d733f0a0b1d6d2e3d2c3c1f60dd96668b73585

`update_sampler`  needs  to be called  before `set_pipeline_args`

Also `noise_sampler_seed = p.seeds` not  just the first seed (that breaks batching and subseeds).

**Comment by vladmandic** [comment]
@leppie best if you document in details and create new issue - you can reference this issue, but replying on something that is closed for half a year doesn't help.
and if you have suggestions, please do try them out and let us know!

**Comment by leppie** [comment]
> @leppie best if you document in details and create new issue - you can reference this issue, but replying on something that is closed for half a year doesn't help. and if you have suggestions, please do try them out and let us know!

PR was quicker :D
