### ISSUE TITLE
[Issue]: Problem with Styles

### ISSUE THREAD

**Issue by StingPax** [vladmandic/automatic#2360]
### Issue Description

Hello, since the new update the save styles button is gone, how do i save styles now? Second question: I cant seem to pull out the prompts of a style anymore as it was before by pushing the (now) apply button. Third thing: When putting prompts of others into the prompt box, by pressing the apply button, it put all the generator settings like sampling steps, resolution etc. in, but now this wont work anymore?

Edit: Found out the "Show" button don't opens the output folder anymore, but a temp folder I never knew about until now, why?

Thanks for helping me! :)

### Version Platform Description

Version: app=sd.next updated=2023-10-19 hash=53d0cb35

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by StingPax** [comment]
> There's a Styles tab in the Networks pane, with buttons in that pane.

Thank you! Could never have guessed that it got moved there. Now that i now and looked it up, i even like that change, i must say.
Do you know, why the "Show" button doesnt get you to the output folder anymore?

**Comment by vladmandic** [comment]
> Edit: Found out the "Show" button don't opens the output folder anymore, but a temp folder I never knew about until now, why?

previously show button was blindly opening output folder. but why?
show button now opens actual location of the image. if image is saved in output folder, it will open output folder.
if image is not saved, it opens temp folder because that is where image currently resides.
if image is saved into some subfolder because user is using 'directory name pattern', it will open that.
etc...

> When putting prompts of others into the prompt box, by pressing the apply button, it put all the generator settings like sampling steps, resolution etc. in, but now this wont work anymore?

that does work.

**Comment by StingPax** [comment]
> > Edit: Found out the "Show" button don't opens the output folder anymore, but a temp folder I never knew about until now, why?
> 
> previously show button was blindly opening output folder. but why? show button now opens actual location of the image. if image is saved in output folder, it will open output folder. if image is not saved, it opens temp folder because that is where image currently resides. if image is saved into some subfolder because user is using 'directory name pattern', it will open that. etc...
> 
> > When putting prompts of others into the prompt box, by pressing the apply button, it put all the generator settings like sampling steps, resolution etc. in, but now this wont work anymore?
> 
> that does work.

But i realy have a copy of the image in output AND temp folder.

**Comment by vladmandic** [comment]
you don't. if image is auto-saved, its never stored in temp to start with.
and if you click save button yes, its saved to whatever your saved folder is. but image in gallery is still the one in temp.

**Comment by StingPax** [comment]
Ah i get it, hey one last question, there was an apply button, with that, ich could apply whole generator settings like resolution, sampling steps, etc, how do i do this now?

**Comment by vladmandic** [comment]
restore button?

**Comment by StingPax** [comment]
Ok i got it now, just dont wanted to work on one gen settings for some reason, tried on another and it worked. Thank you!
