### ISSUE TITLE
[Extension]: Mov2Mov

### ISSUE THREAD

**Issue by UncannyKenny** [vladmandic/automatic#2362]
### Issue Description

When Installing Mov2Mov, it isn't showing up in the UI.
I've tried installing both this:
https://github.com/Scholar01/sd-webui-mov2mov
And a source of it:
https://github.com/DavG25/sd-webui-mov2mov

Both aren't showing up in the UI tabs.
AnimateDiff also isn't showing so I thought maybe there's a problem that is shared between these two extensions?

### Version Platform Description

OS: Ubuntu Linux
GPU: AMD Radeon 6900XT
Program Version: 2023-10-17
Browser: FireFox

### URL link of the extension

https://github.com/Scholar01/sd-webui-mov2mov

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
- AnimateDiff: showing and working
- Mov2Mov: just pushed an update, <https://github.com/DavG25/sd-webui-mov2mov> is working, <https://github.com/Scholar01/sd-webui-mov2mov> is unsupported (im not going to go into details here on why)
