### ISSUE TITLE
Settings page jumps on edit

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#2364]
Just a thing I saw: when you are in the SD config and have clicked "Show all pages" and then edit something, like toggling a checkbox, the page always scrolls/jumps to the top

**Comment by vladmandic** [comment]
which is a fully valid observation, but why delete issue template? it only takes couple of seconds to fill it. and trust me, it does make a difference for me - big one - its not a nitpick. flagging this issue as invalid for now.

**Comment by Tillerz** [comment]
I didn't delete any template, I clicked "link this in a new issue" right from the discussion. If that is not pulling the template it's not MY fault, right?

**Comment by vladmandic** [comment]
i agree that's not your fault, but i also cannot change behavior of githubs buttons such as "link this". if issue is created by using new issue, it will show template.

**Comment by Tillerz** [comment]
Aw bummer. Ok. :) Gonna check if github has a feature request tool somewhere.
