### ISSUE TITLE
[Extension]:  sd-webui-regional-prompter does not function with StableDiffusionXLPipeline

### ISSUE THREAD

**Issue by LankyPoet** [vladmandic/automatic#2365]
### Issue Description

I have updated both SD.Next and Regional Prompter to latest. When I try using Regional Prompter and an SDXL model, I receive the below error. The author of Regional Prompter said "The StableDiffusionXLPipeline is a method introduced by SD.Next for XL models, but it is not compatible with the Regional Prompter. If you want to use SDXL, Use A1111 Web-UI." But I am hoping to not have to use A1111 for this as I much prefer SD.Next.

`10:27:45-891495 ERROR    Running script process: extensions\regional-prompter\scripts\rp.py: AttributeError
╭──────────────────────────────────────────────── Traceback (most recent call last) ────────────────────────────────────────────────╮
│ C:\sdnext\modules\scripts.py:487 in process                                                                                       │
│                                                                                                                                   │
│   486 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                                    │
│ ❱ 487 │   │   │   │   script.process(p, *args, **kwargs)                                                                          │
│   488 │   │   │   except Exception as e:                                                                                          │
│                                                                                                                                   │
│ C:\sdnext\extensions\regional-prompter\scripts\rp.py:480 in process                                                               │
│                                                                                                                                   │
│    479 │   │   │   if "Att" in calcmode:                                                                                          │
│ ❱  480 │   │   │   │   self.handle = hook_forwards(self, p.sd_model.model.diffusion_model)                                        │
│    481 │   │   │   │   if hasattr(shared.opts,"batch_cond_uncond"):                                                               │
│                                                                                                                                   │
│ C:\sdnext\venv\lib\site-packages\diffusers\configuration_utils.py:137 in __getattr__                                              │
│                                                                                                                                   │
│   136 │   │                                                                                                                       │
│ ❱ 137 │   │   raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'"                                    │
│   138                                                                                                                             │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'model'`

### Version Platform Description

Windows 11, Firefox (both at latest patch level).
Regional Prompter [8d96c92] (latest)
GPU is 4090

10:22:00-037277 INFO     Starting SD.Next
10:22:00-037277 INFO     Python 3.10.6 on Windows
10:22:00-116563 INFO     Version: app=sd.next updated=2023-10-20 hash=d8bb3496
                         url=https://github.com/vladmandic/automatic.git/tree/master
10:22:00-366812 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 183 Stepping 1, GenuineIntel system=Windows
                         release=Windows-10-10.0.22621-SP0 python=3.10.6
10:22:00-366812 INFO     nVidia CUDA toolkit detected: nvidia-smi present

### URL link of the extension

https://github.com/hako-mikan/sd-webui-regional-prompter

### URL link of the issue reported in the extension repository

https://github.com/hako-mikan/sd-webui-regional-prompter/issues/254

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
regional prompter not any extension that works inside the model is not supported by backend:diffusers and can be used with backend:original only. which means that such extensions are right now limited to sd15/21 - all other models supported by sdnext (sdxl, kandinsky, deepfloyd, etc. - many) are not supported.

and feature request to support a1111 style of sdxl implementation already exists, so i'm closing this issue.
