### ISSUE TITLE
[Issue]:  Error when ":" is used in the prompt

### ISSUE THREAD

**Issue by cjps-br** [vladmandic/automatic#2369]
### Issue Description

When I use ":" in the prompt, whether in the format (keyword:1.5) or <lora:0.8>, the image is generated, but it is not saved, only a file with the name, without extension, is generated.

Ex:

prompt -> car, houses
status: image generated and saved with the file name "car, houses.jpg"

prompt -> (car), houses
status: Image generated and saved with the filename "(car), houses.jpg"

prompt -> (car:1.5), houses
status: generated image and saves a file named "(car" and size 0 byte

### Version Platform Description

app: SD.next
updated: 2023-10-18
hash: 231ca1ac
url: https://github.com/vladmandic/automatic/tree/HEAD

arch: AMD64
cpu: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.6

xformers: 
diffusers: 0.21.4
transformers: 4.30.2

device: NVIDIA GeForce GTX 1660 SUPER (1) (sm_90) (7, 5)
cuda: 12.1
cudnn: 8801
driver: 536.19

active: cuda
dtype: torch.float32
vae: torch.float32
unet: torch.float32

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Tillerz** [comment]
I think that is a problem with the "prompt" being added to the filename, at least the front part of it. Do you actually NEED that? I have shortened my filenames dramatically in the settings.

![image](https://github.com/vladmandic/automatic/assets/63370525/e87c3df8-edcd-4220-ace1-75bd3a98a3d6)

**Comment by Woisek** [comment]
1. It's not really a good idea to use prompts as a filename. Too long, too complex and you never get them as a whole. It also doesn't make any practical sense.
2. You can't user a : in the filename with the Windows file system, no matter what commit you use.

Maybe you should rethink your naming strategy with leaving prompts completely outside.

**Comment by cjps-br** [comment]
> 1. It's not really a good idea to use prompts as a filename. Too long, too complex and you never get them as a whole. It also doesn't make any practical sense.
> 2. You can't user a : in the filename with the Windows file system, no matter what commit you use.
> 
> Maybe you should rethink your naming strategy with leaving prompts completely outside.

Yes, I understand your points, but I still think that some people may want to use the prompt in the file name and there is no restriction on the developers in doing so. Since version Automatic 1111 it is possible to use, as described in the wiki (https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Custom-Images-Filename-Name-and-Subdirectory)

the "illegal" characters for the operating system were replaced by "_" and it worked perfectly. Filename length is not an issue for me.

**Comment by Woisek** [comment]
Yes, I'm aware of the possibilities and I tried the prompts in the file name too at the beginning of my AI image generating journey. But I learned quickly that it's not feasible to do this. It literally brings absolute no advantage in any form, only problems. If you have a prompt with more then 50 characters, the filename will be cut in Explorer and all you do later is expand and search ... yeah, what for do you search? You also have still the option to save a txt along with every generation, where all the information is in it.
In my opinion and what I do ever since, is just use (for me) important things like seed, steps, cfg and sampler. And rest is in the metadata and If I need them I use the proper tool for it.

**Comment by vladmandic** [comment]
also, while i agree in principle that using `[prompt]` is not great, it should work.
note that i strongly recommend at least using `[prompt_words]` instead as it does prompt cleanup so it actually looks nice, not just safe.

and there were several issues here, invalid filename just tip of the iceberg. bigger one was that sanitize was called at the very end, so what scripts/extensions received was fully unsanitized filename - and that is ancient code, i'm surprised nobody reported issues with that in the past.

anyhow, its fixed.
