### ISSUE TITLE
[Issue]: sd next Colab doesn't start

### ISSUE THREAD

**Issue by MajorGruberth** [vladmandic/automatic#2374]
### Issue Description

The notebook stops after a minute with a FileNotFoundError.  Like: FileNotFoundError: [Errno 2] No such file or directory: 'vladmandic-latest-webui.tar.lz4'

### Version Platform Description

Google COLAB PRO

### Relevant log output

```shell
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-1-1a5e7fb8db76> in <cell line: 302>()
    300     print("All is done! Go to the next step.")
    301 
--> 302 main()

2 frames
<ipython-input-1-1a5e7fb8db76> in pre_download(desc, overwrite)
     97             else:
     98                 get_ipython().system('tar -xI lz4 -f {package_name} {"--overwrite-dir" if overwrite else ""} --directory=/')
---> 99             os.remove(package_name)
    100         del cap
    101 

FileNotFoundError: [Errno 2] No such file or directory: 'vladmandic-latest-webui.tar.lz4'
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
so contact collab author. i'm not even aware of that specific collab nor i have no idea where `vladmandic-latest-webui.tar.lz4` comes from.
