### ISSUE TITLE
[Issue]: WARNING - Likely incompatible Cuda with: xformers

### ISSUE THREAD

**Issue by landrasss** [vladmandic/automatic#2378]
### Issue Description

Trying to use xformers with the latest update, the console gives me the following warning:

`WARNING  Likely incompatible Cuda with: xformers==0.0.23.dev662 installed: torch==2.1.0+cu121 required: torch==2.1.0+cu118 - build xformers manually or downgrade torch`

What would be my best option, to use xformers without breaking the operation of SD.Next.

Thanks in advance.

### Version Platform Description

Starting SD.Next
Python 3.10.6 on Windows
Version: app=sd.next updated=2023-10-21 hash=2f1f9974
                         url=https://github.com/vladmandic/automatic/tree/master
Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19044-SP0 python=3.10.6
nVidia CUDA toolkit detected: nvidia-smi present

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by bulvinkln** [comment]
I have same issue

**Comment by bulvinkln** [comment]
Change setting: System - Cross-attention optimization method - Scaled-Dot-Product (fresh installation use that)

**Comment by vladmandic** [comment]
a) don't use xformers and use sdp
b) build xformers from source
c) install torch that is supported by xformers.

i might provide more detailed steps if this was asked as a question in discussions or discord instead of creating an issue when it clearly is not a product issue and even message is clear.
