### ISSUE TITLE
[Issue]: Out of gpu memory after the first successful generation

### ISSUE THREAD

**Issue by Dachiko** [vladmandic/automatic#2381]
### Issue Description

Something isn't cleared from the GPU memory, because the very first batch (2 images in the batch) + highres fix goes fine, but the second run (same prompt and settings) requires more GPU memory.

see log output

Checkpoint is Zavichromaxl (sdxl based). Even at 1 image per batch it goes beyond 16gb vram on the second and later attempts. I'm using default SD.Next installation using Stability Matrix installer, no extensions added.

### Version Platform Description

12:12:09-808988 INFO     Starting SD.Next                                      
12:12:09-810988 INFO     Python 3.10.11 on Windows                             
12:12:09-909395 INFO     Version: app=sd.next updated=2023-10-22 hash=0288106a 
                         url=https://github.com/vladmandic/automatic/tree/maste
                         r                                                     
12:12:10-524911 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 183   
                         Stepping 1, GenuineIntel system=Windows               
                         release=Windows-10-10.0.22621-SP0 python=3.10.11      
12:12:10-526911 INFO     nVidia CUDA toolkit detected: nvidia-smi present

12:12:35-365237 INFO     Device: device=NVIDIA GeForce RTX 4090 Laptop GPU n=1 
                         arch=compute_37 cap=(8, 9) cuda=11.8 cudnn=8700       
                         driver=545.84     

### Relevant log output

```shell
Progress  2.07it/s #################################12:15:54-068794 INFO     Hires: upscaler=Nearest width=2016 height=1152        
                         images=2                                              
Progress  1.77it/s ################################# 100% 25/25 00:14 00:00 Base
**Progress  1.35s/it** ################################ 100% 20/20 00:27 00:00 Hires
12:16:48-417865 INFO     GPU high memory utilization: 91% {'ram': {'used':     
                         1.74, 'total': 31.63}, 'gpu': {'used': 14.55, 'total':
                         15.99}, 'retries': 0, 'oom': 0}                       
12:16:48-953361 INFO     Processed: images=2 time=70.38s its=0.71              
                         memory={'ram': {'used': 1.75, 'total': 31.63}, 'gpu': 
                         {'used': 8.21, 'total': 15.99}, 'retries': 0, 'oom':  
                         0}                                                    
Progress  2.03it/s ################################# 100% 25/25 00:12 00:00 Base
12:17:02-468905 INFO     Hires: upscaler=Nearest width=2016 height=1152        
                         images=2                                              
**Progress 22.91s/it** ####9                            12:18:42-726667 INFO     Interrupted...                                        
  15% 3/20 01:08 06:29 Hires
```

### Backend

Original

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
torch memory deallocation is always opptunistic by torch design.
you can try setting lower threshold for garbage collect in settings (default is 90%) so its forced more often, but that's about it. 
on linux you can try different memory allocators such as tcmalloc that do help, but on windows there is no such thing - memory handler is os itself. there really isn't anything that i can do here.

and yes, i've confirmed several times there are no actual memory leaks, its just how torch+python+windows opportunistically handle memory deallocation requests.
