### ISSUE TITLE
[Issue]: Missing button for prompt save?

### ISSUE THREAD

**Issue by ktee95** [vladmandic/automatic#2394]
### Issue Description

I just updated the package today and realized there are many changes to the interface.
This change is a bit inconvenient as the row of buttons that help copy and save the prompt has disappeared.
![image](https://github.com/vladmandic/automatic/assets/134923766/da56f26f-f040-4459-9d71-4f915264bf5e)

I wonder how to get them back to the original were, I use them so often.
![image](https://github.com/vladmandic/automatic/assets/134923766/8c1dc18a-c821-4351-9dc9-58879ffa32ac)

### Version Platform Description

app: SD.next
updated: 2023-10-24
hash: b834e3ad
url: https://github.com/vladmandic/automatic/tree/master

Platform:
arch: AMD64
cpu: Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.10.11

GPU: 
device: NVIDIA GeForce RTX 3060 (1) (compute_37) (8, 6)
cuda: 11.8
cudnn: 8700
driver: 545.84

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
It's in the Style tab of Networks.

**Comment by pro-krastinator** [comment]
I guess it is closed too early. I guess OP was talking about the button for pasting generation data from civitai, which I am miss as well:

![зображення](https://github.com/vladmandic/automatic/assets/55561129/ed6af6d9-1c82-4e05-bc9f-f7b733cbd8df)
![зображення](https://github.com/vladmandic/automatic/assets/55561129/10a2c371-1b2f-43a9-a052-e223b4b93eaf)

**Comment by vladmandic** [comment]
that button is not sdnext button, that is created by extension and not something i'm going to look at why its there or not there.

**Comment by pro-krastinator** [comment]
> that button is not sdnext button, that is created by extension and not something i'm going to look at why its there or not there.

Yes, you are correct, that button provided by the well-known extensaion [sd-webui-prompt-all-in-one](https://github.com/Physton/sd-webui-prompt-all-in-one). It was working in october though... :) And currently working in a1111. 
Anyway, thank you for your attention!

**Comment by vladmandic** [comment]
perhaps it would be easy to support it, but i cannot verify every single extension that modifies standard parts of ui. that extension already has a rich ui of its own in the prompt area, that button should likely be there.
