### ISSUE TITLE
[Issue]: Unidiffuser updated

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#2398]
### Issue Description

There was an update to Unidiffuser 20 days ago, something about changing the image_processor, which is what shows up as missing when installing with our Models/huggingface tab. Currently this leaves Unidiffuser non-functional.

https://huggingface.co/thu-ml/unidiffuser-v1/commits/main

### Backend

Diffusers

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
working.
