### ISSUE TITLE
[Issue]: (When using integrated ControlNet with Deforum) ControlNet Error: No ControlNet Unit detected in args. 

### ISSUE THREAD

**Issue by ZDOSt** [vladmandic/automatic#2399]
### Issue Description

This error has been popping up when using ControlNet with Deforum. 

-Only happens in SD-Next
-This error does NOT happen with Automatic1111 

Could the integrated ControlNet in SD-Next have issues? 

Here is the error as it shows up in the terminal:

No ControlNet unit detected in args. It is very likely that you are having an extension conflict. Here are args received by ControlNet: [.] 

Things I've tried:

Disabled all extensions except Deforum and ControlNet

Reinstalled SD-Next + all dependencies. 

Removed all files related to Stable Diffusion, uninstalled Python, Git, everything. And reinstalled everything from scratch.

If there is a way to get a more detailed report, let me know and I'll post it here.

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
duplicate #2301
