### ISSUE TITLE
[Feature]: Fix progress percentage and show both batch and job %

### ISSUE THREAD

**Issue by nCoderGit** [vladmandic/automatic#2402]
### Feature description

I noticed that the progress percentage (as shown in the browser tab title and on the generate button) has changed its behavior:

A few commits before, it would show the progress of the whole job.
Now, as of version hash 11834888, the percentage counts from 0 to 100% for every single batch, and there is no feedback anymore as to how far the whole job has computed so far.

I suppose the new behavior is unintended / a regression, but wouldn't it be nice to actually show both batch and job progress?

Kinda like this on the generate button split in half:
```
|▬▬▬--| with text overlay:  60% -  2s left   ← batch
|▬----| with text overlay:  10% - 30s left   ← job 
```

And for the browser tab a shortened version like `SD.Next: 60% / 10% - 30s left`, or just job percentage like a few commits ago?

### Version Platform Description

23:24:30-390942 INFO     Starting SD.Next
23:24:30-390942 INFO     Python 3.10.6 on Windows
23:24:30-575798 INFO     Version: app=sd.next updated=2023-10-24 hash=11834888 url=https://github.com/vladmandic/automatic/tree/master
23:24:31-092426 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 94 Stepping 3, GenuineIntel system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6
23:24:31-114590 INFO     nVidia CUDA toolkit detected: nvidia-smi present

**Comment by vladmandic** [comment]
i've completely redesigned job monitoring and progress bar in dev branch, will be likely merged to master next week.
