### ISSUE TITLE
[Extension]: sd-webui-animatediff

### ISSUE THREAD

**Issue by Nyx01** [vladmandic/automatic#2408]
### Issue Description

I've been getting an error with the current build of animatediff in the newest version they pushed today.

[message.txt](https://github.com/vladmandic/automatic/files/13171716/message.txt)

The version from the 12st of animatediff works (1.9.4), but today's update (1.10.0) broke something.

### Version Platform Description

17:52:48-537562 INFO     Starting SD.Next
17:52:48-542547 INFO     Python 3.10.11 on Windows
17:52:48-674195 INFO     Version: app=sd.next updated=2023-10-24 hash=11834888
                         url=https://github.com/vladmandic/automatic/tree/master

### URL link of the extension

https://github.com/continue-revolution/sd-webui-animatediff

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by StableInfo** [comment]
You have to make one at their repo aswell I believe:
**URL link of the issue reported in the extension repository**

**Comment by vladmandic** [comment]
added missing function.

**Comment by bluebirdx0int** [comment]
Still seeing these sorts of errors on latest version of [animatediff](https://github.com/continue-revolution/sd-webui-animatediff) v1.11.0
[log.txt](https://github.com/vladmandic/automatic/files/13255085/log.txt)
I'm on latest version of SD.Next, python 3.10.13 on Linux

**Comment by vladmandic** [comment]
> I'm on latest version of SD.Next

Post what that means.
And i've added function in dev branch which will be merged to master shortly. If you're on master (which i have no idea), this is expected - again, that's why version is always required.

**Comment by bluebirdx0int** [comment]
Didn't realize the fix was not on master yet, I'm on master

**Comment by vladmandic** [comment]
i should have noted it when i closed the issue, i normally do.
