### ISSUE TITLE
[Issue]: Bat files crash/close immediately after being opened. Any Help Would be appreciated.

### ISSUE THREAD

**Issue by StableInfo** [vladmandic/automatic#2409]
### Issue Description

I did not use sd.next or any other sd webUI for a long time, I tried other forms of AI techs, that required me to install new and older versions of python, to play with the path values, and to make multiple ENVS manually or through miniconda.

-  I wanted to come back to sd.next only to notice that the bat file is no longer working.
- I did not think much of it at the time, only to try recently by simply making a new installation (I cloned the repo inside a new folder then went to the terminal and wrote webui.bat --debug, the window opened and closed immedialty, I tried manually by clicking on the webui.bat files direclty and it did the same thing.

I have learned to understand (a bit) the bat files format, I learned about "echo" and tried to use it to know where the problems lies, so I inserted it everywhere to evalute things, here is the modified bat file containing echos:

```
@echo off

if not defined PYTHON (set PYTHON=python)
if not defined VENV_DIR (set "VENV_DIR=%~dp0%venv")
set ERROR_REPORTING=FALSE
mkdir tmp 2>NUL

echo 1

%PYTHON% -c "" >tmp/stdout.txt 2>tmp/stderr.txt
echo 1a
if %ERRORLEVEL% == 0 goto :check_pip
echo 1b
echo Cannot launch python
echo 1c
goto :show_stdout_stderr

echo 2

:check_pip
%PYTHON% -mpip --help >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :start_venv
if "%PIP_INSTALLER_LOCATION%" == "" goto :show_stdout_stderr
%PYTHON% "%PIP_INSTALLER_LOCATION%" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :start_venv
echo Cannot install pip
goto :show_stdout_stderr

echo 3

:start_venv
if ["%VENV_DIR%"] == ["-"] goto :skip_venv
if ["%SKIP_VENV%"] == ["1"] goto :skip_venv

echo 4

dir "%VENV_DIR%\Scripts\Python.exe" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :activate_venv

echo 5

for /f "delims=" %%i in ('CALL %PYTHON% -c "import sys; print(sys.executable)"') do set PYTHON_FULLNAME="%%i"
echo Using python: %PYTHON_FULLNAME%
echo Creating VENV: %VENV_DIR%
%PYTHON_FULLNAME% -m venv "%VENV_DIR%" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :activate_venv
echo Failed creating VENV: "%VENV_DIR%"
goto :show_stdout_stderr

echo 6

:activate_venv
set PYTHON="%VENV_DIR%\Scripts\Python.exe"
echo Using VENV: %VENV_DIR%

echo 7

:skip_venv
if [%ACCELERATE%] == ["True"] goto :accelerate
goto :launch

echo 8

:accelerate
set ACCELERATE="%VENV_DIR%\Scripts\accelerate.exe"
if EXIST %ACCELERATE% goto :accelerate_launch

echo 9

:launch
%PYTHON% launch.py %*
pause
exit /b

echo 10

:accelerate_launch
echo Using accelerate
%ACCELERATE% launch --num_cpu_threads_per_process=6 launch.py %*
pause
exit /b

echo 11

:show_stdout_stderr

echo.
echo exit code: %errorlevel%

echo 12

for /f %%i in ("tmp\stdout.txt") do set size=%%~zi
if %size% equ 0 goto :show_stderr
echo.
echo stdout:
type tmp\stdout.txt

echo 13

:show_stderr
for /f %%i in ("tmp\stderr.txt") do set size=%%~zi
if %size% equ 0 goto :show_stderr
echo.
echo stderr:
type tmp\stderr.txt

echo 14

:endofscript

echo.
echo Launch Failed
pause

echo 15
```

I launched it again and Noticed that only the output "1" was echoed.
I added the echo 1a, 1b and 1c lines to see where precisely the program stops working. None were outputed.
It seems my bat file stops working at: (%PYTHON% -c "" >tmp/stdout.txt 2>tmp/stderr.txt)
__
I think I might find the solution myself, but this issue could help others. 
Here is what I noticed:
My GLOBAL PATH, contains links to a python related to another user in the machine.
However the actual user has no python link in the PATH. 
(In windows, you have 2 types of env variables aka PATH, one global and the other for the actual user of the machine)

I reinstalled python but it did not solve it, I will retry by selecting adding to path, to see how it goes out. I hope it does not break my other python projects.

### Version Platform Description

Windows.
SD.next v: irrelevant.

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by StableInfo** [comment]
Actually I went ahead and reinstalled python and checked 'add to path', I dont see any change in the "modify variables" menu BUT the bat file has a new output now:
```
C:\Users\stable\Desktop\NewSDNEXTVlad\automatic>webui.bat --debug
1
1a
4
Using VENV: C:\Users\stable\Desktop\NewSDNEXTVlad\automatic\venv
7
Traceback (most recent call last):
  File "C:\Users\stable\Desktop\NewSDNEXTVlad\automatic\launch.py", line 8, in <module>
    import installer
  File "C:\Users\stable\Desktop\NewSDNEXTVlad\automatic\installer.py", line 12, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Press any key to continue...
```

**Comment by vladmandic** [comment]
original error is basically python not even starting.
then you've reinstalled python.
but if you change/reinstall python, you need to delete `venv` and restart shell or it will use cached version of python and result in exact error you're seeing.

**Comment by StableInfo** [comment]
Dont close it please, it still not working.
I just deleted the venv folder and re opened the bat file:
```
1
1a
4
5
Using python: "C:\Users\Stable\AppData\Local\Programs\Python\Python312\python.exe"
Creating VENV: C:\Users\Stable\Desktop\NewSDNEXTVlad\automatic\venv
Using VENV: C:\Users\Stable\Desktop\NewSDNEXTVlad\automatic\venv
7
Traceback (most recent call last):
  File "C:\Users\Stable\Desktop\NewSDNEXTVlad\automatic\launch.py", line 8, in <module>
    import installer
  File "C:\Users\Stable\Desktop\NewSDNEXTVlad\automatic\installer.py", line 12, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Press any key to continue......
```

**Comment by vladmandic** [comment]
that is still a broken python - adding echo statements to webui.bat doesn't change that.
fyi, `pkg_resources` is a system package inside python itself.

**Comment by StableInfo** [comment]
I even recloned from 0 with a fresh installation:
```
C:\Users\Stable\Desktop\newnewSDNEXT\automatic>webui.bat --debug
Using python: "C:\Users\Stable\AppData\Local\Programs\Python\Python312\python.exe"
Creating VENV: C:\Users\Stable\Desktop\newnewSDNEXT\automatic\venv
Using VENV: C:\Users\Stable\Desktop\newnewSDNEXT\automatic\venv
Traceback (most recent call last):
  File "C:\Users\Stable\Desktop\newnewSDNEXT\automatic\launch.py", line 8, in <module>
    import installer
  File "C:\Users\Stable\Desktop\newnewSDNEXT\automatic\installer.py", line 12, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
Press any key to continue...
```..

**Comment by StableInfo** [comment]
Ok fixed it, I deletec venv again, and installed python 3.11.5 and added it to PATH.
Thanks
