### ISSUE TITLE
[Issue]: The "Add number to filename when saving" option breaks saving images after updating 11834888..480f4fd8

### ISSUE THREAD

**Issue by r7vz9h3** [vladmandic/automatic#2412]
### Issue Description

After a 11834888..480f4fd8 git pull fast-forward no images get saved because WebUI wants to save to a non-existent `00000-outputs\` folder if the "Add number to filename when saving" option is on:
```
14:54:21-855225 WARNING  Image save failed: 00000-outputs\text\2023-10-26\20231026145408-1.jpg [Errno 2] No such file or
                         directory: '00000-outputs\\text\\2023-10-26\\20231026145408-1.jpg'
```
Without that option everything is fine.

I saw there were some changes to `modules/images.py`, the bug could be there somewhere?
https://github.com/vladmandic/automatic/compare/11834888..480f4fd8?diff=split#diff-7035c0b11c034183a4d5570fccaf498d0e1ceea6f1a70efffab2bf963703739aR582

### Version Platform Description

```
14:39:54-018179 INFO     Version: app=sd.next updated=2023-10-26 hash=480f4fd8
                         url=https://github.com/vladmandic/automatic/tree/master
14:39:54-445045 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.22621-SP0 python=3.10.11
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
should be fixed now.
