### ISSUE TITLE
[Issue]: No way to load styles into the positive and negative prompt box now?

### ISSUE THREAD

**Issue by ilikenwf** [vladmandic/automatic#2419]
### Issue Description

It is handy to be able to adjust them in this way, or save variations of them...for that matter, the save style button is gone now too? Can we have these functionalities back please?

![image](https://github.com/vladmandic/automatic/assets/414778/a3f9ef89-4318-4b4d-a6cc-0bb317ba31ab)

### Version Platform Description

d91338b3c75860728d9dcecd018167f1f868d7e4

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
Styles tab in Networks.

**Comment by ilikenwf** [comment]
Styles tab in networks doesn't populate the contents of the style into the negative and positive prompt boxes unless I'm not seeing a button somewhere. Likewise I don't see how to edit it, only it's properties, not the actual prompts.

I searched "style" saw nothing related at a cursory glance.

**Comment by ilikenwf** [comment]
If it is something that's come up before perhaps you could add it to the documentation instead of getting passive aggressive with everyone who mentions it?

**Comment by brknsoul** [comment]
[Update for 2023-10-17](https://github.com/vladmandic/automatic/blob/master/CHANGELOG.md#update-for-2023-10-17)
Styles
save/apply icons moved to extra networks

**Comment by ilikenwf** [comment]
Apply is different from the load of the past - it copied the full content of the positive and negative prompts from the style (all selected styles) into the actual prompt boxes, not a lora style bracketed implementation.

This makes it less useful if one wants to test tweaks to a style before saving it - likewise how does going to the tab in extra networks and clicking add make sense compared to the previous? It would be nice if these aspects of the ui were at least configurable as this change has added 1+ more steps to do things that previously were much faster.

**Comment by vladmandic** [comment]
![image](https://github.com/vladmandic/automatic/assets/57876960/6d52beb1-f76a-4f5a-962e-e6d4d15ac676)

look at marked icon

**Comment by ilikenwf** [comment]
Thanks. Sorry to stir the crap.

**Comment by Vendaciousness** [comment]
> Thanks. Sorry to stir the crap.

You shouldn't apologize, as I had exactly the same problem. I appreciate you putting yourself out there and taking abuse in order to get the facts. Sometimes, using really cool software means dealing with devs treating you like an idiot because you couldn't find the feature where they buried and haven't read the wiki this *week*, I guess. New location is bad and if they had taken a survey, I'm sure it would have backed that up.

**Comment by ilikenwf** [comment]
I'm usually the dev treating other people like idots with the stuff I write, so I just assume it goes both ways, haha.

**Comment by vladmandic** [comment]
> > Thanks. Sorry to stir the crap.
> 
> You shouldn't apologize, as I had exactly the same problem. I appreciate you putting yourself out there and taking abuse in order to get the facts. Sometimes, using really cool software means dealing with devs treating you like an idiot because you couldn't find the feature where they buried and haven't read the wiki this *week*, I guess. New location is bad and if they had taken a survey, I'm sure it would have backed that up.

For sure he has nothing to apologize for, but you should not be that insulting. I'm not paid for this and this kind of stuff is not motivating.

**Comment by ilikenwf** [comment]
@vladmandic is extremely talented and not only has made something that was usable very much more usable and featureful, but he puts up with wiseacres like me, and all the other BS that comes with it. 

I have been part of and even lead a few really large open source communities...they all come with toxic bs, though open source game dev is the most toxic...that said... be nice to devs.

**Comment by brentjohnston** [comment]
> > Thanks. Sorry to stir the crap.
> 
> You shouldn't apologize, as I had exactly the same problem. I appreciate you putting yourself out there and taking abuse in order to get the facts. Sometimes, using really cool software means dealing with devs treating you like an idiot because you couldn't find the feature where they buried and haven't read the wiki this _week_, I guess. New location is bad and if they had taken a survey, I'm sure it would have backed that up.
Thank you for the reminder of the complexities involved in open-source communities. I've been reflecting on my recent experience, and while I understand that managing such projects can be incredibly challenging and thankless at times, communication is a two-way street.

Like the previous commenter mentioned, it can be frustrating when vital information seems buried or outdated, and attempts to seek clarity are met with responses that feel dismissive. This isn't to diminish the incredible effort developers put into their projects, but to emphasize the importance of clear and user-friendly documentation, and a supportive community space where questions are welcomed and addressed constructively.

I've learned a lot through this process, not just about the technical side of things, but also about the dynamics of open-source projects. It's clear that while developers deserve our respect and patience, a collaborative environment also relies on users feeling heard and helped.

I hope we can all continue to work towards improving not just the software we're passionate about but also the communities that form around them. After all, open source isn't just about code; it's about people coming together to create something greater than the sum of its parts. Gn

**Comment by vladmandic** [comment]
Well written!

I'd like to add that contributions are more than welcome - for example, even if someone doesn't write code, he/she can contribute to docs or best practices.
