### ISSUE TITLE
[Issue]: Inpainting throws gradio exception: "ValueError: '0' is not in list"

### ISSUE THREAD

**Issue by V3ntus** [vladmandic/automatic#2422]
### Issue Description

Not sure what special case is causing this, just using inpainting as normal and this will randomly pop up, even after a server restart. Model does not matter, tried with RealisticVision and SD1.5 base, no change. If I need to generate a longer traceback, let me know.
![image](https://github.com/vladmandic/automatic/assets/29584664/52bb6c20-4aba-42bf-a4f1-a558bafbabd3)
![image](https://github.com/vladmandic/automatic/assets/29584664/5784cefa-3d15-4a95-9df5-0cb1cd21eb66)

### Version Platform Description

- `Python 3.10.12 on Linux`
- `Version: app=sd.next updated=2023-10-24 hash=b834e3ad url=https://github.com/vladmandic/automatic/tree/master`
- `Latest published version: e750112612f079dc18b13edb365c79ad1c7eb511`
- `Platform: arch=x86_64 cpu=x86_64 system=Linux release=5.15.0-87-generic python=3.10.12`

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/ventus/automatic/venv/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/ventus/automatic/venv/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/ventus/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1435, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "/home/ventus/automatic/venv/lib/python3.10/site-packages/gradio/blocks.py", line 1245, in preprocess_data
    processed_input.append(block.preprocess(inputs[i]))
  File "/home/ventus/automatic/venv/lib/python3.10/site-packages/gradio/components/radio.py", line 170, in preprocess
    return [value for _, value in self.choices].index(x)
ValueError: '0' is not in list
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by V3ntus** [comment]
Pulled latest e750112612f079dc18b13edb365c79ad1c7eb511  
Will be using it and see if the issue persist

**Comment by vladmandic** [comment]
this is not model or backend error, this type of error is pure ui error - if gradio running on server does not match state of browser.
make sure that browser is not open before you start sdnext and then start it so it loads clean state from server.
other than that, i don't know what to suggest - perhaps clearing browser cache.

and yes, i've tried, i cannot reproduce.

**Comment by V3ntus** [comment]
Makes sense, thank you for the context. I agree that is probably the cause
