### ISSUE TITLE
[Issue]: Specifying the custom path Lora (+LyCORIS) does not work quite correctly.

### ISSUE THREAD

**Issue by D0n-A** [vladmandic/automatic#2423]
### Issue Description

Hello! There is the following small problem: 
01. The repository is installed in the folder: "D:\\AI\\NS02\\";
02. But all models are located in a different folder from a different repository, which already is actually indicated in the settings: "D:\\AI\\NS\\models\\";
03. But when I run the current one, the following appears:
`DEBUG    FS walk error: [WinError 3] The system cannot find the specified path: 'D:\\AI\\NS02\\models\\LyCORIS' D:\AI\NS02\models\LyCORIS`
04. But next:
`DEBUG    Extra networks: page='lora' items=49 subdirs=1 tab=txt2img dirs=['D:\\AI\\NS\\models\\Lora', 'models\\LyCORIS'] time=0.47s`

05. Despite the fact that the interface now uses one “Lora” tab, it’s still either: it’s not enough to select a custom path for the “LyCORIS” folder / or use something else. 

06. At the same time, I’ll note that it would be great if you could manually specify folders with some other models:, for example, "SDUpscale", "deepbooru", "torch_deepdanbooru", "BLIP".

Thank you.

### Version Platform Description:
Chrome 118.0.5993.118 (64x)
Clean install

SD.Next:
Using VENV: D:\AI\NS02\venv
Logger: file=D:\AI\NS02\sdnext.log level=10 size=0 mode=create
Starting SD.Next
Python 3.11.6 on Windows
Version: app=sd.next updated=2023-10-28 hash=e7501126 url=https://github.com/vladmandic/automatic/tree/master
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel system=Windows release=Windows-10-10.0.22631-SP0 python=3.11.6
Setting environment tuning
Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
nVidia CUDA toolkit detected: nvidia-smi present
Repository update time: Sat Oct 28 06:57:28 2023
...
...
Extensions all: []
Extensions enabled: ['clip-interrogator-ext', 'Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg']
Setup complete without errors: 1698594358

### Backend:
Original

### Model:
SD 1.5

### Acknowledgements:
- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
other than the message, what does not work correctly? if i'm mistaken, let me know and i'll reopen.

> DEBUG    FS walk error: [WinError 3] The system cannot find the specified path: 'D:\\AI\\NS02\\models\\LyCORIS' D:\AI\NS02\models\LyCORIS

i was planning to remove that message anyhow as lycoris folder check is purely for older compatibility reasons and if anything is found there, its just added to list of loras.

regarding custom paths for other models, having each individual is getting really cumbersome as there are soo many of them.
easiest is to use custom model root path, so all are relative to that.

**Comment by D0n-A** [comment]
Yes, absolutely, for all existing models on the Internet it would never be possible to register custom paths. I just meant the ability to register them for those extensions that come with the repository, “out of the box,” so to speak. Or, for example, specify a custom “models” folder so that all models are used from there (something like “symbolic link”)

**Comment by vladmandic** [comment]
custom models folder exists pretty much since forever, its a command line flag.
also, a custom data folder which is even higher level as it impacts everything - config, exensions, etc - makes entire sdnext stateless.

but yeah, i should add it to ui.

**Comment by vladmandic** [comment]
fyi, its been added in dev branch
