### ISSUE TITLE
[Issue] DDIM scheduler has model config values overridden

### ISSUE THREAD

**Issue by bghira** [vladmandic/automatic#2424]
https://github.com/vladmandic/automatic/blob/b00abc4c1d16e275422555bf1545dba5d1b2277c/modules/sd_samplers_diffusers.py#L25-L27

These lines are describing that you do not want to override certain values, but for DDIM, they are all currently incorrect, leading to broken results in SD.next.

```py
'DDIM': { 'clip_sample': True, 'set_alpha_to_one': True, 'steps_offset': 0, 'clip_sample_range': 1.0, 'sample_max_value': 1.0, 'timestep_spacing': 'linspace', 'rescale_betas_zero_snr': False },
```

These defaults are making it so that our v-prediction zero-terminal SNR SDXL model does not function correctly.

Here is the scheduler config:

```json
{
 "_class_name": "DDIMScheduler",
 "_diffusers_version": "0.22.0.dev0",
 "beta_end": 0.012,
 "beta_schedule": "scaled_linear",
 "beta_start": 0.00085,
 "clip_sample": false,
 "clip_sample_range": 1.0,
 "dynamic_thresholding_ratio": 0.995,
 "interpolation_type": "linear",
 "num_train_timesteps": 1000,
 "prediction_type": "v_prediction",
 "rescale_betas_zero_snr": true,
 "sample_max_value": 1.0,
 "set_alpha_to_one": false,
 "skip_prk_steps": true,
 "steps_offset": 1,
 "thresholding": false,
 "timestep_spacing": "trailing",
 "trained_betas": null,
 "use_karras_sigmas": false
 }
```

You can find this model for testing on the hub, as `ptx0/vanilla-xltest`

**Comment by bghira** [comment]
to be fair, neither of these schedulers are giving correct results. you might wish to simply use ALL of the model config values instead of overriding with defaults. set alpha to one should be False, or it results in very incorrect outputs.

DDIM:
![image](https://github.com/vladmandic/automatic/assets/59658056/6681c261-95de-4c07-ad65-553a93fab601)

Euler:
![image](https://github.com/vladmandic/automatic/assets/59658056/bce2c798-b19c-4f3d-9f79-6bc3f067bfe4)

**Comment by vladmandic** [comment]
> These defaults are making it so that our v-prediction zero-terminal SNR SDXL model does not function correctly.

which model are you referring to?

> to be fair, neither of these schedulers are giving correct results. you might wish to simply use ALL of the model config values instead of overriding with defaults. set alpha to one should be False, or it results in very incorrect outputs.

I'm not sure where did you see that alpha should be false?
Diffusers have set it to true: <https://github.com/huggingface/diffusers/blob/9135e54e768a59ddcf8ad18818d2ffe69ea3a32a/src/diffusers/schedulers/scheduling_ddim.py#L195>

And my order of applying settings is:
1. apply global (all setting)
2. apply per-scheduler settings
3. apply values from model (if there are any)
4. apply user configuration (if present)

**Comment by bghira** [comment]
alpha to false is from the model config for SDXL 1.0. for whatever reason, that model i indicated isn't correctly having its settings loaded without hacking on the sampler config module.

**Comment by bghira** [comment]
> You can find this model for testing on the hub, as ptx0/vanilla-xltest

or, `ptx0/coco-xltest` - they are two different, concurrently-trained models.

**Comment by vladmandic** [comment]
since you're comfortable with code, i suggest to add some print statements in:
<https://github.com/vladmandic/automatic/blob/b00abc4c1d16e275422555bf1545dba5d1b2277c/modules/sd_samplers_diffusers.py#L75-L84>

that's where model params are read and applied.

**Comment by bghira** [comment]
Nope, I'm driving a few thousand miles and have no time to get around to this. The model doesn't work still, as far as I know. It has been released now, so, you are able to run this locally yourself. Try `ptx0/terminus-xl-gamma-v1` in the UI.

**Comment by vladmandic** [comment]
i've confirmed with other models that model defaults are loading correctly. other than that, update when you can, i cannot troubleshoot each individual model separately.

**Comment by bghira** [comment]
it's fine, i don't use it anyway. i think now that ComfyUI fixed the same issues, people will just use that instead. do whatever you want to the issue. fix it or don't, it doesn't matter to me
