### ISSUE TITLE
[Issue]: Preview and final images look too small in the UI

### ISSUE THREAD

**Issue by Panchovix** [vladmandic/automatic#2437]
### Issue Description

Thanks for all the hard work. Just git cloned without installing any extension, and when generating, both the preview and final images look too small. The log is from the first run.

It seems to be using a smaller version of the image size. Is there a way to fit the available space?

When viewing the livepreview
![image](https://github.com/vladmandic/automatic/assets/19153797/bc7db3c7-d54d-4547-bffa-9159881a475b)

Final image
![image](https://github.com/vladmandic/automatic/assets/19153797/45cbc22b-87ae-428d-81f6-5698f722f808)

### Version Platform Description

I'm using a 2560x1440 screen, Windows 11 and Google Chrome.

### Relevant log output

```shell
Creating VENV: G:\Stable difussion\nexttest\venv
Using VENV: G:\Stable difussion\nexttest\venv
01:14:05-128729 INFO     Starting SD.Next
01:14:05-130729 INFO     Python 3.10.11 on Windows
01:14:05-254030 INFO     Version: app=sd.next updated=2023-11-03 hash=dc79cec1
                         url=https://github.com/vladmandic/automatic.git/tree/master
01:14:05-291887 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
01:14:05-295884 INFO     nVidia CUDA toolkit detected: nvidia-smi present
01:14:05-296886 INFO     Installing package: torch torchvision --index-url https://download.pytorch.org/whl/cu121
01:15:33-736443 INFO     Verifying requirements
01:15:33-739442 INFO     Installing package: addict
01:15:34-352065 INFO     Installing package: aenum
01:15:35-055067 INFO     Installing package: aiohttp
01:15:37-388361 INFO     Installing package: anyio
01:15:38-623590 INFO     Installing package: appdirs
01:15:39-338492 INFO     Installing package: astunparse
01:15:40-335583 INFO     Installing package: blendmodes
01:15:42-021185 INFO     Installing package: clean-fid
01:15:48-611612 INFO     Installing package: easydev
01:15:50-772785 INFO     Installing package: extcolors
01:15:51-557201 INFO     Installing package: facexlib
01:16:03-366902 INFO     Installing package: filetype
01:16:04-256937 INFO     Installing package: future
01:16:08-519865 INFO     Installing package: gdown
01:16:09-840550 INFO     Installing package: gfpgan
01:16:24-830524 INFO     Installing package: GitPython
01:16:26-465902 INFO     Installing package: httpcore
01:16:27-550259 INFO     Installing package: inflection
01:16:28-431258 INFO     Installing package: jsonmerge
01:16:29-806122 INFO     Installing package: kornia
01:16:32-379719 INFO     Installing package: lark
01:16:33-459323 INFO     Installing package: lmdb
01:16:34-209938 INFO     Installing package: lpips
01:16:35-119813 INFO     Installing package: omegaconf
01:16:37-536956 INFO     Installing package: open-clip-torch
01:16:42-309260 INFO     Installing package: opencv-contrib-python-headless
01:16:43-777900 INFO     Installing package: piexif
01:16:44-660757 INFO     Installing package: psutil
01:16:45-726461 INFO     Installing package: pyyaml
01:16:46-521000 INFO     Installing package: resize-right
01:16:47-451277 INFO     Installing package: rich
01:16:48-278548 INFO     Installing package: safetensors
01:16:49-107941 INFO     Installing package: scipy
01:16:49-952631 INFO     Installing package: tb_nightly
01:16:50-930826 INFO     Installing package: toml
01:16:51-790415 INFO     Installing package: torchdiffeq
01:16:52-814311 INFO     Installing package: voluptuous
01:16:53-795468 INFO     Installing package: yapf
01:16:54-611489 INFO     Installing package: scikit-image
01:16:55-487621 INFO     Installing package: basicsr
01:16:56-344120 INFO     Installing package: fasteners
01:16:57-201222 INFO     Installing package: dctorch
01:16:58-194737 INFO     Installing package: compel==2.0.2
01:17:11-271594 INFO     Installing package: torchsde==0.2.6
01:17:12-805951 INFO     Installing package: antlr4-python3-runtime==4.9.3
01:17:13-899945 INFO     Installing package: requests==2.31.0
01:17:15-174437 INFO     Installing package: tqdm==4.66.1
01:17:16-248123 INFO     Installing package: accelerate==0.20.3
01:17:17-757424 INFO     Installing package: opencv-python-headless==4.7.0.72
01:17:19-323429 INFO     Installing package: diffusers==0.21.4
01:17:20-512648 INFO     Installing package: einops==0.4.1
01:17:21-927603 INFO     Installing package: gradio==3.43.2
01:17:37-481152 INFO     Installing package: huggingface_hub==0.17.1
01:17:39-319184 INFO     Installing package: numexpr==2.8.4
01:17:40-832829 INFO     Installing package: numpy==1.24.4
01:17:46-234560 INFO     Installing package: numba==0.57.1
01:18:01-169281 INFO     Installing package: pandas==1.5.3
01:18:10-886249 INFO     Installing package: protobuf==3.20.3
01:18:12-549934 INFO     Installing package: pytorch_lightning==1.9.4
01:18:16-970810 INFO     Installing package: transformers==4.30.2
01:18:28-150834 INFO     Installing package: tomesd==0.1.3
01:18:29-478933 INFO     Installing package: urllib3==1.26.15
01:18:30-980031 INFO     Installing package: Pillow==9.5.0
01:18:32-902738 INFO     Installing package: timm==0.9.7
01:18:35-575385 INFO     Installing package: pydantic==1.10.13
01:18:37-106746 INFO     Installing package: typing-extensions==4.8.0
01:18:38-322646 INFO     Verifying packages
01:18:38-323643 INFO     Installing package: git+https://github.com/openai/CLIP.git
01:18:42-543029 INFO     Installing package:
                         git+https://github.com/patrickvonplaten/invisible-watermark.git@remove_onnxruntime_depedency
01:18:48-139404 INFO     Installing package: onnxruntime==1.15.1
01:18:51-890184 INFO     Installing package: pi-heif
01:18:53-417021 INFO     Installing package: tensorflow==2.13.0
01:19:55-041742 INFO     Verifying repositories
01:19:55-042739 INFO     Cloning repository: https://github.com/Stability-AI/stablediffusion.git
01:19:59-020173 INFO     Cloning repository: https://github.com/CompVis/taming-transformers.git
01:20:15-203540 INFO     Cloning repository: https://github.com/crowsonkb/k-diffusion.git
01:20:16-335111 INFO     Cloning repository: https://github.com/sczhou/CodeFormer.git
01:20:19-061535 INFO     Cloning repository: https://github.com/salesforce/BLIP.git
01:20:20-985860 INFO     Verifying submodules
01:20:50-078387 INFO     Extension installed packages: clip-interrogator-ext ['clip-interrogator==0.6.0']
01:20:54-410783 INFO     Extension installed packages: sd-webui-agent-scheduler ['greenlet==3.0.1',
                         'SQLAlchemy==2.0.23']
01:21:10-630571 INFO     Extension installed packages: sd-webui-controlnet ['pywin32==306', 'lxml==4.9.3',
                         'opencv-contrib-python==4.8.1.78', 'reportlab==4.0.6', 'pycparser==2.21', 'portalocker==2.8.2',
                         'cffi==1.16.0', 'svglib==1.5.1', 'tinycss2==1.2.1', 'mediapipe==0.10.7', 'tabulate==0.9.0',
                         'cssselect2==0.7.0', 'webencodings==0.5.1', 'sounddevice==0.4.6', 'iopath==0.1.9',
                         'yacs==0.1.8', 'fvcore==0.1.5.post20221221']
01:21:12-875066 INFO     Extension installed packages: stable-diffusion-webui-images-browser ['Send2Trash==1.8.2']
01:21:17-176397 INFO     Extension installed packages: stable-diffusion-webui-rembg ['rembg==2.0.52', 'pooch==1.8.0',
                         'PyMatting==1.1.10']
01:21:17-178403 INFO     Extensions enabled: ['clip-interrogator-ext', 'Lora', 'sd-extension-chainner',
                         'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg']
01:21:17-179399 INFO     Verifying requirements
01:21:17-185449 WARNING  Package wrong version: numpy 1.24.3 required 1.24.4
01:21:17-186449 INFO     Installing package: numpy==1.24.4
01:21:22-234993 WARNING  Package wrong version: typing-extensions 4.5.0 required 4.8.0
01:21:22-235994 INFO     Installing package: typing-extensions==4.8.0
01:21:24-281669 INFO     Extension preload: {'extensions-builtin': 0.02, 'extensions': 0.0}
01:21:24-281669 INFO     Command line args: []
01:21:33-998982 INFO     Engine: backend=Backend.ORIGINAL compute=cuda mode=no_grad device=cuda
                         cross-optimization="Scaled-Dot-Product"
01:21:34-089470 INFO     Device: device=NVIDIA GeForce RTX 4090 n=3 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8801
                         driver=546.08
                         546.08
                         546.08
01:21:35-919532 INFO     Create folder=models\Stable-diffusion
01:21:35-920531 INFO     Create folder=models\Diffusers
01:21:35-921531 INFO     Create folder=models\VAE
01:21:35-921531 INFO     Create folder=models\Lora
01:21:35-922530 INFO     Create folder=models\embeddings
01:21:35-924033 INFO     Create folder=models\hypernetworks
01:21:35-925036 INFO     Create folder=outputs\text
01:21:35-925036 INFO     Create folder=outputs\image
01:21:35-926040 INFO     Create folder=outputs\extras
01:21:35-927042 INFO     Create folder=outputs\grids
01:21:35-928039 INFO     Create folder=outputs\save
01:21:35-930042 INFO     Available VAEs: path="models\VAE" items=0
01:21:35-932040 INFO     Available models: path="models\Stable-diffusion" items=0 time=0.00s
Download the default model? (y/N) n
01:22:28-659690 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
01:22:29-086307 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\controlnet.py' Warning:
                         ControlNet failed to load SGM - will use LDM instead.
01:22:29-087309 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\controlnet.py' ControlNet
                         preprocessor location: G:\Stable
                         difussion\nexttest\extensions-builtin\sd-webui-controlnet\annotator\downloads
01:22:29-093820 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\hook.py' Warning: ControlNet
                         failed to load SGM - will use LDM instead.
01:22:29-182072 INFO     Extension:
                         script='extensions-builtin\stable-diffusion-webui-images-browser\scripts\image_browser.py'
                         Image Browser: Creating database
01:22:29-183072 INFO     Extension:
                         script='extensions-builtin\stable-diffusion-webui-images-browser\scripts\image_browser.py'
                         Image Browser: Database created
01:23:04-440099 INFO     Extensions time: 37.28s { nexttest=0.06s clip-interrogator-ext=0.60s Lora=0.17s
                         sd-extension-chainner=0.25s sd-webui-agent-scheduler=0.38s sd-webui-controlnet=0.45s
                         stable-diffusion-webui-images-browser=0.07s stable-diffusion-webui-rembg=35.26s }
01:23:04-603358 INFO     Upscaler create: folder=models\chaiNNer
01:23:04-608873 INFO     Upscaler create: folder=models\RealESRGAN
01:23:04-692502 INFO     Loading UI theme: name=black-teal style=Auto base=style.css
01:23:06-748046 INFO     Local URL: http://127.0.0.1:7860/
01:23:06-749046 INFO     Initializing middleware
01:23:06-911638 INFO     [AgentScheduler] Task queue is empty
01:23:06-912639 INFO     [AgentScheduler] Registering APIs
01:23:07-008729 ERROR    Cannot generate without a checkpoint
01:23:07-010727 INFO     Set system paths to use existing folders in a different location
01:23:07-011729 INFO     Or use --ckpt <path-to-checkpoint> to force using existing checkpoint
01:23:07-286251 INFO     Startup time: 102.97s { torch=8.05s gradio=0.74s libraries=2.79s extensions=37.28s
                         models=50.35s face-restore=0.88s upscalers=0.17s ui-extra-networks=0.08s ui-img2img=0.06s
                         ui-settings=0.67s ui-extensions=0.70s launch=0.48s api=0.06s app-started=0.20s checkpoint=0.28s
                         }
01:23:32-417470 INFO     MOTD: N/A
01:23:33-791669 INFO     Browser session: client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
01:23:36-279166 INFO     Available models: path="models\Stable-diffusion" items=1 time=0.01s
01:23:37-647416 INFO     Select: model="b64_a2v_creamypesto_test"
Loading weights: G:\Stable difussion\nexttest\models\Stable-diffusion\b64_a2v_creamypesto_test.safetensors ━━━ 0.0… -:-…
                                                                                                               GB
01:23:37-837477 INFO     Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float16 unet=torch.float16
                         context=no_grad fp16=True bf16=False
01:23:38-212030 INFO     LDM: LatentDiffusion: Running in eps-prediction mode
01:23:38-213030 INFO     LDM: DiffusionWrapper has 859.52 M params.
01:23:38-214032 INFO     Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline file="G:\Stable
                         difussion\nexttest\models\Stable-diffusion\b64_a2v_creamypesto_test.safetensors" size=5707MB
Calculating hash: G:\Stable difussion\nexttest\models\Stable-diffusion\b64_a2v_creamypesto_test.safetensors ━━━ 6.… 0:0…
                                                                                                                GB
01:23:53-276618 INFO     Cross-attention: optimization=Scaled-Dot-Product options=[]
01:23:53-600888 INFO     Loaded embeddings: loaded=0 skipped=0 time=0.32s
01:23:53-604891 INFO     Model loaded in 15.96s { load=0.14s config=0.06s create=0.37s apply=8.16s vae=6.33s move=0.56s
                         embeddings=0.32s }
01:23:53-909505 INFO     Model load finished: {'ram': {'used': 7.8, 'total': 63.68}, 'gpu': {'used': 3.61, 'total':
                         23.99}, 'retries': 0, 'oom': 0} cached=0
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  6.58it/s]
01:24:42-390838 INFO     Downloading:
                         url="https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_
                         6B.pth" file=G:\Stable difussion\nexttest\models\RealESRGAN\RealESRGAN_x4plus_anime_6B.pth
Downloading ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
01:24:43-482011 INFO     Upscaler loaded: type=RealESRGAN 4x+ Anime6B model=G:\Stable
                         difussion\nexttest\models\RealESRGAN\RealESRGAN_x4plus_anime_6B.pth
Upscaling ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:01
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.64it/s]
01:24:53-724762 INFO     Processed: images=1 time=16.17s its=1.55 memory={'ram': {'used': 2.63, 'total': 63.68}, 'gpu':
                         {'used': 4.66, 'total': 23.99}, 'retries': 0, 'oom': 0}
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  7.57it/s]
Upscaling ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:01
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
01:25:44-749677 INFO     Processed: images=1 time=14.16s its=1.77 memory={'ram': {'used': 2.66, 'total': 63.68}, 'gpu':
                         {'used': 4.69, 'total': 23.99}, 'retries': 0, 'oom': 0}
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by cyr-chang** [comment]
> ### Issue Description
> Thanks for all the hard work. Just git cloned without installing any extension, and when generating, both the preview and final images look too small. The log is from the first run.
> 
> It seems to be using a smaller version of the image size. Is there a way to fit the available space?
> 
> When viewing the livepreview ![image](https://github.com/vladmandic/automatic/assets/19153797/bc7db3c7-d54d-4547-bffa-9159881a475b)
> 
> Final image ![image](https://github.com/vladmandic/automatic/assets/19153797/45cbc22b-87ae-428d-81f6-5698f722f808)
> 
> ### Version Platform Description
> I'm using a 2560x1440 screen, Windows 11 and Google Chrome.
> 
> ### Relevant log output
> Creating VENV: G:\Stable difussion\nexttest\venv
> Using VENV: G:\Stable difussion\nexttest\venv
> 01:14:05-128729 INFO     Starting SD.Next
> 01:14:05-130729 INFO     Python 3.10.11 on Windows
> 01:14:05-254030 INFO     Version: app=sd.next updated=2023-11-03 hash=dc79cec1
>                          url=https://github.com/vladmandic/automatic.git/tree/master
> 01:14:05-291887 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
>                          release=Windows-10-10.0.22631-SP0 python=3.10.11
> 01:14:05-295884 INFO     nVidia CUDA toolkit detected: nvidia-smi present
> 01:14:05-296886 INFO     Installing package: torch torchvision --index-url https://download.pytorch.org/whl/cu121
> 01:15:33-736443 INFO     Verifying requirements
> 01:15:33-739442 INFO     Installing package: addict
> 01:15:34-352065 INFO     Installing package: aenum
> 01:15:35-055067 INFO     Installing package: aiohttp
> 01:15:37-388361 INFO     Installing package: anyio
> 01:15:38-623590 INFO     Installing package: appdirs
> 01:15:39-338492 INFO     Installing package: astunparse
> 01:15:40-335583 INFO     Installing package: blendmodes
> 01:15:42-021185 INFO     Installing package: clean-fid
> 01:15:48-611612 INFO     Installing package: easydev
> 01:15:50-772785 INFO     Installing package: extcolors
> 01:15:51-557201 INFO     Installing package: facexlib
> 01:16:03-366902 INFO     Installing package: filetype
> 01:16:04-256937 INFO     Installing package: future
> 01:16:08-519865 INFO     Installing package: gdown
> 01:16:09-840550 INFO     Installing package: gfpgan
> 01:16:24-830524 INFO     Installing package: GitPython
> 01:16:26-465902 INFO     Installing package: httpcore
> 01:16:27-550259 INFO     Installing package: inflection
> 01:16:28-431258 INFO     Installing package: jsonmerge
> 01:16:29-806122 INFO     Installing package: kornia
> 01:16:32-379719 INFO     Installing package: lark
> 01:16:33-459323 INFO     Installing package: lmdb
> 01:16:34-209938 INFO     Installing package: lpips
> 01:16:35-119813 INFO     Installing package: omegaconf
> 01:16:37-536956 INFO     Installing package: open-clip-torch
> 01:16:42-309260 INFO     Installing package: opencv-contrib-python-headless
> 01:16:43-777900 INFO     Installing package: piexif
> 01:16:44-660757 INFO     Installing package: psutil
> 01:16:45-726461 INFO     Installing package: pyyaml
> 01:16:46-521000 INFO     Installing package: resize-right
> 01:16:47-451277 INFO     Installing package: rich
> 01:16:48-278548 INFO     Installing package: safetensors
> 01:16:49-107941 INFO     Installing package: scipy
> 01:16:49-952631 INFO     Installing package: tb_nightly
> 01:16:50-930826 INFO     Installing package: toml
> 01:16:51-790415 INFO     Installing package: torchdiffeq
> 01:16:52-814311 INFO     Installing package: voluptuous
> 01:16:53-795468 INFO     Installing package: yapf
> 01:16:54-611489 INFO     Installing package: scikit-image
> 01:16:55-487621 INFO     Installing package: basicsr
> 01:16:56-344120 INFO     Installing package: fasteners
> 01:16:57-201222 INFO     Installing package: dctorch
> 01:16:58-194737 INFO     Installing package: compel==2.0.2
> 01:17:11-271594 INFO     Installing package: torchsde==0.2.6
> 01:17:12-805951 INFO     Installing package: antlr4-python3-runtime==4.9.3
> 01:17:13-899945 INFO     Installing package: requests==2.31.0
> 01:17:15-174437 INFO     Installing package: tqdm==4.66.1
> 01:17:16-248123 INFO     Installing package: accelerate==0.20.3
> 01:17:17-757424 INFO     Installing package: opencv-python-headless==4.7.0.72
> 01:17:19-323429 INFO     Installing package: diffusers==0.21.4
> 01:17:20-512648 INFO     Installing package: einops==0.4.1
> 01:17:21-927603 INFO     Installing package: gradio==3.43.2
> 01:17:37-481152 INFO     Installing package: huggingface_hub==0.17.1
> 01:17:39-319184 INFO     Installing package: numexpr==2.8.4
> 01:17:40-832829 INFO     Installing package: numpy==1.24.4
> 01:17:46-234560 INFO     Installing package: numba==0.57.1
> 01:18:01-169281 INFO     Installing package: pandas==1.5.3
> 01:18:10-886249 INFO     Installing package: protobuf==3.20.3
> 01:18:12-549934 INFO     Installing package: pytorch_lightning==1.9.4
> 01:18:16-970810 INFO     Installing package: transformers==4.30.2
> 01:18:28-150834 INFO     Installing package: tomesd==0.1.3
> 01:18:29-478933 INFO     Installing package: urllib3==1.26.15
> 01:18:30-980031 INFO     Installing package: Pillow==9.5.0
> 01:18:32-902738 INFO     Installing package: timm==0.9.7
> 01:18:35-575385 INFO     Installing package: pydantic==1.10.13
> 01:18:37-106746 INFO     Installing package: typing-extensions==4.8.0
> 01:18:38-322646 INFO     Verifying packages
> 01:18:38-323643 INFO     Installing package: git+https://github.com/openai/CLIP.git
> 01:18:42-543029 INFO     Installing package:
>                          git+https://github.com/patrickvonplaten/invisible-watermark.git@remove_onnxruntime_depedency
> 01:18:48-139404 INFO     Installing package: onnxruntime==1.15.1
> 01:18:51-890184 INFO     Installing package: pi-heif
> 01:18:53-417021 INFO     Installing package: tensorflow==2.13.0
> 01:19:55-041742 INFO     Verifying repositories
> 01:19:55-042739 INFO     Cloning repository: https://github.com/Stability-AI/stablediffusion.git
> 01:19:59-020173 INFO     Cloning repository: https://github.com/CompVis/taming-transformers.git
> 01:20:15-203540 INFO     Cloning repository: https://github.com/crowsonkb/k-diffusion.git
> 01:20:16-335111 INFO     Cloning repository: https://github.com/sczhou/CodeFormer.git
> 01:20:19-061535 INFO     Cloning repository: https://github.com/salesforce/BLIP.git
> 01:20:20-985860 INFO     Verifying submodules
> 01:20:50-078387 INFO     Extension installed packages: clip-interrogator-ext ['clip-interrogator==0.6.0']
> 01:20:54-410783 INFO     Extension installed packages: sd-webui-agent-scheduler ['greenlet==3.0.1',
>                          'SQLAlchemy==2.0.23']
> 01:21:10-630571 INFO     Extension installed packages: sd-webui-controlnet ['pywin32==306', 'lxml==4.9.3',
>                          'opencv-contrib-python==4.8.1.78', 'reportlab==4.0.6', 'pycparser==2.21', 'portalocker==2.8.2',
>                          'cffi==1.16.0', 'svglib==1.5.1', 'tinycss2==1.2.1', 'mediapipe==0.10.7', 'tabulate==0.9.0',
>                          'cssselect2==0.7.0', 'webencodings==0.5.1', 'sounddevice==0.4.6', 'iopath==0.1.9',
>                          'yacs==0.1.8', 'fvcore==0.1.5.post20221221']
> 01:21:12-875066 INFO     Extension installed packages: stable-diffusion-webui-images-browser ['Send2Trash==1.8.2']
> 01:21:17-176397 INFO     Extension installed packages: stable-diffusion-webui-rembg ['rembg==2.0.52', 'pooch==1.8.0',
>                          'PyMatting==1.1.10']
> 01:21:17-178403 INFO     Extensions enabled: ['clip-interrogator-ext', 'Lora', 'sd-extension-chainner',
>                          'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
>                          'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg']
> 01:21:17-179399 INFO     Verifying requirements
> 01:21:17-185449 WARNING  Package wrong version: numpy 1.24.3 required 1.24.4
> 01:21:17-186449 INFO     Installing package: numpy==1.24.4
> 01:21:22-234993 WARNING  Package wrong version: typing-extensions 4.5.0 required 4.8.0
> 01:21:22-235994 INFO     Installing package: typing-extensions==4.8.0
> 01:21:24-281669 INFO     Extension preload: {'extensions-builtin': 0.02, 'extensions': 0.0}
> 01:21:24-281669 INFO     Command line args: []
> 01:21:33-998982 INFO     Engine: backend=Backend.ORIGINAL compute=cuda mode=no_grad device=cuda
>                          cross-optimization="Scaled-Dot-Product"
> 01:21:34-089470 INFO     Device: device=NVIDIA GeForce RTX 4090 n=3 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8801
>                          driver=546.08
>                          546.08
>                          546.08
> 01:21:35-919532 INFO     Create folder=models\Stable-diffusion
> 01:21:35-920531 INFO     Create folder=models\Diffusers
> 01:21:35-921531 INFO     Create folder=models\VAE
> 01:21:35-921531 INFO     Create folder=models\Lora
> 01:21:35-922530 INFO     Create folder=models\embeddings
> 01:21:35-924033 INFO     Create folder=models\hypernetworks
> 01:21:35-925036 INFO     Create folder=outputs\text
> 01:21:35-925036 INFO     Create folder=outputs\image
> 01:21:35-926040 INFO     Create folder=outputs\extras
> 01:21:35-927042 INFO     Create folder=outputs\grids
> 01:21:35-928039 INFO     Create folder=outputs\save
> 01:21:35-930042 INFO     Available VAEs: path="models\VAE" items=0
> 01:21:35-932040 INFO     Available models: path="models\Stable-diffusion" items=0 time=0.00s
> Download the default model? (y/N) n
> 01:22:28-659690 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
>                          sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
> 01:22:29-086307 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\controlnet.py' Warning:
>                          ControlNet failed to load SGM - will use LDM instead.
> 01:22:29-087309 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\controlnet.py' ControlNet
>                          preprocessor location: G:\Stable
>                          difussion\nexttest\extensions-builtin\sd-webui-controlnet\annotator\downloads
> 01:22:29-093820 INFO     Extension: script='extensions-builtin\sd-webui-controlnet\scripts\hook.py' Warning: ControlNet
>                          failed to load SGM - will use LDM instead.
> 01:22:29-182072 INFO     Extension:
>                          script='extensions-builtin\stable-diffusion-webui-images-browser\scripts\image_browser.py'
>                          Image Browser: Creating database
> 01:22:29-183072 INFO     Extension:
>                          script='extensions-builtin\stable-diffusion-webui-images-browser\scripts\image_browser.py'
>                          Image Browser: Database created
> 01:23:04-440099 INFO     Extensions time: 37.28s { nexttest=0.06s clip-interrogator-ext=0.60s Lora=0.17s
>                          sd-extension-chainner=0.25s sd-webui-agent-scheduler=0.38s sd-webui-controlnet=0.45s
>                          stable-diffusion-webui-images-browser=0.07s stable-diffusion-webui-rembg=35.26s }
> 01:23:04-603358 INFO     Upscaler create: folder=models\chaiNNer
> 01:23:04-608873 INFO     Upscaler create: folder=models\RealESRGAN
> 01:23:04-692502 INFO     Loading UI theme: name=black-teal style=Auto base=style.css
> 01:23:06-748046 INFO     Local URL: http://127.0.0.1:7860/
> 01:23:06-749046 INFO     Initializing middleware
> 01:23:06-911638 INFO     [AgentScheduler] Task queue is empty
> 01:23:06-912639 INFO     [AgentScheduler] Registering APIs
> 01:23:07-008729 ERROR    Cannot generate without a checkpoint
> 01:23:07-010727 INFO     Set system paths to use existing folders in a different location
> 01:23:07-011729 INFO     Or use --ckpt <path-to-checkpoint> to force using existing checkpoint
> 01:23:07-286251 INFO     Startup time: 102.97s { torch=8.05s gradio=0.74s libraries=2.79s extensions=37.28s
>                          models=50.35s face-restore=0.88s upscalers=0.17s ui-extra-networks=0.08s ui-img2img=0.06s
>                          ui-settings=0.67s ui-extensions=0.70s launch=0.48s api=0.06s app-started=0.20s checkpoint=0.28s
>                          }
> 01:23:32-417470 INFO     MOTD: N/A
> 01:23:33-791669 INFO     Browser session: client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
>                          AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
> 01:23:36-279166 INFO     Available models: path="models\Stable-diffusion" items=1 time=0.01s
> 01:23:37-647416 INFO     Select: model="b64_a2v_creamypesto_test"
> Loading weights: G:\Stable difussion\nexttest\models\Stable-diffusion\b64_a2v_creamypesto_test.safetensors ━━━ 0.0… -:-…
>                                                                                                                GB
> 01:23:37-837477 INFO     Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float16 unet=torch.float16
>                          context=no_grad fp16=True bf16=False
> 01:23:38-212030 INFO     LDM: LatentDiffusion: Running in eps-prediction mode
> 01:23:38-213030 INFO     LDM: DiffusionWrapper has 859.52 M params.
> 01:23:38-214032 INFO     Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline file="G:\Stable
>                          difussion\nexttest\models\Stable-diffusion\b64_a2v_creamypesto_test.safetensors" size=5707MB
> Calculating hash: G:\Stable difussion\nexttest\models\Stable-diffusion\b64_a2v_creamypesto_test.safetensors ━━━ 6.… 0:0…
>                                                                                                                 GB
> 01:23:53-276618 INFO     Cross-attention: optimization=Scaled-Dot-Product options=[]
> 01:23:53-600888 INFO     Loaded embeddings: loaded=0 skipped=0 time=0.32s
> 01:23:53-604891 INFO     Model loaded in 15.96s { load=0.14s config=0.06s create=0.37s apply=8.16s vae=6.33s move=0.56s
>                          embeddings=0.32s }
> 01:23:53-909505 INFO     Model load finished: {'ram': {'used': 7.8, 'total': 63.68}, 'gpu': {'used': 3.61, 'total':
>                          23.99}, 'retries': 0, 'oom': 0} cached=0
> 100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  6.58it/s]
> 01:24:42-390838 INFO     Downloading:
>                          url="https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGAN_x4plus_anime_
>                          6B.pth" file=G:\Stable difussion\nexttest\models\RealESRGAN\RealESRGAN_x4plus_anime_6B.pth
> Downloading ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:00
> 01:24:43-482011 INFO     Upscaler loaded: type=RealESRGAN 4x+ Anime6B model=G:\Stable
>                          difussion\nexttest\models\RealESRGAN\RealESRGAN_x4plus_anime_6B.pth
> Upscaling ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:01
> 100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:06<00:00,  1.64it/s]
> 01:24:53-724762 INFO     Processed: images=1 time=16.17s its=1.55 memory={'ram': {'used': 2.63, 'total': 63.68}, 'gpu':
>                          {'used': 4.66, 'total': 23.99}, 'retries': 0, 'oom': 0}
> 100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [00:03<00:00,  7.57it/s]
> Upscaling ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:01
> 100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:05<00:00,  1.68it/s]
> 01:25:44-749677 INFO     Processed: images=1 time=14.16s its=1.77 memory={'ram': {'used': 2.66, 'total': 63.68}, 'gpu':
>                          {'used': 4.69, 'total': 23.99}, 'retries': 0, 'oom': 0}
> ### Backend
> Original
> 
> ### Model
> SD 1.5
> 
> ### Acknowledgements
> * [x]  I have read the above and searched for existing issues[x]  I confirm that this is classified correctly and its not an extension issue
