### ISSUE TITLE
[Issue]: SD.Next wrongly reports incompatibility between xformers and torch

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2438]
### Issue Description

The pre-release of xformers which the installer downloads is built for CUDA 12.1, although there's no way to tell from the version number. So, if you have / install pytorch built for CUDA 12.1, SD.Next warns you about an incompatibility that is not actually there.
This it is indeed related to issue #2378 but it's not a user error. 

As shown by the xformers information from the session I'm using (I let SD.Next install xformers):

```
>>> xformers.info.print_info()
xFormers 0.0.23.dev682
memory_efficient_attention.cutlassF:               available
memory_efficient_attention.cutlassB:               available
memory_efficient_attention.decoderF:               available
memory_efficient_attention.flshattF@v2.3.2:        available
memory_efficient_attention.flshattB@v2.3.2:        available
memory_efficient_attention.smallkF:                available
memory_efficient_attention.smallkB:                available
memory_efficient_attention.tritonflashattF:        unavailable
memory_efficient_attention.tritonflashattB:        unavailable
memory_efficient_attention.triton_splitKF:         available
indexing.scaled_index_addF:                        available
indexing.scaled_index_addB:                        available
indexing.index_select:                             available
swiglu.dual_gemm_silu:                             available
swiglu.gemm_fused_operand_sum:                     available
swiglu.fused.p.cpp:                                available
is_triton_available:                               True
pytorch.version:                                   2.1.0+cu121
pytorch.cuda:                                      available
gpu.compute_capability:                            8.6
gpu.name:                                          NVIDIA RTX A4000
build.info:                                        available
build.cuda_version:                                1201
build.python_version:                              3.9.18
build.torch_version:                               2.1.0+cu121
build.env.TORCH_CUDA_ARCH_LIST:                    5.0+PTX 6.0 6.1 7.0 7.5 8.0+PTX 9.0
build.env.XFORMERS_BUILD_TYPE:                     Release
build.env.XFORMERS_ENABLE_DEBUG_ASSERTIONS:        None
build.env.NVCC_FLAGS:                              None
build.env.XFORMERS_PACKAGE_FROM:                   wheel-main
build.nvcc_version:                                12.1.66
source.privacy:                                    open source
```

Thus, using torch built for CUDA 11.8 as suggested by the installer actually causes xformers not to be loaded correctly. 
In fact, if you have torch built for CUDA 11.8, the installer *will* download xformers built for CUDA 12.1 and this will cause some potential breakage (this is how I noticed this). 

### Version Platform Description

Ubuntu 20.04, Paperspace
Python 3.9
Latest SD.next master as of 2023-11-05

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
at the time when message was added, xformers only worked on cuda 11.8 - its been addressed from their side by now, so i'll remove the warning.
