### ISSUE TITLE
[Issue]: Cannot install due to "ownership error" and error running git

### ISSUE THREAD

**Issue by Torcelllo** [vladmandic/automatic#2439]
### Issue Description

Please fill this form with as much information as possible10:50:20-815656 INFO     Starting SD.Next
10:50:20-823664 INFO     Python 3.10.6 on Windows
10:50:21-212018 INFO     Version: app=sd.next version=unknown
10:50:21-606377 ERROR    Error running git: None / rev-parse HEAD
10:50:21-837587 INFO     Latest published version: dc79cec19cbc06ed25f62a74c5fea81d02ebdc61 2023-11-03T07:12:28Z
10:50:21-932674 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6
10:50:21-946687 INFO     nVidia CUDA toolkit detected: nvidia-smi present
10:50:22-329442 ERROR    Error running git: None / status --porcelain
10:50:22-333445 WARNING  Deleted files: ["tal: detected dubious ownership in repository at
                         'C:/TCHT/vladmandic/automatic'", ":/TCHT/vladmandic/automatic' is owned by:", "S-1-5-32-544'",
                         't the current user is:', "S-1-5-21-1194271653-2810682028-2473446000-1001'", 'add an exception
                         for this directory, call:', 'it config --global --add safe.directory
                         C:/TCHT/vladmandic/automatic']
10:50:22-504601 ERROR    Error running git: None / log -1 --pretty=format:"%at"
10:50:22-507604 ERROR    Error getting local repository version: invalid literal for int() with base 10: "fatal:
                         detected dubious ownership in repository at
                         'C:/TCHT/vladmandic/automatic'\n'C:/TCHT/vladmandic/automatic' is owned
                         by:\n\t'S-1-5-32-544'\nbut the current user is:\n\t'S-1-5-21-1194271653-2810
10:50:22-513609 ERROR    Uncaught exception occurred: type=<class 'OSError'> value=[Errno 22] Invalid argument
10:50:22-516612 ERROR    '  File "C:\\TCHT\\vladmandic\\automatic\\launch.py", line 191, in <module>\n    elif
                         installer.check_timestamp():\n'
10:50:22-519614 ERROR    '  File "C:\\TCHT\\vladmandic\\automatic\\installer.py", line 926, in check_timestamp\n
                         log.debug(f\'Repository update time: {time.ctime(int(version_time))}\')\n'
Press any key to continue . . .

### Version Platform Description

Win 10, Chrome, RTX 2070 8Gb VRAM,  64G RAM

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
From the command line, run 
`git config --global --add safe.directory *`

**Comment by vladmandic** [comment]
i'd suggest to find the root cause for ownership error to start with. yes, suggestion from @brknsoul is a valid workaround - but you really want to address the root cause. and it has been discussed several times already, search issues and discussions - it always comes down to how clone was performed to start with.
