### ISSUE TITLE
[Issue]: when adding a style, the styles bar under 'generate' doesn't update and requires a refresh

### ISSUE THREAD

**Issue by maraschouche** [vladmandic/automatic#2449]
### Issue Description

As I brought up on Discord (https://discord.com/channels/1101998836328697867/1165098808397545483) when creating a new style, it doesn't show up in the style search bar under the 'generate' button.  Without a refresh button, you cannot see the styles you create without restarting sd.next

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
No version info means issue is invalid.
Also, latest version of sdnext has a refresh button for that exact control.
