### ISSUE TITLE
[Issue]: LCM Dreamshaper model generation error

### ISSUE THREAD

**Issue by gsgoldma** [vladmandic/automatic#2451]
### Issue Description

error when generating with lcm dreamshaper diffusers model

### Version Platform Description

18:12:56-792938 INFO     Starting SD.Next
18:12:56-802937 INFO     Python 3.10.12 on Windows
18:12:58-171364 INFO     Version: app=sd.next updated=2023-11-06 hash=a2b50b69
                         url=https://github.com/vladmandic/automatic.git/tree/master
18:13:01-268044 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.12
18:13:01-277044 INFO     nVidia CUDA toolkit detected: nvidia-smi present

### Relevant log output

```shell
18:22:25-743156 INFO     Select: model="Diffusers\SimianLuo/LCM_Dreamshaper_v7 [models\Dif]"
18:22:25-799154 INFO     Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float16 unet=torch.float16
                         context=no_grad fp16=True bf16=False
Loading pipeline components...: 100%|████████████████████████████████████████████████████| 6/6 [01:17<00:00, 12.87s/it]
18:23:44-014659 WARNING  Disabling model "Move model to CPU" since "Model CPU offload" is enabled
19:31:09-916156 INFO     Load embeddings: loaded=562 skipped=132 time=4045.88
19:31:10-604161 ERROR    executing callback: D:\automatic\scripts\clipconcantentation.py model_loaded_callback:
                         AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\script_callbacks.py:173 in model_loaded_callback                                               │
│                                                                                                                     │
│   172 │   │   │   t0 = time.time()                                                                                  │
│ > 173 │   │   │   c.callback(sd_model)                                                                              │
│   174 │   │   │   timer(t0, c.script, 'model_loaded')                                                               │
│                                                                                                                     │
│ D:\automatic\scripts\clipconcantentation.py:40 in on_model_loaded                                                   │
│                                                                                                                     │
│    39 def on_model_loaded(sd_model):                                                                                │
│ >  40 │   clip_blend.process_tokens = sd_model.cond_stage_model.process_tokens                                      │
│    41 │   sd_model.cond_stage_model.process_tokens = clip_blend                                                     │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\diffusers\configuration_utils.py:137 in __getattr__                             │
│                                                                                                                     │
│   136 │   │                                                                                                         │
│ > 137 │   │   raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'"                      │
│   138                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'LatentConsistencyModelPipeline' object has no attribute 'cond_stage_model'
```

### Backend

Diffusers

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
issue is caused by `scripts\clipconcantentation.py` and that is not an SDNext file.

**Comment by gsgoldma** [comment]
Not sure if I should make a new error report because it's still related to LCM. I deleted the scripts file and the pipeline loads (like it did sometimes before even with the script) and it gives me this error:

01:48:58-352188 ERROR    Exception: "LayerNormKernelImpl" not implemented for 'Half'
01:48:58-355187 ERROR    Arguments: args=('task(mlw1rl2fvwewmz0)', '', '', [], 3, None, None, True, False, False, 1, 1,
                         6, 6, 0.7, 1, -1.0, -1.0, 0, 0, 0, 512, 512, False, 0.5, 2, 'None', False, 20, 0, 0, 5, 0.8,
                         '', '', [], 0, False, '', True, False, 0, 384, 0, True, True, True, 1, '\n
                         <h3><strong>Combinations</strong></h3>\n            Choose a number of terms from a list, in
                         this case we choose two artists\n            <code>{2$$artist1|artist2|artist3}</code>\n
                         If $$ is not provided, then 1$$ is assumed.\n            <br/><br/>\n\n
                         <h3><strong>Wildcards</strong></h3>\n            <p>Available wildcards</p>\n
                         <ul>\n        </ul>\n            <br/>\n            <code>WILDCARD_DIR:
                         scripts/wildcards</code><br/>\n            <small>You can add more wildcards by creating a
                         text file with one term per line and name is mywildcards.txt. Place it in scripts/wildcards.
                         <code>__mywildcards__</code> will then become available.</small>\n        ', None, '',
                         'outputs', 1, '', 0, '', True, False, False, False, False, False, 1, 1, False, True, False,
                         '', 1, True, 100, True, 50, 8, True, 16, 'Median cut', 8, True, True, 16, 'PNN', True, False,
                         None, None, '', '', '', '', 'Auto rename', {'label': 'Upload avatars config'}, 'Open outputs
                         directory', 'Export to WebUI style', True, {'label': 'Presets'}, {'label': 'QC preview'}, '',
                         [], 'Select', 'QC scan', 'Show pics', None, False, False, 'positive', 'comma', 0, '', 25,
                         True, 5.0, False, False, '', '', '', '', 0.0, 'mizuni-concept-v1', 1.0, 0, 'Median cut',
                         'luminance', False, 'svg', True, True, False, 0.5, 0, '', [], 0, '', [], 0, '', [], False,
                         True, False, False, False, False, 0, False, 4.0, '', 10.0, 'Linear', 3, False, 30.0, True,
                         False, False, 0, 0.0, 'Lanczos', 1, True, 0, 0, 0.001, 75, 0.0, False, True, False, 7, 100,
                         'Constant', 0, 'Constant', 0, 4, True, 'MEAN', 'AD', 1, False, 'x264', 'blend', 10, 0, 0,
                         False, True, True, True, 'intermediate', 'animation') kwargs={}
01:48:58-511187 ERROR    gradio call: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\call_queue.py:34 in f                                                                          │
│                                                                                                                     │
│   33 │   │   │   try:                                                                                               │
│ > 34 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│   35 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                     │
│ D:\automatic\modules\txt2img.py:66 in txt2img                                                                       │
│                                                                                                                     │
│   65 │   if processed is None:                                                                                      │
│ > 66 │   │   processed = processing.process_images(p)                                                               │
│   67 │   p.close()                                                                                                  │
│                                                                                                                     │
│ D:\automatic\modules\processing.py:712 in process_images                                                            │
│                                                                                                                     │
│    711 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p):                                        │
│ >  712 │   │   │   │   res = process_images_inner(p)                                                                │
│    713 │   finally:                                                                                                 │
│                                                                                                                     │
│ D:\automatic\modules\processing.py:859 in process_images_inner                                                      │
│                                                                                                                     │
│    858 │   │   │   │   from modules.processing_diffusers import process_diffusers                                   │
│ >  859 │   │   │   │   x_samples_ddim = process_diffusers(p, p.seeds, p.prompts, p.negative_pro                     │
│    860 │   │   │   else:                                                                                            │
│                                                                                                                     │
│ D:\automatic\modules\processing_diffusers.py:426 in process_diffusers                                               │
│                                                                                                                     │
│   425 │   try:                                                                                                      │
│ > 426 │   │   output = shared.sd_model(**base_args) # pylint: disable=not-callable                                  │
│   427 │   except AssertionError as e:                                                                               │
│                                                                                                                     │
│                                              ... 14 frames hidden ...                                               │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:385 in forward                        │
│                                                                                                                     │
│    384 │   │                                                                                                        │
│ >  385 │   │   hidden_states = self.layer_norm1(hidden_states)                                                      │
│    386 │   │   hidden_states, attn_weights = self.self_attn(                                                        │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1518 in _wrapped_call_impl                           │
│                                                                                                                     │
│   1517 │   │   else:                                                                                                │
│ > 1518 │   │   │   return self._call_impl(*args, **kwargs)                                                          │
│   1519                                                                                                              │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1527 in _call_impl                                   │
│                                                                                                                     │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                      │
│ > 1527 │   │   │   return forward_call(*args, **kwargs)                                                             │
│   1528                                                                                                              │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\torch\nn\modules\normalization.py:196 in forward                                │
│                                                                                                                     │
│   195 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ > 196 │   │   return F.layer_norm(                                                                                  │
│   197 │   │   │   input, self.normalized_shape, self.weight, self.bias, self.eps)                                   │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\torch\nn\functional.py:2543 in layer_norm                                       │
│                                                                                                                     │
│   2542 │   │   )                                                                                                    │
│ > 2543 │   return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.c                     │
│   2544
