### ISSUE TITLE
[Feature]: Support for Consistency Distilled Diff VAE

### ISSUE THREAD

**Issue by Trojaner** [vladmandic/automatic#2456]
https://github.com/openai/consistencydecoder

**Comment by vladmandic** [comment]
we did a prototype and initial tests have shown:
- quality is actually worse than original in most cases
- its 2.3gb vs 300mb for original
- vram memory requirements are nearly double.

it will be added sooner or later, but right now it looks like a major disappointment and not a priority.

**Comment by vladmandic** [comment]
supported in dev for diffusers backend. no plans to extend support to original backend, primarily since quality is not great and cost is very high.
