### ISSUE TITLE
[Issue]: Pixart black screen

### ISSUE THREAD

**Issue by brentjohnston** [vladmandic/automatic#2460]
### Issue Description

How do we use the pixart model? I have 24gb vram. When I generate with one of the safetensor files I get a black screen. I placed all of the checkpoints in stablediffusion models folder. Not sure if this is correct and can't seem to find any info on the internet anywhere for this.

### Version Platform Description

Windows

### Backend

Original

Pixart model files

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
Do NOT download safetensors manually. Use built in downloader or new reference models list in extra networks. App needs to fetch more stuff than just single safetensors file.

This applies to all non SD models. 

Its documented in changelog.

**Comment by brentjohnston** [comment]
I saw the changelog before, but I went to networks and searched but it doesn't come up. Having a lot of difficulty here.

**Comment by vladmandic** [comment]
if you don't see reference folder in models, you're either nor running latest sdnext or you're not running in diffusers backend.
ANY non-sd15 model requires diffusers backend, not original.
