### ISSUE TITLE
[Issue]: No "reference" under network, huggingface downloader difficult to use

### ISSUE THREAD

**Issue by brentjohnston** [vladmandic/automatic#2462]
### Issue Description

I had seen the changelogs, but I am still trying to download the pixart model. I appreciate the effort here, but this is not very easy. I went to networks tab (labeled networks as opposed to extra networks which I cannot find anywhere) and there is no "reference" button. I git cloned master branch and everything else working with other models. I tried the huggingface downloader but it says to specify the model revision, which I can not find anywhere on huggingface. It does not search for models.

Just some extra note also: I would also recommend specifying in the step-by-step guide where to put the startup commands like --debug, etc. I finally figured it out but it was difficult because the webui.bat is completely different than auto1111. I also don't understand in this case why simply clicking github green "code" button and downloading the zip file like I do with auto1111 and launching the webui.bat doesn't work and you are required to do git clone. Just some additional feedback here to make this the go-to stable diffusion user interface, I see a lot of potential here but the barriers of entry are very high at the moment for newcomers.

### Version Platform Description

Windows

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
use diffusers backend.
and ask question before creating issue that is not an issue. discussions or discord (which has a really good community).

**Comment by brentjohnston** [comment]
Some guy on reddit helped me.. jk. Yeah found it under system after searching. It is an issue though...  because it's not having proper notes or user friendly. What am I supposed to do read all of your code? Anyways Thanks for the discord info, first time I've heard that too. Oh you did provide a link to discord, I see the simple text that says discord on top, I missed key detail. 

Like all it says is discord on the main page, but I should have know to go there. Too bad it doesn't say "if you have any issues it's best to go to discord first" or some level of communication along those lines. Anyways thanks for the work you put into this though.
