### ISSUE TITLE
[Issue]: SD XL not working due to error: "Object has no attribute alphas_cumprod"

### ISSUE THREAD

**Issue by ZomBrony** [vladmandic/automatic#2473]
### Issue Description

I'm attempting to use this app as a total beginner, and I just downloaded SD XL because I thought it sounds cool!

I've done a bunch of custom settings, for clarity's sake, and I'm trying to generate in a batch. But when I try to, the error 'StableDiffusionXLPipeline' object has no attribute 'alphas_cumprod' occurs.

I don't know how much information I can really provide when I know so little, but any extra details you ask for I can include.

### Version Platform Description

19:05:45-585153 INFO     Starting SD.Next
19:05:45-592149 INFO     Python 3.11.4 on Windows
19:05:46-257409 INFO     Version: app=sd.next updated=2023-11-08 hash=3c9c9cf4 url=https://github.com/vladmandic/automatic.git/tree/master
19:05:47-012977 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 60 Stepping 3, GenuineIntel system=Windows release=Windows-10-10.0.19045-SP0 python=3.11.4
19:05:47-024970 INFO     nVidia CUDA toolkit detected: nvidia-smi present
19:05:47-648940 INFO     Extensions: disabled=[]
19:05:47-650939 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
19:05:47-675925 INFO     Extensions: enabled=[] extensions

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
really need actual log to do anything.

**Comment by ZomBrony** [comment]
Yeah.. Sorry about that! After restarting my computer and properly enabling the FP16 VAE model, it seems to be working fine...

Maybe I was getting that error before because I didn't have my VAE setup properly?

**Comment by vladmandic** [comment]
no, that has nothing to do with VAE.

**Comment by vladmandic** [comment]
since issue seems to be resolved, i'll close it - if it reoccurs, post log and i'll reopen.
