### ISSUE TITLE
[Issue]: styles issues (import of styles.csv moves neg to pos prompt and drops pos prompt) and (List view 'info' button doesn't work)

### ISSUE THREAD

**Issue by maraschouche** [vladmandic/automatic#2474]
### Issue Description

copied from this thread on the discord (https://discord.com/channels/1101998836328697867/1165098808397545483)
I have a couple of styles- related issues, vlado-
**1.) import of styles.csv moves neg to pos prompt and drops pos prompt**
 I went and deleted the jsons in models/styles then pointed settings to styles.csv- when it rebuilt all the jsons, it moved the negative prompts into the positive fields and didn't import the positive field.  This led to some horrific gens until I figured it out.  I've done this twice now, same result.
**2.) List view 'info' button doesn't work**
When I look at the styles on the network pane in *list view* and want to edit one of them, clicking the icon of a circle with an 'i' in the middle doesn't work.  I have to cycle back to normal view.  I've tried both the default (black-teal) and (gradio-glass) theme, no change.

### Version Platform Description

app: SD.next
updated: 2023-11-08
hash: 3c9c9cf4
url: https://github.com/vladmandic/automatic/tree/master
Running on Windows 10, chrome browsr

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
both items should be fixed now.
