### ISSUE TITLE
[Feature]: DeepDanbooru

### ISSUE THREAD

**Issue by Bercraft** [vladmandic/automatic#2480]
### Feature description

Please add support for deepdanbooru interrogator / tagger.
Base automatic1111 already has it.
Link to deepdanbooru : [https://github.com/KichangKim/DeepDanbooru](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/url)
Inside automatic1111 you just add --deppdanbooru as start argument and you can use the interrogator.
Maybe it will also fix WD14-Tagger issue

### Version Platform Description

Latest commit
Radeon w5700 pro
Threadripper 
Windows 10 workstation

**Comment by vladmandic** [comment]
im not sure what's the ask here, its already integrated and available in image tab.

**Comment by Bercraft** [comment]
Sorry my bad i was looking inside interrogator tab.
Thank you for your time, and work,
you can close or delete this request.
