### ISSUE TITLE
[Issue]: Reference Model links broken for LCM SDXL

### ISSUE THREAD

**Issue by patricktodd** [vladmandic/automatic#2495]
### Issue Description

The download under **Networks > Model > Reference** for LCM SD-XL is trying to download files that don't exist.

### Version Platform Description

Python 3.10.9
Version: app=sd.next updated=2023-11-10 hash=b5c05873
Device: device=NVIDIA GeForce RTX 4080 n=1 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8801

### Relevant log output

```shell
21:37:57-594581 ERROR    Diffusers download error: latent-consistency/lcm-sdxl 404 Client Error. (Request ID:
                         Root=1-654ee905-60525e1e45b0ee155af3adb6;7803a43c-3637-4933-aa03-33971320f97c)

                         Entry Not Found for url:
                         https://huggingface.co/latent-consistency/lcm-sdxl/resolve/main/model_index.json.
21:39:03-083958 ERROR    Diffusers download error: latent-consistency/lcm-sdxl 404 Client Error. (Request ID:
                         Root=1-654ee947-6c0174dc69b504c43066af37;fbebcd25-3937-4eb9-9ee5-63373d1895ce)

                         Entry Not Found for url:
                         https://huggingface.co/latent-consistency/lcm-sdxl/resolve/main/model_index.json.
```

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
temporarily removing it from reference list as model is not in directly downloadable format. will be readded once hf uploads full model structure.
