### ISSUE TITLE
[Issue]: Extra Networks (i) metadata won't scroll

### ISSUE THREAD

**Issue by jordanjay29** [vladmandic/automatic#2498]
### Issue Description

When opening the (i) info for a model/lora/etc under Extra Networks, the modal does not display a scrollbar and limits the amount of information viewed. 

For example: 
![Screenshot 2023-11-11 161724](https://github.com/vladmandic/automatic/assets/7871706/9fa2ae4e-aaa6-4a90-93e5-c49dc378f1df)

The embedded metadata cuts off, and while the copy icon in the upper-right corner can copy the whole thing to be pasted elsewhere, this is not very UX friendly. 

![Screenshot 2023-11-11 162717](https://github.com/vladmandic/automatic/assets/7871706/4b909540-bf6c-4194-89ac-de384d3b4a6b)
Other models cut off the metadata entirely in both tabs, as well as the description tab, even the copy button is unavailable. 

A working example provided by @Aptronymist on discord
![image](https://github.com/vladmandic/automatic/assets/7871706/a926c12e-ffd8-45bc-87c6-2eccb260a35e)

I recall this working on a first load or so when this newest version of Extra Networks was released, but since then it has remained un-scrollable and I have to dig into my files to get information. It seems like a step back in usability compared to the different buttons we had before. 

(First time submitting issue, please let me know if I forgot anything or could add more to help better explain.)

### Version Platform Description

16:20:38-925027 INFO     Version: app=sd.next updated=2023-11-11 hash=7f0827d1
Windows 11
Firefox 119
Nvidia RTX 3060

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
something is interefering with scroll on your system (and this is not isolated, i've heard about it already).
i need to investigate why, but its hard since i cannot reproduce - i can see it without any issues.

**Comment by jordanjay29** [comment]
Someone on the discord pointed me toward the canvas zoom extension. After disabling it and restarting, scrolling worked again. 

That could be a path toward finding the culprit here.

**Comment by vladmandic** [comment]
glad you found it - and if you want more permanent solution, you should report to that repo - not much i can do to fix how that extension behaves (its hiding overflow elements which includes scrollbar)
