### ISSUE TITLE
[Issue]: Discolored inpainting area with the SDXL inpainting model

### ISSUE THREAD

**Issue by 23pennies** [vladmandic/automatic#2501]
### Issue Description

Hi,
I was happy to finally have an SDXL based inpainting model, but I noticed an issue with it: the inpainted area gets a discoloration with a random intensity.

Take the following base image:
![base](https://github.com/vladmandic/automatic/assets/150616709/a0347af9-22ee-4b8a-aa9b-108394dd5a3a)
For comparison, I inpaint it with a 1.5 based model at a denoising level of 1.0, and it fits almost perfectly:
![inpaint1](https://github.com/vladmandic/automatic/assets/150616709/e1670127-fef0-4407-b4e8-39411c98b09b)
I inpaint it with the SDXL inpainting model, and you can clearly see the inpainted area from the discoloration. This goes from barely noticable to really noticable, if almost unusable:
![inpaint2](https://github.com/vladmandic/automatic/assets/150616709/11b44e9d-fb7c-404d-9cb3-4a2cbee10263)
The most extreme case is with a denoising value of 1.0. Here the decoloration goes off the charts:
![inpaint3](https://github.com/vladmandic/automatic/assets/150616709/d58e6b5c-8b54-44be-a830-39a6b5552665)
I think this must be an issue with the VAE encoding rather than the model itself. But that is just speculation. I hope it can be fixed.

### Version Platform Description

Windows 10, RTX 3090 Ti, fresh git clone from a few days ago

### Backend

Diffusers

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by 23pennies** [comment]
With https://github.com/vladmandic/automatic/issues/2502 being fixed, this also happens with 1.5 based models when the backend is set to Diffusers. So it's not an issue with the VAE or model.

**Comment by vladmandic** [comment]
thats a good update to know, thanks. this is still on my todo list to dive into.

**Comment by vladmandic** [comment]
i've spent several hours on this, but nothing really helped - seems like there is issue inside `diffusers`, created upstream issue: https://github.com/huggingface/diffusers/issues/5808

**Comment by vladmandic** [comment]
new mask blur, padding and overlay controls have been implemented in dev branch, will be merged to master in the next release.

**Comment by crapthings** [comment]
hello @vladmandic could you pls point me how to solve this?

![image](https://github.com/user-attachments/assets/fe1e709e-6489-43fc-8514-1c6b67d5097e)

i have something like this

**Comment by vladmandic** [comment]
pls do not post unrelated questions on issues closed a year ago
