### ISSUE TITLE
[Issue]: Error thrown when running a 1.5 inpainting model with Diffusers backend

### ISSUE THREAD

**Issue by 23pennies** [vladmandic/automatic#2502]
### Issue Description

Trying to run a 1.5 based inpainting model with the Diffusers backend results in this error. It works fine with the original backend.
I found some issues mentioning a similar error, but they were all related to the upscaler. But none of the tweaks I tried with the upscaler settings helped.

### Version Platform Description

Windows 10, RTX 3090 Ti, fresh git clone from a few days ago

### Relevant log output

```shell
Given groups=1, weight of size [320, 9, 3, 3], expected input[2, 4, 128, 128] to have 9 channels, but got 4 channels instead
```

### Backend

Diffusers

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed. update will be posted later today.
