### ISSUE TITLE
[Issue]: Running the zero123plus pipeline not possible offline, despite all required files having been downloaded

### ISSUE THREAD

**Issue by 23pennies** [vladmandic/automatic#2503]
### Issue Description

I followed the guide to set up the pipeline: https://github.com/vladmandic/automatic/discussions/2421

At first, it worked. It also kept working if I unplugged the internet, suggesting that it just uses the local files. But if I stop the webui, and then start it again while having no internet, and then try to run this model again, it tries to pull the pipeline from the internet and fails. I would expect it to check the local files and use those.

### Version Platform Description

Windows 10, RTX 3090 Ti, recent fresh git clone

### Relevant log output

```shell
17:09:48-843900 ERROR    Failed loading model: models/Diffusers/models--sudo-ai--zero123plus-v1.1/snapshots/36df7de980afd15f80b2e1a4e9a920d7020e2654        
                         auto=AutoPipeline can't find a pipeline linked to Zero123PlusPipeline for None                                                     
                         diffusion=(MaxRetryError("HTTPSConnectionPool(host='huggingface.co', port=443): Max retries exceeded with url:                     
                         /api/models/Disty0/zero123plus-pipeline (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at               
                         0x7fc7c86617e0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))"), '(Request ID:         
                         73475564-6833-4492-4199-75f13b574331)')
```

### Backend

Diffusers

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
custom pipelines require internet lookup. if you wish to open a feature request on huggingface diffusers git repo, please do so and add it here for tracking purposes. but this issue cannot be resolved on purely sdnext side.
