### ISSUE TITLE
[Feature]: XYZ Gird -> 'None' option where applicable. For Refiners in particular

### ISSUE THREAD

**Issue by myndxero** [vladmandic/automatic#2504]
### Feature description

Adding a 'None' entry for drop boxes where applicable, namely Refiners, as that's where I discovered the option would be useful to me.

Some models claim they work better without the refiner, I am finding that I like to test this with a refiner model anyway, as well as some of my other favorite models, including the current model I'm using (seems to produce some very crisp results like it's double-sampled or something (which would make sense)).

VAE could be useful to some? Don't think we need a None option for SD model. I've pondered a none option with rescaler, I am guessing there might need to be extra effort here so an outputted grid could account for the images not being rescaled vs the ones that are, either up or down.

Could become a convoluted undertaking :P I take nothing for granted and hold no expectations, since the mighty Pause button was added just for me. Really should be renamed to mynd's Pause button, but I'll let this one slide.

**Comment by vladmandic** [comment]
vae already has none.
upscaler none would mean that i'd need to upscale image anyhow to fit it into grid so 'None' would be exactly the same as using `nearest` - so just use that instead of None
refiner - just addeded, will be posted soon.

**Comment by myndxero** [comment]
Awesome sauce. Thanks for the extra info!
