### ISSUE TITLE
[Issue]: Two or more `BREAK` elements in a prompt seem to break the prompt

### ISSUE THREAD

**Issue by midcoastal** [vladmandic/automatic#2509]
### Issue Description

When validating another PR, I noticed that `BREAK` seems to be broken.

# backend.DIFFUSERS

Example using an SD1.5 model:

`wood elf rogue, BREAK (white_background:1.4), illustration, absurdres, rpg dnd fantasy, character_portrait, solo, full_body, BREAK traveller rpg`
![image](https://github.com/vladmandic/automatic/assets/125929259/be69bf09-95ec-4152-af85-c2bdca84de39)

`wood elf rogue, BREAK (white_background:1.4), illustration, absurdres, rpg dnd fantasy, character_portrait, solo, full_body, traveller rpg`
![image](https://github.com/vladmandic/automatic/assets/125929259/ddaf44ee-998c-4d50-9467-d59a0a11752d)

Examples using SD-XL model (same prompts):

![image](https://github.com/vladmandic/automatic/assets/125929259/2de2e35e-2267-4053-9f85-8e79621e7322)

![image](https://github.com/vladmandic/automatic/assets/125929259/34d913eb-d88c-4d7a-91fa-9d7a61960ec2)

In theory, the added `BREAK`s shouldn't change the image "much", or at least, "drastically."  For example, here is the same prompt without *any* `BREAK`s:

![image](https://github.com/vladmandic/automatic/assets/125929259/677e6775-4845-4646-9c8b-d42c33a92917)

# backend.ORIGINAL

This seems to be an issue with both backends, so, likely with the way that BREAK is handled at the hijack level.

Three images, with 2, 1, and no BREAK tokens, respectively:

![image](https://github.com/vladmandic/automatic/assets/125929259/98103c26-5707-4315-a20e-439da11bee74)

![image](https://github.com/vladmandic/automatic/assets/125929259/cd0abf11-e008-4c84-893f-6daf470c8a26)

![image](https://github.com/vladmandic/automatic/assets/125929259/574c0425-66db-4a3a-85d1-cfac28ec2c4c)

### Version Platform Description

15:03:33-022632 INFO     Starting SD.Next                                                                                                                     
15:03:33-023127 INFO     Python 3.10.12 on Linux                                                                                                              
15:03:33-028054 INFO     Version: app=sd.next updated=2023-11-13 hash=c68d35a6 url=https://github.com/vladmandic/automatic.git/tree/Issue2339/EmbeddingLoad   
15:03:33-286046 INFO     Latest published version: f1862579fdad7f266e6b5fd292c27914cb19e457 2023-11-13T14:27:57Z                                              
15:03:33-287548 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=6.3.13-060313-generic python=3.10.12 
15:03:36-348121 INFO     Load packages: torch=2.0.1+cu118 diffusers=0.23.0 gradio=3.43.2 
15:03:36-760829 INFO     Device: device=NVIDIA GeForce RTX 4070 Ti n=1 arch=sm_90 cap=(8, 9) cuda=11.8 cudnn=8700 driver=535.104.05
15:30:58-146410 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False no-half-vae=False upscast=False                                                   
15:30:58-147202 INFO     Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float16 unet=torch.float16 context=no_grad fp16=True bf16=False  
15:30:58-147852 INFO     Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline                                                                   
                         file="models/Stable-diffusion/aZovyaRPGArtistTools_v1Pruned/aZovyaRPGArtistTools_v1Prun
                         ed.safetensors" size=2034MB                                                                                                          
15:30:58-955412 DEBUG    Setting model: pipeline=StableDiffusionPipeline config={'low_cpu_mem_usage': True, 'torch_dtype': torch.float16,                     
                         'load_connected_pipeline': True, 'variant': 'fp16', 'extract_ema': True, 'force_zeros_for_empty_prompt ': True,                      
                         'requires_aesthetics_score': False, 'use_safetensors': True}                     

### Backend

Original

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by afbagwell** [comment]
I was under the impression that SDXL was still limited to 75 tokens. At least my experiments about a month ago seemed to ignore **_any_** extra input past the token limit, and BREAK is only a way to strategically end the current token set before the normal cutoff and starting a new one.

Has this changed in SDXL?

**Comment by vladmandic** [comment]
> I was under the impression that SDXL was still limited to 75 tokens. At least my experiments about a month ago seemed to ignore **_any_** extra input past the token limit, and BREAK is only a way to strategically end the current token set before the normal cutoff and starting a new one.
> 
> Has this changed in SDXL?

long prompts are supported for diffusers for couple of releases now.

**Comment by midcoastal** [comment]
Also, this prompt is not "long" at only 34 tokens.  This is strictly related to the `BREAK` keyword.  I remember looking into one of the hijacks and thinking "I don't think that recursive call is behaving the way they think it is behaving."  Basically recusing into the same string, but also continuing to parse the sting locally as well...  it was odd to look at, but I didn't think much until this cropped up.  Haven't looked yet, implementing something else at the moment.

**Comment by vladmandic** [comment]
i understand that, i was just answering that long prompts are supported in current version of sdnext with diffusers.

when it comes to `BREAK` handling, i'm not touching original backend - whatever change happens there causes a riot because "images don't look exactly the way they looked a year ago". i got burned too many times.

but when it comes to diffusers backend - well, `BREAK` handling did not exist at all - I just added it.
and its looking pretty sweet:

> white hair BREAK red dress BREAK green necklace BREAK blue eyes BREAK on a beach

![image](https://github.com/vladmandic/automatic/assets/57876960/6bcabc75-d3db-4b63-89fb-7c3d3d286a85)

changes are in dev branch and will be included in master in the next version.

**Comment by midcoastal** [comment]
@vladmandic - for what i is worth: It wasn't broken in `backend.ORIGINAL` a month or so ago.  I will do an A/B to see where it wen't south, but the example prompt is from a saved style I was using to generate character portraits for DND.  I am fairly sure I was using original, as this was in May that I made the style.
