### ISSUE TITLE
[Feature]: Support for tinygrad as a backend

### ISSUE THREAD

**Issue by DaniAndTheWeb** [vladmandic/automatic#2514]
### Feature description

Right now pytorch rocm is kinda behind in terms of support for the consumer AMD cards so adding a backend like tinygrad that supports opencl to perform the inference may be very helpful for users with unsupported GPUs (my 5700XT is a perfect example).

**Comment by vladmandic** [comment]
currently there are no plans.
tinygrad is not a full implementation (its pretty much alpha-stage) and also there are no documented benchmarks.
