### ISSUE TITLE
[Feature]: LyCORIS OFT Support

### ISSUE THREAD

**Issue by v0xie** [vladmandic/automatic#2516]
### Feature description

LyCORIS now has support for OFT networks in the dev branch, (https://github.com/KohakuBlueleaf/LyCORIS/blob/dev/lycoris/modules/diag_oft.py) so I thought I'd open a feature request here to give a heads-up.

I've got an open pull request on A1111 with support for LyCORIS OFT: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/13692/files

The major differences between kohya-ss and LyCORIS OFT:
* The weight is named _"oft_diag"_, and there is no _"alpha"_ parameter
* The variables _block_num, block_size_ are reversed from kohya-ss (correct size of blocks from paper is [d, d/r, d/r])
* The PR uses LyCORIS calc_updown() which works for both kohya-ss and LyCORIS OFT
    - It's much faster than merging weights like in kohya-ss

Thank you!

### Version Platform Description

n/a

**Comment by vladmandic** [comment]
we already support lora oft, but i this is just slightly different. is there a trained lora that can be used for dev/test?

**Comment by v0xie** [comment]
Here's a diag-oft network and sample image.
https://huggingface.co/v0xie/sdxl-oft_monster_toy/blob/main/monster_toy_diag-oft-000060.safetensors

![monster_toy_oft_20231115234552_e000060_00_1](https://github.com/vladmandic/automatic/assets/28695009/7f06f326-0b8e-41a0-b8bd-044e55ec520c)

**Comment by vladmandic** [comment]
i took a quick look at integrating this, but i think it needs more work...
i'm getting dtype mismatch in `def calc_updown_kb` and scenarios where `out_dim` is not set at all since block is none of the items in if/elif block in `class NetworkModuleOFT`

**Comment by v0xie** [comment]
Maybe the dtype error is related to the `R = R * multiplier + torch.eye(self.block_size, device=orig_weight.device)` line? That's the only line in the function without a dtype specifier.

You can probably set out_dim to `num_blocks * block_size` or `self.oft_blocks.shape[0] * self.oft_blocks.shape[1]` since those are necessarily divisible by the module's out_dim.

**Comment by vladmandic** [comment]
> Maybe the dtype error is related to the `R = R * multiplier + torch.eye(self.block_size, device=orig_weight.device)` line? That's the only line in the function without a dtype specifier.

yes, thats the line and i've worked around it by moving cast from couple of lines below to above the block.

> You can probably set out_dim to `num_blocks * block_size` or `self.oft_blocks.shape[0] * self.oft_blocks.shape[1]` since those are necessarily divisible by the module's out_dim.

i tried that and it passes, but it was still not producing results that i expected.
need to dive deeper into this, but it will have to wait.

**Comment by vladmandic** [comment]
done in dev branch.
