### ISSUE TITLE
Failed To Validate Samples

### ISSUE THREAD

**Issue by robgw84** [vladmandic/automatic#2519]
### Issue Description

Sometimes when I am generating images I will start getting all black images. The only thing that is shown in the logs is this:
```
16:53:18-373093 ERROR    Failed to validate samples: sample=(768, 768, 3) invalid=1769472
16:53:18-388097 WARNING  Attempted to correct samples: min=0.00 max=0.00 mean=0.00
```
Once this pops up once then it constantly shows up for every generation even if the parameters or prompts are changed and wont stop until I restart SD Next. Everything works fine up until that shows up, and no other errors show in the logs. It seems like it's something in the image generation because when running the ADetailer extension it will sometimes generate a black square over the face or hands (though I am not sure if that error appears then or not as I forgot to look). However the problem isn't just with ADetailer since it happens even when not using ADetailer.

### Version Platform Description

19:08:39-888889 INFO     Starting SD.Next
19:08:39-893891 INFO     Python 3.10.11 on Windows
19:08:40-036923 INFO     Version: app=sd.next updated=2023-11-16 hash=1688fa5e
                         url=https://github.com/vladmandic/automatic/tree/master
19:08:40-390155 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.11
19:08:40-394156 INFO     Using DirectML Backend
19:09:37-621148 INFO     Browser session: client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0)
                         Gecko/20100101 Firefox/119.0

### Relevant log output

```shell
16:53:18-373093 ERROR    Failed to validate samples: sample=(768, 768, 3) invalid=1769472
16:53:18-388097 WARNING  Attempted to correct samples: min=0.00 max=0.00 mean=0.00
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this is quite common on directml as its math ops are flaky at best. search for "black images" or "NaN" - that's all the same root cause. other than that, run in fp32 as much as possible to avoid flakly directml code and that's about it, really not much i can do until directml is updated (its quite old by now).

**Comment by jakewhiteley** [comment]
Im getting the same - only when upscaling

**Comment by AndrewRainfall** [comment]
Same issue but with Intel GPU Arc A770
