### ISSUE TITLE
[Issue]: illegal hardware instruction (core dumped)  ./webui.sh

### ISSUE THREAD

**Issue by awad0** [vladmandic/automatic#2520]
### Issue Description

Fresh installation:

```
git clone https://github.com/vladmandic/automatic  
./webui.sh

```
An it throws the error.

### Version Platform Description

- Linux Mint 21.1
- Kepler K80
- CUDA 11.4
- Python 3.10.12

### Relevant log output

```shell
01:01:55-896464 DEBUG    Extensions all: []
01:01:55-899003 INFO     Extensions enabled: ['stable-diffusion-webui-rembg', 'sd-webui-controlnet', 'Lora', 'sd-webui-agent-scheduler', 'sd-extension-system-info', 'stable-diffusion-webui-images-browser',
                         'sd-extension-chainner']
01:01:55-901324 INFO     Verifying requirements
01:01:55-935328 DEBUG    Setup complete without errors: 1700265716
01:01:55-943302 INFO     Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
01:01:55-946231 DEBUG    Starting module: <module 'webui' from '/home/mk/automatic/webui.py'>
01:01:55-948912 INFO     Command line args: ['--debug'] debug=True
[1]    7736 illegal hardware instruction (core dumped)  ./webui.sh --debug
```

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
kepler k80 is from 2014, no chance that modern torch works on that.
plus you've provided no information on the host - is this a phyisical system or some container or vm (which can easily cause reduced instruction set to be provided thus resulting in invalid instruction).

all-in-all, really not much i can do here. you may have some luck by installing torch 3.9 and forcing older torch (you must downgrade python first so older torch is even available).

**Comment by awad0** [comment]
Well, tested that now on more installations. The Tesla K80 was a PCI passthrough in a VM. Now I have a real machine, Mint again, current pytorch etc., GTX 1060, Driver Version 535.129.03 and CUDA Version 12.2. Same error. automatic1111, invokeai and ComfyUI are running fine. I will stick with them for now. Although I guess automatic might be a better experience. Seems very well done, Vlad. Thanks for all your efforts.
