### ISSUE TITLE
[Issue]: Refiners API doesn't seem to work

### ISSUE THREAD

**Issue by DrCyanide** [vladmandic/automatic#2521]
### Issue Description

I'm trying to trigger Refiners via the API, and it doesn't seem to be working. I left some messages in the Discord, and was recommended to try adding `enable_hr`, but that doesn't seem to work.

I'm using SD 1.5 models for both the checkpoint and the refiner. This works in A1111, so I'm expecting similar results. The models are an anime-based primary checkpoint and a realistic refiner, so it's very clear when it works. In A1111 all I need to do is add `{"refiner_checkpoint": "model_name", "refiner_switch_at": 0.6}` and it works, so it seems odd that it's taking so many extra settings to be added to make it work in SD.Next

Here's the request I'm making.
```
{
    "width": 512,
    "height": 512,
    "refiner_start": 0.6,
    "steps": 50,
    "prompt": "A swimmer, onepiece swimsuit, swim cap, standing on a diving board over a pool, goggles on",
    "negative_prompt": "frown, cartoon, uncanny, monochromatic, ugly, realistic, hat, tilted, eyelashes, grayscale, desaturated",
    "batch_size": 1,
    "cfg_scale": 6.999999999999993,
    "seed": -1,
    "subseed": -1,
    "subseed_strength": 0,
    "enable_hr": true,
    "alwayson_scripts": {},
    "override_settings": {
        "sd_model_checkpoint": "abyssorangemix3AOM3_aom3a1b [5493a0ec49]",
        "sd_vae": "vae-ft-ema-560000-ema-pruned.vae.pt",
        "sd_model_refiner": "epicrealism_naturalSin"
    },
    "sampler_name": "",
    "override_settings_restore_afterwards": false,
    "hr_force": true,
    "refiner_steps": 20,
    "refiner_prompt": "A swimmer, onepiece swimsuit, swim cap, standing on a diving board over a pool, goggles on",
    "refiner_negative_prompt": "frown, cartoon, uncanny, monochromatic, ugly, realistic, hat, tilted, eyelashes, grayscale, desaturated",
    "n_iter": 1
}
```

### Version Platform Description

Windows 10
Python 3.10.6 on Windows
Version: app=sd.next updated=2023-11-13 hash=f1862579

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by DrCyanide** [comment]
Worth pointing out that I don't see refiner options in the UI either.
![image](https://github.com/vladmandic/automatic/assets/13542136/ca8d9d31-8db6-4398-889e-668a78334ffd)

**Comment by vladmandic** [comment]
Refiner is not supported in original backend, only in diffusers backend.
