### ISSUE TITLE
[Issue]: Dropdown missing my CKPTs. I've lost all my pickles.

### ISSUE THREAD

**Issue by Ph0rk0z** [vladmandic/automatic#2525]
### Issue Description

I'm using git/dev with diffusers and my CKPT models don't show up in the dropdown. I would try to convert them but they don't show up in the model merging menu either. I do not have prevent using CKPT checked off. Is this a feature of diffusers or some dependency?

### Version Platform Description

Linux 22.04, CUDA 11.8, Torch 2.1.0, Xformers. LCM, SD1.5, Diffusers

### Backend

Diffusers

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
diffusers do not support ckpt as model format. start sdnext using backend:original and convert models to safetensors.
