### ISSUE TITLE
[Issue]: LCM doesn't work with LoRA cache.

### ISSUE THREAD

**Issue by Ph0rk0z** [vladmandic/automatic#2526]
### Issue Description

I have tried to enable LoRA cache because I see them loading constantly in the logs. I am using the LCM lora and several others together for SD 1.5 models. Also using the API so this might be a factor.

When I load the first model it usually works for a bit. If I change lora or load another model it appears that the LoRA no longer apply and I get very ghosty LCM samples and often complaints about the "patch already being applied" in the log.

Turning off lora cache solves the problem and every model consistently uses the ones they are supposed to but there appears some lag as it loads them all from disk or system ram cache.

How do I keep all my lora in memory?

### Version Platform Description

Linux 22.04
git/dev
Diffusers
LCM
Xformers
24G GPU

### Backend

Diffusers

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
lcm lora does not support lora caching yet as lcm lora must be loaded using a pretty different method than any other lora at the moment. i'll leave this open as backlog item until lcm lora loader is unified with the rest of the loras.

**Comment by vladmandic** [comment]
fixed in dev, will be merged to master in the next release.
