### ISSUE TITLE
[Feature]: Add update support to the civitai model manager. 

### ISSUE THREAD

**Issue by srcrist** [vladmandic/automatic#2529]
### Feature description

It would be great to add support to the civitai model management for scanning existing models for available updates and downloading new versions. The best example of this functionality is the civitai-browser-plus extension which is both fast (uses aria for DLs) and efficient (batches requests to civitai for quick queries even during congestion), available here: https://github.com/BlafKing/sd-civitai-browser-plus. This extension has recently stopped working because of A1111/SDNext code divergence, though, and there is no longer a working extension to handle this functionality from what I can tell. It is effectively the only remaining feature missing from the integrated model manager. 

### Version Platform Description

SDNext master, Ubtuntu 22.04, Firefox

**Comment by vladmandic** [comment]
functionality added in dev branch, will be merged to master soon.
