### ISSUE TITLE
[Question]: ControlNet - send to img2img

### ISSUE THREAD

**Issue by fbellgr** [vladmandic/automatic#2534]
### Issue Description

Around the time of [this issue](https://github.com/vladmandic/automatic/issues/2085), ControlNet also made changes that they say was fixing infotext.

What happened is that since that time, with all controlnet revisions after [cde4619](https://github.com/Mikubill/sd-webui-controlnet/commit/cde4619c5dea047589b82a42aaba6a3900e965d9), sending an image to img2img from txt2img also sends along the controlnet settings from txt2img. This mean that if you are using txt2img to create an image with a pose and img2img to upscale with controlnet tiles + ultimate sd upscale, you have to constantly reapply all controlnet settings because they are overriwritten in img2img.

Apparently, this behaviour is intended.

Is it also the intent in SD.Next?

Automatic1111 also behaves in the same way since then. I do not remember people complaining about settings being independent in txt2img and img2img and that it needed "fixing".

PS: I never considered this to be a sd.next issue, but asking people over at controlnet about it only leads to being told to use an old revision if I like infotext broken, or to ask sd.next to "fix" it.

### Backend

Original

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
for most users, yes, this would be intedend behaviour. ideally, it would be a user choice which setting should be applied, but there is no elegant way to do that as list of possible settings is massive.

if you don't want that, you can copy&paste image instead sending it.

**Comment by fbellgr** [comment]
I anyone is annoyed like me by this behaviour, a neat trick is to go through the Process tab.

- Generate image
- Send to Process 
- Sent to Image (from the source panel)

This way you do not have to copy & paste the image + positive prompt + negative prompt.
And ControlNet settings are preserved.
