### ISSUE TITLE
[Issue]: PixArt-alpha/PixArt-XL-2-1024-MS model is not producing legible images

### ISSUE THREAD

**Issue by jetjodh** [vladmandic/automatic#2536]
### Issue Description

The results from the model in the app differ vastly from same prompts and settings in https://huggingface.co/spaces/PixArt-alpha/PixArt-alpha
The commit hash is: 7354f0dfd3680af857ea514f1189fde35716f0c1
I downloaded the model from HF model downloader in webui.

Prompt and settings:

Pirate ship trapped in a cosmic maelstrom nebula, rendered in cosmic beach whirlpool engine, volumetric lighting, spectacular, ambient lights, light pollution, cinematic atmosphere, art nouveau style, illustration art artwork by SenseiJaye, intricate detail. 
base model: PixArt-alpha/PixArt-XL-2-1024-MS 
steps:20 
cfg-scale:3.5
seed:1070899229
sampler: Default

SD Next:
![Pirate ship trapped  (1)](https://github.com/vladmandic/automatic/assets/20591775/fa7f422a-a95a-4861-be49-4b00374c14ff)
HF Space:
![eeb9a40d-3788-4c65-8dff-052fe69d5a56](https://github.com/vladmandic/automatic/assets/20591775/6cb0724a-8e53-40c9-b8ec-5275c9997a67)

### Version Platform Description

Ubuntu 22.04, Nvidia T4

### Backend

Diffusers

### Model

Other

### Infotext

"infotexts": [
      "Pirate ship trapped in a cosmic maelstrom nebula, rendered in cosmic beach whirlpool engine, volumetric lighting, spectacular, ambient lights, light pollution, cinematic atmosphere, art nouveau style, illustration art artwork by SenseiJaye, intricate detail.\nSteps: 20, Seed: 1070899229, Sampler: Default, CFG scale: 3.5, Size: 1024x1024, Parser: Full parser, Model: PixArt-XL-2-1024-MS, Seed resize from: -1x-1, Backend: Diffusers, App: SD.Next, Version: unknown, Operations: txt2img, Pipeline: PixArtAlphaPipeline, CFG rescale: 0.7"
    ]
    
### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
and you have provided absolutely no information.

**Comment by jetjodh** [comment]
@vladmandic updated my issue with prompt and params used

**Comment by vladmandic** [comment]
seems that version of pixart alpha model is suuuper sensitive to cfg scale and default value of 6 basically burns the image.
your prompt with cfg scale of 1 gives quite a nice image at 1024px resolution:
![image](https://github.com/vladmandic/automatic/assets/57876960/04834e61-3762-4e88-bf09-098bdf4b94e4)

**Comment by jetjodh** [comment]
Thanks!
