### ISSUE TITLE
[Issue]: Image Info does not display newlines

### ISSUE THREAD

**Issue by a2ZxgdqHeSs8F51cIyuK** [vladmandic/automatic#2549]
### Issue Description

It's the same issue that comes back every now and then.
The prompts in processing image don't display the newlines, it's all in a single line.
The Prompt in image generation:
![image](https://github.com/vladmandic/automatic/assets/111918717/e2df6932-b58b-49ea-bb3b-efd0b69a4aab)
The Prompt in Image Processing:
![image](https://github.com/vladmandic/automatic/assets/111918717/bd84f81e-72b5-421e-91bb-71320bf0617f)

### Version Platform Description

Version: app=sd.next updated=2023-11-21 hash=bee397e8

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Ah, additionally LoRas and Lycos used don't show up at all now, there's just an empty section in image processing where they should be.
During Prompting:
![image](https://github.com/vladmandic/automatic/assets/111918717/0ea5ee79-d662-458d-9979-f2fef439d720)
In Processing:
![image](https://github.com/vladmandic/automatic/assets/111918717/d7e9876b-a094-4e48-b7d0-8c59aa847bcf)

**Comment by vladmandic** [comment]
fixed in dev, will be merged to master in the next release.
