### ISSUE TITLE
[Issue]: ValueError when inpainting an image that was sent through from the image browser

### ISSUE THREAD

**Issue by gds91** [vladmandic/automatic#2556]
### Issue Description

Converting into an issue as requested.

Steps to reproduce:
1) Generate an image
2) Send the image to img2img
3) Do do any img2img generation with a mask
4) Restart the server
5) Go to the built-in image browser and send it to inpainting. This will reproduce all the settings that were previously used, including the mask settings.
6) Apply a mask and perform another inpaint to reproduce the error. 

I think it probably has something to do with the settings that the image browser sends over that's causing the logic to break when inpainting. This issue does not occur if I don't send over settings from inpainting.

Additional Notes: After encountering this issue I performed a clean install to make sure any of the extensions I downloaded were causing an issue. 

### Version Platform Description

INFO     Python 3.10.11 on Windows
INFO     Version: app=sd.next updated=2023-11-23 hash=36562509
                         url=https://github.com/vladmandic/automatic.git/tree/master
INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 2, GenuineIntel system=Windows
                         release=Windows-10-10.0.22621-SP0 python=3.10.11
INFO     nVidia CUDA toolkit detected: nvidia-smi present
INFO     Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
INFO     Command line args: ['--upgrade'] upgrade=True
INFO     Load packages: torch=2.1.1+cu121 diffusers=0.23.1 gradio=3.43.2
INFO     Engine: backend=Backend.ORIGINAL compute=cuda mode=no_grad device=cuda
                         cross-optimization="Scaled-Dot-Product"
INFO     Device: device=NVIDIA GeForce RTX 3070 Ti Laptop GPU n=1 arch=sm_90 cap=(8, 6) cuda=12.1
                         cudnn=8801 driver=546.17

### Relevant log output

```shell
DEBUG Paste prompt: type="current" prompt="dog
Steps: 20, Seed: 4099890703, Sampler: UniPC, CFG scale: 6, Size: 512x512, Parser: Full parser,
Model: meinamix_meinaV11, Model hash: 54ef3e3610, Backend: Original, App: SD.Next, Version:
e70f3ee, Operations: inpaint, Init image size: 512x512, Init image hash: 44274007, Resize mode:
0, Resize scale: 1.0, Mask blur: 4, Denoising strength: 0.75, Sampler brownian: False, Mask
alpha: 0, Mask invert: 0, Mask content: 1, Mask area: 1, Mask padding: 32"

INFO Parse prompt: {'Prompt': 'dog', 'Negative prompt': '', 'Steps': '20', 'Seed': '4099890703',
'Sampler': 'UniPC', 'CFG scale': '6', 'Size-1': '512', 'Size-2': '512', 'Parser': 'Full
parser', 'Model': 'meinamix_meinaV11', 'Model hash': '54ef3e3610', 'Backend': 'Original',
'App': 'SD.Next', 'Version': 'e70f3ee', 'Operations': 'inpaint', 'Init image size-1': '512',
'Init image size-2': '512', 'Init image hash': '44274007', 'Resize mode': '0', 'Resize scale':
'1.0', 'Mask blur': '4', 'Denoising strength': '0.75', 'Sampler brownian': 'False', 'Mask
alpha': '0', 'Mask invert': '0', 'Mask content': '1', 'Mask area': '1', 'Mask padding': '32',
'Full quality': True}

DEBUG Settings overrides: []

INFO Parse apply: {'Prompt': 'dog', 'Negative prompt': '', 'Sampler': 'UniPC', 'Steps': 20, 'Resize
mode': '0', 'Size-1': 512, 'Size-2': 512, 'Resize scale': 1.0, 'Seed': 4099890703.0, 'Denoising
strength': 0.75, 'CFG scale': 6.0, 'Full quality': True, 'Mask blur': 4, 'Mask alpha': 0, 'Mask
invert': '0', 'Mask area': '1', <function Script.ui.<locals>.<lambda> at 0x000001601FE70790>:
{'value': [], 'type': 'generic_update'}, <function Script.ui.<locals>.<lambda> at
0x000001601FE70820>: {'value': [], 'type': 'generic_update'}, <function
Script.ui.<locals>.<lambda> at 0x000001601FE708B0>: {'value': [], 'type':
'generic_update'}, <function ScriptRunner.setup_ui.<locals>.<lambda> at 0x000001601FEDAE60>:
{'value': 'None', 'type': 'generic_update'}, <function
ScriptRunner.setup_ui.<locals>.onload_script_visibility at 0x000001601FE716C0>: {'visible':
False, 'type': 'generic_update'}, <function connect_paste.<locals>.paste_settings at
0x00000160286D0550>: {'choices': [], 'label': None, 'info': None, 'show_label': None,
'container': None, 'scale': None, 'min_width': None, 'visible': False, 'value': [],
'interactive': None, 'placeholder': None, 'type': 'update'}}

Traceback (most recent call last):
File "C:\AI\TCHT\vladmandic\venv\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
output = await route_utils.call_process_api(
File "C:\AI\TCHT\vladmandic\venv\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
output = await app.get_blocks().process_api(
File "C:\AI\TCHT\vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1435, in process_api
inputs = self.preprocess_data(fn_index, inputs, state)
File "C:\AI\TCHT\vladmandic\venv\lib\site-packages\gradio\blocks.py", line 1245, in preprocess_data
processed_input.append(block.preprocess(inputs[i]))
File "C:\AI\TCHT\vladmandic\venv\lib\site-packages\gradio\components\radio.py", line 170, in preprocess
return [value for _, value in self.choices].index(x)
ValueError: '0' is not in list
```

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
issue was that resize mode has read by-index and update by-value, so value 0/1/2/3 is not a valid value to set.
fixed in dev branch, will be merged to master in the next release.
