### ISSUE TITLE
[Extension] controlnet failure running on mps platform

### ISSUE THREAD

**Issue by pixlemedia** [vladmandic/automatic#2564]
### Issue Description

In a fresh SD.Next installation (just built-in extensions) on my mac Studio, Python stops and giving an error when trying f.e. openPose in Controlnet:
```
| 0/50 [00:00<?, ?it/s]loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/ff32e6fb-db00-11ed-a068-428477786501/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<1x1280xf32>' and 'tensor<1280xf16>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
zsh: abort      /Users/Me/AI/webui.sh
Me@Mac-Studio-von-me ~ % /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

### Version Platform Description

mac studio M2 Ultra (ventura)
vladmandic Automatic updated 2023-11-25
python 3.9.5
ControlNet v1.1.419 (10bd9b25)
Firefox 118.01

### URL link of the extension

https://github.com/Mikubill/sd-webui-controlnet

### URL link of the issue reported in the extension repository

https://github.com/Mikubill/sd-webui-controlnet/issues/2286

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by pixlemedia** [comment]
Hi, thanks for your answer. 
I`ve been researching for the last hours and it looks like a lot of users have the same error i got (especially on M1 / M2 macs). On "standard - SD" it can be "solved" by adding `--no-half` to get rid of the issue but unfortunately this is not a valid SD.Next argument. `--no-half-controlnet ` is but this does not solve the problem in SD.Next repo. Hope this hint helps to get closer to the reason / solution on your side?
I also testet the SD.Next built-in controlnet module on my other workstation (Custom Mac: Intel i9, 256gb, AMD 6900xt GPU) but it also fails. This computer supports Win10 natively so i run the one-line installation from "troublechute" and this works perfectly fine. I still prefer fixing my M2 installation because it is alot faster;) 
Any new thoughts on this?

**Comment by vladmandic** [comment]
`--no-half` has been in settings since very early days of sdnext - so have most of command line params.
![image](https://github.com/vladmandic/automatic/assets/57876960/7e88e417-1cf6-433e-82ae-361d57c91abc)

**Comment by pixlemedia** [comment]
You made my day, this truely helps!
Thanks alot
