### ISSUE TITLE
[Issue]: Refiner Handling Inconsistencies

### ISSUE THREAD

**Issue by midcoastal** [vladmandic/automatic#2573]
### Issue Description

When using a Refiner, I noted a few things:

- Embedding loading:
   - Triggers after the model moves to CPU, unsure if this is an issue or not.  Doesn't matter, because:
   - Embedding loading only triggers against the `shared.sd_model` which is the Base model, and embeddings never load to the refiner.
- The VAE at the time of setting the Refiner is assigned to the Refiner at load only. Subsequent changed to the VAE do not apply to the Refiner.
- Selecting a Base model and a Refiner, prior to the other loading (order independent) causes both Models to fetch and load, however only the last Model is assigned, to both the Base and Refiner.
- Even when selecting `None` or `Automatic` for the `VAE`, using an SD1.5/2.0 and an SD-XL model, in either combination, results in a failed render.

I have local patches ready to go for the first issue and it's sub-parts.

Resolving issue 2 would require some thinking, and, really, is related to #2338 .  A solution there may be a solution here as well.  I am still working on that, but it really does look like it will be a Pipeline-specific selection per.  This is actually doable, and I have an idea for it, but still, a selection per may not be up your alley, I know.

Number 3 is related to how `reload_model_weights()` is used when loading the Model, calling it's self recursively, and relying on global variables, rather than local variables.  When looking at this, I also noted that Model Cacheing is not implemented for `diffusers`, something else I am looking into, as well. I do not have any local patches for either of these two points.

I have patently no idea what is causing the final issue, nor do I wish to look into it at this time, way outside my perview.

### Backend

Diffusers

### Branch

Dev

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by midcoastal** [comment]
@vladmandic - Fifth issue: If you load a Base, and then a Refiner, somehow, even though the refiner has been moved to CPU, you render with the refiner...  Or something weird happens, anyway...

Prompt: `stairs, forest`

Same Seed, UniPC sampler, 20 steps. 

Load Base of `everythingdiffusion_v30`

![image](https://github.com/vladmandic/automatic/assets/125929259/38d59567-694b-484d-8a94-a5e0f3eeddc2)

Load Refiner of `526mixAnimated_v1`

![image](https://github.com/vladmandic/automatic/assets/125929259/10d7beda-eeb9-4473-bdc4-0417f4a69487)

(Mind you, I am not USING the Refiner, in the console it never states that it has triggered, however, it DOES name the output files with the respective models...  Very odd)

Now, if I trigger the Refiner using an ESRGAN upscaler, and then disable upscaling, the next render looks exactly as the first.

Something else worth noting:

I do not see any difference changing `Denoising Strength` or `Refiner Start`.  The following are all images that illustrate several combinations of `Denoising Strength`, `Refiner Start` and `Refiner Steps`.

![image](https://github.com/vladmandic/automatic/assets/125929259/ea430d12-f457-4f2e-aed7-ad8e4183d329)

![image](https://github.com/vladmandic/automatic/assets/125929259/bbf62945-748a-4746-bbfc-82217357ef27)

![image](https://github.com/vladmandic/automatic/assets/125929259/ce22ae0b-1ca1-454f-a6d4-6c1a78bc47c9)

![image](https://github.com/vladmandic/automatic/assets/125929259/f002adfd-d99e-4462-91d5-6f874786b026)

![image](https://github.com/vladmandic/automatic/assets/125929259/1efe01ae-4d92-4a93-95a7-6125005b9e92)

Curiously, the one that stands out in that group is the one at `5 Steps` vs the others which are at `10 Steps`.

Here is one more at 5.

![image](https://github.com/vladmandic/automatic/assets/125929259/f3a985ad-4ebb-421d-8383-16b81289a61f)

Mind you, all of these have a different combination of settings.  

For `Refiner Start`, the setting is one of either `0.2` or `0.9`, same for `Denoise Strength`, and `Steps` are one of either `5` or `10`.  There are *technically* differences, but where Denoise and Start are a range from `0` to `1`, I would expect there to be a greater difference when comparing the polar ends of the settings.

I thought maybe it was `Guidance Rescale` I should be looking at, but setting it from `0.7` to `0.2` did little (it did make it more washed out, and slightly changed features). Changing `Secondary CFG` does make sweeping differences.

![image](https://github.com/vladmandic/automatic/assets/125929259/7b440b27-0639-459e-bf0b-a47420cdcda7)

And lastly, it is interesting to note that, when using an Upscaler that subsequently triggers the Refiner, the First-Stage Image (pre-`hires`) looks again like that broken one above (the one influenced in some manner by the Refiner, after selecting the Refiner, but without triggering it).  Disabling Upscale subsequently produces the expected image rendered by the Base Model...

It is all very silly, to be sure.  Am I just missing something?

I am using Diffusers.

**Comment by vladmandic** [comment]
while i've allowed any model to be used as refiner, that doesn't mean that settings which are really designed for actual refiner model type make sense when used with non-refiner model type.

for example, refiner start 0.8 would mean render 80% of (base steps) using base model, then hand-off unfinished image to refiner for remaining 20% (of refiner steps).
but concept of handing off unfinished image and splitting steps in such manner does not make any sense for models that just do not have that capability. 

so feel free to experiment using any model you want, but that is all best effort only (and some of your results are actually better using refiner in such manner).

**Comment by midcoastal** [comment]
Well cool, I spent 2 hours testing every which thing, and I think I get it now.

The execution order is as follows (correct me if I am wrong):

- The first stage render starts.
- The backend holds a snapshot of the first stage render at the time step relative to Refiner Start.
- The first stage render completes in FULL (all `X` steps, regardless of Refiner settings).
- The first stage snapshot at the time step relative to Refiner Start is fed into Hires.
- **Ignore all of this, yes it is true, but after extensive testing, I gather you don't want to upscale AT ALL (Select `None`) when using a refiner, it results in broken images.  I left this here because...  Well, it IS what "happens."** If using `Latent`, the first stage model is used to render the `Upscale by`, over `Hires steps`, with `Denoising strength`, in *full* (a full Hires steps), in my case, `30` steps. If using a non-`Latent` upscale, the upscaler just upscales the snapshot (complete with remaining noise).
- At this point, the result of the Upscale (or not) is fed to the Refiner for `Refiner steps` relative to `Denoising strength` (my Refiner Steps is `10`, and Denoise Strength is `0.6`, so my resulting number of Refiner Steps was `6`). **NOTE:** Or so I thought....  For whatever reason, after this initial run, always get a refiner of `6` steps, regardless of if I have the Denoise set to `0.1` or `1`, even though I have my Refiner Steps SET to `10`.  Weird...  Or, at least, it never really seems to scale with the Denoise Strength again.  Leaving this here as an "initial finding."

In my experiments, any `Refiner Start` less than `0.5` results in chaos.  `0.8` (default, I think) is meh.  In my experience, it is better to have more steps for the Refiner (default of 5 didn't get me good results, 20 got better [Not actually `20`, there was scaling with Denoise, but not exact]).  Same seemed to go for the initial Steps, basically, the more "shape" the first-stage could lay down, the better, but setting Refiner Start too high didn't seem to do much good either (`0.9` over `0.5`)...  Base of `chimeramiXL_v35` and Refiner of `sdXL_v10RefinerVAEFix`:

Start `0.5`:

![image](https://github.com/vladmandic/automatic/assets/125929259/052c5bd8-63dc-4a01-a2f5-ef84c4f3636d)

Start of `0.9`:

![image](https://github.com/vladmandic/automatic/assets/125929259/555156c4-93f0-45b7-8fa9-702ff4994666)

Unless I am missing something

Discovered "Bugs" (?): 
- Although I had selected  a Base of `everythingdiffusion_v30`, followed by a Refiner of `photomatix_pxRealistikaRefiner` (and the UI was showing this correctly in the quick selects I have at the head of my UI), the reported render "Parameters" were showing `photomatix_pxRealistikaRefiner` as BOTH my Base and Refiner Models... (ignore these Models, they didn't work in testing, only `XL` refiners worked, so I could tell anyway.  I wrote literal pages comparing these models at various settings, I didn't get any "results" until I used one of my XL Refiners).
- When loading the Refiner Models (For `SD-XL` specifically) I got the following error each time: `Model detected as SD-XL refiner model, but attempting to load a base model`.  This is encouraging on one hand, as it shows that they are being correctly detected as Refiner Models.  However, on the other hand, the UI clearly shows that I am loading them as a Refiner, why does the backend think I am loading them as a Base Model?  This is why I need to follow up loading a Base Model, and not the other way around...
- `SD-XL` detection is broken.  I already knew this to some extent, as super large `XL` models (think 12gb) are detected as plain SD, and other like `leosamsHelloworldSDXL_filmGrain20` are as well.  I know this is due to the guess based on file size...  Something to think on...

# Take Away:

The model matters.  Use a Refiner Model.  Don't Upscale (at all). I don't know, still feels a bit shaky to me.  Don't fully understand it.  I'll keep pokeing.  Is there a resource that better explains this somewhere?

**Comment by midcoastal** [comment]
@vladmandic - closing this, as it seems I am missing something. I'm going to do more research (on my own time/thread, so as not to bother you). If I'm still convinced there is an issue (unlikely), I'll round back to it.

Sorry to be a bother.
