### ISSUE TITLE
[Feature]: Add a way to specify the "root" folder of the image Browser

### ISSUE THREAD

**Issue by d8ahazard** [vladmandic/automatic#2574]
### Feature description

Add a command-line argument or setting to specify the root folder for the image browser to use. This way, if we have multiple apps dumping to one shared directory, we can browse *all* the output images.

### Version Platform Description

n/a?

**Comment by vladmandic** [comment]
this is not as trivial as it sounds as that would mean that core app needs to set those folders in allowed list, otherwise security kicks in and regardless of what image browser wants, it will get access denied to files that from locations that are not in allowed list - and allowed list is built from system paths.

also, image browser uses multiple tabs for standard folders (txt, img, extra, etc.) - if there is a different root, then those cannot be assumed to exist in the exact manner, so entire concept of image browser needs to be somewhat redesigned. all doable, but in that case i might rather replace image browser with something new (its a pretty old piece of code anyhow).

**Comment by d8ahazard** [comment]
What about adding an "extra" path option, versus rewriting everything. Then just schlep another tab in it or something?

**Comment by brknsoul** [comment]
You could see if "Infinite Image Browser" suits your needs.

**Comment by Aptronymist** [comment]
I agree with @brknsoul on that, IIB is a lot nicer and more performant, but running as it's own application as I understand it. Image Browser isn't ours or anything, there just aren't a lot of options out there for it that I have noticed.

**Comment by vladmandic** [comment]
infinite image browser is not an option.

**Comment by gohan2091** [comment]
I just installed infinite image browser on SD.Next and think it's really good! I previously used Breadboard which hasn't been updated since March and is buggy (plus it was a standalone app). Nice to have infinite image browser.

**Comment by vladmandic** [comment]
I really like it as well, just integrating it is not an option.

**Comment by gohan2091** [comment]
> I really like it as well, just integrating it is not an option.

Why is that if I may ask? but we can install it as an extension so not a big deal right? or?

**Comment by vladmandic** [comment]
yes, you can install it.
why its not a candidate for integration? because its pretty much a standalone app - it doesn't use any of the standard interface, controls, etc. - in all reality, its just a separate app that happens to be placed in a tab.

**Comment by gohan2091** [comment]
> yes, you can install it. why its not a candidate for integration? because its pretty much a standalone app - it doesn't use any of the standard interface, controls, etc. - in all reality, its just a separate app that happens to be placed in a tab.

Perhaps the person who made that app would be interested in full intergration into SD.next? that would be amazing. I asked [here](https://github.com/zanllp/sd-webui-infinite-image-browsing/discussions/498)

**Comment by AlUlkesh** [comment]
Just saw this issue...

fwiw, the image browser will be faster, once Gradio 4 is integrated into the webuis:
https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/discussions/245#discussioncomment-8149114

As for the original request of this issue, can't you just define a new tab with a custom folder in image browser settings?
