### ISSUE TITLE
Broken images in SD-XL wiki -> incomplete setup instructions

### ISSUE THREAD

**Issue by anothertal3** [vladmandic/automatic#2576]
Only a minor issue:

I intend to dive into SD-XL shortly. For this reason I've checked the wiki for insights on how to start.

Unfortunately, the [SD-XL Wiki](https://github.com/vladmandic/automatic/wiki/SD-XL) contains broken image links. Even more unfortunate: the text always links to the missing images when it comes to setup and configuration (e.g., "we recommend selecting the following items in your Settings Tab...").

Is there a more recent beginner's guide that I'm not aware of?

**Comment by vladmandic** [comment]
if you have a question, that is fine - use discussions.
if you have an issue, you MUST fill issue template - this issue will be closed (yes, even to report broken images in wiki).
@Aptronymist can you take a look at wiki and update as needed?

**Comment by anothertal3** [comment]
Well, it's not so much about questions yet, I simply wanted to report what I thought to be a documentation bug :-)

As all available templates are associated with the actual software I simply used the link at the bottom:
![image](https://github.com/vladmandic/automatic/assets/8721770/c998d0f6-fcda-44ca-9caf-cc64f9e376e9)

But thanks for clarifying. I will use "discussions" for those things then in the future.

**Comment by Aptronymist** [comment]
> if you have a question, that is fine - use discussions. if you have an issue, you MUST fill issue template - this issue will be closed (yes, even to report broken images in wiki). @Aptronymist can you take a look at wiki and update as needed?

crap, yeah. just saw this.
