### ISSUE TITLE
[Extension]: Deforum "AttributeError: 'Field' object has no attribute 'alwayson_scripts'"

### ISSUE THREAD

**Issue by DevilsCrypto** [vladmandic/automatic#2577]
### Issue Description

While using [Deforum](https://github.com/deforum-art/sd-webui-deforum) extension, i get an error. It happens also while doing a full clean install of SDNext and the extension. There is something related to controlnet, but i am not sure how to solve it.

`
*START OF TRACEBACK*
Traceback (most recent call last):
File "/home/ubuntu/automatic/extensions/deforum/scripts/custom_deforum_api/custom_deforum_api.py", line 101, in create_deforum_video
render_animation(args, anim_args, video_args, parseq_args, loop_args, controlnet_args, root)
File "/home/ubuntu/automatic/extensions/deforum/scripts/deforum_helpers/render.py", line 577, in render_animation
image = generate(args, keys, anim_args, loop_args, controlnet_args, root, parseq_adapter, frame_idx, sampler_name=scheduled_sampler_name)
File "/home/ubuntu/automatic/extensions/deforum/scripts/deforum_helpers/generate.py", line 78, in generate
return generate_inner(args, keys, anim_args, loop_args, controlnet_args, root, parseq_adapter, frame, sampler_name)
File "/home/ubuntu/automatic/extensions/deforum/scripts/deforum_helpers/generate.py", line 241, in generate_inner
processed = processing.process_images(p_txt)
File "/home/ubuntu/automatic/modules/processing.py", line 739, in process_images
res = process_images_inner(p)
File "/home/ubuntu/automatic/extensions-builtin/sd-webui-controlnet/scripts/batch_hijack.py", line 39, in processing_process_images_hijack
cn_is_batch, batches, output_dir, input_file_names = get_cn_batches(p)
File "/home/ubuntu/automatic/extensions-builtin/sd-webui-controlnet/scripts/batch_hijack.py", line 184, in get_cn_batches
units = external_code.get_all_units_in_processing(p)
File "/home/ubuntu/automatic/extensions-builtin/sd-webui-controlnet/internal_controlnet/external_code.py", line 203, in get_all_units_in_processing
return get_all_units(p.scripts, p.script_args)
File "/home/ubuntu/automatic/extensions-builtin/sd-webui-controlnet/internal_controlnet/external_code.py", line 212, in get_all_units
cn_script = find_cn_script(script_runner)
File "/home/ubuntu/automatic/extensions-builtin/sd-webui-controlnet/internal_controlnet/external_code.py", line 488, in find_cn_script
for script in script_runner.alwayson_scripts:
AttributeError: 'Field' object has no attribute 'alwayson_scripts'
*END OF TRACEBACK*

User friendly error message:
Error: 'Field' object has no attribute 'alwayson_scripts'. Please, check your schedules/ init values.
No files found for pattern
`

### Version Platform Description

`
06:58:38-650641 INFO     Starting SD.Next                                                                                                                          
06:58:38-653545 INFO     Python 3.10.13 on Linux                                                                                                                   
06:58:38-660918 INFO     Version: app=sd.next updated=2023-11-30 hash=c957a2fb url=https://github.com/vladmandic/automatic.git/tree/master                         
06:58:38-895497 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=5.15.0-67-generic python=3.10.13                                                    
06:58:38-897094 INFO     nVidia CUDA toolkit detected: nvidia-smi present                                                                                          
06:58:38-905329 INFO     Extensions: disabled=[]                                                                                                                   
06:58:38-906117 INFO     Extensions: enabled=['stable-diffusion-webui-rembg', 'sd-extension-system-info', 'Lora', 'sd-webui-agent-scheduler',                      
                         'sd-extension-chainner', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser'] extensions-builtin                               
06:58:38-907511 INFO     Extensions: enabled=['sd-webui-animatediff', 'adetailer', 'deforum', 'ai_api'] extensions                                                 
06:58:38-908600 INFO     Startup: standard                                                                                                                         
06:58:38-909243 INFO     Verifying requirements                                                                                                                    
06:58:38-922203 INFO     Verifying packages                                                                                                                        
06:58:38-923838 INFO     Verifying submodules                                                                                                                      
06:58:40-674342 INFO     Extensions enabled: ['stable-diffusion-webui-rembg', 'sd-extension-system-info', 'Lora', 'sd-webui-agent-scheduler',                      
                         'sd-extension-chainner', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'sd-webui-animatediff', 'adetailer', 'deforum',  
                         'ai_api']         
`

### URL link of the extension

https://github.com/deforum-art/sd-webui-deforum

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
i've made some changes in sdnext dev branch to handle controlnet script errors, hopefully that resolves this issue (dev will be merged to master in the next release).

and please check how to properly format the code - this is unreadable.
