### ISSUE TITLE
[Feature]: add extra noise

### ISSUE THREAD

**Issue by RGX650** [vladmandic/automatic#2584]
### Feature description

Add noisy latent to `ExtraNoiseParams` for callback
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/12856

Add extra noise callback
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/12616

Add extra noise param for img2img operations
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/12564

[catboxanon]
https://gist.github.com/catboxanon)/[zz_extra_noise_mask.py]
https://gist.github.com/catboxanon/69ce64e0389fa803d26dc59bb444af53

**Comment by vladmandic** [comment]
i'm ok with this, but can you submit actual PR?

**Comment by RGX650** [comment]
thanks for your interest and reply! 

I am not a proper dev actually, git related methodologies an subtilities are still a bit obscure to me... 
so please don't be mad at me. 

i kind of manage to start implementing it through my fork
https://github.com/RGX650/sd-webui-bmab-SDNEXT/blob/main/README.md
https://github.com/RGX650/sd-webui-bmab-SDNEXT

It is a fork of @portu-sim BMAB extention working with A1111
https://github.com/portu-sim/sd-webui-bmab

Adding A1111's RNG
https://github.com/RGX650/sd-webui-bmab-SDNEXT/tree/main/sd_bmab/external/rng

Adding extra-noise callbacks
https://github.com/RGX650/sd-webui-bmab-SDNEXT/commit/09d9aecbc22bbfa00157e6f6a485d22fffa4516f

shared.opts.add_option('img2img_extra_noise'
shared.opts.add_option('randn_source'
https://github.com/RGX650/sd-webui-bmab-SDNEXT/blob/main/sd_bmab/ui.py

class StableDiffusionProcessingTxt2ImgOv(StableDiffusionProcessingTxt2Img)
https://github.com/RGX650/sd-webui-bmab-SDNEXT/blob/main/sd_bmab/sd_override/txt2img.py

class KDiffusionSamplerBMAB(KDiffusionSampler)
https://github.com/RGX650/sd-webui-bmab-SDNEXT/blob/main/sd_bmab/sd_override/samper.py

**Comment by vladmandic** [comment]
> I am not a proper dev actually, git related methodologies an subtilities are still a bit obscure to me...
> so please don't be mad at me.

mad? far from it - i appreciate the work!

i'll check out your repo soon, really want to wrap-up work on new control module.
also, i will need to implement callback for diffusers backend (where callbacks work quite differently) - but it should be doable.
with more and more features in diffusers backend, i think there will be even more value there.

**Comment by vladmandic** [comment]
sorry for the delay, last month has been pretty crazy.
anyhow, `img2img_extra_noise` is now added for backend:original k-diffusers. if there is sufficient demand, it can be added to remaining compvis samplers (ddim,unipc). backend:diffusers will need separate implementation.
