### ISSUE TITLE
[Issue]: error when saving meta data to text file

### ISSUE THREAD

**Issue by RCHZ** [vladmandic/automatic#2590]
### Issue Description

Meta data text file is not saved unless it also being saved in the image.

If only the option to save meta data as a text file is checked within settings, I receive a red error message at the top right of ui and the following error in cmd:
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\AI\\1111\\outputs\\save\\(prompt text)\\00000-(checkpoint name)-(prompt text).txt'

The directory does get created and the image does get saved there, but no text file.

When I go to settings and check to have it also save meta data to the image, generate the prompt again and then save the image, the text file and image are then both saved to the directory without error.

![Screenshot 2023-12-04 223646](https://github.com/vladmandic/automatic/assets/29241246/9ae72d0c-9ab4-4a88-8240-f3a165877652)

![Screenshot 2023-12-04 224135](https://github.com/vladmandic/automatic/assets/29241246/aab6e73b-5986-41a5-962f-6d3d0e87ec4e)

![Screenshot 2023-12-04 224255](https://github.com/vladmandic/automatic/assets/29241246/ef45fd83-360d-440a-95a2-44f0b69b2df1)

[sdnext.log](https://github.com/vladmandic/automatic/files/13556355/sdnext.log)

### Version Platform Description

Python 3.10.11 on Windows
Version: app=sd.next updated=2023-12-04 hash=93f35ccf  url=https://github.com/vladmandic/automatic/tree/master
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 183 Stepping 1, GenuineIntel system=Windows release=Windows-10-10.0.22631-SP0 python=3.10.11

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev, will be merged to master in the next release.
