### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by bettinaSim** [vladmandic/automatic#2593]
### Feature description

Easy way to turn face restoration on/off

### Version Platform Description

It would be very nice if face restoration was just a simple checkmark on the text tab. The method for restoring it in AUTOMATIC1111 seems to be missing. 

https://www.kombitz.com/2023/09/03/how-to-add-restore-faces-option-back-to-automatic1111s-web-ui-after-1-6-0-upgrade/

**Comment by vladmandic** [comment]
A) enter title.
B) it already is.
