### ISSUE TITLE
[Extension]: openpose editor window skewed

### ISSUE THREAD

**Issue by SAC020** [vladmandic/automatic#2594]
### Issue Description

Filed this issue in the openpose editor repo, got redirected here

(https://github.com/huchenlei/sd-webui-openpose-editor/issues/57)

### Version Platform Description

Using VENV: C:\ai\automatic\venv
23:59:29-707797 INFO     Starting SD.Next
23:59:29-711269 INFO     Python 3.10.11 on Windows
23:59:29-937217 INFO     Version: app=sd.next updated=2023-11-30 hash=c957a2fb
                         url=https://github.com/vladmandic/automatic/tree/master
23:59:30-221517 INFO     Latest published version: 93f35ccf885b7ad0e85878d58421507aecf14f95 2023-12-04T18:31:52Z
23:59:30-233421 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
23:59:30-236893 INFO     nVidia CUDA toolkit detected: nvidia-smi present
23:59:30-376381 WARNING  Modified files: ['repositories/BLIP/BLIP.gif', 'repositories/CodeFormer/.gitignore',
                         'scripts/detect_extension.py']
23:59:30-431422 INFO     Extensions: disabled=['sd-dynamic-thresholding']
23:59:30-432414 INFO     Extensions: enabled=['clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-extension-chainner',
                         'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
                         extensions-builtin
23:59:30-452851 INFO     Extensions: enabled=['adetailer', 'canvas-zoom', 'deforum-for-automatic1111-webui',
                         'openpose-editor', 'sd-dynamic-prompts', 'sd-webui-3d-open-pose-editor',
                         'sd-webui-openpose-editor', 'sd-webui-regional-prompter'] extensions
23:59:30-480421 INFO     Startup: quick launch
23:59:30-481413 INFO     Verifying requirements
23:59:30-505236 INFO     Verifying packages
23:59:30-508708 INFO     Extensions: disabled=['sd-dynamic-thresholding']
23:59:30-509699 INFO     Extensions: enabled=['clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'ScuNET', 'sd-extension-chainner',
                         'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-agent-scheduler',
                         'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
                         extensions-builtin
23:59:30-516643 INFO     Extensions: enabled=['adetailer', 'canvas-zoom', 'deforum-for-automatic1111-webui',
                         'openpose-editor', 'sd-dynamic-prompts', 'sd-webui-3d-open-pose-editor',
                         'sd-webui-openpose-editor', 'sd-webui-regional-prompter'] extensions
23:59:30-538427 INFO     Extension preload: {'extensions-builtin': 0.01, 'extensions': 0.01}
23:59:30-540411 INFO     Command line args: []

### URL link of the extension

https://github.com/huchenlei/sd-webui-openpose-editor

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by SAC020** [comment]
URL link of the issue reported in the extension repository

https://github.com/huchenlei/sd-webui-openpose-editor/issues/57

**Comment by vladmandic** [comment]
I'd be happy to include necessary CSS, but I'm not chasing down every possibility for every extension.
If someone has a suggestion, great.

**Comment by lbeltrame** [comment]
Where in the CSS should I look at to see what's causing this issue? At least in dev console, setting the width of `cnet-modal` has no effect.

**Comment by lbeltrame** [comment]
Given the above:

- is this an extension bug because the extension is expecting something that may not be correct, or
- is this a SD.Next bug?

**Comment by lbeltrame** [comment]
Thanks @vladmandic, I'll set that as user CSS as a local workaround.

@huchenlei Does it seem doable for you to add this ? Want me to submit a PR or will you make the change yourself, assuming you agree with it?

**Comment by huchenlei** [comment]
Please make a PR and verify that it works in SDNext, as I do not have a SDNext installation to verify problem fixed. 

BTW `cnet-modal-0` is the element id, the selector should match `cnet-modal` class instead.

**Comment by lbeltrame** [comment]
No time to work on it until the weekend, I'm afraid.

**Comment by lbeltrame** [comment]
Ok, I was able to make this work in less than what I had expected (see attached screenshot). PR to sd-webui-controlnet incoming.
![image](https://github.com/vladmandic/automatic/assets/25192/638dab49-6865-4f04-8f4c-8788543f317b)

**Comment by lbeltrame** [comment]
@huchenlei Done. OTOH I can't test with A1111, so let me know if it breaks anything.

**Comment by huchenlei** [comment]
Looks good. Thanks for fixing this!

**Comment by lbeltrame** [comment]
@vladmandic I think that this can be closed now (or whenever the submodule is updated in `master`).

**Comment by Fleival** [comment]
The comments in style.css line 19 and 36  is incorrect : /* Fix sizing with SD.Next (vladmandic/automatic#2594)

**Comment by lbeltrame** [comment]
@Fleival I thought I had committed that one, sorry about that! (I originally made the typo but I didn't commit)
@huchenlei Would you be able to fix it directly? I think a PR is overkill for that.
