### ISSUE TITLE
[Issue]: libmkl_sycl.so not found

### ISSUE THREAD

**Issue by jimbolimbo3** [vladmandic/automatic#2601]
### Issue Description

If you encounter this issue below after updating Intel libraries to 2024:

``` bash
Traceback (most recent call last):
  File "/home/--user--/automatic/venv/bin/ipexrun", line 5, in <module>
    from intel_extension_for_pytorch.launcher import main
  File "/home/--user--/automatic/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/__init__.py", line 93, in <module>
    from .utils._proxy_module import *
  File "/home/--user--/automatic/venv/lib/python3.10/site-packages/intel_extension_for_pytorch/utils/_proxy_module.py", line 2, in <module>
    import intel_extension_for_pytorch._C
ImportError: libmkl_sycl.so.3: cannot open shared object file: No such file or directory
```

you can solve it installing old Intel libraries with:

```bash
wget -O- https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB | gpg --dearmor | tee /usr/share/keyrings/oneapi-archive-keyring.gpg > /dev/null
echo "deb [signed-by=/usr/share/keyrings/oneapi-archive-keyring.gpg] https://apt.repos.intel.com/oneapi all main" | tee /etc/apt/sources.list.d/oneAPI.list
apt update
apt install intel-oneapi-runtime-openmp=2023.2.2-47 intel-oneapi-runtime-dpcpp-cpp=2023.2.2-47 intel-oneapi-runtime-mkl=2023.2.0-49495
```

### Version Platform Description

WSL, Intel A770

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by crasyK** [comment]
Hello, I have encountered the same problem, but your solution, doesn't seem to work, it just gives me a different error. I am also using WSL Ubuntu with a Arc A770. 
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 intel-oneapi-runtime-dpcpp-cpp : Depends: intel-oneapi-runtime-compilers (= 2023.2.2-47) but it is not going to be installed
                                  Depends: intel-oneapi-runtime-dpcpp-cpp-common (= 2023.2.2-47) but 2023.2.3-20 is to be installed
                                  Depends: intel-oneapi-runtime-opencl (= 2023.2.2-47) but 2023.2.3-20 is to be installed
```
Thanks in Advance 

P.S. I tried to change the numbers of the installation, but it seems not make a difference.

**Comment by kunumigab** [comment]
> Hello, I have encountered the same problem, but your solution, doesn't seem to work, it just gives me a different error. I am also using WSL Ubuntu with a Arc A770.
> 
> ```
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  intel-oneapi-runtime-dpcpp-cpp : Depends: intel-oneapi-runtime-compilers (= 2023.2.2-47) but it is not going to be installed
>                                   Depends: intel-oneapi-runtime-dpcpp-cpp-common (= 2023.2.2-47) but 2023.2.3-20 is to be installed
>                                   Depends: intel-oneapi-runtime-opencl (= 2023.2.2-47) but 2023.2.3-20 is to be installed
> ```
> 
> Thanks in Advance
> 
> P.S. I tried to change the numbers of the installation, but it seems not make a difference.

Same problem as you, did you found a solution?

Sorry for reviving this issue

**Comment by mrcbax** [comment]
This issue is not resolved. There are some linux distros that cannot downgrade packages. as suggested by @kunumigab the latest update to Intel OneAPI BaseKit 2024 breaks with the same error.
