### ISSUE TITLE
[Issue]: Error with SDXL inpainting model at 1.0 denoising

### ISSUE THREAD

**Issue by 23pennies** [vladmandic/automatic#2603]
### Issue Description

Running the SDXL inpainting model/pipeline with a 1.0 denoising value results in this error.

### Relevant log output

```shell
UnboundLocalError: local variable 'image_latents' referenced before assignment
```

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
1.0 is not really valid for denoising strength, i'll set the limit at 0.99
