### ISSUE TITLE
[Issue]: Styles sort by name not working for non-built in styles

### ISSUE THREAD

**Issue by Memeheader** [vladmandic/automatic#2611]
### Issue Description

Sorting by name doesn't seem to work properly, it seems that it sorts by date, the issue appears when custom styles are in subfolders or not. It seems like it defaults to sorting by date.
https://ibb.co/S3M1HSR

### Version Platform Description

14:41:28-482469 INFO     Starting SD.Next
14:41:28-486469 INFO     Logger: file="D:\repos\Stable Diffusion\automatic\sdnext.log" level=INFO size=1369087
                         mode=append
14:41:28-488970 INFO     Python 3.10.10 on Windows
14:41:28-622509 INFO     Version: app=sd.next updated=2023-12-04 hash=93f35ccf
                         url=https://github.com/vladmandic/automatic.git/tree/master
14:41:28-874413 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.10
14:41:28-880914 INFO     nVidia CUDA toolkit detected: nvidia-smi present
14:41:28-972430 INFO     Extensions: disabled=[]
14:41:28-974431 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev, will be merged to master in the next release.
