### ISSUE TITLE
[Feature]: Auto add trigger/activation words for loras

### ISSUE THREAD

**Issue by Fectopos** [vladmandic/automatic#2621]
### Feature description

in auto1111 the built in LoRa extension makes it so that when you select a lora to appear in the prompt, the activation words are automatically added i think this would be a nice feature

**Comment by vladmandic** [comment]
you can already add activation words using networks -> lora.
adding them all automatically is bad since loras can have a lot (10+) of different activation words and some can be conflicting (e.g. smile vs angly)

**Comment by Fectopos** [comment]
> you can already add activation words using networks -> lora. adding them all automatically is bad since loras can have a lot (10+) of different activation words and some can be conflicting (e.g. smile vs angly)

how can i do this i dont find it

**Comment by vladmandic** [comment]
click networks -> lora -> hover over lora and you'll see all trigger words -> click on a word you want to add

**Comment by Fectopos** [comment]
> click networks -> lora -> hover over lora and you'll see all trigger words -> click on a word you want to add

ok i saw it but it doesnt work like in auto1111, with the same lora the auto1111 has a lot of activation words that in vladmandic shows wrongly or isn't accurate for example
![image](https://github.com/vladmandic/automatic/assets/153838087/ddce7487-b6ad-4e38-a880-c067ff2c3b8f)

this lora in auto1111 show that his activation words are "tape gag" wich matches the activation word from the civitai lora
now in vladmandic it shows this words
![image](https://github.com/vladmandic/automatic/assets/153838087/8b60ead9-4d45-439b-8980-8cea8a566462)
and in many loras doesnt show the real activation words so its more difficult to make the lora work like it should be

**Comment by vladmandic** [comment]
i cannot verify every single lora that author mislabels. 
and to make it worse, you never provided a link to it.

i found v1.0 eventually, v1.1 you mentioned is NOT on civitai.

this is metadata provided by author:
```json
 {
id:  30113,
name:  "Tape Gag",
description:  "<p><strong>v1.0</strong><br />A simple LoRA model that allows you to put a tape gag on your character. Works with LoRA character models. The screenshots (if they pass moderation) show characters such as Lucy from Edgerunners, Prinz Eugen from Azure Lane and Marikawa Shizuka from High School of Dead.<br /><br /><strong>Tips:</strong> scale - 1 will be good<br /><strong>Training model:</strong> NAI<br /><strong>Used to generation model:</strong> AOM3<br /><strong>Keywords:</strong> tape gag<br /></p><p>If u know how to improve model, let me know</p>",
type:  "LORA",
poi:  false,
nsfw:  false,
allowNoCredit:  true,
allowCommercialUse:  "None",
allowDerivatives:  true,
allowDifferentLicense:  true,
stats:  {
downloadCount:  5846,
favoriteCount:  1022,
commentCount:  4,
ratingCount:  9,
rating:  5,
tippedAmountCount:  13509
},
creator:  {
username:  "DWeoss",
image:  "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/371b7118-4cf3-42b4-17af-83bbb627d300/width=96/DWeoss.jpeg"
},
tags:  [
0:  "anime" ,
1:  "concept" ,
2:  "hentai"
],
modelVersions:  [
]
}
```

and this is metadata inside lora file itself:
```json
ss_tag_frequency:  {
8_Good:  303,
6_CloseUp:  68,
4_NotBad:  245
},
```

there is no **"tape gag"** in either. 
if you wish to contribute, prs are welcome. otherwise, this issue is closed and do not open second issue just because you're not happy with first one - that is really bad manners.

**Comment by Fectopos** [comment]
> i cannot verify every single lora that author mislabels. and to make it worse, you never provided a link to it.
> 
> i found v1.0 eventually, v1.1 you mentioned is NOT on civitai.
> 
> this is metadata provided by author:
> 
> ```json
>  {
> id:  30113,
> name:  "Tape Gag",
> description:  "<p><strong>v1.0</strong><br />A simple LoRA model that allows you to put a tape gag on your character. Works with LoRA character models. The screenshots (if they pass moderation) show characters such as Lucy from Edgerunners, Prinz Eugen from Azure Lane and Marikawa Shizuka from High School of Dead.<br /><br /><strong>Tips:</strong> scale - 1 will be good<br /><strong>Training model:</strong> NAI<br /><strong>Used to generation model:</strong> AOM3<br /><strong>Keywords:</strong> tape gag<br /></p><p>If u know how to improve model, let me know</p>",
> type:  "LORA",
> poi:  false,
> nsfw:  false,
> allowNoCredit:  true,
> allowCommercialUse:  "None",
> allowDerivatives:  true,
> allowDifferentLicense:  true,
> stats:  {
> downloadCount:  5846,
> favoriteCount:  1022,
> commentCount:  4,
> ratingCount:  9,
> rating:  5,
> tippedAmountCount:  13509
> },
> creator:  {
> username:  "DWeoss",
> image:  "https://image.civitai.com/xG1nkqKTMzGDvpLrqFT7WA/371b7118-4cf3-42b4-17af-83bbb627d300/width=96/DWeoss.jpeg"
> },
> tags:  [
> 0:  "anime" ,
> 1:  "concept" ,
> 2:  "hentai"
> ],
> modelVersions:  [
> ]
> }
> ```
> 
> and this is metadata inside lora file itself:
> 
> ```json
> ss_tag_frequency:  {
> 8_Good:  303,
> 6_CloseUp:  68,
> 4_NotBad:  245
> },
> ```
> 
> there is no **"tape gag"** in either.
> 
> and you can see all that in lora details.
> 
> if you wish to contribute, prs are welcome. otherwise, this issue is closed and do not open second issue just because you're not happy with first one - that is really bad manners.

what i mean is that the automatic 1111 recognises the "tape gag" trigger word and vladmandic doesnt and i just wondered if it would be possible to do that because otherwise loras wont work

**Comment by Woisek** [comment]
@Fectopos You can just add the trigger word(s) by yourself from where you downloaded the LoRA. You don't need to relay on something that is not really responsible for it.
It's not like this would be such an incredible, tremendous task to do ...

**Comment by Fectopos** [comment]
> @Fectopos You can just add the trigger word(s) by yourself from where you downloaded the LoRA. You don't need to relay on something that is not really responsible for it. It's not like this would be such an incredible, tremendous task to do ...

ik ik but i just wonder if theres a way to do automatic just like in auto1111, some trigger words are irrelevant, for example i have loras where the trigger words are "a" or "img"

**Comment by vladmandic** [comment]
if trigger words are in metadata, they are displayed. if they are not, i cannot invent them. in this particular lora, i've actually gone extra length to show that's all there is in metadata. so show me where should i get info from? lora you've pointed to is not available and closest to it has correct trigger words.

this is too much discussion for something you've just provided screenshots for (and created second issue). i'm out.
