### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by Fectopos** [vladmandic/automatic#2624]
### Issue Description

i found that trigger words doesnt work like in auto1111, with the same lora the auto1111 has a lot of activation words that in vladmandic shows wrongly or isn't accurate for example
![image](https://github.com/vladmandic/automatic/assets/153838087/595fec16-47b0-43f4-812e-b4db270c22e1)

this lora in auto1111 show that his activation words are "tape gag" wich matches the activation word from the civitai lora
now in vladmandic it shows this words wich are incorrect
![image](https://github.com/vladmandic/automatic/assets/153838087/d5aaa018-7e3a-4d6b-b3cd-85758113ca02)
and in many loras doesnt show the real activation words so its more difficult to make the lora work like it should be

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
- enter valid TITLE
- add link to lora in question
- link to discussion thread so history is known

**Comment by vladmandic** [comment]
you've created a feature request and we're having a conversation there, so you think that creating an issue in parallel will speed it up???
