### ISSUE TITLE
[Feature]: secondary sampler function "same as first"

### ISSUE THREAD

**Issue by Xeltosh** [vladmandic/automatic#2626]
### Feature description

i would love to have the option on second sampler, that it uses the same sampler for the second pass, as it has used on the first generation.

**Comment by Disty0** [comment]
Set it to Default?

**Comment by vladmandic** [comment]
like disty said. or set it to whatever you want - its not that difficult to set both samplers to anything you want.

**Comment by Xeltosh** [comment]
i don´t really want to open this again, but why is the default option disappearing, when choosing it once? loading in old pictures via the process tab also overwrites the default option

**Comment by Disty0** [comment]
Diffusers backend:

1) Euler a, first run:

![image](https://github.com/vladmandic/automatic/assets/47277141/bcbf03c0-cea6-49ae-ada5-479409e45732)


2) Euler a - Default

![image](https://github.com/vladmandic/automatic/assets/47277141/a34851bb-37ec-481c-81f1-74fb7d39103a)


3) Euler a - Euler a

![image](https://github.com/vladmandic/automatic/assets/47277141/bf360f0e-70d8-47f5-a123-97ac1eab8bbd)


4) Euler a - DDIM

![21550-780165887-SD1 5-SoteMixV2  cf585bf6df](https://github.com/vladmandic/automatic/assets/47277141/6297c805-f466-49c0-ae7e-844beee929c8)


5) Euler a - PNDM

![image](https://github.com/vladmandic/automatic/assets/47277141/a565d351-5eb8-4054-a4f8-398a9c44ee39)


6) Euler a - Default

![image](https://github.com/vladmandic/automatic/assets/47277141/72d7fe06-5e43-4805-a0d9-916a51ac1dde)

**Comment by Xeltosh** [comment]
i use the original/standard. 

And the cmd says when choosing default "Running DDIM Sampling" every time, regardless of what sampler i have chosen for the first step, it always applies DDIM for second run

**Comment by vladmandic** [comment]
Because in original backend DDIM is default for all SD15 models. Whats the issue? Just set whatever sampler you want!

**Comment by Xeltosh** [comment]
when i use the xyz-script, and want to change the sampler for testing out prompt, the second sampler doesn´t get changed automatically with it. that is my issue i have with it. if on the scond sampler, there would be an option for "using as first" or something like that, that would be nice XD

**Comment by vladmandic** [comment]
ok, i understand now.
valid, but very limited use-case. i can reopen the request if you wish, but i don't see it as prioritized anytime soon.

prs are welcome.

**Comment by Xeltosh** [comment]
if you can get behind it sometime, it would be nice. It´s no pressing matter, but something that bugs me, especially because either A1111 doesn´t use a second sampler like you do, or uses the same as the standard generation.

I don´t know how hard this is to program into your code, but a reference to the first sampler as a chooseable options sounds doable in theory (i only have limited basic programming knowledge)

what does prs mean?

**Comment by vladmandic** [comment]
its not that difficult, just busy at the moment.

pr = pull request = code contribution

**Comment by Tillerz** [comment]
I'd like to have this, too. :)

**Comment by vladmandic** [comment]
done.
