### ISSUE TITLE
[Issue]: Diffusers work only with UniPC sampler

### ISSUE THREAD

**Issue by damnkrat** [vladmandic/automatic#2640]
### Issue Description

Diffusers backend uses UniPC no matter what sampler I choose. Tested in SD 1.5 and SDXL. I think this is related to #2172

### Version Platform Description

21:40:11-873102 INFO     Starting SD.Next                                                                                                                                                                                                   
21:40:11-874971 INFO     Logger: file="/home/dannkunt/stable-diffusion-automatic/sdnext.log" level=INFO size=10106357 mode=append                                                                                                           
21:40:11-875701 INFO     Python 3.11.6 on Linux                                                                                                                                                                                             
21:40:11-887902 INFO     Version: app=sd.next updated=2023-12-19 hash=00281e15 url=https://github.com/vladmandic/automatic/tree/master                                                                                                      
21:40:12-226033 INFO     Platform: arch=x86_64 cpu= system=Linux release=6.6.4-zen3-xanmod1-1 python=3.11.6                                                                                                                                 
21:40:12-227495 INFO     nVidia CUDA toolkit detected: nvidia-smi present                                                                                                                                                                   
21:40:12-237432 WARNING  Modified files: ['scripts/prompt_gallery.py']                                                                                                                                                                      
21:40:12-256551 INFO     Extensions: disabled=[]                                                                                                                                                                                            
21:40:12-257714 INFO     Extensions: enabled=['stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'sd-webui-controlnet', 'sd-dynamic-thresholding', 'LDSR', 'Lora', 
                         'ScuNET', 'sd-extension-chainner', 'multidiffusion-upscaler-for-automatic1111', 'SwinIR', 'sd-webui-agent-scheduler', 'sd-extension-system-info', 'sd-webui-model-converter'] extensions-builtin                   
21:40:12-261323 INFO     Startup: quick launch                                                                                                                                                                                              
21:40:12-261779 INFO     Verifying requirements                                                                                                                                                                                             
21:40:12-272671 INFO     Verifying packages                                                                                                                                                                                                 
21:40:12-273943 INFO     Extensions: disabled=[]                                                                                                                                                                                            
21:40:12-274468 INFO     Extensions: enabled=['stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'sd-webui-controlnet', 'sd-dynamic-thresholding', 'LDSR', 'Lora', 
                         'ScuNET', 'sd-extension-chainner', 'multidiffusion-upscaler-for-automatic1111', 'SwinIR', 'sd-webui-agent-scheduler', 'sd-extension-system-info', 'sd-webui-model-converter'] extensions-builtin                   
21:40:12-275662 INFO     Running in safe mode without user extensions                                                                                                                                                                       
21:40:12-277441 INFO     Extension preload: {'extensions-builtin': 0.0}                                                                                                                                                                     
21:40:12-278372 INFO     Command line args: ['--listen', '--insecure', '--safe'] insecure=True listen=True safe=True                                                                                                                        
21:40:14-841810 INFO     Load packages: torch=2.1.1+cu121 diffusers=0.24.0 gradio=3.43.2                                                                                                                                                    
21:40:15-244572 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda mode=no_grad device=cuda cross-optimization="Scaled-Dot-Product"                                                                                                    
21:40:15-264811 INFO     Device: device=NVIDIA GeForce RTX 3060 n=1 arch=sm_90 cap=(8, 6) cuda=12.1 cudnn=8902 driver=535.146.02                                                                                                            

### Relevant log output

```shell
2023-12-20 21:41:24,871 | sd | DEBUG | txt2img | txt2img: id_task=task(7g8hpoam5frygo6)|prompt=a woman|negative_prompt=[deformed | disfigured], poorly drawn, [bad : wrong] anatomy, [extra | missing | floating | disconnected] limb, (mutated hands and fingers), blurry|prompt_styles=[]|steps=99|sampler_index=5|latent_index=0|full_quality=True|restore_faces=False|tiling=False|n_iter=1|batch_size=1|cfg_scale=6|clip_skip=2|seed=-1.0|subseed=-1.0|subseed_strength=0|seed_resize_from_h=0|seed_resize_from_w=0||height=960|width=544|enable_hr=False|denoising_strength=0.5|hr_scale=2|hr_upscaler=None|hr_force=False|hr_second_pass_steps=20|hr_resize_x=0|hr_resize_y=0|image_cfg_scale=6|diffusers_guidance_rescale=0.7|refiner_steps=5|refiner_start=0.8|refiner_prompt=|refiner_negative=|override_settings_texts=[]
2023-12-20 21:41:24,872 | sd | WARNING | sd_models | Token merging not supported with HyperTile for UNet
2023-12-20 21:41:24,873 | sd | INFO | sd_hijack_freeu | Applying free-u: b1=1.2 b2=1.4 s1=0.9 s2=0.2
2023-12-20 21:41:24,873 | sd | INFO | sd_hijack_hypertile | Applying hypertile: unet=256
2023-12-20 21:41:25,417 | sd | DEBUG | processing_diffusers | Diffuser pipeline: StableDiffusionPipeline task=DiffusersTaskType.TEXT_2_IMAGE set={'prompt_embeds': torch.Size([1, 77, 768]), 'negative_prompt_embeds': torch.Size([1, 77, 768]), 'guidance_scale': 6, 'generator': device(type='cuda'), 'output_type': 'latent', 'num_inference_steps': 99, 'eta': 1.0, 'guidance_rescale': 0.7, 'height': 960, 'width': 544, 'parser': 'Full parser'}
2023-12-20 21:41:25,418 | sd | DEBUG | sd_samplers | Sampler: sampler="Euler a" config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon'}
2023-12-20 21:41:33,575 | sd | DEBUG | shared_state | Requested interrupt
2023-12-20 21:41:33,580 | sd | INFO | processing_diffusers | Interrupted...
2023-12-20 21:41:33,949 | sd | INFO | processing | Processed: images=0 time=9.07 its=0.00 memory={'ram': {'used': 4.2, 'total': 125.7}, 'gpu': {'used': 3.86, 'total': 11.75}, 'retries': 0, 'oom': 0}
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
provide some proof of the statement you made "diffusers only work with unipc sampler"
because exact log you provided shows:

> Sampler: sampler="Euler a" config={'num_train_timesteps': 1000, 'beta_start': 0.00085, 'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon'}

and then you interrupted the generate.

**Comment by damnkrat** [comment]
![изображение](https://github.com/vladmandic/automatic/assets/32395839/c439171e-3608-4430-bc0a-89558848cc61)

**Comment by vladmandic** [comment]
unipc is the only sampler with stylized progress bar for a different reason, lets not go there right now.

first, start with `--safe`, you have tons of extensions that are interfering, lets rule that out.
and run with standard resolution - rule when troubleshooting is to MINIMIZE number of variables. then you go back to whatever you want to use. better yet, reset configuration. don't run with 99 steps, etc. entire thing is impossible to follow.

second, i still have no idea what "only works" means? what is the output with "unipc" vs for example "euler a"

**Comment by vladmandic** [comment]
closing as no information provided. will reopen if new information is added.
