### ISSUE TITLE
[Fix for] ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor' torchvision 0.17 problem

### ISSUE THREAD

**Issue by onlyreportingissues** [vladmandic/automatic#2643]
### Issue Description

In my case the fix helped me to get Reactor extension working.

The problem: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13985

The fix: https://github.com/XPixelGroup/BasicSR/pull/650#discussion_r1418875403

Maybe it can be implemented.

### URL link of the extension

https://github.com/Gourieff/sd-webui-reactor

### URL link of the issue reported in the extension repository

https://github.com/Gourieff/sd-webui-reactor/issues/241

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
I've already added that to dev branch, try it out.
