### ISSUE TITLE
[Issue]: Variation seed/strength does not work properly in Diffusers backend

### ISSUE THREAD

**Issue by jeditobe1** [vladmandic/automatic#2644]
### Issue Description

If I select the Diffusers backend, setting the variation strength seems to have little to no effect.  Even setting the strength to 1 (which to my knowledge should make the variations entirely unrelated) produces the same image.

Note - testing using Dreamshaper 8, which is a 1.5 model.  The same model did not have the issue on the original backend.

Simple repro steps:
- Start server in diffusers backend mode
- Open browser
- Prompt: A man standing in front of a red car
- 512x512 size
- Sampler = UniPC, 20 steps, Karras scheduling, low order,
- Batch Count = 5, Batch Size = 1
- Seed = 0, Variation Seed = 0, Variation Strength = 1
- Generate

All 5 images generated appear almost identical.  Generation info for each image shows a different variation seed (0, 1, 2, etc)

For comparison to original backend, same settings except:
- Sampler = UniPC, 20 steps, Karras scheduling, discard ultimate sigma

First image generated on original backend looks like all images generated on diffusers.  All other images look substantially different.

### Version Platform Description

Starting SD.Next
Logger: file="/automatic/sdnext.log" level=DEBUG size=64 mode=create
Python 3.10.11 on Linux
Version: app=sd.next updated=2023-12-19 hash=00281e15  url=https://github.com/vladmandic/automatic.git/tree/master
Platform: arch=x86_64 cpu= system=Linux release=5.15.133.1-microsoft-standard-WSL2 python=3.10.11
nVidia CUDA toolkit detected: nvidia-smi present

Startup: standard
Verifying requirements
Verifying packages
Verifying submodules
Extensions enabled: ['sd-extension-chainner','stable-diffusion-webui-images-browser','sd-webui-controlnet', 'sd-webui-agent-scheduler','stable-diffusion-webui-rembg', 'Lora','sd-extension-system-info', 'adetailer','sd-webui-infinite-image-browsing','stable-diffusion-webui-wildcards']

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by jeditobe1** [comment]
I did some digging through the repo with my limited knowledge of python when trying to investigate the above, and my understanding shows that processing_diffusers.py only considers the main seed when creating its random number generator.

Without knowing more about the libraries involved, its possible this is just a feature that is not possible/intended for this backend, in which case it being available on the UI for the backend is the more proper bug rather than it not working.

**Comment by vladmandic** [comment]
that is correct - variation seed is implemented in orginal backend by manually modifying initial noise .
in diffusers backend, noise generation is fully a gpu task. it would be possible to use same algorithm to create noise from original backend to diffusers, but right now i have no plans to do so as i don't see a strong enough use-case and it is significantly slower.

in the meantime, i've imemented hide on those controls when running in diffusers backend (its in dev branch).
if you wish to have full implementation of variation seed in diffusers backend, convert this to feature request.
