### ISSUE TITLE
[Extension]: webui main page disappeared

### ISSUE THREAD

**Issue by Ethan-Ming** [vladmandic/automatic#2646]
### Issue Description

**safe mode works**

![image](https://github.com/vladmandic/automatic/assets/36059080/3a17578c-dd9b-4223-b973-ef20c4d28e99)

below are command line output with debug enabled, apparently some plugins is messing with sd.next, BAD
But i can't find which
[output.txt](https://github.com/vladmandic/automatic/files/13760913/output.txt)

### Version Platform Description

windows10

edge

### URL link of the extension

/

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by Ethan-Ming** [comment]
i've found out the culprit is mov2mov

**Comment by vladmandic** [comment]
closing as there is no follow-up from the extension side.
