### ISSUE TITLE
[Extension]: controlnet mediapipe_face model not detect base model correctly

### ISSUE THREAD

**Issue by Ethan-Ming** [vladmandic/automatic#2647]
### Issue Description

i've set pipeline as orginal and using a sd2.x base model
works with orginal a1111

16:05:26-063895 ERROR    Running script process: extensions-builtin\sd-webui-controlnet\scripts\controlnet.py: Exception
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ E:\AUTOMATIC1111\Alt-Frontend\SD_NEXT\automatic\modules\scripts.py:518 in process                                    │
│                                                                                                                      │
│   517 │   │   │   │   args = p.per_script_args.get(script.title(), p.script_args[script.args_f                       │
│ ❱ 518 │   │   │   │   script.process(p, *args, **kwargs)                                                             │
│   519 │   │   │   except Exception as e:                                                                             │
│                                                                                                                      │
│ E:\AUTOMATIC1111\Alt-Frontend\SD_NEXT\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:1053 in │
│ process                                                                                                              │
│                                                                                                                      │
│   1052 │   │   if not Script.process_has_sdxl_refiner(p):                                                            │
│ ❱ 1053 │   │   │   self.controlnet_hack(p)                                                                           │
│   1054 │   │   return                                                                                                │
│                                                                                                                      │
│ E:\AUTOMATIC1111\Alt-Frontend\SD_NEXT\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:1042 in │
│ controlnet_hack                                                                                                      │
│                                                                                                                      │
│   1041 │   │   t = time.time()                                                                                       │
│ ❱ 1042 │   │   self.controlnet_main_entry(p)                                                                         │
│   1043 │   │   if len(self.enabled_units) > 0:                                                                       │
│                                                                                                                      │
│ E:\AUTOMATIC1111\Alt-Frontend\SD_NEXT\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:750 in  │
│ controlnet_main_entry                                                                                                │
│                                                                                                                      │
│    749 │   │   │   Script.bound_check_params(unit)                                                                   │
│ ❱  750 │   │   │   Script.check_sd_version_compatible(unit)                                                          │
│    751                                                                                                               │
│                                                                                                                      │
│ E:\AUTOMATIC1111\Alt-Frontend\SD_NEXT\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:702 in  │
│ check_sd_version_compatible                                                                                          │
│                                                                                                                      │
│    701 │   │   if sd_version != cnet_sd_version:                                                                     │
│ ❱  702 │   │   │   raise Exception(f"ControlNet model {unit.model}({cnet_sd_version}) is not co                      │
│    703                                                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Exception: ControlNet model control_v2p_sd21_mediapipe_face [6e0c43ab](StableDiffusionVersion.SD2x) is not compatible
with sd model(StableDiffusionVersion.SD1x)

### Version Platform Description

win10
edge browser

### URL link of the extension

https://huggingface.co/CrucibleAI/ControlNetMediaPipeFace

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed in dev branch, will be merged to master in the next release.
