### ISSUE TITLE
fooocus not working on Intel UHD Graphic 630..[Issue]: 

### ISSUE THREAD

**Issue by Jachimeq** [vladmandic/automatic#2648]
### Issue Description

Is there any possibility to work with fooocus on Intel Graphic 630? I have 8GB RAM and 4GB VRAM on this graphic card which is less requirement to work with this software. Any ideas?

### Relevant log output

Found no NVIDIA driver on your system

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
Is this Foocus repo??

**Comment by Jachimeq** [comment]
I'm literal noob here, installed a fooocus, unzipped runned a bat file and after that i got an annouce of 'Found no NVIDIA driver on your system' there is a complex idea to run a program on this requirements and components?

**Comment by vladmandic** [comment]
Go ask Fooocus team, this is a different app!
