### ISSUE TITLE
[Issue]: Image Info does not display newlines

### ISSUE THREAD

**Issue by a2ZxgdqHeSs8F51cIyuK** [vladmandic/automatic#2655]
### Issue Description

Same issue again.
See #2549 for examples.

### Version Platform Description

Version: app=sd.next updated=2023-12-19 hash=00281e15

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
It's fixed, update.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Reusing the example image from the other issue:
![00000-1793358884-best quality 1girl blonde light smile 1 0](https://github.com/vladmandic/automatic/assets/111918717/f9b529ca-a9ee-4246-bacb-bf5ef7e6c8b5)
This is the prompt, using newlines to separate prompts in a logical way (this has no effect on generation, it's purely for readability and to easily grab chunks of the prompt to reuse in other prompts)
![image](https://github.com/vladmandic/automatic/assets/111918717/becdddf0-da80-40d7-92cd-dc66dda200e7)
This is how it shows up in image processing now, it ignores the newlines:
![image](https://github.com/vladmandic/automatic/assets/111918717/3df9f451-0bb7-45c8-a36d-125857959e7e)

**Comment by vladmandic** [comment]
and you cropped part just above it which DOES show prompt in original form.
params at the bottom are presented in compact form and i see no reason to change that.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
What? No I didn't, why would I even do that? What would that get me?
![image](https://github.com/vladmandic/automatic/assets/111918717/076fe6d7-3919-4df0-ac86-c8dec7945b82)

**Comment by vladmandic** [comment]
ah, ok, so in process tab.
this is in text tab for example:
![image](https://github.com/vladmandic/automatic/assets/57876960/d726533d-57e9-44c4-934b-3c5b2bc70513)

and thats why its critical that you note exact workflow.
stating "same issue as xxx" is not helpful.

**Comment by vladmandic** [comment]
fixed in dev.
bottom part should be as-is, but top-part was not showing correctly in processing tab.
![image](https://github.com/vladmandic/automatic/assets/57876960/44f7ff66-a3dc-454a-bf1d-0f7cb993a155)
