### ISSUE TITLE
[Feature]: Controlnet needs its own output folder

### ISSUE THREAD

**Issue by gruevy** [vladmandic/automatic#2657]
### Issue Description

ControlNet outputs are currently placed in the 'save' folder, instead of the 'text' or 'extras' folders like you'd imagine. There is no directory setting for controlnet to change this behavior.

### Version Platform Description

brave, win11

### Relevant log output

```shell
NA
```

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev branch, i'll plan a service-release soon.
