### ISSUE TITLE
[Feature]: --ckpt-dir and --lora-dir

### ISSUE THREAD

**Issue by doodooextinction** [vladmandic/automatic#266]
### Feature description

How do I set my model directories? I plan on using more than one fork but don't want hundreds of GBs of duplicate models.

**Comment by vladmandic** [comment]
ui -> settings -> system paths

**Comment by doodooextinction** [comment]
Much love!

**Comment by curtwagner1984** [comment]
> ui -> settings -> system paths

Was just about to ask this, but did the responsible thing and made a search before posting. 

One thing though, it won't allow you to start without having at least one ckpt. So you can't modify system paths or access the UI, unless you copy at least one model to `automatic\models\Stable-diffusion`.

It would have been great if this was also a command-line argument in `webui.bat`. Or if there was a command line argument that let's you run the webui even though you have no models just so you can set them up.
