### ISSUE TITLE
[Feature]: Clear the search field when clicking between LORA and Checkpoint

### ISSUE THREAD

**Issue by mattehicks** [vladmandic/automatic#2660]
### Feature description

The text in the search field remains populated with whatever labels or folder name I selected, even when moving between tabs [lora  | lycoris | checkpoint | etc ]

Thanks!

![image](https://github.com/vladmandic/automatic/assets/859222/41b83263-a28d-4a01-846c-9b53fe471e15)

version: [## 1.4.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/%3Cnone%3E)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.20  •  gradio: 3.32.0  •  checkpoint: [e5ea559010](https://google.com/search?q=e5ea559010dae2d1cc511649d0440716e3a92469b9c1fa75ab2a05e0c5373fc3)

**Comment by vladmandic** [comment]
i actually like the current behavior as i can search for something and then check each network type for results.
clearing manually is easier than re-typing it.

**Comment by mattehicks** [comment]
How about an 'X' button, so I can clear the search, without having to hit my keyboard?
Most of my navigation is done via mouse, so this is the one/only thing that causes me to have to reach for the keyboard during my workflow.  Seriously, it would be a huge improvement :)

**Comment by vladmandic** [comment]
click `ALL` - its already there.
