### ISSUE TITLE
[Issue]: Control output resolution is not the input resolution by default

### ISSUE THREAD

**Issue by Sunsphire** [vladmandic/automatic#2664]
### Issue Description

While using the new Control module the output resolution is not the same as input resolution by default (as it should be based on Wiki article). It defaults to 512x512 and using Resize by 1 doesn't work (I guess it resize the 512x512 by 1 instead of the input size). 

Not a huge deal, until it's solved we can manually input the width and height.

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev branch, i'll plan a service-release soon.
