### ISSUE TITLE
[Issue]:  IPEX initialization failed: module 'intel_extension_for_pytorch.xpu' has no attribute 'get_device_id_list_per_card'

### ISSUE THREAD

**Issue by perfectnewer** [vladmandic/automatic#2665]
### Issue Description

`get_device_id_list_per_card` and `getDeviceIdListForCard` was deleted: https://github.com/intel/intel-extension-for-pytorch/commit/132759108fea0be04a296a5a4bb58a85f002a154#diff-55919ecb0542e8854370c45de00f68f5b96e63d6b290de703562e7c947810b43

09:10:13-818282 ERROR    IPEX initialization failed: module 'intel_extension_for_pytorch.xpu'
                         has no attribute 'get_device_id_list_per_card'

### Version Platform Description

09:44:41-441773 INFO     Starting SD.Next
09:44:41-445313 INFO     Logger: file="/home/simon/automatic/sdnext.log" level=DEBUG size=64
                         mode=create
09:44:41-446734 INFO     Python 3.10.12 on Linux
09:44:41-465601 INFO     Version: app=sd.next updated=2023-12-19 hash=00281e15
                         url=https://github.com/vladmandic/automatic/tree/master
09:44:42-432297 INFO     Latest published version: c77505fa6f35fd4540abfbe9b2d326b299203461
                         2023-12-29T17:14:09Z
09:44:42-437380 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux
                         release=5.15.133.1-microsoft-standard-WSL2 python=3.10.12
09:44:42-441321 DEBUG    Setting environment tuning
09:44:42-443049 DEBUG    Cache folder: /home/simon/.cache/huggingface/hub
09:44:42-444342 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False
                         openvino=False
09:44:42-446091 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
09:44:58-216119 DEBUG    Extensions all: []
09:44:58-217204 INFO     Extensions enabled: ['Lora', 'sd-webui-controlnet',
                         'stable-diffusion-webui-rembg', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'sd-extension-system-info',
                         'sd-extension-chainner']

### Relevant log output

```shell
09:10:13-818282 ERROR    IPEX initialization failed: module 'intel_extension_for_pytorch.xpu'
                         has no attribute 'get_device_id_list_per_card'
```

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Disty0** [comment]
Update your webui.
