### ISSUE TITLE
[Issue]: Img2img sampler index is off by 1

### ISSUE THREAD

**Issue by afbagwell** [vladmandic/automatic#2676]
### Issue Description

When you choose a sampling method in the drop down menu on the Img2img tab, it uses the next sampler (+1) in the list. This is recorded in the metadata of the generated image. If you choose the last sampling method in the list, Img2img fails with an error "list index out of range".

<img width="1912" alt="Screenshot 2024-01-02 001954" src="https://github.com/vladmandic/automatic/assets/1495201/7a23adf0-a4f7-4020-a0f9-3dd8866d0e5f">

### Version Platform Description

00:16:38-646173 INFO     Starting SD.Next
00:16:38-648013 INFO     Logger: file="/home/afbag/sdnext/sdnext.log" level=INFO size=14007561 mode=append
00:16:38-648624 INFO     Python 3.10.12 on Linux
00:16:38-654629 INFO     Version: app=sd.next updated=2023-12-30 hash=ab7b78cc
                         url=git@github.com:vladmandic/automatic.git/tree/master
00:16:38-956109 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=5.15.133.1-microsoft-standard-WSL2
                         python=3.10.12
00:16:38-968566 INFO     nVidia CUDA toolkit detected: nvidia-smi present
00:16:38-987548 WARNING  Modified files: ['scripts/detect_extension.py']
00:16:38-988584 INFO     Startup: standard
00:16:38-989026 INFO     Verifying requirements
00:16:38-996105 INFO     Verifying packages
00:16:38-997399 INFO     Verifying submodules
00:16:57-030121 ERROR    Error running git: extensions/sd-dynamic-prompts / pull origin main --rebase --force
00:16:57-031131 ERROR    Local changes detected: check log for details: /home/afbag/sdnext/sdnext.log
00:16:57-846573 INFO     Extensions enabled: ['Lora', 'sd-webui-agent-scheduler', 'stable-diffusion-webui-rembg', 'sd-extension-chainner',
                         'stable-diffusion-webui-images-browser', 'clip-interrogator-ext', 'sd-webui-controlnet', 'sd-extension-system-info',
                         'sd-dynamic-thresholding', 'sd-webui-inpaint-anything', 'a1111-mini-paint', 'ultimate-upscale-for-automatic1111',
                         'canvas-zoom', 'sd-webui-segment-anything', 'adetailer', 'sd-webui-reactor-force', 'sd-webui-regional-prompter',
                         'sd-dynamic-prompts', 'openpose-editor', 'sd-webui-aspect-ratio-helper']
00:16:57-847857 INFO     Verifying requirements
00:16:57-856256 INFO     Updating Wiki
00:16:58-208484 WARNING  Setup complete with errors: 1
00:16:58-209403 WARNING  See log file for more details: /home/afbag/sdnext/sdnext.log
00:16:58-212753 INFO     Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
00:16:58-213636 INFO     Command line args: ['--upgrade'] upgrade=True
00:17:00-928069 INFO     Load packages: torch=2.1.0+cu121 diffusers=0.25.0 gradio=3.43.2
00:17:01-340667 INFO     Engine: backend=Backend.ORIGINAL compute=cuda mode=no_grad device=cuda cross-optimization="Scaled-Dot-Product"
00:17:01-365447 INFO     Device: device=NVIDIA GeForce RTX 4090 n=1 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8906 driver=546.29
00:17:03-765358 INFO     Available VAEs: path="/mnt/d/AiApps/StableDiffusion/sd15-models/VAE" items=3
00:17:03-766510 INFO     Disabled extensions: []
00:17:03-965544 INFO     Available models: path="/mnt/d/AiApps/StableDiffusion/sd15-checkpoints" items=55 time=0.20
00:17:04-428637 INFO     Extension: script='scripts/faceid.py' [2;36m00:17:04-427398[0m[2;36m [0m[1;31mERROR   [0m FaceID: No module named
                         [32m'ip_adapter'[0m
00:17:04-875577 INFO     Extension: script='extensions-builtin/sd-webui-agent-scheduler/scripts/task_scheduler.py' Using sqlite file:
                         extensions-builtin/sd-webui-agent-scheduler/task_scheduler.sqlite3
00:17:04-958971 INFO     Extension: script='extensions-builtin/sd-webui-controlnet/scripts/api.py' ControlNet preprocessor location:
                         /home/afbag/sdnext/extensions-builtin/sd-webui-controlnet/annotator/downloads
00:17:05-014321 INFO     Extension: script='extensions-builtin/sd-webui-controlnet/scripts/controlnet.py' Warning: ControlNet failed to load SGM -
                         will use LDM instead.
00:17:05-019181 INFO     Extension: script='extensions-builtin/sd-webui-controlnet/scripts/hook.py' Warning: ControlNet failed to load SGM - will use
                         LDM instead.
00:17:06-155932 INFO     Extension: script='extensions/adetailer/scripts/!adetailer.py' [-] ADetailer initialized. version: 23.12.0, num models: 14
00:17:06-192547 INFO     Extension: script='extensions/sd-dynamic-thresholding/scripts/dynamic_thresholding.py' ======
00:17:06-193347 INFO     Extension: script='extensions/sd-dynamic-thresholding/scripts/dynamic_thresholding.py' Warning! Using legacy KDiff version!
                         Is your WebUI up to date?
00:17:06-193901 INFO     Extension: script='extensions/sd-dynamic-thresholding/scripts/dynamic_thresholding.py' ======
00:17:06-451936 INFO     Extensions time: 2.36 { sdnext=0.35 clip-interrogator-ext=0.15 Lora=0.08 sd-webui-agent-scheduler=0.19
                         sd-webui-controlnet=0.15 stable-diffusion-webui-images-browser=0.15 stable-diffusion-webui-rembg=0.34 adetailer=0.63
                         sd-webui-inpaint-anything=0.13 sd-webui-segment-anything=0.06 }
00:17:06-789777 INFO     Load UI theme: name="black-teal" style=Dark base=sdnext.css
00:17:08-891905 INFO     Local URL: http://127.0.0.1:7860/

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev, will be included in the next release.
