### ISSUE TITLE
[Issue]: KeyError in gradio blocks after reloading UI and trying to read generation parameters

### ISSUE THREAD

**Issue by hollowstrawberry** [vladmandic/automatic#268]
### Issue Description

Steps to reproduce:

1. Launch the program.
2. Read generation parameters, either from the button in the txt2img tab or from the image browser. It should work fine.
3. Reload UI from the settings tab or from the extensions tab
4. Read generation parameters again. This causes the following error and freezes the UI.

```
Traceback (most recent call last):
  File "D:\sd-automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\sd-automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "D:\sd-automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 342
```

Both parts of this issue are fixed by restarting the program completely.

This happens with all extensions disabled except the ones without a URL.

### Version Platform Description

Version: e6701f5c Wed Apr 19 14:12:19 2023 -0400

Firefox, Windows 10

**Comment by Smokyish** [comment]
And what this means is that after starting the app, after you hit Generate once, it stops working. So can only do one generation, after which you need to completely restart everything to do another, the Generate button is just frozen and nothing happens. This started happening in the past couple of days.
