### ISSUE TITLE
[Feature]: Add Scripts Dropdown List for the Control Tab

### ISSUE THREAD

**Issue by Machinekng** [vladmandic/automatic#2686]
### Feature description

Currently, both the Text and Image tab have a drop down list to select relevant scripts, like "X/Y/Z grid", "SD Upscale" and others. In the original backend, several of this scripts were powerful when combined with ControlNet such as using "X/Y/Z grid" to identify the best pre-processor/ControlNet choice, or using the Tile ControlNet combined with an upscaling script to perform more accurate upscaling at higher denoising levels.

### Version Platform Description

Version
app: SD.next
updated: 2023-12-30
hash: ab7b78cc
url: https://github.com/vladmandic/automatic/tree/master

Platform
arch: AMD64
cpu: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.11.5

GPU 
device: NVIDIA GeForce RTX 3080 (1) (sm_90) (8, 6)
cuda: 12.1
cudnn: 8801
driver: 546.01

Browser
Mozilla Firefox

**Comment by vladmandic** [comment]
absolutely - its planned.

**Comment by vladmandic** [comment]
done in dev branch, will be part of the next release.
