### ISSUE TITLE
[Issue]: inpaint mask with upload not working

### ISSUE THREAD

**Issue by cirbani** [vladmandic/automatic#2692]
### Issue Description

Hello, I am not a programmer, not a bit, only little bit tech savy, so please be patient with me...

After a fresh install I tried to test the Inpain feature. For some reasons it looks like the UI is ignoring the mask, or better said, it looks like it doesn't send the mask to the AI for processing. The resulting image always comes out either with only the noise generated in the mask, or without any change. the image outside the mask seems to be processed correctly. I also tried inpaint upload, the result was the same. Log also shows no error.

The first image I tried had a resolution of 512x512, then I tried a larger image with a resolution of 1532x2048, which I manual scaled in PS down to 576x768. The resolution had no effect on the result.

I have already tried to reinstall the whole SD several times with updates of all necessary dependencies (also with --debug command), changing location on the disk, reinstaling python and GIT, nothing helped. It looks like the bug of UI.

Do you have any ideas how to make it work?

**Settings**

I've tried quite a wide range of possible settings with always the same results.

base model: dreamshaper_8 Inpainting (ac84e05d50) ... but not working whith any tested model (juggernaut reborn, dreamshaper 8)
prompt: gigachad
sampling method: default (but tested with Euler, Euler a, DPM2, DPM 2a with same results)
sampling steps: 20 (but tested up to 35 with same results)
CFG scale: 4 (but tested with numbers up to 13 with same results
full quality option checked (tested with unchecked too)
denoising strength: 0,5 (tested from 0,1 to 0,99 with same results)

resize metod: nearest
resize mode: crop
resize to 576x768 (original resolution of the picture)

mask blur: 4
masked contemt: original
mask padding: 32
mask mode: in the picture

As you can see from the picture, masked area is always filled with the noise. Area outside of the mask seems to work fine with prompt and adequate CFG scale.

![dsg](https://github.com/vladmandic/automatic/assets/155904752/ed3635ea-9514-4065-a9d9-0d2bc47655b8)
)

### Version Platform Description

app: SD.next
updated: 2023-12-30
hash: ab7b78cc

**Platform**

arch: AMD64
cpu: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.10.6

GPU
backend: directml
ASRock Steel Legend AMD RX 7800 XT
driver version 23.20.30

browser
Google chrome 

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by xedis** [comment]
No log included so i have no way of knowing all the configuration setings but......

Use FP32 precision and --no-half --no-half-vae settings. 

![image](https://github.com/vladmandic/automatic/assets/4144634/a2ee3dde-87cc-474a-b506-a69c34535a33)

**Comment by cirbani** [comment]
Thx, it looks like that it works for Inpainting itself, but Inpaint upload still gives this result anyways:

![00071-dreamshaper_8Inpainting-gigachad](https://github.com/vladmandic/automatic/assets/155904752/e7277166-0f80-481b-b281-826739915e5e)

**Comment by vladmandic** [comment]
just to confirm, inpaint works if you draw a mask, but it doesn't if you upload a mask?

**Comment by cirbani** [comment]
yup. After changing to FP32, normal Inpaint start works as it shoulf, but if i try to put external mask with picture (same resolution) in Inpaint uplod, the result looks like mentioned picture.

**Comment by vladmandic** [comment]
if you're refering to this, i believe its already fixed in dev branch.
![image](https://github.com/vladmandic/automatic/assets/57876960/5b2b5c94-fb39-4c29-8610-e0ef28b9aa51)

**Comment by cirbani** [comment]
I'm not sure if we're talking about exact same issue, but yes, it occurs inse Inpaint upload.
![hgkhglkhgljg](https://github.com/vladmandic/automatic/assets/155904752/53323736-6da8-4abc-82d7-f4d4ad573cc7)

**Comment by vladmandic** [comment]
yes, mask cropping was using invalid coordinates.

**Comment by cirbani** [comment]
OK, thx for help
