### ISSUE TITLE
[Issue]: TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by Xeltosh** [vladmandic/automatic#2695]
### Issue Description

sporadically i get this random error:
gradio call: TypeError                                
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\call_queue.py:31 in f    │
│                                                                             │
│   30 │   │   │   try:                                                       │
│ > 31 │   │   │   │   res = func(*args, **kwargs)                            │
│   32 │   │   │   │   progress.record_results(id_task, res)                  │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\txt2img.py:88 in txt2img │
│                                                                             │
│   87 │   if processed is None:                                              │
│ > 88 │   │   processed = processing.process_images(p)                       │
│   89 │   p.close()                                                          │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\processing.py:760 in     │
│ process_images                                                              │
│                                                                             │
│    759 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p) │
│ >  760 │   │   │   │   res = process_images_inner(p)                        │
│    761                                                                      │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\processing.py:894 in     │
│ process_images_inner                                                        │
│                                                                             │
│    893 │   │   │   if shared.backend == shared.Backend.ORIGINAL:            │
│ >  894 │   │   │   │   uc = get_conds_with_caching(modules.prompt_parser.ge │
│    895 │   │   │   │   c = get_conds_with_caching(modules.prompt_parser.get │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\processing.py:851 in     │
│ get_conds_with_caching                                                      │
│                                                                             │
│    850 │   │   with devices.autocast():                                     │
│ >  851 │   │   │   cache[1] = function(shared.sd_model, required_prompts, s │
│    852 │   │   cache[0] = (required_prompts, steps)                         │
│                                                                             │
│                          ... 24 frames hidden ...                           │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\extensions\sd-webui-additional-networks\scripts\lora_compvis.py:91 in    │
│ forward                                                                     │
│                                                                             │
│    90 │   │   if self.mask_dic is None:                                     │
│ >  91 │   │   │   return self.org_forward(x) + self.lora_up(self.lora_down( │
│    92                                                                       │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\extensions\sd-webui-additional-networks\scripts\lora_compvis.py:91 in    │
│ forward                                                                     │
│                                                                             │
│    90 │   │   if self.mask_dic is None:                                     │
│ >  91 │   │   │   return self.org_forward(x) + self.lora_up(self.lora_down( │
│    92                                                                       │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\extensions\sd-webui-additional-networks\scripts\lora_compvis.py:91 in    │
│ forward                                                                     │
│                                                                             │
│    90 │   │   if self.mask_dic is None:                                     │
│ >  91 │   │   │   return self.org_forward(x) + self.lora_up(self.lora_down( │
│    92                                                                       │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\extensions\sd-webui-additional-networks\scripts\lora_compvis.py:91 in    │
│ forward                                                                     │
│                                                                             │
│    90 │   │   if self.mask_dic is None:                                     │
│ >  91 │   │   │   return self.org_forward(x) + self.lora_up(self.lora_down( │
│    92                                                                       │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\extensions-builtin\Lora\networks.py:374 in network_Linear_forward        │
│                                                                             │
│   373 │   network_apply_weights(self)                                       │
│ > 374 │   return originals.Linear_forward(self, input)                      │
│   375                                                                       │
└─────────────────────────────────────────────────────────────────────────────┘
TypeError: 'NoneType' object is not callable

At the beginning i thought it was because of the "additional-networks" extension i used. Sometimes i got it after some pictures, sometimes i could generate for several hours without any error whatsoever, so i don't really know what causes the error besides that it is most likely Lora related.

So i first just ticked it not active in the txt2img-tab and called Loras the normal way, had no problems and generated pictures for around 2 hours nonstop. I thought than, that this could have been the problem and i deactivated the extension and restarted SD.next. I entered my prompts and got the random error again. Extension is still installed though, but i somehow doubt, that it being passively in the files would still cause an error, but i am not sure.

I know basics about code and troubleshooted most errors myself so far, but with this, i can't make any sense.
Restarting the program does normally help, but as described, the error happens randomly for me, sometimes, when the error happens while in an endless generation, keeping it running on endless sometimes get's rid of the error after some iterations of the error.

The Error looks like this, when the Extension is deactivated and not actively loaded:

gradio call: TypeError                                
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\call_queue.py:31 in f    │
│                                                                             │
│   30 │   │   │   try:                                                       │
│ > 31 │   │   │   │   res = func(*args, **kwargs)                            │
│   32 │   │   │   │   progress.record_results(id_task, res)                  │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\txt2img.py:88 in txt2img │
│                                                                             │
│   87 │   if processed is None:                                              │
│ > 88 │   │   processed = processing.process_images(p)                       │
│   89 │   p.close()                                                          │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\processing.py:760 in     │
│ process_images                                                              │
│                                                                             │
│    759 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p) │
│ >  760 │   │   │   │   res = process_images_inner(p)                        │
│    761                                                                      │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\processing.py:894 in     │
│ process_images_inner                                                        │
│                                                                             │
│    893 │   │   │   if shared.backend == shared.Backend.ORIGINAL:            │
│ >  894 │   │   │   │   uc = get_conds_with_caching(modules.prompt_parser.ge │
│    895 │   │   │   │   c = get_conds_with_caching(modules.prompt_parser.get │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\processing.py:851 in     │
│ get_conds_with_caching                                                      │
│                                                                             │
│    850 │   │   with devices.autocast():                                     │
│ >  851 │   │   │   cache[1] = function(shared.sd_model, required_prompts, s │
│    852 │   │   cache[0] = (required_prompts, steps)                         │
│                                                                             │
│                          ... 17 frames hidden ...                           │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\venv\lib\site-packages\torch\nn\modules\module.py:1527 in _call_impl     │
│                                                                             │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hook │
│ > 1527 │   │   │   return forward_call(*args, **kwargs)                     │
│   1528                                                                      │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:371 in  │
│ forward                                                                     │
│                                                                             │
│    370 │   │                                                                │
│ >  371 │   │   hidden_states = self.layer_norm1(hidden_states)              │
│    372 │   │   hidden_states, attn_weights = self.self_attn(                │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\venv\lib\site-packages\torch\nn\modules\module.py:1518 in                │
│ _wrapped_call_impl                                                          │
│                                                                             │
│   1517 │   │   else:                                                        │
│ > 1518 │   │   │   return self._call_impl(*args, **kwargs)                  │
│   1519                                                                      │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\venv\lib\site-packages\torch\nn\modules\module.py:1527 in _call_impl     │
│                                                                             │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hook │
│ > 1527 │   │   │   return forward_call(*args, **kwargs)                     │
│   1528                                                                      │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\extensions-builtin\Lora\networks.py:410 in network_LayerNorm_forward     │
│                                                                             │
│   409 │   network_apply_weights(self)                                       │
│ > 410 │   return originals.LayerNorm_forward(self, input)                   │
│   411                                                                       │
└─────────────────────────────────────────────────────────────────────────────┘
TypeError: 'NoneType' object is not callable

### Version Platform Description

happened for me on both of my systems: 
- Windows 11, with AMD RX7800XT, Ryzen 7 7800X3D, 32 GB DDR5 Ram
- WIndows 10, with NVidia RTX3050, Intel Core i3-10105F, 16 GB DDR4 Ram

I use Firefox in both.
SD.Next is installed via Stability Matrix in both cases

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
Remove addional networks extension, it's not necessary and obsolete for months now. It's causing a conflict.

**Comment by Xeltosh** [comment]
ok, will do. hopefully the error doesn't occur anymore. is there something else like it out there?

**Comment by vladmandic** [comment]
like what? which feature do you absolutely need that you don't have without it already?

**Comment by Xeltosh** [comment]
i liked it, how easy a lora strength was variable with the x/y/z script with this extension, that's all^^

btw, i uninstalled the extension, i got an error again after some hours, but it happened right after i restarted the server via the button in the extension tab...

gradio call: TypeError                                
┌───────────────────── Traceback (most recent call last) ─────────────────────┐
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\call_queue.py:31 in f    │
│                                                                             │
│   30 │   │   │   try:                                                       │
│ > 31 │   │   │   │   res = func(*args, **kwargs)                            │
│   32 │   │   │   │   progress.record_results(id_task, res)                  │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\txt2img.py:88 in txt2img │
│                                                                             │
│   87 │   if processed is None:                                              │
│ > 88 │   │   processed = processing.process_images(p)                       │
│   89 │   p.close()                                                          │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\processing.py:760 in     │
│ process_images                                                              │
│                                                                             │
│    759 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p) │
│ >  760 │   │   │   │   res = process_images_inner(p)                        │
│    761                                                                      │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\extensions-builtin\sd-webui-controlnet\scripts\batch_hijack.py:42 in     │
│ processing_process_images_hijack                                            │
│                                                                             │
│    41 │   │   │   # we are not in batch mode, fallback to original function │
│ >  42 │   │   │   return getattr(processing, '__controlnet_original_process │
│    43                                                                       │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web UI\modules\processing.py:894 in     │
│ process_images_inner                                                        │
│                                                                             │
│    893 │   │   │   if shared.backend == shared.Backend.ORIGINAL:            │
│ >  894 │   │   │   │   uc = get_conds_with_caching(modules.prompt_parser.ge │
│    895 │   │   │   │   c = get_conds_with_caching(modules.prompt_parser.get │
│                                                                             │
│                          ... 18 frames hidden ...                           │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\venv\lib\site-packages\torch\nn\modules\module.py:1527 in _call_impl     │
│                                                                             │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hook │
│ > 1527 │   │   │   return forward_call(*args, **kwargs)                     │
│   1528                                                                      │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\venv\lib\site-packages\transformers\models\clip\modeling_clip.py:371 in  │
│ forward                                                                     │
│                                                                             │
│    370 │   │                                                                │
│ >  371 │   │   hidden_states = self.layer_norm1(hidden_states)              │
│    372 │   │   hidden_states, attn_weights = self.self_attn(                │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\venv\lib\site-packages\torch\nn\modules\module.py:1518 in                │
│ _wrapped_call_impl                                                          │
│                                                                             │
│   1517 │   │   else:                                                        │
│ > 1518 │   │   │   return self._call_impl(*args, **kwargs)                  │
│   1519                                                                      │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\venv\lib\site-packages\torch\nn\modules\module.py:1527 in _call_impl     │
│                                                                             │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hook │
│ > 1527 │   │   │   return forward_call(*args, **kwargs)                     │
│   1528                                                                      │
│                                                                             │
│ C:\StabilityMatrix\Packages\SD.Next Web                                     │
│ UI\extensions-builtin\Lora\networks.py:410 in network_LayerNorm_forward     │
│                                                                             │
│   409 │   network_apply_weights(self)                                       │
│ > 410 │   return originals.LayerNorm_forward(self, input)                   │
│   411                                                                       │
└─────────────────────────────────────────────────────────────────────────────┘
TypeError: 'NoneType' object is not callable

**Comment by vladmandic** [comment]
do a full restart from command line. lets not make issue more complicated than it needs to be.

**Comment by Xeltosh** [comment]
yeah, i have it directly after that, because i thought it might be the restart at fault here. Have to run some stuff to see, if the error still happens, or if it was a freak accident

**Comment by vladmandic** [comment]
i'll close this for now, if the issue reoccurs update here and i'll reopen as needed.
