### ISSUE TITLE
[Issue]: Control - Control processor error: multiple values for argument 'pretrained_model_or_path'

### ISSUE THREAD

**Issue by solsol360** [vladmandic/automatic#2698]
### Issue Description

In Control tab: When selecting Zoe Depth as ControlNet processor and then selecting Normal Bae causes error. There might be also other combinations when this happens.

TypeError: NormalBaeDetector.from_pretrained() got multiple values for argument 'pretrained_model_or_path'

Multiple processors stop working after this, but for example Canny still works.
EDIT: Just to note that Normal Bae and all other processors load correctly in normal scenarios, but fails after some processors with extra args(?)  

Debug Log: [sdnext.log](https://github.com/vladmandic/automatic/files/13866098/sdnext.log)

Note: flags: ['SD_CONTROL_DEBUG=true', 'SD_PROCESS_DEBUG=true'] didn't capture the traceback so I took that from the console directly

### Version Platform Description

Python 3.10.11 on Windows
Version: app=sd.next updated=2023-12-30 hash=ab7b78cc url=https://github.com/vladmandic/automatic.git/tree/master
Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows release=Windows-10-10.0.22631-SP0 python=3.10.11

### Relevant log output

```shell
22:36:10-236722 DEBUG    Control processor loading: id="Zoe Depth" class=ZoeDetector
22:36:10-237719 TRACE    Control processor config={'cache_dir': 'models\\control\\processor',
                         'pretrained_model_or_path': 'halffried/gyre_zoedepth', 'filename': 'ZoeD_M12_N.safetensors',
                         'model_type': 'zoedepth'}
22:36:13-601928 DEBUG    Control processor loaded: id="Zoe Depth" class=ZoeDetector time=3.37
22:36:20-032049 DEBUG    Control processor loading: id="Normal Bae" class=NormalBaeDetector
22:36:20-033095 TRACE    Control processor config={'cache_dir': 'models\\control\\processor',
                         'pretrained_model_or_path': 'halffried/gyre_zoedepth', 'filename': 'ZoeD_M12_N.safetensors',
                         'model_type': 'zoedepth'}
22:36:20-034107 ERROR    Control processor load failed: id="Normal Bae" error=NormalBaeDetector.from_pretrained() got
                         multiple values for argument 'pretrained_model_or_path'
22:36:20-035416 ERROR    Control processor load: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ F:\automatic\modules\control\processors.py:175 in load                                                               │
│                                                                                                                      │
│   174 │   │   │   elif config[processor_id]['checkpoint']:                                                           │
│ ❱ 175 │   │   │   │   self.model = cls.from_pretrained("lllyasviel/Annotators", **self.load_co                       │
│   176 │   │   │   else:                                                                                              │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: NormalBaeDetector.from_pretrained() got multiple values for argument 'pretrained_model_or_path'
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev, will be included in the next release
