### ISSUE TITLE
[Issue]: Stable-fast compile failed on Windows

### ISSUE THREAD

**Issue by banjaminicc** [vladmandic/automatic#2699]
### Issue Description

While I understand the error is clearly stated, I thought it would work since explicit support was mentioned in changelog?

![image](https://github.com/vladmandic/automatic/assets/25388581/383ec9d6-d6ba-49f0-8d07-e2cba8953d75)

### Version Platform Description

Windows 11
RTX 3060
Torch 2.0.1
CUDNN 8700

### Relevant log output

```shell
22:25:45-338636 INFO     Compiling pipeline=DiffusionWrapper mode=stable-fast
22:25:45-339909 WARNING  Model compile not supported: Windows not yet supported for torch.compile
```

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by banjaminicc** [comment]
If I update torch to 2.1.2 and stable-fast to use torch 2.1.2 I obtain a new error
```
23:14:52-512461 WARNING  Model compile not supported: Invalid backend: 'stable-fast', see
                         `torch._dynamo.list_backends()` for available backends.
[2024-01-08 23:14:52,512] sd: [WARNING] Model compile not supported: Invalid backend: 'stable-fast', see `torch._dynamo.list_backends()` for available backends.
```

**Comment by banjaminicc** [comment]
After completing a full reinstall with xformer wheels from Facebook and triton wheels build
I get this
```
Model compile: task=Stable-fast error: 'NoneType' object is not iterable
```

**Comment by vladmandic** [comment]
> While I understand the error is clearly stated, I thought it would work since explicit support was mentioned in changelog?

SD.Next does support its usage. But which combinations of compile are supported by underlying platform is not up to SD.Next.
There are huge number of combinations possible and not every combination is possible on every platform.
