### ISSUE TITLE
[Issue]: Batch processing - use original name - name doubled and zeroes added

### ISSUE THREAD

**Issue by Neoony** [vladmandic/automatic#2702]
### Issue Description

I wanted to process many files through upscaler and I needed to output it to another folder with the exact same names.

Using these settings:
Add number to filename when saving - disabled
Use original name during batch process - enabled
Images filename pattern - empty

if a file was named 
1.png

The output would be 
1-1-0000-.png

So it adds dashes and duplicates the name and then it adds the 0000 without the last number, as "Add number to filename when saving" is disabled.

I could not find any workaround inside SD.Next

it should only produce a file like 1.png

I definitely had output set to a different folder than the source folder

----
Workaround:
Currently I got the workaround from gpt-4-1106-preview
To rename it back to original with a batch file

Have to place it to the folder with the output images and run it

```
@echo off
setlocal enableDelayedExpansion

for /r %%f in (*-*-0000-.png) do (
	set "filename=%%~nf"
	set "extension=%%~xf"
	set "pathname=%%~dpf"

	:: Find the position of the first dash from the right
	set "dashpos=0"
	for /l %%a in (1,1,100) do (
		set /a "dashpos=!dashpos!+1"
		if "!filename:~-!dashpos!,1!"=="-" (
			set /a "dashpos=!dashpos!-5"  :: Account for -0000
			goto :rename
		)
	)

	:rename
	set "newname=!filename:~0,-!dashpos!!extension!"

	if not exist "!pathname!!newname!" (
		echo Renaming "%%f" to "!newname!"
		ren "%%f" "!newname!"
	) else (
		echo Conflict: "!newname!" already exists.
	)
)

echo Renaming complete.
pause
:end
```

### Version Platform Description

Windows 10 Pro 64bit
DirectML 
18:14:19-193281 INFO     Starting SD.Next
18:14:19-196733 INFO     Logger: file="H:\Programs\StableDiffusion\automatic-directml2\sdnext.log" level=INFO
                         size=8221831 mode=append
18:14:19-197735 INFO     Python 3.10.11 on Windows
18:14:19-546081 INFO     Version: app=sd.next updated=2023-12-30 hash=ab7b78cc
                         url=https://github.com/vladmandic/automatic.git/tree/master
18:14:19-871569 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.11
18:14:19-874572 INFO     Using DirectML Backend
18:14:19-986177 WARNING  Modified files: ['scripts/run_n_times.py']
18:14:20-081341 INFO     Extensions: disabled=['sd-webui-controlnet']
18:14:20-082342 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
18:14:20-089274 INFO     Extensions: enabled=['adetailer', 'deforum-for-automatic1111-webui', 'sd-dynamic-prompts',
                         'sd-webui-prompt-all-in-one', 'sd-webui-text2video', 'ultimate-upscale-for-automatic1111']
                         extensions

### Backend

Diffusers

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev, will be included in the next release.

**Comment by Neoony** [comment]
Thanks a lot.

Just a note
The script to rename back is not 100%

It starts to fail when some filenames have a lot of dashes

**Comment by vladmandic** [comment]
Could be, haven't actually looked at your script.
But you can test dev branch now if you want.

**Comment by Neoony** [comment]
its just a note in case someone would for some reason find/use the script
dont need you to look at it :P

yep, I will definitely try it on the dev branch, thx

**Comment by Neoony** [comment]
Just tested few
works great and name is the same 
❤️
