### ISSUE TITLE
[Feature]: TPU support

### ISSUE THREAD

**Issue by Zxneric** [vladmandic/automatic#2704]
### Feature description

https://huggingface.co/docs/diffusers/using-diffusers/stable_diffusion_jax_how_to
Diffuser makes it possible to create image with Google TPU.

**Comment by cooperdk** [comment]
I don't think the Web UI was ever designed for TPU...

**Comment by vladmandic** [comment]
In theory, it's doable, but I don't time/resources.
Contributions are welcome.

**Comment by makao007** [comment]
TPU support now in 2026 ?
@vladmandic

**Comment by vladmandic** [comment]
I'd need a test environment with TPU...
