### ISSUE TITLE
[Issue]: Error when using Dynamic Thresholding and Diffusers Backend

### ISSUE THREAD

**Issue by a2ZxgdqHeSs8F51cIyuK** [vladmandic/automatic#2705]
### Issue Description

This was happening on my old install, and it kept happening on the clean install I have done after the latest big update.
Now to test it I have backed up and removed config and ui-config and started with clean ones, only changes are to get an XL model loaded and the DT extension enabled.
Extensions other than DT are not active.
Cleared log file to start clean, debug mode enabled.
Let's start with a simple test output without DT. Quality is low but that doesn't matter, output comes out and is coherent. I set the sampler to DPM++ 2M but I tested others too
![00010-animagine-xl-3 0-best quality 1girl smug sweater pants feet out](https://github.com/vladmandic/automatic/assets/111918717/3ba99049-1540-4b17-96cb-aa93b8bcac87)

Now I enable DT. I don't change any settings so output should look awful, but it should still give me something.
Instead it errors out with " 'DiffusionSampler' object has no attribute 'model_wrap_cfg' "
Full log, only edited out the profile name: 
[Cleaned.sdnext.log](https://github.com/vladmandic/automatic/files/13907020/Cleaned.sdnext.log)

Trying with UniPC gives a different error. DDIM instead says it's not compatible with DT, doesn't use it and gives an output.
I tried messing with various settings without success.

I can't find a straight answer but from my searches I think DT should work on the diffusers backed?
Note: The example image is using an SDXL model, but I get the error if I use diffusers and a 1.5 model too.
DT works normally on original backend + 1.5 model.

### Version Platform Description

Version: app=sd.next updated=2023-12-30 hash=ab7b78cc
url=https://github.com/vladmandic/automatic/tree/master
Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
release=Windows-10-10.0.22621-SP0 python=3.10.11

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
first, dynamic thresholding is an extension, so next time please file an issue using correct template.
anyhow, dynamic thresholding works by directly patching an execution pipeline - and that is only available in backend original. use of any such extension in backend diffusers is not supported.

but on the other hand, you don't need dynamic thresholding in diffusers mode since built-in functionalities such as guidance rescale (available in advanced menu) serve a very similar purpose.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Sorry I did the wrong issue type, I'm a bit... out of sorts lately.
SDXL only works in diffusers? I tried to get it to run on original but have not been able to.
I did try guidance rescale but even maxed it works up to CFG 14 or so, by comparison DT works perfectly at CFG 30 and beyond. Granted it does feel like SDXL really doesn't like high CFG, on 1.5 a CFG of 14 is on the upper end of what you can do without DT, on SDXL in my tests I had to go down to 6 or so without guidance rescale.

**Comment by vladmandic** [comment]
guidance rescale is more subtle, yes.
re: diffusers - diffusers support many different model types. i don't plan to add support to original backend other than existing sd15/sd21. basically, most of new development is focused on diffusers backend which is now much more feature rich. original backend remains primarily for compatibility purposes.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
I have tried diffusers many times since it's been introduced, but I always go back to original very fast because I can't live without DT and setting the CFG really high (I even set it past the limit of 30 in the config file for 1.5).
I have a A1111 install configured to use the same models, loras and outputs folders, might set that up for when I want to play with SDXL and keep this fork set-up for 1.5 since I do like it more.

**Comment by vladmandic** [comment]
of course you're free to do whatever you wish, but note that cfg above 30 is considered undefined in the concept of stable diffusion. this has nothing to do with backend or implementation or fork.
