### ISSUE TITLE
[Issue]: Diffusers Backend - Noticeable colour difference when inpainting

### ISSUE THREAD

**Issue by a2ZxgdqHeSs8F51cIyuK** [vladmandic/automatic#2708]
### Issue Description

I've been trying the diffusers backend again, last time I did there was no FreeU if I recall correctly. With it after some fiddling I've been getting good results.
I'm noticing very visible seams when inpainting though, with noticeably different color. I'm not sure if this is an actual issue, or if there's some setting I missed. I already have the "Apply color correction" setting enabled, without it the issue is much worse.

So let's see how it works on ORIGINAL first.
Simple example output:
![00001-3142563824-best quality 1girl blonde blue eyes smirk victorian](https://github.com/vladmandic/automatic/assets/111918717/d2a099bc-8ae6-400a-80eb-75bbd1a45fca)
Now I take this to Img2Img and do a pretty extreme inpaint of the head at 0.6, using the whole image at resize 1 (this is just for the test, the issue on diffusers happens on "Only masked" inpaints too). Quality doesn't matter, the important thing is how the colours mesh at the edges of the inpaint area.
![image](https://github.com/vladmandic/automatic/assets/111918717/1d8d28b1-51d1-43f0-bb11-88770d51fcce)
Let's see what happened:
![00002-1455383667-best quality 1girl blonde blue eyes smirk victorian](https://github.com/vladmandic/automatic/assets/111918717/59666283-9dd3-4d8b-acf2-34eff36e390e)
The colors are just a tiny little bit off if you know where to look, but it's minimal. I could do an img2img at 0.3 or 0.35 and that would make it invisible.

Now, let's switch to DIFFUSERS.
Simple example output:
![00005-1766130868-best quality 1girl blonde blue eyes smirk victorian](https://github.com/vladmandic/automatic/assets/111918717/ce09a2d2-b1ee-414d-af7f-dc4ebe16a5e0)
Same as before, I do a 0.6 inpaint of the head. I am intentionally going over several colours and the sky, since they make the issue more noticeable.
![image](https://github.com/vladmandic/automatic/assets/111918717/715f950f-a4d2-4511-874c-6a0c7a86e2c7)
And the result:
![00006-1277678797-best quality 1girl blonde blue eyes smirk victorian](https://github.com/vladmandic/automatic/assets/111918717/77a3db96-01c0-46df-a579-830261456018)
Even disregarding the neck/hair area since it changed a lot (does denoise work different on diffusers?) there's still a very visible off colour seam in the sky on the left.

This behaviour doesn't always happen, but it's quite frequent. Doesn't need to be a high denoise either, I've had very visible seams even on 0.35 or 0.4 inpaints, sometimes quite a bit worse than the test image.
A very high Mask blur does help hide it, but it is not necessary on the Original backend. I actually thought of trying it as I am writing this issue, didn't come to mind before. But I think it could lead to ugliness when doing inpaints on small areas.
![00008-1277678797-best quality 1girl blonde blue eyes smirk victorian](https://github.com/vladmandic/automatic/assets/111918717/1fdc6568-d482-4032-9d61-cceb10cc0824)

As I said, I'm not sure this is even really an issue, but I figured it's worth reporting ( I tried searching but didn't see any recent reports for this issue, just some very old IMG2IMG stuff) in case there's something broken with the color correction on Diffusers, or there's some setting I am missing.

P.S. When will the prompt/metadata issue fix (not displaying newlines) be merged to production? It's been some time. This has nothing to do with this issue, I just figured I might as well ask here rather than open a whole separate topic under discussion.

### Version Platform Description

Version: app=sd.next updated=2023-12-30 hash=ab7b78cc

### Relevant log output

```shell
Issue does not produce any special outputs in logs.
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
try to use dev branch, it has several improvements in inpainting quality compared to last release.
plus few notes:
- inpaint full will always have less visible seam since there is more of input image to initialize from. when you use inpaint masked only, there is less input to initialize noise from, so there is a much bigger chance to have inpainted results different than original. you can mitigate that by increasing padding area
- denoise strength fully works in diffusers, but scale is somewhat different. so 0.5 in original and diffusers may not be exactly the same and you may need to use lower denoise strength.

regarding when is dev going to be merged with master - its pretty much ready, but pending team updating docs. there are soo many new features in the last few releases and its becoming pointless to release new features that people don't know how to use.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Yeah I know inpainting works better if it has more "context" but diffusers at the moment is definitely worse with colour matching. But if it's something that is known that's good.
As for denoise, it feels like the higher it is, the more different it becomes. At lower values (up to about 0.45) it doesn't feel too different, at high values it seems to change more than the original backed. It's not a huge problem, just have to learn what the sweet spots are to inpaint things like hands. Original kept fairly close even up to 0.65 or 0.7, on diffusers at 0.7 it will almost competely go nuts, for example if I'm trying to inpaint a hand it will delete it completely, or turn it into a featureless blob, etc. (this is on full image inpaints).
Concerning the dev branch, how does it work?
Do I do a pull of the dev github and then if I do upgrade it pulls updates from that branch?
Or is there some argument similar/in addition to --upgrade to switch to the dev channel? I tried looking in the documentation but didn't find an explanation for this case, just the general description of how to upgrade.

**Comment by vladmandic** [comment]
you can switch to dev branch live, first do upgrade as usual so you're up-to-date, then
> git checkout dev
to switch to dev branch
> git checkout master
to switch back to master branch

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
And then if I launch with --upgrade it uses the branch it's on automatically?

**Comment by vladmandic** [comment]
Yes.

**Comment by a2ZxgdqHeSs8F51cIyuK** [comment]
Alright, thank you.
