### ISSUE TITLE
[Feature]: Support TensorRT

### ISSUE THREAD

**Issue by morganavr** [vladmandic/automatic#272]
### Feature description

Please consider adding support of TensorRT library to significantly increase image speed generation. 

https://www.reddit.com/r/StableDiffusion/comments/12s76mw/nvidia_just_added_tensorrt_to_huggingface/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

**Comment by myndxero** [comment]
Man I wish I had the patience to understand python, I've reviewed it and any of us technically could do it I think by adding the pipeline directly in the the diffuser and compiling a trained checkpoint? Maybe? The ability to download the dependencies is very straight forward. Unfortunately, I don't know the correct steps, but could maybbe figure it out if I wasn't so tired haha.

Starred most relevant, the others are interesting.
** https://github.com/huggingface/diffusers/tree/main/docs
** https://github.com/huggingface/diffusers/commit/bba1c1de151bf0ff0b47a7b81a8251c3bed1db1f
https://github.com/asfiyab-nvidia/diffusers/tree/dev-tensorrt-pipeline-fix
https://github.com/pytorch/TensorRT

**Comment by myndxero** [comment]
Someone likely will, will keep eye on auto1111 too.

It seems likely just a drag and drop of code to smthg, prob needs to be a model merge type scenario or a control net tab like option? 

Yeah don't burn out on us, you gotta make it to week two at least!

**Comment by ilikenwf** [comment]
I couldn't get it working with the current "fast-stable-diffusion" from volta...I could try their old repo I guess, but Lsmith won't execute here either.

**Comment by myndxero** [comment]
Are these two links helpful at all in regards?

https://github.com/huggingface/diffusers/blob/e0a2bd15f9a1eb0d48a69973a9c7ddb4eabb1a27/examples/community/stable_diffusion_tensorrt_txt2img.py#L27

https://github.com/huggingface/diffusers/blob/e0a2bd15f9a1eb0d48a69973a9c7ddb4eabb1a27/examples/community/README.md?plain=1#L34

**Comment by mnpenner** [comment]
FWIW, I had luck with OneFlow: https://github.com/Oneflow-Inc/oneflow

I can get about 40 it/s on 512x512 images with that on an RTX 3090. I get about 13 it/s on Auto1111's for comparison, but it's a little different because the samplers aren't the same.

**Comment by ilikenwf** [comment]
Interesting. Is that a full fledged application or just an SDK?

**Comment by mnpenner** [comment]
Just an SDK/lib.

**Comment by jwvanderbeck** [comment]
> FWIW, I had luck with OneFlow: https://github.com/Oneflow-Inc/oneflow
> 
> I can get about 40 it/s on 512x512 images with that on an RTX 3090. I get about 13 it/s on Auto1111's for comparison, but it's a little different because the samplers aren't the same.

13it/s??? Ok what am I doing wrong because I don't even get anywhere NEAR that on a1111 or vlad.  I get like 5 or 6 for a 512x768 image.  Yeah 512x512 would be faster but not by that much.

**Comment by mnpenner** [comment]
I don't know, try different samplers. Some are quite a bit faster than others, but some also require more/fewer iterations. But do try with 512x512. 512x768 is an additional 131,072 pixels. Could make a difference.

**Comment by vladmandic** [comment]
Best to use system info tab and run benchmark - then you have actual comparable results.

**Comment by jwvanderbeck** [comment]
[
  [
    "2023-04-29 20:27:15.969191",
    "15.2 / 19.56 / 22.2",
    "updated:2023-04-29 hash:408147d9 url:https://github.com/vladmandic/automatic/tree/master",
    "arch:AMD64 cpu:AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system:Windows release:Windows-10-10.0.22621-SP0 python:3.10.11",
    "torch:2.0.0+cu118 Autocast  half xformers:unavailable accelerate:0.18.0 transformers:4.26.1",
    "device:NVIDIA GeForce RTX 3090 Ti (1) (compute_37) (8, 6) cuda:11.8 cudnn:8700 24GB",
    "sdp none",
    "rpg_V4.safetensors [e04b020012]",
    "agathorn",
    "",
    "25d5b9"
  ]
]

**Comment by vladmandic** [comment]
So you're getting 15its with small batches up to 22its when GPU saturates - nothing wrong with that.

**Comment by TheOnlyHolyMoly** [comment]
adding in: https://github.com/stochasticai/x-stable-diffusion

**Comment by vladmandic** [comment]
closing in favor of #1185
