### ISSUE TITLE
[Issue]: LyCORIS LoRA not working when "LoRA use alternative loading method" is set to true.

### ISSUE THREAD

**Issue by Iaotle** [vladmandic/automatic#2720]
### Issue Description

I was trying to use a LyCORIS LoRA and it wasn't applying at all, turns out the issue was `lora_force_diffusers`. I have been using this ui for a few days, and I have to say, it's nice to have the wiki, but it doesn't cover all the options, and little info is provided without having to dig into the code to figure out what certain options do.

In this case, I believe LoRAs should either be fixed with "alternative loading method", or the UI should let the user know that LoRAs won't take effect when `lora_force_diffusers` is set. Would be nice to add a description for this as well, since it was relatively annoying to track down.

### Version Platform Description

 Python 3.10.12 on Linux
 Version: app=sd.next updated=2023-12-30 hash=ab7b78cc
 Platform: arch=x86_64 cpu=x86_64 system=Linux release=5.15.133.1-microsoft-standard-WSL2
device: NVIDIA GeForce RTX 4090 (1) (sm_90) (8, 9)
cuda: 12.1
cudnn: 8902
driver: 546.33
2.1.2+cu121 Autocast  half

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
that is expected. when you use "alternative method", that basically means use whatever is supported by diffusers and we do not control that.

regarding docs - please do contribute to wiki - that is the only way that it will grow.

**Comment by Iaotle** [comment]
It doesn't really give me any reason to contribute to the project when you close the issue and tell me this is "as expected" when clearly the users of your system (even technically inclined ones) have different expectations. Just adding the sentence into the wiki (or the tooltip) would have taken roughly the same amount of time to the owner of the repo.

The button doesn't explain what it does. Pretty simple fix you can do when you're already working on the platform, and I already made the write-up (and you already did the work on figuring out how to phrase at least half the tooltip).

Probably wasn't your intent, but it comes off very dismissive when you just close an issue immediately like that.

**Comment by vladmandic** [comment]
you're right, i should have added hints as i was providing answer here, its added now.
regarding wiki, i made a choice that wiki should be community driven - i'll always provide answers (either here or in discord server), but its really up to community to contribute to wiki.

**Comment by Iaotle** [comment]
@vladmandic thanks for adding the tooltip! And I understand, it's already hard enough to maintain a repo like this without having to manage the wiki.
