### ISSUE TITLE
[Issue]: Can not allocate nullptr for USM type

### ISSUE THREAD

**Issue by dfmjndm** [vladmandic/automatic#2725]
### Issue Description

Using VENV: C:\SD_OpenVino_test\venv
23:46:26-025321 INFO     Starting SD.Next
23:46:26-037327 INFO     Logger: file="C:\SD_OpenVino_test\sdnext.log" level=INFO size=1149025 mode=append
23:46:26-061326 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 190 Stepping 0, GenuineIntel system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6
23:46:26-072327 INFO     Using OpenVINO
23:46:26-078325 INFO     Startup: skip all
23:46:26-110323 INFO     Extension preload: {'extensions-builtin': 0.01, 'extensions': 0.0}
23:46:26-118322 INFO     Command line args: ['--use-openvino', '--skip-all', '--listen'] listen=True use_openvino=True
                         skip_all=True
23:46:47-081358 INFO     Load packages: torch=2.1.1+cpu diffusers=0.25.0 gradio=3.43.2
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, tensorflow, onnx, openvino
23:46:49-357135 INFO     Engine: backend=Backend.DIFFUSERS compute=openvino mode=no_grad device=cpu
                         cross-optimization="Scaled-Dot-Product"
23:46:49-653974 INFO     Device: device=Intel(R) UHD Graphics (iGPU) openvino=2023.2.0
23:46:57-560966 INFO     Available VAEs: path="models\VAE" items=0
23:46:57-567968 INFO     Disabled extensions: ['sd-webui-controlnet']
23:46:57-583965 INFO     Available models: path="models\Stable-diffusion" items=5 time=0.01
23:47:02-829501 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py'
                         Using sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
C:\SD_OpenVino_test\venv\lib\site-packages\numba\np\ufunc\parallel.py:371: NumbaWarning: The TBB threading layer requires TBB version 2021 update 6 or later i.e., TBB_INTERFACE_VERSION >= 12060. Found TBB_INTERFACE_VERSION = 12020. The TBB threading layer is disabled.
  warnings.warn(problem)
23:47:07-840649 INFO     Extensions time: 9.69 { SD_OpenVino_test=0.78 Lora=2.97 sd-extension-chainner=0.12
                         sd-webui-agent-scheduler=0.79 stable-diffusion-webui-images-browser=0.42
                         stable-diffusion-webui-rembg=1.40 maple-from-fall-and-flower=3.19 }
23:47:08-068648 INFO     Load UI theme: name="black-teal" style=Auto base=sdnext.css
23:47:16-965848 INFO     Local URL: http://localhost:7860/
23:47:16-969842 INFO     Initializing middleware
23:47:17-659467 INFO     [AgentScheduler] Task queue is empty
23:47:17-663437 INFO     [AgentScheduler] Registering APIs
23:47:17-888437 INFO     Startup time: 51.64 { torch=12.55 gradio=8.08 diffusers=0.21 libraries=10.47 extensions=9.69
                         face-restore=0.56 upscalers=0.18 ui-extra-networks=0.48 ui-txt2img=0.06 ui-img2img=0.09
                         ui-control=0.07 ui-train=0.34 ui-interrogate=0.05 ui-settings=0.35 ui-extensions=2.27
                         ui-defaults=0.16 launch=4.98 api=0.16 app-started=0.75 }
23:47:52-978113 INFO     MOTD: N/A
23:48:03-226182 INFO     Browser session: user=None client=192.168.31.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
23:49:58-498512 INFO     Select: model="AnythingV5Ink_ink [a1535d0a42]"
Loading model: C:\SD_OpenVino_test\models\Stable-diffusion\AnythingV5Ink_ink.safetensors ----------- 0.0/2.1 GB -:--:--
23:49:58-706504 INFO     Torch override dtype: no-half set
23:49:58-708532 INFO     Torch override VAE dtype: no-half set
23:49:58-711529 INFO     Setting Torch parameters: device=GPU dtype=torch.float32 vae=torch.float32 unet=torch.float32
                         context=no_grad fp16=False bf16=False
23:49:58-719500 INFO     Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline
                         file="C:\SD_OpenVino_test\models\Stable-diffusion\AnythingV5Ink_ink.safetensors" size=2034MB
23:50:23-312802 INFO     Model compile: pipeline=StableDiffusionPipeline mode=default backend=openvino_fx
                         fullgraph=False unet=True vae=True upscaler=True
23:50:23-360797 INFO     Model compile: time=0.01
23:50:23-382796 INFO     Load embeddings: loaded=0 skipped=0 time=0.00
23:50:23-774762 INFO     Load model: time=24.88 { load=24.88 } native=512 {'ram': {'used': 7.63, 'total': 15.78}}
Progress ?it/s                                              0% 0/20 05:51 ? Base
23:56:16-737230 ERROR    Processing: args={'prompt_embeds': tensor([[[-0.3880,  0.0235, -0.0543,  ..., -0.4902,
                         -0.3059,  0.0648],
                                  [-0.8164, -1.1087,  1.2499,  ..., -0.2932,  1.6838, -0.8731],
                                  [ 0.1381, -0.9475,  0.2078,  ...,  0.0245, -1.4611, -1.3896],
                                  ...,
                                  [ 0.0144, -0.0111, -0.1732,  ..., -1.0326, -0.2516,  0.5246],
                                  [ 0.0058, -0.0105, -0.1771,  ..., -1.0376, -0.2430,  0.5390],
                                  [ 0.0689,  0.0163, -0.1012,  ..., -1.0551, -0.2779,  0.5108]]]),
                         'negative_prompt_embeds': tensor([[[-0.3880,  0.0235, -0.0543,  ..., -0.4902, -0.3059,
                         0.0648],
                                  [-0.3712, -1.4371, -0.4176,  ...,  0.9715,  0.2412, -1.1352],
                                  [-0.4894, -1.4298, -0.3677,  ...,  1.0615,  0.1188, -1.0523],
                                  ...,
                                  [ 0.5859, -0.6160, -0.6387,  ...,  1.5169, -0.9820, -0.1958],
                                  [ 0.5758, -0.6020, -0.6299,  ...,  1.5582, -0.9932, -0.1853],
                                  [ 0.5901, -0.5495, -0.5360,  ...,  1.5179, -0.9608, -0.2279]]]), 'guidance_scale': 4,
                         'generator': [<torch._C.Generator object at 0x00000158103637D0>], 'output_type': 'latent',
                         'callback_on_step_end': <function process_diffusers.<locals>.diffusers_callback at
                         0x00000158107EF6D0>, 'callback_on_step_end_tensor_inputs': ['latents', 'prompt_embeds',
                         'negative_prompt_embeds'], 'num_inference_steps': 20, 'eta': 1.0, 'guidance_rescale': 0.7,
                         'width': 1080, 'height': 1080} Exception from src\inference\src\core.cpp:116:
                         [ GENERAL_ERROR ] [CL ext] Can not allocate nullptr for USM type.

23:56:16-839230 ERROR    Processing: RuntimeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\SD_OpenVino_test\modules\processing_diffusers.py:450 in process_diffusers                                        │
│                                                                                                                     │
│   449 │   │   t0 = time.time()                                                                                      │
│ > 450 │   │   output = shared.sd_model(**base_args) # pylint: disable=not-callable                                  │
│   451 │   │   downcast_openvino(op="base")                                                                          │
│                                                                                                                     │
│ C:\SD_OpenVino_test\venv\lib\site-packages\torch\utils\_contextlib.py:115 in decorate_context                       │
│                                                                                                                     │
│   114 │   │   with ctx_factory():                                                                                   │
│ > 115 │   │   │   return func(*args, **kwargs)                                                                      │
│   116                                                                                                               │
│                                                                                                                     │
│ C:\SD_OpenVino_test\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_stable_diffusion.py:1002   │
│ in __call__                                                                                                         │
│                                                                                                                     │
│   1001 │   │   │   │   # predict the noise residual                                                                 │
│ > 1002 │   │   │   │   noise_pred = self.unet(                                                                      │
│   1003 │   │   │   │   │   latent_model_input,                                                                      │
│                                                                                                                     │
│ C:\SD_OpenVino_test\venv\lib\site-packages\torch\nn\modules\module.py:1518 in _wrapped_call_impl                    │
│                                                                                                                     │
│   1517 │   │   else:                                                                                                │
│ > 1518 │   │   │   return self._call_impl(*args, **kwargs)                                                          │
│   1519                                                                                                              │
│                                                                                                                     │
│ C:\SD_OpenVino_test\venv\lib\site-packages\torch\nn\modules\module.py:1527 in _call_impl                            │
│                                                                                                                     │
│   1526 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                      │
│ > 1527 │   │   │   return forward_call(*args, **kwargs)                                                             │
│   1528                                                                                                              │
│                                                                                                                     │
│                                              ... 13 frames hidden ...                                               │
│ in forward:5                                                                                                        │
│                                                                                                                     │
│ C:\SD_OpenVino_test\modules\intel\openvino\__init__.py:70 in __call__                                               │
│                                                                                                                     │
│    69 │   def __call__(self, *args):                                                                                │
│ >  70 │   │   result = openvino_execute(self.gm, *args, executor_parameters=self.executor_para                      │
│    71 │   │   return result                                                                                         │
│                                                                                                                     │
│ C:\SD_OpenVino_test\modules\intel\openvino\__init__.py:288 in openvino_execute                                      │
│                                                                                                                     │
│   287 │   │   else:                                                                                                 │
│ > 288 │   │   │   compiled = openvino_compile(gm, *args, model_hash_str=model_hash_str, file_n                      │
│   289 │   │   shared.compiled_model_state.compiled_cache[partition_id] = compiled                                   │
│                                                                                                                     │
│ C:\SD_OpenVino_test\modules\intel\openvino\__init__.py:238 in openvino_compile                                      │
│                                                                                                                     │
│   237 │                                                                                                             │
│ > 238 │   compiled_model = core.compile_model(om, device)                                                           │
│   239 │   return compiled_model                                                                                     │
│                                                                                                                     │
│ C:\SD_OpenVino_test\venv\lib\site-packages\openvino\runtime\ie_api.py:543 in compile_model                          │
│                                                                                                                     │
│   542 │   │   return CompiledModel(                                                                                 │
│ > 543 │   │   │   super().compile_model(model, device_name, {} if config is None else config),                      │
│   544 │   │   )                                                                                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: Exception from src\inference\src\core.cpp:116:
[ GENERAL_ERROR ] [CL ext] Can not allocate nullptr for USM type.

23:56:17-516545 INFO     Processed: images=0 time=353.73 its=0.00 memory={'ram': {'used': 5.36, 'total': 15.78}}

what‘s wrong with it？I can’t find a output.

### Version Platform Description

win10   chrome

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
issue description is text - write something, not just dump logs.
