### ISSUE TITLE
[Extension]: Ultimate SD Upscaler failing after upscale process.

### ISSUE THREAD

**Issue by ArtDesignAwesome** [vladmandic/automatic#2728]
### Issue Description

See below for the error I am getting:

Canva size: 6144x6144
Image size: 1536x1536
Scale factor: 4
Upscaling iteration 1 with scale factor 4
15:52:21-583175 INFO     Upscaler loaded: type=ESRGAN model=models\ESRGAN\ESRGAN-NMKD-Siax-4x.pth
Upscaling ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 0:00:00 0:00:07
Tile size: 1024x1024
Tiles amount: 36
Grid: 6x6
Redraw enabled: True
Seams fix mode: NONE
[-] ADetailer: img2img inpainting detected. adetailer disabled.
15:52:30-023045 ERROR    Exception: 'numpy.ndarray' object has no attribute 'convert'
15:52:30-024046 ERROR    Arguments: args=('task(q2wsee3yreykynx)', 0.0, 'dynamic portrait, ((reptile squid ape))
                         (hybrid creature animal) in the jungle, highly detailed, dynamic camera angle, dynamic colors,
                         8k  <lora:add_detail:3.0>  <lora:sd_xl_offset_example-lora_1.0:0.25>', 'worst quality, low
                         quality, normal quality, bad quality, poor quality, lowres, extra fingers, missing fingers,
                         poorly rendered hands, mutation, deformed iris, deformed pupils, watermark, realistic,
                         semi-realistic', [], <PIL.Image.Image image mode=RGBA size=1536x1536 at 0x15D106A0D60>, None,
                         None, None, None, None, None, 40, 10, 4, 1, 1, True, False, False, 1, 1, 5, 7, 0.7, 0, 0, 1,
                         0.33, 2077488937.0, -1.0, 0, 0, 0, 0, 1536, 1536, 1, 0, 'None', 0, 32, 0, None, '', '', '',
                         False, 4, 0.95, False, 1, 1, False, 0.6, 1, [], 12, '', '', 0.5, ['FaceID'], 'FaceID Base', 1,
                         None, True, 128, 4, 1, True, '* `CFG Scale` should be 2 or lower.', True, True, '', '', True,
                         50, True, 1, 0, False, 4, 0.5, 'Linear', 'None', '<p style="margin-bottom:0.75em">Recommended
                         settings: Sampling Steps: 80-100, Sampler: Euler a, Denoising strength: 0.8</p>', 128, 8,
                         ['left', 'right', 'up', 'down'], 1, 0.05, 128, 4, 0, ['left', 'right', 'up', 'down'], False,
                         False, 'positive', 'comma', 0, False, False, '', '<p style="margin-bottom:0.75em">Will upscale
                         the image by the selected scale factor; use width and height sliders to set tile size</p>', 64,
                         0, 2, 14, True, 1, 3, 6, 0.5, 0.1, 'None', 2, True, 1, 0, 0, '', [], 0, '', [], 0, '', [],
                         False, True, False, False, False, False, 0, '<p style="margin-bottom:0.75em">Will upscale the
                         image depending on the selected target size type</p>', 1024, 0, 8, 32, 64, 0.35, 32, 30, True,
                         0, False, 8, 0, 2, 2048, 2048, 4, 'None', 16, 'None', 1, True, 'None', 2, True, 1, 0, True,
                         'none', 0.5, None, False, False, {'ad_model': 'face_yolov8n.pt', 'ad_prompt': '',
                         'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0,
                         'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4,
                         'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4,
                         'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32,
                         'ad_use_inpaint_width_height': True, 'ad_inpaint_width': 1024, 'ad_inpaint_height': 1024,
                         'ad_use_steps': True, 'ad_steps': 45, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7,
                         'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False,
                         'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'Default',
                         'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False,
                         'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None',
                         'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0,
                         'ad_controlnet_guidance_end': 1, 'is_api': ()}, {'ad_model': 'None', 'ad_prompt': '',
                         'ad_negative_prompt': '', 'ad_confidence': 0.3, 'ad_mask_k_largest': 0, 'ad_mask_min_ratio': 0,
                         'ad_mask_max_ratio': 1, 'ad_x_offset': 0, 'ad_y_offset': 0, 'ad_dilate_erode': 4,
                         'ad_mask_merge_invert': 'None', 'ad_mask_blur': 4, 'ad_denoising_strength': 0.4,
                         'ad_inpaint_only_masked': True, 'ad_inpaint_only_masked_padding': 32,
                         'ad_use_inpaint_width_height': False, 'ad_inpaint_width': 512, 'ad_inpaint_height': 512,
                         'ad_use_steps': False, 'ad_steps': 28, 'ad_use_cfg_scale': False, 'ad_cfg_scale': 7,
                         'ad_use_checkpoint': False, 'ad_checkpoint': 'Use same checkpoint', 'ad_use_vae': False,
                         'ad_vae': 'Use same VAE', 'ad_use_sampler': False, 'ad_sampler': 'Default',
                         'ad_use_noise_multiplier': False, 'ad_noise_multiplier': 1, 'ad_use_clip_skip': False,
                         'ad_clip_skip': 1, 'ad_restore_face': False, 'ad_controlnet_model': 'None',
                         'ad_controlnet_module': 'None', 'ad_controlnet_weight': 1, 'ad_controlnet_guidance_start': 0,
                         'ad_controlnet_guidance_end': 1, 'is_api': ()}) kwargs={}
15:52:30-034703 ERROR    gradio call: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\AI\automatic\modules\call_queue.py:31 in f                                                                        │
│                                                                                                                      │
│   30 │   │   │   try:                                                                                                │
│ ❱ 31 │   │   │   │   res = func(*args, **kwargs)                                                                     │
│   32 │   │   │   │   progress.record_results(id_task, res)                                                           │
│                                                                                                                      │
│ C:\AI\automatic\modules\img2img.py:259 in img2img                                                                    │
│                                                                                                                      │
│   258 │   else:                                                                                                      │
│ ❱ 259 │   │   processed = modules.scripts.scripts_img2img.run(p, *args)                                              │
│   260 │   │   if processed is None:                                                                                  │
│                                                                                                                      │
│ C:\AI\automatic\modules\scripts.py:498 in run                                                                        │
│                                                                                                                      │
│   497 │   │   parsed = p.per_script_args.get(script.title(), args[script.args_from:script.args_to])                  │
│ ❱ 498 │   │   processed = script.run(p, *parsed)                                                                     │
│   499 │   │   s.record(script.title())                                                                               │
│                                                                                                                      │
│ C:\AI\automatic\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py:555 in run                 │
│                                                                                                                      │
│   554 │   │   upscaler.add_extra_info()                                                                              │
│ ❱ 555 │   │   upscaler.process()                                                                                     │
│   556 │   │   result_images = upscaler.result_images                                                                 │
│                                                                                                                      │
│ C:\AI\automatic\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py:138 in process             │
│                                                                                                                      │
│   137 │   │   if self.redraw.enabled:                                                                                │
│ ❱ 138 │   │   │   self.image = self.redraw.start(self.p, self.image, self.rows, self.cols)                           │
│   139 │   │   │   self.initial_info = self.redraw.initial_info                                                       │
│                                                                                                                      │
│ C:\AI\automatic\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py:245 in start               │
│                                                                                                                      │
│   244 │   │   if self.mode == USDUMode.LINEAR:                                                                       │
│ ❱ 245 │   │   │   return self.linear_process(p, image, rows, cols)                                                   │
│   246 │   │   if self.mode == USDUMode.CHESS:                                                                        │
│                                                                                                                      │
│ C:\AI\automatic\extensions\ultimate-upscale-for-automatic1111\scripts\ultimate-upscale.py:180 in linear_process      │
│                                                                                                                      │
│   179 │   │   │   │   p.image_mask = mask                                                                            │
│ ❱ 180 │   │   │   │   processed = processing.process_images(p)                                                       │
│   181 │   │   │   │   draw.rectangle(self.calc_rectangle(xi, yi), fill="black")                                      │
│                                                                                                                      │
│ C:\AI\automatic\modules\processing.py:780 in process_images                                                          │
│                                                                                                                      │
│    779 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p):                                         │
│ ❱  780 │   │   │   │   res = process_images_inner(p)                                                                 │
│    781                                                                                                               │
│                                                                                                                      │
│ C:\AI\automatic\modules\processing.py:882 in process_images_inner                                                    │
│                                                                                                                      │
│    881 │   │   with devices.autocast():                                                                              │
│ ❱  882 │   │   │   p.init(p.all_prompts, p.all_seeds, p.all_subseeds)                                                │
│    883 │   │   extra_network_data = None                                                                             │
│                                                                                                                      │
│ C:\AI\automatic\modules\processing.py:1307 in init                                                                   │
│                                                                                                                      │
│   1306 │   │   │   │   self.mask_for_overlay = self.image_mask                                                       │
│ ❱ 1307 │   │   │   │   mask = self.image_mask.convert('L')                                                           │
│   1308 │   │   │   │   crop_region = modules.masking.get_crop_region(np.array(mask), self.inpaint_full_res_padding)  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'numpy.ndarray' object has no attribute 'convert'

### Version Platform Description

17:26:05-269960 INFO     Starting SD.Next
17:26:05-272463 INFO     Logger: file="C:\AI\automatic\sdnext.log" level=INFO size=10458471 mode=append
17:26:05-273464 INFO     Python 3.10.6 on Windows
17:26:05-391355 INFO     Version: app=sd.next updated=2024-01-16 hash=3f85c4af
                         url=https://github.com/vladmandic/automatic.git/tree/dev
17:26:05-572949 INFO     Latest published version: 5fb290f443d5f38a5c9f6e6095aabeab8e3a991d 2024-01-13T13:47:29Z
17:26:05-580483 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.6
17:26:05-583486 INFO     nVidia CUDA toolkit detected: nvidia-smi present
17:26:07-192315 INFO     Extensions: disabled=['sd-webui-controlnet']
17:26:07-193400 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
17:26:07-196914 INFO     Extensions: enabled=['adetailer', 'ultimate-upscale-for-automatic1111'] extensions
17:26:07-200561 INFO     Startup: quick launch
17:26:07-201061 INFO     Verifying requirements
17:26:07-211411 INFO     Verifying packages
17:26:07-212913 INFO     Extensions: disabled=['sd-webui-controlnet']
17:26:07-213914 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
17:26:07-216916 INFO     Extensions: enabled=['adetailer', 'ultimate-upscale-for-automatic1111'] extensions
17:26:07-222945 INFO     Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
17:26:07-223946 INFO     Command line args: ['--listen', '--insecure'] insecure=True listen=True
17:26:09-626307 INFO     Load packages: torch=2.1.2+cu121 diffusers=0.25.0 gradio=3.43.2
17:26:10-191229 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="xFormers" mode=no_grad
17:26:10-245038 INFO     Device: device=NVIDIA GeForce RTX 3090 Ti n=1 arch=sm_90 cap=(8, 6) cuda=12.1 cudnn=8801
                         driver=545.84
17:26:10-813447 INFO     Available VAEs: path="models\VAE" items=6
17:26:10-816950 INFO     Disabled extensions: ['sd-webui-controlnet']
17:26:10-821080 INFO     Available models: path="models\Stable-diffusion" items=7 time=0.00
17:26:11-390999 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
17:26:11-792377 INFO     Extension: script='extensions\adetailer\scripts\!adetailer.py' [-] ADetailer initialized.
                         version: 24.1.1, num models: 9
17:26:11-794879 INFO     Extensions time: 0.79 img2imgalt.py=0.08 sd-webui-agent-scheduler=0.22
                         stable-diffusion-webui-images-browser=0.18 adetailer=0.22
17:26:11-824800 INFO     Load UI theme: name="black-teal" style=Auto base=sdnext.css
17:26:15-983473 INFO     Local URL: http://localhost:7860/
17:26:15-984975 INFO     Initializing middleware
17:26:16-134073 INFO     [AgentScheduler] Task queue is empty
17:26:16-135074 INFO     [AgentScheduler] Registering APIs
17:26:16-503305 INFO     Select: model="JSS_JUGGv8 [0e6c2ccd77]"
17:26:16-541062 INFO     Torch override VAE dtype: no-half set
17:26:16-542564 INFO     Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float32 unet=torch.float16
                         context=no_grad fp16=True bf16=None
17:26:16-544065 INFO     Loading VAE: model=models\VAE\sdxl_vae.safetensors source=settings
17:26:16-545066 INFO     Autodetect: vae="Stable Diffusion XL" class=StableDiffusionXLPipeline
                         file="C:\AI\automatic\models\Stable-diffusion\JSS_JUGGv8.safetensors" size=6617MB
17:26:16-592759 INFO     Autodetect: model="Stable Diffusion XL" class=StableDiffusionXLPipeline
                         file="C:\AI\automatic\models\Stable-diffusion\JSS_JUGGv8.safetensors" size=6617MB
17:26:25-295681 INFO     Load embeddings: loaded=2 skipped=0 time=0.03
17:26:25-592492 INFO     Load model: time=8.79 load=8.79 native=512 {'ram': {'used': 7.8, 'total': 31.9}, 'gpu':
                         {'used': 8.06, 'total': 23.99}, 'retries': 0, 'oom': 0}
17:26:25-596529 INFO     Startup time: 18.37 torch=1.53 gradio=0.83 libraries=1.13 extensions=0.79 face-restore=0.18
                         ui-en=0.21 ui-txt2img=0.22 ui-img2img=0.05 ui-control=0.05 ui-settings=0.19 ui-extensions=1.11
                         ui-defaults=0.07 launch=2.18 api=0.07 app-started=0.44 checkpoint=9.09

### URL link of the extension

https://github.com/Coyote-A/ultimate-upscale-for-automatic1111

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by firedelta4** [comment]
ADetailer falls with the same error message and at the same line.

**Comment by ArtDesignAwesome** [comment]
> ADetailer falls with the same error message and at the same LoC

Same here

**Comment by vladmandic** [comment]
fixed in dev branch.

**Comment by firedelta4** [comment]
That masking change seems to have broken inpainting on diffusers for me.
well not broke it but the quality really suffered where it improved in dev in comparison to master before where you can clearly see boxes around faces or hands you fixed with ADetailer again

**Comment by vladmandic** [comment]
pls create a new issue for inpainting and document it.
