### ISSUE TITLE
All Virtual memory, free disk space, is being used up?

### ISSUE THREAD

**Issue by rvdd1962** [vladmandic/automatic#2732]
### Issue Description

Can someone of the dev. team help me please.

I see that all the availible virtual memory, as free diskspace, is being used by the app. Please tell me how to fix this.

Thx.

![2024-01-18_18-07](https://github.com/vladmandic/automatic/assets/149718040/f2f6c42d-d12f-4011-a9e5-ff9059df0206)
![2024-01-18_18-11](https://github.com/vladmandic/automatic/assets/149718040/596d2593-7324-45ce-8bc0-4cc986c64fb5)
![2024-01-18_18-16](https://github.com/vladmandic/automatic/assets/149718040/20dee305-a665-4319-80cf-fd8c9468e73b)
![2024-01-18_18-20](https://github.com/vladmandic/automatic/assets/149718040/08d8f0fd-c506-4ace-bc5d-031a89b5f04c)

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
python's default memory allocator is pretty bad with garbage collection after items are freed, so memory usage over time appears to grow when in reality its not used by app at all.

i'd suggest to switch to tcmalloc (search on how to install/enable it) instead.

**Comment by rvdd1962** [comment]
Well, it's set that way by default cos it's a development enviroment and i can't change that settings cos i don't have sudo right. Malloc is installed, it doesn't make any change to the amount of virtual memory your app is trying to allocate.
I have had ST Automatic webui app installed, that adressed some 100GB of virtual memory. I replace that app with your nice app, cos i like what you did. So nice work there, it's only that virtual memory allocating i need to solve for now.
Fooocus is using and allocating much less and is running alot faster in processing images, see screencaps. My development enviroment is just CPU's only no GPU's.

So give my some good advice please where i can or need to adjust my settings so your app doesn't eat-up all the system  virtual memory disk space. Thx for your quick responce earlier. Great app, if i can help in any way let me know.
![CPU-16-threads](https://github.com/vladmandic/automatic/assets/149718040/9501c981-b94c-4526-8cd6-203350b8f9e8)
![Better memory preformance](https://github.com/vladmandic/automatic/assets/149718040/df1ac386-7927-4752-858e-4ca94fb1b33c)

**Comment by rvdd1962** [comment]
Created new refresh conda env for automatic. Run a clean install, no luck there. 

Found a good cli though rm -rf ~/automatic. 
Switching back to https://github.com/openvinotoolkit/stable-diffusion-webui.git

**Comment by vladmandic** [comment]
if you're not willing to work on it, closing. why bother reporting the issue then.
