### ISSUE TITLE
[Issue]: UI Not Works Sometimes

### ISSUE THREAD

**Issue by amiremami** [vladmandic/automatic#274]
### Issue Description

Hey thanks for your work. Since yesterday that I have migrated to your script, I noticed a lot of times, when I click on generate, it doesn't work. It won't work even if I refresh the page, nothing will print in console either, I need to close the bat file and execute it again. And it's happening again and again to a degree that it's not possible to easily work with it.

Not sure if these are related:
![image](https://user-images.githubusercontent.com/15929497/233317672-fc6a7aea-642f-4395-8b1d-8dfd1241c2ce.png)

Also, the UI is slow, for example in this scenario, I clicked on FILM and look how long it takes options appear. These issues are related to only me or it's global? [I have 32 Gb ram by the way, geforce 2070]

https://user-images.githubusercontent.com/15929497/233318806-e67334b2-9397-4c28-bd4d-bf9964939c8b.mp4

Thanks

### Version Platform Description

Windows 10 
Chrome Version 112.0.5615.121 (Official Build) (64-bit)
Version: e6701f5c Wed Apr 19 14:12:19 2023 -0400

**Comment by amiremami** [comment]
It seems the issues not exist on Firefox. So, it can be related to chrome generally or my chrome only. You can close the ticket if it's related to me only. Thanks.

**Comment by myndxero** [comment]
It's been awhile since I've browser related issues, but when I did, I was on Brave (chrome based) and a security essentials or something or other extension I had was the culprit. You could take a look at your extensions as that's likely the cause.

Another thing you can try is go to the system info tab and 'send interrupt.' May or may not be helpful, get's me unstuck in some strange situations occasionally in general, same with auto1111's.

**Comment by vladmandic** [comment]
@amiremami that error reported in browser console is 100% from extensions.
and lets separate issues:
- generate not working
- slow ui

for generate not working, read through #208. if it still persists, update here with as much information as possible and i'll reopen.

for slow ui, other me me hating gradio, not much i can do. and a lot of those issues come from extensions which do excessive polling thus overloading the browser.
