### ISSUE TITLE
[Issue]: OS Freeze with high RAM usage

### ISSUE THREAD

**Issue by ConfusedMerlin** [vladmandic/automatic#2743]
### Issue Description

**What is happening**

Shortly said, the OS is freezing up at a certain point during Text2Image generation.
It is NOT completely done; in rare cases, it may recover, after some time, but only to freeze on the very next try. 

The behavior of the OS on such events is somewhat comparable with a bash bomb. First nothing to see, then the mouse starts acting up, freezing in place, then music that may play starts to stutter, and finally you end up with a frozen screen. 

**Steps to reproduce**

I do not have an absolute guaranteed way to reproduce that, sadly. But in most cases, I can somehow encourage it to appear by doing the following:

- Have a base model that is a checkpoint merge "Normal" models should do too, but they seem to take longer. For my example I use "toonsushi", as I found out that it is doing well in generating anime like characters without a lot of help an very simple prompts
- enable AdDetailer (currently in 24.1.1); it seems to happen without too, but again, it feels like it accelerates the occurance of the error; no special settings, just enable
- use one or multiple Lora (and even better, keep on switching them in between generations!); for my example; I use "Misty", as it goes  well with the base models style (pair it with "pokegen" to get truly hilarious Fakemon... but that is a topic for another day)
- Now, start on generating... I have no "it takes x generations" or something like this, but as hinted above, the usage of additional lora and frequent switch of them between generations does "help"

And after a while... it just works.... no wait, that was Bethesda. It just happens. 

Okay, I have a bit more data on that. Last time using SD locally, I set up a bunch of monitoring terminal windows at the seconds screen, as I found it inevitable for this error to occur after some time. When it finally happened, I waited for a couple of minutes, saw the TOP update once or twice, but was not able to do anything but hard shut down the system. Also, I made a screnshot... with my phone. 

![auto1111Freeze](https://github.com/vladmandic/automatic/assets/29836528/3180720d-37e7-4032-b4c6-272e431cc858)

As you see, the CPU Usage of the python process is about 200%, and for some reason my Vivaldi browser went amok too. during normal generation, that python process is mostly going up to 100%, and the browser windows stay put. When idle, the python is down to 10%, and everything else is doing 1% and less.... but well, I do have 24 cores, so even all those 200% should be doable.

Still, that is what is looks like when it freezes the OS. 

What else... oh yes! The %MEM value. If I start SD up, it is around... 20 to 30%, but with every generation, with every change of base model and lora, it raises a little. And as far as I have observed, as long as it stays below 90% all is fine. But when it raises above 90%, sh!t hits the fan. Well, the system freezes. I do not have that data on all freezes, but when I had TOP open and was able to look at it, I think it had more than 90% every time it happend. 
Sometimes I can generate houndreds of pictures over hours to come without reaching the limit, but sometimes 30 minutes are all that are needed. I think this somehow ties in if I use a merged base model (bad) or a pure one (good), and the frequency I switch out lora (less is better).

So... I think for now, this is all I can provide. 

Well, there is one little detail that I noticed, which I doubt being of interest, but I shall note it anyway: sometimes Lora and prompts carry over into the next batch of generations, even if removed (the first one). Also, When doing batch gens, I cannot reproduce the seed of a cetain batch picture; it always looks different when done as single generation. But once I batch again, the seed again generates the same picture. But as said, that may be other kinds of bugs.

### Version Platform Description

From Automatics System/System Infopage

**Version**
app: automatic.git
updated: 2024-01-13
hash: 5fb290f4

**Platform**
arch: x86_64 
cpu: x86_64 AMD Ryzen Threadripper 2920X 12-Core
system: Linux, Ubuntu 22.04,
release: 6.2.0-39-generic
python: 3.10.12

**Torch**
2.1.2+rocm5.5 Autocast  half

**GPU**
device: AMD Radeon RX 7600 (1)
hip: 5.5.30201-c1741e9b

**Memory**
ram: free:8.46 used:22.77 total:31.23
gpu: free:3.75 used:4.24 total:7.98
gpu-active: current:0.0 peak:1.74
gpu-allocated: current:0.0 peak:1.74
gpu-reserved: current:3.79 peak:3.79
gpu-inactive: current:0.02 peak:0.63
events: retries:0 oom:0
utilization: 0

**Libs**
xformers: 
diffusers: 0.25.0
transformers: 4.36.2

**Device Info**
active: cuda
dtype: torch.float16
vae: torch.float16
unet: torch.float16

**Backend**
rocm

**Pipeline**
original

**memory optimization**
medvram

**Cross-attention**
Sub-quadratic

**Updated?**
freshly pulled (some days ago), fresh venv (some days ago), had a problem with a missing c++ lib, but that was solved in another issue here. 

### Relevant log output

```shell
22:17:12-026436 INFO     Starting SD.Next                                       
22:17:12-033515 INFO     Logger: file="/opt/ai4/automatic/sdnext.log" level=INFO
                         size=6163441 mode=append                               
22:17:12-035571 INFO     Python 3.10.12 on Linux                                
22:17:12-071133 INFO     Version: app=sd.next updated=2024-01-13 hash=5fb290f4  
                         url=https://github.com/vladmandic/automatic.git/tree/ma
                         ster                                                   
22:17:12-508670 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux          
                         release=6.2.0-39-generic python=3.10.12                
22:17:12-514362 INFO     AMD ROCm toolkit detected                              
22:17:12-860789 INFO     Extensions: disabled=[]                                
22:17:12-862694 INFO     Extensions: enabled=['sd-webui-agent-scheduler',       
                         'stable-diffusion-webui-rembg', 'sd-webui-controlnet', 
                         'sd-extension-chainner', 'sd-extension-system-info',   
                         'stable-diffusion-webui-images-browser', 'Lora']       
                         extensions-builtin                                     
22:17:12-869062 INFO     Extensions: enabled=['adetailer',                      
                         'a1111-sd-webui-lycoris'] extensions                   
22:17:12-872563 INFO     Startup: quick launch                                  
22:17:12-873551 INFO     Verifying requirements                                 
22:17:12-888122 INFO     Verifying packages                                     
22:17:12-890109 INFO     Extensions: disabled=[]                                
22:17:12-890924 INFO     Extensions: enabled=['sd-webui-agent-scheduler',       
                         'stable-diffusion-webui-rembg', 'sd-webui-controlnet', 
                         'sd-extension-chainner', 'sd-extension-system-info',   
                         'stable-diffusion-webui-images-browser', 'Lora']       
                         extensions-builtin                                     
22:17:12-892374 INFO     Extensions: enabled=['adetailer',                      
                         'a1111-sd-webui-lycoris'] extensions                   
22:17:12-900464 INFO     Extension preload: {'extensions-builtin': 0.0,         
                         'extensions': 0.0}                                     
22:17:12-903367 INFO     Command line args: ['--use-rocm', '--medvram']         
                         medvram=True use_rocm=True                             
22:17:18-364730 INFO     Load packages: torch=2.1.2+rocm5.5 diffusers=0.25.0    
                         gradio=3.43.2                                          
22:17:20-587296 INFO     Engine: backend=Backend.ORIGINAL compute=rocm          
                         mode=no_grad device=cuda                               
                         cross-optimization="Sub-quadratic"                     
22:17:20-592384 INFO     Device: device=AMD Radeon RX 7600 n=1                  
                         hip=5.5.30201-c1741e9b                                 
22:17:24-242272 INFO     Available VAEs: path="models/VAE" items=0              
22:17:24-243717 INFO     Disabled extensions: []                                
22:17:24-254390 INFO     Available models: path="models/Stable-diffusion"       
                         items=22 time=0.01                                     
22:17:24-552397 INFO     Extension: script='scripts/faceid.py'                  
                         [2;36m22:17:24-550869[0m[2;36m [0m[1;31mERROR   [0m    
                         FaceID: No module named [32m'insightface'[0m           
22:17:25-637372 INFO     Extension:                                             
                         script='extensions-builtin/sd-webui-agent-scheduler/scr
                         ipts/task_scheduler.py' Using sqlite file:             
                         extensions-builtin/sd-webui-agent-scheduler/task_schedu
                         ler.sqlite3                                            
22:17:25-777148 INFO     Extension:                                             
                         script='extensions-builtin/sd-webui-controlnet/scripts/
                         api.py' ControlNet preprocessor location:              
                         /opt/ai4/automatic/extensions-builtin/sd-webui-controln
                         et/annotator/downloads                                 
22:17:25-852264 INFO     Extension:                                             
                         script='extensions-builtin/sd-webui-controlnet/scripts/
                         controlnet.py' Warning: ControlNet failed to load SGM -
                         will use LDM instead.                                  
22:17:25-859678 INFO     Extension:                                             
                         script='extensions-builtin/sd-webui-controlnet/scripts/
                         hook.py' Warning: ControlNet failed to load SGM - will 
                         use LDM instead.                                       
22:17:27-015154 INFO     Extension:                                             
                         script='extensions/adetailer/scripts/!adetailer.py' [-]
                         ADetailer initialized. version: 24.1.1, num models: 9  
22:17:27-016983 INFO     Extensions time: 2.52 { automatic=0.07 Lora=0.43       
                         sd-webui-agent-scheduler=0.58 sd-webui-controlnet=0.23 
                         stable-diffusion-webui-images-browser=0.21             
                         a1111-sd-webui-lycoris=0.05 adetailer=0.88 }           
22:17:27-083126 INFO     Load UI theme: name="black-teal" style=Auto            
                         base=sdnext.css                                        
22:17:29-433108 INFO     Local URL: http://127.0.0.1:7860/                      
22:17:29-435141 INFO     Initializing middleware                                
22:17:29-664352 INFO     [AgentScheduler] Task queue is empty                   
22:17:29-665467 INFO     [AgentScheduler] Registering APIs                      
22:17:29-830641 INFO     Startup time: 16.90 { torch=4.27 gradio=1.13           
                         libraries=5.88 extensions=2.52 face-restore=0.24       
                         upscalers=0.05 ui-extra-networks=0.47 ui-txt2img=0.12  
                         ui-img2img=0.12 ui-settings=0.22 ui-extensions=0.75    
                         ui-defaults=0.08 launch=0.51 api=0.13 app-started=0.26 
                         }                                                      
22:18:09-844469 INFO     MOTD: N/A                                              
22:18:15-514250 INFO     Browser session: user=None client=127.0.0.1            
                         agent=Mozilla/5.0 (X11; Linux x86_64)                  
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0
                         Safari/537.36                                          
22:27:44-254706 INFO     Select: model="beautifulArt_v70 [a91e177d85]"          
Loading model: /opt/ai4/automatic/models/Stable-diffusion/beautifulArt_v70.saf… 
22:27:45-703350 INFO     Setting Torch parameters: device=cuda                  
                         dtype=torch.float16 vae=torch.float16                  
                         unet=torch.float16 context=no_grad fp16=True bf16=False
22:27:53-713671 INFO     LDM: LatentDiffusion: mode=eps                         
22:27:53-715272 INFO     LDM: DiffusionWrapper params=859.52M                   
22:27:53-716299 INFO     Autodetect: model="Stable Diffusion"                   
                         class=StableDiffusionPipeline                          
                         file="/opt/ai4/automatic/models/Stable-diffusion/beauti
                         fulArt_v70.safetensors" size=2034MB                    
22:27:56-976624 INFO     Cross-attention: optimization=Sub-quadratic options=[] 
22:27:56-984494 INFO     Load embeddings: loaded=0 skipped=0 time=0.00          
22:27:56-991608 INFO     Model loaded in 12.73 { load=1.09 config=0.37          
                         create=8.00 apply=2.34 vae=0.91 }                      
22:27:57-388112 INFO     Model load finished: {'ram': {'used': 6.22, 'total':   
                         31.23}, 'gpu': {'used': 0.08, 'total': 7.98},          
                         'retries': 0, 'oom': 0} cached=0
```

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by tau0-deltav** [comment]
...I didn't think sub-quadratic attention works in diffusers? I am not sure if this is true, so I will double check for you now. Use SDP if you're not using xformers/flash-attenton (which you're not on AMD.) You seem to be trying to load controlnet as well and I can't actually tell from this whether you're really using diffusers or A1111-mode?
This: `Model load finished: {'ram': {'used': 6.22, 'total': 31.23}, **'gpu': {'used': 0.08,** 'total': 7.98},` seems suspicious?
There's more to say here but suffice to say:

1. You're not running out of memory (programs which run out of memory segfault when the OOM killer doesn't get them). Running out of memory causes crashes. If only we were so lucky.
2. **It is the kernel's job, if not the operating system more broadly, to manage memory pressure**. I had problems like this on arch because I threw myself at it deliberately to suffer as many horrific teaching moments as possible. **That this happens on Ubuntu is quite funny but also really seriously not good enough.**
3. Again *if the operating system breaks because a single python script allocates too much memory, the operating system is faulty.**
4. You are **thrashing**. To and from what is beyond the scope of this, but the point is that this isn't actually a stuck system - it's spending all of it's time trying not to run out of memory. 
5.  `cgroups`, which are how we do strict enforcements on memory usage on linux. I think. Check the arch wiki. Regardless of your distro. Maybe red hat will have something for you too. I can't help more because I'm quick on the draw with `killall -9 python`. 
6. Having said all that yes, there's something wrong with memory usage in SD.Next - and to varying lesser degrees, diffusers, torch and python even. Python of course is only able to do this because it can call fork()... which is why this doesn't happen on Windows. (discovering fork() as the Why of all this took me half a year lol.)

**Comment by vladmandic** [comment]
since you took time to write a detailed report, i'll write a detailed answer:
- first, i'm not a rocm expert (or even user), but rocm 5.5 is really old - you may not have a choice of using a newer one depending on your gpu, it sucks that amd's compatibility matrix is so limited.
- similarly, subquad is the worst of cross-attention optimizers, but due to rocm you may not have a choice
and both of those have major impact on gpu memory usage

what else? a lot...
- if you're switching lora's back and forth, reduce load/unload ops by setting lora cache: system->settings->extra networks->lora memory cache
- if there is a leak, lets trace it - you don't know how long/how often this happens, but you can at least do `grep ram sdnext.log` to see memory usage progression over time
- sdnext calls memory garbage collection in many phases of operations, but it chooses to skip actual garbage collection if memory usage is below threshold (why? because gc costs time and i don't want to slow down unnecessarily). you may want to decrease threshold and see how that changes things? see system->settings->compute->threshold for gc (its in percentages), try setting to something like 50
- pythons default memory allocator on linux is just horrible - in many cases, gc basically does nothing, so even if memory is free os will not get it back. i'd really suggest to switch to a better one. i'm using `tcmalloc` and i'm really happy with it. search on how to install & enable it.

**Comment by ConfusedMerlin** [comment]
Thank you for your suggestion, both. 
I will now go to check what impact those instructions do have... but before, I must comment on the "but rocm 5.5 is really old" from  @vladmandi :

> root@rkai:~# dpkg -l | grep rocm
> ii  rocm-clang-ocl                             0.5.0.60000-91~22.04                    amd64        OpenCL compilation with clang compiler.
> ii  rocm-cmake                                 0.11.0.60000-91~22.04                   amd64        rocm-cmake built using CMake
> ii  rocm-core                                  6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime software stack
> ii  rocm-dbgapi                                0.71.0.60000-91~22.04                   amd64        Library to provide AMD GPU debugger API
> ii  rocm-debug-agent                           2.0.3.60000-91~22.04                    amd64        Radeon Open Compute Debug Agent (ROCdebug-agent)
> ii  rocm-developer-tools                       6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime software stack
> ii  rocm-device-libs                           1.0.0.60000-91~22.04                    amd64        Radeon Open Compute - device libraries
> ii  rocm-gdb                                   13.2.60000-91~22.04                     amd64        ROCgdb
> ii  rocm-hip-libraries                         6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime software stack
> ii  rocm-hip-runtime                           6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime software stack
> ii  rocm-hip-runtime-dev                       6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime software stack
> ii  rocm-hip-sdk                               6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime software stack
> ii  rocm-language-runtime                      6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime software stack
> ii  rocm-llvm                                  17.0.0.23483.60000-91~22.04             amd64        ROCm compiler
> ii  rocm-ml-libraries                          6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime software stack
> ii  rocm-ml-sdk                                6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime software stack
> ii  rocm-ocl-icd                               2.0.0.60000-91~22.04                    amd64        clr built using CMake
> ii  rocm-opencl                                2.0.0.60000-91~22.04                    amd64        clr built using CMake
> ii  rocm-opencl-dev                            2.0.0.60000-91~22.04                    amd64        clr built using CMake
> ii  rocm-opencl-runtime                        6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime software stack
> ii  rocm-opencl-sdk                            6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime software stack
> ii  rocm-openmp-sdk                            6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) OpenMP Software development Kit.
> ii  rocm-smi-lib                               6.0.0.60000-91~22.04                    amd64        AMD System Management libraries
> ii  rocm-utils                                 6.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime software stack
> ii  rocminfo                                   1.0.0.60000-91~22.04                    amd64        Radeon Open Compute (ROCm) Runtime rocminfo tool

My system's rocm is... I think end of last year? I should look for a new release, to be honest... still, the torch one is acquired by python itself, when its grabbing all dependencies for a new venv environment. So doesn't that make torch-rocm5.5 the... well... fault of the startup process? Grepping for it says, the installer.py has one... and of course its all over the venv lib folder. ... Yes, line 422 in the installer.py either goes for 5.7, or 5.5 or 5.6. 

And now... up up and away to the testing.

**Comment by ConfusedMerlin** [comment]
Well, first result is in: I can switch to diffusors... I thought they are only for cuda cards, so I never considered that. And at first glance, it works as good/bad as before, maybe a bit faster in the generation and startup, but that is hard to say. Also, it seems to be better at switching base models, which sometimes took a very long time in the past. 

But... It fails to load the base model I declared in the issue report (toon sushi), with that error:

```
Diffusers failed loading:                              
                         model=/opt/ai4/automatic/models/Stable-diffusion/toonSu
                         shi_v1.safetensors pipeline=Autodetect/NoneType Trying 
                         to set a tensor of shape torch.Size([1280, 320]) in    
                         "weight" (which has shape torch.Size([1024, 256])),    
                         this look incorrect. 
```
I yet have to find another model, that my have the same error; the others I tried do still work. 

Regarding the %MEM Usage, it still raises as I switch out models and lora... lets go on to the gc threshold. (tbc)

**Comment by vladmandic** [comment]
> So doesn't that make torch-rocm5.5 the... well... fault of the startup process? Grepping for it says, the installer.py has one... and of course its all over the venv lib folder. ... Yes, line 422 in the installer.py either goes for 5.7, or 5.5 or 5.6.

that's what i meant when i said "you may not have a choice" - newer rocm doesn't work with older gpus, etc. so you're stuck.
love-or-hate-nvidia, but i can use latest cuda with 5 generations old gpu.

**Comment by vladmandic** [comment]
threshold applies to both ram and vram
> if used_gpu >= shared.opts.torch_gc_threshold or used_ram >= shared.opts.torch_gc_threshold
which means that even if sdnext did call gc, python did very little - go to tcmalloc.

**Comment by brknsoul** [comment]
Sorta butting in here.. I use ROCm 5.7 with my 6600 XT, seems to work well.

> tcmalloc [..] search on how to install & enable it.

Does this look about right? https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/6722

**Comment by vladmandic** [comment]
yes, its basically install with:
> sudo apt install libgoogle-perftools-dev

and then run sdnext with something like:
> export LD_PRELOAD=libtcmalloc.so
> ./webui.sh

**Comment by vladmandic** [comment]
any updates?

**Comment by ConfusedMerlin** [comment]
After some serious testing, I think this issue is... not resolved, but at least not very likely any more to appear within a 30 minute timeframe of working.

 @vladmandic , the libtcmalloc.so seems to be as good as you described with keeping the %MEM value far away from the dreaded 90% value. While generating a lot of pictures with all kinds of models and loras, it never did freeze even once, and the %MEM managed to stick around 20% the whole time. Seems fine!

But... one thing: I had to switch back from diffusors to original (backend?), because diffuser's output was somehow way more ugly and unpredictable than originals... But that's fine for me; both are about equally fast, and if the original backend does better for me, it shall stay. 

I will end this with a tiiny feature request: if the %MEM goes over 85, you could display a warning message at the upper right corner (where it also puts some of the error messages, if the server is down). In that case one simply can stop and restart SD, which - in my case - would be ways better than running in the lock up and having to hard reset the whole system.  If thee are people out there that have the same kind of problem as I, it might help them a lot. 

Greetings and happy diffusing, 
Confused Merlin
