### ISSUE TITLE
[Issue]: ERROR    Not a git repository

### ISSUE THREAD

**Issue by patritha** [vladmandic/automatic#2759]
### Issue Description

on first launch the console says ERROR Not a git repository. i have git installed. not sure what im doing wrong.

### Version Platform Description

OS: Windows Server 2019
Shell: Powershell 5.1.17763.5328
CPU: AMD Ryzen 5 2600
GPU: nVidia Tesla M40 24GB

### Relevant log output

```shell
PS D:\shennanigans\stable diffusion next> .\webui-user.bat
Using VENV: D:\shennanigans\stable diffusion next\venv
16:20:06-865928 INFO     Starting SD.Next
16:20:06-865928 INFO     Logger: file="D:\shennanigans\stable diffusion next\sdnext.log" level=INFO size=425
                         mode=append
16:20:06-881568 INFO     Python 3.10.6 on Windows
16:20:06-881568 ERROR    Not a git repository
Press any key to continue . . .

```
```


### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
launch again with
`.\webui.bat --debug`

Note that SD.Next doesn't use `webui-user.bat`, so if you have that file, then either you created it, you're using a _really_ old version of SD.Next, or you're using A1111.

**Comment by patritha** [comment]
```
PS D:\shennanigans\stable diffusion next> .\webui.bat --debug
Using VENV: D:\shennanigans\stable diffusion next\venv
19:58:55-036618 INFO     Starting SD.Next
19:58:55-052257 INFO     Logger: file="D:\shennanigans\stable diffusion next\sdnext.log" level=DEBUG size=65
                         mode=create
19:58:55-052257 INFO     Python 3.10.6 on Windows
19:58:55-067881 ERROR    Not a git repository
Press any key to continue . . .
```

**Comment by vladmandic** [comment]
how did you download sdnext to start with?

**Comment by patritha** [comment]
downloading as a zip on the github page

**Comment by brknsoul** [comment]
Yeah, you don't do that.
You install python and git, then use the 
`git clone https://github.com/vladmandic/automatic`
command

**Comment by patritha** [comment]
ok its installing tons of pip packages so i assume it works now. thanks bros
