### ISSUE TITLE
[Issue]: img2img.py -> batchmode 5 

### ISSUE THREAD

**Issue by Nahasapeemapetilon** [vladmandic/automatic#2766]
### Issue Description

The code encountered an error during image processing with an unknown mode (5.0). (line 196 )
(inputdir , outputdir and mask dir set)
Additionally, an exception occurred in the process_batch function(line 256), indicating that it was expecting 6 positional arguments, but 10 were provided. This inconsistency suggests a mismatch in the number of arguments passed to the function. Further investigation into the function call and the expected parameters is needed to resolve this issue.

### Version Platform Description

linux ,rocm , dev branch 

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
- workflow that leads to this?
- is this reproducible at will or was it a one time thing?
- actual log, not just description?

**Comment by Nahasapeemapetilon** [comment]
[sdnext.log](https://github.com/vladmandic/automatic/files/14077815/sdnext.log)
[rec.webm](https://github.com/vladmandic/automatic/assets/16188935/8c5f9ac4-d604-4e83-8c48-e57192f9050f)
I start the application with the following command:
git switch dev
./webui.sh --safe --use-rocm --debug  
And then I tried to process multiple files in batch mode(inpaint), as shown in the video. I just tested it again in the master branch, and it seems to be still working there.

**Comment by vladmandic** [comment]
fixed in dev.

**Comment by Nahasapeemapetilon** [comment]
Thank you for the quick fix, but is it correct that we don't have an 'elif' for the batch mode (mode == 5)?line 192
![image](https://github.com/vladmandic/automatic/assets/16188935/0d6bf884-3969-4ffb-a5b3-1dab5c537290)

**Comment by vladmandic** [comment]
batch mode is handled differently, so it doesn't matter whats set in that if statement:
```py
    p.is_batch = mode == 5
    if p.is_batch:
        process_batch(p, img2img_batch_files, img2img_batch_input_dir, img2img_batch_output_dir, img2img_batch_inpaint_mask_dir, args)
        processed = processing.Processed(p, [], p.seed, "")
    else:
        processed = modules.scripts.scripts_img2img.run(p, *args)
        if processed is None:
            processed = processing.process_images(p)
```
