### ISSUE TITLE
[Issue]: Control: ControlNet models do not appear immediately when adding a new ControlNet unit

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2768]
### Issue Description

Once you add a ControlNet unit, neither the processor nor the models are immediately available in this new unit. You have to click on the refresh icon to make them available.

Note: I keep models on a symlink (`<sdnext root>/models/controlnet`  to `/tmp/controlnet`) due to space constraints

## To reproduce

1. Switch to Control
2. Increase the number of ControlNet units to 2
3. Open the combox for the models in the newly-added unit 

## Expected result

The list of models is displayed

## Actual result

Only "None" is displayed until the list is refreshed. 

### Version Platform Description

Python 3.10.10
CUDA 12.1
SD.Next dev dc70246c

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev
