### ISSUE TITLE
[Issue]: Disabled ControlNet units in Control stop execution of following units even if enabled

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2770]
### Issue Description

The ControlNet extension in the original backend executes all ControlNet units that are enabled, regardless if they are sequential or not (e.g. unit 0 enabled, unit 2 enabled). In Control, if there are three units and the second is disabled, the third won't run.

## Steps to reproduce

1. Set a control image in Control and input prompt
2. Set an additional ControlNet unit along with the associated image, and keep it disabled
3. Set an additional Control unit along with the associated image, and enable it
4. Hit Generate

## Expected results

The second unit is skipped, but the third unit is run.

## Actual results 

Only the first unit runs. 

### Version Platform Description

Python 3.10.10
SD.Next dc70246c
Ubuntu 20.04 (Paperspace)

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this should be fixed in dev now
