### ISSUE TITLE
[Feature]: Control: Implement "pixel perfect" resizing from ControlNet extension (original backend)

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2771]
### Feature description

The ControlNet extension has a "pixel perfect" resizing which adjusts the control image to the target resolution (and it is also used for preprocessors). 
It might be worthwhile (if possible) to implement this in Control for control images.

Implementation is at https://github.com/Mikubill/sd-webui-controlnet/blob/a773a1a8164c67bad9f27dfb78143b3a8f89d164/internal_controlnet/external_code.py#L97

### Version Platform Description

SD.Next dc70246c

**Comment by vladmandic** [comment]
i don't really like how pixel-perfect is implemented in controlnet.
but i did just implement option so resizing (before one) applies to processor overrides as well.
if i misunderstood, please explain in a bit more details what is needed and i'll reopen.

**Comment by lbeltrame** [comment]
Aside the actual resizing approach, the current "issue" with (some of) the resizing algorithms is that, for control images, they can introduce unwanted blurriness / alterations if you use pre-processed images. While for some it might not be a problem (openpose), for others it may significantly alter the output (depth, for example) and thus the final result.

Anyway, I'm not really pushing for this specific implementation but rather something that limits the noise applied when resizing (to the control images). Assuming that is doable, if not I can live with what's there.

**Comment by vladmandic** [comment]
true. if you want to resize a depth image, you better choose an upscaler that works well with that type of images. but that's more of a wiki item than i'd wish to force from the code.

you can go back to good-old xyz grid script and run all upscalers on one such image so you know (and i'd learn as well) which work well and which dont.

**Comment by lbeltrame** [comment]
Good point. Noted, will try that when I'm back to experimenting.
