### ISSUE TITLE
[Issue]:  Mixture tiling runs with SDXL while it looks like it is compatible with SD only 

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2777]
### Issue Description

As soon as I've seen mixture tiling, I *knew* I had to try it. I tried it with SDXL, which looks not applicable, because the log throws an error when it tries to switch pipeline.

Model: Animagine 3 XL
Prompt: 1girl,  long hair, blue eyes,  cinematic composition, cinematic lighting, cinematic angle, anime artwork, anime style, key visual, vibrant, studio anime,  highly detailed, anime coloring, newest, masterpiece, best quality `<newline>`
1girl, short hair, yellow eyes,  cinematic composition, cinematic lighting, cinematic angle, anime artwork, anime style, key visual, vibrant, studio anime,  highly detailed, anime coloring, newest, masterpiece, best quality 

Parameters:
X components: 2
X spacing 0.5

This is shown in the logs:

```
04:51:07-738229 INFO     Installing package: ligo-segments                      
(…)5.1/examples/community/mixture_tiling.py: 20.5kB [00:00, 63.9MB/s]           
04:51:18-798165 ERROR    Pipeline switch error: from=StableDiffusionXLPipeline  
                         to=StableDiffusionTilingPipeline                       
                         StableDiffusionTilingPipeline.__init__() missing 1     
                         required positional argument: 'safety_checker'         
04:51:18-799611 ERROR    Pipeline switch: TypeError                             
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /notebooks/automatic/modules/sd_models.py:1009 in switch_pipe                │
│                                                                              │
│   1008 │   │   │   │   │   components_skipped.append(item)                   │
│ ❱ 1009 │   │   │   new_pipe = cls(**pipe_dict)                               │
│   1010 │   │   │   switch_mode = 'auto'                                      │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: StableDiffusionTilingPipeline.__init__() missing 1 required positional argument: 'safety_checker'
```

There's a second error for which I'll file a separate issue.

### Version Platform Description

04:40:11-578078 INFO     Starting SD.Next                                       
04:40:11-583778 INFO     Logger: file="/notebooks/automatic/sdnext.log"         
                         level=INFO size=2596258 mode=append                    
04:40:11-585001 INFO     Python 3.10.10 on Linux                                
04:40:11-623486 INFO     Version: app=sd.next updated=2024-01-30 hash=076e16c8  
                         url=https://github.com/vladmandic/automatic/tree/dev   
04:40:11-755913 INFO     Updating main repository                               
04:40:12-162781 INFO     Upgraded to version: 076e16c8 Tue Jan 30 01:40:35 2024 
                         +0300                                                  
04:40:12-168144 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux          
                         release=5.19.0-45-generic python=3.10.10      

### Relevant log output

```shell
04:51:07-738229 INFO     Installing package: ligo-segments                      
(…)5.1/examples/community/mixture_tiling.py: 20.5kB [00:00, 63.9MB/s]           
04:51:18-798165 ERROR    Pipeline switch error: from=StableDiffusionXLPipeline  
                         to=StableDiffusionTilingPipeline                       
                         StableDiffusionTilingPipeline.__init__() missing 1     
                         required positional argument: 'safety_checker'         
04:51:18-799611 ERROR    Pipeline switch: TypeError                             
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /notebooks/automatic/modules/sd_models.py:1009 in switch_pipe                │
│                                                                              │
│   1008 │   │   │   │   │   components_skipped.append(item)                   │
│ ❱ 1009 │   │   │   new_pipe = cls(**pipe_dict)                               │
│   1010 │   │   │   switch_mode = 'auto'                                      │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: StableDiffusionTilingPipeline.__init__() missing 1 required positional argument: 'safety_checker'
```

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
mixture tiling only works with sd15 as base model. i've tried forcing sdxl as base model, but it doesn't work.
i'll add checks and error handling to capture this.
