### ISSUE TITLE
[Issue]: Diffusers Models not loading, giving error

### ISSUE THREAD

**Issue by tscott65** [vladmandic/automatic#2779]
### Issue Description

I've tried a brand-new install of SDNext (and an existing install). The only extension is Dynamic Prompts. 

I've switched back-end to Diffusers.

Regular SDXL and 1.5 models work fine (all models are hosted on a network share). 

When I try to load a diffusers on rtx4080-equipped PC (model hosted on the same network share), I get an error after the model load is attempted three times.

The diffuser model (Kandinsky-2-1) works as expected on M2 Mac Mini (although it's VERY slow to load)

### Version Platform Description

Windows 11 22H2 22621.3007. 128GB RAM, AMD Ryzen 9 3950X 16-Core Processor   
RTX4080 driver 546.01

MS-Edge browser Version 121.0.2277.83 (Official build) (64-bit)
Firefox browser 122.0 (64-bit)

23:23:17-262163 INFO     Starting SD.Next
23:23:17-265162 INFO     Logger: file="J:\AI Apps\autotest\automatic\sdnext.log" level=INFO size=99028 mode=append
23:23:17-266163 INFO     Python 3.10.7 on Windows
23:23:17-400216 INFO     Version: app=sd.next updated=2024-01-29 hash=2a5b98c3
                         url=https://github.com/vladmandic/automatic/tree/master
23:23:17-629064 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22621-SP0 python=3.10.7
23:23:17-634064 INFO     nVidia CUDA toolkit detected: nvidia-smi present
23:23:17-710577 INFO     Extensions: disabled=[]
23:23:17-711575 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
23:23:17-714575 INFO     Extensions: enabled=['sd-dynamic-prompts'] extensions
23:23:17-716576 INFO     Startup: standard
23:23:17-717576 INFO     Verifying requirements
23:23:17-730581 INFO     Verifying packages
23:23:17-732581 INFO     Verifying submodules
23:23:23-658467 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'sd-dynamic-prompts']
23:23:23-659466 INFO     Verifying requirements
23:23:23-677466 INFO     Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
23:23:23-679468 INFO     Command line args: []
23:23:28-153434 INFO     Load packages: torch=2.2.0+cu121 diffusers=0.25.0 gradio=3.43.2
23:23:28-650441 INFO     Engine: backend=Backend.ORIGINAL compute=cuda mode=no_grad device=cuda
                         cross-optimization="Scaled-Dot-Product"
23:23:28-734447 INFO     Device: device=NVIDIA GeForce RTX 4080 n=2 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8801
                         driver=546.01
                         546.01

### Relevant log output

```shell
07:56:27-452214 ERROR    StableDiffusionPipeline: Pipeline <class
                         'diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion.StableDiffusionPipeline'>
                         expected {'vae', 'text_encoder', 'safety_checker', 'image_encoder', 'feature_extractor',
                         'unet', 'scheduler', 'tokenizer'}, but only {'text_encoder', 'safety_checker', 'scheduler',
                         'unet', 'tokenizer'} were passed.
07:56:27-455213 ERROR    Failed loading model:
                         \\10.10.101.100\AIData\AI\Models\Diffusers\models--kandinsky-community--kandinsky-2-1\snaps
                         hots\04b366659663bf60deacb96fd3e38f1cb39a3be4 auto=The deprecation tuple ('no variant default',
                         '0.24.0', "You are trying to load the model files of the `variant=fp16`, but no such modeling
                         files are available.The default model files: {'text_encoder/pytorch_model.bin',
                         'text_encoder/model.safetensors', 'image_encoder/model.safetensors',
                         'image_encoder/pytorch_model.bin', 'prior/diffusion_pytorch_model.safetensors',
                         'prior/diffusion_pytorch_model.bin'} will be loaded instead. Make sure to not load from
                         `variant=fp16`if such variant modeling files are not available. Doing so will lead to an error
                         in v0.24.0 as defaulting to non-variantmodeling files is deprecated.") should be removed since
                         diffusers' version 0.25.0 is >= 0.24.0 diffusion=The deprecation tuple ('no variant default',
                         '0.24.0', "You are trying to load the model files of the `variant=fp16`, but no such modeling
                         files are available.The default model files: {'text_encoder/pytorch_model.bin',
                         'text_encoder/model.safetensors', 'image_encoder/model.safetensors',
                         'image_encoder/pytorch_model.bin', 'prior/diffusion_pytorch_model.safetensors',
                         'prior/diffusion_pytorch_model.bin'} will be loaded instead. Make sure to not load from
                         `variant=fp16`if such variant modeling files are not available. Doing so will lead to an error
                         in v0.24.0 as defaulting to non-variantmodeling files is deprecated.") should be removed since
                         diffusers' version 0.25.0 is >= 0.24.0
07:56:27-459210 WARNING  Model not loaded
```

### Backend

Diffusers

### Branch

Master

### Model

Kandinsky

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this has been fixed in dev branch and will be part of the next release.
