### ISSUE TITLE
[Issue]: Image Info Tab is not working properly

### ISSUE THREAD

**Issue by amiremami** [vladmandic/automatic#278]
### Issue Description

Hi, I was looking for the image info tab, and I found out it has been removed and integrated with process image tab.

I think this is not a good idea. Maybe I'm not doing it correctly, but now there are some lack of features here.

I dragged and dropped the image in to the process tab. It showed me prompts in 2 sections, parameters and user comments. Not sure what these are. But the prompts are not ok and it has bug.

This is what I'm seeing in vladmandic:

![image](https://user-images.githubusercontent.com/15929497/233345644-4d9223a7-b964-4d1f-8189-f11f121819d8.png)

This is what I'm seeing in automatic:

![image](https://user-images.githubusercontent.com/15929497/233345730-0d8cf9e9-4dbe-49c9-b3fd-170f6aa4d7dd.png)

As you can see, half of my negative prompt is not there.

Then, from where I can see the other details such as SEED?

Thanks

### Version Platform Description

Windows 10

Version: e6701f5 Wed Apr 19 14:12:19 2023 -0400

**Comment by DavidSnow1** [comment]
I've just installed this fork and I was just about to raise an issue asking where on earth the image info tab is. Glad I'm not alone. What's the procedure here? I've loaded the image into the process tab, and the →text, →image and →inpaint buttons do absolutely nothing at all. I can see my parameters, but how do I actually load them into the tab I want?

I have to concur with amiremami. This is horribly unintuitive.

**Comment by vladmandic** [comment]
@DavidSnow1 sorry, but how are buttons just below image unintuitive??
@amiremami i'll take a look, but this looks like just a cropping issue, should be simple fix. i don't think functionality is broken.

**Comment by amiremami** [comment]
Functions are ok on my side, at least for sending to text. However, for this image, it's not sending the SEED and it's not sending the correct negative prompt. But for some others it's ok. I'm not sure if the metadata is preserved through github or not.

![00131-96465750-photo of the most beautiful artwork in the world featuring a soft lustrous male hero epic heroic fantasy muscular men rugged](https://user-images.githubusercontent.com/15929497/233356832-84df2027-9e23-4b67-92b9-4b4de78f6fe7.jpg)

![image](https://user-images.githubusercontent.com/15929497/233357073-9278b88c-452f-4eb7-9661-162c92ecf168.png)

**Comment by vladmandic** [comment]
now i have an example image (thanks) and i can work on a fix.

**Comment by DavidSnow1** [comment]
> @DavidSnow1 sorry, but how are buttons just below image unintuitive?? @amiremami i'll take a look, but this looks like just a cropping issue, should be simple fix. i don't think functionality is broken.

In the sense that once the image is loaded in, the only buttons that are responsive at all are the sliders. Here:

https://www.youtube.com/watch?v=pcY-PKIXxLo

I suspect I'm having the same issue as the person who said that the UI is sometimes completely unresponsive.

**Comment by amiremami** [comment]
Thanks a lot Vlad. Is this ok?

![image](https://user-images.githubusercontent.com/15929497/233419784-ef8a9f7b-133a-443f-8ba2-c452c857430f.png)

**Comment by vladmandic** [comment]
@amiremami thats a git complaining about something, there are details in discussions how to deal with that, its not related to this issue at all.
