### ISSUE TITLE
[Feature]: Control: implement a two-pass generation workflow

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2783]
### Feature description

Currently there is no real two-pass workflow in Control: the only way to do so is to run it once with the "regular" resolution, then rerun it with the desired upscale (Control + independent image) and denoising strength. 

Ideally there should be a proper two-pass workflow like txt2img to allow generation + upscale / denoise in one go.

### Version Platform Description

Python 3.10.10
SD.Next 3baff590

**Comment by vladmandic** [comment]
done.
