### ISSUE TITLE
[Issue]: simple merge sliders override manual block values

### ISSUE THREAD

**Issue by Enferlain** [vladmandic/automatic#2785]
### Issue Description

When the sliders in "simple merge" are 0, manual block merge does not work. When they aren't 0, the manual merge values get discarded

Merge method with alpha and beta required which I set specifically in the manual tab, default sliders in simple merge tab (alpha 0.5, beta 0)

`kwargs = {dict: 14} {'alpha': 0.5, 'beta_base': '0.16027571563113877', 'beta_in_blocks': '0.13611656877000583,0.3978682065523139,0.045707845052389874,0.0,0.19059007051287766,0.5278322694876812,0.46020493750920655,0.3656028335744898,0.7184282463142058', `

result: `rotate() missing 1 required positional argument: 'beta'` and alpha_base, alpha blocks get overwritten by just alpha from simple merge or something.

Same result with any other method. Tried just simple weighted_sum for sanity check, tested with merging with simple merge slider on 0 (same error as above error) and different values while manual blocks were set, and sure enough, different results reflecting the slider in simple merge

<img src="https://github.com/vladmandic/automatic/assets/15861396/1484fa53-56e1-4cd7-9dd3-59f024786fe7" width="400" height="400"><img src="https://github.com/vladmandic/automatic/assets/15861396/3b9c6077-5fb4-41d7-87dc-10eff29afb51" width="400" height="400">

 I checked extras.py and ui_models.py but I couldn't really figure out anything more.

### Version Platform Description

https://github.com/vladmandic/automatic/commit/bc66ed16580443adbac7cb089e4ce8411f695f11

### Relevant log output

```shell
no relevant logs other than the errors when sliders on 0
```

### Backend

Original

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
Cc @AI-Casanova

**Comment by AI-Casanova** [comment]
I found the issue (bad coding on my part) and am working on a fix now.

**Comment by AI-Casanova** [comment]
Closing issue, please reopen if latest dev has any issues

**Comment by Enferlain** [comment]
Pog, thanks
