### ISSUE TITLE
[Issue]: Wrong Lora in prompt when restoring last used prompt

### ISSUE THREAD

**Issue by Silanda** [vladmandic/automatic#2786]
### Issue Description

I have two similarly named Lora in my folder: LCMTurboMix_Euler_A_fix.safetensors and LCMTurboMix_DPM_SDE_Karras.safetensors

Whenever I restore the last prompt used in a previous session, it always puts the Euler A lora into the prompt, even when I was last using the DPM one. What's odd is that the correct lora is recorded in params.txt

EDIT: Okay, it's listing both lora as having identical hashes. That can't be right. Could it be anything to do with them both being SDXL Turbo lora?

### Version Platform Description

12:57:45-257340 INFO     Starting SD.Next
12:57:45-259343 INFO     Logger: file="i:\GitHub\automatic\sdnext.log" level=INFO size=20482655 mode=append
12:57:45-259343 INFO     Python 3.11.6 on Windows
12:57:45-439451 INFO     Version: app=sd.next updated=2024-01-30 hash=9bf08c54
                         url=https://github.com/vladmandic/automatic.git/tree/master
12:57:46-027112 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.11.6
12:57:46-029616 INFO     nVidia CUDA toolkit detected: nvidia-smi present
12:57:46-129524 WARNING  Modified files: ['scripts/detect_extension.py']
12:57:46-129524 INFO     Startup: standard
12:57:46-129524 INFO     Verifying requirements
12:57:46-155155 INFO     Verifying packages
12:57:46-155155 INFO     Verifying submodules
12:58:16-052896 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'canvas-zoom', 'sd-webui-regional-prompter']
12:58:16-059899 INFO     Verifying requirements

12:58:16-075123 INFO     Updating Wiki

12:58:16-756182 INFO     Extension preload: {'extensions-builtin': 0.02, 'extensions': 0.0}
12:58:16-756182 INFO     Command line args: ['--upgrade'] upgrade=True
12:58:26-559583 INFO     Load packages: torch=2.1.1+cu121 diffusers=0.25.0 gradio=3.43.2
12:58:27-744881 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda mode=no_grad device=cuda
                         cross-optimization="Scaled-Dot-Product"
12:58:27-806743 INFO     Device: device=NVIDIA GeForce RTX 4070 Ti n=1 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8801      driver=551.23

Browser is Firefox 122.0

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
choice of which has to use for lora was inherited from a1111 and looking at the code, its really a bad choice.
i've updated it to use more modern hash - its in dev branch now and will be part of the next release.

note that you'll also need to delete `cache.json` so it can be rebuilt using new hashes.
