### ISSUE TITLE
[Issue]: IP Adapter  - RuntimeError: mat1 and mat2 shapes cannot be multiplied when changing adapters

### ISSUE THREAD

**Issue by solsol360** [vladmandic/automatic#2798]
### Issue Description

IP-Adapter txt2img,img2img,control doesn't work when changing between ViT-G and normal:

Replicate:
Generate with any SD1.5 adapter like 'Base'
Change to 'Base ViT-G' and generate.
Fails with RuntimeError: mat1 and mat2 shapes cannot be multiplied (2x1024 and 1280x3072)

Other SD 1.5 IP adapters still work.  Adapter image or canvas size doesn't seem to affect the error.
If you generate with 'Base ViT-G' first, then try other SD 1.5 adapters, you get the same error.

Force-unload clip needed.

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
