### ISSUE TITLE
[Feature Request]: Is it any way to run it on Windows natively?

### ISSUE THREAD

**Issue by ke1ne** [vladmandic/automatic#28]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

I would like to run your fork on Windows without WSL. Is it possible, basically?
Thank you!

### Proposed workflow

1. Run some cmd-file.
2. Get WebUI, generation, etc. working.

**Comment by vladmandic** [comment]
i've just re-added original `webui.bat`

**Comment by ecker00** [comment]
The readme is missing documentation on how to install in windows.

**Comment by ke1ne** [comment]
@ecker00 
1. Create&activate virtual environment:
```
cd automatic
python -m venv venv
.\venv\Scripts\activate
```
2. Install Torch into that venv:
```
pip install torch torchaudio torchvision triton --force --extra-index-url https://download.pytorch.org/whl/cu118
```
3. Exit venv:
```
.\venv\Scripts\deactivate
```
3. Run UI via webui.bat. I'm using own runner instead (like start.bat):
```
@echo off

call git pull --recurse-submodules

set TF_CPP_MIN_LOG_LEVEL=2
set FORCE_CUDA="1"
set ATTN_PRECISION=fp16
set PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512
set CUDA_LAUNCH_BLOCKING=0
set CUDA_CACHE_DISABLE=0
set CUDA_AUTO_BOOST=1
set CUDA_DEVICE_DEFAULT_PERSISTING_L2_CACHE_PERCENTAGE_LIMIT=0
set CUDA_MODULE_LOADING="LAZY"
set GRADIO_ANALYTICS_ENABLED="False"
set SAFETENSORS_FAST_GPU=1

set COMMANDLINE_ARGS=--ckpt-dir="D:\AI\models" --vae-dir="D:\AI\vaes" --autolaunch --opt-channelslast --upcast-sampling --api --gradio-queue --theme dark --cors-allow-origins="http://127.0.0.1:7860" --update-all-extensions

call webui.bat
```

**Comment by ecker00** [comment]
That seemed to almost do it, but get error that it's unable to find the required version:
```
pip install torch torchaudio torchvision triton --force --extra-index-url https://download.pytorch.org/whl/cu118

Collecting torch
  Downloading torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 172.3/172.3 MB 12.8 MB/s eta 0:00:00
Collecting torchaudio
  Downloading torchaudio-2.0.1-cp310-cp310-win_amd64.whl (2.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 16.9 MB/s eta 0:00:00
Collecting torchvision
  Downloading torchvision-0.15.1-cp310-cp310-win_amd64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 9.5 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton
```

If this works, should really add it to the readme.md

**Comment by ke1ne** [comment]
> That seemed to almost do it, but get error that it's unable to find the required version:

Oh, simply remove the `triton` from the` pip install` line. There is no triton lib available on Windows.

**Comment by ecker00** [comment]
That got things to progress a but, but now encountering this one, so seems there are still some issues to work out:
https://github.com/vladmandic/automatic/issues/100
