### ISSUE TITLE
[Extension]: ControlNet inpaint "only masked" incorrect cropping

### ISSUE THREAD

**Issue by TimothyKrell** [vladmandic/automatic#2806]
### Issue Description

When inpainting with controlnet, the sample passed to controlnet does not match the cropped portion of the image. You can see the entire image is being overlayed into the inpaint region. This is on a fresh install of sdnext.

![image](https://github.com/vladmandic/automatic/assets/1585669/5a0eae65-800f-44df-bcc0-1f61eba53af5)
![00007-juggernaut_final-4k ultra quality still photograph realistic detailed cinematic](https://github.com/vladmandic/automatic/assets/1585669/ba14f649-5e52-48b2-8dec-b1df46812d51)
![image](https://github.com/vladmandic/automatic/assets/1585669/e4beb21e-827a-423c-b79d-17f3da5a3f6a)
![image](https://github.com/vladmandic/automatic/assets/1585669/aa44ce05-e7dc-4435-a351-f49afb9f04bb)

### Version Platform Description

Python 3.10.6 on Windows
Version: app=sd.next updated=2024-01-30 hash=9bf08c54 url=https://github.com/vladmandic/automatic/tree/master
Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows release=Windows-10-10.0.19045-SP0 python=3.10.6
nVidia CUDA toolkit detected: nvidia-smi present
Extensions: disabled=[]
Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg'] extensions-builtin
Extensions: enabled=[] extensions
Startup: quick launch
Verifying requirements
Verifying packages
Extensions: disabled=[]
Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg'] extensions-builtin

### URL link of the extension

https://github.com/Mikubill/sd-webui-controlnet

### URL link of the issue reported in the extension repository

https://github.com/Mikubill/sd-webui-controlnet/issues/2626

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by TimothyKrell** [comment]
Update from controlnet repo: https://github.com/Mikubill/sd-webui-controlnet/issues/2626#issuecomment-1930030647

**Comment by TimothyKrell** [comment]
The issue is "Crop the input imaged based A1111 mask" options does not show.

Here it is A1111:
![image](https://github.com/vladmandic/automatic/assets/1585669/b3365dd1-8de9-41d8-ac3c-e1c58f92b536)

And here it is in SDNext:
![image](https://github.com/vladmandic/automatic/assets/1585669/e0ea6ecf-8d45-4b4e-8c80-22850a4f57ae)

**Comment by vladmandic** [comment]
fixed in dev branch.

**Comment by TimothyKrell** [comment]
Thank you!
