### ISSUE TITLE
[Issue]: Problem on my favorite SD.NEXT version 

### ISSUE THREAD

**Issue by EKKIV0K** [vladmandic/automatic#2810]
### Issue Description

as i said on a last report (i closed the thread) i have a lot of professional work depending on a specific version of SD.NEXT, 
i formated my computer and then tried to reinstall that version : [89ba8e3](https://github.com/vladmandic/automatic/commit/89ba8e3cf6f4e7697ffe0298b49bed7ea108b039)

I tried to install the last update but SDNEXT is too different and not really ergonomic for me.
and on top of all of that it's unable to reproduce older seeds. and that's a real problem.
i tried to change some settings to get it look like my older version but even wiith those settings the seeds are not back.

i really need to go back to this version, so here is the last problems i faced with the realinstation of the 89ba8e3 version.
Your help will be really really really appreciated ! 

i past my last 2 entire day and night to get it working but failed.
You are the only one that can help me i guess, sorry to bother you about a old version.
But it's really important for me and my job.

@vladmandic 
![help](https://github.com/vladmandic/automatic/assets/119963095/73f8908e-0460-4ae2-a1ae-bd44ea497daa)

### Version Platform Description

Windows 10 21H2 
Stable diffusion 89ba8e3
OperaGX / Google Chrome

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
at the very minimum upload entire `sdnext.log`, nothing i can do based on a short screenshot that doesn't show actual sequence.

**Comment by EKKIV0K** [comment]
@vladmandic 
[sdnext.log](https://github.com/vladmandic/automatic/files/14194459/sdnext.log)

**Comment by vladmandic** [comment]
its encountering too many errors during setup, so it resets itself back to latest and then you're back to square one, but in even worse shape since repo has been heavily modified by then

start fresh:

```shell
git clone https://github.com/vladmandic/automatic sdnext-old
cd sdnext-old
git reset --hard 379fe1f3
git clean -df
git checkout 379fe1f3
webui.bat --debug
```

when you reach state when it says `Initializing` or when it asks to `Download the default model?`, stop it and run, do not continue with startup as now we need to manually fix some dependencies since newer versions of those libraries are not compatibile with old SD.Next

```shell
venv\Scripts\activate
pip install torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 --index-url https://download.pytorch.org/whl/cu118
pip install fastapi==0.102.0
exit
```

now you can start it again using `webui.bat --debug` and it should work

**Comment by EKKIV0K** [comment]
@vladmandic 

I made everything you mentioned step by step .....and 
![gg](https://github.com/vladmandic/automatic/assets/119963095/042efc61-e52c-4cdf-a876-849846cbf3a6)

Still the same version with the brownian noise and penultigate or something.....
Here is the log too. (launched with the command Webui.bat --debug)
[sdnext.log](https://github.com/vladmandic/automatic/files/14195492/sdnext.log)

**Comment by EKKIV0K** [comment]
ok i made it working by replacing the number of the commit by the correct version :)

thanks for all @vladmandic !!!! you helped me a lot !
there is a small problem with lycoris models, but can i simply install the extension to get it back ?!
