### ISSUE TITLE
[Extension]: SD-webui Lycroris

### ISSUE THREAD

**Issue by EKKIV0K** [vladmandic/automatic#2815]
### Issue Description

As my last post mentionned i needed a specific version of SDNEXT to get my work back.
i installed with succes the version 89ba8e3c without any problems 
with the command SDNEXT-old. But just one seems to be still here whatever i do.

**Important : i included the original Lycroris Extension but It's NOT that one.
The problem come from the extension built-in that not load the ext properly.
i tried to delete the folder and then reinstall with another version : Failed. Same problem.**

here is my problem : 
![last issue](https://github.com/vladmandic/automatic/assets/119963095/beca8ba0-afc8-40f1-959b-8acba3ba7610)

this is the Log : 
[sdnext.log](https://github.com/vladmandic/automatic/files/14206834/sdnext.log)

Thanks for your Help @vladmandic and all the contributors to this incredible project !

### Version Platform Description

Windows 10 21H2, SDNEXT 89ba8e3c 

### URL link of the extension

https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
extension `a1111-sd-webui-lycoris` is obsolete in latest versions of sdnext as all functionality is already built-in natively.
if you want to make it work with old version of sdnext, you need to find a version of that extension that works and use same `git  checkout xxx` on it, just like you did with sdnext.

> Important : i included the original Lycroris Extension but It's NOT that one.

i have no idea what that means - you can have only one lyco extension. if you installed it manually in addition to one in `extensions-builtin`, that is bound to cause conflicts.

i'm sorry, but i really cannot help more than that - we're talking about a really old / obsolete code by now.

**Comment by EKKIV0K** [comment]
No problem @vladmandic thanks a lot for all your helps and reactivity :) really appreciated !
