### ISSUE TITLE
[Extension]: NoneType object is not iterable while using adetailer

### ISSUE THREAD

**Issue by firedelta4** [vladmandic/automatic#2834]
### Issue Description

When using ADetailer SD.Next seems to try to apply ipadapter although I didn't even activate any ipadapter features that seems to lead to it trying to loop over a not initizlized list and hence throwing exceptions

Tracelog:

D:\Stable Diffusion\automatic\extensions\adetailer\adetailer\traceback.py:139 in wrapper         │             │
│ │                                                                                                  │             │
│ │   138 │   │   try:                                                                               │             │
│ │ ❱ 139 │   │   │   return func(*args, **kwargs)                                                   │             │
│ │   140 │   │   except Exception as e:                                                             │             │
│ │                                                                                                  │             │
│ │ D:\Stable Diffusion\automatic\extensions\adetailer\scripts\!adetailer.py:764 in                  │             │
│ │ postprocess_image                                                                                │             │
│ │                                                                                                  │             │
│ │    763 │   │   │   │   │   continue                                                              │             │
│ │ ❱  764 │   │   │   │   is_processed |= self._postprocess_image_inner(p, pp, args, n=n)           │             │
│ │    765                                                                                           │             │
│ │                                                                                                  │             │
│ │ D:\Stable Diffusion\automatic\extensions\adetailer\scripts\!adetailer.py:725 in                  │             │
│ │ _postprocess_image_inner                                                                         │             │
│ │                                                                                                  │             │
│ │    724 │   │   │   try:                                                                          │             │
│ │ ❱  725 │   │   │   │   processed = process_images(p2)                                            │             │
│ │    726 │   │   │   except NansException as e:                                                    │             │
│ │                                                                                                  │             │
│ │ D:\Stable Diffusion\automatic\modules\processing.py:187 in process_images                        │             │
│ │                                                                                                  │             │
│ │   186 │   │   │   with context_hypertile_vae(p), context_hypertile_unet(p):                      │             │
│ │ ❱ 187 │   │   │   │   processed = process_images_inner(p)                                        │             │
│ │   188                                                                                            │             │
│ │                                                                                                  │             │
│ │ D:\Stable Diffusion\automatic\modules\processing.py:251 in process_images_inner                  │             │
│ │                                                                                                  │             │
│ │   250 │   │   from modules import ipadapter                                                      │             │
│ │ ❱ 251 │   │   ipadapter.apply(shared.sd_model, p)                                                │             │
│ │   252                                                                                            │             │
│ │                                                                                                  │             │
│ │ D:\Stable Diffusion\automatic\modules\ipadapter.py:90 in apply                                   │             │
│ │                                                                                                  │             │
│ │    89 │   │   │   p.ip_adapter_names = [p.ip_adapter_names]                                      │             │
│ │ ❱  90 │   │   adapters = [ADAPTERS.get(adapter, None) for adapter in p.ip_adapter_names]         │             │
│ │    91 │   │   adapter_names = p.ip_adapter_names                                                 │             │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯             │
│ TypeError: 'NoneType' object is not iterable

### Version Platform Description

23:46:59-216059 INFO     Starting SD.Next
23:46:59-218061 INFO     Logger: file="D:\Stable Diffusion\automatic\sdnext.log" level=DEBUG size=65 mode=create
23:46:59-220576 INFO     Python 3.11.8 on Windows
23:46:59-326974 INFO     Version: app=sd.next updated=2024-02-11 hash=1ff909fc
                         url=https://github.com/vladmandic/automatic//tree/dev
23:46:59-829376 INFO     Latest published version: 3c952675fefd2c94b817940ffbd4cd94fd5876c9 2024-02-10T10:42:56Z
23:46:59-836906 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.11.8
23:47:16-418024 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
23:47:16-468292 INFO     Device: device=NVIDIA GeForce RTX 4060 n=1 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8801
                         driver=551.46
23:47:04-368628 DEBUG    Extensions all: ['--sd-webui-ar-plus', 'adetailer', 'canvas-zoom', 'latent-upscale',
                         'sd-dynamic-thresholding', 'sd-webui-color-enhance', 'sd-webui-reactor', 'sd-webui-resharpen',
                         'ultimate-upscale-for-automatic1111']
                         

### URL link of the extension

https://github.com/Bing-su/adetailer

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed.
