### ISSUE TITLE
[Feature] Support onnxruntime for rocm 5.7 and 6.0

### ISSUE THREAD

**Issue by nnhobby42** [vladmandic/automatic#2836]
The installer tries to download the onnxruntime 1.16.3 but for `rocm > 5.6` there is only a `runtime >= 1.17` available. Any specific reason for that or would it be ok to just bump the version to 1.17?

https://github.com/vladmandic/automatic/blob/3c952675fefd2c94b817940ffbd4cd94fd5876c9/installer.py#L846

**Comment by vladmandic** [comment]
Can you check the code on dev branch? That part has been updated few days ago.

**Comment by nnhobby42** [comment]
The version is still hard coded and thus it tries to download a package which does not exist when using a newer rocm version. I do not know for what the onnxruntime is used, it can apparently fall back to the CPU.

**Comment by vladmandic** [comment]
what is the location for onnxruntime 1.17 for rocm 5.7? if i look at https://download.onnxruntime.ai/, i don't see 5.7 at all.
and without specifying index-url you get normal onnxruntime-gpu is for cuda, not for rocm.

**Comment by vladmandic** [comment]
looking at https://download.onnxruntime.ai/
onnruntime for rocm 5.7 and 6.0 is now available in onnxruntime nightly builds. converting this to feature and possible implementation.

**Comment by lshqqytiger** [comment]
For now, you can force onnxruntime package by adding `ONNXRUNTIME_PACKAGE` environment variable.

**Comment by lshqqytiger** [comment]
closing as it is not relevant now
