### ISSUE TITLE
[Issue]: Control: inconsistent application of preprocessors and exception raised when using multiple processors

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2837]
### Issue Description

This issue (as discussed elsewhere) reports two problems I've found while using Control and ControlNet

## Issue 1: Inconsistent application of preprocessors

Prepare 2 ControlNet units and enable them, then:

1. Load an Openpose stick figure in the Control image
2.  For the first unit, set preprocessor None and model whatever (no need to run it)
3.   Load an image in the second unit  (not in control image)  that needs processing (for example lineart), set preprocessor Lineart (Anime or Realistic) then Canny/Lineart as model
4. Hit the icon for "preview" for the second unit: it should produce a correct lineart
5. Change preprocessor in the second unit to "Canny"
6. Hit the preview button

What you get, like in this screenshot, is that Canny is applied to the control image and not the uploaded image from the second unit (which I would expect)

This also occurs if you generate, so then you get wrongly-made images because the wrong preprocessed image is sent to the model
(IOW I'd have expected the lineart to be applied to the image in the thumbnail at the bottom, not to the openpose stick figure) 

![image](https://github.com/vladmandic/automatic/assets/25192/b1a68f5d-d731-488c-92eb-f68d7624e959)

## Issue 2: Exception raised when resizing with multiple preprocessors

I've noticed that in some combinations of Control preprocessors with more than one unit (None for the first, and  a processed one, e.g. Lineart) for the second along with resize at a specific resolution for the "Before" step (e.g. Lanczos, 832x1216), this check (https://github.com/vladmandic/automatic/blob/3c952675fefd2c94b817940ffbd4cd94fd5876c9/modules/control/processors.py#L216) will actually evaluate to `False` and this means an UnboundLocalError will be raised (because the variables in the subsequent lines are undefined), however I can't quite pinpoint how this can happen (seen in master, but the code is identical in dev). It occurs sporadically.

### Version Platform Description

15:53:31-964490 INFO     Starting SD.Next                                       
15:53:31-984570 INFO     Logger: file="/notebooks/automatic/sdnext.log"         
                         level=INFO size=18509776 mode=append                   
15:53:31-985939 INFO     Python 3.10.10 on Linux                                
15:53:32-032775 INFO     Version: app=sd.next updated=2024-02-10 hash=3c952675  
                         url=https://github.com/vladmandic/automatic/tree/master
15:53:32-185378 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux          
                         release=5.19.0-45-generic python=3.10.10      

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
both issues raised here should now be fixed.
