### ISSUE TITLE
[Issue]: Unable to load model after switching backend to diffusers. 

### ISSUE THREAD

**Issue by Deniryer** [vladmandic/automatic#2841]
### Issue Description

Since las update I'm unable to load most of my checkpoints using diffusers backend. It used to work. Older checkpoint, including original one used to training does work to some extend, after running a couple of gen batches via Agent Scheduler terminal with SDNext crashes. 

### Version Platform Description

<img width="867" alt="Screenshot 2024-02-11 185150" src="https://github.com/vladmandic/automatic/assets/9111055/02da4828-d955-4034-b3b4-be78d9f22e4f">
<img width="867" alt="Screenshot 2024-02-11 185235" src="https://github.com/vladmandic/automatic/assets/9111055/ce2fe3d6-df2c-4c59-8664-8c67f5f46224">

### Relevant log output

```shell
18:35:22-402105 INFO     Select: model="DB\DS3\DS3_89280 [26c165e0c4]"
18:35:22-430104 INFO     Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float16 unet=torch.float16
                         context=no_grad fp16=True bf16=None
18:35:22-432106 INFO     Diffusers: model="Stable Diffusion" class=StableDiffusionPipeline
                         file="G:\AI\SD_Models\DB\DS3\DS3_89280.safetensors" size=8357MB
18:35:22-811685 ERROR    Diffusers failed loading: model=G:\AI\SD_Models\DB\DS3\DS3_89280.safetensors pipeline=Stable
                         Diffusion/NoneType With local_files_only set to False, you must first locally save the
                         tokenizer in the following path: 'openai/clip-vit-large-patch14'.
18:35:22-813192 ERROR    loading model=G:\AI\SD_Models\DB\DS3\DS3_89280.safetensors pipeline=Stable Diffusion/NoneType:
                         ValueError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ G:\SD_Next\venv\lib\site-packages\diffusers\loaders\single_file_utils.py:1229 in create_text_encoders_and_tokenizers ││                                                                                                                      ││   1228 │   │   │   config_name = "openai/clip-vit-large-patch14"                                                     ││ ❱ 1229 │   │   │   text_encoder = create_text_encoder_from_ldm_clip_checkpoint(                                      ││   1230 │   │   │   │   config_name, checkpoint, local_files_only=local_files_only                                    ││                                                                                                                      ││ G:\SD_Next\venv\lib\site-packages\diffusers\loaders\single_file_utils.py:1038 in create_text_encoder_from_ldm_clip_c ││                                                                                                                      ││   1037 │   │   for param_name, param in text_model_dict.items():                                                     ││ ❱ 1038 │   │   │   set_module_tensor_to_device(text_model, param_name, "cpu", value=param)                           ││   1039 │   else:                                                                                                     ││                                                                                                                      ││ G:\SD_Next\venv\lib\site-packages\accelerate\utils\modeling.py:294 in set_module_tensor_to_device                    ││                                                                                                                      ││    293 │   │   for split in splits[:-1]:                                                                             ││ ❱  294 │   │   │   new_module = getattr(module, split)                                                               ││    295 │   │   │   if new_module is None:                                                                            ││                                                                                                                      ││ G:\SD_Next\venv\lib\site-packages\torch\nn\modules\module.py:1688 in __getattr__                                     ││                                                                                                                      ││   1687 │   │   │   │   return modules[name]                                                                          ││ ❱ 1688 │   │   raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")                     ││   1689                                                                                                               │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯AttributeError: 'CLIPTextModel' object has no attribute 'conv_in'

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ G:\SD_Next\modules\sd_models.py:898 in load_diffuser                                                                 ││                                                                                                                      ││    897 │   │   │   │   │   │   modules.sd_hijack_accelerate.restore_accelerate()                                     ││ ❱  898 │   │   │   │   │   sd_model = pipeline.from_single_file(checkpoint_info.path, **diffusers_load_config)       ││    899 │   │   │   │   │   if shared.opts.diffusers_to_gpu:                                                          ││                                                                                                                      ││ G:\SD_Next\venv\lib\site-packages\huggingface_hub\utils\_validators.py:118 in _inner_fn                              ││                                                                                                                      ││   117 │   │                                                                                                          ││ ❱ 118 │   │   return fn(*args, **kwargs)                                                                             ││   119                                                                                                                ││                                                                                                                      ││ G:\SD_Next\venv\lib\site-packages\diffusers\loaders\single_file.py:253 in from_single_file                           ││                                                                                                                      ││   252 │   │   │   else:                                                                                              ││ ❱ 253 │   │   │   │   components = build_sub_model_components(                                                       ││   254 │   │   │   │   │   init_kwargs,                                                                               ││                                                                                                                      ││ G:\SD_Next\venv\lib\site-packages\diffusers\loaders\single_file.py:86 in build_sub_model_components                  ││                                                                                                                      ││    85 │   if component_name in ["text_encoder", "text_encoder_2", "tokenizer", "tokenizer_2"]:                       ││ ❱  86 │   │   text_encoder_components = create_text_encoders_and_tokenizers_from_ldm(                                ││    87 │   │   │   original_config,                                                                                   ││                                                                                                                      ││ G:\SD_Next\venv\lib\site-packages\diffusers\loaders\single_file_utils.py:1235 in create_text_encoders_and_tokenizers ││                                                                                                                      ││   1234 │   │   except Exception:                                                                                     ││ ❱ 1235 │   │   │   raise ValueError(                                                                                 ││   1236 │   │   │   │   f"With local_files_only set to {local_files_only}, you must first locally save the tokenizer  │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯ValueError: With local_files_only set to False, you must first locally save the tokenizer in the following path: 'openai/clip-vit-large-patch14'.
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
you've cut the log just BEFORE the actual error.
post log with error visible.

**Comment by Deniryer** [comment]
It's there. Formatting is screwed for ome reason, when I'm trying to edit it on preview tab it is displayed correctly once saved you need to scroll sideways.  Don't know how to fix formatting since is automatic so I'm going to post a screenshot:
 
<img width="867" alt="Screenshot 2024-02-11 222830" src="https://github.com/vladmandic/automatic/assets/9111055/2d00aa0c-7a65-49f2-a357-fa91764e39bf">

**Comment by Deniryer** [comment]
And another one that occurred just now after switching to original backend:

<img width="867" alt="Screenshot 2024-02-11 223040" src="https://github.com/vladmandic/automatic/assets/9111055/c8deb011-e3d3-411c-8b28-38262e1a56bb">

**Comment by vladmandic** [comment]
are you doing a full server restart after switching backend (not just via ui)? because this looks like server was in inbetween-state, backend was switched but server was not fully restarted.

**Comment by Deniryer** [comment]
Yes. First error (the original log added when I opened issue) occurred after fresh install, second after starting server for the second time with all the setting and extensions reinstalled and last happened just now when I switched orig backend to diffusers and restarted server and it failed loading last used checkpoint with these errors. 

Does not happened when last used checkpoint was vanilla 1.5 or my own checkpoint trained last year.

 
<img width="867" alt="Screenshot 2024-02-11 224219" src="https://github.com/vladmandic/automatic/assets/9111055/069bfc97-0f38-4c7d-8a27-963c1c174e24">

And it really doesn't matter whether I've used Kohya_SS, Dreambooth or any other training module. It won't load it when backend is switched to diffusers. 

I think it might be problem with diffusers, before that I've used 0.25 now I've same problem InvokeAI & A1111. Can't open, convert or extract it.

**Comment by Deniryer** [comment]
Can do, but you'll have to give me a moment, since uploading a 5-8GB (post fine tunning without pruning it weights around 8.8GB) with my upload speed takes ages. I've check the working folder with diffusion model and it seems fine, does have CLIPTokenizer in there. 

After changing this line both OG & Diffusers stopped working
Here is modified output of models.py:
<img width="867" alt="og" src="https://github.com/vladmandic/automatic/assets/9111055/d10469bf-d804-4660-8441-a947d3ddb795">
<img width="867" alt="diff" src="https://github.com/vladmandic/automatic/assets/9111055/5ac01818-1d5c-4e1c-8787-2ccf8935bd3f">

**Comment by vladmandic** [comment]
you made a typo - whitespaces matter in python.
see below:
![image](https://github.com/vladmandic/automatic/assets/57876960/4d1e733b-d5cf-40c6-951b-47f7355b997b)

**Comment by Deniryer** [comment]
In regular notepad seemed fine, Corrected with Notepad++. Now I remember why I hated Python.

Set to both true & false. 
<img width="867" alt="false" src="https://github.com/vladmandic/automatic/assets/9111055/77b547c4-1ef2-467e-82e3-26d23f12575f">
<img width="867" alt="true" src="https://github.com/vladmandic/automatic/assets/9111055/4d44526b-440b-4817-b585-f095ce958575">

**Comment by vladmandic** [comment]
i'll take a look once your model is up, but seems that clip you're baking in is not compatible with standard clip loader.

**Comment by Deniryer** [comment]
Model link:
https://drive.google.com/file/d/1gpKnjqpQlUccgGRU8D24MtNyuQjThvKs/view?usp=sharing

Could usage of DREAM:
https://arxiv.org/abs/2312.00210
Cause this? 

Apart using DREAM I've upgraded SDNext/A1111/InvokeAI, I do test my model in all of them for compatibility sake before publishing it.  Which involved updating diffusers 0.25.0 (both dreambooth ext & Kohya_SS still requires this particular version) there was no major changes has been made to how I trained my model thus far. 

Something during training and then generating final checkpoint had to cause this. 

if so, I'll drop this and start over 4H ish training sessions. Diffusers gave me better gens than OG backend. Nonetheless it's still weird that I can use fine tunned chpt with no problems (including merging via [super merger ](https://github.com/hako-mikan/sd-webui-supermerger)) while switched to original backend.

**Comment by vladmandic** [comment]
i cannot download the model using link you've provided - it just shows "no preview available" and no download button

**Comment by Deniryer** [comment]
Try this one:
https://drive.google.com/file/d/11DiQkyJ8U6MM8hxffEyV6tDPumpPLVG0/view?usp=drive_link
Checked it on edge with & w/o being logged to an account. 
Had to compress it with 7zip, Google did not let me download any model I tried while it had .safetensor file extension.
