### ISSUE TITLE
[Issue]: Memory fallback to system ram if editing prompt

### ISSUE THREAD

**Issue by cgidesign-de** [vladmandic/automatic#2847]
### Issue Description

Nvidia Driver 551.23 on Windows 11
Set to "No System Fallback".

Whenever I set VAE to _Full Quality_ vram goes to max and then vram -> ram fallback happens.

**But:**
this only happens if I edit the prompt while the image generation is active. It does not happen, if I leave the prompt unchanged during image generation.
It also does not happen, if VAE _Full Quality_ is off. In this case prompt editing does not trigger the vram fallback.

Again:
I have no issue with vram to ram fallback, except from when editing the prompt during active image generation.

Installation of Windows is fresh; installation of SD.Next is fresh; no custom extensions installed.

![vram-fallback](https://github.com/vladmandic/automatic/assets/115958660/c83f5682-59c2-4be6-83c1-1cfb8a6445b2)

[sdnext.log](https://github.com/vladmandic/automatic/files/14248031/sdnext.log)

### Version Platform Description

Nvidia Driver 551.23
Windows 11
RTX 4070 Ti Super - 16 GB vram
Intel 13700KF
64 GB ram
Firefox 122.0.1

Starting SD.Next
Python 3.10.11 on Windows
Version: app=sd.next updated=2024-02-10 hash=3c952675
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 183 Stepping 1, GenuineIntel system=Windows release=Windows-10-10.0.22631-SP0 python=3.10.11
nVidia CUDA toolkit detected: nvidia-smi present
Extensions: disabled=[]
Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg'] extensions-builtin

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
when you edit a prompt, it triggers model's tokenizer to update token counters in top-right corner.
if you're generating, that call gets queued so its not impacting generate immediately, but it does get executed as soon as generate completes - so it can be before system garbage collection recovered released memory used during generate.

i've added some extra checks in current dev branch, but i doubt they can solve the problem fully - only solution if you're running that close to the limit would be to completely disable usage of tokenizer as there is no way to tell when torch actually finished with garbage collection unless i add massive delay at the end of each generate we and that is not something i want to do.

**Comment by cgidesign-de** [comment]
Understod that, but in my install there seem to be no tokenizer - at least I don't find it in extensions - and there is no tab for it ?

**Comment by vladmandic** [comment]
Tokenizer is part of the model itself.

**Comment by cgidesign-de** [comment]
Ok then.
