### ISSUE TITLE
[Issue]: Prompt S/R loads the wrong Lora + input box does not auto-extend (and is small)

### ISSUE THREAD

**Issue by SAC020** [vladmandic/automatic#2849]
### Issue Description

Trying to use Prompt S/R to compare two Loras. Prompt is:

```
amateur analog color photo,

<lora:cydohd-mixed-sdxl-v6-civitai:0.7> <lora:sacbf-sacdalle-sdxl-civitai-v2:0.2> <lora:epiCPhotoXL:1>

```
XYZ is:

![image](https://github.com/vladmandic/automatic/assets/50420272/19da56b6-d0b0-4a93-b4cf-d8ce28c3336c)

Lora folder is:

![image](https://github.com/vladmandic/automatic/assets/50420272/217e0fe0-1a72-44a2-b331-bd432165f02c)

Note that the XYZ config seems fine (to me) in the log:

```
07:12:53-971801 DEBUG    xyzgrid: x_type=1|x_values=<lora:cydohd-mixed-sdxl-v6-civitai:0.7>,
                         <lora:cydohd-mixed-sdxl-v7-civitai:0.7>|x_values_dropdown=[]|y_type=51|v2:0.1, v2:0.3,
                         v2:0.5=v2:0.1, v2:0.3, v2:0.5|['Base SXDL', 'Base ViT-H SXDL', 'Plus ViT-H SXDL', 'Plus Face
                         ViT-H SXDL']=['Base SXDL', 'Base ViT-H SXDL', 'Plus ViT-H SXDL', 'Plus Face ViT-H
                         SXDL']|z_type=52|z_values=0.5|z_values_dropdown=['Base SXDL', 'Base ViT-H SXDL', 'Plus ViT-H
                         SXDL', 'Plus Face ViT-H
                         SXDL']|draw_legend=True|include_lone_images=True|include_sub_grids=False|no_grid=False|margin_s
                         ize=0
```

However:

First picture loads "v6-e8" (I asked for v6) and does not load epiCPhotoXL

```
Loading model: C:\ai\automatic\models\Lora\cydohd-mixed-sdxl-v6-civitai-e8.safetensors ━━━━━━━━━━━━ 0.0/228.5 MB -:--:--
Loading model: C:\ai\automatic\models\Lora\sacbf-sacdalle-sdxl-civitai-v2.safetensors ━━━━━━━━━━━━━ 0.0/228.5 MB -:--:--
```

Second picture loads "v7-e8" (I asked for v7) and does not load sacbf-sacdalle-sdxl-civitai-v2

```
Loading model: C:\ai\automatic\models\Lora\cydohd-mixed-sdxl-v7-civitai-e8.safetensors ━━━━━━━━━━━━ 0.0/228.5 MB -:--:--
Loading model: C:\ai\automatic\models\Lora\epiCPhotoXL.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/228.5 MB -:--:--
```

And so on, full log attached. I really don't understand what can cause this.

==

Second issue, on diffusers backend mode, the Prompt S/R box in T2I does not autoextend, and it's quite small. On original backend mode, I remember it auto-extending. I haven't used that mode for a while and did not test is the issue is also present there.

[xyz-prompt-lora-issue.txt](https://github.com/vladmandic/automatic/files/14257596/xyz-prompt-lora-issue.txt)

Thank you

### Version Platform Description

09:42:13-364885 INFO     Starting SD.Next
09:42:13-368356 INFO     Logger: file="C:\ai\automatic\sdnext.log" level=DEBUG size=65 mode=create
09:42:13-369348 INFO     Python 3.10.11 on Windows
09:42:13-625827 INFO     Version: app=sd.next updated=2024-02-10 hash=c61a92d0
                         url=https://github.com/vladmandic/automatic/tree/dev
09:42:14-206837 INFO     Latest published version: 3c952675fefd2c94b817940ffbd4cd94fd5876c9 2024-02-10T10:42:56Z
09:42:14-220229 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev, will push soon.

**Comment by SAC020** [comment]
I'm sorry, but there is something wrong with the lora loader. I'm not even using it in prompt S/R and it picks the wrong ones.

Prompt is asking for <lora:cydohd-mixed-sdxl-v7-civitai:0.7> with 3 loras in total, and it runs on C:\ai\automatic\models\Lora\cydohd-mixed-sdxl-v7-civitai**-e12** instead, and randomly omits one lora

![image](https://github.com/vladmandic/automatic/assets/50420272/494e223d-5854-411d-b5fd-2580dc6295b1)

![image](https://github.com/vladmandic/automatic/assets/50420272/760ae6c7-e9ba-4098-b69a-404b6c04d8fb)

[wrong_lora_log.txt](https://github.com/vladmandic/automatic/files/14299065/wrong_lora_log.txt)

hash=0e91c46a // dev branch

**Comment by SAC020** [comment]
> fixed in dev, will push soon.

I'm sorry, but there is something wrong with the lora loader. I'm not even using it in prompt S/R and it picks the wrong ones.

Prompt is asking for **cydohd-mixed-sdxl-v7-civitai** with 3 loras in total, and it runs on **cydohd-mixed-sdxl-v7-civitai-e12** instead, and randomly omits one lora

![image](https://github.com/vladmandic/automatic/assets/50420272/494e223d-5854-411d-b5fd-2580dc6295b1)

![image](https://github.com/vladmandic/automatic/assets/50420272/760ae6c7-e9ba-4098-b69a-404b6c04d8fb)

[wrong_lora_log.txt](https://github.com/vladmandic/automatic/files/14299065/wrong_lora_log.txt)

hash=0e91c46a // dev branch

**Comment by vladmandic** [comment]
what is your setting for system -> settings -> extra networks -> lora preferred name ?

**Comment by SAC020** [comment]
> this is not related to xyz grid at all, this is due to fact that you have multiple loras that internally have the same alias. i'll add strict by-name instead of by-name and by-alias. update dev branch and set system -> settings -> extra networks -> lora preferred name -> filename

I've seen the original comment, this are the relevant current settings

![image](https://github.com/vladmandic/automatic/assets/50420272/63a8f028-868c-484f-8adb-7d4a398e820a)

**Comment by SAC020** [comment]
> fixed in dev, will push soon.

Are you sure autoextending the S/R box works? Because it doesn't seem to work on my end

![image](https://github.com/vladmandic/automatic/assets/50420272/08286a1c-0ab3-4e03-bb3f-8b622a3614d5)

**Comment by vladmandic** [comment]
no, i did not touch that. original issue was about incorrect lora loading and that is answered.
textarea resizing doesn't work since browsers disable it if height property is set to anything. and if its not set, default height looks ugly.

you can add this to your `user.css` if you want:
```css
textarea[rows="1"] { height: unset !important } 
```
