### ISSUE TITLE
[Feature]: Improve outpainting UI

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#2851]
### Feature description

As per [our discussion](https://discord.com/channels/1101998836328697867/1123710915863388201/1205932501088862318), this seems to be a much more user-friendly way of handling outpainting:

![ui](https://github.com/vladmandic/automatic/assets/108482020/d0a75d7c-7ec8-4c34-a555-02503c4342cb)

https://github.com/Haoming02/sd-webui-mosaic-outpaint

**Comment by vladmandic** [comment]
closing in favor of newly introduced noised-edge-repeat outpainting.
if needed, i'll add additional masking, but that's a separate item.
