### ISSUE TITLE
[Issue]: garbage collector error

### ISSUE THREAD

**Issue by blacklig** [vladmandic/automatic#2864]
### Issue Description

Create and activate python venv
Launching launch.py...
17:44:02-675222 INFO     Starting SD.Next
17:44:02-677322 INFO     Logger: file="/home/sd/automatic/sdnext.log" level=INFO size=43443 mode=append
17:44:02-678183 INFO     Python 3.11.5 on Linux
17:44:02-686122 INFO     Version: app=sd.next updated=2024-02-10 hash=3c952675 url=https://github.com/vladmandic/automatic.git/tree/master
17:44:03-016328 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=6.5.0-17-generic python=3.11.5
17:44:03-017817 INFO     nVidia CUDA toolkit detected: nvidia-smi present
17:44:03-028280 INFO     Extensions: disabled=[]
17:44:03-028974 INFO     Extensions: enabled=['sd-webui-controlnet', 'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser', 'Lora',
                         'stable-diffusion-webui-rembg', 'sd-extension-chainner', 'sd-extension-system-info'] extensions-builtin
17:44:03-030165 INFO     Extensions: enabled=[] extensions
17:44:03-030830 INFO     Startup: quick launch
17:44:03-031350 INFO     Verifying requirements
17:44:03-045895 INFO     Verifying packages
17:44:03-047377 INFO     Extensions: disabled=[]
17:44:03-047959 INFO     Extensions: enabled=['sd-webui-controlnet', 'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser', 'Lora',
                         'stable-diffusion-webui-rembg', 'sd-extension-chainner', 'sd-extension-system-info'] extensions-builtin
17:44:03-048977 INFO     Extensions: enabled=[] extensions
17:44:03-050779 INFO     Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
17:44:03-051747 INFO     Command line args: ['--port', '7681'] port=7681
17:44:06-631208 INFO     Load packages: {'torch': '2.2.0+cu121', 'diffusers': '0.26.2', 'gradio': '3.43.2'}
17:44:06-991403 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product" mode=no_grad
17:44:06-994686 INFO     Device: error=garbage_collect_threshold too small, set it 0.0~1.0

### Version Platform Description

So starting next sd (usually I would say I have experience with this nice application, yet now installed it on new machine (and slightly newer version than my last experience was with) and got this nasty error which I dont know much about.. how do I set that garbage collector treshold if source of error? Why it wont set itself if it detected this as cause of problem?

Thanks

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i have not seen this error before, it seems gc level is set to invalid value in the environment somehow.
please run:
> export SD_ENV_DEBUG=true
> ./webui.sh --debug

and upload the full log.

**Comment by vladmandic** [comment]
any updates?

**Comment by blacklig** [comment]
Hi, did not had time to work on this machine yet.. on another machines it works so kinda strange but once I get to it I will post update. Thanks for your attention and quick replies indeed!

**Comment by blacklig** [comment]
Hi, get to that machine and ran what you suggest and here is output:

(base) ➜  automatic git:(master) ✗ ./webui.sh --debug
Create and activate python venv
Launching launch.py...
14:28:20-794853 INFO     Starting SD.Next
14:28:20-796965 INFO     Logger: file="/home/sd/automatic/sdnext.log" level=DEBUG size=64
                         mode=create
14:28:20-797886 INFO     Python 3.11.5 on Linux
14:28:20-805928 INFO     Version: app=sd.next updated=2024-02-18 hash=9c12b747
                         url=https://github.com/vladmandic/automatic.git/tree/master
14:28:20-992269 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=6.5.0-17-generic
                         python=3.11.5
14:28:20-993196 DEBUG    Setting environment tuning
14:28:20-993816 DEBUG    HF cache folder: /home/sd/.cache/huggingface/hub
14:28:20-994418 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False
                         openvino=False
14:28:20-995180 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
14:28:20-996170 INFO     nVidia CUDA toolkit detected: nvidia-smi present
14:28:21-006453 DEBUG    Repository update time: Sun Feb 18 23:40:13 2024
14:28:21-007116 INFO     Startup: standard
14:28:21-007610 INFO     Verifying requirements
14:28:21-021876 INFO     Verifying packages
14:28:21-023240 INFO     Verifying submodules
14:28:21-291276 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
14:28:21-296931 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
14:28:21-302246 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
14:28:21-307837 DEBUG    Submodule: extensions-builtin/sd-webui-controlnet / main
14:28:21-320648 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-images-browser /
                         main
14:28:21-326078 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
14:28:21-331205 DEBUG    Submodule: modules/k-diffusion / master
14:28:21-336376 DEBUG    Submodule: modules/lora / main
14:28:21-342040 DEBUG    Submodule: wiki / master
14:28:21-345714 DEBUG    Register paths
14:28:21-386419 DEBUG    Installed packages: 244
14:28:21-387064 DEBUG    Extensions all: ['sd-webui-controlnet', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'Lora',
                         'stable-diffusion-webui-rembg', 'sd-extension-chainner',
                         'sd-extension-system-info']
14:28:21-387864 DEBUG    Running extension installer:
                         /home/sd/automatic/extensions-builtin/sd-webui-controlnet/install.py
14:28:21-572359 DEBUG    Running extension installer:
                         /home/sd/automatic/extensions-builtin/sd-webui-agent-scheduler/install.p
                         y
14:28:21-738003 DEBUG    Running extension installer:
                         /home/sd/automatic/extensions-builtin/stable-diffusion-webui-images-brow
                         ser/install.py
14:28:21-941788 DEBUG    Running extension installer:
                         /home/sd/automatic/extensions-builtin/stable-diffusion-webui-rembg/insta
                         ll.py
14:28:22-145603 DEBUG    Running extension installer:
                         /home/sd/automatic/extensions-builtin/sd-extension-system-info/install.p
                         y
14:28:22-310343 DEBUG    Extensions all: []
14:28:22-310984 INFO     Extensions enabled: ['sd-webui-controlnet', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'Lora',
                         'stable-diffusion-webui-rembg', 'sd-extension-chainner',
                         'sd-extension-system-info']
14:28:22-311695 INFO     Verifying requirements
14:28:22-325928 DEBUG    Setup complete without errors: 1708522102
14:28:22-327706 INFO     Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
14:28:22-328500 DEBUG    Starting module: <module 'webui' from '/home/sd/automatic/webui.py'>
14:28:22-329275 INFO     Command line args: ['--debug'] debug=True
14:28:22-329927 TRACE    Environment: SHELL=/usr/bin/zsh LSCOLORS=Gxfxcxdxbxegedabagacad LESS=-R
                         CONDA_EXE=/home/sd/anaconda3/bin/conda _CE_M= LC_ADDRESS=cs_CZ.UTF-8
                         LC_NAME=cs_CZ.UTF-8 LC_MONETARY=cs_CZ.UTF-8 PWD=/home/sd/automatic
                         LOGNAME=sd XDG_SESSION_TYPE=tty CONDA_PREFIX=/home/sd/anaconda3
                         MOTD_SHOWN=pam HOME=/home/sd LC_PAPER=cs_CZ.UTF-8 LANG=en_US.UTF-8
                         LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;
                         33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:
                         ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;
                         31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01
                         ;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31
                         :*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.
                         tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.
                         deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.
                         rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.
                         rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.j
                         pg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35
                         :*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35
                         :*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;
                         35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01
                         ;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v
                         =01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=0
                         1;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=0
                         1;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01
                         ;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00
                         ;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=0
                         0;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=
                         00;36: VIRTUAL_ENV=/home/sd/automatic/venv CONDA_PROMPT_MODIFIER=(base)
                         LC_TERMINAL=iTerm2 SSH_CONNECTION=192.168.88.1 62480 192.168.88.101 22
                         XDG_SESSION_CLASS=user LC_IDENTIFICATION=cs_CZ.UTF-8 TERM=xterm-256color
                         ZSH=/home/sd/.oh-my-zsh _CE_CONDA= USER=sd GIT=git SD_ENV_DEBUG=true
                         CONDA_SHLVL=1 PIP_IGNORE_INSTALLED=0 LC_TERMINAL_VERSION=3.4.22 SHLVL=1
                         PAGER=less LC_TELEPHONE=cs_CZ.UTF-8 LC_MEASUREMENT=cs_CZ.UTF-8
                         XDG_SESSION_ID=1339 VIRTUAL_ENV_PROMPT=(venv)
                         CONDA_PYTHON_EXE=/home/sd/anaconda3/bin/python
                         LD_LIBRARY_PATH=/usr/local/cuda-12/lib64::/home/sd/automatic/venv/lib/
                         LC_CTYPE=C.UTF-8 XDG_RUNTIME_DIR=/run/user/1000 SSH_CLIENT=192.168.88.1
                         62480 22 CONDA_DEFAULT_ENV=base LC_TIME=cs_CZ.UTF-8
                         CUDA_HOME=/usr/local/cuda-12
                         DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus SSH_TTY=/dev/pts/0
                         ERROR_REPORTING=FALSE LC_NUMERIC=cs_CZ.UTF-8 OLDPWD=/home/sd/automatic
                         ACCELERATE=True ATTN_PRECISION=fp16 CUDA_AUTO_BOOST=1
                         CUDA_CACHE_DISABLE=0
                         CUDA_DEVICE_DEFAULT_PERSISTING_L2_CACHE_PERCENTAGE_LIMIT=0
                         CUDA_LAUNCH_BLOCKING=0 CUDA_MODULE_LOADING=LAZY
                         TORCH_CUDNN_V8_API_ENABLED=1 FORCE_CUDA=1 GRADIO_ANALYTICS_ENABLED=False
                         HF_HUB_DISABLE_EXPERIMENTAL_WARNING=1 HF_HUB_DISABLE_TELEMETRY=1
                         K_DIFFUSION_USE_COMPILE=0 NUMEXPR_MAX_THREADS=16 PYTHONHTTPSVERIFY=0
                         PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.8,max_split_size_
                         mb:512 SAFETENSORS_FAST_GPU=1 TF_CPP_MIN_LOG_LEVEL=2
                         TF_ENABLE_ONEDNN_OPTS=0 USE_TORCH=1 UVICORN_TIMEOUT_KEEP_ALIVE=60
                         KINETO_LOG_LEVEL=3 DO_NOT_TRACK=1
                         HF_HUB_CACHE=/home/sd/.cache/huggingface/hub
14:28:25-311476 DEBUG    Package not found: olive-ai
14:28:25-948280 INFO     Load packages: {'torch': '2.2.0+cu121', 'diffusers': '0.26.2', 'gradio':
                         '3.43.2'}
14:28:26-309765 DEBUG    Read: file="config.json" json=13 bytes=503 time=0.000
14:28:26-312196 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda
                         attention="Scaled-Dot-Product" mode=no_grad
14:28:26-314142 INFO     Device: error=garbage_collect_threshold too small, set it 0.0~1.0
14:28:26-314942 DEBUG    Migrated styles: file=styles.csv folder=models/styles
14:28:26-318960 DEBUG    Load styles: folder="models/styles" items=288 time=0.00
[1]    143337 segmentation fault (core dumped)  ./webui.sh --debug
(base) ➜  automatic git:(master) ✗

**Comment by blacklig** [comment]
export PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.99 => INFO     Device: error=garbage_collect_threshold too small, set it 0.0~1.0

 export PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:1.0 =>  INFO     Device: error=garbage_collect_threshold too big, set it 0.0~1.0
 
 🤷🏻‍♂️

**Comment by blacklig** [comment]
So changed this settings and got:

(venv) (base) ➜  automatic git:(master) ✗ ./webui.sh --debug
Create and activate python venv
Launching launch.py...
16:41:58-638778 INFO     Starting SD.Next
16:41:58-640888 INFO     Logger: file="/home/sd/automatic/sdnext.log" level=DEBUG size=64 mode=create
16:41:58-641759 INFO     Python 3.11.5 on Linux
16:41:58-649767 INFO     Version: app=sd.next updated=2024-02-18 hash=9c12b747
                         url=https://github.com/vladmandic/automatic.git/tree/master
16:41:58-984044 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=6.5.0-17-generic python=3.11.5
16:41:58-984931 DEBUG    Setting environment tuning
16:41:58-985561 DEBUG    HF cache folder: /home/sd/.cache/huggingface/hub
16:41:58-986175 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
16:41:58-986900 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
16:41:58-987901 INFO     nVidia CUDA toolkit detected: nvidia-smi present
16:41:58-998129 DEBUG    Repository update time: Sun Feb 18 23:40:13 2024
16:41:58-998797 INFO     Startup: standard
16:41:58-999301 INFO     Verifying requirements
16:41:59-013975 INFO     Verifying packages
16:41:59-015361 INFO     Verifying submodules
16:41:59-282411 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
16:41:59-288050 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
16:41:59-293311 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
16:41:59-298948 DEBUG    Submodule: extensions-builtin/sd-webui-controlnet / main
16:41:59-311909 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-images-browser / main
16:41:59-317192 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
16:41:59-322429 DEBUG    Submodule: modules/k-diffusion / master
16:41:59-327658 DEBUG    Submodule: modules/lora / main
16:41:59-333287 DEBUG    Submodule: wiki / master
16:41:59-336996 DEBUG    Register paths
16:41:59-377467 DEBUG    Installed packages: 244
16:41:59-378136 DEBUG    Extensions all: ['sd-webui-controlnet', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'Lora', 'stable-diffusion-webui-rembg', 'sd-extension-chainner',
                         'sd-extension-system-info']
16:41:59-378951 DEBUG    Running extension installer: /home/sd/automatic/extensions-builtin/sd-webui-controlnet/install.py
16:41:59-564759 DEBUG    Running extension installer: /home/sd/automatic/extensions-builtin/sd-webui-agent-scheduler/install.py
16:41:59-729419 DEBUG    Running extension installer:
                         /home/sd/automatic/extensions-builtin/stable-diffusion-webui-images-browser/install.py
16:41:59-934149 DEBUG    Running extension installer: /home/sd/automatic/extensions-builtin/stable-diffusion-webui-rembg/install.py
16:42:00-147157 DEBUG    Running extension installer: /home/sd/automatic/extensions-builtin/sd-extension-system-info/install.py
16:42:00-312630 DEBUG    Extensions all: []
16:42:00-313299 INFO     Extensions enabled: ['sd-webui-controlnet', 'sd-webui-agent-scheduler',
                         'stable-diffusion-webui-images-browser', 'Lora', 'stable-diffusion-webui-rembg', 'sd-extension-chainner',
                         'sd-extension-system-info']
16:42:00-314548 INFO     Verifying requirements
16:42:00-335628 DEBUG    Setup complete without errors: 1708530120
16:42:00-338112 INFO     Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
16:42:00-339362 DEBUG    Starting module: <module 'webui' from '/home/sd/automatic/webui.py'>
16:42:00-340741 INFO     Command line args: ['--debug'] debug=True
16:42:00-341809 TRACE    Environment: SHELL=/usr/bin/zsh LSCOLORS=Gxfxcxdxbxegedabagacad LESS=-R
                         CONDA_EXE=/home/sd/anaconda3/bin/conda _CE_M= LC_ADDRESS=cs_CZ.UTF-8 LC_NAME=cs_CZ.UTF-8
                         LC_MONETARY=cs_CZ.UTF-8 PWD=/home/sd/automatic LOGNAME=sd XDG_SESSION_TYPE=tty
                         CONDA_PREFIX=/home/sd/anaconda3 MOTD_SHOWN=pam HOME=/home/sd LC_PAPER=cs_CZ.UTF-8 LANG=en_US.UTF-8
                         LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=0
                         0:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj
                         =01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.
                         t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=
                         01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.ja
                         r=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*
                         .7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:
                         *.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=0
                         1;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.m
                         ov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;3
                         5:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01
                         ;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01
                         ;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=
                         00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.op
                         us=00;36:*.spx=00;36:*.xspf=00;36: VIRTUAL_ENV=/home/sd/automatic/venv CONDA_PROMPT_MODIFIER=(base)
                         LC_TERMINAL=iTerm2 SSH_CONNECTION=192.168.88.1 62480 192.168.88.101 22
                         PYTORCH_CUDA_ALLOC_CONF=max_split_size:mb:512 XDG_SESSION_CLASS=user LC_IDENTIFICATION=cs_CZ.UTF-8
                         TERM=xterm-256color ZSH=/home/sd/.oh-my-zsh _CE_CONDA= USER=sd GIT=git SD_ENV_DEBUG=true CONDA_SHLVL=1
                         PIP_IGNORE_INSTALLED=0 LC_TERMINAL_VERSION=3.4.22 SHLVL=1 PAGER=less LC_TELEPHONE=cs_CZ.UTF-8
                         LC_MEASUREMENT=cs_CZ.UTF-8 XDG_SESSION_ID=1339 VIRTUAL_ENV_PROMPT=(venv)
                         CONDA_PYTHON_EXE=/home/sd/anaconda3/bin/python
                         LD_LIBRARY_PATH=/usr/local/cuda-12/lib64::/home/sd/automatic/venv/lib/ LC_CTYPE=C.UTF-8
                         XDG_RUNTIME_DIR=/run/user/1000 SSH_CLIENT=192.168.88.1 62480 22 CONDA_DEFAULT_ENV=base LC_TIME=cs_CZ.UTF-8
                         CUDA_HOME=/usr/local/cuda-12 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus SSH_TTY=/dev/pts/0
                         ERROR_REPORTING=FALSE LC_NUMERIC=cs_CZ.UTF-8 OLDPWD=/home/sd/automatic ACCELERATE=True ATTN_PRECISION=fp16
                         CUDA_AUTO_BOOST=1 CUDA_CACHE_DISABLE=0 CUDA_DEVICE_DEFAULT_PERSISTING_L2_CACHE_PERCENTAGE_LIMIT=0
                         CUDA_LAUNCH_BLOCKING=0 CUDA_MODULE_LOADING=LAZY TORCH_CUDNN_V8_API_ENABLED=1 FORCE_CUDA=1
                         GRADIO_ANALYTICS_ENABLED=False HF_HUB_DISABLE_EXPERIMENTAL_WARNING=1 HF_HUB_DISABLE_TELEMETRY=1
                         K_DIFFUSION_USE_COMPILE=0 NUMEXPR_MAX_THREADS=16 PYTHONHTTPSVERIFY=0 SAFETENSORS_FAST_GPU=1
                         TF_CPP_MIN_LOG_LEVEL=2 TF_ENABLE_ONEDNN_OPTS=0 USE_TORCH=1 UVICORN_TIMEOUT_KEEP_ALIVE=60
                         KINETO_LOG_LEVEL=3 DO_NOT_TRACK=1 HF_HUB_CACHE=/home/sd/.cache/huggingface/hub
16:42:03-329544 DEBUG    Package not found: olive-ai
16:42:03-962857 INFO     Load packages: {'torch': '2.2.0+cu121', 'diffusers': '0.26.2', 'gradio': '3.43.2'}
16:42:04-323296 DEBUG    Read: file="config.json" json=13 bytes=503 time=0.000
16:42:04-325716 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product" mode=no_grad
16:42:04-327604 INFO     Device: error=Unrecognized CachingAllocator option: max_split_size
16:42:04-328278 DEBUG    Migrated styles: file=styles.csv folder=models/styles
16:42:04-332214 DEBUG    Load styles: folder="models/styles" items=288 time=0.00
[1]    148434 segmentation fault (core dumped)  ./webui.sh --debug
(venv) (base) ➜  automatic git:(master) ✗



Cannot be some problem with CUDA toolkit for example? I never know if I have version nvidia-smi shows or different but it shows this:


(venv) (base) ➜  automatic git:(master) ✗ nvidia-smi
Wed Feb 21 16:44:05 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.23.08              Driver Version: 545.23.08    CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 3090        On  | 00000000:01:00.0 Off |                  N/A |
|  0%   37C    P8              24W / 350W |      3MiB / 24576MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+


PyTorch I have latest and I even tried to run it in different conda environments with newest pytorch and cuda where it worked for diffusers and some pytorch trainings etc.. so really strange that your next sd is having this kind of troubles... Also I installed fresh on another machine and there it runs.. on this machine I tried to clone into new folders this repo and same errors as we are solving.. so deff. some problem with this machine but what can it be?

**Comment by blacklig** [comment]
Wow, looks like this fixed it!

INFO     Startup time: 11.76 torch=2.92 olive=3.85 gradio=0.40
                         libraries=1.59 extensions=0.81 face-restore=0.26
                         ui-en=0.24 ui-train=0.19 ui-settings=0.32
                         ui-extensions=0.30 ui-defaults=0.05 launch=0.10
                         api=0.08 app-started=0.34


So what was this method doing that it caused those? Will it now be slower or "worse" in any way?

Thanks :)

**Comment by blacklig** [comment]
ok.

nice to see your deep knowledge of torch etc. I am still lacking here :)

Anyways, will let you know if I run into some troubles on this specific machine, will be interesting to observe this even for me if that would behave somehow differently when for example being full VRAM etc..

**Comment by vladmandic** [comment]
added `--skip-env` command line flag to dev branch, so closing the issue.
