### ISSUE TITLE
[Issue]: Washed out images with SDXL & Olive-AI backend

### ISSUE THREAD

**Issue by Arcadia245** [vladmandic/automatic#2865]
### Issue Description

Hi everyone. I'm currently running Olive-AI backend with a Radeon 7900 xtx for SDXL. Images that are generated while running Olive-AI appear washed out. This did not happen when I tried OpenVino, but only with Olive-AI. I've tried compiling a new sdxl model with the vae fp16 fix, which didn't work either. The issue seems related to the one here: https://github.com/vladmandic/automatic/issues/2824

According to Disty this was fixed, but ONYX could need a work around. I attached a image of how outputs with SDXL look when running Olive-AI. The steps to reproduce the issue is to run Olive-AI backend, compile a SDXL model and generate a image. 

![02328-sd_xl_base_1](https://github.com/vladmandic/automatic/assets/122177052/ef162cd6-bd5b-4507-a5dc-1870999a62a2)

### Version Platform Description

Starting SD.Next
13:39:12-971167 INFO     Logger: file="C:\SDNEXT\automatic\sdnext.log" level=INFO size=12754974 mode=append
13:39:12-972171 INFO     Python 3.10.11 on Windows
13:39:13-100546 INFO     Version: app=sd.next updated=2024-02-14 hash=a956be05
                         url=https://github.com/vladmandic/automatic/tree/dev
13:39:13-376589 INFO     Latest published version: 3c952675fefd2c94b817940ffbd4cd94fd5876c9 2024-02-10T10:42:56Z
13:39:13-383913 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11

### Relevant log output

```shell
None
```

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this should be fixed in the latest release. if issue persists, report here and i'll reopen.
