### ISSUE TITLE
[Extension]: Depthmap Extension broken on latest dev

### ISSUE THREAD

**Issue by aaronsantiago** [vladmandic/automatic#2867]
### Issue Description

I'm forgoing putting an issue in the extension repository as this was working very recently. The attached logs are from attempting inference through the web UI, though I get the same error through the API as well.

```
DepthMap v0.4.6 (51ea821c)
Traceback (most recent call last):
  File "/home/onx/workspace/auto-diffusers-dev/extensions/stable-diffusion-webui-depthmap-script/src/common_ui.py", line 532, in run_generate
    input_i, type, result = next(gen_obj)
  File "/home/onx/workspace/auto-diffusers-dev/extensions/stable-diffusion-webui-depthmap-script/src/core.py", line 94, in core_generation_funnel
    backbone.unload_sd_model()
  File "/home/onx/workspace/auto-diffusers-dev/extensions/stable-diffusion-webui-depthmap-script/src/backbone.py", line 64, in unload_sd_model
    shared.sd_model.cond_stage_model.to(devices.cpu)
  File "/home/onx/workspace/auto-diffusers-dev/venv/lib/python3.10/site-packages/diffusers/configuration_utils.py", line 142, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'StableDiffusionXLPipeline' object has no attribute 'cond_stage_model'

```

### Version Platform Description

18:55:12-819290 INFO     Starting SD.Next
18:55:12-820789 INFO     Logger:
                         file="/home/onx/workspace/auto-diffusers-dev/sdnext.log"
                         level=INFO size=109370 mode=append
18:55:12-821361 INFO     Python 3.10.12 on Linux
18:55:12-826024 INFO     Version: app=sd.next updated=2024-02-10 hash=3c952675
                         url=https://github.com/vladmandic/automatic/tree/master
18:55:12-985573 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux
                         release=6.5.0-17-generic python=3.10.12
18:55:12-989988 INFO     nVidia CUDA toolkit detected: nvidia-smi present
18:55:13-004311 WARNING  Modified files:
                         ['stable_fast-1.0.3+torch212cu121-cp310-cp310-manylinux2014_x8
                         6_64.whl']
18:55:13-007432 INFO     Extensions: disabled=[]
18:55:13-009629 INFO     Extensions: enabled=['stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'sd-webui-agent-scheduler',
                         'sd-extension-system-info', 'Lora', 'sd-extension-chainner',
                         'sd-webui-controlnet'] extensions-builtin
18:55:13-012861 INFO     Extensions: enabled=['stable-diffusion-webui-depthmap-script']
                         extensions
18:55:13-014832 INFO     Startup: standard
18:55:13-015911 INFO     Verifying requirements
18:55:13-029896 INFO     Verifying packages
18:55:13-030795 INFO     Verifying submodules
18:55:14-235099 INFO     Extensions enabled: ['stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'sd-webui-agent-scheduler',
                         'sd-extension-system-info', 'Lora', 'sd-extension-chainner',
                         'sd-webui-controlnet',
                         'stable-diffusion-webui-depthmap-script']
18:55:14-235715 INFO     Verifying requirements
18:55:14-242984 INFO     Extension preload: {'extensions-builtin': 0.0, 'extensions':
                         0.0}
18:55:14-243716 INFO     Command line args: ['--listen', '--docs', '--cors-origins',
                         '*', '--insecure'] insecure=True listen=True docs=True
                         cors_origins=*
18:55:16-059084 INFO     Load packages: {'torch': '2.1.2+cu121', 'diffusers': '0.26.2',
                         'gradio': '3.43.2'}
18:55:16-292359 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda
                         attention="Scaled-Dot-Product" mode=no_grad
18:55:16-305284 INFO     Device: device=NVIDIA GeForce RTX 4090 n=1 arch=sm_90 cap=(8,
                         9) cuda=12.1 cudnn=8902 driver=535.154.05
18:55:16-634555 INFO     ONNX: selected=CUDAExecutionProvider,
                         available=['TensorrtExecutionProvider',
                         'CUDAExecutionProvider', 'AzureExecutionProvider',
                         'CPUExecutionProvider']
18:55:16-665026 INFO     Available VAEs: path="models/VAE" items=0
18:55:16-665657 INFO     Disabled extensions: ['sd-webui-controlnet']
18:55:16-666379 INFO     Available models: path="models/Stable-diffusion" items=1
                         time=0.00
18:55:16-791616 INFO     LoRA networks: available=0 folders=2
18:55:16-900831 INFO     Extension:
                         script='extensions-builtin/sd-webui-agent-scheduler/scripts/ta
                         sk_scheduler.py' Using sqlite file:
                         extensions-builtin/sd-webui-agent-scheduler/task_scheduler.sql
                         ite3
18:55:17-206332 INFO     Extension:
                         script='extensions/stable-diffusion-webui-depthmap-script/scri
                         pts/depthmap_api.py' Started the depthmap API. DO NOT HOST
                         PUBLICLY - SECURITY RISKS!
18:55:17-209998 INFO     Extensions init time: 0.47 sd-webui-agent-scheduler=0.10
                         stable-diffusion-webui-images-browser=0.08
                         stable-diffusion-webui-depthmap-script=0.22
18:55:17-216836 INFO     Load UI theme: name="black-teal" style=Auto base=sdnext.css
18:55:17-911828 INFO     Local URL: http://localhost:7860/
18:55:17-912362 INFO     API Docs: http://localhost:7860/docs
18:55:17-912732 INFO     API ReDocs: http://localhost:7860/redocs
18:55:17-913091 INFO     Initializing middleware
18:55:18-146522 INFO     [AgentScheduler] Task queue is empty
18:55:18-147173 INFO     [AgentScheduler] Registering APIs
18:55:18-207022 INFO     Select: model="SDXLFaetastic_v24 [07b985d12f]"
18:55:18-221655 INFO     Setting Torch parameters: device=cuda dtype=torch.float16
                         vae=torch.float16 unet=torch.float16 context=no_grad fp16=True
                         bf16=None
18:55:18-222410 INFO     Autodetect: model="Stable Diffusion XL"
                         class=StableDiffusionXLPipeline
                         file="/home/onx/workspace/auto-diffusers-dev/models/Stable-dif
                         fusion/SDXLFaetastic_v24.safetensors" size=6617MB
18:55:20-966694 INFO     Load embeddings: loaded=0 skipped=0 time=0.00
18:55:21-123330 INFO     Load model: time=2.76 load=2.76 native=1024 {'ram': {'used':
                         11.43, 'total': 62.56}, 'gpu': {'used': 7.51, 'total': 23.63},
                         'retries': 0, 'oom': 0}
18:55:21-124872 INFO     Startup time: 6.88 torch=1.38 gradio=0.42 libraries=0.60
                         extensions=0.47 face-restore=0.07 ui-en=0.08 ui-settings=0.07
                         ui-extensions=0.32 launch=0.06 app-started=0.25
                         checkpoint=2.92
18:55:46-222385 INFO     MOTD: N/A
18:55:49-948742 INFO     Browser session: user=None client=10.10.1.105
                         agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0
                         Safari/537.36

### URL link of the extension

https://github.com/thygate/stable-diffusion-webui-depthmap-script

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
looking at the code, extension is trying to unload model components that don't exist in diffusers mode.
the rest of the extension seems fine, but it should not attempt to unload core model if its unsure what its doing - if you want to make it work in diffusers mode, report to extension author:
for example:
```py
        if shared.sd_model is not None:
            shared.sd_model.cond_stage_model.to(devices.cpu)
            shared.sd_model.first_stage_model.to(devices.cpu)
```
```
should be safe-checked into:
        if shared.sd_model is not None and shared.sd_model.cond_stage_model is not None:
            shared.sd_model.cond_stage_model.to(devices.cpu)
        if shared.sd_model is not None and shared.sd_model.first_stage_model is not None:
            shared.sd_model.first_stage_model.to(devices.cpu)
```

otherwise, extension works in original backend. not in diffusers backend - it just cant without author making the necessary changes.
