### ISSUE TITLE
[Issue]: windows 11, Cannot run without a checkpoint

### ISSUE THREAD

**Issue by DiGregorioC** [vladmandic/automatic#287]
### Issue Description

When running webui.bat, after it asks me if I want to download the default model. I get an error of 

Cannot run without a checkpoint

### Version Platform Description

Version: e6701f5c Wed Apr 19 14:12:19 2023 -0400

Windows 11

**Comment by vladmandic** [comment]
if you answer no, thats exactly what should happen. 
expectation is you don't want to download default model as you will provide yours.
what is the issue?

**Comment by DiGregorioC** [comment]
Sorry, when I specify yes, it doesn't actually seem to download. I have a bunch of models from a1111 that I can move over, but the regular "yes" does not seem to actually download anything

**Comment by vladmandic** [comment]
> if key.lower().startswith == 'y':

it does, i just tested.
and you don't need to move over models, you can just symlink folders so they are shared

**Comment by DiGregorioC** [comment]
Closing. I was able to fix this by copying the models over. Not idea, but working now

**Comment by nistvan86** [comment]
So, I might completely misunderstood what this should do, but answering with "y" it still doesn't download a default model.

![image](https://user-images.githubusercontent.com/829428/233429220-81494025-4b54-4659-a957-4f4ba3dd2e25.png)

**Comment by vladmandic** [comment]
there was a typo that doesn't handle "y" answer correctly, fixed.

**Comment by VeMeth** [comment]
Wouldn't it be cool to just ask for the Stable-Diffusion model path if someone says no? If someone answers no, they probably already have a model folder somewhere they want to change into. So you could ask there for the path to the models and set it for them. Right now you have to say no, copy a model over from your 1111 install, boot up, change the path and delete the model again you just copied over.

**Comment by vladmandic** [comment]
you don't need to do any of that, you can start using `--ckpt <path_to_model_file>` which takes priority over everything else.

**Comment by VeMeth** [comment]
> you don't need to do any of that, you can start using `--ckpt <path_to_model_file>` which takes priority over everything else.

Thank you, maybe change the exit message to 

`Cannot run without a checkpoint, use --ckpt <path_to_model_file> for an existing checkpoint on your system` . So people know instantly what to do.

**Comment by timsss** [comment]
i have safetensors models and get Cannot generate without a checkpoint
Available models: path="models\Stable-diffusion" items=0 time=0.00

**Comment by vladmandic** [comment]
commenting on issue closed 1 year ago does not help, please document and create new issue.
