### ISSUE TITLE
[Issue]: model not loaded

### ISSUE THREAD

**Issue by technofox01** [vladmandic/automatic#2870]
### Issue Description

I have an AMD 6600XT 8GB GPU. I keep on getting the Error: model not loaded irrespective of the different configurations that I have tried, such as --no-vae-full, --full-precision, --FP32, et al. I have no issues running the DirectML version of Automitic1111 and I had SD.Next version working until a recent update broke it. I would appreciate any help on this.

### Version Platform Description

Windows 11
Ryzen 5700G
6600XT 8GB GPU
64GB of DDR4 RAM

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
upload actual log and version information. marking as invalid for now as no information provided.

**Comment by vladmandic** [comment]
closing since no information is provided.
