### ISSUE TITLE
[Issue]: Refiner not working properly for SD1.5 models

### ISSUE THREAD

**Issue by drhead** [vladmandic/automatic#2875]
### Issue Description

Refiner models do not seem to be functioning properly at all on the second pass.

I am currently using a custom model which I have trained along with a refiner model by training its last 200 timesteps only, which is the same training regime used for the XL refiner and is fairly easy to implement.  The typical implementation for this is:

1. load primary model, denoise until 80%
2. at 80%, swap out for the refiner model and resume denoising along the same schedule.

This is the implementation that A1111 uses.  It is flawed for a specific reason which I will go over later, but it works well enough at least on the default schedule and can be made to work with others.  SD.Next implements the refiner as a second pass though, so necessarily the refiner works differently.

In SD.Next, the refiner is implemented as a second pass option.  I would expect that when I select refiner switchover at 0.8 and 20 refiner steps for a 50 step base model run, that I would get the base model to either run for 40 steps and cut off or run for 50 steps and return a latent that is 80% denoised, and to hand it off to the refiner which then denoises the rest of the way over 20 steps (realistically this wouldn't be that simple under the hood, you'd have to get somewhat creative with the sampling schedules to get them to line up completely right).  What appears to be happening instead, is that the base model runs 50 steps in full, and the *completely* denoised latent is passed to the refiner, which then denoises it in full.  Since the first 800 timesteps of the refiner have been turned into soup, this results in broken output.

I understand that this is likely an issue mainly because Diffusers has not implemented the necessary input arguments for the regular SD pipeline that allow returning partial latents or resuming off of partial latents, since I had to manually patch Diffusers for this when writing validation code for refiner training, if that is the case then monkey patching Diffusers would likely be the only fix.

As for the best method to implement this properly (and something that will make SDXL's refiner and any other ensemble of expert denoiser model work much more reliably) -- one issue that can arise with refiners is related to noise schedule changes, such as when using the Karras schedule with rescaled zero snr betas (for most frontends, this is handled by effectively setting sigma_max to ~4500 which is high enough for the model to sample from the last timestep).  This offsets the rest of the noise schedule to where timestep 200 isn't sampled until about 88% of the way into sampling, and I don't think any frontend currently handles this case properly.  If you want to ensure that a refiner is only used at an appropriate time, the best way to handle refiner switchover is by timestep, not by some percentage of the sampling process.  SDXL's refiner for example should *never* be called unless it is for a timestep less than or equal to 199.  Additionally, if using a high-res pass and denoising goes higher than timestep 200, there is no real point in using it except on the high res pass, because anything the refiner would have done on the first pass will be completely obliterated the second the high res pass starts.

### Version Platform Description

Python 3.11.8 on Linux
Version: app=sd.next updated=2024-02-10 hash=3c952675 url=https://github.com/vladmandic/automatic.git/tree/master
Platform: arch=x86_64 cpu=x86_64 system=Linux release=6.1.21.2-microsoft-standard-WSL2 python=3.11.8
Load packages: {'torch': '2.2.0', 'diffusers': '0.26.2', 'gradio': '3.43.2'}
Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product" mode=no_grad
Device: device=NVIDIA GeForce RTX 3090 n=1 arch=sm_90 cap=(8, 6) cuda=12.1 cudnn=8902 driver=546.17

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by drhead** [comment]
> right now there are no plans to extend switchover support to sd15 models.

Would I be correct in assuming that a custom diffusers pipeline implementing the correct arguments needed for switchover would work properly, whether it's done as a local patch or merged upstream as part of the StableDiffusionPipeline into diffusers?

**Comment by vladmandic** [comment]
I believe so.
