### ISSUE TITLE
[Feature]: add support for ROCm 6.0

### ISSUE THREAD

**Issue by PatchouliPatch** [vladmandic/automatic#2876]
### Issue Description

Managed to solve this one on my own (yay!)

When running webui.sh as stock, it will always try to download the latest torch with no ROCm support, even when I specified --use-rocm. Fixed by manually installing the newest pytorch nightly build with ROCm 6.0 support into the venv.

### Version Platform Description

OS: Ubuntu 22.04.3
Application Version: (Unknown, cannot find anywhere. Help!)
GPU: RX 7900 XTX

16:32:17-363403 INFO     Starting SD.Next                                                                                               
16:32:17-364989 INFO     Logger: file="/home/gabriel/Documents/automatic/sdnext.log" level=INFO size=154540 mode=append                 
16:32:17-365494 INFO     Python 3.10.12 on Linux                                                                                        
16:32:17-381594 INFO     Version: app=sd.next updated=2024-02-10 hash=3c952675 url=https://github.com/vladmandic/automatic/tree/master  
16:32:17-873111 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=6.5.0-18-generic python=3.10.12                          
16:32:17-874876 INFO     AMD ROCm toolkit detected                                                                                      
16:32:18-092900 INFO     Installing package:                                                                                            
                         https://download.onnxruntime.ai/onnxruntime_training-1.17.0%2Brocm60-cp310-cp310-manylinux_2_17_x86_64.manylinu
                         x2014_x86_64.whl                                                                                               
16:32:19-582074 WARNING  Failed to automatically install onxnruntime package for ROCm. Please manually install it if you need.          
16:32:19-608192 INFO     Extensions: disabled=[]                                                                                        
16:32:19-608774 INFO     Extensions: enabled=['sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'Lora',                   
                         'sd-webui-agent-scheduler', 'sd-extension-system-info', 'stable-diffusion-webui-rembg',                        
                         'sd-extension-chainner'] extensions-builtin                                                                    
16:32:19-610102 INFO     Extensions: enabled=[] extensions                                                                              
16:32:19-610552 INFO     Startup: quick launch                                                                                          
16:32:19-610888 INFO     Verifying requirements                                                                                         
16:32:19-617377 INFO     Verifying packages                                                                                             
16:32:19-618307 INFO     Extensions: disabled=[]                                                                                        
16:32:19-618720 INFO     Extensions: enabled=['sd-webui-controlnet', 'stable-diffusion-webui-images-browser', 'Lora',                   
                         'sd-webui-agent-scheduler', 'sd-extension-system-info', 'stable-diffusion-webui-rembg',                        
                         'sd-extension-chainner'] extensions-builtin                                                                    
16:32:19-619447 INFO     Extensions: enabled=[] extensions                                                                              
16:32:19-621541 INFO     Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}                                              
16:32:19-622236 INFO     Command line args: ['--use-rocm'] use_rocm=True                                                                
16:32:22-351630 INFO     Load packages: {'torch': '2.3.0.dev20240216+rocm6.0', 'diffusers': '0.26.2', 'gradio': '3.43.2'}               
16:32:22-750820 INFO     Engine: backend=Backend.DIFFUSERS compute=rocm device=cuda attention="Sub-quadratic" mode=no_grad              
16:32:22-753958 INFO     Device: device=Radeon RX 7900 XTX n=1 hip=6.0.32830-d62f6a171                                                  
16:32:23-156474 INFO     ONNX: selected=CPUExecutionProvider, available=['AzureExecutionProvider', 'CPUExecutionProvider']              
16:32:23-201772 INFO     Available VAEs: path="models/VAE" items=0                                                                      
16:32:23-202386 INFO     Disabled extensions: ['sd-webui-controlnet']                                                                   
16:32:23-203426 INFO     Available models: path="models/Stable-diffusion" items=1 time=0.00                                             
16:32:23-522328 INFO     LoRA networks: available=0 folders=2                                                                           
16:32:23-660631 INFO     Extension: script='extensions-builtin/sd-webui-agent-scheduler/scripts/task_scheduler.py' Using sqlite file:   
                         extensions-builtin/sd-webui-agent-scheduler/task_scheduler.sqlite3                                             
16:32:23-778979 INFO     Extensions init time: 0.32 img2imgalt.py=0.06 sd-webui-agent-scheduler=0.12                                    
                         stable-diffusion-webui-images-browser=0.11                                                                     
16:32:23-790756 INFO     Load UI theme: name="black-teal" style=Auto base=sdnext.css                                                    
16:32:24-351723 INFO     Extension list is empty: refresh required                                                                      
16:32:24-493372 INFO     Local URL: http://127.0.0.1:7860/                                                                              
16:32:24-493960 INFO     Initializing middleware                                                                                        
16:32:24-763887 INFO     [AgentScheduler] Task queue is empty                                                                           
16:32:24-764510 INFO     [AgentScheduler] Registering APIs                                                                              
16:32:24-825199 INFO     Select: model="autismmixSDXL_autismmixPony [821aa5537f]"                                                       
16:32:24-826881 INFO     Torch override dtype: no-half set                                                                              
16:32:24-827335 INFO     Torch override VAE dtype: no-half set                                                                          
16:32:24-827808 INFO     Setting Torch parameters: device=cuda dtype=torch.float32 vae=torch.float32 unet=torch.float32 context=no_grad 
                         fp16=None bf16=None                                                                                            
16:32:24-828491 INFO     Autodetect: model="Stable Diffusion XL" class=StableDiffusionXLPipeline                                        
                         file="/home/gabriel/Documents/automatic/models/Stable-diffusion/autismmixSDXL_autismmixPony.safetensors"       
                         size=6617MB                                                                                                    
16:32:39-696966 INFO     Load embeddings: loaded=0 skipped=0 time=0.01                                                                  
16:32:41-178921 INFO     Load model: time=14.89 load=14.89 native=1024 {'ram': {'used': 9.35, 'total': 14.77}, 'gpu': {'used': 13.56,   
                         'total': 23.98}, 'retries': 0, 'oom': 0}                                                                       
16:32:41-181132 INFO     Startup time: 21.55 torch=2.12 gradio=0.58 libraries=0.84 extensions=0.32 face-restore=0.25 ui-en=0.08         
                         ui-settings=0.23 ui-extensions=0.18 launch=0.06 api=0.23 app-started=0.10 checkpoint=16.36                     

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
> Application Version: (Unknown, cannot find anywhere. Help!)

its near the very top of the log you've posted:
> 16:32:17-381594 INFO Version: app=sd.next updated=2024-02-10 hash=3c952675 

> When running webui.sh as stock, it will always try to download the latest torch with no ROCm support, even when I specified --use-rocm.

this is not true. but it only detects rocm 5.5/5.6/5.7 as last time this was revisited, 6.0 was not in official nightly repo.
this is actual code:

```py
        if rocm_ver in {"5.7"}:
            torch_command = os.environ.get('TORCH_COMMAND', f'torch torchvision --pre --index-url https://download.pytorch.org/whl/nightly/rocm{rocm_ver}')
        elif rocm_ver in {"5.5", "5.6"}:
            torch_command = os.environ.get('TORCH_COMMAND', f'torch torchvision --index-url https://download.pytorch.org/whl/nightly/rocm{rocm_ver}')
        else:
            # ROCm 5.5 is oldest for PyTorch 2.1
            torch_command = os.environ.get('TORCH_COMMAND', 'torch torchvision --index-url https://download.pytorch.org/whl/rocm5.5')
```

now, if you want to contribute to enhance installer to cover rocm 6.0 as well, please contribute. i don't have amd gpu for testing.

i'm converting this to feature request with help wanted.

**Comment by vladmandic** [comment]
closing as pr was merged.
