### ISSUE TITLE
[Issue]: [WinError 126] Error loading cublas64_11.dll following ZLUDA install

### ISSUE THREAD

**Issue by mgth** [vladmandic/automatic#2880]
### Issue Description

trying to follow ZLUDA wiki tuto
I got 
OSError: [WinError 126] Specified module not found. Error loading "L:\_SD\SD.Next.ZLuda\automatic\venv\lib\site-packages\torch\lib\cublas64_11.dll" or one of its dependencies.

### Version Platform Description

Windows 11 AMD 7900XTX

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
per https://github.com/vladmandic/automatic/wiki/ZLUDA#warning closing here
