### ISSUE TITLE
[Issue]: Does not work anymore since I updated to the latest release.

### ISSUE THREAD

**Issue by internetuser1234** [vladmandic/automatic#2883]
### Issue Description

    When I first started using SD.Next in December 2023, text-to-image and image-to-image features worked perfectly with my RX 6700 XT. Using the --use-directml command, I could generate images as large as 1200x1400 with various models. Even with the FreeU extension and the original backend, everything functioned smoothly.

    However, on the latest release, only text-to-image works, and even that is slower. Image-to-image no longer functions, reporting "out of memory" errors and "RuntimeError: The size of tensor a (161) must match the size of tensor b (120) at non-singleton dimension 3."

    I tried reverting to the automatic-revert-2775-patch-4 branch, verified by running the git branch -a command and checking the active branch upon startup. Unfortunately, the issue persists.

    To regain functionality, I'd like to use the older December build. 

### Version Platform Description

set PYTHON=

set GIT=

set VENV_DIR=

set COMMANDLINE_ARGS= --autolaunch

call webui --use-directml --device-id 0

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i have no idea what is `automatic-revert-2775-patch-4 branch`
and sorry to be a pain, but please fill the issue template correctly.

**Comment by internetuser1234** [comment]
The branch is not the issue anyway, it does it on the master branch too.

**Comment by vladmandic** [comment]
issue still needs to be filled correctly. "branch master" looses meaning after a while - exact version is needed and so is the rest.
and i have no idea did you upgrade, do a clean install, etc. - changelog does state default settings have changed and out-of-the-box its more towards performance and less towards low-resource systems. it can still be tuned to your desire, but out-of-the-box its different.

**Comment by internetuser1234** [comment]
2024-02-18 21:17:31.548934",
    "2.05 / 1.74 / 1.68",
    "app:SD.next updated:2024-02-18 hash:9c12b747 url:https://github.com/vladmandic/automatic/tree/master",
    "arch:AMD64 cpu:AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system:Windows release:Windows-10-10.0.22631-SP0 python:3.10.6",
    "torch:2.0.0+cpu Autocast  half xformers: diffusers:0.26.2 transformers:4.37.2",
    " 0GB",
    "original Sub-quadratic none",
    "AOM3B4_orangemixs [b8d425c720]",
    "",
    "",
    "61f5a7"



I fresh installed many of times now.  I done this by deleting the data and starting over. Doing the git clone https://github.com/vladmandic/automatic. Reinstalling to get the directml installed with the custum Webui-User.bat.

**Comment by internetuser1234** [comment]
Cross-attention: optimization=Sub-quadratic options=[]
21:20:21-614152 INFO     Load embeddings: loaded=8 skipped=0 time=0.01
21:20:21-618153 INFO     Model loaded in 6.59 create=3.99 apply=0.36 vae=0.57 move=1.59
21:20:21-829241 DEBUG    GC: collected=7638 device=privateuseone:0 {'ram': {'used': 4.02, 'total': 47.93}, 'gpu':
                         {'used': 2.09, 'total': 3.17}, 'retries': 0, 'oom': 0} time=0.21
21:20:21-831241 INFO     Model load finished: {'ram': {'used': 4.02, 'total': 47.93}, 'gpu': {'used': 2.09, 'total':
                         3.17}, 'retries': 0, 'oom': 0} cached=0
21:20:21-962294 DEBUG    Save: file="config.json" json=32 bytes=1320 time=0.001
21:20:21-964294 DEBUG    Script callback init time: image_browser.py:ui_tabs=0.30 system-info.py:app_started=0.25
                         task_scheduler.py:app_started=0.12
21:20:21-965295 INFO     Startup time: 16.45 torch=2.97 olive=0.09 gradio=0.99 libraries=1.97 extensions=1.02
                         models=0.06 face-restore=0.06 ui-en=0.17 ui-txt2img=0.06 ui-img2img=0.07 ui-settings=0.27
                         ui-extensions=0.83 ui-defaults=0.06 launch=0.11 api=0.07 app-started=0.38 checkpoint=7.12

**Comment by internetuser1234** [comment]
So far so good, I just reinstalled again, and seems to be working with image to image.

**Comment by vladmandic** [comment]
this is just random log dumps, it doesn't document the issue. nor you've done much to do so other than saying "doesn't work anymore". if issue still exists, create a new one documenting everything correctly - this issue as it is is not really actionable.
