### ISSUE TITLE
[Issue]: Can't install onnx

### ISSUE THREAD

**Issue by vgaggia** [vladmandic/automatic#2886]
### Issue Description

I'm using a fresh stock install of SD.Next (just cloned it like an hour ago), and i get an error when trying to install onnx for CUDA

### Version Platform Description

12:07:38-411369 INFO     Starting SD.Next
12:07:38-414883 INFO     Logger: file="G:\Auto\SD.Next\sdnext.log" level=INFO size=194548 mode=append
12:07:38-415890 INFO     Python 3.10.11 on Windows
12:07:38-923701 INFO     Version: app=sd.next updated=2024-02-18 hash=9c12b747
                         url=https://github.com/vladmandic/automatic/tree/master
12:07:39-102653 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
12:07:39-107172 INFO     Installing package: onnxruntime
12:07:52-034611 INFO     nVidia CUDA toolkit detected: nvidia-smi present
12:07:52-036610 INFO     Installing package: onnxruntime-gpu
12:07:57-093149 INFO     Installing package: torch torchvision --index-url https://download.pytorch.org/whl/cu121
12:09:25-725072 INFO     Extensions: disabled=['sd-webui-controlnet']
12:09:25-727070 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin

### Relevant log output

```shell
12:23:58-259469 WARNING  Uninstalling: onnxruntime
12:23:59-128237 WARNING  Uninstalling: onnxruntime-gpu
12:24:00-430146 INFO     Installing package: onnxruntime onnxruntime-gpu
12:24:02-957064 ERROR    Error running pip: install --upgrade onnxruntime onnxruntime-gpu
```

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
provide actual log - it contains more information.

**Comment by vgaggia** [comment]
Ok so upon looking it does seem to be giving an error about checking permissions? but i don't get why i'd be having any permission errors it's in a normal folder as far as i can tell:

>19:21:37-038865 WARNING  Uninstalling: onnxruntime
19:21:37-039865 DEBUG    Running pip: uninstall onnxruntime --yes --quiet
19:21:38-712115 DEBUG    Package not found: onnxruntime-directml
19:21:38-714626 WARNING  Uninstalling: onnxruntime-gpu
19:21:38-715624 DEBUG    Running pip: uninstall onnxruntime-gpu --yes --quiet
19:21:40-139435 DEBUG    Package not found: onnxruntime-training
19:21:40-140439 DEBUG    Package not found: onnxruntime-openvino
19:21:40-140942 INFO     Installing package: onnxruntime onnxruntime-gpu
19:21:40-141948 DEBUG    Running pip: install --upgrade onnxruntime onnxruntime-gpu
19:21:43-229162 ERROR    Error running pip: install --upgrade onnxruntime onnxruntime-gpu
19:21:43-231168 DEBUG    Pip output: Collecting onnxruntime
                           Using cached onnxruntime-1.17.0-cp310-cp310-win_amd64.whl (5.6 MB)
                         Requirement already satisfied: onnxruntime-gpu in g:\auto\sd.next\venv\lib\site-packages
                         (1.17.0)
                         Requirement already satisfied: packaging in g:\auto\sd.next\venv\lib\site-packages (from
                         onnxruntime) (23.2)
                         Requirement already satisfied: flatbuffers in g:\auto\sd.next\venv\lib\site-packages (from
                         onnxruntime) (23.5.26)
                         Requirement already satisfied: protobuf in g:\auto\sd.next\venv\lib\site-packages (from
                         onnxruntime) (3.20.3)
                         Requirement already satisfied: numpy>=1.21.6 in g:\auto\sd.next\venv\lib\site-packages (from
                         onnxruntime) (1.26.2)
                         Requirement already satisfied: sympy in g:\auto\sd.next\venv\lib\site-packages (from
                         onnxruntime) (1.12)
                         Requirement already satisfied: coloredlogs in g:\auto\sd.next\venv\lib\site-packages (from
                         onnxruntime) (15.0.1)
                         Requirement already satisfied: humanfriendly>=9.1 in g:\auto\sd.next\venv\lib\site-packages
                         (from coloredlogs->onnxruntime) (10.0)
                         Requirement already satisfied: mpmath>=0.19 in g:\auto\sd.next\venv\lib\site-packages (from
                         sympy->onnxruntime) (1.3.0)
                         Requirement already satisfied: pyreadline3 in g:\auto\sd.next\venv\lib\site-packages (from
                         humanfriendly>=9.1->coloredlogs->onnxruntime) (3.4.1)
                         Installing collected packages: onnxruntime
                         WARNING: Ignoring invalid distribution -nnxruntime (g:\auto\sd.next\venv\lib\site-packages)
                         WARNING: Ignoring invalid distribution - (g:\auto\sd.next\venv\lib\site-packages)
                         WARNING: Ignoring invalid distribution -nnxruntime (g:\auto\sd.next\venv\lib\site-packages)
                         WARNING: Ignoring invalid distribution - (g:\auto\sd.next\venv\lib\site-packages)
                         WARNING: Ignoring invalid distribution -nnxruntime (g:\auto\sd.next\venv\lib\site-packages)
                         WARNING: Ignoring invalid distribution - (g:\auto\sd.next\venv\lib\site-packages)
                         ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied:
                         'G:\\Auto\\SD.Next\\venv\\Lib\\site-packages\\onnxruntime\\capi\\onnxruntime_providers_shared.dll
                         Check the permissions.
                         WARNING: Ignoring invalid distribution -nnxruntime (g:\auto\sd.next\venv\lib\site-packages)
                         WARNING: Ignoring invalid distribution - (g:\auto\sd.next\venv\lib\site-packages)
                         WARNING: Ignoring invalid distribution -nnxruntime (g:\auto\sd.next\venv\lib\site-packages)
                         WARNING: Ignoring invalid distribution - (g:\auto\sd.next\venv\lib\site-packages)
                         WARNING: Ignoring invalid distribution -nnxruntime (g:\auto\sd.next\venv\lib\site-packages)
                         WARNING: Ignoring invalid distribution - (g:\auto\sd.next\venv\lib\site-packages)
                         [notice] A new release of pip is available: 23.0.1 -> 24.0
                         [notice] To update, run: G:\Auto\SD.Next\venv\Scripts\python.exe -m pip install --upgrade pip
19:21:43-237680 INFO     Please restart SD.Next.

**Comment by vladmandic** [comment]
it could be a file locking issue on windows - pip is notorious with that. 
i know it sounds silly, but try running through install several times so it can sort itself out?

**Comment by rookiemann** [comment]
Had the same problem with fresh install on a server, I switched model to sdxl base and they installed then.
