### ISSUE TITLE
[Issue]: 17:25:42-184794 WARNING  Package wrong version: timm 0.4.12 required 0.6.13

### ISSUE THREAD

**Issue by DavidSchobl** [vladmandic/automatic#289]
### Issue Description

I have received this error while starting.
`17:25:42-184794 WARNING  Package wrong version: timm 0.4.12 required 0.6.13`

### Version Platform Description

Chrome, Windows 7 NVDIDIA Geforce 1060Ti

**Comment by vladmandic** [comment]
so what is the issue? setup detected wrong version of required library and installed correct one.
unless you actually have install failed messages later in the log?

**Comment by DavidSchobl** [comment]
Good, thanks.
