### ISSUE TITLE
[Issue]: inpaint mask blur is broken

### ISSUE THREAD

**Issue by mweggen** [vladmandic/automatic#2892]
### Issue Description

Since e2e6743fbc354d53729255f7355c503e0c586bd5 , mask blur seems to be broken for the Diffusers backend.

ADetailer example with inpaint mask blur 4:
![afbeelding](https://github.com/vladmandic/automatic/assets/361046/ad0d4380-0aca-4c05-8b4f-c41021a5c8e7)

This is with the parent commit c463edb0:
![afbeelding](https://github.com/vladmandic/automatic/assets/361046/21d5f717-af19-46d4-86c3-2feb9ea27dff)

Another example with manual inpainting, again blur 4:

![afbeelding](https://github.com/vladmandic/automatic/assets/361046/fc325ffe-d87f-42f1-a72e-d79db379ea7c)

![afbeelding](https://github.com/vladmandic/automatic/assets/361046/993a5237-3d85-451c-82d6-d14047232921)

And with the previous commit:
![afbeelding](https://github.com/vladmandic/automatic/assets/361046/72acce2c-ecd4-400a-8848-9b8d5a19f7a2)

### Version Platform Description

app: SD.next
updated: 2024-02-04
hash: e2e6743f
url: https://github.com/vladmandic/automatic/tree/HEAD
arch: AMD64
cpu: AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD
system: Windows
release: Windows-10-10.0.22631-SP0
python: 3.10.11
device: NVIDIA GeForce RTX 4090 (1) (sm_90) (8, 9)
cuda: 12.1
cudnn: 8801
driver: 551.52
diffusers: 0.26.1
transformers: 4.37.2

Image settings:

Prompt: masterpiece,best quality,1girl,detailed face,shadows,8k,ultra sharp,intricate,ornaments detailed,
(poison ivy:1.2), dynamic pose, green leaves, seductive smile, plant, nature, vines, flower, 
realistic anime art style,

Negative: (low quality, worst quality), negativeXL_D

Parameters: Steps: 30| Seed: 729517515| Sampler: Default| CFG scale: 6| Size-1: 1024| Size-2: 1536| Parser: Full parser| Model: ghostxl_v10BakedVAE| Model hash: ee1fdc86f7| Backend: Diffusers| App: SD.Next| Version: x| Operations: txt2img| Pipeline: StableDiffusionXLPipeline| Embeddings: negativeXL_D

and for the manual inpaint:

Parameters: Steps: 30| Seed: 729517515| Sampler: Default| CFG scale: 6| Size-1: 1024| Size-2: 1536| Parser: Full parser| Model: ghostxl_v10BakedVAE| Model hash: ee1fdc86f7| Backend: Diffusers| App: SD.Next| Version: x| Operations: inpaint| Init image size-1: 1024| Init image size-2: 1536| Init image hash: 7fd4f468| Resize scale: 1| Denoising strength: 0.5| Mask blur: 8| Mask alpha: 1| Mask invert: 0| Mask content: 1| Mask area: 0| Mask padding: 32| Pipeline: StableDiffusionXLInpaintPipeline| Embeddings: negativeXL_D

### Relevant log output

```shell
PS E:\ai\auto2> .\webui.bat
Using VENV: E:\ai\auto2\venv
18:37:16-286329 INFO     Starting SD.Next
18:37:16-288836 INFO     Logger: file="E:\ai\auto2\sdnext.log" level=INFO size=3022164 mode=append
18:37:16-289836 INFO     Python 3.10.11 on Windows
18:37:16-402530 INFO     Version: app=sd.next updated=2024-02-04 hash=c463edb0
                         url=https://github.com/vladmandic/automatic/tree/HEAD
18:37:16-805544 INFO     Latest published version: 9c12b747a18bb0948974147d411422833e277878 2024-02-18T22:40:13Z
18:37:16-812562 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
18:37:16-817638 INFO     nVidia CUDA toolkit detected: nvidia-smi present
18:37:16-906974 INFO     Extensions: disabled=[]
18:37:16-907979 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
18:37:16-912488 INFO     Extensions: enabled=['adetailer'] extensions
```

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
can you try dev branch - there have been significant fixes/changes/improvements in this area since the last release.

**Comment by blacklig** [comment]
Speaking of diffusers backend - I noticed it is missing some options from "legacy backend". This is what diffusers backend looks like:
<img width="563" alt="image" src="https://github.com/vladmandic/automatic/assets/32385597/d9649ebe-271b-4a04-809e-c57786163fb2">

and this is what legacy backend looks like:

<img width="622" alt="image" src="https://github.com/vladmandic/automatic/assets/32385597/58191fd9-eaf2-4098-9ab4-c8c3bc09a3d0">

so it totally lacks "masked content" option in diffusers backend... how can we get it back? or is diffusers missing this params?

Thanks for any info.. for me it is quite a big deal as "masked content" fill vs original is big difference in output and this totall lacks in diffusers

**Comment by mweggen** [comment]
Looks like the mask blur issue is fixed in dev, but as the previous commenter said, some other inpaint options are missing.

**Comment by vladmandic** [comment]
closing the issue as resolved. we can have separate conversation on perceived missing features.
