### ISSUE TITLE
[Issue]: Current master - buttons are huge and pushing everything down on the page 

### ISSUE THREAD

**Issue by ilikenwf** [vladmandic/automatic#2902]
### Issue Description

The buttons, instead of being side by side, are now much wider, forcing page width to be taller, making a somewhat worse UX because you have to scroll down now - compare to the screenshot on the README.md. First one is the old UI, second is the current.

![image](https://github.com/vladmandic/automatic/assets/414778/9628d89d-6091-4ab5-b0a2-7ca862096197)

![image](https://github.com/vladmandic/automatic/assets/414778/699a868b-58c4-439e-9916-4cf06fdcffe5)

### Version Platform Description

Current master as of c5f6c25a37858daedc6c59988d2e684c4fa7ddfb with all requirements upgraded based on requirements.txt

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
what did you set your theme to? that is not default nor one of the built-in ones.
read https://github.com/vladmandic/automatic/wiki/Themes
