### ISSUE TITLE
[Feature]: Yaml folder

### ISSUE THREAD

**Issue by Zombycow** [vladmandic/automatic#2914]
### Feature description

Some checkpoints like easyfluff come with a special yaml file that lets them work, but it seems the latest version of sdnext doesn't use the yaml file when generating pictures, which causes a white grainy picture to generate. 
maybe a yaml folder for yaml handling is needed.

### Version Platform Description

SDNEXT Version: 2024-02-24 hash c1dfb1b2 
OS: Windows 10
browser: Firefox

**Comment by paypah** [comment]
https://huggingface.co/zatochu/EasyFluff/tree/main

https://civitai.com/models/3671/yiffymix

These are examples of some models I've seen that use v_prediction via their .yaml config.

I believe they just set `parameterization: "v"` like so:
![image](https://github.com/vladmandic/automatic/assets/149858185/16c2c536-ff89-4f9a-8896-3d53ada99b07)

**Comment by Disty0** [comment]
You can set v parameterization from settings too. Also SDNext will use the config from the model if you use models with Diffusers folder type. You can use Models -> Huggingface tab for Diffusers type models.

**Comment by vladmandic** [comment]
what @Disty0 is true and works, but still we should use yaml file if it exists next to model itself - i've pushed an update to dev branch, closing.
