### ISSUE TITLE
How to update the latest stable-diffusion's webui ,and install localization-zh_CN? 

### ISSUE THREAD

**Issue by etchosts** [vladmandic/automatic#2920]
### Feature description

How to update the latest stable-diffusion's webui ,and install localization-zh_CN? 

### Version Platform Description

How to update the latest stable-diffusion's webui ,and install localization-zh_CN?

**Comment by brknsoul** [comment]
SD.Next can be updated from within the System tab.

I don't believe that SD.Next has zh_CN localisation.
