### ISSUE TITLE
[Issue]:  how do i make my vladmantic work its installed i heard it works with intel

### ISSUE THREAD

**Issue by AdamM2024** [vladmandic/automatic#2924]
### Issue Description

how do i make my vladmantic work its installed i heard it works with intel im new to vlad

### Version Platform Description

microsft edeg

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
I'm sorry, but either ask question in discussions or (preffered) on discord. Don't open issues for general questions. And check wiki, it's documented there in details.
