### ISSUE TITLE
Error running git ,text2image takes a long time

### ISSUE THREAD

**Issue by etchosts** [vladmandic/automatic#2927]
### Issue Description

all error information is below：
16:25:02-860211 ERROR    Error running git: None / submodule
16:25:04-369266 ERROR    Error running git: None / submodule --quiet update --init --recursive
16:25:06-208041 ERROR    Error running git: None / submodule --quiet sync --recursive
16:25:07-850377 ERROR    Error updating submodule:
16:25:23-110842 ERROR    Error running extension installer: D:\AI\automatic\extensions-builtin\sd-face-editor\install.py
16:33:06-698129 ERROR    Extension: failed reading data from git repo=sd-extension-system-info: Reference at
                         'refs/heads/master' does not exist

It takes a long  time：
Statistics collection ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 1/1 • 0:00:21 • 0:00:00
Applying Fast Bias correction ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 98/98 • 0:01:33 • 0:00:00
Progress 37.10s/it █████████████████████████████████ 100% 20/20 12:21 00:00 Base

### Version Platform Description

the latest version

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by etchosts** [comment]
And  text cannot generate image, early stopped,
![微信截图_20240229170855](https://github.com/vladmandic/automatic/assets/154983257/1e52218c-8dd2-47fd-8599-b1935028db48)

**Comment by vladmandic** [comment]
> the latest version

this is not version nor there is any information on the platform, gpu or anything.
and you have not provided logs as required.

**Comment by etchosts** [comment]
> > the latest version
> 
> this is not version nor there is any information on the platform, gpu or anything. and you have not provided logs as required.

OS:windows 11 family chinese version
GPU:intel Arc graphics ,driver version:31.0.101.5234
sdnext.log file :
[sdnext.log](https://github.com/vladmandic/automatic/files/14456586/sdnext.log)
