### ISSUE TITLE
[Issue]: Post last update xformers stopped working. 

### ISSUE THREAD

**Issue by Deniryer** [vladmandic/automatic#2936]
### Issue Description

So i managed to make my models compatible with diffusers 0.26.x but now post last update I'm unable to use xformers on an old and a fresh installed instance. Once I switch back to SDP everything seems to be fine. 

Due to limit on github (65536 characters) I had to screenshot it. It is a long one this time. 

<img width="867" alt="1" src="https://github.com/vladmandic/automatic/assets/9111055/f6aefa4d-989b-4ad7-9209-86ce4c6dbc8a">
<img width="867" alt="2" src="https://github.com/vladmandic/automatic/assets/9111055/f98d5078-16f9-4065-b122-a25f3e5e8115">
<img width="867" alt="3" src="https://github.com/vladmandic/automatic/assets/9111055/99d0f81c-cbd4-49ca-84aa-d9f287503f3b">
<img width="867" alt="4" src="https://github.com/vladmandic/automatic/assets/9111055/92e6f366-6ac7-4d92-a751-6c1adb7d38dd">
<img width="867" alt="5" src="https://github.com/vladmandic/automatic/assets/9111055/06c2296f-e0ef-4bab-968e-53bc6cc15654">
<img width="867" alt="6" src="https://github.com/vladmandic/automatic/assets/9111055/b059c834-d826-498f-a199-4bf2f4600c7e">
<img width="867" alt="7" src="https://github.com/vladmandic/automatic/assets/9111055/b86493ae-49d7-4d12-abb5-f06a28542b59">
<img width="867" alt="8" src="https://github.com/vladmandic/automatic/assets/9111055/8f62cd85-4fd0-418f-a182-5d7072a46900">
<img width="867" alt="9" src="https://github.com/vladmandic/automatic/assets/9111055/e2c99477-5c7d-4f2b-ae09-a8abcf6d1bea">
<img width="867" alt="10" src="https://github.com/vladmandic/automatic/assets/9111055/a842bb2b-bb09-4ceb-ae2a-90d6fb631b99">
<img width="867" alt="11" src="https://github.com/vladmandic/automatic/assets/9111055/90e74f0a-7347-40de-ba14-3d3d27255a00">
<img width="867" alt="12" src="https://github.com/vladmandic/automatic/assets/9111055/249fb7d9-c2b5-43a0-b9dd-a19a5eae7890">
<img width="867" alt="13" src="https://github.com/vladmandic/automatic/assets/9111055/2625b455-76a4-488c-91be-619995947acc">
<img width="867" alt="14" src="https://github.com/vladmandic/automatic/assets/9111055/753359fd-3053-4423-842f-caad3bf2a287">
<img width="867" alt="15" src="https://github.com/vladmandic/automatic/assets/9111055/96392b26-2866-4b37-979c-545b8b7fc1ad">
<img width="867" alt="16" src="https://github.com/vladmandic/automatic/assets/9111055/c88d30e6-b79d-478e-8125-015685aee193">
<img width="867" alt="17" src="https://github.com/vladmandic/automatic/assets/9111055/a411634a-7dec-490f-a7f3-2961896fd7f2">

### Version Platform Description

Using VENV: G:\automatic\venv
23:57:56-030852 INFO     Starting SD.Next
23:57:56-033356 INFO     Logger: file="G:\automatic\sdnext.log" level=INFO size=65 mode=append
23:57:56-034356 INFO     Python 3.10.11 on Windows
23:57:56-166749 INFO     Version: app=sd.next updated=2024-03-01 hash=912237ec
                         url=https://github.com/vladmandic/automatic/tree/master
23:57:56-453905 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
23:57:56-456414 INFO     nVidia CUDA toolkit detected: nvidia-smi present
23:57:56-458415 INFO     Installing package: --pre xformers
23:58:04-845824 INFO     Startup: standard
23:58:04-846328 INFO     Verifying requirements
23:58:04-951458 INFO     Verifying packages
23:58:04-953459 INFO     Verifying submodules
23:58:27-926062 INFO     Extension installed packages: sd_dreambooth_extension ['bitsandbytes==0.41.2.post2']
23:58:27-927066 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'sd-webui-infinite-image-browsing', 'sd-webui-supermerger',
                         'sd_dreambooth_extension']
23:58:27-928066 INFO     Verifying requirements
23:58:27-945574 INFO     Command line args: []
23:58:30-970371 INFO     Load packages: {'torch': '2.2.1+cu121', 'diffusers': '0.26.3', 'gradio': '3.43.2'}
23:58:31-868812 INFO     Engine: backend=Backend.ORIGINAL compute=cuda device=cuda attention="xFormers" mode=no_grad
23:58:31-923699 INFO     Device: device=NVIDIA GeForce RTX 4090 n=1 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8801
                         driver=551.61
23:58:33-009829 ERROR    ONNX failed to initialize: Failed to import optimum.onnxruntime.modeling_diffusion because of
                         the following error (look up to see its traceback):
                         Failed to import diffusers.pipelines.stable_diffusion.pipeline_stable_diffusion because of the
                         following error (look up to see its traceback):
                         Failed to import diffusers.loaders.ip_adapter because of the following error (look up to see
                         its traceback):
                         No module named 'triton'
23:58:33-164225 INFO     Available VAEs: path="G:\AI\VAE" items=1
23:58:33-166732 INFO     Disabled extensions: []
23:58:33-233680 INFO     Available models: path="G:\AI\SD_Models" items=118 time=0.07
23:58:33-360397 ERROR    Module load: G:\automatic\scripts\demofusion.py: RuntimeError

### Relevant log output

```shell
n/a
```

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i've modified xformers installer to take care of missing packages - but this is a bug introduced by xformers, it marks triton as optional package so its not installed by default and then tries to import it as mandatory.
anyhow, updated code is in dev branch.
