### ISSUE TITLE
[Issue]: can't launch vladmandic

### ISSUE THREAD

**Issue by iamsuper123** [vladmandic/automatic#2937]
### Issue Description

'  File "C:\\TCHT\\vladmandic\\installer.py", line 975, in check_timestamp\n
                         log.debug(f\'Repository update time: {time.ctime(int(version_time))}\')\n'
this is the error i get

00:03:02-181826 INFO     Starting SD.Next
00:03:02-185820 INFO     Logger: file="C:\TCHT\vladmandic\sdnext.log" level=INFO size=494133 mode=append
00:03:02-186821 INFO     Python 3.10.7 on Windows
00:03:02-312848 INFO     Version: app=sd.next version=unknown
00:03:02-366320 ERROR    Error running git: None / rev-parse HEAD
00:03:03-728373 INFO     Latest published version: 912237ecf7d5b3616a272f983f3f59cc405f64c3 2024-03-01T14:24:24Z
00:03:03-738383 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 154 Stepping 3, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.7
00:03:03-743628 INFO     nVidia CUDA toolkit detected: nvidia-smi present
00:03:03-798101 ERROR    Error running git: None / status --porcelain
00:03:03-800421 WARNING  Deleted files: ["tal: detected dubious ownership in repository at 'C:/TCHT/vladmandic'",
                         ":/TCHT/vladmandic' is owned by:", 'UILTIN/Administrators (S-1-5-32-544)', 't the current user
                         is:', 'w/alienware (S-1-5-21-1471762504-1741428075-2742831531-1002)', 'add an exception for
                         this directory, call:', 'it config --global --add safe.directory C:/TCHT/vladmandic']
00:03:04-023494 ERROR    Error running git: None / log -1 --pretty=format:"%at"
00:03:04-025487 ERROR    Error getting local repository version: invalid literal for int() with base 10: "fatal:
                         detected dubious ownership in repository at 'C:/TCHT/vladmandic'\n'C:/TCHT/vladmandic' is owned
                         by:\n\tBUILTIN/Administrators (S-1-5-32-544)\nbut the current user is:\n\taw/alienware
                         (S-1-5-21
00:03:04-028998 ERROR    Uncaught exception occurred: type=<class 'OSError'> value=[Errno 22] Invalid argument
00:03:04-035013 ERROR    '  File "C:\\TCHT\\vladmandic\\launch.py", line 263, in <module>\n    main()\n'
00:03:04-038645 ERROR    '  File "C:\\TCHT\\vladmandic\\launch.py", line 217, in main\n    elif
                         installer.check_timestamp():\n'

i can't even describe this issue. someone help me understand this. I have no idea what's going on

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
Folder is owned by administrator and you're running as user.
Delete it and clone again using same user as user that is going to be used to run it.
And make sure that parent folder where you clone is also owned by same user.
