### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by econundrum** [vladmandic/automatic#294]
### Issue Description

Error from latest commits today. Tried to restart I use the -update switch no issue this morning. Just restarted and

Creating folder: D:\SD3\automatic\models\VAE
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\SD3\automatic\launch.py:99 in <module>                                                                            │
│                                                                                                                      │
│    98     import webui                                                                                               │
│ ❱  99     webui.webui()                                                                                              │
│   100                                                                                                                │
│                                                                                                                      │
│ D:\SD3\automatic\webui.py:204 in webui                                                                               │
│                                                                                                                      │
│   203 def webui():                                                                                                   │
│ ❱ 204     start_ui()                                                                                                 │
│   205                                                                                                                │
│                                                                                                                      │
│ D:\SD3\automatic\webui.py:156 in start_ui                                                                            │
│                                                                                                                      │
│   155     logging.disable(logging.INFO)                                                                              │
│ ❱ 156     create_paths(opts)                                                                                         │
│   157     initialize()                                                                                               │
│                                                                                                                      │
│ D:\SD3\automatic\modules\paths.py:63 in create_paths                                                                 │
│                                                                                                                      │
│   62     create_path(opts.ckpt_dir)                                                                                  │
│ ❱ 63     create_path(opts.vae_dir)                                                                                   │
│   64     create_path(opts.embeddings_dir)                                                                            │
│                                                                                                                      │
│ D:\SD3\automatic\modules\paths.py:58 in create_path                                                                  │
│                                                                                                                      │
│   57             print('Creating folder:', folder)                                                                   │
│ ❱ 58             os.makedirs(opts.temp_dir, exist_ok=True)                                                           │
│   59     create_path(opts.temp_dir)                                                                                  │
│                                                                                                                      │
│ C:\Users\wrigh\AppData\Local\Programs\Python\Python310\lib\os.py:225 in makedirs                                     │
│                                                                                                                      │
│    224     try:                                                                                                      │
│ ❱  225         mkdir(name, mode)                                                                                     │
│    226     except OSError:                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''

### Version Platform Description

Windows 11
Browser is Chrome but isn't getting that far

**Comment by vladmandic** [comment]
first, **always** set an issue title.
second, this is a duplicate and its already fixed few min ago. search for issues before posting new one.

**Comment by econundrum** [comment]
Thank you and sorry I don't know how I failed to give it a title to be honest just distracted I think. I can see it's fixed now.
