### ISSUE TITLE
[Issue]: [RESOLVED] "Press any key to continue" message with no error

### ISSUE THREAD

**Issue by nbs** [vladmandic/automatic#2943]
### Issue Description

Just wanted to document this for anyone else who runs into it.

Startup looked relatively successful (though a bit shorter than usual output) but it didn't finish booting up and didn't display the URl. The last message shown was "Press any key to continue..." and there were no errors or red lines.

After an hour of trying to get it work I realized **I had 2GB of disk space left, which the program did not mention at all. I created space and it started up successfully.**

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
"Press any key to continue" means that it crashed on OS level, so it couldn't log anything.
anytime you see that, you need to check windows event logs - and its likely you'd see actual error there.

same on linux, if you see "killed" or "segfault", need to check kernel logs why.

application cannot log if its being terminated externally.

**Comment by SAC020** [comment]
Similar issue. Windows event log below, but it's not very informative. Not sure where to dig further

```
Faulting application name: python.exe, version: 3.10.11150.1013, time stamp: 0x642cc427
Faulting module name: c10.dll, version: 0.0.0.0, time stamp: 0x65a01021
Exception code: 0xc0000005
Fault offset: 0x0000000000062cf4
Faulting process id: 0x0xBEA0
Faulting application start time: 0x0x1DA8328C79321AE
Faulting application path: C:\Users\sebas\AppData\Local\Programs\Python\Python310\python.exe
Faulting module path: C:\ai\automatic\venv\lib\site-packages\torch\lib\c10.dll
Report Id: 8b26e300-175a-4e31-abbb-1daa47d630af
Faulting package full name: 
```

```
08:07:48-678618 INFO     Python 3.10.11 on Windows
08:07:48-881933 INFO     Version: app=sd.next updated=2024-03-30 hash=98f9127b branch=dev
                         url=https://github.com/vladmandic/automatic/tree/dev
08:07:49-346684 INFO     Latest published version: 82973c49ca491b1d50418b00e37131d308fad6b6 2024-03-21T02:23:50Z
08:07:49-362555 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
```

**Comment by James-Willer** [comment]
```
 AppName python.exe 
  AppVersion 3.11.9150.1013 
  AppTimeStamp 660bda91 
  ModuleName c10.dll 
  ModuleVersion 0.0.0.0 
  ModuleTimeStamp 6655ec14 
  ExceptionCode c0000005 
  FaultingOffset 0000000000063064 
  ProcessId 0x5930 
  ProcessCreationTime 0x1dac55c30de3caf 
  AppPath C:\Users\Kai\.pyenv\pyenv-win\versions\3.11.6\python.exe 
  ModulePath C:\Users\Kai\automatic\venv\Lib\site-packages\torch\lib\c10.dll 
  IntegratorReportId 1dc96591-8fc1-4a50-8a64-04dba1496498 
  PackageFullName  
  PackageRelativeAppId  

```

I seem to be getting the same error, no idea why it happens, the logfile has nothing in it

**Comment by vladmandic** [comment]
your torch crashed. i have no idea what your environment is.
