### ISSUE TITLE
[Issue]: PROCESS to TEXT,IMAGE copy etc is not working (DEV, #76b0017)

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#2947]
### Issue Description

Copying job data to another tab is not working on DEV.

### Version Platform Description

WSL-2, win11, nvidia, latest chrome, dev branch #76b0017

### Relevant log output

```shell
no log output at all (even with DEBUG ON)
```

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
what do you mean by "copying job data"?

**Comment by vladmandic** [comment]
fixed.
