### ISSUE TITLE
[Issue]: Unable to load model

### ISSUE THREAD

**Issue by RavenMostFowl** [vladmandic/automatic#295]
### Issue Description

When attempting to start the program process crashes on module load.

Checkpoint model.ckpt not found; loading fallback 7th_anime_v2_C.ckpt
Loading weights: /home/nevermoar/automatic/models/Stable-diffusion/7th_anime_v… 
loading model: 
/home/nevermoar/automatic/models/Stable-diffusion/7th_anime_v2_C.ckpt: 
RuntimeError
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/nevermoar/automatic/modules/sd_models.py:238 in read_state_dict        │
│                                                                              │
│   237 │   │   │   │   else:                                                  │
│ ❱ 238 │   │   │   │   │   pl_sd = torch.load(checkpoint_file, map_location=' │
│   239 │   │   │   else:                                                      │
│                                                                              │
│ /home/nevermoar/automatic/venv/lib/python3.10/site-packages/torch/serializat │
│ ion.py:797 in load                                                           │
│                                                                              │
│    796 │   │   │   orig_position = opened_file.tell()                        │
│ ❱  797 │   │   │   with _open_zipfile_reader(opened_file) as opened_zipfile: │
│    798 │   │   │   │   if _is_torchscript_zip(opened_zipfile):               │
│                                                                              │
│ /home/nevermoar/automatic/venv/lib/python3.10/site-packages/torch/serializat │
│ ion.py:283 in __init__                                                       │
│                                                                              │
│    282 │   def __init__(self, name_or_buffer) -> None:                       │
│ ❱  283 │   │   super().__init__(torch._C.PyTorchFileReader(name_or_buffer))  │
│    284                                                                       │
╰──────────────────────────────────────────────────────────────────────────────╯
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding 
central directory
Failed to load checkpooint: 
/home/nevermoar/automatic/models/Stable-diffusion/7th_anime_v2_C.ckpt
No stable diffusion model loaded

### Version Platform Description

PopOS Linux

**Comment by vladmandic** [comment]
it states that `/home/nevermoar/automatic/models/Stable-diffusion/7th_anime_v2_C.ckpt` is not a valid model and its like corrupt?

**Comment by vladmandic** [comment]
what fails is simple `pl_sd = torch.load(checkpoint_file, map_location='cpu')`, that is completely outside of my control.
do you have same version of torch in a1111 repo?
can you post full console log showing startup sequence?

**Comment by vladmandic** [comment]
closing issue as no info provided, will reopen once available.
