### ISSUE TITLE
[Issue]: SAG failure with extensive errors.

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#2957]
### Issue Description

generating with wildcards, decided to turn on SAG to see if that would improve some details. stable fast was enabled (new version) as well. 
Immediate errors on generate, even after setting SAG back to 0, more errors persisted until model unload/reload. Log included. Other errors later left in in case they are relevant. log segment included here as file due to length
[mar824.SAG.plus.sdnext.log](https://github.com/vladmandic/automatic/files/14544455/mar824.SAG.plus.sdnext.log)

### Version Platform Description

Win10 LTSC
'branch': 'dev', 'current': '2024-03-08', 'chash': 'a38142e'

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i'm affraid not much i can do here, stable-fast doesn't seem to be compatible with sag.
i've added a check so it doesn't cause a crash and a note in the log:
> 08:49:08-777753 WARNING  SAG incompatible compile mode: backend=stable-fast

**Comment by Aptronymist** [comment]
> i'm affraid not much i can do here, stable-fast doesn't seem to be compatible with sag. i've added a check so it doesn't cause a crash and a note in the log:
> 
> > 08:49:08-777753 WARNING  SAG incompatible compile mode: backend=stable-fast

Then I think we both know someone that could take a peek at it at least.
