### ISSUE TITLE
[Feature]: PNG Info tab

### ISSUE THREAD

**Issue by kaelysdev** [vladmandic/automatic#296]
### Feature description

I was using the png info tab a lot to retrieve previous generation prompts, and it was very convenient to send the settings to txt2img or img2img.
![2023-04-20_18h30_03](https://user-images.githubusercontent.com/108473996/233429904-da2412dc-c7e2-4757-b0e6-a25ce769ab4a.png)

**Comment by vladmandic** [comment]
please search issues/discussions, this was commented on 10+ times.
tab is removed as all functionality has been integrated in a process tab.

**Comment by kaelysdev** [comment]
My bad, sorry, I didn't see.

Though the clip skip parameters is not mapped correctly, same from Image Browser :
![2023-04-20_18h55_21](https://user-images.githubusercontent.com/108473996/233435889-71737bad-2295-4279-a28c-809b7dcba911.png)

**Comment by vladmandic** [comment]
ok, thats a valid point. its actually mapped correctly but doesn't update ui settings for it since in a1111 that ui settings doesn't exist there. i'll add it to my backlog, no need to open separate issue.
