### ISSUE TITLE
[Issue]: Control: Hires fix runs, but the non-upscaled image is saved

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2961]
### Issue Description

Using the same set up as #2956, the hires fix runs and upscales the images (plus denoising), but the image saved is actually the non-upscaled one.

I ran a generation at 832x1216 with 2X upscale (see other issue for set up) and I should expect an image double the size saved. However, as the log says:

```
18:20:57-781821 INFO     Saving:                                                
                         image="/tmp/images/control/00003-3311082159-animagine-x
                         l-3.0-1girl original solo hand to own chest three.webp"
                         type=WEBP resolution=832x1216 size=0     
```

Notice the resolution, and in fact the image shown in Control is the non-upscaled, non-denoised one.

## Steps to reproduce

1. Set up a generation in the same manner as #2956 
2. Hit Generate

## Expected result

A properly procesed, 1664x2432 image is saved.

## Actual result

A 832x1216 image is saved, corresponding to the result prior to the hires fix. 

### Version Platform Description

17:54:33-359292 INFO     Starting SD.Next                                       
17:54:33-379195 INFO     Logger: file="/notebooks/automatic/sdnext.log"         
                         level=INFO size=12588361 mode=append                   
17:54:33-382593 INFO     Python 3.10.10 on Linux   

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
