### ISSUE TITLE
[Issue]: Control: If a model requires download, generation runs before the model is fully downloaded

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2962]
### Issue Description

When hitting Generate for the first time and a model (for example Openpose XL) is not present on the system, SD.Next proceeds to download it. However, generation starts *anyway*, and so it turns into an img2img workflow running on whatever is set as the control image. This occurs at least when no preprocessor is used.

## Steps to reproduce

1. Make sure no local ControlNet models are present
2. Set up the generation in a similar manner as #2956 
3. Hit Generate

## Expected result

Generation is paused until the model is downloaded

## Actual result

Generation starts with an img2img pipeline before the model is downloaded (see log for example)

### Relevant log output

```shell
18:14:19-110435 INFO     Base: class=StableDiffusionXLImg2ImgPipeline           
diffusion_pytorch_model.bin:   3%|▎         | 157M/5.00G [00:28<12:40, 6.37MB/s]
diffusion_pytorch_model.bin:   5%|▍         | 231M/5.00G [00:36<07:43, 10.3MB/s]  0% 0/28 00:00 ? Base
diffusion_pytorch_model.bin:   5%|▍         | 241M/5.00G [00:37<06:51, 11.6MB/s] 1/28 00:06 02:50 Base
Progress  2.82s/it ██▍                                  7% 2/28 00:06 01:13 Base
Progress  1.70s/it ███▋
```

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this is desired behavior, i don't want to block all operations while downloading a model.
