### ISSUE TITLE
[Extension]: deforum tab won't show

### ISSUE THREAD

**Issue by iamsuper123** [vladmandic/automatic#2964]
### Issue Description

when I install deforum, the tab doesn't show. I have searched online and installed/reinstalled deforum, and it still doesn't show. the extension folder is in the correct directory of vladmandic/extensions
![image](https://github.com/vladmandic/automatic/assets/160750182/0b7286df-23fd-4731-b629-08b309a60695)
![image](https://github.com/vladmandic/automatic/assets/160750182/18ee61eb-ec46-4ce7-910e-42ad0c003a27)

### Version Platform Description

running on vivaldi web browser

Using VENV: C:\TCHT\vladmandic\venv
13:03:57-080117 INFO     Starting SD.Next
13:03:57-085124 INFO     Logger: file="C:\TCHT\vladmandic\sdnext.log" level=INFO size=746592 mode=append
13:03:57-088663 INFO     Python 3.10.7 on Windows
13:03:57-186225 INFO     Version: app=sd.next version=unknown
13:03:57-232099 ERROR    Error running git: None / rev-parse HEAD
13:03:58-186822 INFO     Updating main repository
13:03:58-242414 ERROR    Error running git: None / add .
13:03:58-281361 ERROR    Error running git: None / stash
13:03:58-319828 ERROR    Error running git: None / config rebase.Autostash true
13:03:58-358519 ERROR    Error running git: . / pull --rebase --force
13:03:58-394914 ERROR    Error running git: None / log -1 --pretty=format:"%h %ad"
13:03:58-396914 INFO     Upgraded to version: fatal: detected dubious ownership in repository at 'C:/TCHT/vladmandic'
                         'C:/TCHT/vladmandic' is owned by:
                                 BUILTIN/Administrators (S-1-5-32-544)
                         but the current user is:
                                 aw/alienware (S-1-5-21-1471762504-1741428075-2742831531-1002)
                         To add an exception for this directory, call:

                                 git config --global --add safe.directory C:/TCHT/vladmandic

version information:

error logs:
13:03:59-085989 ERROR    Error running git: None / submodule
13:03:59-435668 ERROR    Error running git: None / submodule --quiet update --init --recursive
13:03:59-941772 ERROR    Error running git: None / submodule --quiet sync --recursive
13:03:59-983744 ERROR    Error running git: None / config rebase.Autostash true
13:03:59-985766 ERROR    Error updating submodule: fatal: detected dubious ownership in repository at
                         'C:/TCHT/vladmandic'
13:04:00-023444 ERROR    Error running git: None / config rebase.Autostash true
13:04:00-025465 ERROR    Error updating submodule: 'C:/TCHT/vladmandic' is owned by:
13:04:00-079351 ERROR    Error running git: None / config rebase.Autostash true
13:04:00-081336 ERROR    Error updating submodule:       BUILTIN/Administrators (S-1-5-32-544)
13:04:00-123814 ERROR    Error running git: None / config rebase.Autostash true
13:04:00-125792 ERROR    Error updating submodule: but the current user is:
13:04:00-164943 ERROR    Error running git: None / config rebase.Autostash true
13:04:00-166942 ERROR    Error updating submodule:       aw/alienware (S-1-5-21-1471762504-1741428075-2742831531-1002)
13:04:00-201995 ERROR    Error running git: None / config rebase.Autostash true
13:04:00-202994 ERROR    Error updating submodule: To add an exception for this directory, call:
13:04:00-205020 ERROR    Error updating submodule:
13:04:00-238645 ERROR    Error running git: None / config rebase.Autostash true
13:04:00-240653 ERROR    Error updating submodule:       git config --global --add safe.directory C:/TCHT/vladmandic
13:04:00-387073 ERROR    Error running git: None / config rebase.Autostash true
13:04:00-425513 ERROR    Error running git: extensions-builtin\Lora / pull origin None --rebase --force
13:04:00-584270 ERROR    Error running git: None / config rebase.Autostash true
13:04:00-622526 ERROR    Error running git: extensions-builtin\sd-extension-chainner / branch
13:04:00-712541 ERROR    Error running git: extensions-builtin\sd-extension-chainner / pull origin fatal: detected
                         dubious ownership in repository at
                         'C:/TCHT/vladmandic/extensions-builtin/sd-extension-chainner' --rebase --force
13:04:00-859904 ERROR    Error running git: None / config rebase.Autostash true
13:04:00-897590 ERROR    Error running git: extensions-builtin\sd-extension-system-info / branch
13:04:00-988236 ERROR    Error running git: extensions-builtin\sd-extension-system-info / pull origin fatal: detected
                         dubious ownership in repository at
                         'C:/TCHT/vladmandic/extensions-builtin/sd-extension-system-info' --rebase --force
13:04:01-520795 ERROR    Error running git: None / config rebase.Autostash true
13:04:01-595589 ERROR    Error running git: extensions-builtin\sd-webui-agent-scheduler / branch
13:04:01-675629 ERROR    Error running git: extensions-builtin\sd-webui-agent-scheduler / pull origin fatal: detected
                         dubious ownership in repository at
                         'C:/TCHT/vladmandic/extensions-builtin/sd-webui-agent-scheduler' --rebase --force
13:04:02-175832 ERROR    Error running git: None / config rebase.Autostash true
13:04:02-219733 ERROR    Error running git: extensions-builtin\stable-diffusion-webui-images-browser / pull origin None
                         --rebase --force
13:04:02-431224 ERROR    Error running git: None / config rebase.Autostash true
13:04:02-485975 ERROR    Error running git: extensions-builtin\stable-diffusion-webui-rembg / branch
13:04:02-572547 ERROR    Error running git: extensions-builtin\stable-diffusion-webui-rembg / pull origin fatal:
                         detected dubious ownership in repository at
                         'C:/TCHT/vladmandic/extensions-builtin/stable-diffusion-webui-rembg' --rebase --force
13:04:03-014739 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg']
13:04:03-016729 INFO     Verifying requirements
13:04:03-025667 INFO     Updating Wiki
13:04:03-064980 ERROR    Error running git: None / config rebase.Autostash true
13:04:03-145733 ERROR    Error running git: C:\TCHT\vladmandic\wiki / branch
13:04:03-245500 ERROR    Error running git: C:\TCHT\vladmandic\wiki / pull origin fatal: detected dubious ownership in
                         repository at 'C:/TCHT/vladmandic/wiki' --rebase --force
13:04:03-247600 WARNING  Setup complete with errors: 36
13:04:03-249296 WARNING  See log file for more details: C:\TCHT\vladmandic\sdnext.log
13:04:03-257409 INFO     Command line args: ['--upgrade', '--models-dir',
                         'C:/Users/alienware/stable-diffusion-webui/models']
                         models_dir=C:/Users/alienware/stable-diffusion-webui/models upgrade=True
13:04:20-001597 INFO     Load packages: {'torch': '2.2.1+cu121', 'diffusers': '0.26.3', 'gradio': '3.43.2'}
13:04:21-994808 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
13:04:22-069526 INFO     Device: device=NVIDIA GeForce RTX 3050 Laptop GPU n=1 arch=sm_90 cap=(8, 6) cuda=12.1
                         cudnn=8801 driver=532.09
13:04:22-220571 ERROR    ONNX failed to initialize: No module named 'onnx'
13:04:22-995198 INFO     Using models path: C:/Users/alienware/stable-diffusion-webui/models
13:04:24-696288 INFO     Available VAEs: path="C:/Users/alienware/stable-diffusion-webui/models\VAE" items=0
13:04:24-698268 INFO     Disabled extensions: []
13:04:24-714356 INFO     Available models: path="C:/Users/alienware/stable-diffusion-webui/models\Stable-diffusion"
                         items=3 time=0.01
13:04:25-870957 INFO     Extension: script='extensions-builtin\Lora\scripts\lora_script.py'
                         [2;36m13:04:25-866369[0m[2;36m [0m[34mINFO    [0m LoRA networks: [33mavailable[0m=[1;36m16[0m
                         [33mfolders[0m=[1;36m2[0m
13:04:26-362583 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
13:04:26-448232 INFO     UI theme: name="black-teal" style=Auto base=sdnext.css
13:04:28-426875 ERROR    Extension: failed reading data from git repo=sd-extension-chainner: Cmd('git') failed due to:
                         exit code(128)
                           cmdline: git remote get-url --all origin
                           stderr: 'fatal: detected dubious ownership in repository at
                         'C:/TCHT/vladmandic/extensions-builtin/sd-extension-chainner'
                         'C:/TCHT/vladmandic/extensions-builtin/sd-extension-chainner' is owned by:
                                 BUILTIN/Administrators (S-1-5-32-544)
                         but the current user is:
                                 aw/alienware (S-1-5-21-1471762504-1741428075-2742831531-1002)
                         To add an exception for this directory, call:

                                 git config --global --add safe.directory
                         C:/TCHT/vladmandic/extensions-builtin/sd-extension-chainner'
13:04:28-493198 ERROR    Extension: failed reading data from git repo=sd-extension-system-info: Cmd('git') failed due
                         to: exit code(128)
                           cmdline: git remote get-url --all origin
                           stderr: 'fatal: detected dubious ownership in repository at
                         'C:/TCHT/vladmandic/extensions-builtin/sd-extension-system-info'
                         'C:/TCHT/vladmandic/extensions-builtin/sd-extension-system-info' is owned by:
                                 BUILTIN/Administrators (S-1-5-32-544)
                         but the current user is:
                                 aw/alienware (S-1-5-21-1471762504-1741428075-2742831531-1002)
                         To add an exception for this directory, call:

                                 git config --global --add safe.directory
                         C:/TCHT/vladmandic/extensions-builtin/sd-extension-system-info'
13:04:28-569299 ERROR    Extension: failed reading data from git repo=sd-webui-agent-scheduler: Cmd('git') failed due
                         to: exit code(128)
                           cmdline: git remote get-url --all origin
                           stderr: 'fatal: detected dubious ownership in repository at
                         'C:/TCHT/vladmandic/extensions-builtin/sd-webui-agent-scheduler'
                         'C:/TCHT/vladmandic/extensions-builtin/sd-webui-agent-scheduler' is owned by:
                                 BUILTIN/Administrators (S-1-5-32-544)
                         but the current user is:
                                 aw/alienware (S-1-5-21-1471762504-1741428075-2742831531-1002)
                         To add an exception for this directory, call:

                                 git config --global --add safe.directory
                         C:/TCHT/vladmandic/extensions-builtin/sd-webui-agent-scheduler'
13:04:28-636474 ERROR    Extension: failed reading data from git repo=stable-diffusion-webui-rembg: Cmd('git') failed
                         due to: exit code(128)
                           cmdline: git remote get-url --all origin
                           stderr: 'fatal: detected dubious ownership in repository at
                         'C:/TCHT/vladmandic/extensions-builtin/stable-diffusion-webui-rembg'
                         'C:/TCHT/vladmandic/extensions-builtin/stable-diffusion-webui-rembg' is owned by:
                                 BUILTIN/Administrators (S-1-5-32-544)
                         but the current user is:
                                 aw/alienware (S-1-5-21-1471762504-1741428075-2742831531-1002)
                         To add an exception for this directory, call:

                                 git config --global --add safe.directory
                         C:/TCHT/vladmandic/extensions-builtin/stable-diffusion-webui-rembg'
13:04:29-054738 INFO     Local URL: http://127.0.0.1:7860/
13:04:29-213946 INFO     [AgentScheduler] Task queue is empty
13:04:29-214947 INFO     [AgentScheduler] Registering APIs
13:04:29-308725 INFO     Select: model="majicmixRealistic_v6 [e4a30e4607]"
13:04:29-390589 INFO     Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float16 unet=torch.float16
                         context=no_grad fp16=True bf16=None optimization=Scaled-Dot-Product
13:04:29-395496 INFO     Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline
                         file="C:\Users\alienware\stable-diffusion-webui\models\Stable-diffusion\majicmixRealistic_v6.sa
                         fetensors" size=2289MB
13:04:40-654899 INFO     MOTD: N/A
13:04:43-349289 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
13:04:43-728012 INFO     Load embeddings: loaded=0 skipped=0 time=0.02
13:04:44-312022 INFO     Load model: time=14.42 load=14.42 native=512 {'ram': {'used': 2.47, 'total': 15.68}, 'gpu':
                         {'used': 2.83, 'total': 4.0}, 'retries': 0, 'oom': 0}
13:04:44-321533 INFO     Startup time: 41.06 torch=13.68 onnx=0.06 olive=0.16 gradio=2.85 libraries=2.95 samplers=1.70
                         extensions=0.75 face-restore=0.93 ui-en=0.32 ui-img2img=0.19 ui-control=0.07 ui-extras=0.86
                         ui-settings=0.34 ui-extensions=0.36 launch=0.34 api=0.09 app-started=0.15 checkpoint=15.01
13:05:56-836401 INFO     Extension install: https://github.com/Mikubill/sd-webui-controlnet
13:05:56-840408 INFO     Installing extension: https://github.com/Mikubill/sd-webui-controlnet into
                         extensions\sd-webui-controlnet
13:07:10-899593 INFO     Disabled extensions: ['sd-webui-controlnet']
13:07:38-457110 INFO     Extension install: https://github.com/deforum-art/deforum-for-automatic1111-webui
13:07:38-459625 INFO     Installing extension: https://github.com/deforum-art/deforum-for-automatic1111-webui into
                         extensions\deforum-for-automatic1111-webui
13:07:45-648545 INFO     Disabled extensions: ['sd-webui-controlnet']
13:09:14-595775 WARNING  Server shutdown requested
13:09:14-940459 INFO     Server restarting...
13:09:15-746261 INFO     Server will restart
13:09:18-221170 INFO     Command line args: ['--upgrade', '--models-dir',
                         'C:/Users/alienware/stable-diffusion-webui/models', '--models-dir',
                         'C:/Users/alienware/stable-diffusion-webui/models']
                         models_dir=C:/Users/alienware/stable-diffusion-webui/models upgrade=True
13:09:18-231692 INFO     Using models path: C:/Users/alienware/stable-diffusion-webui/models
13:09:18-247718 INFO     Available VAEs: path="C:/Users/alienware/stable-diffusion-webui/models\VAE" items=0
13:09:18-252718 INFO     Disabled extensions: ['sd-webui-controlnet']
13:09:18-269912 INFO     Available models: path="C:/Users/alienware/stable-diffusion-webui/models\Stable-diffusion"
                         items=3 time=0.01
13:09:19-472059 INFO     UI theme: name="black-teal" style=Auto base=sdnext.css
13:09:21-841790 ERROR    Executing callback:
                         C:\TCHT\vladmandic\extensions\deforum-for-automatic1111-webui\scripts\deforum.py
                         ui_tabs_callback: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\TCHT\vladmandic\modules\script_callbacks.py:208 in ui_tabs_callback                                               │
│                                                                                                                      │
│   207 │   │   │   t0 = time.time()                                                                                   │
│ ❱ 208 │   │   │   res += c.callback() or []                                                                          │
│   209 │   │   │   timer(t0, c.script, 'ui_tabs')                                                                     │
│                                                                                                                      │
│ C:\TCHT\vladmandic\extensions\deforum-for-automatic1111-webui\scripts\deforum_helpers\ui_right.py:101 in on_ui_tabs  │
│                                                                                                                      │
│   100 │   │   │   │                                                                                                  │
│ ❱ 101 │   │   │   │   deforum_gallery = output_panel.gallery                                                         │
│   102 │   │   │   │   generation_info = output_panel.generation_info                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'tuple' object has no attribute 'gallery'
13:09:22-146702 ERROR    Extension: failed reading data from git repo=sd-extension-chainner: Cmd('git') failed due to:
                         exit code(128)
                           cmdline: git remote get-url --all origin
                           stderr: 'fatal: detected dubious ownership in repository at
                         'C:/TCHT/vladmandic/extensions-builtin/sd-extension-chainner'
                         'C:/TCHT/vladmandic/extensions-builtin/sd-extension-chainner' is owned by:
                                 BUILTIN/Administrators (S-1-5-32-544)
                         but the current user is:
                                 aw/alienware (S-1-5-21-1471762504-1741428075-2742831531-1002)
                         To add an exception for this directory, call:

                                 git config --global --add safe.directory
                         C:/TCHT/vladmandic/extensions-builtin/sd-extension-chainner'
13:09:22-266199 ERROR    Extension: failed reading data from git repo=sd-extension-system-info: Cmd('git') failed due
                         to: exit code(128)
                           cmdline: git remote get-url --all origin
                           stderr: 'fatal: detected dubious ownership in repository at
                         'C:/TCHT/vladmandic/extensions-builtin/sd-extension-system-info'
                         'C:/TCHT/vladmandic/extensions-builtin/sd-extension-system-info' is owned by:
                                 BUILTIN/Administrators (S-1-5-32-544)
                         but the current user is:
                                 aw/alienware (S-1-5-21-1471762504-1741428075-2742831531-1002)
                         To add an exception for this directory, call:

                                 git config --global --add safe.directory
                         C:/TCHT/vladmandic/extensions-builtin/sd-extension-system-info'
13:09:22-343154 ERROR    Extension: failed reading data from git repo=sd-webui-agent-scheduler: Cmd('git') failed due
                         to: exit code(128)
                           cmdline: git remote get-url --all origin
                           stderr: 'fatal: detected dubious ownership in repository at
                         'C:/TCHT/vladmandic/extensions-builtin/sd-webui-agent-scheduler'
                         'C:/TCHT/vladmandic/extensions-builtin/sd-webui-agent-scheduler' is owned by:
                                 BUILTIN/Administrators (S-1-5-32-544)
                         but the current user is:
                                 aw/alienware (S-1-5-21-1471762504-1741428075-2742831531-1002)
                         To add an exception for this directory, call:

                                 git config --global --add safe.directory
                         C:/TCHT/vladmandic/extensions-builtin/sd-webui-agent-scheduler'
13:09:22-456199 ERROR    Extension: failed reading data from git repo=stable-diffusion-webui-rembg: Cmd('git') failed
                         due to: exit code(128)
                           cmdline: git remote get-url --all origin
                           stderr: 'fatal: detected dubious ownership in repository at
                         'C:/TCHT/vladmandic/extensions-builtin/stable-diffusion-webui-rembg'
                         'C:/TCHT/vladmandic/extensions-builtin/stable-diffusion-webui-rembg' is owned by:
                                 BUILTIN/Administrators (S-1-5-32-544)
                         but the current user is:
                                 aw/alienware (S-1-5-21-1471762504-1741428075-2742831531-1002)
                         To add an exception for this directory, call:

                                 git config --global --add safe.directory
                         C:/TCHT/vladmandic/extensions-builtin/stable-diffusion-webui-rembg'
13:09:24-001479 INFO     Local URL: http://127.0.0.1:7860/
13:09:24-211145 INFO     [AgentScheduler] Task queue is empty
13:09:24-214136 INFO     [AgentScheduler] Registering APIs
13:09:24-529075 INFO     Startup time: 280.20 ldm=273.91 extensions=1.10 networks=0.07 ui-en=0.56 ui-txt2img=0.16
                         ui-img2img=0.19 ui-control=0.29 ui-extras=0.10 ui-train=0.09 ui-models=0.11 ui-interrogate=0.07
                         ui-settings=0.56 ui-extensions=1.36 ui-defaults=0.20 launch=0.84 app-started=0.46
13:09:27-913337 INFO     MOTD: N/A
13:09:36-052469 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

### URL link of the extension

https://github.com/deforum-art/sd-webui-deforum

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
its a pretty big mess with folder ownership.
always create a folder, run clone and run webui.bat as the same user. do not use admin or switch users.

**Comment by iamsuper123** [comment]
> its a pretty big mess with folder ownership. always create a folder, run clone and run webui.bat as the same user. do not use admin or switch users.

I don't know how to change the ownership. also my pc only has one user so I don't think that's the problem.

got any ideas

**Comment by vladmandic** [comment]
folder is owned by administrator and you're running as user.

**Comment by iamsuper123** [comment]
> folder is owned by administrator and you're running as user.

I am the administrator. there is only one user on my lock screen but it's saying dubious ownership found which is weird. what might be causing this?

**Comment by iamsuper123** [comment]
> ```
> 'C:/TCHT/vladmandic' is owned by:
> BUILTIN/Administrators (S-1-5-32-544)
> but the current user is:
> aw/alienware (S-1-5-21-1471762504-1741428075-2742831531-1002)
> ```
> 
> > I am the administrator. there is only one user on my lock screen but it's saying dubious ownership found which is weird. what might be causing this?
> 
> there is a difference between adm and user (with adm privileges) accounts, even though you just see one acc on your lock screen, there are a few more hidden behind that, for OS to run you probably created that folder with adm command prompt or on your desktop and moved to driver root, etc just start over, create new folder, clone repo and run app as vlad said on his first reply

ok tysm that explains it. I fixed the issue last night, not with that, but by giving the current user i'm on "ownership" of all the files. I ran the command 

takeown /F <TCH DIRECTORY> /R

and all of the "dubious ownership" issues were fixed and the deforum tab was shown

HOWEVER, it still says "controlnet not found, please install it" when I have it installed. The extension seems to constantly disable itself after every reboot. any ideas what could be causing this? I'm using sd-webui-controlnet (previously it was a built in extension, but I reinstalled it and still nope)

**Comment by vladmandic** [comment]
that is covered in details in many conversations and notes and wiki pages. short version: sdnext has its own control module nowadays and controlnet extension can only be used in legacy backend=original.

**Comment by iamsuper123** [comment]
> that is covered in details in many conversations and notes and wiki pages. short version: sdnext has its own control module nowadays and controlnet extension can only be used in legacy backend=original.

are you 100% sure? does that mean controlnet for deforum only works for sd-webui automatic1111 and NO other modified versions, such as forge, basujingdal, sd.next?

also, could you link some of the "wiki pages" you said to have covered this please, thanks

**Comment by vladmandic** [comment]
depends on level of modifications. sdnext wiyh backend diffusers has almost nothing in common with a1111.
