### ISSUE TITLE
[Issue]: webui.bat with windows dont work

### ISSUE THREAD

**Issue by kalle07** [vladmandic/automatic#2965]
### Issue Description

after clone 
cmd as admin
go into folder
webui.bat
returns no error and do notihng

if i manual create venv
and activate and type
python launch.py

the installation starts and wooow until the end and it worked

### Version Platform Description

win10

### Backend

Original

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by kalle07** [comment]
in addition ...
if i install it in that way CUDA dont work (RTX nvidia)
i have installed automat1111 and foooocus, there it worked perfect without any special things

**Comment by vladmandic** [comment]
first, do not cmd as admin. you're just creating problems.
clone as USER and run webui.bat as the same user.

second, sdnext supports much more types of gpus that a1111 and fooocus and it tries to detect the gpu.
(a1111 does not, it just assumes cuda and anything else is up to user to do manually)

and if your nvidia tools are not in path or not working correctly, detection will fail.
you always have option to force installation of whichever engine you want, for example `webui.bat --use-cuda` - this is all documented.

**Comment by kalle07** [comment]
if a start 
python launch.py --use-cuda

it install some more libs but
it ends up with an error

....
e:\automatic>python launch.py --use-cuda
09:00:18-457998 INFO     Starting SD.Next
09:00:18-473619 INFO     Logger: file="e:\automatic\sdnext.log" level=INFO size=133178 mode=append
09:00:18-473619 INFO     Python 3.10.5 on Windows
09:00:18-812274 INFO     Version: app=sd.next updated=2024-03-07 hash=bc4b633e
                         url=https://github.com/vladmandic/automatic/tree/master
09:00:19-429122 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.5
09:00:19-429122 INFO     nVidia CUDA toolkit detected: nvidia-smi present
09:00:19-660864 INFO     Extensions: disabled=[]
09:00:19-660864 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
09:00:19-676482 INFO     Extensions: enabled=['adetailer', 'sd-webui-aspect-ratio-helper'] extensions
09:00:19-676482 INFO     Startup: quick launch
09:00:19-692076 INFO     Verifying requirements
09:00:19-692076 INFO     Installing package: patch-ng
09:00:35-382566 INFO     Installing package: addict
09:00:39-844265 INFO     Installing package: astunparse
09:00:44-891399 INFO     Installing package: blendmodes
09:00:58-280353 INFO     Installing package: clean-fid
09:01:02-830518 INFO     Installing package: filetype
09:01:07-357341 INFO     Installing package: inflection
09:01:11-363480 INFO     Installing package: jsonmerge
09:01:15-894604 INFO     Installing package: kornia
09:01:22-426011 INFO     Installing package: lark
09:01:27-032725 INFO     Installing package: lpips
09:01:31-573948 INFO     Installing package: open-clip-torch
09:01:39-833961 INFO     Installing package: optimum
09:01:50-048782 INFO     Installing package: piexif
09:01:54-734509 INFO     Installing package: resize-right
09:01:59-345163 INFO     Installing package: tensordict==0.1.2
09:02:04-615684 INFO     Installing package: torchdiffeq
09:02:09-343436 INFO     Installing package: voluptuous
09:02:14-036823 INFO     Installing package: yapf
09:02:19-885830 INFO     Installing package: scikit-image
09:02:32-146633 INFO     Installing package: fasteners
09:02:36-912558 INFO     Installing package: dctorch
09:02:41-656685 INFO     Installing package: pymatting
09:02:54-817417 WARNING  Package version mismatch: httpx 0.25.1 required 0.24.1
09:02:54-819433 INFO     Installing package: httpx==0.24.1
09:03:00-358434 INFO     Installing package: compel==2.0.2
09:03:08-869833 INFO     Installing package: torchsde==0.2.6
09:03:14-652991 INFO     Installing package: clip-interrogator==0.6.0
09:03:19-706346 WARNING  Package version mismatch: antlr4-python3-runtime 4.8 required 4.9.3
09:03:19-706346 INFO     Installing package: antlr4-python3-runtime==4.9.3
09:03:26-476540 WARNING  Package version mismatch: accelerate 0.24.1 required 0.27.2
09:03:26-492162 INFO     Installing package: accelerate==0.27.2
09:03:31-772712 INFO     Installing package: opencv-contrib-python-headless==4.9.0.80
09:03:43-944586 WARNING  Package version mismatch: einops 0.7.0 required 0.4.1
09:03:43-952599 INFO     Installing package: einops==0.4.1
09:03:48-874643 WARNING  Package version mismatch: gradio 4.11.0 required 3.43.2
09:03:48-874643 INFO     Installing package: gradio==3.43.2
09:03:59-493039 WARNING  Package version mismatch: huggingface_hub 0.21.4 required 0.20.3
09:03:59-493039 INFO     Installing package: huggingface_hub==0.20.3
09:04:04-376791 INFO     Installing package: numexpr==2.8.8
09:04:09-281506 WARNING  Package version mismatch: numpy 1.23.5 required 1.26.4
09:04:09-281506 INFO     Installing package: numpy==1.26.4
09:04:19-541332 WARNING  Package version mismatch: numba 0.56.4 required 0.59.0
09:04:19-541332 INFO     Installing package: numba==0.59.0
09:04:34-010629 INFO     Installing package: pytorch_lightning==1.9.4
09:04:42-939076 WARNING  Package version mismatch: tokenizers 0.15.0 required 0.15.2
09:04:42-939076 INFO     Installing package: tokenizers==0.15.2
09:04:48-567550 WARNING  Package version mismatch: transformers 4.35.2 required 4.38.1
09:04:48-567550 INFO     Installing package: transformers==4.38.1
09:05:05-533336 INFO     Installing package: tomesd==0.1.3
09:05:10-548578 WARNING  Package version mismatch: urllib3 2.1.0 required 1.26.18
09:05:10-548578 INFO     Installing package: urllib3==1.26.18
09:05:15-279358 WARNING  Package version mismatch: timm 0.9.16 required 0.9.12
09:05:15-294980 INFO     Installing package: timm==0.9.12
09:05:21-822443 WARNING  Package version mismatch: pydantic 2.5.1 required 1.10.13
09:05:21-822443 INFO     Installing package: pydantic==1.10.13
09:05:27-511382 WARNING  Package version mismatch: typing-extensions 4.8.0 required 4.9.0
09:05:27-511382 INFO     Installing package: typing-extensions==4.9.0
09:05:33-075108 INFO     Verifying packages
09:05:33-075108 INFO     Installing package: git+https://github.com/openai/CLIP.git
09:05:41-219412 INFO     Installing package:
                         git+https://github.com/patrickvonplaten/invisible-watermark.git@remove_onnxruntime_depedency
09:05:51-106031 INFO     Installing package: pi-heif
09:05:56-421064 INFO     Installing package: tensorflow==2.13.0
09:07:24-728987 INFO     Extensions: disabled=[]
09:07:24-728987 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
09:07:24-736999 INFO     Extensions: enabled=['adetailer', 'sd-webui-aspect-ratio-helper'] extensions
09:07:24-747034 INFO     Command line args: ['--use-cuda'] use_cuda=True
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ e:\automatic\launch.py:263 in <module>                                                                              │
│                                                                                                                     │
│   262 if __name__ == "__main__":                                                                                    │
│ > 263     main()                                                                                                    │
│   264                                                                                                               │
│                                                                                                                     │
│ e:\automatic\launch.py:240 in main                                                                                  │
│                                                                                                                     │
│   239                                                                                                               │
│ > 240     uv, instance = start_server(immediate=True, server=None)                                                  │
│   241     while True:                                                                                               │
│                                                                                                                     │
│ e:\automatic\launch.py:168 in start_server                                                                          │
│                                                                                                                     │
│   167     get_custom_args()                                                                                         │
│ > 168     module_spec.loader.exec_module(server)                                                                    │
│   169     uvicorn = None                                                                                            │
│ in exec_module:883                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ e:\automatic\webui.py:11 in <module>                                                                                │
│                                                                                                                     │
│    10 from threading import Thread                                                                                  │
│ >  11 import modules.loader                                                                                         │
│    12 import torch # pylint: disable=wrong-import-order                                                             │
│                                                                                                                     │
│ E:\automatic\modules\loader.py:48 in <module>                                                                       │
│                                                                                                                     │
│   47                                                                                                                │
│ > 48 from fastapi import FastAPI # pylint: disable=W0611,C0411                                                      │
│   49 import gradio # pylint: disable=W0611,C0411                                                                    │
│                                                                                                                     │
│ C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\fastapi\__init__.py:7 in <module>              │
│                                                                                                                     │
│    6                                                                                                                │
│ >  7 from .applications import FastAPI as FastAPI                                                                   │
│    8 from .background import BackgroundTasks as BackgroundTasks                                                     │
│                                                                                                                     │
│ C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\fastapi\applications.py:16 in <module>         │
│                                                                                                                     │
│     15                                                                                                              │
│ >   16 from fastapi import routing                                                                                  │
│     17 from fastapi.datastructures import Default, DefaultPlaceholder                                               │
│                                                                                                                     │
│ C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\fastapi\routing.py:22 in <module>              │
│                                                                                                                     │
│     21                                                                                                              │
│ >   22 from fastapi import params                                                                                   │
│     23 from fastapi._compat import (                                                                                │
│                                                                                                                     │
│ C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\fastapi\params.py:5 in <module>                │
│                                                                                                                     │
│     4                                                                                                               │
│ >   5 from fastapi.openapi.models import Example                                                                    │
│     6 from pydantic.fields import FieldInfo                                                                         │
│                                                                                                                     │
│ C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\fastapi\openapi\models.py:4 in <module>        │
│                                                                                                                     │
│     3                                                                                                               │
│ >   4 from fastapi._compat import (                                                                                 │
│     5     PYDANTIC_V2,                                                                                              │
│                                                                                                                     │
│ C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\fastapi\_compat.py:20 in <module>              │
│                                                                                                                     │
│    19                                                                                                               │
│ >  20 from fastapi.exceptions import RequestErrorModel                                                              │
│    21 from fastapi.types import IncEx, ModelNameMap, UnionType                                                      │
│                                                                                                                     │
│ C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\fastapi\exceptions.py:6 in <module>            │
│                                                                                                                     │
│     5 from starlette.exceptions import WebSocketException as StarletteWebSocketException                            │
│ >   6 from typing_extensions import Annotated, Doc  # type: ignore [attr-defined]                                   │
│     7                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ImportError: cannot import name 'Doc' from 'typing_extensions' (C:\Users\kallemst\.pyenv\pyenv-win\versions\3.10.5\lib\site-packages\typing_extensions.py)


sorry, maybe in 3months i try it once more
had never problems with the GUi´s i mentioned    ;)

**Comment by kalle07** [comment]
ok sry not installed in venv

.....


(venv) e:\automatic>python launch.py --use-cuda
10:05:50-378351 INFO     Starting SD.Next
10:05:50-378351 INFO     Logger: file="e:\automatic\sdnext.log" level=INFO size=149983 mode=append
10:05:50-378351 INFO     Python 3.10.5 on Windows
10:05:50-679200 INFO     Version: app=sd.next updated=2024-03-07 hash=bc4b633e url=https://github.com/vladmandic/automatic/tree/master
10:05:51-211291 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows release=Windows-10-10.0.19045-SP0 python=3.10.5
10:05:51-211291 INFO     nVidia CUDA toolkit detected: nvidia-smi present
10:05:51-396217 INFO     Extensions: disabled=[]
10:05:51-396217 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg'] extensions-builtin
10:05:51-396217 INFO     Extensions: enabled=['adetailer', 'sd-webui-aspect-ratio-helper'] extensions
10:05:51-396217 INFO     Startup: quick launch
10:05:51-396217 INFO     Verifying requirements
10:05:51-411843 INFO     Verifying packages
10:05:51-411843 INFO     Extensions: disabled=[]
10:05:51-427458 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-webui-controlnet',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg'] extensions-builtin
10:05:51-427458 INFO     Extensions: enabled=['adetailer', 'sd-webui-aspect-ratio-helper'] extensions
10:05:51-427458 INFO     Command line args: ['--use-cuda'] use_cuda=True
10:06:00-683059 INFO     Load packages: {'torch': '2.1.1+cpu', 'diffusers': '0.26.3', 'gradio': '3.43.2'}
10:06:02-449495 INFO     Engine: backend=Backend.DIFFUSERS compute=cpu device=cpu attention="Scaled-Dot-Product" mode=no_grad
10:06:02-465117 INFO     Device:
10:06:05-240668 INFO     Available VAEs: path="models\VAE" items=1
10:06:05-240668 INFO     Disabled extensions: ['sd-webui-controlnet']
10:06:05-256289 INFO     Available models: path="models\Stable-diffusion" items=4 time=0.02
10:06:05-557032 INFO     Extension: script='extensions-builtin\Lora\scripts\lora_script.py' 10:06:05-557032 INFO     LoRA networks:
                         available=0 folders=2
10:06:06-243140 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using sqlite file:
                         extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
10:06:07-476321 INFO     Extension: script='extensions\adetailer\scripts\!adetailer.py' [-] ADetailer initialized. version: 24.3.0, num models: 10
10:06:07-598213 INFO     UI theme: name="black-teal" style=Auto base=sdnext.css
10:06:10-422340 ERROR    Extension: failed reading data from git repo=adetailer: Cmd('git') failed due to: exit code(128)
                           cmdline: git remote get-url --all origin
                           stderr: 'fatal: detected dubious ownership in repository at 'E:/automatic/extensions/adetailer'
                         'E:/automatic/extensions/adetailer' is owned by:
                                 'S-1-5-32-544'
                         but the current user is:
                                 'S-1-5-21-3859174244-1993617766-2322335723-1001'
                         To add an exception for this directory, call:

                                 git config --global --add safe.directory E:/automatic/extensions/adetailer'
10:06:10-491359 ERROR    Extension: failed reading data from git repo=sd-webui-aspect-ratio-helper: Cmd('git') failed due to: exit code(128)
                           cmdline: git remote get-url --all origin
                           stderr: 'fatal: detected dubious ownership in repository at 'E:/automatic/extensions/sd-webui-aspect-ratio-helper'
                         'E:/automatic/extensions/sd-webui-aspect-ratio-helper' is owned by:
                                 'S-1-5-32-544'
                         but the current user is:
                                 'S-1-5-21-3859174244-1993617766-2322335723-1001'
                         To add an exception for this directory, call:

                                 git config --global --add safe.directory E:/automatic/extensions/sd-webui-aspect-ratio-helper'
10:06:10-838973 INFO     Local URL: http://127.0.0.1:7861/
10:06:11-196673 INFO     [AgentScheduler] Task queue is empty
10:06:11-196673 INFO     [AgentScheduler] Registering APIs
10:06:11-361187 INFO     Model metadata saved: file="metadata.json" items=4 time=0.02
10:06:11-361187 INFO     Select: model="SDXL_juggernautXL_v9Rundiffusionphoto2 [c9e3e68f89]"
10:06:11-361187 INFO     Torch override dtype: no-half set
10:06:11-361187 INFO     Torch override VAE dtype: no-half set
10:06:11-369215 INFO     Setting Torch parameters: device=cpu dtype=torch.float32 vae=torch.float32 unet=torch.float32 context=no_grad fp16=None bf16=None
                         optimization=Scaled-Dot-Product
10:06:11-369215 INFO     Autodetect: model="Stable Diffusion XL" class=StableDiffusionXLPipeline
                         file="e:\automatic\models\Stable-diffusion\SDXL_juggernautXL_v9Rundiffusionphoto2.safetensors" size=6776MB
10:06:17-128593 INFO     Load embeddings: loaded=0 skipped=0 time=0.00
10:06:17-346372 INFO     Load model: time=5.78 load=5.78 native=1024 {'ram': {'used': 19.59, 'total': 63.89}}
10:06:17-354415 INFO     Startup time: 25.91 torch=6.30 olive=0.12 gradio=2.82 libraries=4.46 samplers=0.06 extensions=2.04 face-restore=0.22 networks=0.05 ui-en=0.34
                         ui-txt2img=0.12 ui-img2img=0.12 ui-control=0.15 ui-settings=0.29 ui-extensions=1.85 ui-defaults=0.09 launch=0.19 api=0.27 app-started=0.25
                         checkpoint=6.00
10:08:39-756572 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
...



gpu dont work

**Comment by vladmandic** [comment]
lets continue in #2972
