### ISSUE TITLE
[Issue]: a ckpt model was not recognized properly

### ISSUE THREAD

**Issue by dfmjndm** [vladmandic/automatic#2969]
### Issue Description

Hello, I did not select the "Disallow models in ckpt format" option, but my ckpt format stable diffusion model was not recognized, even though it has been placed in the stable diffusion folder. I have not encountered this situation in the original version of stable diffusion. What could be the reason?

the link of model is below
https://civitai.com/models/9409?modelVersionId=34373

### Version Platform Description

windows

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by dfmjndm** [comment]
OK，I got it. https://github.com/vladmandic/automatic/issues/2525

Despite this, I think the "Disallow models in ckpt format" option can easily lead to misunderstandings.

**Comment by vladmandic** [comment]
correct.
i'll hide the option when running in default diffusers backend.
