### ISSUE TITLE
[Extension]: Infinite Image Browser sending all metadata to each field

### ISSUE THREAD

**Issue by MysticDaedra** [vladmandic/automatic#2974]
### Issue Description

https://github.com/zanllp/sd-webui-infinite-image-browsing

Normally clicking on the "send to" buttons in the extension would send the proper metadata to each field: positive prompt, negative prompt, and it even works with adetailer, something that SD next natively still seems to struggle with (unrelated issue tho). IIB has been working fine for months, and last was updated on Jan 21 this year. It also worked fine last night, so likely related to something changed on dev this morning, is my thinking.

EDIT: Now instead of sending the full metadata (I didn't manage to get a screenshot of that before I tried refreshing sd.next :( ), it's cutting off the prompt early. 

![image](https://github.com/vladmandic/automatic/assets/17184148/5b0007ac-e4b1-48b6-ad73-daed95675318)

Here's an image of the generation information in IIB:
![image](https://github.com/vladmandic/automatic/assets/17184148/2c344ad0-3656-488f-9942-0b31f5c19808)

### Version Platform Description

Starting SD.Next
19:34:08-461620 INFO     Logger: file="D:\automatic\sdnext.log" level=DEBUG size=65 mode=create
19:34:08-463619 INFO     Python 3.10.6 on Windows
19:34:08-749259 INFO     Version: app=sd.next updated=2024-03-11 hash=98731788
                         url=https://github.com/vladmandic/automatic/tree/dev
19:34:09-173290 INFO     Updating main repository
19:34:11-902859 INFO     Upgraded to version: ed81649c Mon Mar 11 16:59:42 2024 -0400
19:34:11-909861 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.6
19:34:11-911861 DEBUG    Setting environment tuning
19:34:11-912862 DEBUG    HF cache folder: C:\Users\Joshua\.cache\huggingface\hub
19:34:11-913862 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
19:34:11-914862 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
19:34:11-917863 INFO     nVidia CUDA toolkit detected: nvidia-smi present
19:34:11-918863 DEBUG    Installing torch: torch torchvision --index-url https://download.pytorch.org/whl/cu121
19:34:11-996386 INFO     Startup: standard
19:34:11-997385 INFO     Verifying requirements
19:34:12-010388 INFO     Verifying packages
19:34:12-012390 INFO     Verifying submodules
19:34:15-714398 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
19:34:16-413550 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
19:34:17-161477 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
19:34:17-878355 DEBUG    Submodule: extensions-builtin/sd-webui-controlnet / main
19:34:19-143021 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-images-browser / main
19:34:19-847343 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
19:34:20-571127 DEBUG    Submodule: modules/k-diffusion / master
19:34:21-252133 DEBUG    Submodule: wiki / master
19:34:22-077926 DEBUG    Register paths
19:34:22-249288 DEBUG    Installed packages: 321
19:34:22-251289 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg']
19:34:23-043201 DEBUG    Submodule: extensions-builtin\sd-extension-chainner / main
19:34:23-899704 DEBUG    Submodule: extensions-builtin\sd-extension-system-info / main
19:34:24-510740 DEBUG    Running extension installer:
                         D:\automatic\extensions-builtin\sd-extension-system-info\install.py
19:34:25-102467 DEBUG    Submodule: extensions-builtin\sd-webui-agent-scheduler / main
19:34:25-695963 DEBUG    Running extension installer:
                         D:\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
19:34:26-287123 DEBUG    Submodule: extensions-builtin\sd-webui-controlnet / main
19:34:27-323925 DEBUG    Running extension installer: D:\automatic\extensions-builtin\sd-webui-controlnet\install.py
19:34:28-024420 DEBUG    Submodule: extensions-builtin\stable-diffusion-webui-images-browser / main
19:34:28-630904 DEBUG    Running extension installer:
                         D:\automatic\extensions-builtin\stable-diffusion-webui-images-browser\install.py
19:34:29-218135 DEBUG    Submodule: extensions-builtin\stable-diffusion-webui-rembg / master
19:34:29-815047 DEBUG    Running extension installer:
                         D:\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
19:34:30-348701 DEBUG    Extensions all: ['adetailer', 'canvas-zoom', 'sd-webui-infinite-image-browsing',
                         'sd-webui-memory-release', 'sd_civitai_extension', 'ultimate-upscale-for-automatic1111']
19:34:30-437722 DEBUG    Submodule: extensions\adetailer / main
19:34:31-089971 DEBUG    Running extension installer: D:\automatic\extensions\adetailer\install.py
19:34:31-971189 DEBUG    Submodule: extensions\canvas-zoom / main
19:34:32-619691 DEBUG    Running extension installer: D:\automatic\extensions\canvas-zoom\install.py
19:34:42-244948 DEBUG    Submodule: extensions\sd-webui-infinite-image-browsing / main
19:34:42-963030 DEBUG    Running extension installer:
                         D:\automatic\extensions\sd-webui-infinite-image-browsing\install.py
19:34:50-164288 DEBUG    Submodule: extensions\sd-webui-memory-release / main
19:34:51-038282 DEBUG    Submodule: extensions\sd_civitai_extension / main
19:34:51-656462 DEBUG    Running extension installer: D:\automatic\extensions\sd_civitai_extension\install.py
19:34:54-771320 DEBUG    Submodule: extensions\ultimate-upscale-for-automatic1111 / master
19:34:55-585220 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'adetailer', 'canvas-zoom', 'sd-webui-infinite-image-browsing',
                         'sd-webui-memory-release', 'sd_civitai_extension', 'ultimate-upscale-for-automatic1111']

### URL link of the extension

https://github.com/zanllp/sd-webui-infinite-image-browsing

### URL link of the issue reported in the extension repository

https://github.com/zanllp/sd-webui-infinite-image-browsing/issues/541

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by MysticDaedra** [comment]
Here's the log for the paste prompt operation:

```python
19:41:57-212082 DEBUG    Paste prompt: type="current" prompt="A (full body) photograph of druid cla1re standing in a
                         forest casting a pagan spell, (holding a magic druid staff in one hand), wearing a green
                         sweetegl dress with a cloak and a wreath of flowers on her head, looking at the camera with a
                         magical expression, OverallDetail-SDXL, magical lighting, (celtic imagery), photographic,
                         cinematic, highly detailed, intricate details, <lora:SweetLolitaXLv4.23:1.2> <lora:cla1re3
                         (20):1.0>
                         Steps: 15, Seed: 4047384275, Sampler: DPM SDE, CFG scale: 4, Size: 896x896, Parser: Full
                         parser, Model: juggernautXL_v9Rundiffusionphoto2, Model hash: c9e3e68f89, Backend: Diffusers,
                         App: SD.Next, Version: 9557dbf, Operations: hires; upscale; txt2img, Second pass: True, Hires
                         force: True, Hires steps: 10, Hires upscaler: chaiNNer 4xLexicaDAT2_otf, Hires upscale: 1,
                         Hires resize: 1024x1024, Hires size: 1024x1024, Denoising strength: 0.3, Hires sampler: DPM
                         SDE, Image CFG scale: 6, CFG rescale: 0.7, Hypertile UNet: 448, ADetailer model:
                         face_yolov8m.pt, ADetailer prompt: "teenage cla1re, magical expression, fFaceDetail-SDXL
                         EyeDetail-SDXL <lora:cla1re3 (20):1.0>", ADetailer confidence: 0.75, ADetailer mask only top k
                         largest: 1, ADetailer dilate erode: 4, ADetailer mask blur: 4, ADetailer denoising strength:
                         0.4, ADetailer inpaint only masked: True, ADetailer inpaint padding: 32, ADetailer model 2nd:
                         mediapipe_face_mesh_eyes_only, ADetailer prompt 2nd: "purple magical eyes,  EyeDetail-SDXL,
                         <lora:Stunning_eyes_2:1.0>", ADetailer confidence 2nd: 0.6, ADetailer mask only top k largest
                         2nd: 1, ADetailer dilate erode 2nd: 4, ADetailer mask blur 2nd: 4, ADetailer denoising strength
                         2nd: 0.4, ADetailer inpaint only masked 2nd: True, ADetailer inpaint padding 2nd: 32, ADetailer
                         model 3rd: hand_yolov8n.pt, ADetailer prompt 3rd: delicate hand, ADetailer negative prompt 3rd:
                         bad-hands-5-SDXL, ADetailer confidence 3rd: 0.5, ADetailer dilate erode 3rd: 4, ADetailer mask
                         blur 3rd: 4, ADetailer denoising strength 3rd: 0.4, ADetailer inpaint only masked 3rd: True,
                         ADetailer inpaint padding 3rd: 32, ADetailer model 4th: hand_yolov8n.pt, ADetailer prompt 4th:
                         delicate hand, ADetailer negative prompt 4th: bad-hands-5-SDXL, ADetailer confidence 4th: 0.5,
                         ADetailer dilate erode 4th: 4, ADetailer mask blur 4th: 4, ADetailer denoising strength 4th:
                         0.3, ADetailer inpaint only masked 4th: True, ADetailer inpaint padding 4th: 32, ADetailer
                         version: 24.3.0, Lora hashes: "Stunning_eyes_2: 316de08f", Sampler options: karras, Pipeline:
                         StableDiffusionXLInpaintPipeline, Embeddings: bad-hands-5-SDXL, Hashes:
                         {"embed:OverallDetail-SDXL": "d56fc36e04", "lora:SweetLolitaXLv4.23": "efbdc37659", "model":
                         "c9e3e68f89"}"
19:41:57-224084 DEBUG    Settings overrides: []
```

**Comment by MysticDaedra** [comment]
Seems to happen when using the built-in image browser as well.

**Comment by vladmandic** [comment]
i need that metadata as TEXT, not screenshot. not much i can do with a screenshot or text.

**Comment by MysticDaedra** [comment]
Sorry, I wasn't thinking.

Here's the full metadata from the image:

`A (full body) photograph of druid cla1re standing in a forest casting a pagan spell, (holding a magic druid staff in one hand), wearing a green sweetegl dress with a cloak and a wreath of flowers on her head, looking at the camera with a magical expression, OverallDetail-SDXL, magical lighting, (celtic imagery), photographic, cinematic, highly detailed, intricate details, <lora:SweetLolitaXLv4.23:1.2> <lora:cla1re3 (20):1.0>
Steps: 15, Seed: 4047384275, Sampler: DPM SDE, CFG scale: 4, Size: 896x896, Parser: Full parser, Model: juggernautXL_v9Rundiffusionphoto2, Model hash: c9e3e68f89, Backend: Diffusers, App: SD.Next, Version: 9557dbf, Operations: hires; upscale; txt2img, Second pass: True, Hires force: True, Hires steps: 10, Hires upscaler: chaiNNer 4xLexicaDAT2_otf, Hires upscale: 1, Hires resize: 1024x1024, Hires size: 1024x1024, Denoising strength: 0.3, Hires sampler: DPM SDE, Image CFG scale: 6, CFG rescale: 0.7, Hypertile UNet: 448, ADetailer model: face_yolov8m.pt, ADetailer prompt: "teenage cla1re, magical expression, fFaceDetail-SDXL EyeDetail-SDXL <lora:cla1re3 (20):1.0>", ADetailer confidence: 0.75, ADetailer mask only top k largest: 1, ADetailer dilate erode: 4, ADetailer mask blur: 4, ADetailer denoising strength: 0.4, ADetailer inpaint only masked: True, ADetailer inpaint padding: 32, ADetailer model 2nd: mediapipe_face_mesh_eyes_only, ADetailer prompt 2nd: "purple magical eyes,  EyeDetail-SDXL, <lora:Stunning_eyes_2:1.0>", ADetailer confidence 2nd: 0.6, ADetailer mask only top k largest 2nd: 1, ADetailer dilate erode 2nd: 4, ADetailer mask blur 2nd: 4, ADetailer denoising strength 2nd: 0.4, ADetailer inpaint only masked 2nd: True, ADetailer inpaint padding 2nd: 32, ADetailer model 3rd: hand_yolov8n.pt, ADetailer prompt 3rd: delicate hand, ADetailer negative prompt 3rd: bad-hands-5-SDXL, ADetailer confidence 3rd: 0.5, ADetailer dilate erode 3rd: 4, ADetailer mask blur 3rd: 4, ADetailer denoising strength 3rd: 0.4, ADetailer inpaint only masked 3rd: True, ADetailer inpaint padding 3rd: 32, ADetailer model 4th: hand_yolov8n.pt, ADetailer prompt 4th: delicate hand, ADetailer negative prompt 4th: bad-hands-5-SDXL, ADetailer confidence 4th: 0.5, ADetailer dilate erode 4th: 4, ADetailer mask blur 4th: 4, ADetailer denoising strength 4th: 0.3, ADetailer inpaint only masked 4th: True, ADetailer inpaint padding 4th: 32, ADetailer version: 24.3.0, Lora hashes: "Stunning_eyes_2: 316de08f", Sampler options: karras, Pipeline: StableDiffusionXLInpaintPipeline, Embeddings: bad-hands-5-SDXL, Hashes: {"embed:OverallDetail-SDXL": "d56fc36e04", "lora:SweetLolitaXLv4.23": "efbdc37659", "model": "c9e3e68f89"}`

And here's what is being output to the positive prompt field:
`
A (full body) photograph of druid cla1re standing in a forest casting a pagan spell, (holding a magic druid staff in one hand), wearing a green sweetegl dress with a cloak and a wreath of flowers on her head, looking at the camera with a magical expression, OverallDetail-SDXL, magical lighting, (celtic imagery), photographic, cinematic, highly detailed, intricate details, <`

**Comment by vladmandic** [comment]
fixed.
