### ISSUE TITLE
[Issue]: Control: ControlNet (and possibly others) are only applied to the first image of a batch

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#2982]
### Issue Description

As the subject says, when using batch counts greater than 1, only the first one is conditioned by ControlNet. The others are run with the regular pipeline.

An inspection of the logs confirms this:

For the first run
```
10:25:45-329826 INFO     Base: class=StableDiffusionXLControlNetPipeline  
```

For the subsequent images in the batch:

```
10:26:41-328112 INFO     Base: class=StableDiffusionXLPipeline 
```

## Reproduction information

1. Use the Openpose bone image from #2979 
2. Input generation parameters 
3. Set batch count to anything greater than 1
4. Hit Generate 

## Expected results

The ControlNet image conditions every image in the batch

## Actual results

The conditioning is only applied to the first image in the batch. 

### Version Platform Description

08:40:34-882579 INFO     Starting SD.Next                                       
08:40:34-890215 INFO     Logger: file="/notebooks/automatic/sdnext.log"         
                         level=INFO size=24288786 mode=append                   
08:40:34-891536 INFO     Python 3.10.10 on Linux                                                   
08:40:34-932491 INFO     Version: app=sd.next updated=2024-03-16 hash=7ad038df  
                         url=https://github.com/vladmandic/automatic/tree/dev   
08:40:34-938090 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux          
                         release=5.19.0-45-generic python=3.10.10   

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by lbeltrame** [comment]
The second time I did a run, it was applied properly to all images in the batch. So I'm not sure what's going on here.

**Comment by vladmandic** [comment]
fixed.
