### ISSUE TITLE
[Feature]: Api (duplicate methods, method schemas in openapi.json)

### ISSUE THREAD

**Issue by weoses** [vladmandic/automatic#2984]
### Feature description

Some apis in openapi specs is strange

For example, "api_info_info__get" and "api_info_info_get". 
What the difference? And this two fails browser page in swagger... (Firefox 123.0.1)
It is not a problem, i am not going to use it in swagger every day, but it can fail openapi codegenerators like [openapi-generator ](https://github.com/OpenAPITools/openapi-generator). I tried to generate java api client, "__" and "_" squashes when codegen tool converts api names to camel case, and makes a duplicate function. I think it is codegen issue, but method duplicates looks strange...

And some apis doesnt have schema defenition for request/response in openapi. Example:
POST /sdapi/v1/options  
GET /sdapi/v1/loras
GET /sdapi/v1/version
GET /sdapi/v1/platform
GET /sd_extra_networks/*

### Version Platform Description

Version: app=sd.next updated=2024-03-07 hash=bc4b633e
Python 3.10.0 on Windows
Command line args: ['--listen', '--medvram', '--docs'] medvram=True listen=True docs=True

**Comment by vladmandic** [comment]
nobody stated sdapi is 100% openapi schema compliant.
if you want to discuss api design or have a question about specific api, its better suited for either discussion.
and if you want to make schema for an api request, open a feature request (and better yet, contribute and create it via pr).

also, some api requests are too dynamic to have a schema, POST to `options` endpoint is one of them. you want to see whats possible on your current server? do a GET to same endpoint first.

as it is this, this is a very generic issue that i cannot do much about.

oh, i don't know what is `api_info_info__get`, thats not sdapi. you may be referring to swagger internal api.
