### ISSUE TITLE
[Extension]: Ultimate SD Upscaler options covered up in Controlnet tab

### ISSUE THREAD

**Issue by MysticDaedra** [vladmandic/automatic#2987]
### Issue Description

A bunch of the options are being covered or something. I suspect this is just something that needs a CSS fix, but I noticed nobody else has reported it.

![image](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/assets/17184148/808c9902-b0d4-4eb4-bff9-7b30963fd06e)

As you can see, it is impossible to select a scale or view the full list of upscalers. 

### Version Platform Description

Python 3.10.6
Windows 11 Professional
Dev branch 695a2cb8
Mozilla Firefox
RTX 3070 8gb

### URL link of the extension

https://github.com/Coyote-A/ultimate-upscale-for-automatic1111

### URL link of the issue reported in the extension repository

https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/issues/141

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
fixed in latest dev.
