### ISSUE TITLE
[Feature]: Add Second Pass/Refine feature to Img2img

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#2988]
### Feature description

Adding Second Pass/Refine feature to img2img will allow Face Restore to utilise the secondary prompt.

**Comment by vladmandic** [comment]
note that it already works in control tab and you can do all that there, i'm not sure if i want to make major changes to legacy img2img interface. if there is a workflow that you can do in img2img and cant in control, let me know.

**Comment by brknsoul** [comment]
This was feature request added because you asked me too from discord.

![image](https://github.com/vladmandic/automatic/assets/1969381/134ddcaf-49ba-474b-99c8-c0bf2fcf557a)

**Comment by vladmandic** [comment]
i know - and i might still add it - best to keep this open, but question on control tab is valid - is there anything missing there?

**Comment by brknsoul** [comment]
I don't really use Control/ControlNet, so I couldn't tell. :-P

**Comment by vladmandic** [comment]
control tab is intended as do-all - txt2img/img2img/inpaint/outpaint as well as all controlnet and similar items.
and already has more functionality than txt2img and img2img when it comes to resizing and masking (both much more flexible and powerful).
you don't have to use controlnet to use control tab.

**Comment by brknsoul** [comment]
I mean, I don't use ControlNet that often in original backend, nor do I use Control tab in diffusers backend.

**Comment by Aptronymist** [comment]
> I mean, I don't use ControlNet that often in original backend, nor do I use Control tab in diffusers backend.

Sounds like a personal problem. 😉
Try using Control more, it should be your main interface, that's where all of the action happens!

**Comment by vladmandic** [comment]
with all the extra options added to img2img this is pretty much there. but the core msg remains - control tab is the superset.
