### ISSUE TITLE
[Feature]: display download status of pip installs

### ISSUE THREAD

**Issue by cammytown** [vladmandic/automatic#299]
### Feature description

Currently, `setup.py` does not display the status of pip packages being downloaded during the setup process. For people with slower internet connections, this can cause a confusing experience where the terminal simply prints "Installing requirements" and setup.log provides only slightly more information.

In `setup.py`, in the method `install()`, this line of code:

`result = subprocess.run(f'"{sys.executable}" -m pip {arg}', shell=True, check=False, env=os.environ, stdout=subprocess.PIPE, stderr=subprocess.PIPE)`

sends the download status to subprocess.PIPE instead of the terminal.

I can work on this if it is agreed to be an issue.

### Version Platform Description

Arch Linux, conda

**Comment by vladmandic** [comment]
yes, this is on my radar and i'd love contributions.
but i don't want to just print to terminal everything pip says, needs to be a bit more nicer :)
also, pip by default still doesn't show much when its working on a large package, it should be with `-v -log` options, but then its really verbose - so need to parse that output and display something nice instead.

**Comment by GeneralAwareness** [comment]
> ### Feature description
> Currently, `setup.py` does not display the status of pip packages being downloaded during the setup process. For people with slower internet connections, this can cause a confusing experience where the terminal simply prints "Installing requirements" and setup.log provides only slightly more information.
> 
> In `setup.py`, in the method `install()`, this line of code:
> 
> `result = subprocess.run(f'"{sys.executable}" -m pip {arg}', shell=True, check=False, env=os.environ, stdout=subprocess.PIPE, stderr=subprocess.PIPE)`
> 
> sends the download status to subprocess.PIPE instead of the terminal.
> 
> I can work on this if it is agreed to be an issue.
> 
> ### Version Platform Description
> Arch Linux, conda

Yep, got me because it took so damn long, then I got fucked in the end because I can't control anything in this fork.  I was held hostage  not knowing what the fuck it was doing and when it finally finished it had installed torch for cpu.  I just gave up and went back to auto for now.

**Comment by vladmandic** [comment]
until this is done properly, i've just added a bit more verbosity for now:

```
Running setup
Version: 752b91d3 Thu Apr 20 12:29:54 2023 -0400
Installing requirements
Installing package: basicsr
Installing package: bitsandbytes
Installing package: blendmodes
Installing package: clean-fid
Installing package: easydev
```

**Comment by vladmandic** [comment]
actually, i think this is ok for now, parsing pip verbose output is messy as hell.
if someone wants to contribute a pr, i'm open for that.
