### ISSUE TITLE
[Issue]: QuicksettingsUI

### ISSUE THREAD

**Issue by VeteranXT** [vladmandic/automatic#2994]
### Issue Description

Adding sd_lora to quicksetttings dose not show in UI. Only Refiner shows

### Version Platform Description

 Starting SD.Next
Logger: file="E:\Storage\Apps\AI_Geneartor\automatic\sdnext.log" level=INFO size=111845 mode=append
Version: app=sd.next updated=2024-03-21 hash=82973c49 branch=master url=https://github.com/vladmandic/automatic/tree/master
 Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows release=Windows-10-10.0.22631-SP0 python=3.10.11
AMD ROCm toolkit detected
ZLUDA support: experimental
Using ZLUDA in C:\Program Files\AMD\ROCm\5.7\bin
Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg']

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
`sd_lora` settings has been obsolete for a looong time, loras should be referenced using `<lora:xxx>` in prompt.
