### ISSUE TITLE
[Issue]: Image generation start takes way longer since latest commits

### ISSUE THREAD

**Issue by Panchvzluck** [vladmandic/automatic#300]
### Issue Description

Hi there, the issue consists that after https://github.com/vladmandic/automatic/commit/0e7144186d49601356cf890e2dabc2d7f5930801 commit, while using text2image takes way, way longer to start either at the start of the image, or when moving to hi-res steps generations.

(About 10 seconds to start a generation with batch size 2, and 30+ seconds to start hi-res)

Generation speed is the same by itself, but the time to start any generation is longer.

The only option I was using was --no-half-vae, which I enabled in the new setting, but the issue persists.

Reverting to e6701f5 commit fixes this.

### Version Platform Description

Version: 752b91d3 Thu Apr 20 12:29:54 2023 -0400
Windows 11
Google Chrome
RTX 4090
Ryzen 7 5800X

**Comment by Panchvzluck** [comment]
Sampler: DPM++ SDE or DPM++ SDE Karras
Extensions:
```
13:19:38-009037 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'model-keyword', 'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker',
                         'ScuNET', 'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer',
                         'sd-extension-steps-animation', 'sd-extension-system-info', 'sd-webui-controlnet',
                         'sd-webui-model-converter', 'seed_travel', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'SwinIR']
13:19:58-161852 INFO     Extensions enabled: ['sd-dynamic-prompts', 'sd-webui-additional-networks',
                         'stable-diffusion-webui-wd14-tagger']
```

The first paragraph seems to be an extensions in the folder extensions-builtin.
Disabling model-keyword from the extensions-builtin folder didn't seem to help.

Also, when it waits to start any generation (before generating itself), the python usage keeps being high

![image](https://user-images.githubusercontent.com/19153797/233442650-46eb3225-ad4f-4ab0-90bc-55ce578dc1b6.png)

I have the extensions like these, but the issue persits
![image](https://user-images.githubusercontent.com/19153797/233442933-afce865f-ee87-4190-9006-d687aecbc107.png)
Gonna try a re-installation to see if it gets fixed.

**Comment by ApathyJones** [comment]
I have noticed the same issue

**Comment by Panchvzluck** [comment]
@vladmandic after reinstalling and doing some tests, it seems it is something related with a new configuration.

Enabling "Enable cuDNN benchmark feature", disabling it makes the speed the same as older commits.

**Comment by vladmandic** [comment]
there's a reason why that option is disabled by default
that feature tells torch to try several different options and then select fastest, so of course its going to add quite some overhead when starting.
