### ISSUE TITLE
FIRST INSTALLATION / DEPENDENCY MANAGEMENT-HISTORY-BACKUP-DEBUG.RESOLVE-RESTORE

### ISSUE THREAD

**Issue by RGX650** [vladmandic/automatic#3019]
Obviously,
i shouldn't be the only one having extensions breaking my SDNEXT installation with dependency chaos upon their first installation or with time... 
How can I make SDNEXT use an existing venv also managed with Poetry? 

My idea is to use Poetry only as a package manager:

- use Python Poetry to setup a base venv (with also the possibility to use local wheels).
Then install SDNEXT using this venv.

- being able to dry-run debug-resolve the requirements of the extension to install vs my existing SDNEXT dependencies
before installing/updating the extention.

- ability to make a clone of the SDNEXT venv as a kind of sandbox to develop my extention(s)

- i also started to implement a kind of vcs though a local git repo targeting only the Pyproject.toml and its related exported requirements.txt. so could save/backup/restore the installed dependencies "state".

**Comment by RGX650** [comment]
i manage to put together this "setup" without circular dependencies:
------------------
Windows 
Cuda121
Triton-2.10
tensorrt-8.6.1
Torch-2.2.1
Xformers-0.0.26
flash_attn-2.5.2
bitsandbytes-0.43.0
stable_fast-1.0.4
------------------
PYPROJECT.TOML :
------------------


[tool.poetry]
package-mode = false
name = "poetryghost"
version = "0.1.0"
description = "PoetryPackageManager"
authors = ["ZRGX650"]
license = "proprietary"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.*"


Cython = { path = "C:/AI/POETRYGHOST/Cython-3.0.9-cp310-cp310-win_amd64.whl" }

triton = { path = "C:/AI/POETRYGHOST/triton-2.1.0-cp310-cp310-win_amd64.whl" }

nvidia_cudnn_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cudnn_cu12-8.9.7.29-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_cublas_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cublas_cu12-12.1.3.1-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_cuda_cupti_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cuda_cupti_cu12-12.1.105-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_cuda_runtime_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cuda_runtime_cu12-12.1.105-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_cuda_nvrtc_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cuda_nvrtc_cu12-12.1.105-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_cuda_nvcc_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cuda_nvcc_cu12-12.1.105-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_cuda_sanitizer_api_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cuda_sanitizer_api_cu12-12.1.105-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_cufft_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cufft_cu12-11.0.2.54-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_curand_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_curand_cu12-10.3.2.106-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_cusolver_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cusolver_cu12-11.4.5.107-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_cusparse_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cusparse_cu12-12.1.0.106-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_npp_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_npp_cu12-12.1.1.14-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_nvjitlink_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_nvjitlink_cu12-12.1.105-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_nvjpeg_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_nvjpeg_cu12-12.1.1.14-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_nvtx_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_nvtx_cu12-12.1.105-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_cuda_opencl_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cuda_opencl_cu12-12.1.105-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_cuda_cccl_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cuda_cccl_cu12-12.1.109-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
nvidia_cuda_cuxxfilt_cu12 = { path = "C:/AI/POETRYGHOST/nvidia_cuda_cuxxfilt_cu12-12.1.105-py3-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}

cuda_python = { path = "C:/AI/POETRYGHOST/cuda_python-12.1.0-cp310-cp310-win_amd64.whl" }
pycuda = { path = "C:/AI/POETRYGHOST/pycuda-2024.1.tar.gz" }
cupy_cuda12x = { path = "C:/AI/POETRYGHOST/cupy_cuda12x-13.0.0-cp310-cp310-win_amd64.whl" }

torch = { path = "C:/AI/POETRYGHOST/torch-2.2.1+cu121-cp310-cp310-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
torchaudio = { path = "C:/AI/POETRYGHOST/torchaudio-2.2.1+cu121-cp310-cp310-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
torchvision = { path = "C:/AI/POETRYGHOST/torchvision-0.17.1+cu121-cp310-cp310-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}

torchdata = { path = "C:/AI/POETRYGHOST/torchdata-0.7.1-cp310-cp310-win_amd64.whl" }
torchtext = { path = "C:/AI/POETRYGHOST/torchtext-0.17.1+cpu-cp310-cp310-win_amd64.whl" }
torchmetrics = { path = "C:/AI/POETRYGHOST/torchmetrics-1.0.3-py3-none-any.whl" }
torchserve = { path = "C:/AI/POETRYGHOST/torchserve-0.10.0-py3-none-any.whl" }
lit = { path = "C:/AI/POETRYGHOST/lit-18.1.0rc4.tar.gz" }
depyf = { path = "C:/AI/POETRYGHOST/depyf-0.14.1-py3-none-any.whl" }
bitsandbytes = { path = "C:/AI/POETRYGHOST/bitsandbytes-0.43.0-py3-none-win_amd64.whl" }

xformers = { path = "C:/AI/POETRYGHOST/xformers-0.0.26.dev769-cp310-cp310-win_amd64.whl" }

flash_attn = { path = "C:/AI/POETRYGHOST/flash_attn-2.5.2+cu122torch2.2.0cxx11abiFALSE-cp310-cp310-win_amd64.whl" }

tensorboard = { path = "C:/AI/POETRYGHOST/tensorboard-2.16.2-py3-none-any.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
torch_tb_profiler = { path = "C:/AI/POETRYGHOST/torch_tb_profiler-0.4.3-py3-none-any.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}

onnx = { path = "C:/AI/POETRYGHOST/onnx-1.17.0-cp310-cp310-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
onnxruntime_gpu = { path = "C:/AI/POETRYGHOST/onnxruntime_gpu-1.17.1-cp310-cp310-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
tf2onnx = { path = "C:/AI/POETRYGHOST/tf2onnx-1.16.1-py3-none-any.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
onnx2tf = { path = "C:/AI/POETRYGHOST/onnx2tf-1.19.11-py3-none-any.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
onnx2onnx = { path = "C:/AI/POETRYGHOST/onnx2onnx-0.2.4-py3-none-any.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
onnx_extended = { path = "C:/AI/POETRYGHOST/onnx_extended-0.2.4-cp310-cp310-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}

tensorrt = { path = "C:/AI/POETRYGHOST/tensorrt-8.6.1-cp310-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
tensorrt_lean = { path = "C:/AI/POETRYGHOST/tensorrt_lean-8.6.1-cp310-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
tensorrt_dispatch = { path = "C:/AI/POETRYGHOST/tensorrt_dispatch-8.6.1-cp310-none-win_amd64.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
graphsurgeon = { path = "C:/AI/POETRYGHOST/graphsurgeon-0.4.6-py2.py3-none-any.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
onnx_graphsurgeon = { path = "C:/AI/POETRYGHOST/onnx_graphsurgeon-0.3.12-py2.py3-none-any.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}
uff = { path = "C:/AI/POETRYGHOST/uff-0.6.9-py2.py3-none-any.whl", markers = 'platform_system == "Windows" and sys_platform == "win32"'}

stable_fast = { path = "C:/AI/POETRYGHOST/stable_fast-1.0.4+torch221cu121-cp310-cp310-win_amd64.whl" }

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"


[[tool.poetry.source]]
name = "GHOSTREPO"
url = "http://localhost:8080/simple"
priority = "primary"


[[tool.poetry.source]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
priority = "supplemental"


[[tool.poetry.source]]
name = "pytorch-nightly-cu121"
url = "https://download.pytorch.org/whl/nightly/cu121"
priority = "supplemental"


[[tool.poetry.source]]
name = "nvidia-pypi"
url = "https://pypi.nvidia.com/simple"
priority = "supplemental"


[[tool.poetry.source]]
name = "nvidia-ngc"
url = "https://pypi.ngc.nvidia.com/simple"
priority = "supplemental"


[[tool.poetry.source]]
name = "xformers-cu121"
url = "https://download.pytorch.org/whl/cu121/xformers"
priority = "explicit"


[[tool.poetry.source]]
name = "onnxruntime-cuda-121"
url = "https://aiinfra.pkgs.visualstudio.com/PublicPackages/_packaging/onnxruntime-cuda-12/pypi/simple"
priority = "explicit"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

**Comment by vladmandic** [comment]
this looks like a valid dev env suggestion, but not sure what to make of the issue created here? is it an issue? a feature request? something else? also, title is ALL CAPS and not informative. can you please update the issue so it actually states the intention and edit the subject line.

**Comment by RGX650** [comment]
Sorry for the caps, it github cappsed locked the text between my the ----- lines

**Comment by vladmandic** [comment]
no worries, but please edit now?
