### ISSUE TITLE
[Issue]: cant see scripts

### ISSUE THREAD

**Issue by kingofcure** [vladmandic/automatic#302]
### Issue Description

not able to see scripts in both txt2img and img2img, tried changing the order in settings too not seeing it at all. thats all i see 
![image](https://user-images.githubusercontent.com/118279708/233440267-781d6eee-d6b8-45da-93e0-db30cdc91f27.png)

**Comment by kingofcure** [comment]
i just switched to your webui though and can say its so much quicker cuts the time in half keep up the good work

**Comment by vladmandic** [comment]
that is really strange.
can you confirm with default theme, just to rule it out?

**Comment by kingofcure** [comment]
yeah i guess youre right sorry shouldve done that at the start, i was using radius theme but weird
