### ISSUE TITLE
[Issue]: SDXL model Pony Diffusion V6 XL not working in SD.Next on current release (82973c49)

### ISSUE THREAD

**Issue by mph1git** [vladmandic/automatic#3028]
### Issue Description

After my latest update to `Version: app=sd.next updated=2024-03-21 hash=82973c49 branch=master` _(I am using the Stability Matrix for maintaining my webUIs)_ the image generation using SDXL model **Pony Diffusion V6 XL** (https://civitai.com/models/257749/pony-diffusion-v6-xl) creates weird results. See included images (incl. metadata). At least my previous `Version: app=sd.next updated=2023-12-30 hash=ab7b78cc` worked as expected.

Even my pretty old Automatic1111 (v1.7.0 updated on january 2024) does the job right.

I've tested the current SD.Next version and the oldest version available in Stability Matrix (`d0e35a7a`) with my other SDXL models (`sd_xl_base_1.0_0.9vae `, `colossusProjectXLSFW_v202BakedVAE`,`ZavyYumeXL`) with expected result. 

![00042-ponyDiffusionV6XL_v6-a girl in the woods](https://github.com/vladmandic/automatic/assets/166126359/8fc29d9d-f9e8-439f-b376-2bfe1ebc36a3)
![00036-sd_xl_base_1 0_0 9vae-a girl in the woods](https://github.com/vladmandic/automatic/assets/166126359/3315e6aa-d060-47d0-a560-77adb6485f42)
![00038-colossusProjectXLSFW_v202BakedVAE-a girl in the woods](https://github.com/vladmandic/automatic/assets/166126359/b9eb5241-41e3-40f5-b5aa-1477e26005ad)
![00039-zavyyumexl_v10-a girl in the woods](https://github.com/vladmandic/automatic/assets/166126359/3631f620-7bb2-43fa-8222-fcd96aa94381)

Maybe some of the newly added features made the PonyXL model incompatible.

### Version Platform Description

```
14:39:19-746068 INFO     Starting SD.Next                                      
14:39:19-748068 INFO     Logger: file="D:\Data\Packages\SD.Next Web UI\sdnext.log" level=INFO
                         size=214193 mode=append                               
14:39:19-749068 INFO     Python 3.10.11 on Windows                             
14:39:19-835635 INFO     Version: app=sd.next updated=2024-03-21 hash=82973c49 
                         branch=master                                         
                         url=https://github.com/vladmandic/automatic/tree/maste
                         r                                                     
14:39:20-269654 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97     
                         Stepping 2, AuthenticAMD system=Windows               
                         release=Windows-10-10.0.19045-SP0 python=3.10.11      
14:39:20-272654 INFO     nVidia CUDA toolkit detected: nvidia-smi present      
14:39:20-332668 INFO     Extensions: disabled=[]                               
14:39:20-333668 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 
                         'sd-extension-system-info',                           
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet',    
                         'stable-diffusion-webui-images-browser',              
                         'stable-diffusion-webui-rembg'] extensions-builtin    
14:39:20-335669 INFO     Extensions: enabled=['sd-dynamic-prompts',            
                         'sd-webui-infinite-image-browsing'] extensions        
14:39:20-337669 INFO     Startup: standard                                     
14:39:20-338670 INFO     Verifying requirements                                
14:39:20-340670 INFO     Verifying packages                                    
14:39:20-341670 INFO     Verifying submodules                                  
14:39:26-817102 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 
                         'sd-extension-system-info',                           
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet',    
                         'stable-diffusion-webui-images-browser',              
                         'stable-diffusion-webui-rembg', 'sd-dynamic-prompts', 
                         'sd-webui-infinite-image-browsing']                   
14:39:26-818102 INFO     Verifying requirements                                
14:39:26-823103 INFO     Command line args: ['--autolaunch', '--use-cuda']     
                         autolaunch=True use_cuda=True                         
14:39:30-004517 INFO     Load packages: {'torch': '2.2.2+cu121', 'diffusers':  
                         '0.27.0', 'gradio': '3.43.2'}                         
14:39:30-722039 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda        
                         device=cuda attention="Scaled-Dot-Product"            
                         mode=no_grad                                          
14:39:30-766144 INFO     Device: device=NVIDIA GeForce RTX 4080 n=1 arch=sm_90 
                         cap=(8, 9) cuda=12.1 cudnn=8801 driver=551.61         
14:39:31-293512 INFO     Available VAEs: path="models\VAE" items=3             
14:39:31-294519 INFO     Disabled extensions: ['sd-webui-controlnet']          
14:39:31-295510 INFO     Removing empty folder: models\BSRGAN                  
14:39:31-303512 INFO     Available models: path="models\Stable-diffusion"      
                         items=7 time=0.01                                    
14:39:31-378704 INFO     Extension:                                            
                         script='extensions-builtin\Lora\scripts\lora_script.py
                         ' 14:39:31-375704 INFO       
                         LoRA networks: available=15          
                         folders=2                             
14:39:31-722780 INFO     Extension:                                            
                         script='extensions-builtin\sd-webui-agent-scheduler\sc
                         ripts\task_scheduler.py' Using sqlite file:           
                         extensions-builtin\sd-webui-agent-scheduler\task_sched
                         uler.sqlite3                                          
14:39:31-923827 INFO     UI theme: name="black-teal" style=Auto base=sdnext.css
14:39:33-494040 INFO     Local URL: http://127.0.0.1:7860/                     
14:39:33-785102 INFO     [AgentScheduler] Task queue is empty                  
14:39:33-786102 INFO     [AgentScheduler] Registering APIs                     
IIB Database file has been successfully backed up to the backup folder.
14:39:33-880116 INFO     Select: model="sdxl\ponyDiffusionV6XL_v6 [67ab2fd8ec]"
14:39:33-901121 INFO     Setting Torch parameters: device=cuda                 
                         dtype=torch.float16 vae=torch.float16                 
                         unet=torch.float16 context=no_grad fp16=True bf16=None
                         optimization=Scaled-Dot-Product                       
14:39:33-903122 INFO     Autodetect: model="Stable Diffusion XL"               
                         class=StableDiffusionXLPipeline file="D:\Data\Packages
                         \SD.Next Web UI\models\Stable-diffusion\sdxl\ponyDiffu
                         sionV6XL_v6.safetensors" size=6617MB                               
14:39:36-763040 INFO     Load embeddings: loaded=0 skipped=30 time=0.04        
14:39:36-962086 INFO     Load model: time=2.88 load=2.88 native=1024 {'ram':   
                         {'used': 0.98, 'total': 63.15}, 'gpu': {'used': 8.14, 
                         'total': 15.99}, 'retries': 0, 'oom': 0}              
14:39:36-965087 INFO     Startup time: 10.14 torch=2.63 gradio=0.51            
                         libraries=1.26 extensions=0.56 ui-en=0.17             
                         ui-control=0.07 ui-settings=0.14 ui-extensions=0.94   
                         launch=0.09 api=0.24 app-started=0.15 checkpoint=3.08 
14:39:36-968088 INFO     Launching browser                                     
14:39:38-837469 INFO     MOTD: N/A                                             
14:39:42-922864 INFO     Browser session: user=None client=127.0.0.1           
                         agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64;       
                         rv:124.0) Gecko/20100101 Firefox/124.0 
```

### Relevant log output

```shell
14:47:26-056767 INFO     Base: class=StableDiffusionXLPipeline                 
Progress  3.87it/s █████████████████████████████████ 100% 25/25 00:06 00:00 Base
14:47:36-827296 INFO     Saving:                                               
                         image="outputs\text\00006-ponyDiffusionV6XL_v6-a girl 
                         in the woods.jpg" type=JPEG resolution=1024x1024      
                         size=0                                                
14:47:36-833297 INFO     Processed: images=1 time=10.80 its=2.32 memory={'ram':
                         {'used': 1.99, 'total': 63.15}, 'gpu': {'used': 8.88, 
                         'total': 15.99}, 'retries': 0, 'oom': 0}
```

### Backend

Diffusers

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by mph1git** [comment]
Maybe useful additional info:
I've tried to force Stability Matrix (SM) to use another version of SD.Next:
- according to my previous functioning version I've downloaded branch `automatic-ab7b78ccf4bf8e0145c846525e6ddb428c7309d8` from Git via ZIP
- copied the content to a new folder of SM packages
- after launching the SM, on Packages tab I've clicked on Import of unknown package. From the available versions for install I choose commit `a35e800` and launched the newly SM available package
- the installation passed with some errors and a huge list of "WARNING - Modified files"
- however my SD.Next is now up and running and working well (the expected way)

I liked some of the new features (e.g. the Seed variations), of my ordinary SD.Next version which is reported as `82973c4` in SM. So I've tried to go up and downloaded another version from Git - yes: `automatic-a35e8002d9340f994f49e4c4011b04b4afe9c870`
- started over with the _unknown package_, _install_, and installed this another package (again with a lot of Modified files warnings)
- but at this moment the latest package is not working (does not work with the PonyXL model), however, the Stability Matrix shows the same version of SD.Next installed - `master@a35e800` as before.

I am a bit confused now, but at least I have the functioning workspace.
It's a long time I used to be a developer, but never used Git. Just hope I was clear enough to help solve the issue. Still ready to help you to sort it out.

**Comment by vladmandic** [comment]
do not set clip-skip=2, its not needed and causes bad images with pony.
clip-skip=2 is only recommended in model details because clip-skip implementation for sdxl in a1111 is basically broken.

**Comment by mph1git** [comment]
Thank you for your advice, but sadly it does not solved the problem. I did a fresh install of the SD.Next using Stability Matrix (master@82973c4) and the image generation using PonyXL is still not working:
![00000-ponyDiffusionV6XL_v6-a girl in the woods](https://github.com/vladmandic/automatic/assets/166126359/d603517f-8946-4753-aab3-0c684ad3a5e8)

**Comment by mph1git** [comment]
Actually, calling same prompt within my "working" instance of SD.Next and using PonyXL model creates similar result regarding the Clip Skip Settings (1 and 2, see metadata):

Clip Skip=1:
![00005-ponyDiffusionV6XL_v6-a girl in the woods](https://github.com/vladmandic/automatic/assets/166126359/1030d5d3-bcb8-4b80-bdbb-c302f4b8916c)

Clip Skip=2:
![00007-ponyDiffusionV6XL_v6-a girl in the woods](https://github.com/vladmandic/automatic/assets/166126359/a17bfca8-d5c4-4d95-ba86-21142486ef52)

**Comment by Disty0** [comment]
- PonyXL is a hentai model, you have to use danbooru tags.
- PonyXL uses these tags to get an image:
  - source_pony
  - source_anime
  - source_furry
  - source_cartoon
- PonyXL requires the default Clip Skip (1).
  This model will fall apart if you touch the Clip Skip settings.

**Comment by mph1git** [comment]
Ok, many thanks for your effort. According to your advices I did a lot of tests with the latest one and "my working" copy of SD.Next.
The Clip Skip and prompt makes the difference, and with respect to this the latest version generates images well - if correctly used. Thank you for help!

This issue can be closed and I'll looking forward for sorting out the metadata issue (https://github.com/vladmandic/automatic/issues/3030), which makes current version still unusable at the moment.

Thank you once more for your effort!

**Comment by vladmandic** [comment]
closing this issue
