### ISSUE TITLE
[Issue]: Lightbox does not appear wen clicking on an image

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3029]
### Issue Description

This happened after the latest commit that touched JS. At least in Firefox, clicking on images after generation brings the gallery one image forward, but does not display the image in the lightbox. 

### Version Platform Description

SD.Next 9d04255b54af5fc4c62ade5ae4ff10f588c7210b

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
