### ISSUE TITLE
[Feature]: Toggle to allow deletion of the built in extensions

### ISSUE THREAD

**Issue by derrian-distro** [vladmandic/automatic#303]
### Feature description

I don't use a good 90% of the extensions you have included by default and would rather they just be removed entirely, however every startup, even after deletion, they get reinstalled.

It'd be great if these plugins were just optional vs required.

**Comment by vladmandic** [comment]
you can just disable them in extensions if you don't want them. i'm not removing them.

**Comment by derrian-distro** [comment]
it's not a disc space issue, it's an organization issue for me
