### ISSUE TITLE
[Extension]: Infinite Image Browser cannot load image metadata

### ISSUE THREAD

**Issue by mph1git** [vladmandic/automatic#3030]
### Issue Description

My current version of SD.Next `Version: app=sd.next updated=2024-03-21 hash=82973c49 branch=master` produces images, of which metadata cannot be read in the Infinite Image Browsing, the information pop-up in the browser is empty.
![obrazek](https://github.com/vladmandic/automatic/assets/166126359/87288ab5-336f-4a1d-8325-943e33982efb)

Images created with older SD.Next `Version: app=sd.next updated=2023-12-30 hash=ab7b78cc` are still read correctly.
![obrazek](https://github.com/vladmandic/automatic/assets/166126359/d6a4271c-df50-4ebc-b4a7-cbae8fa7bafa)

### Version Platform Description

14:39:19-746068 INFO     Starting SD.Next                                      
14:39:19-748068 INFO     Logger: file="D:\Data\Packages\SD.Next Web UI\sdnext.log" level=INFO
                         size=214193 mode=append                               
14:39:19-749068 INFO     Python 3.10.11 on Windows                             
14:39:19-835635 INFO     Version: app=sd.next updated=2024-03-21 hash=82973c49 
                         branch=master                                         
                         url=https://github.com/vladmandic/automatic/tree/maste
                         r                                                     
14:39:20-269654 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97     
                         Stepping 2, AuthenticAMD system=Windows               
                         release=Windows-10-10.0.19045-SP0 python=3.10.11      
14:39:20-272654 INFO     nVidia CUDA toolkit detected: nvidia-smi present      
14:39:20-332668 INFO     Extensions: disabled=[]                               
14:39:20-333668 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 
                         'sd-extension-system-info',                           
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet',    
                         'stable-diffusion-webui-images-browser',              
                         'stable-diffusion-webui-rembg'] extensions-builtin    
14:39:20-335669 INFO     Extensions: enabled=['sd-dynamic-prompts',            
                         'sd-webui-infinite-image-browsing'] extensions        
14:39:20-337669 INFO     Startup: standard                                     
14:39:20-338670 INFO     Verifying requirements                                
14:39:20-340670 INFO     Verifying packages                                    
14:39:20-341670 INFO     Verifying submodules                                  
14:39:26-817102 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 
                         'sd-extension-system-info',                           
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet',    
                         'stable-diffusion-webui-images-browser',              
                         'stable-diffusion-webui-rembg', 'sd-dynamic-prompts', 
                         'sd-webui-infinite-image-browsing']                   
14:39:26-818102 INFO     Verifying requirements                                
14:39:26-823103 INFO     Command line args: ['--autolaunch', '--use-cuda']     
                         autolaunch=True use_cuda=True                         
14:39:30-004517 INFO     Load packages: {'torch': '2.2.2+cu121', 'diffusers':  
                         '0.27.0', 'gradio': '3.43.2'}                         
14:39:30-722039 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda        
                         device=cuda attention="Scaled-Dot-Product"            
                         mode=no_grad                                          
14:39:30-766144 INFO     Device: device=NVIDIA GeForce RTX 4080 n=1 arch=sm_90 
                         cap=(8, 9) cuda=12.1 cudnn=8801 driver=551.61         
14:39:31-293512 INFO     Available VAEs: path="models\VAE" items=3             
14:39:31-294519 INFO     Disabled extensions: ['sd-webui-controlnet']          
14:39:31-295510 INFO     Removing empty folder: models\BSRGAN                  
14:39:31-303512 INFO     Available models: path="models\Stable-diffusion"      
                         items=7 time=0.01                                    
14:39:31-378704 INFO     Extension:                                            
                         script='extensions-builtin\Lora\scripts\lora_script.py
                         ' 14:39:31-375704 INFO       
                         LoRA networks: available=15          
                         folders=2                             
14:39:31-722780 INFO     Extension:                                            
                         script='extensions-builtin\sd-webui-agent-scheduler\sc
                         ripts\task_scheduler.py' Using sqlite file:           
                         extensions-builtin\sd-webui-agent-scheduler\task_sched
                         uler.sqlite3                                          
14:39:31-923827 INFO     UI theme: name="black-teal" style=Auto base=sdnext.css
14:39:33-494040 INFO     Local URL: http://127.0.0.1:7860/                     
14:39:33-785102 INFO     [AgentScheduler] Task queue is empty                  
14:39:33-786102 INFO     [AgentScheduler] Registering APIs                     
IIB Database file has been successfully backed up to the backup folder.
14:39:33-880116 INFO     Select: model="sdxl\ponyDiffusionV6XL_v6 [67ab2fd8ec]"
14:39:33-901121 INFO     Setting Torch parameters: device=cuda                 
                         dtype=torch.float16 vae=torch.float16                 
                         unet=torch.float16 context=no_grad fp16=True bf16=None
                         optimization=Scaled-Dot-Product                       
14:39:33-903122 INFO     Autodetect: model="Stable Diffusion XL"               
                         class=StableDiffusionXLPipeline file="D:\Data\Packages
                         \SD.Next Web UI\models\Stable-diffusion\sdxl\ponyDiffu
                         sionV6XL_v6.safetensors" size=6617MB                               
14:39:36-763040 INFO     Load embeddings: loaded=0 skipped=30 time=0.04        
14:39:36-962086 INFO     Load model: time=2.88 load=2.88 native=1024 {'ram':   
                         {'used': 0.98, 'total': 63.15}, 'gpu': {'used': 8.14, 
                         'total': 15.99}, 'retries': 0, 'oom': 0}              
14:39:36-965087 INFO     Startup time: 10.14 torch=2.63 gradio=0.51            
                         libraries=1.26 extensions=0.56 ui-en=0.17             
                         ui-control=0.07 ui-settings=0.14 ui-extensions=0.94   
                         launch=0.09 api=0.24 app-started=0.15 checkpoint=3.08 
14:39:36-968088 INFO     Launching browser                                     
14:39:38-837469 INFO     MOTD: N/A                                             
14:39:42-922864 INFO     Browser session: user=None client=127.0.0.1           
                         agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64;       
                         rv:124.0) Gecko/20100101 Firefox/124.0  

### URL link of the extension

https://github.com/zanllp/sd-webui-infinite-image-browsing

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
post two example images - one old that works and one new that doesn't work.

**Comment by mph1git** [comment]
This is an old one, created using sd_xl_base model:
![00036-sd_xl_base_1 0_0 9vae-logo of Agile Kitchen workshop about agile values](https://github.com/vladmandic/automatic/assets/166126359/9151629b-f514-4825-9e68-eec4e1635a81)

This is the new one - broken:
![00036-sd_xl_base_1 0_0 9vae-a girl in the woods](https://github.com/vladmandic/automatic/assets/166126359/6d823887-282d-4c8a-afa9-4dfafe8d5564)

However, using my new "working" instance manualy created from Git (https://github.com/vladmandic/automatic/issues/3028) is ok too:
![00004-sd_xl_base_1 0_0 9vae-a girl in the woods](https://github.com/vladmandic/automatic/assets/166126359/a3d576c8-2cbe-4d6f-b838-fa61d69b4e4e)

And here's the newest one, created on a fresh install of SD.Next and using PonyXL model with Clip Skip set to 1 (according to https://github.com/vladmandic/automatic/issues/3028 advice) - it does not work and the metadata are missing:
![00000-ponyDiffusionV6XL_v6-a girl in the woods](https://github.com/vladmandic/automatic/assets/166126359/09f87309-11c2-4998-94a0-bfd0badf8801)

Thanks for your effort!

**Comment by vladmandic** [comment]
i've checked all 4 images and all 4 appear to have valid metadata:

> vlado@wsl:~ $ image-exif.py ~/downloads/1.jpg
```json
exif:
{
    'UserComment': 'logo of "Agile Kitchen" workshop about agile values and principles , michelin star\n\nSteps: 30, Seed: 2124935285, Sampler: Default, CFG scale: 4, Size: 512x512, Batch: 4x1, Index: 4x1, Parser: Full parser, Model: sd_xl_base_1.0_0.9vae, Model hash:
e6bb9ea85b, Backend: Diffusers, App: SD.Next, Version: ab7b78c, Operations: txt2img, Pipeline: StableDiffusionXLPipeline'
}
info:
{
    'Steps': 30,
    'Seed': 2124935285,
    'Sampler': 'Default',
    'CFG scale': 4,
    'Size': '512x512',
    'Batch': '4x1',
    'Index': '4x1',
    'Parser': 'Full parser',
    'Model': 'sd_xl_base_1.0_0.9vae',
    'Model hash': 'e6bb9ea85b',
    'Backend': 'Diffusers',
    'App': 'SD.Next',
    'Version': 'ab7b78c',
    'Operations': 'txt2img',
    'Pipeline': 'StableDiffusionXLPipeline',
    'Size-1': 512,
    'Size-2': 512,
    'Batch-1': 4,
    'Batch-2': 1,
    'Index-1': 4,
    'Index-2': 1,
    'Prompt': 'logo of "Agile Kitchen" workshop about agile values and principles , michelin star',
    'Negative prompt': ''
}
```

> vlado@wsl:~ $ image-exif.py ~/downloads/2.jpg
```json
{
    'UserComment': 'a girl in the woods\nSteps: 25, Seed: 1530202027, Sampler: Euler a, CFG scale: 6, Size: 1024x1024, Parser: Full parser, Model: sd_xl_base_1.0_0.9vae, Model hash: e6bb9ea85b, Clip skip: 2, Backend: Diffusers, App: SD.Next, Version: d0e35a7, Operations:
txt2img, Sampler options: , Pipeline: StableDiffusionXLPipeline'
}
info:
{
    'Steps': 25,
    'Seed': 1530202027,
    'Sampler': 'Euler a',
    'CFG scale': 6,
    'Size': '1024x1024',
    'Parser': 'Full parser',
    'Model': 'sd_xl_base_1.0_0.9vae',
    'Model hash': 'e6bb9ea85b',
    'Clip skip': 2,
    'Backend': 'Diffusers',
    'App': 'SD.Next',
    'Version': 'd0e35a7',
    'Operations': 'txt2img',
    'Sampler options': '',
    'Pipeline': 'StableDiffusionXLPipeline',
    'Size-1': 1024,
    'Size-2': 1024,
    'Prompt': 'a girl in the woods',
    'Negative prompt': ''
}
```

so i don't think its a metadata issue, its more likely that there is some issue with infinite-browser api integration into sdnext.
please create issue on infinite-browser github and tag me - i can work with author, but chances are it needs to be addressed from that side.

**Comment by vladmandic** [comment]
fixed upstream.
