### ISSUE TITLE
[Feature]: Allow dragging and dropping from img2img output image to input

### ISSUE THREAD

**Issue by Silanda** [vladmandic/automatic#3031]
### Feature description

As it stands, images can be dragged from external sources (e.g. Windows Explorer) into the img2img input, but dragging from the img2img output back into image, inpaint, etc, directly doesn't work.

As someone who uses multiple inpaint passes, and with the number of send to buttons limited, it would be beneficial to workflow if output images could be dragged directly back across to, for example, inpaint. That way the functionality of the lost "to inpaint" button is effectively retained without having to leave SD.Next to drag and drop, or having to do a two step move "to image" and then "to inpaint".

### Version Platform Description

Dev 9d04255b
Windows 11
Firefox 124.0.2

**Comment by Silanda** [comment]
Ah! I've only done a quick and dirty test, so I can't rule out the issue being connected to something else, but here it seems to work using Edge, but not Firefox.

**Comment by vladmandic** [comment]
firefox is full of issues, this would not be the first one. i used to love firefox, nowadays its the worst browser engine by far.
