### ISSUE TITLE
[Issue]: i have safetensors models and get Cannot generate without a checkpoint

### ISSUE THREAD

**Issue by timsss** [vladmandic/automatic#3032]
### Issue Description

i have safetensors models and get Cannot generate without a checkpoint
Using models path: C:\Users\timos\automatic\models
19:31:33-717359 INFO     Available VAEs: path="C:\Users\timos\automatic\models\VAE" items=0
19:31:33-717359 INFO     Disabled extensions: ['sd-webui-controlnet']
19:31:33-733190 INFO     Available models: path="C:\Users\timos\automatic\models\Stable-diffusion" items=0 time=0.02
19:31:33-857661 INFO     Extension: script='extensions-builtin\Lora\scripts\lora_script.py'
                         19:31:33-843747 INFO     LoRA networks: available=0
                         folders=2
19:31:34-346270 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py'
                         Using sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
19:31:34-653135 INFO     UI theme: name="black-teal" style=Auto base=sdnext.css
19:31:35-770654 INFO     Extension list is empty: refresh required
19:31:37-565432 INFO     Local URL: http://127.0.0.1:7860/
19:31:37-685941 INFO     [AgentScheduler] Task queue is empty
19:31:37-685941 INFO     [AgentScheduler] Registering APIs
19:31:37-965529 WARNING  Cannot generate without a checkpoint

### Version Platform Description

window 11

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
> 19:31:33-733190 INFO Available models: path="C:\Users\timos\automatic\models\Stable-diffusion" items=0 time=0.02

can you show content of that folder?

**Comment by timsss** [comment]
amd rx 6400 
![Unbenannt-1-14](https://github.com/vladmandic/automatic/assets/713486/74b3b792-9b5f-4250-b1b1-fb24a81b3b33)

**Comment by vladmandic** [comment]
do an actual `dir` from command line and post text. i need to see file sizes as well as text to be able to select it. screenshots are not advised unless we're talking about ui.

**Comment by vladmandic** [comment]
that looks ok. lets start from beginning
- post full required info in the issue
- upload `webui.bat --debug` full startup log

**Comment by brknsoul** [comment]
> C:\Users\timos\automatic\models\Stable Diffusion

The folder should be `models\stable-diffusion`
You're missing the `-` between the words.

**Comment by timsss** [comment]
thank you very much

**Comment by vladmandic** [comment]
@brknsoul good catch!
