### ISSUE TITLE
Poor image quality

### ISSUE THREAD

**Issue by jason571** [vladmandic/automatic#3038]
### Feature description

The same prompt, using other UIs with good quality
![00022-playground-v2 5-1024px-aesthetic fp16-epiCPhoto RAW photo 8k uhd dslr high quality](https://github.com/vladmandic/automatic/assets/22809213/7c0821d6-b0ca-4ad6-a464-15458a586a9b)

**Comment by vladmandic** [comment]
you have provider ZERO information.
complete all required sections.
and provide image metadata.

And this is not enhancement request.

**Comment by vladmandic** [comment]
closing as no information provided. can be reopened once information is available.
