### ISSUE TITLE
[Feature]: Support for DPM++ SDE on diffusers backend.

### ISSUE THREAD

**Issue by raymanaa** [vladmandic/automatic#3042]
### Feature description

Original backend has DPM++ SDE support. and I cannot find it using the diffusers backend. Eventhough k-diffusion repo does have support for DPM++ SDE.

Most new turbo models use DPM++ SDE so it might be interesting to add support for it.

**Comment by brknsoul** [comment]
Already exists.
Set Sampler to DPM SDE
Go to Settings > Sampler Settings > DPM solver algorithm and select sde-dpmsolver++.

**Comment by Disty0** [comment]
Already exists: DPM++ 1S with default settings or DPM SDE

https://github.com/huggingface/diffusers/issues/4167
