### ISSUE TITLE
[Issue]: Safetensors embeddings disappear from view in dev upon refresh or restart

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#3045]
### Issue Description

Installing an embedding with a .safetensors extension shows up in the Network's embeddings tab until a refresh.

This behaviour is only seen in dev, not in master.

![chrome_RpFB7QA5Tt](https://github.com/vladmandic/automatic/assets/1969381/0e11f723-0ab8-4479-9cc0-1583cbe98162)

### Version Platform Description

Python 3.10.11 on Windows
Version: app=sd.next updated=2024-04-10 hash=5500b8af branch=dev
url=https://github.com/vladmandic/automatic/tree/dev
Latest published version: 7ecc1d7d9a98172326aaa16088039439dcebb02d 2024-04-09T07:14:34Z
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel system=Windows
release=Windows-10-10.0.19045-SP0 python=3.10.11
Setting environment tuning

### Relevant log output

```shell
08:53:20-508255 DEBUG    Extra networks: page='embedding' items=108 subfolders=1 tab=txt2img

08:54:18-615078 DEBUG    Refreshing Extra networks: page='Embedding' items=107 tab=txt2img
```

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
