### ISSUE TITLE
[Issue]: Can't enable sd-webui-controlnet

### ISSUE THREAD

**Issue by kgonia** [vladmandic/automatic#3046]
### Issue Description

I'm trying to enable sd-webui-controlnet but after restart extension is still disabled

### Version Platform Description

18:14:07-166116 INFO     Starting SD.Next
18:14:07-170116 INFO     Logger: file="E:\automatic\sdnext.log" level=DEBUG size=65 mode=create
18:14:07-171116 INFO     Python 3.10.10 on Windows
18:14:07-330591 INFO     Version: app=sd.next updated=2024-04-09 hash=7ecc1d7d branch=master
                         url=https://github.com/vladmandic/automatic.git/tree/master
18:14:07-684633 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
                         system=Windows release=Windows-10-10.0.19045-SP0 python=3.10.10
                       
18:14:25-071783 INFO     Load packages: {'torch': '2.0.0+cu118', 'diffusers': '0.27.0', 'gradio': '3.43.2'}
18:14:25-988991 DEBUG    Read: file="config.json" json=98 bytes=4570 time=0.000
18:14:25-993989 ERROR    Error: bad setting value: cuda_compile: False (bool; expected list)
18:14:25-994992 DEBUG    Unknown settings: ['sd_vae_as_default', 'enable_emphasis', 'enable_batch_seeds',
                         'cross_attention_options', 'grid_only_if_multiple', 'grid_prevent_empty_spots',
                         'enable_pnginfo', 'cuda_allow_tf32', 'cuda_allow_tf16_reduced', 'ESRGAN_tile',
                         'ESRGAN_tile_overlap', 'realesrgan_enabled_models', 'use_old_hires_fix_width_height',
                         'dont_fix_second_order_samplers_schedule', 'memmon_poll_rate', 'multiple_tqdm',
                         'print_hypernet_extra', 'extra_networks_default_view', 'extra_networks_card_width',
                         'extra_networks_card_height', 'extra_networks_add_text_separator',
                         'do_not_show_images', 'add_model_hash_to_info', 'add_model_name_to_info',
                         'js_modal_lightbox', 'js_modal_lightbox_initially_zoomed', 'show_progress_in_title',
                         'quicksettings', 'hidden_tabs', 'ui_reorder', 'ui_extra_networks_tab_reorder',
                         'hide_samplers', 'eta_ddim', 'eta_ancestral', 'always_discard_next_to_last_sigma',
                         'upscaling_max_images_in_cache', 'token_merging', 'token_merging_hr_only',
                         'token_merging_random', 'token_merging_merge_attention',
                         'token_merging_merge_cross_attention', 'token_merging_merge_mlp',
                         'token_merging_maximum_down_sampling', 'token_merging_stride_x',
                         'token_merging_stride_y']
18:14:27-025231 INFO     Disabled extensions: ['a1111-sd-webui-lycoris',
                         'multidiffusion-upscaler-for-automatic1111', 'sd-dynamic-thresholding',
                         'sd-webui-controlnet']

### Relevant log output

```shell
18:11:12-623398 DEBUG    Extensions apply:
                         disable=["sd-dynamic-thresholding","multidiffusion-upscaler-for-automatic1111","a1111-s
                         d-webui-lycoris"] update=[]
18:11:12-626395 WARNING  Server shutdown requested
18:11:13-160697 INFO     Server restarting...
18:11:13-806197 INFO     Server will restart
18:11:16-730693 DEBUG    Memory: 1.08/31.74 collected=130488
18:11:16-732695 DEBUG    Starting module: <module 'webui' from 'E:\\automatic\\webui.py'>
18:11:16-734693 INFO     Command line args: ['--debug'] debug=True lyco_dir=models\LyCORIS
18:11:16-735695 DEBUG    Env flags: []
18:11:16-737693 DEBUG    Entering start sequence
18:11:16-740695 DEBUG    Initializing
18:11:16-742693 INFO     Available VAEs: path="E:\automatic\models\VAE" items=0
18:11:16-744695 INFO     Disabled extensions: ['a1111-sd-webui-lycoris',
                         'multidiffusion-upscaler-for-automatic1111', 'sd-dynamic-thresholding',
                         'sd-webui-controlnet']
```

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
read docs, this was mentioned many times.
original controlnet extension is only available when running in legacy backend=original.
in default mode, backend=diffusers sdnext has its own control functionalitry and original extensions is not supported.
