### ISSUE TITLE
[Issue]: ControlNet lite returning attribute error

### ISSUE THREAD

**Issue by MysticDaedra** [vladmandic/automatic#3049]
### Issue Description

I consistently get an attribute error when using ControlNet lite in dev. I'm specifically using the ControlNet SDXL Realistic Tile model: https://huggingface.co/bdsqlsz/qinglong_controlnet-lllite/blob/main/bdsqlsz_controlllite_xl_tile_realistic.safetensors

I tested with regular controlnet as well, no error. I guess it could be a problem with the model, but I've used it before without getting this error. 

Log: 
[sdnext.log](https://github.com/vladmandic/automatic/files/14964878/sdnext.log)

### Version Platform Description

SD.Next dev version bb0f2365
Windows 11 Professional
RTX 3070 8gb
Python 3.11.8
Torch: 2.2.1+cu121 Autocast  half

### Relevant log output

```shell
See description, log too large to paste here.
```

### Backend

Diffusers

### Branch

Dev

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i cannot reproduce the problem with basic workflow, please document exact workflow.
also note the error message from your log:
> 2024-04-12 16:38:48,262 | sd | WARNING | run | Control: ControlLLLite does not support separate init image

**Comment by MysticDaedra** [comment]
It turns out the ControlLLLite model I was using isn't compatible with diffusers, which is why I was having those errors.
