### ISSUE TITLE
[Issue]: Animatediff not working

### ISSUE THREAD

**Issue by Flooosee** [vladmandic/automatic#3050]
### Issue Description

Animatediff return an error while executing.

### Version Platform Description

Zluda windows 10
ROCm Unbuntu 22.04

### Relevant log output

```shell
ERROR    AnimateDiff load error:                                
                         adapter="vladmandic/animatediff-v3" 'MotionAdapter'    
                         object has no attribute '_get_signature_keys'
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
pls post full log and write actual workflow to get to that point.

**Comment by Flooosee** [comment]
```
1:54:52-904891 INFO     Applying hypertile: unet=256                           
21:54:52-906476 INFO     AnimateDiff load: adapter="vladmandic/animatediff-v3"  
21:54:55-895854 ERROR    AnimateDiff load error:                                
                         adapter="vladmandic/animatediff-v3" 'MotionAdapter'    
                         object has no attribute '_get_signature_keys'          
21:54:55-900481 DEBUG    Pipeline class change:                                 
                         original=StableDiffusionInpaintPipeline                
                         target=StableDiffusionPipeline device=cuda:0 fn=init   
21:54:55-902663 INFO     LoRA apply: ['add_detail'] patch=0.00 load=0.00        
21:54:55-908592 INFO     Base: class=StableDiffusionPipeline                    
21:54:55-982863 DEBUG    Diffuser pipeline: StableDiffusionPipeline             
                         task=DiffusersTaskType.TEXT_2_IMAGE                    
                         set={'prompt_embeds': torch.Size([1, 77, 768]),        
                         'negative_prompt_embeds': torch.Size([1, 77, 768]),    
                         'guidance_scale': 7, 'generator': device(type='cuda'), 
                         'num_inference_steps': 30, 'eta': 1.0,                 
                         'guidance_rescale': 0.7, 'output_type': 'latent',      
                         'width': 512, 'height': 768, 'parser': 'Full parser'}  
21:54:55-986189 DEBUG    Sampler: sampler="DPM++ 2M"                            
                         config={'num_train_timesteps': 1000, 'beta_start':     
                         0.00085, 'beta_end': 0.012, 'beta_schedule':           
                         'scaled_linear', 'prediction_type': 'epsilon',         
                         'thresholding': False, 'sample_max_value': 1.0,        
                         'algorithm_type': 'sde-dpmsolver++', 'solver_type':    
                         'midpoint', 'lower_order_final': True,                 
                         'use_karras_sigmas': True, 'final_sigmas_type': 'zero'}
Progress  9.72it/s █████████████████████████████████ 100% 30/30 00:03 00:00 Base
```
This is only what we get. For the workflow its basic, chose a model (i've tried many), use a prompt (i also tried with no prompt), chose Adapter in Animatediff tab (I've tried Motion 1.5 V3, V2,... it dosent matter, same result), chose video format (MP4 or GIF, still dosent matter). Chose how many frames (24 in this case), chose duration (3s in this case, for 8fps).
![Screenshot from 2024-04-13 22-00-37](https://github.com/vladmandic/automatic/assets/42011279/768f1fc4-20d9-4cb4-a1ac-a34ab14e17f3)

Result: Generate only one image and gives an error.
Expected result: Generate 24 images, at 8fps, for a 3s duration.

**Comment by Vashnera** [comment]
Did the same and got the same Problem.
its a fresh install on Windows.
Also i dont know where else to ask but is it possible to add my own motion models?

**Comment by vladmandic** [comment]
ah, issue was that animateddiff is not compatible with some attention methods, i've added check before blindly applying them.

@Vashnera can you post an url to a model? i'd like to check it. if it works, i'll add ability to add models manually.
so far each variation needed to be handled differently, so i was reluctant to add support for 3rd party models.

**Comment by Vashnera** [comment]
This https://civitai.com/models/155528/improved-humans-motion-module or this https://civitai.com/models/139237/motion-model-experiments for example but there are alot on civitai i want to test, would be nice if that works, basicly i just look for motion model there.

**Comment by vladmandic** [comment]
@Vashnera unfortunately, diffusers still does not support loading animatediff models from single file, see https://github.com/huggingface/diffusers/issues/6248 for details. as soon as that is implemented, i'll add support in sdnext.

**Comment by AndrewWHales** [comment]
In that link is a comment that has animatediff module and lora being converted to diffusers https://github.com/huggingface/diffusers/issues/6248#issuecomment-1968442506 is that possible to implement?
