### ISSUE TITLE
[Issue]: controlnet preprocessor missing

### ISSUE THREAD

**Issue by Flooosee** [vladmandic/automatic#3051]
### Issue Description

I've noticed that some preprocessor are missing in the controlnet : The inpaints one (inpaint, inpaint+lama, inpaint harmonious,..) and the tiled one. Idk if its a feature request, but because controlnet is built-in i assume it is an oversight.

### Version Platform Description

ROCm , Unbuntu

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
it's a feature request. and every preprocessor 8s a completely different thing that needs to be implemented. so pls convert to feature request and document exactly what you would like - don't just drop names.
