### ISSUE TITLE
[Feature]: Keep sort on save style

### ISSUE THREAD

**Issue by Memeheader** [vladmandic/automatic#3062]
### Feature description

Whenever I save a style, the extra networks tab reloads with the default sort, can you please have it resort in the selected sort at the end of this reload? For example Name: [A-Z] is my preferred sort, but it always resets to Date; [Newest to Oldest]

**Comment by vladmandic** [comment]
valid request, will add to queue

**Comment by vladmandic** [comment]
added in dev branch.

**Comment by Memeheader** [comment]
Thanks for your effort. I noticed a couple things. I looks like clicking refresh will keep the sort, but editing a style prompt and saving will return to default. It also won't save Name: [A-Z] on first click. It will save Name: [Z-A]. You have to cycle through the enumeration once for Name; [A-Z] to save.

**Comment by vladmandic** [comment]
i'll handle those edge cases.

**Comment by vladmandic** [comment]
done.
