### ISSUE TITLE
[Issue]: Control: "Restore" does not restore Hires options

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3066]
### Issue Description

When restoring options via the "Restore" button, the Hires options (sampler, steps, enabled state, etc.) are not restored, but are kept with their defaults (or whatever is defined in ui-config.json). 

## Steps to reproduce

1. Run any generation with Control using Hires enabled
2. Reload the browser
3. Access Control and hit "Restore"
4. Check the Refine accordion

## Expected result

The previously-specified Hires options should be defined

## Actual result

The Refine accordion stays with the default options.

### Version Platform Description

SD.Next from devl 13a9e0a333cb1863fd5084399fb9bd6b0a79e174
Python 3.10
NVIDIA A4000 (16G)
Cloud platform (Paperspace)

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this was actually never added, marked as todo in the code, but somehow fell off the radar. i've just added it.
