### ISSUE TITLE
[Feature]: Control: save conditioning metadata in image

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3070]
### Feature description

It would be nice if Control saved also information on the conditioning used (e.g. ControlNet model, strength, start, end), more than for restore (which would be a plus, but given the sketchy format used by A1111 might be a PITA) to keep the information in case someone wants to do something with the same parameters. Currently there's only a generic "conditioning strength". 

### Version Platform Description

Latest dev as of 2024-04-21

**Comment by vladmandic** [comment]
added control metadata in latest dev
example:
```json
    'Control mode': 'ControlNet',
    'Control model': 'Canny Small XL;Depth Mid XL',
    'Control conditioning': '0.5;0.6',
    'Control start': '0.1;0.2',
    'Control end': '0.7;0.9',
    'Control process': 'Canny;DPT Depth Hybrid',
```
