### ISSUE TITLE
[Issue]: Torch ignoring OpenVINO settings

### ISSUE THREAD

**Issue by StarShine1A** [vladmandic/automatic#3075]
### Issue Description

So I made a fresh install with OpenVINO as backend and tried most of the ways suggested in the documentation to enable GPU support but to no avail, Torch always ends up choosing CPU as device even after entering the device id in the cli as GPU, GPU.0 or even the complete GPU name. I even tried changing the settings in the GUI.

### Version Platform Description

Main version, Windows 11, Firefox

### Relevant log output

```shell
(base) PS C:\Users\star\Desktop\automatic-master> .\webui.ps1 --debug --use-openvino --device-id GPU.0
Using VENV: C:\Users\star\Desktop\automatic-master\venv
18:02:14-527880 INFO     Starting SD.Next
18:02:14-543501 INFO     Logger: file="C:\Users\star\Desktop\automatic-master\sdnext.log" level=DEBUG size=65
                         mode=create
18:02:14-543501 INFO     Python 3.11.5 on Windows
18:02:14-606557 WARNING  Not a git repository, all git operations are disabled
18:02:14-889448 INFO     Version: app=sd.next version=unknown
18:02:14-920695 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 142 Stepping 12, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.11.5
18:02:14-936371 DEBUG    Setting environment tuning
18:02:14-952521 DEBUG    HF cache folder: C:\Users\star\.cache\huggingface\hub
18:02:14-952521 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=True
18:02:14-952521 DEBUG    Torch allowed: cuda=False rocm=False ipex=False diml=False openvino=True
18:02:14-952521 INFO     Using OpenVINO
18:02:14-952521 DEBUG    Installing torch: torch==2.2.0 torchvision==0.17.0 --index-url
                         https://download.pytorch.org/whl/cpu
18:02:14-968041 INFO     Startup: quick launch
18:02:14-983733 INFO     Verifying requirements
18:02:14-999301 WARNING  Package version mismatch: numpy 1.24.3 required 1.26.4
18:02:14-999301 INFO     Installing package: numpy==1.26.4
18:02:15-014932 DEBUG    Running pip: install --upgrade numpy==1.26.4
18:02:35-031055 WARNING  Package version mismatch: typing-extensions 4.5.0 required 4.9.0
18:02:35-031055 INFO     Installing package: typing-extensions==4.9.0
18:02:35-031055 DEBUG    Running pip: install --upgrade typing-extensions==4.9.0
18:02:46-944434 INFO     Verifying packages
18:02:46-944434 DEBUG    Package not found: clip
18:02:46-944434 INFO     Installing package: git+https://github.com/openai/CLIP.git
18:02:46-960067 DEBUG    Running pip: install --upgrade git+https://github.com/openai/CLIP.git
18:03:04-529845 DEBUG    Register paths
18:03:04-547798 ERROR    Required path not found:
                         path=C:\Users\star\Desktop\automatic-master\modules\k-diffusion\k_diffusion\sampling.py
                         item=k_diffusion
18:03:04-561327 INFO     Extensions: disabled=[]
18:03:04-576968 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
18:03:04-576968 INFO     Extensions: enabled=[] extensions
18:03:04-576968 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
18:03:04-576968 DEBUG    Starting module: <module 'webui' from 'C:\\Users\\star\\Desktop\\automatic-master\\webui.py'>
18:03:04-592586 INFO     Command line args: ['--debug', '--use-openvino', '--device-id', 'GPU.0'] device_id=GPU.0
                         use_openvino=True debug=True
18:03:04-608208 DEBUG    Env flags: []
18:03:17-726246 INFO     Load packages: {'torch': '2.2.2+cpu', 'diffusers': '0.27.0', 'gradio': '3.43.2'}
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, tensorflow, openvino
18:03:25-446619 DEBUG    Created default config: config.json
18:03:25-477840 INFO     Engine: backend=Backend.DIFFUSERS compute=openvino device=cpu attention="Scaled-Dot-Product"
                         mode=no_grad
18:03:25-572062 INFO     Device: device=Intel(R) UHD Graphics (iGPU) openvino=2023.3.0
18:03:25-572062 DEBUG    Save: file="config.json" json=14 bytes=655 time=0.094
18:03:25-587751 DEBUG    Migrated styles: file=styles.csv folder=models\styles
18:03:26-451056 DEBUG    Load styles: folder="models\styles" items=288 time=0.85
18:03:26-451056 DEBUG    Read: file="html\reference.json" json=36 bytes=21248 time=0.000
18:03:30-215448 DEBUG    Importing LDM
18:03:30-576741 DEBUG    Entering start sequence
18:03:30-592340 INFO     Create: folder="models\ONNX"
18:03:30-607980 INFO     Create: folder="models\Stable-diffusion"
18:03:30-624066 INFO     Create: folder="models\Diffusers"
18:03:30-624066 INFO     Create: folder="models\VAE"
18:03:30-624066 INFO     Create: folder="models\Lora"
18:03:30-624066 INFO     Create: folder="models\embeddings"
18:03:30-639750 INFO     Create: folder="models\hypernetworks"
18:03:30-639750 INFO     Create: folder="outputs\text"
18:03:30-639750 INFO     Create: folder="outputs\image"
18:03:30-639750 INFO     Create: folder="outputs\control"
18:03:30-655326 INFO     Create: folder="outputs\extras"
18:03:30-655326 INFO     Create: folder="outputs\init-images"
18:03:30-655326 INFO     Create: folder="outputs\grids"
18:03:30-655326 INFO     Create: folder="outputs\save"
18:03:30-670973 INFO     Create: folder="outputs\video"
18:03:30-670973 DEBUG    Initializing
18:03:30-953146 INFO     Available VAEs: path="models\VAE" items=0
18:03:30-953146 INFO     Disabled extensions: ['sd-webui-controlnet']
18:03:30-968796 DEBUG    Scanning diffusers cache: folder=models\Diffusers items=0 time=0.00
18:03:30-984422 INFO     Available models: path="models\Stable-diffusion" items=0 time=0.02
18:03:31-078767 DEBUG    Package not found: basicsr
18:03:31-078767 INFO     Installing package: basicsr
18:03:31-094401 DEBUG    Running pip: install --upgrade basicsr
18:04:00-150901 DEBUG    Package not found: gfpgan
18:04:00-150901 INFO     Installing package: gfpgan
18:04:00-166493 DEBUG    Running pip: install --upgrade gfpgan
18:04:14-529830 DEBUG    Load extensions
18:04:17-041936 INFO     Extension: script='extensions-builtin\Lora\scripts\lora_script.py'
                         [2;36m18:04:16-963385[0m[2;36m [0m[34mINFO    [0m LoRA networks: [33mavailable[0m=[1;36m0[0m
                         [33mfolders[0m=[1;36m2[0m
18:04:17-277391 DEBUG    Extensions init time: 2.75 animatediff.py=0.09 differential_diffusion.py=0.11 example.py=0.40
                         ipadapter.py=0.11 ledits.py=0.06 loopback.py=0.42 mixture_tiling.py=0.16
                         outpainting_mk_2.py=0.09 poor_mans_outpainting.py=0.06 regional_prompting.py=0.05
                         xyz_grid.py=0.05 Lora=0.44
18:04:17-763939 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2640 time=0.016
18:04:17-779539 INFO     Upscaler create: folder="models\RealESRGAN"
18:04:17-795146 DEBUG    Load upscalers: total=28 downloaded=0 user=0 time=0.52 ['None', 'Lanczos', 'Nearest', 'ESRGAN',
                         'LDSR', 'RealESRGAN', 'SCUNet', 'SD', 'SwinIR']
18:04:17-827019 DEBUG    Load styles: folder="models\styles" items=288 time=0.03
18:04:17-999496 DEBUG    Creating UI
18:04:18-015113 INFO     UI theme: name="black-teal" style=Auto base=sdnext.css
18:04:18-046777 DEBUG    UI initialize: txt2img
18:04:18-156683 DEBUG    Extra networks: page='model' items=36 subfolders=2 tab=txt2img
                         folders=['models\\Stable-diffusion', 'models\\Diffusers', 'models\\Reference'] list=0.03
                         thumb=0.01 desc=0.00 info=0.00 workers=4
18:04:18-250883 DEBUG    Extra networks: page='style' items=288 subfolders=1 tab=txt2img folders=['models\\styles',
                         'html'] list=0.05 thumb=0.00 desc=0.00 info=0.00 workers=4
18:04:18-266527 DEBUG    Extra networks: page='embedding' items=0 subfolders=0 tab=txt2img
                         folders=['models\\embeddings'] list=0.02 thumb=0.02 desc=0.00 info=0.00 workers=4
18:04:18-282170 DEBUG    Extra networks: page='hypernetwork' items=0 subfolders=0 tab=txt2img
                         folders=['models\\hypernetworks'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=4
18:04:18-297788 DEBUG    Extra networks: page='vae' items=0 subfolders=0 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=4
18:04:18-297788 DEBUG    Extra networks: page='lora' items=0 subfolders=0 tab=txt2img folders=['models\\Lora',
                         'models\\LyCORIS'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=4
18:04:18-973109 DEBUG    UI initialize: img2img
18:04:23-009551 DEBUG    UI initialize: control models=models\control
18:04:25-772453 ERROR    Reading failed: ui-config.json [Errno 2] No such file or directory: 'ui-config.json'
18:04:26-305845 DEBUG    Themes: builtin=12 gradio=5 huggingface=0
18:04:26-557236 DEBUG    Script: op=after-component total=0.01 scripts=['X/Y/Z Grid:0.01']
18:04:26-871243 INFO     Extension list is empty: refresh required
18:04:26-886866 DEBUG    Extension list: processed=7 installed=7 enabled=7 disabled=0 visible=7 hidden=0
18:04:27-059683 DEBUG    Save: file="ui-config.json" json=0 bytes=2 time=0.000
18:04:27-452230 DEBUG    Root paths: ['C:\\Users\\star\\Desktop\\automatic-master']
18:04:27-643871 INFO     Local URL: http://127.0.0.1:7860/
18:04:27-643871 DEBUG    Gradio functions: registered=1473
18:04:27-655928 DEBUG    FastAPI middleware: ['Middleware', 'Middleware']
18:04:27-671599 DEBUG    Creating API
18:04:28-205258 DEBUG    Scripts setup: ['IP Adapters:0.141', 'AnimateDiff:0.044', 'Prompts from File:0.016', 'X/Y/Z
                         Grid:0.078', 'Face:0.078', 'Differential diffusion:0.031', 'Image-to-Video:0.063',
                         'LEdits++:0.016', 'Loopback:0.016', 'Outpainting:0.016', 'Outpainting alternative:0.016',
                         'Stable Video Diffusion:0.032']
18:04:28-205258 DEBUG    Model metadata: file="metadata.json" no changes
18:04:28-220912 DEBUG    Model requested: fn=<lambda>
18:04:28-220912 WARNING  Cannot generate without a checkpoint
18:04:28-220912 INFO     Set system paths to use existing folders in a different location
18:04:28-236583 INFO       or use --models-dir <path-to-folder> to specify base folder with all models
18:04:28-236583 INFO       or use --ckpt-dir <path-to-folder> to specify folder with sd models
18:04:28-236583 INFO       or use --ckpt <path-to-checkpoint> to force using existing model
18:04:28-252109 INFO     Startup time: 83.16 torch=8.91 onnx=0.08 olive=0.11 gradio=3.53 libraries=12.46 ldm=0.39
                         samplers=0.36 extensions=2.75 face-restore=43.55 upscalers=0.52 networks=0.20 ui-en=4.50
                         ui-txt2img=0.52 ui-img2img=0.13 ui-control=0.75 ui-extras=1.76 ui-models=0.11 ui-settings=1.05
                         ui-extensions=0.13 ui-defaults=0.13 launch=0.58 api=0.55
18:04:28-267745 DEBUG    Save: file="config.json" json=28 bytes=1199 time=0.016
18:05:23-841617 DEBUG    Themes: builtin=12 gradio=5 huggingface=0
18:05:28-988822 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64;
                         rv:124.0) Gecko/20100101 Firefox/124.0
18:05:30-010918 INFO     MOTD: N/A
18:05:35-756208 DEBUG    Scanning diffusers cache: folder=models\Diffusers items=0 time=0.00
18:05:35-831244 INFO     Available models: path="models\Stable-diffusion" items=1 time=0.08
18:05:37-563519 INFO     Select: model="stable-diffusion_v1.5-model"
18:05:37-579144 DEBUG    Load model: existing=False
                         target=C:\Users\star\Desktop\automatic-master\models\Stable-diffusion\stable-diffusion_v1.5-mod
                         el.safetensors info=None
18:05:37-579144 INFO     Torch override dtype: no-half set
18:05:37-579144 INFO     Torch override VAE dtype: no-half set
18:05:37-634793 DEBUG    Desired Torch parameters: dtype=FP32 no-half=True no-half-vae=True upscast=False
18:05:37-634793 INFO     Setting Torch parameters: device=GPU dtype=torch.float32 vae=torch.float32 unet=torch.float32
                         context=no_grad fp16=None bf16=None optimization=Scaled-Dot-Product
18:05:37-642301 DEBUG    Diffusers loading:
                         path="C:\Users\star\Desktop\automatic-master\models\Stable-diffusion\stable-diffusion_v1.5-mode
                         l.safetensors"
18:05:37-642301 INFO     Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline
                         file="C:\Users\star\Desktop\automatic-master\models\Stable-diffusion\stable-diffusion_v1.5-mode
                         l.safetensors" size=7346MB
18:05:42-342611 DEBUG    Setting model: pipeline=StableDiffusionPipeline config={'low_cpu_mem_usage': True,
                         'torch_dtype': torch.float32, 'load_connected_pipeline': True, 'extract_ema': True,
                         'original_config_file': 'configs/v1-inference.yaml', 'use_safetensors': True}
Calculating hash: C:\Users\star\Desktop\automatic-master\models\Stable-diffusion\stable-diffusion_v1.5-model.safetenso… 18:06:00-386349 DEBUG    Server: alive=True jobs=1 requests=112 uptime=160 memory=0.64/7.84 backend=Backend.DIFFUSERS
                         state=idle
Calculating hash: C:\Users\star\Desktop\automatic-master\models\Stable-diffusion\stable-diffusion_v1.5-model.safetenso…
18:06:56-267410 DEBUG    Save: file="cache.json" json=1 bytes=187 time=0.000
18:06:56-283000 DEBUG    Setting model: enable VAE slicing
18:06:56-503295 INFO     Model compile: pipeline=StableDiffusionPipeline mode=default backend=openvino_fx
                         fullgraph=False compile=['Model', 'VAE', 'Upscaler']
18:06:56-550597 DEBUG    Model compile available backends: ['cudagraphs', 'inductor', 'onnxrt', 'openvino_fx',
                         'openxla', 'openxla_eval', 'tvm']
18:06:56-581857 INFO     Model compile: time=0.08
18:06:56-597517 INFO     Load embeddings: loaded=0 skipped=0 time=0.02
18:06:56-910806 DEBUG    GC: collected=2610 device=cpu {'ram': {'used': 0.64, 'total': 7.84}} time=0.31
18:06:56-958262 INFO     Load model: time=79.02 load=79.02 native=512 {'ram': {'used': 0.64, 'total': 7.84}}
18:06:56-974822 DEBUG    Setting changed: sd_model_checkpoint=stable-diffusion_v1.5-model progress=True
18:06:56-974822 DEBUG    Save: file="config.json" json=30 bytes=1360 time=0.000
18:07:25-206547 INFO     Settings: changed=1 ['openvino_devices']
18:07:25-206547 DEBUG    Save: file="config.json" json=30 bytes=1384 time=0.000
18:07:34-394960 INFO     Base: class=StableDiffusionPipeline
18:07:38-261173 DEBUG    Diffuser pipeline: StableDiffusionPipeline task=DiffusersTaskType.TEXT_2_IMAGE
                         set={'prompt_embeds': torch.Size([1, 77, 768]), 'negative_prompt_embeds': torch.Size([1, 77,
                         768]), 'guidance_scale': 6, 'generator': device(type='cpu'), 'num_inference_steps': 20, 'eta':
                         1.0, 'guidance_rescale': 0.7, 'output_type': 'latent', 'width': 512, 'height': 512, 'parser':
                         'Full parser'}
Progress ?it/s                                              0% 0/20 00:00 ? Base18:07:59-644418 DEBUG    Server: alive=True jobs=1 requests=179 uptime=280 memory=1.1/7.84 backend=Backend.DIFFUSERS
                         state=idle
18:08:39-578874 INFO     Exiting
(base) PS C:\Users\star\Desktop\automatic-master>
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by StarShine1A** [comment]
![Screenshot (34)](https://github.com/vladmandic/automatic/assets/167694123/a9625962-17d4-475d-977a-e20ea236442e)
![Screenshot (35)](https://github.com/vladmandic/automatic/assets/167694123/03a9b7fd-1a2f-4949-ab4b-03ee3dc57453)

**Comment by Disty0** [comment]
Torch isn't the backend with OpenVINO, it will always think it is using the CPU even tough execution happens on OpenVINO.
Check  the OpenVINO device to see which device is used for execution.

**Comment by StarShine1A** [comment]
> Torch isn't the backend with OpenVINO, so Torch will always think it is using the CPU even tough execution happens on OpenVINO.
> Check  the OpenVINO device to see which device is used for execution. And it is using the iGPU according to the logs:
> `18:03:25-572062 INFO     Device: device=Intel(R) UHD Graphics (iGPU) openvino=2023.3.0`
> 
> Torch data types will be ignored as well after the OpenVINO conversion is completed. OpenVINO will use FP16.
> 
> Also `--device-id GPU.0` is invalid. `GPU.0` is not a number.
> Either use `--device-id 0` or select which device to use from settings, and not both methods at the same time.

Using --device-id 0 still doesn't make it to use the GPU. Idk i dont get it, OpenVINO is clearly stating the use of GPU and CPU but torch got device=cpu. Which is proven by literally not change in GPU use on my task manager. I did state --use-openvino so it feels strange it isnt being used as backend.

**Comment by StarShine1A** [comment]
Hmm I see, but then I still don't get why the GPU is left untouched... like no usage whatsoever be it in terms of execution or ram in the Task Manager, suggesting no usage of it

**Comment by Disty0** [comment]
Conversion to OpenVINO will happen on the CPU first, then it will send the model to OpenVINO.
And the first run will take time with OpenVINO because of this.

**Comment by StarShine1A** [comment]
Surprisingly, It did that indeed. Although now it just sits idle with 1.9/4GB of shared gpu memory for some reasons.

**Comment by StarShine1A** [comment]
`(base) PS C:\Users\star\Desktop\automatic-master> .\webui.ps1 --debug --use-openvino --device-id 0
Using VENV: C:\Users\star\Desktop\automatic-master\venv
20:32:23-552347 INFO     Starting SD.Next
20:32:23-552347 INFO     Logger: file="C:\Users\star\Desktop\automatic-master\sdnext.log" level=DEBUG size=65
                         mode=create
20:32:23-561859 INFO     Python 3.11.5 on Windows
20:32:23-577495 WARNING  Not a git repository, all git operations are disabled
20:32:23-718534 INFO     Version: app=sd.next version=unknown
20:32:23-734157 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 142 Stepping 12, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.11.5
20:32:23-734157 DEBUG    Setting environment tuning
20:32:23-734157 DEBUG    HF cache folder: C:\Users\star\.cache\huggingface\hub
20:32:23-734157 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=True
20:32:23-749783 DEBUG    Torch allowed: cuda=False rocm=False ipex=False diml=False openvino=True
20:32:23-752795 INFO     Using OpenVINO
20:32:23-752795 DEBUG    Installing torch: torch==2.2.0 torchvision==0.17.0 --index-url
                         https://download.pytorch.org/whl/cpu
20:32:23-752795 INFO     Startup: quick launch
20:32:23-752795 INFO     Verifying requirements
20:32:23-781450 INFO     Verifying packages
20:32:23-781450 DEBUG    Register paths
20:32:23-797069 ERROR    Required path not found:
                         path=C:\Users\star\Desktop\automatic-master\modules\k-diffusion\k_diffusion\sampling.py
                         item=k_diffusion
20:32:23-797069 INFO     Extensions: disabled=[]
20:32:23-797069 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
20:32:23-797069 INFO     Extensions: enabled=[] extensions
20:32:23-812694 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
20:32:23-812694 DEBUG    Starting module: <module 'webui' from 'C:\\Users\\star\\Desktop\\automatic-master\\webui.py'>
20:32:23-812694 INFO     Command line args: ['--debug', '--use-openvino', '--device-id', '0'] device_id=0
                         use_openvino=True debug=True
20:32:23-812694 DEBUG    Env flags: []
20:32:35-906707 INFO     Load packages: {'torch': '2.2.2+cpu', 'diffusers': '0.27.0', 'gradio': '3.43.2'}
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, tensorflow, openvino
20:32:39-216433 DEBUG    Read: file="config.json" json=30 bytes=1437 time=0.000
20:32:39-232059 INFO     Engine: backend=Backend.DIFFUSERS compute=openvino device=cpu attention="Scaled-Dot-Product"
                         mode=no_grad
20:32:39-247684 INFO     Device: device=OpenVINO HETERO:GPU,CPU openvino=2023.3.0
20:32:39-247684 DEBUG    Read: file="html\reference.json" json=36 bytes=21248 time=0.000
20:32:40-411615 DEBUG    Importing LDM
20:32:40-442865 DEBUG    Entering start sequence
20:32:40-442865 DEBUG    Initializing
20:32:40-505764 INFO     Available VAEs: path="models\VAE" items=0
20:32:40-505764 INFO     Disabled extensions: ['sd-webui-controlnet']
20:32:40-505764 DEBUG    Scanning diffusers cache: folder=models\Diffusers items=0 time=0.00
20:32:40-505764 DEBUG    Read: file="cache.json" json=1 bytes=194 time=0.000
20:32:40-521393 DEBUG    Read: file="metadata.json" json=1 bytes=123 time=0.000
20:32:40-521393 INFO     Available models: path="models\Stable-diffusion" items=1 time=0.02
20:32:40-678034 DEBUG    Load extensions
20:32:40-897995 INFO     Extension: script='extensions-builtin\Lora\scripts\lora_script.py'
                         [2;36m20:32:40-886484[0m[2;36m [0m[34mINFO    [0m LoRA networks: [33mavailable[0m=[1;36m0[0m
                         [33mfolders[0m=[1;36m2[0m
20:32:40-929257 DEBUG    Extensions init time: 0.25 example.py=0.06
20:32:40-976132 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2640 time=0.000
20:32:40-986651 DEBUG    Load upscalers: total=28 downloaded=0 user=0 time=0.06 ['None', 'Lanczos', 'Nearest', 'ESRGAN',
                         'LDSR', 'RealESRGAN', 'SCUNet', 'SD', 'SwinIR']
20:32:41-007800 DEBUG    Load styles: folder="models\styles" items=288 time=0.02
20:32:41-023421 DEBUG    Creating UI
20:32:41-023421 INFO     UI theme: name="black-teal" style=Auto base=sdnext.css
20:32:41-039050 DEBUG    UI initialize: txt2img
20:32:41-101955 DEBUG    Extra networks: page='model' items=37 subfolders=2 tab=txt2img
                         folders=['models\\Stable-diffusion', 'models\\Diffusers', 'models\\Reference'] list=0.03
                         thumb=0.02 desc=0.00 info=0.00 workers=4
20:32:41-133222 DEBUG    Extra networks: page='style' items=288 subfolders=1 tab=txt2img folders=['models\\styles',
                         'html'] list=0.03 thumb=0.00 desc=0.00 info=0.00 workers=4
20:32:41-148870 DEBUG    Extra networks: page='embedding' items=0 subfolders=0 tab=txt2img
                         folders=['models\\embeddings'] list=0.02 thumb=0.00 desc=0.00 info=0.00 workers=4
20:32:41-148870 DEBUG    Extra networks: page='hypernetwork' items=0 subfolders=0 tab=txt2img
                         folders=['models\\hypernetworks'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=4
20:32:41-148870 DEBUG    Extra networks: page='vae' items=0 subfolders=0 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=4
20:32:41-148870 DEBUG    Extra networks: page='lora' items=0 subfolders=0 tab=txt2img folders=['models\\Lora',
                         'models\\LyCORIS'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=4
20:32:41-415772 DEBUG    UI initialize: img2img
20:32:41-760216 DEBUG    UI initialize: control models=models\control
20:32:42-544726 DEBUG    Script: op=before-component total=0.02 scripts=['Differential diffusion:0.02']
20:32:42-623259 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.016
20:32:42-811558 DEBUG    Themes: builtin=12 gradio=5 huggingface=0
20:32:42-889687 DEBUG    Script: op=after-component total=0.02 scripts=['BLIP Diffusion:0.02']
20:32:42-952599 INFO     Extension list is empty: refresh required
20:32:42-952599 DEBUG    Extension list: processed=7 installed=7 enabled=7 disabled=0 visible=7 hidden=0
20:32:43-109646 DEBUG    Root paths: ['C:\\Users\\star\\Desktop\\automatic-master']
20:32:43-234751 INFO     Local URL: http://127.0.0.1:7860/
20:32:43-234751 DEBUG    Gradio functions: registered=1473
20:32:43-234751 DEBUG    FastAPI middleware: ['Middleware', 'Middleware']
20:32:43-250379 DEBUG    Creating API
20:32:43-407453 DEBUG    Scripts setup: ['IP Adapters:0.031', 'AnimateDiff:0.026', 'DemoFusion:0.016', 'Prompts from
                         File:0.031', 'X/Y/Z Grid:0.016', 'Face:0.031', 'Differential diffusion:0.007']
20:32:43-407453 DEBUG    Model metadata: file="metadata.json" no changes
20:32:43-407453 DEBUG    Model requested: fn=<lambda>
20:32:43-423088 INFO     Select: model="stable-diffusion_v1.5-model [1a189f0be6]"
20:32:43-423088 DEBUG    Load model: existing=False
                         target=C:\Users\star\Desktop\automatic-master\models\Stable-diffusion\stable-diffusion_v1.5-mod
                         el.safetensors info=None
20:32:43-423088 INFO     Torch override dtype: no-half set
20:32:43-423088 INFO     Torch override VAE dtype: no-half set
20:32:43-423088 DEBUG    Desired Torch parameters: dtype=FP32 no-half=True no-half-vae=True upscast=False
20:32:43-423088 INFO     Setting Torch parameters: device=HETERO:GPU,CPU dtype=torch.float32 vae=torch.float32
                         unet=torch.float32 context=no_grad fp16=None bf16=None optimization=Scaled-Dot-Product
20:32:43-438719 DEBUG    Diffusers loading:
                         path="C:\Users\star\Desktop\automatic-master\models\Stable-diffusion\stable-diffusion_v1.5-mode
                         l.safetensors"
20:32:43-438719 INFO     Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline
                         file="C:\Users\star\Desktop\automatic-master\models\Stable-diffusion\stable-diffusion_v1.5-mode
                         l.safetensors" size=7346MB
20:32:46-075028 DEBUG    Setting model: pipeline=StableDiffusionPipeline config={'low_cpu_mem_usage': True,
                         'torch_dtype': torch.float32, 'load_connected_pipeline': True, 'extract_ema': True,
                         'original_config_file': 'configs/v1-inference.yaml', 'use_safetensors': True}
20:32:46-075028 DEBUG    Setting model: enable VAE slicing
20:32:46-122299 INFO     Model compile: pipeline=StableDiffusionPipeline mode=default backend=openvino_fx
                         fullgraph=False compile=['Model', 'VAE', 'Upscaler']
20:32:46-153551 DEBUG    Model compile available backends: ['cudagraphs', 'inductor', 'onnxrt', 'openvino_fx',
                         'openxla', 'openxla_eval', 'tvm']
20:32:46-169177 INFO     Model compile: time=0.05
20:32:46-184802 INFO     Load embeddings: loaded=0 skipped=0 time=0.00
20:32:46-388872 DEBUG    GC: collected=19 device=cpu {'ram': {'used': 0.64, 'total': 7.84}} time=0.2
20:32:46-388872 INFO     Load model: time=2.76 load=2.76 native=512 {'ram': {'used': 0.64, 'total': 7.84}}
20:32:46-398390 INFO     Startup time: 22.49 torch=9.80 onnx=0.06 olive=0.11 gradio=2.02 libraries=4.50 samplers=0.06
                         extensions=0.25 face-restore=0.16 upscalers=0.06 ui-en=0.48 ui-txt2img=0.22 ui-img2img=0.09
                         ui-control=0.31 ui-extras=0.41 ui-settings=0.34 ui-defaults=0.06 launch=0.19 api=0.17
                         checkpoint=2.99
20:32:46-404906 DEBUG    Save: file="config.json" json=30 bytes=1384 time=0.007
20:32:50-893764 INFO     MOTD: N/A
20:32:54-220447 DEBUG    Themes: builtin=12 gradio=5 huggingface=0
20:32:55-130562 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64;
                         rv:124.0) Gecko/20100101 Firefox/124.0
20:33:06-402994 INFO     Base: class=StableDiffusionPipeline
20:33:08-459604 DEBUG    Diffuser pipeline: StableDiffusionPipeline task=DiffusersTaskType.TEXT_2_IMAGE
                         set={'prompt_embeds': torch.Size([1, 77, 768]), 'negative_prompt_embeds': torch.Size([1, 77,
                         768]), 'guidance_scale': 6, 'generator': device(type='cpu'), 'num_inference_steps': 20, 'eta':
                         1.0, 'guidance_rescale': 0.7, 'output_type': 'latent', 'width': 512, 'height': 512, 'parser':
                         'Full parser'}
Progress ?it/s                                              0% 0/20 00:00 ? Base20:33:59-619760 DEBUG    Server: alive=True jobs=1 requests=73 uptime=82

                         memory=3.21/7.84 backend=Backend.DIFFUSERS
                         state=idle
20:35:59-737198 DEBUG    Server: alive=True jobs=1 requests=215 uptime=203
                         memory=3.22/7.84 backend=Backend.DIFFUSERS
                         state=idle`

**Comment by Disty0** [comment]
Closing as Torch device is not an issue.
