### ISSUE TITLE
[Issue]: Control: type mismatch when saving parameters causes an exception

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3077]
### Issue Description

When doing something similar as #3067, I instantly hit an exception when I hit "Generate":

```
03:59:17-838769 ERROR    Control exception: 'float' object is not iterable      
03:59:17-839800 ERROR    Control: TypeError                                     
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /notebooks/automatic/modules/ui_control.py:56 in generate_click              │
│                                                                              │
│    55 │   │   try:                                                           │
│ ❱  56 │   │   │   for results in control_run(units, helpers.input_source, he │
│    57 │   │   │   │   progress.record_results(job_id, results)               │
│                                                                              │
│ /notebooks/automatic/modules/control/run.py:240 in control_run               │
│                                                                              │
│   239 │   │   p.extra_generation_params["Control model"] = ';'.join([(m.mode │
│ ❱ 240 │   │   p.extra_generation_params["Control conditioning"] = ';'.join([ │
│   241 │   │   p.extra_generation_params['Control start'] = ';'.join([str(c)  │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: 'float' object is not iterable
```

The only difference from the workflow of the previous issue is that I loaded a pre-existing image (made before the latest parameter changes). 

### Version Platform Description

03:43:50-094867 INFO     Starting SD.Next                                       
03:43:50-142631 INFO     Logger: file="/notebooks/automatic/sdnext.log"         
                         level=INFO size=4048003 mode=append                    
03:43:50-144085 INFO     Python 3.10.10 on Linux                                
03:43:50-188470 INFO     Version: app=sd.next updated=2024-04-23 hash=a7408bca  
                         branch=dev                                             
                         url=https://github.com/vladmandic/automatic/tree/dev   
03:43:50-562172 INFO     Updating main repository                               
03:43:51-509026 INFO     Upgraded to version: a7408bca Tue Apr 23 20:33:16 2024 
                         -0400                                                  
03:43:51-515428 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux          
                         release=5.19.0-45-generic python=3.10.10   

### Relevant log output

```shell
03:59:17-838769 ERROR    Control exception: 'float' object is not iterable      
03:59:17-839800 ERROR    Control: TypeError                                     
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /notebooks/automatic/modules/ui_control.py:56 in generate_click              │
│                                                                              │
│    55 │   │   try:                                                           │
│ ❱  56 │   │   │   for results in control_run(units, helpers.input_source, he │
│    57 │   │   │   │   progress.record_results(job_id, results)               │
│                                                                              │
│ /notebooks/automatic/modules/control/run.py:240 in control_run               │
│                                                                              │
│   239 │   │   p.extra_generation_params["Control model"] = ';'.join([(m.mode │
│ ❱ 240 │   │   p.extra_generation_params["Control conditioning"] = ';'.join([ │
│   241 │   │   p.extra_generation_params['Control start'] = ';'.join([str(c)  │
╰──────────────────────────────────────────────────────────────────────────────╯
TypeError: 'float' object is not iterable
```

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
