### ISSUE TITLE
[Issue]: Repositories Folder Missing

### ISSUE THREAD

**Issue by ailorum** [vladmandic/automatic#3079]
### Issue Description

I´ve tried to install classic SD on my pc and it didn´t work, then I dicovered SDnext its a little easier, so I tried it.

the problem is that i´ve aldready downloades everything, but the core folder has missing the repositories folder. I tried to clone again the source and it throw back the same error
´´´ERROR: file not found User/bla/bla/automatic/reporitories/ no file named idm¨¨¨
´´´ERROR: file not found User/bla/bla/automatic/reporitories/ not found repositories¨¨
just like that whit every single document in that folder.

is there a way to get only the repositories folder? it doesn´t work for me to clone it from the web source, I dont know whats happenning, I tried to reinstall multile times and it stills missing that folder

### Version Platform Description

windows 10, SDNEXT, 
Python 3.10.6
Version: abd7d160 Sat Jun 10 07:37:42 2023 -0400
nVidia CUDA toolkit detected
Torch 2.1.0.dev20230519+cu121
Torch backend: nVidia CUDA 12.1 cuDNN 8801
Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28

### URL link of the extension

https://github.com/vladmandic/automatic/tree/de267390905335d353deab3e9ac2031432f4d305/repositories

### URL link of the issue reported in the extension repository

https://github.com/vladmandic/automatic/tree/de267390905335d353deab3e9ac2031432f4d305/repositories

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by ailorum** [comment]
UPDATE: i tried reinstalling again and now i Cant even clone, it trows me a message saying its aldready cloned and obviously it aint true

**Comment by ailorum** [comment]
UPDATE: i tried reinstalling again and now i Cant even clone, it trows me a message saying its aldready cloned and obviously it aint true

**Comment by ailorum** [comment]
UPDATE: i tried reinstalling again and now i Cant even clone, it trows me a message saying its aldready cloned and obviously it aint true

**Comment by vladmandic** [comment]
repositories folder is automatically populated by installer on first run - and it does thar by running clone of required sub-repos.

all this sounds like you have some issues with git clone command itself.

can you start from scratch, run git clone of sdnext and then start it up - and post each command as you execute it.

**Comment by ailorum** [comment]
> repositories folder is automatically populated by installer on first run - and it does thar by running clone of required sub-repos.
> 
> all this sounds like you have some issues with git clone command itself.
> 
> can you start from scratch, run git clone of sdnext and then start it up - and post each command as you execute it.

**Comment by vladmandic** [comment]
any updates?

**Comment by vladmandic** [comment]
closing for now as no update provided, will reopen when information is available.
