### ISSUE TITLE
[Issue]: --no-half and --no-half-vae arguments unrecognized

### ISSUE THREAD

**Issue by sullenfish** [vladmandic/automatic#308]
### Issue Description

Launching `webui.sh` with `--no-half` or `--no-half-vae` fails with error:

`launch.py: error: unrecognized arguments: --no-half`
 -or-
`launch.py: error: unrecognized arguments: --no-half-vae`

This can't be avoided in environments where CUDA is unavailable because `check_torch()` adds them in.

### Version Platform Description

Version: [0e71441](https://github.com/vladmandic/automatic/commit/0e7144186d49601356cf890e2dabc2d7f5930801)
Hardware: MacBook Pro M1 Max
OS: macOS Ventura 13.3

**Comment by Shadowghost** [comment]
You can disable them in the settings in the webinterface.

**Comment by sullenfish** [comment]
It never completes the launch.

**Comment by vladmandic** [comment]
fixed, sorry about bad commit.
