### ISSUE TITLE
[Issue]: Bad outputs on RX 5700 using ZLuda

### ISSUE THREAD

**Issue by NemeczeK101** [vladmandic/automatic#3082]
### Issue Description

So to put it simply, the images come out deep-fried is how I would put it, not sure why, I tried tweaking some settings, but nothing did it for me, setting different models, vae models, and nothing changes, I followed all the SD.Next wiki covering ZLuda closely. I attached an example of an image generated on my end.

![00040-picxReal_10-analog film photo photo of a beautiful woman](https://github.com/vladmandic/automatic/assets/96395475/96a43343-0e55-4777-818e-07e9bd5b8afb)

If you need more information please let me know, thanks in advance.

### Version Platform Description

OS: Windows 11
Browser: Mozilla Firefox
ZLuda: version 3.8 prerelease 2 (Tried newest versions to see if it was ZLuda)
GPU: RX 5700
CPU: i7 8700K

### Relevant log output

[sdnext.log](https://github.com/vladmandic/automatic/files/15112259/sdnext.log)

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
as per notes, anything ZLUDA related should be communicated via Discord (see notes in ZLUDA wiki).
