### ISSUE TITLE
[Issue]: Control: Using a Canny image and a depth image raises an exception on generate

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3083]
### Issue Description

When loading both a depth image and a Canny image, OpenCV raises an error, my guess when trying to mix them together in the preview. 

## Steps to reproduce

1. Add a depth image as control image (see end of the post)
2. Activate two CN units, one for depth, one for Canny, both with None preprocessors
3. Add a lineart image to the Canny unit and activate it
4. Insert prompt, set parameters
5. Hit generate

## Expected results

Generation starts and an image is produced

## Actual results

An exception is raised in openCV (see below for log)

## Example images

![Depth image](https://github.com/vladmandic/automatic/assets/25192/a24a9505-7a31-4ed9-a24a-3f74987769da)

![testcanny2](https://github.com/vladmandic/automatic/assets/25192/be76759f-d64f-40c4-b462-c711e95c8125)

### Version Platform Description

20:21:49-928348 INFO     Starting SD.Next                                       
20:21:49-931438 INFO     Logger: file="/notebooks/automatic/sdnext.log"         
                         level=INFO size=6446096 mode=append                    
20:21:49-932560 INFO     Python 3.10.10 on Linux                                
20:21:49-989142 INFO     Version: app=sd.next updated=2024-04-25 hash=01373316  
                         branch=dev                                             
                         url=https://github.com/vladmandic/automatic/tree/dev   
20:21:50-175819 INFO     Updating main repository                               
20:21:52-566003 INFO     Upgraded to version: a38d755e Thu Apr 25 16:18:51 2024 
                         -0400                                                  
20:21:52-573973 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux          
                         release=5.19.0-45-generic python=3.10.10    

### Relevant log output

```shell
diffusion_pytorch_model.safetensors: 100%|█| 1.09G/1.09G [00:32<00:00, 33.5MB/s]
20:34:20-922793 ERROR    Control pipeline failed: type=controlnet units=2       
                         error=OpenCV(4.9.0)                                    
                         /io/opencv/modules/core/src/arithm.cpp:647: error:     
                         (-209:Sizes of input arguments do not match) The       
                         operation is neither 'array op array' (where arrays    
                         have the same size and the same number of channels),   
                         nor 'array op scalar', nor 'scalar op array' in        
                         function 'arithm_op'                                   
                                                                                
20:34:20-925412 ERROR    Control: error                                         
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /notebooks/automatic/modules/control/run.py:448 in control_run               │
│                                                                              │
│   447 │   │   │   │   │   │   │   processed_image = [np.array(i) for i in pr │
│ ❱ 448 │   │   │   │   │   │   │   processed_image = util.blend(processed_ima │
│   449 │   │   │   │   │   │   │   processed_image = Image.fromarray(processe │
│                                                                              │
│ /notebooks/automatic/modules/control/util.py:153 in blend                    │
│                                                                              │
│   152 │   │   │   img = cv2.resize(img, (y.shape[1], y.shape[0]), interpolat │
│ ❱ 153 │   │   y = cv2.add(y, img.astype(np.float32))                         │
│   154 │   y = y.clip(0, 255).astype(np.uint8)                                │
╰──────────────────────────────────────────────────────────────────────────────╯
error: OpenCV(4.9.0) /io/opencv/modules/core/src/arithm.cpp:647: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'
```

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by lbeltrame** [comment]
The error occurs also with preview disabled, so I guess it's something else.

**Comment by vladmandic** [comment]
i know what it is, will take care of it

**Comment by vladmandic** [comment]
i've fixed blending and separated preview image (blended) vs actual separate images sent to multiple control units, but this requires a bit more testing - too many different workflows/scenarios for me to test - can you?
- single or multiple controlnets with single input image and using preprocessors
- single or multiple controlnets with no input image and using override image per unit with or without preprocessor

**Comment by lbeltrame** [comment]
Sorry, I missed this. Will experiment tomorrow, I have plenty of images I can test this with.

**Comment by lbeltrame** [comment]
> single or multiple controlnets with no input image and using override image per unit with or without preprocessor

Nothing gets applied at the moment. Tested with one depth image and one canny image (the same as this post) without loading a control image (aka, txt2img + 2 control images, without preprocessors, similar workflow as the old ControlNet extension), and the resulting image is completely unconditioned. There needs to be at least one control image as input to work.

**Comment by vladmandic** [comment]
closing as original issue is resolved.
