### ISSUE TITLE
[Issue]: Search results in the extensions tab result in a wrong "target" value which causes the link to be opened in the same tab.

### ISSUE THREAD

**Issue by TheSeventhCode** [vladmandic/automatic#3088]
### Issue Description

Something very minor, but which has been bugging me somewhat over the past few days:
Usually, all the listed extensions in the _Extensions_ tab have their target set to `_blank` which of course results those links to be opened in a new tab.
The problem arises, when _searching_ for something, because then the value gets a bit messed up and the `title` value is set to `title="target=&quot;_blank&quot;"`

Which of course, then fails to set the `target`  value correctly, resulting in opening the link in the same tab.

### Version Platform Description

- Running on Linux
- commit de267390905335d353deab3e9ac2031432f4d305
- Brave browser

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by TheSeventhCode** [comment]
Probably a small fix, but as I have no experience at all with Gradio or Python web services in general, I've opened an issue instead of a PR.

**Comment by vladmandic** [comment]
just fixed in latest dev branch, will be merged to master in the next release.
