### ISSUE TITLE
[Issue]: txt2img sampler list does not obey settings after ca7aa42cdbce0de5d341a0a6ea22eb6750bdb728

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3089]
### Issue Description

ca7aa42cdbce0de5d341a0a6ea22eb6750bdb728 changed a bit how the txt2img sampler list is populated. This currently does

https://github.com/vladmandic/automatic/blob/7e1c5a2e115af41a19a4553cf5ec92ccb37e87d1/modules/ui_txt2img.py#L42

However, when called with `None`, `create_sampler_and_steps_selection()` will populate the list with **all** available samplers:

https://github.com/vladmandic/automatic/blob/ca7aa42cdbce0de5d341a0a6ea22eb6750bdb728/modules/ui_sections.py#L202

Therefore before populating, `sd_samplers.set_samplers()` must be called (the old code did so before populating the list). 

If this is not done, the config and the UI are not in sync, and it is impossible to set a sampler for txt2img. Other modules such as Control already call `sd_samplers.set_samplers()` and pass the list explicitly, so they aren't affected.

### Version Platform Description

12:26:47-302549 INFO     Starting SD.Next                                       
12:26:47-306564 INFO     Logger: file="/notebooks/automatic/sdnext.log"         
                         level=INFO size=9938812 mode=append                    
12:26:47-307827 INFO     Python 3.10.10 on Linux                                
12:26:47-308624 INFO     Skipping GIT operations                                
12:26:47-348543 INFO     Version: app=sd.next updated=2024-04-28 hash=7e1c5a2e  
                         branch=dev                                             
                         url=https://github.com/vladmandic/automatic/tree/dev   
12:26:47-353984 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux          
                         release=5.19.0-45-generic python=3.10.10 

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
thnx - should be fixed now.
