### ISSUE TITLE
[Issue]: Control restore button copies wrong image size params

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3094]
### Issue Description

When you generate an image in the IMAGE tab and then click the RESTORE button to fill the fields with the values of that generated image, it loads the FINAL image size into height/weight not the initial one. So if you had 512*768 with upscale ratio x2, width and height are filled with 1024 and 2352. So next image after will be 2048x4704.

### Version Platform Description

WSL2, Chrome, SD.next version: 9ff507d9

### Relevant log output

```shell
N/A
```

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
valid, just not sure how to handle it as metadata normally contains only width/height and control has width/height before and after and i need to keep metadata compatibile between images created with txt2img/img2img and control.

i'll keep issue open for now.

**Comment by vladmandic** [comment]
i've added full before/after metadata, this is now resolved.
