### ISSUE TITLE
[Issue]:  When enabled built-in regional prompting live preview do not gets update till the end.

### ISSUE THREAD

**Issue by Bercraft** [vladmandic/automatic#3095]
### Issue Description

Normally when generating the live preview works fine with any of the 
Simple
Approximate
TAESD
Full VAE
modes, whent he regional prompting script is enabled the live preview stops working, updating only at the end of the generation.
there are no error logs.

### Version Platform Description

Windows 10 workstation, radon pro w5700, zluda,master branch.

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
sorry, but not every model supports live preview.
or to be precise, each model needs its live preview handler. right now there are no plans to add one to regional prompting.
