### ISSUE TITLE
[Feature]: automatically put generated images into folders with current date

### ISSUE THREAD

**Issue by AndrewRainfall** [vladmandic/automatic#3097]
### Feature description

I suggest to add automatic creation of folders for generated images, like it happens in original Stable Diffusion.

I didn't find a way to enable it, if this already exist.

Example how it looks in original Stable Diffusion:
![image](https://github.com/vladmandic/automatic/assets/160651191/3eaf2f5d-a645-458b-b9de-61caa5b032f8)

**Comment by brknsoul** [comment]
Already exists and is plain as day;
![image](https://github.com/vladmandic/automatic/assets/1969381/a9515ace-221a-4ea0-9ef2-2bda3089eac6)

**Comment by vladmandic** [comment]
closing as already exists.
