### ISSUE TITLE
[Issue]: dev branch/old ui: typo, text consistency and a missing mouseover

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3099]
### Issue Description

If it matters: old UI

- Process / Visual Query / Question placeholder typo: "Descirbe..."

- Process tab: "Rembg" - can we have this in full text/more understandable? Rename it to "Remove Background" or at least "RemBG"?

- everywhere texts are "Uppercase lowercase lowercase...", almost only for image uploads this is all uppercase: "Drop Image Here" and "Click top Upload". I suggest to make "Image here" and "Upload" to make lowercase for consistency. Another one is "No Rows To Show" in the Agent Scheduler.

- Full quality / Face restore / Tiling / HiDiffusion
This line has a mouseover text for each except the "HiDiffusion" one which actually is the only one that would need one.

- "=>Text/=>Image/=>Inpaint/=>Process" is capitalized everywhere except in Agent Scheduler / Task History.

### Version Platform Description

dd58b9da, WSL-2, Chrome

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i've updated remb label and typo and added hint for hidiffusion.
for capitalization, need exact example as quick code search does not show much
for agent scheduler items, it should be reported to their github, not much i can do from my side.

**Comment by Tillerz** [comment]
Capitalization example is Image tab, the text in the center of the drop zone:

```html
<div data-testid="image" class="image-container svelte-p3y7hu" style="position: relative;">
  <div class="svelte-116rqfv center boundedheight flex">
    <div class="wrap svelte-1ck5uk8">Drop Image Here
      <span class="or svelte-1ck5uk8">- or -</span> Click to Upload
    </div>
    <input type="file" accept="image/*" class="svelte-116rqfv">
...
  </div>
</div>
```

**Comment by Tillerz** [comment]
The HiDiffusion mouseover text is not showing, I thing it doesn't know where to add it. The `data-hint` entry is missing for it.

```html
<div id="txt2img_hidiffusion" class="block gradio-checkbox svelte-90oupt padded" style="border-style: solid; overflow: visible; min-width: min(160px, 100%); border-width: var(--block-border-width);">
<div class="wrap default full svelte-119qaqt hide" style="position: absolute; padding: 0px;"></div>
  <label class="svelte-1ojmf70"><input type="checkbox" name="test" data-testid="checkbox" class="svelte-1ojmf70">
  <span class="ml-2 svelte-1ojmf70">HiDiffusion</span>
  </label>
</div>```

**Comment by vladmandic** [comment]
i cannot reproduce this, onmouseover hint for hidiffusion appears just fine in both standard and modern ui.
make sure you clear your browser cache.
