### ISSUE TITLE
[Feature]: Custom models path

### ISSUE THREAD

**Issue by ljleb** [vladmandic/automatic#310]
### Feature description

Add an option to change the entire models path, not just the VAE dir or the ckpts dir or or the loras dir. Some extensions put models under `modules.paths.models_path` which defaults to `webui/models`, but I want to put these in a different drive.

Related: #82. Was marked as won't fix, however here it is a different situation. I just want a way to set the `models_path` variable before loading any extensions, ideally from the command line using a `--models-dir <path>` flag.

### Version Platform Description

- commit: 752b91d38ae3fd52a7223dd8f5b73225a300f060
- os: Windows 10
- browser: Firefox

**Comment by ljleb** [comment]
I know I can use symlinks for this for now. I don't want to have to repeat this step every time I reinstall the repo, as of right now I think it would be a better solution to have a flag.

**Comment by ljleb** [comment]
I am aware of the `--data-dir` flag, but this flag moves too many files. I only need to move the models, not the entire webui config.

**Comment by ljleb** [comment]
Thanks a lot!

**Comment by OberstK** [comment]
@vladmandic I tried this and I still get "error: unrecognized arguments: --models-dir=" on the latest commit of master. Is this not intended to be a argument of the launch.py ?

**Comment by vladmandic** [comment]
my bad, argparse happened before arg was added. fixed, will publish in ~1h.
