### ISSUE TITLE
[Issue]: Upgrade scripts for python 3.12

### ISSUE THREAD

**Issue by sekurilabs** [vladmandic/automatic#3104]
### Issue Description

pkg_resource have been deprecated in python 3.12, migration to importlib.resources is recommended.

More info:
```
pydoc3 pkg_resources
Help on package pkg_resources:

NAME
    pkg_resources

DESCRIPTION
    Package resource API
    --------------------

[...8<...snip...8<...]

    This module is deprecated. Users are directed to
    importlib.resources <https://docs.python.org/3/library/importlib.resources.html>_
    and
    importlib.metadata <https://docs.python.org/3/library/importlib.metadata.html>_
    instead.
```
It would be great if python version detection can be made and appropriate modules are used based on that version.

### Version Platform Description

Python 3.12, Ubuntu 24.04.

### Backend

Original

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Disty0** [comment]
You have to wipe the venv after changing Python versions.

https://github.com/vladmandic/automatic/wiki/Python312

**Comment by vladmandic** [comment]
as far as i know installer works fine for python 3.12, can you provide evidence of an issue (and definitely wipe venv when changing python).

**Comment by sekurilabs** [comment]
My apologies you are right of course, webui.sh now launches although I get this error:

```
07:12:04-797381 INFO     Python 3.12.3 on Linux                                                                                        
07:12:04-797750 ERROR    Incompatible Python version: 3.12.3 required 3.[9, 10, 11]   
```

Any advice @vladmandic ?

**Comment by sekurilabs** [comment]
Thanks!
