### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ishanjaiswal2610** [vladmandic/automatic#3106]
20:04:50-148260 INFO     AMD ROCm toolkit detected
20:04:50-907859 WARNING  HIP SDK is detected, but no Torch release for Windows available
20:04:50-908860 INFO     For ZLUDA support specify '--use-zluda'
20:04:50-909860 INFO     Using CPU-only torch
20:04:50-911859 INFO     Installing package: torch torchvision
20:05:41-038704 INFO     Installing package: onnxruntime
20:05:45-404341 INFO     Extensions: disabled=[]
20:05:45-405342 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
20:05:45-410340 INFO     Extensions: enabled=[] extensions
20:05:45-411342 INFO     Startup: standard
20:05:45-412340 INFO     Verifying requirements
20:05:45-414342 INFO     Installing package: patch-ng
20:05:48-561923 INFO     Installing package: anyio
20:05:50-195158 INFO     Installing package: addict
20:05:51-709875 INFO     Installing package: astunparse
20:05:53-412666 INFO     Installing package: blendmodes
20:05:55-690555 INFO     Installing package: clean-fid
20:06:02-789167 INFO     Installing package: filetype
20:06:04-502949 INFO     Installing package: future
20:06:06-855856 INFO     Installing package: GitPython
20:06:09-076718 INFO     Installing package: httpcore
20:06:10-731983 INFO     Installing package: inflection
20:06:12-653808 INFO     Installing package: jsonmerge
20:06:15-828335 INFO     Installing package: kornia
20:06:19-167886 INFO     Installing package: lark
20:06:21-352740 INFO     Installing package: lpips
20:06:23-517087 INFO     Installing package: omegaconf
20:06:26-102534 INFO     Installing package: open-clip-torch
20:06:32-197995 INFO     Installing package: optimum

**Comment by vladmandic** [comment]
no title, no description, no template - refile when you're ready.
