### ISSUE TITLE
[Issue]:  USING CPU INSTEAD OF GPU , I RUN IT THRICE SAME ISSUE , USING RX6600

### ISSUE THREAD

**Issue by ishanjaiswal2610** [vladmandic/automatic#3108]
### Issue Description

Using VENV: C:\ai\zluda\automatic\venv
12:11:49-068604 INFO     Starting SD.Next
12:11:49-072603 INFO     Logger: file="C:\ai\zluda\automatic\sdnext.log" level=INFO size=96527 mode=append
12:11:49-075113 INFO     Python 3.10.14 on Windows
12:11:49-264385 INFO     Version: app=sd.next updated=2024-04-21 hash=de267390 branch=master
                         url=https://github.com/vladmandic/automatic/tree/master
12:11:50-112143 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.14
12:11:50-119663 INFO     AMD ROCm toolkit detected
12:11:51-558951 WARNING  HIP SDK is detected, but no Torch release for Windows available
12:11:51-560951 INFO     For ZLUDA support specify '--use-zluda'
12:11:51-561950 INFO     Using CPU-only torch
12:11:51-734879 INFO     Extensions: disabled=[]
12:11:51-736891 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
12:11:51-747409 INFO     Extensions: enabled=[] extensions
12:11:51-749405 INFO     Startup: quick launch
12:11:51-750405 INFO     Verifying requirements
12:11:51-769719 INFO     Verifying packages
12:11:51-774124 INFO     Extensions: disabled=[]
12:11:51-775191 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sd-webui-controlnet', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg'] extensions-builtin
12:11:51-780342 INFO     Extensions: enabled=[] extensions
12:11:51-789473 INFO     Command line args: []
12:12:05-399147 INFO     Load packages: {'torch': '2.2.1+cu118', 'diffusers': '0.27.0', 'gradio': '3.43.2'}
12:12:08-484685 INFO     Engine: backend=Backend.DIFFUSERS compute=cpu device=cpu attention="Scaled-Dot-Product"
                         mode=no_grad
12:12:08-485693 INFO     Device:
12:12:10-619917 INFO     Available VAEs: path="models\VAE" items=0
12:12:10-621933 INFO     Disabled extensions: ['sd-webui-controlnet']
12:12:10-634837 INFO     Available models: path="models\Stable-diffusion" items=1 time=0.01
12:12:10-932913 INFO     Extension: script='extensions-builtin\Lora\scripts\lora_script.py'
                         [2;36m12:12:10-928913[0m[2;36m [0m[34mINFO    [0m LoRA networks: [33mavailable[0m=[1;36m0[0m
                         [33mfolders[0m=[1;36m2[0m
12:12:11-597436 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
12:12:12-919562 INFO     UI theme: name="black-teal" style=Auto base=sdnext.css
12:12:14-579856 INFO     Extension list is empty: refresh required
12:12:15-824836 INFO     Local URL: http://127.0.0.1:7860/
12:12:16-019137 INFO     [AgentScheduler] Task queue is empty
12:12:16-020136 INFO     [AgentScheduler] Registering APIs
12:12:16-376245 INFO     Select: model="dreamshaper_8 [879db523c3]"
12:12:16-379242 INFO     Torch override dtype: no-half set
12:12:16-380242 INFO     Torch override VAE dtype: no-half set
12:12:16-381244 INFO     Setting Torch parameters: device=cpu dtype=torch.float32 vae=torch.float32 unet=torch.float32
                         context=no_grad fp16=None bf16=None optimization=Scaled-Dot-Product
12:12:16-384747 INFO     Autodetect: model="Stable Diffusion" class=StableDiffusionPipeline
                         file="C:\ai\zluda\automatic\models\Stable-diffusion\dreamshaper_8.safetensors" size=2034MB
12:12:21-722775 INFO     Load embeddings: loaded=0 skipped=0 time=0.01
12:12:21-955642 INFO     Load model: time=5.35 load=5.35 native=512 {'ram': {'used': 4.78, 'total': 15.82}}
12:12:21-959647 INFO     Startup time: 30.16 torch=10.99 olive=0.14 gradio=2.47 libraries=5.16 extensions=1.56
                         face-restore=0.10 networks=0.58 ui-en=0.16 ui-txt2img=0.06 ui-img2img=0.08 ui-control=0.45
                         ui-settings=0.40 ui-extensions=1.42 ui-defaults=0.08 launch=0.20 api=0.10 app-started=0.45
                         checkpoint=5.58
12:12:41-217905 INFO     MOTD: N/A
12:12:46-344337 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
12:13:49-034429 INFO     Available models: path="models\Stable-diffusion" items=1 time=0.00
12:13:50-346259 INFO     Base: class=StableDiffusionPipeline
Progress 12.51s/it █████████████████████████████████ 100% 20/20 04:10 00:00 Base
12:18:10-928118 INFO     Saving: image="outputs\text\00001-dreamshaper_8-a cat wearing a spacesuit inside a
                         spaceship.jpg" type=JPEG resolution=512x512 size=0
12:18:10-937780 INFO     Processed: images=1 time=260.61 its=0.08 memory={'ram': {'used': 5.0, 'total': 15.82}}

### Version Platform Description

WINDOWS, CHROME

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Disty0** [comment]
Readme clearly says this:
```
For any other use case such as DirectML, ONNX/Olive, OpenVINO specify required parameter explicitly
or wrong packages may be installed as installer will assume CPU-only environment
```

```
 --use-directml                                     Use DirectML if no compatible GPU is detected, default: False
```

Logs clearly says you this: 
```
12:11:51-560951 INFO For ZLUDA support specify '--use-zluda'
```

**Comment by vladmandic** [comment]
from what i can tell, app is behaving correctly and as expected - exactly as disty0 said.
and if this is not correct, please take 1min to write an actual description (as required in template), not just dump logs.

**Comment by ishanjaiswal2610** [comment]
what i dit wrong , i am very bad in this coding stuf , i literally heard
git miniconda one moths ago
