### ISSUE TITLE
[Feature]: save last used parameters in txt2img, img2img, process image

### ISSUE THREAD

**Issue by kaelysdev** [vladmandic/automatic#311]
### Feature description

It would be awesome when I launch SD to find everything like it was the last time I closed it:

txt2img
prompt, neg prompt, common parameters that can be retrieved from process image or image browser

img2img
here it's mostly the last SD upscaler, its none by default, and I always forgot to change it, same for the scale factor, and I don't think their default values can be set in settings

process image
it's the worst, always having to change scale, upscaler, and specifically in this fork CodeFormer visibility and weight

the best solution from the user perspective would be all of those things being automatically saved and loaded on first launch or ui reload, that could also be great if default values could be defined in settings

**Comment by tiko13** [comment]
there is an extension called State that does this, but it would be nice to have it baked in (stable-diffusion-webui-state)

**Comment by vladmandic** [comment]
doesn't very first button under generate/stop/skip do exactly that?
> Read generation parameters from prompt or last generation if prompt is empty into user interface.

**Comment by iDeNoh** [comment]
> doesn't very first button under generate/stop/skip do exactly that?
> 
> > Read generation parameters from prompt or last generation if prompt is empty into user interface.

I honestly had no idea that this worked between sessions, but that's excellent to know! Thank you.

**Comment by vladmandic** [comment]
there's a file saved in your root webui folder, `params.txt`
closing the request, but if i'm missing something, post here and i'll revisit.

**Comment by kaelysdev** [comment]
After a bit more testing, it is okay for txt2img.

About what I ask for in both img2img (SD upscale parameters) and process image parameters, I don't see any solution?
