### ISSUE TITLE
[Issue]: Python 3.12 unsupported error on initial installation ?

### ISSUE THREAD

**Issue by germyparker** [vladmandic/automatic#3113]
### Issue Description

On a clean, first install of SD.Next, I'm getting the following error:

```
─ ./webui.sh
Create and activate python venv
Launching launch.py...
10:36:04-175657 INFO     Starting SD.Next
10:36:04-177095 INFO     Logger: file="[...]/sd.next/sdnext.log" level=INFO size=850 mode=append
10:36:04-177658 INFO     Python 3.12.2 on Darwin
10:36:04-178038 ERROR    Incompatible Python version: 3.12.2 required 3.[9, 10, 11]
```

I've read some issues here and they all seem to say 3.12 is ok to use -- and I didn't select 3.12 in any way, it seems to have installed 3.12 by default/on its own.

I'm not sure what else to do -- but I'm happy to supply more output if there's anything I can add.

SD.Next version: current git, main branch  

Python details: MacOS has a built in python which is unwise to change, so (like most people) I use a shim for regular python stuff; the shim is `asdf`, but it shouldn't matter, since SD.Next is a venv.  MacOS (current version), M3 CPU.

Regarding the other elements of this issue form -- the above output is literally as far as SD.Next will go, so the rest is kinda not applicable, but responses are mandatory.  So, just like when I was a kid, I boldly provided incorrect answers.

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
The most supported version of Python for SD.Next _and_ extenstions is 3.10.
The link in the installation instructions wiki points to version 3.10.11.

While having a 'higher' version number, 3.12 is not "better" than 3.10. It may have more features, but it also changes or removes other features than SD.Next relies upon.

**Comment by vladmandic** [comment]
sdnext itself supports python 3.12, but not all packages are available on 3.12
for example, torch-directml only supports 3.10 and realesrgan (used by upscalers) only supports 3.10 and 3.11.

so you have two options:
- use `--experimental` command line flag to allow sdnext to use python 3.12 and live with some missing features
- do a side-install of python 3.10 or 3.11 next to your system python. do not uninstall system python, that will never be required or recommended. once you have side install, you can simply tell sdnext to use it. for example `export PYTHON=/usr/bin/python3.11` before starting sdnext.

having said this, this has been discussed at details before - and in any case, its not an issue. next time perhaps open a question first if unsure.

**Comment by germyparker** [comment]
Thank you!  I apologize I didn't make a question instead of an issue (tbh I didn't realize they were different things).   I didn't even see the python 3.12 wiki page -- the page list gets collapsed...personally I find the github wiki really hard to use.  

However, I did end up falling down a rabbit hole regarding MacOS and Python version control, and I noticed that [SD.Next's instructions for installing Python on MacOS](https://asdf-vm.com/) may cause problems for users down the road.  I wrote up the following as a quick explainer on the issue and some instructions on how to use `asdf` as a shim tool for python version safety.  Feel free to use this in whatever way is helpful.

# MacOS & Python

The MacOS operating system requires Python, so it is installed by default.  However, if you are going to start using Python on your own, it is likely that you'll want to install new packages, perform package updates, and so on -- which can be a problem for MacOS -- it's important to let the operating system handle its own Python.

Most sources online will tell you to use Homebrew as a package manager for MacOS, so it is a natural conclusion to consider using Homebrew for Python -- and it's common to discover that you already have Python installed through Homebrew as a dependency for something else.  However, this isn't the correct solution either -- it's really the same problem as the MacOS problem, but with a coat of paint.

Homebrew's Python is there to support other packages.  Importantly, Homebrew deletes old versions of packages after 30 days.  So, if you are using, say, python 3.12 for random scripting and other tasks, but need version 3.10 for, say, SD.Next, Homebrew will delete 3.10, since it doesn't know that you need it for something (since you didn't install SD.Next via Homebrew).  

The solution is to use another way to manage the Python version(s) that you use on your own.  I use [asdf](https://asdf-vm.com/), which has a [Python plugin](https://github.com/asdf-community/asdf-python), but there are others if you prefer something else.

Sources / Further Reading: 
- https://justinmayer.com/posts/homebrew-python-is-not-for-you/
- https://hackercodex.com/guide/python-development-environment-on-mac-osx/
- https://github.com/asdf-community/asdf-python
- https://asdf-vm.com/
- https://docs.brew.sh/Installation

## Installation Instructions

0. If you haven't got Homebrew installed already:
```zsh
mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip-components 1 -C homebrew

eval "$(homebrew/bin/brew shellenv)"
brew update --force --quiet
chmod -R go-w "$(brew --prefix)/share/zsh"
```

1. Install asdf and python build dependencies:
```zsh
brew install asdf openssl readline sqlite3 xz zlib
```
2. Add asdf to `.zshrc` to use it immediately and persistently:
```zsh
. $(brew --prefix asdf)/asdf.sh
echo -e "\n. $(brew --prefix asdf)/asdf.sh" >> ~/.zshrc
```
3. Add the python asdf plugin:
```zsh
asdf plugin add python

# for SD.Next
asdf install python 3.10.14

# you may want the latest version too; take note of which version is installed
asdf install python latest
```
4. Set the default global version of python.  Since you will always want 3.10 for SD.Next, you will want to always specifically use that version.  You will probably want to use the command `python` in most contexts, and `python3.10` for version-specific uses.
```zsh
asdf global python 3.12.2 
# or whatever version you installed
```
5. Run SD.Next using python3.10:
```zsh
cd /path/to/SD.Next
python3.10 launch.py --debug
```

**Comment by vladmandic** [comment]
great write-up, lets make that into a wiki page.
one comment at the very end:

> python3.10 launch.py --debug

if you do this, `venv` does not get created/activated so all requirements are installed in python 3.10 global context (there is one per python version).
which is not a major problem if you're using python 3.10 only for sdnext.

but recommended way would be simply to say you want to use python 3.10 and leave the rest as-is

> export PYTHON=/path/to/python3.10
> cd /path/to/SD.Next
> ./webui.sh --debug

(webui.sh is simply a wrapper that creates/activates venv and then runs launch.py)

**Comment by germyparker** [comment]
Thanks, nice catch!  

I've never made a GH wiki page, but I'll give it a shot.  Apologies in advance if I do something nooby!   I'll tweak the line to use `$(which python3.10)` to reduce novice users' points of confusion.

**Comment by vladmandic** [comment]
looks good - thanks!

**Comment by mbac** [comment]
Hi. These instructions no longer seem to work (for one, my system can't find the `.sh` file mentioned here.) Also, I can't find a wiki page about it. I'm currently on 3.12.5 and SD.next wants 3.12.3. I installed `asdf` on my own and set the local version to 3.12.3, but then it complains that it's missing `python-venv`…
