### ISSUE TITLE
[Issue]: dev/new ui: sampler options not recognized for UI / Set new defaults, so the toggle states get lost

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3128]
### Issue Description

sampler options are not recognized for UI / Set new defaults, so the toggle states get lost.

- karras
- dynamic threshold
- low order
- rescale beta

### Version Platform Description

WSL2, Win11

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this was discussed many times, samplers options are not part of ui-config
sampler settings are part of server config as they are generally tweaked in settings -> samplers and ui section is just explosing whats in settings for quick access.
