### ISSUE TITLE
[Issue]: dev: timestamp AYS SD15 prefills Timesteps override, which must be empty for this selection

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3129]
### Issue Description

When selecting "AYS SD15", Timesteps override gets prefilled with "999,850,736,645,545,455,343,233,124,24". But if you then start a render, it complaints about

```ValueError: The current scheduler class <class 'diffusers.schedulers.scheduling_dpmsolver_multistep.DPMSolverMultistepScheduler'>'s `set_timesteps` does not support custom timestep schedules. Please check whether you are using the correct scheduler.
```

So either it needs to accept the values, or it should not prefill with values.

### Version Platform Description

WSL2, Win11

### Relevant log output

```shell
ValueError: The current scheduler class <class 'diffusers.schedulers.scheduling_dpmsolver_multistep.DPMSolverMultistepScheduler'>'s `set_timesteps` does not support custom timestep schedules. Please check whether you are using the correct scheduler.
```

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by lbeltrame** [comment]
IIRC, this requires diffusers 0.28.0, which is not yet.

**Comment by vladmandic** [comment]
correct, this feature requires diffusers=0.28
