### ISSUE TITLE
[Issue]: Cannot pass `--controlnet-dir` to launch.py

### ISSUE THREAD

**Issue by ljleb** [vladmandic/automatic#313]
### Issue Description

Starting the webui with controlnet arguments:

```
--controlnet-dir E:\sd\models\ControlNet --controlnet-annotator-models-path E:\sd\models
```

Does not work:
```
usage: launch.py [-h] [--medvram] [--lowvram] [--lowram] [--ckpt CKPT] [--vae VAE] [--data-dir DATA_DIR] [--allow-code] [--share] [--enable-insecure] [--use-cpu USE_CPU [USE_CPU ...]] [--listen]
                 [--port PORT] [--hide-ui-dir-config] [--freeze-settings] [--gradio-auth GRADIO_AUTH] [--gradio-auth-path GRADIO_AUTH_PATH] [--autolaunch] [--disable-console-progressbars]
                 [--disable-safe-unpickle] [--api-auth API_AUTH] [--api-log] [--device-id DEVICE_ID] [--cors-origins CORS_ORIGINS] [--cors-regex CORS_REGEX] [--tls-keyfile TLS_KEYFILE]
                 [--tls-certfile TLS_CERTFILE] [--server-name SERVER_NAME] [--no-hashing] [--no-download-sd-model] [--profile] [--disable-queue] [--debug] [--reset] [--upgrade] [--noupdate]
                 [--skip-requirements] [--skip-extensions] [--skip-git]
launch.py: error: unrecognized arguments: --controlnet-dir E:\sd\models\ControlNet --controlnet-annotator-models-path E:\sd\models
```

As the controlnet extension is builtin, we should consider adding an exception to the arg parser maybe? Or something like that.

### Version Platform Description

- commit: 752b91d38ae3fd52a7223dd8f5b73225a300f060
- os: Windows 10
- browser: Firefox

**Comment by hollowstrawberry** [comment]
Personally I use this setting

![image](https://user-images.githubusercontent.com/33796679/233476761-93400c5c-659e-44f7-b375-da69781c1036.png)

**Comment by ljleb** [comment]
Sure, but consider there are 2 other flags: (copy+paste from controlnet repo)

```
    --controlnet-dir <path to directory with controlnet models>                                ADD a controlnet models directory
    --controlnet-annotator-models-path <path to directory with annotator model directories>    SET the directory for annotator models
    --no-half-controlnet                                                                       load controlnet models in full precision
```

**Comment by myndxero** [comment]
This what you're looking for?
![Screenshot_20230420-165751](https://user-images.githubusercontent.com/113237671/233496393-9d398f24-e56e-408f-b65b-ce97ef5965d9.png)

**Comment by ljleb** [comment]
Yes. If you look at the git blame in the controlnet repo, I literally coded this part. Again, a programmatic solution is more sustainable than manual settings in the long term.

Should I use, maintain and backup the `config.json` file for this type of use case, or should we add these arguments to the repo?

**Comment by vladmandic** [comment]
i've moved extensions preloading to earlier in init code so any params that extensions register are available in launcher.
fixed in latest release.

**Comment by ljleb** [comment]
I tried updating both controlnet and the webui manually with git, but the flag `--controlnet-annotator-models-path` does not seem to be accepted:

```
usage: webui.py [-h] [--medvram] [--lowvram] [--lowram] [--ckpt CKPT] [--vae VAE] [--data-dir DATA_DIR] [--models-dir MODELS_DIR] [--allow-code] [--share] [--enable-insecure]
                [--use-cpu USE_CPU [USE_CPU ...]] [--listen] [--port PORT] [--hide-ui-dir-config] [--freeze-settings] [--gradio-auth GRADIO_AUTH] [--gradio-auth-path GRADIO_AUTH_PATH] [--autolaunch]
                [--disable-console-progressbars] [--disable-safe-unpickle] [--api-auth API_AUTH] [--api-log] [--device-id DEVICE_ID] [--cors-origins CORS_ORIGINS] [--cors-regex CORS_REGEX]
                [--tls-keyfile TLS_KEYFILE] [--tls-certfile TLS_CERTFILE] [--server-name SERVER_NAME] [--no-hashing] [--no-download-sd-model] [--profile] [--disable-queue] [--token-merging]
webui.py: error: unrecognized arguments: --controlnet-annotator-models-path E:\sd\models
```

You can see it is registered here:
https://github.com/Mikubill/sd-webui-controlnet/blob/9eeb71a796b06f912e1e66acecf4242d165db67b/preload.py#L3

**Comment by vladmandic** [comment]
are you sure you're using latest version of the repo?

``shell
python launch.py --help | grep controlnet

  --controlnet-dir CONTROLNET_DIR                      Path to directory with ControlNet models
  --controlnet-annotator-models-path CONTROLNET_ANNOTATOR_MODELS_PATH
  --no-half-controlnet                                 do not switch the ControlNet models to 16-bit floats (only needed without --no-half)
```

**Comment by ljleb** [comment]
When passed to launch.py it works, but not when passed to webui.py. However, webui.py does not accept the `--embeddings-dir` flag so I am not sure which one I am supposed to call.

**Comment by ljleb** [comment]
Ah yes, that makes sense now. There are no issues then, thanks for your help.

**Comment by vladmandic** [comment]
FYI, more than 70% of cmdflags are gone and moved to UI. mostly either in **CUDA Params** section or in **System Paths** section. data-dir and models-dir remain because they are needed much earlier than opts are even available.
