### ISSUE TITLE
[Issue]: dev/new ui: render time and manual save state is missing

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3130]
### Issue Description

With the current UI, after rendering an image you can see the time it took, and when manually saving, this line got replaced with the info that you saved it. Both informations are missing in the new UI.

### Version Platform Description

WSL2, Win11

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
In the Control tab, I've found this to be true. The metadata shows, but the time-taken doesn't;

![image](https://github.com/vladmandic/automatic/assets/1969381/d0c01422-b3be-43db-9016-ca6a019e3837)

**Comment by Tillerz** [comment]
![image](https://github.com/vladmandic/automatic/assets/63370525/0b962014-6b9f-409c-a423-258d9b7d385d)

It could be placed into that big empty space left and right of those buttons.

**Comment by brknsoul** [comment]
The first line could be adjusted;
`Ready | Saved | Images 1 | Size 512x512 | Time taken: 0:06`

**Comment by vladmandic** [comment]
done.

![image](https://github.com/vladmandic/automatic/assets/57876960/a704caa2-5297-4860-9051-5ff32b44ce60)
