### ISSUE TITLE
[Issue]: dev: metadata not saving to png/webp

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3135]
### Issue Description

Since this morning metadata are not being saved into png/webp files.

### Version Platform Description

wsl-2, win11

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i cannot reproduce - pls verify settings and try to gather more information.

**Comment by vladmandic** [comment]
fixed.
