### ISSUE TITLE
[Issue]: dev - manual image save: log output of image size wrong

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3143]
### Issue Description

The saved image size is shown as zero in the log, instead of the actual size. It's shown correct in the UI: 
![image](https://github.com/vladmandic/automatic/assets/63370525/9d2c290a-e01f-4d03-b170-2687aa7a7380)

### Version Platform Description

WSL2, Win11

### Relevant log output

```shell
09:53:11-462939 INFO     Saving: image="/home/tillerz/images/2024-05-17/00001-20240517095311-1354167277.webp" type=WEBP resolution=1024x1536 size=0
```

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed, thnx for reporting.
