### ISSUE TITLE
Request for ROCm 6.1 support on Linux

### ISSUE THREAD

**Issue by james-banks** [vladmandic/automatic#3144]
In `installer.py`, the code which checks the `rocm_ver` has a comment explaining Pytorch does not have a release for ROCm 6.1, but this is no longer true.

Removing this condition from the if statement allows the rest of the script to install Torch for ROCm 6.1 automatically as expected already, so it's a very easy fix.

**Comment by lbeltrame** [comment]
I didn't see any Pytorch nightlies offering support for ROCm 6.1.

**Comment by james-banks** [comment]
> I didn't see any Pytorch nightlies offering support for ROCm 6.1. 

Check out the ROCm docs: https://rocm.docs.amd.com/projects/install-on-linux/en/develop/how-to/3rd-party/pytorch-install.html 

```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.1/
```

**Comment by lbeltrame** [comment]
Oh, I wasn't aware of that, thanks.

**Comment by vladmandic** [comment]
i've added rocm 6.1 to installer - note that its in nightly builds only, not yet in released builds.
also, in the future please create feature request using actual TEMPLATE and fill required fields - issues section is not for free-for-all-text.

**Comment by james-banks** [comment]
> i've added rocm 6.1 to installer in dev branch - note that its in nightly builds only, not yet in released builds.
> also, in the future please create feature request using actual TEMPLATE and fill required fields - issues section is not for free-for-all-text.
> 

Thank you for the quick response. 

Appreciate and understand your point about templates - I was on mobile and didn't want to forget to make the request - but I will ensure I use them in the future.
