### ISSUE TITLE
[Issue]: dev - wildcard replacement not triggering right now

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3145]
### Issue Description

Wildcards are not being replaced, there's also no wildcard replacement log entries.

### Version Platform Description

WSL2, Win11

### Relevant log output

```shell
Ready | Time 9.21s | Images 1 | Size 1024x1536

Prompt: (in the style of oil and watercolor, roberto ferri), regency era, fantasy, vivid, colourful, intrinsic details, farmer woman __fname__ with __fhair__ on the field, __dress__, summer, sunny, lush overgrown hills in the background <lora:add_detail:0.3>
```

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed, my bad, i broke it yesterday. thnx for reporting.
