### ISSUE TITLE
[Issue]: dev - system profiler: bad visuals of "is profiler on or off", also how DO I disable it again?

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3146]
### Issue Description

I saw a button overlapping "Start profiling" and wondered why it's overlapping the text.

![image](https://github.com/vladmandic/automatic/assets/63370525/b73351a6-aa41-4784-bf07-43f1e163e677)

Clicked it. Apparently I enabled the profiler. But there is no sign if the profiler is on/off now. It just keeps profiling when I start rendering a new image.

I can't find a way to disable profiling except by a restart.

### Version Platform Description

WSL2, Win11

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
button acts as on/off, i've added label change on click.
