### ISSUE TITLE
[Issue]: Cannot save styles or give a name via extra networks

### ISSUE THREAD

**Issue by futaposting** [vladmandic/automatic#3147]
### Issue Description

Trying to save a style via the book icon in extra networks does not work and you cannot set a name

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this should already be fixed in dev branch and release should be soon. if issue reoccurs with the new version, let me know and i'll reopen.
