### ISSUE TITLE
[Issue]:  Diffusers failed loading

### ISSUE THREAD

**Issue by gRedDeer** [vladmandic/automatic#3151]
### Issue Description

SD/Next launches but I am unable to load model. getting this error not sure why. Please help whats missing I have tried many 2-3 models. 

![image](https://github.com/vladmandic/automatic/assets/130822677/fb62ae43-a9d6-4b20-9a7f-5883f1375486)

![image](https://github.com/vladmandic/automatic/assets/130822677/742325be-cfc7-45b0-8a8a-b180b9cdc7d9)

### Version Platform Description
GPU: 6700 xt

![image](https://github.com/vladmandic/automatic/assets/130822677/ec186c82-5c67-4edc-b3c2-fcd1200ad5c3)

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by gRedDeer** [comment]
One more screenshot:

![image](https://github.com/vladmandic/automatic/assets/130822677/ca50afe2-f591-49d1-98ae-308dd60da48a)

**Comment by AcamBash** [comment]
![image](https://github.com/vladmandic/automatic/assets/20889233/3b95526b-0610-4bcd-a3bc-843e102c54df)
![image](https://github.com/vladmandic/automatic/assets/20889233/b10eb62c-a9df-4e3c-a99b-9cb51221c282)
![image](https://github.com/vladmandic/automatic/assets/20889233/2d838fd8-b593-4e4c-abf0-47261cbe6f27)
Same on my end. Using a Rx6800

**Comment by Sveartear** [comment]
Same issue, had a working Zluda installation that started doing this. Did some trial and error troubleshooting and found that a fresh install from the dev branch doesn't exhibit this issue, but fresh install from the main branch does. So it's likely fixed and just hasn't been pushed out to main yet. Gotta wait.

**Comment by vladmandic** [comment]
in the first few screenshots, you've tried to use AMD ROCm on Windows which is simply not supported by AMD - i hope it will be soon, but not yet.

then you tried using ZLUDA, but you did not specify `--reinstall` so it was using same torch that was previously installed.

**Comment by Disty0** [comment]
ZLUDA specific issue, got fixed in dev branch.

**Comment by vladmandic** [comment]
closing per last comment.
