### ISSUE TITLE
[Issue]: adetailer and sdnext battle for protobuf version

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3166]
### Issue Description

On SDNext start, adetailer upgrades protobuf to 4.25.3, SDNext then downgrades it again to 3.20.3. Keeps doing it on restarts.

### Version Platform Description

WSL-2, Win11

### Relevant log output

```shell
13:54:17-691009 INFO     Extension installed packages: adetailer ['protobuf==4.25.3']
13:54:17-691797 INFO     Extensions enabled: ['sd-extension-system-info', 'sd-webui-agent-scheduler', 'sd-extension-chainner', 'sdnext-modernui',
                         'stable-diffusion-webui-rembg', 'Lora', 'adetailer']
13:54:17-692706 INFO     Verifying requirements
13:54:17-694372 WARNING  Package version mismatch: protobuf 4.25.3 required 3.20.3
13:54:17-694846 INFO     Installing package: protobuf==3.20.3
13:54:17-695289 DEBUG    Running pip: install --upgrade protobuf==3.20.3
```

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
