### ISSUE TITLE
[Issue]: Where it Train Tab??

### ISSUE THREAD

**Issue by scooller** [vladmandic/automatic#3168]
### Issue Description

Maybe I'm doing something wrong, but I updated and I don't see the training tab or the reprocessing image tab.
![imagen](https://github.com/vladmandic/automatic/assets/2198953/6d0ba669-b4d8-4dcf-907b-568997a05809)
![imagen](https://github.com/vladmandic/automatic/assets/2198953/26c5d7ed-7bcf-4a19-b775-a9eb2dbbe623)

### GPU:
device: NVIDIA GeForce RTX 3060 (1) (sm_90) (8, 6)
cuda: 12.1
cudnn: 8801
driver: 555.85
### Plataform
arch: AMD64
cpu: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
system: Windows
release: Windows-10-10.0.22631-SP0
python: 3.10.11
### Version:
app: automatic.git
updated: 2024-05-21
hash: e2af4542
url: https://github.com/vladmandic/automatic.git/tree/master

### Backend

Original

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Aptronymist** [comment]
> ### Issue Description
> Maybe I'm doing something wrong, but I updated and I don't see the training tab or the reprocessing image tab.

Ah, well the simple fact is that we spend so much more time on everything else, including our custom meh-based model merging, and everything else, that we just couldn't devote any time to updating or advancing training itself. We don't see ourselves as a platform for training, and at best it was only ever hypernetworks and embeddings.

There has been some talk of integrating OneTrainer to take care of it, but that's not going to happen in the next release for certain.

**Comment by scooller** [comment]
So they deleted the tab? I liked it a lot, it was better than the Automatic 1111

**Comment by vladmandic** [comment]
to train what? hypernetworks are obsolete. embeddings are still valid, but training method was ancient and there are far better tools. and nothing else was ever added.

sorry.

if there is a big demand, i might do ui integration with onetrainer (i already have cli integration).
