### ISSUE TITLE
[Feature]: Gamma adjustment for TCD Sampler

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#3169]
### Feature description

per [original docs](https://mhh0318.github.io/tcd/) value gamma should control the level of detail in output, yet I see [no reference to that on huggingface](https://huggingface.co/docs/diffusers/main/en/api/schedulers/tcd)

Edit: I actually found reference to it here, I knew there was something... it's apparently mapped to ETA? 0.3 default.
[link](https://huggingface.co/docs/diffusers/using-diffusers/inference_with_tcd_lora)

**Comment by vladmandic** [comment]
tcd maps gamma param to existing eta param as eta is otherwise unused. as such, its already supported.
and yes, if not present in configuration it will use 0.3 as default.
