### ISSUE TITLE
[Issue]: AYS scheduler timesteps (999) saved unconditionally in `config.json`

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3173]
### Issue Description

Once scheduler timesteps are set, i.e. with the presets, even clearing the form still affects sampling steps: e.g. if I set DPM++ 2M to 10 steps with AYS presets for SDXL, and I clear the form afterwards, effective sampling steps are still 10 regardless of what's in the UI. In other words, setting for example 30 steps will have no effect.

In the metadata it looks like there's a 999 injected for timesteps even when the field is empty.

### Version Platform Description

Latest dev (on mobile so I can't look the revision up)

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by lbeltrame** [comment]
A possible reason is that the `999` is put in `config.json` under `timestep_overrides`.

**Comment by lbeltrame** [comment]
A regular `config.json` has this, when set:

```
"schedulers_timesteps": "999,845,730,587,443,310,193,116,53,13"
```

However, when clearing the form (simply by erasing what's there) gets this saved:

```
"schedulers_timesteps": "999"
```

**Comment by vladmandic** [comment]
this only happens if a) deleting number-by-number, b) your keyboard repeat rate is faster than gradio can handle updates.
- if i select all and delete all at once, its all good.
- if i set preset to none, its all good.
- if i position cursor at the end and use backspace, you can see in the server log what is going on:
```log
08:01:02-898764 DEBUG    Sampler set options: spacing=default timesteps=999,850,736,645,545,455,343,233,124,24
08:01:03-767852 DEBUG    Sampler set options: spacing=default timesteps=999,850,736,645,545,455,343,233,124,2
08:01:04-265319 DEBUG    Sampler set options: spacing=default timesteps=999,850,736,645,545,455,343,233,124,
08:01:07-224565 DEBUG    Sampler set options: spacing=default timesteps=999,850,736,645,545,455,343,233,12
08:01:07-743653 DEBUG    Sampler set options: spacing=default timesteps=999,850,736,645,545,455,343,233,1
08:01:07-915326 DEBUG    Sampler set options: spacing=default timesteps=999,850,736,645,545,455,343,
08:01:08-091350 DEBUG    Sampler set options: spacing=default timesteps=999,850,736,645,545,455
08:01:08-270445 DEBUG    Sampler set options: spacing=default timesteps=999,850,736,645,5
08:01:08-445424 DEBUG    Sampler set options: spacing=default timesteps=999,850,736,
08:01:08-614805 DEBUG    Sampler set options: spacing=default timesteps=999,850
08:01:08-792856 DEBUG    Sampler set options: spacing=default timesteps=99
08:01:15-513141 DEBUG    Sampler set options: spacing=default timesteps=9
08:01:16-381931 DEBUG    Sampler set options: spacing=default timesteps=
```

and if your keyboard repeat rate is higher than gradio can handle updates, some updates may be missed and you end up with what you see - some numbers remain in config while they are no longer visible in the ui.

not much i can do here.

**Comment by lbeltrame** [comment]
This occurred when I was testing things via mobile on a slow link, so that's the cause. No big deal, as long as I know what causes it won't be a problem.
