### ISSUE TITLE
[Issue]: Image tab Resize By non-functional.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#3176]
### Issue Description

Attempting to use the Image tab Resize By(scale) function isn't working.
![image](https://github.com/vladmandic/automatic/assets/1969381/f7c5da7c-d562-4991-bcf6-2ca6c5d1f95d)

The Resize To(HxW) is working fine.
![image](https://github.com/vladmandic/automatic/assets/1969381/68f2869f-ebdb-4341-b9ef-d14d8335f17c)

### Version Platform Description

Python 3.10.11 on Windows
Version: app=sd.next updated=2024-05-28 hash=f5283c37 branch=master
url=https://github.com/vladmandic/automatic/tree/master

### Relevant log output

```shell
n/a
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
just to confirm, issue is specific to modernui only?

**Comment by brknsoul** [comment]
Ok, confirmed: modernui only.

**Comment by vladmandic** [comment]
@Disty0 this is core issue somewhere in modernui - it prevents gr.Tab.select event from firing.
in this case, event should be triggered in `modules/ui_sections.py:create_hires_input`, line 
```py
tab_scale_to.select(fn=lambda: 0, inputs=[], outputs=[selected_scale_tab])
```

with standardui event triggers and server gets correct info which tab is selected. 
with modernui event does not trigger so server never knows which resize method (by size or by scale) is selected.
