### ISSUE TITLE
[Issue]: xyz script not working as expected

### ISSUE THREAD

**Issue by fraxyl** [vladmandic/automatic#3180]
### Issue Description

Since the latest update, x/y/z script no longer does it's thing. I filled it out exactly the same way as I did in previous versions, only when I hit generate, it generates one image over and over, seemingly only using the first prompt and not updating it when moving along to the next.

I am not sure if it's related to modern ui or not. Here's a test image where I only filled out the X section with a prompt s/r

![image](https://github.com/vladmandic/automatic/assets/159160137/8bd75532-ce9f-4f8d-a978-679759542a18)

Also first time creating an issue on git, if you require anything else please let me know.

### Relevant log output

```shell
02:33:22-431003 INFO     Starting SD.Next
02:33:22-438995 INFO     Logger: file="E:\automatic\sdnext.log" level=INFO size=9388387 mode=append
02:33:22-442995 INFO     Python 3.10.6 on Windows
02:33:22-699052 INFO     Version: app=sd.next updated=2024-05-29 hash=d19fc8c7 branch=master
                         url=https://github.com/vladmandic/automatic/tree/master
02:33:23-326205 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i cannot reproduce, see screenshot below.
![image](https://github.com/vladmandic/automatic/assets/57876960/d9a87959-2939-438d-9463-6066eeecb048)

can you post your screenshot so both prompt and xyz grid prompt s/r fields are visible?

**Comment by vladmandic** [comment]
ah, reproduced with modernui.

**Comment by vladmandic** [comment]
fixed.
