### ISSUE TITLE
[Issue]: Generations break when using refine/force hirez and variation strength slider on SDXL

### ISSUE THREAD

**Issue by devils-shadow** [vladmandic/automatic#3182]
### Issue Description

When using the variation seed slider during any generation with any SDXL/Pony model, the resulting image is broken.
Please note that using the variation seed slider on SD1.5 models works as expected.
No errors or additional information appears in the console when running with --debug.
![image](https://github.com/vladmandic/automatic/assets/17099756/e3bfb065-6261-4bee-a6c8-132371c4ffb0)

Prerequisites:
- SDXL/Pony model present

Steps to reproduce:

1. Run SDN
2. Select any SDXL/Pony model
3. Set resolution to 768x1280
4. Set sampling method to euler a
5. Untick full quality
6. Generate 1 image
7. Reuse seed from image generated in step 6
8. Set variation strength to a value above 0 (tested with 0.3)
9. Enable second pass
10. Select RealESRGAN 4x+ Anime6B upscaler
11. Tick force hirez
12. Set hirez steps to 10
13. Attempt to generate an image
_Notice that the resulting image is broken_

### Version Platform Description

```
Python 3.10.11 on Windows
Version: app=sd.next updated=2024-05-29 hash=7a7cea3b branch=master
Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
release=Windows-10-10.0.22631-SP0 python=3.10.11
nVidia CUDA toolkit detected: nvidia-smi present
Extensions: disabled=['sdnext-modernui']
Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'stable-diffusion-webui-rembg'] extensions-builtin
Extensions: enabled=['a1111-sd-webui-tagcomplete', 'adetailer', 'sd-civitai-browser-plus'] extensions
Startup: standard
Load packages: {'torch': '2.3.0+cu121', 'diffusers': '0.28.0', 'gradio': '3.43.2'}
VRAM: Detected=11.99 GB Optimization=none
Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product" mode=no_grad
Device: device=NVIDIA GeForce RTX 4070 n=1 arch=sm_90 cap=(8, 9) cuda=12.1 cudnn=8801 driver=552.44
```

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
