### ISSUE TITLE
[Issue]: Initial Seed & Variation Seed Sharing Same Seed Value

### ISSUE THREAD

**Issue by ForceX34** [vladmandic/automatic#3188]
### Issue Description

Both the Initial Seed and the Variation Seed are sharing the same Seed generation value. Or more like the Variation Seed is referencing the Initial Seed value and not generation its own unique seed.

Reproduce:
1. Generate any image.
2. Hit the arrow to freeze the current seed in both the Initial and Variation, both will have the same seed.

When Initial Seed is fixed and Variation is "random" the Variation Seed will not generate a new unique seed because it is referencing the Initial Seed value. 
This appears to have started in the DEV release about 2 weeks ago (New UI Update?).

### Version Platform Description

Version:
app: SD.next
updated: 2024-05-31
hash: fdb5e240
url: https://github.com/vladmandic/automatic/tree/master

Platform:
arch: AMD64
cpu: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
system: Windows
release: Windows-10-10.0.22631-SP0
browser : Brave
python: 3.10.11
device: NVIDIA GeForce RTX 4090 (1) (sm_90) (8, 9)
cuda: 12.1
cudnn: 8801
driver: 555.85

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
should be fixed now.

**Comment by ForceX34** [comment]
Yes the seed values are Seed (int) values are separated now however the random / fixed states are sharing the same reference. IE when the Initial Seed is random then the Variation Seed is free to generate random seeds, but when the Initial Seed is fixed then the Variation Seed becomes fixed and cant generate another seed value.

Thank you for your fast attention. I think you have the best UI for SD

**Comment by vladmandic** [comment]
not sure i fully understand. i just pushed one more change, perhaps that fixes it.
otherwise, can you explain in a bit more detail?

**Comment by ForceX34** [comment]
Yes i opened a new ticket as to not confuse the two issues that describes in more detail

**Comment by ForceX34** [comment]
Everything is now working as intended after commit 7998f4
Thank you for  your speedy response!
