### ISSUE TITLE
[Issue] Problems with Intel Ipex support when used on Jamboree platform

### ISSUE THREAD

**Issue by freeload101** [vladmandic/automatic#3199]
### Issue Description

I added support for this project / Intel UHD Graphics to https;//JAMBOREE.rmccurdy.com comming from A1111 

like with all SD projects it's the torch nightmare but at least it's not CUDA too :) 

### Version Platform Description

https://github.com/freeload101/Java-Android-Magisk-Burp-Objection-Root-Emulator-Easy/blob/790536ec2b4a49e745eea2ed6aa9aab6200f57a2/JAMBOREE.ps1#L982

 ------------------
System Information
------------------
      Time of this report: 6/4/2024, 16:21:50
             Machine name: NATL1-49V9GB3
               Machine Id: {2FA088C8-54B5-4913-850F-28EC6F880F18}
         Operating System: Windows 10 Enterprise 64-bit (10.0, Build 19045) (19041.vb_release.191206-1406)
                Processor: Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 CPUs), ~2.2GHz
                   Memory: 16384MB RAM
      Available OS Memory: 15984MB RAM
                Page File: 8941MB used, 11154MB available
          DirectX Version: DirectX 12
 
           Card name: Intel(R) UHD Graphics
        Manufacturer: Intel Corporation
           Chip type: Intel(R) UHD Graphics Family
            DAC type: Internal
         Device Type: Full Device (POST)
          Device Key: Enum\PCI\VEN_8086&DEV_9B41&SUBSYS_09A01028&REV_02
       Device Status: 0180200A [DN_DRIVER_LOADED|DN_STARTED|DN_DISABLEABLE|DN_NT_ENUMERATOR|DN_NT_DRIVER] 
  
 Driver File Version: 27.20.0100.9664 (English)
      Driver Version: 27.20.100.9664
         DDI Version: unknown
      Feature Levels: Unknown
        Driver Model: WDDM 2.7
  

### Relevant log output

```shell
C:\ROBERT\AUTO\automatic>webui.bat --use-ipex
Using VENV: C:\ROBERT\AUTO\automatic\venv
16:17:50-348086 INFO     Starting SD.Next
16:17:50-354089 INFO     Logger: file="C:\ROBERT\AUTO\automatic\sdnext.log" level=INFO size=4208 mode=append
16:17:50-358089 INFO     Python 3.10.6 on Windows
16:17:51-022091 INFO     Version: app=sd.next updated=2024-06-02 hash=4acb0c88 branch=master
                         url=https://github.com/vladmandic/automatic.git/tree/master
16:17:51-520619 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 142 Stepping 12, GenuineIntel system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6
16:17:51-525657 INFO     Intel OneAPI Toolkit detected
16:17:53-811674 INFO     Torch 2.1.0a0+cxx11.abi
C:\ROBERT\AUTO\automatic\venv\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
16:17:54-673635 ERROR    Could not load torch: [WinError 127] The specified procedure could not be found. Error loading
                         "C:\ROBERT\AUTO\automatic\venv\lib\site-packages\intel_extension_for_pytorch\bin\pi_level_zero.                         dll" or one of its dependencies.
Press any key to continue . . .
Terminate batch job (Y/N)? y

C:\ROBERT\AUTO\automatic>dir C:\ROBERT\AUTO\automatic\venv\lib\site-packages\intel_extension_for_pytorch\bin\pi_level_zero.dll
 Volume in drive C is Windows
 Volume Serial Number is EC91-9C28

 Directory of C:\ROBERT\AUTO\automatic\venv\lib\site-packages\intel_extension_for_pytorch\bin

06/04/2024  04:11 PM         1,728,128 pi_level_zero.dll
               1 File(s)      1,728,128 bytes
               0 Dir(s)  66,773,397,504 bytes free
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by freeload101** [comment]
Looks like it's workong on another laptop so ill post what I figure out the problem is

**Comment by freeload101** [comment]
`06/04:17:29:08 INFO Cloning vladmandic_automatic
Cloning into 'automatic'...
remote: Enumerating objects: 45249, done.
remote: Counting objects: 100% (13677/13677), done.
remote: Compressing objects: 100% (1168/1168), done.
remote: Total 45249 (delta 13016), reused 12938 (delta 12496), pack-reused 31572
Receiving objects: 100% (45249/45249), 55.12 MiB | 23.81 MiB/s, done.
Resolving deltas: 100% (33235/33235), done.
Using python: "C:\ROBERT\_AUTO\pythonA111\tools\python.exe"
Creating VENV: C:\ROBERT\_AUTO\automatic\venv
Using VENV: C:\ROBERT\_AUTO\automatic\venv
17:29:24-469715 INFO     Starting SD.Next
17:29:24-475602 INFO     Logger: file="C:\ROBERT\_AUTO\automatic\sdnext.log" level=INFO size=65 mode=append
17:29:24-477849 INFO     Python 3.10.6 on Windows
17:29:24-877623 INFO     Version: app=sd.next updated=2024-06-02 hash=4acb0c88 branch=master
                         url=https://github.com/vladmandic/automatic.git/tree/master
17:29:24-953059 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 142 Stepping 12, GenuineIntel system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6
17:29:24-959525 INFO     Intel OneAPI Toolkit detected
17:29:24-963295 INFO     Installing package: openvino==2023.3.0
17:29:33-620445 INFO     Installing package: nncf==2.7.0
17:30:22-580121 INFO     Installing package: onnxruntime-openvino
17:30:37-046814 INFO     Installing package:
                         https://github.com/Nuullll/intel-extension-for-pytorch/releases/download/v2.1.10%2Bxpu/torch-2.
                         1.0a0+cxx11.abi-cp310-cp310-win_amd64.whl
                         https://github.com/Nuullll/intel-extension-for-pytorch/releases/download/v2.1.10%2Bxpu/torchvis
                         ion-0.16.0a0+cxx11.abi-cp310-cp310-win_amd64.whl
                         https://github.com/Nuullll/intel-extension-for-pytorch/releases/download/v2.1.10%2Bxpu/intel_ex
                         tension_for_pytorch-2.1.10+xpu-cp310-cp310-win_amd64.whl
17:31:34-889109 INFO     Torch 2.1.0a0+cxx11.abi
C:\ROBERT\_AUTO\automatic\venv\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: ''If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
17:31:38-063296 INFO     Torch backend: Intel IPEX 2.1.10+xpu
17:31:38-067439 INFO     Torch detected GPU: Intel(R) UHD Graphics VRAM 6417 Compute Units 24
17:31:38-074268 INFO     Installing package: onnx
17:31:46-921955 INFO     Startup: standard
17:31:46-924411 INFO     Verifying requirements
17:31:46-928464 WARNING  Package version mismatch: setuptools 63.2.0 required 69.5.1
17:31:46-930544 INFO     Installing package: setuptools==69.5.1
17:31:49-898672 INFO     Installing package: patch-ng
17:31:57-021490 INFO     Installing package: anyio
17:31:59-270691 INFO     Installing package: addict`

**Comment by Disty0** [comment]
Seems like a broken install.

And IPEX doesn't support iGPUs as stated in the Wiki.

**Comment by freeload101** [comment]
kagi.com searches 'iGPU' ... Ohhh my bad .. well I added it anyway. I will test it on my 8gig GPU today. Thanks again!

**Comment by Disty0** [comment]
You want OpenVINO instead of IPEX on iGPUs but it's pita to use because of its hard compiled nature.
