### ISSUE TITLE
Warning: XPU Device count is zero! (function initGlobalDevicePoolState) trouble shooting question

### ISSUE THREAD

**Issue by webghostdeveloper** [vladmandic/automatic#3201]
I have Ubuntu 24.04 installed on metal hardware - no dual boot. I have an arc770 I want to run which is why I chose SD.next.

I followed the installation instructions; adding the "jammy" repository as I don't see an updated repository for "noble".

I also set up pyenv and used both python3 -v 3.10.14 and -v 3.11.9 but keep having the following issue:

when I run ./webui.sh --use-ipex
 
I get:
`[W Device.cpp:127] Warning: XPU Device count is zero! (function initGlobalDevicePoolState)
Segmentation fault (core dumped)`

While it is just a warning and no errors occur in the debug output, the server never starts and just kicks me back to the stdin prompt.

[sdnext.log](https://github.com/user-attachments/files/15574514/sdnext.log)
[arc770-xpu-issue.txt](https://github.com/user-attachments/files/15574868/arc770-xpu-issue.txt)

Looking for some suggestions on how to go about troubleshooting this issue further.

**Comment by vladmandic** [comment]
@webghostdeveloper sorry to say this, but for any issues, use provided template - i'll have to mark this as invalid for now.

**Comment by webghostdeveloper** [comment]
> Kernel 6.8 is broken on Intel ARC.
> 
> Update your intel-compute-runtime to the latest one.

Thank you for that info.

**Comment by webghostdeveloper** [comment]
> @webghostdeveloper sorry to say this, but for any issues, use provided template - i'll have to mark this as invalid for now.

My Apologies, I didn't really know which template to use as I don't consider this a real issue. I can't join discord otherwise I would have asked the question there, but I'll be sure to use a template in the future - thanks for your work on this project
