### ISSUE TITLE
[Issue]: Networks > No Scroll option when you have too many folders

### ISSUE THREAD

**Issue by HyunJae5463** [vladmandic/automatic#3208]
### Issue Description

When you have too many subfolders, for Lora for example, you can't scroll down and cant select folders outside the "Default Height". There is no slider to scroll and using mousewheel doesn't work either.

![image](https://github.com/vladmandic/automatic/assets/107355366/de924c31-39a5-452b-8bea-dae05860c927)

### Version Platform Description

Not relevant

### Relevant log output

```shell
Not relevant
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
version-platform-description are always relevant.
and you didn't say are you using modern or standard ui.
if this is about modernui, this was addressed post-release, you just need to update.
and as far as i know, standard ui was no affected.

**Comment by HyunJae5463** [comment]
> version-platform-description are always relevant. and you didn't say are you using modern or standard ui. if this is about modernui, this was addressed post-release, you just need to update. and as far as i know, standard ui was no affected.

Hi, i apologize for the lack of information I've provided. Next time i report something i will make sure to provide as much information as possible.
I had already updated to the latest version but the bug was still there. But after changing the theme once the bug seems to be fixed. Thank you for your time. This can be closed.
