### ISSUE TITLE
[Issue]: importing libraries seems to be failing

### ISSUE THREAD

**Issue by sadelcri** [vladmandic/automatic#321]
### Issue Description

so I'm trying to use this extension https://github.com/Astropulse/sd-palettize with vladmandic's automatic and it seems to pop up this error:
![dasd](https://user-images.githubusercontent.com/120217469/233483619-c0debceb-f93f-44dd-a8d3-7c7181e0b97a.png)

every other extension works fine and this extension works fine with automatic1111. It seems that the error is provoked because the hitherdither library is not being installed automatically

### Version Platform Description

windows 11, google chrome.

**Comment by vladmandic** [comment]
issue is that extensions is trying to install package from `git+https://www.github.com/hbldh/hitherdither` and not providing friendly name for it, so installer had no idea what is the actual package name to check if its installed or not.
i've created a compatibility layer for that, but extension should really provide a friendly name for anything it wants to install, not just url.
