### ISSUE TITLE
[Issue]: Error of extension 'sd-forge-layerdiffuse' when using OpenVINO

### ISSUE THREAD

**Issue by HajiyevEl** [vladmandic/automatic#3211]
### Issue Description

Using OpenVINO.
Installed extension: https://github.com/layerdiffusion/sd-forge-layerdiffuse
After restart - failed to update numpy to version 1.26.4 (current version 1.24.3) (log attached). Seems like installation failed due to permissions.
Couldn't run webui.bat as administrator.
Installed numpy 1.26.4 manually.
After installation had following errors:

![Screenshot 2024-06-10 170202](https://github.com/vladmandic/automatic/assets/70325881/90736940-f69a-4f2f-a682-ee94233a5888)

Server starts and modern UI works properly. Extension - does not.

### Version Platform Description

Python 3.10.6 on Windows
Version: app=sd.next updated=2024-06-07 hash=84f9caaf branch=master url=https://github.com/vladmandic/automatic.git/tree/master
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 126 Stepping 5, GenuineIntel system=Windows release=Windows-10-10.0.19045-SP0 python=3.10.6
Setting environment tuning
HF cache folder: C:\Users\Elbrus\.cache\huggingface\hub
Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=True
Torch allowed: cuda=False rocm=False ipex=False diml=False openvino=True
Using OpenVINO
Torch 2.3.1+cpu
Repository update time: Fri Jun  7 05:10:59 2024
Previous setup time: Mon Jun 10 16:29:08 2024
Extensions: disabled=[]
Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg'] extensions-builtin
Extensions: enabled=['sd-forge-layerdiffuse'] extensions
Latest extensions time: Mon Jun 10 16:29:04 2024

### Relevant log output

```shell
2024-06-10 16:36:15,149 | sd | WARNING | installer | Package version mismatch: numpy 1.24.3 required 1.26.4
2024-06-10 16:36:15,149 | sd | INFO | installer | Installing package: numpy==1.26.4
2024-06-10 16:36:15,149 | sd | DEBUG | installer | Running pip: install --upgrade  numpy==1.26.4 
2024-06-10 16:36:42,078 | sd | ERROR | installer | Error running pip: install --upgrade  numpy==1.26.4
2024-06-10 16:36:42,078 | sd | DEBUG | installer | Pip output: Collecting numpy==1.26.4

  Using cached numpy-1.26.4-cp310-cp310-win_amd64.whl (15.8 MB)

Installing collected packages: numpy

  Attempting uninstall: numpy

    Found existing installation: numpy 1.24.3

    Uninstalling numpy-1.24.3:

      Successfully uninstalled numpy-1.24.3


ERROR: Could not install packages due to an OSError: [WinError 5] \u041e\u0442\u043a\u0430\u0437\u0430\u043d\u043e \u0432 \u0434\u043e\u0441\u0442\u0443\u043f\u0435: 'C:\\Users\\xxx\\Desktop\\Stable Diffusion\\SDNext\\venv\\Lib\\site-packages\\~~mpy\\.libs\\libopenblas64__v0.3.21-gcc_10_3_0.dll'

Check the permissions.
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
a) this is an extension, so you should use extension template
b) forge extensions are rarely compatible with anything but forge
c) sdnext has layer diffuse built-in, you don't need extension to start with
