### ISSUE TITLE
[Issue]: very strange image quality

### ISSUE THREAD

**Issue by heeyfox** [vladmandic/automatic#3212]
### Issue Description

I used to use SD on an RTX 2060, I upgraded to an RX 6700XT and I'm using this version of SD, but I try to create an image with the same prompt I would use on Nvidia SD and the image comes out blurry or with mixed colors, I'm missing something ?

### Version Platform Description

Starting SD.Next
Logger: file="X:\Git\SD_AMD\automatic\sdnext.log" level=DEBUG size=65 mode=create
Python 3.10.6 on Windows
Version: app=sd.next updated=2024-06-07 hash=84f9caaf branch=master
                         url=https://github.com/vladmandic/automatic/tree/master
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 63 Stepping 2, GenuineIntel system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6
Setting environment tuning
HF cache folder: C:\Users\mathe\.cache\huggingface\hub
Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
AMD ROCm toolkit detected
WARNING  ZLUDA support: experimental
Using ZLUDA in X:\Git\SD_AMD\automatic\.zluda
Torch 2.3.0+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: AMD Radeon RX 6700 XT [ZLUDA] VRAM 12272 Arch (8, 8) Cores 20

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
as documented here https://github.com/vladmandic/automatic/wiki/ZLUDA, zluda is experimental and support is best received via discord, not github, especially for issues like this

also, you said "very strange image quality", but have provided no actual details or examples.

**Comment by futaposting** [comment]
The effect he's talking about is when the VAE is not applied. I am also seeing this. Returning to an older commit applies the VAE.

**Comment by vladmandic** [comment]
there is no such thing as "vae not applied", so even for that, need for info.

**Comment by futaposting** [comment]
Okay, it's acting as if the VAE is set to None, when it's set to sdxl_vae, does that make sense?

**Comment by vladmandic** [comment]
it doesn't really - vae set to none means "use vae thats already baked into model".
if vae was actually none, there would be error at the end of generate and no image as there is nothing to decode latents at all.
so again, need examples.

**Comment by heeyfox** [comment]
the problem was like the SD didn't use the negative prompt, it always gave me blurry or distorted image results, now I'm using stable-diffusion-webui-amdgpu from lshqqytiger with zluda and it's working great, thanks everyone

**Comment by futaposting** [comment]
@vladmandic Please see the following generations and the commit they were generated on
de26739 - Deploying to master from @ vladmandic/automatic@7ecc1d7d9a98172326aaa16088039439dcebb02d 🚀 April 21, 2024
https://files.catbox.moe/11pjjp.jpg
84f9caa - Deploying to master from @ vladmandic/automatic@7c9f1bc79778ac3438ef74095082ea568e970b97 🚀 June 6, 2024
https://files.catbox.moe/3vc9j8.jpg

**Comment by vladmandic** [comment]
try settings -> diffusers -> VAE upcasting -> true

**Comment by vladmandic** [comment]
just to verify, did you restart sdnext or reload a model afterwards? because setting is applied during model load.

**Comment by futaposting** [comment]
I've isolated the commit when the problem starts occurring 
0cedf95 - update diffusers, release notes, lint fixes

**Comment by vladmandic** [comment]
ok, i'll investigate, reopening.

**Comment by vladmandic** [comment]
just made a change on dev branch that should help with this.
if you can test with dev branch, great.
if not, i'll likely do a refresh of the master within couple of days anyhow.
if issue persists, let me know and i'll reopen.

**Comment by futaposting** [comment]
It's working on the latest commit, thanks.
