### ISSUE TITLE
[Feature]: Add "Unload model after generation" and "Reload model generation".

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#3220]
### Feature description

Add "Unload/Reload model after generation" as an experimental checkbox in Diffusers Settings, for testing.

Use case: SD3 requires me to reload the model after each use due to vram usage creep.

### Version Platform Description

```
Version: app=sd.next updated=2024-06-12 hash=63909203 branch=dev
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel system=Windows
release=Windows-10-10.0.19045-SP0 python=3.10.11
```

**Comment by vladmandic** [comment]
thats a sledgehammer solution to an actual problem. if there is a leak, document as an issue and lets see what we can do about it.
