### ISSUE TITLE
[Feature]: Disable "Apply Changes" unless SD.NEXT is idle

### ISSUE THREAD

**Issue by cgwers** [vladmandic/automatic#3237]
### Feature description

IMHO, it would be a good idea to disable the "Apply Changes" action in system settings unless the system is idle, or at the very least add a restart confirmation dialog with the prompt, "Applying changes will halt the current operation and restart the server," and the continue action prompt, yes/no or OK/Cancel. Waiting on generations to finish almost begs users to tweak things while they're waiting. 

### Version Platform Description

vivaldi or opera. Windows 10. Python 3.11.8

**Comment by vladmandic** [comment]
apply changes is instant for most changes, only few require server restart and few more require model reload.

why would applying changes abort operation in progress?
