### ISSUE TITLE
Read first before creating new Issue

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#324]
Search existing issues and discussions before creating a new one - as of right now, nearly 30% of newly reported issues are duplicates.
If possible update to latest version before reporting the issue as older versions cannot be properly supported

Any issues without version information will be closed
Look at console log and copy the version string from there
For example: Version: f256fb8b Fri Apr 14 17:41:30 2023 -0400

Additionally provide any relevant platorm information (OS, browser, versions)

If issue is setup, installation or startup related, please check setup.log before reporting
And when posting console logs, please use code blocks ( ``` ) to format them insead of uploading screenshots

Verify that issue persists after restarting server from command line
Restarting from UI or reloading browser is insufficient to create reproducible environment

If you have additional extensions installed, try to reproduce the issue with user extensions disabled
And if the issue is with compatibility with specific extension, mark it as such when creating the issue

**Comment by gitmylo** [comment]
Hmm, maybe you could update the issue form to use the same layout as the upstream Automatic1111 webui repository. Since the upstream repo issue form has a field called `Commit where the problem happens` where you, well, you put the commit hash in the field.

**Comment by vladmandic** [comment]
i don't want to have overly complex template that takes forever to fill. and at the end, users still don't provide all required info.
