### ISSUE TITLE
[Feature]: ControlNet support for SD3

### ISSUE THREAD

**Issue by Alchete** [vladmandic/automatic#3240]
### Feature description

The first SD3 control nets have been released.  This is a feature request to add support for them.  Thanks.

https://huggingface.co/InstantX/SD3-Controlnet-Canny/tree/main
https://huggingface.co/InstantX/SD3-Controlnet-Pose/tree/main
https://huggingface.co/InstantX/SD3-Controlnet-Tile
https://huggingface.co/InstantX/SD3-Controlnet-Inpainting

**Comment by jugadorgl1** [comment]
How to use them in the ConfyUI?
Standard nodes give an error ((

**Comment by vladmandic** [comment]
this is not comfy, ask in appropriate repo.

**Comment by vikm2o** [comment]
https://huggingface.co/InstantX/SD3-Controlnet-Inpainting gives 404

**Comment by vladmandic** [comment]
done!
