### ISSUE TITLE
[Issue]: Ugly UI with --theme dark

### ISSUE THREAD

**Issue by BiosNod** [vladmandic/automatic#3242]
### Issue Description

I just did some commands according some guide:
git clone https://github.com/vladmandic/automatic.git
webui.bat --api-log --theme dark --no-hashing --use-directml --debug --listen

And I see this weird dark theme:
![изображение](https://github.com/vladmandic/automatic/assets/16207244/82deee23-017c-44fe-a259-d4232d787c5d)

Maybe I should change it to StandardUI or ModernUI from settings... But it doesn't work with dark theme option:
![изображение](https://github.com/vladmandic/automatic/assets/16207244/440a602e-d53d-46df-b8d8-e0ba6e8048bf)

![изображение](https://github.com/vladmandic/automatic/assets/16207244/9c8df0a4-54b0-4efa-a0b3-502744cfc759)

Without --theme dark it seems OK, theme is dark even without this argument, but why --theme dark option will break the theme? Theme without this argument:
![изображение](https://github.com/vladmandic/automatic/assets/16207244/a6698639-1f9d-4f13-a03b-bfad6f915467)

I can change theme to dark using only UI like this:
![изображение](https://github.com/vladmandic/automatic/assets/16207244/966c2716-5374-49e9-b7a0-3d7dd2c51a07)

But what a hell happen with UI using --theme dark? Is it not equivalent dark/light theme from this settings?
This is extremely not obvious to new users and I still don't know is it a bug? I want to use --theme dark/light without any theme breaking

### Backend

Diffusers

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
`--theme dark` does not exist, so what you ended up is base gradio interface without either standard-ui or modern-ui.
can you point where you saw `--theme dark` as param? that doc should be updated.

and i just made code update if theme specified on command line is invalid, it does a correct fallback.

**Comment by BiosNod** [comment]
> --theme dark

From this topic:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/2586

I know that it is another realization but... I was used to using this argument for a dark theme and thought that it works as it should be for SD.Next too

"if theme specified on command line is invalid, it does a correct fallback." - please make this argument correspond to those settings in the interface (at screen), it seems this settings exists in any theme?
![изображение](https://github.com/vladmandic/automatic/assets/16207244/d4c421e6-3093-4b7a-9d75-0b2b352a2a33)

**Comment by vladmandic** [comment]
this is not AUTOMATIC1111. See https://github.com/vladmandic/automatic/wiki/Themes

**Comment by BiosNod** [comment]
> this is not AUTOMATIC1111. See https://github.com/vladmandic/automatic/wiki/Themes

Thanks.. Can you make error instead of fallback? It seems better, no?

**Comment by vladmandic** [comment]
i did both:
>  ./webui --theme dark
```log
08:37:02-193654 ERROR    UI theme invalid: theme="dark" available=['standard/*', 'modern/*', 'none/*'] fallback="standard/black-teal"
```
