### ISSUE TITLE
[Issue]: Preview theme error

### ISSUE THREAD

**Issue by BiosNod** [vladmandic/automatic#3243]
### Issue Description

Try to preview any theme:

![изображение](https://github.com/vladmandic/automatic/assets/16207244/a65568bd-184b-4ece-b601-26b5ecf688f1)

Error:
![изображение](https://github.com/vladmandic/automatic/assets/16207244/84fc8300-cbb5-48c8-b77d-1ae27335c890)

It seems html/themes.json not found, but why I must have this json file if I just have fresh sd.next installed and want to see preview of theme in settings? Is it a bug or I really must create this file to use preview feature? 

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i've fixed it in latest dev
