### ISSUE TITLE
[Issue]: Backend Original cause error

### ISSUE THREAD

**Issue by BiosNod** [vladmandic/automatic#3244]
### Issue Description

I want to recreate some image that I was generated  a year ago, I opened .txt nearby image and checked all options:
![изображение](https://github.com/vladmandic/automatic/assets/16207244/1ad4e744-4501-4ec7-9511-a524b3762666)

And noticed that right now sd.next using execution method "diffusers", so I changed backend to Original here:
![изображение](https://github.com/vladmandic/automatic/assets/16207244/4a2acdd1-6b80-4a7a-b7cb-c4c89cd25cf0)

And I got error ( it seems the main line is - WARNING  Sampler: invalid):

![изображение](https://github.com/vladmandic/automatic/assets/16207244/1c09cfb3-cb90-4be2-ab99-30a2e2462a9e)
...
![изображение](https://github.com/vladmandic/automatic/assets/16207244/3821d570-5a3a-475b-ab27-85ad58e4dd01)

Is error related to TOMESD option?

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
did you restart the server (completely, not from ui) after changing backend?

**Comment by BiosNod** [comment]
> did you restart the server (completely, not from ui) after changing backend?

yes, even 2 times to make sure

**Comment by brknsoul** [comment]
Is there a pressing reason you're using Backend: Original, rather than the recommended Diffusers?

**Comment by BiosNod** [comment]
> Is there a pressing reason you're using Backend: Original, rather than the recommended Diffusers?

It seems Euler A algorithm generating picture in some different way in Diffusers than Euler A in Original backend, for example in DIffusers backend TAESTD preview will generate mosaic preview but in Original preview is just blur instead of mosaic view

**Comment by brknsoul** [comment]
Unless you're trying to get the same type of image each time, you probably should be updating SD.Next and using Diffusers.

**Comment by BiosNod** [comment]
Proofs:

Live preview with `Euler A` in Diffusers backend (current sd.next revision):
![изображение](https://github.com/vladmandic/automatic/assets/16207244/221837c1-3537-4622-b45b-e239b7e243d0)

Live preview with `Euler A` in Original backend (old 2023 sd.next revision):
![изображение](https://github.com/vladmandic/automatic/assets/16207244/4c40ed7f-cd13-43ba-82c4-cb7099ff1402)

Why live previews different?

**Comment by brknsoul** [comment]
With the same seed and settings, do both produce the same image?
If so, then the preview really doesn't matter, right?

**Comment by vladmandic** [comment]
lets not mix issues - does preview work or not is one thing. does backend original work with latest sdnext is another.

**Comment by BiosNod** [comment]
> With the same seed and settings, do both produce the same **image?**
Different images with same hash using different backends:

robot
Steps: 20, Seed: 4089542119, Sampler: DDPM, CFG scale: 6, Size: 256x256, Parser: Full parser, Model: dreamshaper_8, Backend: Diffusers, App: SD.Next, Version: f2b99d6, Operations: txt2img, Sampler options: , Pipeline: StableDiffusionPipeline
![00004-dreamshaper_8-DDPM-4089542119](https://github.com/vladmandic/automatic/assets/16207244/3fee3040-bbca-4caf-819b-f02bac95509a)

robot
Steps: 20, Seed: 4089542119, Sampler: Euler a, CFG scale: 6, Size: 256x256, Parser: Full parser, Model: dreamshaper_8, Backend: Original, App: SD.Next, Version: f2b99d6, Operations: txt2img, Sampler brownian: False, Sampler karras: False
![00005-dreamshaper_8-Euler a-4089542119](https://github.com/vladmandic/automatic/assets/16207244/92408aa1-2582-4dd3-ada0-7bb66497511a)

NOTE: I used 2023 year sd.next  revision - this version can change Backend from Original to Diffusers on the fly - all works fine and no need to restart, but images with same hash is different! See screens.

And current sd.next revision can't switch to Original. Because images with same hash is different I want to use Original Backend in current SD.Next revision - this is a big problem right now for me

**Comment by BiosNod** [comment]
Let me time to check it

**Comment by BiosNod** [comment]
> With the same seed and settings, do both produce the same **image?**
Different images with same hash using different backends:

`00005-dreamshaper_8-Euler a-4089542119.txt`:
robot
Steps: 20, Seed: 4089542119, Sampler: Euler a, CFG scale: 6, Size: 256x256, Parser: Full parser, Model: dreamshaper_8, Backend: Original, App: SD.Next, Version: f2b99d6, Operations: txt2img, Sampler brownian: False, Sampler karras: False
![Uploading 00005-dreamshaper_8-Euler a-4089542119.jpg…]()


`00006-dreamshaper_8-Euler a-4089542119.txt`:
robot
Steps: 20, Seed: 4089542119, Sampler: Euler a, CFG scale: 6, Size: 256x256, Parser: Full parser, Model: dreamshaper_8, Backend: Diffusers, App: SD.Next, Version: f2b99d6, Operations: txt2img, Sampler options: , Pipeline: StableDiffusionPipeline
![00006-dreamshaper_8-Euler a-4089542119](https://github.com/vladmandic/automatic/assets/16207244/d12d0681-ea60-4298-978a-468c0a7f161e)


NOTE: I used 2023 year sd.next  revision - this version can change Backend from Original to Diffusers, but images with same hash is different! See screens. I think also in current sd.next revision different backends will generate different images

My main isssue:
Current sd.next revision can't switch to Original. Because images with same hash is different I want to use Original Backend in current SD.Next revision - this is a big problem right now for me

**Comment by BiosNod** [comment]
Also I noticed when I changed Backend:
`Sampler brownian: False, Sampler karras: False` changed to: `Sampler options: , Pipeline: StableDiffusionPipeline`
But I changed only Backround, nothing else!

Also I have as I said I have no errors with both Backends in revision https://github.com/vladmandic/automatic/commit/f2b99d61f63ebd5d7a3e36d11c2317c42c86b875
But current latest master's commit have errors

**Comment by BiosNod** [comment]
> If so, then the preview really doesn't matter, right?

But images is different, unfortunately, see my proofs above, I hope I gave detailed information as much as I could

**Comment by BiosNod** [comment]
> lets not mix issues - does preview work or not is one thing. does backend original work with latest sdnext is another.

Is it possible to restore Original support instead of compare images with different backends? It seems a long way... Do developers want to remove Original backend from sd.next in the future instead of repair?...

**Comment by vladmandic** [comment]
> Do developers want to remove Original backend from sd.next in the future instead of repair and force to use Diffusers only?...

your entire issue is 2h old and you're already jumping to conclusions?!?!

**Comment by BiosNod** [comment]
> your entire issue is 2h old and you're already jumping to conclusions?!?!
Sorry, I thought that it was already in the dev plans, so I just specified 👀

**Comment by vladmandic** [comment]
i've fixed warning about invalid sampler with backend=original, patch is in latest dev.
the rest, i cannot reproduce the issue, with or without tome enabled.
so need more info from you if issue persists:
- enable `set SD_PROCESS_DEBUG=true`
- start `webui.bat --debug`
- reproduce the problem
- and then upload `sdnext.log` (btw, never upload screenshot of a log to an issue, it makes it impossible to work with)

**Comment by BiosNod** [comment]
I checked out latest dev version and waited for env update and... Original backend work without any errors, wow
It seems it is not necessary to reproduce because of the magical solution of the problem, guess you can close issue as solved?
![изображение](https://github.com/vladmandic/automatic/assets/16207244/f9d4197b-af98-438f-a486-4c94a3918ccc)


All good even with ToMe enabled:
![изображение](https://github.com/vladmandic/automatic/assets/16207244/f1a9c988-18fd-44cb-bd3a-c71ef26efae3)

Also I can repeat old images using Original backend + ToMe
![изображение](https://github.com/vladmandic/automatic/assets/16207244/eeebe7cf-cef6-4e05-8e6d-524cecaae232)

Recent fixes in the dev branch, apparently, were very important, plus I suffered for a long time with another settings...

![изображение](https://github.com/vladmandic/automatic/assets/16207244/98226d42-eaea-4144-bdfd-0f15e4ba1e8f)
