### ISSUE TITLE
[Feature]: Networks/LoRA: add a link back to the source (Civitai etc.)

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3245]
### Feature description

Trigger keywords are often not shown on mousover because people misuse the civitai config as SEO, so you have to look up the trigger keywords on the download page.

Suggestion: when fetching the METADATA from Civitai, also add a link to the LoRa panel or the (I)nfo button.

### Version Platform Description

WSL-2, Windows 11

**Comment by vladmandic** [comment]
done:
![image](https://github.com/vladmandic/automatic/assets/57876960/83b217f9-8349-4a69-bcc8-d821ad97bf17)
