### ISSUE TITLE
[Issue]: Playground v2.5 get wrong result

### ISSUE THREAD

**Issue by stoickk** [vladmandic/automatic#3246]
### Issue Description

when I run Playground v2.5 with huggingface code ,
``` python
from diffusers import DiffusionPipeline
import torch

pipe = DiffusionPipeline.from_pretrained(
    "playgroundai/playground-v2.5-1024px-aesthetic",
    torch_dtype=torch.float16,
    variant="fp16",
).to("cuda")

prompt = "Astronaut in a jungle, cold color palette, muted colors, detailed, 8k"
image = pipe(prompt=prompt, num_inference_steps=50, guidance_scale=3).images[0]
````
 the result is:
 <img width="689" alt="image" src="https://github.com/vladmandic/automatic/assets/10822701/6e6ddf59-29d1-4668-bc79-6ea1df634605">

I run Playground v2.5 with [automatic], the result is
![image](https://github.com/vladmandic/automatic/assets/10822701/f1804c6b-78e5-4d05-a71e-5ed9e52c4b4e)
 
![image](https://github.com/vladmandic/automatic/assets/10822701/1a58ca44-cb30-4569-acb5-78a4970904e6)

I have tried many times and the quality of the results obtained on the two platforms is completely different

### Backend

Diffusers

### Branch

Master

### Model

Playground v2.5 

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this was fixed in dev branch few days ago, i'll post a refresh release next week
