### ISSUE TITLE
[Feature]: Lumina Model Support

### ISSUE THREAD

**Issue by JohnAlcatraz** [vladmandic/automatic#3249]
### Feature description

Would be great to have support for the Lumina models: https://github.com/Alpha-VLLM/Lumina-T2X

Lumina-Next Demo Video: https://www.youtube.com/watch?v=K0-AJa33Rw4

**Comment by tscott65** [comment]
I see that it's supposed to be supported now, but I cannot get any results. I don't see a Wiki page or other instructions on how to use it. I've tried various cfg values from 1 to 5.

Here's the error I get with either "Default" sampler or "Huen Flowmatch" (note: Euler Flowmatch gives an error early-on and won't work).

Progress  1.78it/s                                      0% 39/? 00:21 00:00 Base
12:33:42-145095 ERROR    Failed to validate samples: sample=(1024, 1024, 3) min=0.00 max=0.00 mean=0.00 invalid=3145728
12:33:42-174151 INFO     Save: image="outputs\text\00074-Lumina-Next-SFT-diffusers-a medieval D D fantasy intricately
                         detailed fantasy.jpg" type=JPEG width=1024 height=1024 size=8136
12:33:42-176730 INFO     Processed: images=1 time=31.36 its=0.64 memory={'ram': {'used': 8.83, 'total': 31.87}, 'gpu':
                         {'used': 2.01, 'total': 15.99}, 'retries': 0, 'oom': 0}
12:34:02-512526 INFO     Base: class=LuminaText2ImgPipeline
Progress  1.75it/s                                      0% 39/? 00:22 00:00 Base
12:34:35-320757 ERROR    Failed to validate samples: sample=(1024, 1024, 3) min=0.00 max=0.00 mean=0.00 invalid=3145728
12:34:35-345758 INFO     Save: image="outputs\text\00075-Lumina-Next-SFT-diffusers-a medieval D D fantasy intricately
                         detailed realistic.jpg" type=JPEG width=1024 height=1024 size=8014
12:34:35-347759 INFO     Processed: images=1 time=32.86 its=0.61 memory={'ram': {'used': 8.89, 'total': 31.87}, 'gpu':
                         {'used': 2.01, 'total': 15.99}, 'retries': 0, 'oom': 0}

**Comment by vladmandic** [comment]
there was a bug in alphavllm-lumina that i just fixed in dev branch, but i don't think its related to above.
`failed to validate samples` is typically fp16 overflow issue - i have no idea which gpu you have, but if its compatible you may want to use bf16 as its much better with numeric ranges. if not, you'll have to use fp32 which uses 2x memory.

anyhow closing this feature request as its implemented.

**Comment by tscott65** [comment]
Thank you. I'll give it a try. I have a 4080.

**Comment by vladmandic** [comment]
bf16 is perfect on rtx3xxx or rtx4xxx gpus
also make sure you're on latest dev so you have fix i mentioned.
