### ISSUE TITLE
[Issue]: Face Hires with batch counts > 1 causes (sporadically) exceptions

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3257]
### Issue Description

If setting face restore with face hires, and setting > 1 batch size, sporadically the pipeline with fail after the first image with a seemingly cryptic exception:

```
ValueError: StableDiffusionXLPAGPipeline {
  "_class_name": "StableDiffusionXLPAGPipeline",
  "_diffusers_version": "0.29.0",
  "_name_or_path": null,
  "feature_extractor": [
    null,
    null
  ],
  "force_zeros_for_empty_prompt": true,
  "image_encoder": [
    null,
    null
  ],
  "requires_aesthetics_score": false,
  "scheduler": [
    "diffusers",
    "DPMSolverMultistepScheduler"
  ],
  "text_encoder": [
    "transformers",
    "CLIPTextModel"
  ],
  "text_encoder_2": [
    "transformers",
    "CLIPTextModelWithProjection"
  ],
  "tokenizer": [
    "transformers",
    "CLIPTokenizer"
  ],
  "tokenizer_2": [
    "transformers",
    "CLIPTokenizer"
  ],
  "unet": [
    "diffusers",
    "UNet2DConditionModel"
  ],
  "vae": [
    "diffusers",
    "AutoencoderKL"
  ]
}
 has been incorrectly initialized or <class 'modules.pag.pipe_sdxl.StableDiffusionXLPAGPipeline'> is incorrectly implemented. Expected {'tokenizer_2', 'vae', 'text_encoder_2', 'text_encoder', 'feature_extractor', 'tokenizer', 'scheduler', 'image_encoder', 'unet'} to be defined, but dict_keys(['vae', 'text_encoder', 'text_encoder_2', 'tokenizer', 'tokenizer_2', 'unet', 'image_encoder', 'feature_extractor', 'scheduler', 'requires_aesthetics_score']) are defined.
```

This is referred to PAG, but it also occurs with the regular `StableDIffusionXLPipeline`.  The tricky part is that it does not always occur, but once it does, it is 100% reproducible. I was able to reproduce this on three different installs.

### Version Platform Description

17:10:16-398035 INFO     Starting SD.Next
17:10:16-406968 INFO     Logger: file="/workspace/automatic/sdnext.log" level=INFO size=16345220 mode=append
17:10:16-410510 INFO     Python version=3.10.12 platform=Linux bin="/workspace/automatic/venv/bin/python3" venv="/workspace/automatic/venv"
17:10:16-730147 INFO     Version: app=sd.next updated=2024-06-16 hash=a1f53add branch=dev url=https://github.com/vladmandic/automatic/tree/dev ui=dev
17:10:17-747226 INFO     Updating main repository
17:10:22-315989 INFO     Upgraded to version: a4309110 Mon Jun 17 11:13:55 2024 -0400
17:10:22-332703 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=5.15.0-105-generic python=3.10.12
17:10:22-337750 INFO     HF cache folder: /workspace/.cache/huggingface/hub
17:10:22-345325 INFO     nVidia CUDA toolkit detected: nvidia-smi present

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i cannot reproduce, but i've heard others mention this before.
i've added some extra code to deal with that param, hope it resolves the issue. if not post here and i'll reopen.
