### ISSUE TITLE
[Issue]: FaceID in txt2img input prompt ignore partially?

### ISSUE THREAD

**Issue by DevilsCrypto** [vladmandic/automatic#3259]
### Issue Description

I am not 100% sure if this is a bug, or if this is just how FaceID works. While playing with FaceID i can see that the face structure is maintained but seems to skip or not listen to parts of the prompt (example the skin texture). Even when i add weights into them they are being skipped. Only thing that works is moving parts of the prompt into the beginning, but then other stuff is being ignored. 

During the tests i was comparing the output with the IP Adapter "Full Face", which basically seems to listen better to the prompts.

This is just an ugly example to demonstrate the case.

Input image:
![input](https://github.com/vladmandic/automatic/assets/95778834/eb861baa-090f-44f2-ace6-c6d1c2ccf773)

Inputs:
- Prompt: RAW photo of a 40 years old (Chilean:1.2) female, (Rainbow Colored hair:1.2), (wearing a dress:1.2), Masterpiece, best quality, 35mm photo, highly detailed, uhd, dslr, soft lighting, high quality, film grain, gloomy, highly detailed skin, ultra-detailed, hyperrealism, hyperdetailed, insane details
- Negative: naked, nude, nsfw, bad quality, worst quality, ugly, watermark
- Steps: 8
- Seed: 1968334186
- Sampler: DPM SDE
- CFG scale: 1.5
- Size: 512x768

Here are the FaceID settings:
![faceid_settings](https://github.com/vladmandic/automatic/assets/95778834/4ce62696-8222-4325-865a-c56b95422d2b)

Here are the IP Adapter settings:
![ip_adapter_settings](https://github.com/vladmandic/automatic/assets/95778834/41d88a8a-cbb9-423d-b6c2-102a955ae20e)

This is the output from FaceID, as you can see there is no skin texture:
![output_faceid](https://github.com/vladmandic/automatic/assets/95778834/f9678030-770e-44a9-93df-76a1b801f21a)

This is the output from the ipadapter, as you can see the skin texture is normal as requested.
![output_ip_adapter](https://github.com/vladmandic/automatic/assets/95778834/d2ed838b-7ef5-4166-a43d-1e14fe9c93be)

You can see the original image looks realistic with skin texture, also the ip adapter version has the skin texture, but the faceID example shows just skin without texture.

This same also is applied when i for example in the end of the prompt have the clothing specified, with FaceID it just skips the part it seems, while without it its generated, or when i use ip adapter its also generated.

### Version Platform Description

```
07:39:20-900833 INFO     Starting SD.Next                                                                                                                                                               
07:39:20-903819 INFO     Logger: file="/home/ubuntu/ai_api/automatic_diffusers/sdnext.log" level=INFO size=2953031 mode=append                                                                          
07:39:20-905053 INFO     Python version=3.10.12 platform=Linux bin="/home/ubuntu/ai_api/automatic_diffusers/venv/bin/python3" venv="/home/ubuntu/ai_api/automatic_diffusers/venv"                       
07:39:20-915778 INFO     Version: app=sd.next updated=2024-06-17 hash=549f9ff7 branch=dev url=https://github.com/vladmandic/automatic/tree/dev ui=dev                                                   
07:39:21-192843 INFO     Latest published version: a3ffd478e54c1735a1affc8b4760cef81594c293 2024-06-13T18:57:56Z                                                                                        
07:39:21-195064 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=6.2.0-37-generic python=3.10.12                                                                                          
07:39:21-196141 INFO     HF cache folder: /home/ubuntu/.cache/huggingface/hub                                                                                                                           
07:39:21-197038 INFO     nVidia CUDA toolkit detected: nvidia-smi present   
```

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
internally faceid is a special type of ipadapter - and ipadapters in general work on attention level - they don't care about prompt at all - prompt embeds are still used during overal generate, but during a different part of processing and results are modified much later by ipadapter.

how good or bad or strong is a different ipadapter, well, it depends on ipadapter itself. faceid is a bit over-baked in my opinion.
other than saying this, i'm affraid there is not much i can do here.
