### ISSUE TITLE
[Extension]: ADetailer not being "enabled" via UI

### ISSUE THREAD

**Issue by anothertal3** [vladmandic/automatic#3263]
### Issue Description

ADetailer doesn't appear to get activated via UI anymore. Whether it's "enabled" doesn't make any difference.
(Funny thing though: both tabs are now "enabled" by default and I don't remember saving that config)

I'm using the theme "black-teal".

Step by step:
1. Make sure it's "enabled" via UI 
  ![image](https://github.com/vladmandic/automatic/assets/8721770/250f5e21-39ff-4ce1-aed5-e7022e10d9ed)
2. Prepare breakpoint in "!adetailer.py" and execute image generation. Apparently, "enabled" is not set to "True" anymore?
  ![image](https://github.com/vladmandic/automatic/assets/8721770/7cdaa2d4-89ad-44d7-9b76-d492bd5a7722)
3. ADetailer will thus not execute

Further notes:
- There are no issues/errors within the log
- It's working via API (i.e., the args are set manually by an external request)

### Version Platform Description

Python version=3.10.11 platform=Windows
Version: app=sd.next updated=2024-06-13 hash=a3ffd478 branch=master                          url=https://github.com/vladmandic/automatic/tree/master ui=main
Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows                          release=Windows-10-10.0.22631-SP0 python=3.10.11
nVidia CUDA toolkit detected: nvidia-smi present
Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info', 'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'a1111-sd-webui-tagcomplete', 'adetailer', 'sd-dynamic-prompts', 'sd-webui-controlnet', 'ultimate-upscale-for-automatic1111']

Browser: Chrome 125
ADetailer: v24.6.0

### URL link of the extension

https://github.com/Bing-su/adetailer

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
adetailer recently updated ui controls they use and those were not available in sdnext.
support was added in sdnext dev branch few days ago for standardui and we're still looking at modernui solution: https://github.com/BinaryQuantumSoul/sdnext-modernui/issues/70

since you're using standardui, dev branch addresses this - it will be merged to master soon.

**Comment by anothertal3** [comment]
Understood. Thank you for the quick explanation. Looking forward to the fix then.

**Comment by MysticDaedra** [comment]
Did this get merged? I suspect I'm having the same issue. On latest dev (0b680777), adetailer is enabled, but is not being included in the generation.
