### ISSUE TITLE
[Feature]: Add the ability to select Extra Networks (loras at this point) to xyz script

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#3266]
### Feature description

It's clumsy to use S/R for that and takes a lot longer to do when we could just select them from a dropdown list like we do models, though there would have to be a way to indicate the strength they were each being applied at since it's rarely 1.0, not sure on how to manage that, but definitely up for confab on subject.

**Comment by vladmandic** [comment]
you either want dropdown with list of loras or you want a string where you can type names with strength - pick one.

**Comment by Aptronymist** [comment]
> you either want dropdown with list of loras or you want a string where you can type names with strength - pick one.

I would say a dropdown, but I'm unsure how that could go along with strengths ui-wise. If that leaves us with typing it in, then so be it.

**Comment by vladmandic** [comment]
also, in either case forget about trigger words - doing that is basically lets do prompt s/r.

**Comment by Aptronymist** [comment]
> also, in either case forget about trigger words - doing that is basically lets do prompt s/r.

That hadn't even crossed my mind tbh

**Comment by vladmandic** [comment]
done. applied strength can be chosen in settings -> extra networks -> default strength.
