### ISSUE TITLE
[Issue]: When using PAG, after running ADetailer the wrong pipeline is restored

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3269]
### Issue Description

When running ADetailer after setting the pipeline to PAG, the pipeline class is wrongly reset to `StableXLDiffusionPipeline`.  Hence, PAG is applied only to the first image of a batch. 

This can be seen in the log when an image after the first is generated:

```
00:14:14-162989 INFO     Base: class=StableDiffusionXLPipeline  
```

When it should be (from the first image in the pipeline)

```
00:06:03-545161 INFO     Base: class=StableDiffusionXLPAGPipeline   
```

Note that this only occurs if ADetailer is on. It will not happen with Face Hires enabled.

### Version Platform Description

SD.Next dev as of bbaec297207b74a96d6a3bc1d5741e22f444bf6e. 

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
