### ISSUE TITLE
[Issue]: Wrong order in pipeline restore after ADetailer breaks extension with batch counts > 1

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3271]
### Issue Description

This is filed as a bug as it's a problem in SD.Next that it is unintentionally triggered by ADetailer. The example here is for SDXL processing: I'm not sure it occurs with SD or other pipelines.

The base is a txt2img job, with ADetailer enabled. Batch counts should be > 1 or this won't be triggered.

What happens is this:

1. The pipeline runs (PAG/regular/whatever) with the base class instance specified
2. ADetailer switches it to the inpaint pipeline (at least w/SDXL) and does it job
3. New image? No problem, let's start a new generation
4. Task is `DiffusersTaskType.TEXT_2_IMAGE` but the pipeline is still the `Inpaint` pipeline class, it hasn't been switched yet to the regular base class (e.g. `StableDiffusionXLPipeline`)
5. Hence, the code strips the `requires_aestethics_score` attribute **from the Inpaint pipeline instance**
6. On the second run of ADetailer, `pipeline_stable_diffusion_xl_inpaint` will be reached, it will actually require  the attribute
7. Kaboom, `AttributeError`

### Version Platform Description

Dev as of 3856cb213aee391680af0d3a433f8682fcd8a713.

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
