### ISSUE TITLE
[Issue]: Setting VAE to None doesn't unload VAE in memory.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#3272]
### Issue Description

If I've genned something with an SDXL model and explicit SDXL VAE, then I switch to an SD15 model and set the VAE to None, the SDXL VAE doesn't unload.

### Version Platform Description

```
Python version=3.10.11 platform=Windows bin="E:\sddev\venv\Scripts\python.exe"
venv="E:\sddev\venv"
Version: app=sd.next updated=2024-06-22 hash=3856cb21 branch=dev
url=https://github.com/vladmandic/automatic/tree/dev ui=dev
Branch sync failed: sdnext=dev ui=dev
Updating main repository
Upgraded to version: e8165c3d Sat Jun 22 18:40:06 2024 -0400
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel system=Windows
release=Windows-10-10.0.19045-SP0 python=3.10.11
AMD ROCm toolkit detected
ROCm agents detected: ['gfx1032']
ROCm agent used by default: idx=0 gpu=gfx1032 arch=navi2x
ROCm version detected: None
ZLUDA support: experimental
Using ZLUDA in C:\Utils\ZLUDA
```

### Backend

Diffusers

### Branch

Dev

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
done.
new behavior is when loading explicit vae, original vae state is saved. when setting vae to none (or automatic which resolves to none), it will restore original vae.
