### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by AbramovS1** [vladmandic/automatic#328]
### Issue Description

After receiving the ip, it gives this text "To create a public link, set 'share=True' to 'launch()'.
Initializing Middleware
I can't work without a checkpoint"

I have crawled through all the scripts and have not found this parameter anywhere

### Version Platform Description

Win11

**Comment by vladmandic** [comment]
do you have a checkpoint available?
if not, it will ask you to download a default checkpoint.
as it is, i don't know what is the issue?

and post actual console log, not one line

**Comment by AbramovS1** [comment]
![image](https://user-images.githubusercontent.com/56324569/233533862-3648ce76-34a6-409f-a22b-0e30d3fbbddb.png)
And so every time

**Comment by vladmandic** [comment]
it asked you to download default model and you answered "n", so it didn't do it. 
and then it aborted since there are no models found that it can use.
i'm not sure what do you expect?

**Comment by AbramovS1** [comment]
![image](https://user-images.githubusercontent.com/56324569/233536918-b46a5fdb-bdb8-4e11-bea9-612b0ac0759c.png)
As you can see the same problem when you try to download a model

**Comment by vladmandic** [comment]
which version? did you upgrade to latest? 
there was a problem where download was not initiated when choosing "y", but that was resolved earlier today.

**Comment by AbramovS1** [comment]
I installed it yesterday and it hasn't been updated yet

**Comment by vladmandic** [comment]
then its a known and solved issue.
