### ISSUE TITLE
[Feature]: Adds the identification of model subdirectories

### ISSUE THREAD

**Issue by alex13by** [vladmandic/automatic#3284]
### Feature description

When I added the directory location for the comfyui model, I found that the subdirectories were not recognized, which was very inconvenient

**Comment by vladmandic** [comment]
English only please.

**Comment by vladmandic** [comment]
pls provide more information as use of subfolders inside main models folder is quite common and fully supported.

**Comment by alex13by** [comment]
before that the relative path was used in addition to the base model, so it could not be recognized. Thank you very much for your reply.It's been solved.
