### ISSUE TITLE
[Issue]: OpenPose XL filename changed on HuggingFace

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#3289]
### Issue Description

It appears the .safetensors filename is now OpenPoseXL2.safetensors on https://huggingface.co/thibaud/controlnet-openpose-sdxl-1.0/tree/main

### Version Platform Description

```
Starting SD.Next
Logger: file="E:\sddev\sdnext.log" level=DEBUG size=65 mode=create
Python version=3.10.11 platform=Windows bin="E:\sddev\venv\Scripts\python.exe"
venv="E:\sddev\venv"
Version: app=sd.next updated=2024-06-23 hash=4d0ba869 branch=dev
url=https://github.com/vladmandic/automatic/tree/dev ui=dev
Branch sync failed: sdnext=dev ui=dev
Updating main repository
Upgraded to version: b429a6bb Tue Jun 25 15:08:10 2024 -0400
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel system=Windows
release=Windows-10-10.0.19045-SP0 python=3.10.11
```

### Relevant log output

```shell
6:43:42-599760 ERROR    An error occurred while trying to fetch thibaud/controlnet-openpose-sdxl-1.0:
                         thibaud/controlnet-openpose-sdxl-1.0 does not appear to have a file named
                         diffusion_pytorch_model.safetensors.
```

### Backend

Diffusers

### Branch

Dev

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev.
![image](https://github.com/vladmandic/automatic/assets/57876960/2e6b1c42-02db-4c38-b60b-13bc0a5da3d2)
