### ISSUE TITLE
[Issue]: NansException in VAE

### ISSUE THREAD

**Issue by Metachs** [vladmandic/automatic#329]
### Issue Description

After updating earlier today, I started getting "NansException: A tensor with all NaNs was produced in VAE" when running img2img at high resolutions. I normally use --no-half-vae to prevent this, but this is no longer working.

As far as I can tell, it looks like [commit:0e71441](https://github.com/vladmandic/automatic/commit/0e7144186d49601356cf890e2dabc2d7f5930801) broke no-half-vae by removing the line 
`devices.dtype_vae = torch.float32 if shared.cmd_opts.no_half or shared.cmd_opts.no_half_vae else torch.float16`
from load_model_weights in sd_model.py.

Adding the line back in so devices.dtype_vae gets set to float32 fixed the problem entirely, and removing it brings the problem back.

### Version Platform Description

commit: [df424d6d](https://github.com/vladmandic/automatic/commit/df424d6d5123628741f34599d58e95c7c83b0d23)
Windows

**Comment by vladmandic** [comment]
`--no-half-vae` is now option in UI -> Settings -> CUDA Params  
(and so are pretty much all CUDA options), did you try that?

**Comment by Metachs** [comment]
Yes, obviously I was using the options setting, the launch options just crash the program now.

**Comment by vladmandic** [comment]
ok, can you tell me full details so i can try to repoduce? model, vae, full geninfo params

**Comment by Metachs** [comment]
It's the old problem with the NAI based VAEs, it happens with any model, when using one of the effected VAE's , eg https://huggingface.co/NoCrypt/blessed_vae/tree/main

It happens every time I run img2img at a resolution of 1280x1280 with a batch size of 4 while using the linked VAE. using the params in the following image. 

![00095-2896149618-](https://user-images.githubusercontent.com/9453185/233543566-35080c6e-a295-4b04-89e1-42ac7549ce74.png)

**Comment by FirstZero** [comment]
I can confirm adding back this line fixes it.
I have had exactly the same problems. Before I could always fix the problem with --no-half-vae. But since the line `devices.dtype_vae = torch.float32 if shared.cmd_opts.no_half or shared.cmd_opts.no_half_vae else torch.float16` got removed I keep getting NaN errors again.

**Comment by vladmandic** [comment]
i just changed logic, see <https://github.com/vladmandic/automatic/blob/cf277e7326aa72a5f6a369da06fd47c71faf4a5c/modules/devices.py#L56>

this should behave the same as previous logic, but allow finer tuning as i wanted for.
if it doesn't post here and i'll reopen.

**Comment by vladmandic** [comment]
there there are still issues, lets continue in #374
