### ISSUE TITLE
[Issue]: Lightbox and Gallery buttons not showing properly

### ISSUE THREAD

**Issue by phreeck988** [vladmandic/automatic#3290]
### Issue Description

When I generate an image and click to enlarge it in the full screen lightbox none of the controls at the top load the proper icons. They are just hollow squares.

![Screenshot 2024-06-26 020638](https://github.com/vladmandic/automatic/assets/89193974/fe37e32f-ff9b-4ef3-958a-822492129d06)

Every other tab but the Gallery tab seems to be fine
![Screenshot 2024-06-26 030109](https://github.com/vladmandic/automatic/assets/89193974/4e0e02c6-2b3b-46ad-8d7c-91f4ee4b3e4c)

Using inspect element shows: 
![Screenshot 2024-06-26 021022](https://github.com/vladmandic/automatic/assets/89193974/8d27f693-a22d-4bdd-9840-54ebc11f956a)

Vivaldi browser console:
![Screenshot 2024-06-26 031014](https://github.com/vladmandic/automatic/assets/89193974/5469933a-20cc-4432-8578-35744c154fdb)
![Screenshot 2024-06-26 031207](https://github.com/vladmandic/automatic/assets/89193974/6f60991f-263a-4d93-a8de-664f2bf8394e)

Reproduces in Edge but Edge's console also includes this notification that doesn't show in Vivaldi's console
![Screenshot 2024-06-26 031536](https://github.com/vladmandic/automatic/assets/89193974/3010cb76-b6fc-4475-b9d6-fa2d9b09ef79)

Link directs to information about LazyLoad which appears to be a chromium feature that defers loading certain elements until said feature thinks they'll be viewed.

No errors in the Terminal for SDnext itself

I have done refreshes, reinstalls, upgrades, I have 3 separate installation folders, they all have the same issue.

I don't know if this is a SDnext, Gradio issue, or maybe it's that LazyLoad is being overzealous?

### Version Platform Description

Python version 3.10.9 on Windows 11
Version: 94f6f0db 2024-6-24
nVidia CUDA toolkit detected
Torch 2.3.1+cu121
Torch backend: nVidia CUDA 12.1 cuDNN 8907
Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 12288 Arch (8, 6) Cores 70
Extensions: disabled=[]
Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
Gradio: 3.43.2
Vivaldi browser

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
lazy load is not an issue - it will be used if available, no harm if its not.
the icons are referenced from the font file - which means that font is not loaded correctly.
- which theme are you using? 
- go through browsers inspector -> network panel and search for font requests - what does it say?

**Comment by phreeck988** [comment]
I usually use Dark theme with Black - Teal but I switched and tried a few others and it didn't seem to help.

Network tab didn't show any font related requests.
![Screenshot 2024-06-26 121657](https://github.com/vladmandic/automatic/assets/89193974/219c84a3-307b-425e-ab6a-8be5f5a827d9)
![Screenshot 2024-06-26 121707](https://github.com/vladmandic/automatic/assets/89193974/8b846960-9c21-4626-b6db-c0311af8ec7a)

**Comment by vladmandic** [comment]
hmm...one possibiliy is that your system already has a font with that name, so browser decides it doesn't need to download it
font definition is this:
```css
@font-face { font-family: 'NotoSans'; font-display: swap; font-style: normal; font-weight: 100; src: local('NotoSans'), url('notosans-nerdfont-regular.ttf') }
```
can you check if you have `NotoSans` installed in your OS and possibly remove it?

**Comment by phreeck988** [comment]
Thanks, had to restart PC so it stopped saying the font was in use but it eventually let me uninstall them and now it works.

![Screenshot 2024-06-26 153903](https://github.com/vladmandic/automatic/assets/89193974/bead703c-0f19-4e11-a4c4-91f9ea485970)
![Screenshot 2024-06-26 153856](https://github.com/vladmandic/automatic/assets/89193974/29003187-0a6d-4cca-8948-d484b56e8718)
