### ISSUE TITLE
[Feature]: Python 3.12.4

### ISSUE THREAD

**Issue by GTP95** [vladmandic/automatic#3294]
### Feature description

Is there any known incompatibility with Python 3.12.4? If not, where can I find the version check, so that I can try to disable it?
Thank you for your help,

GTP

### Version Platform Description

OS: Arch Linux

**Comment by vladmandic** [comment]
python 3.12.4 is supposed to be a service pack only, but it breaks pydantic. you can search here in issues for more details.
python 3.12.3 is supported although any python 3.12 is still very experimental due to many 3rd party packages not being fully available yet. python 3.11 is recommended.
