### ISSUE TITLE
[Issue] : No server initialization using Zluda SDnext

### ISSUE THREAD

**Issue by Zurak69** [vladmandic/automatic#3301]
No server localhost or initialization using Zluda, bit new to this, any help would be appreciated, the UI doesnt launch and I followed the steps on the [Zluda Wiki](https://github.com/vladmandic/automatic/wiki/ZLUDA) 
Posting my CMD here.
Stuck on the press any key to continue without anything launching or a localhost provided to use SDnext.

C:\Users\Ahmed\automatic>webui.bat --use-zluda --debug --autolaunch
Using VENV: C:\Users\Ahmed\automatic\venv
20:15:41-505988 INFO     Starting SD.Next
20:15:41-508105 INFO     Logger: file="C:\Users\Ahmed\automatic\sdnext.log" level=DEBUG size=65 mode=create
20:15:41-508105 INFO     Python version=3.10.11 platform=Windows bin="C:\Users\Ahmed\automatic\venv\Scripts\python.exe"
                         venv="C:\Users\Ahmed\automatic\venv"
20:15:41-638199 INFO     Version: app=sd.next updated=2024-06-24 hash=94f6f0db branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
20:15:41-799656 DEBUG    Branch sync failed: sdnext=master ui=main
20:15:42-122696 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
20:15:42-125782 DEBUG    Setting environment tuning
20:15:42-125782 INFO     HF cache folder: C:\Users\Ahmed\.cache\huggingface\hub
20:15:42-127010 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
20:15:42-127010 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
20:15:42-128072 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
20:15:42-131583 INFO     Python version=3.10.11 platform=Windows bin="C:\Users\Ahmed\automatic\venv\Scripts\python.exe"
                         venv="C:\Users\Ahmed\automatic\venv"
20:15:42-134876 INFO     AMD ROCm toolkit detected
20:15:43-198228 DEBUG    ROCm agents detected: ['gfx1100', 'gfx1100']
20:15:43-199733 DEBUG    ROCm agent used by default: idx=0 gpu=gfx1100 arch=navi3x
20:15:43-211864 DEBUG    ROCm version detected: None
20:15:43-212887 WARNING  ZLUDA support: experimental
20:15:43-245800 INFO     Using ZLUDA in C:\Users\Ahmed\automatic\.zluda
20:15:43-246799 INFO     Install: package="torch==2.3.0 torchvision --index-url https://download.pytorch.org/whl/cu118"
20:15:43-246799 DEBUG    Running: pip="install --upgrade torch==2.3.0 torchvision --index-url
                         https://download.pytorch.org/whl/cu118 "
20:17:00-391757 DEBUG    Package not found: onnx
20:17:00-392768 INFO     Install: package="onnx"
20:17:00-394082 DEBUG    Running: pip="install --upgrade onnx "
20:17:07-559023 DEBUG    Package not found: onnxruntime
20:17:07-560529 INFO     Install: package="onnxruntime"
20:17:07-560529 DEBUG    Running: pip="install --upgrade onnxruntime "
20:17:11-215633 INFO     Installing requirements: this make take a while...
20:17:11-216631 DEBUG    Running: pip="install -r requirements.txt "
20:18:54-620699 INFO     Verifying requirements
20:18:54-621943 WARNING  Package version mismatch: setuptools 65.5.0 required 69.5.1
20:18:54-623173 INFO     Install: package="setuptools==69.5.1"
20:18:54-624375 DEBUG    Running: pip="install --upgrade setuptools==69.5.1 "
20:18:56-640026 DEBUG    Package not found: patch-ng
20:18:56-641065 INFO     Install: package="patch-ng"
20:18:56-642066 DEBUG    Running: pip="install --upgrade patch-ng "
20:18:57-895050 DEBUG    Package not found: anyio
20:18:57-896068 INFO     Install: package="anyio"
20:18:57-896068 DEBUG    Running: pip="install --upgrade anyio "
20:18:59-251159 DEBUG    Package not found: addict
20:18:59-252227 INFO     Install: package="addict"
20:18:59-253526 DEBUG    Running: pip="install --upgrade addict "
20:19:00-517260 DEBUG    Package not found: astunparse
20:19:00-518267 INFO     Install: package="astunparse"
20:19:00-518267 DEBUG    Running: pip="install --upgrade astunparse "
20:19:01-831062 DEBUG    Package not found: clean-fid
20:19:01-832058 INFO     Install: package="clean-fid"
20:19:01-833058 DEBUG    Running: pip="install --upgrade clean-fid "
20:19:03-127912 DEBUG    Package not found: filetype
20:19:03-129987 INFO     Install: package="filetype"
20:19:03-129987 DEBUG    Running: pip="install --upgrade filetype "
20:19:04-418075 DEBUG    Package not found: future
20:19:04-419075 INFO     Install: package="future"
20:19:04-419075 DEBUG    Running: pip="install --upgrade future "
20:19:05-712524 DEBUG    Package not found: GitPython
20:19:05-713523 INFO     Install: package="GitPython"
20:19:05-714521 DEBUG    Running: pip="install --upgrade GitPython "
20:19:07-114352 DEBUG    Package not found: httpcore
20:19:07-115353 INFO     Install: package="httpcore"
20:19:07-116353 DEBUG    Running: pip="install --upgrade httpcore "
20:19:08-710077 DEBUG    Package not found: inflection
20:19:08-710077 INFO     Install: package="inflection"
20:19:08-711404 DEBUG    Running: pip="install --upgrade inflection "
20:19:10-015722 DEBUG    Package not found: jsonmerge
20:19:10-016721 INFO     Install: package="jsonmerge"
20:19:10-017720 DEBUG    Running: pip="install --upgrade jsonmerge "
20:19:11-308353 DEBUG    Package not found: kornia
20:19:11-309858 INFO     Install: package="kornia"
20:19:11-309858 DEBUG    Running: pip="install --upgrade kornia "
20:19:12-601373 DEBUG    Package not found: lark
20:19:12-602372 INFO     Install: package="lark"
20:19:12-602372 DEBUG    Running: pip="install --upgrade lark "
20:19:13-898667 DEBUG    Package not found: lpips
20:19:13-898667 INFO     Install: package="lpips"
20:19:13-900172 DEBUG    Running: pip="install --upgrade lpips "
20:19:15-186553 DEBUG    Package not found: omegaconf
20:19:15-187562 INFO     Install: package="omegaconf"
20:19:15-188566 DEBUG    Running: pip="install --upgrade omegaconf "
20:19:16-524650 DEBUG    Package not found: optimum
20:19:16-525648 INFO     Install: package="optimum"
20:19:16-525648 DEBUG    Running: pip="install --upgrade optimum "
20:19:18-136693 DEBUG    Package not found: piexif
20:19:18-137694 INFO     Install: package="piexif"
20:19:18-137694 DEBUG    Running: pip="install --upgrade piexif "
20:19:19-530207 DEBUG    Package not found: pyyaml
20:19:19-530712 INFO     Install: package="pyyaml"
20:19:19-531797 DEBUG    Running: pip="install --upgrade pyyaml "
20:19:21-042002 DEBUG    Package not found: resize-right
20:19:21-042999 INFO     Install: package="resize-right"
20:19:21-043999 DEBUG    Running: pip="install --upgrade resize-right "
20:19:22-494481 DEBUG    Package not found: toml
20:19:22-495485 INFO     Install: package="toml"
20:19:22-496489 DEBUG    Running: pip="install --upgrade toml "
20:19:23-790207 DEBUG    Package not found: voluptuous
20:19:23-790207 INFO     Install: package="voluptuous"
20:19:23-791213 DEBUG    Running: pip="install --upgrade voluptuous "
20:19:25-090209 DEBUG    Package not found: yapf
20:19:25-091363 INFO     Install: package="yapf"
20:19:25-092394 DEBUG    Running: pip="install --upgrade yapf "
20:19:26-431887 DEBUG    Package not found: fasteners
20:19:26-433224 INFO     Install: package="fasteners"
20:19:26-434225 DEBUG    Running: pip="install --upgrade fasteners "
20:19:27-812667 DEBUG    Package not found: orjson
20:19:27-813685 INFO     Install: package="orjson"
20:19:27-814705 DEBUG    Running: pip="install --upgrade orjson "
20:19:29-237307 DEBUG    Package not found: invisible-watermark
20:19:29-238307 INFO     Install: package="invisible-watermark"
20:19:29-239307 DEBUG    Running: pip="install --upgrade invisible-watermark "
20:19:30-524144 DEBUG    Package not found: pi-heif
20:19:30-525144 INFO     Install: package="pi-heif"
20:19:30-525144 DEBUG    Running: pip="install --upgrade pi-heif "
20:19:31-870291 DEBUG    Package not found: diffusers
20:19:31-871438 INFO     Install: package="diffusers==0.29.1"
20:19:31-872462 DEBUG    Running: pip="install --upgrade diffusers==0.29.1 "
20:19:33-212418 DEBUG    Package not found: safetensors
20:19:33-213504 INFO     Install: package="safetensors==0.4.3"
20:19:33-214502 DEBUG    Running: pip="install --upgrade safetensors==0.4.3 "
20:19:34-688111 DEBUG    Package not found: tensordict
20:19:34-689217 INFO     Install: package="tensordict==0.1.2"
20:19:34-689217 DEBUG    Running: pip="install --upgrade tensordict==0.1.2 "
20:19:36-086568 DEBUG    Package not found: peft
20:19:36-086568 INFO     Install: package="peft==0.11.1"
20:19:36-087722 DEBUG    Running: pip="install --upgrade peft==0.11.1 "
20:19:37-407786 DEBUG    Package not found: httpx
20:19:37-408113 INFO     Install: package="httpx==0.24.1"
20:19:37-409112 DEBUG    Running: pip="install --upgrade httpx==0.24.1 "
20:19:39-052177 DEBUG    Package not found: compel
20:19:39-052177 INFO     Install: package="compel==2.0.2"
20:19:39-053666 DEBUG    Running: pip="install --upgrade compel==2.0.2 "
20:19:40-399947 DEBUG    Package not found: torchsde
20:19:40-401102 INFO     Install: package="torchsde==0.2.6"
20:19:40-402108 DEBUG    Running: pip="install --upgrade torchsde==0.2.6 "
20:19:41-714053 DEBUG    Package not found: open-clip-torch
20:19:41-715054 INFO     Install: package="open-clip-torch"
20:19:41-716053 DEBUG    Running: pip="install --upgrade open-clip-torch "
20:19:43-030178 DEBUG    Package not found: clip-interrogator
20:19:43-031342 INFO     Install: package="clip-interrogator==0.6.0"
20:19:43-032489 DEBUG    Running: pip="install --upgrade clip-interrogator==0.6.0 "
20:19:44-336868 DEBUG    Package not found: antlr4-python3-runtime
20:19:44-337868 INFO     Install: package="antlr4-python3-runtime==4.9.3"
20:19:44-338869 DEBUG    Running: pip="install --upgrade antlr4-python3-runtime==4.9.3 "
20:19:45-611026 WARNING  Package version mismatch: requests 2.32.3 required 2.31.0
20:19:45-612030 INFO     Install: package="requests==2.31.0"
20:19:45-613035 DEBUG    Running: pip="install --upgrade requests==2.31.0 "
20:19:46-971406 DEBUG    Package not found: tqdm
20:19:46-972426 INFO     Install: package="tqdm==4.66.4"
20:19:46-972426 DEBUG    Running: pip="install --upgrade tqdm==4.66.4 "
20:19:48-380289 DEBUG    Package not found: accelerate
20:19:48-381301 INFO     Install: package="accelerate==0.30.1"
20:19:48-381301 DEBUG    Running: pip="install --upgrade accelerate==0.30.1 "
20:19:49-694409 DEBUG    Package not found: opencv-contrib-python-headless
20:19:49-695521 INFO     Install: package="opencv-contrib-python-headless==4.9.0.80"
20:19:49-696621 DEBUG    Running: pip="install --upgrade opencv-contrib-python-headless==4.9.0.80 "
20:19:51-024360 DEBUG    Package not found: einops
20:19:51-025470 INFO     Install: package="einops==0.4.1"
20:19:51-026678 DEBUG    Running: pip="install --upgrade einops==0.4.1 "
20:19:52-310206 DEBUG    Package not found: gradio
20:19:52-310206 INFO     Install: package="gradio==3.43.2"
20:19:52-311211 DEBUG    Running: pip="install --upgrade gradio==3.43.2 "
20:19:53-787452 DEBUG    Package not found: huggingface_hub
20:19:53-788460 INFO     Install: package="huggingface_hub==0.23.2"
20:19:53-788460 DEBUG    Running: pip="install --upgrade huggingface_hub==0.23.2 "
20:19:55-198827 DEBUG    Package not found: numexpr
20:19:55-200331 INFO     Install: package="numexpr==2.8.8"
20:19:55-201335 DEBUG    Running: pip="install --upgrade numexpr==2.8.8 "
20:19:56-583388 WARNING  Package version mismatch: numpy 1.26.3 required 1.26.4
20:19:56-585391 INFO     Install: package="numpy==1.26.4"
20:19:56-585391 DEBUG    Running: pip="install --upgrade numpy==1.26.4 "
20:19:57-999058 DEBUG    Package not found: numba
20:19:58-000058 INFO     Install: package="numba==0.59.1"
20:19:58-001369 DEBUG    Running: pip="install --upgrade numba==0.59.1 "
20:19:59-424377 DEBUG    Package not found: blendmodes
20:19:59-425375 INFO     Install: package="blendmodes"
20:19:59-425375 DEBUG    Running: pip="install --upgrade blendmodes "
20:20:00-712990 DEBUG    Package not found: scipy
20:20:00-713990 INFO     Install: package="scipy"
20:20:00-714990 DEBUG    Running: pip="install --upgrade scipy "
20:20:02-069309 DEBUG    Package not found: pandas
20:20:02-070309 INFO     Install: package="pandas"
20:20:02-070813 DEBUG    Running: pip="install --upgrade pandas "
20:20:03-538794 WARNING  Package version mismatch: protobuf 5.27.2 required 4.25.3
20:20:03-538794 INFO     Install: package="protobuf==4.25.3"
20:20:03-540298 DEBUG    Running: pip="install --upgrade protobuf==4.25.3 "
20:20:04-965481 DEBUG    Package not found: pytorch_lightning
20:20:04-966479 INFO     Install: package="pytorch_lightning==1.9.4"
20:20:04-966479 DEBUG    Running: pip="install --upgrade pytorch_lightning==1.9.4 "
20:20:06-306730 DEBUG    Package not found: tokenizers
20:20:06-307730 INFO     Install: package="tokenizers==0.19.1"
20:20:06-308731 DEBUG    Running: pip="install --upgrade tokenizers==0.19.1 "
20:20:07-695937 DEBUG    Package not found: transformers
20:20:07-696974 INFO     Install: package="transformers==4.41.2"
20:20:07-696974 DEBUG    Running: pip="install --upgrade transformers==4.41.2 "
20:20:09-006239 WARNING  Package version mismatch: urllib3 2.2.2 required 1.26.19
20:20:09-007237 INFO     Install: package="urllib3==1.26.19"
20:20:09-008375 DEBUG    Running: pip="install --upgrade urllib3==1.26.19 "
20:20:10-285918 WARNING  Package version mismatch: Pillow 10.2.0 required 10.3.0
20:20:10-286918 INFO     Install: package="Pillow==10.3.0"
20:20:10-286918 DEBUG    Running: pip="install --upgrade Pillow==10.3.0 "
20:20:11-639374 DEBUG    Package not found: timm
20:20:11-640374 INFO     Install: package="timm==0.9.16"
20:20:11-641850 DEBUG    Running: pip="install --upgrade timm==0.9.16 "
20:20:12-957316 DEBUG    Package not found: pydantic
20:20:12-958331 INFO     Install: package="pydantic==1.10.15"
20:20:12-958331 DEBUG    Running: pip="install --upgrade pydantic==1.10.15 "
20:20:14-335677 WARNING  Package version mismatch: typing-extensions 4.9.0 required 4.11.0
20:20:14-336789 INFO     Install: package="typing-extensions==4.11.0"
20:20:14-336789 DEBUG    Running: pip="install --upgrade typing-extensions==4.11.0 "
20:20:15-692616 DEBUG    Package not found: torchdiffeq
20:20:15-693659 INFO     Install: package="torchdiffeq"
20:20:15-694688 DEBUG    Running: pip="install --upgrade torchdiffeq "
20:20:16-976010 DEBUG    Package not found: dctorch
20:20:16-976010 INFO     Install: package="dctorch"
20:20:16-977010 DEBUG    Running: pip="install --upgrade dctorch "
20:20:18-266187 DEBUG    Package not found: scikit-image
20:20:18-267197 INFO     Install: package="scikit-image"
20:20:18-268221 DEBUG    Running: pip="install --upgrade scikit-image "
20:20:19-568496 INFO     Verifying packages
20:20:19-568496 INFO     Install: package="git+https://github.com/openai/CLIP.git"
20:20:19-570001 DEBUG    Running: pip="install --upgrade git+https://github.com/openai/CLIP.git "
20:20:23-524290 INFO     Startup: standard
20:20:23-525290 INFO     Verifying submodules
20:20:25-365747 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
20:20:25-430329 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
20:20:25-491323 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
20:20:25-581073 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
20:20:25-582411 DEBUG    Submodule: extensions-builtin/sdnext-modernui / main
20:20:25-656864 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
20:20:25-719942 DEBUG    Submodule: modules/k-diffusion / master
20:20:25-806916 DEBUG    Git detached head detected: folder="wiki" reattach=master
20:20:25-807915 DEBUG    Submodule: wiki / master
20:20:25-854407 DEBUG    Register paths
20:20:25-911350 DEBUG    Installed packages: 168
20:20:25-912350 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
20:20:26-068661 DEBUG    Running extension installer:
                         C:\Users\Ahmed\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
20:20:30-090038 INFO     Extension installed packages: sd-webui-agent-scheduler ['greenlet==3.0.3',
                         'SQLAlchemy==2.0.31']
20:20:30-147131 DEBUG    Running extension installer:
                         C:\Users\Ahmed\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
20:20:35-710789 INFO     Extension installed packages: stable-diffusion-webui-rembg
                         ['opencv-python-headless==4.10.0.84', 'rembg==2.0.57', 'pooch==1.8.2', 'PyMatting==1.1.12']
20:20:35-711786 DEBUG    Extensions all: []
20:20:35-711786 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
20:20:35-715297 INFO     Verifying requirements
20:20:35-716298 DEBUG    Setup complete without errors: 1719688836
20:20:35-718421 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
20:20:35-719424 DEBUG    Starting module: <module 'webui' from 'C:\\Users\\Ahmed\\automatic\\webui.py'>
20:20:35-720421 INFO     Command line args: ['--use-zluda', '--debug', '--autolaunch'] autolaunch=True use_zluda=True
                         debug=True
20:20:35-721712 DEBUG    Env flags: []
20:20:43-890337 INFO     Load packages: {'torch': '2.3.0+cu118', 'diffusers': '0.29.1', 'gradio': '3.43.2'}
20:20:45-021623 INFO     VRAM: Detected=19.98 GB Optimization=none
20:20:45-023850 DEBUG    Read: file="config.json" json=32 bytes=1391 time=0.000
20:20:45-024871 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Dynamic Attention BMM"
                         mode=no_grad
20:20:45-035884 INFO     Device: device=AMD Radeon RX 7900 XT [ZLUDA] n=1 arch=compute_37 cap=(8, 8) cuda=11.8
                         cudnn=8700 driver=
20:20:45-037883 DEBUG    Read: file="html\reference.json" json=43 bytes=24978 time=0.000
Press any key to continue . . .

**Comment by brknsoul** [comment]
I had a similar problem;
Edit your config.json file and edit or add
`  "torch_gc_threshold": 10,`
between the `{}`s

**Comment by Zurak69** [comment]
> I had a similar problem, this happens when GC is set to 0. Edit your config.json file and edit or add ` "torch_gc_threshold": 10,` between the `{}`s

I tried it, still does not launch, I am using 23.Q4 pro drivers, using adrenaline drivers bricks the whole process as soon as it reached ROCm detected. 

Here is the log after trying this.

[config.json](https://github.com/user-attachments/files/16042275/config.json)

23:02:40-759163 INFO     Starting SD.Next
23:02:40-761331 INFO     Logger: file="C:\Users\Ahmed\Downloads\ZLUDA-windows-amd64\zluda\automatic\sdnext.log"
                         level=DEBUG size=65 mode=create
23:02:40-762333 INFO     Python version=3.10.11 platform=Windows
                         bin="C:\Users\Ahmed\Downloads\ZLUDA-w


indows-amd64\zluda\automatic\venv\Scripts\python.exe"
                         venv="C:\Users\Ahmed\Downloads\ZLUDA-windows-amd64\zluda\automatic\venv"
23:02:40-909916 INFO     Version: app=sd.next updated=2024-06-24 hash=94f6f0db branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
23:02:41-071884 DEBUG    Branch sync failed: sdnext=master ui=main
23:02:41-218792 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
23:02:41-219799 DEBUG    Setting environment tuning
23:02:41-221240 INFO     HF cache folder: C:\Users\Ahmed\.cache\huggingface\hub
23:02:41-221240 DEBUG    Torch allocator: "garbage_collection_threshold:0.10,max_split_size_mb:512"
23:02:41-222240 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
23:02:41-222240 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
23:02:41-227536 INFO     Python version=3.10.11 platform=Windows
                         bin="C:\Users\Ahmed\Downloads\ZLUDA-windows-amd64\zluda\automatic\venv\Scripts\python.exe"
                         venv="C:\Users\Ahmed\Downloads\ZLUDA-windows-amd64\zluda\automatic\venv"
23:02:41-230551 INFO     AMD ROCm toolkit detected
23:02:42-285696 DEBUG    ROCm agents detected: ['gfx1100', 'gfx1100']
23:02:42-286835 DEBUG    ROCm agent used by default: idx=0 gpu=gfx1100 arch=navi3x
23:02:42-407860 DEBUG    ROCm version detected: 5.7
23:02:42-407860 WARNING  ZLUDA support: experimental
23:02:42-441475 INFO     Using ZLUDA in C:\Users\Ahmed\Downloads\ZLUDA-windows-amd64\zluda\automatic\.zluda
23:02:42-546561 INFO     Verifying requirements
23:02:42-549562 INFO     Verifying packages
23:02:42-582310 DEBUG    Repository update time: Mon Jun 24 20:35:47 2024
23:02:42-583335 INFO     Startup: standard
23:02:42-584840 INFO     Verifying submodules
23:02:44-465711 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
23:02:44-529825 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
23:02:44-592099 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
23:02:44-682850 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
23:02:44-684355 DEBUG    Submodule: extensions-builtin/sdnext-modernui / main
23:02:44-758876 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
23:02:44-824758 DEBUG    Submodule: modules/k-diffusion / master
23:02:44-911129 DEBUG    Git detached head detected: folder="wiki" reattach=master
23:02:44-912127 DEBUG    Submodule: wiki / master
23:02:44-950960 DEBUG    Register paths
23:02:45-004827 DEBUG    Installed packages: 186
23:02:45-005844 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
23:02:45-156599 DEBUG    Running extension installer:
                         C:\Users\Ahmed\Downloads\ZLUDA-windows-amd64\zluda\automatic\extensions-builtin\sd-webui-agent-
                         scheduler\install.py
23:02:45-444840 DEBUG    Running extension installer:
                         C:\Users\Ahmed\Downloads\ZLUDA-windows-amd64\zluda\automatic\extensions-builtin\stable-diffusio
                         n-webui-rembg\install.py
23:02:45-677974 DEBUG    Extensions all: []
23:02:45-678974 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
23:02:45-678974 INFO     Verifying requirements
23:02:45-679975 DEBUG    Setup complete without errors: 1719698566
23:02:45-682975 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
23:02:45-682975 DEBUG    Starting module: <module 'webui' from
                         'C:\\Users\\Ahmed\\Downloads\\ZLUDA-windows-amd64\\zluda\\automatic\\webui.py'>
23:02:45-684481 INFO     Command line args: ['--use-zluda', '--debug', '--autolaunch'] autolaunch=True use_zluda=True
                         debug=True
23:02:45-685489 DEBUG    Env flags: []
23:02:49-790419 INFO     Load packages: {'torch': '2.3.0+cu118', 'diffusers': '0.29.1', 'gradio': '3.43.2'}
23:02:50-665438 INFO     VRAM: Detected=19.98 GB Optimization=none
23:02:50-667686 DEBUG    Read: file="config.json" json=32 bytes=1368 time=0.000
23:02:50-668723 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Dynamic Attention BMM"
                         mode=no_grad
23:02:50-679748 INFO     Device: device=AMD Radeon RX 7900 XT [ZLUDA] n=1 arch=compute_37 cap=(8, 8) cuda=11.8
                         cudnn=8700 driver=
23:02:50-681754 DEBUG    Read: file="html\reference.json" json=43 bytes=24978 time=0.000
Press any key to continue . . .

**Comment by vladmandic** [comment]
> Press any key to continue . . .

this is a message from command prompt interpreter which basically means "whatever you were running crashed and i'd like to close the terminal now".

so you need to look at windows event log for what crashed and possible causes. most likely its torch causing crash of python and torch most likely crashed because of incompatibility with drivers or something like that. in either case, this is completely outside of sdnext control.
