### ISSUE TITLE
[Issue]: ZLUDA/ROCm detection on Windows returns none for detected devices

### ISSUE THREAD

**Issue by ratnacrimson** [vladmandic/automatic#3307]
### Issue Description

I gave up it's beyond my knowledge hope you guys could help me to solve this problem
it's seem rocm is the culcript why sd next render as cpu unable to load the models due to rocm version act as a none
i'm using rx6700xt sometimes try to reinstall driver, hip sdk and pasted optimized lib gfx31 and delete venv folder the problems still won't perish.

### Version Platform Description

00:48:37-493718 INFO     Starting SD.Next
00:48:37-495717 INFO     Logger: file="C:\Users\R U S T Y\AMDSDXL\sdnext.log" level=DEBUG size=65 mode=create
00:48:37-497718 INFO     Python version=3.11.8 platform=Windows bin="C:\Users\R U S T Y\AMDSDXL\venv\Scripts\python.exe"
                         venv="C:\Users\R U S T Y\AMDSDXL\venv"
00:48:37-651718 INFO     Version: app=sd.next updated=2024-06-24 hash=94f6f0db branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
00:48:38-493716 INFO     Latest published version: 081c19fc122c6c8e60fcddfc37917e8107f65290 2024-07-01T08:20:42Z
00:48:38-507716 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.11.8
00:48:38-511716 DEBUG    Setting environment tuning
00:48:38-512716 INFO     HF cache folder: C:\Users\R U S T Y\.cache\huggingface\hub
00:48:38-514716 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
00:48:38-515716 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
00:48:38-516716 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
00:48:38-524716 INFO     Python version=3.11.8 platform=Windows bin="C:\Users\R U S T Y\AMDSDXL\venv\Scripts\python.exe"
                         venv="C:\Users\R U S T Y\AMDSDXL\venv"
00:48:38-531716 INFO     AMD ROCm toolkit detected
00:48:38-635719 DEBUG    ROCm agents detected: []
00:48:38-654718 DEBUG    ROCm version detected: None
00:48:38-655717 WARNING  ZLUDA support: experimental
00:48:38-687718 INFO     Using ZLUDA in C:\Users\R U S T Y\AMDSDXL\.zluda
00:48:38-688718 INFO     Install: package="torch==2.3.0 torchvision --index-url https://download.pytorch.org/whl/cu118"
00:48:38-688718 DEBUG    Running: pip="install --upgrade torch==2.3.0 torchvision --index-url
                         https://download.pytorch.org/whl/cu118 "

### Backend

Diffusers

### Branch

Master

### Model

SD-XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by manotroll** [comment]
For me, this tip did the trick
https://github.com/vladmandic/automatic/issues/3318#issuecomment-2211766345

**Comment by vladmandic** [comment]
any updates here? did you try newer sdnext - rocm detection has been much improved in the past few months.

**Comment by ratnacrimson** [comment]
Problems has been solved

**Comment by ratnacrimson** [comment]
Glad to hear it! Thanks newest rocm do the trick 🙏

**Comment by manotroll** [comment]
I will test it now
