### ISSUE TITLE
[Feature]: a setting to toggle show and use lora's model metadata/activation-text instead of embedded metadata

### ISSUE THREAD

**Issue by shivshankar11** [vladmandic/automatic#3309]
### Feature description

extra network's ui shows model's embedded metadata. there should be a toggle to show model's metadata instead or maybe both. applying model metadata/activation-text are more accurate for civitai user. embedded metadata/ss_tag_frequency  are usually wrong (thanks to model creator) and trigger nothing.

**Comment by vladmandic** [comment]
Please provide examples, not blind request. 

Also, embedded metadata is nearly always more accurate and model metadata is what author thinks should be used, but is often wrong - which is opposite of what you wrote?

**Comment by vladmandic** [comment]
closing this request in favor of #3310 which is a much more end-to-end suggestion to the same underlying problem.
