### ISSUE TITLE
[Issue] invalid torchvision version when installing torch with zluda

### ISSUE THREAD

**Issue by manotroll** [vladmandic/automatic#3318]
### Issue Description

when running while webui.bat --debug --use-zluda

│ F:\ia\automatic\webui.py:11 in <module>                                                                              │
│                                                                                                                      │
│    10 from threading import Thread                                                                                   │
│ ❱  11 import modules.loader                                                                                          │
│    12 import torch # pylint: disable=wrong-import-order                                                              │
│                                                                                                                      │
│ F:\ia\automatic\modules\loader.py:23 in <module>                                                                     │
│                                                                                                                      │
│   22 warnings.filterwarnings(action="ignore", category=UserWarning, module="torchvision")                            │
│ ❱ 23 import torchvision # pylint: disable=W0611,C0411                                                                │
│   24 import pytorch_lightning # pytorch_lightning should be imported after torch, but it re-enables warnings on impo │
│                                                                                                                      │
│ F:\ia\automatic\venv\lib\site-packages\torchvision\__init__.py:6 in <module>                                         │
│                                                                                                                      │
│     5 import torch                                                                                                   │
│ ❱   6 from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils                      │
│     7                                                                                                                │
│                                                                                                                      │
│ F:\ia\automatic\venv\lib\site-packages\torchvision\_meta_registrations.py:4 in <module>                              │
│                                                                                                                      │
│     3 import torch                                                                                                   │
│ ❱   4 import torch._custom_ops                                                                                       │
│     5 import torch.library                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'torch._custom_ops'

### Version Platform Description

[sdnext.txt](https://github.com/user-attachments/files/16116027/sdnext.txt)
09:19:13-840873 INFO     Starting SD.Next
09:19:13-843874 INFO     Logger: file="F:\ia\automatic\sdnext.log" level=DEBUG size=65 mode=create
09:19:13-844876 INFO     Python version=3.10.11 platform=Windows bin="F:\ia\automatic\venv\Scripts\python.exe"
                         venv="F:\ia\automatic\venv"
09:19:14-199180 INFO     Version: app=sd.next updated=2024-07-05 hash=9e7bb45c branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
09:19:14-646564 DEBUG    Branch sync failed: sdnext=master ui=main
09:19:15-087444 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11

### Relevant log output

```shell
09:16:35-651062 INFO     Starting SD.Next
09:16:35-654066 INFO     Logger: file="F:\ia\automatic\sdnext.log" level=DEBUG size=65 mode=create
09:16:35-655066 INFO     Python version=3.10.11 platform=Windows bin="F:\ia\automatic\venv\Scripts\python.exe"
                         venv="F:\ia\automatic\venv"
09:16:36-004367 INFO     Version: app=sd.next updated=2024-07-05 hash=9e7bb45c branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
09:16:36-446246 DEBUG    Branch sync failed: sdnext=master ui=main
09:16:36-650923 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
09:16:36-652425 DEBUG    Setting environment tuning
09:16:36-653426 INFO     HF cache folder: C:\Users\manotroll\.cache\huggingface\hub
09:16:36-654426 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
09:16:36-655427 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
09:16:36-656428 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
09:16:36-666937 INFO     Python version=3.10.11 platform=Windows bin="F:\ia\automatic\venv\Scripts\python.exe"
                         venv="F:\ia\automatic\venv"
09:16:36-675944 INFO     AMD ROCm toolkit detected
09:16:36-710475 DEBUG    ROCm agents detected: []
09:16:36-752512 DEBUG    ROCm version detected: None
09:16:36-754011 WARNING  ZLUDA support: experimental
09:16:38-551057 INFO     Using ZLUDA in F:\ia\automatic\.zluda
09:16:38-689677 INFO     Verifying requirements
09:16:38-693179 INFO     Verifying packages
09:16:38-745724 DEBUG    Repository update time: Thu Jul  4 22:10:32 2024
09:16:38-746726 INFO     Startup: standard
09:16:38-747727 INFO     Verifying submodules
09:16:41-413519 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
09:16:41-538127 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
09:16:41-670239 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
09:16:41-849393 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
09:16:41-850394 DEBUG    Submodule: extensions-builtin/sdnext-modernui / main
09:16:41-984010 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
09:16:42-108616 DEBUG    Submodule: modules/k-diffusion / master
09:16:42-289773 DEBUG    Git detached head detected: folder="wiki" reattach=master
09:16:42-291274 DEBUG    Submodule: wiki / master
09:16:42-366838 DEBUG    Register paths
09:16:42-420385 DEBUG    Installed packages: 173
09:16:42-421886 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
09:16:42-611548 DEBUG    Running extension installer:
                         F:\ia\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
09:16:42-922317 DEBUG    Running extension installer:
                         F:\ia\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
09:16:43-187043 DEBUG    Extensions all: []
09:16:43-188044 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
09:16:43-189046 INFO     Verifying requirements
09:16:43-190046 DEBUG    Setup complete without errors: 1720268203
09:16:43-193050 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
09:16:43-194551 DEBUG    Starting module: <module 'webui' from 'F:\\ia\\automatic\\webui.py'>
09:16:43-195551 INFO     Command line args: ['--debug', '--use-zluda'] use_zluda=True debug=True
09:16:43-196553 DEBUG    Env flags: []
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ F:\ia\automatic\launch.py:263 in <module>                                                                            │
│                                                                                                                      │
│   262 if __name__ == "__main__":                                                                                     │
│ ❱ 263     main()                                                                                                     │
│   264                                                                                                                │
│                                                                                                                      │
│ F:\ia\automatic\launch.py:240 in main                                                                                │
│                                                                                                                      │
│   239                                                                                                                │
│ ❱ 240     uv, instance = start_server(immediate=True, server=None)                                                   │
│   241     while True:                                                                                                │
│                                                                                                                      │
│ F:\ia\automatic\launch.py:168 in start_server                                                                        │
│                                                                                                                      │
│   167     get_custom_args()                                                                                          │
│ ❱ 168     module_spec.loader.exec_module(server)                                                                     │
│   169     uvicorn = None                                                                                             │
│ in exec_module:883                                                                                                   │
│ in _call_with_frames_removed:241                                                                                     │
│                                                                                                                      │
│ F:\ia\automatic\webui.py:11 in <module>                                                                              │
│                                                                                                                      │
│    10 from threading import Thread                                                                                   │
│ ❱  11 import modules.loader                                                                                          │
│    12 import torch # pylint: disable=wrong-import-order                                                              │
│                                                                                                                      │
│ F:\ia\automatic\modules\loader.py:23 in <module>                                                                     │
│                                                                                                                      │
│   22 warnings.filterwarnings(action="ignore", category=UserWarning, module="torchvision")                            │
│ ❱ 23 import torchvision # pylint: disable=W0611,C0411                                                                │
│   24 import pytorch_lightning # pytorch_lightning should be imported after torch, but it re-enables warnings on impo │
│                                                                                                                      │
│ F:\ia\automatic\venv\lib\site-packages\torchvision\__init__.py:6 in <module>                                         │
│                                                                                                                      │
│     5 import torch                                                                                                   │
│ ❱   6 from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils                      │
│     7                                                                                                                │
│                                                                                                                      │
│ F:\ia\automatic\venv\lib\site-packages\torchvision\_meta_registrations.py:4 in <module>                              │
│                                                                                                                      │
│     3 import torch                                                                                                   │
│ ❱   4 import torch._custom_ops                                                                                       │
│     5 import torch.library                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'torch._custom_ops'
```

### Backend

Diffusers

### Branch

Master

### Model

SD 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i don't think this is windows 11 specific - for some reason version of torchvision installed does not match version of torch installed.
can you activate venv (`venv\Scripts\activate`) and check:
> pip show torch
> pip show torchvision

and possibly rerun installation using `webui --debug --use-zluda --reinstall` ?

**Comment by manotroll** [comment]
F:\ia\automatic\venv\Scripts>activate.bat

(venv) F:\ia\automatic\venv\Scripts>pip show torch
Name: torch
Version: 2.3.1
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: f:\ia\automatic\venv\lib\site-packages
Requires: filelock, fsspec, jinja2, mkl, networkx, sympy, typing-extensions
Required-by: accelerate, clean-fid, clip, clip-interrogator, compel, dctorch, invisible-watermark, kornia, lpips, open_clip_torch, optimum, peft, pytorch-lightning, tensordict, timm, torchdiffeq, torchmetrics, torchsde, torchvision

(venv) F:\ia\automatic\venv\Scripts>pip show torchvision
Name: torchvision
Version: 0.18.1
Summary: image and video datasets and models for torch deep learning
Home-page: https://github.com/pytorch/vision
Author: PyTorch Core Team
Author-email: soumith@pytorch.org
License: BSD
Location: f:\ia\automatic\venv\lib\site-packages
Requires: numpy, pillow, torch
Required-by: clean-fid, clip, clip-interrogator, lpips, open_clip_torch, timm

F:\ia\automatic>webui --debug --use-zluda --reinstall
Using VENV: F:\ia\automatic\venv
10:25:13-974677 INFO     Starting SD.Next
10:25:13-977680 INFO     Logger: file="F:\ia\automatic\sdnext.log" level=DEBUG size=65 mode=create
10:25:13-978681 INFO     Python version=3.10.11 platform=Windows bin="F:\ia\automatic\venv\Scripts\python.exe"
                         venv="F:\ia\automatic\venv"
10:25:14-522148 INFO     Version: app=sd.next updated=2024-07-05 hash=9e7bb45c branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
10:25:15-051603 DEBUG    Branch sync failed: sdnext=master ui=main
10:25:15-727684 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
10:25:15-729686 DEBUG    Setting environment tuning
10:25:15-731688 INFO     HF cache folder: C:\Users\manotroll\.cache\huggingface\hub
10:25:15-732690 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
10:25:15-733690 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
10:25:15-735191 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
10:25:15-751705 INFO     Python version=3.10.11 platform=Windows bin="F:\ia\automatic\venv\Scripts\python.exe"
                         venv="F:\ia\automatic\venv"
10:25:15-762215 INFO     AMD ROCm toolkit detected
10:25:16-531376 DEBUG    ROCm agents detected: ['gfx1100']
10:25:16-532877 DEBUG    ROCm agent used by default: idx=0 gpu=gfx1100 arch=navi3x
10:25:16-592929 DEBUG    ROCm version detected: None
10:25:16-593930 WARNING  ZLUDA support: experimental
10:25:17-855515 INFO     Using ZLUDA in F:\ia\automatic\.zluda
10:25:17-857015 INFO     Install: package="torch==2.3.0 torchvision --index-url https://download.pytorch.org/whl/cu118"
10:25:17-858017 DEBUG    Running: pip="install --upgrade torch==2.3.0 torchvision --index-url
                         https://download.pytorch.org/whl/cu118 "
10:28:43-036485 ERROR    Error running pip: install --upgrade torch==2.3.0 torchvision --index-url
                         https://download.pytorch.org/whl/cu118
10:28:45-498102 DEBUG    Pip output: Looking in indexes: https://download.pytorch.org/whl/cu118
                         Collecting torch==2.3.0
                           Using cached
                         https://download.pytorch.org/whl/cu118/torch-2.3.0%2Bcu118-cp310-cp310-win_amd64.whl (2673.0
                         MB)
                         Requirement already satisfied: torchvision in f:\ia\automatic\venv\lib\site-packages (0.18.1)
                         Collecting torchvision
                           Using cached
                         https://download.pytorch.org/whl/cu118/torchvision-0.18.1%2Bcu118-cp310-cp310-win_amd64.whl
                         (4.9 MB)
                         Requirement already satisfied: jinja2 in f:\ia\automatic\venv\lib\site-packages (from
                         torch==2.3.0) (3.1.4)
                         Requirement already satisfied: sympy in f:\ia\automatic\venv\lib\site-packages (from
                         torch==2.3.0) (1.12.1)
                         Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in
                         f:\ia\automatic\venv\lib\site-packages (from torch==2.3.0) (2021.4.0)
                         Requirement already satisfied: fsspec in f:\ia\automatic\venv\lib\site-packages (from
                         torch==2.3.0) (2024.6.1)
                         Requirement already satisfied: typing-extensions>=4.8.0 in
                         f:\ia\automatic\venv\lib\site-packages (from torch==2.3.0) (4.11.0)
                         Requirement already satisfied: networkx in f:\ia\automatic\venv\lib\site-packages (from
                         torch==2.3.0) (3.3)
                         Requirement already satisfied: filelock in f:\ia\automatic\venv\lib\site-packages (from
                         torch==2.3.0) (3.15.4)
                         Requirement already satisfied: numpy in f:\ia\automatic\venv\lib\site-packages (from
                         torchvision) (1.26.4)
                         Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in f:\ia\automatic\venv\lib\site-packages
                         (from torchvision) (10.3.0)
                           Using cached
                         https://download.pytorch.org/whl/cu118/torchvision-0.18.0%2Bcu118-cp310-cp310-win_amd64.whl
                         (4.9 MB)
                         Requirement already satisfied: tbb==2021.* in f:\ia\automatic\venv\lib\site-packages (from
                         mkl<=2021.4.0,>=2021.1.1->torch==2.3.0) (2021.13.0)
                         Requirement already satisfied: intel-openmp==2021.* in f:\ia\automatic\venv\lib\site-packages
                         (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.0) (2021.4.0)
                         Requirement already satisfied: MarkupSafe>=2.0 in f:\ia\automatic\venv\lib\site-packages (from
                         jinja2->torch==2.3.0) (2.1.5)
                         Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in f:\ia\automatic\venv\lib\site-packages
                         (from sympy->torch==2.3.0) (1.3.0)
                         Installing collected packages: torch, torchvision
                           Attempting uninstall: torch
                             Found existing installation: torch 2.3.1
                             Uninstalling torch-2.3.1:
                               Successfully uninstalled torch-2.3.1
                           Attempting uninstall: torchvision
                             Found existing installation: torchvision 0.18.1
                             Uninstalling torchvision-0.18.1:
                               Successfully uninstalled torchvision-0.18.1

                         ERROR: Could not install packages due to an OSError: [WinError 5] Acesso negado:
                         'F:\\ia\\automatic\\venv\\Lib\\site-packages\\~orchvision-0.18.1.dist-info\\INSTALLER'
                         Check the permissions.


                         [notice] A new release of pip is available: 23.0.1 -> 24.1.1
                         [notice] To update, run: F:\ia\automatic\venv\Scripts\python.exe -m pip install --upgrade pip
10:28:46-451422 INFO     Forcing reinstall of all packages
10:28:46-539999 INFO     Verifying requirements
10:28:46-564520 INFO     Verifying packages
10:28:46-566021 INFO     Install: package="git+https://github.com/openai/CLIP.git"
10:28:46-567022 DEBUG    Running: pip="install --upgrade git+https://github.com/openai/CLIP.git "
10:28:53-788733 INFO     Startup: standard
10:28:53-790233 INFO     Verifying submodules
10:29:09-070374 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
10:29:09-213997 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
10:29:09-393152 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
10:29:09-607336 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
10:29:09-608837 DEBUG    Submodule: extensions-builtin/sdnext-modernui / main
10:29:09-751460 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
10:29:09-914600 DEBUG    Submodule: modules/k-diffusion / master
10:29:10-128284 DEBUG    Git detached head detected: folder="wiki" reattach=master
10:29:10-129785 DEBUG    Submodule: wiki / master
10:29:10-212356 DEBUG    Register paths
10:29:10-305436 DEBUG    Installed packages: 174
10:29:10-307438 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
10:29:10-481087 DEBUG    Running extension installer:
                         F:\ia\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
10:29:10-843899 DEBUG    Running extension installer:
                         F:\ia\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
10:29:11-142656 DEBUG    Extensions all: []
10:29:11-143657 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
10:29:11-145158 INFO     Verifying requirements
10:29:11-146160 WARNING  Setup complete with errors: 1
10:29:11-147160 WARNING  See log file for more details: F:\ia\automatic\sdnext.log
10:29:11-165176 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
10:29:11-166677 DEBUG    Starting module: <module 'webui' from 'F:\\ia\\automatic\\webui.py'>
10:29:11-167678 INFO     Command line args: ['--debug', '--use-zluda', '--reinstall'] use_zluda=True reinstall=True
                         debug=True
10:29:11-168679 DEBUG    Env flags: []
10:29:40-659546 INFO     Load packages: {'torch': '2.3.0+cu118', 'diffusers': '0.29.1', 'gradio': '3.43.2'}
10:29:42-759852 DEBUG    Reading failed: config.json [Errno 2] No such file or directory: 'config.json'
10:29:43-524509 INFO     VRAM: Detected=23.98 GB Optimization=none
10:29:43-526516 DEBUG    Created default config: config.json
10:29:43-529013 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
10:29:43-530515 DEBUG    Save: file="config.json" json=14 bytes=589 time=0.002
10:29:43-579557 INFO     Device: device=AMD Radeon RX 7900 XTX [ZLUDA] n=1 arch=compute_37 cap=(8, 8) cuda=11.8
                         cudnn=8700 driver=
10:29:43-581058 DEBUG    Migrated styles: file=styles.csv folder=models\styles
10:29:43-653120 DEBUG    Load styles: folder="models\styles" items=288 time=0.07
10:29:43-672637 DEBUG    Read: file="html\reference.json" json=43 bytes=24978 time=0.018
10:29:49-777887 DEBUG    ONNX: version=1.18.1 provider=CPUExecutionProvider, available=['AzureExecutionProvider',
                         'CPUExecutionProvider']
10:29:50-279318 DEBUG    Importing LDM
10:29:50-478490 DEBUG    Entering start sequence
10:29:50-479991 INFO     Create: folder="models\ONNX"
10:29:50-481492 INFO     Create: folder="models\Stable-diffusion"
10:29:50-482493 INFO     Create: folder="models\Diffusers"
10:29:50-483495 INFO     Create: folder="models\VAE"
10:29:50-484995 INFO     Create: folder="models\UNET"
10:29:50-485996 INFO     Create: folder="models\Lora"
10:29:50-486997 INFO     Create: folder="models\embeddings"
10:29:50-487998 INFO     Create: folder="models\hypernetworks"
10:29:50-488998 INFO     Create: folder="outputs\text"
10:29:50-490000 INFO     Create: folder="outputs\image"
10:29:50-491000 INFO     Create: folder="outputs\control"
10:29:50-492001 INFO     Create: folder="outputs\extras"
10:29:50-493002 INFO     Create: folder="outputs\init-images"
10:29:50-494003 INFO     Create: folder="outputs\grids"
10:29:50-495504 INFO     Create: folder="outputs\save"
10:29:50-496505 INFO     Create: folder="outputs\video"
10:29:50-497506 INFO     Create: folder="models\wildcards"
10:29:50-499007 DEBUG    Initializing
10:29:50-643131 INFO     Available VAEs: path="models\VAE" items=0
10:29:50-644632 DEBUG    Available UNets: path="models\UNET" items=0
10:29:50-646134 INFO     Disabled extensions: ['sdnext-modernui']
10:29:50-648135 DEBUG    Scanning diffusers cache: folder=models\Diffusers items=0 time=0.00
10:29:50-649136 INFO     Available models: path="models\Stable-diffusion" items=0 time=0.00
10:29:50-657644 INFO     Install: package="basicsr"
10:29:50-658645 DEBUG    Running: pip="install --upgrade basicsr "
10:30:00-861919 INFO     Install: package="gfpgan"
10:30:00-862920 DEBUG    Running: pip="install --upgrade gfpgan "
10:30:06-890604 DEBUG    Load extensions
10:30:07-791378 INFO     Extension: script='extensions-builtin\Lora\scripts\lora_script.py'
                         [2;36m10:30:07-759351[0m[2;36m [0m[34mINFO    [0m LoRA networks: [33mavailable[0m=[1;36m0[0m
                         [33mfolders[0m=[1;36m2[0m
10:30:12-619030 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
10:30:12-722119 DEBUG    Extensions init time: 5.83 demofusion.py=0.06 layerdiffuse.py=0.05 loopback.py=0.12
                         poor_mans_outpainting.py=0.06 prompt_matrix.py=0.09 Lora=0.12 sd-extension-chainner=1.14
                         sd-extension-system-info=0.07 sd-webui-agent-scheduler=3.62
10:30:13-076423 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.003
10:30:13-077924 INFO     Upscaler create: folder="models\chaiNNer"
10:30:13-088934 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=24 bytes=2719 time=0.010
10:30:13-090937 DEBUG    chaiNNer models: path="models\chaiNNer" defined=24 discovered=0 downloaded=0
10:30:13-092437 INFO     Upscaler create: folder="models\RealESRGAN"
10:30:13-094939 DEBUG    Load upscalers: total=52 downloaded=0 user=0 time=0.37 ['None', 'Lanczos', 'Nearest',
                         'ChaiNNer', 'ESRGAN', 'LDSR', 'RealESRGAN', 'SCUNet', 'SD', 'SwinIR']
10:30:13-109952 DEBUG    Load styles: folder="models\styles" items=288 time=0.01
10:30:13-142981 DEBUG    Creating UI
10:30:13-144482 DEBUG    UI themes available: type=Standard themes=12
10:30:13-145483 INFO     UI theme: type=Standard name="black-teal"
10:30:13-150988 DEBUG    UI theme: css="F:\ia\automatic\javascript\black-teal.css" base="sdnext.css" user="None"
10:30:13-166501 DEBUG    UI initialize: txt2img
10:30:13-198028 DEBUG    Networks: page='model' items=42 subfolders=2 tab=txt2img folders=['models\\Stable-diffusion',
                         'models\\Diffusers', 'models\\Reference'] list=0.01 thumb=0.00 desc=0.00 info=0.00 workers=4
                         sort=Default
10:30:13-200030 DEBUG    Networks: page='lora' items=0 subfolders=0 tab=txt2img folders=['models\\Lora',
                         'models\\LyCORIS'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=4 sort=Default
10:30:13-223550 DEBUG    Networks: page='style' items=288 subfolders=1 tab=txt2img folders=['models\\styles', 'html']
                         list=0.01 thumb=0.00 desc=0.00 info=0.00 workers=4 sort=Default
10:30:13-227053 DEBUG    Networks: page='embedding' items=0 subfolders=0 tab=txt2img folders=['models\\embeddings']
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=4 sort=Default
10:30:13-229055 DEBUG    Networks: page='vae' items=0 subfolders=0 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=4 sort=Default
10:30:13-306622 DEBUG    UI initialize: img2img
10:30:13-426224 DEBUG    UI initialize: control models=models\control
10:30:14-051762 DEBUG    Reading failed: ui-config.json [Errno 2] No such file or directory: 'ui-config.json'
10:30:14-454609 DEBUG    UI themes available: type=Standard themes=12
10:30:14-686808 DEBUG    Reading failed: F:\ia\automatic\html\extensions.json [Errno 2] No such file or directory:
                         'F:\\ia\\automatic\\html\\extensions.json'
10:30:14-688810 INFO     Extension list is empty: refresh required
10:30:15-694175 DEBUG    Extension list: processed=6 installed=6 enabled=5 disabled=1 visible=6 hidden=0
10:30:15-768739 DEBUG    Save: file="ui-config.json" json=0 bytes=2 time=0.001
10:30:15-812276 DEBUG    Root paths: ['F:\\ia\\automatic']
10:30:16-259161 INFO     Local URL: http://127.0.0.1:7860/
10:30:16-260161 DEBUG    Gradio functions: registered=1704
10:30:16-290187 DEBUG    FastAPI middleware: ['Middleware', 'Middleware']
10:30:16-293690 DEBUG    Creating API
10:30:16-439316 INFO     [AgentScheduler] Task queue is empty
10:30:16-440316 INFO     [AgentScheduler] Registering APIs
10:30:16-540402 DEBUG    Scripts setup: ['IP Adapters:0.021', 'AnimateDiff:0.009', 'X/Y/Z Grid:0.012', 'Face:0.012',
                         'Image-to-Video:0.006']
10:30:16-541904 DEBUG    Model metadata: file="metadata.json" no changes
10:30:16-543405 DEBUG    Torch mode: deterministic=False
10:30:17-236000 DEBUG    Desired Torch parameters: dtype=FP16 no-half=False no-half-vae=False upscast=False
10:30:17-237502 INFO     Setting Torch parameters: device=cuda dtype=torch.float16 vae=torch.float16 unet=torch.float16
                         context=no_grad fp16=True bf16=None optimization=Scaled-Dot-Product
10:30:17-240005 DEBUG    Model requested: fn=<lambda>
10:30:17-241005 WARNING  Cannot generate without a checkpoint
10:30:17-242506 INFO     Set system paths to use existing folders
10:30:17-243006 INFO       or use --models-dir <path-to-folder> to specify base folder with all models
10:30:17-244008 INFO       or use --ckpt-dir <path-to-folder> to specify folder with sd models
10:30:17-245008 INFO       or use --ckpt <path-to-checkpoint> to force using specific model
10:30:17-246510 DEBUG    Script callback init time: task_scheduler.py:app_started=0.11
10:30:17-247510 INFO     Startup time: 66.05 torch=14.94 gradio=11.64 diffusers=2.88 libraries=9.62 ldm=0.20
                         samplers=0.16 extensions=5.83 face-restore=16.24 upscalers=0.37 ui-en=0.20 ui-txt2img=0.06
                         ui-img2img=0.07 ui-control=0.10 ui-extras=0.06 ui-models=0.37 ui-settings=0.61
                         ui-extensions=1.06 ui-defaults=0.06 launch=0.52 api=0.08 app-started=0.16 checkpoint=0.71
10:30:17-249012 DEBUG    Save: file="config.json" json=29 bytes=1139 time=0.003
10:32:00-289129 DEBUG    Server: alive=True jobs=1 requests=1 uptime=138 memory=0.97/63.92 backend=Backend.DIFFUSERS
                         state=idle
10:34:00-333871 DEBUG    Server: alive=True jobs=1 requests=1 uptime=258 memory=0.97/63.92 backend=Backend.DIFFUSERS
                         state=idle
10:36:00-379114 DEBUG    Server: alive=True jobs=1 requests=1 uptime=378 memory=0.97/63.92 backend=Backend.DIFFUSERS
                         state=idle
10:36:20-595500 INFO     MOTD: N/A
10:36:24-316199 DEBUG    UI themes available: type=Standard themes=12
10:36:24-340721 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64)
                         AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36

now it's working :D

**Comment by manotroll** [comment]
but it's not using the video card, I already downloaded a model to test

**Comment by brknsoul** [comment]
> It seems like I always have to add --use-zluda to use the gpu

that's right. You might wanna create a shortcut from webui.bat and place `--use-zluda --debug --autolaunch` at the end of the target field

![image](https://github.com/vladmandic/automatic/assets/1969381/ffb2e27d-57d8-4654-9520-c75a77d50eef)

**Comment by manotroll** [comment]
I made another .bat file with the aro parameters for it

**Comment by brknsoul** [comment]
Heh, that's what I do too;

```bat
@echo off
set VENV_DIR=
set PYTHON=
webui.bat --autolaunch --debug --use-zluda %*
```

**Comment by vladmandic** [comment]
seems this issue is resolved?

**Comment by manotroll** [comment]
yes it is resolved
