### ISSUE TITLE
[Feature]: Add none to Lora list

### ISSUE THREAD

**Issue by sadelcri** [vladmandic/automatic#332]
### Issue Description

when addind sd_lora everything works fine but there is no option there to select "none". 

![Screenshot_5](https://user-images.githubusercontent.com/120217469/233586732-150fc572-2150-4923-a2ae-9370996e3986.png)

### Version Platform Description

windows 11, google chrome

**Comment by vladmandic** [comment]
in core repo, you'd add lora by clicking on its card from extra networks.
this pulldown comes from where? i guess from an extension? if yes, its up to extension to show none as first entry.
closing as external issue, but i'm wrong let me know and i'll reopen.

**Comment by CodeMonkey80** [comment]
> in core repo, you'd add lora by clicking on its card from extra networks. this pulldown comes from where? i guess from an extension? if yes, its up to extension to show none as first entry. closing as external issue, but i'm wrong let me know and i'll reopen.

I noticed the same problem today. It's not an extension but a UI "shortcut" that adds Lora list on top of interface for convenience. Yes, it's similar to choosing a Lora from extra networks but allows to do this faster without having to open the extra networks menu every time and you can always see which Lora is selected on top of screen. It's quite useful for quick Lora swapping and saves a lot of time in the end. I use a couple of other A1111 fork repos and yours is the only one which has this issue, so it's not an extension problem. I can see that you're a very busy guy these days and your works is greatly appreciated but it would be great if this little problem could be fixed. I even tried to locate it myself but I'm not very experienced with Python :(

Below is the setup where this shortcut is activated:

![image](https://user-images.githubusercontent.com/37898238/233789294-15bd4783-f9c5-40a5-a7f5-be3e30238296.png)

**Comment by vladmandic** [comment]
ok, i understand now. yes, its a valid request. but lets mark it as feature request, its not an issue.

**Comment by biship** [comment]
This works for me:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9723

**Comment by vladmandic** [comment]
perfect, having ready-made pr makes it simpler. i've merged it.

**Comment by biship** [comment]
@vladmandic  How do you merge a pr from another repo? I cloned your repo and maintain a local copy, but would love to know how to merge other repo pr's.

**Comment by vladmandic** [comment]
1. go to original PR -> wants to merge from -> click on fork/branch
2. click on a link that says 'x commits ahead'
3. change base repository to your fork/branch
4. click pull request
new pr will be opened on your fork
