### ISSUE TITLE
[Feature]: XYZ Improvement #2 - option to report generation time

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#3334]
### Feature description

Some of the options could very well be of interest to know how long it takes to generate the images, as things stand we have to look at a log and figure that out manually. I think it would be better to just indicate it right below each option in smaller text on the chart itself since the info is readily available by that point.

**Comment by vladmandic** [comment]
cool idea, will implement.

**Comment by vladmandic** [comment]
better late then never - done!
