### ISSUE TITLE
[Issue]: DPM Adaptive removed?

### ISSUE THREAD

**Issue by nbs** [vladmandic/automatic#3338]
### Issue Description

Sorry if this is a stupid question, was the DPM adaptive sampler removed?

I can see references to it in the codebase when I searched but I can't find it in the dropdown nor in the settings to manually enable, where it has the list of samplers to enable.

I switched the backend to `original` as well wondering if it'd show up but no dice.

Is it just called something else perhaps?

If it was removed I assume it'd be mentioned in the changelog file but no dice there either.

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
DPM Adaptive is available in backend:original and not removed, it was never part of backend:diffusers
