### ISSUE TITLE
[Feature]: Adjust model update page

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#3340]
### Feature description

![image](https://github.com/user-attachments/assets/e539cad4-3441-4bd4-bf2e-168dbac811a7)

👍🏻👍🏻

**Comment by vladmandic** [comment]
they say that picture is worth a thousand words - but not this one! 😂
care to do a short writeup to explain?

**Comment by Aptronymist** [comment]
> they say that picture is worth a thousand words - but not this one! 😂
> care to do a short writeup to explain?

Hahahaha!
Just wanted to move the log below the  list so it would be wider, and since I'm thinking about it, the list itself could definitely stretch a bit to fit the screen rather than being so boxed in and showing so few at a time. Could likely cut down on some padding as well.

**Comment by vladmandic** [comment]
all subtabs in models tab share the same layout, so that change would have either pretty massive impact everywhere else or tab would need to be separated su each subtab individual layout which is pretty big code change.

**Comment by Aptronymist** [comment]
> all subtabs in models tab share the same layout, so that change would have either pretty massive impact everywhere else or tab would need to be separated su each subtab individual layout which is pretty big code change.

Ahhhh.. then I can just do it with some css tool. no biggie. closing.

**Comment by vladmandic** [comment]
entire right side pane (log) is what's shared between subtabs, it's not separate per tab. so if you move it here, it moves everywhere.

**Comment by Aptronymist** [comment]
> entire right side pane (log) is what's shared between subtabs, it's not separate per tab. so if you move it here, it moves everywhere.

checkbox to hide it? I'm not even sure it's necessary since it's all in the console anyway.

**Comment by vladmandic** [comment]
yeah, thats doable
