### ISSUE TITLE
[Issue]: Text Tab scripts do not match Control Tab scripts

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#3341]
### Issue Description

The list of scripts available in Control tab and Text tab do not match.

| Script                  | Control Tab | Text Tab |
|-------------------------|-------------|----------|
| LayerDiffuse            | ✔           | ✔        |
| MuLan                   | ✔           | ✔        |
| Prompt matrix           | ✔           | ✔        |
| Prompts from File       | ✔           | ✔        |
| X/Y/Z Grid              | ✔           | ✔        |
| Face                    | ✔           | ✔        |
| BLIP Diffusion          | ✔           | ❌       |
| Differential diffusion  | ✔           | ❌       |
| LEdits++                | ✔           | ❌       |
| Loopback                | ✔           | ❌       |
| Outpainting             | ✔           | ❌       |
| Outpainting alternative | ✔           | ❌       |
| SD Upscale              | ✔           | ❌       |
| Stable Video Diffusion  | ✔           | ❌       |
| DemoFusion              | ❌           | ✔        |
| Kohya HiRes Fix         | ❌           | ✔        |
| Mixture tiling          | ❌           | ✔        |
| Regional prompting      | ❌           | ✔        |
| ResAdapter              | ❌           | ✔        |
| T-Gate                  | ❌           | ✔        |
| Text-to-Video           | ❌           | ✔        |

While I understand that some Control scripts don't make sense in Text, ALL Text scripts should be available in Control.

### Version Platform Description

```
Python version=3.10.11 platform=Windows bin="E:\sdmaster\venv\Scripts\python.exe"
venv="E:\sdmaster\venv"
Version: app=sd.next updated=2024-07-10 hash=2ec6e9ee branch=master
url=https://github.com/vladmandic/automatic/tree/master ui=main
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel system=Windows
release=Windows-10-10.0.19045-SP0 python=3.10.11
```

### Backend

Diffusers

### UI

ModernUI

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev
