### ISSUE TITLE
[Issue]: Very Bad generations

### ISSUE THREAD

**Issue by Hunter9886** [vladmandic/automatic#3344]
### Issue Description

So i recently managed to install sdnext for my amd gpu (6700 xt) after using the directml (lshqqytiger version) for so long, not being able to use XL models was a pain in the ass and now i have twice if not 3x the speed here with SDnext, however with sdnext i have been using it for a while and the results are all terrible and not normal compared to any normal generation in Stable diffusion(even the SD 1.5 generations i used to get in directml were better), after even using Dreamshaper XL it comes with bad results and deformed and low quality Generations, is this normal? do i need to change something in the settings so that the Images i generate are actually normal? this has happend to me while using different models as well and i am not a newbie when it comes to Prompts so this is very Unusual to me. is this a Gpu related issue? need to change some settings? or is the speed im getting is Costing me the quality of generating good images (Deformed humans/deformed backround even, low quality, lora not work as it should), Aren't sdxl models and loras better than SD 1.5 ? this is very confusing to me.

![One](https://github.com/user-attachments/assets/b4efa05a-0c7d-4d0d-a1cd-55b2e3dbc829)
(My generated Image of queen Amidala. ( you can see its deformed wether with her or the backround, low quality)

![two](https://github.com/user-attachments/assets/8c5e4c88-2d7a-4f61-9dd2-15970b0af16c)
(Lora Creator's Generation of the queen)

Both Used with Adetailer and same generation data. i get these deformities in almost every model.

![three](https://github.com/user-attachments/assets/122e84cb-f8cf-4036-bb2a-96be92d9909f)
(Another Example)

is the issue maybe because of 512x512 and not generating at 1024x1024?

### Version Platform Description

-app: SD.next
-updated: 2024-07-10
-hash: 2ec6e9ee
-url: https://github.com/vladmandic/automatic/tree/master

-arch: AMD64
-cpu: AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
-system: Windows
-release: Windows-10-10.0.19045-SP0
-python: 3.10.14

(sdnext) C:\Users\Desktop\automatic>python launch.py --use-zluda --debug --autolaunch
01:35:51-773894 INFO     Starting SD.Next
01:35:51-787910 INFO     Logger: file="C:\Users\Desktop\automatic\sdnext.log" level=DEBUG size=65
                         mode=create
01:35:51-794916 INFO     Python version=3.10.14 platform=Windows bin="C:\Users\miniconda3\envs\sdnext\python.exe"
                         venv="C:\Users\miniconda3\envs\sdnext"
01:35:52-280111 INFO     Version: app=sd.next updated=2024-07-10 hash=2ec6e9ee branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
01:35:55-335641 INFO     Platform: arch=AMD64 cpu=AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.14
01:35:55-343659 DEBUG    Setting environment tuning
01:35:55-346651 INFO     HF cache folder: C:\Users\.cache\huggingface\hub
01:35:55-349654 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
01:35:55-352656 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
01:35:55-359662 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
01:35:55-383684 INFO     Python version=3.10.14 platform=Windows bin="C:\Users\miniconda3\envs\sdnext\python.exe"
                         venv="C:\Users
![System info](https://github.com/user-attachments/assets/533d036d-50a2-477d-8d39-3da8e7141379)
\miniconda3\envs\sdnext"
01:35:55-398698 INFO     AMD ROCm toolkit detected
01:35:56-149061 DEBUG    ROCm agents detected: ['gfx1031']
01:35:56-153065 DEBUG    ROCm agent used by default: idx=0 gpu=gfx1031 arch=navi2x
01:35:56-188098 DEBUG    ROCm version detected: None
01:35:56-192101 WARNING  ZLUDA support: experimental
01:35:56-632748 INFO     Using ZLUDA in C:\Users\Desktop\automatic\.zluda
01:35:57-151873 INFO     Verifying requirements
01:35:57-164885 INFO     Verifying packages
01:35:57-231946 DEBUG    Repository update time: Wed Jul 10 16:29:43 2024
01:35:57-235951 INFO     Startup: standard
01:35:57-239964 INFO     Verifying submodules
01:36:01-482070 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
01:36:01-658230 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
01:36:01-822381 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
01:36:02-055593 DEBUG    Git detached head detected: folder="extensions-builtin/sdnext-modernui" reattach=main
01:36:02-060598 DEBUG    Submodule: extensions-builtin/sdnext-modernui / main
01:36:02-321836 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
01:36:02-506005 DEBUG    Submodule: modules/k-diffusion / master
01:36:02-773247 DEBUG    Git detached head detected: folder="wiki" reattach=master
01:36:02-778252 DEBUG    Submodule: wiki / master
01:36:02-866331 DEBUG    Register paths
01:36:03-111775 DEBUG    Installed packages: 212
01:36:03-116779 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
01:36:04-090061 DEBUG    Running extension installer: C:\Users\Desktop\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
01:36:05-187228 DEBUG    Running extension installer: C:\Users\Desktop\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
01:36:06-082394 DEBUG    Extensions all: ['adetailer', 'sd-civitai-browser-plus', 'sd-webui-3d-open-pose-editor',
                         'sd-webui-reactor', 'ultimate-upscale-for-automatic1111']
01:36:06-090401 DEBUG    Running extension installer: C:\Users\Desktop\automatic\extensions\adetailer\install.py
01:36:07-071785 DEBUG    Running extension installer: C:\Users\Desktop\\automatic\extensions\sd-civitai-browser-plus\install.py
01:36:22-070415 DEBUG    Running extension installer: C:\Users\Desktop\automatic\extensions\sd-webui-3d-open-pose-editor\install.py
01:36:22-753178 DEBUG    Running extension installer: C:\Users\Desktop\automatic\extensions\sd-webui-reactor\install.py
01:36:30-570469 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg', 'adetailer',
                         'sd-civitai-browser-plus', 'sd-webui-3d-open-pose-editor', 'sd-webui-reactor',
                         'ultimate-upscale-for-automatic1111']
01:36:30-584482 INFO     Verifying requirements
01:36:30-596494 DEBUG    Setup complete without errors: 1721259391
01:36:30-626522 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
01:36:30-633526 DEBUG    Starting module: <module 'webui' from 'C:\\Users\\Desktop\\automatic\\webui.py'>
01:36:30-640533 INFO     Command line args: ['--use-zluda', '--debug', '--autolaunch'] autolaunch=True use_zluda=True
                         debug=True

### Relevant log output

```shell
Progress  2.68it/s █████████████████████▍             65% 13/20 00:04 00:02 Base02:01:59-706043 DEBUG    Server: alive=True jobs=1 requests=655 uptime=499 memory=1.71/15.95 backend=Backend.DIFFUSERS
                         state=job="" 0/6
Progress  2.68it/s █████████████████████████████████ 100% 20/20 00:07 00:00 Base
02:02:02-484953 DEBUG    GC: utilization={'gpu': 85, 'ram': 11, 'threshold': 80} gc={'collected': 2261, 'saved': 2.89}
                         before={'gpu': 10.14, 'ram': 1.7} after={'gpu': 7.25, 'ram': 1.62, 'retries': 0, 'oom': 0}
                         device=cuda fn=nextjob time=0.44
02:02:05-449940 DEBUG    GC: utilization={'gpu': 100, 'ram': 24, 'threshold': 80} gc={'collected': 261, 'saved': 4.61}
                         before={'gpu': 11.98, 'ram': 3.87} after={'gpu': 7.37, 'ram': 1.75, 'retries': 0, 'oom': 0}
                         device=cuda fn=vae_decode time=0.68
02:02:05-488968 DEBUG    Pipeline class change: original=StableDiffusionXLInpaintPipeline
                         target=StableDiffusionXLPipeline device=cuda:0 fn=process_images_inner
02:02:05-494973 INFO     Processed: images=1 time=12.73 its=1.57 memory={'ram': {'used': 1.75, 'total': 15.95}, 'gpu':
                         {'used': 7.37, 'total': 11.98}, 'retries': 0, 'oom': 0}

0: 640x640 1 hand, 17.1ms
Speed: 5.0ms preprocess, 17.1ms inference, 2.9ms postprocess per image at shape (1, 3, 640, 640)
02:02:06-011443 DEBUG    Pipeline class change: original=StableDiffusionXLPipeline
                         target=StableDiffusionXLInpaintPipeline device=cuda:0 fn=init
02:02:06-021464 DEBUG    Mask: size=512x512 masked=20460px area=0.08 auto=None blur=0.031 erode=0.010 dilate=0.250
                         type=Grayscale time=0.00
02:02:06-160591 INFO     Base: class=StableDiffusionXLInpaintPipeline
02:02:06-165584 DEBUG    Sampler: sampler="DPM++ 2M" config={'num_train_timesteps': 1000, 'beta_start': 0.00085,
                         'beta_end': 0.012, 'beta_schedule': 'scaled_linear', 'prediction_type': 'epsilon',
                         'thresholding': False, 'sample_max_value': 1.0, 'algorithm_type': 'sde-dpmsolver++',
                         'solver_type': 'midpoint', 'lower_order_final': True, 'use_karras_sigmas': True,
                         'final_sigmas_type': 'zero', 'timestep_spacing': 'linspace', 'solver_order': 2}
02:02:06-178596 DEBUG    Torch generator: device=cuda seeds=[3791978311]
02:02:06-183601 DEBUG    Diffuser pipeline: StableDiffusionXLInpaintPipeline task=DiffusersTaskType.INPAINTING
                         batch=1/1x1 set={'prompt_embeds': torch.Size([1, 77, 2048]), 'pooled_prompt_embeds':
                         torch.Size([1, 1280]), 'negative_prompt_embeds': torch.Size([1, 77, 2048]),
                         'negative_pooled_prompt_embeds': torch.Size([1, 1280]), 'guidance_scale': 6,
                         'num_inference_steps': 50, 'eta': 1.0, 'guidance_rescale': 0.7, 'denoising_start': None,
                         'denoising_end': None, 'output_type': 'latent', 'image': [<PIL.Image.Image image mode=RGB
                         size=512x512 at 0x20BBA21C2B0>], 'mask_image': <PIL.Image.Image image mode=L size=512x512 at
                         0x20BBA21EB00>, 'strength': 0.4, 'height': 512, 'width': 512, 'parser': 'Full parser'}
Progress  2.66it/s █████████████████████████████████ 100% 20/20 00:07 00:00 Base
02:02:15-423167 DEBUG    GC: utilization={'gpu': 87, 'ram': 12, 'threshold': 80} gc={'collected': 1336, 'saved': 3.14}
                         before={'gpu': 10.42, 'ram': 1.87} after={'gpu': 7.28, 'ram': 1.64, 'retries': 0, 'oom': 0}
                         device=cuda fn=nextjob time=0.44
02:02:18-381793 DEBUG    GC: utilization={'gpu': 100, 'ram': 24, 'threshold': 80} gc={'collected': 254, 'saved': 4.6}
                         before={'gpu': 11.98, 'ram': 3.89} after={'gpu': 7.38, 'ram': 1.75, 'retries': 0, 'oom': 0}
                         device=cuda fn=vae_decode time=0.73
02:02:18-420829 DEBUG    Pipeline class change: original=StableDiffusionXLInpaintPipeline
                         target=StableDiffusionXLPipeline device=cuda:0 fn=process_images_inner
02:02:18-426836 INFO     Processed: images=1 time=12.42 its=1.61 memory={'ram': {'used': 1.76, 'total': 15.95}, 'gpu':
                         {'used': 7.38, 'total': 11.98}, 'retries': 0, 'oom': 0}
02:02:18-755144 INFO     Save: image="outputs\text\00192-epicrealismXL_v8Kiss-A woman sitting in a cafe sitting
                         table.png" type=PNG resolution=512x512 size=340530
02:02:18-763142 INFO     Processed: images=1 time=37.41 its=0.53 memory={'ram': {'used': 1.75, 'total': 15.95}, 'gpu':
                         {'used': 7.38, 'total': 11.98}, 'retries': 0, 'oom': 0}
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
> is the issue maybe because of 512x512 and not generating at 1024x1024?

every model has list of optimal resolutions. sdxl doesn't have to be just 1024x1024, but 512x512 is inadequate for sure.
i suggest to reach out on discord for advices.

**Comment by Hunter9886** [comment]
@vladmandic does 1.5 SD checkpoints and models work on Sdnext??

**Comment by vladmandic** [comment]
of course. any many more models.
list is in main readme.

**Comment by Hunter9886** [comment]
@vladmandic when i downloaded a 1.5 model famous called epicphotogasm and tried it , it generated blurry images , how to fix that???

**Comment by vladmandic** [comment]
please ask general help questions on discord. I can't say what to change when I don't know how blurry it look and don't know which settings are you using.

For controlnet, check wiki. for standard models such as canny, you don't need to download anything. manual download is allowed and possible, but only needed if you need a model that is not already on a list (which is quite extensive).

**Comment by Hunter9886** [comment]
@vladmandic alright thanks, i apologize.
