### ISSUE TITLE
[Issue]: STEALER MALWARE IN SETUP FILE

### ISSUE THREAD

**Issue by skep1337** [vladmandic/automatic#3347]
### Issue Description

The installation page has a Windows download that is not sd.next, but rather malware.

https://github.com/vladmandic/automatic/wiki/Installation

Evidence: https://app.any.run/tasks/4a501baf-034e-4c8f-b528-1b8618045c8a/

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by skep1337** [comment]
It seems the install page was updated by a brand new, random account just hours ago

**Comment by vladmandic** [comment]
i've reverted his edits and reported the user- thanks for bringing it to attention

**Comment by GreenGhost21** [comment]
Seems it happened again about 13 hours ago?

**Comment by GreenGhost21** [comment]
Edited the page myself to remove the links.

**Comment by vladmandic** [comment]
thank you.
we're planning to move from wiki to docs page to have better search/indexing and avoid such issues in the future.
