### ISSUE TITLE
[Issue]: WD14 tagger seems to make problem

### ISSUE THREAD

**Issue by ppkppk8520** [vladmandic/automatic#335]
### Issue Description

after installed wd14 tagger(https://github.com/toriato/stable-diffusion-webui-wd14-tagger), i got error.
i can generate images even after the error but can't use lora and lycoris.

Module load: G:\automatic\extensions-builtin\a1111-sd-webui-lycoris\scripts\lycoris_script.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ G:\automatic\modules\script_loading.py:10 in load_module                                                            │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 3 frames hidden ...                                               │
│                                                                                                                     │
│ G:\automatic\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora.py:362 in <module>        │
│                                                                                                                     │
│   361                                                                                                               │
│ > 362 list_available_loras()                                                                                        │
│   363                                                                                                               │
│                                                                                                                     │
│ G:\automatic\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora.py:343 in                 │
│ list_available_loras                                                                                                │
│                                                                                                                     │
│   342 │                                                                                                             │
│ > 343 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)                                                      │
│   344                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Namespace' object has no attribute 'lora_dir'
Module load: G:\automatic\extensions-builtin\Lora\scripts\lora_script.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ G:\automatic\modules\script_loading.py:10 in load_module                                                            │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ G:\automatic\extensions-builtin\Lora\lora.py:362 in <module>                                                        │
│                                                                                                                     │
│   361                                                                                                               │
│ > 362 list_available_loras()                                                                                        │
│   363                                                                                                               │
│                                                                                                                     │
│ G:\automatic\extensions-builtin\Lora\lora.py:343 in list_available_loras                                            │
│                                                                                                                     │
│   342 │                                                                                                             │
│ > 343 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)                                                      │
│   344                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Namespace' object has no attribute 'lora_dir'

### Version Platform Description

windows10

**Comment by gharmonica** [comment]
I'm having the same error without installing the WD14 tagger. But I did install the OpenOutpaint Extension.

**Comment by CKwasd** [comment]
```
venv "E:\automatic\venv\Scripts\Python.exe"
2023-04-21 23:00:58,478 | WARNING | E:\automatic\venv\lib\site-packages\xformers\__init__.py | A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
E:\automatic\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
23:00:59-089315 INFO     Python 3.10.0 on Windows
23:00:59-160361 INFO     Running setup
23:00:59-233476 INFO     Version: cf80857b Fri Apr 21 09:59:50 2023 -0400
23:01:00-038166 INFO     Updating Wiki
23:01:02-659611 INFO     nVidia toolkit detected
23:01:02-661611 INFO     Torch 2.0.0+cu118
23:01:02-662611 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
23:01:02-662611 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10240 Arch (8, 6) Cores 68
23:01:02-663611 INFO     Installing requirements
23:01:02-674119 INFO     Installing packages
23:01:02-675118 INFO     Installing repositories
23:01:02-976596 INFO     Installing submodules
23:01:06-108192 INFO     Updating submodules

23:01:26-993664 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui

                                                                                                                      i-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-remb                        bg', 'SwinIR']
23:01:56-471350 INFO     Extensions enabled: ['a1111-sd-webui-tagcomplete'                                            , 'openOutpaint-webUI-extension',
                         'sd-webui-additional-networks', 'stable-diffusion-webui-dataset-tag-e                        editor',
                         'stable-diffusion-webui-wd14-tagger']

23:02:08-742914 INFO     Setting environment tuning

23:02:08-743913 INFO     Server arguments: ['--upgrade', '--medvra                                                    am']
Available models: models\Stable-diffusion 3
Module load: E:\automatic\extensions-builtin\a1111-sd-webui-lycoris\scripts\lycoris_script.py: AttributeError
╭───────────────────────────────────────── Traceback (most recent call l                                              last) ─────────────────────────────────────────╮
│ E:\automatic\modules\script_loading.py:10 in load_module
                                   │
│
        │
│    9 │   try:
                                 │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)
                         │
│   11 │   except Exception as e:
                                                   │
│ in exec_module:883
                          │
│
               │
│                                               ... 3 frames hidden ...
               │
│
        │
│ E:\automatic\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora.                          .py:382 in <module>        │
│
        │
│   381
                │
│ ❱ 382 list_available_loras()
                 │
│   383
                │
│
        │
│ E:\automatic\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora.                          .py:363 in                 │
│ list_available_loras
                 │
│
        │
│   362 │
                        │
│ ❱ 363 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)
                                  │
│   364
                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────    ─────╯
AttributeError: 'Namespace' object has no attribute 'lora_dir'
Module load: E:\automatic\extensions-builtin\Lora\scripts\lora_script.py: AttributeError
╭───────────────────────────────────────── Traceback (most recent call l                                              last) ─────────────────────────────────────────╮
│ E:\automatic\modules\script_loading.py:10 in load_module
                                   │
│
        │
│    9 │   try:
                                 │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)
                         │
│   11 │   except Exception as e:
                                                   │
│ in exec_module:883
                          │
│
               │
│                                               ... 2 frames hidden ...
               │
│
        │
│ E:\automatic\extensions-builtin\Lora\lora.py:382 in <module>
                                   │
│
        │
│   381
                │
│ ❱ 382 list_available_loras()
                 │
│   383
                │
│
        │
│ E:\automatic\extensions-builtin\Lora\lora.py:363 in list_available_loras
                                   │
│
        │
│   362 │
                        │
│ ❱ 363 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)
                                  │
│   364
                │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────    ─────╯
AttributeError: 'Namespace' object has no attribute 'lora_dir'
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Loading theme: gradio/default
executing callback: E:\automatic\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py ui_tabs_callback:
AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────╮
│ E:\automatic\modules\script_callbacks.py:122 in ui_tabs_callback                                                    │
│                                                                                                                     │
│   121 │   │   try:                                                                                                  │
│ ❱ 122 │   │   │   res += c.callback() or []                                                                         │
│   123 │   │   except Exception as e:                                                                                │
│                                                                                                                     │
│ E:\automatic\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py:329 in on_ui_tabs                           │
│                                                                                                                     │
│   328 │   │   │   │   │   with gr.Row(variant='compact'):                                                           │
│ ❱ 329 │   │   │   │   │   │   interrogator_names = utils.refresh_interrogators()                                    │
│   330 │   │   │   │   │   │   interrogator = utils.preset.component(                                                │
│                                                                                                                     │
│ E:\automatic\extensions\stable-diffusion-webui-wd14-tagger\tagger\utils.py:70 in refresh_interrogators              │
│                                                                                                                     │
│   69 │                                                                                                              │
│ ❱ 70 │   for path in os.scandir(shared.cmd_opts.deepdanbooru_projects_path):                                        │
│   71 │   │   if not path.is_dir():                                                                                  │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'
```
full log with error

**Comment by vladmandic** [comment]
extension `stable-diffusion-webui-wd14-tagger` is trying to read unknown command line flag `deepdanbooru_projects_path`. that flag does not exist in core repo (here or in a1111) nor in this extension. my best guess is that this extension relies on some other extension to set that flag or flag, but that is a really really bad design. report issue in that extension, its not a core issue and will not be addressed here.

**Comment by Panchvzluck** [comment]
I made it work but it's entirely based on the author of wd14 tagger fixing it.

Basically adding the argument on cmdargs, removing the load_parser function of preload.py of the extension, then setting the path manually.

Finally, moving the extension to the extensions-builtin folder makes it work, and loras work as well.

So if you must use the tagger, you can do that or use the auto111 webui (probably the latter is a better way)

**Comment by GiusTex** [comment]
> 

Thanks, it worked! I had also to close the command window and restart it.
If anyone has trouble these are the steps I followed, according to Panchvzluck:
1. Move WD14 tagger extension from "estensions" to "extensions-builtin";
2. Open preload.py in WD14 tagger and remove or comment out (add # before every line) these lines:
`def preload(parser: ArgumentParser):
     default deepdanbooru use different paths:
     models/deepbooru and models/torch_deepdanbooru
     https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/c81d440d876dfd2ab3560410f37442ef56fc6632

    parser.add_argument(
        '--deepdanbooru-projects-path',
        type=str,
        help='Path to directory with DeepDanbooru project(s).',
        default=default_ddp_path
    )`
3. In automatic>modules open cmd_args.py and add at line 47 this:
`parser.add_argument('--deepdanbooru-projects-path', type=str, help='Path to directory with DeepDanbooru project(s).', default="your/path")`
I changed your/path with "C:/Users/YourUserName/.cache/huggingface/hub/models--SmilingWolf--wd-v1-4-vit-tagger-v2/snapshots/1f3f3e8ae769634e31e1ef696df11ec37493e4f2" (use / and not \ ; for me this path is working);
4. Close the command window of the webui and restart it

**Comment by vladmandic** [comment]
> Move WD14 tagger extension from "estensions" to "extensions-builtin";

If you move extension from `/extensions`, to `/extensions-builtin` and that solves it, that means extension is in conflict with some other extension and you just changed order in which they are loaded. so you fixed this one, but very likely broke something else.

**Comment by GiusTex** [comment]
> 

Damn, I didn't know it. If I found what has been broken I'll post it here and disable wf14-tagger then

**Comment by Panchvzluck** [comment]
@GiusTex You're right, after doing that, the extension works fine on the extensions folder. So I guess it's something related to the parser or the argument itself.

**Comment by vladmandic** [comment]
i've already mentioned, that argument does not exist. it was removed looooong time ago, but extension wasn't updated.
it only works on a1111 if you had it months ago so your `config.json` still carries dead entries. if you did clean install of a1111, it also wouldn't work.

**Comment by pldsofficial** [comment]
reported the problem, but original author has quit webui so it is likely that he will not maintain the extension.

**Comment by pldsofficial** [comment]
add this in 65th row of tagger/utils.py

deepdanbooru_projects_path = "A:/AI_Illust/automatic/models/torch_deepdanbooru"
    shared.cmd_opts.deepdanbooru_projects_path = deepdanbooru_projects_path

**Comment by GeneralAwareness** [comment]
> add this in 65th row of tagger/utils.py
> 
> deepdanbooru_projects_path = "A:/AI_Illust/automatic/models/torch_deepdanbooru" shared.cmd_opts.deepdanbooru_projects_path = deepdanbooru_projects_path

Doesn't work.

![image](https://user-images.githubusercontent.com/124339252/234735390-577b90cc-3497-44b1-b7d2-a20413929bbe.png)

**Comment by zethfoxster** [comment]
this is convoluted 
change youre preload to this instead but pointing to the location of your hugging face cache for it.

from pathlib import Path
from argparse import ArgumentParser

default_ddp_path = "C:/Users/omega/.cache/huggingface/hub/models--SmilingWolf--wd-v1-4-vit-tagger-v2/snapshots/1f3f3e8ae769634e31e1ef696df11ec37493e4f2"

def preload(parser: ArgumentParser):
    # default deepdanbooru use different paths:
    # models/deepbooru and models/torch_deepdanbooru
    # https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/c81d440d876dfd2ab3560410f37442ef56fc6632

    parser.add_argument(
        '--deepdanbooru-projects-path',
        type=str,
        help='Path to directory with DeepDanbooru project(s).',
        default=default_ddp_path
    )

**Comment by GiusTex** [comment]
If anyone is interested I made a [repo](https://github.com/GiusTex/vladmandic-WD14-Tagger) with instructions and files on how to use wd14-tagger on vladmandic

**Comment by zethfoxster** [comment]
> 

you made it with the convoluted fix. the fix i posted just above you the models load in and out as normal with the drop downs as before. just point it to a default model to load as i showed above, and use it as it is.
due to folder structure change in vlads it cant find its default model cache to load. it just needs to be pointed to it. nothing else.

**Comment by GiusTex** [comment]
I think I have done right, I used your solution in fact (I'll add you too in the credits, sorry).
The "new" preload.py:
```
username = os.getenv('USERNAME')
default_ddp_path = f"C:/Users/{username}/.cache/huggingface/hub/models--SmilingWolf--wd-v1-4-vit-tagger-v2/snapshots/1f3f3e8ae769634e31e1ef696df11ec37493e4f2"

def preload(parser: ArgumentParser):
    parser.add_argument(
        '--deepdanbooru-projects-path',
        type=str,
        help='Path to directory with DeepDanbooru project(s).',
        default=default_ddp_path
    )
```
The new utils.py:
```
# Where to look for the model folder
    username = os.getenv('USERNAME')
    deepdanbooru_projects_path = f"C:/Users/{username}/.cache/huggingface/hub/models--SmilingWolf--wd-v1-4-vit-tagger-v2/snapshots/1f3f3e8ae769634e31e1ef696df11ec37493e4f2"
    # create folder if it doesn't exist
    os.makedirs(deepdanbooru_projects_path, exist_ok=True)

    # Load model
    for path in os.scandir(deepdanbooru_projects_path):
     #...
```
The problem is that when you select a new model from the dropdown it downlaods and uses it, but every time you tag something else the script looks for the dropdown-model in the hard-coded default path, doesn't find it and downloads it again
