### ISSUE TITLE
[Feature]: Control: Allow resizing the input images in Control units to match the target resolution aspect ratio

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3362]
### Feature description

When using an input image, even for control only, there is quite some flexibility on how to handle the resizing to match the target resolution (or not match it at all). This is not possible for the input images for each individual unit, and the result is that while the preview for the control images looks correct, images end up being distorted when generating (because the input control images are resized without any regard of the aspect ratio). This means that unless using preprocessors, existing processed images need to be adjusted for the target aspect ratio.

IOW, if I use a depth image (example) in 9:16 aspect ratio to generate an image in 16:9, the result will look "squashed".

Note that I'm not advocating for complicated options (in fact it's already complicated enough), but allowing the resizing to match the aspect ratio, to avoid distortions. This allows re-use of preprocessed images (or poses found for example on Civitai) without having to adjust them.

**Comment by vladmandic** [comment]
added in dev branch. 
from changelog:
- control module allows reszing of indivudual process override images to match input image  
  for example: set size->before->method:nearest, mode:fixed or mode:fill

**Comment by lbeltrame** [comment]
Thanks Vlad! I'll give it a spin soon and see how it goes.
