### ISSUE TITLE
[Issue]: Aura SR 4x upscaler blows up at the end of upscaling when "Unload upscaler after processing" option is checked

### ISSUE THREAD

**Issue by AznamirWoW** [vladmandic/automatic#3367]
### Issue Description

unlike other upscaler scripts aurasr_model.py does not populate self.models, so it breaks on this line
`
if shared.opts.upscaler_unload and selected_model in self.models:`

should replace with 

`if shared.opts.upscaler_unload:`

### Version Platform Description

dev

### Backend

Diffusers

### UI

ModernUI

### Branch

Dev

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
since you already found the cause and solution, why not do a pr?

**Comment by AznamirWoW** [comment]
> since you already found the cause and solution, why not do a pr?

done
