### ISSUE TITLE
[Issue]: Input types tensor are not broadcast compatible on Apple M1

### ISSUE THREAD

**Issue by WojtekKowaluk** [vladmandic/automatic#337]
### Issue Description

Fresh install of app, when trying to generate any image I get error and app shuts down:
```
loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<2x1280xf32>' and 'tensor<1280xf16>' are not broadcast compatible
```

AUTOMATIC1111 works great with:
- torch==2.1.0.dev20230311 torchvision==0.15.0.dev20230311
- --skip-torch-cuda-test --upcast-sampling --opt-sub-quad-attention --use-cpu interrogate

but somehow I can't recreate same settings with vladmandic and always get this error.

### Version Platform Description

Apple MacBook Pro M1
macOS: Ventura 13.3

**Comment by lambadalambda** [comment]
This is something that happened to me too on an M2 after restarting webui. I think it did an automatic update, which made this break.

**Comment by vladmandic** [comment]
anything M1/M2, lets continue at #347
