### ISSUE TITLE
[Feature]: Control: Offload model if unit is inactive

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3379]
### Feature description

I was victim of an OOM because while I disabled a ControlNet unit, its model was still loaded, causing an out of memory error. Setting it to None fixed it, but my expectation is that inactive units do not have loaded models (like the old ControlNet extension did).

This is not a bug, but an additional feature, so it is marked as a feature request.

**Comment by vladmandic** [comment]
i'm not sure if this is logical - loaded-but-disabled is not the same as not-loaded-at-all.
we can talk about having better offloading for loaded controlnet models, but not force-unloading when disabled.

**Comment by lbeltrame** [comment]
Probably better to word as "offload" rather than "unload", I agree (the downsinde in the old CN extension is that it *significantly* slowed down startup due to that). I'll adjust the title.

**Comment by vladmandic** [comment]
added in dev.
