### ISSUE TITLE
[Feature]: Condense the dropdowns on main page?

### ISSUE THREAD

**Issue by some9000** [vladmandic/automatic#338]
### Feature description

Hi! I was working on my extension and thinking about ways to clean up/compact interface and, actually, seems like **automatic** may also benefit from something like that? Example:
![image](https://user-images.githubusercontent.com/17021558/233598513-6eff4a36-1c72-47c6-94f1-875f7359f4f4.png)
How about having a "main" Accordion, as gradio calls it, for Advanced tools and then put Tiled Diffusion, Tiled VAE, Enable Dynamic Thresholding, Steps animation, ControlNet and whatever else comes up in there?

And, another point - are those Accordions correctly implemented in the interface? Their bottoms do not close the way you would expect, like they do on the ones below.

**Comment by Woisek** [comment]
In regard of this section a question: is it somehow possible to configure the order in which the dropdowns appear?

**Comment by vladmandic** [comment]
> How about having a "main" Accordion

I think it would hide too much.

> In regard of this section a question: is it somehow possible to configure the order in which the dropdowns appear?

They appear in order in which they are loaded: modules, extensions-builtin, extensions, scripts
I have it on my todo list to support custom ordering, tracking separately.

> Are those Accordions correctly implemented in the interface? Their bottoms do not close the way you would expect, like they do on the ones below.

Each "plugin" is responsible for its own UI, its not enforced from the main UI.

**Comment by Woisek** [comment]
>I have it on my todo list to support custom ordering, tracking separately.

Cool! Looking forward to it. 👍 Thanks!

**Comment by vladmandic** [comment]
fyi, custom ordering of tabs and scripts is now available.

**Comment by Woisek** [comment]
Hmm .. can't see it in the "User Interface" section ... ?! 😶

**Comment by vladmandic** [comment]
UI Settings -> User Interface
![image](https://github.com/vladmandic/automatic/assets/57876960/1061d240-bdaf-4580-8708-8ea3ad06ecaf)

**Comment by Woisek** [comment]
![Zwischenablagebild](https://github.com/vladmandic/automatic/assets/122026301/005d24a8-a7d2-4252-b3b7-9d475f2ff848)
Version: 4d9fab49 Mon May 8 11:56:59 2023 -0400

**Comment by Woisek** [comment]
Ah ... I did a pull twice and it did not update ... 😐

**Comment by Woisek** [comment]
OK, see it now ... But how do we know what to enter ... ? 🤔

**Comment by vladmandic** [comment]
its a `string.startswith()` match.
so whatever is in the ui, enter that as comma sparate strings.

for example, to have controlnet on top, just enter controlnet, no need for full string which also includes version.

**Comment by Woisek** [comment]
![Zwischenablagebild (1)](https://github.com/vladmandic/automatic/assets/122026301/c47fbcba-ee4e-41ef-a7b6-2d9cfab7fe76)

OK, so I can just use the titles of the entries? Are spaces supported? How do I address the resolution/aspect ratio buttons ... ?

**Comment by Woisek** [comment]
Alright, will test it.
But here is a new issue for you 😁:
When I start up, the top nav is like this:
![Zwischenablagebild](https://github.com/vladmandic/automatic/assets/122026301/73210c01-5648-4d8c-a274-32d1036f95f6)
when I select "Settings" the nav change to this:
![Zwischenablagebild (1)](https://github.com/vladmandic/automatic/assets/122026301/4e1d9729-9f07-47ac-8b98-d42957ba2460)
and it doesn't change back.
Any ideas? 🤔

**Comment by vladmandic** [comment]
when you change order, you need to restart server and reload browser.

**Comment by Woisek** [comment]
>when you change order, you need to restart server and reload browser.

Yes, of course. But that's not what I mean. It's like I wrote.
Or simply said: Clicking "Settings" changes the navigation entries you see in the screen shots.

While I'm writing this, I noticed, that this is not specific to "Settings". Depending on which tab you click, the navigation tabs shift. Like, the sorting is active on a visible level at first, but clicking a tab changes to another order (the original one maybe)? It's weird ... 🤪
Did no one noticed that yet?

**Comment by vladmandic** [comment]
working on it. issue is that gradio replaces selected button instead of marking existing one as selected, so it looses order property.

**Comment by vladmandic** [comment]
fixed.

**Comment by Woisek** [comment]
Yeah, that was fast. 👍
Just one more thing. Look here:
![Zwischenablagebild (2)](https://github.com/vladmandic/automatic/assets/122026301/b9eb303c-c658-4f15-af46-d4ac2012d9d7)
You can see in the UI tabs order, "Model Previews" should go after "Promptgen". But looking at the tabs shows the "Model Previews" way later. Any ideas on that?
