### ISSUE TITLE
[Extension]: Lora styles not affecting output image

### ISSUE THREAD

**Issue by leakerbeaker69** [vladmandic/automatic#3382]
### Issue Description

So any character Lora's that I try to use, don't really affect the output image. I'm using vlad fork a1111 sdnext on amd gpu. I copied all the settings(same model/prompt/cfg/steps/sampler/seed), the only difference is excluding some negative prompts such as "too much detail, DeepNegative_xl_v1, BREAK. makeup, lipstick, angry, frowning, disembodied, floating". Does anyone know what I'm doing wrong? Also, not sure why my output is doing "3d" instead of "2d".

[Link](https://www.reddit.com/r/StableDiffusion/comments/1es9tg6/lora_styles_not_affecting_output_image/) to my reddit post with example images.

Here are my prompts:

```
score_9, score_8_up, score_7_up, score_6_up, score_5_up, score_4_up, flat color, source_anime, 2d, BREAK. indoors, blush, smile, looking at viewer, BREAK. uncensored, nsfw, source_explicit, rating_explicit, BREAK. cowboy shot, BREAK. superhero, bodysuit, long sleeves, red skirt, mini skirt, red cape, thighhighs, red footwear, thigh boots, BREAK. <lora:Supergirl(LOS)_v1:1.3>, 1girl, solo, blue eyes, long hair, blonde hair
```

```
score_4, score_5, score_6, BREAK. 3d, render
```

### Version Platform Description

Using VENV: E:\automatic\venv
01:26:23-734842 INFO     Starting SD.Next
01:26:23-742356 INFO     Logger: file="E:\automatic\sdnext.log" level=INFO size=15192707 mode=append
01:26:23-743405 INFO     Python version=3.10.11 platform=Windows bin="E:\automatic\venv\Scripts\python.exe"
                         venv="E:\automatic\venv"
01:26:24-012003 INFO     Version: app=sd.next updated=2024-07-24 hash=a874b27e branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
01:26:24-540282 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 2, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
01:26:24-542299 INFO     HF cache folder: C:\Users\jason\.cache\huggingface\hub
01:26:24-552664 INFO     Python version=3.10.11 platform=Windows bin="E:\automatic\venv\Scripts\python.exe"
                         venv="E:\automatic\venv"
01:26:24-554707 INFO     AMD ROCm toolkit detected
01:26:24-584203 WARNING  ZLUDA support: experimental
01:26:35-122728 INFO     Using ZLUDA in E:\automatic\.zluda
01:26:35-536437 INFO     Verifying requirements
01:26:35-546591 INFO     Verifying packages
01:26:35-697169 INFO     Extensions: disabled=['sdnext-modernui']
01:26:35-698183 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-rembg'] extensions-builtin
01:26:35-715522 INFO     Extensions: enabled=['adetailer', 'sd-webui-controlnet', 'sd-webui-mosaic-outpaint'] extensions
01:26:35-750503 INFO     Startup: quick launch
01:26:35-765392 INFO     Extensions: disabled=['sdnext-modernui']
01:26:35-766423 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-rembg'] extensions-builtin
01:26:35-772033 INFO     Extensions: enabled=['adetailer', 'sd-webui-controlnet', 'sd-webui-mosaic-outpaint'] extensions
01:26:35-787352 INFO     Command line args: ['--use-zluda', '--autolaunch', '--lowvram'] lowvram=True autolaunch=True
                         use_zluda=True

### URL link of the extension

https://civitai.com/models/564247/supergirl-legion-of-super-heroes-ponyxl

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by brknsoul** [comment]
Is your lora surrounded by angle brackets? Git comments strip them out, so you should encase your prompts in triple-back ticks;

\`\`\`
like
this
\`\`\`

becomes
```
like
this
```

**Comment by leakerbeaker69** [comment]
Hi, yes my lora is surrounded by angle brackets. I've updated the post with the correct prompt structure.

**Comment by vladmandic** [comment]
this issue is invalid - its not an extension thing since you did not install extension for lora
which also means that issue template is incomplete - i don't have enough information about your environment at all.
please refile with required information.
