### ISSUE TITLE
[Issue]: saving image via SAVE button doesn't properly replace [seed] in filename

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3385]
### Issue Description

When you manually save a result, `[seed]` gets replaced by an empty string. So `[job_timestamp]-[seed]` will result in something like `00043-20240830132350-.webp`

This did work 12 hours ago.

### Version Platform Description

WSL-2, Win11, SDNext version ed45477

### Relevant log output

```shell
13:23:50-848279 INFO     Save: image="/home/tillerz/images/2024-08-30/00043-20240830132350-.webp" type=WEBP resolution=1024x1538 size=341358
```

### Backend

Diffusers

### UI

ModernUI

### Branch

Dev

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
weird, nothing changed in that area of the code. i'll check.

**Comment by Tillerz** [comment]
Looks like it's even worse. It doesn't also save any metadata into the image. This is the metadata in the saved webp:

![image](https://github.com/user-attachments/assets/ad02e702-7a8c-429b-87a4-dbdee4a44712)

**Comment by Tillerz** [comment]
Ok, this all resolved with a fresh checkout of dev/ and not copying over my settings / ui settings or installing any modules. I'll keep a close I on when I readd stuff, where it breaks.
