### ISSUE TITLE
[Issue]: Gallery not sorting on dev

### ISSUE THREAD

**Issue by MysticDaedra** [vladmandic/automatic#3386]
### Issue Description

Choosing any of the sorting options under the Gallery tab after selecting a folder (in my case the text/txt2img folder) returns 0 images, even if images started to load when initially selecting the folder. The result is an empty gallery page. Worked previously, but I can't remember which dev build I was on when it last worked.

### Version Platform Description

09:30:55-987986 INFO     Starting SD.Next
09:30:55-991489 INFO     Logger: file="D:\automatic\sdnext.log" level=DEBUG size=65 mode=create
09:30:55-992495 INFO     Python version=3.11.8 platform=Windows bin="D:\automatic\venv\Scripts\Python.exe"
                         venv="D:\automatic\venv"
09:30:56-346546 INFO     Version: app=sd.next updated=2024-08-29 hash=ec85ab40 branch=dev
                         url=https://github.com/vladmandic/automatic/tree/dev ui=dev
09:30:57-024329 INFO     Updating main repository
09:31:01-894677 INFO     Upgraded to version: ed45477a Thu Aug 29 21:31:55 2024 -0400
09:31:01-901678 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.11.8
09:31:01-903678 DEBUG    Setting environment tuning
09:31:01-904677 INFO     HF cache folder: C:\Users\Joshua\.cache\huggingface\hub
09:31:01-905678 DEBUG    Torch allocator:
                         "garbage_collection_threshold:0.20,max_split_size_mb:512,backend:cudaMallocAsync"
09:31:01-921126 DEBUG    Torch overrides: cuda=False rocm=False ipex=False diml=False openvino=False
09:31:01-922124 DEBUG    Torch allowed: cuda=True rocm=True ipex=True diml=True openvino=True
09:31:01-933131 INFO     nVidia CUDA toolkit detected: nvidia-smi present
09:31:02-272086 INFO     Verifying requirements
09:31:02-281086 INFO     Verifying packages
09:31:02-282086 INFO     Startup: standard
09:31:02-283088 INFO     Verifying submodules
09:31:05-298645 DEBUG    Submodule: extensions-builtin/sd-extension-chainner / main
09:31:05-937792 DEBUG    Submodule: extensions-builtin/sd-extension-system-info / main
09:31:06-690293 DEBUG    Submodule: extensions-builtin/sd-webui-agent-scheduler / main
09:31:07-319978 DEBUG    Submodule: extensions-builtin/sdnext-modernui / dev
09:31:08-014413 DEBUG    Submodule: extensions-builtin/stable-diffusion-webui-rembg / master
09:31:08-680991 DEBUG    Submodule: modules/k-diffusion / master
09:31:09-441442 DEBUG    Git detached head detected: folder="wiki" reattach=master
09:31:09-442369 DEBUG    Submodule: wiki / master
09:31:10-347900 DEBUG    Register paths
09:31:10-419958 DEBUG    Installed packages: 202
09:31:10-421957 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg']
09:31:11-026860 DEBUG    Submodule: extensions-builtin\sd-extension-chainner / main
09:31:11-726437 DEBUG    Submodule: extensions-builtin\sd-extension-system-info / main
09:31:12-460796 DEBUG    Submodule: extensions-builtin\sd-webui-agent-scheduler / main
09:31:13-110838 DEBUG    Running extension installer:
                         D:\automatic\extensions-builtin\sd-webui-agent-scheduler\install.py
09:31:13-499521 DEBUG    Submodule: extensions-builtin\stable-diffusion-webui-images-browser / main
09:31:14-163953 DEBUG    Running extension installer:
                         D:\automatic\extensions-builtin\stable-diffusion-webui-images-browser\install.py
09:31:14-539138 DEBUG    Submodule: extensions-builtin\stable-diffusion-webui-rembg / master
09:31:15-142067 DEBUG    Running extension installer:
                         D:\automatic\extensions-builtin\stable-diffusion-webui-rembg\install.py
09:31:15-484352 DEBUG    Extensions all: ['adetailer', 'canvas-zoom', 'sd-webui-infinite-image-browsing',
                         'sd-webui-temporal', 'ultimate-upscale-for-automatic1111']
09:31:15-528866 DEBUG    Submodule: extensions\adetailer / main
09:31:16-262235 DEBUG    Running extension installer: D:\automatic\extensions\adetailer\install.py
09:31:16-686260 DEBUG    Submodule: extensions\canvas-zoom / main
09:31:17-339569 DEBUG    Running extension installer: D:\automatic\extensions\canvas-zoom\install.py
09:31:27-034481 DEBUG    Submodule: extensions\sd-webui-infinite-image-browsing / main
09:31:27-694575 DEBUG    Running extension installer:
                         D:\automatic\extensions\sd-webui-infinite-image-browsing\install.py
09:31:35-046637 DEBUG    Submodule: extensions\sd-webui-temporal / master
09:31:35-866111 DEBUG    Submodule: extensions\ultimate-upscale-for-automatic1111 / master
09:31:36-528877 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'stable-diffusion-webui-images-browser',
                         'stable-diffusion-webui-rembg', 'adetailer', 'canvas-zoom', 'sd-webui-infinite-image-browsing',
                         'sd-webui-temporal', 'ultimate-upscale-for-automatic1111']
09:31:36-529876 INFO     Verifying requirements
09:31:36-530876 INFO     Updating Wiki
09:31:36-561876 DEBUG    Submodule: D:\automatic\wiki / master
09:31:37-144804 DEBUG    Setup complete without errors: 1725035497
09:31:37-153804 DEBUG    Extension preload: {'extensions-builtin': 0.01, 'extensions': 0.0}
09:31:37-154804 DEBUG    Starting module: <module 'webui' from 'D:\\automatic\\webui.py'>
09:31:37-155801 INFO     Command line args: ['--debug', '--upgrade', '--share'] share=True upgrade=True debug=True
09:31:37-157446 DEBUG    Env flags: ['SD_MASK_DEBUG=true']
09:31:52-775234 INFO     Load packages: {'torch': '2.3.1+cu121', 'diffusers': '0.30.1', 'gradio': '3.43.2'}
09:31:54-612018 INFO     VRAM: Detected=8.0 GB Optimization=medvram
09:31:54-613615 DEBUG    Read: file="config.json" json=76 bytes=4846 time=0.000
09:31:54-614614 DEBUG    Unknown settings: ['cross_attention_options', 'ad_max_models', 'civitai_link_key',
                         'multiple_tqdm', 'ad_same_seed_for_each_tap', 'mudd_states', 'civitai_folder_lyco',
                         'diffusers_aesthetics_score', 'image_browser_active_tabs', 'ad_extra_models_dir',
                         'canvas_zoom_mask_clear', 'canvas_zoom_draw_staight_lines', 'ad_script_names']
09:31:54-616614 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda attention="Scaled-Dot-Product"
                         mode=no_grad
09:31:54-631661 INFO     Device: device=NVIDIA GeForce RTX 3070 n=1 arch=sm_90 cap=(8, 6) cuda=12.1 cudnn=8907 driver=
09:31:54-638472 DEBUG    Read: file="html\reference.json" json=52 bytes=29118 time=0.006
09:31:55-378966 TRACE    Trace: MASK
09:31:55-703695 DEBUG    ONNX: version=1.18.0 provider=CUDAExecutionProvider, available=['TensorrtExecutionProvider',
                         'CUDAExecutionProvider', 'CPUExecutionProvider']

### Relevant log output

```shell
09:32:38-340873 INFO     MOTD: N/A
09:32:47-792203 DEBUG    UI themes available: type=Standard themes=12
09:33:37-269478 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64;
                         rv:129.0) Gecko/20100101 Firefox/129.0
09:33:59-804779 DEBUG    Server: alive=True jobs=1 requests=204 uptime=126 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
09:35:59-842088 DEBUG    Server: alive=True jobs=1 requests=228 uptime=246 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
09:37:59-877243 DEBUG    Server: alive=True jobs=1 requests=251 uptime=366 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
09:39:59-914481 DEBUG    Server: alive=True jobs=1 requests=275 uptime=486 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
09:41:59-947120 DEBUG    Server: alive=True jobs=1 requests=299 uptime=606 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
09:43:59-983677 DEBUG    Server: alive=True jobs=1 requests=323 uptime=726 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
09:46:00-021038 DEBUG    Server: alive=True jobs=1 requests=346 uptime=846 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
09:48:00-056777 DEBUG    Server: alive=True jobs=1 requests=370 uptime=966 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
09:50:00-095099 DEBUG    Server: alive=True jobs=1 requests=394 uptime=1086 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
09:50:43-954448 DEBUG    Gallery: folder="D:\Stable Diffusion Files\Outputs\text" files=1780 time=0.089
09:52:00-276687 DEBUG    Server: alive=True jobs=1 requests=453 uptime=1207 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
09:54:00-312712 DEBUG    Server: alive=True jobs=1 requests=477 uptime=1327 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
09:56:00-344933 DEBUG    Server: alive=True jobs=1 requests=500 uptime=1447 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
09:58:00-380144 DEBUG    Server: alive=True jobs=1 requests=524 uptime=1567 memory=2.16/31.9 backend=Backend.DIFFUSERS
                         state=idle
```

### Backend

Diffusers

### UI

Standard

### Branch

Dev

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
should be fixed now in dev branch.
