### ISSUE TITLE
X/Y/Z Plotting for testing various loras ISSUE

### ISSUE THREAD

**Issue by ambiition** [vladmandic/automatic#3389]
![xyz_grid-0004-1074063030](https://github.com/user-attachments/assets/229dc22b-8497-4d47-8ece-fa11679edfd4)

I keep running into an error where my x/y/z plot will show blank. Here is my prompt:  <lora:add_detail:1> , <lora:Katherine_W-000004:0.6>, <lora:Katherine_W-000005:0.6>, <lora:Katherine_W-000006:0.6>, <lora:Katherine_W-000007:0.6>,  <lora:Katherine_W:0.6>,  [[soft blue eyes]], (blonde hair), (dress) highest quality, (perfect body), photo taken with phone, (natural skin texture), [full-makeup], instagram picture, smile     [[soft blue eyes]], (blonde hair), (dress) highest quality, (perfect body), photo taken with phone, (natural skin texture), [full-makeup], instagram picture, smile     

Negative Prompt: blurry, out of focus, low resolution, grainy, distorted, warped, stretched, deformed, extra limbs, missing limbs, mutated, disfigured, malformed, text, watermark, logo, signature, frame, border, cartoon, anime, sketch, drawing, painting, 3D render, glasses, hat, mask, jewelry, tattoos, nsfw

Here's a screenshot of my x/y/z : 

<img width="1199" alt="Screenshot 2024-08-31 at 1 20 07 PM" src="https://github.com/user-attachments/assets/4a4e1811-aed8-44db-9936-496fe172279c">

**Comment by vladmandic** [comment]
sorry, but issue template exists for a reason - please refile this with full info. i have to close this issue.
also, if your desire is just to try different loras, why use prompt s/r for that, you can simply use lora itself and select loras you want.
