### ISSUE TITLE
[Issue]: Reload scripts/Restart UI does not refresh code (after a while?).

### ISSUE THREAD

**Issue by some9000** [vladmandic/automatic#339]
### Issue Description

This one may be a little hard to catch, but... When working on an extension and using Reload scripts and then Restart UI after the first couple of restarts it just ignores any code changes. Like I would change a scrollbar max value and it wouldn't change. Even after several Reload scripts/Restart UI attempts.

Version: 2ddbb667 Fri Apr 21 00:07:38 2023 -0400

### Version Platform Description

Windows, Vivaldi

**Comment by vladmandic** [comment]
restart ui is flaky at best as there is no clean way at the moment to reload entire ui without python caching states - and i wrote about this in discussion thread.
i need to completely redo it, its in my backlog and i'm tracking it separately.
in the meantime, i'm closing this issue.
