### ISSUE TITLE
[Feature]: what is Default sampler for Flux?

### ISSUE THREAD

**Issue by ptits** [vladmandic/automatic#3396]
### Feature description

FLUX: no difference between Euler Flowmatch and Heun Flowmatch samplers. But THERE is difference between  Default and Euler Flowmatch

### Version Platform Description

Ubuntu, H100

**Comment by vladmandic** [comment]
default and euler flowmatch are the same, just one param is different - default has dynamic shift calculation enabled.
i'll add that param to settings -> samplers so user can choose if they want dynamic shift on or off.

heun flowmatch is currently not compatible, its code needs to be slightly updated. setting any non-compatible sampler results in ignoring that sampler.

btw, this is better suited for discussions than issue.
