### ISSUE TITLE
[Issue]: Flux Model Not Loaded. 

### ISSUE THREAD

**Issue by EKKIVOK01** [vladmandic/automatic#3399]
### Issue Description

hello, i wonder why Flux Models Cannot be loaded i have same problem with SDXL models it says -> 
![image](https://github.com/user-attachments/assets/da56e258-7ff2-4e78-9e03-5c3a010b9494)

### Version Platform Description

Windows 11

Logger: file="C:\automatic\sdnext.log" level=INFO size=61228 mode=append
16:15:54-693700 INFO     Python version=3.10.9 platform=Windows bin="C:\automatic\venv\Scripts\python.exe"
                         venv="C:\automatic\venv"
16:15:54-836785 INFO     Version: app=sd.next updated=2024-08-31 hash=bab17a0b branch=master
                         url=https://github.com/vladmandic/automatic.git/tree/master ui=main
16:15:55-353583 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 158 Stepping 13, GenuineIntel system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.9
16:15:55-357583 INFO     HF cache folder: C:\Users\kimh1\.cache\huggingface\hub
16:15:55-367583 INFO     nVidia CUDA toolkit detected: nvidia-smi present
16:15:55-485588 INFO     Verifying requirements
16:15:55-491583 INFO     Verifying packages
16:15:55-529583 INFO     Extensions: disabled=[]
16:15:55-532611 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
                         extensions-builtin
16:15:55-536615 INFO     Extensions: enabled=[] extensions
16:15:55-538611 INFO     Startup: quick launch
16:15:55-540611 INFO     Extensions: disabled=[]
16:15:55-541583 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
                         extensions-builtin
16:15:55-546581 INFO     Extensions: enabled=[] extensions
16:15:55-551581 INFO     Command line args: []
16:16:00-470623 INFO     Load packages: {'torch': '2.4.0+cu124', 'diffusers': '0.30.2', 'gradio': '3.43.2'}

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
enable debug logging (`--debug` command line flag) and upload actual log - providing a screenshot that captures only several lines is not sufficient.

**Comment by EKKIVOK01** [comment]
![1](https://github.com/user-attachments/assets/e676419a-09e5-4b35-9c2f-286d5c95ece3)
![2](https://github.com/user-attachments/assets/cab8a493-baad-46e4-9323-676ab09e9591)
[sdnext.log](https://github.com/user-attachments/files/16839559/sdnext.log)

**Comment by vladmandic** [comment]
you're attempting to load all-in-one single-file safetensors, 22gb in size - that is explicitly stated as not supported in wiki.
support for that is coming soon. but at the moment, follow wiki.

**Comment by EKKIVOK01** [comment]
@vladmandic i tried every singler others flux models and same things. and not only NF4 models.

**Comment by vladmandic** [comment]
I understand, but try to understand me as well - different ppl here report different issues in the same thread and it's impossible to follow.

Btw, no need for @ mentions, only causes annoying popup notification.
