### ISSUE TITLE
[Feature]: Add LoKr support to FLUX

### ISSUE THREAD

**Issue by blu3nh** [vladmandic/automatic#3405]
### Issue Description

LoKr on flux isn't working.

Example LoKr: https://civitai.com/models/714292

Basically LoKr allows for full finetune like experiences, without the full vram costs of full finetuning.
its become the default type trained in simpletuner, and even onetrainer is specifically adding it, due to the improvements it brings.

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fair request, but let's be realistic - change this to feature request!

**Comment by vladmandic** [comment]
taking a look, this is lokr, but it also has lyco prefix.
```log
07:12:03-325065 WARNING  LoRA name="juno_for_flux_by_caith" type=set() unmatched=1026 matched=0
07:12:03-326147 DEBUG    LoRA name="juno_for_flux_by_caith" unmatched={'lycoris_single_transformer_blocks_0_attn_to_k.alpha': ['lycoris_single_transformer_blocks_0_attn_to_k'],
```
likely need to add handler in `lora_convert.py`

**Comment by AI-Casanova** [comment]
I'll look at it this evening, should be a simple string replace. Thanks for linking an example @blu3nh

**Comment by AI-Casanova** [comment]
All keys now match, but strength seems minimal. Please test.

**Comment by vladmandic** [comment]
thanks @AI-Casanova 
re: strength - that is quite common for flux.
