### ISSUE TITLE
[Feature]: Update T-Gate

### ISSUE THREAD

**Issue by DeeH0pe** [vladmandic/automatic#3407]
### Feature description

Hello, is it possible to update T-Gate to the newest version or to implent T-Gate 2?
I saw that T-Gate now supports SDXL w Deepcache. Thank you for your effort with all that great extensions!
https://github.com/HaozheLiu-ST/T-GATE/commits/main/

**Comment by vladmandic** [comment]
i've verified that sdnext is compatible with latest tgate, simply uninstall currently installed version and sdnext will auto-install latest when tgate operations are triggered.
