### ISSUE TITLE
[Issue]: Image transfer/display failure

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#341]
### Issue Description

When I send a generated image to inpaint, I get sometimes a wrong displayed image like this:

![Zwischenablagebild](https://user-images.githubusercontent.com/122026301/233621656-daba03f8-c5d3-43f1-836d-45b02b22db44.png)

I can't say why, but it seems mostly after a new start of WebUI and when I delete and re-send the image, most of the times it stays correct again.

### Version Platform Description

Win10, Firefox 106
https://github.com/vladmandic/automatic/commit/2ddbb6670484ed31120dc7bcdef4c292400e7a27

**Comment by Woisek** [comment]
Sure, will do and report when this issue appears again.

**Comment by vladmandic** [comment]
closing for now, if issue persists, will reopen.

**Comment by Woisek** [comment]
It happend just now again. Sorry to say. 😐

**Comment by drax-xard** [comment]
This keeps happening to me, sometimes it works and sometimes the images will be sent exactly like the example posted by OP.
