### ISSUE TITLE
[Feature]: Select VAE per-model

### ISSUE THREAD

**Issue by AznamirWoW** [vladmandic/automatic#3422]
### Feature description

Right now VAE selection under 'Execution & Models' settings applies to all models, so while a user may pick 'fixFP16ErrorsSDXLLowerMemoryUse_v10.safetensors' for SDXL models, SD1.5 or other do not work with that and require a manual change and model reload, making operation cumbersome.

**Comment by brknsoul** [comment]
You can add sd_vae to quicksettings (settings > interface options). Quick settings appear in the top most side-bar button. You don't have to reload a model in order for a VAE to take effect.
