### ISSUE TITLE
[Feature]: Add a CLI flag to define a specific config file to use

### ISSUE THREAD

**Issue by Shadowghost** [vladmandic/automatic#343]
### Feature description

Add a CLI flag to define a specific `config.json` file to use.
This would allow quick switching between multiple configurations without manually changing all the UI settings or replacing `config.json`. Before this could be achieved by just using different CLI parameters but since a lot of settings got moved to the UI this is not possible anymore to the extent it was before.

**Comment by vladmandic** [comment]
there is a hidden cmdflag for that, i just don't want to expose massive list of cmdflags to normal users
`---ui_settings_file`

**Comment by Shadowghost** [comment]
Thanks for the info, that's exactly what I was looking for. Seems like I did forget to manually check the orginal wiki, sorry for that.

With so many changes inside this repo and the documentation the GitHub search is rather useless in such cases due to it not allowing code search on forked repos. This might in general be a problem when filing issues related to documentation.

As to not exposing cmdflags: I totally agree, it's way better to have everything in a config file anyway than requiring CLI flags, that's why I asked for a flag to define a config file and not for separate flags :)
