### ISSUE TITLE
[Feature]: Add Auto-trigger-insertion option for Loras

### ISSUE THREAD

**Issue by EnragedAntelope** [vladmandic/automatic#3432]
### Feature description

This should be an option for both loras used via prompt OR coupled with loras selected in XYZ grid.
Basically when choosing a lora, SD.Next would ideally have an option to auto-insert the trigger word at a specified place in the prompt from the Civit metadata.

### Version Platform Description

This would apply to any platform.
Personally I use latest dev, Windows 11, and firefox (but also test things in Edge and Vivaldi if Firefox is acting up :))

**Comment by EnragedAntelope** [comment]
Addendum: 
I should note in the absence of tags, I auto-insert the lora name (minus .safetensors) in comfy, since that is usually helpful with characters if there's no trigger word. So this might be an additional option to consider.

**Comment by vladmandic** [comment]
![image](https://github.com/user-attachments/assets/414269de-659a-4d97-a64e-9ad82e3adec3)
