### ISSUE TITLE
[Issue]: first time run on Debian 12 will  crash with complaining  "cannot import name 'splat' from 'distutils._functools'"

### ISSUE THREAD

**Issue by LeptonWu** [vladmandic/automatic#3435]
### Issue Description

Reproduced it on 2 different debian 12 machine. I debugged it a while. It seems the python-setuptools package in debian 12 is on verison  66.1.1-1   and there is no "splat" function inside 'distutils._functools'.
While webui.sh will install a new version of setuptools with version 69.5.1 (see requirements.txt) first, it seems for some reason when it start launch, it somehow still uses the old version of setuptools and then it will fail.

The second time run doesn't have this issue. Also I can work around it by doing this before running webui.sh:

python3 -m venv venv
. venv/bin/activate
pip install --upgrade setuptools==69.5.1

### Version Platform Description

Debian 12 Bookworm

### Relevant log output

```shell
Activate python venv: /home/lepton/automatic/venv
Launch: venv/bin/python3
22:06:11-973233 INFO     Starting SD.Next                                       
22:06:11-976014 INFO     Logger: file="/home/lepton/automatic/sdnext.log"       
                         level=INFO size=14340 mode=append                      
22:06:11-977192 INFO     Python version=3.11.2 platform=Linux                   
                         bin="/home/lepton/automatic/venv/bin/python3"          
                         venv="/home/lepton/automatic/venv"                     
22:06:11-988445 INFO     Version: app=sd.next updated=2024-09-13 hash=e7ec07f9  
                         branch=master                                          
                         url=https://github.com/vladmandic/automatic/tree/master
                         ui=main                                                
22:06:12-299993 INFO     Platform: arch=x86_64 cpu= system=Linux                
                         release=6.1.0-25-amd64 python=3.11.2      
...
RuntimeError: Failed to import diffusers.pipelines.pipeline_utils because of the following error (look up to see its traceback):
Failed to import diffusers.models.autoencoders.autoencoder_kl because of the following error (look up to see its traceback):
Failed to import diffusers.loaders.unet because of the following error (look up to see its traceback):
cannot import name 'splat' from 'distutils._functools' (/home/lepton/automatic/venv/lib/python3.11/site-packages/setuptools/_distutils/_functools.py)
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by LeptonWu** [comment]
My fix is here:

https://github.com/vladmandic/automatic/pull/3436

**Comment by vladmandic** [comment]
valid issue and thanks for the pr, i just don't like to handle that in webui.sh as there are valid scenarios where 
- start script is not used (e.g. no need for venv if already in a container)
- needs to be cross-platform, so would need to update and test all launch scripts.

instead i've pushed an update that handles it internally in `installer.py`, see `ensure_base_requirements` function.

**Comment by LeptonWu** [comment]
Sorry, I checked the git log and it seems the latest commit is still from last week,  what do you mean by "I've pushed an update"?
