### ISSUE TITLE
[Extension]: adetailer generate white image(mask) when use directml + fp16

### ISSUE THREAD

**Issue by ChiaYen-Kan** [vladmandic/automatic#3437]
### Issue Description

after update to e7ec07f9783701629ca1411ad82aec87232501b9, i try to use directml + fp16 with adetailer , but adetailer is generate white image(mask)
so i restore setting to fp32, everything is fine
i don't this is adetailer or SD.Next problem

fp16

before adetailer 
![fp16-20240917201107-ad-before](https://github.com/user-attachments/assets/ad3292d0-c25d-4911-b5d2-219b6a12eff3)

after adetailer
![fp16-20240917201107](https://github.com/user-attachments/assets/62a74d94-ed6a-4ac1-941e-3ecaf6acd4f7)

fp16 log
[fp16.txt](https://github.com/user-attachments/files/17028097/fp16.txt)

fp32

before adetailer 
![fp32-20240917195752](https://github.com/user-attachments/assets/0b45097f-86ea-4c34-9504-5546088ecf3f)

after adetailer
![fp32-20240917195751-ad-before](https://github.com/user-attachments/assets/679eeb30-2dd9-4aa8-9cba-fd31f0edafde)

fp32 log
[fp32.txt](https://github.com/user-attachments/files/17028144/fp32.txt)

### Version Platform Description

Platform:
cpu: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD (amd ryzen 5 5600g without other gpu)
system: Windows
release: Windows-10-10.0.19045-SP0
python: 3.11.9

Backend:
directml

Version:
e7ec07f9783701629ca1411ad82aec87232501b9

Browser:
Firefox 130

### URL link of the extension

https://github.com/Bing-su/adetailer

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by Bing-su** [comment]
https://github.com/Bing-su/adetailer/issues/250
https://github.com/Bing-su/adetailer/issues/370
https://github.com/Bing-su/adetailer/issues/481

This issue has been reported before.

It seems to only happen with the directml + fp16 combination.
