### ISSUE TITLE
[Feature]: For TAESD add button to redecode latent with full VAE

### ISSUE THREAD

**Issue by shivshankar11** [vladmandic/automatic#3439]
### Feature description

Option to decode all generated image with taesd and on-demand decode a selected result with full quality vae with button- Redecode latent with Full Vae. 
latents are small,Hold it in memory until next gen starts.
this approach far better than use previous seed and regenerate with full quality on.
flux vae is noticeably slow when using 4 step model but taesd is fast and maybe less memory. this can be useful.

### Version Platform Description

Windows 11, RTX4090, 7800x3d

**Comment by vladmandic** [comment]
yup, valid request, will see what can be done.

**Comment by vladmandic** [comment]
just implemented in dev branch, see changelog for details.

**Comment by shivshankar11** [comment]
new users will not know what **reprocess last image** mean. maybe **Decode selected image with Full VAE** is better description.
