### ISSUE TITLE
[Issue]: Animatediff issues

### ISSUE THREAD

**Issue by AznamirWoW** [vladmandic/automatic#3440]
### Issue Description

1) Deleted config.json, started SD.Next, selected SD1.5 model, entered prompt "puppy playing with a tennis ball", 512x512, sampler DPM SDE, checked highdiffusion, selected AnimeteDiff Motion 1.5 v2 (the one that used to work several months ago), 16 frames, [x] Override Sampler, Lora = None, Video File = Gif, left everything on default, clicked generate

error - Division by Zero (see attached error 1)

2) unchecked HiDiffusion, clicked generate

error - Input for postprocessing is in incorrect format (see attached error 2)

3) applied config changes
  VAE = None, Diffusers offload mode = Model, Diffusers Vae Tiling = true
   clicked generate

error - 'prompt attention' (see attached error 3)
[error1.txt](https://github.com/user-attachments/files/17032881/error1.txt)
[error2.txt](https://github.com/user-attachments/files/17032882/error2.txt)
[error3.txt](https://github.com/user-attachments/files/17032883/error3.txt)

 

### Version Platform Description

2024-09-17 13:43:44,021 | sd | INFO | launch | Starting SD.Next
2024-09-17 13:43:44,023 | sd | INFO | installer | Logger: file="G:\SD\sdnext.log" level=INFO size=697539 mode=append
2024-09-17 13:43:44,025 | sd | INFO | installer | Python version=3.10.11 platform=Windows bin="G:\SD\venv\Scripts\python.exe" venv="G:\SD\venv"
2024-09-17 13:43:44,119 | sd | INFO | installer | Version: app=sd.next updated=2024-09-17 hash=fedb35e9 branch=dev url=https://github.com/vladmandic/automatic/tree/dev ui=dev
2024-09-17 13:43:44,307 | sd | INFO | installer | Latest published version: e7ec07f9783701629ca1411ad82aec87232501b9 2024-09-13T16:51:56Z

### Backend

Diffusers

### UI

Standard

### Branch

Dev

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
for errors 1 and 2 you've correctly diagnosed and corrected.
for error 3 i just pushed a fix on dev branch.

**Comment by AznamirWoW** [comment]
@vladmandic I actually have no solution for #1 and #2

for #1 If HiDiffusion is not supported, it should not trigger an exception

for #2 I dont know which exact setting is triggering 'prompt attention' exception

**Comment by vladmandic** [comment]
it would be a massive effort to cross-validate compatibility of every single setting against every single model.
