### ISSUE TITLE
[Feature]: maybe openvino_disable_model_caching should be true by default

### ISSUE THREAD

**Issue by LeptonWu** [vladmandic/automatic#3441]
### Issue Description

I am trying with cpu diffusion and it seems openvino give me best performance, basically I can generate a 512x512 image with  recommended settings from Realistic Vision V6.0 B1 for around 40 seconds on a 5700G. The only issues is when I am trying different models and configuration, the cache directory keep increasing and finally I am runnning out of disk space. (I had around 65G free space after installation and cache increased to 65G).  I did some investigation and it seems by default the disk cache is on for openvino. I am not sure if the cache  really matter a lot since I didn't notice obvious performance issue after I disable caching.

Maybe we should disable openvino model cache by default. Or at least we should say it explicitly somewhere to remind users it could increase rapidly if users are keep trying different models etc.

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Disty0** [comment]
Model caching reduces the startup time from minutes to a few seconds if a cache for the model already exists.

There is a wiki page for Model Caching: https://github.com/vladmandic/automatic/wiki/OpenVINO#model-caching

**Comment by vladmandic** [comment]
i'm open to suggestions, but disabling cache by default is not a likely one.
anyhow, converting this to feature request.

**Comment by LeptonWu** [comment]
I will come with more data since I didn't remember I noticed unusual latency with openvino cached disabled.
But it seems whenever you change things like width and height, openvino have to regenerate the model?
That could be the issue here.  

Are we doing any kind of GC for the cache?

Or maybe just check the free disk size and don't write cache if the free disk is less than some reasonable value?

Or just give some warning on the UI to let they know?

I noticed the disk was full just by an error message that the generated image can't be save because of disk full which
is totally out of my expectation....

**Comment by LeptonWu** [comment]
Did a quick test with one computer, hardware: CPU: AMD 3700X  GPU: Intel ARC A580

Fresh start with cache dir removed:
Start up time: 7.27s
First image process time: 18 Seconds 

Secondtime start with cached dir:
Start up time: 7.27s
First image process time: 12 seconds

So for me it's only 6 seconds difference on this hardware. 

I am using realisticVisionV60B1_v51HyperVAE.safetensors,

**Comment by Disty0** [comment]
Set to true on dev branch: https://github.com/vladmandic/automatic/commit/6d3d23bddd6efd53196a400795ccfcdc31e6723b
