### ISSUE TITLE
[Feature]: Improve bf16 test capabilities to better detect invalid gpu implementations

### ISSUE THREAD

**Issue by LeptonWu** [vladmandic/automatic#3442]
### Issue Description

On debian 12, I installed intel  oneapi toolkit and then launch webui.sh with --use-ipex to hope I can use the iGPU of it.  It looks it's working and when it generated images, intel_gpu_top showed there is load on GPU. But the generated image is a mess, I attached 2 images to show what I mean (bad one is generated by default setup, good one is generated after I change the device type to FP16 and restart the server). I noticed that in the log, it's telling pytorch to use bf16  but as far as I know bf16 is something new and my old iGPU maybe doesn't work with it. So changed the system settings and set device type to FP16, then it works.

I did see there is one test_bf16 function in modules/devices.py before we enabling it by default. But it seems it's just calling some api and didn't check any output.  This could actually be a bug of some version of intel oneapi, but I am wondering, should we do some basic correctness check in test_bf16?

It's kind of quite confusing for me when there isn't any warning while I got assorted image.
![00044-realisticVisionV60B1_v51HyperVAE-A black cat-failed](https://github.com/user-attachments/assets/8715c24c-1645-4943-8d5d-41d1bb096cf9)
![00041-realisticVisionV60B1_v51HyperVAE-A black cat](https://github.com/user-attachments/assets/8da77d7e-8f98-42c2-a998-b07b497eb961)

BTW, it takes around 2.5 mins to generate a 512x512 image with the iGPU of this G4620

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
> This could actually be a bug of some version of intel oneapi, but I am wondering, should we do some basic correctness check in test_bf16?

function test_bf16 as-is serves to perform basic correctness as it fails if gpu is not bf16 compatible.
anything more - well, contributions are welcome.
i'm changing this to a feature request.

**Comment by Disty0** [comment]
iGPUs are not officially supported. Every device officially supported by IPEX also supports BF16, so there is no check for IPEX.

**Comment by LeptonWu** [comment]
Thanks for the explanation, I filed a bug at intel side to ask them at leas throw some exception...

https://github.com/intel/intel-extension-for-pytorch/issues/711

BTW, I did some simple test and it seems it at least give reasonable result for my tested simple function. Not really
sure what intel was doing there.

```python
import torch
import intel_extension_for_pytorch
import torch.nn as nn

dev="xpu"
dt=torch.bfloat16
t=torch.full((1,3), 5000).to(dev, dtype=dt)
f=nn.Linear(3,1).to(dev, dtype=dt)
nn.init.constant_(f.weight, 2)
nn.init.constant_(f.bias, 10000)
o=f(t)
print(o[0][0])
```

**Comment by Disty0** [comment]
> Also, it seems the SdNext default setting doesn't work, I have to switch to FP32 to make it use my iGPU.
Default dtype for PyTorch (the setting in SDNext) when using OpenVINO is already FP32. OpenVINO does convert it to FP16 on its own.

**Comment by LeptonWu** [comment]
> > Also, it seems the SdNext default setting doesn't work, I have to switch to FP32 to make it use my iGPU.
> 
> Default dtype for PyTorch (the setting in SDNext) when using OpenVINO is already FP32. OpenVINO can convert the new OpenVINO model to FP16 on its own based on your device.

Sorry, I changed my comments. It turned out that when switching to openvino, I just clean the venv but I didn't deleted the config.json, so SdNext still read the configuration from the old config.json which is for ipex.  I confirmed if I delete the config.json, SdNext will set dtype to FP32.

**Comment by Disty0** [comment]
Also noticed that your iGPU lists itself as fp64 capable according to the env info.
Can you try exporting `IPEX_FORCE_ATTENTION_SLICE=1`

This might be a 4GB allocation issue if the iGPU is a 32 bit iGPU
Intel ARC and other 32 bit GPUs computes nonsense when you allocate more than 4GB on a single block.

**Comment by LeptonWu** [comment]
> Also noticed that your iGPU lists itself as fp64 capable according to the env info. Can you try exporting `IPEX_FORCE_ATTENTION_SLICE=1`
> 
> This might be a 4GB allocation issue if the iGPU is a 32 bit iGPU Intel ARC and other 32 bit GPUs computes nonsense when you allocate more than 4GB on a single block.

Thanks, tried this and didn't find difference, if this was a 4G issue, I guess both fp16 and bf16 will get impacted?

**Comment by Disty0** [comment]
> if this was a 4G issue, I guess both fp16 and bf16 will get impacted?
Yep.

**Comment by LeptonWu** [comment]
BTW, one thing I noticed is:  after I change switch datatype from bf16 to fp16 from the UI, even after I clicked "restart server", the image generated is still buggy. I have to shutdown server and start it again to get things working.
Could this give some hints to where could be wrong?

**Comment by vladmandic** [comment]
this is mostly complete now.
