### ISSUE TITLE
[Feature]: reprocess last image with adetailer-face/hand/xxx.   skip regenerating image if generation parameters didnt change

### ISSUE THREAD

**Issue by shivshankar11** [vladmandic/automatic#3451]
### Feature description

add a button to preview section to reprocess last image with adetailer-face/hand/xxx so we dont have to regenerate image again.
we should also skip regenerating image if generation parameters didnt change (like comfyui) , so enabling post processing scripts like faceswapper/adetailer can skip regeneration.

### Version Platform Description

Windows 12

**Comment by vladmandic** [comment]
i like the idea!

**Comment by vladmandic** [comment]
added to dev branch:
- **reprocess**
  - new top-level button: reprocess your last generated image(s)  
  - generate using full-quality:off and then reprocess using *full quality decode*  
  - generate without hires/refine and then *reprocess with hires/refine*  
    *note*: you can change hires/refine settings and run-reprocess again!  
  - reprocess using *face-restore*  

![image](https://github.com/user-attachments/assets/bfa5131e-549e-4284-9c15-d8b9d83bddf2)
