### ISSUE TITLE
[Issue]: Input type error "dtype mismatch" on Upscaling with Force HiRes + non-Latent method

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3459]
### Issue Description

RuntimeError: Input type (c10::Half) and bias type (float) should be the same error.

Attached log contains startup + render (with attached settings) until error happens. Then I switched to a Latent* method and rendered again, that's the log output right after the error.

### Version Platform Description

WSL-2, WIN11, 157f581

[config.json](https://github.com/user-attachments/files/17163777/config.json)
[ui-config.json](https://github.com/user-attachments/files/17163781/ui-config.json)
[sdnext.log](https://github.com/user-attachments/files/17163786/sdnext.log)

### Relevant log output

```shell
See attached files.
```

### Backend

Diffusers

### UI

ModernUI

### Branch

Dev - NOTE: works without error on Master branch e7ec07f

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Tillerz** [comment]
Not about the settings.

I used DEFAULT as renderer here, usually I use DPM++ 2M. Error occurs with both.
Also DEFAULT supports no timesteps, so timesteps is the problem neither.
And I rendered with scale x1, usually I use x2. Error happens with both.

**Comment by vladmandic** [comment]
ah, i think i found it, its specific to really combo of couple of settings. 
try updating - hopefully should be ok.

and afterwards (not before, need to confirm the fix first):
why are you running in fp16 with vae-upcast enabled? you have rtx4090, you should be all-in with bf16 and no upcasting - so much more reliable and faster.
