### ISSUE TITLE
[Issue]: Compatibility with Apple M1

### ISSUE THREAD

**Issue by potatochips489** [vladmandic/automatic#347]
### Issue Description

Doesn't work at all on my M1 Macbook, many models crash the entire process, some start "generating" but at the end fail with the following error:
```
RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: float key.dtype: float and value.dtype: c10::Half instead.
```

I tried changing some settings like `--no-half` and "Upcast cross attention layer to float32", didn't work. A1111 is working on Mac M1, not sure what you changed here.

### Version Platform Description

Commit Version: 57204b3d702b7586c789dbad1e1e3bd85746d81e

**Comment by vladmandic** [comment]
yes, I'm aware. new torch is very different and i have open ask for M1 community to provide proper package instructions - what exactly should be installed automatically. i don't have M1 system available, so this is up to community to provide me some guidance. but so far i have not received any inputs.

it was the same for AMD and that community is very active so there has been a lot of progress.

**Comment by jasoncwade** [comment]
I got the same error on my MBA M2 and fixed it, but not completely sure how. I think it had something to do with the steps below.

I copied the "webui-macos-env.sh" file I had in my Automatic1111 install over. I commented out every line in it except two:
export TORCH_COMMAND="pip install torch==1.12.1 torchvision==0.13.1"
and
export PYTORCH_ENABLE_MPS_FALLBACK=1

I deleted my venv and then ran webui.sh. It installed those two versions of torch and torchvision. It then threw an error and crashed so I commented out that torch command.

I did not delete the 1.12.1 install and then re-ran web.sh. It installed torch 2.0 and since then has been working.

I left the export PYTORCH_ENABLE_MPS_FALLBACK=1 line uncommented as it solved a different error.

**Comment by naijim** [comment]
Maybe this discussion is helpful:

https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/7453

**Comment by ptppan** [comment]
> I got the same error on my MBA M2 and fixed it, but not completely sure how. I think it had something to do with the steps below.
> 
> I copied the "webui-macos-env.sh" file I had in my Automatic1111 install over. I commented out every line in it except two: export TORCH_COMMAND="pip install torch==1.12.1 torchvision==0.13.1" and export PYTORCH_ENABLE_MPS_FALLBACK=1
> 
> I deleted my venv and then ran webui.sh. It installed those two versions of torch and torchvision. It then threw an error and crashed so I commented out that torch command.
> 
> I did not delete the 1.12.1 install and then re-ran web.sh. It installed torch 2.0 and since then has been working.
> 
> I left the export PYTORCH_ENABLE_MPS_FALLBACK=1 line uncommented as it solved a different error.
> 
> Edit: Forgot to mention I'm running build [7c684a8](https://github.com/vladmandic/automatic/commit/7c684a8bdec42434f3a231a0f9d1433b607731b7).

Godsend. I missed where you wrote that you commented out the torch command, and when I received the error after the torch and torchvision installations, I deleted the webui-macos-env.sh file altogether and then reran it, so I didn't comment out the torch command, I removed the file completely, and now it works for me. I haven't worked with Python before, so I, completely, have no idea why this works, but I just wanted to say that I did this and it worked for me, don't know why.

Thank you again for posting your steps.

**Comment by WojtekKowaluk** [comment]
Instead of `no-half` I recommend "Enable upcast sampling" on Stable Diffusion tab.

**Comment by nybe** [comment]
ok... tried some of the above stuff and now am getting:

ModuleNotFoundError: No module named 'clip'

**Comment by lauretta91** [comment]
I get the same - illegal hardware instruction when running ./webui.sh.

Just to confirm with other users, what file are you running?

**Comment by krummrey** [comment]
I've tried to install it just now (Apr. 24th 10 AM GMT) from a fresh git clone. 
Apple M1 Pro / 32 GB
OSX Version 13.2.1 (22D68)

Various errors during install, mostly from not having xcode installed. Fill log here on [Pastebin](https://pastebin.com/sAY8W64x) 
The automatic download of the default model didn't work. Installed a model manually

After installing xcode all failed pip installs worked 
```
xcode-select --install
pip install --upgrade pip
pip install --upgrade basicsr
pip install --upgrade gfpgan
pip install --upgrade lmdb
Pip install --upgrade realesrgan
```
Launched with `./webui.sh`. Starts but fails to generate an image.
```Initializing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 
0:00:00loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<2x1280xf32>' and 'tensor<1280xf16>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
zsh: abort      ./webui.sh
```

**Comment by jasoncwade** [comment]
Following up on my earlier post, after the changes vladmandic made I removed the webui-macos-env.sh file (since what I was using it for is now built-in) and everything has been working for me.

I have "Use full precision for VAE" checked under CUDA Settings (but not "Use full precision for model") and "Enable upcast sampling" under Stable Diffusion settings. I think those are the only settings I've changed from the default that would affect image generation.

I'm currently running build 98adfb31.

**Comment by nniikkllaass** [comment]
In my case the installation works fine on the M1. It does not download the default sd v.1.5 but I imported it to the SD folder so it works fine. As soon as I press the generate button I get an error message with the information that python crashed...I tried different models but nothing helped.

**Comment by Scholar01** [comment]
export install_dir="$HOME"
export COMMANDLINE_ARGS="--skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate"
export TORCH_COMMAND="pip install torch==1.12.1 torchvision==0.13.1"
export K_DIFFUSION_REPO="https://github.com/brkirch/k-diffusion.git"
export K_DIFFUSION_COMMIT_HASH="51c9778f269cedb55a4d88c79c0246d35bdadb71"
export PYTORCH_ENABLE_MPS_FALLBACK=1

I am running well.

**Comment by Scholar01** [comment]
Traceback (most recent call last):
  File "launch.py", line 94, in <module>
    setup.run_setup()
  File "/Users/db/Documents/Python Projects/automatic/setup.py", line 528, in run_setup
    setup_logging(args.upgrade)
  File "/Users/db/Documents/Python Projects/automatic/setup.py", line 37, in setup_logging
    logging.basicConfig(level=logging.DEBUG, format='%(asctime)s | %(levelname)s | %(pathname)s | %(message)s', filename='setup.log', filemode='a', encoding='utf-8', force=True)
  File "/Users/db/opt/anaconda3/envs/control/lib/python3.8/logging/__init__.py", line 1997, in basicConfig
    raise ValueError('Unrecognised argument(s): %s' % keys)
ValueError: Unrecognised argument(s): encoding

**Comment by nybe** [comment]
Finally got it installed and running but cannot create images.

errors:

Initializing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━   0% -:--:-- 0:00:00loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<2x1280xf32>' and 'tensor<1280xf16>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
zsh: abort      ./webui.sh

**Comment by hs1n** [comment]
Continue to #337

I'am able to generate image with DPM++ 2M Karras sampler after checking
UI > Settings > CUDA Settings
...
- [x] Enable upcast sampling. Usually produces similar results to --no-half with better performance while using less memory
...
> Apply Settings

**Comment by lauretta91** [comment]
> Finally got it installed and running but cannot create images.
> 
> errors:
> 
> Initializing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0% -:--:-- 0:00:00loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<2x1280xf32>' and 'tensor<1280xf16>' are not broadcast compatible LLVM ERROR: Failed to infer result type(s). zsh: abort ./webui.sh



I  finally got it. I had to swap the venv folder with the one from Automatic1111. It seems that the previous one was downgrading Python to 3.9.7 (from Python 3.10), therefore, it wasn't running. 

Once initialized, I changed the Sampler to Euler a. The default one is Unipc, which doesn't work and gives me the below error.
error: input types 'tensor<2x1280xf32>' and 'tensor<1280xf16>' are not broadcast compatible

**Comment by hs1n** [comment]
512x512 image generation speed on MBP M1 16G:
Sampler: DPM++ 2M Karras, steps: 20

this project(--medvram):
00:32<00:00,  1.62s/it
webui(--skip-torch-cuda-test --upcast-sampling --disable-nan-check --medvram --opt-sub-quad-attention --use-cpu interrogate):
00:32<00:00,  1.61s/it 

Almost the same.

**Comment by nniikkllaass** [comment]
if I change the venv folder with the a1111 one I get this: "No module 'xformers'. Proceeding without it." which results in this error: "ModuleNotFoundError: No module named 'clip'"

**Comment by lauretta91** [comment]
> if I change the venv folder with the a1111 one I get this: "No module 'xformers'. Proceeding without it." which results in this error: "ModuleNotFoundError: No module named 'clip'"

It's normal that you get no module xformers as this is available only for NVIDIA GPUs. And we are using a macOS, which doesn't support an NVIDIA GPU.

For CLIP, you install it manually from openai/clip (https://github.com/openai/CLIP). I am scared you will be asked to install other requirements after CLIP. If this is the case, you can run the requirements.txt file with the below command:
python install -r requirements.txt

Note that I had this already installed from the automatic1111, so you might want to use the same.

**Comment by nniikkllaass** [comment]
> > if I change the venv folder with the a1111 one I get this: "No module 'xformers'. Proceeding without it." which results in this error: "ModuleNotFoundError: No module named 'clip'"
> 
> It's normal that you get no module xformers as this is available only for NVIDIA GPUs. And we are using a macOS, which doesn't support an NVIDIA GPU.
> 
> For CLIP, you install it manually from openai/clip (https://github.com/openai/CLIP). I am scared you will be asked to install other requirements after CLIP. If this is the case, you can run the requirements.txt file with the below command: python install -r requirements.txt
> 
> Note that I had this already installed from the automatic1111, so you might want to use the same.

Does it work for you to generate images and so on, if yes...what did you change that it works for you? In my case it looks good while running the sirup but as soon as I want to generate python quits...

**Comment by lauretta91** [comment]
> > > if I change the venv folder with the a1111 one I get this: "No module 'xformers'. Proceeding without it." which results in this error: "ModuleNotFoundError: No module named 'clip'"
> > 
> > 
> > It's normal that you get no module xformers as this is available only for NVIDIA GPUs. And we are using a macOS, which doesn't support an NVIDIA GPU.
> > For CLIP, you install it manually from openai/clip (https://github.com/openai/CLIP). I am scared you will be asked to install other requirements after CLIP. If this is the case, you can run the requirements.txt file with the below command: python install -r requirements.txt
> > Note that I had this already installed from the automatic1111, so you might want to use the same.
> 
> Does it work for you to generate images and so on, if yes...what did you change that it works for you? In my case it looks good while running the sirup but as soon as I want to generate python quits...

Yes, it works. I have followed what @hs1n suggested to do, i.e., changed the sampling method to something different from the default (UniPc), and enabled upcast sampling under Settings > CUDA Settings.

**Comment by nniikkllaass** [comment]
Python does not crash anymore but I get this error: NotImplementedError: The operator 'aten::_linalg_solve_ex.result' is not 
currently implemented for the MPS device. If you want this op to be added in 
priority during the prototype phase of this feature, please comment on 
https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set
the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a 
fallback for this op. WARNING: this will be slower than running natively on MPS.


> > > > if I change the venv folder with the a1111 one I get this: "No module 'xformers'. Proceeding without it." which results in this error: "ModuleNotFoundError: No module named 'clip'"
> > > 
> > > 
> > > It's normal that you get no module xformers as this is available only for NVIDIA GPUs. And we are using a macOS, which doesn't support an NVIDIA GPU.
> > > For CLIP, you install it manually from openai/clip (https://github.com/openai/CLIP). I am scared you will be asked to install other requirements after CLIP. If this is the case, you can run the requirements.txt file with the below command: python install -r requirements.txt
> > > Note that I had this already installed from the automatic1111, so you might want to use the same.
> > 
> > 
> > Does it work for you to generate images and so on, if yes...what did you change that it works for you? In my case it looks good while running the sirup but as soon as I want to generate python quits...
> 
> Yes, it works. I have followed what @hs1n suggested to do, i.e., changed the sampling method to something different from the default (UniPc), and enabled upcast sampling under Settings > CUDA Settings.

**Comment by lauretta91** [comment]
> error: NotImplementedError: The operator 'aten::_linalg_solve_ex.result' is not
> currently implemented for the MPS device. If you want this op to be added in
> priority during the prototype phase of this feature, please comment on
> [pytorch/pytorch#77764](https://github.com/pytorch/pytorch/issues/77764). As a temporary fix, you can set
> the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a
> fallback for this op. WARNING: this will be slower than running natively on MPS.

Yep. It seems you need to run this: 

export PYTORCH_ENABLE_MPS_FALLBACK=1

Before running the ./webui.sh

The error suggests that you are trying to use a PyTorch function that is not yet implemented for the MPS device. MPS (Memory Pooling System) is a technology that allows for efficient memory management on NVIDIA GPUs, but not all PyTorch functions are currently supported on MPS.

**Comment by nybe** [comment]
> Finally got it installed and running but cannot create images.
> 
> errors:
> 
> Initializing ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0% -:--:-- 0:00:00loc("mps_add"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<2x1280xf32>' and 'tensor<1280xf16>' are not broadcast compatible LLVM ERROR: Failed to infer result type(s). zsh: abort ./webui.sh

FYI: I seem to have fixed my install problems by installing tensorflow-metal for Apple silicon... 
https://developer.apple.com/metal/tensorflow-plugin/

**Comment by nybe** [comment]
Had more issues this morning, installing PyTorch seems to have fixed problems:

https://pytorch.org/get-started/locally/#macos-version

**Comment by hs1n** [comment]
> > if I change the venv folder with the a1111 one I get this: "No module 'xformers'. Proceeding without it." which results in this error: "ModuleNotFoundError: No module named 'clip'"
> 
> It's normal that you get no module xformers as this is available only for NVIDIA GPUs. And we are using a macOS, which doesn't support an NVIDIA GPU.
> 
> For CLIP, you install it manually from openai/clip (https://github.com/openai/CLIP). I am scared you will be asked to install other requirements after CLIP. If this is the case, you can run the requirements.txt file with the below command: python install -r requirements.txt
> 
> Note that I had this already installed from the automatic1111, so you might want to use the same.


Possible fix for experiencing `No module named 'clip'"` is launch with `./webui.sh --upgrade` then you shall see
```
10:31:14-498482 INFO     Installing packages
10:31:14-498880 INFO     Installing package: git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
```

For `./webui.sh` user, launch with venv is by default. If you think your environment is corrupted. I suggest you remove `venv` directory and start over.


## If you want to check/install requirements manually
If you use `webui.sh` for launch, make sure you are activated venv.
```
source venv/bin/activate
pip install -r requirements.txt
deactivate
```

Plus, you can use `which pip` to locate which pip you are using.
e.g.
```
$ which pip
/Users/username/Projects/automatic/venv/bin/pip
```

**Comment by moebis** [comment]
> FYI: I seem to have fixed my install problems by installing tensorflow-metal for Apple silicon... https://developer.apple.com/metal/tensorflow-plugin/

@nybe Are you able to run automatic1111 or Vlad Diffusion inside of miniconda? Because those instructions from Apple look promising. One issue I have is that pip3 is installing modules outside of the normal paths. I also think the Apple version of tensor flow with metal support might allow us to utilize our GPU's instead of just the CPUs (maybe even the NPUs too?)

**Comment by vladmandic** [comment]
nothing to do with M1, those command line flags are removed and moved to UI settings.

**Comment by nybe** [comment]
> > FYI: I seem to have fixed my install problems by installing tensorflow-metal for Apple silicon... https://developer.apple.com/metal/tensorflow-plugin/
> 
> @nybe Are you able to run automatic1111 or Vlad Diffusion inside of miniconda? Because those instructions from Apple look promising. One issue I have is that pip3 is installing modules outside of the normal paths. I also think the Apple version of tensor flow with metal support might allow us to utilize our GPU's instead of just the CPUs (maybe even the NPUs too?)

Been running A1111 right outta the box but I did install miniconda and it seems to have fixed alot of initial issues I was having running Vlad... I'm sure I've made a mess out of my Mac with all the stuff I've been trying but it's all smooth now (knock wood)

**Comment by ptppan** [comment]
I kneel. It works on Mac now, thank you so much for the devs! I am trying to img2img at 1408x1408 resolution (which works on A1111), but on Vladomatic I get this error:

```
/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:725: failed assertion `[MPSNDArray initWithDevice:descriptor:] Error: total bytes of NDArray > 2**32'
zsh: abort      ./webui.sh
@MacBook-Pro-7 automatic % /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

Does anyone else get this issue? I am using the M2 Max with 64GB ram and gens at that res work on A1111.

**Comment by vladmandic** [comment]
ok, so all community suggestions on what to do for defaults on M1 setups have been added and I haven't seen any further updates to those on this thread, so I'll close it.
if there are any remaining issues or further tuning needed, lets start with the new thread as there is a lot of history here.

note that there are still quite a few reports on binary incompatibilities on some systems - unless they involve suggestions to install different version of a binary package causing errors, i really cannot help as i cannot debug underlying binary packages.

**Comment by vladmandic** [comment]
> AFAIK, the most competent person on Apple Silicon compatibility & optimizations for Stable Diffusion/A1111 is @brkirch. 

Thanks, I've reached out - will see what happens.

**Comment by ZachNagengast** [comment]
Sharing my anecdotal evidence using an M2 mac because I tried everything in this thread and nothing worked:

I was using `python3.9` before

When I tried running it with a fresh install of `python3.10`, it worked first try. No idea why, but hopefully that's helpful to someone in my same situation.
