### ISSUE TITLE
[Issue]: 404 error

### ISSUE THREAD

**Issue by ahmaddie1378** [vladmandic/automatic#3482]
### Issue Description

hii i getting this error 
``
11:45:24-823149 INFO     AMD ROCm toolkit detected
11:45:24-832208 INFO     ROCm agents detected: []
11:45:24-833209 INFO     ROCm version detected: bin
11:45:24-834209 WARNING  ZLUDA support: experimental
11:45:25-194150 WARNING  Failed to install ZLUDA: HTTP Error 404: Not Found
11:45:25-195151 INFO     Using CPU-only torch
11:45:25-197196 DEBUG    Diffusers install: current=None@
``
any help ?

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
issues without all required info provided are invalid and will be auto-closed.
you provided ZERO information, i can only guess you're trying to use zluda and rocm detection is failing.

**Comment by vladmandic** [comment]
closing as no required info provided after a week.
