### ISSUE TITLE
[Issue]: Failed to load resource: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by gerroon** [vladmandic/automatic#3483]
### Issue Description

I use this on a non connected computer. It seems like it is trying to load a remote script and cant load it naturally. it would be nice if this is included locally

```
https://[cdnjs.cloudflare.com](https://cdnjs.cloudflare.com/ajax/libs/iframe-resizer/4.3.6/iframeResizer.contentWindow.min.js)/ajax/libs/iframe-resizer/4.3.6/iframeResizer.contentWindow.min.js
```

![image](https://github.com/user-attachments/assets/4e3a8bcf-95c6-47d0-a08c-6338515dd36a)

### Version Platform Description

Windows 11 server
Windows 10 client
Edge on Windows 10

### Backend

Original

### UI

Standard

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this is coming from inside gradio, see <https://github.com/gradio-app/gradio/blob/fd0264f3358ef848690eceacb75481212dceecf0/js/app/src/app.html#L27>

but i've managed to monkey-patch it to load from local url instead. resolved in latest dev.
