### ISSUE TITLE
[Issue]: KeyError: 331 when trying to load Settings from a image into Text2Img

### ISSUE THREAD

**Issue by OlivioSarikas** [vladmandic/automatic#349]
### Issue Description

Every other time i try, i get KeyError: 331 when  loading Settings from a image into Text2Img
The UI freezes and i can't click on the top tabs anymore. It does not change to the Txt2Img tab, but instead stays in the image processing or gallery tab

Traceback (most recent call last):
  File "C:\Users\multi\Vlad1111\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\multi\Vlad1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "C:\Users\multi\Vlad1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 331

### Version Platform Description

Windows 11 PRO, with a 4080 GPU and a Python 3.10.6 install
Processor 13th Gen Intel(R) Core(TM) i7-13700KF, 3400 Mhz, 16 Core(s), 24 Logical Processor(s)

**Comment by vladmandic** [comment]
did you perform restart server from ui and can you confirm the issue occurs as well if you restart server from command line?

**Comment by OlivioSarikas** [comment]
Not sure where "restart server" is, but restart UI in settings does not fix it

**Comment by vladmandic** [comment]
Restart server from command line. Stop server (CTRL+C) and start it again. Does the issue happen on freshly started server.
Yes, I expect Restart UI in settings does not fix it and mostly actually causes it - that's why I asked if you used it or not.

**Comment by radry** [comment]
Same. When trying to load txt2img from an img I get this error:  

```
Traceback (most recent call last):
  File "G:\_AI\Stable Diffusion\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "G:\_AI\Stable Diffusion\automatic\venv\lib\site-packages\gradio\blocks.py", line 1078, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "G:\_AI\Stable Diffusion\automatic\venv\lib\site-packages\gradio\blocks.py", line 994, in postprocess_data
    block = self.blocks[output_id]
KeyError: 331
```

**Comment by Seputaes** [comment]
I can confirm that Restarting the UI appears to trigger the issue. Restarting the server fixes until you restart the UI again.

- Launch server/webui
- Go to Image Browser > Select Image > Send to Text (This works)
- Go to Settings > Click `Restart UI`
- Go to Image Browser > Select Image > Send to Text (You get the `KeyError` here and need to restart the server)

**Comment by vladmandic** [comment]
I though so. Then it's exactly as documented as possible to happen since Restart from UI does not clear internal states. And also documented not to open issues for that.

**Comment by radry** [comment]
> Then it's exactly as documented as possible to happen since Restart from UI does not clear internal states. And also documented not to open issues for that.

So since you are already aware of the issue, will it be fixed?

**Comment by OlivioSarikas** [comment]
I also get the problem if i freshly start Vlad Diffusion

**Comment by vladmandic** [comment]
@OlivioSarikas you get `KeyError` on fresh start of WebUI server when loading image in "Process Image" tab and sending it to "From Text" ?

**Comment by vladmandic** [comment]
> > Then it's exactly as documented as possible to happen since Restart from UI does not clear internal states. And also documented not to open issues for that.
> 
> So since you are already aware of the issue, will it be fixed?

Yes, but will require bigger changes that are currently in my backlog.
