### ISSUE TITLE
[Feature]: Add precision control setting to OpenVINO

### ISSUE THREAD

**Issue by hygehyge** [vladmandic/automatic#3494]
### Feature description

As described [here](https://docs.openvino.ai/2024/openvino-workflow/running-inference/optimize-inference/precision-control.html), OpenVINO has precision control hints.  
This allows users to select which is important, ACCURACY or PERFORMANCE.  
And in my environment(OpenVINO + Intel Iris Xe iGPU), these flags affect to inference result significantly.

### Version Platform Description

SD.Next:hash=5c684cb0 branch=master

**Comment by Disty0** [comment]
Is there any point to add another option for FP32? You will double the VRAM usage and double the generation time for no reason. FP16 and FP32 outputs are basically the same.
OpenVINO will use FP16 by default on GPU or BF16 on CPU if the CPU supports it.

**Comment by hygehyge** [comment]
@Disty0 
> OpenVINO will use FP16 by default on GPU or BF16 on CPU if the device supports them, otherwise FP32.  

Yes, that's right.  
And because of this, if model is trained in FP32 and use it with OpenVINO (which is my case), the inference result is different from expected.  
If we can control precision hint for device that supports FP32 will fix this isuue.  

For example, my iGPU supports FP32 and INFERENCE_PRECISION_HINT is FP16.  
>[ INFO ] GPU :
>[ INFO ]        SUPPORTED_PROPERTIES:
>[ INFO ]                AVAILABLE_DEVICES: 0
>[ INFO ]                DEVICE_ARCHITECTURE: GPU: vendor=0x8086 arch=v12.3.0
>[ INFO ]                FULL_DEVICE_NAME: Intel(R) Iris(R) Xe Graphics (iGPU)
>[ INFO ]                OPTIMIZATION_CAPABILITIES: $\color{red}{\textsf{FP32}}$, BIN, FP16, INT8, EXPORT_IMPORT
>[ INFO ]                INFERENCE_PRECISION_HINT: <Type: $\color{red}{\textsf{'float16'}}$ >

And when I set `execution_mode` to `ACCURACY` like below, the result seem to be as expected.  
(it tooks about 2s/it, when FP16 mode tooks about 1s/it, as you mentioned.)
```python
# in modules/intel/openvino/__init__.py
core.set_property(
    "GPU",
    {hints.execution_mode: hints.ExecutionMode.ACCURACY},
)
```
So I think to add precision control setting is useful.

**Comment by Disty0** [comment]
Can you give a link to an example FP32 model.

If it is a 2~ GB SD 1.5 model or a 6-7 GB SDXL model, then they are FP16 and you are wasting comput with FP32.

**Comment by Disty0** [comment]
Done: https://github.com/vladmandic/automatic/commit/3acf6013f618da7c9c72d1fd93ed854f77a66e4d

Have to manually delete the caches for it to take affect.

Also Accuracy mode is 4 it/s while Performance mode is 12 it/s

|  Accuracy  |  Performance  |
|---|---|
| ![Accuracy](https://github.com/user-attachments/assets/61d0fe4a-df44-48b5-becc-bc721252118d) | ![Performance](https://github.com/user-attachments/assets/aa74d639-48b7-4471-aeda-1ab6cccce2c9)  |

**Comment by hygehyge** [comment]
@vladmandic @Disty0 
Set accuracy works on my environment.  
Thank you !
