### ISSUE TITLE
[Feature]: Expose Upscaler2 in extras/process image again

### ISSUE THREAD

**Issue by leppie** [vladmandic/automatic#350]
### Feature description

This is currently hidden by CSS (and some code).

**Comment by vladmandic** [comment]
asked for several times, answer provided.

**Comment by leppie** [comment]
You only give a vague reasoning in #131. The reasoning is wrong though. 

The second upscaler still works on the base resolution and not the final output (at 1x scale). 

I can understand this might be confusing for novice users, but allow it via a setting then? Please.

**Comment by vladmandic** [comment]
i get it, but i'd rather spend time finding/implementing whatever is best upscaler than mess with combos of multiple.

**Comment by leppie** [comment]
There is no best upscaler. 

Personally I use SwinIR as primary, but it is too smooth. For seconday I use a noisier one. (you point is vaild up to here)

The fact is that you can change the visibility/ratio on both without incurring extra upscaling time (besides the CPU merge time) for how many times you like (takes ~6 seconds for my workflow). Sometimes it needs more noise, sometimes less, sometimes it takes 5+ guesses. That is the main benefit.
