### ISSUE TITLE
[Issue]: is controlnet not working? (cannot even install it / run it?)

### ISSUE THREAD

**Issue by ClothingAI** [vladmandic/automatic#3501]
### Issue Description

Hello,
I just installed SD NEXT (so I have latest one probably) and I did the --debug first launch.
Does "controlnet" (the most important extension) not work on SD NEXT?
![image](https://github.com/user-attachments/assets/a8022241-4ff1-4d31-8b93-4d3b3d41e620)

THe only change I did was on the webui bat where I hardcoded the bersion of python 
set PYTHON="C:\Users\.........\AppData\Local\Programs\Python\Python311\python.exe"
and commented "if not defined PYTHON (set PYTHON...."

So can I make it work or not? I only installed it because of the PEZ interogator, then I thought I might just use it. Then I see that controlnet does not work?

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
read docs.
simple search would answer this.
controlnet extension is not necessary in sdnext, sdnext has built-in control tab.
controlnet extension is only supported when running in original backend (a.k.a. legacy mode).

**Comment by ClothingAI** [comment]
> read docs. simple search would answer this. controlnet extension is not necessary in sdnext, sdnext has built-in control tab. controlnet extension is only supported when running in original backend (a.k.a. legacy mode).

@vladmandic 
Where is it? I can't see it:
![image](https://github.com/user-attachments/assets/05a75668-0203-4e34-b46d-9dad3cab026b)

That note should be written in the extenion manager for people who were searching like me.
Today I 3 UIs, and tried ton of workflows, I really would/could not read any documentation. This should be displayed in my front of eyes.
I even looked at the tab "control" did not see anything ressembling ControlNet there? so..?

**Comment by vladmandic** [comment]
> That note should be written in the extenion manager for people who were searching like me.
it is. that's what colors and mean and when you hover over it, it explains it.

> I even looked at the tab "control" did not see anything ressembling ControlNet there? so..?
it is there. and its pretty visible. but yes, its different than original controlnet extension.
again, if unsure, read docs. if you would/could not do that, not much i can do.

**Comment by ClothingAI** [comment]
I understand, but where is this documentation?
Anyway the real question here (for me) is:
![image](https://github.com/user-attachments/assets/692a1f2c-f8e1-4515-bd25-1cc7ec81455d)

Where is the drop downmenu to choose the control net model (Canny, Depth..) etc? I promise I tried and clicked in all places I could identify.

**Comment by ClothingAI** [comment]
Oooh It was hiding here: 
![image](https://github.com/user-attachments/assets/3d45da38-53fe-4fcf-9794-b5253862f839)

You really really guys should highlight this area. 
Actually this the most important area, should be first thing I see!
Without that, that tab look like just a "extra" "process" tab

**Comment by vladmandic** [comment]
> Without that, that tab look like just a "extra" "process" tab

the long-term intention of control tab is to supersede text and image and be single all-in-one - and that is already the default behavior when using modernui.
standardui is a bit more complicated - need to maintain compatibility with legacy workflows, so text and image are still there. plus actual layout of control tab is still in being tuned.

**Comment by ClothingAI** [comment]
Oh I saw the modern ui there but did not try it, I would try it next time.
Otherwise I noticed another problem but did not have time to check it.
In the PATHS settings; I configured a path for controlnet (I put the full path direclty and not a sub path like models\directory, it was like "C:\.....\controlent" from another UI.
And for some reason it worked for checkpoints, but controlnet models were not recognized. Wonder if that's normal.

**Comment by vladmandic** [comment]
i just tried, i cannot reproduce - seems to work.
if you have an problem, best to create an issue and fully document it:
- `set SD_CONTROL_DEBUG=true`
- `webui --debug`
- upload sdnext.log

**Comment by ClothingAI** [comment]
> i just tried, i cannot reproduce - seems to work. if you have an problem, best to create an issue and fully document it:
> 
> * `set SD_CONTROL_DEBUG=true`
> * `webui --debug`
> * upload sdnext.log

Ok I will next time.
Now that I think about it, it could be possibly because I inserted them inside a sub directory (like C:.....\controlent\SD)
Who knows. Will see
