### ISSUE TITLE
[Issue]: Alpha Matting appears to be broken on Windows

### ISSUE THREAD

**Issue by bparrott78** [vladmandic/automatic#351]
### Issue Description

When I try to use remove background and process image with alpha matting, I get this error:

RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1106 onnxruntime::ProviderLibrary::Get
[ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 126 "" when trying to load
"F:\automatic\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll"

It looks as if the location is hardcoded, the dll is in the correct directory.

### Version Platform Description

Windows, Chrome.

**Comment by vladmandic** [comment]
> It looks as if the location is hardcoded, the dll is in the correct directory.

so the file `F:\automatic\venv\lib\site-packages\onnxruntime\capi\onnxruntime_providers_tensorrt.dll` exists?

**Comment by vladmandic** [comment]
closing as no information provided, can reopen if new information is available.
