### ISSUE TITLE
[Issue]:  Error: upcast=True failed to validate // Generating SDXL

### ISSUE THREAD

**Issue by meditat2001** [vladmandic/automatic#3512]
### Issue Description

First thanks and congratulations a lot for this incredible sd.next!!!! 
Clean install with the latest SDnext (from yesterday) dev-master. Generating with trained model, 1k x 1k, no extensions, lora etc used. No upscaler, hires, etc.....
Openvino, cache is enabled. 

Error: 
 ERROR    Decode: sample=(1024, 1024, 3) invalid=3145728 mean=0.0 dtype=float32 vae=torch.float32
                         upcast=True failed to validate

This error comes in every version since sd.next updated=2024-07-24. 

### Version Platform Description

Win 11, latest Opera, Intel Iris Xe, 16GB Ram, 

### Relevant log output

```shell
Torch parameters: backend=openvino device=GPU config=Auto dtype=torch.float32 vae=torch.float32 unet=torch.float32 context=no_grad nohalf=True nohalfvae=True upscast=False deterministic=False test-fp16=False test-bf16=False optimization="Scaled-Dot-Product"
2024-10-23 19:23:40,299 | sd | INFO | shared | Device: device=Intel(R) Iris(R) Xe Graphics (iGPU) openvino=2024.3.0
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Disty0** [comment]
If it is an SDXL model, use this VAE: https://huggingface.co/madebyollin/sdxl-vae-fp16-fix/blob/main/sdxl_vae.safetensors

**Comment by meditat2001** [comment]
Yes the error is gone with the VAE! But now the image has only slightly(good as nothing), to do with the prompt. I used 2 SDXL models with built-in-VAE. I can try the SDXL 1.0 base model?
Thanks!

**Comment by meditat2001** [comment]
ok. I am just saying, the error is coming if I use a trained sdxl model with a VAE built in. The error didn’t appear in the  version 2024-07-24 with the same model. 

And if I use the  specific sdxl VAE, it works, but the output is so big different to the output of sd.next latest version (both same parameters)
output: version 2024-07-24. vs latest:

![00312-realvisxl5_steps_0596000_float16-In watercolor beautiful scenary nature small house on a small river a few people Art zen style](https://github.com/user-attachments/assets/5c4e387e-97a1-4e1c-8d12-546fd227db59)

![download](https://github.com/user-attachments/assets/14be7474-4828-4a56-b24e-9bbc17f824df)

**Comment by meditat2001** [comment]
Maybe it is the openvino version that changed?
SD.NeXt version 2024-07-24 uses openvino=2023.3.0
vs   latest version: openvino==2024.3.0

**Comment by Disty0** [comment]
Might be. 2024.4.0 has this issue on Intel ARC.
Try manually downgrading to 2024.2 or upgrading to 2024.4

**Comment by meditat2001** [comment]
Great Tip!!!
I guess, I can't do the version change pre-install?
 
I copied in venv\lib\site-packages\ the folders 
openvino\
openvino_telemetry\
openvino_telemetry-2024.1.0.dist-info\
openvino-2024.2.0.dist-info\
and deleted the current version. 

With  2024.2.0 it works! With  2024.4.0 it generates only a black image.
And also no additional VAE, but with the VAE included in the model.

Thanks a lot! Great Work!!!

**Comment by meditat2001** [comment]
ah ok, thanks! ok, for me this thread can be closed now...
