### ISSUE TITLE
[Issue]: Diffuser Model not loading after downloading

### ISSUE THREAD

**Issue by sk3nn1xxx** [vladmandic/automatic#3516]
### Issue Description

I download the Model but it just says 0mb size
i tried without directml and with.

### Version Platform Description

Windows, librewolf

### Relevant log output

```shell
(venv) C:\Users\sk3nn1x\Documents\SDNEXT>webui.bat
Using VENV: C:\Users\sk3nn1x\Documents\SDNEXT\venv
17:11:27-190930 INFO     Starting SD.Next
17:11:27-192936 INFO     Logger: file="C:\Users\sk3nn1x\Documents\SDNEXT\sdnext.log" level=INFO size=57244 mode=append
17:11:27-193936 INFO     Python: version=3.12.3 platform=Windows
                         bin="C:\Users\sk3nn1x\Documents\SDNEXT\venv\Scripts\python.exe"
                         venv="C:\Users\sk3nn1x\Documents\SDNEXT\venv"
17:11:27-326833 INFO     Version: app=sd.next updated=2024-10-23 hash=0d332ca7 branch=master
                         url=https://github.com/vladmandic/automatic.git/tree/master ui=main
17:11:27-862634 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-11-10.0.22631-SP0 python=3.12.3
17:11:27-873883 INFO     Python: version=3.12.3 platform=Windows
                         bin="C:\Users\sk3nn1x\Documents\SDNEXT\venv\Scripts\python.exe"
                         venv="C:\Users\sk3nn1x\Documents\SDNEXT\venv"
17:11:27-875884 INFO     OpenVINO: selected
17:11:27-876883 INFO     Install: package="onnxruntime-openvino" mode=pip
17:11:29-068861 INFO     Verifying requirements
17:11:29-071937 INFO     Verifying packages
17:11:29-107985 INFO     Extensions: disabled=[]
17:11:29-108985 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
                         extensions-builtin
17:11:29-111500 INFO     Extensions: enabled=[] extensions
17:11:29-112657 INFO     Startup: quick launch
17:11:29-113662 INFO     Extensions: disabled=[]
17:11:29-113662 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
                         extensions-builtin
17:11:29-116753 INFO     Extensions: enabled=[] extensions
17:11:29-119866 INFO     Command line args: []
17:11:33-533628 INFO     System packages: {'torch': '2.4.1+cpu', 'diffusers': '0.32.0.dev0', 'gradio': '3.43.2',
                         'transformers': '4.45.2', 'accelerate': '1.0.0'}
17:11:33-862670 INFO     Engine: backend=Backend.DIFFUSERS compute=cpu device=cpu attention="Scaled-Dot-Product"
                         mode=no_grad
17:11:33-864982 INFO     Torch parameters: backend=cpu device=cpu config=Auto dtype=torch.bfloat16 vae=torch.bfloat16
                         unet=torch.bfloat16 context=no_grad nohalf=False nohalfvae=False upscast=False
                         deterministic=False test-fp16=True test-bf16=True optimization="Scaled-Dot-Product"
17:11:34-191198 INFO     Device:
17:11:34-289549 INFO     Available VAEs: path="models\VAE" items=0
17:11:34-291615 INFO     Available UNets: path="models\UNET" items=0
17:11:34-291615 INFO     Available TEs: path="models\Text-encoder" items=0
17:11:34-292622 INFO     Disabled extensions: ['sdnext-modernui']
17:11:34-293704 INFO     Available Models: path="models\Stable-diffusion" items=0 time=0.00
17:11:34-350637 INFO     Available Yolo: path="models\yolo items=6 downloaded=0
17:11:34-498969 INFO     Extension: script='extensions-builtin\Lora\scripts\lora_script.py'
                         [2;36m17:11:34-396947[0m[2;36m [0m[34mINFO    [0m Available LoRAs: [33mitems[0m=[1;36m0[0m
                         [33mfolders[0m=[1;36m2[0m
17:11:34-929370 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
17:11:34-947685 INFO     Available Upscalers: items=53 downloaded=0 user=0 time=0.01 types=['None', 'Lanczos',
                         'Nearest', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'LDSR', 'RealESRGAN', 'SCUNet', 'SD', 'SwinIR']
17:11:34-957697 INFO     Available Styles: folder="models\styles" items=288 time=0.01
17:11:34-960698 INFO     UI theme: type=Standard name="black-teal"
17:11:35-716013 INFO     Extension list is empty: refresh required
17:11:36-185532 INFO     Local URL: http://127.0.0.1:7860/
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
17:11:37-178776 WARNING  OpenVINO: No compatible GPU detected! Using CPU
17:11:37-455912 INFO     [AgentScheduler] Task queue is empty
17:11:37-456913 INFO     [AgentScheduler] Registering APIs
17:11:37-526322 WARNING  Cannot generate without a checkpoint
17:11:37-527323 INFO     Set system paths to use existing folders
17:11:37-527323 INFO       or use --models-dir <path-to-folder> to specify base folder with all models
17:11:37-528322 INFO       or use --ckpt-dir <path-to-folder> to specify folder with sd models
17:11:37-528322 INFO       or use --ckpt <path-to-checkpoint> to force using specific model
17:11:37-529323 INFO     Startup time: 8.41 torch=3.27 gradio=0.84 diffusers=0.07 libraries=0.95 extensions=0.58
                         detailer=0.06 ui-networks=0.11 ui-txt2img=0.06 ui-img2img=0.06 ui-control=0.09 ui-settings=0.17
                         ui-extensions=0.55 launch=0.08 app-started=1.29
17:11:39-880796 INFO     MOTD: N/A
17:11:45-714366 INFO     Browser session: user=None client=127.0.0.1 agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64;
                         rv:129.0) Gecko/20100101 Firefox/129.0
17:12:09-409806 INFO     HF login: token="C:\Users\sk3nn1x\.cache\huggingface\token" Token is valid (permission: read).
model_index.json: 100%|███████████████████████████████████████████████████████████████████████| 577/577 [00:00<?, ?B/s]
tokenizer/special_tokens_map.json: 100%|██████████████████████████████████████████████████████| 460/460 [00:00<?, ?B/s]
scheduler/scheduler_config.json: 100%|████████████████████████████████████████████████████████| 341/341 [00:00<?, ?B/s]
(…)ature_extractor/preprocessor_config.json: 100%|████████████████████████████████████████████| 518/518 [00:00<?, ?B/s]
safety_checker/config.json: 100%|█████████████████████████████████████████████████████████| 4.89k/4.89k [00:00<?, ?B/s]
tokenizer/tokenizer_config.json: 100%|████████████████████████████████████████████████████████| 819/819 [00:00<?, ?B/s]
text_encoder/config.json: 100%|███████████████████████████████████████████████████████████████| 620/620 [00:00<?, ?B/s]
tokenizer/merges.txt: 100%|█████████████████████████████████████████████████████████| 525k/525k [00:00<00:00, 1.39MB/s]
vae/config.json: 100%|████████████████████████████████████████████████████████████████████████| 601/601 [00:00<?, ?B/s]
unet/config.json: 100%|███████████████████████████████████████████████████████████████████| 1.00k/1.00k [00:00<?, ?B/s]
tokenizer/vocab.json: 100%|███████████████████████████████████████████████████████| 1.06M/1.06M [00:00<00:00, 1.17MB/s]
diffusion_pytorch_model.safetensors: 100%|██████████████████████████████████████████| 335M/335M [00:55<00:00, 5.98MB/s]
model.safetensors: 100%|██████████████████████████████████████████████████████████| 1.36G/1.36G [02:15<00:00, 10.1MB/s]
model.safetensors: 100%|██████████████████████████████████████████████████████████| 1.22G/1.22G [02:23<00:00, 8.45MB/s]
diffusion_pytorch_model.safetensors: 100%|████████████████████████████████████████| 3.46G/3.46G [03:28<00:00, 16.6MB/s]
Diffusers 13.94s/it ███████████████████ 100% 15/15 03:29 00:00 Fetching 15 files  | 1.50G/3.46G [02:23<02:09, 15.1MB/s]
17:15:40-006434 INFO     Available Models: path="models\Stable-diffusion" items=1 time=0.01
17:15:40-006434 INFO     Diffuser model downloaded: model="hakurei/waifu-diffusion"
17:16:14-114739 INFO     Available Models: path="models\Stable-diffusion" items=1 time=0.00
17:16:16-038486 INFO     Load model: select="Diffusers\hakurei/waifu-diffusion [87a6d830b9]"
17:16:16-040992 INFO     Autodetect model: detect="Stable Diffusion" class=StableDiffusionPipeline
                         file="models\Diffusers\models--hakurei--waifu-diffusion\snapshots\87a6d830b9b23f7e5727f162782cf
                         3f4a7a84be1" size=0MB
17:16:16-042996 ERROR    Diffuser model not loaded
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by sk3nn1xxx** [comment]
it worked with the normal 3.5 stable diffusion model but this just eats too much ressources

**Comment by vladmandic** [comment]
need more info why model load failed - it just says `not loaded`
- run `set SD_LOAD_DEBUG=true`
- start sdnext with `webui --debug`
- upload full log here

**Comment by sk3nn1xxx** [comment]
(venv) C:\Users\sk3nn1x\Documents\SDNEXT>webui.bat --use-directml --debug
Using VENV: C:\Users\sk3nn1x\Documents\SDNEXT\venv
18:18:35-014644 INFO     Starting SD.Next
18:18:35-017147 INFO     Logger: file="C:\Users\sk3nn1x\Documents\SDNEXT\sdnext.log" level=DEBUG size=65 mode=create
18:18:35-017669 INFO     Python: version=3.12.3 platform=Windows
                         bin="C:\Users\sk3nn1x\Documents\SDNEXT\venv\Scripts\python.exe"
                         venv="C:\Users\sk3nn1x\Documents\SDNEXT\venv"
18:18:35-193760 INFO     Version: app=sd.next updated=2024-10-23 hash=0d332ca7 branch=master
                         url=https://github.com/vladmandic/automatic.git/tree/master ui=main
18:18:35-784534 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-11-10.0.22631-SP0 python=3.12.3
18:18:35-786533 DEBUG    Setting environment tuning
18:18:35-787533 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
18:18:35-792040 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=True openvino=False zluda=False
18:18:35-793041 INFO     DirectML: selected
18:18:35-885935 INFO     Verifying requirements
18:18:35-889442 INFO     Verifying packages
18:18:35-919504 DEBUG    Timestamp repository update time: Wed Oct 23 20:59:10 2024
18:18:35-919504 INFO     Startup: standard
18:18:35-920504 INFO     Verifying submodules
18:18:37-684343 DEBUG    Git submodule: extensions-builtin/sd-extension-chainner / main
18:18:37-751134 DEBUG    Git submodule: extensions-builtin/sd-extension-system-info / main
18:18:37-815163 DEBUG    Git submodule: extensions-builtin/sd-webui-agent-scheduler / main
18:18:37-880179 DEBUG    Git submodule: extensions-builtin/sdnext-modernui / main
18:18:37-943393 DEBUG    Git submodule: extensions-builtin/stable-diffusion-webui-rembg / master
18:18:38-003983 DEBUG    Git submodule: modules/k-diffusion / master
18:18:38-062056 DEBUG    Git submodule: wiki / master
18:18:38-096855 DEBUG    Register paths
18:18:38-142506 DEBUG    Installed packages: 198
18:18:38-143504 DEBUG    Extensions all: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
18:18:38-269481 DEBUG    Extension installer:
                         C:\Users\sk3nn1x\Documents\SDNEXT\extensions-builtin\sd-webui-agent-scheduler\install.py
18:18:40-110476 DEBUG    Extension installer:
                         C:\Users\sk3nn1x\Documents\SDNEXT\extensions-builtin\stable-diffusion-webui-rembg\install.py
18:18:46-241524 DEBUG    Extensions all: []
18:18:46-242524 INFO     Extensions enabled: ['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
18:18:46-242524 INFO     Verifying requirements
18:18:46-243523 DEBUG    Setup complete without errors: 1729786726
18:18:46-246157 DEBUG    Extension preload: {'extensions-builtin': 0.0, 'extensions': 0.0}
18:18:46-247156 DEBUG    Starting module: <module 'webui' from 'C:\\Users\\sk3nn1x\\Documents\\SDNEXT\\webui.py'>
18:18:46-248659 INFO     Command line args: ['--use-directml', '--debug'] use_directml=True debug=True
18:18:46-248659 DEBUG    Env flags: []
18:18:51-250081 INFO     System packages: {'torch': '2.4.1+cpu', 'diffusers': '0.32.0.dev0', 'gradio': '3.43.2',
                         'transformers': '4.45.2', 'accelerate': '1.0.0'}
18:18:51-604441 DEBUG    Huggingface cache: folder="C:\Users\sk3nn1x\.cache\huggingface\hub"
18:18:51-678416 INFO     Device detect: memory=8.0 ptimization=medvram
18:18:51-680452 DEBUG    Read: file="config.json" json=33 bytes=1455 time=0.000
18:18:51-681455 INFO     Engine: backend=Backend.DIFFUSERS compute=directml device=privateuseone:0 attention="Dynamic
                         Attention BMM" mode=no_grad
18:18:51-682460 DEBUG    Read: file="html\reference.json" json=58 bytes=30996 time=0.000
18:18:51-747887 INFO     Torch parameters: backend=directml device=privateuseone:0 config=Auto dtype=torch.float16
                         vae=torch.float16 unet=torch.float16 context=no_grad nohalf=False nohalfvae=False upscast=False
                         deterministic=False test-fp16=True test-bf16=False optimization="Dynamic Attention BMM"
18:18:52-089414 DEBUG    ONNX: version=1.19.2 provider=DmlExecutionProvider, available=['AzureExecutionProvider',
                         'CPUExecutionProvider']
18:18:52-135253 INFO     Device: device=AMD Radeon RX 7800 XT n=2 directml=0.2.5.dev240914
18:18:52-202985 DEBUG    Importing LDM
18:18:52-214060 DEBUG    Entering start sequence
18:18:52-216582 DEBUG    Initializing
18:18:52-245084 INFO     Available VAEs: path="models\VAE" items=0
18:18:52-246587 INFO     Available UNets: path="models\UNET" items=0
18:18:52-247592 INFO     Available TEs: path="models\Text-encoder" items=0
18:18:52-247592 INFO     Disabled extensions: ['sdnext-modernui']
18:18:52-250591 DEBUG    Read: file="metadata.json" json=4 bytes=800 time=0.000
18:18:52-251590 DEBUG    Scanning diffusers cache: folder="models\Diffusers" items=1 time=0.00
18:18:52-252591 INFO     Available Models: path="models\Stable-diffusion" items=5 time=0.00
18:18:52-314395 INFO     Available Yolo: path="models\yolo items=6 downloaded=0
18:18:52-315399 DEBUG    Load extensions
18:18:52-476279 INFO     Extension: script='extensions-builtin\Lora\scripts\lora_script.py'
                         [2;36m18:18:52-361823[0m[2;36m [0m[34mINFO    [0m Available LoRAs: [33mitems[0m=[1;36m0[0m
                         [33mfolders[0m=[1;36m2[0m
18:18:52-932545 INFO     Extension: script='extensions-builtin\sd-webui-agent-scheduler\scripts\task_scheduler.py' Using
                         sqlite file: extensions-builtin\sd-webui-agent-scheduler\task_scheduler.sqlite3
18:18:52-935053 DEBUG    Extensions init time: 0.62 Lora=0.12 sd-webui-agent-scheduler=0.42
18:18:52-958648 DEBUG    Read: file="html/upscalers.json" json=4 bytes=2672 time=0.000
18:18:52-960647 DEBUG    Read: file="extensions-builtin\sd-extension-chainner\models.json" json=24 bytes=2719 time=0.000
18:18:52-961650 DEBUG    chaiNNer models: path="models\chaiNNer" defined=24 discovered=0 downloaded=0
18:18:52-962648 INFO     Available Upscalers: items=53 downloaded=0 user=0 time=0.03 types=['None', 'Lanczos',
                         'Nearest', 'ChaiNNer', 'AuraSR', 'ESRGAN', 'LDSR', 'RealESRGAN', 'SCUNet', 'SD', 'SwinIR']
18:18:52-972664 INFO     Available Styles: folder="models\styles" items=288 time=0.01
18:18:52-977170 DEBUG    Creating UI
18:18:52-978170 DEBUG    UI themes available: type=Standard themes=12
18:18:52-979170 INFO     UI theme: type=Standard name="black-teal"
18:18:52-982220 DEBUG    UI theme: css="C:\Users\sk3nn1x\Documents\SDNEXT\javascript\black-teal.css" base="sdnext.css"
                         user="None"
18:18:52-983724 DEBUG    UI initialize: txt2img
18:18:53-010276 DEBUG    Networks: page='model' items=62 subfolders=2 tab=txt2img folders=['models\\Stable-diffusion',
                         'models\\Diffusers', 'models\\Reference'] list=0.01 thumb=0.00 desc=0.00 info=0.00 workers=8
                         sort=Default
18:18:53-012276 DEBUG    Networks: page='lora' items=0 subfolders=0 tab=txt2img folders=['models\\Lora',
                         'models\\LyCORIS'] list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
18:18:53-017313 DEBUG    Networks: page='style' items=288 subfolders=1 tab=txt2img folders=['models\\styles', 'html']
                         list=0.01 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
18:18:53-020313 DEBUG    Networks: page='embedding' items=0 subfolders=0 tab=txt2img folders=['models\\embeddings']
                         list=0.00 thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
18:18:53-021312 DEBUG    Networks: page='vae' items=0 subfolders=0 tab=txt2img folders=['models\\VAE'] list=0.00
                         thumb=0.00 desc=0.00 info=0.00 workers=8 sort=Default
18:18:53-022311 DEBUG    Networks: page='history' items=0 subfolders=0 tab=txt2img folders=[] list=0.00 thumb=0.00
                         desc=0.00 info=0.00 workers=8 sort=Default
18:18:53-093872 DEBUG    UI initialize: img2img
18:18:53-176051 DEBUG    UI initialize: control models=models\control
18:18:53-400892 DEBUG    Read: file="ui-config.json" json=0 bytes=2 time=0.000
18:18:53-499510 DEBUG    UI themes available: type=Standard themes=12
18:18:53-792181 DEBUG    Reading failed: C:\Users\sk3nn1x\Documents\SDNEXT\html\extensions.json [Errno 2] No such file
                         or directory: 'C:\\Users\\sk3nn1x\\Documents\\SDNEXT\\html\\extensions.json'
18:18:53-792181 INFO     Extension list is empty: refresh required
18:18:54-141144 DEBUG    Extension list: processed=6 installed=6 enabled=5 disabled=1 visible=6 hidden=0
18:18:54-226607 DEBUG    Root paths: ['C:\\Users\\sk3nn1x\\Documents\\SDNEXT']
18:18:54-283652 INFO     Local URL: http://127.0.0.1:7860/
18:18:54-284766 DEBUG    Gradio functions: registered=1895
18:18:54-285767 DEBUG    FastAPI middleware: ['Middleware', 'Middleware']
18:18:54-288273 DEBUG    Creating API
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
18:18:55-377092 WARNING  OpenVINO: No compatible GPU detected! Using CPU
18:18:55-664534 INFO     [AgentScheduler] Task queue is empty
18:18:55-665533 INFO     [AgentScheduler] Registering APIs
18:18:55-739074 DEBUG    Scripts setup: ['IP Adapters:0.017', 'XYZ Grid:0.017', 'Face:0.012', 'AnimateDiff:0.006',
                         'CogVideoX:0.006', 'Image-to-Video:0.006']
18:18:55-740071 DEBUG    Model metadata: file="metadata.json" no changes
18:18:55-875401 DEBUG    Model requested: fn=run:<lambda>
18:18:55-876903 INFO     Load model: select="Diffusers\hakurei/waifu-diffusion [87a6d830b9]"
18:18:55-878907 INFO     Autodetect model: detect="Stable Diffusion" class=StableDiffusionPipeline
                         file="models\Diffusers\models--hakurei--waifu-diffusion\snapshots\87a6d830b9b23f7e5727f162782cf
                         3f4a7a84be1" size=0MB
18:18:55-879907 ERROR    Diffuser model not loaded
18:18:55-880905 DEBUG    Script callback init time: system-info.py:app_started=1.08 task_scheduler.py:app_started=0.32
18:18:55-881905 INFO     Startup time: 9.63 torch=3.73 gradio=0.92 diffusers=0.08 libraries=1.22 extensions=0.62
                         detailer=0.06 ui-networks=0.12 ui-txt2img=0.06 ui-img2img=0.06 ui-control=0.10 ui-settings=0.38
                         ui-extensions=0.38 launch=0.09 api=0.05 app-started=1.40 checkpoint=0.14
18:18:55-881905 DEBUG    Save: file="config.json" json=33 bytes=1405 time=0.001

**Comment by vladmandic** [comment]
should be resolved in the lastest update.
