### ISSUE TITLE
[Issue] how to run sd35

### ISSUE THREAD

**Issue by stayen** [vladmandic/automatic#3528]
### Issue Description

GPU: NVidia RTX A2000 12Gb

I am trying to use SP 3.5 Large or Turbo models (downloaded from Huggingface using its token), setting all generation parameters to defaults, and see

`op=txt model not loaded`

after setting text model to TP5 and quantization to NF4 and trying to launch the generation.

Are there sample settings to run SP 3.5 in the low-RAM GPUs like mentioned? The "TP5", "NF4" were taken from Stability.AI sample code on the model card.

### Version Platform Description

OS: Ubuntu 22.04
Browser: Firefox, latest version
Automatic: latest pulled from Github

Logs start with 

```
Starting SD.Next                                       
Logger: file="/home/renderer/automatic/sdnext.log"     
                         level=DEBUG size=64 mode=create                        
Python: version=3.10.12 platform=Linux                 
                         bin="/home/renderer/automatic/venv/bin/python3"        
                         venv="/home/renderer/automatic/venv"                   
Version: app=sd.next updated=2024-10-24 hash=06dd9e5f  
                         branch=master                                          
                         url=https://github.com/vladmandic/automatic/tree/master
                         ui=main                                                
Platform: arch=x86_64 cpu=x86_64 system=Linux          
                         release=6.8.0-47-generic python=3.10.12                
Setting environment tuning                             
Torch allocator:                                       
                         "garbage_collection_threshold:0.80,max_split_size_mb:51
                         2"                                                     
Torch overrides: cuda=False rocm=False ipex=False      
                         directml=False openvino=False zluda=False              
CUDA: nVidia toolkit detected                          
Diffusers upgrade: package=diffusers 0.32.0.dev0       
                         current=                                               
                         target=e45c25d03aeb0a967d8aaa0f6a79f280f6838e1f 
                         
```

### Relevant log output

```shell
23:36:33-115048 DEBUG    Model requested: fn=f:txt2img                          
23:36:33-116414 WARNING  Aborted: op=txt model not loaded
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
> downloaded from Huggingface using its token

downloaded what? entire folder structure? single file? provide detailed information.

note that sdnext recommends not to manually download sd3 at all - simply select in networks -> models -> reference!

**Comment by stayen** [comment]
The models are being downloaded via WebUI (not manually): Models - Huggingface, enter "stable diffusion 3.5" in "Search models", select the  model and click "Download model"). I have to enter contact data in separate authenticated Hugginface browser tab, otherwise download fails.

The models data are placed into models/Diffusers, namely under

models--stabilityai--stable-diffusion-3.5-large/
models--stabilityai--stable-diffusion-3.5-large-turbo/

After that, the models are listed in the models dropdown:

![models-dropdown](https://github.com/user-attachments/assets/79c197f2-e603-407e-9808-464fb750e576)

**Comment by vladmandic** [comment]
run
- `export SD_LOAD_DEBUG=true`
- `./webui.sh --debug`
and upload full log here.

**Comment by stayen** [comment]
Started WebUI as requested.

Loaded SDXLmodel, ran generation to make sure generation works.
Tried to load Stable Diffusion 3.5 Large, waited till it failed due to OOM.
Loaded SDXLmodel, ran generation to make sure generation works.

The logs are attached.

[sdnext.log](https://github.com/user-attachments/files/17535750/sdnext.log)

**Comment by vladmandic** [comment]
nf4 quantization support for sd35 was added very recently, its not in master branch yet - try using dev branch.
and since this is no longer an issue, but more of a question, i'm closing the github issue - you can still reply here, but for purposes of issue tracking its closed.

**Comment by stayen** [comment]
My only question is whether Wiki will be updated by samples of configurations related to quantization. Otherwise, the majority of users will be excluded from using Flux/SD 3.5 until a major upgrade is done to the GPU unit.

Thanks for the reference to dev branch, I appreciate your assistance.

**Comment by stayen** [comment]
NB: the link to [NNCF Wiki](https://github.com/vladmandic/automatic/wiki/Model-Compression-with-NNCF) redirects back to main Wiki page (perhaps it's stub, not yet generated). Thanks again and good luck.
