### ISSUE TITLE
[Issue]: model is not cached locally

### ISSUE THREAD

**Issue by luoyefengxing** [vladmandic/automatic#3538]
### Issue Description

ERROR    Load model: path="D:\SDNEXT\automatic\models\Stable-diffusion\flux_dev.safetensors" Cannot load model flux_dev: model is not cached locally and an error occurred while trying to fetchmetadata from the Hub. Please check out the root cause in the stacktrace above.

console log
14:46:29-272601 INFO     Starting SD.Next
14:46:29-275600 INFO     Logger: file="D:\SDNEXT\automatic\sdnext.log" level=DEBUG size=65 mode=create
14:46:29-277603 INFO     Python: version=3.10.6 platform=Windows bin="D:\SDNEXT\automatic\venv\Scripts\python.exe"
                         venv="D:\SDNEXT\automatic\venv"
14:46:29-404085 INFO     Version: app=sd.next updated=2024-10-29 hash=41f9a350 branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
14:46:30-237184 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD system=Windows
                         release=Windows-10-10.0.19045-SP0 python=3.10.6
14:46:30-245767 DEBUG    Setting environment tuning
14:46:30-247767 DEBUG    Torch allocator: "garbage_collection_threshold:0.80,max_split_size_mb:512"
14:46:30-252769 DEBUG    Torch overrides: cuda=False rocm=False ipex=False directml=False openvino=False zluda=True
14:46:30-260768 INFO     Python: version=3.10.6 platform=Windows bin="D:\SDNEXT\automatic\venv\Scripts\python.exe"

### Version Platform Description

pyyhon3.10,

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
upload actual log.
also, describe what is `flux_dev.safetensors` - where did it come from? how big is the file?

**Comment by luoyefengxing** [comment]
> upload actual log. also, describe what is `flux_dev.safetensors` - where did it come from? how big is the file?

1![ERROR](https://github.com/user-attachments/assets/b282a33b-4b99-47f0-8349-7cb812c328fe)
2.flux_dev.safetensors(15.9GB) from CIVITAI

**Comment by vladmandic** [comment]
never post a screenshot of log, always post a log itself.
and look at the error message: "model detected as flux unet model, but attempting to load a base model"
that is NOT a model, that is only one model component. read flux wiki on how to use it.

**Comment by luoyefengxing** [comment]
> never post a screenshot of log, always post a log itself. and look at the error message: "model detected as flux unet model, but attempting to load a base model" that is NOT a model, that is only one model component. read flux wiki on how to use it.

OK,Thanks
