### ISSUE TITLE
[Issue]: Networks incorrect initial sort order on load

### ISSUE THREAD

**Issue by futaposting** [vladmandic/automatic#3541]
### Issue Description

Default sort order is set to [A-Z], but there is some strangeness on first load. All loras are in subfolders.
Here you can see some of the lora sorted by a-z, but some are missing.
![Capture](https://github.com/user-attachments/assets/a42f5211-f38e-4d75-8043-6e9c454759d8)
The rest are later down the list, it appears to group the loras into two groups and sort each one a-z
![Capture3](https://github.com/user-attachments/assets/12aa7bff-83f2-4d49-a88e-f6225104b797)
After cycling through all the 6 sort methods back to [A-Z] it's sorted correctly
![Capture2](https://github.com/user-attachments/assets/de6b0c38-f98e-41aa-b699-022727aecffc)

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by futaposting** [comment]
I agree that it shouldn't wait. Could another solution be to make the refresh button apply the current sort since all loras should be analyzed at that point?

**Comment by vladmandic** [comment]
yes, that should be doable, just need to figure out how to reproduce so i can test and its really timing dependent. i'll probably need to create fake lora that loads very slowly.

**Comment by vladmandic** [comment]
ok, this should now be resolved. make sure you're using latest dev branch AND clear browser cache.
