### ISSUE TITLE
[Issue]: Lora is not recognized when installing the extension stable-diffusion-webui-wd14-tagger

### ISSUE THREAD

**Issue by wkdtjs** [vladmandic/automatic#355]
### Issue Description

When I downloaded it for the first time, there is no problem, but when I install the stable-diffusion-webui-wd14-tagger, I don't recognize Lora.

![화면 캡처 2023-04-22 071437](https://user-images.githubusercontent.com/65364921/233742542-2d1d7eff-cc13-4f6e-bf40-10f084123857.png)

venv "D:\automatic\automatic\venv\Scripts\Python.exe"
2023-04-22 07:10:08,494 | WARNING | D:\automatic\automatic\venv\lib\site-packages\xformers\__init__.py | A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
D:\automatic\automatic\venv\lib\site-packages\pytorch_lightning\utilities\distributed.py:258: LightningDeprecationWarning: `pytorch_lightning.utilities.distributed.rank_zero_only` has been deprecated in v1.8.1 and will be removed in v2.0.0. You can import it from `pytorch_lightning.utilities` instead.
  rank_zero_deprecation(
07:10:09-120928 INFO     Python 3.10.6 on Windows
07:10:09-161387 INFO     No changes detected: quick launch active
07:10:09-162384 INFO     Setting environment tuning
07:10:09-162384 INFO     Server arguments: []
Available models: models\Stable-diffusion 30
Module load: D:\automatic\automatic\extensions-builtin\Lora\scripts\lora_script.py: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\automatic\modules\script_loading.py:10 in load_module                                                   │
│                                                                                                                      │
│    9 │   try:                                                                                                        │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                                  │
│   11 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│                                                                                                                      │
│                                               ... 2 frames hidden ...                                                │
│                                                                                                                      │
│ D:\automatic\automatic\extensions-builtin\Lora\lora.py:382 in <module>                                               │
│                                                                                                                      │
│   381                                                                                                                │
│ ❱ 382 list_available_loras()                                                                                         │
│   383                                                                                                                │
│                                                                                                                      │
│ D:\automatic\automatic\extensions-builtin\Lora\lora.py:363 in list_available_loras                                   │
│                                                                                                                      │
│   362 │                                                                                                              │
│ ❱ 363 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)                                                       │
│   364                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'lora_dir'
Loading theme: gradio/default
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Loading weights: models\Stable-diffusion\0.25(uenomigiDB_v1) + 0.75(AbyssMapleVer3).safetensors ━━━━━━━━ 0.0/1.7 -:--:--
                                                                                                         GB
Creating model from config: D:\automatic\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: models\Stable-diffusion\orangemix.vae.pt ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/822.8 MB -:--:--
Applying xformers cross attention optimization
Embeddings loaded: bad-hands-5, badhandv4, badv3, bad_prompt_version2, By bad artist -neg (5)
Model loaded in 5.0s (load=0.2s create=2.0s apply=0.3s vae=0.8s move=0.4s embeddings=1.4s)
Startup time: 9.5s (libraries=1.3s models=0.2s codeformer=0.1s scripts=0.1s ui=2.5s start=0.1s scripts
app_started_callback=0.1s checkpoint=5.1s)
Traceback (most recent call last):
  File "D:\automatic\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\automatic\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\automatic\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\automatic\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\automatic\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
asyncio.exceptions.CancelledError
WebSocket closed (ignore asyncio.exceptions.CancelledError)
Server shutdown
Server restart
Available models: models\Stable-diffusion 30
Module load: D:\automatic\automatic\extensions-builtin\a1111-sd-webui-lycoris\scripts\lycoris_script.py: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\automatic\modules\script_loading.py:10 in load_module                                                   │
│                                                                                                                      │
│    9 │   try:                                                                                                        │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                                  │
│   11 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│                                                                                                                      │
│                                               ... 3 frames hidden ...                                                │
│                                                                                                                      │
│ D:\automatic\automatic\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora.py:382 in        │
│ <module>                                                                                                             │
│                                                                                                                      │
│   381                                                                                                                │
│ ❱ 382 list_available_loras()                                                                                         │
│   383                                                                                                                │
│                                                                                                                      │
│ D:\automatic\automatic\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora.py:363 in        │
│ list_available_loras                                                                                                 │
│                                                                                                                      │
│   362 │                                                                                                              │
│ ❱ 363 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)                                                       │
│   364                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'lora_dir'
Module load: D:\automatic\automatic\extensions-builtin\Lora\scripts\lora_script.py: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\automatic\modules\script_loading.py:10 in load_module                                                   │
│                                                                                                                      │
│    9 │   try:                                                                                                        │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                                  │
│   11 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│                                                                                                                      │
│                                               ... 2 frames hidden ...                                                │
│                                                                                                                      │
│ D:\automatic\automatic\extensions-builtin\Lora\lora.py:382 in <module>                                               │
│                                                                                                                      │
│   381                                                                                                                │
│ ❱ 382 list_available_loras()                                                                                         │
│   383                                                                                                                │
│                                                                                                                      │
│ D:\automatic\automatic\extensions-builtin\Lora\lora.py:363 in list_available_loras                                   │
│                                                                                                                      │
│   362 │                                                                                                              │
│ ❱ 363 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)                                                       │
│   364                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'lora_dir'
Module load: D:\automatic\automatic\extensions\AI-WEBUI-scripts-Random\scripts\Random grid.py: ImportError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\automatic\modules\script_loading.py:10 in load_module                                                   │
│                                                                                                                      │
│    9 │   try:                                                                                                        │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                                  │
│   11 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│ in _call_with_frames_removed:241                                                                                     │
│                                                                                                                      │
│ D:\automatic\automatic\extensions\AI-WEBUI-scripts-Random\scripts\Random grid.py:27 in <module>                      │
│                                                                                                                      │
│    26 from modules.hypernetworks import hypernetwork                                                                 │
│ ❱  27 from modules.processing import process_images, Processed, get_correct_sampler, StableDif                       │
│    28 from modules.shared import opts, cmd_opts, state                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'get_correct_sampler' from 'modules.processing'
(D:\automatic\automatic\modules\processing.py)
Loading theme: gradio/default
executing callback: D:\automatic\automatic\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py
ui_tabs_callback: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\automatic\modules\script_callbacks.py:122 in ui_tabs_callback                                           │
│                                                                                                                      │
│   121 │   │   try:                                                                                                   │
│ ❱ 122 │   │   │   res += c.callback() or []                                                                          │
│   123 │   │   except Exception as e:                                                                                 │
│                                                                                                                      │
│ D:\automatic\automatic\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py:329 in on_ui_tabs                  │
│                                                                                                                      │
│   328 │   │   │   │   │   with gr.Row(variant='compact'):                                                            │
│ ❱ 329 │   │   │   │   │   │   interrogator_names = utils.refresh_interrogators()                                     │
│   330 │   │   │   │   │   │   interrogator = utils.preset.component(                                                 │
│                                                                                                                      │
│ D:\automatic\automatic\extensions\stable-diffusion-webui-wd14-tagger\tagger\utils.py:70 in refresh_interrogators     │
│                                                                                                                      │
│   69 │                                                                                                               │
│ ❱ 70 │   for path in os.scandir(shared.cmd_opts.deepdanbooru_projects_path):                                         │
│   71 │   │   if not path.is_dir():                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Startup time: 9.8s (scripts=4.7s ui=5.0s start=0.1s)

### Version Platform Description

windows 11

**Comment by The-Noble** [comment]
I had this happen to me once, I just re-pulled and restarted and it worked.
Try that, while you wait for a more official response.

**Comment by wkdtjs** [comment]
I've tried many times, but I failed.

**Comment by The-Noble** [comment]
I see, my error must have had a different cause then yours. Probably best to wait for a response from the Vlad. 
Sorry!

**Comment by wkdtjs** [comment]
No, thank you for your answer.

**Comment by wkdtjs** [comment]
As a result of checking, downloading "stable-diffusion-webui-wd14-tagger" will result in the above error.

**Comment by vladmandic** [comment]
There was ws this exact issue earlier today and ive closed it. It's a bug in extension I don't want to accommodate for. It tries to read option that doesn't exist for months.

**Comment by ude6** [comment]
Try the solution from here: https://arca.live/b/aiart/74746694?category=%EC%8B%A4%ED%97%98%EC%A0%95%EB%B3%B4

**Comment by GiusTex** [comment]
If anyone is interested I made a [repo](https://github.com/GiusTex/vladmandic-WD14-Tagger) with instructions and files on how to use wd14-tagger on vladmandic. The lora files work, and it's easy to use. It's not perfect since for now you have to change tagger model manually, if you don't like the default one (anyway all instructions are in my repo)
