### ISSUE TITLE
[Feature]: download model 

### ISSUE THREAD

**Issue by alphaleadership** [vladmandic/automatic#3551]
### Feature description

add the download of model requested automaticaly

**Comment by vladmandic** [comment]
which model? where? if you're requesting a feature, be more verbose and descriptive.

**Comment by alphaleadership** [comment]
in the install process install all the basic model to start dinamicly the model

**Comment by vladmandic** [comment]
automatically downloading a model at the end of install is not desired.
but auto-download from ui already exists, just click on networks -> models -> reference and any of the reference models can be auto-downloaded on first use - there is over 50 different models!

**Comment by alphaleadership** [comment]
ok
