### ISSUE TITLE
[Issue]: LoRA error `dictionary update sequence element #0 has length 1; 2 is required`

### ISSUE THREAD

**Issue by IowaSovereign** [vladmandic/automatic#3554]
### Issue Description

Downloaded lora does not appear in the UI and cannot be loaded, giving the following error: 
`ERROR    Networks: type=lora file="Illustrious NSFW/Illustrious - BLE V0.1" dictionary update sequence element #0 has length 1; 2 is required`

All the LoRA's in the collection linked below cause the error (NSFW warning):
https://civitai.com/models/825880?modelVersionId=925918

### Version Platform Description

Windows 11 24H2, GTX 1080Ti 11Gb
Microsoft Edge browser

### Relevant log output

`ERROR    Networks: type=lora file="Illustrious NSFW/Illustrious - BLE V0.1" dictionary update sequence element #0 has length 1; 2 is required`

### Backend

Diffusers

### UI

ModernUI

### Branch

Dev

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
