### ISSUE TITLE
[Issue]: SD3.5 too slow with AMD and zluda

### ISSUE THREAD

**Issue by conkydong** [vladmandic/automatic#3555]
### Issue Description

Installed everything according to the tutorial/Wiki, then downloaded SD3.5 Large via SD.Next (supplied a huggingface token) and clicked on generate to let it compile. There was just a quick info about compiling, it then generated the picture. Took about 36 minutes. 
Second image still takes as long - about 105s/it to 117s/it.
Could I have done anything wrong?

### Version Platform Description

CPU: AMD Ryzen 9 5900x)
GPU: AMD RX 6800 XT
RAM: 64GB 
Windows 10 Pro N (22H2)
Google Chrome

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 3

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
a) you have provided no logs - what can anyone say without that
b) this is a question, not an issue. post in discussions or better yet, reach out on discord.
