### ISSUE TITLE
[Issue]: using rocm window but still using zluda

### ISSUE THREAD

**Issue by Ugijago** [vladmandic/automatic#3556]
### Issue Description

![image](https://github.com/user-attachments/assets/b532d0be-270f-4326-8cd5-113b9681b451)

### Version Platform Description

window 23h2 opera,edge,etc

### Relevant log output

```shell
i dunnow what this is
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
there is no pure rocm on windows. if you have a question, open a discussion item or ask on discord. this is not an issue.
