### ISSUE TITLE
[Issue]:  Python version incompatible: 3.12.7 required 3.12.3 or lower

### ISSUE THREAD

**Issue by Smo-RBR** [vladmandic/automatic#3561]
### Issue Description

We all know that python is a incompatible bitch even in minor releases, so, please keep the requirements actual.

09:56:35-942893 INFO     Starting SD.Next
09:56:35-949875 INFO     Logger: file="C:\Users\Smo\Desktop\SD-Next-Gui\sdnext.log" level=DEBUG size=65 mode=create
09:56:35-951870 INFO     Python: version=3.12.7 platform=Windows
                         bin="C:\Users\Smo\Desktop\SD-Next-Gui\venv\Scripts\python.exe"
                         venv="C:\Users\Smo\Desktop\SD-Next-Gui\venv"
09:56:35-952867 ERROR    Python version incompatible: 3.12.7 required 3.12.3 or lower

### Version Platform Description

Python: version=3.12.7 platform=Windows

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by brknsoul** [comment]
When it comes to Python and python modules, newer is most definitely not better.

This isn't an issue, install a compatible version of Python. I've found the most compatible versions are 3.10.6 to 3.10.11. This ensures that some extensions should work as well.

**Comment by vladmandic** [comment]
what is the actual ask in this issue?
sdnext clearly states what are the requirements.

**Comment by inrush-overload** [comment]
> When it comes to Python and python modules, newer is most definitely not better.
> 
> This isn't an issue, install a compatible version of Python. I've found the most compatible versions are 3.10.6 to 3.10.11. This ensures that some extensions should work as well.

weirdly my system is reporting version 3.8 is installed but I get the same error as OP :\

**Comment by brknsoul** [comment]
when you do `python --version` ensure you're using the virtual environment. (`venv\scripts\activate`)

**Comment by inrush-overload** [comment]
> when you do `python --version` ensure you're using the virtual environment. (`venv\scripts\activate`)
> 
> The guide (Getting Started > Installation instructions > [Install Python and Git](https://github.com/vladmandic/automatic/wiki/Installation#install-python-and-git)) links to Python 3.10.11. So installing 3.12.7 is on you.
> 
> Remove 3.12.7, install 3.10 or 3.11, delete venv and run `webui.bat` again.

It appears that python 3.8.5 was installed (as well as 3.10.11 and a couple others), BUT for some reason the venv pointed at 3.12.7 that was packaged with microconda instead of a more useful version
