### ISSUE TITLE
[Issue]: Downloading the extension "stable-diffusion-webui-wd14-tagger" will result in the following error.

### ISSUE THREAD

**Issue by wkdtjs** [vladmandic/automatic#357]
### Issue Description

Downloading "stable-diffusion-webui-wd14-tagger" will cause an error in the roller as shown below.

![화면 캡처 2023-04-22 071437](https://user-images.githubusercontent.com/65364921/233749529-11f618e2-773a-4ce6-98cd-de61a81df7d2.png)

08:48:24-264180 INFO     Python 3.10.6 on Windows
08:48:24-305615 INFO     No changes detected: quick launch active
08:48:24-306612 INFO     Setting environment tuning
08:48:24-307609 INFO     Server arguments: []
Creating folder: outputs/text
Creating folder: outputs/image
Creating folder: outputs/extras
Creating folder: outputs/grids
Creating folder: outputs/save
Available models: models\Stable-diffusion 1
Module load: D:\새 폴더\extensions-builtin\a1111-sd-webui-lycoris\scripts\lycoris_script.py: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\새 폴더\modules\script_loading.py:10 in load_module                                                               │
│                                                                                                                      │
│    9 │   try:                                                                                                        │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                                  │
│   11 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│                                                                                                                      │
│                                               ... 3 frames hidden ...                                                │
│                                                                                                                      │
│ D:\새 폴더\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora.py:382 in <module>           │
│                                                                                                                      │
│   381                                                                                                                │
│ ❱ 382 list_available_loras()                                                                                         │
│   383                                                                                                                │
│                                                                                                                      │
│ D:\새 폴더\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora.py:363 in                    │
│ list_available_loras                                                                                                 │
│                                                                                                                      │
│   362 │                                                                                                              │
│ ❱ 363 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)                                                       │
│   364                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'lora_dir'
Module load: D:\새 폴더\extensions-builtin\Lora\scripts\lora_script.py: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\새 폴더\modules\script_loading.py:10 in load_module                                                               │
│                                                                                                                      │
│    9 │   try:                                                                                                        │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                                  │
│   11 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│                                                                                                                      │
│                                               ... 2 frames hidden ...                                                │
│                                                                                                                      │
│ D:\새 폴더\extensions-builtin\Lora\lora.py:382 in <module>                                                           │
│                                                                                                                      │
│   381                                                                                                                │
│ ❱ 382 list_available_loras()                                                                                         │
│   383                                                                                                                │
│                                                                                                                      │
│ D:\새 폴더\extensions-builtin\Lora\lora.py:363 in list_available_loras                                               │
│                                                                                                                      │
│   362 │                                                                                                              │
│ ❱ 363 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)                                                       │
│   364                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'lora_dir'
Loading theme: gradio/default
executing callback: D:\새 폴더\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py ui_tabs_callback:
AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\새 폴더\modules\script_callbacks.py:122 in ui_tabs_callback                                                       │
│                                                                                                                      │
│   121 │   │   try:                                                                                                   │
│ ❱ 122 │   │   │   res += c.callback() or []                                                                          │
│   123 │   │   except Exception as e:                                                                                 │
│                                                                                                                      │
│ D:\새 폴더\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py:329 in on_ui_tabs                              │
│                                                                                                                      │
│   328 │   │   │   │   │   with gr.Row(variant='compact'):                                                            │
│ ❱ 329 │   │   │   │   │   │   interrogator_names = utils.refresh_interrogators()                                     │
│   330 │   │   │   │   │   │   interrogator = utils.preset.component(                                                 │
│                                                                                                                      │
│ D:\새 폴더\extensions\stable-diffusion-webui-wd14-tagger\tagger\utils.py:70 in refresh_interrogators                 │
│                                                                                                                      │
│   69 │                                                                                                               │
│ ❱ 70 │   for path in os.scandir(shared.cmd_opts.deepdanbooru_projects_path):                                         │
│   71 │   │   if not path.is_dir():                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'

### Version Platform Description

Latest version + windows 11

**Comment by vladmandic** [comment]
Duplicate, please search issues before creating a new one.

**Comment by GiusTex** [comment]
If anyone is interested I made a [repo](https://github.com/GiusTex/vladmandic-WD14-Tagger) with instructions and files on how to use wd14-tagger on vladmandic. The lora files work (there were problems in other issues) and it's easy to use. It's not perfect since for now you have to change tagger model manually, if you don't like the default one (anyway all instructions are in my repo)
