### ISSUE TITLE
[Issue] Errors installing sub-repositories on Windows

### ISSUE THREAD

**Issue by ZeroCool22** [vladmandic/automatic#358]
### Issue Description

After cloning the repo and executing the **webui.bat**:

`Creating venv in directory C:\Users\ZeroCool22\Desktop\automatic\venv using python "C:\Users\ZeroCool22\AppData\Local\Programs\Python\Python310\python.exe"
venv "C:\Users\ZeroCool22\Desktop\automatic\venv\Scripts\Python.exe"
Module load: extensions-builtin\LDSR\preload.py: AssertionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\ZeroCool22\Desktop\automatic\modules\script_loading.py:10 in load_module                                   │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\extensions-builtin\LDSR\preload.py:2 in <module>                              │
│                                                                                                                     │
│   1 import os                                                                                                       │
│ > 2 from modules import paths                                                                                       │
│   3                                                                                                                 │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\modules\paths.py:26 in <module>                                               │
│                                                                                                                     │
│   25                                                                                                                │
│ > 26 assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_                       │
│   27                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AssertionError: Couldn't find Stable Diffusion in any of:
['C:\\Users\\ZeroCool22\\Desktop\\automatic\\repositories/stable-diffusion-stability-ai', '.',
'C:\\Users\\ZeroCool22\\Desktop']
Module load: extensions-builtin\Lora\preload.py: AssertionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\ZeroCool22\Desktop\automatic\modules\script_loading.py:10 in load_module                                   │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\extensions-builtin\Lora\preload.py:2 in <module>                              │
│                                                                                                                     │
│   1 import os                                                                                                       │
│ > 2 from modules import paths                                                                                       │
│   3                                                                                                                 │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\modules\paths.py:26 in <module>                                               │
│                                                                                                                     │
│   25                                                                                                                │
│ > 26 assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_                       │
│   27                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AssertionError: Couldn't find Stable Diffusion in any of:
['C:\\Users\\ZeroCool22\\Desktop\\automatic\\repositories/stable-diffusion-stability-ai', '.',
'C:\\Users\\ZeroCool22\\Desktop']
Module load: extensions-builtin\ScuNET\preload.py: AssertionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\ZeroCool22\Desktop\automatic\modules\script_loading.py:10 in load_module                                   │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\extensions-builtin\ScuNET\preload.py:2 in <module>                            │
│                                                                                                                     │
│   1 import os                                                                                                       │
│ > 2 from modules import paths                                                                                       │
│   3                                                                                                                 │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\modules\paths.py:26 in <module>                                               │
│                                                                                                                     │
│   25                                                                                                                │
│ > 26 assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_                       │
│   27                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AssertionError: Couldn't find Stable Diffusion in any of:
['C:\\Users\\ZeroCool22\\Desktop\\automatic\\repositories/stable-diffusion-stability-ai', '.',
'C:\\Users\\ZeroCool22\\Desktop']
Module load: extensions-builtin\SwinIR\preload.py: AssertionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\ZeroCool22\Desktop\automatic\modules\script_loading.py:10 in load_module                                   │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\extensions-builtin\SwinIR\preload.py:2 in <module>                            │
│                                                                                                                     │
│   1 import os                                                                                                       │
│ > 2 from modules import paths                                                                                       │
│   3                                                                                                                 │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\modules\paths.py:26 in <module>                                               │
│                                                                                                                     │
│   25                                                                                                                │
│ > 26 assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_                       │
│   27                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AssertionError: Couldn't find Stable Diffusion in any of:
['C:\\Users\\ZeroCool22\\Desktop\\automatic\\repositories/stable-diffusion-stability-ai', '.',
'C:\\Users\\ZeroCool22\\Desktop']
19:52:38-585151 INFO     Python 3.10.6 on Windows
19:52:38-635048 INFO     Running setup
19:52:38-684823 INFO     Version: c205251c Fri Apr 21 16:15:31 2023 -0400
19:52:38-725084 INFO     nVidia toolkit detected
19:52:38-725084 INFO     Installing package: torch torchaudio torchvision --index-url
                         https://download.pytorch.org/whl/cu118`

`Available models: models\Stable-diffusion 0
Download the default model? (y/N) y
Downloading: "https://huggingface.co/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.safetensors" to C:\Users\ZeroCool22\Desktop\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors

100.0%
Module load: C:\Users\ZeroCool22\Desktop\automatic\extensions-builtin\a1111-sd-webui-lycoris\scripts\lycoris_script.py:
AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\ZeroCool22\Desktop\automatic\modules\script_loading.py:10 in load_module                                   │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 3 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora. │
│ py:382 in <module>                                                                                                  │
│                                                                                                                     │
│   381                                                                                                               │
│ > 382 list_available_loras()                                                                                        │
│   383                                                                                                               │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora. │
│ py:363 in list_available_loras                                                                                      │
│                                                                                                                     │
│   362 │                                                                                                             │
│ > 363 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)                                                      │
│   364                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Namespace' object has no attribute 'lora_dir'
Module load: C:\Users\ZeroCool22\Desktop\automatic\extensions-builtin\Lora\scripts\lora_script.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\ZeroCool22\Desktop\automatic\modules\script_loading.py:10 in load_module                                   │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\extensions-builtin\Lora\lora.py:382 in <module>                               │
│                                                                                                                     │
│   381                                                                                                               │
│ > 382 list_available_loras()                                                                                        │
│   383                                                                                                               │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\extensions-builtin\Lora\lora.py:363 in list_available_loras                   │
│                                                                                                                     │
│   362 │                                                                                                             │
│ > 363 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)                                                      │
│   364                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Namespace' object has no attribute 'lora_dir'
Module load:
C:\Users\ZeroCool22\Desktop\automatic\extensions-builtin\stable-diffusion-webui-rembg\scripts\postprocessing_rembg.py:
SystemError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\Users\ZeroCool22\Desktop\automatic\modules\script_loading.py:10 in load_module                                   │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 8 frames hidden ...                                               │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\venv\lib\site-packages\numba\np\ufunc\__init__.py:3 in <module>               │
│                                                                                                                     │
│    2                                                                                                                │
│ >  3 from numba.np.ufunc.decorators import Vectorize, GUVectorize, vectorize, guvectorize                           │
│    4 from numba.np.ufunc._internal import PyUFunc_None, PyUFunc_Zero, PyUFunc_One                                   │
│                                                                                                                     │
│ C:\Users\ZeroCool22\Desktop\automatic\venv\lib\site-packages\numba\np\ufunc\decorators.py:3 in <module>             │
│                                                                                                                     │
│     2                                                                                                               │
│ >   3 from numba.np.ufunc import _internal                                                                          │
│     4 from numba.np.ufunc.parallel import ParallelUFuncBuilder, ParallelGUFuncBuilder                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
SystemError: initialization of _internal failed without raising an exception
Loading theme: black-orange
Image Browser: Creating database
Image Browser: Database created
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Checkpoint model.ckpt not found; loading fallback v1-5-pruned-emaonly.safetensors
Loading weights: C:\Users\ZeroCool22\Desktop\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors -- 0… -…
                                                                                                                  GB
Creating model from config: C:\Users\ZeroCool22\Desktop\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Calculating sha256: C:\Users\ZeroCool22\Desktop\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors6ce0161689b3853acaa03779ec93eafe75a02f4ced659bee03f50797806fa2fa
Applying scaled dot product cross attention optimization
Embeddings loaded:  (0)
Model loaded in 7.0s (load=0.3s create=0.3s hash=3.1s apply=0.8s vae=0.7s move=0.8s embeddings=0.9s)
Startup time: 950.1s (torch=5.9s gradio=1.6s libraries=2.1s models=928.2s codeformer=0.2s scripts=2.2s ui=2.6s
start=0.1s scripts app_started_callback=0.1s checkpoint=7.2s)`

Also:

![Screenshot_1](https://user-images.githubusercontent.com/13344308/233746211-cb212f33-e517-410d-856d-b5988ab33de2.png)

But the Start don't shows any error:

![Screenshot_3](https://user-images.githubusercontent.com/13344308/233750238-83807f8d-855f-404b-9a73-571c639a059f.png)

### Version Platform Description

![Screenshot_2](https://user-images.githubusercontent.com/13344308/233748761-eeca4558-3d0b-43f4-9576-20ff9181e68b.png)

**Comment by vladmandic** [comment]
initial setup did not manage to install any of the required sub repositories.
the fact that subsequent starts show no errors is pointless, initial clone is broken.
i suggest to start from fresh clone and report errors printed on console during first run.
also check `setup.log`.

btw, issue title "lots of errors", does not help.

**Comment by AnyKillAtor** [comment]
venv "D:\automatic\venv\Scripts\Python.exe"
Module load: D:\automatic\extensions-builtin\LDSR\preload.py: AssertionError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\script_loading.py:10 in load_module                                                             │
│                                                                                                                      │
│    9 │   try:                                                                                                        │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                                  │
│   11 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│                                                                                                                      │
│                                               ... 1 frames hidden ...                                                │
│                                                                                                                      │
│ D:\automatic\extensions-builtin\LDSR\preload.py:2 in <module>                                                        │
│                                                                                                                      │
│   1 import os                                                                                                        │
│ ❱ 2 from modules import paths                                                                                        │
│   3                                                                                                                  │
│                                                                                                                      │
│ D:\automatic\modules\paths.py:26 in <module>                                                                         │
│                                                                                                                      │
│   25                                                                                                                 │
│ ❱ 26 assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_                        │
│   27                                                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Couldn't find Stable Diffusion in any of: ['D:\\automatic\\repositories/stable-diffusion-stability-ai',
'.', 'D:\\']
Module load: D:\automatic\extensions-builtin\Lora\preload.py: AssertionError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\script_loading.py:10 in load_module                                                             │
│                                                                                                                      │
│    9 │   try:                                                                                                        │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                                  │
│   11 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│                                                                                                                      │
│                                               ... 1 frames hidden ...                                                │
│                                                                                                                      │
│ D:\automatic\extensions-builtin\Lora\preload.py:2 in <module>                                                        │
│                                                                                                                      │
│   1 import os                                                                                                        │
│ ❱ 2 from modules import paths                                                                                        │
│   3                                                                                                                  │
│                                                                                                                      │
│ D:\automatic\modules\paths.py:26 in <module>                                                                         │
│                                                                                                                      │
│   25                                                                                                                 │
│ ❱ 26 assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_                        │
│   27                                                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Couldn't find Stable Diffusion in any of: ['D:\\automatic\\repositories/stable-diffusion-stability-ai',
'.', 'D:\\']
Module load: D:\automatic\extensions-builtin\ScuNET\preload.py: AssertionError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\script_loading.py:10 in load_module                                                             │
│                                                                                                                      │
│    9 │   try:                                                                                                        │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                                  │
│   11 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│                                                                                                                      │
│                                               ... 1 frames hidden ...                                                │
│                                                                                                                      │
│ D:\automatic\extensions-builtin\ScuNET\preload.py:2 in <module>                                                      │
│                                                                                                                      │
│   1 import os                                                                                                        │
│ ❱ 2 from modules import paths                                                                                        │
│   3                                                                                                                  │
│                                                                                                                      │
│ D:\automatic\modules\paths.py:26 in <module>                                                                         │
│                                                                                                                      │
│   25                                                                                                                 │
│ ❱ 26 assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_                        │
│   27                                                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Couldn't find Stable Diffusion in any of: ['D:\\automatic\\repositories/stable-diffusion-stability-ai',
'.', 'D:\\']
Module load: D:\automatic\extensions-builtin\SwinIR\preload.py: AssertionError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\script_loading.py:10 in load_module                                                             │
│                                                                                                                      │
│    9 │   try:                                                                                                        │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                                  │
│   11 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│                                                                                                                      │
│                                               ... 1 frames hidden ...                                                │
│                                                                                                                      │
│ D:\automatic\extensions-builtin\SwinIR\preload.py:2 in <module>                                                      │
│                                                                                                                      │
│   1 import os                                                                                                        │
│ ❱ 2 from modules import paths                                                                                        │
│   3                                                                                                                  │
│                                                                                                                      │
│ D:\automatic\modules\paths.py:26 in <module>                                                                         │
│                                                                                                                      │
│   25                                                                                                                 │
│ ❱ 26 assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_                        │
│   27                                                                                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError: Couldn't find Stable Diffusion in any of: ['D:\\automatic\\repositories/stable-diffusion-stability-ai',
'.', 'D:\\']
14:36:44-996541 INFO     Python 3.10.10 on Windows
14:36:45-091527 INFO     Running setup
14:36:45-145529 INFO     Version: d3fbd798 Sat Apr 22 09:29:41 2023 -0400
14:36:45-198539 INFO     nVidia toolkit detected
14:36:45-200536 INFO     Installing package: torch torchaudio torchvision --index-url
                         https://download.pytorch.org/whl/cu118

**Comment by vladmandic** [comment]
i'm not even sure what am i look at now?
are you saying that `AssertionError: Couldn't find Stable Diffusion in any of: ['D:\automatic\repositories/stable-diffusion-stability-ai',`

happens before even this line is printed? `14:36:44-996541 INFO Python 3.10.10 on Windows`

and the rest is begging of console log, its doing install, so why post update here before it even finished?

**Comment by vladmandic** [comment]
ok, i believe this is now fixed. issue was that some modules were getting loaded even before installer had a chance to complete.
