### ISSUE TITLE
[Issue]: Live Preview enabled significantly slows generation

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#3605]
### Issue Description

I believe this is due to Live Preview slowing things down.

I'll attached the gifs I took;

Live preview display period = 1, method == approximate
![chrome_Tyx3p6RXio](https://github.com/user-attachments/assets/a35a596d-6026-473a-a7d0-1eea8622ee4e)

Live preview display period = 0 (ie: disabled);
![chrome_fm3XBE8ce5](https://github.com/user-attachments/assets/4a04561e-c666-43b6-a873-34eefda2ce71)

The slowdowns seems to coincide with spikes in vram usage (first spike = generation, second spike = detailer);
![image](https://github.com/user-attachments/assets/c8dbcf3d-bfb4-4e1b-b8e7-46f2169d5d47)

### Version Platform Description

```
Python: version=3.10.11 platform=Windows bin="E:\sddev\venv\Scripts\python.exe"
venv="E:\sddev\venv"
Version: app=sd.next updated=2024-11-28 hash=75dd6219 branch=dev
url=https://github.com/vladmandic/automatic/tree/dev ui=dev
Repository latest available 6846f4e5d3e650d2a8dc8460906901086a350d27 2024-11-22T18:01:15Z
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel system=Windows
release=Windows-10-10.0.19045-SP0 python=3.10.11 docker=False
Packages: venv=venv site=['venv', 'venv\\lib\\site-packages']
Args: ['--autolaunch', '--debug', '--uv']
```

### Relevant log output

[Command Prompt - astart.bat.txt](https://github.com/user-attachments/files/17962698/Command.Prompt.-.astart.bat.txt)

### Backend

Diffusers

### UI

Standard

### Branch

Dev

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i understand the issue, but are you saying this is NEW behavior and there was no slowdown previously?

**Comment by brknsoul** [comment]
Just installed master, no slow down.

![chrome_Ocu8HPftsz](https://github.com/user-attachments/assets/79447450-f77a-4801-8635-3d12dfb36a87)

**Comment by vladmandic** [comment]
argh. one of those that i cannot reproduce, likely because there are no slowdowns on high end gpus.

**Comment by brknsoul** [comment]
My GPU is now a 4060Ti 16gb...
But I'll try.

**Comment by vladmandic** [comment]
can you try with the latest dev branch code?

**Comment by vladmandic** [comment]
resolved based on conversation in discord.

**Comment by brknsoul** [comment]
For future searches: The resolution was that I was using CUDAMallocAsync, instead of Native memory allocator.
