### ISSUE TITLE
[Issue]: Cannot generate images (returning full black/empty)

### ISSUE THREAD

**Issue by paulo-coronado** [vladmandic/automatic#361]
### Issue Description

I just fresh installed Vlad and yet, I cannot generate images... tried different models, VAEs, I also tried to set xformers, --no-half, --no-half-vae, re-installing Vlad, but unfortunately nothing makes it work. 😢

Any ideas why this is happening?

![image](https://user-images.githubusercontent.com/25768651/233756355-e6bf7ae9-bed5-47a8-8828-21c177f0d638.png)

### Version Platform Description

- Windows 11
- NVIDIA GeForce GTX 1660 Ti (6GB VRAM)
- Microsoft Edge

**Comment by keny25** [comment]
I have the same issue, started generating images normally but after changing VAE and applying it started to just make black images. The UI also showed that during applying this VAE change others parameters that were not changed by me (user) were also applied.

**Comment by ronmurphy** [comment]
same here, atfirst i thought it was the nsfw filter going crazy .. but nope.  it's all black

**Comment by mannycalavera656** [comment]
My Automatic1111 works, but like always it's incredibly slow.  Vlad generates completely black images. 

An ASUS laptop 
Windows 11
NVIDIA GeForce GTX 1650 (a pitiful 4GB VRAM) 
Google Chrome

**Comment by paulo-coronado** [comment]
To solve this issue, in **Settings**>**CUDA Settings**, I checked **--no-half**, clicked **Apply Settings** and restarted my computer. And, although the images are being generated, I am getting CUDA Out of Memory when the image is about to render.

**Comment by keny25** [comment]
I was able to solve my problem of black inages by changing ldsr_steps, ldsr_cached, SWIN_tile and SWIN_tile_overlap to lower values

**Comment by vladmandic** [comment]
there is a lot of different issues and noise about this problem, i've created a single issue to unify it and posted instructions there.
i'm closing this issue, lets continue in #374.
