### ISSUE TITLE
[Issue]: API error when running on colab

### ISSUE THREAD

**Issue by vorstcavry** [vladmandic/automatic#3613]
### Issue Description

API ERROR when open stable diffusion link, running on colab                        

### Version Platform Description

05:19:22-665209 INFO     Starting SD.Next                                                           
05:19:22-671648 INFO     Logger: file="/content/stable-diffusion-webui-forge/sdnext.log" level=INFO 
                         size=64 mode=append                                                        
05:19:22-673580 INFO     Python: version=3.10.12 platform=Linux bin="/usr/bin/python3" venv="/usr"  
05:19:22-693937 INFO     Version: app=sd.next updated=2024-11-22 hash=6846f4e5 branch=HEAD          
                         url=https://github.com/vladmandic/automatic/tree/HEAD ui=main              
05:19:23-271382 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux release=6.1.85+              
                         python=3.10.12 docker=False                                                
05:19:23-274960 INFO     Args: ['--share', '--no-hashing', '--disable-console-progressbars',        
                         '--lowram', '--listen', '--use-zluda']                                     
05:19:23-286102 INFO     CUDA: nVidia toolkit detected                                              
05:19:23-287072 INFO     Install: package="onnxruntime-gpu" mode=pip                                
05:19:46-190375 INFO     Install: package="triton" mode=pip                                         
05:19:58-096763 INFO     Install: package="onnx" mode=pip                                           
05:20:04-931273 INFO     Install: package="onnxruntime" mode=pip                                    
05:20:08-712580 INFO     Diffusers upgrade: package=diffusers 0.31.0 current=                       
                         target=b5fd6f13f5434d69d919cc8cedf0b11db664cf06                            
05:20:27-054217 INFO     Install: verifying requirements                                            
05:20:27-055768 INFO     Install: package="patch-ng" mode=pip                                       
05:20:34-533697 INFO     Install: package="addict" mode=pip                                         
05:20:37-231871 INFO     Install: package="filetype" mode=pip                                       
05:20:40-375247 INFO     Install: package="inflection" mode=pip                                     
05:20:42-834771 INFO     Install: package="jsonmerge" mode=pip                                      
05:20:45-322086 INFO     Install: package="kornia" mode=pip                                         
05:20:48-819599 INFO     Install: package="lark" mode=pip                                           
05:20:52-329962 INFO     Install: package="omegaconf" mode=pip                                      
05:20:56-539234 INFO     Install: package="optimum" mode=pip                                        
05:21:01-712115 INFO     Install: package="piexif" mode=pip                                         
05:21:06-130679 INFO     Install: package="resize-right" mode=pip                                   
05:21:08-799759 INFO     Install: package="voluptuous" mode=pip                                     
05:21:11-437858 INFO     Install: package="yapf" mode=pip                                           
05:21:14-265058 INFO     Install: package="fasteners" mode=pip                                      
05:21:17-715245 INFO     Install: package="ruff" mode=pip                                           
05:21:22-369201 INFO     Install: package="pylint" mode=pip                                         
05:21:26-615808 INFO     Install: package="invisible-watermark" mode=pip                            
05:21:30-677592 INFO     Install: package="pi-heif" mode=pip                                        
05:21:33-764130 INFO     Install: package="tensordict==0.1.2" mode=pip                              
05:21:36-591741 WARNING  Package: peft installed=0.13.2 required=0.13.1 version mismatch            
05:21:36-593227 INFO     Install: package="peft==0.13.1" mode=pip                                   
05:21:39-572831 WARNING  Package: httpx installed=0.27.2 required=0.24.1 version mismatch           
05:21:39-574324 INFO     Install: package="httpx==0.24.1" mode=pip                                  
05:21:43-573268 INFO     Install: package="compel==2.0.3" mode=pip                                  
05:21:46-339716 INFO     Install: package="torchsde==0.2.6" mode=pip                                
05:21:49-077516 WARNING  Package: tqdm installed=4.66.6 required=4.66.5 version mismatch            
05:21:49-078938 INFO     Install: package="tqdm==4.66.5" mode=pip                                   
05:21:51-935754 INFO     Install: package="opencv-contrib-python-headless==4.9.0.80" mode=pip       
05:21:58-504275 WARNING  Package: einops installed=0.8.0 required=0.4.1 version mismatch            
05:21:58-505652 INFO     Install: package="einops==0.4.1" mode=pip                                  
05:22:01-170399 INFO     Install: package="gradio==3.43.2" mode=pip                                 
05:22:10-421974 WARNING  Package: numexpr installed=2.10.1 required=2.8.8 version mismatch          
05:22:10-423447 INFO     Install: package="numexpr==2.8.8" mode=pip                                 
05:22:13-538834 WARNING  Package: numba installed=0.60.0 required=0.59.1 version mismatch           
05:22:13-540226 INFO     Install: package="numba==0.59.1" mode=pip                                  
05:22:23-668942 WARNING  Package: protobuf installed=4.25.5 required=4.25.3 version mismatch        
05:22:23-670568 INFO     Install: package="protobuf==4.25.3" mode=pip                               
05:22:27-253594 INFO     Install: package="pytorch_lightning==1.9.4" mode=pip                       
05:22:31-768394 WARNING  Package: urllib3 installed=2.2.3 required=1.26.19 version mismatch         
05:22:31-770320 INFO     Install: package="urllib3==1.26.19" mode=pip                               
05:22:35-073302 WARNING  Package: timm installed=1.0.11 required=0.9.16 version mismatch            
05:22:35-074884 INFO     Install: package="timm==0.9.16" mode=pip                                   
05:22:38-830947 WARNING  Package: pydantic installed=2.9.2 required=1.10.15 version mismatch        
05:22:38-832372 INFO     Install: package="pydantic==1.10.15" mode=pip                              
05:22:42-420563 WARNING  Package: pyparsing installed=3.2.0 required=3.1.4 version mismatch         
05:22:42-422074 INFO     Install: package="pyparsing==3.1.4" mode=pip                               
05:22:46-438834 INFO     Install: package="blendmodes" mode=pip                                     
05:22:49-639761 INFO     Install: package="torchdiffeq" mode=pip                                    
05:22:52-454447 INFO     Install: package="dctorch" mode=pip                                        
05:22:55-196758 INFO     Install: package="seam-carving" mode=pip                                   
05:22:58-906133 INFO     Verifying packages                                                         
05:22:58-907376 INFO     Install: package="git+https://github.com/openai/CLIP.git" mode=pip         
05:23:04-410560 INFO     Install: package="open-clip-torch" mode=pip                                
05:23:05-524199 INFO     Startup: standard                                                          
05:23:05-525362 INFO     Verifying submodules                                                       
05:23:43-882635 INFO     Extension installed packages: stable-diffusion-webui-rembg                 
                         ['PyMatting==1.1.13', 'rembg==2.0.60']                                     
05:23:58-150139 INFO     Extension installed packages: sd-civitai-browser-plus ['Send2Trash==1.8.2',
                         'ZipUnicode==1.1.1', 'packaging==23.2']                                    
05:23:58-151694 INFO     Extensions enabled: ['sd-webui-agent-scheduler', 'sd-extension-chainner',  
                         'stable-diffusion-webui-rembg', 'sd-extension-system-info',                
                         'sdnext-modernui', 'Lora', 'sd-webui-aspect-ratio-helper',                 
                         'sd-civitai-browser-plus']                                                 
05:23:58-153140 INFO     Install: verifying requirements                                            
05:23:58-157198 INFO     Command line args: ['--share', '--no-hashing',                             
                         '--disable-console-progressbars', '--lowram', '--listen', '--use-zluda']   
                         no_hashing=True share=True listen=True lowram=True use_zluda=True          
05:24:11-687989 INFO     Torch: torch==2.5.1+cu121 torchvision==0.20.1+cu121                        
05:24:11-696948 INFO     Packages: diffusers==0.32.0.dev0 transformers==4.46.2 accelerate==1.1.1    
                         gradio==3.43.2                                                             
05:24:12-675575 INFO     Device detect: memory=14.8 optimization=none                               
05:24:12-685117 WARNING  Setting validation: unknown=['forge_preset', 'xl_t2i_width',               
                         'xl_t2i_height', 'xl_t2i_cfg', 'xl_t2i_hr_cfg', 'xl_t2i_sampler',          
                         'xl_t2i_scheduler']                                                        
05:24:12-691421 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda                 
                         attention="Scaled-Dot-Product" mode=no_grad                                
05:24:12-704847 INFO     Available Styles: folder="models/styles" items=288 time=0.01               
05:24:13-053123 INFO     Torch parameters: backend=cuda device=cuda config=Auto dtype=torch.bfloat16
                         vae=torch.bfloat16 unet=torch.bfloat16 context=no_grad nohalf=False        
                         nohalfvae=False upscast=False deterministic=False test-fp16=True           
                         test-bf16=True optimization="Scaled-Dot-Product"                           
05:24:13-099126 INFO     Device: device=Tesla T4 n=1 arch=sm_90 capability=(7, 5) cuda=12.1         
                         cudnn=90100 driver=535.104.05                                              
05:24:14-515707 INFO     Create: folder="models/Diffusers"                                          
05:24:14-517036 INFO     Create: folder="models/UNET"                                               
05:24:14-518173 INFO     Create: folder="models/Text-encoder"                                       
05:24:14-519255 INFO     Create: folder="models/embeddings"                                         
05:24:14-520337 INFO     Create: folder="models/hypernetworks"                                      
05:24:14-521553 INFO     Create: folder="models/ONNX/temp"                                          
05:24:14-522619 INFO     Create: folder="outputs/control"                                           
05:24:14-523712 INFO     Create: folder="outputs/init-images"                                       
05:24:14-524792 INFO     Create: folder="outputs/grids"                                             
05:24:14-525815 INFO     Create: folder="outputs/save"                                              
05:24:14-526854 INFO     Create: folder="outputs/video"                                             
05:24:14-527908 INFO     Create: folder="models/yolo"                                               
05:24:14-528925 INFO     Create: folder="models/wildcards"                                          
05:24:14-571920 INFO     Available VAEs: path="models/VAE" items=0                                  
05:24:14-573583 INFO     Available UNets: path="models/UNET" items=0                                
05:24:14-574795 INFO     Available TEs: path="models/Text-encoder" items=0                          
05:24:14-576073 INFO     Disabled extensions: ['sdnext-modernui']                                   
05:24:14-584498 INFO     Available Models: path="models/Stable-diffusion" items=1 time=0.01         
05:24:14-588948 INFO     Install: package="basicsr" mode=pip                                        
05:24:20-930298 INFO     Install: package="gfpgan" mode=pip                                         
05:24:26-273156 INFO     Available Yolo: path="models/yolo" items=6 downloaded=0                    
05:24:26-275144 INFO     Load extensions                                                            
05:24:27-066032 INFO     Available LoRAs: path="models/Lora" items=0 folders=2 time=0.00            
05:24:28-463717 INFO     Extension:                                                                 
                         script='extensions-builtin/sd-webui-agent-scheduler/scripts/task_scheduler.
                         py' Using sqlite file:                                                     
                         extensions-builtin/sd-webui-agent-scheduler/task_scheduler.sqlite3         
05:24:28-620641 INFO     Extension:                                                                 
                         script='extensions/sd-civitai-browser-plus/scripts/civitai_api.py'         
                         [96mCivitAI Browser+[0m: Aria2 RPC started                                 
fatal: No names found, cannot describe anything.
05:24:28-757432 INFO     Upscaler create: folder="models/chaiNNer"                                  
05:24:28-760329 INFO     Upscaler create: folder="models/RealESRGAN"                                
05:24:28-761976 INFO     Available Upscalers: items=53 downloaded=0 user=0 time=0.09 types=['None', 
                         'Lanczos', 'Nearest', 'ChaiNNer', 'ESRGAN', 'RealESRGAN', 'SD', 'LDSR',    
                         'SCUNet', 'AuraSR', 'SwinIR']                                              
05:24:28-772119 INFO     Available Styles: folder="models/styles" items=288 time=0.01               
05:24:28-778961 INFO     UI start                                                                   
05:24:28-780425 ERROR    UI theme invalid: type=Standard theme="Default"                            
                         available=['amethyst-nightfall', 'black-gray', 'black-orange',             
                         'black-teal', 'emerald-paradise', 'invoked', 'light-teal',                 
                         'midnight-barbie', 'orchid-dreams', 'simple-dark', 'simple-light',         
                         'timeless-beige']                                                          
05:24:28-782197 INFO     UI theme: type=Standard name="black-teal"                                  
05:24:28-924899 INFO     Install: package="clean-fid" mode=pip                                      
05:24:33-902789 INFO     Extension list is empty: refresh required                                  
05:24:35-526892 INFO     Local URL: http://localhost:7860/                                          
05:24:35-528382 INFO     Share URL: https://1afa002fb958ab5586.gradio.live/                          
05:24:35-806141 INFO     [AgentScheduler] Task queue is empty                                       
05:24:35-807600 INFO     [AgentScheduler] Registering APIs                                          
05:24:35-980902 INFO     Model metadata saved: file="metadata.json" items=1 time=0.01               
05:24:35-983273 INFO     Selecting first available checkpoint                                       
05:24:35-985823 INFO     Startup time: 37.81 torch=11.42 gradio=1.07 diffusers=0.54 libraries=3.28  
                         samplers=0.06 extensions=2.40 detailer=11.69 upscalers=0.09                
                         ui-networks=0.58 ui-txt2img=3.08 ui-img2img=0.17 ui-control=0.28           
                         ui-extras=0.07 ui-models=0.07 ui-settings=0.61 ui-extensions=0.30          
                         ui-defaults=0.10 launch=1.43 api=0.15 app-started=0.30                     
05:25:13-594447 INFO     MOTD: N/A                                                                  
05:25:41-536819 ERROR    API error: GET: https://1afa002fb958ab5586.gradio.live/file=placeholder    
                         {'error': 'HTTPException', 'code': 404, 'detail': 'File not found:         
                         placeholder.', 'body': '', 'errors': '404: File not found: placeholder.'}

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
what is the impact of this? this does not look like critical error?
can you get browser logs?

btw, this is not a1111, `--disable-console-progressbars` does not exist
also, typically its either `--share` OR `--listen` depending what you need, why do you run both?

**Comment by vorstcavry** [comment]
I forget to remove that

**Comment by vladmandic** [comment]
i'm really not sure what is the ask here - remove the invalid parameters and just run. and pick do you want `--share` or `--listen` - which one is your choice, they do a very different thing.
the `placeholder` log item is not important and you did not tell me what is the actual probelm?

i'm closing as this does not appear to be a product issue, but i'll reopen if new information is provided.
