### ISSUE TITLE
[Issue]: SD1.5 generations consumes ALL VRAM and uses shared memory, completely tanking the performance

### ISSUE THREAD

**Issue by AznamirWoW** [vladmandic/automatic#3616]
### Issue Description

automatic/master SD1.5 generation consumes all VRAM, uses shared memory
![image](https://github.com/user-attachments/assets/3146e713-f140-445d-9726-8c2b858fda38)

automatic/dev  SD1.5 generation consumes all VRAM, uses shared memory, uses all RAM during VAE application.
![image](https://github.com/user-attachments/assets/fd60099e-85f4-491e-82b2-403fd7148b75)

attached logs

[sdnext.dev.log](https://github.com/user-attachments/files/18013987/sdnext.dev.log)
[sdnext.master.log](https://github.com/user-attachments/files/18013988/sdnext.master.log)

### Version Platform Description

window 10, firebox

### Relevant log output

```shell
included as attachments
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
i've switched upcast default value to false on all standard models.
you really should not be running in fp32 precision if possible at all.
