### ISSUE TITLE
[Issue]: Hello. Tell me how to install the theme

### ISSUE THREAD

**Issue by takenava** [vladmandic/automatic#3619]
### Issue Description

Hello. Tell me how to install the gradio default theme?

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
do not create issues with simple questions.
first, read wiki, this is covered.
second, reach out on discord or discussions, not issues.

**Comment by takenava** [comment]
Okay. I apologize. I'd better go back to 1111. The support there is much more loyal. Thank you and good luck in developing.
