### ISSUE TITLE
[Issue]: Ctrl+Delete deletes the current gen

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#3621]
### Issue Description

Ctrl+Delete, when inside a text box should delete the word in front of the cursor, similar to how Ctrl+Backspace delete the word behind the cursor. Instead it functions as a shortcut to the Delete button under the image.

There's no way to disable this shortcut and results in unintended actions when editing a prompt.

### Version Platform Description

```
Python: version=3.10.11 platform=Windows bin="E:\sdmaster\venv\Scripts\python.exe"
venv="E:\sdmaster\venv"
Version: app=sd.next updated=2024-11-22 hash=6846f4e5 branch=master
url=https://github.com/vladmandic/automatic/tree/master ui=main
Repository latest available f79e85efeb5c43a344c9979c9dc5fa4c56a0d8ed 2024-12-05T08:43:49Z
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel system=Windows
release=Windows-10-10.0.19045-SP0 python=3.10.11 docker=False
Packages: venv=venv site=['venv', 'venv\\lib\\site-packages']
```

### Relevant log output

```shell
n/a
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
dev branch is updated, see wiki for new key mappings.
