### ISSUE TITLE
[Issue]: Stable Cascade previewer: Input type (struct c10::Half) and bias type (float) should be the same

### ISSUE THREAD

**Issue by HDembinski** [vladmandic/automatic#3622]
### Issue Description

On running Diffusers\sayakpaul/flux.1-dev-nf4 [b054bc66ae], the preview does not work. It produces the error:

Stable Cascade previewer: Input type (struct c10::Half) and bias type (float) should be the same

### Version Platform Description

Version: app=sd.next updated=2024-12-05 hash=f79e85ef branch=master
Platform: Windows 11
Python: 3.11

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
this is now fixed in dev branch, but note that only valid preview method for flux is taesd.

also, for future - issue template does explicitly ask for log - and its very rarely that single line error message is sufficient, what's important is what leads to it.

**Comment by HDembinski** [comment]
> also, for future - issue template does explicitly ask for log - and its very rarely that single line error message is sufficient, what's important is what leads to it.

Fair enough, but I am an experienced developer myself, and my judgement was that this is sufficient and more info would just be noise in this case.
