### ISSUE TITLE
[Issue]: out of VRAM and RAM with the new Lora loader (Flux nf4)

### ISSUE THREAD

**Issue by SAC020** [vladmandic/automatic#3624]
### Issue Description

Out of CUDA VRAM and system RAM with the new Lora loader (3 Loras). Had no issues before with the previous Lora loading mechanism.

Nvidia 4090, 24GB VRAM, 64GB system RAM

Flux nf4

![image](https://github.com/user-attachments/assets/f0513cc3-1e47-48fb-b340-a0f22f5aecfb)

![image](https://github.com/user-attachments/assets/d4a90295-4a60-4940-8f9e-a5435829c725)

### Version Platform Description

PS C:\ai\automatic> .\webui.bat --debug --medvram
Using VENV: C:\ai\automatic\venv
10:23:29-731386 INFO     Starting SD.Next
10:23:29-734456 INFO     Logger: file="C:\ai\automatic\sdnext.log" level=DEBUG size=65 mode=create
10:23:29-736631 INFO     Python: version=3.11.9 platform=Windows bin="C:\ai\automatic\venv\Scripts\python.exe"
                         venv="C:\ai\automatic\venv"
10:23:30-030244 INFO     Version: app=sd.next updated=2024-12-07 hash=f346cccb branch=dev
                         url=https://github.com/vladmandic/automatic/tree/dev ui=dev
10:23:30-780395 INFO     Repository latest available f79e85efeb5c43a344c9979c9dc5fa4c56a0d8ed 2024-12-05T08:43:49Z
10:23:30-794671 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.26100-SP0 python=3.11.9 docker=False

### Relevant log output

```shell
Apply network: type=LoRA ━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━━━━  62% 0:00:27 0:00:36 networks=3 skip10:26:00-127316 DEBUG    Server: alive=True requests=105 memory=25.17/63.92 status='idle' task='' timestamp=None
                         id='task(ot5lm3g8uoyuf9w)' job=0 jobs=0 total=1 step=0 steps=0 queued=0 uptime=118
                         elapsed=106.45 eta=None progress=0
Apply network: type=LoRA ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━━━━━━━━━  70% 0:00:26 0:00:41 networks=3 skip
10:26:04-848893 ERROR    Activating network: type=lora args:[<modules.extra_networks.ExtraNetworkParams object at
                         0x0000019A8DA2E2D0>, <modules.extra_networks.ExtraNetworkParams object at 0x0000019B07AA8310>,
                         <modules.extra_networks.ExtraNetworkParams object at 0x0000019C9E37A810>]: OutOfMemoryError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\ai\automatic\modules\extra_networks.py:96 in activate                                                             │
│                                                                                                                      │
│    95 │   │   │   try:                                                                                               │
│ ❱  96 │   │   │   │   extra_network.activate(p, extra_network_args, step=step)                                       │
│    97 │   │   │   except Exception as e:                                                                             │
│                                                                                                                      │
│ C:\ai\automatic\modules\lora\extra_networks_lora.py:127 in activate                                                  │
│                                                                                                                      │
│   126 │   │   networks.network_load(names, te_multipliers, unet_multipliers, dyn_dims) # load                        │
│ ❱ 127 │   │   networks.network_activate()                                                                            │
│   128 │   │   if len(networks.loaded_networks) > 0 and step == 0:                                                    │
│                                                                                                                      │
│ C:\ai\automatic\modules\lora\networks.py:545 in network_activate                                                     │
│                                                                                                                      │
│   544 │   │   │   │   weight = weight.to(devices.device) if weight is not None else None                             │
│ ❱ 545 │   │   │   │   backup_size += network_backup_weights(module, weight, network_layer_name, wanted_names)        │
│   546 │   │   │   │   batch_updown, batch_ex_bias = network_calc_weights(module, weight, network_layer_name)         │
│                                                                                                                      │
│ C:\ai\automatic\modules\lora\networks.py:326 in network_backup_weights                                               │
│                                                                                                                      │
│   325 │   │   │   │   │   with devices.inference_context():                                                          │
│ ❱ 326 │   │   │   │   │   │   weights_backup = bnb.functional.dequantize_4bit(weight, quant_state=weight.quant_state │
│   327 │   │   │   │   │   │   self.quant_state = weight.quant_state                                                  │
│                                                                                                                      │
│ C:\ai\automatic\venv\Lib\site-packages\bitsandbytes\functional.py:1375 in dequantize_4bit                            │
│                                                                                                                      │
│   1374 │   if out is None:                                                                                           │
│ ❱ 1375 │   │   out = torch.empty(quant_state.shape, dtype=quant_state.dtype, device=A.device)                        │
│   1376                                                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
OutOfMemoryError: CUDA out of memory. Tried to allocate 108.00 MiB. GPU 0 has a total capacity of 23.99 GiB of which 347.54 MiB is free. Of the allocated memory 21.48 GiB is allocated by PyTorch, and 96.48 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
```

### Backend

Diffusers

### UI

Standard

### Branch

Dev

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by SAC020** [comment]
Trying to activate "Lora low memory mode" results in the following error.

How can I revert to the version before the new Lora loader while it's still being wip?


```
Load network: C:\ai\automatic\models\Lora\cydohd-flux-v9-colab-nonstandard-content-undistilled_000010000.safetensors   …
10:44:01-657208 DEBUG    LoRA name="cydohd-flux-v9-colab-nonstandard-content-undistilled_000010000"
                         type={'ModuleTypeLora'} keys=494
Load network: C:\ai\automatic\models\Lora\h4nging.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/38.4 MB -:--:--
10:44:02-007454 DEBUG    LoRA name="h4nging" type={'ModuleTypeLora'} keys=494
Load network: C:\ai\automatic\models\Lora\sacbf-dalle-flux-v4-colab-style-rural-concise_captions-adam_000007500.safete…
10:44:02-733844 DEBUG    LoRA name="sacbf-dalle-flux-v4-colab-style-rural-concise_captions-adam_000007500"
                         type={'ModuleTypeLora'} keys=494
Apply network: type=LoRA ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━  33% 0:00:07 0:00:03 networks=3 skip
10:44:06-565870 ERROR    Activating network: type=lora args:[<modules.extra_networks.ExtraNetworkParams object at
                         0x0000024426197B90>, <modules.extra_networks.ExtraNetworkParams object at 0x0000024426133450>,
                         <modules.extra_networks.ExtraNetworkParams object at 0x0000024428DEDD10>]: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\ai\automatic\modules\extra_networks.py:96 in activate                                                             │
│                                                                                                                      │
│    95 │   │   │   try:                                                                                               │
│ ❱  96 │   │   │   │   extra_network.activate(p, extra_network_args, step=step)                                       │
│    97 │   │   │   except Exception as e:                                                                             │
│                                                                                                                      │
│ C:\ai\automatic\modules\lora\extra_networks_lora.py:127 in activate                                                  │
│                                                                                                                      │
│   126 │   │   networks.network_load(names, te_multipliers, unet_multipliers, dyn_dims) # load                        │
│ ❱ 127 │   │   networks.network_activate()                                                                            │
│   128 │   │   if len(networks.loaded_networks) > 0 and step == 0:                                                    │
│                                                                                                                      │
│ C:\ai\automatic\modules\lora\networks.py:547 in network_activate                                                     │
│                                                                                                                      │
│   546 │   │   │   │   batch_updown, batch_ex_bias = network_calc_weights(module, weight, network_layer_name)         │
│ ❱ 547 │   │   │   │   weights_device, weights_dtype = network_apply_weights(module, batch_updown, batch_ex_bias, ori │
│   548 │   │   │   │   weights_devices.append(weights_device)                                                         │
│                                                                                                                      │
│ C:\ai\automatic\modules\lora\networks.py:417 in network_apply_weights                                                │
│                                                                                                                      │
│   416 │   │   │   │   updown *= -1                                                                                   │
│ ❱ 417 │   │   │   new_weight = weights_backup.to(devices.device) + updown.to(devices.device)                         │
│   418 │   │   │   if getattr(self, "quant_type", None) in ['nf4', 'fp4'] and bnb is not None:                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The size of tensor a (28311552) must match the size of tensor b (18432) at non-singleton dimension 0
```


Load network: C:\ai\automatic\models\Lora\cydohd-flux-v9-colab-nonstandard-content-undistilled_000010000.safetensors   …
10:44:01-657208 DEBUG    LoRA name="cydohd-flux-v9-colab-nonstandard-content-undistilled_000010000"
                         type={'ModuleTypeLora'} keys=494
Load network: C:\ai\automatic\models\Lora\h4nging.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/38.4 MB -:--:--
10:44:02-007454 DEBUG    LoRA name="h4nging" type={'ModuleTypeLora'} keys=494
Load network: C:\ai\automatic\models\Lora\sacbf-dalle-flux-v4-colab-style-rural-concise_captions-adam_000007500.safete…
10:44:02-733844 DEBUG    LoRA name="sacbf-dalle-flux-v4-colab-style-rural-concise_captions-adam_000007500"
                         type={'ModuleTypeLora'} keys=494
Apply network: type=LoRA ━━━━━━━━━━━━━╺━━━━━━━━━━━━━━━━━━━━━━━━━━  33% 0:00:07 0:00:03 networks=3 skip
10:44:06-565870 ERROR    Activating network: type=lora args:[<modules.extra_networks.ExtraNetworkParams object at
                         0x0000024426197B90>, <modules.extra_networks.ExtraNetworkParams object at 0x0000024426133450>,
                         <modules.extra_networks.ExtraNetworkParams object at 0x0000024428DEDD10>]: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\ai\automatic\modules\extra_networks.py:96 in activate                                                             │
│                                                                                                                      │
│    95 │   │   │   try:                                                                                               │
│ ❱  96 │   │   │   │   extra_network.activate(p, extra_network_args, step=step)                                       │
│    97 │   │   │   except Exception as e:                                                                             │
│                                                                                                                      │
│ C:\ai\automatic\modules\lora\extra_networks_lora.py:127 in activate                                                  │
│                                                                                                                      │
│   126 │   │   networks.network_load(names, te_multipliers, unet_multipliers, dyn_dims) # load                        │
│ ❱ 127 │   │   networks.network_activate()                                                                            │
│   128 │   │   if len(networks.loaded_networks) > 0 and step == 0:                                                    │
│                                                                                                                      │
│ C:\ai\automatic\modules\lora\networks.py:547 in network_activate                                                     │
│                                                                                                                      │
│   546 │   │   │   │   batch_updown, batch_ex_bias = network_calc_weights(module, weight, network_layer_name)         │
│ ❱ 547 │   │   │   │   weights_device, weights_dtype = network_apply_weights(module, batch_updown, batch_ex_bias, ori │
│   548 │   │   │   │   weights_devices.append(weights_device)                                                         │
│                                                                                                                      │
│ C:\ai\automatic\modules\lora\networks.py:417 in network_apply_weights                                                │
│                                                                                                                      │
│   416 │   │   │   │   updown *= -1                                                                                   │
│ ❱ 417 │   │   │   new_weight = weights_backup.to(devices.device) + updown.to(devices.device)                         │
│   418 │   │   │   if getattr(self, "quant_type", None) in ['nf4', 'fp4'] and bnb is not None:                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: The size of tensor a (28311552) must match the size of tensor b (18432) at non-singleton dimension 0

**Comment by SAC020** [comment]
I was able to load the loras with Flux.dev fp16, but it's extremely slow. 3 minutes to load four loras which used to load in seconds before. 

While it might pay off if there are many subsequent generations without switching Loras, but in my case I am doing a lot of xyz with different Lora combos. If it takes 3 minutes just to load each combo, let alone to generate the images, then this feature is unusable from my perspective. I believe the previous Lora loader should remain available as an option.

![image](https://github.com/user-attachments/assets/1becb2af-fff9-4bdf-bddb-18f06a508b1f)

**Comment by Clayd341** [comment]
Same here, it was working perfectly fine, but now with the update it's just crashing when loading the loras...

**Comment by vladmandic** [comment]
new lora loader is still experimental - and that is what dev branch is for. keeping this issue open, but wont provide direct feedback here until lora code is closer to be ready to be merged.
if you want stable, use master, not dev.

**Comment by vladmandic** [comment]
yes, it is

**Comment by vladmandic** [comment]
just pushed a major update to lora loader, i suggest to try it out

**Comment by SAC020** [comment]
> just pushed a major update to lora loader, i suggest to try it out

At first look it seems great, thank you.

- overall generation speed is back to baseline, not sure if it's going to improve overall with later optimizations of the code
- system RAM consumption seems improved **by a lot**
- VRAM consumption is normal

Lora effect seems a bit overblown but I am not sure at this point.

Live preview doesn't work anymore, it doesn't show anything during generation - pls see ss, this is while I am running an xyz (and it is running). Maybe it's something conjunctural. 


![image](https://github.com/user-attachments/assets/054ed22d-993c-426c-8cd3-aa5f736fa4c3)

![Screenshot 2024-12-11 180151](https://github.com/user-attachments/assets/71ebae60-bc8a-4750-842e-7da7b2f31749)

^^ this is very good and stable

**Comment by vladmandic** [comment]
i've noticed live preview sometimes just doesn't trigger. for me it mostly works, but sometimes it just doesn't and then i need to refresh and then it runs again. will need to dig into that, but thats a separate issue.
closing this one for now - if there are other lora related items, post here and i'll reopen.

> system RAM consumption seems improved by a lot

that was one of the major goals.

> Lora effect seems a bit overblown but I am not sure at this point.

math didnt change, it should be the same.
