### ISSUE TITLE
[Issue]: xformer undetected

### ISSUE THREAD

**Issue by bryanray** [vladmandic/automatic#363]
### Issue Description

![image](https://user-images.githubusercontent.com/1768531/233763386-d92a39d3-ca60-47c2-98c1-b393ff4b849f.png)

![image](https://user-images.githubusercontent.com/1768531/233763399-2eb19d03-9a6d-44d1-9ca9-00d9e6614db1.png)

i enable it from setting, without flag this is the only way am i doing it right?

the webui.bat cannot detect nor install new xformer, i have xformer downloaded from sd-webui, it cannot detect it and i delete xformer in site-package folder and restart vlad webui.bat and it does not install new xformer.

without xformer my 6g 3060 laptop cannot render 2048x2048. (which sd-webui can do with xformer.)
it will output error CUDA out of memory.
please help.

**Comment by mart-hill** [comment]
Could you try opening a powershell or cmd in your UI folder, and then execute:

`.\venv\Scripts\activate`

...and then

`python.exe -m pip install --force-reinstall --no-deps --pre xformers==0.0.17`

...then close this window, and re-run the UI?

Seeing as you have Torch 2, this should help. 🙂

**Comment by SGKino** [comment]
My xformers is not working too.
Yet is likely to be caused, due to other issues.
I don't know why, but it just "unload" the xformers automatically.

##venv "C:\Diffusion\automatic\venv\Scripts\Python.exe"
13:56:43-556463 INFO     Python 3.10.6 on Windows
13:56:43-973863 INFO     No changes detected: quick launch active
13:56:43-977012 INFO     Setting environment tuning
13:56:43-978014 INFO     Server arguments: []
Unloading xFormers
Available models: models\Stable-diffusion 2
Loading theme: black-orange
Running on local URL:  http://127.0.0.1:7860##

**Comment by mafen** [comment]
> Could you try opening a powershell or cmd in your UI folder, and then execute:
> 
> `.\venv\Scripts\activate`
> 
> ...and then
> 
> `python.exe -m pip install --force-reinstall --no-deps --pre xformers==0.0.17`
> 
> ...then close this window, and re-run the UI?
> 
> Seeing as you have Torch 2, this should help. 🙂
> 
> If you'd like to generate large images, you might want to activate Tiled VAE from the included in this repo multidiffusion extension, and set its tile to, let's say, 512. This should lower the VRAM requirements.

i am also getting this and tried running it in a venv, but no luck

**Comment by mart-hill** [comment]
I believe that even if you're not able to use xformers, with Torch 2, the **Scale-dot-product** optimization gives practically the same performance, and, if VRAM usage is the issue, Tiled VAE should help - despite having RTX 3090, I'm observing the VRAM usage constantly, out of habit, so I can tell it should be within the reach of a 6GB GPU, especially with activated Tiled VAE with tile of 256 or 512pix. And I'm not using --medvram cmdline option.

**Comment by vladmandic** [comment]
@mafen what does `i am also getting this and tried running it directly in a venv, but no luck` this mean? you executed `pip install ...` and what happened?

@SGKino re: `Unloading xFormers' - you have `xformers` installed, but not selected in UI Settings, so app automatically unloads them - because you didn't choose to use them.

@bryanray did you try to install xformers yourself using instructions from @mart-hill ?

**Comment by SGKino** [comment]
> I believe that even if you're not able to use xformers, with Torch 2, the **Scale-dot-product** optimization gives practically the same performance, and, if VRAM usage is the issue, Tiled VAE should help - despite having RTX 3090, I'm observing the VRAM usage constantly, out of habit, so I can tell it should be within the reach of a 6GB GPU, especially with activated Tiled VAE with tile of 256 or 512pix. And I'm not using --medvram cmdline option.

Thanks for your advice. I changed the settings as you mentioned, and I tried a few test in upscaling, all failed due to the cuda out of memory. I just got a GTX 1060 and it seems that it won't work without applying 0.18 xformers.

**Comment by vladmandic** [comment]
> it seems that it won't work without applying 0.18 xformers.

feel free to install them?
there are several other issues with xformers 0.0.18, so i don't place them in recommended list just yet.

**Comment by mart-hill** [comment]
> python.exe -m pip install --force-reinstall --no-deps --pre xformers==0.0.17

When, for example, you mistype 0.0.17 for something non-existent for xformers in

`python.exe -m pip install --force-reinstall --no-deps --pre xformers==0.0.17`

you'll get all the versions currently existing:

```
ERROR: Could not find a version that satisfies the requirement xformers==0.0.13d (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.16rc424, 0.0.16rc425, 0.0.16, 0.0.17rc481, 0.0.17rc482, 0.0.17, 0.0.18.dev502, 0.0.18.dev503, 0.0.18.dev504, 0.0.18, 0.0.19.dev505, 0.0.19.dev516)
ERROR: No matching distribution found for xformers==0.0.13d
```

I mistyped xformers for non-existent version 0.0.13d. I believe you could test anything starting from 0.0.17rc481 for Torch 2. New adventure!🙂

**Comment by vladmandic** [comment]
given the provided feedback, is there anything else to do in this issue?

**Comment by vladmandic** [comment]
closing as feedback was provided and i don't see anything else that should be done here.
if there are remaining issues, update here and i'll reopen.
