### ISSUE TITLE
[Issue]: xyz logical issue

### ISSUE THREAD

**Issue by fraxyl** [vladmandic/automatic#3635]
### Issue Description

I have the x set up with none and a few lora, then in y I have a bunch of styles, when it selects no lora, none of the styles are being applied when I start generating from xyz.

### Version Platform Description

23:49:25-844246 INFO     Starting SD.Next
23:49:25-850452 INFO     Logger: file="E:\automatic\sdnext.log" level=INFO size=5086275 mode=append
23:49:25-851974 INFO     Python: version=3.10.6 platform=Windows bin="E:\automatic\venv\Scripts\python.exe"
                         venv="E:\automatic\venv"
23:49:26-125944 INFO     Version: app=sd.next updated=2024-12-09 hash=a2f5a39a branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
23:49:26-683021 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.6 docker=False

### Backend

Diffusers

### UI

ModernUI

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
both styles and xyz itself log their operation - please provide logs. any issue that does not provide logs is not a valid issue.

**Comment by fraxyl** [comment]
[sdnext.log](https://github.com/user-attachments/files/18173555/sdnext.log)

Sorry, hope this helps.

**Comment by vladmandic** [comment]
now fixed in dev branch:

![image](https://github.com/user-attachments/assets/01d03fc8-5282-49db-99ed-5486a7d5f1ac)
