### ISSUE TITLE
[Feature] Batch img2img with caption files

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#3644]
### Discussed in https://github.com/vladmandic/automatic/discussions/3643

<div type='discussions-op-text'>

<sup>Originally posted by **SAC020** December 21, 2024</sup>
Hi,

The use case is: I have a bunch of images with associated caption files (like for lora training), and I want to run a batch img2img but instead of having a common prompt for all files in the batch, the prompt for each img2img should be the one from the associated (same filename) caption file.

Is this achievable? If so, how to?

Thanks!</div>

**Comment by vladmandic** [comment]
@SAC020 this is now live in dev branch.
when using image -> batch, it will automatically use captions file if its present, if not it will default to standard prompt.

**Comment by SAC020** [comment]
thank you, that was super-fast. looking forward to using this new feature! thanks
