### ISSUE TITLE
[Issue]: --use flags

### ISSUE THREAD

**Issue by rev3rend** [vladmandic/automatic#3649]
### Issue Description

Hi there. Trying to disable openVINO after the configuration auto-detected that I want it. 

Saying 

./webui.sh --use-openvino=false

(or any other reasonable combination I can think of)

doesn't do anything. 

Any ideas? I'm on Mac silicon and trying to prevent the system from a CPU fallback (which it's doing I think b/c OpenVINO is failing).

### Version Platform Description

Apple M4 Max.

### Relevant log output

```shell
23:23:19-547967 INFO     Starting SD.Next                                       
23:23:19-549295 INFO     Logger:                                                
                         file="/Users/lukedubois/MLstuff/automatic/sdnext.log"  
                         level=INFO size=48941 mode=append                      
23:23:19-549798 INFO     Python: version=3.10.14 platform=Darwin                
                         bin="/Users/lukedubois/MLstuff/automatic/venv/bin/pytho
                         n3" venv="/Users/lukedubois/MLstuff/automatic/venv"    
23:23:19-635157 INFO     Version: app=sd.next updated=2024-12-09 hash=a2f5a39a  
                         branch=master                                          
                         url=https://github.com/vladmandic/automatic/tree/master
                         ui=main                                                
23:23:19-948728 INFO     Platform: arch=arm64 cpu=arm system=Darwin             
                         release=24.1.0 python=3.10.14 docker=False             
23:23:19-951185 INFO     Args: []                                               
23:23:19-968691 INFO     Python: version=3.10.14 platform=Darwin                
                         bin="/Users/lukedubois/MLstuff/automatic/venv/bin/pytho
                         n3" venv="/Users/lukedubois/MLstuff/automatic/venv"    
23:23:19-969673 INFO     OpenVINO: selected                                     
23:23:19-970368 INFO     Install: package="onnxruntime-openvino" mode=pip       
23:23:20-372348 INFO     Install: verifying requirements                        
23:23:20-374464 INFO     Verifying packages                                     
23:23:20-390891 INFO     Extensions: disabled=[]                                
23:23:20-391508 INFO     Extensions: enabled=['sd-extension-chainner',          
                         'sdnext-modernui', 'stable-diffusion-webui-rembg',     
                         'sd-webui-agent-scheduler', 'Lora',                    
                         'sd-extension-system-info'] extensions-builtin         
23:23:20-392268 INFO     Extensions: enabled=[] extensions                      
23:23:20-392668 INFO     Startup: quick launch                                  
23:23:20-393038 INFO     Extensions: disabled=[]                                
23:23:20-393371 INFO     Extensions: enabled=['sd-extension-chainner',          
                         'sdnext-modernui', 'stable-diffusion-webui-rembg',     
                         'sd-webui-agent-scheduler', 'Lora',                    
                         'sd-extension-system-info'] extensions-builtin         
23:23:20-393961 INFO     Extensions: enabled=[] extensions                      
23:23:20-395578 INFO     Command line args: []                                  
23:23:23-088640 INFO     Torch: torch==2.5.1 torchvision==0.20.1                
23:23:23-090089 INFO     Packages: diffusers==0.32.0.dev0 transformers==4.46.2  
                         accelerate==1.1.1 gradio==3.43.2                       
23:23:23-691684 INFO     Engine: backend=Backend.DIFFUSERS compute=mps          
                         device=mps attention="Scaled-Dot-Product" mode=no_grad 
23:23:23-692682 INFO     Torch parameters: backend=mps device=mps config=Auto   
                         dtype=torch.float32 vae=torch.float32                  
                         unet=torch.float32 context=no_grad nohalf=False        
                         nohalfvae=False upscast=True deterministic=False       
                         test-fp16=False test-bf16=False                        
                         optimization="Scaled-Dot-Product"                      
23:23:23-787184 INFO     Device:                                                
23:23:23-828382 INFO     Available VAEs: path="models/VAE" items=0              
23:23:23-828922 INFO     Available UNets: path="models/UNET" items=0            
23:23:23-829362 INFO     Available TEs: path="models/Text-encoder" items=0      
23:23:23-829797 INFO     Disabled extensions: ['sdnext-modernui']               
23:23:23-830885 INFO     Available Models: path="models/Stable-diffusion"       
                         items=3 time=0.00                                      
23:23:23-855410 INFO     Available Yolo: path="models/yolo" items=6 downloaded=0
23:23:23-855921 INFO     Load extensions                                        
23:23:23-953967 INFO     Available LoRAs: path="models/Lora" items=0 folders=2  
                         time=0.00                                              
23:23:24-215857 INFO     Extension:                                             
                         script='extensions-builtin/sd-webui-agent-scheduler/scr
                         ipts/task_scheduler.py' Using sqlite file:             
                         extensions-builtin/sd-webui-agent-scheduler/task_schedu
                         ler.sqlite3                                            
23:23:24-224023 INFO     Available Upscalers: items=53 downloaded=0 user=0      
                         time=0.01 types=['None', 'Lanczos', 'Nearest',         
                         'ChaiNNer', 'LDSR', 'SD', 'AuraSR', 'ESRGAN',          
                         'RealESRGAN', 'SwinIR', 'SCUNet']                      
23:23:24-227502 INFO     Available Styles: folder="models/styles" items=288     
                         time=0.00                                              
23:23:24-228682 INFO     UI start                                               
23:23:24-229226 INFO     UI theme: type=Standard name="black-teal"              
23:23:24-780302 INFO     Extension list is empty: refresh required              
23:23:25-229263 INFO     Local URL: http://127.0.0.1:7860/                      
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
23:23:25-537553 WARNING  OpenVINO: No compatible GPU detected! Using CPU        
23:23:25-586499 INFO     [AgentScheduler] Task queue is empty                   
23:23:25-587026 INFO     [AgentScheduler] Registering APIs                      
23:23:25-759271 INFO     Load model: select="v2-1_512-ema-pruned [df955bdf6b]"  
23:23:25-760096 INFO     Autodetect model: detect="Stable Diffusion 2"          
                         class=StableDiffusionPipeline                          
                         file="/Users/lukedubois/MLstuff/automatic/models/Stable
                         -diffusion/v2-1_512-ema-pruned.safetensors" size=4973MB
Diffusers 175493.89it/s ███████████████ 100% 10/10 00:00 00:00 Fetching 10 files
Diffusers 23.04it/s ████████ 100% 6/6 00:00 00:00 Loading pipeline components...
23:23:26-290536 INFO     Load network: type=embeddings loaded=0 skipped=0       
                         time=0.00                                              
23:23:29-499601 INFO     Load model: time=3.63 load=0.53 move=3.09 native=768   
                         memory={'ram': {'used': 1.03, 'total': 36.0}}          
23:23:29-500625 INFO     Startup time: 9.09 torch=2.02 gradio=0.54              
                         libraries=0.78 extensions=0.36 ui-networks=0.08        
                         ui-txt2img=0.10 ui-img2img=0.06 ui-control=0.10        
                         ui-settings=0.14 ui-extensions=0.37 launch=0.06        
                         app-started=0.48 checkpoint=3.74
```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 2.1

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
run `./webui.sh --reinstall`
`--use-openvino` like any other `--use-xxx` flags install specific flavor or `torch`, you can't "disable" it like you tried.
but you can reinstall torch and just don't specify openvino when using reinstall.

**Comment by rev3rend** [comment]
Thanks! Tried that but it's still doing it (log below, says OpenVINO is "selected"). IIRC I never asked for OpenVINO. It seems to have decided to do it for me.

Mac:automatic lukedubois$ ./webui.sh --reinstall
Activate python venv: /Users/lukedubois/MLstuff/automatic/venv
Launch: venv/bin/python3
23:31:37-996487 INFO     Starting SD.Next                                       
23:31:37-997826 INFO     Logger:                                                
                         file="/Users/lukedubois/MLstuff/automatic/sdnext.log"  
                         level=INFO size=63164 mode=append                      
23:31:37-998302 INFO     Python: version=3.10.14 platform=Darwin                
                         bin="/Users/lukedubois/MLstuff/automatic/venv/bin/pytho
                         n3" venv="/Users/lukedubois/MLstuff/automatic/venv"    
23:31:38-066071 INFO     Version: app=sd.next updated=2024-12-09 hash=a2f5a39a  
                         branch=master                                          
                         url=https://github.com/vladmandic/automatic/tree/master
                         ui=main                                                
23:31:38-386393 INFO     Platform: arch=arm64 cpu=arm system=Darwin             
                         release=24.1.0 python=3.10.14 docker=False             
23:31:38-389212 INFO     Args: ['--reinstall']                                  
23:31:38-404802 INFO     Python: version=3.10.14 platform=Darwin                
                         bin="/Users/lukedubois/MLstuff/automatic/venv/bin/pytho
                         n3" venv="/Users/lukedubois/MLstuff/automatic/venv"    
23:31:38-405749 INFO     OpenVINO: selected                                     
23:31:38-406216 INFO     Install: package="openvino==2024.3.0" mode=pip         
23:31:39-078843 INFO     Install: package="onnxruntime-openvino" mode=pip       
23:31:39-349330 INFO     Install: package="nncf==2.12.0" mode=pip               
23:31:39-975298 INFO     Install: package="torch==2.3.1+cpu                     
                         torchvision==0.18.1+cpu --index-url                    
                         https://download.pytorch.org/whl/cpu" mode=pip         
23:31:40-506094 ERROR    Install: pip: install --upgrade torch==2.3.1+cpu       
                         torchvision==0.18.1+cpu --index-url                    
                         https://download.pytorch.org/whl/cpu                   
23:31:40-554942 INFO     Forcing reinstall of all packages                      
23:31:40-569522 INFO     Install: verifying requirements                        
23:31:40-571248 INFO     Verifying packages                                     
23:31:40-571556 INFO     Install:                                               
                         package="git+https://github.com/openai/CLIP.git"       
                         mode=pip                                               
23:31:42-359563 INFO     Install: package="open-clip-torch" mode=pip            
23:31:42-657776 INFO     Startup: standard                                      
23:31:42-658334 INFO     Verifying submodules                                   
23:31:45-768971 INFO     Extensions enabled: ['sd-extension-chainner',          
                         'sdnext-modernui', 'stable-diffusion-webui-rembg',     
                         'sd-webui-agent-scheduler', 'Lora',                    
                         'sd-extension-system-info']                            
23:31:45-769542 INFO     Install: verifying requirements                        
23:31:45-769936 WARNING  Setup complete with errors: ['pip: torch==2.3.1+cpu    
                         torchvision==0.18.1+cpu --index-url                    
                         https://download.pytorch.org/whl/cpu']                 
23:31:45-770322 WARNING  See log file for more details:                         
                         /Users/lukedubois/MLstuff/automatic/sdnext.log         
23:31:45-771611 INFO     Command line args: ['--reinstall'] reinstall=True      
23:31:47-615647 INFO     Torch: torch==2.5.1 torchvision==0.20.1                
23:31:47-617131 INFO     Packages: diffusers==0.32.0.dev0 transformers==4.46.2  
                         accelerate==1.1.1 gradio==3.43.2                       
23:31:47-932525 INFO     Engine: backend=Backend.DIFFUSERS compute=mps          
                         device=mps attention="Scaled-Dot-Product" mode=no_grad 
23:31:47-933335 INFO     Torch parameters: backend=mps device=mps config=Auto   
                         dtype=torch.float32 vae=torch.float32                  
                         unet=torch.float32 context=no_grad nohalf=False        
                         nohalfvae=False upscast=True deterministic=False       
                         test-fp16=False test-bf16=False                        
                         optimization="Scaled-Dot-Product"                      
23:31:47-990511 INFO     Device:                                                
23:31:48-021218 INFO     Available VAEs: path="models/VAE" items=0              
23:31:48-021715 INFO     Available UNets: path="models/UNET" items=0            
23:31:48-022119 INFO     Available TEs: path="models/Text-encoder" items=0      
23:31:48-022514 INFO     Disabled extensions: ['sdnext-modernui']               
23:31:48-023292 INFO     Available Models: path="models/Stable-diffusion"       
                         items=3 time=0.00                                      
23:31:48-023970 INFO     Install: package="basicsr" mode=pip                    
23:31:48-633901 INFO     Install: package="gfpgan" mode=pip                     
23:31:49-258840 INFO     Available Yolo: path="models/yolo" items=6 downloaded=0
23:31:49-259476 INFO     Load extensions                                        
23:31:49-418428 INFO     Available LoRAs: path="models/Lora" items=0 folders=2  
                         time=0.00                                              
23:31:49-556196 INFO     Extension:                                             
                         script='extensions-builtin/sd-webui-agent-scheduler/scr
                         ipts/task_scheduler.py' Using sqlite file:             
                         extensions-builtin/sd-webui-agent-scheduler/task_schedu
                         ler.sqlite3                                            
23:31:49-561860 INFO     Available Upscalers: items=53 downloaded=0 user=0      
                         time=0.00 types=['None', 'Lanczos', 'Nearest',         
                         'ChaiNNer', 'LDSR', 'SD', 'AuraSR', 'ESRGAN',          
                         'RealESRGAN', 'SwinIR', 'SCUNet']                      
23:31:49-565017 INFO     Available Styles: folder="models/styles" items=288     
                         time=0.00                                              
23:31:49-566143 INFO     UI start                                               
23:31:49-566686 INFO     UI theme: type=Standard name="black-teal"              
23:31:49-615814 INFO     Install: package="clean-fid" mode=pip                  
23:31:50-811622 INFO     Extension list is empty: refresh required              
23:31:51-184965 INFO     Local URL: http://127.0.0.1:7860/                      
INFO:nncf:NNCF initialized successfully. Supported frameworks detected: torch, onnx, openvino
23:31:51-364363 WARNING  OpenVINO: No compatible GPU detected! Using CPU        
23:31:51-525401 INFO     [AgentScheduler] Task queue is empty                   
23:31:51-525918 INFO     [AgentScheduler] Registering APIs                      
23:31:51-580906 INFO     Load model: select="v2-1_512-ema-pruned [df955bdf6b]"  
23:31:51-581734 INFO     Autodetect model: detect="Stable Diffusion 2"          
                         class=StableDiffusionPipeline                          
                         file="/Users/lukedubois/MLstuff/automatic/models/Stable
                         -diffusion/v2-1_512-ema-pruned.safetensors" size=4973MB
Diffusers 161319.38it/s ███████████████ 100% 10/10 00:00 00:00 Fetching 10 files
Diffusers 37.78it/s ████████ 100% 6/6 00:00 00:00 Loading pipeline components...
23:31:51-981919 INFO     Load network: type=embeddings loaded=0 skipped=0       
                         time=0.00                                              
23:31:52-974719 INFO     Load model: time=1.28 load=0.40 move=0.88 native=768   
                         memory={'ram': {'used': 1.04, 'total': 36.0}}          
23:31:52-975863 INFO     Startup time: 7.20 torch=1.38 gradio=0.33              
                         libraries=0.49 extensions=0.30 detailer=1.24           
                         ui-networks=0.08 ui-txt2img=0.69 ui-img2img=0.06       
                         ui-control=0.10 ui-settings=0.24 ui-extensions=0.30    
                         launch=0.06 app-started=0.35 checkpoint=1.39

**Comment by vladmandic** [comment]
openvino should never be auto-selected, it has to be done either using `--use-openvino` or by having env variable `SD_USEOPENVINO`
can you try deleting `venv`?

**Comment by Disty0** [comment]
It was a bug that was fixed a day ago. Should be fixed in master branch too now.
