### ISSUE TITLE
[Feature]: How to bring back tiling (the one with hirez fix and face restore)?

### ISSUE THREAD

**Issue by shawhu** [vladmandic/automatic#365]
### Feature description

I'm using stable diffusion for generating textures which can be used in games.
I need tiling checkbox or the generated texture won't be seamless.

how do I do that?

### Version Platform Description

windows 10

**Comment by vladmandic** [comment]
i though that option was never used and removed it, but you have a valid use case.
unfortunately, that removal was done a while ago, so cant recall exact code - can you point to exact feature in A1111?

**Comment by shawhu** [comment]
yes sure. actually they are 2 of them. one for the txt2img UI and the other one for img2img. I've found the UI elements in the following py file.

[installation folder]/modules/ui.py

line 487 for txt2img

    restore_faces = gr.Checkbox(label='Restore faces', value=False, visible=len(shared.face_restorers) > 1, elem_id="txt2img_restore_faces")
    tiling = gr.Checkbox(label='Tiling', value=False, elem_id="txt2img_tiling")    <-------------here
    enable_hr = gr.Checkbox(label='Hires. fix', value=False, elem_id="txt2img_enable_hr")
    hr_final_resolution = FormHTML(value="", elem_id="txtimg_hr_finalres", label="Upscaled resolution", interactive=False)

and 
line 771 for img2img

    restore_faces = gr.Checkbox(label='Restore faces', value=False, visible=len(shared.face_restorers) > 1, elem_id="img2img_restore_faces")
    tiling = gr.Checkbox(label='Tiling', value=False, elem_id="img2img_tiling")


let me know if need anything else, i'm not an expert on gradio programming, so i don't know if its enough information.

**Comment by shawhu** [comment]
closing the feature request.

**Comment by qsniyg** [comment]
Could this be restored? My use case is a 360 degree panorama, where each side needs to be seamlessly tiled together.

**Comment by vladmandic** [comment]
done. i'll upload new version as soon as outage on github is resolved.
