### ISSUE TITLE
[Issue]: Cant run `webui.sh` with `--api`

### ISSUE THREAD

**Issue by bboyles303** [vladmandic/automatic#3650]
### Issue Description

with a fresh pull on Ubuntu 24.04, any attempt to do the initial install va webui.sh fails (regardless of arguments) with: 

./webui.sh --debug  --use-rocm
Activate python venv: /home/user/automatic/venv
Launch: venv/bin/python3
usage:  [-h] [--backend {original,diffusers}] [--config CONFIG] [--ui-config UI_CONFIG] [--medvram] [--lowvram] [--freeze] [--ckpt CKPT] [--data-dir DATA_DIR] [--models-dir MODELS_DIR] [--no-hashing]
        [--no-metadata] [--disable-queue] [--device-id DEVICE_ID] [--server-name SERVER_NAME] [--tls-keyfile TLS_KEYFILE] [--tls-certfile TLS_CERTFILE] [--tls-selfsign] [--cors-origins CORS_ORIGINS]
        [--cors-regex CORS_REGEX] [--subpath SUBPATH] [--autolaunch] [--auth AUTH] [--auth-file AUTH_FILE] [--api-only] [--allowed-paths ALLOWED_PATHS [ALLOWED_PATHS ...]] [--share] [--insecure]
        [--listen] [--port PORT] [--reset] [--upgrade] [--requirements] [--reinstall] [--optional] [--uv] [--quick] [--skip-requirements] [--skip-extensions] [--skip-git] [--skip-torch] [--skip-all]
        [--skip-env] [--use-directml] [--use-openvino] [--use-ipex] [--use-cuda] [--use-rocm] [--use-zluda] [--use-xformers] [--safe] [--experimental] [--test] [--version] [--ignore] [--log LOG]
        [--debug] [--profile] [--docs] [--api-log]
: error: argument --api: expected one argument

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
where does `--api` param come from? sdnext does not have it for a long time. did you edit the webui.sh or anything like that?

**Comment by brknsoul** [comment]
SD.Next runs with API already enabled. Perhaps you're looking for `--api-only` to supress launching the webui?

vlad: `--api` still exists in `modules\cmd_args.py`

**Comment by vladmandic** [comment]
> --api still exists in modules\cmd_args.py

in *compatibility* section and hidden, basically it means if used it will be ignored instead of complaining. but it had wrong signature, even in compatibility, its expecting something like `--api true` instead of just `--api`

in any case, like you said - `--api` should not be used

**Comment by vladmandic** [comment]
@bboyles303 any updates?

**Comment by vladmandic** [comment]
closing for now since there is no information provided since issue was first created.
once additional information is added here, i'll reopen as needed.
