### ISSUE TITLE
[Issue]: Consistory?

### ISSUE THREAD

**Issue by nuttintoseehere** [vladmandic/automatic#3655]
### Issue Description

This one's probably not a bug per se, maybe rather a problem on my end but can someone point me in the right direction as i can't seem to find where/how to enable Consistory?

Patch notes for 24/12/11 state:
_ConsiStory: Consistent Image Generation
    create consistent anchor image and then generate images that are consistent with anchor
    select in scripts -> consistory_

But none of the script dropdown menus have Consistory, in text/image/control tabs? There is a "consistory" subfolder in the modules folder, indicating it's supposed to show up somewhere - how can i enable this to try it out?

### Version Platform Description

Linux

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by nuttintoseehere** [comment]
Possibly only an Nvidia thing? Looking at consistory_ext.py in scripts folder, it says "make it non-cuda exclusive" but also "forces uses of xformers" which i don't have, on Linux with 7900XTX.

**Comment by vladmandic** [comment]
ah, because of all of the limitations, consistory requires use of `--experimental` command line flag.
i'll remove the need for the flag in dev branch now.
