### ISSUE TITLE
[Issue]: ERROR    Interrogate: 'blip2-flip-t5-xxl

### ISSUE THREAD

**Issue by jp7189** [vladmandic/automatic#3661]
### Issue Description

Process, Interrogate Image, change the caption model to "blip2-flip-t5-xl" or "blip2-flip-t5-xl".  Other models will download on first run.  These just throw this error:
16:03:06-075083 ERROR    Interrogate: 'blip2-flip-t5-xxl'
16:03:15-825644 ERROR    Interrogate: 'blip2-flip-t5-xl'

### Version Platform Description

15:53:17-291179 INFO     Starting SD.Next
15:53:17-291179 INFO     Logger: file="C:\StableDiffusion\SD.Next\sdnext.log" level=INFO size=11971666 mode=append
15:53:17-479175 INFO     Version: app=sd.next updated=2024-11-02 hash=65ddc611 branch=master
                         url=https://github.com/vladmandic/automatic/tree/master ui=main
15:53:17-525977 INFO     Platform: arch=AMD64 cpu=AMD64 Family 25 Model 17 Stepping 0, AuthenticAMD system=Windows
                         release=Windows-10-10.0.22631-SP0 python=3.10.11
15:53:17-525977 INFO     Args: ['--autolaunch', '--device-id=1', '--quick']
15:53:17-525977 INFO     CUDA: nVidia toolkit detected
15:53:17-588312 INFO     Verifying requirements
15:53:17-603838 INFO     Verifying packages
15:53:17-603838 INFO     Startup: quick launch
15:53:17-603838 INFO     Extensions: disabled=[]
15:53:17-603838 INFO     Extensions: enabled=['Lora', 'sd-extension-chainner', 'sd-extension-system-info',
                         'sd-webui-agent-scheduler', 'sdnext-modernui', 'stable-diffusion-webui-rembg']
                         extensions-builtin
15:53:17-603838 INFO     Extensions: enabled=['a1111-sd-webui-tagcomplete', 'sd-dynamic-prompts', 'sd-webui-reactor']
                         extensions
15:53:17-603838 INFO     Command line args: ['--autolaunch', '--device-id=1', '--quick'] device_id=1 autolaunch=True
                         quick=True
15:53:23-647526 INFO     System packages: {'torch': '2.4.1+cu124', 'diffusers': '0.32.0.dev0', 'gradio': '3.43.2',
                         'transformers': '4.46.1', 'accelerate': '1.0.1'}
15:53:24-479014 INFO     Device detect: memory=48.0 optimization=none
15:53:24-479014 INFO     Engine: backend=Backend.DIFFUSERS compute=cuda device=cuda:1 attention="Scaled-Dot-Product"
                         mode=no_grad
15:53:24-822659 INFO     Torch parameters: backend=cuda device=cuda:1 config=Auto dtype=torch.bfloat16
                         vae=torch.bfloat16 unet=torch.bfloat16 context=no_grad nohalf=False nohalfvae=False
                         upscast=False deterministic=False test-fp16=True test-bf16=True
                         optimization="Scaled-Dot-Product"
15:53:25-447685 INFO     Device: device=NVIDIA RTX 6000 Ada Generation n=2 arch=sm_90 capability=(8, 9) cuda=12.4
                         cudnn=90100 driver=528.49
                         528.49

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

Other

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
just fixed in dev branch, will do a master refresh in the next few days.
