### ISSUE TITLE
[Issue]: After 7b7f121a965d304ed20e136bba4b3b0560c1cdd2 images in a batch are all identical (no variation) if hires pass is enabled

### ISSUE THREAD

**Issue by lbeltrame** [vladmandic/automatic#3665]
### Issue Description

As the subject says, the changes introduced in https://github.com/vladmandic/automatic/commit/7b7f121a965d304ed20e136bba4b3b0560c1cdd2 somehow affected the generation during hires pass. In particular, using a non-latent upscaler causes the *first* image of the batch to be passed to the hires pass, rather than the one being generated, thus in the end all the images are identical.

To reproduce (model: https://civitai.com/models/953679?modelVersionId=1067742): 

Prompt

```
1girl, original, (solo:1.1), standing 
```

Negative

```
lowres, (worst quality, bad quality:1.0), bad anatomy, bad hands, fewer digits, extra digits, sketch, signature, watermark, 
```

Parameters: 1024x1024, Upscale 2x, Upscaler RealESRGAN Anime6B+, denoising strength 0.35, seed 12345, batch count 2.

The end result is something like this (screen from the gallery):

![immagine](https://github.com/user-attachments/assets/19666642-4bfc-405f-afd5-a274ccfee7bb)

### Version Platform Description

02:09:01-247405 INFO     Starting SD.Next                                       
02:09:01-250375 INFO     Logger: file="/notebooks/automatic/sdnext.log"         
                         level=INFO size=25985286 mode=append                   
02:09:01-251459 INFO     Python: version=3.10.10 platform=Linux                 
                         bin="/usr/local/bin/python" venv="/usr"                
02:09:01-308309 INFO     Version: app=sd.next updated=2024-12-29 hash=bb87afbc  
                         branch=dev                                             
                         url=https://github.com/vladmandic/automatic/tree/dev   
                         ui=dev     

### Backend

Diffusers

### UI

ModernUI

### Branch

Dev

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed in dev.
