### ISSUE TITLE
[Issue]: Live Preview breaks after a couple of renders

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3666]
### Issue Description

After a few renders, live preview just stops working, output area stays blank and only displays the final image when done.

I tried to reproduce with default settings, but that didn't work, so I reverted to my full usual settings. I also noticed it's doing previews of detailer stuff, not sure if that actually should happen.  

### Version Platform Description

Win 11, WSL-2, bb87afbc

### Relevant log output

```shell
see attachments
```

### Backend

Diffusers

### UI

ModernUI

### Branch

Dev

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Tillerz** [comment]
Last one or two renders did not get a preview anymore. SDLog from server and console.log from browser.

[sdnext.log](https://github.com/user-attachments/files/18272506/sdnext.log)
[console.log](https://github.com/user-attachments/files/18272507/console.log)

**Comment by vladmandic** [comment]
seems it stopped working once preview was requested during upscale operation - thats ok, but it never recovered after that.
just did a minor update, please test.
also, i need sdnext.log and browser console log (f12 in chrome), not command line console ;)

**Comment by Tillerz** [comment]
[127.0.0.1-1735569708690.log](https://github.com/user-attachments/files/18275454/127.0.0.1-1735569708690.log)
[sdnext.log](https://github.com/user-attachments/files/18275455/sdnext.log)

**Comment by vladmandic** [comment]
based on conversation in discord closing for now - if there is reoccurrence, post here and i'll reopen.

**Comment by SAC020** [comment]
I am having a similar issue. Behavior is:

- 1st image is previewed completely, all steps
- 2nd image is previewed a couple of steps, then dissapears
- next images are not previewed at all

Not sure how to generate the console log (I did press F12, then what?). But I see this error in the console, and it relates to the sdnext page. I don't know if it is relevant

[Deprecation] Custom state pseudo classes have been changed from ":--color-var" to ":state(color-var)". See more here: https://github.com/w3c/csswg-drafts/issues/4805

[preview log.txt](https://github.com/user-attachments/files/18279749/preview.log.txt)

I am on dev branch, and using Flux qint8

```
08:50:53-463586 INFO     Python: version=3.11.9 platform=Windows bin="C:\ai\automatic\venv\Scripts\python.exe"
                         venv="C:\ai\automatic\venv"
08:50:53-710776 INFO     Version: app=sd.next updated=2024-12-31 hash=9adf777e branch=dev
                         url=https://github.com/vladmandic/automatic/tree/dev ui=dev
08:50:54-348682 INFO     Repository latest available 451eeab138defd158ec71a1c28cd1f3573aa1ef5 2024-12-24T13:58:24Z
08:50:54-364386 INFO     Platform: arch=AMD64 cpu=Intel64 Family 6 Model 165 Stepping 5, GenuineIntel system=Windows
                         release=Windows-10-10.0.26100-SP0 python=3.11.9 docker=False
```

**Comment by vladmandic** [comment]
@SAC020 log provides no information. if you're on latest dev and still have issues, provide required info:
- set env variables `SD_PREVIEW_DEBUG=true` and `SD_STATE_DEBUG=true`
- full sdnext from startup until when live preview images stop appearing
- full browser console log covering same period

note that preview may still stop working for any particular generated job, fix provided is so it recovers and the next job will again work.

**Comment by SAC020** [comment]
Attaching sdnext.log for a 3-image xyz, 50 steps / image. It shows that:

- previews were generated completely for the first image
- for the second image, they stopped at step 34 (and the preview vanished from the UI)
- there were no previews generated at all for image number 3

[sdnext-log.txt](https://github.com/user-attachments/files/18282508/sdnext-log.txt)

Again, I don't know how to export the console log other than manual entry by entry, but it looks like this:

I tried to export the last 3 entries

[127.0.0.1-1735660456514.log](https://github.com/user-attachments/files/18282529/127.0.0.1-1735660456514.log)
[127.0.0.1-1735660464904.log](https://github.com/user-attachments/files/18282530/127.0.0.1-1735660464904.log)
[127.0.0.1-1735660470218.log](https://github.com/user-attachments/files/18282531/127.0.0.1-1735660470218.log)


![image](https://github.com/user-attachments/assets/00cb6988-e189-4758-b6fe-4ef587eee683)

**Comment by vladmandic** [comment]
see previous comment!

> note that preview may still stop working for any particular generated job, fix provided is so it recovers and the next job will again work.

does preview work for any future generate tasks AFTER xyz has completed?

**Comment by SAC020** [comment]
Yes, the preview works (and breaks again, consistently at the second image in the xyz) after the xyz is completed.

Does this mean there is no issue?

**Comment by vladmandic** [comment]
i'm saying that is a different issue.
yes, we can investigate why it breaks in the first place - this particular issue was to address that preview never recovers.

i'll reopen this so no need to create new issue, but this is NOT considered as critical.

**Comment by SAC020** [comment]
Ok, now I understand your point. Yes, it's probably not the same problem (but maybe apply your original solution at each xyz image generation? idk, just a thought)

Sure, thank you for looking into this when you have the time.

Have a Happy New Year and thanks for all the work put into sdnext!

**Comment by vladmandic** [comment]
@SAC020 i just moved locking code to be per-job, so that might help with your xyz issue - try latest update.
if it doesn't help, i'll need logs as noted above.

**Comment by SAC020** [comment]
Hi,

It's still happening, but seems to be specific to xyz. It does not occur when generating batches, but occurs consistently with xyz, both in text-to-image and in image-to-image.

Attaching 2 log files, one with a batch of 4 images (works fine), the second with a 4-image xyz (breakis during the generation of the second image). I have restarted webui between the two tests. Let me know if it's useful to run a sequence (such as xyz followed by batch, or something similar)

[sdnext - batch.log](https://github.com/user-attachments/files/18284845/sdnext.-.batch.log)

[sdnext - xyz.log](https://github.com/user-attachments/files/18284846/sdnext.-.xyz.log)

3 log entries for warnings or errors in the browser console:

[127.0.0.1-1735720799081.log](https://github.com/user-attachments/files/18284847/127.0.0.1-1735720799081.log)
[127.0.0.1-1735720792744.log](https://github.com/user-attachments/files/18284848/127.0.0.1-1735720792744.log)
[127.0.0.1-1735720805055.log](https://github.com/user-attachments/files/18284849/127.0.0.1-1735720805055.log)

Let me know if you want me to export all 30+ entries which are not marked as errors. I need to export each manually, and I don't believe they are meaningful.

**Comment by vladmandic** [comment]
ah, that might be related to xyzgrid progress calculation - so progress looks like it reached 100% before it actually did and ui stops requesting further previews. i'll push an update shortly.

**Comment by SAC020** [comment]
Ok, looking forward to testing it. I will mention that this is a relatively new behavior (a couple of weeks, maybe?). I am mentioning this so maybe you can correlate with something that was introduced or changed in xyz recently.

Since you mention progress, I will add that one thing I have always missed in xyz was an ETA estimation, this never worked for me and feel it would be useful to have / work.
