### ISSUE TITLE
[Issue]: Corrections are applied to only first image from the batch

### ISSUE THREAD

**Issue by Rinelw** [vladmandic/automatic#3668]
### Issue Description

![image](https://github.com/user-attachments/assets/369c0e8f-5cd4-4126-b28d-43222e7a9e2c)
Corrections are only applied to the first image from the batch.
It happens both with batch size and batch count.

### Version Platform Description

Windows 11, Edge, Current Dev branch (8dd24979).

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusionXL

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by lbeltrame** [comment]
Can confirm.

**Comment by vladmandic** [comment]
fixed. note that the fix changes the values for corrections as previously correction was applied once and then modified its values - but if its modifying its values, then next item in batch would get modified value even if its intended for first image.
