### ISSUE TITLE
[Issue]: List of generators and effective batch size mismatch.

### ISSUE THREAD

**Issue by Rinelw** [vladmandic/automatic#3669]
### Issue Description

Curently when you try to upscale an image with hi-res fix and have something written in the refiner prompt you'll get this error:

ValueError: You have passed a list of generators of length 2, but requested an effective batch size of 1. Make sure the batch size matches the length of the generators.

### Version Platform Description

Windows 11, Python 3.11.11, Edge, dev (8dd24979)

### Backend

Diffusers

### UI

Standard

### Branch

Dev

### Model

StableDiffusion XL

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
fixed.
