### ISSUE TITLE
'Namespace' object has no attribute 'lora_dir'

### ISSUE THREAD

**Issue by AI-Casanova** [vladmandic/automatic#367]
### Issue Description

I tracked down the following error (which repeated for LyCORIS) to this https://github.com/vladmandic/automatic/blob/c205251c65a87e8c55220e245f40b4a038e100ed/modules/cmd_args.py#L71-L74

If I remove the if statements, Lora and LyCORIS work correctly. 

`Module load: 
/content/gdrive/MyDrive/vladmandic/sd/automatic/extensions-builtin/a1111-sd-webu
i-lycoris/scripts/lycoris_script.py: AttributeError
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /content/gdrive/MyDrive/vladmandic/sd/automatic/modules/script_loading.py:10 │
│ in load_module                                                               │
│                                                                              │
│    9 │   try:                                                                │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                          │
│   11 │   except Exception as e:                                              │
│ in exec_module:850                                                           │
│                                                                              │
│                           ... 3 frames hidden ...                            │
│                                                                              │
│ /content/gdrive/MyDrive/vladmandic/sd/automatic/extensions-builtin/a1111-sd- │
│ webui-lycoris/../../extensions-builtin/Lora/lora.py:382 in <module>          │
│                                                                              │
│   381                                                                        │
│ ❱ 382 list_available_loras()                                                 │
│   383                                                                        │
│                                                                              │
│ /content/gdrive/MyDrive/vladmandic/sd/automatic/extensions-builtin/a1111-sd- │
│ webui-lycoris/../../extensions-builtin/Lora/lora.py:363 in                   │
│ list_available_loras                                                         │
│                                                                              │
│   362 │                                                                      │
│ ❱ 363 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)               │
│   364                                                                        │
╰──────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'lora_dir'`

### Version Platform Description

Google Colab
Python 3.9.16 on Linux
Version: c205251c Fri Apr 21 16:15:31 2023 -0400

**Comment by Averytingwong** [comment]
Same issue, trying to use any lora gives me this error.

**Comment by CKwasd** [comment]
what extension have you installed?

**Comment by AI-Casanova** [comment]
> what extension have you installed?

System extensions only here.

**Comment by vladmandic** [comment]
i patched something else yesterday that changed order or appending cmdflags so this broke. fixed.

**Comment by ahakagei** [comment]
This error comes up after the update:


Available models: E:\Stabilized-Diffusion automatic1111\automatic\automatic\models\Stable-diffusion 62
Module load: E:\Stabilized-Diffusion
automatic1111\automatic\automatic\extensions-builtin\a1111-sd-webui-lycoris\scripts\lycoris_script.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ E:\Stabilized-Diffusion automatic1111\automatic\automatic\modules\script_loading.py:10 in load_module               │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 3 frames hidden ...                                               │
│                                                                                                                     │
│ E:\Stabilized-Diffusion                                                                                             │
│ automatic1111\automatic\automatic\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora.py:3 │
│ 82 in <module>                                                                                                      │
│                                                                                                                     │
│   381                                                                                                               │
│ > 382 list_available_loras()                                                                                        │
│   383                                                                                                               │
│                                                                                                                     │
│ E:\Stabilized-Diffusion                                                                                             │
│ automatic1111\automatic\automatic\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora.py:3 │
│ 63 in list_available_loras                                                                                          │
│                                                                                                                     │
│   362 │                                                                                                             │
│ > 363 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)                                                      │
│   364                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Namespace' object has no attribute 'lora_dir'
Module load: E:\Stabilized-Diffusion automatic1111\automatic\automatic\extensions-builtin\Lora\scripts\lora_script.py:
AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ E:\Stabilized-Diffusion automatic1111\automatic\automatic\modules\script_loading.py:10 in load_module               │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 2 frames hidden ...                                               │
│                                                                                                                     │
│ E:\Stabilized-Diffusion automatic1111\automatic\automatic\extensions-builtin\Lora\lora.py:382 in <module>           │
│                                                                                                                     │
│   381                                                                                                               │
│ > 382 list_available_loras()                                                                                        │
│   383                                                                                                               │
│                                                                                                                     │
│ E:\Stabilized-Diffusion automatic1111\automatic\automatic\extensions-builtin\Lora\lora.py:363 in                    │
│ list_available_loras                                                                                                │
│                                                                                                                     │
│   362 │                                                                                                             │
│ > 363 │   os.makedirs(shared.cmd_opts.lora_dir, exist_ok=True)                                                      │
│   364                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Namespace' object has no attribute 'lora_dir'

**Comment by AI-Casanova** [comment]
Perhaps I was unclear in my initial post. 

The if statements are the problem, because they do not trigger properly, `args.lora_dir = opts.lora_dir` is necessary to prevent this error, my apologies.

**Comment by vladmandic** [comment]
found the error, it was a chicken-or-the-egg issue, some extensions try to register cmd flags, but that cannot be done if setup never completed to start with. fixed.

**Comment by Averytingwong** [comment]
Did a pull, still getting this issue, any advice?

**Comment by vladmandic** [comment]
I've heard multiple issues with thar extension, but nobody created actual issue with proper logs that I can take a look at and track.

**Comment by bbecausereasonss** [comment]
> Still getting the error after pull:
> 
> Loading weights: models\Lora\char\aasAstolfoLora_aaAstolfoV4.safetensors ------------------------- 0.0/151.1 MB -:--:-- gradio call: AttributeError ┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐ │ C:\automatic\modules\call_queue.py:58 in f │ │ │ │ 57 │ │ │ │ pr.enable() │ │ > 58 │ │ │ res = list(func(*args, **kwargs)) │ │ 59 │ │ │ if shared.cmd_opts.profile: │ │ │ │ C:\automatic\modules\call_queue.py:38 in f │ │ │ │ 37 │ │ │ try: │ │ > 38 │ │ │ │ res = func(*args, **kwargs) │ │ 39 │ │ │ finally: │ │ │ │ ... 22 frames hidden ... │ │ │ │ C:\automatic\extensions\stable-diffusion-webui-composable-lora\composable_lora.py:59 in lora_forward │ │ │ │ 58 │ │ │ │ > 59 │ │ if shared.opts.lora_apply_to_outputs and res.shape == input.shape: │ │ 60 │ │ │ patch = module.up(module.down(res)) │ │ │ │ C:\automatic\modules\shared.py:544 in **getattr** │ │ │ │ 543 │ │ │ │ > 544 │ │ return super(Options, self).**getattribute**(item) │ │ 545 │ └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘ AttributeError: 'Options' object has no attribute 'lora_apply_to_outputs'
> 
> -edit: I figured it out, it was the extension.

Which extension?

**Comment by Averytingwong** [comment]
> > Still getting the error after pull:
> > Loading weights: models\Lora\char\aasAstolfoLora_aaAstolfoV4.safetensors ------------------------- 0.0/151.1 MB -:--:-- gradio call: AttributeError ┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐ │ C:\automatic\modules\call_queue.py:58 in f │ │ │ │ 57 │ │ │ │ pr.enable() │ │ > 58 │ │ │ res = list(func(*args, **kwargs)) │ │ 59 │ │ │ if shared.cmd_opts.profile: │ │ │ │ C:\automatic\modules\call_queue.py:38 in f │ │ │ │ 37 │ │ │ try: │ │ > 38 │ │ │ │ res = func(*args, **kwargs) │ │ 39 │ │ │ finally: │ │ │ │ ... 22 frames hidden ... │ │ │ │ C:\automatic\extensions\stable-diffusion-webui-composable-lora\composable_lora.py:59 in lora_forward │ │ │ │ 58 │ │ │ │ > 59 │ │ if shared.opts.lora_apply_to_outputs and res.shape == input.shape: │ │ 60 │ │ │ patch = module.up(module.down(res)) │ │ │ │ C:\automatic\modules\shared.py:544 in **getattr** │ │ │ │ 543 │ │ │ │ > 544 │ │ return super(Options, self).**getattribute**(item) │ │ 545 │ └─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘ AttributeError: 'Options' object has no attribute 'lora_apply_to_outputs'
> > -edit: I figured it out, it was the extension.
> 
> Which extension?

Composable Lora

**Comment by vladmandic** [comment]
there are several extensions that check for `lora_apply_to_outputs` param, but that param has been removed a looong time ago, both here and in a1111. only works in a1111 if you have legacy install so the param is still written in config.

but ok, fine, i'll add compatibility dummy flag to keep such extensions happy and it will be a no-op.
