### ISSUE TITLE
[Issue]: LORA applied to render despite being removed from prompt before

### ISSUE THREAD

**Issue by Tillerz** [vladmandic/automatic#3670]
### Issue Description

- generate image, no lora
- add a lora, generate image
- remove lora from prompt, generate -> lora is still being applied

### Version Platform Description

Win11, WSL-2, 73de0997

### Relevant log output

```shell
Log in comment.
```

### Backend

Diffusers

### UI

ModernUI

### Branch

Dev

### Model

StableDiffusion 1.5

### Acknowledgements

- [X] I have read the above and searched for existing issues
- [X] I confirm that this is classified correctly and its not an extension issue

**Comment by Tillerz** [comment]
[sdnext.log](https://github.com/user-attachments/files/18282592/sdnext.log)

**Comment by vladmandic** [comment]
i cant find whats wrong based on the log.
i'll really need some info on how to reproduce reliably to move forward.

**Comment by Tillerz** [comment]
Hm... I am not sure, but what happens if I do not request any loras. With this code, sd_model.loaded_loras stays as it is and the function returns False. What does it do after? Does it still USE the loaded_loras or does the return code False make it NOT use it in the calling code?

```
        if not hasattr(sd_model, 'loaded_loras'):
            sd_model.loaded_loras = {}
        key = f'{",".join(include)}:{",".join(exclude)}'
        loaded = sd_model.loaded_loras.get(key, [])
        shared.log.trace(f'Load network: type=LoRA key="{key}" requested={requested} loaded={loaded}')
        if len(requested) != len(loaded):
            sd_model.loaded_loras[key] = requested
            return True
        for r, l in zip(requested, loaded):
            if r != l:
                sd_model.loaded_loras[key] = requested
                return True
        return False
```

Ok, so when I add this right after the trace, it properly does NOT apply the lora anymore:

```
        if len(requested) == 0:
            sd_model.loaded_loras[key] = requested
            return True
```

Apparently sd_model.loaded_loras[key] never gets changed when requested is empty, it only just returns False here, thus the model still applying the attached lora keys, and not logging anything, cause there is no additional loading being done. That's how I understand it.

Adding this works for me, no idea if it has any sideeffects.

**Comment by vladmandic** [comment]
it has a sideeffect that both active and deactivate are going to unnecessarily run, but since they are going to go over empty list if nothing to do is few miliseconds at worst.
i pushed a change, can you test?

**Comment by Tillerz** [comment]
Works for me, I can switch back and forth and the lora doesn't get stuck.

**Comment by vladmandic** [comment]
i'll do a master refresh as well. if there are other issues, lmk.

**Comment by Tillerz** [comment]
I was already using my own change for like since I found it, and your's just combines that with another block. I do not see why it should break now. Worked the last 2 hours. :P
