### ISSUE TITLE
[Issue]: extension updating changes webui branch

### ISSUE THREAD

**Issue by acorderob** [vladmandic/automatic#377]
### Issue Description

I'm trying to have my own webui branch with some small changes, but when the setup updates the built-in extensions, some of them do not have a .git file/folder and it checks out master for the main webui repo.

I had to add a check for that file in the install_extensions function to keep my branch loaded. Please add that check to master.

### Version Platform Description

WebUI commit: c205251c65a87e8c55220e245f40b4a038e100ed
Windows 10
Chrome

**Comment by vladmandic** [comment]
totally valid, but why not submit a PR?

**Comment by acorderob** [comment]
I have no experience with PRs and publishing to github, and since the change is just one line all the trouble feels unnecessary.

**Comment by vladmandic** [comment]
ok, i've added the check:

```python
def update(folder):
    if not os.path.exists(os.path.join(folder, '.git')):
        return
    ...
```
