### ISSUE TITLE
[Issue]: Install not working 

### ISSUE THREAD

**Issue by MoreColors123** [vladmandic/automatic#378]
### Issue Description

When trying to fresh install by running webui.bat I keep getting the following console output. Other SD-repos are working though (a1111 and the one from anapnoe):

venv "C:\programs\automatic\venv\Scripts\Python.exe"
Module load: C:\programs\automatic\extensions-builtin\LDSR\preload.py: AssertionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\programs\automatic\modules\script_loading.py:10 in load_module                                                   │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\programs\automatic\extensions-builtin\LDSR\preload.py:2 in <module>                                              │
│                                                                                                                     │
│   1 import os                                                                                                       │
│ > 2 from modules import paths                                                                                       │
│   3                                                                                                                 │
│                                                                                                                     │
│ C:\programs\automatic\modules\paths.py:26 in <module>                                                               │
│                                                                                                                     │
│   25                                                                                                                │
│ > 26 assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_                       │
│   27                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AssertionError: Couldn't find Stable Diffusion in any of:
['C:\\programs\\automatic\\repositories/stable-diffusion-stability-ai', '.', 'C:\\programs']
Module load: C:\programs\automatic\extensions-builtin\Lora\preload.py: AssertionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\programs\automatic\modules\script_loading.py:10 in load_module                                                   │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\programs\automatic\extensions-builtin\Lora\preload.py:2 in <module>                                              │
│                                                                                                                     │
│   1 import os                                                                                                       │
│ > 2 from modules import paths                                                                                       │
│   3                                                                                                                 │
│                                                                                                                     │
│ C:\programs\automatic\modules\paths.py:26 in <module>                                                               │
│                                                                                                                     │
│   25                                                                                                                │
│ > 26 assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_                       │
│   27                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AssertionError: Couldn't find Stable Diffusion in any of:
['C:\\programs\\automatic\\repositories/stable-diffusion-stability-ai', '.', 'C:\\programs']
Module load: C:\programs\automatic\extensions-builtin\ScuNET\preload.py: AssertionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\programs\automatic\modules\script_loading.py:10 in load_module                                                   │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\programs\automatic\extensions-builtin\ScuNET\preload.py:2 in <module>                                            │
│                                                                                                                     │
│   1 import os                                                                                                       │
│ > 2 from modules import paths                                                                                       │
│   3                                                                                                                 │
│                                                                                                                     │
│ C:\programs\automatic\modules\paths.py:26 in <module>                                                               │
│                                                                                                                     │
│   25                                                                                                                │
│ > 26 assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_                       │
│   27                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AssertionError: Couldn't find Stable Diffusion in any of:
['C:\\programs\\automatic\\repositories/stable-diffusion-stability-ai', '.', 'C:\\programs']
Module load: C:\programs\automatic\extensions-builtin\SwinIR\preload.py: AssertionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\programs\automatic\modules\script_loading.py:10 in load_module                                                   │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\programs\automatic\extensions-builtin\SwinIR\preload.py:2 in <module>                                            │
│                                                                                                                     │
│   1 import os                                                                                                       │
│ > 2 from modules import paths                                                                                       │
│   3                                                                                                                 │
│                                                                                                                     │
│ C:\programs\automatic\modules\paths.py:26 in <module>                                                               │
│                                                                                                                     │
│   25                                                                                                                │
│ > 26 assert sd_path is not None, "Couldn't find Stable Diffusion in any of: " + str(possible_                       │
│   27                                                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AssertionError: Couldn't find Stable Diffusion in any of:
['C:\\programs\\automatic\\repositories/stable-diffusion-stability-ai', '.', 'C:\\programs']
16:22:24-185053 INFO     Python 3.10.6 on Windows
16:22:24-222586 INFO     Running setup
16:22:24-252110 INFO     Version: cb465b12 Sat Apr 22 09:37:17 2023 -0400
16:22:24-281636 INFO     nVidia toolkit detected
16:22:24-283138 INFO     Installing package: torch torchaudio torchvision --index-url
                         https://download.pytorch.org/whl/cu118

### Version Platform Description

Win 10

**Comment by vladmandic** [comment]
this looks like some modules are imported before install ever had a chance to to do its job.
did you clone the repo before running `webui.bat` or?
does the message `AssertionError: Couldn't find Stable Diffusion in any of:` appear even before message `16:22:24-185053 INFO Python 3.10.6 on Windows`

**Comment by MoreColors123** [comment]
Yes, first I cloned it in CMDline: git clone https://github.com/vladmandic/automatic
Then I ran webui.bat. The output as shown above is the exact output after that.

I already got it to work on another computer with the same procedure.

**Comment by usigg3** [comment]
Maybe related to my problem? I tried to start it today, got it updated and then it just will nor start. See separate new issue.

**Comment by vladmandic** [comment]
found the error, it was a chicken-or-the-egg issue, some extensions try to register cmd flags, but that cannot be done if setup never completed to start with. fixed.

**Comment by kentvuong88** [comment]
> found the error, it was a chicken-or-the-egg issue, some extensions try to register cmd flags, but that cannot be done if setup never completed to start with. fixed.

Doesn't appear to have resolved my issue for it. 
![image](https://user-images.githubusercontent.com/62925665/233834773-0595bd4c-38ef-405d-9b42-8bd85b29cb0d.png)

**Comment by vladmandic** [comment]
@kentvuong88 what is your issue, i don't see anything in the screenshot you've posted?
issue here was identified with `AssertionError: Couldn't find Stable Diffusion in any of:` before setup even started.
