### ISSUE TITLE
[Feature]: Add installer option for creating container

### ISSUE THREAD

**Issue by zhl146** [vladmandic/automatic#380]
### Feature description

Currently there's a script that offers a fairly easy install path for users who want to install and run on the same machine, but it's a slog to get a reproducible install to create a working docker container. If you try to run the installer in a Dockerfile, for example, it will try to install CPU torch, because the builder may not have a GPU. It will also attempt to run the GUI automatically.

Would it be possible to get an install-only script? I tried running some functions directly out of setup.py without much success. I'm going to check the code and see if I can make a simple PR, but I wanted to ask in case it's trivial for you to support this case :)

Thanks for your great work!

### Version Platform Description

linux builder with no GPU
ubuntu 20.04

**Comment by vladmandic** [comment]
i don't know if its trivial or not, i'd have to try and see what happens and what should be done.
but if you can dive into this and create pr to support docker out-of-the-box, i'd welcome it.

**Comment by vladmandic** [comment]
pr#403 is posted, lets continue conversion there.
