### ISSUE TITLE
[Issue]: Can't install DepthMap Script

### ISSUE THREAD

**Issue by gadaszewski** [vladmandic/automatic#384]
### Issue Description

Hello, after installing DepthMap Script from extensions tab I get this message:
"18:30:48-308321 ERROR    Error running extension installer:
                         D:\AI\automatic\extensions\stable-diffusion-webui-depthmap-script\install.py"

### Version Platform Description

arch: AMD64
cpu: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.11.3
updated: 2023-04-22
hash: ec532ee9

**Comment by vladmandic** [comment]
what does `setup.log` say for that error?

**Comment by gadaszewski** [comment]
Traceback (most recent call last):

file "d: \ai\automatic\extensions-builtin\stable-diffusion-webui-rembg\install. Py", line 4, in <module>

launch. Run_pip("install rembg==2.0.30 --no-deps", "rembg")

file "d: \ai\automatic\launch. Py", line 79, in run_pip

return run(f'"{sys. Executable}" -m pip {pkg} --prefer-binary{index_url_line}', desc=f"installing {desc}", errdesc=f"couldn't install {desc}")

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

file "d: \ai\automatic\launch. Py", line 51, in run

raise runtimeerror(f"""{errdesc or 'error running command'}: {command} code: {result. Returncode}

runtimeerror: couldn't install rembg: "d: \ai\automatic\venv\scripts\python. Exe" -m pip install rembg==2.0.30 --no-deps --prefer-binary code: 1

error: ignored the following versions that require a different python version: 2.0.28 requires-python >3.7, <3.11; 2.0.29 requires-python >3.7, <3.11; 2.0.30 requires-python >3.7, <3.11; 2.0.31 requires-python >3.7, <3.11; 2.0.32 requires-python >3.7, <3.11

error: could not find a version that satisfies the requirement rembg==2.0.30 (from versions: none)

error: no matching distribution found for rembg==2.0.30

[notice] a new release of pip available: 22.3.1 -> 23.1.1

[notice] to update, run: d: \ai\automatic\venv\scripts\python. Exe -m pip install --upgrade pip

2023-04-22 18:40:20,137 | info | d: \ai\automatic\setup. Py | extensions enabled: ['stable-diffusion-webui-depthmap-script']
2023-04-22 18:40:20,777 | debug | d: \ai\automatic\setup. Py | running extension installer: d: \ai\automatic\extensions\stable-diffusion-webui-depthmap-script\install. Py
2023-04-22 18:40:23,350 | error | d: \ai\automatic\setup. Py | error running extension installer: d: \ai\automatic\extensions\stable-diffusion-webui-depthmap-script\install. Py
2023-04-22 18:40:23,352 | debug | d: \ai\automatic\setup. Py | installing numba requirement for depthmap script

traceback (most recent call last):

file "d: \ai\automatic\extensions\stable-diffusion-webui-depthmap-script\install. Py", line 14, in <module>

launch. Run_pip("install numba", "numba requirement for depthmap script")

file "d: \ai\automatic\launch. Py", line 79, in run_pip

return run(f'"{sys. Executable}" -m pip {pkg} --prefer-binary{index_url_line}', desc=f"installing {desc}", errdesc=f"couldn't install {desc}")

^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

file "d: \ai\automatic\launch. Py", line 51, in run

raise runtimeerror(f"""{errdesc or 'error running command'}: {command} code: {result. Returncode}

runtimeerror: couldn't install numba requirement for depthmap script: "d: \ai\automatic\venv\scripts\python. Exe" -m pip install numba --prefer-binary code: 1

collecting numba

using cached numba-0.56.4. Tar. Gz (2.4 mb)

preparing metadata (setup. Py): started

preparing metadata (setup. Py): finished with status 'error'

error: subprocess-exited-with-error

python setup. Py egg_info did not run successfully.

Exit code: 1

[8 lines of output]

traceback (most recent call last):

file "<string>", line 2, in <module>

file "<pip-setuptools-caller>", line 34, in <module>

file "c: \users\gad-pc\appdata\local\temp\pip-install-8s4xdj44\numba_3d0fa6237c75492a8fce923798f84c2c\setup. Py", line 51, in <module>

_guard_py_ver()

file "c: \users\gad-pc\appdata\local\temp\pip-install-8s4xdj44\numba_3d0fa6237c75492a8fce923798f84c2c\setup. Py", line 48, in _guard_py_ver

raise runtimeerror(msg. Format(cur_py, min_py, max_py))

runtimeerror: cannot install on python version 3.11.3; only versions >=3.7, <3.11 are supported.

[end of output]

note: this error originates from a subprocess, and is likely not a problem with pip.

Error: metadata-generation-failed

encountered error while generating package metadata.

**Comment by vladmandic** [comment]
well, error is clear.

> runtimeerror: cannot install on python version 3.11.3; only versions >=3.7, <3.11 are supported.

and i have SAME requirements for this repo. Do not use Python 3.11

**Comment by gadaszewski** [comment]
Ah,  your right, sorry for that lol
