### ISSUE TITLE
[Issue]: FileNotFoundError: [Errno 2] No such file or directory: 'javascript/themes.json'

### ISSUE THREAD

**Issue by gregazbill** [vladmandic/automatic#390]
### Issue Description

linux mint, 
cloned repo and went through installation process
got to  ./webui.sh
feeds back this...

FileNotFoundError: [Errno 2] No such file or directory: 'javascript/themes.json'

then navigated to javascript folder....yup, no themes.json file
looked around a bit, found nothing. couldn't find file in repo, couldn't find any record of issue or any solutions  to try.

Its probably something I'm doing wrong... but thought it'd be wise to check in.

**Comment by gregazbill** [comment]
edit....ran [$ python3 launch.py] before running ./webui.sh
It spit out a string of errors but now themes.json is there
(in linux mint)

**Comment by vladmandic** [comment]
That file should be autocreated from list of available themes on Hugginfqce, I'll check why that is not happening.
You can go to UI settings - themes and click refresh, that should recreate it.

**Comment by vladmandic** [comment]
Reopening so I can double check, will close later.

**Comment by vladmandic** [comment]
confirmed that `themes.json` gets autocreated, but if request to huggingface fails (and huggingface does have regular downtime), it was still trying to read it anyhow, added handler for that.
