### ISSUE TITLE
[Feature]: k-diffusion update for improvements to DPM++ 2M Karras sampling and Euler A

### ISSUE THREAD

**Issue by sdbds** [vladmandic/automatic#395]
### Feature description

better at small steps with this change ,detailed see here↓
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8457

someone forked this update and test in mac↓
https://github.com/AUTOMATIC1111/stable-diffusion-webui/discussions/8457#discussioncomment-5500863

fork git ↓
https://github.com/wywywywy/k-diffusion

### Version Platform Description

i test in Windows,it works well

**Comment by vladmandic** [comment]
anyone care to create a pr for this?

**Comment by vladmandic** [comment]
my concern is that `crowsonkb` is official one - will `wywywywy` be maintained in the long-run? what if there are updates to `crowsonkb`? and why are fixes from `wywywywy` not submited to `crowsonkb`?  

also, changing line in `setup.py` would only impact fresh installs, any existing installs would not be updated. and rehosting origin in existing install is messy at best.

**Comment by vladmandic** [comment]
thanks. lets continue the conversation in #411
