### ISSUE TITLE
[Issue]: Image Info Not showing

### ISSUE THREAD

**Issue by kyle215ps3** [vladmandic/automatic#396]
### Issue Description

The image info tab is missing in the UI.
Reload, change the theme updating hasn't fixed the problem.

### Version Platform Description

Version: 4cb46d54 Sat Apr 22 13:33:11 2023 -0400
Windows 11 Edge Browser, Vivaldi and also tried on Opera GX

**Comment by exodia52** [comment]
It being changed to Process Image.

Process Image > Drop Picture > Image Info on bottom right.

**Comment by kyle215ps3** [comment]
this is all i see atm.


![2023-04-23 02 09 47 127 0 0 1 10f82ae8b17c](https://user-images.githubusercontent.com/87888660/233830611-19b219a3-c1f0-4f55-9466-b4e5e02ad0f3.png)
