### ISSUE TITLE
[Issue]: ControlNet models are added to the all 'Stable Diffusion checkpoint' lists

### ISSUE THREAD

**Issue by ostap667inbox** [vladmandic/automatic#400]
### Issue Description

Models for Stable Diffusion and models for ControlNet are stored in different folders.

Bug: everywhere in the WebUI, where the list of models is displayed, the list also contains models for ControlNet

The original Automatic1111 does not have this bug.
![bug](https://user-images.githubusercontent.com/123593542/233830531-7375177e-f3b0-4693-b82d-84451a15bfa2.jpg)

### Version Platform Description

[4cb46d5](https://github.com/vladmandic/automatic/commit/4cb46d5400b04491ae9e70d992ca0019d48942a9)

**Comment by vladmandic** [comment]
issue does exist in a1111 and has to do with your naming of model folders: 
original code is `pattern = name + '**/**'` 
which means it searches in models* and your controlnet model folder is models_for_control_net, so it gets included.
i've fixed it, will be published in ~2h.
