### ISSUE TITLE
[Issue]: duplicates in various lists in 'Settings'

### ISSUE THREAD

**Issue by ostap667inbox** [vladmandic/automatic#402]
### Issue Description

Multiple duplicate items found in Settings: 'Face restoration', 'User Interface', 'Upscaling'

![bug1](https://user-images.githubusercontent.com/123593542/233831351-258cb002-9033-4ec8-8797-33ee92dfef2e.png)
![bug2](https://user-images.githubusercontent.com/123593542/233831357-e6a37bda-bbdb-44a9-86af-d47c9f3cf19e.png)
![bug3](https://user-images.githubusercontent.com/123593542/233831359-84b952f6-01fd-44b6-ae65-984bff67b7e8.png)

### Version Platform Description

[4cb46d5](https://github.com/vladmandic/automatic/commit/4cb46d5400b04491ae9e70d992ca0019d48942a9)

**Comment by vladmandic** [comment]
duplicate issue, already tracking.
