### ISSUE TITLE
does not detect GPU, generates on CPU

### ISSUE THREAD

**Issue by inck86** [vladmandic/automatic#409]
### Issue Description

I have an RTX2060 6Gb, but the generation process starts on the CPU, in the "System Info" section it says "2.0.0+cpu Autocast half" and an empty stash in the "GPU".

At the same time, everything works fine in A1111, all the necessary drivers and CUDA toolkit are installed.

How to switch CPU to GPU ?

### Version Platform Description

OS: Win10 Pro x64

WebIU: 
updated: 2023-04-23
hash: bef352c2
url: https://github.com/vladmandic/automatic/tree/master

**Comment by vladmandic** [comment]
installer installed cpu version of torch as at the time of installation it did not detect gpu.
do you have nvidia cuda installed? if not, install it.
then uninstall torch:
> pip uninstall torch torchvision torchaudio`
and rerun webui so it can detect gpu and install correct torch.

**Comment by inck86** [comment]
> do you have nvidia cuda installed?

yes, I installed nvidia cuda
![image](https://user-images.githubusercontent.com/119116007/233838351-b7c12b84-7964-4dc3-a310-d853352fe3df.png)

where should I enter the command "pip uninstall torch torch vision torchaudio"?
If I do this in the installation folder, it gives me:

PS C:\Vlad1111\automatic\venv\Scripts> pip uninstall torch torchvision torchaudio 
WARNING: Skipping torch as it is not installed.
WARNING: Skipping torchvision as it is not installed.
WARNING: Skipping torchaudio as it is not installed.

**Comment by vladmandic** [comment]
> cd C:\Vlad1111\automatic
> venv\Scripts\activate
> pip uninstall torch torchvision torchaudio

before that, make sure you can run `nvidia-smi` and it shows your gpu and cuda correctly?

**Comment by inck86** [comment]
> before that, make sure you can run `nvidia-smi` and it shows your gpu and cuda correctly?

when trying to run a file "C:\Windows\System32\nvidia-smi.exe "nothing is happening, I will try to reinstall NVIDIA drivers.

after uninstalling torch and restarting webui.bat, the system again defined as "Using CPU-only Torch"

**Comment by inck86** [comment]
> yeah, if `nvidia-smi` doesn't work, app doesn't stand a chance. that is core nvidia utility.

So, I reinstall NVIDIA drivers and now Ihave info from nvidia-smi:

C:\Users\Professional>C:\Windows\System32\nvidia-smi.exe
Sun Apr 23 15:30:49 2023
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 531.14                 Driver Version: 531.14       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                      TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 2060       WDDM | 00000000:01:00.0  On |                  N/A |
| 29%   42C    P0               34W / 160W|    450MiB /  6144MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1332    C+G   ...ndexBrowser\Application\browser.exe    N/A      |
|    0   N/A  N/A      5024    C+G   ...CBS_cw5n1h2txyewy\TextInputHost.exe    N/A      |
|    0   N/A  N/A      6392    C+G   ...ience\NVIDIA GeForce Experience.exe    N/A      |
|    0   N/A  N/A      7120    C+G   ....Search_cw5n1h2txyewy\SearchApp.exe    N/A      |
|    0   N/A  N/A      8724    C+G   ...ns\Software\Current\LogiOverlay.exe    N/A      |
|    0   N/A  N/A     17524    C+G   ...GeForce Experience\NVIDIA Share.exe    N/A      |
+---------------------------------------------------------------------------------------+

but the installer still does not see CUDA and installs torch only for CPU :(

venv "C:\Vlad1111\automatic\venv\Scripts\Python.exe"
15:32:10-669858 INFO     Python 3.10.9 on Windows
15:32:10-721691 INFO     Version: bef352c2 Sun Apr 23 07:19:51 2023 -0400
15:32:11-266236 INFO     Latest published version: 176ac924af83ce8df6a9cdad8cc3b16c64690cc0 2023-04-23T12:11:26Z
15:32:11-269227 INFO     Updating Wiki
15:32:13-121274 INFO     Using CPU-only Torch
15:32:13-122272 INFO     Installing package: torch torchaudio torchvision
15:32:43-545941 INFO     Torch 2.0.0+cpu
15:32:43-547911 WARNING  Torch repoorts CUDA not available
15:32:43-549906 INFO     Verifying requirements
15:32:43-568883 INFO     Installing package: torch
15:32:47-025612 INFO     Installing package: torchvision
15:32:49-495008 INFO     No changes detected: Quick launch active
15:32:49-496005 INFO     Setting environment tuning
15:32:49-502987 INFO     Running extension preloading
15:32:49-503984 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.

**Comment by vladmandic** [comment]
did you reboot after driver reinstall?
if your `nvidia-smi` in path? installer uses that to detect nvidia gpu.

try executing:
`venv/Scripts/cli/activate`
`python -c "import shutil; print(shutil.which(\"nvidia-smi\"))"`

**Comment by inck86** [comment]
> did you reboot after driver reinstall?
yes, I did

> if your `nvidia-smi` in path?
I guess so, yes
![image](https://user-images.githubusercontent.com/119116007/233842914-e2dc188b-67af-4353-9fef-03a0b9162b5f.png)

> try executing:
> `venv/Scripts/cli/activate`
> `python -c "import shutil; print(shutil.which(\"nvidia-smi\"))"`
I'm sorry, but where to enter it?
![image](https://user-images.githubusercontent.com/119116007/233842989-df0522bd-daa9-4608-a72e-584eb1c18e3e.png)
![image](https://user-images.githubusercontent.com/119116007/233843022-aafeb2a7-e497-44ee-b101-2a3f79670926.png)
![image](https://user-images.githubusercontent.com/119116007/233843041-772b9e89-bf2a-49ab-a28d-35cef3dd79e5.png)
![image](https://user-images.githubusercontent.com/119116007/233843119-eecdf806-7044-4ab4-9a0c-9dac8c60ad7e.png)

**Comment by vladmandic** [comment]
that a copy&paste error on your side that results in mismatch in `"` chars.

**Comment by inck86** [comment]
> just type it exactly as its written.

but I'm entering exactly as you wrote..
![image](https://user-images.githubusercontent.com/119116007/233843817-39356dd5-1822-4971-883c-5576132f0264.png)

tried different options X)
![image](https://user-images.githubusercontent.com/119116007/233843890-cd382581-cea6-43c2-a36e-a5f2cc4b5a79.png)

**Comment by vladmandic** [comment]
there should be `\"` before and after `nvidia-smi`, that's pretty much only option you didn't try :)

**Comment by inck86** [comment]
> here should be `\"` before and after `nvidia-smi`

oh, it blows my head (
I have `\"` before and after `nvidia-smi`, why is it not entered either via VLC or via CMD (((

![image](https://user-images.githubusercontent.com/119116007/233844295-3f10968e-e871-4b7f-888e-46e4efa50fbb.png)

**Comment by vladmandic** [comment]
so now you got command running, but it clearly says `nvidia-smi` is NOT in path. if it were, it would print the path to it.
check your system paths and reboot if needed.

for example, when i run it:
> (venv) D:\SD>python -c "import shutil; print(shutil.which(\"nvidia-smi\"))"
> C:\Windows\system32\nvidia-smi.EXE

**Comment by inck86** [comment]
> is NOT in path
I added the path to nvidia-smi.exe , rebooted the computer, but nothing has changed:(

There are no other ways to manually specify for the installer where is my GPU (figuratively speaking)?

I somehow had problems with installing InvokeAI, so I replaced all "python" with "py" in the installer there - otherwise it didn't work. But since then I have reinstalled python closer to the root of C and similar errors have disappeared. Now this is it...

![image](https://user-images.githubusercontent.com/119116007/233845418-4763c1b2-a5f0-4eb0-a9c8-4c9ee83647c8.png)

**Comment by vladmandic** [comment]
you shouldn't have full path to file in os path, you'll break os, literally.
path should be "C:\Windows\System32" and it tells Windows where to search for anything - so if you type nvidia-smi, it will check there.

Btw, I've NEVER seen Windows system without that specific path, but I guess there is always first time.

**Comment by inck86** [comment]
> path should be "C:\Windows\System32"

Holy cookies, it's alive!
Thanks! I'll tell everyone how cool and responsive Vlad Mandic is :)

and in order not to create a separate branch - somewhere in webui.bat is there a place for commands like "git pull" or "--autolaunch"?

![image](https://user-images.githubusercontent.com/119116007/233845982-21d87e2c-9375-4225-9d21-6370cff7b55f.png)

**Comment by vladmandic** [comment]
you can create `webui-user.bat` and have that:
```batch
@echo off
git pull
webui --autolaunch
```
