### ISSUE TITLE
[Issue]: Restarting UI duplicates upscalers

### ISSUE THREAD

**Issue by acorderob** [vladmandic/automatic#410]
### Issue Description

When you restart the UI some upscalers get duplicated in the combos. As far as i know it only happens with SwinIR and LDSR.

### Version Platform Description

commit: 4cb46d5400b04491ae9e70d992ca0019d48942a9
Windows 10
Chrome

**Comment by vladmandic** [comment]
there are 5+ reports for this. read #224.
