### ISSUE TITLE
[Extension]: Batch processing errors when using SD Upscale script

### ISSUE THREAD

**Issue by MoreColors123** [vladmandic/automatic#412]
### Issue Description

Not a major issue, but when I batch processed some images I got them in two different folders:
Specified "Output directory": C:\programs\automatic\outputs\text\travels\00009\hires
It _did_ save the pictures there, but also in this folder: C:\programs\automatic\outputs\image

Oh and after finishing output, the console had some errors waiting for me:

gradio call: FileNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\programs\automatic\modules\call_queue.py:58 in f                                                                 │
│                                                                                                                     │
│    57 │   │   │   │   pr.enable()                                                                                   │
│ >  58 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ C:\programs\automatic\modules\call_queue.py:38 in f                                                                 │
│                                                                                                                     │
│    37 │   │   │   try:                                                                                              │
│ >  38 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    39 │   │   │   finally:                                                                                          │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ C:\programs\automatic\modules\img2img.py:47 in process_batch                                                        │
│                                                                                                                     │
│    46 │   │   try:                                                                                                  │
│ >  47 │   │   │   img = Image.open(image)                                                                           │
│    48 │   │   except UnidentifiedImageError:                                                                        │
│                                                                                                                     │
│ C:\programs\automatic\venv\lib\site-packages\PIL\Image.py:3236 in open                                              │
│                                                                                                                     │
│   3235 │   if filename:                                                                                             │
│ > 3236 │   │   fp = builtins.open(filename, "rb")                                                                   │
│   3237 │   │   exclusive_fp = True                                                                                  │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
FileNotFoundError: [Errno 2] No such file or directory:
'C:\\programs\\automatic\\outputs\\text\\travels\\00009\\1\\00113-1700567082-(RAW uhd photograph of ....

**Comment by vladmandic** [comment]
For first item, UI -> Settings -> Image Options -> Save a copy of image before applying highres fix.
For second item, I'll look into it.

**Comment by MoreColors123** [comment]
Oh, my bad, I didn't realize that saving a copy was an option in the settings. But still I actually didn't hires fix, I was in the IMG2IMG section. But I did use SD upscale, not sure if thats connected with hires fix. I will try to disable and do the same again.

Second item, my workflow: 
From image -> Batch. Here i specified an input folder with about 50 images (which i got from a seed travel extension generation before, but that shouldn't matter), and i also specified an output folder.
Script used: SD upscale with R-ESRGAN 4x+

Dynamic Prompts was enabled but not in use (no trigger words used)
Nothing else was activated (no controlnet, no restore faces)

**Comment by vladmandic** [comment]
there's something wrong with "SD Upscale" script, on my system it created a total nonsense workitem:
with two images in input folder and using all defaults, it said:
> SD upscaling will process a total of 12 images tiled as 3x4 per upscale in a total of 12 batches.
then started processing, got to 22% and just hang there without any progress with GPU on 100%.

went to process, loaded one of images and used same upscaler and it processed image without issues.

i hope someone can help with this, by backlog at the moment is pretty big and i'm totally unfamiliar with sd upscale script.

**Comment by AlUlkesh** [comment]
Instead of `SD Upscale`, have you tried the `Ultimate SD upscale` extension? At the very least we'd know if it is a problem with the builtin SD Upscale or some issue with upscaling in general.

**Comment by MoreColors123** [comment]
> i hope someone can help with this, by backlog at the moment is pretty big and i'm totally unfamiliar with sd upscale script.

as i said not a major issue, keep up with the good work on more important stuff... thanks! I will try ultimate SD upscale.
