### ISSUE TITLE
[Issue]: image preview popup to fullscreen

### ISSUE THREAD

**Issue by rayminator2023** [vladmandic/automatic#414]
### Issue Description

this is new to me hope I got everything 
image preview popup to fullscreen doesn't popup anymore it worked two hours ago but now it doesn't there was no error code
it's just that click on the image after you generate doesn't popup to fullscreen

updated: 2023-04-23
hash: 40184f9e

### Version Platform Description

arch: AMD64
cpu: AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
system: Windows 11
release: Windows-10-10.0.22621-SP0
python: 3.10.9
2.0.0+cu118 Autocast  half
NVIDIA GeForce RTX 3060

**Comment by DrQuantumAI** [comment]
Same here.

**Comment by vladmandic** [comment]
ahh, a type in recently merged pr broke it, fixed.

**Comment by DrQuantumAI** [comment]
Thank you. I just did an update via
git pull

and it works!
Thank you again.

**Comment by rayminator2023** [comment]
it's not working again

Python 3.10.9 on Windows
18:11:11-578229 INFO     Version: 6cd4d62f Sat Apr 29 17:36:13 2023 -0400
18:11:11-871356 INFO     Setting environment tuning
18:11:11-873353 INFO     nVidia toolkit detected
18:11:15-836660 INFO     Torch 2.0.0+cu118
18:11:15-860436 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
18:11:15-862437 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28

**Comment by vladmandic** [comment]
you're FAST - you caught it just perfectly in-between two merges :)

i've removed server-side option to even disable this (why would anyone disable it?)
and then 5min later i actually forced in on client-side.

anyhow, its resolved.

**Comment by RJSprod** [comment]
> you're FAST - you caught it just perfectly in-between two merges :)
> 
> i've removed server-side option to even disable this (why would anyone disable it?) and then 5min later i actually forced in on client-side.
> 
> anyhow, its resolved.

I want to disable it! Full screen is not my preference. Sorry, i opened a feature request about this. Sorry, lightbox isn't so good to me. Maybe it it were redesigned, it take up a larger header and has tiny arrows to navigate. Really sucks on mobile, would much rather just tap to go through my images right on the generation page.

https://github.com/vladmandic/automatic/issues/757

**Comment by vladmandic** [comment]
So valid feature request would be to describe how to improve lightbox.
Lets try to think constructively and not just look into past.
