### ISSUE TITLE
[Issue]: Error: Server disconnet without sending a response

### ISSUE THREAD

**Issue by xiedawei** [vladmandic/automatic#416]
### Issue Description

![Screenshot 2023-04-23 230858](https://user-images.githubusercontent.com/10558352/233847913-0ff8fdae-a7d4-4f8c-a6f4-2abd03f6196b.png)
something went wrong

### Version Platform Description

win 11

**Comment by vladmandic** [comment]
This literally says nothing - what is the output on your console where you run actual server?
and `win 11` is not what i expect when asking for detailed platform and version information.

**Comment by xiedawei** [comment]
OS: window 11
Browser: Chrome
Python version:  3.10.11

**Comment by vladmandic** [comment]
still not console log

**Comment by xiedawei** [comment]
I found the problem. Disable the VPN, then work.

**Comment by vladmandic** [comment]
fyi, typical vpn configuration tries to redirect all network traffic to go over vpn, including local network - which is just a bad vpn configuration. there should be option in your vpn to allow local network traffic as-is.
