### ISSUE TITLE
[Feature]: Can you guys cooperate?

### ISSUE THREAD

**Issue by bbecausereasonss** [vladmandic/automatic#418]
### Feature description

You have the best code and functionality repo. 
This guy has the best UX/UI repo.

PLEASE find a way to cooperate! He was trying to merge with Automatic's main fork but as you can imagine that took forever and Auto is pretty unresponsive.

https://github.com/anapnoe/stable-diffusion-webui-ux

**Comment by vladmandic** [comment]
yup, we have started direct communication few days ago and when there is something to announce, you'll hear it :)

**Comment by bbecausereasonss** [comment]
OMFG YAAAAAAAAAAAASSS :p

**Comment by TotalDay** [comment]
i want add intel ARC support to your project
https://github.com/TotalDay/Intel_ARC_GPU_WSL_Stable_Diffusion_WEBUI

**Comment by vladmandic** [comment]
@TotalDay if you wish to contribute, i'd love it.

**Comment by vladmandic** [comment]
@TotalDay i'm getting a lot of warnings - seems your PR <https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9826> is trying to merge this fork with original A1111? best to close it and have separate PR pointing from your code base towards this fork?

**Comment by StudioWren** [comment]
will this work on an AMD based system?

**Comment by vladmandic** [comment]
@StudioWren This is about Intel ARC. There is a separate effort for AMD - a) make it compatible with normal torch, this is mostly done and working, b) optimize using DirectML, that is separate effort.
