### ISSUE TITLE
[Issue]: Does not work on M1 Mac

### ISSUE THREAD

**Issue by wojteksosnowski** [vladmandic/automatic#421]
### Issue Description

M1 iMac
proceed with basic install
webui works
crash at "generate"
<img width="672" alt="image" src="https://user-images.githubusercontent.com/46383030/233856013-ca8b0384-992c-4548-8fa7-016927ce3781.png">

**Comment by vladmandic** [comment]
duplicate. search before opening issues. and don't create issue without actually providing required information in issue template.
