### ISSUE TITLE
[Issue]: Model Dropdown List loads forever on public IP

### ISSUE THREAD

**Issue by byteconcepts** [vladmandic/automatic#423]
### Issue Description

I started vladmandic with the --listen and --upgrade parameters.

When I start the WebUI on any browser on another computer, the Model-Dropdown-List loads forever and never shows the list. - I tried three different browsers, even without any extensions, the behavior is the same on all.

Everything else seem to work also on a public IP. - But you can't switch between models, so the UI is kind of unusable this way.

When I call the WebUI on the computer here I started vladmandic with http://127.0.0.1:7860, the problem does not occur. Everything seems fine.

My "Path to directory with stable diffusion checkpoints" points to a directory on another disk...
  D:\stable-diffusion\models\stable-diffusion
...which seems to work korrectly, I can create Images with the module initially discovered on startup.

### Version Platform Description

updated: 2023-04-23
hash: 98adfb31
url: https://github.com/vladmandic/automatic/tree/master

arch: AMD64
cpu: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
system: Windows
release: Windows-10-10.0.19044-SP0
python: 3.10.8

**Comment by WojtekKowaluk** [comment]
This is one of bug that I also have in A1111, after gradio 3.23 update. Other bugs that I think are related is "generate" button stops working after some time and "extra networks" won't show hide after some time. I have those 3 problem with vladmandic/A1111 lastest version, but not with A1111 a9eab236d7e8afa4d6205127904a385b2c43bb24, so I assume all of them are connected to gradio 3.23.

**Comment by byteconcepts** [comment]
Great, this was fast! - Many thanks :-)
I don't know who did it but with today's update it works again for me.
But Gradio is still on version 3.23.0, so maybe this is not a gradio issue.

I don't know if I should close this issue now, maybe WojtekKowaluk could check his installation and if his errors are also gone then maybe he should close the issue.

**Comment by vladmandic** [comment]
there is a major update regarding generate stops working, see <https://github.com/vladmandic/automatic/issues/340#issuecomment-1520159105>

i haven't taken a look at listen issue yet.

**Comment by WojtekKowaluk** [comment]
@byteconcepts I still get problems with extra networks stoping to show/hide and generate button blocked. I did not seen model list generating forever with latest version.

**Comment by WojtekKowaluk** [comment]
@vladmandic hopefully newer gradio version will fix issues. BTW "generate" button and "extra networks" still randomly get stuck for me, any way I can help with debugging this?

**Comment by horribleCodes** [comment]
Oh, so it's an issue with the public address? I noticed Auto's version becoming less and less responsive on my tablet, but I assumed it was an issue with my wifi connection or tablet. Switching from Brave to Opera helped a little, but it's still unusable.

**Comment by vladmandic** [comment]
i'm just testing 3.28.1 as we speak, going ok so far and planning to release later today.

**Comment by vladmandic** [comment]
published.
