### ISSUE TITLE
[Issue]: zsh: illegal hardware instruction  ./webui.sh

### ISSUE THREAD

**Issue by nybe** [vladmandic/automatic#429]
### Issue Description

forgive me if this isn't described properly... I cannot get this to install on M1 Max laptop... it get's to

"Server arguments: []"

then says: 

"zsh: illegal hardware instruction  ./webui.sh"

### Version Platform Description

Apple M1 Max, macOS 13.3.1 (22E261)

**Comment by vladmandic** [comment]
adding to #347 and closing here.
