### ISSUE TITLE
[Issue]: Controlnet check box option is not working.

### ISSUE THREAD

**Issue by wkdtjs** [vladmandic/automatic#439]
### Issue Description

The check box option in the controlnet entry does not work.

I checked that it works on the basic webui.

There will be an error after that code.

https://github.com/Mikubill/sd-webui-controlnet/commit/cf2dae57d1cbbd42cae69c8db65ec1ffcb5d701d

### Version Platform Description

98adfb3151575f1020ecda509956ed9bef30ea86

**Comment by AlUlkesh** [comment]
Which checkbox? And what exactly do you mean with "does not work"? Can't click it? Has no effect? ...

**Comment by wkdtjs** [comment]
Yes, clicking the check box in the control net option does not change.
