### ISSUE TITLE
[Issue]: not aware of the new features of controlnet.

### ISSUE THREAD

**Issue by wkdtjs** [vladmandic/automatic#442]
### Issue Description

The ability to focus on the controlnet or picture is incompatible.

18:23:45-365014 INFO     Installing packages
18:23:45-366010 INFO     Installing repositories
18:23:45-498168 INFO     Installing submodules
18:23:48-492891 INFO     Updating submodules
18:23:55-169533 ERROR    Error running git: extensions-builtin/sd-webui-controlnet / checkout main
18:23:55-766009 ERROR    Error running git: extensions-builtin/sd-webui-controlnet / pull --rebase --autostash
18:24:00-784119 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
18:24:08-732725 ERROR    Error running git: D:\vladmandic\automatic\extensions-builtin\sd-webui-controlnet / checkout
                         main
18:24:09-301242 ERROR    Error running git: D:\vladmandic\automatic\extensions-builtin\sd-webui-controlnet / pull
                         --rebase --autostash
18:24:13-228196 INFO     Extensions enabled: ['a1111-sd-webui-tagcomplete', 'ABG_extension', 'gif2gif',
                         'sd-webui-3d-open-pose-editor', 'sd-webui-ar', 'sd-webui-ddsd', 'sd-webui-supermerger',
                         'stable-diffusion-webui-wd14-tagger']
18:24:22-080516 WARNING  Setup complete with errors (4)
18:24:22-080516 WARNING  See log file for more details: setup.log
18:24:22-081513 INFO     Setting environment tuning
18:24:22-088526 INFO     Running extension preloading
18:24:22-089524 INFO     Server arguments: []

### Version Platform Description

windows 11, rtx 3060 ti

vladmandic: 98adfb3151575f1020ecda509956ed9bef30ea86

controlnet: c5984671ccd7da7d554f239143648b8157ae1c39

**Comment by vladmandic** [comment]
> The ability to focus on the controlnet or picture is incompatible.

This doesn't say much - can you be a bit more descriptive when creating issues?

**Comment by vladmandic** [comment]
rerun. the error is simple git update error that should go away. i don't want to keep retrying during each startup.
and you can always go to extensions and run update from there.
and that is UPDATE error, nothing to do with issue title. if you said "controlnet was not automatically updated during startup", i'd at least know what you meant.
