### ISSUE TITLE
[Issue]: Multiple errors making it unable to install

### ISSUE THREAD

**Issue by gitmylo** [vladmandic/automatic#448]
### Issue Description

I had installed [this extension](https://github.com/SHI-Labs/Text2Video-Zero-sd-webui/). And it downgraded my torch to 1.13.1.
The extension failed to install, so i removed it, and then realized i was unable to generate images.
So i tried to delete my venv. And then re-running the webui.bat.
During the install i saw an error saying `Error running pip: install --upgrade facexlib`
Then after the install finished and it tried to run, i get `ModuleNotFoundError: No module named 'clip'`. and it crashes.
After installing clip, and then some other packages that it keeps coming with. I still get a lot of errors when launching.
`ModuleNotFoundError: No module named 'clip_interrogator'`, `ModuleNotFoundError: No module named 'rembg'`
Installing rembg is easy, but for clip_interrogator i need to run `pip install --upgrade clip_interrogator==0.5.4` specifically? and doing that downgrades timm to 0.4.12, which is lower than recommended. so it installs the newer version.

Does the same happen for others when installing from scratch? Because installing worked fine when i did it a few days ago for the first time.

### Version Platform Description

Version: 98adfb31 Sun Apr 23 11:50:30 2023 -0400
Platform: Windows 10
Browser: Firefox (doesn't really matter, since the errors happen before the webui launched)
issue occurs with user installed plugins enabled and disabled (completely taken out of the plugins folder)

**Comment by gitmylo** [comment]
So to get it working it requires manual install.
Here's the steps i had to do to get it working manually:
`venv\scripts\activate.bat`
`pip install --upgrade facexlib`
`pip install --upgrade clip`
`pip install --upgrade rembg`
`pip install --upgrade clip_interrogator==0.5.4`

**Comment by gitmylo** [comment]
Also, after putting the extensions back into my extensions folder, they also didn't install. Is it because extensions only try to run install.py once? Because that doesn't account for venv being deleted and recreated.

**Comment by vladmandic** [comment]
> Also, after putting the extensions back into my extensions folder, they also didn't install. Is it because extensions only try to run install.py once? Because that doesn't account for venv being deleted and recreated.

launcher will re-run extensions installer if a) main repo is updated, b) any of extensions is updated.
if you mess around venv manually, no, it doesn't. you can alwayt run `webui --upgrade` to force it.
