### ISSUE TITLE
[Issue]: error Updating submodules

### ISSUE THREAD

**Issue by bryanray** [vladmandic/automatic#454]
### Issue Description

01:39:49-221158 INFO     Python 3.10.6 on Windows
01:39:49-520658 INFO     Version: 85798f63 Mon Apr 24 12:34:49 2023 -0400
01:39:50-211279 INFO     nVidia toolkit detected
01:39:52-968911 INFO     Torch 2.0.0+cu118
01:39:52-999477 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
01:39:53-001477 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 Laptop GPU VRAM 6144 Arch (8, 6) Cores 30
01:39:53-002478 INFO     Installing package: tensorflow==2.12.0
01:40:01-353461 INFO     Verifying requirements
01:40:01-404462 INFO     Running setup
01:40:01-405461 INFO     Installing packages
01:40:01-406461 INFO     Installing repositories
01:40:01-573462 INFO     Installing submodules
01:40:04-660369 INFO     Updating submodules
01:40:27-052956 ERROR    Error running git: extensions-builtin/clip-interrogator-ext / pull --autostash
01:40:48-259570 ERROR    Error running git: extensions-builtin/multidiffusion-upscaler-for-automatic1111 / pull
                         --autostash
01:41:10-949344 ERROR    Error running git: extensions-builtin/sd-extension-aesthetic-scorer / pull --autostash

all ext has this start errors......
strangely the prev erros resolved but this news one appeared after git pull from repo

**Comment by vladmandic** [comment]
if there is error, it points to check out `setup.log` at the end - so what does setup.log say?

**Comment by vladmandic** [comment]
ok, i've updated installer, should fix the update.

**Comment by doctord98618** [comment]
> ok, i've updated installer, should fix the update.

yes it is fixed, still one error remains 
 ERROR    Error running git: None / submodule --quiet update  --init --recursive

**Comment by bryanray** [comment]
was ok before update, bu before update tensorflow cant even installed, new update fix git problem, but this new error

**Comment by bryanray** [comment]
dont close it it is not fixed yet

**Comment by vladmandic** [comment]
what is not fixed? the only error in your latest setup.log is your connection error:

> Failed to connect to github.com port 443 after 21055 ms:

**Comment by doctord98618** [comment]
> what is not fixed? the only error in your latest setup.log is your connection error:
> 
> > Failed to connect to github.com port 443 after 21055 ms:

Error at line 166
[setup (1).log](https://github.com/vladmandic/automatic/files/11314436/setup.1.log)

**Comment by vladmandic** [comment]
it literally said 'already exists'. do you have problems with "control-net"?

**Comment by doctord98618** [comment]
> it literally said 'already exists'. do you have problems with "control-net"?

Sorry it was my mistake, no errors now, thanks for help, keep up the good work

**Comment by bryanray** [comment]
[setup.log](https://github.com/vladmandic/automatic/files/11315941/setup.log)

check this error

**Comment by bryanray** [comment]
![image](https://user-images.githubusercontent.com/1768531/234162228-d32723a6-c079-4b90-ae2f-02368cce50c9.png)
[setup.log](https://github.com/vladmandic/automatic/files/11316003/setup.log)

**Comment by doctord98618** [comment]
> ![image](https://user-images.githubusercontent.com/1768531/234162228-d32723a6-c079-4b90-ae2f-02368cce50c9.png) [setup.log](https://github.com/vladmandic/automatic/files/11316003/setup.log)
Did you update it download the latest comits

**Comment by doctord98618** [comment]
> ![image](https://user-images.githubusercontent.com/1768531/234162228-d32723a6-c079-4b90-ae2f-02368cce50c9.png) [setup.log](https://github.com/vladmandic/automatic/files/11316003/setup.log)

Latest commits solved the issue, update it if you haven't already

**Comment by bryanray** [comment]
whats the laest version? i think i just git the latest from the repo

**Comment by bryanray** [comment]
023e
![image](https://user-images.githubusercontent.com/1768531/234175942-a0b73895-b98d-41cf-ab56-02f857d6a0a2.png)
