### ISSUE TITLE
Very slow loading of additional modules and materials

### ISSUE THREAD

**Issue by inck86** [vladmandic/automatic#457]
### Issue Description

![image](https://user-images.githubusercontent.com/119116007/234094445-e69f7af9-6689-47c5-8eb0-a067731d8ca6.png)

Net control preprocessors are loaded at a speed of 20kb/s, while the Internet allows downloading at a speed of 10Mb/s.
The same thing happens when starting "interrogate CLIP", although the model "model_base_caption_capfilt_large.pth" has already been downloaded and placed in "automatic\models\BLIP".

what could be the reason for such slow speeds?

### Version Platform Description

![image](https://user-images.githubusercontent.com/119116007/234094666-6706c591-7427-43aa-9a20-9e8e22aa9bdc.png)

**Comment by zixuan-nplace** [comment]
I have the same issue, load checkpoint takes forever. PTAL

**Comment by zixuan-nplace** [comment]
> @zixuan-nplace are you sure its "the same issue" - what was asked here is why initial download of model over internet is slow. "load checkpoint takes forever" sounds like a totally different issue.

I think he/she also mentioned about slow loading. However for me it only occurred at the first loading. Now it works fine. Thank you!
