### ISSUE TITLE
[Issue]: Where is Euler A? Please re-enable it at default

### ISSUE THREAD

**Issue by hithereai** [vladmandic/automatic#463]
### Issue Description

Did you remove Euler A from the samplers? If so, why?

**Comment by hithereai** [comment]
Turns out it's disabled by default for some strange reason. It is the default Deforum sampler, please bring it back to on by default.

**Comment by hithereai** [comment]
Reopening for visibility. I can make a PR to turn it back on that seems silly. Lmk if you want me to do it.

**Comment by vladmandic** [comment]
oh, it was not removed by choice. i've merged a pr that changed settings from (hide samplers to show samplers, so inverse. but it didn't inverse the list itself.). just fixed it, will push in few min.
