### ISSUE TITLE
[Feature]: have 'Automatic' SD VAE and 'Ignore selected VAE...' parse VAE directory in VAE dir

### ISSUE THREAD

**Issue by Gazzoo-byte** [vladmandic/automatic#466]
### Feature description

I may have set something up incorrectly, but the Automatic and Ignore selected VAE... settings don't appear to try searching the configured VAE path, I have made symlinks to match my preferred VAEs to their corresponding models, which works fine when the VAEs are in the same folder as the models, but when I place the VAEs into their own folder it no longer automatically detects them

### Version Platform Description

21:24:31-451245 INFO     Python 3.10.6 on Windows
21:24:31-861524 INFO     Version: 20b64aad Mon Apr 24 16:16:52 2023 -0400
21:24:32-292980 INFO     nVidia toolkit detected
21:24:34-229756 INFO     Torch 2.1.0.dev20230424+cu118
21:24:34-278183 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
21:24:34-281188 INFO     Torch detected GPU: NVIDIA GeForce RTX 4070 VRAM 12282 Arch (8, 9) Cores 46

Firefox

**Comment by Gazzoo-byte** [comment]
Certainly, so I have my VAE files in the specified folder, rather than in the folder where my checkpoints are stored
![image](https://user-images.githubusercontent.com/73721238/234330656-50fecf05-3a7d-4f8e-bd09-a699ff2c3915.png)

however when they aren't in the same folder as the checkpoint this option does not work correctly
![image](https://user-images.githubusercontent.com/73721238/234330920-9f9d929e-9389-402f-8ef1-780169263ce1.png)

![image](https://user-images.githubusercontent.com/73721238/234331106-4ff82b77-d9f7-47bf-8861-4d943148f814.png)

The symlink stuff I mentioned before is unrelated to the issue, not sure why I mentioned it in hindsight, but in case it helps this is how I have things set up

![image](https://user-images.githubusercontent.com/73721238/234331769-f8f8e20a-62d9-4815-932e-1c04f48a5882.png)

I made links to specific VAEs depending on my preference, so when the UI is set to Automatic, or when the option above is ticked, it should automatically detect the correctly named VAE and use it - saves space by deduplicating.

For reference, this is the expected behaviour when the VAE is in the same folder as the checkpoint
![image](https://user-images.githubusercontent.com/73721238/234332674-1cc68c2c-9518-4bef-adc6-2275c05baef7.png)

I hope this clarifies my request

**Comment by vladmandic** [comment]
closed via #498
