### ISSUE TITLE
[Feature]:  Parameters (Image Info) Improvements

### ISSUE THREAD

**Issue by Holyniwa** [vladmandic/automatic#471]
### Feature description

I do wish the entire parameters tab (image info) would be redesigned in way that was more legible (adding a line break and space between the prompt parameters, negative parameters, and image settings), but for now, would it be a simple task to include which vae was used in an image generation?/write into parameters which vae is used for future generations?
if not, i understand that there are more pressing issues to resolve.

**Comment by vladmandic** [comment]
done (both items).
