### ISSUE TITLE
[Feature]: Add "None" option to LyCORIS dropdown

### ISSUE THREAD

**Issue by brunogcar** [vladmandic/automatic#474]
### Issue Description

Add LyCORIS to prompt dropdown  - sd_lyco 

as A1111 doesnt support lyco, original PR didnt cover Add LyCORIS to prompt dropdown  - sd_lyco 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9723
https://github.com/vladmandic/automatic/pull/383

just to :
Add hypernetwork to prompt - sd_hypernetwork
Add Lora to prompt - sd_lora

### Version Platform Description

Version: 023e13b3714d34b02de5d23fcdb6cb3e5f63e5ab

**Comment by vladmandic** [comment]
`sd_lyco` option is maintained by extension `a1111-sd-webui-lycoris`, so feature request should be made there.
if i made changes in this repo, then extension update would no longer be possible as it would be out-of-sync with local changes.
