### ISSUE TITLE
[Feature]: Some method of supporting different users without duplicating data directory

### ISSUE THREAD

**Issue by crazygonuts** [vladmandic/automatic#477]
### Feature description

For context, I would like to be able to launch a version of automatic that only has a limited subset of my checkpoints / loras / lycoris / etc, so that i can allow my kids to generate images using checkpoints that are unlikely to generate NSFW results.  Automatic1111 didn't support this in a great way, but since I could specify each data directory directly on the command line I was able to set up different .bat launchers that pointed to different checkpoint/lora/lycoris/etc directories but all still used the same directories for other data like controlnet, vae, upscalers, extensions, etc.

As far as I can tell to get the same behavior on vladmandic I would need to set up different backup config.json for each user and then copy it over the actual config before running launch.py, and even that method would mean any time i change a setting i would need to duplicate that change in the other jsons.

Can we bring some kind of user profile support?  Even if it was just to bring back the --ckpt-dir/--lora-dir/etc command flags that probably suffice.

Thanks.

**Comment by Ancanus** [comment]
You could fork the installation and soft-link the subset of resources you want.

**Comment by crazygonuts** [comment]
> You could fork the installation and soft-link the subset of resources you want.

so i would move the checkpoints/loras into a 3rd location, point my config in the 1st install at that location, fork the installation and soft-link it back to the original data directory, and then have the 2nd install config point at a 4th location with different models?  Am I following correctly?

**Comment by vladmandic** [comment]
you can specify which `config.json` you want to use with hidden cmdline flag `--ui-settings-file`.
anything more than that would require adding proper multi-user workflows - that does sound like a more than a valid feature request, but due to nature of tons of legacy code, it would be anything but simple to implement.
