### ISSUE TITLE
[Issue]: When selecting a TI from the GUI, it adds the file extension to the prompt as well.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [vladmandic/automatic#481]
### Issue Description

In the GUI, under "Textual Inversion" tab, the names of the TIs all have the .pt extension, and clicking on them also adds then extension to the prompt. The Loras do not show the extension and do not add it to the prompt.

### Version Platform Description

Version: 023e13b3 Mon Apr 24 19:20:48 2023 -0400
Windows 11
Chrome

**Comment by vladmandic** [comment]
extension or not, thats not how adding embedding is interpreted when added to prompt, see #304 for details.

**Comment by GalaxyTimeMachine** [comment]
I think you misunderstood the reported bug. The UI wasn't working as expected. It has started doing it again after restarting and updating to: Upgraded to version: dcd6d5bf Tue Apr 25 08:04:43 2023 -0400

The images show the names of TIs all end with .pt (extension shouldn't be shown).
![image](https://user-images.githubusercontent.com/52193044/234280052-cc906345-67f8-4c8e-9650-43d0de02d852.png)

Selecting one of the TIs adds it to the prompt, with the .pt extension (it should not include the .pt as this was not what is loaded on start):
![image](https://user-images.githubusercontent.com/52193044/234280591-1f7e055d-31f6-4976-b961-cd7a68311162.png)

**Comment by vladmandic** [comment]
ok, i'll remove extensions.
