### ISSUE TITLE
[Issue]: An error occurs when the DAAM Extension is executed

### ISSUE THREAD

**Issue by toyxyz** [vladmandic/automatic#482]
### Issue Description

An error occurs when the DAAM Extension is executed.

https://github.com/toriato/stable-diffusion-webui-daam

Loading weights: G:\SD_Model\Ckpt\Illustration\CounterfeitV25_25.safetensors ----------------------- 0.0/4.3 GB -:--:--
Creating model from config: C:\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading weights: G:\SD_Model\VAE\kl-f8-anime2.ckpt ---------------------------------------- 0.0/404.7 MB -:--:--
Applying scaled dot product cross attention optimization
Embeddings loaded: AuroraNegative, bad-artist-anime, bad-artist, badhandv4, bad_prompt, bad_prompt_version2,
CharTurner, CharTurnerV2, EasyNegative, KHFB, NG_DeepNegative_V1_75T, PureErosFace_V1, ulzzang-6500 (13)
Model loaded in 5.0s (load=0.6s create=0.4s apply=0.8s vae=0.9s move=1.1s embeddings=1.2s)
Startup time: 37.6s (torch=5.6s gradio=2.1s libraries=1.4s models=0.2s codeformer=0.2s scripts=13.9s ui=8.3s start=0.6s
scripts app_started_callback=0.1s checkpoint=5.2s)
Running script process batch: C:\automatic\extensions\stable-diffusion-webui-daam\scripts\daam_script.py:
AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\automatic\modules\scripts.py:438 in process_batch                                                                │
│                                                                                                                     │
│   437 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 438 │   │   │   │   script.process_batch(p, *script_args, **kwargs)                                               │
│   439 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ C:\automatic\extensions\stable-diffusion-webui-daam\scripts\daam_script.py:145 in process_batch                     │
│                                                                                                                     │
│   144 │   │                                                                                                         │
│ > 145 │   │   prompt_analyzer = utils.PromptAnalyzer(embedder, styled_prompt)                                       │
│   146 │   │   self.prompt_analyzer = prompt_analyzer                                                                │
│                                                                                                                     │
│ C:\automatic\extensions\stable-diffusion-webui-daam\scripts\daam\utils.py:265 in __init__                           │
│                                                                                                                     │
│   264 │   def __init__(self, clip : FrozenCLIPEmbedderWithCustomWordsBase, text : str):                             │
│ > 265 │   │   use_old = opts.use_old_emphasis_implementation                                                        │
│   266 │   │   assert not use_old, "use_old_emphasis_implementation is not supported"                                │
│                                                                                                                     │
│ C:\automatic\modules\shared.py:510 in __getattr__                                                                   │
│                                                                                                                     │
│   509 │   │                                                                                                         │
│ > 510 │   │   return super(Options, self).__getattribute__(item)                                                    │
│   511                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Options' object has no attribute 'use_old_emphasis_implementation'
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.57it/s]
Running script postprocess: C:\automatic\extensions\stable-diffusion-webui-daam\scripts\daam_script.py: TypeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ C:\automatic\modules\scripts.py:446 in postprocess                                                                  │
│                                                                                                                     │
│   445 │   │   │   │   script_args = p.script_args[script.args_from:script.args_to]                                  │
│ > 446 │   │   │   │   script.postprocess(p, processed, *script_args)                                                │
│   447 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ C:\automatic\extensions\stable-diffusion-webui-daam\scripts\daam_script.py:189 in postprocess                       │
│                                                                                                                     │
│   188 │   │                                                                                                         │
│ > 189 │   │   for trace in self.tracers:                                                                            │
│   190 │   │   │   trace.unhook()                                                                                    │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: 'NoneType' object is not iterable

### Version Platform Description

window 10, edge
 Version: 023e13b3 Mon Apr 24 19:20:48 2023 -0400

**Comment by vladmandic** [comment]
fixed.
