### ISSUE TITLE
[Issue]: Git file ownership issues

### ISSUE THREAD

**Issue by tangtaojim** [vladmandic/automatic#483]
### Issue Description

Tried to reinstall the GIT error remains, help solve the problem, please

                 
 ERROR    Error running pip: install --upgrade
                         git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1

 ERROR    Error running git: D:\automatic\repositories\stable-diffusion-stability-ai / checkout
                    
 ERROR    Error running git: D:\automatic\repositories\taming-transformers / checkout
                      

ERROR    Error running git: None / submodule --quiet update --init --recursive

### Version Platform Description

Python 3.10.11 on Windows
Version: 98adfb3 Sun Apr 23 11:50:30 2023 -0400

Windows 11 build 23440,ni_prerelease.230414-1348

**Comment by vladmandic** [comment]
upload `setup.log` here as attachment.

**Comment by vladmandic** [comment]
which GIT are you using? it doesn't seem like a normal git, it misinterprets most of commands.
and whats the version: `git --version`?

**Comment by tangtaojim** [comment]
git version 2.40.0.windows.1

**Comment by vladmandic** [comment]
this is weird, its almost like something is changing git commands on-the-fly.
where did you install git from?

for example, in `setup.log`:

    Running command git clone --filter=blob:none --quiet https://github.com/openai/CLIP.git 'C:\Users\tangt\AppData\Local\Temp\pip-req-build-najmog28'
    warning: filtering not recognized by server, ignoring

    Running command git fetch -q https://github.com/openai/CLIP.git d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
    error: Server does not allow request for unadvertised object d50d76daa670286dd6cacf3bcd80b5e4823fc8e1

the thing is, my installer did not set `--filter` param and it doesn't send any explict `fetch` commands

**Comment by vladmandic** [comment]
can you run `git config -l` to see what is your global git config?

**Comment by tangtaojim** [comment]
ok，On the official git website
C:\Users\tangt>git config -l
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
url.https://gitclone.com/github.com.insteadof=https://github.com
safe.directory=*

**Comment by tangtaojim** [comment]
How to do to block the interference items?Thank you for your patience

**Comment by tangtaojim** [comment]
Maybe I should re-download a new git. maybe it will solve the problem

**Comment by PsiClone99** [comment]
> Maybe I should re-download a new git. maybe it will solve the problem

Tried a clean instal, does not work, same error

**Comment by vladmandic** [comment]
@tangtaojim reinstalling git wont help, those settings are written in your git config which persists. Why is that setting there, I don't know. Typically, they are stored in `~/.gitconfig` or `%USERPROFILE%\.gitconfig`

@PsiClone99 "mee too" type of a post does not help EVER! Provide actual console log and `setup.log`

**Comment by PsiClone99** [comment]
> @tangtaojim reinstalling git wont help, those settings are written in your git config which persists. Why is that setting there, I don't know. Typically, they are stored in `~/.gitconfig` or `%USERPROFILE%\.gitconfig`
> 
> @PsiClone99 "mee too" type of a post does not help EVER! Provide actual console log and `setup.log`

Sorry for that, I am attaching my Setup log file
[setup.log](https://github.com/vladmandic/automatic/files/11326350/setup.log)

**Comment by vladmandic** [comment]
@PsiClone99 From your `setup.log`, you had bigger issues than noted. 

> Could not resolve host: github.com

And yes, they may have been temporary and gone by now, but why not check `setup.log` yourself? Launcher actually says to check if there are any errors.

**Comment by PsiClone99** [comment]
> @PsiClone99 From your `setup.log`, you had bigger issues than noted.
> 
> > Could not resolve host: github.com
> 
> And yes, they may have been temporary and gone by now, but why not check `setup.log` yourself? Launcher actually says to check if there are any errors.

Yes it is working now, I did a TCP and IP reset and it worked after that.
Thanks for the fast response and feedback, sorry if it caused any unnecessary trouble, Cheers!

**Comment by tangtaojim** [comment]
C:\Users\tangt>git config -l
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/etc/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
safe.directory=*


I changed the local configuration again, but the redeployment still gives the same problem or even more errors
[setup.log](https://github.com/vladmandic/automatic/files/11328847/setup.log)

**Comment by tangtaojim** [comment]
@vladmandic 
@PsiClone99 

Thanks for the fast response and feedback

**Comment by vladmandic** [comment]
@tangtaojim ouch, that is hard. not sure what i can do to help :(

**Comment by tangtaojim** [comment]
> @tangtaojim ouch, that is hard. not sure what i can do to help :(

Thank you. Maybe there can be a comprehensive installer in the future. Aha, you're amazing.

**Comment by vladmandic** [comment]
offline version that can be downloaded without requiring github at all - yes, on my radar. but pointless to make while repo is moving so fast daily.

**Comment by tangtaojim** [comment]
Yes, you are right, 
Maybe you could have a basic integrated package and then automatically sync the latest version after each launch, the user could choose whether to sync or not, this would require a launcher that could integrate options to provide optional features based on the detected user configuration, the stable diffuser I'm using now uses a similar launcher that solves most of the launch issues. 
The launcher will jump directly to the browser so the user only needs to experience your features and not be concerned with programming issues, I think this will massively increase the number of users like me and lower the barrier to use, 
just my little thoughts, don't worry, Thanks again

**Comment by thebleak13** [comment]
Hello, 

I recently ran into this same issue and after reviewing logs, configs, and etc.... the only way I was able to fully correct this problem was to **delete all of the files in my project folder and reinstall fresh**. I did find another post about this issue under the automatic project. 

How I ran into this problem
After I installed the webui, it all worked but when I restarted the app, it was yelling at me because I was on python 3.11. So, I downgraded my python and ever since I received the CLIP issue. 

- git version 2.40.0.windows.1
- python-3.10.6

btw, shout-out to the team working on this project. You ROCK!

**Comment by tangtaojim** [comment]
@thebleak13 
I tried everything I could, and I completely emptied the project files, but it didn't work, and it was frustrating, yes, I agree with you, everyone working on this project is fantastic,

**Comment by Juafeis** [comment]
I'm having a somewhat similar problem, but with "detected dubious ownership" being prompted as well (log attached). Is it normal that i have to enable so many safe.directory ?
[setup.log](https://github.com/vladmandic/automatic/files/11351886/setup.log)

**Comment by vladmandic** [comment]
@Juafeis each entry is basically a sub-repository (original a1111 only has one master repo and no subrepositories).
but bigger question is why are ownerships not set correctly to start with so you need to mark them safe manually?

**Comment by Juafeis** [comment]
> @Juafeis each entry is basically a sub-repository (original a1111 only has one master repo and no subrepositories). but bigger question is why are ownerships not set correctly to start with so you need to mark them safe manually?

Yeah, that's a good question, only using " directory = '*' "  doesn't fix the issue.

**Comment by eyeweaver** [comment]
I'm having the same problem with one of my machines.. it's working fine on the other two .. the only difference is that on the machine with the problem I have an antivirus installed.. it's Kaspersky.. could an antivirus cause this?

**Comment by vladmandic** [comment]
a quick follow-up, when you're on windows wildcard for git must not be quoted. and best not to edit git configuration file manually - instead use

> git config --global safe.directory *

now, on why ownership appears as wrong to start with, well....NTFS clearly states that it really is different:
> 'L:/StableDiffusion/automatic/extensions-builtin/a1111-sd-webui-lycoris' is owned by:  'S-1-5-32-544'
> but the current user is: 'S-1-5-21-3438296884-308912500-242138028-1001'

maybe you can look-up those SIDs in Windows and see what they map to?
also, such errors can be if git for windows is operating on a filesystem it doesn't understand. for example, if that drive/folder is a network share or a mount with a different filesystem type, etc...

and yes, might be antivirus as well. i've seen AV software do that, but those are mostly nighmare stories from 20 years ago, i haven't seen any AV being THAT broken anymore.

other than that, i'm not sure how else i can help here...

let me know how you want to proceed?

**Comment by vladmandic** [comment]
any updates?

**Comment by tangtaojim** [comment]
Yes ，my SID is different ，Do they need to be modified?
S-1-5-21-3342592805-3737107488-2980880155-1002
Thanks for the feedback 



> a quick follow-up, when you're on windows wildcard for git must not be quoted. and best not to edit git configuration file manually - instead use
> 
> > git config --global safe.directory *
> 
> now, on why ownership appears as wrong to start with, well....NTFS clearly states that it really is different:
> 
> > 'L:/StableDiffusion/automatic/extensions-builtin/a1111-sd-webui-lycoris' is owned by:  'S-1-5-32-544'
> > but the current user is: 'S-1-5-21-3438296884-308912500-242138028-1001'
> 
> maybe you can look-up those SIDs in Windows and see what they map to? also, such errors can be if git for windows is operating on a filesystem it doesn't understand. for example, if that drive/folder is a network share or a mount with a different filesystem type, etc...
> 
> and yes, might be antivirus as well. i've seen AV software do that, but those are mostly nighmare stories from 20 years ago, i haven't seen any AV being THAT broken anymore.
> 
> other than that, i'm not sure how else i can help here...
> 
> let me know how you want to proceed?

**Comment by vladmandic** [comment]
> Yes ，my SID is different ，Do they need to be modified?

That's up to you - I don't know which one is correct or not?

**Comment by tangtaojim** [comment]
Thank you for your long attention and response,

**Comment by SilkySnarks** [comment]
Hey all,
I had the same issue - was able to fix it by running takeown /F "<path-to-automatic-folder>" /R /D Y in CMD
Note that modifying ownership and permissions should be done carefully, as it can have unintended side effects.
You might need to run icacls command(was not neccesery for me).
Let me know if this solves the issue for you.
