### ISSUE TITLE
[Issue]: The sampler list has reverted since yesterday.

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [vladmandic/automatic#484]
### Issue Description

I did an update yesterday (can't remember which version) that added more samplers to the list. The update this morning seems to have reduced the list back to what it was before.

### Version Platform Description

Version: 023e13b3 Mon Apr 24 19:20:48 2023 -0400
Win 11
Chrome

**Comment by vladmandic** [comment]
i've merged a user pr that suggested to use "show samplers" (as positive list) instead of "hide samplers" (negative list).
as a result, list of default samplers is reset. you want to add more samplers to be visible, just go to ui settings and enable them.

**Comment by JanPono** [comment]
> 

this is somehow broken ... I failed to add some samplers in txt2img via settings. After clean install same problem - unable to add more than defaults...

**Comment by vladmandic** [comment]
just tried, works fine. but you need to restart server afer adding a sampler and applying settings as samplers are enumerated during server startup.
