### ISSUE TITLE
[Issue]: Something went wrong Unexpected token '<', "<html> <h"... is not valid JSON

### ISSUE THREAD

**Issue by ShadeRedeye** [vladmandic/automatic#487]
### Issue Description

using --disable-queue args to avoid a image preview problem like this #394 and it looks like it make another problem such like this

console log (also show up in UI)
![Screenshot_2](https://user-images.githubusercontent.com/84408428/234296785-f1f5e63a-2764-4d7a-a3ed-e077d3ba492e.png)

![Screenshot_1](https://user-images.githubusercontent.com/84408428/234297262-9c05c5b9-54d1-4c4d-b83a-9b80f1f248d3.png)

looking to the network and there predict that show up like this
![Screenshot_3](https://user-images.githubusercontent.com/84408428/234297776-f0398ab8-0a69-44e6-a21c-39d62918e631.png)

use launch.py and there no prob during installation

i can't explain it too much since only a message like that show up, 

### Version Platform Description

Linux,
Cloud Service : Paperspace use --share args 
Google Browser ver 112.0.5615.138 
APP version: dcd6d5bf562c0e731dee5f5bd4c91f950ba298dd
2023-04-25T12:04:43Z

**Comment by vladmandic** [comment]
disable-queue should NOT be used to solve #394.
and in general, it should not be used unless for very specific diagnostic purposes. any issue with disable-queue will not be analyzed.
