### ISSUE TITLE
[Issue]: Repetitive desktop notifications on page refresh

### ISSUE THREAD

**Issue by Jon-dog** [vladmandic/automatic#488]
### Issue Description

The default generation (the A logo) triggers like 3 separate notifications on startup.
Is there a way to disable this? I'd rather not disable desktop notifications entirely.

### Version Platform Description

Version: dcd6d5bf Tue Apr 25 08:04:43 2023 -0400
Browser: Firefox
OS: Windows 11

**Comment by vladmandic** [comment]
Continuing in #495
