### ISSUE TITLE
[Issue]: AttributeError: 'Options' object has no attribute 'lora_apply_to_outputs'

### ISSUE THREAD

**Issue by alex-des-santos** [vladmandic/automatic#491]
### Issue Description

I can't apply any lora, getting this message:

AttributeError: 'Options' object has no attribute 'lora_apply_to_outputs'

Here a screenshot.:

![image](https://user-images.githubusercontent.com/122044206/234352375-cfef5710-08e2-4599-9895-e15b4d52d834.png)

### Version Platform Description

Browser: Microsoft Edge
OS: Windows 11 22H2

**Comment by vladmandic** [comment]
duplicate #225 
that extension needs to be updated, i'm open to add compatibility to any extension that looks for valid options that i may have removed, but not to extensions that look up options that don't exist.
