### ISSUE TITLE
[Issue]: Clip Skip exists in multiple places and can indicate different values

### ISSUE THREAD

**Issue by crazygonuts** [vladmandic/automatic#494]
### Issue Description

Clip Skip exists in settings->Stable Diffusion, but it is also on the UI for each individual kind of generation (text2img, img2img, etc).  The value in settings does not change on reload, as it comes from the config.json, but the value on the generation windows defaults to 1 on every reload.  This leads to the case where clip skip is set to 2 in settings and 1 in txt2image when you generate.  I assume it uses the one on the generation ui, in which case the settings version seems vestigial.

It would be potentially better if the settings value was a default for all the generation UIs since clip skip 2 is the default for so many models, not 1.

**Comment by crazygonuts** [comment]
after messing around with this a bit, my best guess is that it uses the clip skip value from the settings and not the one on the generation ui, until you change the one on the ui, then it will use that one.  

example steps:

1. using a fixed seed.
2. settings says clip skip == 2
3. txt2img ui defaults to 1
4. click generate, take note of image
5. change "clip skip" to 2 on txt2img ui
6. click generate - notice that the image is the same
7. change clip skip back to 1 on txt2img ui
8. notice that the image is now different

**Comment by vladmandic** [comment]
yeah, its a bug and i need to fix it.
