### ISSUE TITLE
[Feature]: torch: 1.13.1+cu117

### ISSUE THREAD

**Issue by DevArqSangoi** [vladmandic/automatic#501]
### Feature description

Just want the possibility to use "torch: 1.13.1+cu117", 2.0.0 with cuda 118 and no xformers get a lot worse in my ancient gtx970.

**Comment by vladmandic** [comment]
if you have torch already installed, this repo will not change it, it will just try to use whatever you have.
did you try before creating a feature request?

yes, if you uninstall torch, it will try to install what it things is best and that would be torch 2.0 + cuda 11.8 + cudnn 8.7.

**Comment by DevArqSangoi** [comment]
> if you have torch already installed, this repo will not change it, it will just try to use whatever you have. did you try before creating a feature request?
> 
> yes, if you uninstall torch, it will try to install what it things is best and that would be torch 2.0 + cuda 11.8 + cudnn 8.7.

I have 3 SD UI here, they use venv, a1111 default use 1.13, yours use 2.0.0 and anapnoe use 1.13. I opened this request because your repo installs the dependencies inside the venv, and I couldn't find where to change to install 1.13 instead of 2.0

**Comment by vladmandic** [comment]
just set env variable `TORCH_COMMAND` before first start and it will install whatever torch you want.
default value is `torch torchaudio torchvision --index-url https://download.pytorch.org/whl/cu118`

**Comment by DevArqSangoi** [comment]
I really don't like this kind o workaround or w/e, then I just went again check the files and found that torch version is inside the setup.py. Thanks.

**Comment by vladmandic** [comment]
that's not a workaround, that is exactly what setup.py does. what would you prefer a solution to be?

**Comment by DevArqSangoi** [comment]
I thought that you meant to include the 'torch' command in something like 'webui-user.bat' like the original 'a1111', so that 'pip install' would run every time I start the SD.

**Comment by vladmandic** [comment]
uninstall torch if its already installed, set which torch you want to use with (for example):
> set TORCH_COMMAND="torch torchaudio torchvision --index-url https://download.pytorch.org/whl/cu118"
and start webui, it will install that one instead of the one it thinks its best.
