### ISSUE TITLE
Mac M1 Ultra: Python crash on first run

### ISSUE THREAD

**Issue by moebis** [vladmandic/automatic#504]
### Issue Description

Tried to generate an image after default install and I get this in the console:

automatic % /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

And this in a crashed python dialog:

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Python [74613]
Path:                  /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/Resources/Python.app/Contents/MacOS/Python
Identifier:            com.apple.python3
Version:               3.9.6 (3.9.6)
Build Info:            python3-133100001001000~131
Code Type:             ARM-64 (Native)
Parent Process:        zsh [74546]
Responsible:           Terminal [21223]
User ID:               501

Date/Time:             2023-04-25 22:10:22.5407 +0200
OS Version:            macOS 13.3.1 (22E261)
Report Version:        12
Anonymous UUID:        CA07BCE3-E8E4-1E87-BF10-331E44001AB6

Time Awake Since Boot: 370000 seconds

System Integrity Protection: enabled

Crashed Thread:        40  Dispatch queue: cache queue

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Thread 0::  Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	       0x19947eff0 __select + 8
1   Python3                       	       0x1028b62e4 0x102710000 + 1729252
2   Python3                       	       0x1027937c4 0x102710000 + 538564
3   Python3                       	       0x102822604 0x102710000 + 1123844
4   Python3                       	       0x10281f754 _PyEval_EvalFrameDefault + 22644
5   Python3                       	       0x102751010 0x102710000 + 266256
6   Python3                       	       0x102822604 0x102710000 + 1123844
7   Python3                       	       0x10281f754 _PyEval_EvalFrameDefault + 22644
8   Python3                       	       0x1028234ac 0x102710000 + 1127596
9   Python3                       	       0x102819e18 PyEval_EvalCode + 80
10  Python3                       	       0x10285de54 0x102710000 + 1367636
11  Python3                       	       0x10285e028 0x102710000 + 1368104
12  Python3                       	       0x10285c154 PyRun_SimpleFileExFlags + 820
13  Python3                       	       0x1028792b0 Py_RunMain + 1604
14  Python3                       	       0x102879720 0x102710000 + 1480480
15  Python3                       	       0x1028797c0 Py_BytesMain + 40
16  dyld                          	       0x19915bf28 start + 2236

### Version Platform Description

Mac OS (latest)

**Comment by vladmandic** [comment]
closing in favor of #347
