### ISSUE TITLE
[Issue]: after first generation, it takes a while for the image to finish loading on the UI

### ISSUE THREAD

**Issue by gsgoldma** [vladmandic/automatic#506]
### Issue Description

This only occurs with the first image that the program makes. All the subsequent ones immediately load into the UI. 

This is not the initialization at the beginning, but after the image shows 100% completion in the console, it may take 20-30 seconds for it to update onto the WebUI.

### Version Platform Description

Windows 10

**Comment by jvivian** [comment]
@gsgoldma - are you by chance using WSL2? I had that problem but after changing some of the CUDA settings and doing the latest `git pull` I no longer have the problem. What CUDA settings are you using?

**Comment by gsgoldma** [comment]
11.8 cuda, no wsl2

**Comment by inck86** [comment]
> image shows 100% completion in the console, it may take 20-30 seconds

Have same trouble

**Comment by jvivian** [comment]
Do either of you have the CUDA option `Enable cuDNN benchmark feature` enabled? Try disabling that or the `Use channels last as torch memory format` option.

**Comment by gsgoldma** [comment]
> Do either of you have the CUDA option `Enable cuDNN benchmark feature` enabled? Try disabling that or the `Use channels last as torch memory format` option.

Yes, and that worked- thank you! it reduced the time of the initialization before hand too!

**Comment by inck86** [comment]
> Try disabling that

Confirm, it helped! Thanks!

**Comment by vladmandic** [comment]
do note that feature `Enable cuDNN benchmark` is disabled for a reason - what it does is tell CUDA to try all different options on how to optimize math operations before selecting best one - so its totally expected that initial execution will have a delay (while CUDA is actually internally benchmarking itself)

is there anything else to be done in this issue?

**Comment by inck86** [comment]
> is there anything else to be done in this issue?

Is it possible to organize a one-time benchmark programmatically with the recording of tests and their subsequent use? does it make sense to look for the best option on the same hardware every time?

**Comment by vladmandic** [comment]
that is a totally valid request and i have that conversation open with torch team :)
its not something that can be done on app level.

**Comment by vladmandic** [comment]
depending on circumstances, it will run benchmark before/during/after, they all trigger different torch operations.
also depends on which sampler you use - for example, unipc triggers denoiser at the end only, so if benchmark is optimizing ops inside denoiser, it will apear slow/stuck near the end only.
