### ISSUE TITLE
[Issue]:  Attirbute error trying to run an inference /w Lora.

### ISSUE THREAD

**Issue by bbecausereasonss** [vladmandic/automatic#507]
### Issue Description

AttributeError: 'Options' object has no attribute 'lora_apply_to_outputs'
Time taken: 0.13sTorch active/reserved: 4579/4658 MiB, Sys VRAM: 7644/24564 MiB (31.12%)

>
AttributeError: 'Options' object has no attribute 'lora_apply_to_outputs'
Available models: C:\Users\vdrut\Deep\automatic\models\Stable-diffusion 140
gradio call: AttributeError
╭────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\xxxx\Deep\automatic\modules\call_queue.py:58 in f                                                           │
│                                                                                                                       │
│    57 │   │   │   │   pr.enable()                                                                                     │
│ ❱  58 │   │   │   res = list(func(*args, **kwargs))                                                                   │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                         │
│                                                                                                                       │
│ C:\Users\xxxx\Deep\automatic\modules\call_queue.py:38 in f                                                           │
│                                                                                                                       │
│    37 │   │   │   try:                                                                                                │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                     │
│    39 │   │   │   finally:                                                                                            │
│                                                                                                                       │
│                                               ... 25 frames hidden ...

### Version Platform Description

Windows 11, Chrome, Latest commit

**Comment by vladmandic** [comment]
duplicate. search for `lora_apply_to_outputs`

**Comment by bbecausereasonss** [comment]
So it's still broken and you need more info to fix it? I'm confused.

**Comment by vladmandic** [comment]
what did the search show? its a broken extension that i have no intention of making extra rule to make it work.
it tries to read options value that doesn't exist. so contact extension author if you really want that extension.

**Comment by bbecausereasonss** [comment]
The lora extension? The one that's baked into the interface? Or is it a different extension. Sorry I was unable to understand which one it was causing the issue.

**Comment by vladmandic** [comment]
see <https://github.com/vladmandic/automatic/issues/225#issuecomment-1515067698>
