### ISSUE TITLE
[Issue]: Error loading 2.1 Loras

### ISSUE THREAD

**Issue by fabiobtex** [vladmandic/automatic#509]
### Issue Description

Not being able to load 2.1 Loras. **1.5 Loras works normally**

Error activating extra network lora with arguments [<modules.extra_networks.ExtraNetworkParams object at
0x0000028865AA5B40>]: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\extra_networks.py:75 in activate                                                                │
│                                                                                                                      │
│    74 │   │   try:                                                                                                   │
│ ❱  75 │   │   │   extra_network.activate(p, extra_network_args)                                                      │
│    76 │   │   except Exception as e:                                                                                 │
│                                                                                                                      │
│ D:\automatic\extensions-builtin\Lora\extra_networks_lora.py:23 in activate                                           │
│                                                                                                                      │
│   22 │   │                                                                                                           │
│ ❱ 23 │   │   lora.load_loras(names, multipliers)                                                                     │
│   24                                                                                                                 │
│                                                                                                                      │
│ D:\automatic\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora.py:214 in load_loras       │
│                                                                                                                      │
│   213 │   │   │   if lora is None or os.path.getmtime(lora_on_disk.filename) > lora.mtime:                           │
│ ❱ 214 │   │   │   │   lora = load_lora(name, lora_on_disk.filename)                                                  │
│   215                                                                                                                │
│                                                                                                                      │
│ D:\automatic\extensions-builtin\a1111-sd-webui-lycoris\..\..\extensions-builtin/Lora\lora.py:176 in load_lora        │
│                                                                                                                      │
│   175 │   │   with torch.no_grad():                                                                                  │
│ ❱ 176 │   │   │   module.weight.copy_(weight)                                                                        │
│   177                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: output with shape [100, 320] doesn't match the broadcast shape [100, 320, 100, 320]

**The image is generated normally but with no lora effects**

**Comment by vladmandic** [comment]
if you have an issue with a specific lora, please provide link to model, link to lora and exact prompt. not much i can do based on info provided.

**Comment by fabiobtex** [comment]
> if you have an issue with a specific lora, please provide link to model, link to lora and exact prompt. not much i can do based on info provided.

https://civitai.com/models/8765/theovercomer8s-contrast-fix-sd15sd21-768

The 2.1 version

Then a downloaded another to test:

https://civitai.com/models/36911/reuben-wu-style-lora

Model hash: 4ee4331304, Model: (2.1)artiusV21_v21, ENSD: 33373 https://civitai.com/models/27739/artius-v21
I also tested with others

**Comment by vladmandic** [comment]
Thanks.
Any extensions you have here and in A1111?

**Comment by fabiobtex** [comment]
> Thanks. Any extensions you have here and in A1111?

I have an huge list in auto1111
![image](https://user-images.githubusercontent.com/125583939/234437466-18531338-32b4-4237-b042-086ebe6258f9.png)

I only installed ultimate-upscale- here

**Comment by vladmandic** [comment]
thanks. that should be enough information for me.

**Comment by vladmandic** [comment]
ok, finally found few min to go back to this.

a1111 by itself does not support 2.1 loras. but you have `a1111-sd-webui-locon` extension which patches a1111 built-in lora support, so it "just works". however, that method of patching is prone to errors (single namespace "lora" is handled by two different networks). for that reason, author of `a1111-sd-webui-locon` actually **obsoleted** that extension and new one is `a1111-sd-webui-lycoris` - and that is already built-in here - so SD 2.1 loras are fully supported.

only difference is that you should use different namespace - so load it using `<lyco:filename:strength>` instead of `<lora:filename:strenght>`

i've tried exact lora you mentioned and works perfectly.
