### ISSUE TITLE
[Feature]: PNG Info/Scraper 

### ISSUE THREAD

**Issue by Shadowzeny** [vladmandic/automatic#512]
### Feature description

A1111 had this feature to allow it to pull meta data from image files by dragging/dropping images, much like the Image browser but allowed for files to be uploaded/drag and dropped on a whim. 
![Screenshot 2023-04-26 121237](https://user-images.githubusercontent.com/38971476/234448546-c8a5106d-f167-48e7-9fd8-6a049a83852a.png)

Example above from A1111

**Comment by vladmandic** [comment]
it exists and its even extended in functionality, just go to process image and drop image there, its more a unified workflow way of doing things.
