### ISSUE TITLE
[Issue]: Running webui.bat fails with ambiguous --api command line arg error message

### ISSUE THREAD

**Issue by brianjz** [vladmandic/automatic#514]
### Issue Description

The error appears whenever running webui.bat on Windows 10 with zero or more command line args.

No extra logging shows in setup.log as it never gets that far.

```
usage: launch.py [-h] [--medvram] [--lowvram] [--lowram] [--ckpt CKPT] [--vae VAE] [--data-dir DATA_DIR] [--models-dir MODELS_DIR] [--allow-code] [--share] [--enable-insecure]
                 [--use-cpu USE_CPU [USE_CPU ...]] [--listen] [--port PORT] [--hide-ui-dir-config] [--freeze-settings] [--gradio-auth GRADIO_AUTH] [--gradio-auth-path GRADIO_AUTH_PATH] [--autolaunch]
                 [--disable-console-progressbars] [--disable-safe-unpickle] [--api-auth API_AUTH] [--api-log] [--device-id DEVICE_ID] [--cors-origins CORS_ORIGINS] [--cors-regex CORS_REGEX]
                 [--tls-keyfile TLS_KEYFILE] [--tls-certfile TLS_CERTFILE] [--server-name SERVER_NAME] [--no-hashing] [--no-download-sd-model] [--profile] [--disable-queue] [--lyco-dir LYCO_DIR]
                 [--controlnet-dir CONTROLNET_DIR] [--controlnet-annotator-models-path CONTROLNET_ANNOTATOR_MODELS_PATH] [--no-half-controlnet] [--db-provider DB_PROVIDER] [--debug] [--reset]
                 [--upgrade] [--noupdate] [--skip-requirements] [--skip-extensions] [--skip-git] [--experimental]
launch.py: error: ambiguous option: --api could match --api-auth, --api-log
```

Tried to see if a recent change from earlier today affected this, since an earlier commit worked fine, but I couldn't track anything down.

### Version Platform Description

Python 3.10.6 on Windows
Version: 2453139

**Comment by myndxero** [comment]
Standard --api flag you may be used to from auto1111 doesn't work. There's api-auth you could try. What are you needing api for? -listen will give you remote access to your desktop running stable, assuming you've the ports opened in any firewall.

**Comment by brianjz** [comment]
I have not used the --api flag. I used no flags and received the error.

**Comment by vladmandic** [comment]
is your `webui.bat` unmodified and from this repo? are you running it from command prompt or via shortcut? if via shortcut, check shortcut properties.

**Comment by brianjz** [comment]
Interesting. It was an unmodified webui.bat run from the cmd prompt directly, except for updating the VENV directory, but it worked fine until yesterday. I just restarted the CMD window and re-ran it and it worked. I don't know if something got cached weird, but I never ran across a Windows command window doing something like that. I apologize for not trying the "turn it on and off again" step.
