### ISSUE TITLE
[Issue]: Black images after running V1111

### ISSUE THREAD

**Issue by Bodzijun** [vladmandic/automatic#519]
### Issue Description

After I switched to xformers and run webui for the first time, all images are rendered black.
But as soon as I change the model, the rendering proceeds normally. That is, the failure occurs only with the original model running under xformers, after reloading it all works fine

### Version Platform Description
Win 11, Edge
hash: 24531398

**Comment by Bodzijun** [comment]
Did the test on different models.  The problem occurs exclusively on certain models. (e.g. Edge of realism)

**Comment by vladmandic** [comment]
read through #374 and update there, that is an existing issue for everything about black images.
