### ISSUE TITLE
[Issue]: Authnetication errors during startup?

### ISSUE THREAD

**Issue by tusharbhutt** [vladmandic/automatic#523]
### Issue Description

Hello, whenever I start up the WebUI, it goes through the initial start, and then after creating the public link, I get this stream of errors:

To create a public link, set `share=True` in `launch()`.
Initializing middleware
API error: GET: http://localhost:24278/file=script.js?1682385475.5314631 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: http://localhost:24278/file=javascript/aspectRatioOverlay.js?1682385475.3717277 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: http://localhost:24278/file=javascript/contextMenus.js?1682385475.3767393 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: http://localhost:24278/file=javascript/dragdrop.js?1682385475.3767393 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: http://localhost:24278/file=javascript/edit-attention.js?1682385475.381773 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: http://localhost:24278/file=javascript/extensions.js?1682385475.381773 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: http://localhost:24278/file=extensions-builtin/stable-diffusion-webui-images-browser/javascript/image_browser.js?1682386321.9224555 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: http://localhost:24278/file=extensions/Config-Presets/javascript/config_presets.js?1682389972.6128163 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: http://localhost:24278/file=extensions/sd-dynamic-prompts/javascript/dynamic_prompting.js?1682389866.8800104 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: http://localhost:24278/file=extensions/sd-dynamic-prompts/javascript/dynamic_prompting_hints.js?1682389866.8850322 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: http://localhost:24278/file=extensions/sd-webui-additional-networks/javascript/additional_networks.js?1682390004.5503862 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
API error: GET: http://localhost:24278/file=javascript/notification.js?1682517838.7030602 {'error': 'HTTPException', 'detail': 'Not authenticated', 'body': '', 'errors': ''}
Loading weights: C:\Applications\StableDiffusion\VladMandic\models\Stable-diffusion\Sourced\prmj_v1.safetensors

The program then continues to load the weights.  Not sure what the error is, and it doesn't seem to impact anything locally done. No errors show in the log file either, not that I can see anyway.  I did a search and no one else seems to have reported this, so thought you may want to know.  It seems related to user added extensions, but doesn't seem to interfere with their functionality.  Disabling extensions removes these error messages.

### Version Platform Description

Here is the version and OS info:

2023-04-26 08:57:41,026 | INFO | C:\Applications\StableDiffusion\VladMandic\setup.py | Python 3.10.6 on Windows
2023-04-26 08:57:41,169 | DEBUG | C:\Applications\StableDiffusion\VladMandic\setup.py | Git 2.38.0.windows.1
2023-04-26 08:57:42,039 | INFO | C:\Applications\StableDiffusion\VladMandic\setup.py | Version: 93b0de7e Wed Apr 26 09:02:32 2023 -0400

This has been appearing in previous commits too, rebooting/restarting has no impact.  Browser used is Firefox, but the issue is logged before it's launched.  I am on the latest version as of time of writing.

**Comment by ash368** [comment]
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9322

**Comment by vladmandic** [comment]
planning upgrade to gradio 3.28 once its available.

**Comment by vladmandic** [comment]
gradio has been upgraded to 3.28.1
