### ISSUE TITLE
[Issue]: CodeFormer error, not installed

### ISSUE THREAD

**Issue by wa2el** [vladmandic/automatic#526]
### Issue Description

16:56:00-752061 INFO     Installing repositories                                
16:56:47-138300 ERROR    Error running git: None / -C                           
                         "/content/drive/MyDrive/A1113/repositories/CodeFormer" 
                         checkout c5b4593074ba6214284d6acd5f1719b6c5d739af      
16:56:47-140723 ERROR    Local changes detected: check setup.log for details    

### Version Platform Description

using google colab

**Comment by vladmandic** [comment]
for google collab see #81 and #453
