### ISSUE TITLE
[Feature]: Show grid image by default after image generation

### ISSUE THREAD

**Issue by Aptronymist** [vladmandic/automatic#527]
### Feature description

Presently the UI (or at least mine always has) stays focused on the last image slot you were viewing when you generate new images. 
This doesn't make any sense if you're generating a batch, the UI should always show you the grid of images generated to give you an overview of what you made.

last image viewed after generation: (ignore elmo looking like he had genetic issues)
![firefox_9GlXynZVY1](https://user-images.githubusercontent.com/108482020/234659487-62d0bf51-e120-4fb4-8e09-32a280f5256c.png)

next generation, still on the same image, so you have to manually click on the grid:
![firefox_Gn1pX5aB9q](https://user-images.githubusercontent.com/108482020/234659671-feeea4c1-f63b-4271-99d5-369ee2e67aec.png)

**Comment by Aptronymist** [comment]
Oh, I'd love to see that bar with the thumbnails be larger too, it's pretty tiny.

**Comment by vladmandic** [comment]
section is whatever last selection was. so if you unselect image before running new batch, it will start as you want.
but regarding thumbnail sizes, i agree, i'll increase them a bit.
