### ISSUE TITLE
[Issue]: Process Image - Parameters broken

### ISSUE THREAD

**Issue by a2ZxgdqHeSs8F51cIyuK** [vladmandic/automatic#530]
### Issue Description

Hello,
sorry to bother you again with once again another issue on the image info function.
Now it's putting every single word in a newline, and also omitting some commas.
Image is using the same example girl from the previous issue I opened but I tried a bunch of images both recent and old and they all have the same issue.
https://files.catbox.moe/zmqjxc.png
If I send the image to txt2img or img2img it inputs the prompt correctly but as mentioned in issue #273 this behaviour breaks the ability to easily copy paste parts of the prompt.

### Version Platform Description

Version: 93b0de7e Wed Apr 26 09:02:32 2023 -0400
Windows 10
Tested on Firefox and Edge

**Comment by vladmandic** [comment]
fixed.
