### ISSUE TITLE
[Feature]: Add model files to a second drive/new directory

### ISSUE THREAD

**Issue by hirtelen** [vladmandic/automatic#531]
### Feature description

What do I do if some of the frequently used models are on my C drive and the rarely used ones are in the D/models folder (they don't fit on C). What do I have to type and where do I type it so that Vlad can find the second folder?

### Version Platform Description

Win 11, Vlad :-)

**Comment by vladmandic** [comment]
there is no way to have models split in two different locations at the moment.
i wanted to add it and it would be relatively easy for initial model load, but too many legacy code paths expect single string for model location. its in my backlog, but not with a high priority at the moment. i'm closing it as i'm already tracking it internally and no point of having feature request open for long periods without activity.
