### ISSUE TITLE
[Issue]: Default sampler list seems inconsistent

### ISSUE THREAD

**Issue by AlUlkesh** [vladmandic/automatic#536]
### Issue Description

The current list: https://github.com/vladmandic/automatic/blob/def7a02d82f4e7456177f3dbdf697dc7d02a3214/modules/shared.py#L433

has "DPM++ SDE" twice.

And I wonder how this list was chosen. I would think most people would want to use the newest samplers of each type, so perhaps
Euler a
DPM++ 2S a Karras
DPM++ 2M Karras
DPM++ SDE Karras
UniPC

### Version Platform Description

https://github.com/vladmandic/automatic/commit/def7a02d82f4e7456177f3dbdf697dc7d02a3214
Windows 10
Chrome

**Comment by vladmandic** [comment]
Valid question, but how is this an issue? I'm trying to keep bugs under control and this does not help. Why not create a discussion topic and when there is consensus, I'm totally open to update a default list.
