### ISSUE TITLE
[Bug]: Invalid requirement: 'clip_interrogator=0.6.0' (from line 2 of requirements_versions.txt)

### ISSUE THREAD

**Issue by ke1ne** [vladmandic/automatic#54]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Got that error during the installation. It's because of mistype in the requirements_versions.txt file.

clip_interrogator=0.6.0 should be changed to clip_interrogator==0.6.0

Cheers!

### Steps to reproduce the problem

Run installtion or update via the automatic.sh.

### What should have happened?

It had to install all requirements without errors.

### Commit where the problem happens

f275e43eb9a584358d2037d7ca276fd0315c48a3

### What platforms do you use to access the UI ?

Windows, Linux

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
nope
```

### List of extensions

nope

### Console logs

```Shell
ERROR: Invalid requirement: 'clip_interrogator=0.6.0' (from line 2 of requirements_versions.txt)
Hint: = is not a valid operator. Did you mean == ?

Installing requirements for Web UI
Traceback (most recent call last):
  File "/home/uuser/ai/automatic/launch.py", line 305, in <module>
    prepare_environment()
  File "/home/uuser/ai/automatic/launch.py", line 270, in prepare_environment
    run_pip(f"install -r \"{requirements_file}\"", "requirements for Web UI")
  File "/home/uuser/ai/automatic/launch.py", line 132, in run_pip
    return run(f'"{python}" -m pip {args} --prefer-binary{index_url_line}', desc=f"Installing {desc}", errdesc=f"Couldn't install {desc}")
  File "/home/uuser/ai/automatic/launch.py", line 100, in run
    raise RuntimeError(message)
RuntimeError: Couldn't install requirements for Web UI.
Command: "/home/uuser/ai/automatic/venv/bin/python" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stdout: <empty>
stderr: ERROR: Invalid requirement: 'clip_interrogator=0.6.0' (from line 2 of requirements_versions.txt)
Hint: = is not a valid operator. Did you mean == ?
```

### Additional information

none

**Comment by vladmandic** [comment]
you stumbled on it really fast - i fixed it about 1h later :)
