### ISSUE TITLE
[Feature]: PNGInfo for a single file needs to be added.

### ISSUE THREAD

**Issue by GeneralAwareness** [vladmandic/automatic#544]
### Issue Description

Image Browser needs a single file option such as a pnginfo (or a separate tab for it) input option as having thousands, to hundreds of thousands, of images on a HDD for a browser to scrape just grinds me down to almost crashing.

### Version Platform Description

Version: def7a02d on Windows 10.

**Comment by vladmandic** [comment]
search for it, its been asked 20+ times. hint: it exists and you don't need image browser for it.

**Comment by GeneralAwareness** [comment]
> search for it, its been asked 20+ times. hint: it exists and you don't need image browser for it.

I dead as I searched for port.  I searched for pnginfo and github search must suck ass juice because it didn't come up with either.

**Comment by vladmandic** [comment]
pnginfo functionality has been integrated into "process image", just load it there and full functionality is available.

**Comment by GeneralAwareness** [comment]
https://github.com/vladmandic/automatic/discussions/301#discussioncomment-5676382

I used Google search instead of github and found that  Damn, I really wouldn't have bothered you if I had found it but github searc really does suck.  Now time to find medvram and port as 7860 isn't going to cut it for me.
