### ISSUE TITLE
[Issue]: Black image on preview. 

### ISSUE THREAD

**Issue by asilvamaia** [vladmandic/automatic#545]
### Issue Description

21:02:07-153321 INFO     Version: def7a02d Wed Apr 26 16:08:56 2023 -0400

Atter click in generate, only a black box is show on preview box. Using a GTX 1650 4gb. Its work on other fork of Automatic1111. 
![Screenshot 2023-04-26 at 21-08-07 Stable Diffusion](https://user-images.githubusercontent.com/3327849/234728008-39513315-fa4b-4fd9-9d68-3a3aea75e006.png)

### Version Platform Description

Windows 11 - Ryzen 7 3750H - GTX 1650 - 16GB DDR4
21:02:06-576798 INFO     Python 3.10.9 on Windows
21:02:07-153321 INFO     Version: def7a02d Wed Apr 26 16:08:56 2023 -0400
21:02:07-624668 INFO     Setting environment tuning
21:02:07-624668 INFO     nVidia toolkit detected
21:02:10-636653 INFO     Torch 2.0.0+cu118
21:02:11-687657 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
21:02:11-690168 INFO     Torch detected GPU: NVIDIA GeForce GTX 1650 VRAM 4096 Arch (7, 5) Cores 16
21:02:11-690168 INFO     Verifying requirements
21:02:11-783947 INFO     No changes detected: Quick launch active
21:02:11-787957 INFO     Running extension preloading
21:02:11-787957 INFO     Server arguments: ['--medvram']

**Comment by vladmandic** [comment]
merging with #374
