### ISSUE TITLE
[Feature]: Dropdown for default scaler for inpainting

### ISSUE THREAD

**Issue by scpedicini** [vladmandic/automatic#546]
### Feature description

The "Upscaler for img2img" defaults to SwinIR 4x. It seems to use this upscaler for both img2img as well as inpainting (masked regions that are scaled up to add detail). 

![image](https://user-images.githubusercontent.com/2040540/234730387-8024a88a-8749-4df6-91b8-d4f6537dad35.png)

Scalers labeled "4x" tend to produce their best results at 4x multiplication, but obviously with the inpainting masked only, the scaling will be all kinds of ratios. Additionally, I've found purely anecdotally that SwinIR has a bit of a "painter" feeling to it and is less on the photorealistic side, so it might not be the best fit when working on certain images.

Since this setting is sort of hidden (I doubt your average user even realizes that they can set a specific upscaler for their inpainting), it might be better to expose this as a dropdown choice in the InPainting tab so that they can switch it around as necessary.

**Comment by vladmandic** [comment]
i took a look at this and it would be extremely intrusive change as that setting is not actually used for img2img operations only, its basically a default upscaler for any `image.resize` calls throughout all code. I've changed the setting name to reflect that.

it would be possible to have a second local setting in img2img local ui settings and then pass that as additional param - i'd welcome contributions / PR for that.

**Comment by vladmandic** [comment]
i took a second look and post processing eventually calls img2img which calls any registered post-processing script. by that point, only global params are available, locally selected upscaler cannot be passed. so leaving it as-is for now.
to avoid unnecessary operations, i've set default upscaler in settings back to none instead of swinir.
