### ISSUE TITLE
[Issue]: wd 14 tagger from extensions won't load

### ISSUE THREAD

**Issue by zethfoxster** [vladmandic/automatic#547]
### Issue Description

executing callback: C:\WebUi\automatic\extensions\stable-diffusion-webui-wd14-tagger\scripts\tagger.py ui_tabs_callback:
AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\WebUi\automatic\modules\script_callbacks.py:142 in ui_tabs_callback                                               │
│                                                                                                                      │
│   141 │   │   try:                                                                                                   │
│ ❱ 142 │   │   │   res += c.callback() or []                                                                          │
│   143 │   │   except Exception as e:                                                                                 │
│                                                                                                                      │
│ C:\WebUi\automatic\extensions\stable-diffusion-webui-wd14-tagger\tagger\ui.py:329 in on_ui_tabs                      │
│                                                                                                                      │
│   328 │   │   │   │   │   with gr.Row(variant='compact'):                                                            │
│ ❱ 329 │   │   │   │   │   │   interrogator_names = utils.refresh_interrogators()                                     │
│   330 │   │   │   │   │   │   interrogator = utils.preset.component(                                                 │
│                                                                                                                      │
│ C:\WebUi\automatic\extensions\stable-diffusion-webui-wd14-tagger\tagger\utils.py:70 in refresh_interrogators         │
│                                                                                                                      │
│   69 │                                                                                                               │
│ ❱ 70 │   for path in os.scandir(shared.cmd_opts.deepdanbooru_projects_path):                                         │
│   71 │   │   if not path.is_dir():                                                                                   │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'deepdanbooru_projects_path'

**Comment by vladmandic** [comment]
Did you search? There's about 10 duplicates.

**Comment by zethfoxster** [comment]
apologies, i don't really know how to search the issues section other than reading the issues titles :(

**Comment by GeneralAwareness** [comment]
> apologies, i don't really know how to search the issues section other than reading the issues titles :(

Github search is rubbish so don't feel bad as it just made me look like a lazy stupid ass.  Never use github search just go do a Google search that will probably land you back to one of thos 10 duplicates Vlad spoke of.

**Comment by GiusTex** [comment]
If anyone is interested I made a [repo](https://github.com/GiusTex/vladmandic-WD14-Tagger) with instructions and files on how to use wd14-tagger on vladmandic. The lora files work (there were problems in other issues) and it's easy to use. It's not perfect since for now you have to change tagger model manually, if you don't like the default one (anyway all instructions are in my repo)
