### ISSUE TITLE
[Issue]: I have custom path folder for upscaler in it but it's still downloading and using default folder

### ISSUE THREAD

**Issue by KumiIT** [vladmandic/automatic#549]
### Issue Description

I decided to have one folder that contains all of the models that i can use sort of globally on all software, avoiding downloading each time the same X GB model, but i found out that an upscaler (in my case realesrgan but possible more other too), not only it doesn't use the model (the path i have setup in the settings already) but it also start downloading it, as it see no models in the default path (it does kill my entire purpose of separate folder)

### Version Platform Description

OS: Ubuntu 20.04
Browser: Firefox
commit: def7a02d82f4e7456177f3dbdf697dc7d02a3214
GPU: NVIDIA 3070 8 GB VRAM Laptop

Looks like a reproducible to me and it happens at every server restart: 
* when it downloads: use upscaler (high res. fix) to generate image (in my case realesrgan) while custom path setup but no model in default path
* when it uses: temporarely moving models from custom folder, doesn't influence at all, because it use the model from default path folder that is already there (the first proof is that it works and the second proof is that it doesn't download it again)

I do not have any other extension than the pre-installed

**Comment by vladmandic** [comment]
fixed for realesrgan, new code will be publiushed in ~1h.
