### ISSUE TITLE
[Issue]: Ultimate upscale extension: Only outputs jpg regardless of image output settings

### ISSUE THREAD

**Issue by crazygonuts** [vladmandic/automatic#550]
### Issue Description

Referring to this extension https://github.com/Coyote-A/ultimate-upscale-for-automatic1111
In automatic1111 this extension outputs a png and a jpg when it upscales an image
in Vladmandic it only outputs a jpg, regardless of what format is set in "settings->image options->file format for images"

I reported this issue here as well https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/issues/71 but I wasn't sure which project was more appropriate, considering that the script works as intended for the automatic1111 fork it was originally written for

### Version Platform Description

Version: def7a02d Wed Apr 26 16:08:56 2023 -0400, windows 10, chrome

**Comment by vladmandic** [comment]
For some unknown reason, it looks like that extension is using grid format instead of samples format. Report to extension author, closing here.
As a workaround, you should be able to set grid format to png.
