### ISSUE TITLE
[Issue]: RuntimeError: unexpected EOF, expected 3786101 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by itsastroa** [vladmandic/automatic#551]
### Issue Description

C:\vlad1111\automatic\venv\lib\site-packages\torch\serialization.py:1051 in _legacy_load                             │
│                                                                                                                      │
│   1050 │   │   typed_storage = deserialized_objects[key]                                                             │
│ ❱ 1051 │   │   typed_storage._untyped_storage._set_from_file(                                                        │
│   1052 │   │   │   f, offset, f_should_read_directly,                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: unexpected EOF, expected 3786101 more bytes. The file might be corrupted.
gradio call: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\vlad1111\automatic\modules\call_queue.py:58 in f                                                                  │
│                                                                                                                      │
│    57 │   │   │   │   pr.enable()                                                                                    │
│ ❱  58 │   │   │   res = list(func(*args, **kwargs))                                                                  │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                        │
│                                                                                                                      │
│ C:\vlad1111\automatic\modules\call_queue.py:38 in f                                                                  │
│                                                                                                                      │
│    37 │   │   │   try:                                                                                               │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    39 │   │   │   finally:                                                                                           │
│                                                                                                                      │
│                                               ... 8 frames hidden ...                                                │
│                                                                                                                      │
│ C:\vlad1111\automatic\venv\lib\site-packages\torch\serialization.py:815 in load                                      │
│                                                                                                                      │
│    814 │   │   │   │   raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None                               │
│ ❱  815 │   │   return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args                      │
│    816                                                                                                               │
│                                                                                                                      │
│ C:\vlad1111\automatic\venv\lib\site-packages\torch\serialization.py:1051 in _legacy_load                             │
│                                                                                                                      │
│   1050 │   │   typed_storage = deserialized_objects[key]                                                             │
│ ❱ 1051 │   │   typed_storage._untyped_storage._set_from_file(                                                        │
│   1052 │   │   │   f, offset, f_should_read_directly,                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: unexpected EOF, expected 3786101 more bytes. The file might be corrupted.

**Comment by vladmandic** [comment]
You've provided zero information other than traceback.
In the future such issues will be closed automatically.
