### ISSUE TITLE
[Issue]: OOM when using Xformers.

### ISSUE THREAD

**Issue by GeneralAwareness** [vladmandic/automatic#553]
### Issue Description

This is using Xformers in your program and using --lowvram, or my normal Automatic1111 --medvram.  I have no issues running with Xformers on Automatic1111 and I did check xformers (it Installing package: xformers==0.0.17).

DDIM Sampler:   0%|                                                                             | 0/20 [00:00<?, ?it/s]
gradio call: OutOfMemoryError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\vlads_automatic\modules\call_queue.py:58 in f                                                                    │
│                                                                                                                     │
│    57 │   │   │   │   pr.enable()                                                                                   │
│ >  58 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ D:\vlads_automatic\modules\call_queue.py:38 in f                                                                    │
│                                                                                                                     │
│    37 │   │   │   try:                                                                                              │
│ >  38 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    39 │   │   │   finally:                                                                                          │
│                                                                                                                     │
│                                              ... 31 frames hidden ...                                               │
│                                                                                                                     │
│ D:\vlads_automatic\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                             │
│                                                                                                                     │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                      │
│ > 1501 │   │   │   return forward_call(*args, **kwargs)                                                             │
│   1502 │   │   # Do not call functions when jit is used                                                             │
│                                                                                                                     │
│ D:\vlads_automatic\modules\hypernetworks\hypernetwork.py:416 in attention_CrossAttention_forward                    │
│                                                                                                                     │
│   415 │   # attention, what we cannot get enough of                                                                 │
│ > 416 │   attn = sim.softmax(dim=-1)                                                                                │
│   417                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
OutOfMemoryError: CUDA out of memory. Tried to allocate 3.16 GiB (GPU 0; 6.00 GiB total capacity; 2.48 GiB already
allocated; 2.56 GiB free; 2.51 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Version Platform Description

def7a02d on Windows 10.

**Comment by GeneralAwareness** [comment]
Let me add this I just saw

![image](https://user-images.githubusercontent.com/124339252/234766816-68a13682-b765-47e9-9e55-4f5675f717b8.png)
00:23:05-192311 INFO     Installing package: xformers==0.0.17
00:23:07-055986 INFO     Verifying requirements
00:23:07-099210 INFO     No changes detected: Quick launch active
00:23:07-102213 INFO     Running extension preloading
00:23:07-103214 INFO     Server arguments: ['--theme', 'dark', '--lowvram', '--disable-safe-unpickle', '--port',
                         '9000']
No module 'xformers'. Proceeding without it.
Available models: D:\vlads_automatic\models\Stable-diffusion 90
Loading theme: black-orange

**Comment by crazygonuts** [comment]
i think you need xformers 0.0.18 or later to work with torch 2.  try pip install xformers==0.0.18

**Comment by vladmandic** [comment]
> i think you need xformers 0.0.18 or later to work with torch 2. try pip install xformers==0.0.18

No. Torch 2.0 support was added in xFormers 0.0.17rc, so its available in 0.0.17. 

But in general, not sure what is expected of me here? Yes, I see traceback with OOM, but that's it. nothing else. I'm flagging issues like this as invalid as there is no actionable information provided.

**Comment by GeneralAwareness** [comment]
I did select them and what do you expect from me, us, the users when that is all the information we are given?  Come on, be sensible you wrote this thing, and we give you the only information we were given about the issue.  You are now being entirely unreasonable.

After watching a video about this last night the content creator said this is a known issue as it happens to a lot of people.  In other words it isn't just me, buddy, and you can't just play an Automatic on us and wimp out.  Give us the ability to give you more information about the error, if you can.

**Comment by vladmandic** [comment]
> You are now being entirely unreasonable.

unreasonable???
i didn't close the issue. i didn't ignore it. i asked for more details. so yes, lets be real!

i still don't know
- which HW you're running on? you wrote Windows 10 and thats it. don't even know if you have GPU or not.
- actual startup log. i don't even see which torch is used.
- which model you're using (could be 2GB or up to 8GB)
- what was the workflow leading to this? i see that hypernetwork code path was triggered, but have no idea what leads to that

so yes, marking this issue as invalid until information is provided is totally valid.

> After watching a video about this last night the content creator said this is a known issue as it happens to a lot of people

in majority of cases, people are running at the very limit of their HW and yes, this repo uses more VRAM.
so people that were able to run at 1234px now need to run at 1233px.
No, its not a general issue that happens during normal operations for most people.

> Give us the ability to give you more information about the error, if you can.

think about it, if you were me, what do you think might be relevant? none of the above? or perhaps all of the above?
and i don't have time to hand-hold each issue without any relevant information in it.

**Comment by GeneralAwareness** [comment]
First let's get this part out of the way, as I had people look at this to see who was being unreasonable (I can be at times so I needed to know):  Here is what they said...How rude you were.  Another said "Seems like he's pissed about his repo getting issues posted on it.  He should have made it private when it git traction if that's how he wanted it."

With that out of the way we may continue.

#1 How, or why, are you using more vram than Automatic1111 when this is a fork?
#2 1060 6GB
#3 A standard 2.7GB model (never seen an 8GB one yet)
#4 Standard prompt used in Automatic1111 and yours.  1 HN used.
#5 No errors in the startup, or even warnings (though I do not have that log now and it doesn't save startup logs)

This runs fine on SDP but do not touch that radial for xformers as it will download it then fucked you will probably be, as I was, because that is precisely what the warning was from the content creator on Youtube mentioning the exact same issue I had.  Fact is I had to delete your entire folder to start over as the old automatic1111 way of just deleting the venv to let it rebuild it did NOT help.

Maybe a way to turn on a debug log would be greatly helpful, or a log that logs what you need when it is started as InvokeAI does to help their devs trace what happened to fix the bugs (best damn devs I have worked with for a very long time) is needed with this as well.

**Comment by vladmandic** [comment]
> With that out of the way we may continue.

Sure, write a paragraph and then stop it. For real.

Do not use #<number> as that is used as LINK in github. so you've just linked your issue to 5 unrelated issues.

> How, or why, are you using more vram than Automatic1111 when this is a fork?

If its the same as A1111 then what would be the point of this repo existing? It started as a fork and there has beeen a LOT of new stuff since. Far too long to list here.

1060 is old card. Yes, those are far more succeptible to OOM than newer cards. But that is really critical piece of information.

> Standard prompt used in Automatic1111 and yours. 1 HN used.

Given that traceback explicitly shows issue in hypernetwork, that is pretty important piece of information.
And "standard prompt" is still not enough. Do you have issues without hypernetwork? If no, can you share that hypernetwork? and need exact prompt or i cannot even begin to reproduce.

> This runs fine on SDP but do not touch that radial for xformers as it will download it then fucked you will probably be, as I was, because that is precisely what the warning was from the content creator on Youtube mentioning the exact same issue I had. Fact is I had to delete your entire folder to start over as the old automatic1111 way of just deleting the venv to let it rebuild it did NOT help.

This makes no sense and information you said is just wrong.
And watch the language.

> (best damn devs I have worked with for a very long time) is needed with this as well.

Yup, they're great. And they're paid for what they do. Totally feel free to use InvokeAI.

All-in-all, this is becoming more of a rant than actual troubleshooting. So either stay on topic and actually provide information when needed or close the issue. Imagine if i had to deal with 50 of those per day? Just this 1 is enough. And yes, this is the worst for the last day.

**Comment by vladmandic** [comment]
> make a log you can have us submit in case we run into any errors.

like i haven't? have you seen original a1111 logging? its 10x worse. i'm working on it. and you're a spoiled child.

**Comment by GeneralAwareness** [comment]
You are a dickhead, and I am a spoiled child.  Time to move on.
