### ISSUE TITLE
[Issue]: X/Y/Z plot all of a sudden doesn't work for LoRA values and parameters, it just keeps the same LoRA loaded

### ISSUE THREAD

**Issue by onegex1214** [vladmandic/automatic#558]
### Issue Description

Usually I'll put the LoRA in the prompt <lora:blabla:0.15>

Then in the X/Y/Z plot I'll open a S/R prompt grid maker and put "0.15,0.25,0.5,0.8"

So it picks up the 0.15 from the prompt value and makes a grid. This has always been working, in Auto1111 as much as in Vlad Diffusion here. But all of a sudden, it just doesn't work... tried to update, relaunch, reload, everything.

It just keeps the same LoRA loaded. The first value.

### Version Platform Description

11:39:26-673997 INFO     Python 3.10.6 on Windows
11:39:27-000937 INFO     Version: def7a02d Wed Apr 26 16:08:56 2023 -0400
11:39:27-332015 INFO     Setting environment tuning
11:39:27-336487 INFO     nVidia toolkit detected
11:39:28-495617 INFO     Torch 2.0.0+cu118
11:39:28-509616 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
11:39:28-511616 INFO     Torch detected GPU: NVIDIA GeForce GTX 1080 VRAM 8192 Arch (6, 1) Cores 20
11:39:28-513713 INFO     Verifying requirements
11:39:28-526689 WARNING  Package wrong version: diffusers 0.14.0 required 0.15.0
11:39:28-528182 INFO     Installing package: diffusers==0.15.0
11:39:31-664199 INFO     No changes detected: Quick launch active
11:39:31-665699 INFO     Running extension preloading
11:39:31-666698 INFO     Server arguments: ['--autolaunch']

**Comment by onegex1214** [comment]
I'm sorry could you guide me through the steps, I'm not familiar with git at all !

**Comment by nekoworkshop** [comment]
@onegex1214 Could you share the full text you put into the "X values" box? I just checked prompt SR and it's working fine for me adjusting LoRA weights. In my case the LoRA is _<lora:Texas_Arknights_#head#omertosa#:1>_ in the prompt. My prompt SR is 

`
"<lora:Texas_Arknights_#head#omertosa#:1>","<lora:Texas_Arknights_#head#omertosa#:0.7>","<lora:Texas_Arknights_#head#omertosa#:0.4>"` 

Basically replace the entire part including the angle brackets

![xyz_grid-0293-2743655392-DPM++ 2M Karras-22-7-20230430113139](https://user-images.githubusercontent.com/1346257/235361828-c2fc5986-7822-485c-bd8b-abfcac8cc5dd.jpg)

**Comment by onegex1214** [comment]
It's suddenly working back, maybe an update fixed it or something :D so all fine!

**Comment by vladmandic** [comment]
Oh well 😁
I'll close the issue, but update if it reoccurs.
