### ISSUE TITLE
[Issue]: Use ACCELERATE lost Server arguments

### ISSUE THREAD

**Issue by meishild** [vladmandic/automatic#560]
### Issue Description

:accelerate_launch
echo Accelerating
%ACCELERATE% launch --num_cpu_threads_per_process=8 launch.py %*
pause
exit /b

webui.bat need add %*

### Version Platform Description

all

**Comment by vladmandic** [comment]
are you sure this is needed - server args seem to work as-is?
can you show how they are not passed?

**Comment by meishild** [comment]
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/3060761/234858129-f453bc85-7909-43c4-8e76-3447ff36570b.png">
E:\web-ui\automatic>echo %ACCELERATE%
"True"

E:\web-ui\automatic>webui.bat --listen --port 8123
venv "E:\web-ui\automatic\venv\Scripts\Python.exe"
Checking for accelerate
Accelerating
[20:11:04] WARNING  The following values were not passed to `accelerate launch` and had defaults used instead:                       launch.py:895
                            `--num_processes` was set to a value of `1`
                            `--num_machines` was set to a value of `1`
                            `--mixed_precision` was set to a value of `'no'`
                            `--dynamo_backend` was set to a value of `'no'`
                    To avoid this warning pass in values for each of the problematic parameters or run `accelerate config`.
20:11:05-138628 INFO     Python 3.10.11 on Windows
20:11:05-490166 INFO     Version: def7a02d Wed Apr 26 16:08:56 2023 -0400
20:11:17-199565 INFO     Setting environment tuning
20:11:17-201566 INFO     nVidia toolkit detected
20:11:18-188967 INFO     Torch 2.0.0+cu118
20:11:18-199970 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
20:11:18-201136 INFO     Torch detected GPU: NVIDIA GeForce RTX 4090 VRAM 24564 Arch (8, 9) Cores 128
20:11:18-202143 INFO     Verifying requirements
20:11:18-264387 INFO     No changes detected: Quick launch active
20:11:18-265386 INFO     Running extension preloading
20:11:18-266387 INFO     Server arguments: []
Unloading xFormers
Available models: E:\web-ui\automatic\models\Stable-diffusion 37
ControlNet v1.1.116
ControlNet v1.1.116
dirname:  localizations
localizations:  {'sd-webui-zh_CN': 'E:\\web-ui\\automatic\\localizations\\sd-webui-zh_CN.json'}
Civitai Helper: Get Custom Model Folder
Civitai Helper: Load setting from: E:\web-ui\automatic\extensions\Stable-Diffusion-Webui-Civitai-Helper\setting.json
Civitai Helper: No setting file, use default
Theme download error accessing HuggingFace
Loading theme: mindwrapped/flamingo_dark
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by vladmandic** [comment]
those params are `accelerate` params and should NOT be passed to launch - launch does not know what to do with them.
and there are no one-size-fits-all for accelerate params. you should run `accelerate config` once to set them for your system.

**Comment by meishild** [comment]
> those params are `accelerate` params and should NOT be passed to launch - launch does not know what to do with them. and there are no one-size-fits-all for accelerate params. you should run `accelerate config` once to set them for your system.

NONONO i'dont said  those --num_processes was set to a value of 1
--num_machines was set to a value of 1
--mixed_precision was set to a value of 'no'
--dynamo_backend was set to a value of 'no'

I said Server arguments: []

lost listen and port arguments.
webui.bat --listen --port 8123

**Comment by meishild** [comment]
@vladmandic I said Server arguments: []

**Comment by vladmandic** [comment]
ahh, only when SKIP_VENV is set and ACCELERATE is set.
ok, i'll add params.
