### ISSUE TITLE
[Feature]: Customiseable Hires Fix sampler

### ISSUE THREAD

**Issue by Gazzoo-byte** [vladmandic/automatic#561]
### Feature description

Allow selection of which sampler gets used in the 2nd pass of Hires fix, i.e. if using UniPC (which as yet does not support i2i operations) allow the user to choose which sampler will be used in the second part, rather than defaulting to DDIM

### Version Platform Description

N/A in this instance

**Comment by vladmandic** [comment]
i've added a "fallback sampler" option in ui settings -> samplers.
new code will be published in ~2h.

**Comment by Gazzoo-byte** [comment]
wow, you got that done so much faster than I could have imagined! I stumbled onto an unrelated issue while trying to figure out how to load the list of samplers used in i2i - UniPC is listed as a viable sampler when it shouldn't, gives

`AttributeError: 'UniPCSampler' object has no attribute 'make_schedule'`

from ln 179 of sd_samplers_compvis.py

Should I make a separate issue for that?

**Comment by Gazzoo-byte** [comment]
https://github.com/wl-zhao/UniPC/issues/6#issuecomment-1464911620 seems my knowledge was out of date and UniPC allegedly can do i2i now, if this helps diagnose things

**Comment by vladmandic** [comment]
interesting, let me test unipc with hires fix and img2img.

**Comment by horribleCodes** [comment]
I'd still appreciate it if you could freely pick the sampler for the hires pass, even if I'm not using UniPC for the first pass. I think mixing and matching samplers has its uses, and I'd have to use img2img otherwise.

**Comment by vladmandic** [comment]
UI Settings -> Sampler parameters -> Secondary sampler
(just wait ~1h until i push changes).
If you set it to None, primary will always be used. If its set to any value, it will be used for secondary operations such as hires fix.

**Comment by horribleCodes** [comment]
Fantastic, thanks!
