### ISSUE TITLE
[Issue]: ui freeze bug when i reload ui.

### ISSUE THREAD

**Issue by meishild** [vladmandic/automatic#564]
### Issue Description

When i reaload my ui used to last Generation Info button
![image](https://user-images.githubusercontent.com/3060761/234911601-c4f63b37-425c-48f2-b41d-f09180dd4c18.png)

Generation Info
`mini\(ttp\), (8k, RAW photo, best quality, masterpiece:1.2), cyberpunk city, miniature, landscape,  isometric,  <lyco:miniatureWorldStyle_v10:1>
Negative prompt: (((blur))), (EasyNegative:1.2), ng_deepnegative_v1_75t, paintings, sketches, (worst quality:2), (low quality:2), (normal quality:2), lowres, normal quality, ((monochrome)), ((grayscale)), bad anatomy,(long hair:1.4),DeepNegative,(fat:1.2),facing away, looking away,tilted head,lowres,bad anatomy,bad hands, text, error, missing fingers,extra digit, fewer digits, cropped, worstquality, low quality, normal quality,jpegartifacts,signature, watermark, username,blurry,bad feet,cropped,poorly drawn hands,poorly drawn face,mutation,deformed,worst quality,low quality,normal quality,jpeg artifacts,signature,watermark,extra fingers,fewer digits,extra limbs,extra arms,extra legs,malformed limbs,fused fingers,too many fingers,long neck,cross-eyed,mutated hands,polar lowres,bad body,bad proportions,gross proportions,text,error,missing fingers,missing arms,missing legs,extra digi
Steps: 40, Sampler: DPM++ 2M Karras, CFG scale: 7, Seed: 248372777, Size: 768x768, Model hash: 68c0a27380, Model: cetusMix_Coda2, Denoising strength: 0.5, ENSD: 31337, Hires upscale: 2, Hires steps: 20, Hires upscaler: R-ESRGAN 4x+ Anime6B `

chrome console 1 error.
![image](https://user-images.githubusercontent.com/3060761/234911152-6bda1769-a6c8-4bf5-bb31-6e8f08497e85.png)

and my termial 
![image](https://user-images.githubusercontent.com/3060761/234911435-b12e820d-fc35-4b33-bdc9-70a55fe542db.png)

### Version Platform Description

commit 5dcaaba614cf76005f66c2e9269361750440caf9 (HEAD -> master, origin/master, origin/diffusers, origin/HEAD)
Author: Vladimir Mandic <mandic00@live.com>
Date:   Thu Apr 27 09:42:41 2023 -0400

    reduce extra network exception

**Comment by vladmandic** [comment]
> When i reaload my ui

See #224 
Any issues that appear after reloading UI using server restart from UI will be fixed once that function is redesigned, closing for now.
