### ISSUE TITLE
[Issue]: API error: alwayson_scripts

### ISSUE THREAD

**Issue by Hetaneko** [vladmandic/automatic#566]
### Issue Description

I get this error when using "alwayson_scripts" in request body

{'error': 'TypeError', 'detail': '', 'body': '', 'errors': "unsupported operand type(s) for -=: 'str' and 'float'"}

"alwayson_scripts": {"Upscale": { "args":[0,2,512,512,false,"4x-UltraSharp"]}}

**Comment by vladmandic** [comment]
script `Upscale` is not a built-in script - can you reproduce this problem using any of the built-in scripts?
params to always-on scripts are passed as-is, I cannot install & troubleshoot every 3rd party script.
and in general, if it were me, i'd rather get txt2img and then do a second api call to upscale it (without the need for scripts).

**Comment by Hetaneko** [comment]
Controlnet works. I wanted to use this postprocessing script.
![image](https://user-images.githubusercontent.com/54069666/234927927-c9ca1440-7e95-4f02-a498-fe0f302adaaf.png)
![image](https://user-images.githubusercontent.com/54069666/234928265-57209efa-77d3-4c7c-a58d-02cdd3acfd84.png)
i guess i'll go with /sdapi/v1/extra-single-image to upscale the image

**Comment by vladmandic** [comment]
yes, but thats a postprocessing operation, not an always-on script.

**Comment by Hetaneko** [comment]
Ok, deleting sd-dynamic-thresholding extension fixed the problem.

**Comment by vladmandic** [comment]
really? i'm reopening the issue as that should not happen.

**Comment by Hetaneko** [comment]
I'm sorry for the conclusion, english is not my native language. `Upscale` is a postprocessing operation.
![image](https://user-images.githubusercontent.com/54069666/235245647-c3f772aa-8847-415b-bf05-6d71180a9a84.png)
I'm using it so i dont have to send the image back as it is not needed. After enabling it you can use it as an `alwayson_script` with the API. Both for txt2img and img2img. I also use [rembg](https://github.com/AUTOMATIC1111/stable-diffusion-webui-rembg) extension like this way. I was able to use it before but somehow i started get an error caused by the plugin `sd-dynamic-thresholding`. This problem is only when you are using API. This postprocessing operation is somehow interfering the extension `sd-dynamic-thresholding`. I'm guessing it can be fixed by setting the parameters of  `sd-dynamic-thresholding` as none when using the API.

**Comment by vladmandic** [comment]
this was a nightmare to fix, but finally done!

issue was not in a specific extension, issue was general way how a1111 chains always-on extensions so one set of params overwrites params for a totally different extension.
