### ISSUE TITLE
[Feature]: Upscaler dropbox for img2img as that of the hiresfix

### ISSUE THREAD

**Issue by giteeeeee** [vladmandic/automatic#569]
### Feature description

The upscaler selection box for img2img is currently in the settings. 

And the latent scaling is under the "just resize (latent upscale)" button.

Thus I suggest to unify the upscalers into one dropbox under the "From Image" tab, like that of the hiresfix.

**Comment by vladmandic** [comment]
isn't this basically a duplicate of #546?

**Comment by giteeeeee** [comment]
> isn't this basically a duplicate of #546?

I'll close this one.
