### ISSUE TITLE
[Issue]: 'Show samplers in user interface' option seems to apply to img2img while txt2img forces PLMS and UniPC samplers to always appear

### ISSUE THREAD

**Issue by Phosay** [vladmandic/automatic#571]
### Issue Description

Changing samplers in option 'show samplers in user interface' applies correctly to img2img tab but in case of txt2img tab regardless of choices PLMS and UniPC samplers always appear under sampling method
![Show samplers](https://user-images.githubusercontent.com/80211709/234963753-e1ee40c3-7592-43a9-8039-8747083b52cb.png)

img2img tab
![Img2Img](https://user-images.githubusercontent.com/80211709/234963825-eacb8926-c287-4bb8-81fb-7da046251770.png)

txt2img tab
![Txt2Img](https://user-images.githubusercontent.com/80211709/234963955-200d775d-9ca3-495e-b00b-947bf1f8ad19.png)

### Version Platform Description

OS - Windows 10 Home (22H2)
GPU - NVIDIA GeForce RTX 2060 (6 GB VRAM)
Version: 1f6261be Thu Apr 27 13:12:20 2023 -0400

**Comment by vladmandic** [comment]
That is by design as part of the code require those two to always be available as fallbacks.
And wouldn't this be better suited as a question in discussions instead of creating an issue (especially since there is no user impact one way or the other)?
