### ISSUE TITLE
[Feature]: Add Download-All or Zip option when using Batch

### ISSUE THREAD

**Issue by ancker010** [vladmandic/automatic#572]
### Feature description

Similar to the Auto1111 UI. 
When generating a batch of images, have an option to save all images as a Zip file, or at least have a way to say "download all of this batch".

**Comment by vladmandic** [comment]
valid request, putting on my back-log (or even better, if someone wants to contribute)

**Comment by ancker010** [comment]
Turns out this is a simple CSS fix.
The 'black-orange' theme simply disables the Zip button.

https://github.com/vladmandic/automatic/blob/bfe62127e9d90015ba4c24df55333163bf53c73a/javascript/black-orange.css#L84

**Comment by ancker010** [comment]
Fixed in #577
