### ISSUE TITLE
[Issue]: wrong launch directory in webui.sh

### ISSUE THREAD

**Issue by derVedro** [vladmandic/automatic#575]
### Issue Description

If you start webui.sh from a different non local directory, webui.sh checks if _stable-diffusion-webui_ directory exists and runs stuff from it. It doesn't matter, that your stuff is in a different directory. Imagine you still have a parallel installation of automatic1111 in that _stable-diffusion-webui_ directory, so that automatic1111 will be launched.

That was the behavior with automatic version 93b0de7e, with the last bfe6212 you simply can't even start it from an another directory, cause it looks for launch.py in local directory.

A simple solution to the problem is to cd into automatic directory by the webui.sh. I made a patch #576.

### Version Platform Description

ubuntu 22.10

**Comment by vladmandic** [comment]
closing. btw, when creating PR that closes an issue, best practise is to write `closes #issue_number` and then github automatically tracks it.
