### ISSUE TITLE
[Issue]: Error "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by awy-ww** [vladmandic/automatic#579]
### Issue Description

After the installation is complete, the first time I run the picture, I start to report an error
`RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'`

### Version Platform Description

win10     Google Chrome      6600xt

**Comment by vladmandic** [comment]
which version?
can you post the console log startup sequence so i can see if amd gpu was correctly identified and which torch was installed?
can you try setting cuda params in ui settings -> cuda to no-half and no-half-vae?

**Comment by RetroactiveTypo** [comment]
Having the same error, using the most recent pull (d3f0294b), but on Linux. I've tried each combo of those cuda settings mentioned to no avail.
Here's some startup logs:

> Create and activate python venv
> Launching launch.py...
> 23:46:43-471577 INFO     Python 3.10.6 on Linux                                                                                                                                               
> 23:46:43-497875 INFO     Version: d3f0294b Fri Apr 28 22:01:29 2023 -0400                                                                                                                     
> 23:46:43-729803 INFO     Setting environment tuning                                                                                                                                           
> 23:46:43-730758 INFO     AMD toolkit detected                                                                                                                                                 
> 23:46:44-689730 INFO     Torch 2.0.0+rocm5.4.2                                                                                                                                                
> 23:46:44-690787 WARNING  Torch repoorts CUDA not available                                                                                                                                    
> 23:46:44-691739 INFO     Verifying requirements                                                                                                                                               
> 23:46:44-709514 INFO     No changes detected: Quick launch active                                                                                                                             
> 23:46:44-710553 INFO     Running extension preloading                                                                                                                                         
> 23:46:44-711200 INFO     Server arguments: []                                                                                                                                                 
> No module 'xformers'. Proceeding without it.
> Available models: [git dir]/automatic/models/Stable-diffusion 1
> ControlNet v1.1.116
> ControlNet v1.1.116
> Loading theme: black-orange
> Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
> Initializing middleware
> Loading weights: [model]
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/[size] GB -:--:--
> Creating model from config: [git dir]/automatic/configs/v1-inference.yaml
> LatentDiffusion: Running in eps-prediction mode
> DiffusionWrapper has 859.52 M params.
> Scaled dot product cross attention is not available on CPU
> Embeddings loaded:  (0)
> Model loaded in 3.0s (load=1.7s create=0.3s apply=0.5s vae=0.5s)
> Startup time: 9.0s (torch=1.9s gradio=0.9s libraries=0.5s codeformer=0.1s scripts=1.4s ui=0.8s start=0.1s scripts app_started_callback=0.1s checkpoint=3.2s)

**Comment by vladmandic** [comment]
@awy-ww any updates?

**Comment by vladmandic** [comment]
closing as no details are provided after issue was created, will reopen if there are any updates.
