### ISSUE TITLE
[Issue]: System Info Page: data loaded: Loading benchmark-data-local.json again and again until System Info Page is left

### ISSUE THREAD

**Issue by byteconcepts** [vladmandic/automatic#584]
### Issue Description

System Info Page: data loaded: Loading benchmark-data-local.json again and again until System Info Page is left

Is that supposed to be like that without any command or interaction on the System Info Page before?

### Version Platform Description

updated: 2023-04-27
hash: bfe62127
url: https://github.com/vladmandic/automatic/tree/master

arch: AMD64
cpu: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
system: Windows
release: Windows-10-10.0.19044-SP0
python: 3.10.8

**Comment by vladmandic** [comment]
its not actually loading again and again, its just that gradio is refreshing ui component on each poll and showing whatever is the the last message the extension generated.
refresh is by default set to 1sec so it can monitor memory usage in real-time.
