### ISSUE TITLE
[Issue]: --models-dir invalid?

### ISSUE THREAD

**Issue by iconnoci** [vladmandic/automatic#589]
### Issue Description

I tried to modify --models-dir to D:\stable-diffusion-webui\models, but the BLIP model will still be downloaded to D:\automatic\models\BLIP, I wonder if I used it wrong?

### Version Platform Description

Version:  bfe62127e9d90015ba4c24df55333163bf53c73a  
time: 2023/4/28 8:21:22
windows11

**Comment by iconnoci** [comment]
I tried to modify part of the code in shared.py, and now the BLIP model can be used in the stable-diffusion-webui directory, but I don't know if I used it correctly
![QQ截图20230428202239](https://user-images.githubusercontent.com/22522962/235146213-624be170-0ece-4ddc-8b8a-150defe64493.png)

**Comment by vladmandic** [comment]
thanks for identifying the issue. correct syntax would be:
```python
models_path = cmd_opts_pre.models_dir if os.path.isabs(cmd_opts_pre.models_dir) else os.path.join(data_path, cmd_opts_pre.models_dir)
```
i've made changes and new version will be online in ~2h.

**Comment by iconnoci** [comment]
@vladmandic Thank you, it works. I used it on COMMANDLINE_ARGS before, and the new fix didn’t work. After reading your code, I changed the back of launch.py directly, and it worked. Your modification speed is really fast.
![Snipaste_2023-04-29_07-24-48](https://user-images.githubusercontent.com/22522962/235269636-d8b82cc7-5abc-4e7e-b894-229bec8eb1c8.png)
