### ISSUE TITLE
[Issue]: Seed always appended to image filename regardless of option

### ISSUE THREAD

**Issue by MrLawbreaker** [vladmandic/automatic#590]
### Issue Description

When generating an image, the filename for me always gets the seed appended even though my image options look like this
![image](https://user-images.githubusercontent.com/6021031/235157610-e181ad2a-3f2b-4851-8df0-ac6dfd255c8f.png)

Adding something to "Images Filename Pattern" correctly sets the filename but leaving it empty i always end up with the seed in the name even though the option for including seed etc. is turned off.

In this case, I would expect it to only be the number so I get 
**00039.png**
instead of
**00039-3172825024.png**

Is this expected behavior or is there something I have to change to get it like I want?

### Version Platform Description

Version: bfe62127 Thu Apr 27 15:47:13 2023 -0400

**Comment by vladmandic** [comment]
that is how default filename pattern is set: `"[seed]-[prompt_spaces]"`
if you set your own, it will use whatever you set.
