### ISSUE TITLE
[Issue]: Some extensions cause issue with txt2img

### ISSUE THREAD

**Issue by siddharthpanda99** [vladmandic/automatic#592]
### Issue Description

I am able to install and run these few extensions fine but text2img generations fail without showing any error. Other tabs work fine but on clicking Generate in text2Img tab, the button doesn't change and in the cmd terminal I see no failures or progressbar indication the generation has started.

https://github.com/zero01101/openOutpaint-webUI-extension
https://github.com/AUTOMATIC1111/stable-diffusion-webui-promptgen
https://github.com/dr413677671/PromptGallery-stable-diffusion-webui

There are many extensions that don't work/cause issues. Do we have a list of most important extensions that work with automatic?

**Comment by vladmandic** [comment]
for each extension that is reported as non-functional, i take a look. for some, i had to add compatibility support and for others they are broken since they havent been updated in a looong time.
i'll check the 3 listed above.

**Comment by siddharthpanda99** [comment]
I will test out and report as may important extensions as possible. Some of them are update recently though.
The main issue is no error message is shown, the generate button stops working. The first time it shows progress bar and says waiting but then goes back to generate (text on the button) without throwing any error in commandline.

Also it works for a few iterations and then stops without warning. This issue is only with text2img, other tabs work fine

**Comment by vladmandic** [comment]
Update:
- OpenOutpaint works fine, I have not seen any issues
- PromptGen works fine. Note that it downloads its model on first usage.
- PromptGallery is broken and what I'd consider actually harmful as it attempts to modify core repo files during its installation instead of being an actual extension. And in worst case, its actually evil since it doesn't perform any checks, so that copy can destroy files in core repo.

**Comment by vladmandic** [comment]
I'm closing this issue as answered, if there are any other items, update here and i'll reopen if needed.
