### ISSUE TITLE
[Issue]: Save button freezes out image preview metadata with dynamic prompts

### ISSUE THREAD

**Issue by afbagwell** [vladmandic/automatic#597]
### Issue Description

At the end of running batch of images on the FromText tab, the image previewer on the right will load the image metadata when selecting a single image. This works for dynamic prompts where there will be different metadata in each image.

However, after the first use of the "Save" button and then generating another batch of images, the metadata panel takes on an "inactive" color, and remains frozen on whatever metadata was last displayed there. Selecting individual images no longer updates the panel. The load button (below generate) will also not put the correct metadata for the selected image into the settings boxes.

The only part of the metadata panel that works in the Save button's mini-panel which provided a "Download" link and will update correctly.

I have not discovered a way to "unstick" the panel except by reloading the whole UI.

Restarting the server does not solve the problem as this has been an issue through many updates.

### Version Platform Description

Version: 57241e25 Fri Apr 28 09:28:59 2023 -0400
Windows 11, Chrome 112.0.5615.138
User installed extension (everything is up to date):
openpose-editor
sd-dynamic-prompts
sd-webui-3d-open-pose-editor
sd-webui-aspect-ratio-helper
sd-webui-depth-lib
ultimate-upscale-for-automatic1111

**Comment by afbagwell** [comment]
^^ should also mention I only had dynamic prompts enabled on the "From Image" tab. No others, including built-ins, were used.

**Comment by vladmandic** [comment]
does this happen only when dynamic prompt extension is used?

**Comment by afbagwell** [comment]
Turns out it works fine without dynamic prompts, but also fine if only one dynamic prompt is present. I guess this only happens if the number is sufficiently large.

**Comment by afbagwell** [comment]
Definitely only happening with dynamic prompts. It's leaving the metadata panel in the "inactive" mode after image generation stops.

**Comment by vladmandic** [comment]
it sounds like dynamic prompt never actually returns fully - so metadata info does not get updated and save button is not available - simply because server is waiting for operation to complete.
you really should report to author of sd-dynamic-prompts at <https://github.com/adieyal/sd-dynamic-prompts>
and if author needs my help in any way, i'm open to it.

if you run into problems without using that extension, let me know and i'll reopen the issue.
