### ISSUE TITLE
[Feature]: Paper describing on-device acceleration

### ISSUE THREAD

**Issue by Metsuryu** [vladmandic/automatic#605]
### Feature description

There is a recent paper that presents a series of implementation optimizations for large diffusion models that achieve the fastest reported inference latency to-date:

https://arxiv.org/abs/2304.11267

It would be great to implement these optimizations.

**Comment by vladmandic** [comment]
would be nice to check once they release some code, not just generic paper.

**Comment by Metsuryu** [comment]
@vladmandic  Of course. In the meantime, if anyone wants to give it a shot anyway, I thought I'd open the issue.

**Comment by vladmandic** [comment]
for sure - opening feature request so it can be monitored is a good thing

**Comment by vladmandic** [comment]
3 months later, but i still don't see any actual code, just paper. closing for now.
