### ISSUE TITLE
[Issue]: Extra Networks UI button (this red button under Generate) stopped working while on gradio-soft theme (possibly others similar)

### ISSUE THREAD

**Issue by mart-hill** [vladmandic/automatic#607]
### Issue Description

Clicking on it doesn't do anything, but I'm using gradio-soft theme. I'll check with the default theme. _Edit: seems to be working._

Model drop down list also decided it's going on vacation, it went to infinite refresh mode after I wanted to change a model. It happened when I "restored" image parameters from Image Viewer to txt2img, changed the parameters in ControlNet (added image and turned Pixel Perfect off) and turned on Composable Lora extension. I could generate an image, but was unable to change a model.

I think ControlNet extension might have troubles with Pixel Perfect option in connection to WebUI's hires fix Upscaling option (new or legacy), because when PP option is turned off in between uses, it can display the "width" part of the UI with indefinite refreshing, and I can't set this parameter anymore then. I mentioned UI's hires fix upscaling, because it always now sets forcibly itself to "new" hires fix variant every startup, no matter me changing it to legacy one and saving this setting.
And ControlNet Pixel Pefect option takes the width from the set width of the image which will be generated, and it hires fix is on, this width will also change for PP accordingly.

Sorry for the long description. 🙂 

PS: I'd like to ask - should I use "new" hires fix option only, or "legacy"? Since it requires a bit of fight with image width/height parameters in txt2img later, if I want to have the same resolution as before with hires on AND "legacy" option on in Settings.

### Version Platform Description

Windows 22H2, RTX 3090, Firefox 102.2
Version: 3b6effe4 Fri Apr 28 16:46:15 2023 -0400

**Comment by tkiikt** [comment]
maybe see this: #225

**Comment by mark-wd** [comment]
Could also be tied to #599

**Comment by vladmandic** [comment]
this seems to be a jumbo of 3 unrelated items? can you confirm if i understand correctly...
- extra networks button not working with non-default theme, but works with default theme?
- model change stops working under some circumstances?
- combo of controlnet with pixelperfect and hires fix?

**Comment by bdulfer** [comment]
I had the same problem.
Button didn't work with my preferred theme and didn't work with the default theme as well.

It seems to be an issue with the 'stable-diffusion-webui-state' extension from https://github.com/ilian6806/stable-diffusion-webui-state.git.
I "fixed" this by removing the tick on the 'extra_networks' button.

To me it looks like something to do with event routing in JS.

**Comment by mart-hill** [comment]
For the past troubles with "restoring" the workflow either with "blue angled arrow" button or by Image Viewer extension, I was afraid to use this "state" extension. 🙂 
I do have enabled this [extension though](https://github.com/zanllp/sd-webui-infinite-image-browsing) - I wonder if this one could be the one interfering (in my case)?

**Comment by tkiikt** [comment]
@mart-hill Have you checked that extensions off?

I think you should answer Vlad's question in the first.
> this seems to be a jumbo of 3 unrelated items? can you confirm if i understand correctly...
> 
> * extra networks button not working with non-default theme, but works with default theme?
> * model change stops working under some circumstances?
> * combo of controlnet with pixelperfect and hires fix?

**Comment by mart-hill** [comment]
You mean, disabling ControlNet?

**Comment by tkiikt** [comment]
[extension though](https://github.com/zanllp/sd-webui-infinite-image-browsing)

**Comment by vladmandic** [comment]
i just several fixes regarding extra networks button and how extra networks are displayed in thumbs and cards view.
if anything regarding that specific problem persists, update here and i'll reopen.

for any other issues mentioned here, please create separate issues as needed, i cannot commit fixes to multiple unrelated items in a single issue.
