### ISSUE TITLE
[Feature]: Add support Hidet compiler to enhance performance

### ISSUE THREAD

**Issue by Em1tSan** [vladmandic/automatic#608]
### Feature description

Torch have released information about the new compiler, [Hidet](https://github.com/hidet-org/hidet) 
https://pytorch.org/blog/introducing-hidet/, and write "For example, we can use hidet.torch.dynamo_config.use_tensor_core(True) to allow Hidet to generate CUDA kernels that leverage the Tensor Cores on NVIDIA GPUs,"

If I understand correctly, this is one of the ways to leverage Tensor Cores and get acceleration.

More information: https://docs.hidet.org/stable/gallery/tutorials/optimize-pytorch-model.html

**Comment by vladmandic** [comment]
i love it if it actually works. unfortunately, dynamo is quite buggy in torch 2.0 in general, waiting for service release before any real kind of testing. torch compile framework is already implemented in this repo, but not much that can be done with it at the moment.

**Comment by vladmandic** [comment]
well, as anything with `torch.compile` is experimental anyhow - i've added `hidet` support.

**Comment by ilikenwf** [comment]
So far with it all I get is compile errors but my 1080ti may be too old?

**Comment by vladmandic** [comment]
torch.compile is very expensive and takes a lot of vram. also requires a much newer gpu. so yes, i don't expect it to work on 1080ti. lowest i've seen is rtx3060 and that is barely working (result is fragmented model, not fully optimized).
