### ISSUE TITLE
"for hires fix use width height setting" ignored from config

### ISSUE THREAD

**Issue by zethfoxster** [vladmandic/automatic#609]
### Issue Description

the setting use old hi res fix keeps resetting to default.
it refuses to load it from the config, i tested by opening with notepad++ and then closed the webui and relaunched the whole thing. in notepad it shows my setting is true for that option, however, it is unchecked when i look in the settings. notepad++ never prompts me to reload the file and it still shows as true. even after closing and reopening the whole ui and cli, the config.json shows true, but it is essentially unchecked and false in the webui.

verified that even with all extensions disabled, the issue contenues.
clarifying that when i restart the UI, i close the cli and webui and relaunch it fresh each time. setting the setting to checked(true) and using the tabs restart ui will not reproduce, it completely closing reproduces.

### Version Platform Description

Version: 3b6effe4 Fri Apr 28 16:46:15 2023 -0400

**Comment by zethfoxster** [comment]
interestingly, if you load an img from image browser with "text->" where hires fix was used with this option correctly. it correctly sets itself to true and uses the H/W sliders as final res.

**Comment by vladmandic** [comment]
fixed, will update repo in ~1h.
