### ISSUE TITLE
[Issue]: Civitai Helper Icons not showing

### ISSUE THREAD

**Issue by iredmedia** [vladmandic/automatic#612]
### Issue Description

Just want to start by saying I love what you (all) have done with this project!

My issue is with Civitai Helper and the base themes, but also a bit with Kitchen theme its just a bit more extreme. Pictures say a thousand words so hopefully this helps.

Let me know if this should be directed towards one of the other extensions - I did check with my other instance running normal automatic1111 and it all worked fine.

Base theme:
![image](https://user-images.githubusercontent.com/584038/235287995-41fc1501-57f6-424a-bbc4-722de63af6d8.png)

Kitchen Theme (tried gradio/base and gradio/default as base themes):
![image](https://user-images.githubusercontent.com/584038/235287929-7b4ff94f-f11f-4b9e-b4f4-9bbfaae69f9d.png)

It seems these buttons are bugging out under "Extra Networks" in the Kitchen theme (which I'm really hoping to use).
![image](https://user-images.githubusercontent.com/584038/235288018-8f6ce2d3-05eb-4de5-8498-5674d95c6ca1.png)
![image](https://user-images.githubusercontent.com/584038/235288353-a454baae-262b-4817-a585-960783b90c25.png)

I've confirmed the HTML is actually rendering differently, and the content is different but I'm not sure why
![image](https://user-images.githubusercontent.com/584038/235288405-d83a1a99-6fde-4c01-a2d3-3fb0f802cf3c.png)
![image](https://user-images.githubusercontent.com/584038/235288419-d723f763-9347-4dfb-bcad-41fbc82bc996.png)

I have done lots of restarting webui.bat, refreshing, etc. Switching between themes to see if gradio/base or default would help but no luck.

I looked at the other issues referencing Civitai helper but nothing seemed relevant.

Any help is greatly appreciated!

### Version Platform Description

Windows 10
Version: latest pull (d3f029) Fri Apr 28 22:01:29 2023 -0400
Browser: Chrome

**Comment by vladmandic** [comment]
regarding first screenshot, civitai helper extension is working fine except it does one undesirable thing - it changes the built-in text with icon. its ok for extension to add its icons, like it does at the bottom. but it should NOT attempt to change elements defined in core repo.

regarding kitchen theme, i'm sorry, i'm not familar with it at all, never tried it, never used it and given the huge number of changes here, not surprised it misbehaves.

hopefully one of available gradio themes here can serve you for now. note that anapnoe ui/ux improvements are commit to this fork soon.
