### ISSUE TITLE
[Issue]: Extra networks description breaks thumb view

### ISSUE THREAD

**Issue by redrightsmile** [vladmandic/automatic#615]
### Issue Description

Thumbnail view shows 3 circles on the image side which does nothing and replace preview icon doesn't work anymore.

![image](https://user-images.githubusercontent.com/119710513/235297302-b97e2dbc-c51c-4c24-9300-e1db40b7a651.png)

How to reproduce:
Set Default view for Extra Networks as thumbs in settings. 

And could we have the option to disable extra networks descriptions? It adds big textbook to already cluttered UI. And it's usefulness is debatable. Also doesn't work well with Kitchen theme.

### Version Platform Description

Windows 10
Version: d3f0294b Fri Apr 28 22:01:29 2023 -0400
Browser: Chrome

**Comment by vladmandic** [comment]
fixed.
