### ISSUE TITLE
[Feature]: support for deepfloyd IF text to image 

### ISSUE THREAD

**Issue by lalamapaka** [vladmandic/automatic#616]
### Feature description

Add support for the deepfloyd IF model 
https://deepfloyd.ai/deepfloyd-if

**Comment by rawheat1** [comment]
wow quite fast

**Comment by lalamapaka** [comment]
> wow quite fast

Yeah, After seeing the news about it, I had an idea to enhance this repository by potentially incorporating support for other open-source models. Rather than creating a new web user interface for each model, perhaps this could become a universal web UI for local text-to-image conversion. This would help distinguish this repository even further.

**Comment by vladmandic** [comment]
supported
