### ISSUE TITLE
[Feature]: CLIP skip value not copied to Text or Image from Image Browser

### ISSUE THREAD

**Issue by sean-kang** [vladmandic/automatic#617]
### Issue Description

It is a low priority issue.

Steps to reproduce the problem:
1. Go to Image Browser.
2. Select any image that has CLIP size different than the default value.
3. Click "-> text (Send to Text)" button.
4. Go to From Text
5. You will see the CLIP size is not changed although other details have been successfully copied.

### Version Platform Description

Version: https://github.com/vladmandic/automatic/commit/d3f0294bde458778d51010bf990848ee8a993881 Fri Apr 28 22:01:29 2023 -0400
OS: Windows 10 (Stable Diffusion application running on Ubuntu 22.04.2 LTS, WSL2)
browser: Firefox 112.0.2
Command line flags: none

**Comment by CyberLykan** [comment]
Same issue happens with the Process Image tab.

**Comment by vladmandic** [comment]
totally valid report, but given that clip skip just became a per-image option, i'd rather mark this as feature than isuse.

**Comment by vladmandic** [comment]
transfering clip skip values now works betweeen txt2img img2img and process tabs.
