### ISSUE TITLE
[Issue]: Extra Networks description doesn't display anymore

### ISSUE THREAD

**Issue by radry** [vladmandic/automatic#621]
### Issue Description

Since the change was made to have buttons for "read description" and "replace description" it's not possible to show the metadata anymore.

Previously when there was only an "i" symbol, a frame opened with the models meta data but now nothing happens when clicking "read description"

### Version Platform Description

Version: 79c7e9d0 Sat Apr 29 10:58:06 2023 -0400

Windows 10, Firefox 112.0.2

**Comment by vladmandic** [comment]
fixed
