### ISSUE TITLE
[Feature]: Save button on Process Image tab

### ISSUE THREAD

**Issue by keenmouse** [vladmandic/automatic#623]
### Feature description

The Process Image tab should have a Save button like the From Text and From Image tabs.

When I am on my PC, I can just right-click and save the result image locally to any folder, but it is not saved in the Save folder by default. On my mobile devices, I can save the image locally, but there is no way to save it to the Save folder.

AUTOMATIC1111 does not have this either, though I could swear it did at some point.

### Version Platform Description

Version
updated: 2023-04-25
hash: 058666f9

OS
Windows 10

Browser
Firefox for Windows, Firefox for Android, Brave for iPad

**Comment by vladmandic** [comment]
valid request. i'd welcome pr for that, if not i'll place it on backlog.

**Comment by keenmouse** [comment]
Please do backlog it. I'm not a developer and it doesn't look like there's interest from anyone else.

**Comment by vladmandic** [comment]
done.
