### ISSUE TITLE
[Issue]:  Error when generating images with the Composable LoRA extension on AUTO1111 fork

### ISSUE THREAD

**Issue by TheRobberPanda** [vladmandic/automatic#629]
### Issue Description

Description:

When generating images after installing the Composable LoRA extension (https://github.com/opparco/stable-diffusion-webui-composable-lora) on the AUTO1111 fork, an error is raised. The error message is as follows:
```
Traceback (most recent call last):
  File "C:\Astronomically large folder\automatic\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Astronomically large folder\automatic\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "C:\Astronomically large folder\automatic\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Astronomically large folder\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Astronomically large folder\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
```
Here are my installed extensions:
- LDSR
- Lora
- ScuNET
- SwinIR
- a1111-sd-webui-lycoris (https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris, commit hash: ce584a0f, Sun Apr 23 14:50:56 2023)
- clip-interrogator-ext (https://github.com/pharmapsychotic/clip-interrogator-ext.git, commit hash: 9e6bbd9b, Tue Mar 28 03:20:44 2023)
- multidiffusion-upscaler-for-automatic1111 (https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111, commit hash: 6931b89c, Sat Apr 29 12:10:43 2023)
- prompt-bracket-checker
- sd-dynamic-thresholding (https://github.com/mcmonkeyprojects/sd-dynamic-thresholding, commit hash: 5d3465c4, Wed Apr 12 12:39:43 2023)
- sd-extension-aesthetic-scorer (https://github.com/vladmandic/sd-extension-aesthetic-scorer, commit hash: 896b6aa0, Sat Apr 22 15:30:47 2023)
- sd-extension-steps-animation (https://github.com/vladmandic/sd-extension-steps-animation, commit hash: 90663eb7, Sat Apr 15 15:52:38 2023)
- sd-extension-system-info (https://github.com/vladmandic/sd-extension-system-info, commit hash: cc86ce88, Thu Apr 20 03:53:09 2023)
- sd-webui-controlnet (https://github.com/Mikubill/sd-webui-controlnet, commit hash: 4d4

### Version Platform Description

The version used is `Version: 69ee51f7 Sat Apr 29 14:16:39 2023 -0400`. I am using Windows 10 LTSC. Browser is Chrome.

**Comment by TheRobberPanda** [comment]
Please, let me know if you need any additional information, and thank you for your hard work, I really appreciate it.

**Comment by Shadowghost** [comment]
Can you check if it works with this fork, he updated the extension to match some current changes: https://github.com/a2569875/stable-diffusion-webui-composable-lora

**Comment by vladmandic** [comment]
there are at least three issues with composable lora extension.

it hijaacks torch processing as soon as its loaded, it doesn't wait for it to be enabled at all. this is really bad behavior
<https://github.com/opparco/stable-diffusion-webui-composable-lora/blob/d4963e487c55e2adb292fa2021fa5c05bf169a7d/scripts/composable_lora_script.py#LL24C1-L25C62>

it relies on obsolete options which were removed both here in a1111 a while ago:
<https://github.com/opparco/stable-diffusion-webui-composable-lora/blob/d4963e487c55e2adb292fa2021fa5c05bf169a7d/composable_lora.py#LL59C24-L59C46>

it doesn't check tensor location in its processing, so at the end you have big chances in ending up with torch runtime error:
> RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

all-in-all, this is BAD, no chance i'd support this extension without some major work from extension author.
