### ISSUE TITLE
[Bug]: Could not find a version that satisfies the requirement for triton

### ISSUE THREAD

**Issue by aluhrs13** [vladmandic/automatic#63]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Running webui.bat (Windows) hits an error: `Could not find a version that satisfies the requirement triton (from versions: none)`

### Steps to reproduce the problem

1. .\webui.bat

### What should have happened?

Installation worked

### Commit where the problem happens

latest

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```powershell
PS D:\StableDiffusion\automatic> .\webui.bat
venv "D:\StableDiffusion\automatic\venv\Scripts\Python.exe"
Installing torch and torchvision
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu118
Collecting torch
  Using cached https://download.pytorch.org/whl/cu118/torch-2.0.0%2Bcu118-cp310-cp310-win_amd64.whl (2611.3 MB)
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/cu118/torchaudio-2.0.1%2Bcu118-cp310-cp310-win_amd64.whl (2.5 MB)
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cu118/torchvision-0.15.1%2Bcu118-cp310-cp310-win_amd64.whl (4.9 MB)
ERROR: Could not find a version that satisfies the requirement triton (from versions: none)
ERROR: No matching distribution found for triton
Traceback (most recent call last):
  File "D:\StableDiffusion\automatic\launch.py", line 335, in <module>
    prepare_environment()
  File "D:\StableDiffusion\automatic\launch.py", line 238, in prepare_environment
    run(f'"{python}" -m {torch_command}', "Installing torch and torchvision", "Couldn't install torch", live=True)
  File "D:\StableDiffusion\automatic\launch.py", line 67, in run
    raise RuntimeError(f"""{errdesc or 'Error running command'}.
RuntimeError: Couldn't install torch.
Command: "D:\StableDiffusion\automatic\venv\Scripts\python.exe" -m pip install torch torchaudio torchvision triton --force --extra-index-url https://download.pytorch.org/whl/cu118
Error code: 1
Press any key to continue . . .
```
### Additional information

I haven't tried to look too deep into this yet, totally could be user error. Mostly posting in case there's an obvious solution.

**Comment by vladmandic** [comment]
i've updated dependencies so this repo tries to use torch 2.0, but it seems that not all optional packages are yet available on windows.
can you try:

> set TORCH_COMMAND="pip install torch torchaudio torchvision --force --extra-index-url https://download.pytorch.org/whl/cu118"

and rerun the script?

if that works, i'll make it as default for windows

**Comment by aluhrs13** [comment]
Thanks! Did a pull and complete repo reset. Just running the batch file straight off the pull

```powershell
Creating venv in directory D:\StableDiffusion\automatic\venv using python "C:\Users\aluhr\AppData\Local\Programs\Python\Python310\python.exe"
venv "D:\StableDiffusion\automatic\venv\Scripts\Python.exe"
Traceback (most recent call last):
  File "D:\StableDiffusion\automatic\launch.py", line 335, in <module>
    prepare_environment()
  File "D:\StableDiffusion\automatic\launch.py", line 241, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "D:\StableDiffusion\automatic\launch.py", line 107, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "D:\StableDiffusion\automatic\launch.py", line 83, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "D:\StableDiffusion\automatic\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'torch' has no attribute 'cuda'
```

Realized the README says to install xformers and PyTorch first, and saw this error when trying that:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.16 requires torch==1.13.1, but you have torch 2.0.0+cu117 which is incompatible.
```

I'm not super familiar with Python, but competent enough to take directions if there's a few things you think I'd need to tweak or try.

**Comment by aluhrs13** [comment]
So I got it working, but haven't tried with xformers yet. I installed `xformers`, then ran `webui.bat` with your new torch command, that made good progress but failed on loading `rich`, I had to manually run `pip -r requirements.txt`, then it worked. Will try with xformers when I get some time.

**Comment by vladmandic** [comment]
If you're using torch 2.0, you don't need xformers at all. Xformers are important only for torch 1.13.
I'll update the readme.

**Comment by aluhrs13** [comment]
Wow I’m getting way better performance with your repo and like your customizations a lot. Thanks for making it available and the help!

**Comment by vladmandic** [comment]
i'm closing the issue since its resolved, but feel free to post any questions.
