### ISSUE TITLE
[Issue]: AttributeError: 'Namespace' object has no attribute 'debug'

### ISSUE THREAD

**Issue by metadreamx** [vladmandic/automatic#633]
### Issue Description

Every time I generate an image It disappears and this is the error I am seeing. Any fix?

AttributeError: 'NoneType' object has no attribute 'startswith'
100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [00:24<00:00,  2.47s/it]
gradio call: AttributeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\Powered By Virl\AUTO1111NEW\automatic\modules\call_queue.py:58 in f                                               │
│                                                                                                                      │
│    57 │   │   │   │   pr.enable()                                                                                    │
│ ❱  58 │   │   │   res = list(func(*args, **kwargs))                                                                  │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                        │
│                                                                                                                      │
│ D:\Powered By Virl\AUTO1111NEW\automatic\modules\call_queue.py:38 in f                                               │
│                                                                                                                      │
│    37 │   │   │   try:                                                                                               │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    39 │   │   │   finally:                                                                                           │
│                                                                                                                      │
│ D:\Powered By Virl\AUTO1111NEW\automatic\modules\txt2img.py:49 in txt2img                                            │
│                                                                                                                      │
│   48 │   generation_info_js = processed.js()                                                                         │
│ ❱ 49 │   if cmd_opts.debug:                                                                                          │
│   50 │   │   log.info(f'Processed: {len(processed.images)} Memory: {memory_stats()} txt')                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Namespace' object has no attribute 'debug'

### Version Platform Description

Date: Sat Apr 29 18:24:35 2023
updated: 2023-04-29
hash: 6cd4d62f
url: https://github.com/vladmandic/automatic/tree/master

GPU
device: NVIDIA GeForce RTX 2070 (1) (compute_37) (7, 5)
cuda: 11.8
cudnn: 8700

Platform
arch: AMD64
cpu: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.6

Memory
ram: free:23.82 used:0.03 total:23.85
gpu: free:4.01 used:3.99 total:8.0
gpu-active: current:2.03 peak:2.56
gpu-allocated: current:2.03 peak:2.56
gpu-reserved: current:2.03 peak:3.22
gpu-inactive: current:0.0 peak:0.14
events: retries:0 oom:0

**Comment by vladmandic** [comment]
if you run `webui --help`, what does it say?

**Comment by vladmandic** [comment]
nvm, i just made debug flag as optional, closing as fixed.

**Comment by metadreamx** [comment]
I ran Launch.py 3 times it seemed to have fixed all the warnings and updated.
