### ISSUE TITLE
[Feature]: Add torch._dynamo.config.suppress_errors = True/False as an option to the CUDA settings

### ISSUE THREAD

**Issue by ke1ne** [vladmandic/automatic#636]
### Feature description

Hi, please add such an option to the CUDA settings and sd_hijack.py. It's not a perfect solution, for sure. But this couple of lines and checkboxes will allow risky guys to run and test torch.compile using the current not-totally-stable Torch 2.0 with less of additional debugging.
Thanks!

### Version Platform Description

Version: 9ac7f377

**Comment by vladmandic** [comment]
done.
