### ISSUE TITLE
[Issue]: Token Merging Maximum Downsampling config breaks browser access

### ISSUE THREAD

**Issue by Gazzoo-byte** [vladmandic/automatic#637]
### Issue Description

Trying to interact with the "Maximum Downsampling" config results in the UI becoming unresponsive until the webpage is reloaded - no output given to CMD, however Firefox's browser console provides the below information, also tested in Edge with the same behaviour, also appears to be irrespective of which theme is active

```
Uncaught (in promise) TypeError: n[0].includes is not a function
    c http://127.0.0.1:7860/assets/index.a5a7351b.js:1
    c http://127.0.0.1:7860/assets/index.a5a7351b.js:1
    p http://127.0.0.1:7860/assets/index.a5a7351b.js:1
    Ar http://127.0.0.1:7860/assets/index.37b24c07.js:4
    Xt http://127.0.0.1:7860/assets/index.37b24c07.js:4
index.a5a7351b.js:1:1969
```

### Version Platform Description

Win 11, Firefox 112.0.2 and Edge 112.0.1722.64 and version: 9ac7f377 Sat Apr 29 19:30:26 2023 -0400

**Comment by nekoworkshop** [comment]
Thanks for the report. I have a PR that includes a fix for this. https://github.com/vladmandic/automatic/pull/632

**Comment by vladmandic** [comment]
pr is merged, closing.
