### ISSUE TITLE
[Issue]: Running remotely (colab/runpod), everything is just the same as Auto1111, only a bit faster

### ISSUE THREAD

**Issue by roseyyy2022ai** [vladmandic/automatic#642]
### Issue Description

I have a pretty terrible computer to be able to run SD locally, so I mostly use remote services such as RunPod and Google Colab (mostly colab, but runpod has the same issue)
It looks like it is possible to install this webui there as well, but it doesn't seem to really change anything.
Here on this repository it says that the webui comes with ControlNet, Image Browser and some other popular extensions preinstalled, while I have figured that I still have to install everything manually.
I had to set up the model download cell in the notebook to run twice and manually create some directories (models/Stable-diffusion, models/Lora etc.) since the first time nothing was being created and downloaded....???
And the interface doesn't look any different from the regular Automatic1111 UI when started up, trying to install gradio themes doesn't work either.
Looks like the only thing that changes is how fast everything is downloaded compared to when I have Auto1111 selected, even though visually nothing really changes as promised (and as it seems to work on local installations - I've seen other people have it locally)
.....
Am I missing something in the installation steps? (I've just cloned the repo)
I'd really appreciate you looking into this and trying to help me.
Thanks. May everyone reading this have a great day 🙂
[Here's the link to the colab notebook I use (it's custom)](https://colab.research.google.com/drive/1i2wQDB9XAdG_fHXhmr1j7ipr9-Y7-T2S?hl=en)
----------
[Alternative URL](https://colab.research.google.com/drive/1i2wQDB9XAdG_fHXhmr1j7ipr9-Y7-T2S?usp=share_link)

**Comment by ShyRed** [comment]
@roseyyy2022ai There's already a discussion regarding colab notebooks: #81

**Comment by vladmandic** [comment]
closing as answered.
