### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by luka0611** [vladmandic/automatic#647]
### Issue Description

I can't apply any lora, getting this message:

AttributeError: 'Options' object has no attribute 'lora_apply_to_outputs'

Here a screenshot.:

![image](https://user-images.githubusercontent.com/6626119/235356874-fa466761-0e93-4407-a8fe-697404d455ff.png)

It was working a few days ago, but now it doesn't work with any loras

### Version Platform Description

Browser: Opera GX
OS: Windows 11 22H2

**Comment by vladmandic** [comment]
extension composable lora is misbehaving badly, delete it.
see <https://github.com/vladmandic/automatic/issues/629#issuecomment-1528884183>
