### ISSUE TITLE
[Issue]: Start Up issues

### ISSUE THREAD

**Issue by Doctor0S** [vladmandic/automatic#650]
### Issue Description

I am using the --upgrade flag, but running into an error where the flag isn't recognized and not allowing the Webui to start.  when starting without the flag it'll run okay while getting an error from the the load module from built in lycoris extension until it claims that the port 7860 is in use and exits out of the webui. 

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\automatic\modules\script_loading.py:10 in load_module                                                             │
│                                                                                                                      │
│    9 │   try:                                                                                                        │
│ ❱ 10 │   │   module_spec.loader.exec_module(module)                                                                  │
│   11 │   except Exception as e:                                                                                      │
│ in exec_module:883                                                                                                   │
│                                                                                                                      │
│                                               ... 2 frames hidden ...                                                │

Also still having the issue with extra networks (TI, Lora, Checkpoints, hypernetworks) not fully loading.  Clicking on the extra network icon works fine but some are just omitted, refreshing brings them up, but if I close the extra network menu and reopen it I have to refresh it again.  I do have a large number of these models so it may just be a personal issue with too many models. 

### Version Platform Description

12:02:42-214119 INFO     Python 3.10.10 on Windows
12:02:42-526673 INFO     Version: ac78a48c Sun Apr 30 11:42:46 2023 -0400
12:02:42-779078 INFO     Latest published version: d62ee69c75fe79c9452d51b0997cf5e91efb7dca 2023-04-30T16:01:25Z

**Comment by vladmandic** [comment]
i just updated launcher as it was not parsing all command line flags unless there is at least one full complete run of installation.
