### ISSUE TITLE
[Issue]:  Unable to launch post todays updates

### ISSUE THREAD

**Issue by Lumpsack** [vladmandic/automatic#652]
### Issue Description

Hi - after using the upgrade this afternoon I cannot launch the application - for info I'm running directml (not via the branch).

Here is the error from the strartup

![image](https://user-images.githubusercontent.com/127429289/235366495-43655b2f-5a17-40f8-a6c4-c7a78ee913d5.png)
![image](https://user-images.githubusercontent.com/127429289/235366498-bc3c7576-aeff-448b-9f48-4375ce72c7ab.png)

From setup.log

2023-04-30 18:01:46,616 | DEBUG | D:\GitHub\Vlad\automatic\setup.py | 
Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\GitHub\Vlad\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "D:\GitHub\Vlad\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "D:\GitHub\Vlad\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "D:\GitHub\Vlad\automatic\extensions\openOutpaint-webUI-extension\install.py", line 3, in <module>
    from modules import scripts
  File "D:\GitHub\Vlad\automatic\modules\scripts.py", line 6, in <module>
    from modules import paths, script_callbacks, extensions, script_loading, scripts_postprocessing, errors
  File "D:\GitHub\Vlad\automatic\modules\extensions.py", line 5, in <module>
    from modules import shared, errors
  File "D:\GitHub\Vlad\automatic\modules\shared.py", line 53, in <module>
    devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan, devices.device_codeformer = (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_optimal_device() for x in ['sd', 'interrogate', 'gfpgan', 'esrgan', 'codeformer'])
  File "D:\GitHub\Vlad\automatic\modules\shared.py", line 53, in <genexpr>
    devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan, devices.device_codeformer = (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_optimal_device() for x in ['sd', 'interrogate', 'gfpgan', 'esrgan', 'codeformer'])
  File "D:\GitHub\Vlad\automatic\modules\devices.py", line 61, in get_optimal_device
    return torch.device(get_optimal_device_name())
  File "D:\GitHub\Vlad\automatic\modules\devices.py", line 44, in get_optimal_device_name
    if shared.cmd_opts.use_ipex:
AttributeError: 'Namespace' object has no attribute 'use_ipex'. Did you mean: 'use_cpu'?

### Version Platform Description

18:00:59-807148 INFO     Python 3.10.7 on Windows
18:01:01-053615 INFO     **Version: 682330b1 Sun Apr 30 10:54:59 2023 -0400**
18:01:03-967759 INFO     **Upgraded to version: 7eb82e26 Sun Apr 30 12:21:32 2023 -0400**
18:01:03-969759 INFO     Setting environment tuning
18:01:03-974268 INFO     Using DirectML Backend
18:01:03-976269 INFO     Installing package: torch==2.0.0 torchvision torch-directml
18:01:09-949085 INFO     Torch 2.0.0+cpu
18:01:09-950083 INFO     Torch backend: DirectML (torch-directml 0.2.0.dev230426)
18:01:10-153276 INFO     Torch detected GPU: AMD Radeon RX 7900 XTX
18:01:10-154276 INFO     DirectML default device: AMD Radeon RX 7900 XTX
18:01:10-155276 INFO     Verifying requirements
18:01:10-175572 INFO     Running setup
18:01:10-176248 INFO     Installing packages
18:01:10-177275 INFO     Installing repositories
18:01:10-378641 INFO     Installing submodules
18:01:12-264301 INFO     Updating submodules
18:01:22-744370 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
18:01:37-145184 INFO     Extensions enabled: ['a1111-sd-webui-tagcomplete', 'bad_prompt', 'canvas-zoom', 'EasyNegative',                         'openOutpaint-webUI-extension', 'sd-dynamic-prompts', 'sd-webui-ar',
                         'sd-webui-aspect-ratio-helper', 'Stable-Diffusion-Webui-Civitai-Helper',
                         'stable-diffusion-webui-wd14-tagger', 'SwinIR']
18:01:46-615594 ERROR    Error running extension installer:
                         D:\GitHub\Vlad\automatic\extensions\openOutpaint-webUI-extension\install.py
18:01:52-493311 INFO     Updating Wiki
18:01:53-803154 WARNING  Setup complete with errors (1)
18:01:53-805154 WARNING  See log file for more details: setup.log
18:01:53-813153 INFO     Running extension preloading

**Comment by vladmandic** [comment]
its fixed, update again. pr that was merged introduced a circular dependency.
