### ISSUE TITLE
[Feature]: do not downgrade pip packages :)

### ISSUE THREAD

**Issue by arpitest** [vladmandic/automatic#655]
### Feature description

Project description says this repo uses latest versions of libraries... but it keeps downgrading stuff at startup:

19:14:15-613014 WARNING  Package wrong version: diffusers 0.16.1 required 0.15.0
19:14:15-613761 INFO     Installing package: diffusers==0.15.0
19:14:23-044795 WARNING  Package wrong version: transformers 4.28.1 required 4.26.1
19:14:23-045357 INFO     Installing package: transformers==4.26.1

is it really required, aren't they compatible?

### Version Platform Description

ubuntu linux 22 lts server, Python 3.10.6
rtx 3090, Driver Version: 525.105.17   CUDA Version: 12.0

**Comment by vladmandic** [comment]
if you want to experiment, you can always change versions in `requirements.txt` and installer will use what's written there.

`diffusers` 0.16.0 had an issue. diffusers 0.16.1 just came out less than two days ago. and major project of integration this repo with core diffusers is in progress.

`tranfomers` are compatible, but some versions of transformers actually change quality of results. for some users, 4.19 still has best quality. its on my todo list to both test latest and compare quality through versions.
