### ISSUE TITLE
[Issue]: Checkpoint name option on X/Y/Z plot is broken

### ISSUE THREAD

**Issue by Varen-6** [vladmandic/automatic#657]
### Issue Description

Checkpoint name option on X/Y/Z plot script misses the button to get all checkpoints and if attempted to manually write down the checkpoints, the output results with the next error:
```
X/Y/Z plot will create 0 images on 1 0x1 grid. (Total steps to process: 0)
Unexpected error: Processing could not begin, you may need to refresh the tab or restart the service.
```

**Comment by DrJKL** [comment]
Might be in https://github.com/vladmandic/automatic/commit/9975f819a0e6de41a26b007ab1320c94e179cccd
```py
                if len(choices) > 12:
                    has_choices = False
            if has_choices:
```

**Comment by vladmandic** [comment]
fixed.
