### ISSUE TITLE
[Issue]: Switching checkpoints results in mismatch torch.cuda.FloatTensor vs torch.FloatTensor

### ISSUE THREAD

**Issue by scooller** [vladmandic/automatic#661]
### Issue Description

When i try all my checkpoint and Batch count to 6, is working fine after change the Checkpoint and i have the error

```
API error: POST: http://127.0.0.1:7860/internal/progress {'error': 'RuntimeError', 'detail': '', 'body': '', 'errors': 'Input type (torch.cuda.FloatTensor) and bias type (torch.FloatTensor) should be the same'}
HTTP API: RuntimeError
```

My list of checkpoint is:
- anime\allboymix_v10.safetensors [07374cf25e]
- anime\ambientgrapemixAnime2D_v20.safetensors [d50153c65a]
- anime\anyhentai_20.safetensors [61bc7001e8]
- anime\anything-v4.5-pruned.safetensors [6e430eb514]
- anime\beenyouToon_alpha2.safetensors [682908cf26]
- anime\camelliamix_v20.safetensors [b9157afbfe]
- anime\chilloutgerph_10.safetensors [827e8476eb]
- anime\cMoonSD_v10.safetensors [9c720387e9]
- anime\flat2DAnimerge_v10.safetensors [2c3bbd47cb]
- anime\gerphOrigin_10.safetensors [98d43f0041]
- anime\mistoonAmethyst_v20.safetensors [fc896c44f1]
- anime\mistoonAnime_v10.safetensors [a49140c6c5]
- anime\mistoonRuby_v20.safetensors [6704d37b6b]
- anime\mistoonSapphire_v10.safetensors [b3ef8af57b]
- anime\nyanMix_230303Absurd2.safetensors [8ac3e79e96]
- anime\OldFish_v11.safetensors [7be100b0f3]
- anime\primemix_v2.safetensors [71d9cd52ff]
- anime\toonify_v20.safetensors [392cea89e4]
- anime\wd-v1-2-full-ema-pruned.ckpt [5512bc271c]
- anime\yesmix_v16Original.safetensors [3e9211917c]
- mix\aoaokoPVCStyleModel_pvcAOAOKO.safetensors [cf64507cef]
- mix\deliberate_v2.safetensors [9aba26abdf]
- mix\dreamlike-photoreal-2.0.ckpt [fc52756a74]
- mix\neverendingDreamNED_bakedVae.safetensors [64b14b6ca5]
- mix\perfectWorld_v2Baked.safetensors [79e42fb744]
- orange\abyssorangemix2NSFW_abyssorangemix2Nsfw.safetensors [e892703c61]
- orange\abyssorangemix3AOM3_aom3a1.safetensors [f303d10812]
- orange\abyssorangemix3AOM3_aom3a1b.safetensors [5493a0ec49]
- orange\abyssorangemix3AOM3_aom3a3.safetensors [eb4099ba9c]
- orange\BloodorangemixHardcore_bloodorangemix.safetensors [55cfe9bdf0]
- others\duchaitendreamworld_V30.safetensors [cc69b2c5ec]
- real\dreamshaper_5Bakedvae.safetensors [a60cfaa90d]
- real\edgeOfRealism_eorV20Fp16BakedVAE.safetensors [7f6146b8a9]
- real\galaxytimemachines_v10.safetensors [1d3da73c93]
- real\lazymixRealAmateur_v10Updatedshowcase.ckpt [5a6d11cbf6]
- real\metagodRealRealism_v10.safetensors [5951fef99c]
- real\orangechillmix_v70.safetensors [a92311f07a]
- real\protogenX58RebuiltScifi_10.safetensors [847da9eead]
- real\realisticVisionV20_v20.safetensors [c0d1994c73]
- real\uberRealisticPornMerge_urpmv13.safetensors [40f9701da0]
- orange\abyssorangemix3AOM3_aom3a2.safetensors [553398964f]
- mix\kotosmix_v10.safetensors [0f789fc3c4]
- real\photomaxultrav1_.safetensors [c7f1c20497]
- real\cyberrealistic_v20.safetensors [e0be2fb84b]
- real\braBeautifulRealistic_v40.safetensors [9c03252bea]

### Version Platform Description

Windows 11
Python 3.10.11 on Windows
Version: 8c562941 Tue Apr 25 16:11:26 2023 -0400
Latest published version: 4dc5941912cc78bbe986a0c1fcdba6d7b194ab4d 2023-05-01T01:01:49Z
nVidia toolkit detected
Torch 2.0.0+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28

**Comment by scooller** [comment]
`
API error: POST: http://127.0.0.1:7860/internal/progress {'error': 'RuntimeError', 'detail': '', 'body': '', 'errors': 'Input type (torch.cuda.FloatTensor) and bias type (torch.FloatTensor) should be the same'}
HTTP API: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Vlad-automatic\venv\lib\site-packages\anyio\streams\memory.py:94 in receive                                       │
│                                                                                                                      │
│ C:\Vlad-automatic\venv\lib\site-packages\anyio\streams\memory.py:89 in receive_nowait                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
WouldBlock

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Vlad-automatic\venv\lib\site-packages\starlette\middleware\base.py:78 in call_next                                │
│                                                                                                                      │
│ C:\Vlad-automatic\venv\lib\site-packages\anyio\streams\memory.py:114 in receive                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
EndOfStream

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Vlad-automatic\modules\middleware.py:68 in exception_handling                                                     │
│                                                                                                                      │
│   67 │   │   try:                                                                                                    │
│ ❱ 68 │   │   │   return await call_next(req)                                                                         │
│   69 │   │   except CancelledError:                                                                                  │
│                                                                                                                      │
│ C:\Vlad-automatic\venv\lib\site-packages\starlette\middleware\base.py:84 in call_next                                │
│                                                                                                                      │
│                                               ... 35 frames hidden ...                                               │
│                                                                                                                      │
│ C:\Vlad-automatic\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward                                     │
│                                                                                                                      │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ ❱  463 │   │   return self._conv_forward(input, self.weight, self.bias)                                              │
│    464                                                                                                               │
│                                                                                                                      │
│ C:\Vlad-automatic\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward                               │
│                                                                                                                      │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                                             │
│ ❱  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                                     │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Input type (torch.cuda.FloatTensor) and bias type (torch.FloatTensor) should be the same
Loading weights: C:\stable-diffusion-webui\models\Stable-diffusion\anime\ambientgrapemixAnime2D_v20.safetensors ━━ 0… -…
                                                                                                                   GB
`

**Comment by vladmandic** [comment]
@scooller what are your settings under UI Settings -> CUDA

**Comment by scooller** [comment]
![imagen](https://user-images.githubusercontent.com/2198953/235547033-b8cbe4be-5891-4b48-b5b0-6075d9711cbd.png)

**Comment by scooller** [comment]
> @scooller what are your settings under UI Settings -> CUDA

![imagen](https://user-images.githubusercontent.com/2198953/235547092-ec9f2e7d-8242-41a7-87c4-7cdbd4a86985.png)

**Comment by vladmandic** [comment]
since you have RTX3060
- you really shouldn't be using BF16, use FP16.
- also, why no-half, no-half-vae and upcast-sampling. first, those mostly needed on some broken GPUs, yours is fine. unless you're using some terribly broken model/VAE (in which case, find a better model). and no-half-vae and upscast-sampling are one or the other, never both.
- and why is autocast disabled? that pretty much guarantees issues you're seeing.
- and cudnn benchmark enabled? why? unless you really know what that does?

btw, none of this has anything to do with x/y/z script, its far more general.

btw, with correct settings, you should be getting 2x performance as well.

honestly, i'm inclined to suggest to delete `config.json` and let server set best detected defaults on the next startup.

**Comment by scooller** [comment]
> since you have RTX3060
> 
>     * you really shouldn't be using BF16, use FP16.
> 
>     * also, why no-half, no-half-vae and upcast-sampling. first, those mostly needed on some broken GPUs, yours is fine. unless you're using some terribly broken model/VAE (in which case, find a better model). and no-half-vae and upscast-sampling are one or the other, never both.
> 
>     * and why is autocast disabled? that pretty much guarantees issues you're seeing.
> 
>     * and cudnn benchmark enabled? why? unless you really know what that does?
> 
> 
> btw, none of this has anything to do with x/y/z script, its far more general.
> 
> btw, with correct settings, you should be getting 2x performance as well.
> 
> honestly, i'm inclined to suggest to delete `config.json` and let server set best detected defaults on the next startup.

ok, i try with that setting, thanks

**Comment by scooller** [comment]
Same error

**Comment by scooller** [comment]
Same error when change the path for the checkpoints

**Comment by vladmandic** [comment]
lets isolate this:
- what are your cuda settings now?
- can you load one model, run single generate
- switch to second model, run single generate
- if possible, post links to last model you used sucesfully and first model where it fails.

**Comment by scooller** [comment]
![imagen](https://user-images.githubusercontent.com/2198953/235558536-3c5fcd01-dbe7-4835-ad12-8c81a4b3dc2f.png)
Run in single, it good no problem at all
First Checkpoint https://huggingface.co/andite/anything-v4.0/tree/main  it 4.5 pruned
Last checkpoint https://civitai.com/models/30240?modelVersionId=58693 Alpha model 2

![imagen](https://user-images.githubusercontent.com/2198953/235558866-be766083-4295-4ddd-8f5c-d95d16c6bc54.png)
![imagen](https://user-images.githubusercontent.com/2198953/235559193-0ae577f1-88df-4856-9a45-2b7c2e313305.png)

this it the prompt
![imagen](https://user-images.githubusercontent.com/2198953/235559239-c204191e-02df-494e-b767-0bf87404b1e8.png)

**Comment by vladmandic** [comment]
ok, that should be enough info, its going to take me a while to test everything, placing this issue on my backlog.

**Comment by vladmandic** [comment]
haven't manage to reproduce the problem yet, but based on whats visible i've pushed an update - can you update the repo and try? (no need for logs if issue is exactly the same).

**Comment by scooller** [comment]
I erase the venv and pull from git, it working right now
