### ISSUE TITLE
[Issue]: openpose issues

### ISSUE THREAD

**Issue by tonny1314sy** [vladmandic/automatic#662]
### Issue Description

TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
![image](https://user-images.githubusercontent.com/66168519/235407291-1c286cf9-531e-4d82-8b61-3f18e53b511a.png)

### Version Platform Description
windows 11 22H2  3080TI
_No response_

When I use the control net plug-in and call the openpose processor, I click to preview the processing result, and this error will be returned

**Comment by vladmandic** [comment]
can you fill the version section and add actual workflow that leads to this? i cannot do much based on the traceback alone.
