### ISSUE TITLE
[Issue]: Controlnet Showing loading twice

### ISSUE THREAD

**Issue by chuckkay** [vladmandic/automatic#671]
### Issue Description

Terminal window on startup of webui.bat shows controlnet loading twice, amongst other things

C:\AI\Automatic\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: dm is an invalid version and will not be supported in a future release
  warnings.warn(
No module 'xformers'. Proceeding without it.
Checkpoint not found: None
Available models: C:\AI\Automatic\models\Stable-diffusion 14
ControlNet v1.1.125
ControlNet v1.1.125
Loading theme: freddyaboulton/dracula_revamped
Checkpoint not found: None
Available models: C:\AI\Automatic\models\Stable-diffusion 14
CUDA SETUP: Loading binary C:\AI\Automatic\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.

**Comment by chuckkay** [comment]
Sorry didn’t know, thanks

**Comment by vladmandic** [comment]
no worries, all good, i'd rather provide answer than ignore it, just saying for future...
