### ISSUE TITLE
[Issue]: warning wrong version even after script says installing package (new version)

### ISSUE THREAD

**Issue by chuckkay** [vladmandic/automatic#672]
### Issue Description

I get this on every start of webui.bat
12:55:12-048352 WARNING  Package wrong version: diffusers 0.14.0 required 0.16.1
12:55:12-050353 INFO     Installing package: diffusers==0.16.1
used to say installing 15 today 16.1
point being I always seem to remain at version 14 of diffusers..

and also as of today I am now getting the same thing for transformers also
12:55:12-040353 INFO     Verifying requirements
12:55:12-048352 WARNING  Package wrong version: diffusers 0.14.0 required 0.16.1
12:55:12-050353 INFO     Installing package: diffusers==0.16.1
12:55:14-707870 WARNING  Package wrong version: transformers 4.26.1 required 4.28.1
12:55:14-707870 INFO     Installing package: transformers==4.28.1

**Comment by vladmandic** [comment]
can you do this and paste output here?

```shell
pip show diffusers
venv\Scripts\activate
pip show diffusers
```

**Comment by chuckkay** [comment]
C:\AI\Automatic>pip show diffusers
WARNING: Package(s) not found: diffusers

C:\AI\Automatic>venv\Scripts\activate

(venv) C:\AI\Automatic>pip show diffusers
WARNING: Ignoring invalid distribution - (c:\ai\automatic\venv\lib\site-packages)
WARNING: Ignoring invalid distribution -illow (c:\ai\automatic\venv\lib\site-packages)
Name: diffusers
Version: 0.14.0
Summary: Diffusers
Home-page: https://github.com/huggingface/diffusers
Author: The HuggingFace team
Author-email: patrick@huggingface.co
License: Apache
Location: c:\ai\automatic\venv\lib\site-packages
Requires: filelock, huggingface-hub, importlib-metadata, numpy, Pillow, regex, requests
Required-by:

**Comment by vladmandic** [comment]
It seems your venv cache is somehow corrupt, so newer version never actually gets installed.

I'd remove venv folder and let it be recreated.

**Comment by chuckkay** [comment]
yes some files in C:\Users\charl\Dropbox\PC\Desktop\venv\Lib\site-packages\sympy\utilities\mathml\data were currupted.  deleted venv folder. and let webui.bat recreate venv again..

that problem went away temporarily but came back after a few restarts (no changes or mods just restarted to make sure everything was running smoothly, but the problem is back 

C:\AI\Automatic>webui.bat --autolaunch --listen --upgrade
Using VENV: C:\AI\Automatic\venv
16:14:14-860579 INFO     Python 3.10.10 on Windows
16:14:15-121082 INFO     Version: d4a748d7 Mon May 1 12:25:35 2023 -0400
16:14:15-339837 INFO     Setting environment tuning
16:14:15-339837 INFO     nVidia CUDA toolkit detected
16:14:16-798193 INFO     Torch 2.0.0+cu118
16:14:16-813819 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
16:14:16-829445 INFO     Torch detected GPU: NVIDIA GeForce RTX 4070 Ti VRAM 12282 Arch (8, 9) Cores 60
16:14:16-829445 INFO     Verifying requirements
16:14:16-829445 WARNING  Package wrong version: diffusers 0.14.0 required 0.16.1
16:14:16-829445 INFO     Installing package: diffusers==0.16.1
16:14:19-600878 WARNING  Package wrong version: transformers 4.26.1 required 4.28.1
16:14:19-608871 INFO     Installing package: transformers==4.28.1
16:14:30-262999 INFO     Running setup
16:15:33-237219 INFO     Installing packages
16:15:33-237219 INFO     Installing repositories
16:15:33-398510 INFO     Installing submodules
16:15:35-364294 INFO     Updating submodules
16:15:42-040826 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
16:15:54-583633 INFO     Extensions enabled: ['a1111-sd-webui-tagcomplete', 'sd-dynamic-prompts',
                         'sd_dreambooth_extension', 'stable-diffusion-webui-state', 'training-picker']
16:16:17-997178 INFO     Updating Wiki
16:16:18-872868 INFO     Running extension preloading
16:16:18-872868 INFO     Server arguments: ['--autolaunch', '--listen', '--upgrade']
No module 'xformers'. Proceeding without it.
Checkpoint not found: None
Available models: C:\AI\Automatic\models\Stable-diffusion 14
ControlNet v1.1.125
ControlNet v1.1.125
Loading theme: freddyaboulton/dracula_revamped
Checkpoint not found: None
Available models: C:\AI\Automatic\models\Stable-diffusion 14
CUDA SETUP: Loading binary C:\AI\Automatic\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Loading weights: C:\AI\Automatic\models\Stable-diffusion\uberRealisticPornMergeURPM_urpmCE2Alpha.safetensors -- 0… -:-…
                                                                                                                GB
Creating model from config: C:\AI\Automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
API error: GET: http://localhost:7860/static/img/api-logo.svg {'error': 'HTTPException', 'detail': 'Forbidden', 'body': '', 'errors': '403'}
Loading weights: C:\AI\Automatic\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors ------------- 0.0/334.6 MB -:--:--
Applying scaled dot product cross attention optimization
Embeddings loaded:  (0)
Model loaded in 3.1s (load=0.4s create=0.3s apply=0.7s vae=0.6s move=1.0s)
Startup time: 18.9s (torch=3.5s gradio=1.4s libraries=0.8s codeformer=0.1s scripts=2.7s opts onchange=0.2s ui=2.5s
start=4.2s checkpoint=3.4s)

**Comment by chuckkay** [comment]
this error was new but only happened once
API error: GET: http://localhost:7860/static/img/api-logo.svg {'error': 'HTTPException', 'detail': 'Forbidden', 'body': '', 'errors': '403'}

but now i keep having that 
16:28:26-724670 WARNING  Package wrong version: diffusers 0.14.0 required 0.16.1
16:28:26-726669 INFO     Installing package: diffusers==0.16.1
16:28:29-478948 WARNING  Package wrong version: transformers 4.26.1 required 4.28.1
16:28:29-478948 INFO     Installing package: transformers==4.28.1




C:\AI\Automatic>webui.bat --autolaunch --listen --upgrade
Using VENV: C:\AI\Automatic\venv
16:28:24-693461 INFO     Python 3.10.10 on Windows
16:28:24-949413 INFO     Version: d4a748d7 Mon May 1 12:25:35 2023 -0400
16:28:25-235150 INFO     Setting environment tuning
16:28:25-238149 INFO     nVidia CUDA toolkit detected
16:28:26-678903 INFO     Torch 2.0.0+cu118
16:28:26-712665 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
16:28:26-714671 INFO     Torch detected GPU: NVIDIA GeForce RTX 4070 Ti VRAM 12282 Arch (8, 9) Cores 60
16:28:26-716670 INFO     Verifying requirements
16:28:26-724670 WARNING  Package wrong version: diffusers 0.14.0 required 0.16.1
16:28:26-726669 INFO     Installing package: diffusers==0.16.1
16:28:29-478948 WARNING  Package wrong version: transformers 4.26.1 required 4.28.1
16:28:29-478948 INFO     Installing package: transformers==4.28.1
16:28:39-786289 INFO     Running setup
16:28:39-786289 INFO     Installing packages
16:28:39-786289 INFO     Installing repositories
16:28:39-942537 INFO     Installing submodules
16:28:41-900866 INFO     Updating submodules
16:28:48-505478 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
16:28:59-494714 INFO     Extensions enabled: ['a1111-sd-webui-tagcomplete', 'sd-dynamic-prompts',
                         'sd_dreambooth_extension', 'stable-diffusion-webui-state', 'training-picker']
16:29:22-228238 INFO     Updating Wiki
16:29:23-000671 INFO     Running extension preloading
16:29:23-002666 INFO     Server arguments: ['--autolaunch', '--listen', '--upgrade']
No module 'xformers'. Proceeding without it.
Checkpoint not found: None
Available models: C:\AI\Automatic\models\Stable-diffusion 14
ControlNet v1.1.125
ControlNet v1.1.125
Loading theme: freddyaboulton/dracula_revamped
Checkpoint not found: None
Available models: C:\AI\Automatic\models\Stable-diffusion 14
CUDA SETUP: Loading binary C:\AI\Automatic\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Loading weights: C:\AI\Automatic\models\Stable-diffusion\uberRealisticPornMergeURPM_urpmCE2Alpha.safetensors -- 0… -:-…
                                                                                                                GB
Creating model from config: C:\AI\Automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
API error: GET: http://localhost:7860/static/img/api-logo.svg {'error': 'HTTPException', 'detail': 'Forbidden', 'body': '', 'errors': '403'}
Loading weights: C:\AI\Automatic\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors ------------- 0.0/334.6 MB -:--:--
Applying scaled dot product cross attention optimization
Embeddings loaded:  (0)
Model loaded in 3.0s (load=0.4s create=0.3s apply=0.6s vae=0.6s move=1.0s)
Startup time: 19.5s (torch=3.8s gradio=1.4s libraries=0.9s codeformer=0.1s scripts=2.8s opts onchange=0.1s ui=2.7s
start=4.3s checkpoint=3.3s)

**Comment by vladmandic** [comment]
It would be useful, but unfortunately it only works with hard-coded values, so its bound to break when there are any bigger changes.

**Comment by chuckkay** [comment]
now everything is running without errors in the system log but renders are taking 10 time longer???? beyond strange
almost like it's not utilizing cuda or torch  fyi nvidia RTX4070ti...
also getting that error regarding the api_svg logo

C:\AI\Automatic>webui.bat --autolaunch --listen --upgrade
Using VENV: C:\AI\Automatic\venv
17:32:54-540336 INFO     Python 3.10.10 on Windows
17:32:54-789878 INFO     Version: d4a748d7 Mon May 1 12:25:35 2023 -0400
17:32:55-040100 INFO     Setting environment tuning
17:32:55-040100 INFO     nVidia CUDA toolkit detected
17:32:56-454889 INFO     Torch 2.0.0+cu118
17:32:56-466940 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
17:32:56-466940 INFO     Torch detected GPU: NVIDIA GeForce RTX 4070 Ti VRAM 12282 Arch (8, 9) Cores 60
17:32:56-466940 INFO     Verifying requirements
17:32:56-513819 INFO     Running setup
17:32:56-513819 INFO     Installing packages
17:32:56-513819 INFO     Installing repositories
17:32:56-654440 INFO     Installing submodules
17:32:58-639942 INFO     Updating submodules
17:33:05-158518 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
17:33:15-826212 INFO     Extensions enabled: ['a1111-sd-webui-tagcomplete', 'sd-dynamic-prompts',
                         'stable-diffusion-webui-state', 'training-picker']
17:33:18-921630 INFO     Updating Wiki
17:33:19-687245 INFO     Running extension preloading
17:33:19-687245 INFO     Server arguments: ['--autolaunch', '--listen', '--upgrade']
No module 'xformers'. Proceeding without it.
Checkpoint not found: None
Available models: C:\AI\Automatic\models\Stable-diffusion 14
ControlNet v1.1.125
ControlNet v1.1.125
Loading theme: freddyaboulton/dracula_revamped
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Loading weights: C:\AI\Automatic\models\Stable-diffusion\uberRealisticPornMergeURPM_urpmCE1Alpha.safetensors -- 0… -:-…
                                                                                                                GB
Creating model from config: C:\AI\Automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
API error: GET: http://localhost:7860/static/img/api-logo.svg {'error': 'HTTPException', 'detail': 'Forbidden', 'body': '', 'errors': '403'}
Loading weights: C:\AI\Automatic\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors ------------- 0.0/334.6 MB -:--:--
Applying scaled dot product cross attention optimization
Embeddings loaded:  (0)
Model loaded in 2.9s (load=0.4s create=0.3s apply=0.7s vae=0.5s move=1.0s)
Startup time: 17.7s (torch=3.3s gradio=1.5s libraries=0.6s codeformer=0.1s scripts=2.2s opts onchange=0.3s ui=2.1s
start=4.5s checkpoint=3.1s)
  6%|█████                                                                              | 2/33 [00:05<01:27,  2.83s/it]
  0%|                                                                                           | 0/33 [00:00<?, ?it/s]
Progress 1.82it/s ---------------------------------------- 100% 0:00:00 0:00:18
Progress 1.62it/s ---------------------------------------- 100% 0:00:00 0:00:12
100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:30<00:00,  1.08it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 33/33 [00:30<00:00,  1.09it/s]
  9%|███████▌                                                                           | 3/33 [00:05<00:55,  1.83s/it]


Any suggestions appreciated

**Comment by vladmandic** [comment]
There's a pinned issue regarding performance problems. They are caused upstream and I've written a workaround in the issue until upstream is fixed.

**Comment by chuckkay** [comment]
Thanks for your great work

**Comment by vladmandic** [comment]
i'm closing the issue as resolved, feel free to create any new issues if there are problems.
i'll check separately whats going on with api-logo.svg

**Comment by chuckkay** [comment]
thanks
