### ISSUE TITLE
[Issue]: Performance problems with recent update

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#675]
### Issue Description

Performance can drop 2x or more compared to expected performance.

Cause is recent code change upstream and I've notified the author:
<https://github.com/KohakuBlueleaf/a1111-sd-webui-lycoris/issues/21>

As a temporary workaround, you can disable the extension `a1111-sd-webui-lycoris`:
1. UI -> Settings -> Extensions -> unselect extension
2. Restart server from command line so extension is not loaded during startup

**Comment by Danamir** [comment]
I confirm, the workaround is working. 18s generation with the extension enabled, 8s without the extension. 😅

**Comment by leppie** [comment]
Workaround works 👍

**Comment by Vodrin** [comment]
I'm still seeing a huge performance decrease with lora/lycoris disabled (or prior commits)

From 15.38 / 25.41 / 33.0 it/s (batch1/2/4) to 3.57 / 7.04 / 13.45 it/s. The only change being transformers 4.26.1 to 4.28.1.

**Comment by vladmandic** [comment]
i've downgraded transformers in the meantime due to some compatibility issues.

**Comment by thygate** [comment]
confirmed workaround is working for me .. performance impact was an order of magnitude difference in generation times for me. (11 secs to 1 sec now)

**Comment by vladmandic** [comment]
issue is resolved.

@wzgrx if you still have performance problems, lets look at them separately as its not the same as root cause for which this issue wsa created.
