### ISSUE TITLE
[Issue]: 404 error on API /docs

### ISSUE THREAD

**Issue by Danamir** [vladmandic/automatic#676]
### Issue Description

The API docs previously accessible at http://127.0.0.1:7860/docs now returns a 404 error. Tried with the command line argument `--listen` and without.

The rest of the API is working fine, for example http://127.0.0.1:7860/sdapi/v1/sd-models still gets the models list.

The docs URL was was working yesterday. 

### Version Platform Description

Installed version : Version: d4a748d7 Mon May 1 12:25:35 2023 -0400
OS : Windows 10
Browser : Firefox 112.0.2

**Comment by zolrath** [comment]
I can confirm this issue is happening here as well!

**Comment by Danamir** [comment]
In fact I got the same issue with the last release on `dev` branch of Auto1111. I created an issue on their side too : https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/9993

**Comment by vladmandic** [comment]
its been redesigned, check out <https://127.0.0.1:7860/?view=api>

**Comment by Danamir** [comment]
Thanks ! I guessed it would be something like that, but I couldn't find the new URL !

**Comment by Danamir** [comment]
Too bad the new `view=api` seems to be unusable at the moment. I'll wait for a later update.

![image](https://user-images.githubusercontent.com/15424198/235552347-fd0d3bdf-4bf5-4da1-8ffc-ab6f4aabdc36.png)

**Comment by vladmandic** [comment]
yeah, not a fan of the new layout or functionality at all as well.

**Comment by zolrath** [comment]
Hm, yeah this new view doesn't really help when building an external API client in another language.

The swagger UI allowed you to see the endpoint URLs and their parameters/response type and test them in the UI, this just seems to list the gradio_clients functionality?

**Comment by vladmandic** [comment]
gradio is trying to promote `gradio_client` as THE tool to access gradio. and its probably the worst tool out there.
this looks like a product manager decision that cares about tool promotion more than anything.
