### ISSUE TITLE
[Issue]: TypeError: list indices must be integers or slices, not NoneType

### ISSUE THREAD

**Issue by lolxdmainkaisemaanlu** [vladmandic/automatic#677]
### Issue Description

gradio call: TypeError
╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮
│ /home/siddhesh/Desktop/automatic/modules/call_queue.py:58 in f                                                                                                                                       │
│                                                                                                                                                                                                      │
│    57 │   │   │   │   pr.enable()                                                                                                                                                                    │
│ ❱  58 │   │   │   res = list(func(*args, **kwargs))                                                                                                                                                  │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                                                                                                        │
│                                                                                                                                                                                                      │
│ /home/siddhesh/Desktop/automatic/modules/call_queue.py:38 in f                                                                                                                                       │
│                                                                                                                                                                                                      │
│    37 │   │   │   try:                                                                                                                                                                               │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                                                                                                    │
│    39 │   │   │   finally:                                                                                                                                                                           │
│                                                                                                                                                                                                      │
│ /home/siddhesh/Desktop/automatic/modules/txt2img.py:24 in txt2img                                                                                                                                    │
│                                                                                                                                                                                                      │
│   23 │   │   seed_enable_extras=True,                                                                                                                                                                │
│ ❱ 24 │   │   sampler_name=sd_samplers.samplers[sampler_index].name,                                                                                                                                  │
│   25 │   │   batch_size=batch_size,                                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: list indices must be integers or slices, not NoneType
gradio call: TypeError
╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮
│ /home/siddhesh/Desktop/automatic/modules/call_queue.py:58 in f                                                                                                                                       │
│                                                                                                                                                                                                      │
│    57 │   │   │   │   pr.enable()                                                                                                                                                                    │
│ ❱  58 │   │   │   res = list(func(*args, **kwargs))                                                                                                                                                  │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                                                                                                        │
│                                                                                                                                                                                                      │
│ /home/siddhesh/Desktop/automatic/modules/call_queue.py:38 in f                                                                                                                                       │
│                                                                                                                                                                                                      │
│    37 │   │   │   try:                                                                                                                                                                               │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                                                                                                    │
│    39 │   │   │   finally:                                                                                                                                                                           │
│                                                                                                                                                                                                      │
│ /home/siddhesh/Desktop/automatic/modules/txt2img.py:24 in txt2img                                                                                                                                    │
│                                                                                                                                                                                                      │
│   23 │   │   seed_enable_extras=True,                                                                                                                                                                │
│ ❱ 24 │   │   sampler_name=sd_samplers.samplers[sampler_index].name,                                                                                                                                  │
│   25 │   │   batch_size=batch_size,                                                                                                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: list indices must be integers or slices, not NoneType

### Version Platform Description

GTX 1060 6GB

**Comment by vladmandic** [comment]
What is the workflow that leads to this? Having traceback alone does not help me.

**Comment by yunghoy** [comment]
1. Update webui 5/1/2023
2. Start webui
3. Create "a chair"
4. You get message below
```
Applying scaled dot product cross attention optimization
Weights loaded in 5.3s (load=3.6s apply=0.3s vae=0.3s device=1.1s)
gradio call: TypeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Users\AAA\Desktop\AI\automatic\modules\call_queue.py:58 in f                                                    │
│                                                                                                                      │
│    57 │   │   │   │   pr.enable()                                                                                    │
│ ❱  58 │   │   │   res = list(func(*args, **kwargs))                                                                  │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                        │
│                                                                                                                      │
│ C:\Users\AAA\Desktop\AI\automatic\modules\call_queue.py:38 in f                                                    │
│                                                                                                                      │
│    37 │   │   │   try:                                                                                               │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    39 │   │   │   finally:                                                                                           │
│                                                                                                                      │
│ C:\Users\AAA\Desktop\AI\automatic\modules\txt2img.py:24 in txt2img                                                 │
│                                                                                                                      │
│   23 │   │   seed_enable_extras=True,                                                                                │
│ ❱ 24 │   │   sampler_name=sd_samplers.samplers[sampler_index].name,                                                  │
│   25 │   │   batch_size=batch_size,                                                                                  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: list indices must be integers or slices, not NoneType

```

**Comment by vladmandic** [comment]
It's there, but disabled by default as it's 99.9% identical to some others.
Just go to settings and enable it.
