### ISSUE TITLE
[Bug]: New progress bars in console are always zeroed for models loading

### ISSUE THREAD

**Issue by ke1ne** [vladmandic/automatic#68]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

New progress bars in console are always zeroed for models loading. No errors, models loaded, generation works well.

![image](https://user-images.githubusercontent.com/8934421/228599244-b0e6ad0e-b8fd-4794-9b18-bb6a51313e9c.png)

### Steps to reproduce the problem

1. Run the UI.
2. Wait for model load.
OR
1. Change the model in drop-down.
2. Wait for model load.

### What should have happened?

Progress bars should reflect the progress.

### Commit where the problem happens

426268d54111f1dffce0e9c3967b5839f9d9f8f5

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
--ckpt-dir="E:\.ai\models" --vae-dir="E:\.ai\vae" --autolaunch --opt-channelslast --upcast-sampling --api --gradio-queue --update-all-extensions --theme dark --cors-allow-origins="http://127.0.0.1:7860"
```

### List of extensions

None.

### Console logs

```Shell
Nothing to log.
```

**Comment by vladmandic** [comment]
i've disabled gradio animations as they were fake animations to start with - they were not showing actual progress, just something to indicate busy state. 

yes, model loading should be represented better and i'm working on that, but old css-based progress bar that gradio was drawing was just bad and its gone.
