### ISSUE TITLE
[Issue]: latest clip-interrogator-ext incompatible with transformers==4.28.1

### ISSUE THREAD

**Issue by Metachs** [vladmandic/automatic#680]
### Issue Description

The current version of clip-interrogator-ext uses clip-interrogator 5.4, which is broken on transformers>4.26.1 (throws "The size of tensor a (8) must match...", see links below).  Need to revert to the previous commit [1ecedb5ccd59ada1e9b8f7b635bcdfa30459fa01](https://github.com/pharmapsychotic/clip-interrogator-ext/tree/1ecedb5ccd59ada1e9b8f7b635bcdfa30459fa01) which uses clip-interrogator 6.0 to support transformers==4.28.1.

https://github.com/pharmapsychotic/clip-interrogator-ext/issues/33
https://github.com/pharmapsychotic/clip-interrogator/issues/62

### Version Platform Description

Latest, W10

**Comment by vladmandic** [comment]
Thanks, I'll mark that version as required.

**Comment by vladmandic** [comment]
actually, i've downgraded to 4.26.1 as there are couple of more extensions that are not yet compatible.
