### ISSUE TITLE
Suddenly lot of errors[Issue]: 

### ISSUE THREAD

**Issue by ronbere** [vladmandic/automatic#681]
### Issue Description

Pleasesing VENV: D:\automatic\venv
23:21:01-014105 INFO     Python 3.10.9 on Windows
23:21:01-272567 INFO     Version: 75b741f1 Sun Apr 30 23:06:32 2023 -0400
23:21:01-678422 INFO     Latest published version: d4a748d758e1f3dd4bdf36c045fc30113043fe50 2023-05-01T16:25:35Z
23:21:01-680425 INFO     Setting environment tuning
23:21:01-684418 INFO     nVidia CUDA toolkit detected
23:21:02-927548 INFO     Torch 2.0.0+cu118
23:21:02-955578 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
23:21:02-958581 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 Ti VRAM 12287 Arch (8, 6) Cores 80
23:21:02-960583 INFO     Verifying requirements
23:21:02-972594 WARNING  Package wrong version: diffusers 0.16.1 required 0.15.0
23:21:02-974596 INFO     Installing package: diffusers==0.15.0
23:21:05-559036 WARNING  Package wrong version: gradio 3.28.1 required 3.23.0
23:21:05-562038 INFO     Installing package: gradio==3.23.0
23:21:08-292236 WARNING  Package wrong version: transformers 4.28.1 required 4.26.1
23:21:08-294238 INFO     Installing package: transformers==4.26.1
23:21:16-953668 INFO     Running setup
23:21:16-955670 INFO     Installing packages
23:21:16-956671 INFO     Installing package:
                         git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
23:21:22-371447 INFO     Installing repositories
23:21:22-533330 INFO     Installing submodules
23:21:24-720434 INFO     Updating submodules
23:21:35-239199 INFO     Extensions enabled: ['clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
23:22:09-454833 INFO     Extensions enabled: ['canvas-zoom', 'model-keyword', 'openOutpaint-webUI-extension',
                         'openpose-editor', 'posex', 'sd-canvas-editor', 'sd-webui-3d-open-pose-editor',
                         'sd-webui-additional-networks', 'sd-webui-aspect-ratio-helper', 'sd-webui-regional-prompter',
                         'sd-webui-supermerger', 'sd_dreambooth_extension', 'stable-diffusion-webui-Prompt_Generator',
                         'stable-diffusion-webui-two-shot', 'ultimate-upscale-for-automatic1111']
23:22:20-391041 ERROR    Error running extension installer:
                         D:\automatic\extensions\openOutpaint-webUI-extension\install.py
23:22:41-495454 ERROR    Error running extension installer: D:\automatic\extensions\sd_dreambooth_extension\install.py
23:22:43-508904 INFO     Updating Wiki
23:22:44-765957 WARNING  Setup complete with errors (2)
23:22:44-767958 WARNING  See log file for more details: setup.log
23:22:44-770961 INFO     Running extension preloading
23:22:44-772963 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
Checkpoint not found: None
Available models: F:\Telechargements\SUPER SD 2.0 Dependencies\stable-diffusion-webui\models\Stable-diffusion 130
ControlNet v1.1.125
ControlNet v1.1.125
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
[AddNet] Updating model hashes...
0it [00:00, ?it/s]
Module load: D:\automatic\extensions\sd_dreambooth_extension\scripts\main.py: ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\script_loading.py:10 in load_module                                                            │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ D:\automatic\extensions\sd_dreambooth_extension\scripts\main.py:51 in <module>                                      │
│                                                                                                                     │
│     50 )                                                                                                            │
│ >   51 from dreambooth.webhook import save_and_test_webhook                                                         │
│     52 from helpers.log_parser import LogParser                                                                     │
│                                                                                                                     │
│ D:\automatic\extensions\sd_dreambooth_extension\dreambooth\webhook.py:6 in <module>                                 │
│                                                                                                                     │
│     5                                                                                                               │
│ >   6 import discord_webhook                                                                                        │
│     7 from PIL import Image                                                                                         │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'discord_webhook' fill this form with as much information as possible

### Version Platform Description

Windows 10
Version: 75b741f1 Sun Apr 30 23:06:32 2023 -0400

**Comment by vladmandic** [comment]
Dreambooth extension installs it's own conflicting versions of core packages. Extension should never change core requirements, but that is authors choice.

**Comment by vladmandic** [comment]
i've downgraded my requirements for `transformers` as that seems to be the biggest issue, but general issue is that dreambooth requirements are not really in-sync. which would be ok if they were private requirements, but it changes requirements of the core repo which is a no-no.

hope downgrade of transformers helps, but otherwise, this is on dreambooth extension and not much i can do about it.
