### ISSUE TITLE
[Issue]: Cannot generate images on Intel Integrated graphics Card using DirectML

### ISSUE THREAD

**Issue by amarillonmc** [vladmandic/automatic#682]
### Issue Description

Since I noticed DirectML support was added to this fork, I decided to give it a try on one of my dedi servers running Xeon E3-1275 v5 with Intel(R) HD Graphics P530 Integrated Graphics - sources said this one's general performance is "slightly behind a dedicated GeForce 920M" so I figured it wouldn't hurt to have a try.

While everything else works fine and I can get to the Server Interface, attempting to generate an image returns the following error(I've not made/add any additional configurations/parameters):

`Using VENV: D:\SD\automatic\venv
05:25:09-425447 INFO     Python 3.10.10 on Windows
05:25:10-019267 INFO     Version: d4a748d7 Mon May 1 12:25:35 2023 -0400
05:25:10-503455 INFO     Setting environment tuning
05:25:10-514964 INFO     Using DirectML Backend
05:25:11-003364 INFO     Installing package: torch==2.0.0 torchvision torch-directml
05:25:20-735631 INFO     Torch 2.0.0+cpu
05:25:20-883425 INFO     Torch backend: DirectML (torch-directml 0.2.0.dev230426)
05:25:20-939168 INFO     Torch detected GPU: Intel(R) HD Graphics P530
05:25:20-967671 INFO     Torch detected GPU: Intel(R) HD Graphics P530
05:25:20-970663 INFO     DirectML default device: Intel(R) HD Graphics P530
05:25:20-972663 INFO     Installing package: tensorflow==2.12.0
05:26:05-487545 INFO     Verifying requirements
05:26:05-503741 WARNING  Package wrong version: diffusers 0.15.0 required 0.16.1
05:26:05-519248 INFO     Installing package: diffusers==0.16.1
05:26:10-425268 WARNING  Package wrong version: gradio 3.23.0 required 3.28.1
05:26:10-434623 INFO     Installing package: gradio==3.28.1
05:26:15-378422 WARNING  Package wrong version: transformers 4.26.1 required 4.28.1
05:26:15-378422 INFO     Installing package: transformers==4.28.1
05:26:33-727505 WARNING  Package wrong version: timm 0.4.12 required 0.6.13
05:26:33-727505 INFO     Installing package: timm==0.6.13
05:26:38-050242 INFO     Running setup
05:26:38-050242 INFO     Installing packages
05:26:38-050242 INFO     Installing repositories
05:26:38-237643 INFO     Installing submodules
05:26:41-456457 INFO     Updating submodules
05:26:51-542854 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
05:27:11-709941 INFO     Extensions enabled: []
05:27:11-717440 INFO     Updating Wiki
05:27:13-222072 INFO     Running extension preloading
05:27:13-222072 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
Checkpoint not found: None
Available models: D:\SD\automatic\models\Stable-diffusion 4
ControlNet v1.1.125
ControlNet v1.1.125
Loading theme: black-orange
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Loading weights: D:\SD\automatic\models\Stable-diffusion\AnythingV5_v5PrtRE.safetensors ------------ 0.0/2.1 GB -:--:--
Creating model from config: D:\SD\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying sub-quadratic cross attention optimization
Embeddings loaded:  (0)
Model loaded in 71.8s (load=2.4s create=0.5s apply=59.2s move=9.6s)
Startup time: 114.6s (torch=4.4s gradio=7.0s libraries=0.8s models=0.1s codeformer=0.2s scripts=26.7s ui=3.0s
start=0.3s scripts app_started_callback=0.1s checkpoint=72.0s)
Initializing ----------------------------------------   0% -:--:-- 0:00:01
gradio call: NotImplementedError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\SD\automatic\modules\call_queue.py:58 in f                                                                       │
│                                                                                                                     │
│    57 │   │   │   │   pr.enable()                                                                                   │
│ >  58 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ D:\SD\automatic\modules\call_queue.py:38 in f                                                                       │
│                                                                                                                     │
│    37 │   │   │   try:                                                                                              │
│ >  38 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    39 │   │   │   finally:                                                                                          │
│                                                                                                                     │
│                                              ... 39 frames hidden ...                                               │
│                                                                                                                     │
│ D:\SD\automatic\modules\dml\__init__.py:27 in memory_stats                                                          │
│                                                                                                                     │
│   26 │   │   optimizer = DirectML.get_optimizer(device)                                                             │
│ > 27 │   │   return optimizer.memory_stats(device.index)                                                            │
│   28                                                                                                                │
│                                                                                                                     │
│ D:\SD\automatic\modules\dml\optimizer\intel\__init__.py:5 in memory_stats                                           │
│                                                                                                                     │
│   4 │   def memory_stats(index):                                                                                    │
│ > 5 │   │   raise NotImplementedError()                                                                             │
│   6 │   │   # DML TODO: Implement                                                                                   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
NotImplementedError`

From the error, I assume Intel Support is not completed yet? or are there anything else I can do on that?

### Version Platform Description

Program Version: d4a748d7 Mon May 1 12:25:35 2023 -0400
OS: Windows Server 2022 21HR
CPU: Xeon E3-1275 v5
Memory: 64 GB
GPU: Intel(R) HD Graphics P530 with 32GB shared video memory
Browser: Edge

**Comment by vladmandic** [comment]
i've added some exception handling wherever that function is accessed, hope it helps.
looping in @lshqqytiger as author of directml code.

**Comment by amarillonmc** [comment]
It... doesn't help:

Using VENV: D:\SD\automatic\venv
07:26:14-721837 INFO     Python 3.10.10 on Windows
07:26:15-025919 INFO     Version: d22103e9 Mon May 1 19:12:10 2023 -0400
07:26:15-346657 INFO     Setting environment tuning
07:26:15-359162 INFO     Using DirectML Backend
07:26:15-549432 INFO     Installing package: torch==2.0.0 torchvision torch-directml
07:26:19-471565 INFO     Torch 2.0.0+cpu
07:26:19-471565 INFO     Torch backend: DirectML (torch-directml 0.2.0.dev230426)
07:26:19-518862 INFO     Torch detected GPU: Intel(R) HD Graphics P530
07:26:19-550004 INFO     Torch detected GPU: Intel(R) HD Graphics P530
07:26:19-550004 INFO     DirectML default device: Intel(R) HD Graphics P530
07:26:19-550004 INFO     Verifying requirements
07:26:19-581139 WARNING  Package wrong version: transformers 4.28.1 required 4.26.1
07:26:19-581139 INFO     Installing package: transformers==4.26.1
07:26:35-627932 INFO     Running setup
07:26:35-627932 INFO     Installing packages
07:26:35-627932 INFO     Installing repositories
07:26:35-815389 INFO     Installing submodules
07:26:38-534373 INFO     Updating submodules
07:26:48-128243 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
07:27:02-788106 INFO     Extensions enabled: []
07:27:02-788106 INFO     Updating Wiki
07:27:03-971790 INFO     Running extension preloading
07:27:03-971790 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
Checkpoint not found: None
Available models: D:\SD\automatic\models\Stable-diffusion 4
ControlNet v1.1.125
ControlNet v1.1.125
Loading theme: black-orange
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Loading weights: D:\SD\automatic\models\Stable-diffusion\AnythingV5_v5PrtRE.safetensors ------------ 0.0/2.1 GB -:--:--
Creating model from config: D:\SD\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying sub-quadratic cross attention optimization
Embeddings loaded:  (0)
Model loaded in 10.4s (load=0.4s create=0.4s apply=0.5s move=9.0s)
Startup time: 23.3s (torch=3.9s gradio=2.3s libraries=0.3s codeformer=0.1s scripts=3.0s ui=2.7s start=0.2s scripts
app_started_callback=0.1s checkpoint=10.7s)
API error: GET: http://127.0.0.1:7860/static/img/api-logo.svg {'error': 'HTTPException', 'detail': 'Forbidden', 'body': '', 'errors': '403'}
Initializing ----------------------------------------   0% -:--:-- 0:00:01
gradio call: NotImplementedError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\SD\automatic\modules\call_queue.py:58 in f                                                                       │
│                                                                                                                     │
│    57 │   │   │   │   pr.enable()                                                                                   │
│ >  58 │   │   │   res = list(func(*args, **kwargs))                                                                 │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                       │
│                                                                                                                     │
│ D:\SD\automatic\modules\call_queue.py:38 in f                                                                       │
│                                                                                                                     │
│    37 │   │   │   try:                                                                                              │
│ >  38 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    39 │   │   │   finally:                                                                                          │
│                                                                                                                     │
│                                              ... 39 frames hidden ...                                               │
│                                                                                                                     │
│ D:\SD\automatic\modules\dml\__init__.py:27 in memory_stats                                                          │
│                                                                                                                     │
│   26 │   │   optimizer = DirectML.get_optimizer(device)                                                             │
│ > 27 │   │   return optimizer.memory_stats(device.index)                                                            │
│   28                                                                                                                │
│                                                                                                                     │
│ D:\SD\automatic\modules\dml\optimizer\intel\__init__.py:5 in memory_stats                                           │
│                                                                                                                     │
│   4 │   def memory_stats(index):                                                                                    │
│ > 5 │   │   raise NotImplementedError()                                                                             │
│   6 │   │   # DML TODO: Implement                                                                                   │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
NotImplementedError

**Comment by lshqqytiger** [comment]
Oh, I thought I already added try-except at that part.
I'll add it.

**Comment by lshqqytiger** [comment]
We can't get vram usage of Intel GPUs except for xpu.
I'm finding a general and more better way than now (getting vram usage from GPU driver and it depends on GPU vendor).
Should be solved [9e214b3](https://github.com/vladmandic/automatic/commit/9e214b32d739a83d1c94205e0872cfadcf02d030).

**Comment by amarillonmc** [comment]
The image generation works fine now:

Steps: 15, Sampler: UniPC, CFG scale: 7, Seed: 2092517513, Size: 512x768, Model hash: 7f96a1a9ca, Model: AnythingV5_v5PrtRE, Clip skip: 1

Time taken: 10m 40.29s

The time is to be expected - just a heads up - the used GPU memory is not being released after generation, an oddity also observed on AMD Graphic cards as well and seems to be an DirectML issue?

Since the issue described has been resolved, I'll close this issue.

**Comment by vladmandic** [comment]
>  the used GPU memory is not being released after generation, an oddity also observed on AMD Graphic cards as well and seems to be an DirectML issue?

which memory? but then, there is no detailed memory monitoring on directml.
torch used to work the way it pre-allocated as much as it could and then it would internally shuffle it.
and directml is based on older torch, so it wouldn't surprised me if it did exactly that.
ideally you'd see allocated vs active vs reserved vs inactive. but with directml, its difficult to track it granularly.

**Comment by amarillonmc** [comment]
![`G9XLV}LY%D`IF U66DD2$9](https://user-images.githubusercontent.com/7876442/235555416-8f1ce622-2ee8-47d6-a385-26c41b367c91.png)
Shared GPU memory is not being released after the image is generated..

**Comment by vladmandic** [comment]
thats what i've meant - there is no granular way of checking what is that with directml.
perhaps its just torch pre-allocated and it does that based on thresholds (75% of total memory) and not active at all.
for example, if you had 16gb, it might pre-allocate 12gb and still run just fine.

**Comment by lshqqytiger** [comment]
DirectML does not access its memory due to technical problems. https://github.com/microsoft/DirectML/issues/425
I'm not sure DirectML team can solve this problem. But they are working for memory optimization.
