### ISSUE TITLE
[Issue]:  Install fails ubuntu 22.10 AMD GPU

### ISSUE THREAD

**Issue by thePlott** [vladmandic/automatic#684]
### Issue Description

Run webui.sh
(if you require more info please ask)

using: torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.4.2, fails almost completely at the start.

using: torch==1.13.1+rocm5.2 torchvision==0.14.1+rocm5.2 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/rocm5.2, gives the error from the below terminal output.

<pre><font color="#26A269"><b>aone@a1-pc</b></font>:<font color="#12488B"><b>/mnt/xxx/automatic</b></font>$ ./webui.sh
Create and activate python venv
Launching launch.py...
<font color="#1C6B77">22:42:05-881283 </font><font color="#12488B">INFO    </font> Python <font color="#2AA1B3"><b>3.10</b></font>.<font color="#2AA1B3"><b>7</b></font> on Linux                                 
<font color="#1C6B77">22:42:05-910912 </font><font color="#12488B">INFO    </font> Version: d4a748d7 Mon May <font color="#2AA1B3"><b>1</b></font> <font color="#33DA7A"><b>12:25:35</b></font> <font color="#2AA1B3"><b>2023</b></font> <font color="#2AA1B3"><b>-0400</b></font>        
<font color="#1C6B77">22:42:05-914319 </font><font color="#12488B">INFO    </font> Setting environment tuning                             
<font color="#1C6B77">22:42:05-915041 </font><font color="#12488B">INFO    </font> AMD ROCm toolkit detected                              
<font color="#1C6B77">22:42:05-915660 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">torch</font>==<font color="#2AA1B3"><b>1.13</b></font>.<font color="#2AA1B3"><b>1</b></font>+rocm5.<font color="#2AA1B3"><b>2</b></font>              
<font color="#1C6B77">                </font>         <font color="#A2734C">torchvision</font>==<font color="#2AA1B3"><b>0.14</b></font>.<font color="#2AA1B3"><b>1</b></font>+rocm5.<font color="#2AA1B3"><b>2</b></font> <font color="#A2734C">torchaudio</font>==<font color="#2AA1B3"><b>0.13</b></font>.<font color="#2AA1B3"><b>1</b></font>         
<font color="#1C6B77">                </font>         --extra-index-url                                      
<font color="#1C6B77">                </font>         <font color="#2A7BDE"><u style="text-decoration-style:single">https://download.pytorch.org/whl/rocm5.2</u></font>               
<font color="#1C6B77">22:42:52-259769 </font><font color="#12488B">INFO    </font> Torch <font color="#2AA1B3"><b>1.13</b></font>.<font color="#2AA1B3"><b>1</b></font>+rocm5.<font color="#2AA1B3"><b>2</b></font>                                                                                                                                 
<font color="#1C6B77">22:42:53-026970 </font><font color="#12488B">INFO    </font> Torch backend: AMD ROCm HIP <font color="#2AA1B3"><b>5.2</b></font>.<font color="#2AA1B3"><b>21151</b></font>-afdc89f8                                                                                                       
<font color="#1C6B77">22:42:53-028318 </font><font color="#12488B">INFO    </font> Torch detected GPU: AMD Radeon RX <font color="#2AA1B3"><b>570</b></font> Series VRAM <font color="#2AA1B3"><b>4096</b></font> Arch <b>(</b><font color="#2AA1B3"><b>10</b></font>, <font color="#2AA1B3"><b>3</b></font><b>)</b> Cores <font color="#2AA1B3"><b>16</b></font>                                                                         
<font color="#1C6B77">22:42:53-029093 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">tensorflow</font>==<font color="#2AA1B3"><b>2.12</b></font>.<font color="#2AA1B3"><b>0</b></font>                                                                                                               
<font color="#1C6B77">22:43:14-277397 </font><font color="#12488B">INFO    </font> Verifying requirements                                                                                                                               
<font color="#1C6B77">22:43:14-278947 </font><font color="#12488B">INFO    </font> Installing package: addict                                                                                                                           
<font color="#1C6B77">22:43:14-776191 </font><font color="#12488B">INFO    </font> Installing package: aenum                                                                                                                            
<font color="#1C6B77">22:43:15-359223 </font><font color="#12488B">INFO    </font> Installing package: aiohttp                                                                                                                          
<font color="#1C6B77">22:43:18-302097 </font><font color="#12488B">INFO    </font> Installing package: anyio                                                                                                                            
<font color="#1C6B77">22:43:18-965724 </font><font color="#12488B">INFO    </font> Installing package: appdirs                                                                                                                          
<font color="#1C6B77">22:43:19-535167 </font><font color="#12488B">INFO    </font> Installing package: astunparse                                                                                                                       
<font color="#1C6B77">22:43:20-044131 </font><font color="#12488B">INFO    </font> Installing package: basicsr                                                                                                                          
<font color="#1C6B77">22:43:25-310169 </font><font color="#12488B">INFO    </font> Installing package: bitsandbytes                                                                                                                     
<font color="#1C6B77">22:43:27-542983 </font><font color="#12488B">INFO    </font> Installing package: blendmodes                                                                                                                       
<font color="#1C6B77">22:43:28-252571 </font><font color="#12488B">INFO    </font> Installing package: clean-fid                                                                                                                        
<font color="#1C6B77">22:43:28-937573 </font><font color="#12488B">INFO    </font> Installing package: easydev                                                                                                                          
<font color="#1C6B77">22:43:29-913673 </font><font color="#12488B">INFO    </font> Installing package: extcolors                                                                                                                        
<font color="#1C6B77">22:43:30-795430 </font><font color="#12488B">INFO    </font> Installing package: facexlib                                                                                                                         
<font color="#1C6B77">22:43:35-590663 </font><font color="#12488B">INFO    </font> Installing package: filetype                                                                                                                         
<font color="#1C6B77">22:43:36-318170 </font><font color="#12488B">INFO    </font> Installing package: font-roboto                                                                                                                      
<font color="#1C6B77">22:43:37-055234 </font><font color="#12488B">INFO    </font> Installing package: fonts                                                                                                                            
<font color="#1C6B77">22:43:37-769047 </font><font color="#12488B">INFO    </font> Installing package: future                                                                                                                           
<font color="#1C6B77">22:43:38-460608 </font><font color="#12488B">INFO    </font> Installing package: gdown                                                                                                                            
<font color="#1C6B77">22:43:39-437293 </font><font color="#12488B">INFO    </font> Installing package: gfpgan                                                                                                                           
<font color="#1C6B77">22:43:40-292466 </font><font color="#12488B">INFO    </font> Installing package: GitPython                                                                                                                        
<font color="#1C6B77">22:43:41-243855 </font><font color="#12488B">INFO    </font> Installing package: httpcore                                                                                                                         
<font color="#1C6B77">22:43:42-087191 </font><font color="#12488B">INFO    </font> Installing package: inflection                                                                                                                       
<font color="#1C6B77">22:43:42-818476 </font><font color="#12488B">INFO    </font> Installing package: jsonmerge                                                                                                                        
<font color="#1C6B77">22:43:43-758462 </font><font color="#12488B">INFO    </font> Installing package: kornia                                                                                                                           
<font color="#1C6B77">22:43:44-814768 </font><font color="#12488B">INFO    </font> Installing package: lark                                                                                                                             
<font color="#1C6B77">22:43:45-613082 </font><font color="#12488B">INFO    </font> Installing package: lmdb                                                                                                                             
<font color="#1C6B77">22:43:46-374213 </font><font color="#12488B">INFO    </font> Installing package: lpips                                                                                                                            
<font color="#1C6B77">22:43:47-156774 </font><font color="#12488B">INFO    </font> Installing package: numpy                                                                                                                            
<font color="#1C6B77">22:43:49-578056 </font><font color="#12488B">INFO    </font> Installing package: omegaconf                                                                                                                        
<font color="#1C6B77">22:43:50-490607 </font><font color="#12488B">INFO    </font> Installing package: open-clip-torch                                                                                                                  
<font color="#1C6B77">22:43:53-119468 </font><font color="#12488B">INFO    </font> Installing package: opencv-contrib-python                                                                                                            
<font color="#1C6B77">22:43:55-148902 </font><font color="#12488B">INFO    </font> Installing package: piexif                                                                                                                           
<font color="#1C6B77">22:43:55-995516 </font><font color="#12488B">INFO    </font> Installing package: Pillow                                                                                                                           
<font color="#1C6B77">22:43:56-998977 </font><font color="#12488B">INFO    </font> Installing package: psutil                                                                                                                           
<font color="#1C6B77">22:43:58-024285 </font><font color="#12488B">INFO    </font> Installing package: pyyaml                                                                                                                           
<font color="#1C6B77">22:43:58-864044 </font><font color="#12488B">INFO    </font> Installing package: realesrgan                                                                                                                       
<font color="#1C6B77">22:44:01-628576 </font><font color="#12488B">INFO    </font> Installing package: requests                                                                                                                         
<font color="#1C6B77">22:44:02-557495 </font><font color="#12488B">INFO    </font> Installing package: resize-right                                                                                                                     
<font color="#1C6B77">22:44:03-420320 </font><font color="#12488B">INFO    </font> Installing package: rich                                                                                                                             
<font color="#1C6B77">22:44:04-295344 </font><font color="#12488B">INFO    </font> Installing package: safetensors                                                                                                                      
<font color="#1C6B77">22:44:05-290810 </font><font color="#12488B">INFO    </font> Installing package: scipy                                                                                                                            
<font color="#1C6B77">22:44:06-260375 </font><font color="#12488B">INFO    </font> Installing package: tb_nightly                                                                                                                       
<font color="#1C6B77">22:44:07-544197 </font><font color="#12488B">INFO    </font> Installing package: toml                                                                                                                             
<font color="#1C6B77">22:44:08-458791 </font><font color="#12488B">INFO    </font> Installing package: torch                                                                                                                            
<font color="#1C6B77">22:44:49-327214 </font><font color="#12488B">INFO    </font> Installing package: torchdiffeq                                                                                                                                                     
<font color="#1C6B77">22:44:50-284595 </font><font color="#12488B">INFO    </font> Installing package: torchsde                                                                                                                                                        
<font color="#1C6B77">22:44:51-391043 </font><font color="#12488B">INFO    </font> Installing package: torchvision                                                                                                                                                     
<font color="#1C6B77">22:44:52-993212 </font><font color="#12488B">INFO    </font> Installing package: tqdm                                                                                                                                                            
<font color="#1C6B77">22:44:53-916971 </font><font color="#12488B">INFO    </font> Installing package: voluptuous                                                                                                                                                      
<font color="#1C6B77">22:44:54-849321 </font><font color="#12488B">INFO    </font> Installing package: yapf                                                                                                                                                            
<font color="#1C6B77">22:44:55-738827 </font><font color="#12488B">INFO    </font> Installing package: scikit-image                                                                                                                                                    
<font color="#1C6B77">22:44:56-691440 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">accelerate</font>==<font color="#2AA1B3"><b>0.18</b></font>.<font color="#2AA1B3"><b>0</b></font>                                                                                                                                              
<font color="#1C6B77">22:44:57-779530 </font><font color="#12488B">INFO    </font> Installing package: opencv-<font color="#A2734C">python</font>==<font color="#33DA7A"><b>4.7.0.72</b></font>                                                                                                                                         
<font color="#1C6B77">22:44:58-814885 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">diffusers</font>==<font color="#2AA1B3"><b>0.16</b></font>.<font color="#2AA1B3"><b>1</b></font>                                                                                                                                               
<font color="#1C6B77">22:45:00-294357 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">einops</font>==<font color="#2AA1B3"><b>0.4</b></font>.<font color="#2AA1B3"><b>1</b></font>                                                                                                                                                   
<font color="#1C6B77">22:45:01-306986 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">gradio</font>==<font color="#2AA1B3"><b>3.28</b></font>.<font color="#2AA1B3"><b>1</b></font>                                                                                                                                                  
<font color="#1C6B77">22:45:08-001585 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">numexpr</font>==<font color="#2AA1B3"><b>2.8</b></font>.<font color="#2AA1B3"><b>4</b></font>                                                                                                                                                  
<font color="#1C6B77">22:45:09-233794 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">pandas</font>==<font color="#2AA1B3"><b>1.5</b></font>.<font color="#2AA1B3"><b>3</b></font>                                                                                                                                                   
<font color="#1C6B77">22:45:13-304832 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">protobuf</font>==<font color="#2AA1B3"><b>3.20</b></font>.<font color="#2AA1B3"><b>3</b></font>                                                                                                                                                
<font color="#1C6B77">22:45:14-548888 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">pytorch_lightning</font>==<font color="#2AA1B3"><b>1.9</b></font>.<font color="#2AA1B3"><b>4</b></font>                                                                                                                                        
<font color="#1C6B77">22:45:16-420809 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">transformers</font>==<font color="#2AA1B3"><b>4.28</b></font>.<font color="#2AA1B3"><b>1</b></font>                                                                                                                                            
<font color="#1C6B77">22:45:20-770477 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">timm</font>==<font color="#2AA1B3"><b>0.6</b></font>.<font color="#2AA1B3"><b>13</b></font>                                                                                                                                                    
<font color="#1C6B77">22:45:22-243935 </font><font color="#12488B">INFO    </font> Installing package: <font color="#A2734C">tomesd</font>==<font color="#2AA1B3"><b>0.1</b></font>.<font color="#2AA1B3"><b>2</b></font>                                                                                                                                                   
<font color="#1C6B77">22:45:23-823433 </font><font color="#12488B">INFO    </font> No changes detected: Quick launch active                                                                                                                                            
<font color="#1C6B77">22:45:23-824350 </font><font color="#12488B">INFO    </font> Running extension preloading                                                                                                                                                        
<font color="#1C6B77">22:45:23-824928 </font><font color="#12488B">INFO    </font> Server arguments: <b>[]</b>                                                                                                                                                                
/mnt/xxx/automatic/venv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: &apos;libc10_cuda.so: cannot open shared object file: No such file or directory&apos;If you don&apos;t plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Segmentation fault (core dumped)
<font color="#26A269"><b>aone@a1-pc</b></font>:<font color="#12488B"><b>/mnt/xxx/automatic</b></font>$ 

</pre>

### Version Platform Description

ubuntu 22.10
python 3.10.7
amd drivers for 22.04 (none available for 22.10)

<pre><font color="#26A269"><b>aone@a1-pc</b></font>:<font color="#12488B"><b>~</b></font>$ rocm-smi

======================= ROCm System Management Interface =======================
================================= Concise Info =================================
GPU  Temp (DieEdge)  AvgPwr   SCLK    MCLK    Fan  Perf  PwrCap  VRAM%  GPU%  
0    41.0c           32.172W  300Mhz  300Mhz  0%   auto  135.0W   22%   0%    
================================================================================
============================= End of ROCm SMI Log ==============================
 </pre>

<pre><font color="#26A269"><b>aone@a1-pc</b></font>:<font color="#12488B"><b>~</b></font>$ rocminfo
<font color="#D0CFCC">ROCk module is loaded</font>
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 5 3600 6-Core Processor  
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD Ryzen 5 3600 6-Core Processor  
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   3600                               
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            12                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    65773700(0x3eba084) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    65773700(0x3eba084) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    65773700(0x3eba084) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    gfx1030                            
  Uuid:                    GPU-XX                             
  Marketing Name:          Radeon RX 570 Series               
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
  Chip ID:                 26591(0x67df)                      
  ASIC Revision:           1(0x1)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1244                               
  BDFID:                   9728                               
  Internal Node ID:        1                                  
  Compute Unit:            32                                 
  SIMDs per CU:            4                                  
  Shader Engines:          4                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        40(0x28)                           
  Max Work-item Per CU:    2560(0xa00)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    4194304(0x400000) KB               
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx1030         
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done *** </pre>
issue is repeatable

**Comment by vladmandic** [comment]
looping in @lshqqytiger as author of torchml support, hope he can help?

**Comment by vladmandic** [comment]
> Segmentation fault (core dumped)

this is happening on a much lower level than app, can you check linux system logs about segfault itself?

**Comment by Soulreaver90** [comment]
The RX 570 is an old card. I am too lazy to pull mine out to test, but googling shows that the following arg might be needed or Polaris cards.
`Export ROC_ENABLE_PRE_VEGA=1`

**Comment by thePlott** [comment]
> The RX 570 is an older card. I am too lazy to pull mine out to test, but googling shows that the following arg might be needed for Polaris cards. They seem to work mostly with the 8gb variant, not sure how the 4gb will fair, if at all. `Export ROC_ENABLE_PRE_VEGA=1`

I have tried this with both a 4gb 570 & 8gb 580, i get the same result using either card.

**Comment by thePlott** [comment]
> > Segmentation fault (core dumped)
> 
> this is happening on a much lower level than app, can you check linux system logs about segfault itself?

should have mentioned in my OP, not new to linux but by no means an expert, where do i find said system logs?

**Comment by vladmandic** [comment]
typically in `/var/logs`, actual names differ from distro to distro, typically look at something like `syslog`
also check output of command `dmesg -kuT` which is the kernel ring buffer (best to do that soon after error occurs)

**Comment by thePlott** [comment]
> dmesg -kuT

from kern.log

May  1 21:55:17 a1-pc kernel: [11447.935832] python3[13354]: segfault at 10 ip 00007f765d4cb4d8 sp 00007ffdc776e4b0 error 4 in libhsa-runtime64.so[7f765d400000+153000]
May  1 21:55:17 a1-pc kernel: [11447.935842] Code: 45 31 e4 e9 ca fe ff ff 66 2e 0f 1f 84 00 00 00 00 00 c7 44 24 0c 04 00 00 00 45 31 ff 45 31 f6 e9 ad fe ff ff 0f 1f 44 00 00 <49> 8b 45 10 49 8d 4d 08 48 85 c0 0f 84 87 00 00 00 48 89 ca eb 0e
May  1 22:00:39 a1-pc kernel: [11770.119601] python3[13688]: segfault at 10 ip 00007f6873ccb4d8 sp 00007ffd4ed85f60 error 4 in libhsa-runtime64.so[7f6873c00000+153000]
May  1 22:00:39 a1-pc kernel: [11770.119613] Code: 45 31 e4 e9 ca fe ff ff 66 2e 0f 1f 84 00 00 00 00 00 c7 44 24 0c 04 00 00 00 45 31 ff 45 31 f6 e9 ad fe ff ff 0f 1f 44 00 00 <49> 8b 45 10 49 8d 4d 08 48 85 c0 0f 84 87 00 00 00 48 89 ca eb 0e

**Comment by vladmandic** [comment]
that's deeeep inside ROCm, specifically inside HSA module used by ROCm - and that module has not been updated in YEARS - last commit was 2017?! <https://github.com/HSAFoundation/HSA-Runtime-AMD>

this is way beyond me, but it feels like current ROCm is just not compatible with your GPU.

**Comment by thePlott** [comment]
> that's deeeep inside ROCm, specifically inside HSA module used by ROCm - and that module has not been updated in YEARS - last commit was 2017?! https://github.com/HSAFoundation/HSA-Runtime-AMD
> 
> this is way beyond me, but it feels like current ROCm is just not compatible with your GPU.

OK, not a problem. i am going to try on another box with a fresh install of 22.04 & rx580. will see how that goes and let you know. thank you for the input.

**Comment by vladmandic** [comment]
sorry to be closing this without resolution, but this is beyond me. if you have any issues with new install, can you create a new issue? or if its exactly the same, you can update here.

**Comment by thePlott** [comment]
> sorry to be closing this without resolution, but this is beyond me. if you have any issues with new install, can you create a new issue? or if its exactly the same, you can update here.

no problem, and again thank you.
