### ISSUE TITLE
Intel Arc bad speed[Issue]: 

### ISSUE THREAD

**Issue by TotalDay** [vladmandic/automatic#688]
### Issue Description

speed 4.6 it/sec
but with old WebUI and libs - 7.2 it/sec
https://www.reddit.com/r/StableDiffusion/comments/12ufe4u/intel_arc_gpu_stable_diffusion_webui_720_itsec/

Thanks for Intel Arc support, but 4.6 vs 7.2 is too bad

**Comment by TotalDay** [comment]
i try new and old version of torch and intel extension at your WebUi - and 4.6 Max
I think the problem is in the libs, i`m using old libs from February 2023

**Comment by vladmandic** [comment]
See pinned issue regarding current general performance problems. I don't think this is Arc specific.

**Comment by thygate** [comment]
much slower for me after updating today (3 sec before to 11 sec now for same params), rtx3070 .. It seems to stall every other sample when i look at the console progress bar when generating ..

**Comment by vladmandic** [comment]
See #675
