### ISSUE TITLE
[Feature]: No longer limit the version of xforms，

### ISSUE THREAD

**Issue by wzgrx** [vladmandic/automatic#690]
### Feature description

When starting, the default check must be to install xformers0.017 version
Other versions installed by oneself will be automatically uninstalled

### Version Platform Description

Python 3.10.10 on Windows
11:07:15-807092 INFO     Version: eaea88a4 Mon May 1 21:03:08 2023 -0400
11:07:17-392662 INFO     Setting environment tuning
11:07:17-399512 INFO     nVidia CUDA toolkit detected
11:07:21-219161 INFO     Torch 2.1.0.dev20230421+cu118
11:07:21-238560 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700

**Comment by Panchvzluck** [comment]
I agree with this, when I build my own xformers, I have to change the line on installer.py every time there's an update.

**Comment by vladmandic** [comment]
why change installer - if you're already changing it, you can see it reads from env variable?
just set env variable `XFORMERS_PACKAGE`, default is `xformers==0.0.17`, you can set it to anything you want. if you set it to `none` (or anything that doesn't have `xformers` in the string itself), installer will skip it completely and whatever is installed will be used.
