### ISSUE TITLE
[Issue]: Extras (post-processing) Upscaling overwriting metadata

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#692]
### Issue Description

When sending a generated image to the Extras tab for upscaling, the embedded metadata is being overwritten with; 
```
postprocessing: Postprocess upscale by: 3, Postprocess upscaler: 4x_foolhardy_Remacri
extras: Postprocess upscale by: 3, Postprocess upscaler: 4x_foolhardy_Remacri
```

Upscaled info should probably be _added_ to the metadata, rather than overwriting it.

### Version Platform Description

Version: 917ecad4 Sun Apr 30 09:31:38 2023 -0400
Ubuntu 22, Chrome, AMD RX 6600 XT 8Gb, ROCm.

**Comment by brknsoul** [comment]
This doesn't seem to be fixed on Version: 22090d7b Thu May 4 06:53:01 2023 -0400

Before
![image](https://user-images.githubusercontent.com/1969381/236315501-5acb2821-f54a-4e10-888b-4b79774c2bf3.png)

After
![image](https://user-images.githubusercontent.com/1969381/236315385-46727920-a134-4a72-b543-4eb2a7e0ebda.png)

**Comment by vladmandic** [comment]
i cannot reproduce this, i've tried with jpg, webp and png and postprocessing data is correctly appended.
after you run processing and new image is created, did you load new image so metadata can be re-processed? metadata is not updated on run, its updated on load.

**Comment by brknsoul** [comment]
Ok, i'll upload the images themselves;
(ran on  Version: c470f399 Thu May 4 16:55:41 2023 -0400)

Generated image;
![00003-20230507012654-2259414791](https://user-images.githubusercontent.com/1969381/236634488-6a13f739-b25d-4ca8-9960-5546ab484bc7.png)

Upscaled image;
![00043](https://user-images.githubusercontent.com/1969381/236634509-112cb338-cfbc-4809-989d-6463c33158fb.png)

**Comment by vladmandic** [comment]
reproduced and fixed, its a specific combo of file formats that was causing original data not to be loaded.
but i'll upload the fix on monday, i have too much pending code to risk updating repo right now.

> This seems counter-intuitive. 

yes, it is counter-intuitive. there's a LOT of legacy code there and i'm fixing it bit by bit. this is how A1111 worked from long time ago.

**Comment by vladmandic** [comment]
fixed.

**Comment by brknsoul** [comment]
The "UserComment" should probably be renamed to "parameters"

The first is from a semi-random request from Unstable bot on Unstable Diffusion discord, the second is my uploaded image.
![image](https://user-images.githubusercontent.com/1969381/236908947-b6c21956-5519-40c8-91b5-b09ae408c13b.png)

**Comment by vladmandic** [comment]
top text-box is what was actually parsed.

bottom text-box is full metadata. if you edit image in photoshop, it will add metadata. if you open an image taken with phone, it will have metadata. just so happens that everything *we* write, we write in metadata section called "UserComment" and that's where parsed data will come from.
