### ISSUE TITLE
[Issue]:Updating submodules------how do you disable update on startup?

### ISSUE THREAD

**Issue by bryanray** [vladmandic/automatic#698]
### Issue Description

i am using proxy on internet, cannot use "git submodule" properly....
it will always output this error:
"Failed to connect to github.com port 443 after 21042 ms: Couldn't connect to server"

**Comment by acorderob** [comment]
Use the --noupdate flag, or configure git to use your proxy.

**Comment by bryanray** [comment]
> 

--noupdate 
where to put it? the new install of vlad's versionn is so different than og a1111.

configure git to use your proxy
I had search for the answer, not quite there yet.
I am using using clash for windows, there are no username and password i dont know how to set it via git.

**Comment by vladmandic** [comment]
just add command line parameter to `webui.bat` when starting the server:

`webui --help`

```log
...
Setup options:
  --reset                                              Reset main repository to latest version, default: False
  --upgrade                                            Upgrade main repository to latest version, default: False
  --skip-update                                        Skip update of extensions and submodules, default: False
  --skip-requirements                                  Skips checking and installing requirements, default: False
  --skip-extensions                                    Skips running individual extension installers, default: False
  --skip-git                                           Skips running all GIT operations, default: False
...
```

btw, this is better asked as question in discussion, not create an issue since there is no issue with the app.

**Comment by bryanray** [comment]
> --skip-update

how do you add to webui.bat

please be more detailed

**Comment by vladmandic** [comment]
asked and answered in discussions many times, please search.

you can create shortcut to file and add in properties of a shortcut
or you can create your own .bat file (for example `webui-user.bat`) with a single line
`@webui --skip-git`

**Comment by bryanray** [comment]
create your own .bat file (for example webui-user.bat) with a single line
@webui --skip-git

doesnt work, 

webui-user.bat
@webui --skip-git

**Comment by vladmandic** [comment]
"doesn't work" meaning what??? you created that file and with the line written as above and when you run it, what happens?

**Comment by bryanray** [comment]
created a file name: 
webui-user.bat

content inside: 
@webui --skip-git

location root folder as webui.bat

run it -> cmd window briefly appeared and close itself without any warning

**Comment by vladmandic** [comment]
run it from command prompt so you can see what it says before window gets closed.
