### ISSUE TITLE
[Bug]: Torch not installed, aborting in WSl

### ISSUE THREAD

**Issue by LaikaSa** [vladmandic/automatic#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

On wsl Ubuntu for window, after successfully install Torch 2.0.0 compliled with cuda 11.8 and run ./automatic.sh install, I got this error:
``./automatic.sh: line 31: : command not found
Torch not installed, aborting``
Not sure what is the problem, I make sure to install cuda 11.8 and python is 3.10.6 version already

### Steps to reproduce the problem

1. open wsl2 Ubuntu on window
2. Install python and Torch as instructed 
3. run command: ./automatic.sh install

### What should have happened?

It should install all requirements and launch

### Commit where the problem happens

ee412dde58fa4e1fd27aeeab07c78987aecd7ba6

### What platforms do you use to access the UI ?

Windows, Linux

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
./automatic.sh: line 31: : command not found
Torch not installed, aborting
```

**Comment by vladmandic** [comment]
can you run `which python && python -m pip show torch`?

**Comment by LaikaSa** [comment]
Nothing happened when I run the command:
![image](https://user-images.githubusercontent.com/112873279/229331633-c7b90b66-21f4-4366-998b-e31d4c239bca.png)

**Comment by LaikaSa** [comment]
But when I run ``pip show torch`` individually this appear:
``Name: torch
Version: 2.0.0+cu118
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /home/bright/.local/lib/python3.10/site-packages
Requires: filelock, jinja2, networkx, sympy, triton, typing-extensions
Required-by: accelerate, basicsr, clean-fid, clip-interrogator, facexlib, gfpgan, invisible-watermark, kornia, open-clip-torch, pytorch-lightning, realesrgan, timm, torchaudio, torchdiffeq, torchmetrics, torchsde, torchvision, triton``

**Comment by vladmandic** [comment]
Do you have python in path? Seems like you have python without alias to python?

**Comment by LaikaSa** [comment]
Ok that is the exactly the issue, after I some google and install python-is-python3, the script run smoothly now. Thanks

**Comment by vladmandic** [comment]
Good.
I'll add additional checks to start script to cover thar in the future.
