### ISSUE TITLE
[Issue]: Script selector and script place splitted

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#701]
### Issue Description

At first I thought it was just a glitch, but even after restarting and updating, this split still exists.
The script selector is now on first position and the selected script is placed on the very bottom.

![Zwischenablagebild](https://user-images.githubusercontent.com/122026301/235717270-e931bbc4-f9d5-4d2c-ab58-3a5e20ea39c0.png)

### Version Platform Description

Win10, Firefox 106
Version: 2166b4de Tue May 2 09:56:33 2023 -0400

**Comment by vladmandic** [comment]
what is this theme/skin you're using? i cannot reproduce using default black-orange theme or gradio/default?

**Comment by Woisek** [comment]
Ah ... good keyword. This is not a theme, this is just the user.ccs with a visual adjustment and some undo of bad design decisions.
And the split was the rest of a desperate attempt to put the modules in an order. But without a unique id or class this is hopeless. An update probably changed that. Anyway, sorry for bothering. 🙄

**Comment by vladmandic** [comment]
> to put the modules in an order

care to elaborate?

**Comment by Woisek** [comment]
>care to elaborate?

Well, I don't like how the modules are listed. For instance, I need the ratio and resolution button at first , not way down there. After that, ControlNet. After that Tiled Diffusion, etc.
You have told me, that those modules are listed as they are loaded (a pretty stupid concept, but that is just Gradio apparently).

My approach now was to rearrange the components via CSS. This works perfectly, if ... yes, if you could address the individual components exactly. With an id, for example. unfortunately, Gradio assigns a component id and embeds the modules in it, which makes their own id (which would be exactly the right thing to do) pointless. That wouldn't be so bad, but the problem is, that these ids change at every restart, or at least, when a new component is added or taken away. 
So you would have to provide the component wrapper with a unique class, which is created from the contained module. maybe you could use the id as class name. Then this unique class would be addressable via CSS and you could order the entries as you want them. As a hard work maybe also somehow embedded in the settings, so you don't always have to muddle around in the CSS file.
🙂

**Comment by Woisek** [comment]
Great news!
So, in the root folder of each extension, I create a text file named .priority and inside I write a sorting number, did I get this right?

**Comment by vladmandic** [comment]
yup. eventually that file and number will go away and be replaced with ui for that and priority will be stored in config.json.

**Comment by Woisek** [comment]
OK, if no .priority file is found, it is considered as 50 ... ?
And if yes, that would mean, if a single extension has a .priority with, say, 30 in it, it would theoretically move to the top, right?

**Comment by vladmandic** [comment]
correct on both. it would move it to the top of the group (cannot change order of groups)

**Comment by Woisek** [comment]
Yeah, I got this. But the extensions in the sections what is defined as #txt2img_script_container or #img2img_script_container on the website, those are affected for sorting ... ?! Basically the section in my screen shot. 😁

**Comment by vladmandic** [comment]
each script or extension defines its ui elements which are drawn when that script/extension is loaded. some have elements in script container, some define tabs, some are silent. but changing order of loading should change order in ui as well.

**Comment by Woisek** [comment]
Hmm ... I have put a .priority with 30 into the extension of the aspect ratio/resolution preset, but it is not on top but still where it was. What do I miss here?

**Comment by vladmandic** [comment]
.priority controls order of loading of scripts, but what happens with ui is well, complicated.
anyhow, that's besides the point as i've just added ability to set order of scripts and tabs in ui settings.
