### ISSUE TITLE
[Issue]: GPU idling at 0% and Out of VRAM

### ISSUE THREAD

**Issue by Metalica** [vladmandic/automatic#704]
### Issue Description

- **Before update:** Picture was completed in 20~ seconds. **After update:** MY GPU is idling at 0% while doing task. Know the tasks take 5 min. or so to complete. 
- **After update** my gpu stops at 50% and then decides to move after 20-30 seconds.
- My system get's constantly out of memory: Cross post: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10005

### Version Platform Description

19:04:40-533925 INFO     Python 3.10.6 on Windows
19:04:40-853539 INFO     Version: eaea88a4 Mon May 1 21:03:08 2023 -0400
19:04:41-255063 INFO     Latest published version: 2166b4de06fc06dfce2afc16ede56d4dbcf4b292 2023-05-02T13:56:33Z
19:04:41-257057 INFO     Setting environment tuning
19:04:41-260049 INFO     nVidia CUDA toolkit detected
19:04:45-280524 INFO     Torch 2.0.0+cu118
19:04:45-301554 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
19:04:45-303523 INFO     Torch detected GPU: NVIDIA GeForce GTX 1070 VRAM 8192 Arch (6, 1) Cores 15
19:04:45-305517 INFO     Verifying requirements
19:04:45-369500 INFO     No changes detected: Quick launch active
19:04:45-375484 INFO     Running extension preloading
19:04:45-377452 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
Checkpoint not found: None
Available models: D:\automatic\models\Stable-diffusion 1
ControlNet v1.1.130
ControlNet v1.1.130
Loading theme: black-orange
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Initializing middleware
Loading weights: D:\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors -------------- 0.0/4.3 GB -:--:--
Creating model from config: D:\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying scaled dot product cross attention optimization
Embeddings loaded:  (0)
Model loaded in 6.8s (load=0.4s create=0.4s apply=4.4s vae=0.6s move=0.8s embeddings=0.1s)
Startup time: 29.1s (torch=8.1s gradio=2.5s libraries=5.3s codeformer=0.2s scripts=3.2s ui=2.5s start=0.2s scripts
app_started_callback=0.1s checkpoint=7.0s)

**Comment by vladmandic** [comment]
performance is very likely related to #675 which was introduced yesterday afternoon and fixed this morning, please update.
regardin OOM, it seems that hires in general is much more memory hungry when running on torch 2.0, i need to spend more time on that.

**Comment by Metalica** [comment]
![image](https://user-images.githubusercontent.com/411059/235749110-388479fa-8ac0-4a26-a6b7-3db0474be654.png)

20:05:21-698772 INFO     Python 3.10.6 on Windows
20:05:21-978501 INFO     Version: 2166b4de Tue May 2 09:56:33 2023 -0400
20:05:22-333980 INFO     Setting environment tuning
20:05:22-336940 INFO     nVidia CUDA toolkit detected
20:05:24-493456 INFO     Torch 2.0.0+cu118
20:05:24-513578 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
20:05:24-516543 INFO     Torch detected GPU: NVIDIA GeForce GTX 1070 VRAM 8192 Arch (6, 1) Cores 15
20:05:24-518538 INFO     Installing package: tensorflow==2.12.0
20:05:37-311486 INFO     Verifying requirements

- I started random picture and hit the "stop" button when gpu went to 0% idle mode. Nothing happened.
- I restarted the server and wanted to do another picture. 
- Picture above shows Vram is still being used for previous picture and is not released when i hit the stop button.

**Comment by vladmandic** [comment]
let me try to reproduce
- which command line flags are you using ?
- what are your ui settings -> cuda ?
- exact workflow - its txt2img with hires, anything specific ?

**Comment by Metalica** [comment]
![1](https://user-images.githubusercontent.com/411059/235759765-6bd79e2f-496e-4ac3-915e-bc1f374b864c.jpg)
![2](https://user-images.githubusercontent.com/411059/235759781-e97e5f21-41e0-42bf-97b1-7982ed0e6a80.jpg)

- Before update i had 0 issues. 
- I could run 12 pictures at same time - no issues for gpu.
- For the fun of it i even tested my gpu on max samples several times before the update.

**Comment by Metalica** [comment]
![1](https://user-images.githubusercontent.com/411059/235760594-bbe71636-54a0-4170-80be-ee24eed1f2cb.jpg)

![2](https://user-images.githubusercontent.com/411059/235760613-1210f6b3-1b4b-4e16-86f9-8160cb56b733.jpg)

I do not use any commands lines - clean install.
Before update could run 10 pictures at same time 0 issues.
I even tried for fun running max sampling, no issues before update.

**Comment by Metalica** [comment]
![1](https://user-images.githubusercontent.com/411059/235761115-81d8ba71-f872-419a-9158-1ccff1b1e116.jpg)

![2](https://user-images.githubusercontent.com/411059/235761125-e86e184a-86ef-4eb6-8d83-91e6d6229d1c.jpg)

I hope this helps. Before update i had no issues. Neither did my gpu idle at 0%.

**Comment by vladmandic** [comment]
yes, that answers nearly everything - are you using `lowvram` or `medvram` cmdflags (or any other flags for that matter)?

**Comment by Metalica** [comment]
Nothing of that. Clean install.

**Comment by Metalica** [comment]
![3](https://user-images.githubusercontent.com/411059/235764679-2d3e261a-b654-4bb5-acda-c0e35bd929c9.jpg)

For fun i tried to stop and start the server to see what is going on. It seems ram is deadlocked with the server.

**Comment by vladmandic** [comment]
its not deadlocked, you have no-half in cuda settings, so its normal that model loaded on server startup takes that much vram.

**Comment by vladmandic** [comment]
btw, whats the reason autocast is set to full instead of default, precision to fp32 instead of fp16 and both no-half and no-half-vae are enabled? combo of those 4 would kill performance of my system, it should only be used if there are specific compatibility problems (e.g., some gpus cannot run in fp16 at all and some models are just badly trained, so no-half/no-half-vae helps with precision, but thats pretty much due to broken old models and there are so many new ones that do better job).

**Comment by Metalica** [comment]
> btw, whats the reason autocast is set to full instead of default, precision to fp32 instead of fp16 and both no-half and no-half-vae are enabled? combo of those 4 would kill performance of my system, it should only be used if there are specific compatibility problems (e.g., some gpus cannot run in fp16 at all and some models are just badly trained, so no-half/no-half-vae helps with precision, but thats pretty much due to broken old models and there are so many new ones that do better job).

Before update it made pictures fast, that's about it.

**Comment by Metalica** [comment]
More info which is not related to the bug report:

> whats the reason autocast is set to full instead of default, precision to fp32 instead of fp16

 Picture result's in fb16 versus my settings are

**Comment by vladmandic** [comment]
i've made some updates on how fp16 vs fp32 is handled, can you check latest version and update?

**Comment by Metalica** [comment]
> OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 8.00 GiB total capacity; 7.01 GiB already allocated; 0 bytes free; 7.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
> Time taken: 38.89s | GPU active 7246 MB reserved 7504 MB | System peak 8192 MB total 8192 MB

> 16:37:19-269862 ERROR    gradio call: OutOfMemoryError
> ┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
> │ D:\automatic\modules\call_queue.py:54 in f                                                                          │
> │                                                                                                                     │
> │    53 │   │   │   │   pr.enable()                                                                                   │
> │ >  54 │   │   │   res = func(*args, **kwargs)                                                                       │
> │    55 │   │   │   if res is None:                                                                                   │
> │                                                                                                                     │
> │ D:\automatic\modules\call_queue.py:35 in f                                                                          │
> │                                                                                                                     │
> │    34 │   │   │   try:                                                                                              │
> │ >  35 │   │   │   │   res = func(*args, **kwargs)                                                                   │
> │    36 │   │   │   │   progress.record_results(id_task, res)                                                         │
> │                                                                                                                     │
> │                                              ... 17 frames hidden ...                                               │
> │                                                                                                                     │
> │ D:\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward                                         │
> │                                                                                                                     │
> │    462 │   def forward(self, input: Tensor) -> Tensor:                                                              │
> │ >  463 │   │   return self._conv_forward(input, self.weight, self.bias)                                             │
> │    464                                                                                                              │
> │                                                                                                                     │
> │ D:\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward                                   │
> │                                                                                                                     │
> │    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                                            │
> │ >  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                                    │
> │    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)
> 

16:32:12-604232 INFO     Starting SD.Next
16:32:12-613494 INFO     Python 3.10.6 on Windows
16:32:12-928288 INFO     Version: 1288aec4 Tue May 9 09:09:06 2023 -0400

**Comment by vladmandic** [comment]
what is your workflow? 8gb should be sufficient for normal ops.
can you run with `--debug` flag so it will print memory stats during each operation and we can see what's going on with memory?

**Comment by Metalica** [comment]
> what is your workflow? 8gb should be sufficient for normal ops. can you run with `--debug` flag so it will print memory stats during each operation and we can see what's going on with memory?

This is different then automatic1111. Where do i put here --debug .

**Comment by vladmandic** [comment]
just start `webui --debug` from the command prompt

**Comment by vladmandic** [comment]
> TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

this is displayed in UI, what does console log say? it should have far more information leading up to that.

**Comment by Metalica** [comment]
To create a public link, set `share=True` in `launch()`.
18:06:52-234582 INFO     Local URL: http://127.0.0.1:7860/
18:06:52-236578 INFO     API Docs: http://127.0.0.1:7860/docs
18:06:52-239570 DEBUG    Gradio registered functions: 968
18:06:52-241565 INFO     Initializing middleware
18:06:52-315367 DEBUG    Load model: info=False dict=False
18:06:52-318358 DEBUG    Model unloaded: {'ram': {'used': 0.91, 'total': 15.97}, 'gpu': {'used': 0.94, 'total': 8.0},
                         'retries': 0, 'oom': 0}
18:06:52-349277 DEBUG    Setting CUDA parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
Loading weights: D:\automatic\models\Stable-diffusion\v1-5-pruned-emaonly.safetensors -------------- 0.0/4.3 GB -:--:--
18:06:52-616561 DEBUG    Model dict loaded: {'ram': {'used': 0.93, 'total': 15.97}, 'gpu': {'used': 0.95, 'total':
                         8.0}, 'retries': 0, 'oom': 0}
18:06:52-633515 DEBUG    Model config loaded: {'ram': {'used': 0.94, 'total': 15.97}, 'gpu': {'used': 0.95, 'total':
                         8.0}, 'retries': 0, 'oom': 0}
18:06:52-641494 INFO     Creating model from config: D:\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
18:06:54-053718 DEBUG    Model weights loaded: {'ram': {'used': 8.9, 'total': 15.97}, 'gpu': {'used': 0.95, 'total':
                         8.0}, 'retries': 0, 'oom': 0}
18:06:55-615542 DEBUG    Model weights moved: {'ram': {'used': 4.93, 'total': 15.97}, 'gpu': {'used': 5.04, 'total':
                         8.0}, 'retries': 0, 'oom': 0}
18:06:55-629532 INFO     Applying scaled dot product cross attention optimization
18:06:55-663414 INFO     Embeddings loaded: 0 []
18:06:55-671394 INFO     Model loaded in 3.4s (load=0.3s create=0.5s apply=0.9s move=1.6s)
18:06:55-902775 DEBUG    Model load finished: {'ram': {'used': 4.96, 'total': 15.97}, 'gpu': {'used': 5.04, 'total':
                         8.0}, 'retries': 0, 'oom': 0}
18:06:56-110250 DEBUG    Reload model weights skip
18:06:56-112213 INFO     Startup time: 14.1s (torch=3.4s gradio=1.4s libraries=0.7s codeformer=0.1s scripts=3.0s opts
                         onchange=0.1s ui=1.0s start=0.4s scripts app_started_callback=0.1s checkpoint=3.8s)
18:06:56-117896 INFO     Memory used: 0.99 total: 15.97
18:07:00-136774 DEBUG    Server alive: True Memory used: 0.99 total: 15.97
18:07:08-475998 DEBUG    txt2img: task(38xtqq5xp20v900)|orc
                         warrior||[]|31|3|True|False|1|1|6|-1.0|-1.0|0|0|0|False|512|512|True|0.7|2|R-ESRGAN 4x+
                         Anime6B|0|0|0|[]
 48%|███████████████████████████████████████▋                                          | 15/31 [00:20<00:20,  1.30s/it]18:07:30-401457 DEBUG    Server alive: True Memory used: 4.75 total: 15.97
100%|██████████████████████████████████████████████████████████████████████████████████| 31/31 [00:40<00:00,  1.31s/it]
18:07:50-815865 DEBUG    Saving image: JPEG outputs/text\00206-2016004476-orc warrior-before-highres-fix.jpg
18:07:50-819731 DEBUG    upscale: <PIL.Image.Image image mode=RGB size=512x512 at
                         0x192D110FB80>|2.0|https://github.com/xinntao/Real-ESRGAN/releases/download/v0.2.2.4/RealESRGA
                         N_x4plus_anime_6B.pth
        Tile 1/9
        Tile 2/9
        Tile 3/9
        Tile 4/9
        Tile 5/9
        Tile 6/9
        Tile 7/9
        Tile 8/9
        Tile 9/9
18:07:57-329185 ERROR    gradio call: OutOfMemoryError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\call_queue.py:54 in f                                                                          │
│                                                                                                                     │
│    53 │   │   │   │   pr.enable()                                                                                   │
│ >  54 │   │   │   res = func(*args, **kwargs)                                                                       │
│    55 │   │   │   if res is None:                                                                                   │
│                                                                                                                     │
│ D:\automatic\modules\call_queue.py:35 in f                                                                          │
│                                                                                                                     │
│    34 │   │   │   try:                                                                                              │
│ >  35 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    36 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│                                              ... 12 frames hidden ...                                               │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\torch\nn\modules\module.py:1501 in _call_impl                                   │
│                                                                                                                     │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                      │
│ > 1501 │   │   │   return forward_call(*args, **kwargs)                                                             │
│   1502 │   │   # Do not call functions when jit is used                                                             │
│                                                                                                                     │
│ D:\automatic\modules\sd_hijack_optimizations.py:511 in sdp_attnblock_forward                                        │
│                                                                                                                     │
│   510 │   v = v.contiguous()                                                                                        │
│ > 511 │   out = torch.nn.functional.scaled_dot_product_attention(q, k, v, dropout_p=0.0, is_ca                      │
│   512 │   out = out.to(dtype)                                                                                       │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
OutOfMemoryError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 8.00 GiB total capacity; 6.76 GiB already
allocated; 0 bytes free; 7.04 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting
max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
18:07:59-671335 DEBUG    Server alive: True Memory used: 4.81 total: 15.97

Version: a9139294 Tue May 9 11:25:43 2023 -0400

I'ts using my ram instead of vram ?

**Comment by Metalica** [comment]
> > I'ts using my ram instead of vram?
> 
> models are always loaded to ram first and then depending on settings, either moved to vram completely (default) or partially (with medvram setting) or swapped in-and-out (with lowvram setting).
> 
> in your case, generate works fine, but you're running out of vram when running upscaling using real-esrgan in postprocessing.
> 
> do you have issues without real-esrgan upscaling in postprocessing? original issue was "gpu idling" and there was no mention of upscaling at all. what are your upscaling settings? its quite likely that nothing is wrong, just your upscaling settings are pushing it above the limit.

You got picture above it, since nothing is changed for your reference.

**Comment by vladmandic** [comment]
> Edit: upscaling has never been touched by me. It is default settings.

well, something changed it.
i suggest to delete `ui-config.json` and `config.json` so settings are return to their default values.
you have hires fix enabled and settings are configured to use real-esrgan as upscaler.

and this perfectly matches your original description - image DOES complete, then there is a PAUSE (idle at 0%)_until upscaling model is loaded and then it starts upscaling, but runs out of memory.

you can see that image is actually generated and saved:
> 18:07:50-815865 DEBUG Saving image: JPEG outputs/text\00206-2016004476-orc warrior-before-highres-fix.jpg

then it starts second pass with hires fix and upscaling and it cannot do that.

as it is, this does not look like an issue in the app, just hires fix and upscaling are set overly high and your GPU cannot handle that.

**Comment by vladmandic** [comment]
run with `--debug` and post first 10 lines of the log and last 10 lines 2min after you pressed generate.

**Comment by Metalica** [comment]
Update: Version: 4ba9f0c8 Tue May 9 12:22:52 2023 -0400

Gpu is no more idling at 0% i would that is a fix =)
