### ISSUE TITLE
[Issue]: error starting webui ( Logger._log() got an unexpected keyword argument 'file')

### ISSUE THREAD

**Issue by cjps-br** [vladmandic/automatic#709]
### Issue Description

I updated automatic to the last commit (568e7009) and the following error message started to appear when starting: 
![Captura de tela 2023-05-02 163727](https://user-images.githubusercontent.com/75840971/235768894-7c696f5a-41ab-42aa-b151-c77b94b19910.jpg)

### Version Platform Description

commit Version: 568e7009 Tue May 2 15:12:13 2023 -0400
OS: windows
Browser: Brave

**Comment by cjps-br** [comment]
I returned to commit eaea88a and everything started normally.

**Comment by TKS4** [comment]
Same, can't make sense of it, seems like it's looking for a model it can't find or something?

**Comment by MrLawbreaker** [comment]
2166b4de06fc06dfce2afc16ede56d4dbcf4b292 is the last one working for me

**Comment by utak3r** [comment]
> 

Yup, the next commit about logging is broken.

**Comment by TPPy** [comment]
Same here,  it doesnt like the 'file' keyword in "modules\sd_models.py" line 113. 
I removed it and kept only the first part; shared.log.warning(f"Checkpoint not found: {shared.cmd_opts.ckpt}")
Seems to work

**Comment by vladmandic** [comment]
yes, fixed, sorry.
amazing that i have 4 different issue for this in matter of minutes - thats active community.

**Comment by utak3r** [comment]
Confirmed working, thanks.
