### ISSUE TITLE
[Feature]: prompt to install a default VAE

### ISSUE THREAD

**Issue by DirtyHamster** [vladmandic/automatic#714]
### Feature description

On install it asks if you want to download the default model checkpoint. Just after that. Prompt to install the latest SD VAE as well.
https://huggingface.co/stabilityai/sd-vae-ft-mse-original/tree/main

Add SD_VAE to Quicksettings list of user interface. 

The baked in VAE has a habit of leaving purple artifacts in images and under saturating colors. So for first installers this would offer them a higher quality result out of the box, as well as saving them a set up step.

**Comment by vladmandic** [comment]
i understand the ask, but the only reason why default model is asked to be downloaded is because app cannot work without a single model - everything else is optional.
i agree that using vae is a good thing, but its not up to installer to provide it.
