### ISSUE TITLE
[Feature]: Add option to allow the preview images to scroll to the beginning 

### ISSUE THREAD

**Issue by Silanda** [vladmandic/automatic#720]
### Feature description

As per the discussion page: if there are more preview images than fit on the interface at once after a generation, the preview images no longer scroll to the beginning when moving through them. This is apparently new and deliberate behaviour.

Please add an option to revert the behaviour to its previous state (scrolling images to the beginning). IMO the current behaviour is counter-intuitive and hurts the usability of the scrolling previews.

**Comment by vladmandic** [comment]
new gradio changed behavior of gr.Gallery component, fallback is not really that trivial.
but i like the updated thumbnail design, so i've opted to use that as default once generation is complete.
number of columns in the grid is autodetermined based on screen width.
