### ISSUE TITLE
[Feature]:  Anyone tell me how to use "PNG Info" tab in Stable Diffusion - Automatic?

### ISSUE THREAD

**Issue by jsmile** [vladmandic/automatic#722]
### Feature description

The ability to provide png image informations provided by Automatic1111 webui's "PNG Info" tab is very useful. I would like to know how to use the function of "PNG Info" tab here as well.

**Comment by vladmandic** [comment]
this has been asked & answered a lot of times. but even if you cannot find it, that's ok, perhaps ask a question in discussions first before creating feature request?

anyhow, pnginfo functionality has been integrated into process image, no need for extra tab. just drop image there and you'll get everything that pnginfo had and a bit more.

**Comment by jsmile** [comment]
I'm sorry.
I searched with PNG Info and PNG, but I couldn't find the corresponding content, so I wrote it.

**Comment by ruSauron** [comment]
> > anyhow, pnginfo functionality has been integrated into process image, no need for extra tab. just drop image there and you'll get everything that pnginfo had and a bit more.

Vanilla automatic11 also has this integration, but the PNG info tab allows you to see information about the image without affecting the already existing prompt. That way you can manually copy part of the settings or prompt without messing up the already set parameters. So I miss it too.

**Comment by vladmandic** [comment]
if you load image into `process image`, it does not mess with prompt/params until you choose to - i'm not sure what you're referring to.

**Comment by ruSauron** [comment]
> no, a1111 **does not** have this. if you load image into `process image`, it does not mess with prompt/params until you choose to - i'm not sure what you're referring to.

Oh, yes, sorry, I was wrong. Previously, I only dragged pictures to the From text - Prompt tab. Sorry for the wasted time. The replacement for png info works as it should.
