### ISSUE TITLE
[Issue]: Startup --upgrade fails on submodules

### ISSUE THREAD

**Issue by nistvan86** [vladmandic/automatic#725]
### Issue Description

Since a couple versions the `--upgrade` switch seems to get tangled in itself on submodules.
This happened today:

    2023-05-03 09:31:15,374 | INFO | e:\aistuff\automatic\installer.py | Python 3.10.11 on Windows
    2023-05-03 09:31:15,398 | DEBUG | e:\aistuff\automatic\installer.py | Git 2.40.0.windows.1
    2023-05-03 09:31:15,552 | INFO | e:\aistuff\automatic\installer.py | Version: 2166b4de Tue May 2 09:56:33 2023 -0400
    2023-05-03 09:31:15,981 | DEBUG | e:\aistuff\automatic\installer.py | Setting branch: . / master
    2023-05-03 09:31:16,617 | ERROR | e:\aistuff\automatic\installer.py | Error running git: . / pull origin master --autostash --rebase
    2023-05-03 09:31:16,618 | ERROR | e:\aistuff\automatic\installer.py | Local changes detected: check setup.log for details
    2023-05-03 09:31:16,618 | DEBUG | e:\aistuff\automatic\installer.py | Git output: Updating 2166b4de..6f976c35
    
    From https://github.com/vladmandic/automatic
     * branch              master     -> FETCH_HEAD
    error: Your local changes to the following files would be overwritten by merge:
	    extensions-builtin/sd-webui-controlnet
    Please commit your changes or stash them before you merge.
    Aborting
    2023-05-03 09:31:16,645 | INFO | e:\aistuff\automatic\installer.py | Upgraded to version: 2166b4de Tue May 2 09:56:33 2023 -0400

Directory status

    e:\aistuff\automatic>git status
    On branch master
    Your branch is behind 'origin/master' by 12 commits, and can be fast-forwarded.
      (use "git pull" to update your local branch)
    
    Changes to be committed:
      (use "git restore --staged <file>..." to unstage)
            modified:   extensions-builtin/sd-webui-controlnet
    
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git restore <file>..." to discard changes in working directory)
      (commit or discard the untracked or modified content in submodules)
            modified:   extensions-builtin/multidiffusion-upscaler-for-automatic1111 (new commits)
            modified:   extensions-builtin/sd-webui-controlnet (new commits)
            modified:   modules/lora (new commits)
            modified:   wiki (modified content)

I have to manually do

    git restore --staged **
    git pull --all
    git submodule update --init --recursive

to make everything right then it will launch correctly, but during the next update it will very likely get in a stuck state again.

### Version Platform Description

Version: 2166b4de Tue May 2 09:56:33 2023 -0400
Python 3.10.11 on Windows
Git 2.40.0.windows.1

**Comment by vladmandic** [comment]
> error: Your local changes to the following files would be overwritten by merge: extensions-builtin/sd-webui-controlnet

i wonder what is going on there - when issue occurs can you do this before your manual cleanup?
`cd extensions-builtin/sd-webui-controlnet`
`git status`

**Comment by nistvan86** [comment]
If it happens again I'll dump here what I find.

**Comment by vladmandic** [comment]
sounds good. i'll close the issue and as soon as you report a reoccurence, update here and i'll reopen (just my typical workflow).

**Comment by nistvan86** [comment]
Happened again this morning.
Attaching [setup.log](https://github.com/vladmandic/automatic/files/11403623/setup.log).

The status of main git this time around


    e:\aistuff\automatic>git status
    On branch master
    Your branch is behind 'origin/master' by 4 commits, and can be fast-forwarded.
      (use "git pull" to update your local branch)
    
    Changes to be committed:
      (use "git restore --staged <file>..." to unstage)
            modified:   extensions-builtin/a1111-sd-webui-lycoris
            modified:   extensions-builtin/multidiffusion-upscaler-for-automatic1111
            modified:   extensions-builtin/sd-webui-controlnet
            modified:   wiki
    
    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git restore <file>..." to discard changes in working directory)
            modified:   extensions-builtin/multidiffusion-upscaler-for-automatic1111 (new commits)

Status inside any of the modified folder don't seem to show anything interesting (not repeating the output, it's the same for all of them):

    e:\aistuff\automatic\extensions-builtin\sd-webui-controlnet>git status
    On branch main
    Your branch is up to date with 'origin/main'.
    
    nothing to commit, working tree clean


git diff in the main folder tells that the multidiffusion submodule has moved to a different commit, that's the only modification. As far as I know git submodule not just tells which other git repositories are used in a project, but the commit which needs to be checked out into the working directory.
I'm just guessing but maybe because I'm constantly running `--upgrade` it updated in the previous run the multidiffusion extension independently of the main repo; this updated the git submodule entry locally. But now this conflicts with your remote update of the submodule entry in the main repo where you moved it to a different commit.

    e:\aistuff\automatic>git diff
    diff --git a/extensions-builtin/multidiffusion-upscaler-for-automatic1111 b/extensions-builtin/multidiffusion-upscaler-for-automatic1111
    index eada8e51..0f55e98e 160000
    --- a/extensions-builtin/multidiffusion-upscaler-for-automatic1111
    +++ b/extensions-builtin/multidiffusion-upscaler-for-automatic1111
    @@ -1 +1 @@
    -Subproject commit eada8e5101417f60850efa15f7454a826da6cf0d
    +Subproject commit 0f55e98e27235984a31fbd38287ba6584c4884c5

**Comment by MrLawbreaker** [comment]
I have had the same issue in the past and again today. Cleaned it up by discarding changes before remembering there was an issue here.

**Comment by vladmandic** [comment]
i've added some extra handling to upgrade procedure. if issue reoccurs, please upload the log here and i'll reopen.
