### ISSUE TITLE
[Issue]: UI selection loading does not take effect and multiple selections still do not automatically select

### ISSUE THREAD

**Issue by wzgrx** [vladmandic/automatic#729]
### Issue Description

Important bug, UI selection loading does not take effect, multiple selections still do not automatically select,All UI choices will have this issue

### Version Platform Description

Important bug, UI selection loading does not take effect, multiple selections still do not automatically select,

After clicking once, it will automatically select and then close the UI
![Snipaste_2023-05-03_20-07-30](https://user-images.githubusercontent.com/39661556/235914642-5a0b4ec0-dfec-401a-8201-43ad95fd92c8.png)

 Python 3.10.10 on Windows
20:13:59-715064 INFO     Version: 6f976c35 Tue May 2 21:30:31 2023 -0400
20:14:02-819001 INFO     Latest published version: e566fed3a15e725cc494997ece29f7b1e51ffdd2 2023-05-03T12:00:26Z
20:14:02-820575 INFO     Setting environment tuning
20:14:02-828130 INFO     nVidia CUDA toolkit detected
20:14:31-410080 INFO     Torch 2.0.0.dev20230502+cu118
20:14:31-529480 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
20:14:31-581825 INFO     Verifying requirements
20:14:31-700937 INFO     No changes detected: Quick launch active
20:14:31-702960 INFO     Running extension preloading
20:14:31-704260 INFO     Server arguments: []
20:15:46-999822 INFO     Unloading xFormers
20:15:57-000237 INFO     Libraries loaded
20:15:57-064385 INFO     Available models: E:\Soft\automatic\models\Stable-diffusion 1
ControlNet v1.1.133
ControlNet v1.1.133
20:16:22-672787 INFO     No internet access detected, using default fonts
20:16:22-673787 INFO     Loading theme: black-orange

The same problem also occurred on the original SD version

**Comment by vladmandic** [comment]
i cannot reproduce.
- added `sd_vae` to quick settings
- confirmed that vae can be changed in pull down

can you provide any more information?
also, which browser are you using?

**Comment by vladmandic** [comment]
as soon as i click on any vae, list closes and new vae is loaded.
btw, the screenshot is from a1111, not this repo, but if you say issue is the same, thats ok.
do you have any extensions or `user.css` that might modify ui behavior?

**Comment by wzgrx** [comment]
> 一旦我点击任何 VAE，列表就会关闭并加载新的 VAE。顺便说一句，屏幕截图来自 A1111，而不是这个存储库，但如果你说问题是一样的，那没关系。是否有任何扩展或可能修改 UI 行为的扩展？`user.css`

https://user-images.githubusercontent.com/39661556/235920938-6929e4d2-d526-419e-b7c9-2dbb4db90149.mp4

**Comment by wzgrx** [comment]
> 一旦我点击任何 VAE，列表就会关闭并加载新的 VAE。顺便说一句，屏幕截图来自 A1111，而不是这个存储库，但如果你说问题是一样的，那没关系。是否有任何扩展或可能修改 UI 行为的扩展？`user.css`

Reinstalled without all other extensions

**Comment by wzgrx** [comment]
After completing the selection, I had to click elsewhere to close the UI interface for this smile, which is very inconvenient compared to before
