### ISSUE TITLE
[Bug]: Autolaunch not working on windows

### ISSUE THREAD

**Issue by Centurion-Rome** [vladmandic/automatic#73]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Web ui not opened 

### Steps to reproduce the problem

1. place "set COMMANDLINE_ARGS=--autolaunch" in webui-user,bat"
2. run it
3. 

### What should have happened?

web ui should open in browser

### Commit where the problem happens

ffc54d09383a51b3f93d195d692d44d736bf8f47

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--autolaunch --disable-sdp-attention --xformers --api --no-half-vae --upcast-sampling --opt-channelslast --medvram  --opt-channelslast --opt-sub-quad-attention
```

### List of extensions

none

### Console logs

```Shell
not needed
```

**Comment by vladmandic** [comment]
I'm out for few days, but will take a look Tue or Wed.
