### ISSUE TITLE
[Issue]: temp icon png file not remove but keep filing up.

### ISSUE THREAD

**Issue by tigers2020** [vladmandic/automatic#730]
### Issue Description

![tmp5g2lkym8](https://user-images.githubusercontent.com/18249934/235915360-8a2cef95-9bbe-4f0e-b92c-ae86002d122d.png)
so, this image is keep generate every time when I refresh pages, and keep add same file over and over.
I am using custom model folder path. would it be effect of it?

![image](https://user-images.githubusercontent.com/18249934/235915257-1f672207-d213-4a48-8f0e-f850a0a0e498.png)

**Comment by tigers2020** [comment]
now I am having more tmp files with API errors.
![image](https://user-images.githubusercontent.com/18249934/236111053-f59e317d-0fb2-4556-8fc0-ae14c85de285.png)
![image](https://user-images.githubusercontent.com/18249934/236111080-9a33bed4-3594-40db-b08b-515589b0cc3d.png)
![image](https://user-images.githubusercontent.com/18249934/236111100-1b99855c-b611-42b9-90f0-dece8ab390cb.png)

**Comment by vladmandic** [comment]
there's a separate issue for that and that is due to a bug in gradio, i'll work with that team to fix it.
`api-log.svg` is not even used or referenced by this app, purely by gradio internally.
