### ISSUE TITLE
How to update repo

### ISSUE THREAD

**Issue by specblades** [vladmandic/automatic#733]
### Issue Description

I add --upgrade to args but:
<img width="852" alt="image" src="https://user-images.githubusercontent.com/113993746/235953127-ed2f5a34-1237-43fe-bc0a-c270a725dbe5.png">

**Comment by vladmandic** [comment]
which version are you on? this could be from before `--upgrade` flag was added.
if you posted the version information, i'd know more - please always provide that.
you can do `git pull` once to refresh main repo manually and try again?

**Comment by vladmandic** [comment]
yeah, that commit introduced circular imports so command line args were incorrectly parsed.
do `git pull` once to refresh and then `--upgrade` will work again.
