### ISSUE TITLE
[Feature]: Restore Show Progress In Title Bar

### ISSUE THREAD

**Issue by Lopunny1** [vladmandic/automatic#736]
### Feature description

A few days ago the option to show progress in the title bar option was removed. Is it possible to be restored?

**Comment by vladmandic** [comment]
Changing title in frequent intervals is considered bad practiser and should be avoided.
I understand you're used to this, but I don't want to have it.
Would some other type of notification suffice?

**Comment by Lopunny1** [comment]
I guess that makes sense. I don't always have sound on so I wouldn't use the sound notification.
Perhaps a small pop up box upon completion? I think those cause the tab to flash if you aren't focused on it so that work. 
Or perhaps only update the title to show that it is in progress, then only reverting once completed.
If either is to difficult I'll just have to deal with it, thanks anyway.

**Comment by vladmandic** [comment]
Both are fine, just frequent updates should be avoided.

**Comment by vladmandic** [comment]
ok so you have:
- progress in title bar. i'd re-add it, but different formatting and less frequent updates not to bomb the browser.
- browser notication with actual picture preview, but it only triggers if browser is not in focus
- audio notication, also only triggers if browser is not in focus and its disabled by default, enable in server settings.
