### ISSUE TITLE
[Feature]: Reintroduce Swagger API docs

### ISSUE THREAD

**Issue by zolrath** [vladmandic/automatic#738]
### Feature description

The previous `/docs` endpoint allowed users to view, experiment, and understand what options were available via the API.
This was generally applicable and allowed anyone to integrate this repo into their project, regardless of language.

The gradio docs now available at `?view=api` simply show a list of gradio_client functions that can be called, limiting its usefulness to only users of gradio_client.

It would be great for the swagger API docs to return!

### Version Platform Description

May 3, 2023 - [5d8c787](https://github.com/vladmandic/automatic/commit/5d8c787a7bee2a5ac0ae5e3ee91fe9c6e371bfa2)

**Comment by zolrath** [comment]
> This was generally applicable and allowed anyone to integrate this repo into their project, regardless of language.
> 
> The gradio docs now available at `?view=api` simply show a list of gradio_client functions that can be called, limiting its usefulness to only users of gradio_client.

I've made a simple Feature Request here: https://github.com/gradio-app/gradio/issues/4054

**Comment by vladmandic** [comment]
i've implemented monkey-patch as suggested by gradio theme, docs are available.
