### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'rich'

### ISSUE THREAD

**Issue by alectprasad** [vladmandic/automatic#74]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

webui.bat exits with ModuleNotFoundError: No module named 'rich'

### Steps to reproduce the problem

1. python -m pip install -r .\requirements.txt
2. run webui.bat

### What should have happened?

webui opens

### Commit where the problem happens

ffc54d09383a51b3f93d195d692d44d736bf8f47

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Google Chrome

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
PS C:\Users\alect\Downloads\automatic> pip show rich
Name: rich
Version: 13.3.3
Summary: Render rich text, tables, progress bars, syntax highlighting, markdown and more to the terminal
Home-page: https://github.com/Textualize/rich
Author: Will McGugan
Author-email: willmcgugan@gmail.com
License: MIT
Location: c:\users\alect\appdata\local\programs\python\python310\lib\site-packages
Requires: markdown-it-py, pygments
Required-by:
PS C:\Users\alect\Downloads\automatic> .\webui.bat
venv "C:\Users\alect\Downloads\automatic\venv\Scripts\Python.exe"
Traceback (most recent call last):
  File "C:\Users\alect\Downloads\automatic\launch.py", line 12, in <module>
    from rich import print
ModuleNotFoundError: No module named 'rich'
Press any key to continue . . .
```

**Comment by vladmandic** [comment]
Thanks for report.
I'm out at the moment, ETA for a fix is Tue or Wed.

**Comment by t4ggno** [comment]
Did you used the python from venv? Had the same problem and the following step resolved the issue.

`.\venv\Scripts\Python.exe -m pip install -r requirements.txt`

**Comment by JoBilert** [comment]
Tried that but now get the error 
`ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)`
`ERROR: No matching distribution found for mediapipe`

**Comment by JoBilert** [comment]
> Tried that but now get the error `ERROR: Could not find a version that satisfies the requirement mediapipe (from versions: none)` `ERROR: No matching distribution found for mediapipe`

I solved it by manually creating a python3.10 venv. The webui.bat seemed to use 3.11 for which mediapipe ist not available under Windows.

**Comment by Woisek** [comment]
> I solved it by manually creating a python3.10 venv. The webui.bat seemed to use 3.11 for which mediapipe ist not available under Windows.

Could you please describe how to do this?

**Comment by JoBilert** [comment]
> > I solved it by manually creating a python3.10 venv. The webui.bat seemed to use 3.11 for which mediapipe ist not available under Windows.
> 
> Could you please describe how to do this?

Use **miniconda** to create a python 3.10 environment:

```bash
conda create -n automatic python=3.10
conda activate automatic
```
Now create the python venv:
```bash
python -m venv venv
```
Now you can use the following lines to install the packages:

```bash
.\venv\Scripts\Python.exe -m pip install -r requirements.txt
.\venv\Scripts\Python.exe -m pip install -r requirements_versions.txt
```

Be advised, I still get the CUDA error mentioned in another Bug-Post here. But I can start the WebUI with:

```bash
webui.bat --skip-torch-cuda-test
```

But it obviously means, that I'll have no CUDA-support and run in CPU-Mode only :(

**Comment by Woisek** [comment]
Ah, OK, many thanks anyway. 👍

**Comment by JoBilert** [comment]
> Ah, OK, many thanks anyway. 👍

I added a solution to the CUDA-bug in the corresponding post here. Seems to work

**Comment by Woisek** [comment]
Thanks, I look it up.

**Comment by vladmandic** [comment]
See #92. Work is in progress, in the meantime closing this as duplicate.

**Comment by sdbds** [comment]
> > > I solved it by manually creating a python3.10 venv. The webui.bat seemed to use 3.11 for which mediapipe ist not available under Windows.
> > 
> > 
> > Could you please describe how to do this?
> 
> Use **miniconda** to create a python 3.10 environment:
> 
> ```shell
> conda create -n automatic python=3.10
> conda activate automatic
> ```
> 
> Now create the python venv:
> 
> ```shell
> python -m venv venv
> ```
> 
> Now you can use the following lines to install the packages:
> 
> ```shell
> .\venv\Scripts\Python.exe -m pip install -r requirements.txt
> .\venv\Scripts\Python.exe -m pip install -r requirements_versions.txt
> ```
> 
> Be advised, I still get the CUDA error mentioned in another Bug-Post here. But I can start the WebUI with:
> 
> ```shell
> webui.bat --skip-torch-cuda-test
> ```
> 
> But it obviously means, that I'll have no CUDA-support and run in CPU-Mode only :(

just pip install torch and torchvision with cu118
