### ISSUE TITLE
[Issue]: The notification sound continues until the generation is completed.

### ISSUE THREAD

**Issue by tkiikt** [vladmandic/automatic#740]
### Issue Description

Version: 5d8c787a ,and Same for Version: ba3a0827

When setting the "Play a sound..." check is set to on. The first few milliseconds of the notification sound now repeats after pressing the generate button until it completes. Also, if you uncheck "Play a sound..." and then turn it on, there will be a momentary sound when the server is restarted and the UI returns.

### Version Platform Description

INFO     Starting SD.Next
INFO     Python 3.10.9 on Windows
INFO     Version: 5d8c787a Wed May 3 17:20:22 2023 -0400
INFO     Setting environment tuning
INFO     nVidia CUDA toolkit detected
INFO     Torch 2.0.0+cu118
INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 VRAM 12288 Arch (8, 6) Cores 28

**Comment by vladmandic** [comment]
silly mistake, should be fixed now.
