### ISSUE TITLE
[Feature]: Please also add notification.mp3 to the ignore list.

### ISSUE THREAD

**Issue by tkiikt** [vladmandic/automatic#742]
### Feature description

I would like notification.mp3 to be included in the Ignore list. I have replaced the mp3 file with my preferred sound, but it seems to be overwritten by the upgrade.

**Comment by vladmandic** [comment]
added `/*.mp3` to .gitignore.

**Comment by tkiikt** [comment]
In fact, even after this support, notification.mp3 is overwritten at each update.

Version: 05656a54

**Comment by vladmandic** [comment]
notifiation.mp3 is part of repo. create your own and set it as default. don't overwrite.

**Comment by tkiikt** [comment]
Ok, If you say so, I'll do it, but if the user doesn't have a choice, it's a pretty boring feature.

**Comment by vladmandic** [comment]
what are you talking about??? you have full choice - **put any mp3 you want, just don't call it exactly `notifications.mp3`, call it anything you want**. and then in settings, select that mp3 instead of default one.

**Comment by tkiikt** [comment]
Oh, I am sorry. I misunderstood your meaning. Understood.
