### ISSUE TITLE
[Issue]: Noise Inversion Fail because missing 's_min_uncond' arg

### ISSUE THREAD

**Issue by ConstantEgo** [vladmandic/automatic#746]
### Issue Description

The extension [multidiffusion-upscaler-for-automatic1111](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111) does not work as it should after auto-updating the extension. (By default, the extension update is triggered every time we start the main module.) 
The authors of the original extension have updated the code to match the updates from "AUTOMATIC1111". 
https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111/issues/164

And now we have broken Noise Inversion. 

HOW TO FIX IT AT THIS POINT (TEMPORARILY):

Go to .\extensions-builtin\multidiffusion-upscaler-for-automatic1111" and run git command:
git checkout 860f8a405193bcd992e21d82e43fa18137bc4923

Then add "--skip-update --skip-requirements --skip-extensions --skip-git" to "webui.bat" launch options. 

When the respected author [vladmandic](https://github.com/vladmandic) (or someone else) can update the code to meet the new requirements of the extension, the launch options MUST be removed. 

### Version Platform Description

Latest published version: e0543e4475b6de07fb40a03ccad413a5bbd2397f 2023-05-03T23:15:18Z

**Comment by vladmandic** [comment]
fixed, closing.
