### ISSUE TITLE
[Issue]: model.ckpt not found

### ISSUE THREAD

**Issue by Metalica** [vladmandic/automatic#749]
### Issue Description

10:05:17-740905 WARNING  Checkpoint model.ckpt not found; loading fallback v1-5-pruned-emaonly.safetensors

**Also:** 
WARNING  Package wrong version: timm 0.4.12 required 0.6.13
INFO     Installing package: timm==0.6.13

### Version Platform Description

INFO     Version: e0543e44 Wed May 3 19:15:18 2023 -0400

**Comment by vladmandic** [comment]
what is the actual problem?

if there was no previous model selected, default desired model is just `model.ckpt`.
and if it doesn't exist, it will load first available model which happens to be `v1-5-pruned-emaonly.safetensors`.

and regarding `wrong versions` - installer did its job! it found incorrect version and corrected it.
