### ISSUE TITLE
[Issue]: temp icon png file not remove but keep filing up it gets worse.

### ISSUE THREAD

**Issue by tigers2020** [vladmandic/automatic#751]
### Issue Description

![image](https://user-images.githubusercontent.com/18249934/236191328-2c91278c-d2ea-4ac6-8ffe-a57c6831f637.png)
![image](https://user-images.githubusercontent.com/18249934/236191446-7d53bb52-92d1-4e67-96e5-32e8d571dae5.png)

every time I refresh the page, more tmp png created.

**Comment by rayminator2023** [comment]
that has something to do with the api you just to wait for it to catch up

those are just temp file they mostly are only 1kb file size they suppose to be cleared after a complete shutdown I think

**Comment by tigers2020** [comment]
well, it doesn't go away, that's is the problem.
the file still remain and keep filing up every time running server. 
plus, whenever server working download model need, tmp folder also filing up without remove any after.
![image](https://user-images.githubusercontent.com/18249934/236200419-ae435511-8d8b-45ae-968a-3c902ede01fe.png)

**Comment by vladmandic** [comment]
thats a bug in new gradio, i'll try to work with them to fix it.

**Comment by TKS4** [comment]
Yeah I seem to have this happening anytime the server fires up, just a ton of little files and folders (the png images seem to correspond to the typical logo placeholder images in the various tabs when starting up a fresh new session). Not sure why we need these temporary png's always being created on bootup, seems to have only started with the major gradio update to my recollection.

**Comment by vladmandic** [comment]
created gradio issue <https://github.com/gradio-app/gradio/issues/4063>

and attempting a workaround so as soon as img element is created in dom, i'm trying to delete it.
(code for this will be published this afternoon)

**Comment by 1lint** [comment]
I also had this issue, making the following change fixed it for me:
In `gradio.routes.App` change lines 267 and 272 from
`@app.get("/static/{path:path}")` to `@app.get("/assets/{path}")`

You can find the file by running 
```
from gradio.routes import App
from inspect import getfile
import subprocess
# replace "code" with your text editor, i.e. "nano"
subprocess.run(["code", getfile(App)])
```

**Comment by vladmandic** [comment]
fixed upstream and will be resolved when new gradio version is released.

**Comment by vladmandic** [comment]
fixed!
