### ISSUE TITLE
[Issue]: Inpaint Sketch lags out in some browsers

### ISSUE THREAD

**Issue by gruevy** [vladmandic/automatic#752]
### Issue Description

This issue is also in base automatic1111:   https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7776

Short version is that the sketch canvas lags out and is unusable in Chrome and other common browsers, but works in Firefox. Some users in the link above reported that changing their resolution's zoom factor for the monitor back down to 100% fixed it as well. 

Does not throw any errors in the console logs.

### Version Platform Description

Windows 11, chrome

Version: 22090d7b Thu May 4 06:53:01 2023 -0400

**Comment by cvrunmin** [comment]
Such issue can be reproduced in separated gradio app. See gradio/gradio#3473

**Comment by crazygonuts** [comment]
If its helpful, ill mention that for me at least this only occurs when using the "send to inpaint / send to sketch" buttons from the im2img tav.  If i drag and drop the same image directly into the sketch or inpaint window it doesnt occur

**Comment by TKS4** [comment]
This may be totally tangential but in FF, antifingerprinting settings can throw off the entire rendering of a browser where things like Vsync will be non-functional. Likewise in FF there is HTML canvas data that is prompted for sharing when you first try to inpaint something, and if you have that set to blocked, it will cause a whole host of issues (most times it will just block the ability to inpaint entirely).

Now the issue here is about browsers other than FF, which makes what I'm talking about basically inconsequential (since I really don't think Edge nor Chrome are browsers that install by default with these fingerprinting preventive measures).

**Comment by gruevy** [comment]
I just tried it again, and the inpaint sketch worked. It was a little slow to get ready, but after giving it the ten seconds or so it needed, it worked. 

I got a cuda out of memory error when I hit generate, though, but that might be expected. i think the image was too big

**Comment by vladmandic** [comment]
ok, at least some progress with gradio :)

**Comment by cibernicola** [comment]
I have this "feature" from the beginning, I don't know why.
As mentioned above, if I bring the image to "in paint sketch" via buttons, everything is completely lag and unusable. If I paste the image directly, it works but first run goes crazy long.


Although in the version of a few days ago it worked correctly. I'm not clear if it's some option, plugin or configuration. 

Tested on FF, Chrome and Vivaldi (Chromium based)
Win 10, 3090

**Comment by vladmandic** [comment]
see https://github.com/gradio-app/gradio/issues/5858

**Comment by Number6UK** [comment]
This is an old, closed issue for a long-standing problem but I think I may have discovered a workaround. It's definitely working for me.

My workaround at the moment (on Windows 11, but there'll be an equivalent for the other OSs), which I'm still testing but seems to work so far, is to:

    Always use a particular browser for WebUI stuff; in my case, Firefox Developer Edition.

    Create a shortcut for the browser's .exe

    Right cilck the shortcut > Compatibility tab > Change high DPI settings button

    In Program DPI, tick the box Use this setting to fix scaling problems for this program instead of the ones in Settings

    In High DPI scaling override, tick the box Override high DPI scaling behaviour. In the Scaling performed by: dropdown, choose System (Enhanced) (this might not be available on older versions of Windows - if not, try one of the other options; I haven't tested them myself yet)

    Press OK to close the High DPI settings window,

    Press OK to close the shortcut properties window.

    Close any instance of the browser affected by the High DPI change - e.g. if you were setting the DPI settings on a shortcut to chrome.exe, close all instances of Chrome.

    Start the browser from the shortcut you set the properties on

    Open the WebUI in that browser and see if the bug still occurs

Hopefully it will help you. The main drawbacks to this workaround are having to use a different browser just for WebUI, the fonts being a tiny bit less pretty, and some odd mouseover issues where tooltips sometimes show up a large distance from the mouse cursor. I've not found anything that's actually broken by this method however and have been using it for over a week now sucessfully.

Hope it works for you too.
