### ISSUE TITLE
[Issue]: tqdm and diffusers wrong version on every restart

### ISSUE THREAD

**Issue by crazygonuts** [vladmandic/automatic#756]
### Issue Description

Every time I start my server it gives me these lines:

10:15:46-763163 WARNING  Package wrong version: tqdm 4.64.1 required 4.65.0
10:15:46-763163 INFO     Installing package: tqdm==4.65.0
10:15:48-517692 WARNING  Package wrong version: diffusers 0.14.0 required 0.16.1
10:15:48-517692 INFO     Installing package: diffusers==0.16.1

and then on the next restart apparently they are the wrong version again.  I'm attaching my setup.log but I don't see any further mention of them

Everything seems to be working fine so this is not a high priority issue but I thought it was odd.

[setup.log](https://github.com/vladmandic/automatic/files/11399903/setup.log)

### Version Platform Description

Version: 22090d7b Thu May 4 06:53:01 2023 -0400
Windows 10
Chrome

**Comment by vladmandic** [comment]
Most likely some extension is modifying system package (extensions should never do thar, but by installing extension you give it full power).

Disable any extensions you have installed and try what happens then.

**Comment by crazygonuts** [comment]
is there a file i can edit to disable and enable extensions so its easier to track down which one is the culprit rather than needing to go through the ui?

**Comment by vladmandic** [comment]
`config.json`
> "disabled_extensions": []

its an array of strings where each string is basically a folder name from `/extensions`
or you can just move extension from `/extensions` to somewhere outside of the repo and then move it back when you want.

**Comment by crazygonuts** [comment]
the culprit seems to be [dreambooth](https://github.com/d8ahazard/sd_dreambooth_extension).  i will try re-downloading it, would be interesting to hear if other people are getting this or not.

**Comment by crazygonuts** [comment]
yeah the dreambooth requirements.txt has both

diffusers~=0.14.0
tqdm~=4.64.1

**Comment by vladmandic** [comment]
Dreambooth should not change those requirements, that is bad behavior.
