### ISSUE TITLE
[Issue]: RSS memory leak when changing models

### ISSUE THREAD

**Issue by lolxdmainkaisemaanlu** [vladmandic/automatic#758]
### Issue Description

Process frequently getting killed (often after just 2 repeats ) with UniPC sampler, 20 steps. Prompt S/R and CFG scale as x and y scale respectively. Also using a Lora. Same is not happening on auto1111.

Definitely not a VRAM issue, have RTX 3060 12GB. 

### Version Platform Description

Linux Mint 21.1, 16 GB RAM, RTX 3060 12GB, SDP attention.

**Comment by vladmandic** [comment]
Need details on "process's killed"?
I'd it's by kernel, what do system logs show.

**Comment by vladmandic** [comment]
That means that linux kernel decided to kill the process.

So check linux system log on why it did that and maybe we can do something about it.

Typically they're in /var/log

**Comment by vladmandic** [comment]
linux kernel decided to kill a process when it went above allowed memory threshold, seems there is a memory leak (RAM, not VRAM) when switching models, i'll chase it down.

**Comment by vladmandic** [comment]
i've reduced the leak significantly, from >1GB per switch to ~100mb per model switch.
the rest will be hard to track down, but this should be sufficient to run with decent number of models (just don't try to do grid with 100 models)

**Comment by vladmandic** [comment]
there's a flag for xyz which controls if previous settings are going to be unwound on each generation.
so if you even have a single model listed, it will load it, run one generation, restore to base model, etc...
but yes, still looks a bit strange. can you share exact xyz script configuration you're using?

**Comment by vladmandic** [comment]
i've just uploaded some major changes to xyz script.
