### ISSUE TITLE
[Issue]: Model and VAE seem to load twice when starting the server.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#759]
### Issue Description

When starting the sever, the model checkpoint and the VAE seem to load twice;

![image](https://user-images.githubusercontent.com/1969381/236301415-e873a4be-b6ad-4fd9-80e3-a0bdd980cd12.png)

### Version Platform Description

Version: eb03fce3 Tue May 2 15:57:28 2023 -0400

Windows 10, AMD RX 6600 XT 8Gb, Chrome.

**Comment by vladmandic** [comment]
fix in dev, will publish later today.

**Comment by vladmandic** [comment]
i said in my private dev, its not published yet. will publish later today.

**Comment by brknsoul** [comment]
I dunno if I said it before, but huge thanks for doing what you do, vladmandic.

**Comment by vladmandic** [comment]
published, closing.
