### ISSUE TITLE
[Bug]: Process (upscale) endless loop on windows

### ISSUE THREAD

**Issue by Centurion-Rome** [vladmandic/automatic#76]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Using upscale causes endless loop

### Steps to reproduce the problem

1. Go to "Process" tab and get any generated image
2. Select any upscaler ie "4x-UltraSharp" set ratio to 1.6 and press generate
3. processing never ends, image is not beeing saved. you have to stop terminal

### What should have happened?

Image gets upscaled and saved to disk

### Commit where the problem happens

ffc54d09383a51b3f93d195d692d44d736bf8f47

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
--autolaunch --disable-sdp-attention --xformers --api --no-half-vae --upcast-sampling --opt-channelslast --medvram  --opt-channelslast --opt-sub-quad-attention
```

### List of extensions

none

### Console logs

```Shell
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 27/27 [00:26<00:00,  1.01it/s]
```

**Comment by gelukuMLG** [comment]
Same thing happens when you try generating higher res images, infinite loop at 1024x1024 resolution.

**Comment by vladmandic** [comment]
See #92. Work is in progress, in the meantime closing this as duplicate.
