### ISSUE TITLE
[Extension]: Runtime Error using Ultimate SD Upscale in IMG-2-IMG

### ISSUE THREAD

**Issue by Arkane** [vladmandic/automatic#761]
### Issue Description

- Create base image
- Use Hirez to upscale once
- Send to img2img
- Use Ultimate SD Upscale script to upscale again

Get this error everytime, doesn't matter which upscaling method I use with the script
`RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4 channels instead`

This seems to be new, I never encountered this error before

### Version Platform Description

Version: bb438efe Tue Apr 25 09:53:11 2023 -0400

Windows 11

**Comment by vladmandic** [comment]
i think i've heard about similar ultimate sd upscale issues if input is too large (and you're already doing hires before sd upscale, so that might just push it over the edge) - can you try with different input sizes, just to verify?

**Comment by Arkane** [comment]
Will check right now👍

**Comment by Arkane** [comment]
Okay so it seems i'm able to use it with much smaller resolutions, but currently it seems to return this error with just 1024x1024 images being upscaled. I've never had this issue before, I used to be able to upscale very large images, even around 2000x2000.

Not sure what's going on but something is definitely not right, I will try a few more things on my end to make sure

**Comment by vladmandic** [comment]
very similar to #434, but need to check what is triggering this. 
however, i'll be mostly ooo for few days, so not likely before next week.

**Comment by Arkane** [comment]
Okay so I tried a few things but i'm getting the same result, no restart or settings reset seems to fix it
I'm actually getting the exact same error as #434, it seems both are linked somehow

Alright sounds good, let me know if you find something out👍 
Have a nice weekend, thanks for the quick response! 👏 
```
gradio call: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\Stable Diffusion - Vladmandic\automatic\modules\call_queue.py:58 in f                                             │
│                                                                                                                      │
│    57 │   │   │   │   pr.enable()                                                                                    │
│ ❱  58 │   │   │   res = list(func(*args, **kwargs))                                                                  │
│    59 │   │   │   if shared.cmd_opts.profile:                                                                        │
│                                                                                                                      │
│ C:\Stable Diffusion - Vladmandic\automatic\modules\call_queue.py:38 in f                                             │
│                                                                                                                      │
│    37 │   │   │   try:                                                                                               │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    39 │   │   │   finally:                                                                                           │
│                                                                                                                      │
│                                               ... 23 frames hidden ...                                               │
│                                                                                                                      │
│ C:\Stable Diffusion - Vladmandic\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward            │
│                                                                                                                      │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ ❱  463 │   │   return self._conv_forward(input, self.weight, self.bias)                                              │
│    464                                                                                                               │
│                                                                                                                      │
│ C:\Stable Diffusion - Vladmandic\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward      │
│                                                                                                                      │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                                             │
│ ❱  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                                     │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4
channels instead
```

**Comment by Badenstein** [comment]
I had the same error on Automatic 1111. With exactly the same RunTimeError. The solution was to set the "Default upscaler for image resize operations" to none in the settings panel. Solution suggested on the FAQ page for Ultimate SD Upscaler: https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/wiki/FAQ , lists the same error.

**Comment by vladmandic** [comment]
related #434 #761 #809

**Comment by vladmandic** [comment]
@Arkane can you confirm the solution from @Badenstein is applicable?

**Comment by Arkane** [comment]
That actually does seem to have "fixed" the issue👏
I am now able to upscale large images again ~

Good catch!🙌

**Comment by AlanZhou2022** [comment]
A different problem occurred when I used ultimate SD upscale to optimize my picture, and I cannot save the modified picture (FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/rl/9htrh67s3fd7z1c4kvy5kttw0000gn/T/gradio/tmpgv1ug2um.png'), anybody knows how to solve the problem?

**Comment by dareima** [comment]
> I had the same error on Automatic 1111. With exactly the same RunTimeError. The solution was to set the "Default upscaler for image resize operations" to none in the settings panel. Solution suggested on the FAQ page for Ultimate SD Upscaler: https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/wiki/FAQ , lists the same error.

You're my hero. That absolutely fixed it for me. The script works great again, with no errors.
