### ISSUE TITLE
[Issue]: --ui-settings-file command line argument no longer works

### ISSUE THREAD

**Issue by Karajorma** [vladmandic/automatic#765]
### Issue Description

Setting --ui-settings-file doesn't seem to do anything. Settings are still saved to config.json instead of the file specified. This still seems to work correctly in Automatic1111

### Version Platform Description

Windows 10, Version: e0543e44 Wed May 3 19:15:18 2023 -0400

**Comment by vladmandic** [comment]
Renamed to just `--config`
Check `--help` for currently available flags.

**Comment by Karajorma** [comment]
Cheers. I was using the wiki.
