### ISSUE TITLE
[Issue]: TypeError: cannot create weak reference to 'weakref.CallableProxyType' object on startup (loading models)

### ISSUE THREAD

**Issue by kotx** [vladmandic/automatic#766]
### Issue Description

Loading any models (ckpt, safetensors, etc) errors with `TypeError: cannot create weak reference to 'weakref.CallableProxyType' object`.

Logs:
<details>
<pre>
22:52:34-165456 WARNING  Checkpoint model.ckpt not found; loading fallback AOM3.safetensors
Loading weights: /home/kot/automatic/models/Stable-diffusion/AOM3.safetensors ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/2.1 GB -:--:--
22:52:34-346264 INFO     Creating model from config: /home/kot/automatic/configs/v1-inference.yaml
22:52:34-347702 ERROR    loading stable diffusion model: TypeError
╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮
│ /home/kot/automatic/modules/sd_models.py:380 in load_model                                                                                                                                           │
│                                                                                                                                                                                                      │
│   379 │   │   with sd_disable_initialization.DisableInitialization(disable_clip=clip_is_includ                                                                                                       │
│ ❱ 380 │   │   │   sd_model = instantiate_from_config(sd_config.model)                                                                                                                                │
│   381 │   except Exception:                                                                                                                                                                          │
│                                                                                                                                                                                                      │
│ /home/kot/automatic/repositories/stable-diffusion-stability-ai/ldm/util.py:89 in instantiate_from_config                                                                                             │
│                                                                                                                                                                                                      │
│    88 │   │   raise KeyError("Expected key `target` to instantiate.")                                                                                                                                │
│ ❱  89 │   return get_obj_from_str(config["target"])(**config.get("params", dict()))                                                                                                                  │
│    90                                                                                                                                                                                                │
│                                                                                                                                                                                                      │
│                                                                                       ... 4 frames hidden ...                                                                                        │
│                                                                                                                                                                                                      │
│ /home/kot/automatic/venv/lib/python3.10/site-packages/torch/nn/modules/module.py:1471 in _register_load_state_dict_pre_hook                                                                          │
│                                                                                                                                                                                                      │
│   1470 │   │   handle = hooks.RemovableHandle(self._load_state_dict_pre_hooks)                                                                                                                       │
│ ❱ 1471 │   │   self._load_state_dict_pre_hooks[handle.id] = _WrappedHook(hook, self if with_mod                                                                                                      │
│   1472 │   │   return handle                                                                                                                                                                         │
│                                                                                                                                                                                                      │
│ /home/kot/automatic/venv/lib/python3.10/site-packages/torch/nn/modules/module.py:54 in __init__                                                                                                      │
│                                                                                                                                                                                                      │
│     53 │   │   if module is not None:                                                                                                                                                                │
│ ❱   54 │   │   │   self.module: weakref.ReferenceType["Module"] = weakref.ref(module)                                                                                                                │
│     55 │   │   │   self.with_module = True                                                                                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: cannot create weak reference to 'weakref.CallableProxyType' object

During handling of the above exception, another exception occurred:

╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮
│ /home/kot/automatic/webui.py:151 in load_model                                                                                                                                                       │
│                                                                                                                                                                                                      │
│   150 │   try:                                                                                                                                                                                       │
│ ❱ 151 │   │   modules.sd_models.load_model()                                                                                                                                                         │
│   152 │   │   modules.sd_models.skip_next_load = True                                                                                                                                                │
│                                                                                                                                                                                                      │
│ /home/kot/automatic/modules/sd_models.py:382 in load_model                                                                                                                                           │
│                                                                                                                                                                                                      │
│   381 │   except Exception:                                                                                                                                                                          │
│ ❱ 382 │   │   sd_model = instantiate_from_config(sd_config.model)                                                                                                                                    │
│   383 │   # sd_model = instantiate_from_config(sd_config.model)                                                                                                                                      │
│                                                                                                                                                                                                      │
│                                                                                       ... 5 frames hidden ...                                                                                        │
│                                                                                                                                                                                                      │
│ /home/kot/automatic/venv/lib/python3.10/site-packages/torch/nn/modules/module.py:1471 in _register_load_state_dict_pre_hook                                                                          │
│                                                                                                                                                                                                      │
│   1470 │   │   handle = hooks.RemovableHandle(self._load_state_dict_pre_hooks)                                                                                                                       │
│ ❱ 1471 │   │   self._load_state_dict_pre_hooks[handle.id] = _WrappedHook(hook, self if with_mod                                                                                                      │
│   1472 │   │   return handle                                                                                                                                                                         │
│                                                                                                                                                                                                      │
│ /home/kot/automatic/venv/lib/python3.10/site-packages/torch/nn/modules/module.py:54 in __init__                                                                                                      │
│                                                                                                                                                                                                      │
│     53 │   │   if module is not None:                                                                                                                                                                │
│ ❱   54 │   │   │   self.module: weakref.ReferenceType["Module"] = weakref.ref(module)                                                                                                                │
│     55 │   │   │   self.with_module = True                                                                                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
TypeError: cannot create weak reference to 'weakref.CallableProxyType' object
</pre>
</details>

### Version Platform Description

SD.Next Version: c470f399 Thu May 4 16:55:41 2023 -0400

Intel Arc A770 GPU
WSL2 Ubuntu 22.04
Python 3.10.6

**Comment by kotx** [comment]
Contents of setup.log (hopefully they are not sensitive):
[setup.log](https://github.com/vladmandic/automatic/files/11403630/setup.log)

**Comment by vladmandic** [comment]
looping in @Disty0 as IPEX expert

**Comment by Disty0** [comment]
This causes it: pip install --upgrade pytorch_lightning==1.9.4

Using pytorch_lightning with version 1.9.4 causes this error.
Installer should have installed pytorch_lightning version 1.8.6.

If it didn't (and it did not install it according to your logs) you can install it manually with pip.

First switch to Automatic's virtual enviroment.
Run this command inside of the automatic folder:
`source venv/bin/activate`

Then install pytorch_lightning version 1.8.6:
`pip install --upgrade pytorch_lightning==1.8.6`

**Comment by vladmandic** [comment]
actually, its much simpler than that @kotx, from your log - your server arguments are []
if you want to use IPEX, you **must** have `--use-ipex` param explicitly set.

you probably had it before, so ipex support was installed, then you started without the flag so it uses newer version of `pytorch_lightning` which is not supported with ipex.

**Comment by kotx** [comment]
> if you want to use IPEX, you **must** have `--use-ipex` param explicitly set.

@vladmandic 

Ah, I wasn't aware a flag was required, but it makes sense. Works now, thank you!

By the way, the library you use to display tracebacks is so cool, what's it called?

**Comment by vladmandic** [comment]
It's `rich`
You can see common init code in `modules/errors.py`
