### ISSUE TITLE
[Feature]: Organize extra networks by date added

### ISSUE THREAD

**Issue by gsgoldma** [vladmandic/automatic#767]
### Feature description

it would be nice to be able to sort the loras, hypernetworks, checkpoints, text inversions, etc, by date added to the folder. Sometimes I want to check out all the new ones I've added since I don't remember the file names necessarily.

**Comment by vladmandic** [comment]
looping in @anapnoe

**Comment by anapnoe** [comment]
yes it can be of some use to people for now you can organize by folder create one name it recent and add your new staff there

**Comment by vladmandic** [comment]
closing in favor of #1337
