### ISSUE TITLE
[Issue]: "Train > Preprocess Images" should keep the alpha channel of images

### ISSUE THREAD

**Issue by GammelSami** [vladmandic/automatic#769]
### Issue Description

I removed the background of every image in my dataset and now want to add BLIP Caption txt files. But even when I enable "Keep original size" all the images get white backgrounds again.

Idk if there is a usecase where you are glad to get rid of the alpha channel. If yes, it should be an optional checkbox ofc.

Also in my case it would be cool to have the option to disable the "image processing" so it only saves the TXTs to protect my drive from unneccessary writing.

### Version Platform Description

Python 3.10.9 on Windows 10
Version: c470f399 Thu May 4 16:55:41 2023 -0400

**Comment by vladmandic** [comment]
training works with with RGB images only. even if preprocessing left alpha in-place, it would still either cause issues or be converted to RGB during actual image loading while training. so its highly desired that preprocessing does that as well.
leaving alpha would make sense only if alpha was actually used later on in any shape or form.

on the second, that is valid - create captions only. please create a feture request for that.

**Comment by GammelSami** [comment]
I wanna use "Use PNG alpha channel as loss weight" during training. 

But if the user took the time to remove backgrounds, they probably also cropped their images already.

**Comment by vladmandic** [comment]
ah, ok, that is a special case. not even sure how its handled, haven't looked at that code (quite a legacy) in a while.
will take a look.

**Comment by GammelSami** [comment]
but if alpha can lead to issues during training it may be better to just leave it as it is and only implement the captions only feature?

if a user wants to really crop their alpha images, there are plenty of easy (and even better) UIs to batch crop images ([birme.net](https://www.birme.net/?target_width=512&target_height=512), [Power Toys](https://github.com/microsoft/PowerToys)) but there are no easy ways to run BLIP.

**Comment by vladmandic** [comment]
I've added `Keep original image channels` and `Create captions only` options in preprocessing.
Don't really have time for deep-testing, so report if any issues.

**Comment by vladmandic** [comment]
That's up to Python's Pillow package. What that option does is disable `image.convert('RGB')`, nothing else.
