### ISSUE TITLE
[Bug]: Sliders in Firefox are broken

### ISSUE THREAD

**Issue by t4ggno** [vladmandic/automatic#77]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Something is wrong with the CSS in Firefox. 

![image](https://user-images.githubusercontent.com/14984216/230796433-fe4d59a1-0397-473c-8e11-d8677b3e5ecd.png)

### Steps to reproduce the problem

1. Start automatic
2. Open firefox and chrome
3. Go to "http://127.0.0.1:7860/"
4. Check the stylesheet

### What should have happened?

The UI should be the same

### Commit where the problem happens

a7a2b30

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox, Google Chrome

### Command Line Arguments

```Shell
.\webui.bat --skip-torch-cuda-test --autolaunch
```

### List of extensions

No

### Console logs

```Shell
Creating model from config: C:\vlad-automatic-512\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Couldn't find VAE named vae-ft-mse-840000-ema-pruned.ckpt; using None instead
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0):
Model loaded in 2.2s (load=0.3s create=0.4s apply=0.9s vae=0.6s)
Startup time: 10.8s (torch=4.3s libraries=2.3s codeformer=0.1s scripts=1.0s ui=0.3s gradio=0.2s scripts
app_started_callback=0.1s checkpoint=2.6s)
```

### Additional information

Fresh installation

**Comment by AbdBarho** [comment]
Might be relevant:
https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/

**Comment by vladmandic** [comment]
fixed in the latest update
