### ISSUE TITLE
[Feature]: Option to create captions only in Train > Preprocess Images

### ISSUE THREAD

**Issue by GammelSami** [vladmandic/automatic#770]
### Feature description

My dataset is already preprocessed, I just wanna add BLIP captions without duplicating my images. (Train > Preprocess Images)

Idea from #769 

### Version Platform Description

Python 3.10.9 on Windows 10
Version: c470f39 Thu May 4 16:55:41 2023 -0400

**Comment by vladmandic** [comment]
I've added `Keep original image channels` and `Create captions only` options in preprocessing.
Don't really have time for deep-testing, so report if any issues.

**Comment by vladmandic** [comment]
ok, i've updated the logic.

**Comment by GammelSami** [comment]
sry, i was offline for a while. 
looks like txt files are still named in the same pattern.

**Comment by vladmandic** [comment]
ahhh, overlooked one case, should be fixed now.
