### ISSUE TITLE
Error running git: None / clone

### ISSUE THREAD

**Issue by little-happypig** [vladmandic/automatic#771]
### Issue Description

Creating venv in directory E:\All-Assets\AI-Painting\automatic\venv using python "D:\Python\python.exe"
Using VENV: E:\All-Assets\AI-Painting\automatic\venv
20:19:37-606200 INFO     Starting SD.Next
20:19:37-609129 INFO     Python 3.10.10 on Windows
20:19:37-947011 INFO     Version: 19007ca6 Fri May 5 08:02:40 2023 -0400
20:19:38-001854 INFO     Setting environment tuning
20:19:38-015665 INFO     nVidia CUDA toolkit detected
20:19:38-016642 INFO     Installing package: torch torchaudio torchvision --index-url
                         https://download.pytorch.org/whl/cu118
20:21:55-263715 INFO     Torch 2.0.0+cu118
20:21:55-281974 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
20:21:55-283929 INFO     Torch detected GPU: NVIDIA GeForce RTX 3060 Ti VRAM 8191 Arch (8, 6) Cores 38
20:21:55-284905 INFO     Installing package: tensorflow==2.12.0
20:22:20-168903 INFO     Verifying requirements
20:22:20-169879 INFO     Installing package: addict
20:22:21-511031 INFO     Installing package: aenum
20:22:22-923902 INFO     Installing package: aiohttp
20:22:26-462044 INFO     Installing package: anyio
20:22:28-308886 INFO     Installing package: appdirs
20:22:29-668735 INFO     Installing package: astunparse
20:22:30-997290 INFO     Installing package: basicsr
20:23:02-108860 INFO     Installing package: bitsandbytes
20:23:06-264766 INFO     Installing package: blendmodes
20:23:08-047812 INFO     Installing package: clean-fid
20:23:10-313037 INFO     Installing package: easydev
20:23:12-757507 INFO     Installing package: extcolors
20:23:14-749589 INFO     Installing package: facexlib
20:23:33-829030 INFO     Installing package: filetype
20:23:35-607249 INFO     Installing package: font-roboto
20:23:37-329793 INFO     Installing package: fonts
20:23:38-916014 INFO     Installing package: future
20:23:40-396111 INFO     Installing package: gdown
20:23:42-965104 INFO     Installing package: gfpgan
20:23:44-839747 INFO     Installing package: GitPython
20:23:47-316915 INFO     Installing package: httpcore
20:23:49-530702 INFO     Installing package: inflection
20:23:51-261683 INFO     Installing package: jsonmerge
20:23:53-999202 INFO     Installing package: kornia
20:23:58-125548 INFO     Installing package: lark
20:24:00-050931 INFO     Installing package: lmdb
20:24:01-607250 INFO     Installing package: lpips
20:24:03-304718 INFO     Installing package: numpy
20:24:11-972991 INFO     Installing package: omegaconf
20:24:14-556720 INFO     Installing package: open-clip-torch
20:24:22-269659 INFO     Installing package: opencv-contrib-python
20:24:25-313711 INFO     Installing package: piexif
20:24:27-136654 INFO     Installing package: Pillow
20:24:30-235111 INFO     Installing package: psutil
20:24:32-459832 INFO     Installing package: pyyaml
20:24:34-403623 INFO     Installing package: realesrgan
20:24:36-435579 INFO     Installing package: requests
20:24:38-590003 INFO     Installing package: resize-right
20:24:40-451728 INFO     Installing package: rich
20:24:42-221687 INFO     Installing package: safetensors
20:24:44-136690 INFO     Installing package: scipy
20:24:46-005842 INFO     Installing package: tb_nightly
20:24:48-204130 INFO     Installing package: toml
20:24:50-139193 INFO     Installing package: torch
20:24:53-006815 INFO     Installing package: torchdiffeq
20:24:55-170846 INFO     Installing package: torchsde
20:24:58-036610 INFO     Installing package: torchvision
20:25:00-033046 INFO     Installing package: voluptuous
20:25:02-050824 INFO     Installing package: yapf
20:25:03-821886 INFO     Installing package: scikit-image
20:25:05-599425 INFO     Installing package: tqdm==4.65.0
20:25:07-375759 INFO     Installing package: accelerate==0.18.0
20:25:09-979709 INFO     Installing package: opencv-python==4.7.0.72
20:25:11-805349 INFO     Installing package: diffusers==0.16.1
20:25:16-249204 INFO     Installing package: einops==0.4.1
20:25:18-297898 INFO     Installing package: gradio==3.28.1
20:25:46-491839 INFO     Installing package: numexpr==2.8.4
20:25:48-889520 INFO     Installing package: pandas==1.5.3
20:26:07-261629 INFO     Installing package: protobuf==3.20.3
20:26:09-414933 INFO     Installing package: pytorch_lightning==1.9.4
20:26:16-155697 INFO     Installing package: transformers==4.26.1
20:26:31-683790 INFO     Installing package: timm==0.6.13
20:26:34-063286 INFO     Installing package: tomesd==0.1.2
20:26:36-639591 INFO     Installing package: urllib3==1.26.15
20:26:39-565534 INFO     Running setup
20:26:39-566510 INFO     Installing packages
20:26:39-567487 INFO     Installing package:
                         git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
20:27:04-836564 ERROR    Error running pip: install --upgrade
                         git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
20:27:04-838517 INFO     Installing repositories
20:27:25-980772 ERROR    Error running git: None / clone "https://github.com/Stability-AI/stablediffusion.git"
                         "E:\All-Assets\AI-Painting\automatic\repositories\stable-diffusion-stability-ai"
20:27:26-047721 ERROR    Error running git: None / -C
                         "E:\All-Assets\AI-Painting\automatic\repositories\stable-diffusion-stability-ai" checkout
                         cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf
20:27:47-240888 ERROR    Error running git: None / clone "https://github.com/CompVis/taming-transformers.git"
                         "E:\All-Assets\AI-Painting\automatic\repositories\taming-transformers"
20:27:47-294074 ERROR    Error running git: None / -C
                         "E:\All-Assets\AI-Painting\automatic\repositories\taming-transformers" checkout
                         3ba01b241669f5ade541ce990f7650a3b8f65318
20:32:47-419070 ERROR    Error running git: None / clone "https://github.com/crowsonkb/k-diffusion.git"
                         "E:\All-Assets\AI-Painting\automatic\repositories\k-diffusion"
20:32:47-473657 ERROR    Error running git: None / -C "E:\All-Assets\AI-Painting\automatic\repositories\k-diffusion"
                         checkout b43db16749d51055f813255eea2fdf1def801919
20:33:08-618842 ERROR    Error running git: None / clone "https://github.com/sczhou/CodeFormer.git"
                         "E:\All-Assets\AI-Painting\automatic\repositories\CodeFormer"
20:33:08-671075 ERROR    Error running git: None / -C "E:\All-Assets\AI-Painting\automatic\repositories\CodeFormer"
                         checkout c5b4593074ba6214284d6acd5f1719b6c5d739af
20:33:29-826108 ERROR    Error running git: None / clone "https://github.com/salesforce/BLIP.git"
                         "E:\All-Assets\AI-Painting\automatic\repositories\BLIP"
20:33:29-878936 ERROR    Error running git: None / -C "E:\All-Assets\AI-Painting\automatic\repositories\BLIP" checkout
                         48211a1594f1321b00f14c9f7a5b4813144b2fb9
20:33:29-880918 INFO     Installing submodules

**Comment by Danamir** [comment]
I got the same error, here is the relevant part of `setup.log` in my case :  

```
2023-05-05 18:13:51,825 | ERROR | F:\automatic\installer.py | Error running git: None / submodule --quiet update --init --recursive
2023-05-05 18:13:51,827 | DEBUG | F:\automatic\installer.py | Git output: error: invalid path 'RuntimeError:-"upsample_nearest2d_channels_last"-not-implemented-for-'Half'.md'
fatal: Unable to checkout '6ace793c822fb74c897daba2529479ff1906227c' in submodule path 'wiki/origin-wiki'
fatal: Failed to recurse into submodule path 'wiki'
2023-05-05 18:13:51,827 | INFO | F:\automatic\installer.py | Updating submodules
```

**Comment by ke1ne** [comment]
Getting this too. Setup.log:
```
 7f17a980b920696963aa79ef45b16ecf68ddec87 wiki (heads/master)
2023-05-05 19:37:34,245 | ERROR | e:\.ai\automatic\installer.py | Error running git: None / submodule --quiet update --init --recursive
2023-05-05 19:37:34,247 | DEBUG | e:\.ai\automatic\installer.py | Git output: error: invalid path 'RuntimeError:-"upsample_nearest2d_channels_last"-not-implemented-for-'Half'.md'
fatal: Unable to checkout '6ace793c822fb74c897daba2529479ff1906227c' in submodule path 'wiki/origin-wiki'
fatal: Failed to recurse into submodule path 'wiki'
```

**Comment by vladmandic** [comment]
that is different, somebody uploaded a badly named file to A1111 wiki and my repo keeps a copy of that WIKI:

> "upsample_nearest2d_channels_last"-not-implemented-for-'Half'.md

I'll eventually remove that copy completely

**Comment by vladmandic** [comment]
closing as no info provided by author. if issue is updated, i'll reopen it.

**Comment by Danamir** [comment]
FYI I did not have the problem anymore with the latest updates.
