### ISSUE TITLE
[Issue]: Inspiration extension runtime error 

### ISSUE THREAD

**Issue by jsmile** [vladmandic/automatic#774]
### Issue Description

I install inspiration extension successfully.
I unziped the file to /extections/stable-diffusion-webui-inspiration.
And I push 'Get inspiration' button and can show images for inspiration. 
But I click a image among them, then shows error message.

cmd console says 

Traceback (most recent call last):
  File "F:\AI\Vlad1111\automatic\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "F:\AI\Vlad1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "F:\AI\Vlad1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1133, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "F:\AI\Vlad1111\automatic\venv\lib\site-packages\gradio\blocks.py", line 1120, in validate_inputs
    raise ValueError(
ValueError: An event handler (select_click) didn't receive enough input values (needed: 2, got: 1).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [textbox, state]
Received inputs:
    ["NaN"]

How can I fix this error ? 

![inspiration error](https://user-images.githubusercontent.com/5867997/236530659-8615cc89-966e-489e-a4bf-ba8f765f8c30.PNG)

### Version Platform Description

Windows 10 pro.
Python version :  3.10.10
Version: 2166b4de Tue May 2 09:56:33 2023 -0400
Torch 2.0.0+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce GTX 1070 Ti VRAM 8192 Arch (6, 1) Cores 19

**Comment by vladmandic** [comment]
i'm using inspiration extension extensively and i cannot reproduce.

**Comment by vladmandic** [comment]
inspiration extension was recently updated, can you try and post update here?

**Comment by vladmandic** [comment]
any updates?

**Comment by jsmile** [comment]
Yes, of cause.
I remove the old one and reinstall inspiration extension yesterday.
I wrote my error again on issue board. 
https://github.com/yfszzx/stable-diffusion-webui-inspiration/issues/37

What is my ploblem ?
What should I do ?

**Comment by vladmandic** [comment]
i've traced the problem and provided information in the upstream ticket you've created. this is clearly a bug in the extension itself.
