### ISSUE TITLE
[Issue]: The new checkpoint listing in X/Y/Z Plot acts strangely

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#775]
### Issue Description

In addition to the thread here -> https://github.com/vladmandic/automatic/discussions/618

Summary:
When generating an X/Y/Z Plot with many checkpoints, it seems that either selected checkpoints are not used or randomly others, that where not selected.
Till now I haven't found out if this occurs always or is just sporadic, but I will further test it to maybe gather more informations.

### Version Platform Description

Win10, Firefox 106
Version: 22090d7b Thu May 4 06:53:01 2023 -0400

**Comment by vladmandic** [comment]
duplicate #778

**Comment by Woisek** [comment]
> duplicate #778

??? What does that mean?

**Comment by DrJKL** [comment]
It means that the same issue was reported separately and that follow-up will happen on that issue thread.

**Comment by Woisek** [comment]
But you told me I should open this as issue so you don't lose it ... 🙄


>vladmandic
May 5, 2023
Maintainer
>Please create issue with this information so it doesn't fall of my radar.

**Comment by vladmandic** [comment]
I did, but I just clicked transfer so it ended up with both.
It's the same thing, so I closed one.

**Comment by Woisek** [comment]
Ah, OK ... didn't noticed that, sorry. 😊
