### ISSUE TITLE
[Issue] setting "inpaint area" to "only masked" upscales the output image

### ISSUE THREAD

**Issue by crazygonuts** [vladmandic/automatic#780]
### Issue Description

is it intended that setting the inpaint area to "only masked" would change the output size of the final image?  my image is set to 1536x1680 but if I use "only masked" the output image is 2304x2520, 1.5x the size in the configuration

**Comment by anapnoe** [comment]
can you test this version most of the UI related issues have been fixed but can be applied yet to this fork work in progress it would be helpful to know that this is already taken care for the SD.Next version we are working on
https://github.com/anapnoe/stable-diffusion-webui-ux

**Comment by crazygonuts** [comment]
I was unable to reproduce this bug on either anapnoe or vladmandic today
