### ISSUE TITLE
[Issue]: De-selecting all Samplers except one never removes PLMS and UniPC from the drop-down list.

### ISSUE THREAD

**Issue by chmatse** [vladmandic/automatic#784]
### Issue Description

As written in the subject: Disable any Sampler in the Settings except for example **Euler a**, Save Settings, restart manually and afterwards the Dropdown list still contains [Euler a, PLMS, UniPC] **_+ (while writing this, found another Bug with DPM++ SDE (see below))_**

Here what i did:

- Complete fresh install of the webui:
```powershell
git clone https://github.com/vladmandic/automatic debugvlad
cd debugvlad
.\webui.bat     # Started a few times until no package needed to be installed anymore
```
- Went to `Settings -> Sampler Parameters`
- Under `Show samplers in user interface` Disabled all Samplers except `Euler a`
![Selected_Sampler](https://user-images.githubusercontent.com/6755463/236610845-485b734f-28f9-423f-bc07-d7f4194989ce.jpg)
- Clicked `Apply Settings` and then manually restarted `Ctrl-C -> J -> .\webui.bat`
- After the Server is started, the sampler Dropdown list still shows `PLMS` and `UniPC` **AND** `DPM++ SDE`. 
- I first thought i missed DPM++ SDE but you can reproduce it. Remove `config.json`, start Server, de-select all Samplers and after restart DPM++ SDE is in the List. If you go to Settings DPM++ SDE is checkmarked (hence why i thought i did miss it). If you then deselect it and restart it again, this "problem" is gone forever. Which means, even if you select ALL Samplers, restart Deselect All except Euler a, the DPM++ SDE never re-appears in the list again, only PLMS and UniPC. But if you remove config.json you can reproduce that DPM++ SDE Problem once again!
- So beside the `DPM++ SDE` Problem above, if you also deselect that and restart, in the settings only `Euler a` is selected but the dropdown list shows `Euler a`, `PLMS` and `UniPC`
![Sampler_list](https://user-images.githubusercontent.com/6755463/236611626-ebccaa09-b328-48dd-b01a-bd2b12167959.jpg)

### Version Platform Description

* Testing on Windows 10, with all actual updates installed
* The Environment:
```powershell
Using VENV: D:\AI\debugvlad\venv
09:55:23-332968 INFO     Starting SD.Next
09:55:23-332968 INFO     Python 3.10.11 on Windows
09:55:23-649192 INFO     Version: f6898c9a Fri May 5 13:40:53 2023 -0400
09:55:24-033762 INFO     Setting environment tuning
09:55:24-033762 INFO     nVidia CUDA toolkit detected
09:55:25-896516 INFO     Torch 2.0.1+cu118
09:55:25-912112 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
09:55:25-912112 INFO     Torch detected GPU: NVIDIA GeForce GTX 1080 Ti VRAM 11264 Arch (6, 1) Cores 28
```
* As mentioned above, this was a complete fresh checkout with even freshly downloaded checkpoint file.
* I'm running everything inside a miniconda python environment.

**Comment by vladmandic** [comment]
this is by design to allow app not to run into "impossible" configuration.
not sure why do you believe this is an issue? its a valid question for sure, but an issue?

**Comment by chmatse** [comment]
Thank you vladmandic for taking time to give me a response.

The issue i have is, that i have a setting `Show samplers in user interface` where the description suggests, that i should be able to select/deselect any sampler i like or dislike. But that is not true as 10% of the de-/selectable options do not work (PLMS and UniPC). Because even if i have selected ALL samplers and then want - for whatever reason - deselect PLMS and UniPC, deselecting these two samplers have no impact.

So this - for my understanding - has nothing to do with an impossible configuration as we still would have 18 samplers.

If it does not matter if i select or deselect PLMS and UniPC, then either there is - for my understanding - a bug in the GUI which prevents me from de-selecting those two Samplers OR they should never be deselectable (even if enough samplers are selected) and therefore should be removed from the list.

**Comment by vladmandic** [comment]
PLMS is internally referenced by code in many places as it's the original sampler in SD, it should never be disabled. UniPC could be disabled, but then I'd have to implement a fallback function to find first available. Definitely doable, but is it really a high priority issue? No. It's a choice I made, it's not a bug in the UI. If you want to open a low priority feature request to be able to disable UniPC, you can do that, but again, is it worth the effort?

**Comment by chmatse** [comment]
Thank you for the explanation. You're right. This is absolutetly nothing with any kind of importance. For me it looked just wrong, because when i have a list of stuff to enable/disable i'm used to be able to enable/disable everything on that list :-) Since i know now that it is not a bug and since you explained the reason why it behaves like it behaves, i can live with that. And should anyone else stumble across it, it is now documented here. So again, thank you very much for the answer and keep up the great work!
