### ISSUE TITLE
[Bug]: Torch is not able to use GPU

### ISSUE THREAD

**Issue by Raz0rStorm** [vladmandic/automatic#79]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

After installing the requirements, I run webui.bat and got the error

### Steps to reproduce the problem

1. Install requirements
2. Run webui.bat
3. error

### What should have happened?

It should go through, I encoutered no such error when using the vanilla webui

### Commit where the problem happens

ffc54d0

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
No
```

### List of extensions

No

### Console logs

```Shell
venv "D:\Stable_diffusion\automatic\venv\Scripts\Python.exe"
Traceback (most recent call last):
  File "D:\Stable_diffusion\automatic\launch.py", line 310, in <module>
    prepare_environment()
  File "D:\Stable_diffusion\automatic\launch.py", line 247, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "D:\Stable_diffusion\automatic\launch.py", line 108, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "D:\Stable_diffusion\automatic\launch.py", line 84, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "D:\Stable_diffusion\automatic\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check
Press any key to continue . . .
```

**Comment by JoBilert** [comment]
You can solve this by manually reinstalling the proper PyTorch version from the [PyTorch-Website](https://pytorch.org/get-started/locally/).

Make sure to adapt the command to use your local venv. In my example, I had to change it from:

`pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

to 

` .\venv\Scripts\Python.exe -m pip install --upgrade --force-reinstall torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118`

After that I get a **numpy** version error, but webui.bat seems to run fine.

**Comment by AceroMagico** [comment]
To eleminate the numpy (or any other lib) version error you can do :
.\venv\Scripts\Python.exe -m pip install --force-reinstall --no-deps numpy

**Comment by Raz0rStorm** [comment]
All that got me through the first step of launch, thank you JoBilert and AceroMagico.
However, then I encoutered:
Fetching updates for Taming Transformers...
Checking out commit for Taming Transformers with hash: 3ba01b241669f5ade541ce990f7650a3b8f65318...
Traceback (most recent call last):
  File "D:\Stable_diffusion\automatic\launch.py", line 310, in <module>
    prepare_environment()
  File "D:\Stable_diffusion\automatic\launch.py", line 275, in prepare_environment
    git_clone(taming_transformers_repo, repo_dir('taming-transformers'), "Taming Transformers", taming_transformers_commit_hash)
  File "D:\Stable_diffusion\automatic\launch.py", line 135, in git_clone
    run(f'"{git}" -C "{dir}" checkout {commithash}', f"Checking out commit for {name} with hash: {commithash}...", f"Couldn't checkout commit {commithash} for {name}")
  File "D:\Stable_diffusion\automatic\launch.py", line 84, in run
    raise RuntimeError(message)
RuntimeError: Couldn't checkout commit 3ba01b241669f5ade541ce990f7650a3b8f65318 for Taming Transformers.
Command: "git" -C "D:\Stable_diffusion\automatic\repositories\taming-transformers" checkout 3ba01b241669f5ade541ce990f7650a3b8f65318
Error code: 128
stdout: <empty>
stderr: fatal: reference is not a tree: 3ba01b241669f5ade541ce990f7650a3b8f65318
this is strange, because the latest hash should be 3ba01b2
Does anyone know how to solve this?

**Comment by AceroMagico** [comment]
If you have the folder `taming-transformers` in `D:\Stable_diffusion\automatic\repositories` you can try to go in folder with a cmd shell and do an update to last Version:

git checkout master

this are other useful commands:

Current Version log commit checkout number
rem git log -1

rem All Previews Versions Updates log commit hash (press enter for more)
git log

rem To revert to Preview Version paste a commit checkout number after git checkout
git checkout XXXXXXXX

If I make `git log -1` (Current Version log commit checkout number)  I take :
commit 3ba01b241669f5ade541ce990f7650a3b8f65318 (HEAD, origin/master, origin/HEAD, master)
Merge: 2426893 9e9981c
Author: Robin Rombach <robin.rombach@gmail.com>
Date:   Mon Nov 7 21:00:25 2022 +0100

    Merge pull request #190 from carmocca/patch-1

    Use compatible import

**Comment by vladmandic** [comment]
See #92. Work is in progress, in the meantime closing this as duplicate.
