### ISSUE TITLE
[Issue]: Tunnel instantly being killed on startup

### ISSUE THREAD

**Issue by AI-Casanova** [vladmandic/automatic#792]
### Issue Description

After commit 5d8c787a7bee2a5ac0ae5e3ee91fe9c6e371bfa2 , the instant the server fully loads, it kills the tunnel and exits.

`2023-05-06 20:07:13,525 | INFO | /content/gdrive/MyDrive/vladmandic/sd/automatic/webui.py | Startup time: 48.0s (torch=8.8s gradio=2.4s libraries=1.2s models=2.3s codeformer=0.1s scripts=12.5s upscalers=0.8s vae=0.2s ui=9.2s start=4.7s scripts app_started_callback=0.1s checkpoint=5.7s)
Killing tunnel 127.0.0.1:7860 <> https://932adcd25ab4e3846b.gradio.live/`

### Version Platform Description

Google Colab
Chrome
Commit 5d8c787a7bee2a5ac0ae5e3ee91fe9c6e371bfa2 +

**Comment by AI-Casanova** [comment]
Reverting https://github.com/vladmandic/automatic/blob/22e588091376a458ae529d18c5ffaee5f0dcaa1b/webui.py#L267 to the older code fixes the issue for me. Not sure why the new system doesn't seem to work, perhaps only for Colab?

**Comment by vladmandic** [comment]
i'm assuming you're using `--share` option? and how are you starting the app? both are relevant and specific to this issue, but not provided.

one major difference between two commits is that main loop that keeps gradio open is no longer in `webui`, its in `launch`.
so any workflows should always start with launch - starting with `webui` directly is not a valid startup.

**Comment by AI-Casanova** [comment]
My startup code is
`webui.py --no-download --share --disable-safe-unpickle --ckpt "$Path_to_MODEL"  $auth --disable-console-progressbars`

The loop moving to launch.py makes perfect sense. 

Unfortunately that introduces a new problem, as launch.py seems to hang on Colab, see also https://github.com/vladmandic/automatic/discussions/81#discussioncomment-5826480

**Comment by vladmandic** [comment]
there is a lot in that thread, so not sure what's the current status of that "hang".
you can try running launch with `--debug` flag so it outputs more info to console and post last few lines before hang here?

**Comment by AI-Casanova** [comment]
The "hang" is 5+ minutes of this
![ss](https://user-images.githubusercontent.com/54461896/236854284-8d6e60d9-258e-4e1a-b2b8-073c19be0150.png)

Just remembered though that Colab has been having git trouble since upgrading to python 3.10 (got pull works, got status for some reason doesn't)

`--skip-git` seems to fix my problem, and returns a stable UI

I'll close this, and perhaps open an issue over at colabtools
