### ISSUE TITLE
[Issue]: Inpainting masked area only is brightening the entire image (SOLVED, CHROME CLIPBOARD ISSUE)

### ISSUE THREAD

**Issue by scpedicini** [vladmandic/automatic#793]
### Issue Description

For some reason, when running inpaint on a masked area when I compare it to the original picture. The entire image has had its colors very slightly changed, but enough to be noticable.

![CleanShot 2023-05-06 at 15 53 03@2x](https://user-images.githubusercontent.com/2040540/236646207-e30e8f45-1c0f-4ef7-9dc7-193383f0c8e5.jpg)

I've attached full size images of before and after, you can see that outside the mask it is a lighter scale of brown (very easy to see when using layers in Photoshop to compare back and forth).

Original:
![original](https://user-images.githubusercontent.com/2040540/236646299-16e21ccf-56aa-4395-8ea3-ac14fce0b772.png)

After inpaint:
![colors modified](https://user-images.githubusercontent.com/2040540/236646306-fc1fea9b-efc1-4fe8-ab52-79db53c11942.png)

### Tests

I have tried:
- a complete reset 
- simplify prompt (no embeddings, etc)
- multiple models (revAnimated, 526, realisticVision)
- Setting SD VAE from Automatic to None

### Conclusion

I was under the impression that inpainting the Masked area only would make zero changes to the original image outside of the masked area itself.

### Version Platform Description

5:49:15-533575 INFO     Version: 82d7b45c Mon Apr 24 16:54:12 2023 -0400
15:49:15-783156 INFO     Latest published version: 22e588091376a458ae529d18c5ffaee5f0dcaa1b 2023-05-06T12:51:23Z

**Comment by scpedicini** [comment]
HOLY SH## **I figured it out.**

![CleanShot 2023-05-06 at 16 14 44@2x](https://user-images.githubusercontent.com/2040540/236646812-71f1d4af-9fb8-4d94-b8de-3f55c7fcfd30.jpg)

When I went and grabbed the actual JPG output file that was created in my `output` folder, it did not have this color alteration issue. It's only if I right-click Copy Image and paste it into Photoshop.

**Comment by vladmandic** [comment]
Oh, that is soo random!
Glad you figured it out...
