### ISSUE TITLE
[Feature]: Different notification for errors.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#796]
### Feature description

Now that we've got a notification for generation completion, I wonder if it would be possible for a notification on failure.

This is like suuuper low priority, just a pipe-dream/wish-list kinda thang! ;-)

### Version Platform Description

n/a

**Comment by vladmandic** [comment]
can you give me an example of such error?
the thing is, in normal operation, there should be no "normal" errors - any error is pretty much an exception handler, and those cannot be used to trigger client-side notifications.

**Comment by brknsoul** [comment]
Out of memory errors, for example.

**Comment by vladmandic** [comment]
yeah, thats an exception, not a error that can be fixed or passed as notificaiton.

**Comment by brknsoul** [comment]
Okey doke. Thanks for looking into it. You can close this as 'not planned', if you like.

Thanks for being awesome! :-)

**Comment by BinaryQuantumSoul** [comment]
> can you give me an example of such error?
> the thing is, in normal operation, there should be no "normal" errors - any error is pretty much an exception handler, and those cannot be used to trigger client-side notifications.

Btw why can't them be used to trigger notifications? Since they "trigger" the error text output?

**Comment by vladmandic** [comment]
> Btw why can't them be used to trigger notifications? Since they "trigger" the error text output?

You're thinking of the normal workflow. First, in any backend -> frontend, its non-trivial for backend to send notifications directly as typically front-end has to request things. Its possible with advanced JS code, but - here we don't have that luxury as Gradio hides that.

And with Gradio only way to interact with Gradio is via Gradio controls. E.g., I cannot send anything to UI unless you clicked on Gradio button.
If you wish to have Gradio button in UI "view recent exceptions", that is possible, but that's just silly.
