### ISSUE TITLE
[Feature]: Support swapping axes with string and list items

### ISSUE THREAD

**Issue by horribleCodes** [vladmandic/automatic#797]
### Issue Description

When using one of the `Swap axes` values with one of the axes using `Checkpoint name` and the other any comma-separated textfield, the values of the two swapped axes will be empty. When changing the axis type from something else back to the previous type, the values will appear again. I assume this has something to do with #778.

To recreate:
1. In the X/Y/Z plot settings, pick `Checkpoint name` and some other type that uses a comma-separated list, for example `Seed`.
2. Populate the axes with values.
3. Swap the two axes with the according action below. *The values will now be empty*.
4. Change the type of the `Checkpoint name` axis to something else and back to ``Checkpoint name`. *The values from step 2 are now back.*

### Version Platform Description

Version: Version: 22e58809 Sat May 6 08:51:23 2023 -0400
OS: Windows 11
Browser: Brave

**Comment by vladmandic** [comment]
closing in favor of #778
