### ISSUE TITLE
[Issue]: Access denied

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#799]
### Issue Description

I'm currently train a TI and now two times I get a access denied on a preview image:

Training textual inversion step 149 loss: 0.00463 lr: 0.00100:   50% ----- ----- 50/101  [ 0:01:18 < 0:01:07 , 1 it/s ]12:31:04-985609 ERROR    embedding train: PermissionError
Training textual inversion step 149 loss: 0.00463 lr: 0.00100: ┌─────────────────────────────────────────  50%  Traceback -----(most recent call last)  -----──────────────────────────────────────── ─┐50/101
 │[  I:\Super SD 2.0\automatic\modules\textual_inversion\textual_inversion.py0:01:19: <578  in 0:01:07train_embedding ,                     1 it/s ] │
│                                                                                                                     │
│   577 │   │   │   │   │                                                                                             │
│ > 578 │   │   │   │   │   last_saved_image, _last_text_info = images.save_image(image, images_                      │
│   579 │   │   │   │   │   last_saved_image += f", prompt: {preview_text}"                                           │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\modules\images.py:597 in save_image                                                       │
│                                                                                                                     │
│   596 │   │   fullfn = params.filename                                                                              │
│ > 597 │   _atomically_save_image(image, fullfn_without_extension, extension)                                        │
│   598                                                                                                               │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\modules\images.py:589 in _atomically_save_image                                           │
│                                                                                                                     │
│   588 │   │   # atomically rename the file with correct extension                                                   │
│ > 589 │   │   os.replace(temp_file_path, filename_without_extension + extension)                                    │
│   590                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
PermissionError: [WinError 5] Zugriff verweigert: 'textual_inversion\\LucindaBunker\\images\\LucindaBunker-150.tmp' ->
'textual_inversion\\LucindaBunker\\images\\LucindaBunker-150.png'
Training textual inversion step 149 loss: 0.00463 lr: 0.00100:   50% ----- ----- 50/101  [ 0:01:19 < 0:01:07 , 1 it/s ]
12:31:05-218020 INFO     Applying scaled dot product cross attention optimization

This was also once happening when doing a X/Y/Z Plot, but then I thought it's just a hiccup of some sort. But now, twice while training ... that must be something serious. 😐
Please look into it. 

### Version Platform Description

Win10, Firefox 106
Version: 22e58809 Sat May 6 08:51:23 2023 -0400

**Comment by vladmandic** [comment]
i've modifed how temp files are handled, this should address issue on windows where os does not release handle in time so next operation fails with access denied (due to file-in-use).

upgrade and test.
if issue persists, update here and i'll reopen.

**Comment by Woisek** [comment]
Alright, thanks! Will update and observe. 👍
