### ISSUE TITLE
[Feature]: Styles viewer/editor, Notes

### ISSUE THREAD

**Issue by mef0** [vladmandic/automatic#800]
### Feature description

Could you make a right click on a style to open a window where you can view the content of the style and edit it. And it would be ideal if in this pop-up editor you could also change the order of styles.

Another thing missing as we use the SD is some kind of container/notes. Often I have to copy some promt to notepad to quickly pick it up from there. 

I see an implementation like this --> that when you select text in the notepad window and press a new button, this text is copied or cut into this container

**Comment by vladmandic** [comment]
new styles manager is introduced in lastest sdnext update.
