### ISSUE TITLE
[Feature]: New Minimum for img2img noise multipler

### ISSUE THREAD

**Issue by SadisticLeprechaun** [vladmandic/automatic#803]
### Feature description

noise multiplier for im2img gets more photorealism if it can go all the way to 0 instead of 0.5, right now I do some f12 trick and change the script temporarily to min 0, using 0.2 makes the photos look more real but the current minimum is 0.5, this would be a wonderful tweak.

Thank you very much.

### Version Platform Description

Win 11, 3070ti 8GB, i7 12700 5ghz
10:10:40-216318 INFO     Latest published version: 22e588091376a458ae529d18c5ffaee5f0dcaa1b 2023-05-06T12:51:23Z

**Comment by vladmandic** [comment]
done.

**Comment by SadisticLeprechaun** [comment]
Amazing, thanks!
