### ISSUE TITLE
[Issue]: Image viewer not showing correct generation metadata 

### ISSUE THREAD

**Issue by DrMeo** [vladmandic/automatic#805]
### Issue Description

After generation multiple images the image viewer does not update to the proper metadata after scrolling through full screen image viewer images and closing the full view. 

Steps to reproduce: 
1: Generate multiple images on txt2image tab
2: click on the generated images to bring up the full screen viewer
3: navigate with arrow keys through the images to the image you want the generation info on
4: close the full viewer. _You will see the filmstrip of images having the image you stopped on highlighted in yellow._
5: take note of the seed number
6: _click on the highlighted image in the filmstrip_ 
7: take note of the **proper** seed number, usually +1/-1 from what it was showing when the image viewer stopped

Issue persists even after disabling all "extra" extensions in webui. 

This is a major annoyance if you want to explore seeds before using hires fix, as unless you remember ( or even know) to click on the highlighted image in the filmstrip you will get a prior or further image's seed number and will not generate the desired image with highres fix enabled. It will be a different image from the prior image set.

### Version Platform Description

Noticed on Version: c470f39 Thu May 4 16:55:41 2023 -0400

Still present on  Version: 22e58809 Sat May 6 08:51:23 2023 -0400

Windows 11
Chrome browser 

Extra extensions: 
OpenOutpaint
tagcomplete
webui-state

**Comment by lbeltrame** [comment]
FTR, this issue exists also in the upstream webui. And it has been present for quite a while. It looks like some off-by-one error somewhere.

**Comment by anapnoe** [comment]
This has been fixed wait a bit for the SD.Next release

**Comment by anapnoe** [comment]
javascript/generationParams.js
replace this function with the code below
the issue has been fixed for SD.Next release
```
function attachGalleryListeners(tab_name) {
  var gallery = gradioApp().querySelector("#" + tab_name + "_gallery");
  gallery?.addEventListener("click", () =>
    setTimeout(function () {
      gradioApp()
        .getElementById(tab_name + "_generation_info_button")
        ?.click();
    }, 500)
  );
  gallery?.addEventListener("keydown", (e) => {
    if (e.keyCode == 37 || e.keyCode == 39)
      // left or right arrow
      gradioApp()
        .getElementById(tab_name + "_generation_info_button")
        .click();
  });
  return gallery;
}
```

**Comment by vladmandic** [comment]
i've added this fix to master, closing the issue.
