### ISSUE TITLE
[Issue]: 4090, very slow speed

### ISSUE THREAD

**Issue by bbecausereasonss** [vladmandic/automatic#806]
### Issue Description

I get about 2.5x speed in Automatics, for some reason even Eulier normal size I'm generating only at 10.2 it/s... on a 4090

### Version Platform Description

latest chrome

**Comment by srcrist** [comment]
Not experiencing this issue on my 4090

![image](https://user-images.githubusercontent.com/29871690/236700460-56ba3c5c-f993-4dd2-a643-dcb370a7feed.png)

**Comment by vladmandic** [comment]
Author has provided no information.
No version and "latest chrome" is not platform details.
Not to mention that performance issues should be reporter using standardized built - in benchmark. You saying 10 it/s tells me nothing about conditions.

**Comment by rayminator2023** [comment]
make sure you have remove your old driver from your computer and reinstall video card driver use ddu uninstaller 
your driver is acting as your old card settings not the new card
