### ISSUE TITLE
[Issue]: Update breaks sd-webui-image-browser

### ISSUE THREAD

**Issue by tranzmatt** [vladmandic/automatic#808]
### Issue Description

Using the image-browser extension, when I click -> Image, or -> Text, the fields no longer correctly populate.  These still show up in the Negative Prompt window:

Steps: 40, Sampler: DPM++ 2S a Karras, CFG scale: 7, Seed: 724142464, Face restoration: CodeFormer, Size: 512x768, Model hash: ce91c1ec3c, Model: halcyon_v10, VAE: vae-ft-mse-840000-ema-pruned, Denoising strength: 0.5, Clip skip: 2,

### Version Platform Description

Linux 22.04 running 22e588091376a458ae529d18c5ffaee5f0dcaa1b

**Comment by AlUlkesh** [comment]
https://github.com/AlUlkesh/stable-diffusion-webui-images-browser/issues/162

**Comment by vladmandic** [comment]
i've tried image browser -> send to txt2img, img2img and extras and all work fine.
can you update and confim the issue.
any error messages in either console or browser console?

**Comment by Gouden89** [comment]
[https://ibb.co/YBvXGpy](url)
I have this issue with several pictures with the same prompts, other prompts work fine
