### ISSUE TITLE
[Extension]: Ultimate Upscale extension error channels mismatch

### ISSUE THREAD

**Issue by YKefasu** [vladmandic/automatic#809]
### Issue Description

Following Olivo Sarikas Tutorial on this video https://youtu.be/3z4MKUqFEUk
But i got ERROR
```
Canva size: 2368x3520
Image size: 1176x1760
Scale factor: 2
Upscaling iteration 1 with scale factor 2
Tile size: 1024x1536
Tiles amount: 9
Grid: 3x3
Redraw enabled: True
Seams fix mode: NONE
Loading model from cache: control_v11f1e_sd15_tile [a371b31b]
Loading preprocessor: tile_resample
preprocessor resolution = 64
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [01:17<00:00,  2.59s/it]
06:47:25-629574 ERROR    gradio call: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ C:\New folder\automatic\modules\call_queue.py:59 in f                                                                │
│                                                                                                                      │
│    58 │   │   │   │   pr.enable()                                                                                    │
│ ❱  59 │   │   │   res = list(func(*args, **kwargs))                                                                  │
│    60 │   │   │   if shared.cmd_opts.profile:                                                                        │
│                                                                                                                      │
│ C:\New folder\automatic\modules\call_queue.py:38 in f                                                                │
│                                                                                                                      │
│    37 │   │   │   try:                                                                                               │
│ ❱  38 │   │   │   │   res = func(*args, **kwargs)                                                                    │
│    39 │   │   │   │   progress.record_results(id_task, res)                                                          │
│                                                                                                                      │
│                                               ... 23 frames hidden ...                                               │
│                                                                                                                      │
│ C:\New folder\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward                               │
│                                                                                                                      │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                                               │
│ ❱  463 │   │   return self._conv_forward(input, self.weight, self.bias)                                              │
│    464                                                                                                               │
│                                                                                                                      │
│ C:\New folder\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:459 in _conv_forward                         │
│                                                                                                                      │
│    458 │   │   │   │   │   │   │   _pair(0), self.dilation, self.groups)                                             │
│ ❱  459 │   │   return F.conv2d(input, weight, bias, self.stride,                                                     │
│    460 │   │   │   │   │   │   self.padding, self.dilation, self.groups)                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 4, 192, 192] to have 3 channels, but got 4
channels instead
```

### Version Platform Description

06:27:14-131193 INFO     Python 3.10.8 on Windows
06:27:14-639594 INFO     Version: c470f399 Thu May 4 16:55:41 2023 -0400
06:27:15-092093 INFO     Latest published version: 22e588091376a458ae529d18c5ffaee5f0dcaa1b 2023-05-06T12:51:23Z
06:27:15-094100 INFO     Setting environment tuning
06:27:15-098093 INFO     nVidia CUDA toolkit detected
06:27:15-100593 INFO     Torch 2.0.0+cu118
06:27:15-102093 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
06:27:15-103593 INFO     Torch detected GPU: NVIDIA GeForce RTX 2060 VRAM 12288 Arch (7, 5) Cores 34

**Comment by vladmandic** [comment]
Can you describe the exact workflow leading to this instead of linking to video?

**Comment by iDeNoh** [comment]
> Can you describe the exact workflow leading to this instead of linking to video?

I actually have seen this recently, I have no idea how long it's been happening as I just noticed it the other day, but it's happened on my previous install and is still happening after a full erase and install of my Linux drive. It happens for me whenever I attempt to use ultimate SD upscale, and I've not had the same issue in base A1111

**Comment by YKefasu** [comment]
> Can you describe the exact workflow leading to this instead of linking to video?

using the exact workflow in the video, but only change img2img resolution. in base A1111 dont have the issue

**Comment by MaxJa4** [comment]
I watched that video too, although I use a different workflow for upscaling which yields better results for me.
Anyway, I tried to reproduce your issue and while doing that, I stumbled upon two oddities in your log / process.
1. Your tile size is not the typical 512x512 or 768x768 but 1024x1536
2. The shown progress bar in your log goes up to '30', which hints that your denoising strength might be set to '1' and your steps to '30', otherwise it e.g. would be '7' with a denoising strength of '0.25' and 25 steps.
-> Try using 512x512 or 768x768 as tile size in the Ultimate SD Upscale script and set your denoising strength to 0.2-0.3 (like suggested in the video)

I tried it both with the suggested values and with your values (high tile size and high denoising strength), both approaches worked for me though without the error. But maybe it's worth a try, just to be sure.

<details>
<summary>Specs</summary>

- Python 3.10.11 on Windows
- Version: 22e58809 Sat May 6 08:51:23 2023 -0400
- Torch 2.0.0+cu118
- Torch backend: nVidia CUDA 11.8 cuDNN 8700
- Torch detected GPU: NVIDIA GeForce RTX 4070 Ti VRAM 12282 Arch (8, 9) Cores 60

</details>

**Comment by vladmandic** [comment]
> using the exact workflow in the video, but only change img2img resolution. in base A1111 dont have the issue

i don't plan to watch a youtube video to figure out your workflow - when creating an issue, issue description must stand on its own. so please edit the issue add step-by-step instructions on the workflow you used to description.

**Comment by iDeNoh** [comment]
I found a workaround, if you set the default upscaler for image resize options to none it works fine.

**Comment by iDeNoh** [comment]
Found a workaround via the [Ultimate SD Upscale FAQ](https://github.com/Coyote-A/ultimate-upscale-for-automatic1111/wiki/FAQ#i-have-something-like-runtimeerror-given-groups1-weight-of-size-64-3-3-3-expected-input1-4-256-256-to-have-3-channels-but-got-4-channels-instead-error) 

Setting the default upscaler for img2img does indeed work.

**Comment by vladmandic** [comment]
@YKefasu can you confirm if solution from @iDeNoh is applicable?
