### ISSUE TITLE
[Issue]: Image Options Save a copy dont include this settings in the generation info

### ISSUE THREAD

**Issue by HariboApfel** [vladmandic/automatic#819]
### Issue Description

When generating with the options 
Save a copy of image before doing face restoration
Save a copy of image before applying highres fix
Save a copy of image before applying color correction to img2img results

the saved copys always have the same generation parameters. 

BUT,

they should have different parameters depending on the step the copy was saved after.

**Comment by vladmandic** [comment]
fixed.
