### ISSUE TITLE
[Feature]: Support multiple model locations

### ISSUE THREAD

**Issue by sdbds** [vladmandic/automatic#82]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What would your feature do ?

 load extra models form other path.
i think we dont want to copy more models in limit Disk space.

even extension...

### Proposed workflow

 load extra models form other path

**Comment by AceroMagico** [comment]
to avoid copying models you can use symlinks, this installs an extension for window explorer that makes it much easier to use symlinks
[symlinks linkshellextension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html)

this program on the other hand is able to copy folders while keeping the symlinks (if you make a normal copy of symlinks in window the originals are copied and not the symlinks):

[Fastcopy](https://fastcopy.jp/)

Remember in Fastcopy to make the setting:
`Main settings - Copy/Move options - Copy Junction/Symlink as Junction/Symlink (not target)`

this way for example you can have the models in a disk\folder you want, create the symlinks and put them in the models folder of automatic1111, then with Fastcopy copy them to the models folder of any app require them, for example automatic (this repo)

**Comment by vladmandic** [comment]
its in my backlog to add support for multiple folders for models.

**Comment by sdbds** [comment]
> to avoid copying models you can use symlinks, this installs an extension for window explorer that makes it much easier to use symlinks [symlinks linkshellextension](https://schinagl.priv.at/nt/hardlinkshellext/linkshellextension.html)
> 
> this program on the other hand is able to copy folders while keeping the symlinks (if you make a normal copy of symlinks in window the originals are copied and not the symlinks):
> 
> [Fastcopy](https://fastcopy.jp/)
> 
> Remember in Fastcopy to make the setting: `Main settings - Copy/Move options - Copy Junction/Symlink as Junction/Symlink (not target)`
> 
> this way for example you can have the models in a harddisk:\folder you want, create the symlinks and put them in the models folder of automatic1111, then with Fastcopy copy them to the models folder of any app require them, for example automatic (this repo)
> 
> Of course you can not install Fastcopy and redo the symlinks each time, but having many installations such as auto1111, this, comfyui, invokeai etc it is more convenient to copy them once you have done them in one of them. Especially if of all the models you have you have made a tighter selection with symlinks.
> 
> And this is another possible use of symlinks, from your harddisk:\folder you make a selection of only those you need for a particular job, create symlinks of those in a "Job1" folder, and then copy the contents of "Job1" folder with Fastcopy to the Models folder you want.

thank you！I have used symbolic links, but they become invalid after git pull unless I create an additional layer of folders. I will try using FastCopy and hope it works better.

**Comment by vladmandic** [comment]
i took a look at this and it would be feasible to add it to core repo, but the big issue is that a lot of existing extensions expect a single folder as a string value, so this would either break quite a few extensions or those extensions would not be able to access models in secondary locations.

**Comment by vladmandic** [comment]
because of compatibility with extensions, i have to mark this as "wont fix", sorry.
