### ISSUE TITLE
[Issue]: UI tabs change position 

### ISSUE THREAD

**Issue by tripletto** [vladmandic/automatic#832]
### Issue Description

UI tabs like From Text, From Image, [...], Settings etc. behave erratically. When I am in "From Text" for example and I click "Settings", "Settings" becomes the 2nd item from left, instead of staying on the right side (2nd item from right). When I go back to "From Text", "Settings" stays as 2nd item from left.

Only reloading the browser restores the native order. Other tabs switch positions as well. 

Setting the "UI tabs order" didn't make a difference.

<pre>Traceback (most recent call last):
  File "c:\stable-diffusion-webui-vlad\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "c:\stable-diffusion-webui-vlad\venv\lib\site-packages\gradio\blocks.py", line 1297, in process_api
    inputs = self.preprocess_data(fn_index, inputs, state)
  File "c:\stable-diffusion-webui-vlad\venv\lib\site-packages\gradio\blocks.py", line 1133, in preprocess_data
    self.validate_inputs(fn_index, inputs)
  File "c:\stable-diffusion-webui-vlad\venv\lib\site-packages\gradio\blocks.py", line 1120, in validate_inputs
    raise ValueError(
ValueError: An event handler (update_ranking) didn't receive enough input values (needed: 4, got: 0).
Check if the event handler calls a Javascript function, and make sure its return value is correct.
Wanted inputs:
    [textbox, textbox, radio, textbox]
Received inputs:
    []</pre>

### Version Platform Description

Version: d7fdc594 Tue May 9 10:41:40 2023 -0400
Deactivated all extra extensions

On Windows 10, Chrome and Firefox tested.

**Comment by reznyt** [comment]
I noticed this as well, just before I lost the ability to launch. Same version as #831.

**Comment by vladmandic** [comment]
fixed.
