### ISSUE TITLE
[Issue]:  Cannot use From Image (img2img) at all.

### ISSUE THREAD

**Issue by ultimaKV** [vladmandic/automatic#833]
### Issue Description

txt2img working fine without problem. but From Image, it can't generate any image from source **except** the logo of theme. I can only send the logo image to From Image and made something like change color the logo. The cmd show progress normally and the result was delivered to output folder.

![image](https://github.com/vladmandic/automatic/assets/133022290/43a1af00-0f9c-450a-8481-26a148d8660f)

![00002-3692609159-change to green color](https://github.com/vladmandic/automatic/assets/133022290/6837df77-7866-4d3b-9b92-9fb6c96d67e8)

![00005-2470812255-(change to Blue_1 3)](https://github.com/vladmandic/automatic/assets/133022290/98ff80fc-a9c4-44f8-85cd-cf0541b0e036)

Any image I use other than triangle logo can't be generated at all whether it come from txt2img ,random google image or just screen capture and ctrl+v or choose image manually on computer. CMD won't show progress or any error warning texts whatsoever and it freezed in FromImage tab. (I can go to the txt2img tab and generate image normally)

Use after clean install. Did not touch any settings, No arguments added, No extension used or added, No LoRA LyCORIS TI Hypernetworks and VAE used, Checkpoint is SD1.5 that downloaded from this installer. (I've also tried on other checkpoints but also no luck). I've also try clean install several times in the past few days and this bug was always the same. I'm not a developer so I don't really know what exactly happened.

Ps. I have no issues on A1111 (old stable commited. manually upgraded to Torch 2.0, installed ToMe, used SDP optimization, no xformers). Just want to try another webui

### Version Platform Description

-just made a clean install, commit d7fdc594 (actually, commits like 3 days before was also have the same problem)
-Version: d7fdc594 Tue May 9 10:41:40 2023 -0400
hash: https://github.com/vladmandic/automatic/commit/d7fdc5944c637d564afb2d22bdcc14d40239d72f

OS : Chrome and Microsoft Edge

Python 3.10.6 on Windows 
-installed CUDA 12.1

Torch 2.0.1+cu118
Torch backend: nVidia CUDA 11.8 cuDNN 8700
Torch detected GPU: NVIDIA GeForce RTX 3080 Ti VRAM 12288 Arch (8, 6) Cores 80
cpu: 12th Gen Intel(R) Core(TM) i9-12900   2.40 GHz
system: 
Edition	Windows 11 Pro
Version	22H2
OS build	22624.1690

**Comment by AlUlkesh** [comment]
@ultimaKV Anything on the javascript console?

**Comment by ultimaKV** [comment]
> @ultimaKV Anything on the javascript console?

not sure what's javascript console (i'm an ordinary user). If you mean the cmd console of webui.bat, then nothing shows up at all like not registering my 'generate' action. The webui generate button changed tho but not working. It works only with the logo lol.

**Comment by ultimaKV** [comment]
> > not sure what's javascript console (i'm an ordinary user). If you mean the cmd console of webui.bat, then nothing shows up at all like not registering my 'generate' action.
> 
> No, that's different. In Chrome press F12 and then head over to Console: ![image](https://user-images.githubusercontent.com/99896447/237179997-bdb05d20-931c-4a18-b10c-b2467e397936.png)

@AlUlkesh  sorry for the late reply.
Chrome (and edge is the same)
![image](https://github.com/vladmandic/automatic/assets/133022290/c74fc7d3-0408-4a8c-9bad-c3b768a9ffdb)

look like this at the start webui. When generated, nothing happens to console both txt2img and img2img. and only txt2img works.

**Comment by vladmandic** [comment]
`api-logo.svg` error is irrelevant here, its listed as a separate issue, mostly cosmetic.
lets go back to basics - how are you trying to use img2img? step by step, be detailed.

**Comment by ultimaKV** [comment]
@vladmandic 
It's really a weird problem as this should not be happened... But it has anyway

I've just try clean installed again by deleted the previous attempt, entire automatic folder. (In drive C, ssd, window installation drive)

Doing clean installed by git bash and git clone command. After that, I just double clicked open webui.bat straight away.

After place some sd1.5 model in /models/Stable-diiffusion and wait for installation to finished, I have accessed this it on both Chrome and Edge as usual.

First, in the default tab, txt2img, I typed a positive prompt like 1 word such as sad and then just clicked generate straight away. The cmd webui.bat show progress bar. It was fast as it should be. The image of a sad girl was generated in less than a second.

Then, I send this image by ->Image button below generated image. It was sent successfully without problem. I used the same positive prompt, used a default sampling method and try some other methods. The results was freezed tab. No show error on cmd or progress at all. (Lastest log was image generation progress of txt2img)

I can still switched to txt2img tab and generate something there tho. Not the entire webui has freezed.

This made me so confused as it shouldn't have this silly bug when I can use A1111 freely with a lot of manually upgrade from old stable built (25 march commit) that was almost the same core of this webui (torch2.0, sdp optimizing), installed a lot of extensions, etc.

I haven't try other python version. But some people who use 3.10.6 have no issues with it  so in the end, I have no idea.

**Comment by vladmandic** [comment]
no need for reinstalls or changing python, lets figure this out.
just to confirm, you're saying that a simple workflow doesn't work?
1. in txt2img generate image
2. click `-> image`
3. click generate in img2img tab

can you run `webui --debug`, reproduce problem and upload log here?

**Comment by ultimaKV** [comment]
here,
==============================
Using VENV: C:\AI_Stable-Diffusion\automatic\venv
23:36:29-992748 INFO     Starting SD.Next
23:36:29-996775 INFO     Python 3.10.6 on Windows
23:36:30-035911 DEBUG    Git 2.40.1.windows.1
23:36:30-260858 INFO     Version: 5bd863f9 Tue May 9 14:08:57 2023 -0400
23:36:30-861324 INFO     Latest published version: aff2dcb625953fbffb8db272fe0e0e6e991ab52f 2023-05-11T16:08:38Z
23:36:30-866187 INFO     Setting environment tuning
23:36:30-869203 INFO     nVidia CUDA toolkit detected
23:36:31-099095 DEBUG    Package version found: torch 2.0.0+cu118
23:36:31-102607 DEBUG    Package version found: torchvision 0.15.1+cu118
23:36:31-105705 DEBUG    Package version found: torchaudio 2.0.1+cu118
23:36:33-424781 INFO     Torch 2.0.0+cu118
23:36:33-435854 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
23:36:33-437854 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 Ti VRAM 12288 Arch (8, 6) Cores 80
23:36:33-439354 DEBUG    Package version found: tensorflow 2.12.0
23:36:33-439854 INFO     Verifying requirements
23:36:33-441375 DEBUG    Package version found: addict 2.4.0
23:36:33-442379 DEBUG    Package version found: aenum 3.1.12
23:36:33-443455 DEBUG    Package version found: aiohttp 3.8.4
23:36:33-444455 DEBUG    Package version found: anyio 3.6.2
23:36:33-445955 DEBUG    Package version found: appdirs 1.4.4
23:36:33-446759 DEBUG    Package version found: astunparse 1.6.3
23:36:33-448220 DEBUG    Package version found: basicsr 1.4.2
23:36:33-449222 DEBUG    Package version found: bitsandbytes 0.38.1
23:36:33-450227 DEBUG    Package version found: blendmodes 2022
23:36:33-451454 DEBUG    Package version found: clean-fid 0.1.35
23:36:33-452459 DEBUG    Package version found: easydev 0.12.1
23:36:33-454295 DEBUG    Package version found: extcolors 1.0.0
23:36:33-455297 DEBUG    Package version found: facexlib 0.3.0
23:36:33-456305 DEBUG    Package version found: filetype 1.2.0
23:36:33-457305 DEBUG    Package version found: font-roboto 0.0.1
23:36:33-458305 DEBUG    Package version found: fonts 0.0.3
23:36:33-459305 DEBUG    Package version found: future 0.18.3
23:36:33-459805 DEBUG    Package version found: gdown 4.7.1
23:36:33-461325 DEBUG    Package version found: gfpgan 1.3.8
23:36:33-463061 DEBUG    Package version found: GitPython 3.1.31
23:36:33-463561 DEBUG    Package version found: httpcore 0.17.0
23:36:33-465375 DEBUG    Package version found: inflection 0.5.1
23:36:33-466885 DEBUG    Package version found: jsonmerge 1.9.0
23:36:33-468379 DEBUG    Package version found: kornia 0.6.12
23:36:33-469379 DEBUG    Package version found: lark 1.1.5
23:36:33-470885 DEBUG    Package version found: lmdb 1.4.1
23:36:33-472402 DEBUG    Package version found: lpips 0.1.4
23:36:33-473482 DEBUG    Package version found: numpy 1.23.5
23:36:33-474483 DEBUG    Package version found: omegaconf 2.3.0
23:36:33-475772 DEBUG    Package version found: open-clip-torch 2.19.0
23:36:33-476273 DEBUG    Package version found: opencv-contrib-python 4.7.0.72
23:36:33-477773 DEBUG    Package version found: piexif 1.1.3
23:36:33-478773 DEBUG    Package version found: Pillow 9.5.0
23:36:33-479827 DEBUG    Package version found: psutil 5.9.5
23:36:33-480832 DEBUG    Package version found: pyyaml 6.0
23:36:33-482774 DEBUG    Package version found: realesrgan 0.3.0
23:36:33-484340 DEBUG    Package version found: requests 2.30.0
23:36:33-485854 DEBUG    Package version found: resize-right 0.0.2
23:36:33-486854 DEBUG    Package version found: rich 13.3.5
23:36:33-488997 DEBUG    Package version found: safetensors 0.3.1
23:36:33-490033 DEBUG    Package version found: scipy 1.10.1
23:36:33-491555 DEBUG    Package version found: tb_nightly 2.14.0a20230509
23:36:33-492560 DEBUG    Package version found: toml 0.10.2
23:36:33-493576 DEBUG    Package version found: torchdiffeq 0.2.3
23:36:33-494576 DEBUG    Package version found: torchsde 0.2.5
23:36:33-495577 DEBUG    Package version found: voluptuous 0.13.1
23:36:33-497077 DEBUG    Package version found: yapf 0.33.0
23:36:33-500601 DEBUG    Package version found: scikit-image 0.20.0
23:36:33-501103 DEBUG    Package version found: tqdm 4.65.0
23:36:33-503021 DEBUG    Package version found: accelerate 0.18.0
23:36:33-504034 DEBUG    Package version found: opencv-python 4.7.0.72
23:36:33-505534 DEBUG    Package version found: diffusers 0.16.1
23:36:33-506534 DEBUG    Package version found: einops 0.4.1
23:36:33-507534 DEBUG    Package version found: gradio 3.28.1
23:36:33-509033 DEBUG    Package version found: numexpr 2.8.4
23:36:33-510033 DEBUG    Package version found: pandas 1.5.3
23:36:33-511039 DEBUG    Package version found: protobuf 3.20.3
23:36:33-511550 DEBUG    Package version found: pytorch_lightning 1.9.4
23:36:33-513070 DEBUG    Package version found: transformers 4.26.1
23:36:33-514075 DEBUG    Package version found: timm 0.6.13
23:36:33-515562 DEBUG    Package version found: tomesd 0.1.2
23:36:33-517056 DEBUG    Package version found: urllib3 1.26.15
23:36:33-554586 DEBUG    Repository update time: Wed May 10 01:08:57 2023
23:36:33-555587 DEBUG    Previous setup time: Wed May 10 04:26:31 2023
23:36:33-557587 DEBUG    Extension version: Wed May 10 04:17:31 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;a1111-sd-webui-lycoris
23:36:33-559087 DEBUG    Extension version: Wed May 10 04:17:32 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;clip-interrogator-ext
23:36:33-560087 DEBUG    Extension version: Wed May 10 04:17:32 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;LDSR
23:36:33-561614 DEBUG    Extension version: Wed May 10 04:17:32 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;Lora
23:36:33-563626 DEBUG    Extension version: Wed May 10 04:17:32 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;multidiffusion-upscaler-for-automatic1111
23:36:33-565683 DEBUG    Extension version: Wed May 10 04:04:05 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;prompt-bracket-checker
23:36:33-567156 DEBUG    Extension version: Wed May 10 04:17:46 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;ScuNET
23:36:33-569139 DEBUG    Extension version: Wed May 10 04:17:32 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;sd-dynamic-thresholding
23:36:33-570139 DEBUG    Extension version: Wed May 10 04:17:32 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;sd-extension-aesthetic-scorer
23:36:33-571666 DEBUG    Extension version: Wed May 10 04:17:32 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;sd-extension-steps-animation
23:36:33-574682 DEBUG    Extension version: Wed May 10 04:17:32 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;sd-extension-system-info
23:36:33-576182 DEBUG    Extension version: Wed May 10 04:17:32 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;sd-webui-controlnet
23:36:33-577682 DEBUG    Extension version: Wed May 10 04:17:32 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;sd-webui-model-converter
23:36:33-579682 DEBUG    Extension version: Wed May 10 04:17:32 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;seed_travel
23:36:33-581187 DEBUG    Extension version: Wed May 10 04:17:47 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;stable-diffusion-webui-images-browser
23:36:33-583728 DEBUG    Extension version: Wed May 10 04:17:32 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;stable-diffusion-webui-rembg
23:36:33-585241 DEBUG    Extension version: Wed May 10 04:17:46 2023
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin;SwinIR
23:36:33-587921 DEBUG    Latest extensions time: Wed May 10 04:17:48 2023
23:36:33-588924 DEBUG    Timestamps: version:1683655737 setup:1683667591 extension:1683667068
23:36:33-589923 INFO     No changes detected: Quick launch active
23:36:33-591443 INFO     Running extension preloading
23:36:33-592448 INFO     Server arguments: ['--debug']
23:36:33-593575 DEBUG    Starting WebUI
23:36:33-611634 DEBUG    Memory used: 0.34 total: 31.75 Collected 0
No module 'xformers'. Proceeding without it.
23:36:42-539509 INFO     Libraries loaded
23:36:42-542537 DEBUG    Entering WebUI
23:36:42-543047 DEBUG    Entering StartUI
23:36:42-544047 DEBUG    Entering Initialize
23:36:42-549048 INFO     Available models: C:\AI_Stable-Diffusion\automatic\models\Stable-diffusion 1
ControlNet v1.1.150
ControlNet v1.1.150
Image Browser: ImageReward is not installed, cannot be used.
23:36:45-649532 INFO     Loading theme: black-orange
23:36:45-653594 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\aspectRatioOverlay.js
23:36:45-654838 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\contextMenus.js
23:36:45-655338 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\dragdrop.js
23:36:45-657094 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\edit-attention.js
23:36:45-657893 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\extensions.js
23:36:45-659397 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\extraNetworks.js
23:36:45-659897 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\generationParams.js
23:36:45-661418 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\hints.js
23:36:45-661418 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\hires_fix.js
23:36:45-662946 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\imageMaskFix.js
23:36:45-663445 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\imageParams.js
23:36:45-664451 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\imageviewer.js
23:36:45-665452 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\notification.js
23:36:45-666454 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\progressbar.js
23:36:45-666454 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\textualInversion.js
23:36:45-668066 DEBUG    Loading JS script: C:\AI_Stable-Diffusion\automatic\javascript\ui.js
23:36:45-669487 DEBUG    Loading JS script:
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111\
                         javascript\bboxHint.js
23:36:45-671513 DEBUG    Loading JS script:
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin\prompt-bracket-checker\javascript\prompt-b
                         racket-checker.js
23:36:45-674033 DEBUG    Loading JS script:
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin\sd-extension-system-info\javascript\system
                         -info.js
23:36:45-677164 DEBUG    Loading JS script:
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin\sd-webui-controlnet\javascript\hints.js
23:36:45-678164 DEBUG    Loading JS script:
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin\stable-diffusion-webui-images-browser\java
                         script\image_browser.js
23:36:45-680164 DEBUG    Adding stylesheet: javascript/style.css
23:36:45-681684 DEBUG    Adding stylesheet:
                         C:\AI_Stable-Diffusion\automatic\extensions-builtin\stable-diffusion-webui-images-browser\styl
                         e.css
23:36:45-682690 DEBUG    Adding stylesheet: C:\AI_Stable-Diffusion\automatic\javascript\black-orange.css
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
23:36:46-548521 INFO     Local URL: http://127.0.0.1:7861/
23:36:46-549521 INFO     API Docs: http://127.0.0.1:7861/docs
23:36:46-550021 DEBUG    Gradio registered functions: 969
23:36:46-551553 INFO     Initializing middleware
23:36:46-596906 DEBUG    Load model: info=False dict=False
23:36:46-598175 WARNING  Default checkpoint not found: model.ckpt
23:36:46-599177 WARNING  Loading fallback checkpoint: camelliamix25DV2_v2.safetensors [ed4f26c284]
23:36:46-599679 DEBUG    Model unloaded: {'ram': {'used': 0.96, 'total': 31.75}, 'gpu': {'used': 1.17, 'total': 12.0},
                         'retries': 0, 'oom': 0}
23:36:46-628209 DEBUG    Setting CUDA parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
Loading weights: C:\AI_Stable-Diffusion\automatic\models\Stable-diffusion\camelliamix25DV2_v2.safetensors --- 0.0… -:-…
                                                                                                              GB
23:36:46-746302 DEBUG    Model dict loaded: {'ram': {'used': 0.98, 'total': 31.75}, 'gpu': {'used': 1.22, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
23:36:46-757585 DEBUG    Model config loaded: {'ram': {'used': 0.98, 'total': 31.75}, 'gpu': {'used': 1.22, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
23:36:46-760129 INFO     Creating model from config: C:\AI_Stable-Diffusion\automatic\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
23:36:48-243294 DEBUG    Model weights loaded: {'ram': {'used': 4.99, 'total': 31.75}, 'gpu': {'used': 1.22, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
23:36:48-825774 DEBUG    Model weights moved: {'ram': {'used': 3.0, 'total': 31.75}, 'gpu': {'used': 3.25, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
23:36:48-832305 INFO     Applying scaled dot product cross attention optimization
23:36:48-855970 INFO     Embeddings loaded: 0 []
23:36:48-860976 INFO     Model loaded in 2.3s (load=0.1s create=0.4s apply=0.5s vae=0.6s move=0.6s)
23:36:49-038290 DEBUG    Model load finished: {'ram': {'used': 3.03, 'total': 31.75}, 'gpu': {'used': 3.25, 'total':
                         12.0}, 'retries': 0, 'oom': 0}
23:36:49-231087 DEBUG    Reload model weights skip
23:36:49-232617 INFO     Startup time: 15.6s (torch=5.6s gradio=2.2s libraries=1.1s codeformer=0.2s scripts=2.7s opts
                         onchange=0.1s ui=0.8s start=0.1s checkpoint=2.6s)
23:36:49-235679 INFO     Memory used: 1.05 total: 31.75
23:37:00-239255 DEBUG    Server alive: True Memory used: 1.05 total: 31.75
23:37:27-867082 DEBUG    txt2img:
                         task(mx2xl4suciysnmc)|sad||[]|20|4|False|False|1|1|6|-1.0|-1.0|0|0|0|False|512|512|False|0.7|2
                         |Latent|0|0|0|[]
Data shape for DDIM sampling is (1, 4, 64, 64), eta 0.0
Running DDIM Sampling with 20 timesteps
DDIM Sampler:  75%|███████████████████████████████████████████████████                 | 15/20 [00:01<00:00, 11.53it/s]23:37:30-252506 DEBUG    Server alive: True Memory used: 3.17 total: 31.75
DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  8.58it/s]
23:37:30-811672 DEBUG    Saving image: JPEG outputs/text\00009-1077548315-sad.jpg
23:37:30-817003 DEBUG    Processed: 1 Memory: {'ram': {'used': 3.19, 'total': 31.75}, 'gpu': {'used': 3.28, 'total':
                         12.0}, 'retries': 0, 'oom': 0} txt
                         
======================

when I click ->Image from txt2img generated image, no more debug log showed up. When I click generate in img2img tab, nothing show up or debug log whatsoever.

So, I tried once again by close webui.bat and web tab and restarted over. this time I go straight to img2img tab. Sent triangle logo ->Image, use "green" in positve and "orange, red" in negative prompt. I got this result
![image](https://github.com/vladmandic/automatic/assets/133022290/8fed80f9-630c-4025-9a40-e636c2d0475d)

log
============
23:42:17-565156 INFO     Startup time: 10.9s (torch=2.4s gradio=1.2s libraries=0.7s codeformer=0.1s scripts=2.5s opts
                         onchange=0.2s ui=0.8s start=0.1s checkpoint=2.8s)
23:42:17-568677 INFO     Memory used: 1.05 total: 31.75
23:42:29-574423 DEBUG    Server alive: True Memory used: 1.05 total: 31.75
23:42:51-840240 DEBUG    img2img: task(ysryqrctqpjzfxk)|0|green|orange, red|[]|<PIL.Image.Image image mode=RGBA
                         size=512x512 at
                         0x2D225295720>|None|None|None|None|None|None|20|0|4|0|1|False|False|1|1|6|1.5|0.75|-1.0|-1.0|0
                         |0|0|False|0|512|512|1|0|0|32|0||||[]
100%|██████████████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00,  9.49it/s]
23:42:54-260337 DEBUG    Saving image: JPEG outputs/image\00000-2496926999-green.jpg
23:42:54-264151 DEBUG    Processed: 1 Memory: {'ram': {'used': 3.22, 'total': 31.75}, 'gpu': {'used': 3.41, 'total':
                         12.0}, 'retries': 0, 'oom': 0} img
23:42:59-585106 DEBUG    Server alive: True Memory used: 3.22 total: 31.75
============

if I send this image by click ->Image and click generate again, nothing showed up in debug log.

**Comment by vladmandic** [comment]
that is so strange - there is no trace that you ever clicked generate in img2img. and only way that function would not be triggered if javascript code in browser never returned at all - lets double check browser inspector console?
and do you have some browser extensions installed? lets try to elimitnate variables - can you disable them?

**Comment by ultimaKV** [comment]
I switched to Guest mode in Chrome. And the bug still occured. Debug log was the same as the previous attempt. (no log showup after click generate in img2img)

![image](https://github.com/vladmandic/automatic/assets/133022290/e5471c99-9c9f-4147-9909-52d9f5b52897)

=============
I have adguard (adblock software program) active but it shouldn't interfere the image generation? (A1111 have no problems with it or any browser extensions I've installed) 

When I disable, end task Adguard and restart, the bug still occur. Console change to this

![image](https://github.com/vladmandic/automatic/assets/133022290/b12a503a-1c7a-4d07-b978-678d6fdbf668)

Very weird behavior 😂

**Comment by vladmandic** [comment]
actually, yes, it can - and there have been reports that it interferes. but since you tried with adguard disabled, we can discount that.
only idea i have is to add tons of extra debug messages to code (that would annoy everyone else).
unless anyone has an idea?

**Comment by Tillerz** [comment]
Is there maybe a problem with overlapping UI elements with the selected UI theme and a click on the "to image" just doesn't get registred at all because some other element is hovering above it?

**Comment by ultimaKV** [comment]
@Tillerz 
1) I think there's nothing wrong with ui overlapping because I can click generate button only with the logo theme sent to img2img. (I've also tried other theme such as gradio default. Same results)

2) both doesn't work at all, including ctrl+v method. Only thing that works is sending the logo to img2img, then I can click generate button

**Comment by Yodrik** [comment]
A toss into the darkness...

I didn't expect to reproduce, but I followed the simple workflow and console in Chromium (Chrome/Edge) simply do not show any much more than progress bar javascript and task requests when generating text-to-image and tossing images to image-to-image. Lots of frowning girls, but tossing to image tab/upload/copy/drag doesn't flag anything normally. 

This is the same by default in Firefox, but I found you see a bit more when when enabling network monitoring. There are requests being done within assets of gradio. 
![image](https://github.com/vladmandic/automatic/assets/75619281/a1d121bb-9a0e-4308-89dc-2062599b4bb0)

@ultimaKV would it be possible to share with us the version of gradio you use in the working auto1111 environment and the version you have set in SD.Next? 
I understand from your original post you have upgraded your auto1111 environment in pieces and not pulled it up to latest version overall. If you installed a fresh version of the latest auto1111, does this problem reproduce there as well?

**Comment by ultimaKV** [comment]
@Yodrik I didn't expect someone can reproduce this...
- My stable A1111
python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.16.2  •  commit: [a9eef1fb](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/a9eef1fbb1dcdce4f0eb0b8e0f79dcd4c96713e1)

- Lastest commit of A1111 . 
version: [v1.2.1]  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: N/A  •  gradio: 3.29.0  •  commit: [89f9faa]

It froze like SD.next. but when I switched to txt2img tab and generate something, it give this error (and generate txt2img image after)
==========
Task exception was never retrieved
future: <Task finished name='algh81ioyf4_586' coro=<Queue.process_events() done, defined at C:\AI_Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py:343> exception=WebSocketDisconnect(1006)>
Traceback (most recent call last):
  File "C:\AI_Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 347, in process_events
    client_awake = await self.gather_event_data(event)
  File "C:\AI_Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 220, in gather_event_data
    data, client_awake = await self.get_message(event, timeout=receive_timeout)
  File "C:\AI_Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\gradio\queueing.py", line 453, in get_message
    data = await asyncio.wait_for(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 445, in wait_for
    return fut.result()
  File "C:\AI_Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\websockets.py", line 133, in receive_json
    self._raise_on_disconnect(message)
  File "C:\AI_Stable-Diffusion\stable-diffusion-webui\venv\lib\site-packages\starlette\websockets.py", line 105, in _raise_on_disconnect
    raise WebSocketDisconnect(message["code"])
starlette.websockets.WebSocketDisconnect: 1006
===========

- Lastest commit of SD.next [5c51633]
python: 3.10.6  •  torch: 2.0.1+cu118 gradio==3.32.0
no error log like A1111. it just froze.

**Comment by ultimaKV** [comment]
@vladmandic It works! this solved by add your argument
_______
20:33:53-346368 INFO     Server arguments: ['--disable-queue']
_______

Thank you! I'll try to set up something more to see if it still working as intended.

**Comment by vladmandic** [comment]
> starlette.websockets.WebSocketDisconnect: 1006

this gave me a hint.

newer versions of gradio use websockets by default for browser <-> server communication.
disabling queue also disables websockets so it uses pure http only.

there were quite a few issues with websockets on slow networks, they have been addressed 2 days ago (websocket timeout was increased). but in your cae, you're getting actual websocket disconnects - there is something strange on your network (what matters is network server<->browser, not to internet)!

and yes, it can be even if you're running on localhost, some 3rd party adblocker or firewall or vpn - something is causing websocket disconnects.

so using `--disable-queue` is a good workaround (no harm in using it), but if i were you, i'd investigate what is going on with your network.

**Comment by Longsua123** [comment]
> > starlette.websockets.WebSocketDisconnect: 1006
> 
> this gave me a hint.
> 
> newer versions of gradio use websockets by default for browser <-> server communication. disabling queue also disables websockets so it uses pure http only.
> 
> there were quite a few issues with websockets on slow networks, they have been addressed 2 days ago (websocket timeout was increased). but in your cae, you're getting actual websocket disconnects - there is something strange on your network (what matters is network server<->browser, not to internet)!
> 
> and yes, it can be even if you're running on localhost, some 3rd party adblocker or firewall or vpn - something is causing websocket disconnects.
> 
> so using `--disable-queue` is a good workaround (no harm in using it), but if i were you, i'd investigate what is going on with your network.

I'm dumb, I don't know how or where to add --disable-queue

**Comment by ultimaKV** [comment]
> > > starlette.websockets.WebSocketDisconnect: 1006
> > 
> > 
> > this gave me a hint.
> > newer versions of gradio use websockets by default for browser <-> server communication. disabling queue also disables websockets so it uses pure http only.
> > there were quite a few issues with websockets on slow networks, they have been addressed 2 days ago (websocket timeout was increased). but in your cae, you're getting actual websocket disconnects - there is something strange on your network (what matters is network server<->browser, not to internet)!
> > and yes, it can be even if you're running on localhost, some 3rd party adblocker or firewall or vpn - something is causing websocket disconnects.
> > so using `--disable-queue` is a good workaround (no harm in using it), but if i were you, i'd investigate what is going on with your network.
> 
> I'm dumb, I don't know how or where to add --disable-queue

in webui.bat
add after launch.py and before %
![image](https://github.com/vladmandic/automatic/assets/133022290/7c20254f-7144-4554-9465-a2710d946a05)

to
%PYTHON% launch.py --autolaunch --disable-queue%*

ps. --autolaunch is just automatically open the sd tab on browser. nothing much
