### ISSUE TITLE
[Issue]: Numerous git command errors, no issues with network environment

### ISSUE THREAD

**Issue by wzgrx** [vladmandic/automatic#834]
### Issue Description

00:04:53-029753 ERROR    Error running git: G:\Soft\automatic\repositories\stable-diffusion-stability-ai / rev-parse
                         HEAD
00:04:53-133045 ERROR    Error running git: G:\Soft\automatic\repositories\stable-diffusion-stability-ai / fetch
00:04:53-230173 ERROR    Error running git: G:\Soft\automatic\repositories\stable-diffusion-stability-ai / checkout
                         cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf
00:04:53-329988 ERROR    Error running git: G:\Soft\automatic\repositories\taming-transformers / rev-parse HEAD
00:04:53-439950 ERROR    Error running git: G:\Soft\automatic\repositories\taming-transformers / fetch
00:04:53-581357 ERROR    Error running git: G:\Soft\automatic\repositories\taming-transformers / checkout
                         3ba01b241669f5ade541ce990f7650a3b8f65318
00:04:53-676577 ERROR    Error running git: G:\Soft\automatic\repositories\k-diffusion / rev-parse HEAD
00:04:53-750109 ERROR    Error running git: G:\Soft\automatic\repositories\k-diffusion / fetch
00:04:53-840230 ERROR    Error running git: G:\Soft\automatic\repositories\k-diffusion / checkout
                         b43db16749d51055f813255eea2fdf1def801919
00:04:53-920020 ERROR    Error running git: G:\Soft\automatic\repositories\CodeFormer / rev-parse HEAD
00:04:54-011461 ERROR    Error running git: G:\Soft\automatic\repositories\CodeFormer / fetch
00:04:54-100163 ERROR    Error running git: G:\Soft\automatic\repositories\CodeFormer / checkout
                         c5b4593074ba6214284d6acd5f1719b6c5d739af
00:04:54-189971 ERROR    Error running git: G:\Soft\automatic\repositories\BLIP / rev-parse HEAD
00:04:54-269794 ERROR    Error running git: G:\Soft\automatic\repositories\BLIP / fetch
00:04:54-354916 ERROR    Error running git: G:\Soft\automatic\repositories\BLIP / checkout
                         48211a1594f1321b00f14c9f7a5b4813144b2fb9
00:04:54-354916 INFO     Installing submodules
00:05:00-841502 INFO     Updating submodules
00:05:05-129912 ERROR    Error running git: extensions-builtin/a1111-sd-webui-lycoris / branch
00:05:05-230212 ERROR    Error running git: extensions-builtin/a1111-sd-webui-lycoris / checkout fatal: detected dubious
                         ownership in repository at 'G:/Soft/automatic/extensions-builtin/a1111-sd-webui-lycoris'
00:05:05-319940 ERROR    Error running git: extensions-builtin/a1111-sd-webui-lycoris / pull origin fatal: detected
                         dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/a1111-sd-webui-lycoris' --autostash --rebase --force
00:05:05-403090 ERROR    Error running git: extensions-builtin/clip-interrogator-ext / branch
00:05:05-485646 ERROR    Error running git: extensions-builtin/clip-interrogator-ext / checkout fatal: detected dubious
                         ownership in repository at 'G:/Soft/automatic/extensions-builtin/clip-interrogator-ext'
00:05:05-570921 ERROR    Error running git: extensions-builtin/clip-interrogator-ext / pull origin fatal: detected
                         dubious ownership in repository at 'G:/Soft/automatic/extensions-builtin/clip-interrogator-ext'
                         --autostash --rebase --force
00:05:05-661050 ERROR    Error running git: extensions-builtin/multidiffusion-upscaler-for-automatic1111 / branch
00:05:05-752352 ERROR    Error running git: extensions-builtin/multidiffusion-upscaler-for-automatic1111 / checkout
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/multidiffusion-upscaler-for-automatic1111'
00:05:05-839727 ERROR    Error running git: extensions-builtin/multidiffusion-upscaler-for-automatic1111 / pull origin
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/multidiffusion-upscaler-for-automatic1111' --autostash
                         --rebase --force
00:05:05-931551 ERROR    Error running git: extensions-builtin/sd-dynamic-thresholding / branch
00:05:06-019982 ERROR    Error running git: extensions-builtin/sd-dynamic-thresholding / checkout fatal: detected
                         dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-dynamic-thresholding'
00:05:06-110206 ERROR    Error running git: extensions-builtin/sd-dynamic-thresholding / pull origin fatal: detected
                         dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-dynamic-thresholding' --autostash --rebase --force
00:05:06-190012 ERROR    Error running git: extensions-builtin/sd-extension-aesthetic-scorer / branch
00:05:06-280858 ERROR    Error running git: extensions-builtin/sd-extension-aesthetic-scorer / checkout fatal: detected
                         dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-extension-aesthetic-scorer'
00:05:06-369879 ERROR    Error running git: extensions-builtin/sd-extension-aesthetic-scorer / pull origin fatal:
                         detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-extension-aesthetic-scorer' --autostash --rebase
                         --force
00:05:06-455933 ERROR    Error running git: extensions-builtin/sd-extension-steps-animation / branch
00:05:06-539889 ERROR    Error running git: extensions-builtin/sd-extension-steps-animation / checkout fatal: detected
                         dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-extension-steps-animation'
00:05:06-620360 ERROR    Error running git: extensions-builtin/sd-extension-steps-animation / pull origin fatal:
                         detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-extension-steps-animation' --autostash --rebase
                         --force
00:05:06-710049 ERROR    Error running git: extensions-builtin/sd-extension-system-info / branch
00:05:06-789809 ERROR    Error running git: extensions-builtin/sd-extension-system-info / checkout fatal: detected
                         dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-extension-system-info'
00:05:06-879804 ERROR    Error running git: extensions-builtin/sd-extension-system-info / pull origin fatal: detected
                         dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-extension-system-info' --autostash --rebase --force
00:05:06-969908 ERROR    Error running git: extensions-builtin/sd-webui-controlnet / branch
00:05:07-056157 ERROR    Error running git: extensions-builtin/sd-webui-controlnet / checkout fatal: detected dubious
                         ownership in repository at 'G:/Soft/automatic/extensions-builtin/sd-webui-controlnet'
00:05:07-140167 ERROR    Error running git: extensions-builtin/sd-webui-controlnet / pull origin fatal: detected dubious
                         ownership in repository at 'G:/Soft/automatic/extensions-builtin/sd-webui-controlnet'
                         --autostash --rebase --force
00:05:07-239867 ERROR    Error running git: extensions-builtin/sd-webui-model-converter / branch
00:05:07-320179 ERROR    Error running git: extensions-builtin/sd-webui-model-converter / checkout fatal: detected
                         dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-webui-model-converter'
00:05:07-413293 ERROR    Error running git: extensions-builtin/sd-webui-model-converter / pull origin fatal: detected
                         dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-webui-model-converter' --autostash --rebase --force
00:05:07-501498 ERROR    Error running git: extensions-builtin/seed_travel / branch
00:05:07-590100 ERROR    Error running git: extensions-builtin/seed_travel / checkout fatal: detected dubious ownership
                         in repository at 'G:/Soft/automatic/extensions-builtin/seed_travel'
00:05:07-676121 ERROR    Error running git: extensions-builtin/seed_travel / pull origin fatal: detected dubious
                         ownership in repository at 'G:/Soft/automatic/extensions-builtin/seed_travel' --autostash
                         --rebase --force
00:05:07-756781 ERROR    Error running git: extensions-builtin/stable-diffusion-webui-images-browser / branch
00:05:07-840201 ERROR    Error running git: extensions-builtin/stable-diffusion-webui-images-browser / checkout fatal:
                         detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/stable-diffusion-webui-images-browser'
00:05:07-931205 ERROR    Error running git: extensions-builtin/stable-diffusion-webui-images-browser / pull origin
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/stable-diffusion-webui-images-browser' --autostash
                         --rebase --force
00:05:08-014072 ERROR    Error running git: extensions-builtin/stable-diffusion-webui-rembg / branch
00:05:08-100231 ERROR    Error running git: extensions-builtin/stable-diffusion-webui-rembg / checkout fatal: detected
                         dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/stable-diffusion-webui-rembg'
00:05:08-190303 ERROR    Error running git: extensions-builtin/stable-diffusion-webui-rembg / pull origin fatal:
                         detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/stable-diffusion-webui-rembg' --autostash --rebase
                         --force
00:05:08-299748 ERROR    Error running git: modules/lora / branch
00:05:08-380111 ERROR    Error running git: modules/lora / checkout fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/modules/lora'
00:05:08-480146 ERROR    Error running git: modules/lora / pull origin fatal: detected dubious ownership in repository
                         at 'G:/Soft/automatic/modules/lora' --autostash --rebase --force
00:05:08-560237 ERROR    Error running git: modules/lycoris / branch
00:05:08-645116 ERROR    Error running git: modules/lycoris / checkout fatal: detected dubious ownership in repository
                         at 'G:/Soft/automatic/modules/lycoris'
00:05:08-730103 ERROR    Error running git: modules/lycoris / pull origin fatal: detected dubious ownership in
                         repository at 'G:/Soft/automatic/modules/lycoris' --autostash --rebase --force
00:05:08-819933 ERROR    Error running git: wiki / branch
00:05:08-900048 ERROR    Error running git: wiki / checkout fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/wiki'
00:05:08-993975 ERROR    Error running git: wiki / pull origin fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/wiki' --autostash --rebase --force
00:05:08-999985 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
00:05:09-087696 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\a1111-sd-webui-lycoris / branch
00:05:09-170021 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\a1111-sd-webui-lycoris / checkout
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/a1111-sd-webui-lycoris'
00:05:09-293411 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\a1111-sd-webui-lycoris / pull origin
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/a1111-sd-webui-lycoris' --autostash --rebase --force
00:05:09-391057 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\clip-interrogator-ext / branch
00:05:09-489844 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\clip-interrogator-ext / checkout fatal:
                         detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/clip-interrogator-ext'
00:05:09-602990 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\clip-interrogator-ext / pull origin
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/clip-interrogator-ext' --autostash --rebase --force
00:05:39-974238 ERROR    Error running git:
                         G:\Soft\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111 / branch
00:05:40-063465 ERROR    Error running git:
                         G:\Soft\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111 / checkout
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/multidiffusion-upscaler-for-automatic1111'
00:05:40-168102 ERROR    Error running git:
                         G:\Soft\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111 / pull origin
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/multidiffusion-upscaler-for-automatic1111' --autostash
                         --rebase --force
00:05:40-283216 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-dynamic-thresholding / branch
00:05:40-384278 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-dynamic-thresholding / checkout
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-dynamic-thresholding'
00:05:40-489769 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-dynamic-thresholding / pull origin
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-dynamic-thresholding' --autostash --rebase --force
00:05:40-575799 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-extension-aesthetic-scorer / branch
00:05:40-683315 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-extension-aesthetic-scorer /
                         checkout fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-extension-aesthetic-scorer'
00:05:40-794234 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-extension-aesthetic-scorer / pull
                         origin fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-extension-aesthetic-scorer' --autostash --rebase
                         --force
00:05:40-897349 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-extension-steps-animation / branch
00:05:40-997029 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-extension-steps-animation / checkout
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-extension-steps-animation'
00:05:41-079954 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-extension-steps-animation / pull
                         origin fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-extension-steps-animation' --autostash --rebase
                         --force
00:05:41-180912 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-extension-system-info / branch
00:05:41-280927 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-extension-system-info / checkout
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-extension-system-info'
00:05:41-378325 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-extension-system-info / pull origin
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-extension-system-info' --autostash --rebase --force
00:05:41-723496 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-webui-controlnet / branch
00:05:41-826004 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-webui-controlnet / checkout fatal:
                         detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-webui-controlnet'
00:05:41-911410 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-webui-controlnet / pull origin
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-webui-controlnet' --autostash --rebase --force
00:05:42-967815 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-webui-model-converter / branch
00:05:43-069915 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-webui-model-converter / checkout
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-webui-model-converter'
00:05:43-232659 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\sd-webui-model-converter / pull origin
                         fatal: detected dubious ownership in repository at
                         'G:/Soft/automatic/extensions-builtin/sd-webui-model-converter' --autostash --rebase --force
00:05:43-340016 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\seed_travel / branch
00:05:43-439878 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\seed_travel / checkout fatal: detected
                         dubious ownership in repository at 'G:/Soft/automatic/extensions-builtin/seed_travel'
00:05:43-530021 ERROR    Error running git: G:\Soft\automatic\extensions-builtin\seed_travel / pull origin fatal:
                         detected dubious ownership in repository at 'G:/Soft/automatic/extensions-builtin/seed_travel'
                         --autostash --rebase --force

### Version Platform Description

win1
edge
Latest version

**Comment by AlUlkesh** [comment]
> win1
edge
Latest version

The problem is probably that you are running Windows 1  🤣 
...

Is this a network drive?

**Comment by vladmandic** [comment]
this all looks like major permission/ownership issues with your location "G:\Soft\automatic" so git cannot complete any operations.
also check what is the git you're actually using (and where did you download it from)? run `git --version'

**Comment by wzgrx** [comment]
> > win1 边缘 最新版本
> 
> 问题可能是您正在运行Windows 1🤣...
> 
> 这是网络驱动器吗？

I found the wrong problem, it's actually a hard drive format issue. This problem can occur in the exfat format, just convert it to vtfs.

**Comment by wzgrx** [comment]
> 这一切看起来都是您的位置“G：\Soft\automatic”的主要权限/所有权问题，因此 git 无法完成任何操作。还要检查您实际使用的 git 是什么（以及您从哪里下载的）？跑`git --version`

I found the wrong problem, it's actually a hard drive format issue. This problem can occur in the exfat format, just convert it to vtfs.
