### ISSUE TITLE
[Issue]: Inpaint undoing steps back more states than requested

### ISSUE THREAD

**Issue by mark-wd** [vladmandic/automatic#838]
### Issue Description

This seems to be a new issue from the most recent versions. While using the standard Inpaint function on Firefox latest, if I add several different lines, one at a time, and then attempt to undo the latest line via the provided button, more lines are being removed than what was requested.

This can be reproduced by just spreading a bunch of inpainted dots, I believe.

### Version Platform Description

updated: 2023-05-09
hash: 1288aec4

**Comment by vladmandic** [comment]
can you check if issue still exists?

**Comment by vladmandic** [comment]
@mark-wd ?

**Comment by vladmandic** [comment]
closing for now, if there is update i'll reopen.
