### ISSUE TITLE
[Issue]: "Incompatible Python version: 3.11.3 required 3.[9, 10]"

### ISSUE THREAD

**Issue by TheWonderfulTartiflette** [vladmandic/automatic#853]
### Issue Description

I had Python 3.11 on my PC, but I uninstalled it due to the program not supporting it to install 3.10, I even rebooted to make sure changes were applied, but I'm still having that same error

### Version Platform Description

Windows 11 Pro 22H2 Insider

**Comment by 1r00t** [comment]
what does it say when you type `python --version` and `python3 --version` ?

**Comment by TheWonderfulTartiflette** [comment]
My bad it was because I had installed Python 3.11 from MS store, so it won't figure in the Unistall Apps section of the control panel

**Comment by unstabledelusions** [comment]
I've tried but can't work out how to launch it using Python 3.10. I have 3.10 installed and tried a few solutions but nothing seems to work. 

What's the best way to launch webui.bat with Python 3.10?

**Comment by unstabledelusions** [comment]
Okay if others have this problem this is what I did. I created a new file called "webui-user.bat" based on the one in Automatic1111 with:

`@echo off`
`set PYTHON="C:\Users\YOURUSERNAME\AppData\Local\Programs\Python\Python310\python.exe"`
`call webui.bat`

I deleted the Venv folder that had already been created then ran webui-user.bat.

Obviously your Python 3.10may be elsehwere

**Comment by vladmandic** [comment]
if its not there already, add to faq: https://github.com/vladmandic/automatic/discussions/1011
