### ISSUE TITLE
[Issue]: How to delete the cached png icon?

### ISSUE THREAD

**Issue by wzgrx** [vladmandic/automatic#854]
### Issue Description

How to delete the cached png icon? He changed the icon of the original SD, restarted the computer, and the browser couldn't solve it.
![Snipaste_2023-05-10_21-39-22](https://github.com/vladmandic/automatic/assets/39661556/9fdd0610-e6e9-4d3d-b0e3-eed330874814)

### Version Platform Description

win11
edge
the latest version

**Comment by wzgrx** [comment]
![Snipaste_2023-05-10_21-54-09](https://github.com/vladmandic/automatic/assets/39661556/13bbb296-b9c4-4b28-bc9b-a4af60851c42)

**Comment by vladmandic** [comment]
you're asking why icon from this repo shows when you load some other page? bacuse for browser, you're loading both from same url - your localhost. and if the second app does not have an icon, browser will return last known one from cache.

totally valid question, but why open an issue for this? this is not an app issue, much better suited for discussions.
