### ISSUE TITLE
[Bug]: FileNotFoundError: [Errno 2] No such file or directory: 'T:\systemp\sd_temp_files\tmpe4svot1d'

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#86]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

Unfortunately, this bug still exists in this fork.
A defined temp folder in the WebUI settings will not be created if it's not existent and causes errors (even up to crashes) for some actions and extensions that rely on this folder.
Please fix this ASAP, because it's really annoying for almost half a year now.

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

The temp folder specified in the settings should be created if not existent.

### Commit where the problem happens

https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/ffc54d09383a51b3f93d195d692d44d736bf8f47

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Mozilla Firefox

### Command Line Arguments

```Shell
--disable-sdp-attention --xformers --api --administrator --opt-split-attention --theme=dark
```

### List of extensions

![extensions_automatic](https://user-images.githubusercontent.com/122026301/230896003-51aa2596-55dd-4850-b61f-9fe0bb66a3a9.png)

### Console logs

```Shell
FileNotFoundError: [Errno 2] No such file or directory: 'T:\systemp\sd_temp_files\tmpe4svot1d'
```

**Comment by vladmandic** [comment]
See #92. Work is in progress, in the meantime closing this as duplicate.

**Comment by vladmandic** [comment]
did you restart server after changing temp_dir?
if folder does not exist, it should provide output on console:
> Creating folder: /tmp/sd/images

**Comment by vladmandic** [comment]
check/create-if-missing happens as soon as launcher is complete and it starts webui.
basically first line after `Server arguments` and before `Available models`
no, there are no checks while running.

**Comment by Woisek** [comment]
So, if a script/extension needs the temp folder and the folder was flushed previously, it will not be re-created ... ?

**Comment by vladmandic** [comment]
it will be recreated during startup. how can a folder be flushed during runtime? if you delete it manually, then yes, thats a problem.

**Comment by Woisek** [comment]
> how can a folder be flushed during runtime?

As I said a while ago, this is the system temp folder. And since using SD, it also came to be a bit of a working folder for me (i.e., saving pose pictures when I'm creating poses, so they will be deleted again and don't stay in a folder where I maybe forget them). So, occasionally the temp folder will be deleted and with it the sd-temp-files folder.

> if you delete it manually, then yes, thats a problem.

Well, maybe I'm wrong, but shouldn't the main program take care of such things? To watch if every folder is accessible during runtime?
And isn't there any "report" from scripts/extensions, that the temp folder is gonna needed and then it will be checked again if it's existing?
Just a naive thought of mine.

And while we are at it again: those empty temp folder that being created ... do you already know from where they come and why they are not created in the system set temp folder?

**Comment by vladmandic** [comment]
ideally, yes, you're right. but if someone takes away a floor you're standing on, it takes a lot of exception handling not to fall. i'd have to trace down every instance where temp folder may be referenced to and wrap it. should had it be done correctly from the start? yes. but while i'm fixing old code, this is pretty low on priority list.

re: temp files outside of it, i'll check.
