### ISSUE TITLE
[Issue]: Extra networks reload ignores filter box

### ISSUE THREAD

**Issue by slimeqslimedog** [vladmandic/automatic#863]
### Issue Description

When the "extra networks" pane is reloaded, either by clicking the reload button or by adding a preview thumbnail to a network, the contents of the filter box are ignored until they are changed by the user. (This has also been an unfixed issue in A1111 for months now.)

### Version Platform Description

Git commit aad2a5337985b5e1af35ea41da1eab9472fbfacd

Chrome Version 113.0.5672.63 (Official Build) (64-bit) on Windows 11

**Comment by vladmandic** [comment]
fixed (i hope).

**Comment by slimeqslimedog** [comment]
Confirmed! Thanks!

**Comment by vladmandic** [comment]
could be - that part of the code is a mess. list is maintained in python, but search/filter is done in js, so passing event from python to js gets lost sometimes. i'll dig in, but don't want to spend too much time on it given the higher-priority items.
