### ISSUE TITLE
[Issue]: Some settings will not be respected after some time

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#866]
### Issue Description

I found out lately, that some settings won't be respected after some time.
I have **Max prompt words for [prompt_words] pattern** and **Create a text file next to every image with generation parameters** in my quick access because I use them frequently between generations.
It started with the **Max prompt words for [prompt_words] pattern**, after some time, no matter what number I dial in, it stays to the one that was set before. It's like the script isn't updating it.
How do I know? Obviously when i.e. 3 is set and 7 from before  is used. 🙂 No, joke aside, when using the up and down dial and you click too fast, it sometimes jumps back or to another number, because the script isn't keeping up with the speed. But after some time, one can click as fast as hell and no jump backs or delays occur, like the script stopped working. This is then the point, where it don't work anymore.
Now I noticed the same behavior on **Create a text file next to every image with generation parameters**. I had it checked to generate the text files, with the next image I unchecked it and it still generates the text files.
To get it to work again I have to reload the webpage, but this isn't really a solution when in the middle of an workflow ... 🙄

So, I don't know if this is a generic problem or something related to the quick menu.

### Version Platform Description

Win10, Firefox 1.6
Version: aad2a533 Tue May 9 17:27:23 2023 -0400

**Comment by vladmandic** [comment]
unfortunately, most options in settings do not work dynamically and require restart, its just how it is. some require server restart (anything to do with server params like changing compute options) and some require browser restart (like you've mentioned).
making it fully dynamic with the current concept is nearly impossible, sorry about that.

**Comment by Woisek** [comment]
>unfortunately, most options in settings do not work dynamically and require restart

But the one mentioned by me worked flawlessly since I've used A1111 ... 😶 It also wouldn't make no sense otherwise.
And the fact that there are now suddenly problems can only have been triggered by a change. Possibly during one of the last updates ... ?! 🤔

**Comment by Woisek** [comment]
Hmm ... Clip Skip was in the settings before you moved it into the txt2img/img2img pages. Do the users now have always to reload the webpage if they change the clip skip?
I don't want to argue again, but not everything in the settings is for the system itself. Some of them are for the generation, thus parameters that will be send on generating (as I understand it). It makes no sense if such parameters need a reload of the webpage ... 🤔 Well ...

**Comment by Woisek** [comment]
>i've moved clip skip explicitly so it can be set on the fly without needing to set global setting.

Yes, that's what I meant. It was in the settings, and it worked without reload. It's now outside and still works without reload. The same goes for my two settings I use, with the difference, that now it sometimes stop to work and I don't know why.
I just hoped you could look it up when you got time. Maybe it's just a small thing that was accidentally changed, idk. ... 🙂

**Comment by vladmandic** [comment]
my general approach is that anything that needs to be changed regularly should be available directly, not needing to go to settings. settings should be "set once and forget about it". i don't see a use case for frequently changing settings you're talking about

**Comment by Woisek** [comment]
My template pattern for my working directory is like this: **test/[prompt_words]/[model_name]/**
So I constantly need to change the length of the prompt words to a reasonable size (**Max prompt words for [prompt_words] pattern**)
While I'm working on a design, I constantly change settings like resize, sampler, cfg, checkpoint, etc. till I found my final settings.
So, at every mayor change I do, I want to also save a txt file as "settings backup" (**Create a text file next to every image with generation parameters**). After that I deactivate it till the next change I do, where I again will save a text file with the new settings. And so on and so on ... 

Would you also consider this as "regularly changed" ... ? 🙂

**Comment by vladmandic** [comment]
frequently changing "max prompt for words ..." is not something i'd consider normal.
but the second use case is valid - and i like to go after use-cases, not "enable this or that option in settings". if i understand correctly you simply want to be able to save image params on-demand - that would be a valid feature request.

**Comment by Woisek** [comment]
>frequently changing "max prompt for words ..." is not something i'd consider normal.

I don't know about others on how they work, but I differentiate my generations after the prompt I use so that every work is in some way unique and distinguishable. 
Only when I'm fully finished, I maybe consider renaming the folder if needed.

I understand why you question some things, I do the same as a developer. But there is also feedback from people who really understand an application and can use it for themselves. And maybe even more effectively than others, because they think differently and further than the "normal" users. It would be nice if you also give these people a place and give them the opportunity to use the program even more effectively. There is no harm in it but can only benefit everyone.
Apart from that, think about what the quick settings are for. And then think about why you still need them, if you have to restart everything anyway, so that it becomes active. That makes absolutely no sense otherwise.

Therefore the correct approach would be IMHO this: Everything that can be put into quick access, must also be able to be activated during the runtime. Very simple. With that, questions if something specific should work there or not, are answered by themselves.
In my case: why give these two options into quick access, if i have to interrupt my work, restart and wait for it anyway. Then it doesn't matter to go into the options first and then restart and wait for it.

And please don't think I'm bringing up all these things just to make work for you, I sure don't. I know your side all too well. I just want to help to make a good program even better for everyone. since I can't do it programming-wise myself, I just try to give feedback and suggestions where it seems important to me. And I emphasize "important" because I am absolutely no friend of unnecessary frippery and want to avoid unimportant or unnecessary things. I just wanted to make that clear.

I'll leave it like this to think about. Thanks for your work so far.

**Comment by vladmandic** [comment]
quick settings don't discriminate - there is no check what can and cannot be placed there. you can put anything from settings.
yes, there absolutely should be some logic, but there is soo much legacy code.

regarding behavior here vs original a1111, its the same with difference being newer gradio version - and that means that gradio is trying to intelligent and not trigger frequent updates - so for example, if you have numeric value and you click up-up-up, it will not trigger event and app doesn't even know something changed.

i've added log statements, if you run `webui --debug`, it will print each change made so you can see which are not applied.

```log
08:20:19-827047 DEBUG    Setting changed: key=img_max_size_mp, value=201.0
08:20:20-291571 DEBUG    Setting changed: key=img_max_size_mp, value=202.0
08:20:26-984078 DEBUG    Setting changed: key=img_max_size_mp, value=203.0
08:20:31-909321 DEBUG    Setting changed: key=img_max_size_mp, value=202.0
08:20:32-188479 DEBUG    Setting changed: key=img_max_size_mp, value=201.0
08:20:35-588779 DEBUG    Setting changed: key=img_max_size_mp, value=200.0
```

and i've checked two options you've mentioned - both are applicable on-the-fly. so if settings get applied, they are ok to use.
