### ISSUE TITLE
[Issue]: Automatic sets the wrong TORCH.LOAD variable at install time when building on github actions, this prevents model from loading correctly

### ISSUE THREAD

**Issue by adjarar** [vladmandic/automatic#867]
### Issue Description

In the automatic1111 webui there is the option flag --skip-torch-cuda-test when running prepare_environment(). This prevents torch from checking if the current build system has a compatible GPU, and just installs the requirements. This option is no longer there in automatic. When torch doesn't find a cuda device It sets map_location='cpu' instead of cuda, this in turn prevents the model from being loaded later on a device that does have a compatible card.

The image is built with Github actions and then runs on a Vast.ai pod. All of this works with the automatic1111 version.

This is the error I get when running ./webui.sh: 

![console_output](https://github.com/vladmandic/automatic/assets/82608399/a1a5e113-a1aa-480a-8d36-57f27bfb3270)
[console_output.txt](https://github.com/vladmandic/automatic/files/11454094/console_output.txt)

### Version Platform Description

Docker image was built on a github actions ubuntu pod, then ran on a Vast.ai GPU pod with a 3090.

Running automatic version:

commit 16aef2a88c6880636aa4ea803360706ad537518b
Author: Craig Wright <craig_wright156@hotmail.com>
Date:   Tue May 9 22:00:50 2023 +0100

**Comment by vladmandic** [comment]
fixed. i've added `--skip-torch`.

**Comment by adjarar** [comment]
Thanks for the quick fix, it works now! There's another small issue in regards to Docker, but I'll open a separate case for that, it's not that urgent.

May 11, 2023, 18:09 by ***@***.***:
