### ISSUE TITLE
[Issue]: Rollback VAE functionality requires Torch 2.1 or higher

### ISSUE THREAD

**Issue by mobilehacker** [vladmandic/automatic#872]
### Issue Description

Hello! Recently noticed that error in console. Always starting with an --upgrade flag. Reproduces with every launch for the last couple of versions. Is that possible to upgrade torch version to 2.1?

### Version Platform Description

Version: 0f2a03a5 Thu May 11 11:50:51 2023 -0400
Upgraded to version: aff2dcb6 Thu May 11 12:08:38 2023 -0400

launch options: call webui.bat --upgrade --listen --port 65000 --allow-code --insecure
platform: Windows 11 x64, RTX 3060 12gb.

**Comment by vladmandic** [comment]
you somehow enabled that option in settings - disable it:
UI -> Settings -> Compute Settings -> Attempt to roll back VAE when produced NaN values, requires NaN check (experimental)

**Comment by mobilehacker** [comment]
Thanks! Thought I was missing out a feature, glad its not like that.
