### ISSUE TITLE
[Issue]: Pressing zip in the UI doesn't work and gives error

### ISSUE THREAD

**Issue by adjarar** [vladmandic/automatic#875]
### Issue Description

After generating image on the txt2img tab and pressing zip the following error occurs and nothing else happens.

18:29:14-025573 ERROR    gradio call: IndexError                                                                        ╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ /home/webui/automatic/modules/call_queue.py:52 in f                                                                  │
│                                                                                                                      │
│   51 │   │   │   │   pr.enable()                                                                                     │
│ ❱ 52 │   │   │   res = func(*args, **kwargs)                                                                         │
│   53 │   │   │   if res is None:                                                                                     │
│                                                                                                                      │
│ /home/webui/automatic/modules/ui_common.py:74 in save_files                                                          │
│                                                                                                                      │
│    73 │   │   │   │   p.all_prompts.append(p.prompt) # pylint: disable=no-member                                     │
│ ❱  74 │   │   │   fullfn, txt_fullfn = modules.images.save_image(image, path, "", seed=p.all_s                       │
│    75                                                                                                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯IndexError: list index out of range

### Version Platform Description

I run this on a vast.ai with the --share option enabled.

commit e038bf15495ef116a479daf86611573426aead7d
Author: Vladimir Mandic <mandic00@live.com>
Date:   Wed May 10 16:03:55 2023 -0400

**Comment by vladmandic** [comment]
i cannot reproduce, but i've made a slight change, try upgrading.

pressing zip creates zip file and opens a list below gallery with images AND zip file so you can download it.
![image](https://github.com/vladmandic/automatic/assets/57876960/1f75aae0-8aef-4453-9020-a617efcb007a)

if you don't see that, report here and i'll reopen.

**Comment by adjarar** [comment]
I found the culprit. The error only happens when you have controlnet enabled. Most likely because it outputs an extra image from the mask which it doesn't expect. Try it with this for openpose for example.

![front-pose](https://github.com/vladmandic/automatic/assets/82608399/65839e3b-c554-4dfd-9d99-f6d0d1d5305b)

**Comment by vladmandic** [comment]
Interesting. I'll try.

**Comment by vladmandic** [comment]
fixed.
