### ISSUE TITLE
[Issue]: Linux: CUDA and rocm at the same time

### ISSUE THREAD

**Issue by Chilluminati91** [vladmandic/automatic#877]
### Issue Description

The initial installer will always install pytorch for cuda if both platforms are detected (because it checks first for cuda and then rocm). A better solution would be to first detect ALL platforms and then ask the user which one he wants to install in that case.

After manually installing the rocm version the webui crashes before loading the model with a segmentation fault.

Both problems can be circumvented by manually removing the cuda check from installer.py (line 212) and just keeping the rocm one. (dirty workaround)

### Version Platform Description

Ubuntu 22.04 LTS
Firefox
AMD RX 6650 XT
Nvidia GTX 1060

Version: 8c981159 Thu May 11 14:20:27 2023 -0400

**Comment by vladmandic** [comment]
I'll add flags to force usage of specific platform.

**Comment by vladmandic** [comment]
done

> webui --help

```log
  --use-cuda                                           Force use nVidia CUDA backend, default: False
  --use-rocm                                           Force use AMD ROCm backend, default: False
  --use-ipex                                           Use Intel OneAPI XPU backend, default: False
  --use-directml                                       Use DirectML if no compatible GPU is detected, default: False
```
