### ISSUE TITLE
[Issue]: Generations not completing after latest update (8c981159) with 9 images in batch

### ISSUE THREAD

**Issue by gruevy** [vladmandic/automatic#883]
### Issue Description

I've had this happen several times in a row now. I'll start a generation with 9 images in the batch and it'll get to 92% and stop there forever. I have to shut it down in the terminal and rerun webui.bat it to try again. It doesn't save the images in the outputs folder or in %temp%, or the grid. I was using a LoRA so I tried without and it happened on the 3rd round. I tried it with 4 images in the batch and it worked every time. I dunno when exactly it stopped working, but probably in the last week or so.

### Version Platform Description

Firefox, windows 11, 8c981159

**Comment by vladmandic** [comment]
are you talking about batch count or batch size?

with batch size, all allocation happens at once and generate runs in parallel.
and behavior seems perfectly fine.

1. fresh start: system info -> `gpu-allocated: current:3.99 peak:3.99`
2. run txt2img 1024x1024 batch size 10, results in oom:
`CUDA out of memory. Tried to allocate 1.56 GiB (GPU 0; 12.00 GiB total capacity; 10.66 GiB already allocated; 0 bytes free; 10.78 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF`
(note that memory deallocation and garbage collection runs automatically **after** the error.)
3. check system-info again: `gpu-allocated: current:4.0 peak:10.66` - so we're back to normal (and you can see the peak which matches what oom message said)
4. run txt2img 1024x1024 batch size 1, works just fine.

with batch count, i've tried to set it to 100 and gpu-allocated was oscillating by ~200mb, but never actually grew and it was pretty constant.

in either case, i cannot reproduce. if anything, i've added more aggressive garbage collection recently.

**Comment by gruevy** [comment]
It was batch count. I'll see if I can narrow it down and see what circumstances make it more or less likely. Could be something on my end, too.

**Comment by eadnams22** [comment]
This sounds similar to the issue I had, turning off use channels last memory seems to have fixed it for me.

**Comment by gruevy** [comment]
I haven't been able to reproduce this. I dunno if it was one of the small updates since I posted it or something that changed on my PC but I suppose it can be closed.
