### ISSUE TITLE
[Issue]:  Linux version not launching since today

### ISSUE THREAD

**Issue by oobov** [vladmandic/automatic#884]
### Issue Description

Hello,
I usually do get pull anytime I launch vlad. 
For weeks it was ok, but today it crashes before starting.

I got a lot of error lines, but the final one is : 
_RuntimeError: jaxlib version 0.4.9 is newer than and incompatible with jax version 0.4.8. Please update your jax and/or jaxlib packages._

And the error lines before are related to jax, tensorflow, pytorch_lighting, torchmetrics.

Edit : I can launch 1111.

I'm not a pro but usually i have nothing to do to use your SD version so I thought i would mention the issue.

### Version Platform Description

Version: 8c981159 Thu May 11 14:20:27 2023 -0400

6.1.26-1-MANJARO 
KDE Plasma 5.27.4

**Comment by vladmandic** [comment]
i've run into that, but cannot update requirements as jax package did a piecemeal - different versions are available for different platforms. once jax is properly published, i can fix it on my end.

in the meantime just run `pip install jax==0.4.9`

**Comment by oobov** [comment]
I just mention one thing in case someone has the same issue.
I deleted my venv folder, and launched webui.sh which installed everything again, and for some reasons it worked. <3
