### ISSUE TITLE
[Issue]: Lora's not working.

### ISSUE THREAD

**Issue by lebakerino** [vladmandic/automatic#885]
### Issue Description

Ok, so i had a build from the 26th of April and with LORA's I was getting an error where when a LORA model was in the prompt and I would try to generate, it wouldn't generate and this error would appear below the preview window;

AttributeError; 'Options' object has no attribute 'lora_apply_to_outputs'

So I decided to see if there any updates and I have just upgraded to the latest version to see if it resolves the issue and a new error has appeared:

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

### Version Platform Description

Windows 11, Firefox and Brave browser, VLAD (latest version around on 26th april and current = 8c981159 Thu May 11 14:20:27 2023 -0400)

**Comment by vladmandic** [comment]
if you did a quick search, you'd find 4 duplicates, all because of broken user-installed extension
duplicate #225.
