### ISSUE TITLE
[Issue]: Using controlnet in txt2img with openpose and hires fix gives error

### ISSUE THREAD

**Issue by adjarar** [vladmandic/automatic#887]
### Issue Description

Tried it with the enclosed pose and hires fix on and received the following error. It does work with hire fix off.

22:52:30-194959 ERROR    gradio call: RuntimeError                                                                      ╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ /home/webui/automatic/modules/call_queue.py:52 in f                                                                  │
│                                                                                                                      │
│   51 │   │   │   │   pr.enable()                                                                                     │
│ ❱ 52 │   │   │   res = func(*args, **kwargs)                                                                         │
│   53 │   │   │   if res is None:                                                                                     │
│                                                                                                                      │
│ /home/webui/automatic/modules/call_queue.py:33 in f                                                                  │
│                                                                                                                      │
│   32 │   │   │   try:                                                                                                │
│ ❱ 33 │   │   │   │   res = func(*args, **kwargs)                                                                     │
│   34 │   │   │   │   progress.record_results(id_task, res)                                                           │
│                                                                                                                      │
│                                               ... 18 frames hidden ...                                               │
│                                                                                                                      │
│ /home/webui/automatic/venv/lib/python3.10/site-packages/torch/nn/modules/module.py:1501 in _call_impl                │
│                                                                                                                      │
│   1500 │   │   │   │   or _global_forward_hooks or _global_forward_pre_hooks):                                       │
│ ❱ 1501 │   │   │   return forward_call(*args, **kwargs)                                                              │
│   1502 │   │   # Do not call functions when jit is used                                                              │
│                                                                                                                      │
│ /home/webui/automatic/repositories/stable-diffusion-stability-ai/ldm/models/diffusion/ddpm.py:1337 in forward        │
│                                                                                                                      │
│   1336 │   │   elif self.conditioning_key == 'hybrid':                                                               │
│ ❱ 1337 │   │   │   xc = torch.cat([x] + c_concat, dim=1)                                                             │
│   1338 │   │   │   cc = torch.cat(c_crossattn, 1)                                                                    │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 256 but got size 128 for tensor number 1 in the list.

![front-pose](https://github.com/vladmandic/automatic/assets/82608399/8f152e5c-f594-4c14-9662-f3e3b0bd1db5)

### Version Platform Description

commit 8c981159141a6c2abfa210a2446d9b10342b99fc (HEAD -> master, origin/master, origin/HEAD)
Author: Vladimir Mandic <mandic00@live.com>
Date:   Thu May 11 14:20:27 2023 -0400

**Comment by adjarar** [comment]
My mistake, the inpaint model was selected when I tried to do this. Would be nice if a warning was given if that is the case. It's a very easy mistake to make.

**Comment by vladmandic** [comment]
yes, that would be a good feature request to detect inpaint model automatically.
