### ISSUE TITLE
[Issue]: Visual Issue: Some drop down menus are white on cyan when selected. ..PEBKAC

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#888]
### Issue Description

In the From Text and From Image tabs, the Upscaler (enabled in Postprocessing Settings) and the Script dropdown menus display light-grey background when nothing is selected and a cyan background when something is selected, making reading these selections very difficult to read;

Before selection;
![image](https://github.com/vladmandic/automatic/assets/1969381/0835aef1-212c-430a-8b8f-248171730b4d)

After selection;
![image](https://github.com/vladmandic/automatic/assets/1969381/e91b1ba6-35cd-49e9-886d-96d33b8d7b11)

These colours should probably match all other dropdown menus, eg: the Sampler dropdown menu;
![image](https://github.com/vladmandic/automatic/assets/1969381/867d73be-783e-4907-89f2-6c0ac56fc039)

This seems to be theme independent.

### Version Platform Description

08:21:43-285925 INFO     Version: 8c981159 Thu May 11 14:20:27 2023 -0400

Windows 10, Chrome.

**Comment by brknsoul** [comment]
You added the "question" label, but what's the question? ;-)

**Comment by vladmandic** [comment]
using which theme? that doesn't look like deafult black-orange.

**Comment by vladmandic** [comment]
> You added the "question" label, but what's the question? ;-)

i was just about to press submit :)

**Comment by brknsoul** [comment]
It's on all themes.

**Comment by vladmandic** [comment]
but the controls for `samplers` and `scripts` are the same components and they share the same css, there is no separate styling.
plus i checked entire css, and there is no cyan-like being used anywhere.
just as a test, can you try with edge since you're already on windows 10?

**Comment by brknsoul** [comment]
> edge

ew.. ok.. ;-)

Same result

![image](https://github.com/vladmandic/automatic/assets/1969381/6273792b-973d-48fb-996c-c732a9632913)

**Comment by vladmandic** [comment]
i'm at a loss - don't know if you're comfortable with browser inspector (f12)?
if yes, select element in question and look which value is it picking up for `background`? it should be `var(--input-background-fill)`. then click on that value and see where it takes you - it should be `var(--neutral-800)`

![image](https://github.com/vladmandic/automatic/assets/57876960/4faf4c88-ba12-4fb5-8437-6b43cbf0af11)

**Comment by brknsoul** [comment]
I'm reinstalling sd.next using
`git clone -b directml-stable https://github.com/vladmandic/automatic`

I'll report back when done.

**Comment by vladmandic** [comment]
i don't think reinstalling will make a difference, this is about browser not using correct style because something is overriding it.

but why are you cloning directml-stable branch - that does have older styles, so issues are possible? but that branch is not needed anymore - it has been fully incorporated into main branch. clone from master and just run `webui --use-directml`

**Comment by brknsoul** [comment]
>  run `webui --use-directml`

D'oh! I kinda wish that was in the main readme.md that's displayed in the Code tab of this git ;-)

**Comment by vladmandic** [comment]
yeah, i'm way behind updating readme - too many issues to deal with :)

**Comment by brknsoul** [comment]
Ah shit.. shitty shit shit crap!

TOTALLY MY BAD! 

![image](https://github.com/vladmandic/automatic/assets/1969381/a593d248-97eb-4f8f-9129-ed6ba69e9e55)
