### ISSUE TITLE
[Issue] [low priority]: The UI Theme selection list needs updating

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#889]
### Issue Description

Some UI Themes previews are returning a 404 error, and cause the Theme to default to gradio-default (which is probably preferred behaviour).

Also, some gradio themes are duplicated in the list.

### Version Platform Description

Platform independent. 
08:21:43-285925 INFO     Version: 8c981159 Thu May 11 14:20:27 2023 -0400

**Comment by vladmandic** [comment]
i've fixed duplicates. regarding broken links, click refresh button next to themes list in settings - list comes from huggingface.

**Comment by brknsoul** [comment]
Wow, fast work!
