### ISSUE TITLE
[Issue]: New Extensions UI issue; can't uninstall, updating enables disabled extensions.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#894]
### Issue Description

Using the Uninstall button on an extension doesn't seem to do anything. (Yet?)

Using the Update Installed Extensions button seems to re-enable previously disabled extensions.

Suggestion: Include a  "Check for Updates" button and have each updatable extension display a button that can individually update  that extension.

### Version Platform Description

Version: df2cfd51 Thu May 11 20:36:34 2023 -0400
Win10, Chrome

**Comment by vladmandic** [comment]
uninstall works - and extension immediately gets marked as uninstalled and removed from disk. but you need to restart the server (which also reloads reloads browser) to actually unload it from memory.

upadate does not re-enable extensions. but if you disabled an extension, you need to "apply" first. if you just uncheck box, it doesn't mean anything until you apply changes so when you click update, it will appear as you say.

regarding suggestion to allow per-extension update - yes, that's coming soon.

if i missed something, update here and i'll reopen the issue.

**Comment by vladmandic** [comment]
update: new version just published, enables per-extension individual update and much better last-updated time checks to know in advance which extension has available updates.
