### ISSUE TITLE
[Issue]: unable to install extensions

### ISSUE THREAD

**Issue by SAC020** [vladmandic/automatic#895]
### Issue Description

Fresh new install

Server arguments: []

```
11:49:13-728655 ERROR    Failed reading extension data from Git repository: sd-webui-model-converter: Commit.__init__()
                         missing 2 required positional arguments: 'repo' and 'binsha'
11:49:14-051616 ERROR    Failed reading extension data from Git repository: stable-diffusion-webui-images-browser:
                         Commit.__init__() missing 2 required positional arguments: 'repo' and 'binsha'
11:49:14-109886 ERROR    Failed reading extension data from Git repository: seed_travel: Commit.__init__() missing 2
                         required positional arguments: 'repo' and 'binsha'
11:49:14-433329 ERROR    Failed reading extension data from Git repository: sd-extension-steps-animation:
                         Commit.__init__() missing 2 required positional arguments: 'repo' and 'binsha'
11:49:14-484832 ERROR    Failed reading extension data from Git repository: sd-dynamic-thresholding: Commit.__init__()
                         missing 2 required positional arguments: 'repo' and 'binsha'
11:49:14-803897 ERROR    Failed reading extension data from Git repository: sd-webui-controlnet: Commit.__init__()
                         missing 2 required positional arguments: 'repo' and 'binsha'
11:49:14-855572 ERROR    Failed reading extension data from Git repository: sd-extension-system-info: Commit.__init__()
                         missing 2 required positional arguments: 'repo' and 'binsha'
11:49:15-187945 ERROR    Failed reading extension data from Git repository: sd-extension-aesthetic-scorer:
                         Commit.__init__() missing 2 required positional arguments: 'repo' and 'binsha'
11:49:15-241020 ERROR    Failed reading extension data from Git repository: clip-interrogator-ext: Commit.__init__()
                         missing 2 required positional arguments: 'repo' and 'binsha'
11:49:15-564454 ERROR    Failed reading extension data from Git repository: multidiffusion-upscaler-for-automatic1111:
                         Commit.__init__() missing 2 required positional arguments: 'repo' and 'binsha'
11:49:15-615850 ERROR    Failed reading extension data from Git repository: stable-diffusion-webui-rembg:
                         Commit.__init__() missing 2 required positional arguments: 'repo' and 'binsha'
11:49:15-935831 ERROR    Failed reading extension data from Git repository: a1111-sd-webui-lycoris: Commit.__init__()
                         missing 2 required positional arguments: 'repo' and 'binsha'
```

### Version Platform Description

Version: 1943bfea Thu May 11 22:24:12 2023 -0400

**Comment by vladmandic** [comment]
Github is having some intermittent issues last few days, it's not an app problem.
You can check on http://githubstatus.com

**Comment by PeggyFree** [comment]
Maybe there is a real problem on client side, I currently have the same error while the github statut is full green. Can we re-open this issue?

`20:36:01-480105 INFO     Installing extension: https://github.com/glucauze/sd-webui-faceswaplab into
                         C:\Users\PeggyFree\automatic\extensions\sd-webui-faceswaplab
20:36:04-898681 ERROR    gradio call: TypeError
┌────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────┐
│ C:\Users\PeggyFree\automatic\modules\call_queue.py:58 in f                                                       │
│                                                                                                               │
│    57 │   │   │   │   pr.enable()                                                                             │
│ >  58 │   │   │   res = func(*args, **kwargs)                                                                 │
│    59 │   │   │   if res is None:                                                                             │
│                                                                                                               │
│ C:\Users\PeggyFree\automatic\modules\ui_extensions.py:184 in install_extension                                   │
│                                                                                                               │
│   183 │   shared.log.info(f'Extension install: {extension_to_install}')                                       │
│ > 184 │   code, message = install_extension_from_url(None, extension_to_install, None, search_                │
│   185 │   return code, message                                                                                │
│                                                                                                               │
│                                            ... 9 frames hidden ...                                            │
│                                                                                                               │
│ C:\Users\PeggyFree\automatic\venv\lib\site-packages\git\objects\base.py:63 in __init__                           │
│                                                                                                               │
│    62 │   │   :param binsha: 20 byte SHA1"""                                                                  │
│ >  63 │   │   super(Object, self).__init__()                                                                  │
│    64 │   │   self.repo = repo                                                                                │
│                                                                                                               │
│ C:\Users\PeggyFree\AppData\Local\Programs\Python\Python310\lib\typing.py:1422 in _no_init_or_replace_init        │
│                                                                                                               │
│   1421 │                                                                                                      │
│ > 1422 │   cls.__init__(self, *args, **kwargs)                                                                │
│   1423                                                                                                        │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: Commit.__init__() missing 2 required positional arguments: 'repo' and 'binsha'`

**Comment by vladmandic** [comment]
this is a totally different issue, so no, cant reopen closed one. please create a new issue.
