### ISSUE TITLE
[Feature]: add torch_directml to the requirement.txt in the directml branch

### ISSUE THREAD

**Issue by wuzhican** [vladmandic/automatic#896]
### Feature description

as the question，add torch_directml tothe requirement to autoinstall the dependence。

**Comment by vladmandic** [comment]
no. even `torch` is not in `requirements.txt` as its handled dynamically by `install.py`
if you use `webui --use-directml`, it will check if `torch-directml` is installed and if not, it will install correct version automatically.
and there there is no need to use directml branch, functionality has been included in the master branch, just use flag `--use-directml`
