### ISSUE TITLE
[Issue] Lora models not loading when they are outside installation folder

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#898]
### Discussed in https://github.com/vladmandic/automatic/discussions/897

<div type='discussions-op-text'>

<sup>Originally posted by **elen07zz** May 12, 2023</sup>
Hello, no lora is being loaded if it is not the default location.
I tried to change the default location to the one I use in automatic1111
but it does not show any, but it seems to detect the subfolders inside, but without any content.

/home/user/stable-diffusion-webui/models/Lora

</div>

**Comment by fabiobtex** [comment]
Just to add, same with ESRGAN upscalers

Both Lora and upscalers were working fine before the last updates

**Comment by jasparagus** [comment]
Summary for me (which things with "moved" directories are/are not appearing):

**NOK:**
LoRA
LyCORIS

**OK:**
TI + Models

**Not tested:** 
Hypernetworks

**Note:**
I tested manually calling a LoRA (e.g. manually inputting <lora:example:1> into the prompt), so it seems the code can't find them. I get the (expected) WARNING:
_11:02:28-068153 WARNING  Could not find Lora with name example_

**Comment by vladmandic** [comment]
fixed.

**Comment by Flaegster** [comment]
Fun - but how did you fix it?

**Comment by vladmandic** [comment]
by making code changes to correctly scan user-defined folders?
