### ISSUE TITLE
[Issue]: extension access disabled because of command line flags

### ISSUE THREAD

**Issue by sebaxakerhtc** [vladmandic/automatic#901]
### Issue Description

Hi there!
Reinstalled Windows, cloned repo and now i see "extension access disabled because of command line flags"
In original branch that was solved with "--enable-insecure-extension-access" but this parameter is not work here. How to solve it here?

Command line args:
`--listen --auth user:password --api-auth apiuser:apipassword --upgrade`

### Version Platform Description

Windows, Firefox

**Comment by vladmandic** [comment]
run `webui --help`, it shows everything.
here is just `--insecure`.
