### ISSUE TITLE
[Issue]: Question about git status in installer.py breaking Google Colab

### ISSUE THREAD

**Issue by AI-Casanova** [vladmandic/automatic#903]
### Issue Description

Are these lines needed?

 https://github.com/vladmandic/automatic/blob/1921504e6478c61fd368970eb5e481fbaf934365/installer.py#L483-L486 

Google Colab has an issue with `git status`, ever since they upgraded to Python 3.10

I can't find another reference to `_status` and was wondering if it could be removed as well, as that corrects the inability to use `launch.py` without `--skip-git`

### Version Platform Description

Version: 1921504e Fri May 12 15:58:00 2023 -0400       
Google Colab

**Comment by vladmandic** [comment]
done.
