### ISSUE TITLE
[Feature]: Browser notification

### ISSUE THREAD

**Issue by razvanab** [vladmandic/automatic#906]
### Feature description

Can you please add some sort of browser notification once the image has been generated?
Something like this maybe.

![Screenshot 2023-05-13 044559](https://github.com/vladmandic/automatic/assets/2854730/db5ae2af-f96b-4964-85c1-125cd4b0454c)

**Comment by vladmandic** [comment]
they exist, but only if browser is not in focus.
- as notification (but most browsers nowadays block notifications by default, you need to allow it)
- as sound (disabled by default, enable in settings -> live preview -> play sound)

**Comment by razvanab** [comment]
Thank you.
