### ISSUE TITLE
[Feature]: Ability to save current UI settings

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#909]
### Feature description

It seems that one has to manually edit the ui-config.json file to alter default settings. I'm mainly talking about these settings;
![image](https://github.com/vladmandic/automatic/assets/1969381/2a119740-b03b-423b-aa12-828cac62b39a)

It'd be nice to have a button that updates ui-config.json with new desired default settings.
And perhaps a 'oh shit I messed up' button to restore settings back to installed defaults (UniPC/20 steps/512x512/etc/etc)

### Version Platform Description

n/a

**Comment by gnadenlos** [comment]
Even better would be a good built-in preset solution that could save different combinations of settings.

**Comment by brknsoul** [comment]
There are extensions for this, but I'm talking about 'boot up' settings. I imagine most people have a comfortable set of initial generation settings and then adjust things afterward as needed.

**Comment by vladmandic** [comment]
and none of the extensions work properly as list of settings they support is a hard coded list of strings. any changes to ui (rename/add/remove) breaks them.

this is a very valid feature request, but at the moment it would be quite hard to implement. i'll keep it in the backlog.

**Comment by dstults** [comment]
Just reached out in Discord, would be happy to help with the coding and engage in a thread/discussion on how to approach this. It also bears some likeness to this issue: https://github.com/vladmandic/automatic/issues/1247 and both would probably need to be considered when approaching these changes especially if placed into the base UI and not as part of an extension.

**Comment by vladmandic** [comment]
Feature has been added.
