### ISSUE TITLE
[Issue]: rocm detection tries rocminfo when /dev/kfd is sufficient.

### ISSUE THREAD

**Issue by brimston3** [vladmandic/automatic#910]
### Issue Description

On systems without the AMD rocm package installed, torch+rocm (as would be installed by the installer.py script) will pull in enough to run without any external packages. The check for rocminfo can be reduced to `os.path.exists('/dev/kfd')` and not require installing AMD's rocm sdk package.

Related to issue #217.

### Version Platform Description

Version: a2485cf7 Fri May 12 21:12:24 2023 -0400
Ubuntu 22.04

**Comment by vladmandic** [comment]
i'll add that as OR statement. but once AMD allows running ROCm in a VM, that path will likely changed, for example CUDA inside WSL2 maps to /dev/dxg which is a VDDM virtual display.
