### ISSUE TITLE
[Feature]: Stable Animation SDK, a powerful text-to-animation tool for developers

### ISSUE THREAD

**Issue by Metalica** [vladmandic/automatic#911]
### Feature description

Stability AI releases Stable Animation SDK, a powerful text-to-animation tool for developers.

- Text to animation: Users input a text prompt (as with Stable Diffusion) and tweak various parameters to produce an animation.
- Text input + initial image input: Users provide an initial image that acts as the starting point of their animation. A text prompt is used in conjunction with the image to produce the final output animation.
- Input video + text input: Users provide an initial video to base their animation on. By tweaking various parameters, they arrive at a final output animation that is additionally guided by a text prompt.

**Source:** https://stability.ai/blog/stable-animation-sdk

**Comment by vladmandic** [comment]
its only available via api. if stabilityai actually ever releases the code and the model, i'd be more than interested in integrating it.
