### ISSUE TITLE
[Issue]: Selecting Image obscures Send To buttons.

### ISSUE THREAD

**Issue by AI-Casanova** [vladmandic/automatic#916]
### Issue Description

Within the last few commits, selecting a result image in the lightbox obscures the buttons below it, but I can't seem to find the commit at fault.

![image](https://github.com/vladmandic/automatic/assets/54461896/c267b795-bca5-4839-b8d1-3e273dbac4c2)
(notice the gray bar and occluded prompt in the lower portion)

Is there somewhere specific I can look to track down the issue?

### Version Platform Description

Version: a2485cf7 Fri May 12 21:12:24 2023 -0400  
Google Colab

**Comment by AI-Casanova** [comment]
Found it https://github.com/vladmandic/automatic/blob/5905fcb97e341a6518dec31167634f076d095a14/javascript/black-orange.css#L93

Reverting `height: 45vh` fixed my issue

**Comment by vladmandic** [comment]
what is the max value that works for you? i still want to have slightly bigger default than gradio original?

**Comment by AI-Casanova** [comment]
Will experiment when I get back to the computer.

**Comment by AI-Casanova** [comment]
Ok, I'm getting mixed results. if I f12 and add height 45vh to an already loaded gradio, the buttons and gen parameters move down to compensate.

If I add it directly to the css file it does not, and overwrites like I showed above.

**Comment by AI-Casanova** [comment]
Actually cancel that, it works because the inspection box is open, changing my window to an approximate square, as soon as I close the window, it goes back to the error behavior.

**Comment by AI-Casanova** [comment]
Without height (note the screen sizes)
![image](https://github.com/vladmandic/automatic/assets/54461896/95875eaa-8118-4e30-89ba-334f17a3ab8e)
![image](https://github.com/vladmandic/automatic/assets/54461896/dbfb6530-0392-489e-aa1c-da9e8b52c19a)
With height
![image](https://github.com/vladmandic/automatic/assets/54461896/555c41b8-6a8c-4cc7-9129-3db00308275f)
![image](https://github.com/vladmandic/automatic/assets/54461896/6e37c6a3-4a11-4d1f-a2a5-cbf33da2517c)

**Comment by vladmandic** [comment]
i'll remove it.
