### ISSUE TITLE
[Issue]: From Text prompts don't run on AMD GPU out-of-the-box on Windows 10

### ISSUE THREAD

**Issue by khusain** [vladmandic/automatic#917]
### Issue Description

**Steps Performed**
- 	git clone https://github.com/vladmandic/automatic.git
- 	run webui.bat
- 	Perform a From Text generation using Prompt "Man holding a video game controller" with the default settings

**Expected Result**
Image is generated using the GPU

**Actual Result**
Image is generated using the CPU. Took 2 minutes and 38 seconds to generate.

The AUTOMATIC1111/stable-diffusion-webui project generates images using my 7900 XT. Considering that this project is a fork of it, I assumed that no special setup would be needed to enable AMD support. I also didn't see any special steps for it.

I also restarted my computer after the first run, but encountered the same result.

### Version Platform Description

Version: a2485cf7 Fri May 12 21:12:24 2023 -0400

Microsoft Windows 10 Pro Version 10.0.19045 Build 19045
AMD Ryzen 9 5900X
32GB Ram
Radeon RX 7900 XT with Adrenalin version 23.4.3
Mozilla Firefox 113.0.1 (64-bit)
Python 3.10.11

Attached Setup.log file
[setup.log](https://github.com/vladmandic/automatic/files/11469937/setup.log)

**Comment by howarduong** [comment]
In fact, it does not support AMD graphics cards, you need to download another version

**Comment by vladmandic** [comment]
> The AUTOMATIC1111/stable-diffusion-webui project generates images using my 7900 XT. Considering that this project is a fork of it, I assumed that no special setup would be needed to enable AMD support. I also didn't see any special steps for it.

that is not really true:
- first, amd does not have rocm support for windows, only linux.
- second, you can run using your gpu using `torch-direcml` and on a1111 that is fully manual setup process.

here, you need to say `webui --use-directml`

i suggest to upgrade to latest version first as i've just redone some related code.

@howarduong i don't know what you're referring to.

**Comment by howarduong** [comment]
I just saw you update the code for DirectML. So buddy, how do I need to turn on --use-directml to support AMD graphics cards?

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: Vladimir ***@***.***>
发送时间: 2023年5月13日 23:33
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [vladmandic/automatic] [Issue]: From Text prompts don't run on AMD GPU out-of-the-box on Windows 10 (Issue #917)


Closed #917<https://github.com/vladmandic/automatic/issues/917> as completed.

―

**Comment by vladmandic** [comment]
`webui.bat --use-directml`

or add it as param in windows shortcut.

**Comment by khusain** [comment]
> here, you need to say webui --use-directml

This resolved my issue, thanks!

This step should be added to the Run section on the README so that others don't run into the same issue I did.

**Comment by vladmandic** [comment]
yeah, i know, i'm waaay behind updating README, too many issues :)
