### ISSUE TITLE
[Issue]: using torch-directml in fp16 fails

### ISSUE THREAD

**Issue by vladmandic** [vladmandic/automatic#918]
### Issue Description

seems that torch-directml itself has no issues with fp16, but autocast operations are not working as expected, so if any part of the model ends up as fp32, it will result in runtime error.

for now, i've set:

`modules/devices.py:set_cuda_params()`
```python
    if shared.cmd_opts.use_directml:
        shared.opts.no_half = True
```

without that, error happens in `modules/processing.py`:
```python
    with devices.without_autocast() if devices.unet_needs_upcast else devices.autocast():
        samples_ddim = p.sample(conditioning=c, unconditional_conditioning=uc, seeds=seeds, subseeds=subseeds, subseed_strength=p.subseed_strength, prompts=prompts)
```

error is:
```log
RuntimeError: mat1 and mat2 must have the same dtype
```

checking `c.batch[0][0].schedules[0].cond.dtype`, its always `torch.float32` even if model dtype is `torch.float16`.
(btw that object is created in `modules/prompt_parser.py:reconstruct_multicond_batch()`)

first error is typically while `lycoris` module is parsing text encodings, but that's just a tip of the iceberg.

`extensions-builtin/a1111-sd-webui-lycoris/lycoris.py:lyco_Linear_forward()`
> 733 │   return torch.nn.Linear_forward_before_lyco(self, input)

**Comment by lshqqytiger** [comment]
I implemented alternative autocast for this, it worked very fine on my fork, but it generates broken images on this repo.

## Tests

### My fork (of AUTOMATIC1111)
--opt-sub-quad-attention
```
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:30<00:00,  1.54s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:27<00:00,  1.36s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:24<00:00,  1.24s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:24<00:00,  1.23s/it]
```
Generated normal images.

### My fork
--no-half --opt-sub-quad-attention
```
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:23<00:00,  1.16s/it]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:19<00:00,  1.02it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:19<00:00,  1.05it/s]
Total progress: 100%|██████████████████████████████████████████████████████████████████| 20/20 [00:18<00:00,  1.06it/s]
```
Generated normal images.

### automatic/directml-develop
Precision type: Autocast
Device precision type: FP16
- [ ] Use full precision for model (--no-half)
- [ ] Use full precision for VAE (--no-half-vae)

Cross-attention optimization method: Sub-quadratic
```
Setting Torch parameters: dtype=torch.float16 vae=torch.float16 unet=torch.float16
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:29<00:00,  1.49s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:24<00:00,  1.24s/it]
```
Generated weird images.

### automatic/directml-develop
Precision type: Autocast
Device precision type: FP16
- [x] Use full precision for model (--no-half)
- [x] Use full precision for VAE (--no-half-vae)

Cross-attention optimization method: Sub-quadratic
```
Setting Torch parameters: dtype=torch.float32 vae=torch.float32 unet=torch.float32
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:23<00:00,  1.18s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:19<00:00,  1.05it/s]
```
Generated normal images.

**Comment by vladmandic** [comment]
`dml/amp` was completely missing in my repo
otherwise, there were few more instances where device was set to `cpu` instead of dml device, so that may what was causing the difference

and it works fine, no corrupt images

but...performance is 1/3 of native cuda performance on my test system?
don't know if thats normal or due to SDP cross-optimization or something else
(maybe i messed up something in your directml code?)
can you compare my branch with yours?

using direct-ml

- fp16 with autocast: ~2 it/s
- fp32 no autocast: ~1 it/s

using cuda:

- fp16 with autocast: ~6 it/s
- fp32 no autocast: ~3 it/s

**Comment by lshqqytiger** [comment]
`dml/amp` is defined in modules/dml.
The performance seems to be fine.
It is related to how DirectML works. (https://github.com/microsoft/DirectML/issues/386#issuecomment-1432642471)
But the performance will be better with sub quadratic attention (sdp attention for who has more vram) and medvram.
The excessive memory consumption of DirectML is related to the tensor implementation of DirectML. (https://github.com/microsoft/DirectML/issues/425)

**Comment by vladmandic** [comment]
> dml/amp is defined in modules/dml (directml-develop tree).

yup, saw that and copied to `master`
if you say performance/memory are as-expected, that's fine by me, i don't have any directml experience.

so only issue left seems to be compatibility with loras? see #952

**Comment by vladmandic** [comment]
yeah, i've tested that and no issues. also one more issue created over night was about switching models 1.5 -> 2.1 causing some problems, but cannot reproduce that as well.
anyhow, closing this issue - thanks for the help!
