### ISSUE TITLE
[Issue]: Slow rendering speed on ROCm | Low power draw and utilization

### ISSUE THREAD

**Issue by CNR0706** [vladmandic/automatic#919]
### Issue Description

After a recent update the rendering speed on my 6700XT has dropped significantly on lower resolutions (<1024p). (at 512x512: ~7.6 it/s >> ~1.0 it/s)

I used to be able to work around this by turning on model compilation, rendering an image and then turning it off again. This would fix the rendering speed until I reboot my computer. However, this does not seem to work anymore as it complains about:

17:30:04-834464 WARNING  Model compile not supported: torch._dynamo.config.log_level does not exist

I've tried changing the power profile to "compute" using CoreCTRL (no effect)
I've tried locking the clockspeed to max using CoreCTRL (no effect)
I've tried putting a load on the GPU using a stress test (no effect)
I've tried different pytorch versions (default vs. nightly) (no effect)
I've tried Automatic1111 (works like expected)

### Version Platform Description

CPU:          R5 3600 (undervolt)
RAM:         DDR4 3600 MT/s CL16 (OC)
GPU:          RX 6700XT (undervolt)
OS:             openSuSE Tumbleweed Linux (up to date)
Kernel:       Linux 6.3.1-2-default
ROCm:       5.5.0 (from official AMD repo)
Mesa:         23.0.3
Torch:         2.1.0.dev20230513+rocm5.4.2
python:      3.10.9

automatic: Version: d96ab6a1 Sat May 13 11:21:11 2023 -0400

launch command: ./webui.sh --medvram --experimental --upgrade --listen (after entering venv)

**Comment by vladmandic** [comment]
this was a known issue where amd gpu stays in wrong power state and needs a "nudge" to wake up to full potential.
but your workaround is informative.

i just made some changes, can you try updating the repo?

**Comment by CNR0706** [comment]
> this was a known issue where amd gpu stays in wrong power state and needs a "nudge" to wake up to full potential. but your workaround is informative.
> 
> i just made some changes, can you try updating the repo?

Sure. I'll try it now.
