### ISSUE TITLE
[Issue]: DirectML.memory_stats() missing 1 required positional argument: 'device'

### ISSUE THREAD

**Issue by Lumpsack** [vladmandic/automatic#921]
### Issue Description

Thanks for sorting the issue where it would not launch, that worked, but now when going to create an image there is a new problem.

I searched and found that lshqqytiger had fixed this in his version and the code looks to match what was changed, so not sure where to go now.

![image](https://github.com/vladmandic/automatic/assets/127429289/75b27393-0456-48f7-ac0f-ddb15d918fdc)

### Version Platform Description

Windows 11, Edge, version: a6522709 Sat May 13 12:26:00 2023

**Comment by vladmandic** [comment]
fixed.
