### ISSUE TITLE
[Issue]: AssertionError: extension access disabled because of command line flags

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#923]
### Issue Description

Can't install extensions because of this error.
Any hints?

18:28:22-256866 INFO     Extension install: https://github.com/Kahsolt/stable-diffusion-webui-sonar.git
18:28:22-259830 ERROR    gradio call: AssertionError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\modules\call_queue.py:56 in f                                                             │
│                                                                                                                     │
│    55 │   │   │   │   pr.enable()                                                                                   │
│ >  56 │   │   │   res = func(*args, **kwargs)                                                                       │
│    57 │   │   │   if res is None:                                                                                   │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\modules\ui_extensions.py:157 in install_extension                                         │
│                                                                                                                     │
│   156 │   shared.log.info(f'Extension install: {extension_to_install}')                                             │
│ > 157 │   code, message = install_extension_from_url(None, extension_to_install, None, search_                      │
│   158 │   return code, message                                                                                      │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\modules\ui_extensions.py:115 in install_extension_from_url                                │
│                                                                                                                     │
│   114 def install_extension_from_url(dirname, url, branch_name, search_text, sort_column):                          │
│ > 115 │   check_access()                                                                                            │
│   116 │   assert url, 'No URL specified'                                                                            │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\modules\ui_extensions.py:52 in check_access                                               │
│                                                                                                                     │
│    51 def check_access():                                                                                           │
│ >  52 │   assert not shared.cmd_opts.disable_extension_access, "extension access disabled beca                      │
│    53                                                                                                               │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AssertionError: extension access disabled because of command line flags

### Version Platform Description

Win10, FF106
Version: c46f0dbd Sat May 13 12:55:50 2023 -0400

**Comment by vladmandic** [comment]
you're using either `--share` or `--listen` params and in that case, app by default runs in secure mode so extensions cannot be modified.
add `--insecure` to allow extensions modifications explicitly.

**Comment by Woisek** [comment]
I have indeed --listen enabled, so I can access the WebUI from my local network. What drawback has --insecure?

**Comment by vladmandic** [comment]
that's pretty much it - it allows options and extensions to be modified, otherwise its locked.
