### ISSUE TITLE
[Feature]: The ability to use the ui over http using the ip+port number

### ISSUE THREAD

**Issue by adjarar** [vladmandic/automatic#930]
### Feature description

I don't know how hard this is to implement using gradio, but it's very annoying to have to login over ssh to get the gradio link.

**Comment by arshesney** [comment]
Add ```--listen``` flag for the server to listen on all interfaces.

**Comment by vladmandic** [comment]
correct. then you can connect using your system IP (or external IP if you configure your router to port-forward).
