### ISSUE TITLE
[Issue]: The installation process is incorrect

### ISSUE THREAD

**Issue by howarduong** [vladmandic/automatic#933]
### Issue Description

hi buddy, I just re-cloned the code, and during the installation process, I found these errors, I don't know how to solve them,

Creating venv in directory D:\VladDiffusionAI\automatic\venv using python "C:\Users\Uong\AppData\Local\Programs\Python\Python310\python.exe"
Using VENV: D:\VladDiffusionAI\automatic\venv
11:20:10-561908 INFO     Starting SD.Next
11:20:10-561908 INFO     Python 3.10.6 on Windows
11:20:10-661690 INFO     Version: 926b8666 Sat May 13 16:42:01 2023 -0400
11:20:10-711658 INFO     Setting environment tuning
11:20:10-727102 INFO     Using CPU-only Torch
11:20:10-730067 INFO     Installing package: torch torchvision==0.15.1
11:21:31-683345 INFO     Torch 2.0.0+cpu
11:21:31-685346 INFO     Installing package: tensorflow==2.12.0
11:22:03-548687 INFO     Verifying requirements
11:22:03-557213 INFO     Installing package: addict
11:22:05-211041 INFO     Installing package: aenum
11:22:06-749580 INFO     Installing package: aiohttp
11:22:11-401249 INFO     Installing package: anyio
11:22:13-571283 INFO     Installing package: appdirs
11:22:15-004575 INFO     Installing package: astunparse
11:22:16-667319 INFO     Installing package: bitsandbytes
11:22:21-512219 INFO     Installing package: blendmodes
11:22:23-259700 INFO     Installing package: clean-fid
11:22:39-240064 INFO     Installing package: easydev
11:22:42-399391 INFO     Installing package: extcolors
11:22:44-243348 INFO     Installing package: facexlib
11:23:11-594282 INFO     Installing package: filetype
11:23:13-666173 INFO     Installing package: font-roboto
11:23:15-254871 INFO     Installing package: fonts
11:23:17-755227 INFO     Installing package: future
11:23:21-463141 INFO     Installing package: gdown
11:23:25-501186 INFO     Installing package: gfpgan
11:23:49-941876 INFO     Installing package: GitPython
11:23:53-348758 INFO     Installing package: httpcore
11:23:55-904909 INFO     Installing package: inflection
11:23:57-936007 INFO     Installing package: jsonmerge
11:24:00-853048 INFO     Installing package: kornia
11:24:06-127140 INFO     Installing package: lark
11:24:08-276609 INFO     Installing package: lmdb
11:24:09-745373 INFO     Installing package: lpips
11:24:11-795329 INFO     Installing package: numpy
11:24:21-389712 INFO     Installing package: omegaconf
11:24:25-593807 INFO     Installing package: open-clip-torch
11:24:35-921332 INFO     Installing package: opencv-contrib-python
11:24:39-779565 INFO     Installing package: piexif
11:24:41-862055 INFO     Installing package: Pillow
11:24:43-786637 INFO     Installing package: psutil
11:24:46-353696 INFO     Installing package: pyyaml
11:24:48-120781 INFO     Installing package: realesrgan
11:24:50-698993 INFO     Installing package: resize-right
11:24:52-842768 INFO     Installing package: rich
11:24:54-630594 INFO     Installing package: safetensors
11:24:57-153779 INFO     Installing package: scipy
11:24:59-003163 INFO     Installing package: tb_nightly
11:25:01-381878 INFO     Installing package: toml
11:25:03-564039 INFO     Installing package: torchdiffeq
11:25:05-907772 INFO     Installing package: torchsde
11:25:09-128330 INFO     Installing package: voluptuous
11:25:11-244663 INFO     Installing package: yapf
11:25:13-076643 INFO     Installing package: scikit-image
11:25:14-930422 INFO     Installing package: basicsr
11:25:16-889747 INFO     Installing package: requests==2.30.0
11:25:18-744596 INFO     Installing package: tqdm==4.65.0
11:25:20-580805 INFO     Installing package: accelerate==0.18.0
11:25:23-476103 INFO     Installing package: opencv-python==4.7.0.72
11:25:25-432077 INFO     Installing package: diffusers==0.16.1
11:25:31-059645 INFO     Installing package: einops==0.4.1
11:25:33-315011 INFO     Installing package: gradio==3.29.0
11:26:05-973884 INFO     Installing package: numexpr==2.8.4
11:26:08-976535 INFO     Installing package: pandas==1.5.3
11:26:28-964149 INFO     Installing package: protobuf==3.20.3
11:26:31-281384 INFO     Installing package: pytorch_lightning==1.9.4
11:26:41-049578 INFO     Installing package: transformers==4.26.1
11:27:00-846549 INFO     Installing package: timm==0.6.13
11:27:03-530365 INFO     Installing package: tomesd==0.1.2
11:27:06-423267 INFO     Installing package: urllib3==1.26.15
11:27:09-063661 INFO     Installing package: onnxruntime==1.14.0
11:27:16-024006 INFO     Running setup
11:27:16-027083 INFO     Installing packages
11:27:16-029080 INFO     Installing package:
                         git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
11:27:36-586125 ERROR    Error running pip: install --upgrade
                         git+https://github.com/openai/CLIP.git@d50d76daa670286dd6cacf3bcd80b5e4823fc8e1
11:27:36-590124 INFO     Installing repositories
11:28:10-780197 ERROR    Error running git: None / clone "https://github.com/CompVis/taming-transformers.git"
                         "D:\VladDiffusionAI\automatic\repositories\taming-transformers"
11:28:10-834218 ERROR    Error running git: None / -C "D:\VladDiffusionAI\automatic\repositories\taming-transformers"
                         checkout 3ba01b241669f5ade541ce990f7650a3b8f65318
11:28:31-997817 ERROR    Error running git: None / clone "https://github.com/crowsonkb/k-diffusion.git"
                         "D:\VladDiffusionAI\automatic\repositories\k-diffusion"
11:28:32-050089 ERROR    Error running git: None / -C "D:\VladDiffusionAI\automatic\repositories\k-diffusion" checkout
                         b43db16749d51055f813255eea2fdf1def801919
11:28:53-340058 ERROR    Error running git: None / clone "https://github.com/sczhou/CodeFormer.git"
                         "D:\VladDiffusionAI\automatic\repositories\CodeFormer"
11:28:53-392151 ERROR    Error running git: None / -C "D:\VladDiffusionAI\automatic\repositories\CodeFormer" checkout
                         c5b4593074ba6214284d6acd5f1719b6c5d739af
11:29:14-592630 ERROR    Error running git: None / clone "https://github.com/salesforce/BLIP.git"
                         "D:\VladDiffusionAI\automatic\repositories\BLIP"
11:29:14-648268 ERROR    Error running git: None / -C "D:\VladDiffusionAI\automatic\repositories\BLIP" checkout
                         48211a1594f1321b00f14c9f7a5b4813144b2fb9
11:29:14-652781 INFO     Installing submodules
11:34:12-954028 ERROR    Error running git: None / submodule --quiet update --init --recursive
11:34:12-957052 INFO     Updating submodules
11:34:50-957155 ERROR    Error running git: extensions-builtin/clip-interrogator-ext / pull origin main --autostash
                         --rebase --force
11:35:12-293244 ERROR    Error running git: extensions-builtin/multidiffusion-upscaler-for-automatic1111 / pull origin
                         main --autostash --rebase --force
11:35:33-664932 ERROR    Error running git: extensions-builtin/sd-dynamic-thresholding / pull origin master --autostash
                         --rebase --force
11:35:54-999853 ERROR    Error running git: extensions-builtin/sd-extension-steps-animation / pull origin main
                         --autostash --rebase --force
11:36:16-347559 ERROR    Error running git: extensions-builtin/sd-extension-system-info / pull origin main --autostash
                         --rebase --force
11:36:38-045524 ERROR    Error running git: extensions-builtin/sd-webui-controlnet / pull origin main --autostash
                         --rebase --force
11:36:59-361772 ERROR    Error running git: extensions-builtin/sd-webui-model-converter / pull origin main --autostash
                         --rebase --force
11:37:20-875555 ERROR    Error running git: extensions-builtin/seed_travel / pull origin main --autostash --rebase
                         --force
11:37:44-475465 ERROR    Error running git: D:\VladDiffusionAI\automatic\extensions-builtin\a1111-sd-webui-lycoris /
                         pull origin main --autostash --rebase --force
11:38:29-342026 ERROR    Error running git:
                         D:\VladDiffusionAI\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111 /
                         pull origin main --autostash --rebase --force
11:39:39-964370 ERROR    Error running git: D:\VladDiffusionAI\automatic\extensions-builtin\sd-webui-controlnet / pull
                         origin main --autostash --rebase --force
11:40:48-843424 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
11:40:48-851909 INFO     Updating Wiki
11:40:48-853909 WARNING  Setup complete with errors (21)
11:40:48-855909 WARNING  See log file for more details: setup.log
11:40:48-866007 INFO     Running extension preloading
Warning: Taming Transformers not found at path D:\VladDiffusionAI\automatic\repositories\taming-transformers\taming
Warning: CodeFormer not found at path D:\VladDiffusionAI\automatic\repositories\CodeFormer\inference_codeformer.py
Warning: BLIP not found at path D:\VladDiffusionAI\automatic\repositories\BLIP\models\blip.py
Warning: k_diffusion not found at path D:\VladDiffusionAI\automatic\repositories\k-diffusion\k_diffusion\sampling.py
11:40:48-916648 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\VladDiffusionAI\automatic\launch.py:141 in <module>                                                              │
│                                                                                                                     │
│   140                                                                                                               │
│ > 141     instance = start_server(immediate=True, server=None)                                                      │
│   142     while True:                                                                                               │
│                                                                                                                     │
│ D:\VladDiffusionAI\automatic\launch.py:116 in start_server                                                          │
│                                                                                                                     │
│   115     server = importlib.util.module_from_spec(module_spec)                                                     │
│ > 116     module_spec.loader.exec_module(server)                                                                    │
│   117     if args.test:                                                                                             │
│ in exec_module:883                                                                                                  │
│ in _call_with_frames_removed:241                                                                                    │
│                                                                                                                     │
│ D:\VladDiffusionAI\automatic\webui.py:35 in <module>                                                                │
│                                                                                                                     │
│    34 import ldm.modules.encoders.modules # pylint: disable=W0611,C0411                                             │
│ >  35 from modules import extra_networks, ui_extra_networks_checkpoints # pylint: disable=C041                      │
│    36 from modules import extra_networks_hypernet, ui_extra_networks_hypernets, ui_extra_netwo                      │
│                                                                                                                     │
│ D:\VladDiffusionAI\automatic\modules\ui_extra_networks_checkpoints.py:5 in <module>                                 │
│                                                                                                                     │
│    4                                                                                                                │
│ >  5 from modules import shared, ui_extra_networks, sd_models                                                       │
│    6                                                                                                                │
│                                                                                                                     │
│ D:\VladDiffusionAI\automatic\modules\ui_extra_networks.py:11 in <module>                                            │
│                                                                                                                     │
│    10 from modules import shared                                                                                    │
│ >  11 from modules.images import read_info_from_image                                                               │
│    12 from modules.generation_parameters_copypaste import image_from_url_text                                       │
│                                                                                                                     │
│ D:\VladDiffusionAI\automatic\modules\images.py:17 in <module>                                                       │
│                                                                                                                     │
│    16 from PIL import Image, ImageFont, ImageDraw, PngImagePlugin, ExifTags                                         │
│ >  17 from modules import sd_samplers, shared, script_callbacks, errors                                             │
│    18                                                                                                               │
│                                                                                                                     │
│ D:\VladDiffusionAI\automatic\modules\sd_samplers.py:1 in <module>                                                   │
│                                                                                                                     │
│ >  1 from modules import sd_samplers_compvis, sd_samplers_kdiffusion, shared                                        │
│    2                                                                                                                │
│                                                                                                                     │
│ D:\VladDiffusionAI\automatic\modules\sd_samplers_kdiffusion.py:4 in <module>                                        │
│                                                                                                                     │
│     3 import torch                                                                                                  │
│ >   4 import k_diffusion.sampling                                                                                   │
│     5 from modules import prompt_parser, devices, sd_samplers_common                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: No module named 'k_diffusion'

### Version Platform Description

win11 ，AMD4G，china

**Comment by howarduong** [comment]
Okay, I've successfully launched under the default webui .bat, but I have these issues when using --use-directml and don't know how to deal with them
Using VENV: D:\VladDiffusionAI\automatic\venv
12:49:41-555531 INFO     Starting SD.Next
12:49:41-571158 INFO     Python 3.10.6 on Windows
12:49:41-665230 INFO     Version: 926b8666 Sat May 13 16:42:01 2023 -0400
12:49:42-229423 INFO     Setting environment tuning
12:49:42-229423 INFO     Using DirectML Backend
12:49:44-182727 INFO     Torch 2.0.0+cpu
12:49:44-182727 WARNING  Torch reports CUDA not available
12:49:44-198324 INFO     Verifying requirements
12:49:44-260834 INFO     Running setup
12:49:44-276488 INFO     Installing packages
12:49:44-276488 INFO     Installing repositories
12:49:44-495281 INFO     Installing submodules
12:49:46-974979 INFO     Updating submodules
12:50:08-244073 ERROR    Error running git: extensions-builtin/a1111-sd-webui-lycoris / pull origin main --autostash
                         --rebase --force
12:51:03-302005 ERROR    Error running git: extensions-builtin/sd-extension-aesthetic-scorer / pull origin main
                         --autostash --rebase --force
12:51:44-272681 ERROR    Error running git: extensions-builtin/stable-diffusion-webui-images-browser / pull origin main
                         --autostash --rebase --force
12:52:05-584559 ERROR    Error running git: extensions-builtin/stable-diffusion-webui-rembg / pull origin master
                         --autostash --rebase --force
12:52:26-866389 ERROR    Error running git: modules/lora / pull origin main --autostash --rebase --force
12:52:48-458335 ERROR    Error running git: modules/lycoris / pull origin main --autostash --rebase --force
12:53:08-254783 ERROR    Error running git: wiki / pull origin master --autostash --rebase --force
12:53:29-580101 ERROR    Error running git: D:\VladDiffusionAI\automatic\extensions-builtin\a1111-sd-webui-lycoris /
                         pull origin main --autostash --rebase --force
12:53:50-893120 ERROR    Error running git: D:\VladDiffusionAI\automatic\extensions-builtin\clip-interrogator-ext /
                         pull origin main --autostash --rebase --force
12:54:19-364590 ERROR    Error running git:
                         D:\VladDiffusionAI\automatic\extensions-builtin\multidiffusion-upscaler-for-automatic1111 /
                         pull origin main --autostash --rebase --force
12:54:40-693473 ERROR    Error running git: D:\VladDiffusionAI\automatic\extensions-builtin\sd-dynamic-thresholding /
                         pull origin master --autostash --rebase --force
12:55:18-063220 ERROR    Error running git: D:\VladDiffusionAI\automatic\extensions-builtin\sd-extension-system-info /
                         pull origin main --autostash --rebase --force
12:55:39-456206 ERROR    Error running git: D:\VladDiffusionAI\automatic\extensions-builtin\sd-webui-controlnet / pull
                         origin main --autostash --rebase --force
12:56:15-951049 ERROR    Error running git: D:\VladDiffusionAI\automatic\extensions-builtin\seed_travel / pull origin
                         main --autostash --rebase --force
12:56:38-640535 ERROR    Error running git:
                         D:\VladDiffusionAI\automatic\extensions-builtin\stable-diffusion-webui-images-browser / pull
                         origin main --autostash --rebase --force
12:57:00-360833 ERROR    Error running git:
                         D:\VladDiffusionAI\automatic\extensions-builtin\stable-diffusion-webui-rembg / pull origin
                         master --autostash --rebase --force
12:57:00-782698 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
12:57:00-782698 INFO     Updating Wiki
12:57:22-136372 ERROR    Error running git: D:\VladDiffusionAI\automatic\wiki / pull origin master --autostash --rebase
                         --force
12:57:22-151938 WARNING  Setup complete with errors (17)
12:57:22-151938 WARNING  See log file for more details: setup.log
12:57:22-151938 INFO     Running extension preloading
12:57:22-167565 INFO     Server arguments: ['--use-directml']
No module 'xformers'. Proceeding without it.
Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\VladDiffusionAI\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "D:\VladDiffusionAI\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "D:\VladDiffusionAI\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "D:\VladDiffusionAI\automatic\launch.py", line 141, in <module>
    instance = start_server(immediate=True, server=None)
  File "D:\VladDiffusionAI\automatic\launch.py", line 116, in start_server
    module_spec.loader.exec_module(server)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\VladDiffusionAI\automatic\webui.py", line 29, in <module>
    from modules import import_hook # pylint: disable=W0611,C0411,C0412
  File "D:\VladDiffusionAI\automatic\modules\import_hook.py", line 2, in <module>
    from modules.shared import opts, log
  File "D:\VladDiffusionAI\automatic\modules\shared.py", line 607, in <module>
    devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan, devices.device_codeformer = (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_optimal_device() for x in ['sd', 'interrogate', 'gfpgan', 'esrgan', 'codeformer'])
  File "D:\VladDiffusionAI\automatic\modules\shared.py", line 607, in <genexpr>
    devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan, devices.device_codeformer = (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_optimal_device() for x in ['sd', 'interrogate', 'gfpgan', 'esrgan', 'codeformer'])
  File "D:\VladDiffusionAI\automatic\modules\devices.py", line 53, in get_optimal_device
    return torch.device(get_optimal_device_name())
  File "D:\VladDiffusionAI\automatic\modules\devices.py", line 41, in get_optimal_device_name
    import torch_directml # pylint: disable=import-error
ModuleNotFoundError: No module named 'torch_directml'

**Comment by howarduong** [comment]
I tried to turn on the agent, or turn off the agent, the content of the pop-up window is still the same, I think it is not ready for DirectML
Using VENV: D:\VladDiffusionAI\automatic\venv
19:35:10-189368 INFO     Starting SD.Next
19:35:10-189368 INFO     Python 3.10.6 on Windows
19:35:10-283920 INFO     Version: 926b8666 Sat May 13 16:42:01 2023 -0400
19:35:12-601874 INFO     Setting environment tuning
19:35:12-612438 INFO     Using DirectML Backend
19:35:14-450527 INFO     Torch 2.0.0+cpu
19:35:14-450527 WARNING  Torch reports CUDA not available
19:35:14-450527 INFO     Verifying requirements
19:35:14-529157 INFO     Running setup
19:35:14-529157 INFO     Installing packages
19:35:14-529157 INFO     Installing repositories
19:35:14-750212 INFO     Installing submodules
19:35:17-089296 INFO     Updating submodules
19:35:54-296314 ERROR    Error running git: extensions-builtin/a1111-sd-webui-lycoris / pull origin main --autostash
                         --rebase --force
19:36:15-641633 ERROR    Error running git: extensions-builtin/clip-interrogator-ext / pull origin main --autostash
                         --rebase --force
19:36:36-967476 ERROR    Error running git: extensions-builtin/multidiffusion-upscaler-for-automatic1111 / pull origin
                         main --autostash --rebase --force
19:36:58-315944 ERROR    Error running git: extensions-builtin/sd-dynamic-thresholding / pull origin master --autostash
                         --rebase --force
19:37:19-623024 ERROR    Error running git: extensions-builtin/sd-extension-aesthetic-scorer / pull origin main
                         --autostash --rebase --force
19:37:41-029961 ERROR    Error running git: extensions-builtin/sd-extension-steps-animation / pull origin main
                         --autostash --rebase --force
19:38:03-605551 ERROR    Error running git: extensions-builtin/sd-webui-controlnet / pull origin main --autostash
                         --rebase --force
19:38:45-097471 ERROR    Error running git: extensions-builtin/sd-webui-model-converter / pull origin main --autostash
                         --rebase --force
19:39:04-900817 ERROR    Error running git: extensions-builtin/seed_travel / pull origin main --autostash --rebase
                         --force
19:39:26-280008 ERROR    Error running git: extensions-builtin/stable-diffusion-webui-images-browser / pull origin main
                         --autostash --rebase --force
19:39:47-664153 ERROR    Error running git: extensions-builtin/stable-diffusion-webui-rembg / pull origin master
                         --autostash --rebase --force
19:40:09-019344 ERROR    Error running git: modules/lora / pull origin main --autostash --rebase --force
19:40:30-364807 ERROR    Error running git: modules/lycoris / pull origin main --autostash --rebase --force
19:40:51-623803 ERROR    Error running git: wiki / pull origin master --autostash --rebase --force
19:41:13-026987 ERROR    Error running git: D:\VladDiffusionAI\automatic\extensions-builtin\a1111-sd-webui-lycoris /
                         pull origin main --autostash --rebase --force
19:41:34-367981 ERROR    Error running git: D:\VladDiffusionAI\automatic\extensions-builtin\clip-interrogator-ext /
                         pull origin main --autostash --rebase --force
19:42:19-543674 ERROR    Error running git:
                         D:\VladDiffusionAI\automatic\extensions-builtin\sd-extension-aesthetic-scorer / pull origin
                         main --autostash --rebase --force
19:42:43-496386 ERROR    Error running git: D:\VladDiffusionAI\automatic\extensions-builtin\sd-webui-model-converter /
                         pull origin main --autostash --rebase --force
19:43:04-931311 ERROR    Error running git: D:\VladDiffusionAI\automatic\extensions-builtin\seed_travel / pull origin
                         main --autostash --rebase --force
19:43:26-647061 ERROR    Error running git:
                         D:\VladDiffusionAI\automatic\extensions-builtin\stable-diffusion-webui-images-browser / pull
                         origin main --autostash --rebase --force
19:43:48-383680 ERROR    Error running git:
                         D:\VladDiffusionAI\automatic\extensions-builtin\stable-diffusion-webui-rembg / pull origin
                         master --autostash --rebase --force
19:43:48-784412 INFO     Extensions enabled: ['a1111-sd-webui-lycoris', 'clip-interrogator-ext', 'LDSR', 'Lora',
                         'multidiffusion-upscaler-for-automatic1111', 'prompt-bracket-checker', 'ScuNET',
                         'sd-dynamic-thresholding', 'sd-extension-aesthetic-scorer', 'sd-extension-steps-animation',
                         'sd-extension-system-info', 'sd-webui-controlnet', 'sd-webui-model-converter', 'seed_travel',
                         'stable-diffusion-webui-images-browser', 'stable-diffusion-webui-rembg', 'SwinIR']
19:43:48-792452 INFO     Updating Wiki
19:44:10-137758 ERROR    Error running git: D:\VladDiffusionAI\automatic\wiki / pull origin master --autostash --rebase
                         --force
19:44:10-141247 WARNING  Setup complete with errors (22)
19:44:10-143456 WARNING  See log file for more details: setup.log
19:44:10-152025 INFO     Running extension preloading
19:44:10-159882 INFO     Server arguments: ['--use-directml']
No module 'xformers'. Proceeding without it.
Error in sys.excepthook:
Traceback (most recent call last):
  File "D:\VladDiffusionAI\automatic\venv\lib\site-packages\rich\traceback.py", line 103, in excepthook
    Traceback.from_exception(
  File "D:\VladDiffusionAI\automatic\venv\lib\site-packages\rich\traceback.py", line 346, in from_exception
    return cls(
  File "D:\VladDiffusionAI\automatic\venv\lib\site-packages\rich\traceback.py", line 280, in __init__
    for suppress_entity in suppress:
TypeError: 'module' object is not iterable

Original exception was:
Traceback (most recent call last):
  File "D:\VladDiffusionAI\automatic\launch.py", line 141, in <module>
    instance = start_server(immediate=True, server=None)
  File "D:\VladDiffusionAI\automatic\launch.py", line 116, in start_server
    module_spec.loader.exec_module(server)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\VladDiffusionAI\automatic\webui.py", line 29, in <module>
    from modules import import_hook # pylint: disable=W0611,C0411,C0412
  File "D:\VladDiffusionAI\automatic\modules\import_hook.py", line 2, in <module>
    from modules.shared import opts, log
  File "D:\VladDiffusionAI\automatic\modules\shared.py", line 607, in <module>
    devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan, devices.device_codeformer = (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_optimal_device() for x in ['sd', 'interrogate', 'gfpgan', 'esrgan', 'codeformer'])
  File "D:\VladDiffusionAI\automatic\modules\shared.py", line 607, in <genexpr>
    devices.device, devices.device_interrogate, devices.device_gfpgan, devices.device_esrgan, devices.device_codeformer = (devices.cpu if any(y in cmd_opts.use_cpu for y in [x, 'all']) else devices.get_optimal_device() for x in ['sd', 'interrogate', 'gfpgan', 'esrgan', 'codeformer'])
  File "D:\VladDiffusionAI\automatic\modules\devices.py", line 53, in get_optimal_device
    return torch.device(get_optimal_device_name())
  File "D:\VladDiffusionAI\automatic\modules\devices.py", line 41, in get_optimal_device_name
    import torch_directml # pylint: disable=import-error
ModuleNotFoundError: No module named 'torch_directml'

**Comment by vladmandic** [comment]
you're redoing same thing again and again and not actually reading what setup says:
> 19:44:10-141247 WARNING Setup complete with errors (22)
> 19:44:10-143456 WARNING See log file for more details: setup.log

since you're in china, quite possibly that access to github is blocked so no installation works. but if you check actual log, you'll know more. and if that is the case, ask a question in discussions how to configure github to work with proxy or something to bypass restrictions - that's not something i can do.

**Comment by vladmandic** [comment]
closing as no info provided. can be reopened if new info is available.
