### ISSUE TITLE
[Feature]: Show button should open actual location of image, rather than the base folder.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#934]
### Feature description

Clicking the show button will open up `text` instead of `text\2023-05-14`, where the image is located.

Also, it'd be nice if the show button would focus the file browser window. Currently the file browser window opens behind the web browser window.

### Version Platform Description

Version: 926b8666 Sat May 13 16:42:01 2023 -0400
Win10/Chrome

**Comment by vladmandic** [comment]
`show` will simply trigger whatever is the OS registered handler. how does that handler behave, its not under app control.
and does the os open it in focus or behind or whatever - that's up to os.

for reference, code is at <https://github.com/vladmandic/automatic/blob/master/modules/ui_common.py#L94>
