### ISSUE TITLE
[Issue]: error during the install 

### ISSUE THREAD

**Issue by chouaibmeramria** [vladmandic/automatic#936]
### Issue Description

Please fill this18:40:07-585013 INFO     Updating Wiki
18:40:15-777767 WARNING  Setup complete with errors (25)
18:40:15-778765 WARNING  See log file for more details: setup.log
18:40:15-780779 INFO     Running extension preloading
Warning: k_diffusion not found at path D:\AI\Vlade\automatic\repositories\k-diffusion\k_diffusion\sampling.py
18:40:15-784775 INFO     Server arguments: []
No module 'xformers'. Proceeding without it.
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮
│ D:\AI\Vlade\automatic\launch.py:141 in <module>                                                                      │
│                                                                                                                      │
│   140                                                                                                                │
│ ❱ 141     instance = start_server(immediate=True, server=None)                                                       │
│   142     while True:                                                                                                │
│                                                                                                                      │
│ D:\AI\Vlade\automatic\launch.py:116 in start_server                                                                  │
│                                                                                                                      │
│   115     server = importlib.util.module_from_spec(module_spec)                                                      │
│ ❱ 116     module_spec.loader.exec_module(server)                                                                     │
│   117     if args.test:                                                                                              │
│ in exec_module:883                                                                                                   │
│ in _call_with_frames_removed:241                                                                                     │
│                                                                                                                      │
│ D:\AI\Vlade\automatic\webui.py:35 in <module>                                                                        │
│                                                                                                                      │
│    34 import ldm.modules.encoders.modules # pylint: disable=W0611,C0411                                              │
│ ❱  35 from modules import extra_networks, ui_extra_networks_checkpoints # pylint: disable=C041                       │
│    36 from modules import extra_networks_hypernet, ui_extra_networks_hypernets, ui_extra_netwo                       │
│                                                                                                                      │
│ D:\AI\Vlade\automatic\modules\ui_extra_networks_checkpoints.py:5 in <module>                                         │
│                                                                                                                      │
│    4                                                                                                                 │
│ ❱  5 from modules import shared, ui_extra_networks, sd_models                                                        │
│    6                                                                                                                 │
│                                                                                                                      │
│ D:\AI\Vlade\automatic\modules\ui_extra_networks.py:11 in <module>                                                    │
│                                                                                                                      │
│    10 from modules import shared                                                                                     │
│ ❱  11 from modules.images import read_info_from_image                                                                │
│    12 from modules.generation_parameters_copypaste import image_from_url_text                                        │
│                                                                                                                      │
│ D:\AI\Vlade\automatic\modules\images.py:17 in <module>                                                               │
│                                                                                                                      │
│    16 from PIL import Image, ImageFont, ImageDraw, PngImagePlugin, ExifTags                                          │
│ ❱  17 from modules import sd_samplers, shared, script_callbacks, errors                                              │
│    18                                                                                                                │
│                                                                                                                      │
│ D:\AI\Vlade\automatic\modules\sd_samplers.py:1 in <module>                                                           │
│                                                                                                                      │
│ ❱  1 from modules import sd_samplers_compvis, sd_samplers_kdiffusion, shared                                         │
│    2                                                                                                                 │
│                                                                                                                      │
│ D:\AI\Vlade\automatic\modules\sd_samplers_kdiffusion.py:4 in <module>                                                │
│                                                                                                                      │
│     3 import torch                                                                                                   │
│ ❱   4 import k_diffusion.sampling                                                                                    │
│     5 from modules import prompt_parser, devices, sd_samplers_common                                                 │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
ModuleNotFoundError: No module named 'k_diffusion' form with as much information as possible

**Comment by vladmandic** [comment]
posting console output like this does not help. and you've provided no platform or version information.
note that at the VERY TOP, it says:
> 18:40:15-777767 WARNING Setup complete with errors (25)
> 18:40:15-778765 WARNING See log file for more details: setup.log

**Comment by vladmandic** [comment]
closing as no info provided, can be reopened if info becomes available.
