### ISSUE TITLE
[Issue]: Repeated extensions in new manager

### ISSUE THREAD

**Issue by acorderob** [vladmandic/automatic#937]
### Issue Description

The new extension manager seems to repeat extensions that have their folder renamed. I rename the folders to load the extensions in the order i want, mainly to move the UI to place i want. Also, the renamed folder copy does not seem to get the correct repo info (seems to get the dates from the folder).

![image](https://github.com/vladmandic/automatic/assets/6293935/6d434ab7-b300-4e19-ba92-cbcae52092e2)

Also, if i click the "refresh extensions" button, the copies with the renamed folder disappear.

Other extensions also disappear (this has happened at least with my own extension, https://github.com/acorderob/sd-webui-sendtonegative), but this might be a different issue.

### Version Platform Description

Commit: 1921504e6478c61fd368970eb5e481fbaf934365
Windows 10
Chrome

**Comment by ronbere** [comment]
I dont have this issue, but where is the list of available extensions? the official extensions list...

**Comment by vladmandic** [comment]
fixed.

**Comment by acorderob** [comment]
The duplication is fixed, but my extension still disappears when i refresh the list. I think it is because it is not yet in the extension index. It should not remove already installed extensions even if they are not in the index.

**Comment by vladmandic** [comment]
fixed that as well now :)
