### ISSUE TITLE
[Issue]: Warning info at launch

### ISSUE THREAD

**Issue by ronbere** [vladmandic/automatic#939]
### Issue Description

13:43:42-433893 INFO     Starting SD.Next
13:43:42-456914 INFO     Python 3.10.9 on Windows
13:43:42-537988 INFO     Version: 926b8666 Sat May 13 16:42:01 2023 -0400
13:43:43-684022 INFO     Setting environment tuning
13:43:43-689027 INFO     nVidia CUDA toolkit detected
13:44:08-270358 INFO     Torch 2.0.0+cu118
13:44:08-365672 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
13:44:08-368317 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 Ti VRAM 12287 Arch (8, 6) Cores 80
13:44:08-370260 INFO     Verifying requirements
13:44:08-381593 WARNING  Package wrong version: requests 2.29.0 required 2.30.0
13:44:08-383595 INFO     Installing package: requests==2.30.0
13:44:20-030469 WARNING  Package wrong version: tqdm 4.64.1 required 4.65.0
13:44:20-032122 INFO     Installing package: tqdm==4.65.0
13:44:22-431687 WARNING  Package wrong version: diffusers 0.14.0 required 0.16.1
13:44:22-432688 INFO     Installing package: diffusers==0.16.1
13:44:27-206706 WARNING  Package wrong version: gradio 3.28.1 required 3.29.0
13:44:27-208708 INFO     Installing package: gradio==3.29.0
13:44:35-206482 WARNING  Package wrong version: urllib3 1.26.13 required 1.26.15
13:44:35-207482 INFO     Installing package: urllib3==1.26.15
13:44:37-939395 WARNING  Package wrong version: onnxruntime 1.14.1 required 1.14.0
13:44:37-940396 INFO     Installing package: onnxruntime==1.14.0ase fill this form with as much information as possible

### Version Platform Description

Windows 10, Chrome

**Comment by 1r00t** [comment]
it is just updating dependencies, is it running fine after that?

**Comment by ronbere** [comment]
> it is just updating dependencies, is it running fine after that?

Yes, it works, but at each launch, it redoes the update, that's why I ask the question

**Comment by vladmandic** [comment]
that means that some extension is changing without checking so repo fixes it each time - not much i can do about that.
this is also better suited as a question in discussions instead of creating issue.
