### ISSUE TITLE
[Issue]: VAE file isn't recognized

### ISSUE THREAD

**Issue by TomerGadol** [vladmandic/automatic#94]
### Issue Description

I am using the `--vae-dir` and the `--ckpt-dir` flags directing to my A1111 folders. Both of them contain the appropriate file named 'vae-ft-mse-840000-ema-pruned.ckpt'. However when I run the bat file I still receive the following message:
`Couldn't find VAE named vae-ft-mse-840000-ema-pruned.ckpt; using None instead`.

### Platform Description

Using Windows 10.

**Comment by SqueakyZee** [comment]
The only time I could get the web ui to recognize the vae-ft-mse-840000-ema-pruned.ckpt or vae-ft-mse-840000-ema-pruned.safetensors files were to create a new folder in models named VAE and stick them both in there. The ui was recognizing my other vae file just fine that was stuck in the same folder as the normal models... But I went and moved it out of there and into the new VAE folder just for neater folders(still worked)  
![image](https://user-images.githubusercontent.com/83526556/231353412-3aa4b1c7-a258-47b2-9bd2-58eee9ca8b25.png)

**Comment by TomerGadol** [comment]
Well, I was being stupid and used a single backslash (\) instead of a double backslash (\\). After correcting this the web-ui now recognizes the paths to ckpt, vae and embeddings directories.
