### ISSUE TITLE
[Issue]: generate button does not appear if theme is different from orange:

### ISSUE THREAD

**Issue by cjps-br** [vladmandic/automatic#946]
### Issue Description

installed version: Version: 618a1703 Sun May 14 12:28:37 2023 -0400

today, after updating the version, the generate button disappeared. I like to use the gradio/monochrome theme and I suspected it was this, so I put the black/orange theme and the button appeared:

![Captura de tela 2023-05-14 140533](https://github.com/vladmandic/automatic/assets/75840971/2da322ea-3c26-402e-bd8b-bcf8882c59d6)

![Captura de tela 2023-05-14 140300](https://github.com/vladmandic/automatic/assets/75840971/3372ae73-4010-4712-8649-3d1a5937713c)

I then put the gradio/default theme and the generate button did not appear either
I put the Black/Orange theme and the button appears:
![Captura de tela 2023-05-14 140300](https://github.com/vladmandic/automatic/assets/75840971/f97ec3b7-9222-4d4b-87af-5ffe6eaf0b18)

### Version Platform Description

Windows, 
browser: Brave
Commit: 
updated: 2023-05-14
hash: 618a1703
url: https://github.com/vladmandic/automatic/tree/master

arch: AMD64
cpu: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
system: Windows
release: Windows-10-10.0.22621-SP0
python: 3.10.6

**Comment by cjps-br** [comment]
![Captura de tela 2023-05-14 140533](https://github.com/vladmandic/automatic/assets/75840971/8877784f-5d45-4655-8dfb-14aa4e0726dc)

**Comment by vladmandic** [comment]
fixed.
