### ISSUE TITLE
[Issue]: Generate button hidden below Stop/Skip buttons in txt2img and img2img

### ISSUE THREAD

**Issue by dchatel** [vladmandic/automatic#947]
### Issue Description

Version: 618a1703 Sun May 14 12:28:37 2023 -0400

The generate button on the txt2img and img2img ui is not showing because it's behind the stop and skip buttons.

Basically, style.css got changed in commit 85d67d63. In particular, line 137 became:
```
display: block;
```
But instead, it should be:
```
display: none;
```

### Version Platform Description

On Windows 10, with edge or firefox, I suspect the bug is everywhere.

**Comment by VeMeth** [comment]
Can confirm this, at the moment you can't generate any pics because you only got stop and skip as buttons.

**Comment by cjps-br** [comment]
> Can confirm this, at the moment you can't generate any pics because you only got stop and skip as buttons.

a workaround is to put the Black/Orange theme. It shows the generate button. It's not my favorite theme, but it works on it.

**Comment by vladmandic** [comment]
yes, duplicate, fixed.
