### ISSUE TITLE
[Issue]: Extensions stuck at Loading... after update

### ISSUE THREAD

**Issue by Davikar** [vladmandic/automatic#951]
### Issue Description

After hitting the "Update installed extensions" button they get stuck showing the Loading... text instead of a checkmark.
Disappears after reloading the UI.
![image](https://github.com/vladmandic/automatic/assets/8229634/ede3e393-7525-41cf-96aa-a1ce80aea708)

### Version Platform Description

Windows 11, Vivaldi (Chrome)
Version: 2ce17e72 Sun May 14 13:27:59 2023 -0400

**Comment by vladmandic** [comment]
fixed.
