### ISSUE TITLE
[Issue]: Scripts reloading

### ISSUE THREAD

**Issue by Woisek** [vladmandic/automatic#956]
### Issue Description

When clicking "Reload scripts" I get this error:

22:52:06-210299 INFO     Memory used: 1.28 total: 63.95
22:59:50-003453 ERROR    Module load: I:\Super SD
                         2.0\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:
                         ModuleNotFoundError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ I:\Super SD 2.0\automatic\modules\script_loading.py:10 in load_module                                               │
│                                                                                                                     │
│    9 │   try:                                                                                                       │
│ > 10 │   │   module_spec.loader.exec_module(module)                                                                 │
│   11 │   except Exception as e:                                                                                     │
│ in exec_module:883                                                                                                  │
│                                                                                                                     │
│                                               ... 1 frames hidden ...                                               │
│                                                                                                                     │
│ I:\Super SD 2.0\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:13 in <module>               │
│                                                                                                                     │
│     12 from scripts import global_state, hook, external_code, processor, batch_hijack, controln                     │
│ >   13 importlib.reload(processor)                                                                                  │
│     14 importlib.reload(global_state)                                                                               │
│                                                                                                                     │
│ F:\Programme\Python310\lib\importlib\__init__.py:168 in reload                                                      │
│                                                                                                                     │
│   167 │   │   if spec is None:                                                                                      │
│ > 168 │   │   │   raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=na                      │
│   169 │   │   _bootstrap._exec(spec, module)                                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ModuleNotFoundError: spec not found for the module 'scripts.processor'
[-] ADetailer initialized. version: 23.5.12, num models: 7
[Errno 2] No such file or directory: 'I:\\Super SD 2.0\\automatic\\additional_configs.json'
I:\Super SD 2.0\automatic\additional_configs.json not found, check if it exists or if you have moved it.
Traceback (most recent call last):
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\gradio\routes.py", line 408, in run_predict
    output = await app.get_blocks().process_api(
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\gradio\blocks.py", line 1315, in process_api
    result = await self.call_function(
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\gradio\blocks.py", line 1043, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "I:\Super SD 2.0\automatic\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "I:\Super SD 2.0\automatic\modules\ui.py", line 1399, in reload_scripts
    modules.scripts.reload_script_body_only()
  File "I:\Super SD 2.0\automatic\modules\scripts.py", line 461, in reload_script_body_only
    scripts_txt2img.reload_sources(cache)
  File "I:\Super SD 2.0\automatic\modules\scripts.py", line 448, in reload_sources
    self.scripts[si] = script_class()
  File "I:\Super SD 2.0\automatic\extensions\sd_web_ui_preset_utils\scripts\zpreset_utils.py", line 126, in __init__
    self.additional_components_for_presets = self.get_config(self.additional_settings_file) #additionalComponents
  File "I:\Super SD 2.0\automatic\extensions\sd_web_ui_preset_utils\scripts\zpreset_utils.py", line 582, in get_config
    return as_dict
UnboundLocalError: local variable 'as_dict' referenced before assignment

Is this known?

### Version Platform Description

Win10, FF 106
Version: 2ce17e72 Sun May 14 13:27:59 2023 -0400

**Comment by vladmandic** [comment]
i'll remove that option, its bound to never work correctly. restart server is the only way.

**Comment by vladmandic** [comment]
that button was meant to reload scripts python code on the fly so dev can edit the script code and reload it without needing to restart server. but because how python works internally, that can never do any good.

regarding update messages - its typically just that fast. and you get message at the very top, just below search bar.
i'll add more messages to console output, currently they were hidden in debug mode.
