### ISSUE TITLE
[Issue]: can't make generations

### ISSUE THREAD

**Issue by gsgoldma** [vladmandic/automatic#962]
### Issue Description

c99c1410

03:03:13-196055 ERROR    Running script process: D:\automatic\extensions\sd-webui-segment-anything\scripts\sam.py:
                         TypeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\scripts.py:374 in process                                                                      │
│                                                                                                                     │
│   373 │   │   │   │   log.debug(f'Script process: {script.title()}')                                                │
│ > 374 │   │   │   │   script.process(p, *args, **kwargs)                                                            │
│   375 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ D:\automatic\extensions\sd-webui-segment-anything\scripts\sam.py:761 in process                                     │
│                                                                                                                     │
│   760 │   │   process_unit = SAMProcessUnit(args, is_img2img)                                                       │
│ > 761 │   │   process_unit.set_process_attributes(p)                                                                │
│   762                                                                                                               │
│                                                                                                                     │
│ D:\automatic\extensions\sd-webui-segment-anything\scripts\process_params.py:87 in set_process_attributes            │
│                                                                                                                     │
│    86 │   │   inpaint_mask_blur = getattr(p, "mask_blur", 0)                                                        │
│ >  87 │   │   inpaint_image, inpaint_mask = self.sam_inpaint_unit.get_input_and_mask(inpaint_m                      │
│    88 │   │   inpaint_cn_num = self.sam_inpaint_unit.cnet_inpaint_idx                                               │
│                                                                                                                     │
│ D:\automatic\extensions\sd-webui-segment-anything\scripts\process_params.py:43 in get_input_and_mask                │
│                                                                                                                     │
│    42 │   │   │   if self.dilation_checkbox and self.dilation_output_gallery is not None:                           │
│ >  43 │   │   │   │   mask = Image.open(self.dilation_output_gallery[1]['name']).convert('L')                       │
│    44 │   │   │   elif self.output_mask_gallery is not None:                                                        │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: 'UiControlNetUnit' object is not subscriptable
03:03:13-562057 ERROR    Running script process: D:\automatic\extensions\sd-webui-cutoff\scripts\cutoff.py: TypeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\scripts.py:374 in process                                                                      │
│                                                                                                                     │
│   373 │   │   │   │   log.debug(f'Script process: {script.title()}')                                                │
│ > 374 │   │   │   │   script.process(p, *args, **kwargs)                                                            │
│   375 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ D:\automatic\extensions\sd-webui-cutoff\scripts\cutoff.py:210 in process                                            │
│                                                                                                                     │
│   209 │   │                                                                                                         │
│ > 210 │   │   if targets_ is None or len(targets_) == 0:                                                            │
│   211 │   │   │   return                                                                                            │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: object of type 'bool' has no len()
03:03:13-665056 ERROR    Running script process: D:\automatic\extensions\sd-webui-llul\scripts\llul.py: ValueError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\scripts.py:374 in process                                                                      │
│                                                                                                                     │
│   373 │   │   │   │   log.debug(f'Script process: {script.title()}')                                                │
│ > 374 │   │   │   │   script.process(p, *args, **kwargs)                                                            │
│   375 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ D:\automatic\extensions\sd-webui-llul\scripts\llul.py:131 in process                                                │
│                                                                                                                     │
│   130 │   │   multiply = 2 ** int(max(multiply, 0))                                                                 │
│ > 131 │   │   weight = float(weight)                                                                                │
│   132 │   │   if x is None or len(x) == 0:                                                                          │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
ValueError: could not convert string to float: 'Lerp'
03:03:13-762055 ERROR    Running script process: D:\automatic\extensions\sd-webui-regional-prompter\scripts\rp.py:
                         AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\scripts.py:374 in process                                                                      │
│                                                                                                                     │
│   373 │   │   │   │   log.debug(f'Script process: {script.title()}')                                                │
│ > 374 │   │   │   │   script.process(p, *args, **kwargs)                                                            │
│   375 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ D:\automatic\extensions\sd-webui-regional-prompter\scripts\rp.py:304 in process                                     │
│                                                                                                                     │
│   303 │   │   │   elif self.cells:                                                                                  │
│ > 304 │   │   │   │   self, p = matrixdealer(self, p, aratios, bratios, mode, usebase, comprom                      │
│   305                                                                                                               │
│                                                                                                                     │
│ D:\automatic\extensions\sd-webui-regional-prompter\scripts\regions.py:381 in matrixdealer                           │
│                                                                                                                     │
│   380 │   │   breaks = mainprompt.count(KEYBRK) + int(self.usebase)                                                 │
│ > 381 │   │   (aratios2r,aratios2) = split_l2(aratios, DELIMROW, DELIMCOL, indsingles = True,                       │
│   382 │   │   # Cannot determine which breaks matter.                                                               │
│                                                                                                                     │
│ D:\automatic\extensions\sd-webui-regional-prompter\scripts\regions.py:126 in split_l2                               │
│                                                                                                                     │
│   125 │   if basestruct is None:                                                                                    │
│ > 126 │   │   lrows = s.split(kr)                                                                                   │
│   127 │   │   lrows = [row.split(kc) for row in lrows]                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'NoneType' object has no attribute 'split'
03:03:13-948057 ERROR    Running script process:
                         D:\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py: AttributeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\scripts.py:374 in process                                                                      │
│                                                                                                                     │
│   373 │   │   │   │   log.debug(f'Script process: {script.title()}')                                                │
│ > 374 │   │   │   │   script.process(p, *args, **kwargs)                                                            │
│   375 │   │   │   except Exception as e:                                                                            │
│                                                                                                                     │
│ D:\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:984 in process                            │
│                                                                                                                     │
│    983 │   │   if not batch_hijack.instance.is_batch:                                                               │
│ >  984 │   │   │   self.enabled_units = self.get_enabled_units(p)                                                   │
│    985                                                                                                              │
│                                                                                                                     │
│ D:\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:943 in get_enabled_units                  │
│                                                                                                                     │
│    942 │   │   for idx, unit in enumerate(units):                                                                   │
│ >  943 │   │   │   unit = self.parse_remote_call(p, unit, idx)                                                      │
│    944 │   │   │   if not unit.enabled:                                                                             │
│                                                                                                                     │
│ D:\automatic\extensions-builtin\sd-webui-controlnet\scripts\controlnet.py:795 in parse_remote_call                  │
│                                                                                                                     │
│    794 │   │                                                                                                        │
│ >  795 │   │   unit.enabled = selector(p, "control_net_enabled", unit.enabled, idx, strict=True                     │
│    796 │   │   unit.module = selector(p, "control_net_module", unit.module, idx)                                    │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'int' object has no attribute 'enabled'
Initializing ----------------------------------------   0% -:--:-- 0:00:00
03:03:15-923055 ERROR    Exception: '<' not supported between instances of 'str' and 'int'
03:03:15-925055 ERROR    gradio call: TypeError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\call_queue.py:33 in f                                                                          │
│                                                                                                                     │
│    32 │   │   │   try:                                                                                              │
│ >  33 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    34 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ D:\automatic\modules\txt2img.py:53 in txt2img                                                                       │
│                                                                                                                     │
│   52 │   if processed is None:                                                                                      │
│ > 53 │   │   processed = process_images(p)                                                                          │
│   54 │   p.close()                                                                                                  │
│                                                                                                                     │
│                                              ... 30 frames hidden ...                                               │
│                                                                                                                     │
│ D:\automatic\venv\lib\site-packages\torch\nn\modules\conv.py:463 in forward                                         │
│                                                                                                                     │
│    462 │   def forward(self, input: Tensor) -> Tensor:                                                              │
│ >  463 │   │   return self._conv_forward(input, self.weight, self.bias)                                             │
│    464                                                                                                              │
│                                                                                                                     │
│ D:\automatic\extensions\asymmetric-tiling-sd-webui\scripts\asymmetric_tiling.py:87 in                               │
│ __replacementConv2DConvForward                                                                                      │
│                                                                                                                     │
│   86 │   │   step = modules.shared.state.sampling_step                                                              │
│ > 87 │   │   if ((self.paddingStartStep < 0 or step >= self.paddingStartStep) and (self.paddi                       │
│   88 │   │   │   working = F.pad(input, self.paddingX, mode=self.padding_modeX)                                     │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
TypeError: '<' not supported between instances of 'str' and 'int'

**Comment by vladmandic** [comment]
no description, no platform information. no list of installed extensions - so setting invalid label for issue.

and tons of errors relating extensions.
i suggest to remove extensions and add them one by one as right now there is really tons of them that are causing problems for each other.

**Comment by gsgoldma** [comment]
It's windows 10, and I'm trying to wittle down  the extensions and find the problem one. I hadn't add any new ones, so it must have been from recent git pull from the either this UI or one of the extensions.

**Comment by vladmandic** [comment]
ok, i'll wait until i hear more from you.

**Comment by Bodzijun** [comment]
I have this problem too.  Disabling an extension  "sd-webui-segment-anything" fixed the problem

**Comment by gsgoldma** [comment]
That wa

> I have this problem too. Disabling an extension "sd-webui-segment-anything" fixed the problem

That is the same experience for me too. Segment anything appears to be the culprit this time.

**Comment by vladmandic** [comment]
i'll start creating a list of "disallowed" extensions as there are some that frequently cause problems.
