### ISSUE TITLE
[Issue]:  Updating extensions gives error gradio call: UnboundLocalError

### ISSUE THREAD

**Issue by solsol360** [vladmandic/automatic#969]
### Issue Description

When running 'Update installed extensions' from Manage Extensions the list in UI disappears and console shows errors below.
Restarted the console and issue persist.

18:22:54-560548 INFO     Extensions update check: update=17 disabled=2
18:22:55-187380 ERROR    Exception: local variable 'e' referenced before assignment
18:22:55-189465 ERROR    gradio call: UnboundLocalError
┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\ui_extensions.py:97 in check_updates                                                           │
│                                                                                                                     │
│    96 │   │   │   else:                                                                                             │
│ >  97 │   │   │   │   commit_date = ext.get('commit_date', 1577836800) or 1577836800                                │
│    98 │   │   │   │   shared.log.debug(f'Extensions no update available: {ext.name} {ext.commi                      │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
AttributeError: 'Extension' object has no attribute 'get'

During handling of the above exception, another exception occurred:

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ D:\automatic\modules\call_queue.py:33 in f                                                                          │
│                                                                                                                     │
│    32 │   │   │   try:                                                                                              │
│ >  33 │   │   │   │   res = func(*args, **kwargs)                                                                   │
│    34 │   │   │   │   progress.record_results(id_task, res)                                                         │
│                                                                                                                     │
│ D:\automatic\modules\ui_extensions.py:103 in check_updates                                                          │
│                                                                                                                     │
│   102 │   │   except Exception:                                                                                     │
│ > 103 │   │   │   errors.display(e, f'extensions check update: {ext.name}')                                         │
│   104 │   │   shared.state.nextjob()                                                                                │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
UnboundLocalError: local variable 'e' referenced before assignment

### Version Platform Description

18:22:07-446743 INFO     Starting SD.Next
18:22:07-456057 INFO     Python 3.10.9 on Windows
18:22:07-538995 INFO     Version: 8350b93a Mon May 15 09:32:20 2023 -0400
18:22:08-012296 INFO     Setting environment tuning
18:22:08-016265 INFO     nVidia CUDA toolkit detected
18:22:10-221120 INFO     Torch 2.0.0+cu118
18:22:10-238024 INFO     Torch backend: nVidia CUDA 11.8 cuDNN 8700
18:22:10-240400 INFO     Torch detected GPU: NVIDIA GeForce RTX 3080 VRAM 10239 Arch (8, 6) Cores 68

**Comment by vladmandic** [comment]
fixed.
