### ISSUE TITLE
[Issue]: LORA models don't work anymore

### ISSUE THREAD

**Issue by Rojinski** [vladmandic/automatic#971]
### Issue Description

Hello!

First of all, thank you for the wonderful Vlad Diffusion. Here's my problem:

1. since very recently (last upgrade maybe), I can't use LORAs anymore. When i try to generate an image with a LORA, i get this error message, whatever the LORA I'm using: 

**"Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)"**

2. If I don't use a LORA, everything is ok. I've tried to change the setting about "Use full precision for model (--no-half)" (checked and unchecked). Nothing works.

3. I have absolutely no knowledge in coding but I'm an experimented user. :)

4. I also use Automatic 1111 and InvokeAI and i have no problem using LORAs.

Could you help me please? Thanks on advance.

Al

**Comment by vladmandic** [comment]
can you update repo to latest version and if possible reset configuration (you can do that from ui settings directly)?
there have been some changes in yesterday and i want to make sure i'm not looking at the wrong code.

i cannot reproduce locally, lora's are working fine here on a similar setup (rtx gpu using cuda).

**Comment by Rojinski** [comment]
> can you update repo to latest version and if possible reset configuration (you can do that from ui settings directly)? there have been some changes in yesterday and i want to make sure i'm not looking at the wrong code.
> 
> i cannot reproduce locally, lora's are working fine here on a similar setup (rtx gpu using cuda).

Okay, I did it

1.  Upgraded to version: 1b73161e Mon May 15 12:25:41 2023 -0400
2. Restored defaults in settings of the UI
3. same issue --> Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)

4. I've copied the messsages in the CMD window, if it's useful for you... 

Loading weights: D:\Programmes 2\Logiciels\stable-diffusion-webui\models\Lora\adAmericana_v10.safetensors ━━━━ 0.0… -:-…                                                                                                               MB
18:41:22-859331 ERROR    Exception: Expected all tensors to be on the same device, but found at least two devices,
                         cuda:0 and cpu! (when checking argument for argument mat2 in method wrapper_CUDA_mm)
18:41:22-861302 ERROR    gradio call: RuntimeError
╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮│ D:\Programmes 2\Logiciels\Vlad\automatic\modules\call_queue.py:33 in f                                               ││                                                                                                                      ││    32 │   │   │   try:                                                                                               ││ ❱  33 │   │   │   │   res = func(*args, **kwargs)                                                                    ││    34 │   │   │   │   progress.record_results(id_task, res)                                                          ││                                                                                                                      ││ D:\Programmes 2\Logiciels\Vlad\automatic\modules\txt2img.py:53 in txt2img                                            ││                                                                                                                      ││   52 │   if processed is None:                                                                                       ││ ❱ 53 │   │   processed = process_images(p)                                                                           ││   54 │   p.close()                                                                                                   ││                                                                                                                      ││                                               ... 25 frames hidden ...                                               ││                                                                                                                      ││ D:\Programmes 2\Logiciels\Vlad\automatic\extensions-builtin\a1111-sd-webui-lycoris\lycoris.py:734 in                 ││ lyco_Linear_forward                                                                                                  ││                                                                                                                      ││   733 │                                                                                                              ││ ❱ 734 │   return torch.nn.Linear_forward_before_lyco(self, input)                                                    ││   735                                                                                                                ││                                                                                                                      ││ D:\Programmes 2\Logiciels\Vlad\automatic\venv\lib\site-packages\torch\nn\modules\linear.py:114 in forward            ││                                                                                                                      ││   113 │   def forward(self, input: Tensor) -> Tensor:                                                                ││ ❱ 114 │   │   return F.linear(input, self.weight, self.bias)                                                         ││   115                                                                                                                │╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when
checking argument for argument mat2 in method wrapper_CUDA_mm)

**Comment by vladmandic** [comment]
which extensions do you have installed? there are several extensions that are known to cause problems. they do work if you disable optimizations present in this repo, but you probably don't want to do that.

**Comment by Rojinski** [comment]
> which extensions do you have installed? there are several extensions that are known to cause problems. they do work if you disable optimizations present in this repo, but you probably don't want to do that.

I have deleted some extensionq (two shot)... I don't use xformers and the settings of the UI are on "defaults" in the settings tab....  I have the exact same config in automatic 1111 and have no problem there.... :/ I use Loas and Lycoris a lot (mine).  What are the optimizations i could disable, for example...? Until two days ago, I had no problems, tho.  I run the .bat file without args...

**Comment by vladmandic** [comment]
post the full startup log and i'll check if there is anything strange there.

**Comment by Rojinski** [comment]
[VladStartUpLog.txt](https://github.com/vladmandic/automatic/files/11481765/VladStartUpLog.txt)

Here comes the start-up log.... I've disabled the LORA in the settings and it wrks (without LORA of course).... Some people told me it's maybe caused by that built-in extension. But as I said, i'm not a specialist.... Just that it was working yesterday or the day before, I don't remember :) Thanks for trying to help me, tho... :)

**Comment by vladmandic** [comment]
you still have TONS of installed extensions. and some are KNOWN to cause problems.
try disabling `stable-diffusion-webui-composable-lora`, that's the most likely one.

**Comment by Rojinski** [comment]
OK :)

**Comment by Rojinski** [comment]
You are right! I've deleted it and now, everything is working perfectly!!! Thank you so much for you help! Can I buy you a coffee? :)

**Comment by vladmandic** [comment]
glad it works :)

**Comment by Rojinski** [comment]
> glad it works :)

Me too. I love your work! Very fast and efficient ! One again, thank you for your kindness and patience.
