### ISSUE TITLE
[Feature]: Populate the whole 'From Text' tab when you drop an image into the prompt box 

### ISSUE THREAD

**Issue by gruevy** [vladmandic/automatic#973]
### Feature description

Currently, if you drop a .png file with generation info into the prompt field, it'll fill the prompt field with that info. But it puts the negative prompt, steps, sample, cfg scale, etc, in the prompt field too. It'd be sweet if it put all that stuff where it needs to go instead.

**Comment by vladmandic** [comment]
that already exists, just need one extra click to make it explict - click on read generation params (first button in toolbar below generate/stop/sip buttons)
