### ISSUE TITLE
[Feature]: Faster Cold Boot Mode

### ISSUE THREAD

**Issue by zolrath** [vladmandic/automatic#975]
### Feature description

Hello!
Thanks again for monkey patching the Swagger docs back in!
I've been looking at methods of deploying this repo to the cloud as most online stable diffusion APIs feel ill suited for any needs beyond simple generations.

I'd love to be able to deploy in a serverless environment to more easily scale up/down with use but that has the issue of requiring the docker image to boot up, a process which currently takes quite a bit of time.

It would be amazing if there was a mode (similar to adding the flags that skip checking for updates) specifically tuned for being able to go from bootup to serving images as quickly as possible, potentially skipping loading the UI and only loading a subset of plugins specified in the config.

Thanks again for all the work put into this repo!

**Comment by vladmandic** [comment]
i plan to add api-only mode in the near-future.
regarding loading subset of plugins, you can always disable them in ui or specify disabled plugins in config. exposing that via command line flags would be an overkill.

**Comment by zolrath** [comment]
That works for me!

Realistically the only concern I'd have is that the docker container be able to spin up quickly and start serving without needing to wait more than a handful of seconds to allow for the most economical hosting as possible, allowing more people to deploy apps depending on Stable Diffusion without getting gutted on price.

The faster the start up the more allowance users could have as far as allowing serverless containers to shut down automatically since we won't have to worry about adding an additional 30 seconds to over a minute to their response time if all the instances are off.

Thanks for the confirmation that you're adding API only mode, quite excited!

**Comment by vladmandic** [comment]
new flag is now avaialble `--api-only` :)
btw, which front end are you using for this?

**Comment by zolrath** [comment]
Awesome! I'm making my own game at the moment and I've been running this as my local API for development.
Ideally I'd like to be able to host it on a serverless environment such as runpod.io and be able to have the container boot quickly enough that I could scale down to 0 instances almost immediately.

They've got the start of a series of blog articles on reducing the startup time of an automatic1111 container using various forms of caching which may be of interest to you as well:
https://blog.runpod.io/reduce-your-serverless-automatic1111-start-time/

**Comment by vladmandic** [comment]
Article is not really that deep.
If you want fast startup, you want to use --data-dir pointing to really fast shared storage outside of the container. Trick is that it should be fully mmap compliant as that shaves a lot from model load time.

Objectively, I'd set a startup time target at around 6-9sec.
