### ISSUE TITLE
[Feature]: Hotkeys?

### ISSUE THREAD

**Issue by mark-wd** [vladmandic/automatic#979]
### Feature description

I do not currently know of any webui-specific hotkey. If they exist, I do not see them documented anywhere that's easy to find.

In case those do not exist, could we get a few for very basic tasks? The ones that would help the most are "Save", "Send to image" and "Send to inpaint", at least in my use-case.

### Version Platform Description

2023-05-13
hash: 926b8666

**Comment by brunogcar** [comment]
AFAIK

From Text - Generate - ctrl + enter
From Image - Generate - ctrl + enter
From Image - Generate - shift + enter (if positive prompt is selected (mouseover and clicked))
Process Image - Generate - ctrl + enter

**Comment by brknsoul** [comment]
Also, highlight a word or phrease and use Ctrl+Up/Down to increase/decrease its weight by 0.1.

**Comment by mark-wd** [comment]
That's some nice bit of documentation @brunogcar... the one @brknsoul mentioned is probably the only widespread one.

I reinforce my request for eventual adding of a few additional hotkeys... maybe it should happen upstream? Only issue is how difficult it is to get something into auto1111.

**Comment by BinaryQuantumSoul** [comment]
> I reinforce my request for eventual adding of a few extra hotkeys for essential tasks

Which ones ?

**Comment by BinaryQuantumSoul** [comment]
> The list is in original post: "Save", "Send to image", "Send to inpaint".

Ups sorry. You're right all of the buttons below generated images should be tied to a hotkey.

**Comment by brunogcar** [comment]
a nice addition since Agent Scheduler was added would be standardize shift + enter to enqueue to From Text, From Image, Process Image

ATM its kinda duplicated on From Image in a very specific situation
