### ISSUE TITLE
[Issue]: (minor issue) Image Browser: ImageReward is not installed, cannot be used

### ISSUE THREAD

**Issue by mark-wd** [vladmandic/automatic#980]
### Issue Description

In my startup log, this message has started appearing: 

```
ControlNet v1.1.173

Image Browser: ImageReward is not installed, cannot be used.

INFO     Loading UI theme: gradio/default
```

This does not seem to affect actual usage of the Image Browser from preliminary tests.

Maybe a dependency is not being properly installed or checked?

### Version Platform Description

2023-05-13
hash: 926b8666

**Comment by vladmandic** [comment]
for anything that's not really an issue (like you say), maybe better to ask a question in discussions first?
anyhow, image browser is pre-packaged here, but the message comes from it, not this repo. 
and its not an error or missing dependency as its fully optional (and i personally don't use imagereward anyhow). honestly, i think imagebrowser author should remove that message.

**Comment by mark-wd** [comment]
Will take the issue to their repo.
