### ISSUE TITLE
[Issue]: Broken image generation using Textual Inversion and half precision with AMD/DirectML on Windows

### ISSUE THREAD

**Issue by Dardoth** [vladmandic/automatic#984]
### Issue Description

Images generated while using Textual Inversion and using half precision appear as blurred static.

Keeping Textual Inversion in the prompt and checking both 'Use full precision for model' and 'Use full precision for VAE' options allows generation of images as normal.

Removing all Textual Inversion in the prompt and leaving both the above precision settings unchecked also allows generation of images as normal.

The issue seems to be specific with the use of Textual Inversion paired with half precision, but I don't know if this is only specific to running DirectML on Windows.

TEST1:
```
Use full precision for model: Checked
Use full precision for VAE: Checked
Model used: ReV Animated v1.2.2
VAE: None
Positive prompt: space, stars, planets, nebula, sun, black hole
Negative prompt: easynegative
resolution: 512 x 512
Seed: 4207516266
CFG scale: 7
Sampling method: DPM++ 2M Karras
Sampling steps: 40
```
Result: Normal image

TEST2:
```
Use full precision for model: Unchecked
Use full precision for VAE: Unchecked
Model used: ReV Animated v1.2.2
VAE: None
Positive prompt: space, stars, planets, nebula, sun, black hole
Negative prompt: 
resolution: 512 x 512
Seed: 4207516266
CFG scale: 7
Sampling method: DPM++ 2M Karras
Sampling steps: 40
```
Result: Normal image

TEST3:
```
Use full precision for model: Unchecked
Use full precision for VAE: Unchecked
Model used: ReV Animated v1.2.2
VAE: None
Positive prompt: space, stars, planets, nebula, sun, black hole
Negative prompt: easynegative
resolution: 512 x 512
Seed: 4207516266
CFG scale: 7
Sampling method: DPM++ 2M Karras
Sampling steps: 40
```
Result: Broken image

Things I've tried so far to try and mitigate this:

Tested with other means of Textual Inversion and this issue is not tied specifically to easynegative.
Tested with other sampling methods and this issue is not sampling method specific.
Tried 'Restore defaults' and --reinstall arguments but issue remains.
Tried disabling all extensions but issue remains.

No errors were reported in the command window during testing, even when the issue occurs.

### Version Platform Description

Software info
```
Operating system: Windows 11 22H2
Web browser: Microsoft Edge
```
Command window info
```
23:33:39-874929 INFO     Starting SD.Next
23:33:39-878932 INFO     Python 3.10.11 on Windows
23:33:39-973438 INFO     Version: 7fe05875 Mon May 15 16:55:10 2023 -0400
23:33:40-350872 INFO     Setting environment tuning
23:33:40-351873 INFO     Using DirectML Backend
23:33:41-734454 INFO     Torch 2.0.0+cpu
23:33:41-744450 INFO     Torch backend: DirectML (torch-directml 0.2.0.dev230426)
23:33:41-817896 INFO     Torch detected GPU: AMD Radeon RX 6800 XT
23:33:41-818898 INFO     Verifying requirements
23:33:41-833934 INFO     Installing packages
23:33:41-879988 INFO     Running setup
23:33:41-882439 INFO     Installing repositories
23:33:42-089944 INFO     Installing submodules
23:33:44-422946 INFO     Updating submodules
23:33:59-416037 INFO     Extensions enabled: ['Lora', 'prompt-bracket-checker', 'sd-dynamic-thresholding',
                         'stable-diffusion-webui-images-browser', 'a1111-sd-webui-tagcomplete', 'canvas-zoom',
                         'sd-web-ui-kitchen-theme']
23:33:59-418045 INFO     Updating Wiki
23:34:00-082586 INFO     Running extension preloading
23:34:00-083586 INFO     Server arguments: ['--upgrade', '--use-directml', '--medvram']

23:34:10-287585 INFO     Model created from config: C:\Program Files\automatic\configs\v1-inference.yaml
23:34:11-186056 INFO     Applying sub-quadratic cross attention optimization
23:34:11-194090 INFO     Embeddings loaded: 1 ['easynegative']
23:34:11-200602 INFO     Model loaded in 1.4s (load=0.2s create=0.3s apply=0.5s vae=0.4s)
23:34:11-365842 INFO     Model load finished: {'ram': {'used': 6.65, 'total': 31.92}}
23:34:11-792089 INFO     Startup time: 11.7s (torch=3.1s gradio=1.9s libraries=0.2s codeformer=0.1s scripts=1.6s opts
                         onchange=0.1s ui=2.2s start=0.3s scripts app_started_callback=0.1s checkpoint=2.2s)
23:34:11-796092 INFO     Memory used: 2.7 total: 31.92
```
UI compute settings
```
Precision type: Autocast
Device precision type: FP16
Use full precision for model: Checked
Use full precision for VAE: Checked
Enable upcast sampling: Unchecked
Do not check NANs: Unchecked
Attempt to roll back VAE: Unchecked
Use channels last: Unchecked
Enable cuDNN: Unchecked
Allow TF32 math ops: Checked
Allow TF16 reduced precision math ops: Checked
Enable model compile: Unchecked
```

**Comment by Dardoth** [comment]
I've done some further testing and I can't replicate this issue using lshqqytiger's fork. Both full and half precision with and without Textual Inversion and produce clean images using the same prompt settings above. For now the only way I can get this working with your fork is to keep the full precision settings checked.

**Comment by Dardoth** [comment]
There are further issues related to using half precision with AMD/DirectML on windows. For example, inpainting just doesn't work properly.

Issue: lshqqytiger/stable-diffusion-webui-directml#87

This issue exists in your fork too.

Even if my original issue could be resolved, we'll move onto the next issue. It might be better to have the default setting for AMD windows user such as I to use full precision due to the issues involved with half precision.

**Comment by vladmandic** [comment]
OK, I'll change it tomorrow. Code is already there, just need to enable it.

**Comment by vladmandic** [comment]
done. i'll track overal fp16 work separately, so closing this issue.

**Comment by maruf7705** [comment]
Slove bug
