### ISSUE TITLE
[Issue]: Updating still forces wrong onnxruntime lib update

### ISSUE THREAD

**Issue by mark-wd** [vladmandic/automatic#991]
### Issue Description

As of the latest commit, updating Automatic still forces onnxruntime 1.14.1. As we previously established, this breaks rembg and other image manipulation extensions.

Manually installing version 1.14.0 fixed the issue.

### Version Platform Description

2023-05-13
hash: 926b8666

**Comment by vladmandic** [comment]
`requirements.txt` includes `onnxruntime==1.14.0`.
if some other extension is changing it on the fly, i cannot control that.

start the server with `--debug` flag, it will print
```log
07:56:19-266469 INFO     Verifying requirements
...
07:56:19-303796 DEBUG    Package version found: onnxruntime 1.14.0
```

**Comment by mark-wd** [comment]
Thanks for clarifying. PBRemTools is the one doing it, then:

packages = [
    "onnx",
    "onnxruntime-gpu",
...
]

I'll open a ticket there.
