### ISSUE TITLE
[Issue]: Segfault on install: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by allkhor** [vladmandic/automatic#992]
### Issue Description

I tried the original Automatic1111 before and the install just worked but there is a bug https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10223. Someone in a comment mentioned that this fork works like expected.

Fresh install. Segfault on install/launch.

[setup.clean.log](https://github.com/vladmandic/automatic/files/11485474/setup.clean.log)
[setup.second_run.log](https://github.com/vladmandic/automatic/files/11485475/setup.second_run.log)

dmesg -kuT 
```
[Tu may 16 12:18:49 2023] traps: pyTuon3[17775] trap invalid opcode ip:7fc1fc586067 sp:7ffcfdbd30e8 error:0 in libtensorflow_framework.so.2[7fc1fb4d1000+157e000]
[Tu may 16 12:18:54 2023] traps: pyTuon3[17101] trap invalid opcode ip:7fb2b9586067 sp:7ffe706dd088 error:0 in libtensorflow_framework.so.2[7fb2b84d1000+157e000]
[Tu may 16 12:27:14 2023] traps: pyTuon3[19005] trap invalid opcode ip:7f19db186067 sp:7ffde0809aa8 error:0 in libtensorflow_framework.so.2[7f19da0d1000+157e000]
[Tu may 16 12:27:20 2023] traps: pyTuon3[18334] trap invalid opcode ip:7fdd01586067 sp:7ffe82d475c8 error:0 in libtensorflow_framework.so.2[7fdd004d1000+157e000]
[Tu may 16 12:59:32 2023] traps: pyTuon3[20622] trap invalid opcode ip:7fcd36386067 sp:7ffc482e2788 error:0 in libtensorflow_framework.so.2[7fcd352d1000+157e000]
[Tu may 16 12:59:38 2023] traps: pyTuon3[19954] trap invalid opcode ip:7f0983186067 sp:7ffc7b060398 error:0 in libtensorflow_framework.so.2[7f09820d1000+157e000]
```

### Version Platform Description

Version: 7fe05875 Mon May 15 16:55:10 2023 -0400 

```
System:
  Kernel: 5.15.0-71-lowlatency x86_64 bits: 64 Desktop: Xfce 4.16.0
    Distro: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
Memory:
  RAM: total: 15.62 GiB used: 4.24 GiB (27.2%)
CPU:
  Info: quad core model: Intel Core i5 750
Graphics:
  Device-1: NVIDIA GP106 [GeForce GTX 1060 6GB] driver: nvidia v: 525.105.17
  Display: server: X.Org v: 1.21.1.4 driver: X: loaded: nvidia gpu: nvidia
    resolution: 1920x1080
  OpenGL: renderer: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2
    v: 4.6.0 NVIDIA 525.105.17
```

**Comment by vladmandic** [comment]
crash happens inside `tensorflow` and cause is invalid cpu instruction.
your cpu seems *extremely* old: **i5-750** is from 2009!
most likely your cpu simply does not have support for advanced cpu instructions used by newer versions of `tensorflow`

you can try manually installing older tensorflow (i don't know how far back you'd have to go to find version that works):
for example:
> venv\Scripts\activate
> pip install tensorflow==2.10.1

**Comment by allkhor** [comment]
Thanks for pointing me in the right direction! After version 1.15 official tensorflow builds are compiled with AVF support only. Thanks to the community for providing a precompiled wheel https://github.com/yaroslavvb/tensorflow-community-wheels/issues/220 Installing this wheel solves the problem.
