### ISSUE TITLE
[Issue]: Adjusting available Samplers in Sampler Settings isn't reflected in UI until server shutdown.

### ISSUE THREAD

**Issue by brknsoul** [vladmandic/automatic#994]
### Issue Description

Changing Samplers isn't reflected in the UI even after a software restart and page refresh. It requires a shutdown and restart of the server.

### Version Platform Description

Version: 7fe05875 Mon May 15 16:55:10 2023 -0400
Win10, Chrome

**Comment by vladmandic** [comment]
done.
